### PR TITLE
Move selections to a new layer

### LINKED ISSUE #8938: Can't interact with edges in the default node layout
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When nodes are rendered in the automatic layout used if they are loaded from a file without any position metadata, they are close enough together that the nodes' selection areas completely cover the gaps between nodes. Since node selection areas take I/O precedence over edges (is this the bug here?) it is not possible to disconnect edges without rearranging nodes.

### Expected behaviour

It should be possible to hover and disconnect edges even between nodes that are close together.

### How we can reproduce it?

Load any file without metadata, after #8893 (which fixes a bug where automatic node layout was upside-down, so all edges were backward edges)--or move some nodes close together vertically.

### Screenshots or screencasts

image

### Logs

_No response_

### Enso Version

current

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

any

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Move selections to a new Vue component so that they don't interfere with clicking on edges.

https://github.com/enso-org/enso/assets/1047859/190006df-1402-4a5f-9117-f43788fa4187

### Important Notes

- The new `GraphNodeSelection` components are drawn in a `GraphNodeSelections` container. They are created by the `GraphNode`s and teleported so that the node can set properties directly.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/GraphNodeSelection.vue [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+  inset: calc(0px - var(--selected-node-border-width));
+  width: calc(var(--selected-node-border-width) * 2 + v-bind('nodeWidthPx'));
+  height: calc(var(--selected-node-border-width) * 2 + v-bind('nodeHeightPx'));
+
+  &:before {
+    position: absolute;
+    content: '';
+    opacity: 0.2;
+    display: block;
+    inset: calc(var(--selected-node-border-width));
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphNodeSelection.vue]: `calc` is not needed here.

File: app/gui2/src/components/GraphEditor/GraphNodeSelections.vue
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphNodeSelections.vue:1]: This component could be even named "GraphEditorLayer", as it contains nothing very specific to selections.

File: app/gui2/src/components/GraphEditor/GraphNodeSelection.vue [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    border-radius: var(--node-border-radius);
+
+    transition:
+      box-shadow 0.2s ease-in-out,
+      opacity 0.2s ease-in-out;
+  }
+}
+
+.GraphNodeSelection.visible::before {
+  box-shadow: 0 0 0 calc(var(--selected-node-border-width)) v-bind('props.color');
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphNodeSelection.vue]: And here too, I think `calc` is not needed.

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/components/GraphEditor/GraphNodeSelection.vue (hunk 1 above)
Comment (kazcw) [reply app/gui2/src/components/GraphEditor/GraphNodeSelection.vue]: Oops, refactoring artifact.
