### PR TITLE
Disable linting passes for IDE and repl

### LINKED ISSUE #9883: Don't unnecessarily report bindings as unused variables (in IDE & REPL)
The repro is trivial - just declare a named binding in the REPL:
```
> abc = 123
[WARN] [2024-05-08T00:52:20+02:00] [enso.org.enso.compiler.Compiler] Internal_Repl_Module___:1:1: warning: Unused variable abc.
    1 | from Standard.Base import all
      | ^~~
>>> Nothing
```

### Expected behaviour

1. The warning should not be reported - it is expected in the REPL that the variable is not yet used.
2. Even if it is shown - the location of the error is wrong.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

There is no need to generate unused variables warnings or other linting for IDE and repl users. By default linting is enabled during compilation and for those use-cases it is now disabled via runtime options.

Closes #9883 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by radeusgd — APPROVED** [review]
OK, although not future-proof - once we get other linting passes e.g. Type Inference - we do not want to disable these in interactive mode - as they can still give useful warnings there.

IMO it would be better to disable `UnusedBindings` only.

File: engine/common/src/main/java/org/enso/common/ContextFactory.java [hunk 1]
```diff
@@ -109,6 +111,11 @@ public ContextFactory strictErrors(boolean strictErrors) {
     return this;
   }
 
+  public ContextFactory disableLinting(boolean disableLinting) {
```
Comment (JaroslavTulach) [inline engine/common/src/main/java/org/enso/common/ContextFactory.java:114]: Extending `ContextFactory`. Nice.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala [hunk 2]
```diff
@@ -308,6 +308,7 @@ class MainModule(serverConfig: LanguageServerConfig, logLevel: Level) {
   val extraOptions = new java.util.HashMap[String, String]()
   extraOptions.put(RuntimeServerInfo.ENABLE_OPTION, "true")
   extraOptions.put(RuntimeOptions.INTERACTIVE_MODE, "true")
+  extraOptions.put(RuntimeOptions.DISABLE_LINTING, "true")
```
Comment (JaroslavTulach) [inline engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala]: Why don't you use `ContextFactory.disableLinting(true)`?

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala [hunk 3]
```diff
@@ -97,15 +94,19 @@ class Passes(
       AliasAnalysis,
       DataflowAnalysis,
       CachePreferenceAnalysis,
-      // TODO passes below this line could be separated into a separate group, but it's more complicated - see usages of `functionBodyPasses`
```
Comment (Akirathan) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala:100]: What about other linting passes, inside `org.enso.compiler.pass.lint` package, like `ModuleNameConflicts` and `ShadowedPatternFields`? Seems like we can remove those from interactive use as well.

**Review by Akirathan — APPROVED** [review]
Nice. Try to also disable the two other linting passes I have mentioned in the review.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala (hunk 3 above)
Comment (radeusgd) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala:100]: As I noted above - I think the only lint pass we should remove is Unused Bindings. Other passes can actually help in interactive mode - they can provide better error descriptions for issues that may be hard to debug otherwise.

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala (hunk 2 above)
Comment (hubertp) [reply engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala]: sure

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala (hunk 3 above)
Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala:100]: This is a valid statement. But unless you are manipulating code in the editor, IDE must not generate invalid programs that would trip on such passes.

Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala:100]: I moved typechecking out of linting but added `ModuleNameConflicts`. `ShadowedPatternFields` appears to modify IR to make alias analysis happy so (for now) I left it around. If needed we can easily modify it.

**Comment by hubertp** [comment]
Cannot reproduce MacOS failure locally so far. As such, this is good to go.

**Comment by JaroslavTulach** [comment]
Passes that produce _warnings_ or _hints_ can be disabled. Passes that yield errors need to **yield**  (at least runtime) **errors**. Hubert mentioned an idea to disable `private` check - that's not an option - we cannot have code that runs in the IDE fails when executed the CLI. The **failures must be identical** in both environments. Otherwise we get into situation hardly explainable/understandable by Enso users.

**Comment by JaroslavTulach** [comment]
PS: if _private check_ pass is slow (which I know it is), then we have to speed it up. There is no reason for it being slow.

**Comment by Akirathan** [comment]
> PS: if private check pass is slow (which I know it is), then we have to speed it up. There is no reason for it being slow.

Tracked in #10722
