### PR TITLE
Fix input ports

### LINKED ISSUE #14279: Input ports incorrectly showing on arguments with dropdowns
e.g. filter

Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #14279

Arrow is now displayed by WidgetArgumentName, and it is hidden if any other widget is present. This requires some degree of coupling between different widgets, though.

CleanShot 2025-11-17 at 11 48 28@2x

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetMultiSelection.vue [hunk 1]
```diff
@@ -173,6 +174,15 @@ export const widgetDefinition = defineWidget(
...
 )
+
+export const MultiSelectionWidgetShownKey: unique symbol = Symbol.for(
+  'WidgetInput:MultiSelectionWidgetShown',
+)
+declare module '$/providers/openedProjects/widgetRegistry' {
+  export interface WidgetInput {
+    [MultiSelectionWidgetShownKey]?: true | undefined
+  }
+}
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetMultiSelection.vue]: Please add a short comment why such key is needed.

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue [hunk 2]
```diff
@@ -262,9 +263,11 @@ export const widgetDefinition = defineWidget(
 )
 
 export { CustomDropdownItemsKey }
+export const SelectionWidgetShownKey: unique symbol = Symbol.for('WidgetInput:SelectionWidgetShown')
 declare module '$/providers/openedProjects/widgetRegistry' {
   export interface WidgetInput {
     [CustomDropdownItemsKey]?: readonly DropdownItem[]
+    [SelectionWidgetShownKey]?: true | undefined
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue]: As above

**Review by farmaazon — APPROVED** [review]
It's quite elegant solution.

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue [hunk 3]
```diff
@@ -35,6 +41,17 @@ const innerInput = computed(() => ({
...
   [ArgumentNameShownKey]: true,
 }))
+
+const childWidgetRef = useTemplateRef<typeof NodeWidget>('childWidgetRef')
+const isChildWidgetEmpty = computed(() => !childWidgetRef.value?.isSelected)
+const connected = computed(() => portInfo?.connected ?? false)
+const showArrow = computed(() => {
+  // Selection widgets are always above WidgetArgumentName by their priority, so we check them separately.
+  const selectionWidgetsShown =
+    props.input[SelectionWidgetShownKey] || props.input[MultiSelectionWidgetShownKey]
```
Comment (Frizi) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue]: I think adding special keys to determine if specific widgets were shown is not the right call here. I'd prefer one of two other solutions:
- either make a `HideArgumentArrow` key and use it in both `SelectionWidget` and `MultiSelectionWidget`
- or specifically look for those widgets existence using `previouslyUsed` array from `injectWidgetUsageInfo`.

**Review by Frizi — APPROVED** [review]
Generally fine, though I see one potential simplification.

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue]: That’s a good suggestion!
