### PR TITLE
Fix JSON Visualization issues

### LINKED ISSUE #13689: JSON visualization missing scrollbars
The JSON visualization truncates large content, but lacks scrollbars, so there's no way to see the cut-off part.

Image

### LINKED ISSUE #13690: JSON visualization not clickable
The JSON visualization supports clicking on a field name to create a component that selects that field; this is only enabled when the data is recognized as JSON by looking for the value type `Standard.Base.Data.Json.JS_Object`. I would expect the output of `parse_json` to be recognized as JSON (and this feature to be enabled for it), but it seems to be a `Vector`.

Image

### LINKED ISSUE #13876: Hyperlink to add new component functionality broken
2025.1

Image

2025.2

Image

Version 2025.2.2-rc2
Build d07a335bf25a317c8f38bc728f982fffbb0c9786
Electron 37.2.1
Chrome 138.0.7204.97
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2025.2.2-rc2 Chrome/138.0.7204.97 Electron/37.2.1 Safari/537.36

### LINKED ISSUE #13889: JSON visualization is not useful
JSON visualization is not scrollable, and I can’t select and copy text from it.

https://github.com/user-attachments/assets/18bf6aa8-e999-4bac-9787-1e33a489b257

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #13889
Closes #13689 
Closes #13690 
Closes #13876 

https://github.com/user-attachments/assets/b4dc7d69-4d95-4b8c-9d85-99392c54b654

### Important Notes

* Removed an underscore on key hover: it was misleading anyway, because you don't need to click at key, just the entire pair to create a new node.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/dashboard/App.tsx [hunk 1]
```diff
@@ -137,7 +137,7 @@ function AppRouter(props: React.PropsWithChildren) {
         !eventModule.isElementTextInput(document.activeElement)
       ) {
         const selection = document.getSelection()
-        const app = document.getElementById('app')
+        const app = document.getElementById('ProjectView')
```
Comment (farmaazon) [inline app/gui/src/dashboard/App.tsx:140]: Before this code snippet was meant for ProjectView root. It is needed to keep selection in JSON visualization (otherwise it gets deselected automatically, as it is seemingly designed in the Dashboard).

Comment (kazcw) [reply app/gui/src/dashboard/App.tsx:140]: Since this has been broken before, can it be covered by integration tests?

File: app/gui/src/project-view/components/visualizations/JSONVisualization/JsonArrayWidget.vue [hunk 2]
```diff
@@ -1,10 +1,12 @@
...
+import { Opt } from '@/util/data/opt'
 import { computed } from 'vue'
+import { CreateProjection } from './types'
 
-const props = defineProps<{ data: unknown[] }>()
-const emit = defineEmits<{
-  createProjection: [path: (string | number)[][]]
+const props = defineProps<{
+  data: unknown[]
+  onCreateProjection?: Opt<CreateProjection>
```
Comment (kazcw) [inline app/gui/src/project-view/components/visualizations/JSONVisualization/JsonArrayWidget.vue]: We have found before that naming a property starting with `on` can lead to problems

File: app/gui/src/project-view/components/visualizations/TableVisualization.vue [hunk 3]
```diff
@@ -331,7 +332,7 @@ watch(tableVersionHash, () => {
 
 watchEffect(() => {
   // if the column definitions remain the same but there has been updates upstream ag grid doesn't know to change its row model or to fetch new data
-  if (nodeType.value != config.nodeType) {
+  if (!nodeType.value?.equals(config.nodeType)) {
```
Comment (kazcw) [inline app/gui/src/project-view/components/visualizations/TableVisualization.vue]: I think it would be more robust if the conditional doesn't run when they are both `undefined`--it works as-is, but given that this is in a `watchEffect`, an innocuous-looking change that adds a side-effect could lead to an infinite loop if the assignment doesn't ensure that the equality condition becomes false.

**Review by kazcw — COMMENTED** [review]
How did the string/ProjectPath change break the logic while still passing typecheck? Can the type safety be improved? If not, can we cover it with an integration test?

**Comment by farmaazon** [comment]
> How did the string/ProjectPath change break the logic while still passing typecheck? Can the type safety be improved? 

VisualizationHost, being in shadow-dom, was attached using `<component>`, which ignores typechecking parameters.

But improved type safety by adding a type constraint in variable.

**Comment by farmaazon** [comment]
Applied review comments, and created a followup task to add integration tests once the Paweł's refactorings are done: https://github.com/enso-org/enso/issues/13973

**Review by kazcw — APPROVED** [review]
