### PR TITLE
Store graph viewport in client local storage

### LINKED ISSUE #6250: After saving and reopening project the camera settings are not preserved
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

1. Open an existing project.
2. Pan/zoom the scene.
3. Close and reopen the project.

Project after reopening has a default zoom and focus, not the last saved one. If the nodes were added - they are there, so the file is updated.

### Expected behaviour

Camera settings should be saved with project metadata.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

2023.1.1-nightly.2023.4.12

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #6250 

With this change, I've also slightly refactored the graph editor component by grouping related functionality into neat block and moving already loosely coupled groups to separate files. Further work will be needed to simplify it, but it is a good first step.

https://github.com/enso-org/enso/assets/919491/fedce111-ea79-463f-a543-da3ecce28bf5

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/visualizations/TableVisualization.vue [hunk 1]
```diff
@@ -384,8 +389,22 @@ onMounted(() => {
   const agGridLicenseKey = import.meta.env.VITE_ENSO_AG_GRID_LICENSE_KEY
   if (typeof agGridLicenseKey === 'string') {
     LicenseManager.setLicenseKey(agGridLicenseKey)
-  } else {
-    console.warn('The AG_GRID_LICENSE_KEY is not defined.')
+  } else if (import.meta.env.DEV) {
+    // Hide annoying license validation errors in dev mode when the license is not defined. The
+    // missing define warning is still displayed to not forget about it, but it isn't as obnoxious.
```
Comment (farmaazon) [inline app/gui2/src/components/visualizations/TableVisualization.vue:394]: :heart:

File: app/gui2/src/composables/navigator.ts [hunk 2]
```diff
@@ -314,5 +295,11 @@ export function useNavigator(viewportNode: Ref<Element | undefined>, keyboard: K
     viewport,
     stepZoom,
     scrollTo,
+    setCenterAndScale(newCenter: Vec2, newScale: number) {
+      targetCenter.value = newCenter
+      targetScale.value = newScale
+      scale.skip()
+      center.skip()
+    },
```
Comment (farmaazon) [inline app/gui2/src/composables/navigator.ts]: scrollTo is defined in body, but setCenterAndScale here; I would keep thier definitions next to each other.

File: app/gui2/src/composables/navigatorStorage.ts [hunk 3]
```diff
@@ -0,0 +1,60 @@
+import { Vec2 } from '@/util/data/vec2'
+import { debouncedWatch, useLocalStorage } from '@vueuse/core'
+import { encoding } from 'lib0'
+import { xxHash128 } from 'shared/ast/ffi'
+import { computed, watch } from 'vue'
+import type { NavigatorComposable } from './navigator'
+
+export function useNavigatorStorage(
+  navigator: NavigatorComposable,
+  storageKeyEncoder: (enc: encoding.Encoder) => void,
```
Comment (farmaazon) [inline app/gui2/src/composables/navigatorStorage.ts]: This parameter serves more like a "reactive getter" than a function, but it's not obvious from the type signature IMO. Maybe some short doc explaining it?

**Review by farmaazon — APPROVED** [review]
