### PR TITLE
Fix spurious tooltip

### LINKED ISSUE #13612: Spurious tooltip for a project name
Image

### PR DESCRIPTION
**Pull request by kazcw**
Fix spurious tooltip (Fixes #13612)

UI:
- Tab name tooltip is no longer shown when name is not truncated.
- Tab name tooltip is no longer triggered by hovering tab close button.

APIs:
- TooltipTrigger: Add support for specifying an overflow element other than the trigger element.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/TooltipTrigger.vue [hunk 1]
```diff
@@ -1,16 +1,23 @@
...
   showOnClick = false,
 } = defineProps<{
   placement?: Placement
-  when?: TooltipDisplayStrategy
+  /**
+   * If set, the tooltip is inhibited unless the reference element is overflowing. If `true`, the
+   * element in the default slot is the reference element; if an element is explicitly provided, it
+   * will be used as the reference element.
+   */
+  whenOverflow?: Opt<true | HTMLElement | VueInstance>
```
Comment (farmaazon) [inline app/gui/src/project-view/components/TooltipTrigger.vue]: From usage perspective, I think this prop could be called `whenOverflowOnly` and take `Opt<boolean | ...>` so false is also valid (maybe even without `Opt`)

Or

make it quite explicit with union of objects with discriminator:
```suggestion
  condition?: { when: 'always' } | { when: 'overflow', element?: Opt<HtmlElement | VueInstance> }
```

For me both options are good.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/project-view/components/TooltipTrigger.vue (hunk 1 above)
Comment (kazcw) [reply app/gui/src/project-view/components/TooltipTrigger.vue]: Yeah, either would be an improvement... but I'm starting to think the complexity of this feature is exceeding its convenience. I think I will reduce the API to an `enabled` prop and let the user call an `isOverflowing` utility.

Comment (farmaazon) [reply app/gui/src/project-view/components/TooltipTrigger.vue]: LGTM
