### PR TITLE
Unable to access constructor value in interactive mode

### LINKED ISSUE #7184: Unable to access constructor value in interactive mode
## Issue

In the interactive mode, when trying to create a node with a type getter, it returns an error that the method is not available. The issue only affects the nodes created after the project is started. 

## How to reproduce

- Open the Unnamed project in the IDE [Unnamed.zip](https://github.com/enso-org/enso/files/11936431/Unnamed.zip)
   ```py
  from Standard.Base import all
  from Standard.Table import all
  import Standard.Visualization

  type Student
      Value id region

  main =
      operator1 = Student.Value 1 'EAST'
      operator2 = operator1.id
      operator2
   ```
- Create a new node `operator1.id`

### Expected result

Node evaluates to a value

### Actual result

Node evaluates to an error:
```
Method `id` of type Student could not be found
```

https://github.com/enso-org/enso/assets/357683/eb16f747-add9-452e-ad81-be3f709862f3

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7184 

The constructor value was not accessible because during the re-compilation a new instance of the type was registered in runtime. Then during the execution, an old cached instance of the type was used in method resolution.

Changelog:
- update: the registration of types in runtime
- update: invalidate cached nodes that became a resolution error after applying the edit

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by 4e6** [comment]
Re-using the type in the compiler scope fixed the issue with method resolution. Now the fun part is to invalidate the scope (and the context caches) properly when the type is edited.

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+  var context: TestContext = _
+
+  class TestContext(packageName: String)
+      extends InstrumentTestContext(packageName) {
+
+    val out: ByteArrayOutputStream    = new ByteArrayOutputStream()
+    val logOut: ByteArrayOutputStream = new ByteArrayOutputStream()
+    val context =
+      Context
+        .newBuilder(LanguageInfo.ID)
```
Comment (Akirathan) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala:37]: It's probably not necessary and maybe even desirable for these tests, for you don't need to limit the polyglot `Context` to "enso". Now, in `runtime`, you have access to all the languages and instruments that we use everywhere.

**Comment by 4e6** [comment]
I just realized that the update of cache invalidation logic will also fix the scenario when an import got changed making some of the symbols in the program invalid (unresolved). I remember that we have discussed this issue earlier but I was not able to find an open ticket for it.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 2]
```diff
@@ -71,8 +71,9 @@ public ModuleScope(
     this.exports = exports;
   }
 
-  public void registerType(Type type) {
-    types.put(type.getName(), type);
+  public Type registerType(Type type) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:74]: What is the intended return value of this method? Is it:
- some `Type`
- previous `Type`
- newest `Type`

I am not sure I get what the return type shall represent.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 3]
```diff
@@ -396,7 +397,6 @@ public void reset() {
     imports = new HashSet<>();
     exports = new HashSet<>();
     methods = new HashMap<>();
-    types = new HashMap<>();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:399]: `ModuleScope.reset()` no longer removes types. OK.

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala [hunk 4]
```diff
@@ -0,0 +1,533 @@
...
+import org.scalatest.BeforeAndAfterEach
+import org.scalatest.flatspec.AnyFlatSpec
+import org.scalatest.matchers.should.Matchers
+
+import java.io.{ByteArrayOutputStream, File}
+import java.nio.file.{Files, Paths}
+import java.util.UUID
+
+@scala.annotation.nowarn("msg=multiarg infix syntax")
+class RuntimeTypesTest
```
Comment (hubertp) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala:21]: I'm not sure it is worth it but we already have runtime instrumentation tests in Java

**Review by hubertp — APPROVED** [review]

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java [hunk 5]
```diff
@@ -406,7 +406,7 @@ public void modifyModuleSources(
               rope -> {
                 logger.log(
                     Level.FINE,
-                    "Applied edits. Source has {} lines, last line has {} characters",
+                    "Applied edits. Source has {0} lines, last line has {1} characters.",
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:409]: I see. Logging in Java requires `{0}`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java [hunk 6]
```diff
@@ -345,6 +345,7 @@ public boolean isEigenType() {
 
   public void registerConstructor(AtomConstructor constructor) {
     constructors.put(constructor.getName(), constructor);
+    gettersGenerated = false;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java:348]: It would be nice, if this was covered by a (non `Runtime*Test`) unit test

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala
Comment (JaroslavTulach) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala:1]: We shouldn't be adding new Scala code.

**Review by JaroslavTulach — APPROVED** [review]

**Review by Akirathan — APPROVED** [review]
