### PR TITLE
Fix blank arguments in signature

### LINKED ISSUE #14077: API signature checker wrongly generates signature of returned lambda
Created from https://github.com/enso-org/enso/pull/14071#discussion_r2387804677.

Blocks #14071

The signature generator generates this signature:
```
func <internal-0>:Standard.Base.Any.Any -> Standard.Base.Any.Any
```
for this method:
```
func =
    _ -> 42
```

**This is wrong, as `func` has no arguments**.

Adding the following test:
```java
  @Test
  public void signatureOfReturnedLambda_IsDifferentThanMethod() throws Exception {
    String firstFunc = """
        func =
            _ -> 42
        """;
    String firstSig;
    try (var ctx = ContextUtils.createDefault()) {
      firstSig = DumpTestUtils.generateSignatures(ctx, firstFunc, "Main");
    }
    String secondFunc = """
        func _ =
            42
        """;
    String secondSig;
    // Second context is explicitly created on purpose - to restart compiler's random name generator.
    try (var ctx = ContextUtils.createDefault()) {
      secondSig = DumpTestUtils.generateSignatures(ctx, secondFunc, "Main");
    }

    assertThat(firstSig, is(notNullValue()));
    assertThat(secondSig, is(notNullValue()));
    assertThat("Signatures must be different", firstSig, is(not(secondSig)));
  }
```
to [DocsGenerateTest](https://github.com/enso-org/enso/blob/e41cb2f5ace1049feb44a6f1ad738184ace523d7/engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java), it **fails**. In other words, signature generator considers these two methods equivalent.

## Is it a bug in signature generator or in the compiler?
Having this module:
```
foo =
    _ -> 42

bar _ =
    42

main =
    1
```
and executing it with:
```
env JAVA_TOOL_OPTIONS='--add-exports=jdk.graal.compiler/jdk.graal.compiler.graphio=org.enso.runtime.compiler.dump.igv -Denso.compiler.dumpIr=tmp' enso --run tmp.enso
```
The following IR graph is produced:

Image

This suggests that from the compiler perspective, **both `foo` and `bar` methods have one argument**.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #14077 

Unblocks #14071

### Pull Request Description

Signature generator prints blank (underscore) arguments, instead of `<internal-*>`.

On develop, signature for
```
func _ =
    42
```
is `func <internal-0> -> Standard.Base.Any.Any`, on this PR, the signature is `func _ -> Standard.Base.Any.Any`

### Important Notes

The compiler transform all blank (underscore) arguments into arguments with `<internal-\d+>` literal names. The information that the argument was created from an underscore is lost in the compilation pipeline. This PR adds a workaround to signature generator: if such argument is encountered, simple `_` is printed instead of its internal name.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java [hunk 1]
```diff
@@ -76,20 +76,36 @@ static String toFqnOrSimpleName(Name ir) {
...
+        sb.append("=");
+      }
+      return sb.toString();
     }
-    if (a.defaultValue().isDefined()) {
-      sb.append("=");
+  }
+
+  /** Returns true if the argument represents an underscore (blank) argument. */
+  private static boolean isBlankArg(DefinitionArgument arg) {
```
Comment (Akirathan) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java:104]: There is no better way to check if the `DefinitionArgument` was `_`. This information is simply lost in the compilation pipeline.

Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java:104]: Amazing hack.

**Review by JaroslavTulach — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]

File: distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/XML/XML_Format.md [hunk 2]
```diff
@@ -8,4 +8,4 @@
     - read self file:Standard.Base.System.File.File on_problems:Standard.Base.Errors.Problem_Behavior.Problem_Behavior -> Standard.Base.Any.Any
     - read_stream self stream:Standard.Base.System.Input_Stream.Input_Stream metadata:Standard.Base.System.File_Format_Metadata.File_Format_Metadata= -> Standard.Base.Any.Any
     - resolve constructor:Standard.Base.Any.Any -> Standard.Base.Any.Any
-- Standard.Base.System.File_Format.File_Format_SPI.from that:Standard.Base.Data.XML.XML_Format.XML_Format -> Standard.Base.System.File_Format.File_Format_SPI
+- Standard.Base.System.File_Format.File_Format_SPI.from _:Standard.Base.Data.XML.XML_Format.XML_Format -> Standard.Base.System.File_Format.File_Format_SPI
```
Comment (Akirathan) [inline distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/XML/XML_Format.md:11]: Signature for https://github.com/enso-org/enso/blob/7f26fdeb1ea58639d4d9714b28b70e7d361bf697/distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso#L92
