### PR TITLE
Dragging edges

### LINKED ISSUE #9423: Drag and release from an output port should add a new component
Adding a new component from an existing output port should be possible in 2 ways:
1. Click the output port and then click the destination.
2. Click and drag from the output port and release.

Currently 2 does not work.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #9423 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/dragging.ts [hunk 1]
```diff
@@ -200,3 +200,5 @@ export function useDragging() {
     },
   }
 }
+
+function useEdgeDragging() {}
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/dragging.ts]: What's this?

**Review by kazcw — APPROVED** [review]

File: app/gui2/src/components/GraphEditor/dragging.ts (hunk 1 above)
Comment (farmaazon) [reply app/gui2/src/components/GraphEditor/dragging.ts]: A leftover, to be removed.
