### PR TITLE
Referencing self from static method raises compiler error

### LINKED ISSUE #7040: Raise a compile error if `self` is referenced from a static method
Currently code like
```
type Foo
    Value x
    bar = self.x*self.x
```

yields no error at compile time because every method has the 'synthetic self'.

But of ourse this is most of the time an oversight - I forgot to add `self` and created a static method instead of a member - and it's my mistake.

So if I do:
```
o = Foo.Value 42
o.bar
```
which I wanted to work, it will fail with `Unresolved_Symbol` because the method is static by accident.

To prevent this, we can report a compile time error whenever `self` is referenced in method body but the method does not declare to be taking `self`.

The only issue is if the synthetic self reference ever needs to be used by user code. I'm not aware of such situations however. @hubertp do you know any obstacles here?

If not, I think reporting an error could make it easier to catch issues as essentially a `self` reference without a `self` argument is most likely just a mistake.

[(As mentioned on Discord)](https://discord.com/channels/@me/948519891961544714/1118588355798630420)

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #7040.

### Pull Request Description

Adds a new compiler pass `NoSelfInStatic` that ensures that `self` argument is not used from static methods. So, for example, the following snippet will result in a compiler error (because `Foo.bar` is a static method):
```
type Foo
    Value x
    bar = self.x * 2
```

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala [hunk 1]
```diff
@@ -77,7 +77,8 @@ trait IRPass extends ProcessingPass {
     * @return the result of updating metadata in `copyOfIr` globally using
     *         information from `sourceIr`
     */
-  def updateMetadataInDuplicate[T <: IR](sourceIr: T, copyOfIr: T): T
+  def updateMetadataInDuplicate[T <: IR](@unused sourceIr: T, copyOfIr: T): T =
+    copyOfIr
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala:81]: This introduces a substantial change that spans multiple Scala files. I have done it because in my own compiler pass, I wanted to provide the default implementation for this method, and I accidentally returned `sourceIr` instead of `copyOfIr`, which led to a bug that was very difficult to find.

To ensure that nobody has to bump into the same bug in the future, I provided the default implementation in this trait. Moreover, many of the inheritors provided the default implementation anyway.

**Comment by Akirathan** [comment]
Cherry-picked commits a1030faa9ee213e1c93f280fb749a5cfab6f85c2 and ae9983b19d2468d079899747e380b9ad40710669 from #7072 that add dependency for `fansi` to make Compiler's diagnostic output work.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso [hunk 2]
```diff
@@ -1117,7 +1117,7 @@ type Number_Parse_Error
     ## PRIVATE
        Pretty print the syntax error.
     to_display_text : Text
-    to_display_text =
+    to_display_text self =
         "Could not parse " + self.text.to_text + " as a double."
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso:1121]: And this proves that this pass was useful - this would likely just fail at runtime.

**Review by radeusgd — APPROVED** [review]

File: engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala [hunk 3]
```diff
@@ -0,0 +1,99 @@
+package org.enso.compiler.test.pass.lint
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala:1]: New test in `.scala`! Ugly, please give Java a chance.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+  ): IR.Module = {
+    ir.copy(
+      bindings = ir.bindings.map {
+        case method: IR.Module.Scope.Definition.Method.Explicit
+            if isStaticMethod(method) =>
+          method.copy(
+            body = method.body.transformExpressions(transformSelfToError)
+          )
+        case method: IR.Module.Scope.Definition.Method.Binding =>
+          throw new CompilerError("Unreachable: Method.Binding should not be present in this pass: " + method)
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala]: I would keep the error message simpler:
```suggestion
          throw new CompilerError(s"unexpected Method.Binding $method present in pass NoSelfInStatic")
```

File: engine/runtime/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+                _,
+                _,
+                _,
+                _,
+                _
+              ) =>
+            findSelfArgument(arguments) match {
+              case Some(_) => false
+              case None    => true
+            }
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala]:
```suggestion
            findSelfArgument(arguments).isEmpty
```

**Review by hubertp — APPROVED** [review]
nits

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+          |        nested_method 42
+          |""".stripMargin.preprocessModule.lint
+      val errs = ir.bindings.flatMap(_.preorder).collect {
+        case err @ IR.Error
+              .Syntax(_, IR.Error.Syntax.InvalidSelfArgUsage, _, _) =>
+          err
+      }
+      errs should be(empty)
+    }
+  }
```
Comment (4e6) [inline engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala:131]: Please add a test for extension methods

**Review by 4e6 — APPROVED** [review]

File: engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/NoSelfInStaticTests.scala:131]: Done in c852990680daae34dd8afb841800a7fa2f08e2a8

**Comment by Akirathan** [comment]
language server's TextOperationsTest failed transiently - https://github.com/enso-org/enso/actions/runs/5400627094/jobs/9809318502#step:10:6178. Restarting the job.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Referencing self from static method raises compiler error · enso-org/enso@1706378</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by radeusgd** [comment]
I just have to say how happy I am we have got this feature. I'm constantly forgetting to add `self` to new methods and this error makes me catch the issue much easier and clearly know what's up. Thanks!
