### PR TITLE
Collect ObservedMessages and dump them on test failure

### LINKED ISSUE #12725: Slf4j logs are not showing in tests
The Slf4j logger is used in many places, such as in `ProgramExecutionSupport` https://github.com/enso-org/enso/blob/6cdbac66ea9cb98b7dbd9f93ba09be73b4737187/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala#L62

## Issue

When running tests, the log statements produced by the `org.slf4j.LoggerFactory.getLogger(this.getClass)` are not visible. It makes debugging more difficult.

## How to reproduce

```scala
class Slf4jTest extends org.scalatest.flatspec.AnyFlatSpec {

  private val logger = org.slf4j.LoggerFactory.getLogger(this.getClass)

  it should "boo" in {
    logger.error("Boo!")
  }
}
```

The test will produce no output in SBT console:
`
```
sbt:enso> runtime-integration-tests/testOnly *.Slf4jTest
```

### LINKED ISSUE #13308: Collect logs in tests and only print them on failure
Implement `@Rule CollectLogs` that will swallow all logs by default and only print them all if failure in test happens.

- May be useful to use [ObservedMessage](https://github.com/enso-org/enso/pull/12163/files#diff-379d73c069bcb7b7ff58f3bdad18c6ab980af576b20f38a6b9cb1c0b9b238625R17).

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- requested by #12725 
- inspired by work in #13721, but ...
- ...using `ObservedMessage` as #13308 suggests
- one has to **opt-in** by adding `with org.enso.testkit.ReportLogsOnFailure` like:
```scala
package org.enso.polyglot.test

class Slf4jTest extends org.scalatest.flatspec.AnyFlatSpec with org.enso.testkit.ReportLogsOnFailure {

  private val logger = org.slf4j.LoggerFactory.getLogger(this.getClass)

  it should "boo" in {
    val l = logger;
    l.error("Boo!")
   if (false) throw new IllegalStateException("OK");
  }
}
```
- such a test doesn't log anything when it succeeds
- but when it fails it [dumps all messages logged](https://github.com/enso-org/enso/pull/14932#discussion_r3023369593) during its execution
- most prominent Scala tests were modified to **opt-in**, other tests can be added on an incremental basis when needed

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala [hunk 1]
```diff
@@ -1,51 +1,48 @@
...
-import ch.qos.logback.classic.spi.ILoggingEvent
-import ch.qos.logback.core.Appender
-import org.enso.logging.service.logback.MemoryAppender
 import org.scalatest.{Args, Failed, Outcome, Status, TestSuite}
-import org.slf4j.{Logger, LoggerFactory}
+import org.enso.logger.ObservedMessage
 
 trait ReportLogsOnFailure extends TestSuite {
 
-  private lazy val appender: Appender[ILoggingEvent] = {
```
Comment (JaroslavTulach) [inline lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala:11]: - changes in this class are taken from https://github.com/enso-org/enso/pull/13721/changes#diff-eced82398b2bf6e8ec3336b3e02d23f1b2648b8ee92a485a1179e0b175e3a0ffR4
- and rewritten to use `ObservedMessage` infrastructure

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala [hunk 2]
```diff
@@ -191,7 +192,7 @@ class RuntimeErrorsTest
         contextId,
         mainResId,
         Api.ExpressionUpdate.Payload.Panic(
-          "Compile error: The name `undefined` could not be found.",
+          "Wrong error: The name `undefined` could not be found.",
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala]: With this change the test fails. When that happens, this is the output:
```
[DEBUG] [2026-04-01T16:54:39.115810255Z] Executing command asynchronously: CreateContextCmd...
[TRACE] [2026-04-01T16:54:39.117341608Z] Waited [CreateContextCmd] 0ms for the write context lock (context=<missing>)
[TRACE] [2026-04-01T16:54:39.120931400Z] Kept write context lock [CreateContextCmd] for 3ms
[DEBUG] [2026-04-01T16:54:39.121516436Z] Command CreateContextCmd finished.
[DEBUG] [2026-04-01T16:54:39.129363313Z] Executing command synchronously: OpenFileCmd...
[TRACE] [2026-04-01T16:54:39.129605175Z] Waited [OpenFileCmd] 0ms for the read compilation
[TRACE] [2026-04-01T16:54:39.129975297Z] Waited [OpenFileCmd] 0ms for the file
[TRACE] [2026-04-01T16:54:39.135618375Z] Kept file lock [OpenFileCmd] for 6ms
[TRACE] [2026-04-01T16:54:39.135645293Z] Kept read compilation lock [OpenFileCmd] for 6ms
[TRACE] [2026-04-01T16:54:39.135661466Z] Command OpenFileCmd finished.
[DEBUG] [2026-04-01T16:54:39.138185759Z] Executing command asynchronously: PushContextCmd...
[TRACE] [2026-04-01T16:54:39.144981524Z] Submitting job: org.enso.interpreter.instrument.job.EnsureCompiledJob@62608933 with 15d08a24-9ac8-44d5-a596-6cbb2907aebb id...
[TRACE] [2026-04-01T16:54:39.145391919Z] Number of pending jobs: 1
[DEBUG] [2026-04-01T16:54:39.145438845Z] Executing job: org.enso.interpreter.instrument.job.EnsureCompiledJob@62608933...
[TRACE] [2026-04-01T16:54:39.145622459Z] Waited [EnsureCompiledJob] 0ms for the write compilation
[TRACE] [2026-04-01T16:54:39.146197142Z] Compiling Enso_Test.Test.Main.
[TRACE] [2026-04-01T16:54:39.166905087Z] runPassesOnModule[Standard.Builtins.Main@INITIAL]
[TRACE] [2026-04-01T16:54:39.168688373Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.169739251Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.170695057Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.171158840Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.171424580Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.171595893Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.171769409Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.175316077Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.182962124Z] runPassesOnModule[Standard.Builtins.Main@AFTER_PARSING]
[TRACE] [2026-04-01T16:54:39.183025135Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.183234305Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.183290597Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.183331003Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.183349005Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.184608375Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.186372762Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.186399583Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.186418848Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.186434214Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.186473267Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.186489660Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.186507550Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.188249551Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.189135082Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.189399864Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.189521785Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.189662552Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.194211141Z] runPassesOnModule[Standard.Builtins.Main@AFTER_PARSING]
[TRACE] [2026-04-01T16:54:39.194281725Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.195781944Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.195966621Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.196754662Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.197123784Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.197387731Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.197497788Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.197637180Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.197652762Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.197804392Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.197819443Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.197943825Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.198626021Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.198642665Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.198831834Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.198845728Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.198918246Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.199068315Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.199351613Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.199770086Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.199804516Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.199958982Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.200597607Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.200772090Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.200792640Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.200952293Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.200986475Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.223731647Z] runPassesOnModule[Enso_Test.Test.Main@INITIAL]
[TRACE] [2026-04-01T16:54:39.223790552Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.225577438Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.229004426Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.229025536Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.229042126Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.232000891Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.232054126Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.232460476Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.233870450Z] ANALYZE of Enso_Test.Test.Main
[TRACE] [2026-04-01T16:54:39.235166983Z] TRANSITIVE of Enso_Test.Test.Main is []
[TRACE] [2026-04-01T16:54:39.239117664Z] runPassesOnModule[Enso_Test.Test.Main@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.239182722Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.239196828Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.239207777Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.239236933Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.239266028Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.239301630Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.241458137Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.241485426Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.241501495Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.241514983Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.241528301Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.241542059Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.241556500Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.241619694Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.244324488Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.244588339Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.246170616Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.247253452Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.249826846Z] runPassesOnModule[Enso_Test.Test.Main@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.249884128Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.250299593Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.252425584Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.255345918Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.260030975Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.261590675Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.262099739Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.262675090Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.263036286Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.267715321Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.268006015Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.268380676Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.269198152Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.269495920Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.270628650Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.270924487Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.270965029Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.271533344Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.272343901Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.272879358Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.273167708Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.275200359Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.276270560Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.276336344Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.278134754Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.278472263Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.278511448Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.279107942Z] runPassesOnModule[Enso_Test.Test.Main@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.329748197Z] Waited [EnsureCompiledJob] 0ms for the file
[TRACE] [2026-04-01T16:54:39.329889153Z] Waited [EnsureCompiledJob] 0ms for the pending edit
[TRACE] [2026-04-01T16:54:39.330288208Z] Applying pending file [/tmp/enso-test-packages-15784128233406824955/Test_8636764811586138967/src/Main.enso] edits [0] idMap [None]
[TRACE] [2026-04-01T16:54:39.349960244Z] Kept pending edits lock [EnsureCompiledJob] for 20ms
[TRACE] [2026-04-01T16:54:39.349991646Z] Kept file lock [EnsureCompiledJob] for 20ms
[TRACE] [2026-04-01T16:54:39.355176357Z] Cache - clear keys: Set(e0077bc1-13b9-47f0-89cc-31efc36699e9, 818e50de-2ecc-481b-93a9-a99d9eb23513), indexes: Set(Weights), reason: changeset
[TRACE] [2026-04-01T16:54:39.356407678Z] Cache - clear stale keys: Set(), indexes: Set(All)
[TRACE] [2026-04-01T16:54:39.370443587Z] Cache - clear set preferences: WeightInfo(CachePreferences[preferences={e0077bc1-13b9-47f0-89cc-31efc36699e9=BINDING_EXPRESSION, e46d3ea6-6058-437b-b809-dc0f9418a9b0=BINDING_EXPRESSION}])
[TRACE] [2026-04-01T16:54:39.370842912Z] Kept write compilation lock [EnsureCompiledJob, context <missing>] for 225ms
[TRACE] [2026-04-01T16:54:39.370861636Z] Job org.enso.interpreter.instrument.job.EnsureCompiledJob@62608933 finished in 225 ms.
[TRACE] [2026-04-01T16:54:39.371109128Z] Number of remaining pending regular jobs: 0
[TRACE] [2026-04-01T16:54:39.371661431Z] Submitting job: ExecuteJob(contextId=340ee382-be33-410d-888d-d4e870eb910d, jobId=7da2b2af-aa76-4e56-8c78-911c720df32d, triggeredByVisualization=List()) with 7da2b2af-aa76-4e56-8c78-911c720df32d id...
[TRACE] [2026-04-01T16:54:39.371700400Z] Number of pending jobs: 1
[DEBUG] [2026-04-01T16:54:39.371826838Z] Executing job: ExecuteJob(contextId=340ee382-be33-410d-888d-d4e870eb910d, jobId=7da2b2af-aa76-4e56-8c78-911c720df32d, triggeredByVisualization=List())...
[DEBUG] [2026-04-01T16:54:39.371846261Z] Starting ExecuteJob[7da2b2af-aa76-4e56-8c78-911c720df32d, trigger=push context]
[TRACE] [2026-04-01T16:54:39.372074969Z] Waited [ExecuteJob] 0ms for the read context lock
[TRACE] [2026-04-01T16:54:39.372210971Z] Waited [ExecuteJob] 0ms for the read compilation
[TRACE] [2026-04-01T16:54:39.374314925Z] Run program 340ee382-be33-410d-888d-d4e870eb910d
[TRACE] [2026-04-01T16:54:39.449559073Z] Resolving library Standard.Base.
[TRACE] [2026-04-01T16:54:39.449610402Z] Resolving version of library 'Standard.Base' with edition Edition(Some(Edition(None,Some(0.0.0-dev),Map(main -> Repository(main,https://libraries.release.enso.org/libraries)),Map(Standard.Base -> PublishedLibrary(Standard.Base,0.0.0-dev,Repository(main,https://libraries.release.enso.org/libraries)), Test.Logical_Export -> PublishedLibrary(Test.Logical_Export,0.0.0-dev,Repository(main,https://libraries.release.enso.org/libraries))))),None,Map(),Map()), preferLocalLibraries=false
[TRACE] [2026-04-01T16:54:39.450196473Z] Resolved version of library 'Standard.Base' to Right(0.0.0-dev)
[TRACE] [2026-04-01T16:54:39.450219363Z] Resolved Standard.Base to [Right(0.0.0-dev)].
[TRACE] [2026-04-01T16:54:39.457402507Z] Standard.Base found at [***/0.0.0-dev].
[DEBUG] [2026-04-01T16:54:39.459291047Z] Found library Standard.Base @ 0.0.0-dev at [***/0.0.0-dev].
[DEBUG] [2026-04-01T16:54:39.459735117Z] Loading library Standard.Base from [***/0.0.0-dev].
[TRACE] [2026-04-01T16:54:39.487379300Z] runPassesOnModule[Standard.Base.Errors.Common@INITIAL]
[TRACE] [2026-04-01T16:54:39.487438489Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.488082749Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.490564124Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.491875453Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.496036146Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.497282168Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.497791893Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.499784345Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.499911658Z] ANALYZE of Standard.Base.Errors.Common
[TRACE] [2026-04-01T16:54:39.505219202Z] runPassesOnModule[Standard.Base.Any@INITIAL]
[TRACE] [2026-04-01T16:54:39.505281211Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.505373408Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.505625515Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.505685139Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.506442607Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.506596308Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.506688838Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.506792830Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.509701002Z] runPassesOnModule[Standard.Base.Data.Text@INITIAL]
[TRACE] [2026-04-01T16:54:39.509743241Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.509780778Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.509826757Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.509837177Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.509905981Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.509941209Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.509968136Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.510001753Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.512184604Z] runPassesOnModule[Standard.Base.Error@INITIAL]
[TRACE] [2026-04-01T16:54:39.512235841Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.512305197Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.512448508Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.512503251Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.512705118Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.512776152Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.512850434Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.513204286Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.515238404Z] runPassesOnModule[Standard.Base.Nothing@INITIAL]
[TRACE] [2026-04-01T16:54:39.515273650Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.515306937Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.515351419Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.515391719Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.515477196Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.515514123Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.515546822Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.515596638Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.516157233Z] TRANSITIVE of Standard.Base.Errors.Common is [Standard.Base.Any, Standard.Base.Data.Text, Standard.Base.Error, Standard.Base.Meta, Standard.Base.Nothing]
[TRACE] [2026-04-01T16:54:39.516388505Z] ANALYZE of Standard.Base.Nothing
[TRACE] [2026-04-01T16:54:39.519542158Z] runPassesOnModule[Standard.Base.Data.Boolean@INITIAL]
[TRACE] [2026-04-01T16:54:39.519584180Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.519630842Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.519718664Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.520380449Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.520591731Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.520658609Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.520708429Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.520755504Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.520889891Z] TRANSITIVE of Standard.Base.Nothing is [Standard.Base.Data.Boolean]
[TRACE] [2026-04-01T16:54:39.520944876Z] ANALYZE of Standard.Base.Data.Boolean
[TRACE] [2026-04-01T16:54:39.522815561Z] TRANSITIVE of Standard.Base.Data.Boolean is [Standard.Base.Data.Boolean]
[TRACE] [2026-04-01T16:54:39.527052296Z] runPassesOnModule[Standard.Base.Meta@INITIAL]
[TRACE] [2026-04-01T16:54:39.527108478Z]   mega running: ModuleAnnotations
[TRACE] [2026-04-01T16:54:39.527176013Z]   mega running: DocumentationComments
[TRACE] [2026-04-01T16:54:39.527402739Z]   mega running: Imports
[TRACE] [2026-04-01T16:54:39.527425156Z]   mega running: ComplexType
[TRACE] [2026-04-01T16:54:39.527651350Z]   mega running: FunctionBinding
[TRACE] [2026-04-01T16:54:39.527787746Z]   mega running: GenerateMethodBodies
[TRACE] [2026-04-01T16:54:39.527926693Z]   mega running: BindingAnalysis
[TRACE] [2026-04-01T16:54:39.528011155Z]   mega running: ModuleNameConflicts
[TRACE] [2026-04-01T16:54:39.528040837Z] ANALYZE of Standard.Base.Meta
[TRACE] [2026-04-01T16:54:39.528193386Z] TRANSITIVE of Standard.Base.Meta is [Standard.Base.Nothing]
[TRACE] [2026-04-01T16:54:39.528239468Z] ANALYZE of Standard.Base.Error
[TRACE] [2026-04-01T16:54:39.528512991Z] TRANSITIVE of Standard.Base.Error is [Standard.Base.Any, Standard.Base.Data.Boolean]
[TRACE] [2026-04-01T16:54:39.528540930Z] ANALYZE of Standard.Base.Any
[TRACE] [2026-04-01T16:54:39.528679132Z] TRANSITIVE of Standard.Base.Any is [Standard.Base.Data.Boolean]
[TRACE] [2026-04-01T16:54:39.528700172Z] ANALYZE of Standard.Base.Data.Text
[TRACE] [2026-04-01T16:54:39.528718615Z] TRANSITIVE of Standard.Base.Data.Text is []
[TRACE] [2026-04-01T16:54:39.532983293Z] runPassesOnModule[Standard.Base.Errors.Common@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.533014673Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.533025957Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.533033098Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.533045297Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.533053758Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.533083442Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.537402462Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.537431845Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.537449434Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.537463574Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.537476919Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.537502539Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.537521946Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.537609005Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.544732061Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.546113899Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.547793590Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.548713636Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.553908511Z] runPassesOnModule[Standard.Base.Any@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.553942678Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.553952313Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.553958709Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.553981040Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.553990890Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.554019372Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.555167365Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.555186716Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.555197220Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.555209793Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.555217609Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.555225299Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.555233969Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.555279082Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.555876303Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.555985951Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.556290513Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.556497228Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.556922707Z] runPassesOnModule[Standard.Base.Nothing@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.556942281Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.556954156Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.556961568Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.556969481Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.556975675Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.556993368Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.557326763Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.557341901Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.557354577Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.557365322Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.557380587Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.557391532Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.557402691Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.557461289Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.558646494Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.558678533Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.558740382Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.558765332Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.559745203Z] runPassesOnModule[Standard.Base.Meta@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.559771977Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.559778563Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.559783878Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.559791580Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.559797646Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.559815616Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.560401121Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.560412260Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.560421051Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.560427327Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.560433629Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.560440950Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.560447801Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.560518146Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.561277223Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.561486629Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.561751934Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.561882940Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.562429104Z] runPassesOnModule[Standard.Base.Data.Text@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.562448986Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.562454847Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.562465100Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.562475678Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.562484412Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.562507615Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.562645469Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.562655077Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.562663652Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.562669464Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.562685209Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.562694541Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.562702362Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.562747635Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.562890573Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.562910420Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.562941085Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.562961587Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.563076107Z] runPassesOnModule[Standard.Base.Data.Boolean@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.563091947Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.563096393Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.563100227Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.563106050Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.563110979Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.563125002Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.563406212Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.563417427Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.563426510Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.563434650Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.563444151Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.563463256Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.563472598Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.563515807Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.563750423Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.563786871Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.563858309Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.563894880Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.564124680Z] runPassesOnModule[Standard.Base.Error@AFTER_IMPORT_RESOLUTION]
[TRACE] [2026-04-01T16:54:39.564141532Z]   mini collected: org.enso.compiler.pass.resolve.MethodDefinitions@6f46cac9
[TRACE] [2026-04-01T16:54:39.564152301Z]   mini collected: org.enso.compiler.pass.desugar.SectionsToBinOp@6edaaafe
[TRACE] [2026-04-01T16:54:39.564165666Z]   mini collected: OperatorToFunction
[TRACE] [2026-04-01T16:54:39.564177374Z]   mini collected: LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.564182725Z]   pass OperatorToFunction forces flush before (invalidates) LambdaShorthandToLambda
[TRACE] [2026-04-01T16:54:39.564196123Z]   flushing pending mini pass: {{org.enso.compiler.pass.resolve.MethodDefinitions$Mini + org.enso.compiler.pass.desugar.SectionsToBinOp$Mini} + org.enso.compiler.pass.desugar.OperatorToFunctionMini}
[TRACE] [2026-04-01T16:54:39.564438456Z]   mini collected: org.enso.compiler.pass.analyse.ImportSymbolAnalysis@2d7c2504
[TRACE] [2026-04-01T16:54:39.564446121Z]   mini collected: org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis@360d3929
[TRACE] [2026-04-01T16:54:39.564451515Z]   mini collected: org.enso.compiler.pass.analyse.PrivateModuleAnalysis@7f61bdbe
[TRACE] [2026-04-01T16:54:39.564456208Z]   mini collected: org.enso.compiler.pass.analyse.PrivateConstructorAnalysis@146d442e
[TRACE] [2026-04-01T16:54:39.564461169Z]   mini collected: org.enso.compiler.pass.analyse.IfThenElseToCaseOf@58f517a2
[TRACE] [2026-04-01T16:54:39.564466238Z]   mini collected: org.enso.compiler.pass.lint.ShadowedPatternFields@7eeb9e4
[TRACE] [2026-04-01T16:54:39.564471435Z]   mini collected: org.enso.compiler.pass.optimise.UnreachableMatchBranches@751078ea
[TRACE] [2026-04-01T16:54:39.564496684Z]   flushing pending mini pass: {{{{{{{org.enso.compiler.pass.desugar.LambdaShorthandToLambdaMini + org.enso.compiler.pass.analyse.ImportSymbolAnalysis$Mini} + org.enso.compiler.pass.analyse.AmbiguousImportsAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateModuleAnalysis$Mini} + org.enso.compiler.pass.analyse.PrivateConstructorAnalysis$Mini} + org.enso.compiler.pass.analyse.IfThenElseToCaseOf$Mini} + org.enso.compiler.pass.lint.ShadowedPatternFields$Mini} + org.enso.compiler.pass.optimise.UnreachableMatchBranches$Mini}
[TRACE] [2026-04-01T16:54:39.564657458Z]   mega running: NestedPatternMatch
[TRACE] [2026-04-01T16:54:39.564706226Z]   mega running: IgnoredBindings
[TRACE] [2026-04-01T16:54:39.564822076Z]   mega running: TypeFunctions
[TRACE] [2026-04-01T16:54:39.564878637Z]   mega running: TypeSignatures
[TRACE] [2026-04-01T16:54:39.565223991Z] runPassesOnModule[Standard.Base.Errors.Common@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.565259651Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.565733840Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.571133268Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.573523177Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.577101583Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.580443238Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.581382843Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.581777533Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.584196052Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.585607993Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.587182564Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.587672144Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.588220250Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.589162941Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.591086527Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.592321542Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.592380642Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.594663147Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.595801377Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.599231661Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.600443218Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.604932556Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.605523199Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.605634248Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.607113898Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.607468636Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.607500033Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.608004504Z] runPassesOnModule[Standard.Base.Any@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.608049562Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.608318653Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.608915436Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.609246416Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.609714852Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.609946442Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.610040049Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.610407676Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.610649667Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.611693014Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.611873609Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.611907496Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.612206294Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.612429129Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.612601617Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.612765725Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.612793821Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.613074314Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.613168370Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.613480274Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.613771978Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.614536670Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.614710009Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.614757968Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.615294752Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.615334626Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.615365684Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.615504926Z] runPassesOnModule[Standard.Base.Nothing@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.615525608Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.615564438Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.615611550Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.616100196Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.616161777Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.616187061Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.616222703Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.616260153Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.616285084Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.616386988Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.616404563Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.616412667Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.616482943Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.616533092Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.616582187Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.616621551Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.616638599Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.616686245Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.616701979Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.616769747Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.616790008Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.616863919Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.616879506Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.616893308Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.616915841Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.616927109Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.616941361Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.616985602Z] runPassesOnModule[Standard.Base.Meta@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.617001968Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.617118165Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.617507018Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.617785228Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.618272469Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.618529021Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.618604506Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.618687008Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.618872745Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.619381487Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.619528311Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.619591342Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.619883343Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.620075211Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.620313233Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.620471688Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.620493739Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.620781421Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.620846652Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.621274122Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.621565428Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.621947674Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.622119871Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.622193323Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.622335095Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.622388249Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.622405493Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.622541271Z] runPassesOnModule[Standard.Base.Data.Text@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.622560025Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.622607702Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.622658519Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.622679716Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.622695217Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.622727389Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.622737404Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.622766126Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.622783026Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.622908258Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.622939112Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.622950768Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.623057204Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.623086252Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.623120368Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.623147301Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.623163899Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.623206862Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.623242019Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.623288152Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.623317357Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.623393765Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.623440802Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.623457372Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.623479796Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.623495156Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.623510333Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.623557095Z] runPassesOnModule[Standard.Base.Data.Boolean@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.623574757Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.623641402Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.623712625Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.623835678Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.623871643Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.623941422Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.623964818Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.624004566Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.624057290Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.624350788Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.624406506Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.624418342Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.624522333Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.624560310Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.624606533Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.624637808Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.624653346Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.624705711Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.624730967Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.624768531Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.624803216Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.624855738Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.624905863Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.624919144Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.624960026Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.624978350Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.624992977Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.625061991Z] runPassesOnModule[Standard.Base.Error@AFTER_GLOBAL_TYPES]
[TRACE] [2026-04-01T16:54:39.625084593Z]   mega running: ExpressionAnnotations
[TRACE] [2026-04-01T16:54:39.625166981Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.625275336Z]   mega running: FullyQualifiedNames
[TRACE] [2026-04-01T16:54:39.625391193Z]   mega running: GlobalNames
[TRACE] [2026-04-01T16:54:39.625468631Z]   mega running: TypeNames
[TRACE] [2026-04-01T16:54:39.625531876Z]   mega running: org.enso.compiler.pass.resolve.MethodCalls$@b220e52
[TRACE] [2026-04-01T16:54:39.625563706Z]   mega running: org.enso.compiler.pass.resolve.FullyAppliedFunctionUses$@7b1a4093
[TRACE] [2026-04-01T16:54:39.625610409Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.625666497Z]   mega running: LambdaConsolidate
[TRACE] [2026-04-01T16:54:39.626011231Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.626080754Z]   mega running: SuspendedArguments
[TRACE] [2026-04-01T16:54:39.626106608Z]   mega running: OverloadsResolution
[TRACE] [2026-04-01T16:54:39.626303737Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.626397775Z]   mega running: DemandAnalysis
[TRACE] [2026-04-01T16:54:39.626541473Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.626631371Z]   mini collected: org.enso.compiler.pass.analyse.TailCall@2cc2a17b
[TRACE] [2026-04-01T16:54:39.626669172Z]   flushing pending mini pass: org.enso.compiler.pass.analyse.TailCall$Mini
[TRACE] [2026-04-01T16:54:39.626781712Z]   mega running: org.enso.compiler.pass.resolve.Patterns$@6e396374
[TRACE] [2026-04-01T16:54:39.626911756Z]   mega running: org.enso.compiler.pass.analyse.PrivateSymbolsAnalysis@7f680966
[TRACE] [2026-04-01T16:54:39.627083272Z]   mega running: AliasAnalysis
[TRACE] [2026-04-01T16:54:39.627186496Z]   mega running: FramePointerAnalysis
[TRACE] [2026-04-01T16:54:39.627435892Z]   mega running: CachePreferenceAnalysis
[TRACE] [2026-04-01T16:54:39.627602715Z]   mega running: GenericAnnotations
[TRACE] [2026-04-01T16:54:39.627630341Z]   mega running: UnusedBindings
[TRACE] [2026-04-01T16:54:39.627714472Z]   mega running: org.enso.compiler.pass.lint.NoSelfInStatic$@6423d847
[TRACE] [2026-04-01T16:54:39.627755063Z]   mini collected: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls@4d940288
[TRACE] [2026-04-01T16:54:39.627775250Z]   flushing pending mini pass: org.enso.compiler.pass.lint.NoDuplicateSelfInMethodCalls$Mini
[TRACE] [2026-04-01T16:54:39.627861036Z] runPassesOnModule[Standard.Base.Errors.Common@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627886774Z] runPassesOnModule[Standard.Base.Any@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627897086Z] runPassesOnModule[Standard.Base.Nothing@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627912633Z] runPassesOnModule[Standard.Base.Meta@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627924770Z] runPassesOnModule[Standard.Base.Data.Text@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627933620Z] runPassesOnModule[Standard.Base.Data.Boolean@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.627942597Z] runPassesOnModule[Standard.Base.Error@AFTER_STATIC_PASSES]
[TRACE] [2026-04-01T16:54:39.654074654Z] ON_COMPUTED e46d3ea6-6058-437b-b809-dc0f9418a9b0
[TRACE] [2026-04-01T16:54:39.724031724Z] ON_COMPUTED e0077bc1-13b9-47f0-89cc-31efc36699e9
[TRACE] [2026-04-01T16:54:39.726130478Z] ON_COMPUTED 818e50de-2ecc-481b-93a9-a99d9eb23513
[TRACE] [2026-04-01T16:54:39.729239348Z] Execution finished: Right(())
[TRACE] [2026-04-01T16:54:39.729859380Z] Kept read compilation lock [ExecuteJob] for 357ms
[TRACE] [2026-04-01T16:54:39.729867624Z] Kept read context lock [ExecuteJob] for 357ms
[TRACE] [2026-04-01T16:54:39.729873523Z] Finished ExecuteJob[7da2b2af-aa76-4e56-8c78-911c720df32d]
[TRACE] [2026-04-01T16:54:39.729876318Z] Job ExecuteJob(contextId=340ee382-be33-410d-888d-d4e870eb910d, jobId=7da2b2af-aa76-4e56-8c78-911c720df32d, triggeredByVisualization=List()) finished in 358 ms.
[TRACE] [2026-04-01T16:54:39.729913651Z] Number of remaining pending regular jobs: 0
[DEBUG] [2026-04-01T16:54:39.729951319Z] Executing command asynchronously: DeserializeLibrarySuggestionsCmd...
[DEBUG] [2026-04-01T16:54:39.729967237Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.729979705Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.729991857Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.730003267Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.730014912Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.730025892Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.730036393Z] Executing command asynchronously: SerializeModuleCommand...
[DEBUG] [2026-04-01T16:54:39.731352299Z] Command PushContextCmd finished.
[DEBUG] [2026-04-01T16:54:39.731388818Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731405323Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731416649Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731432033Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731443225Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731459264Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731498740Z] Command SerializeModuleCommand finished.
[DEBUG] [2026-04-01T16:54:39.731517461Z] Command DeserializeLibrarySuggestionsCmd finished.
[info] - should return panic sentinels in method body *** FAILED *** (666 milliseconds)

```

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala [hunk 3]
```diff
@@ -1,51 +1,50 @@
...
+    val log    = org.slf4j.LoggerFactory.getLogger("org")
+    val ps     = System.out
+    val arr    = new java.util.ArrayList[ObservedMessage]()
+    val handle = ObservedMessage.observe(log, arr.add(_))
+    try {
+      super.runTest(testName, args)
+    } catch {
+      case e: Throwable =>
+        arr.forEach {
+          ps.println(_)
```
Comment (4e6) [inline lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: Scalatest [calls `withFixture` from the `runTest` method](https://www.scalatest.org/scaladoc/1.8/org/scalatest/fixture/Suite.html#:~:text=This%20trait's%20runTest%20method%20delegates,it%20to%20the%20test%20function.) and in the current setup it seems that both handlers will dump the same messages to stdout. Only observing in `withFixture` should be enough.

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala [hunk 4]
```diff
@@ -1,51 +1,50 @@
...
-              outcome
+    val log    = org.slf4j.LoggerFactory.getLogger("org")
+    val ps     = System.out
+    val arr    = new java.util.ArrayList[ObservedMessage]()
+    val handle = ObservedMessage.observe(log, arr.add(_))
+    try {
+      super.withFixture(test) match {
+        case outcome @ Failed(_) =>
+          arr.forEach {
+            ps.println(_)
```
Comment (4e6) [inline lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: `System.out` can be inlined. What's the purpose of a variable?
```suggestion
            System.out.println(_)
```

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala [hunk 5]
```diff
@@ -1,51 +1,50 @@
...
     testName: String,
     args: Args
   ): Status = {
-    appender match {
-      case memoryAppender: MemoryAppender =>
-        memoryAppender.stopForwarding()
-        super.runTest(testName, args)
-      case _ =>
-        super.runTest(testName, args)
+    val log    = org.slf4j.LoggerFactory.getLogger("org")
```
Comment (4e6) [inline lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: Why the "org" logger and not the root logger like in the original code?

File: lib/scala/logging-utils/src/main/java/org/enso/logger/ObservedMessage.java [hunk 6]
```diff
@@ -115,6 +115,11 @@ public String getFormattedMessage() {
     return formattedMsg.get();
   }
 
+  @Override
+  public String toString() {
+    return "[" + level + "] [" + instant + "] " + getFormattedMessage();
```
Comment (4e6) [inline lib/scala/logging-utils/src/main/java/org/enso/logger/ObservedMessage.java:120]: Maybe include the logger name to match the standard log output:
> [DEBUG] [2026-04-01T11:01:12.732] [org.enso.interpreter.instrument.command.Command] Executing command synchronously: EditFileCmd...

**Review by 4e6 — APPROVED** [review]
Scalatest logic should be updated

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala (hunk 3 above)
Comment (JaroslavTulach) [reply lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: OK, done in 55554d5adf and yes, the [output is still printed](https://github.com/enso-org/enso/pull/14932#discussion_r3023369593).

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala (hunk 4 above)
Comment (JaroslavTulach) [reply lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: - OK, changed in 55554d5adf
- originally I tried to use `System.err`, but that _printed nothing_!
   - I found out that someone calls `System.err.close()` and nothing gets printed then
   - then I tried to capture `System.err` (as it can be changed by `System.setErr` even being final)
   - but that didn't help - hence I used `System.out` - that works
- however using `System.out` isn't very "proper"
   - ideally I'd made the log part of proper `scalatest` error reporting
   - but I need a hint how to do that...

File: lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala (hunk 5 above)
Comment (JaroslavTulach) [reply lib/scala/testkit/src/main/scala/org/enso/testkit/ReportLogsOnFailure.scala]: Done in 55554d5adffcd37b1c79da0be307dc1cc6fd921d, thanks.

File: lib/scala/logging-utils/src/main/java/org/enso/logger/ObservedMessage.java (hunk 6 above)
Comment (JaroslavTulach) [reply lib/scala/logging-utils/src/main/java/org/enso/logger/ObservedMessage.java:120]: - The current `ObservedMessage` infrastructure doesn't have information about the logger name.
- It is probably possible to add it, if really needed
- but I leave it out of this PR for some future work
