### PR TITLE
Fix issues with mouse cursor position when editing nodes

### LINKED ISSUE #6702: Ctrl+click is placing cursor in a random place on a node
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When starting editing an existing node, `ctrl+click` is placing a cursor in a random place.

### Expected behaviour

Cursor should be placed exactly where user clicks.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

nightly 12.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #6702 

The issue was in the code for hiding/showing the node label. When showing it for the first time, the position of the label was updated only in the next frame, so the whole calculation was incorrect.

It is fixed using the `DETACHED` scene layer to hide the label when needed. Its position is always correct.

https://github.com/enso-org/enso/assets/6566674/bd39c99e-163b-47e7-9b6d-158831c230cc

### Important Notes

I added a bit of additional code to ensure we always use the correct layer. The label is a complicated entity, as it lives in different layers in different application states. Also, I removed the code for setting the initial layer from the `init` method, as it seems unused. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node/input/area.rs [hunk 1]
```diff
@@ -205,12 +238,19 @@ impl Model {
...
 
         self
     }
 
     fn set_label_layer(&self, layer: &display::scene::Layer) {
-        self.edit_mode_label.add_to_scene_layer(layer);
+        *self.label_layer.borrow_mut() = layer.downgrade();
+        // We're taking extra measures to ensure that the actual layer of the label will be updated
+        // even if it is already displayed. It should be unnecessary with the current
+        // implementation. See [`Self::show_edit_mode_label`] and [`Self::hide_edit_mode_label`].
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/area.rs]: >  It should be unnecessary with the current implementation.

I don't understand this. If it's unnecessary, why do we do this?

**Review by farmaazon — APPROVED** [review]

File: app/gui/view/graph-editor/src/component/node/input/area.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: Well, we have no control over when the `set_label_layer` method will be called from outside of this component, and technically it can happen when we already have the label visible. As far as I understand the code, it shouldn't happen, but one can refactor it in the future and accidentally change the behavior. So it is just a preventative measure.

Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: I think the docs rephrased this way would be more understandable to me:
```
Currently, we never sets label layer when it's already displayed, but - as `set_label_layer` is a public method of this component - we're taking extra measures.
```

**Comment by kazcw** [comment]
# QA: :green_circle:

File: CHANGELOG.md [hunk 2]
```diff
@@ -183,6 +183,7 @@
   execution failed][6918].
 - [Performance and readability of documentation panel was improved][6893]. The
   documentation is now split into separate pages, which are much smaller.
+- [Fixed cursor position when ctrl-clicking the node][7014].
```
Comment (wdanilo) [inline CHANGELOG.md]: These are user-facing logs. Users reading them should understand what changed without the need to click something and without prior knowledge. Telling "fixed cursor position" does not really explain what changed to the reader. I'd be thankful If you could expand that a little bit.

File: app/gui/view/graph-editor/src/component/node/input/area.rs (hunk 1 above)
Comment (wdanilo) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: 1. Adam asked a question because the comment in the code is confusing. I see that the code did not change (the docs are not improved / expanded) and it is still confusing, so the question was not addressed yet. The comment is also very confusing to me – if it "should be unnecessary with the current implementation", it should not be there.
2. You have full control of if the `set_label_layer` will be called from outside of this component – the method is private, so it will not be called from outside.

I don't think we should include "dead code" that does nothing and is there just in case someone refactors code without thinking about the logic. This makes the whole code hard to understand and follow. In the future, when browsing this code, I would probably spend a lot of time trying to understand why `edit_mode_label_displayed` is needed and why we are managing this state, thinking that probably this solves some issue. If it is not needed, lets not add it :)

**Review by wdanilo — CHANGES_REQUESTED** [review]

File: app/gui/view/graph-editor/src/component/node/input/area.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: > You have full control of if the set_label_layer will be called from outside of this component – the method is private, so it will not be called from outside.

This is not true, it is called from the public method of view.

Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: Github have fooled me. I actually added a comment yesterday, but it was kept in a pending state, and I didn't notice.

Now it should be visible. I proposed an alternative comment. Check @wdanilo if it's ok to you.

Comment (vitvakatu) [reply app/gui/view/graph-editor/src/component/node/input/area.rs]: Thank you, I like your proposal.

**Comment by sylwiabr** [comment]
@wdanilo can you re-review this?

**Review by wdanilo — APPROVED** [review]

**Comment by xvcgreg** [comment]
@vitvakatu What's the status here? It's 4 days old w/o any action.

**Comment by vitvakatu** [comment]
@xvcgreg blame engine CI on windows, I don't know what has happened to it. Restarting one more time...

**Comment by wdanilo** [comment]
@vitvakatu in case of random failures, ping me and I will merge it :)
