### PR TITLE
Unexpected warning when running a standalone script

### LINKED ISSUE #9109: Unexpected warning when running a standalone script
Repro:
1. create a file `test.enso` with contents `main = 42`
2. run it

## Actual behaviour

```
> .\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\bin\enso --run .\test.enso
[WARN] [2024-02-20T12:04:21+01:00] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization of module `test` failed: Unable to write cache data for test.`
42
```

A warning about inability to write cache data for the script's module is printed.

## Expected behaviour

The warning shouldn't be there. I don't think we should expect cache for standalone scripts.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #9109

Fixes the issue when the runner displays unexpected log messages
```
> .\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\bin\enso --run .\test.enso
[WARN] [2024-02-20T12:04:21+01:00] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization of module `test` failed: Unable to write cache data for test.`
42
```

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runner/src/main/scala/org/enso/runner/Main.scala [hunk 1]
```diff
@@ -1056,9 +1056,13 @@ object Main {
...
 
-  /** Default log level to use if the LOG_LEVEL option is not provided.
+  /** Default log level to use when starting a language server if the
+    * `LOG_LEVEL` option is not provided.
     */
-  private val defaultLogLevel: Level = Level.WARN
+  private val defaultServerLogLevel: Level = Level.WARN
+
+  /** Default log level to use if the `LOG_LEVEL` option is not provided. */
+  private val defaultLogLevel: Level = Level.ERROR
```
Comment (JaroslavTulach) [inline engine/runner/src/main/scala/org/enso/runner/Main.scala]: Is it wise to change log level for all messages when the goal is to suppress single message?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java [hunk 2]
```diff
@@ -386,7 +386,7 @@ private Callable<Boolean> doSerializeModule(
       } catch (Throwable e) {
         logSerializationManager(
             e instanceof IOException ? Level.WARNING : Level.SEVERE,
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java]: If we want to suppress this message, then we should change used `Level` here rather than mangling with with global configuration of logging.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala [hunk 3]
```diff
@@ -1056,9 +1056,13 @@ object Main {
         exitFail()
     }
 
-  /** Default log level to use if the LOG_LEVEL option is not provided.
+  /** Default log level to use when starting a language server if the
+    * `LOG_LEVEL` option is not provided.
     */
-  private val defaultLogLevel: Level = Level.WARN
+  private val defaultServerLogLevel: Level = Level.WARN
```
Comment (JaroslavTulach) [inline engine/runner/src/main/scala/org/enso/runner/Main.scala]: Can we have/update documentation describing:
- what to do to log a message into console?
- what to do to log a message into log file?
- what to do to log a stack trace into log file?
- what to do to log a stack trace into console?
- how to do that with sl4j?
- how to do that with `TruffleLogger`?

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
I believe "unexpected warning" should be fixed without changing global logging configuration.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 1 above)
Comment (4e6) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: I only switched it back to its original value https://github.com/enso-org/enso/pull/7825/files#diff-7111bba91c7d387c5ae7e93bc67c9e0b513b31f99e3a10a86d1a1cff82baff0b

Comment (hubertp) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: I think it should stay as `WARN`. Just the level of the offending log message should be lowered.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 3 above)
Comment (hubertp) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: > what to do to log a message into console?
> what to do to log a message into log file?

I don't see how those are related. Besides one should not care at this point where we are logging. 

> how to do that with sl4j?
> how to do that with TruffleLogger?

Isn't this kind of self-explanatory? The former - use slf4j Logger, the latter - use TruffleLogger.

> what to do to log a stack trace into log file?
> what to do to log a stack trace into console?

OK, that one "might" deserve some clarification though it's not related to this PR.
Since **all** layout is controlled in a single configuration it's a question of adding `%ex` vs `%noex` in the pattern field, eg. https://github.com/enso-org/enso/blob/develop/engine/launcher/src/main/resources/application.conf#L30. As per slf4j rules.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: I see. Why do I have a feeling we are shuffling logging and its configuration back and forth without any serious plan?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java]: I agree. Serialization is not a critical failure, it can be `debug`

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 1 above)
Comment (hubertp) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: > I see. Why do I have a feeling we are shuffling logging and its configuration back and forth without any serious plan?

I don't know. I don't have such a feeling.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: > one should not care at this point where we are logging

Isn't the whole point of this issue that "unexpected warning" gets logged? If we had clear answers to 

> what to do to log a message into console?
> what to do to log a message into log file?

we would know what `Level` to use to suppress the message.

> ... it can be debug

No, it cannot be debug. There is no debug in `java.util.logging.Level`... 

> how to do that with sl4j?
> how to do that with TruffleLogger?

That's why I am asking for examples of code to achieve each action in both systems.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 1 above)
Comment (4e6) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: > I think it should stay as `WARN`. Just the level of the offending log message should be lowered.

Okay

**Review by JaroslavTulach — APPROVED** [review]
