### PR TITLE
Sandbox&Sentry fixes

### LINKED ISSUE #11035: AppImage problem on newest Ubuntu
From @hubertp 
> I upgraded recently to latest Ubunut (24.04) and built IDE today. 
Running the AppImage yields: 
The SUID sandbox helper binary was found, but is not configured correctly.
> 
> This appears to be a common issue but we should work out of the box on any linux system. 

It prevents app from starting

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #11035 

1. `--no-sandbox` option is now always added to electron
2. Fix a sentry configuration warning I noticed.

### Important Notes

I tried to use `electron-builder-sandbox-fix`, but it failed to recognize AppArmor in our CI's Ubuntu. I tried to find a way of better recognition, but it proved to be hard.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
✅ CR looks okay but a second opinion is welcome

File: app/ide-desktop/client/electron-builder-config.ts [hunk 1]
```diff
@@ -292,7 +293,39 @@ export function createElectronBuilderConfig(passedArgs: Arguments): electronBuil
...
+      // to user's filesystem anyway.
+      if (passedArgs.platform === electronBuilder.Platform.LINUX) {
+        if (
+          !('executableName' in context.packager) ||
+          typeof context.packager.executableName !== 'string'
+        )
+          throw new Error('Expected executableName in context.packager')
+        const executableName = context.packager.executableName
+        const executable = path.join(context.appOutDir, executableName)
+        const loaderScript = `#!/usr/bin/env bash
```
Comment (Frizi) [inline app/ide-desktop/client/electron-builder-config.ts:315]: Do we actually need bash here? `sh` should probably be enough and technically would be more portable. I don't care too much if it's a hassle for whatever reason though.

**Review by Frizi — APPROVED** [review]

File: app/ide-desktop/client/electron-builder-config.ts (hunk 1 above)
Comment (farmaazon) [reply app/ide-desktop/client/electron-builder-config.ts:315]: During my little research, `BASH_SOURCE` was declared to be more resilient in getting script's directory in some crazy situations.
