### PR TITLE
Fix code editor positioning

### LINKED ISSUE #14189: Code panel is opening weirdly in the middle of the screen
Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #14189

The issue was introduced by layout changes in https://github.com/enso-org/enso/pull/14163

https://github.com/user-attachments/assets/d596f838-b22d-4b71-8769-c829b4341ac5

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/BottomPanel.vue [hunk 1]
```diff
@@ -38,34 +38,36 @@ const style = computed(() =>
 </script>
 
 <template>
-  <ActionButton
```
Comment (vitvakatu) [inline app/gui/src/project-view/components/BottomPanel.vue:41]: Just added a wrapper `<div>` here.

**Review by farmaazon — APPROVED** [review]
