### PR TITLE
Fix editing number and string literals from code editor

### LINKED ISSUE #10684: Code editor edits to literals are not propagated to graph view
Editing text or number literal in code editor does not update displayed value on a widget.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #10684

https://github.com/user-attachments/assets/a6b42121-b684-414c-a370-f64174621212

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/shared/ast/index.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export function parentId(ast: Ast): AstId | undefined {
 export function subtrees(module: Module, ids: Iterable<AstId>) {
   return reachable(ids, (id) => {
     const parent = module.tryGet(id)?.parent()
-    return parent ? [parent.id] : []
+    return parent ? [id, parent.id] : []
```
Comment (kazcw) [inline app/gui2/shared/ast/index.ts]: This is not correct when `ids` contains only the root. Should have a test case.

**Review by kazcw — APPROVED** [review]
