### PR TITLE
Prevent incorrect application of list widget on incompatible expressions

### LINKED ISSUE #6747: IDE doesn't render Vector concatenation.
`[["Default", "Locale.default"]] + operator10 + [["From Language Tag", "(Locale.from_language_tag 'en-US')"]]`

was rendered incorrectly by the new Vector editor.

image

Additionally, when the expression had a mistake it was impossible to see the node at all.

`[["Default", "Locale.default"]] + operator10 + [["From Language Tag", "(Locale.from_language_tag 'en-US')]]`

Rendered as:

image

### LINKED ISSUE #6760: Node with randomly added by CB `Column.from_vector` to `select_nodes` renders weirdly and behaves like a part of a vector editor
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When CB added `Column.from_vector` to `select_columns ["id"]` node it started behave weirdly (like it was a part of a vector) and had problems with rendering.

### Expected behaviour

`Column.from_vector` should not be part of a widget.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/8b996367-261e-43f6-a8e0-39a1d0a4c64b

### Enso Version

nightly 18.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #6785: Argument to `Table.transpose` disappears from the node once chosen from the dropdown
Once I chose an argument for `Table.transpose` from the dropdown widget, the argument disappeared from the node. I have to ctrl+click to see it again.

[transpose-arg-dissapear.webm](https://github.com/enso-org/enso/assets/14013887/7099a3a3-456b-461d-ac05-9f1497ef12ec)
[20230519-161155-414-enso-project-manager.log.zip](https://github.com/enso-org/enso/files/11518678/20230519-161155-414-enso-project-manager.log.zip)

### PR DESCRIPTION
**Pull request by Frizi**
Fixes #6760
Fixes #6747

### Pull Request Description

Refactored the logic behind selecting appropriate widgets for span tree nodes. Now the bulk of it is moved into widget methods. When a given widget type is reporting to be not compatible with the expression, it will not be used even if the configuration was overriden using an method argument annotation. In that case, the usual logic for automatically selecting the appropriate widget will kick in.

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 1]
```diff
@@ -126,9 +138,17 @@ pub struct OverrideKey {
 
 /// Common trait for constructing and reconfiguring all widget variants. See "Widget Lifecycle"
 /// section of the module documentation for more details.
-pub trait SpanWidget {
+pub trait SpanWidget: Sized {
     /// Configuration associated with specific widget variant.
     type Config: Debug + Clone + PartialEq;
+    /// Determine the match of this widget kind to a given span node. When this method returns
+    /// [`None`], the widget of this kind will not be created for passed node, even if it was set
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: `Score` cannot be `None`

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 2]
```diff
@@ -126,9 +138,17 @@ pub struct OverrideKey {
 
 /// Common trait for constructing and reconfiguring all widget variants. See "Widget Lifecycle"
 /// section of the module documentation for more details.
-pub trait SpanWidget {
+pub trait SpanWidget: Sized {
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: The `Sized` bound should not be needed here; `Configuration` could accept a `?Sized` type parameter. I think it would express more clearly that `Configuration<T>` doesn't contain a `T`.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 3]
```diff
@@ -60,7 +60,19 @@ use span_tree::node::Ref as SpanRef;
...
+    pub use super::Entry;
+    pub use super::IdentityBase;
+    pub use super::NodeInfo;
+    pub use super::Score;
+    pub use super::SpanWidget;
+    pub use super::TransferRequest;
+    pub use super::TreeNode;
+    pub use super::WidgetIdentity;
+    pub use super::WidgetsFrp;
+}
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs:75]: If it's both `pub` for `super` and reexports things from `super`, maybe we should move it to `super`?

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 4]
```diff
@@ -129,6 +141,16 @@ pub struct OverrideKey {
 pub trait SpanWidget {
     /// Configuration associated with specific widget variant.
     type Config: Debug + Clone + PartialEq;
+    /// Score how well a widget kind matches current builder context. The best scoring widget kind
+    /// will be asked to provide a config using [`SpanWidget::default_config`] method. When this
+    /// method returns [`Score::NotMatched`], this widget kind will not be used, even if it was
+    /// requested by an override. The override will be ignored and another best scoring widget with
+    /// default configuration will be used.
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: I think the docs are not as clear as they could be:
> Score how well a widget kind matches current builder context.

What is the _current_ builder context? Perhaps we could just say it's `ctx`?

> The best scoring widget kind will be asked to provide a config using [`SpanWidget::default_config`] method.

This looks as not necessary, and not contributing much to understanding `match_node` method (and it obscures `When method` in the next sentence - what method do you mean at this point?).

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 5]
```diff
@@ -146,6 +168,25 @@ pub trait SpanWidget {
...
+    /// explicitly requested using an override. Should be the default choice for cases where
+    /// the node is syntactically valid in this widget's context, but no sensible defaults can
+    /// be inferred from context.
+    #[default]
+    OnlyOverride,
+    /// A good match, but there might be a better one. Use this widget if there is no better
+    /// option.
+    Good,
+    /// Widget matches perfectly, stop searching and use this widget immediately.
+    Perfect,
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]:
```suggestion
    /// A good match, but there might be a better one. This widget will be used if there is no better
    /// option.
    Good,
    /// Widget matches perfectly, and be taken outright, without checking other kinds.
    Perfect,
```
Just a proposition. The previous variants don't speak to me, as if it would be _me_ the one searching for widget kind.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 6]
```diff
@@ -227,6 +296,9 @@ macro_rules! define_widget_modules(
                 }
             }
 
+            fn match_node(_: &ConfigContext) -> Score { unreachable!() }
+            fn default_config(_: &ConfigContext) -> Configuration<Self> { unreachable!() }
+
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: Both `DynWidget` and `SpanWidget` are a public API, so I'm not sure if `unreachable` is a good word here.

I strongly prefer one of:
1. Implementing the methods here with some default values (e.g. assume some default widget)
2. make `match_node` and `default_config` a different trait, like `WidgetKind` or similar. If we have a case where something is `SpanWidget` and it does not implement some set of methods, then those methods probably should not be part of this trait.

I think the option 2 is better.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 7]
```diff
@@ -293,136 +370,44 @@ impl Configuration {
...
-                (Kind::Token | Kind::Operation, _) if allow(F::Label) =>
-                    Self::inert(label::Config::default()),
-
-                (Kind::InsertionPoint(_), _) if allow(F::InsertionPoint) =>
-                    Self::inert(insertion_point::Config),
-
-                _ => {
-                    // Option of last resort, label is allowed in this case. Skip assert.
-                    return Self::always(label::Config::default());
+    fn automatic(ctx: &ConfigContext, disallowed: DynKindFlags) -> Self {
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: The documentation does not explain why the function is called `automatic`.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 8]
```diff
@@ -293,136 +370,44 @@ impl Configuration {
...
+            let score = kind.match_node(ctx);
+            let current_score = best_match.map(|(_, score)| score).unwrap_or(Score::NotMatched);
+            if score > current_score {
+                best_match = Some((kind, score));
+                if score == Score::Perfect {
+                    break;
                 }
-            };
+            }
+        }
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: I think we could use `Iterator::fold` or something similar.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 9]
```diff
@@ -1220,7 +1209,7 @@ pub enum IdentityBase {
 }
 
 impl StableSpanIdentity {
-    fn from_node(node: &span_tree::node::Ref) -> Self {
+    fn from_node(node: &SpanRef) -> Self {
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs:1196]: Yes, I know it's an older alias. But I read SpanRef as "reference to span" which it is not.

Maybe `NodeRef`? Assuming that it's obvious in this context that `Node` means "span tree node"?

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 10]
```diff
@@ -1448,50 +1433,51 @@ impl<'a> TreeBuilder<'a> {
...
-                let expr = &self.node_expression;
-                inferred_config =
-                    Configuration::from_node(&span_node, &info, expr, disallowed_configs);
+                inferred_config = Configuration::automatic(&ctx, disallowed_configs);
                 &inferred_config
             }
         };
 
+        let this = &mut *ctx.builder;
+        let ptr_usage = this.pointer_usage.entry(main_ptr).or_default();
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs:1455]: I admit I don't understand many of the changes in this method. And the line `let ptr_usage = this.pointer_usage.entry(main_ptr).or_default();` - is it intentional?

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs [hunk 11]
```diff
@@ -565,23 +577,74 @@ impl From<ImString> for DefaultValue {
...
+    fn match_node(ctx: &ConfigContext) -> Score {
+        let node_expr = ctx.span_expression();
+        let is_placeholder = ctx.span_node.is_expected_argument();
+        let looks_like_vector = is_placeholder
+            || (node_expr.starts_with('[')
+                && node_expr.ends_with(']')
+                && matches!(ctx.span_node.tree_type, Some(ast::TreeType::Expression)));
+
+        if ctx.info.connection.is_some() || !looks_like_vector {
+            return Score::NotMatched;
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: We can make `else` instead of early return without sacrificing code readability.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs [hunk 12]
```diff
@@ -565,23 +577,74 @@ impl From<ImString> for DefaultValue {
...
 }
 
-impl super::SpanWidget for Widget {
+impl SpanWidget for Widget {
     type Config = Config;
 
+    fn match_node(ctx: &ConfigContext) -> Score {
+        let node_expr = ctx.span_expression();
+        let is_placeholder = ctx.span_node.is_expected_argument();
+        let looks_like_vector = is_placeholder
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: TBH when reading this I was confused by the fact that placeholders look like vectors. It's not obvious to me. 

I'd prefer `|| !(looks_like_vector || !is_placeholder)` in the usage place a few lines below.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs [hunk 13]
```diff
@@ -226,6 +234,7 @@ impl Widget {
 struct Model {
     self_id:              WidgetIdentity,
     list:                 ListEditor<ListItem>,
+    append_insert:        Option<object::Instance>,
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: What is "append_insert"? I don't understand the name completely.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs [hunk 14]
```diff
@@ -395,20 +401,14 @@ impl Model {
...
+        self.append_insert = last_insert_crumb
+            .map(|index| build_child_widget(index, insert_config, INSERT_HOVER_MARGIN).root_object);
 
         let (open_bracket, close_bracket) = open_bracket.zip(close_bracket).unzip();
         let mut children = SmallVec::<[&object::Instance; 4]>::new();
         children.extend(&open_bracket);
         children.push(self.list.display_object());
-        children.extend(&append_insert);
+        children.extend(&self.append_insert);
         children.extend(&close_bracket);
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: Cannot we chain and collect? I think it may construct a vector with already sufficient capacity.

**Review by farmaazon — CHANGES_REQUESTED** [review]

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 3 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:75]: It's intentionally a module which you can import using a single declaration. This is a set of common things you want imported in all widget definitions.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 7 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs]: That name indeed looks weak. I will rename it to `infer_from_context`.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 3 above)
Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:75]: Ah, I forget super refers to `widget` module, not `input` :facepalm:

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 6 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs]: I was also thinking about this problem. I think I should just not implement `SpanWidget` for `DynWidget`, as it doesn't really have any utility. Instead, all required methods will be implemented directly on the type.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 8 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs]: I tried using iterators here, but I wasn't able to find anything nice here. It is important to me here to ensure that the iteration stops after first `Score::Perfect` is found. The closest solution I attempted is a chain of `take_while` and `max_by_key`, but that would stop the iteration one element too early (`take_while` would not pass the matched element through itself). I could write similar logic by using `try_fold` and storing extra flag externally, but I don't think it would be simpler than it is right now.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 9 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:1196]: The issue is that the `Ref` is a slightly bigger structure than `Node`, it has important additional fields about the actual span it refers to. `Node` is also too ambiguous when we are talking about widget tree, as it's easy to confuse which tree's node it is.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 10 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:1455]: Yes. I don't love that, but it was necessary to lookup the `pointer_usage` again, so we can break the mutable reference on `self`. It is used when creating the context, which now needed to be created earlier.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs (hunk 13 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: It's the append insertion point element. We need to store it, because its margin is modified in the FRP network. I'm going to rename it to `append_insertion_point`.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs (hunk 14 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: It will never allocate, as this is a SmallVec of up to 4 elements on stack, and we only extend it with at most 4.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 8 above)
Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs]: You don't need a flag. You can check if current_score is already Perfect before checking of next element score.
```rust
    allowed.try_fold(None, |best_match, score| {
        let current_score = best_match.map(|(_, score)| score).unwrap_or(Score::NotMatched);
        (current_score != Score::Perfect).then(|| {
             let score = ....
        }
    }
```
But I'm not sure if it's actually cleaner, so we can stick to your version.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 9 above)
Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:1196]: Then, personally, I would stick to the longer version and remove alias. But it is from older code, so I won't block the PR because of that.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs (hunk 11 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: Refactored this method to avoid nested if expressions.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs (hunk 13 above)
Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: Even with the new name, a comment would be useful, as someone could be not accustomed to span-tree terminology.

File: app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs (hunk 14 above)
Comment (farmaazon) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: You see, it's not obvious from this code. And in the future one could add some `extend` not noticing the 4 constant in the SmallVec. That's why I prefer making chains.

Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs]: Changed it to an iterator using array/flatten/collect, as it reads much better than a series of chains.

**Review by farmaazon — APPROVED** [review]

**Comment by farmaazon** [comment]
## QA Report :red_circle: 

1. One of the reported issues https://github.com/enso-org/enso/issues/6747 is not fully fixed: the second problem (expression not visible entirely on syntax error) still occurs:

image

(The node's expression is `[1, 2, 3] + var1 + [4, 6, "]`)

2. I cannot connect to gray port if it's just a label (drop-downs and list editors can be connected into).

image

Similarly, here I cannot connect to "than", because the entire argument is selected:

image

**Review by wdanilo — APPROVED** [review]

**Comment by wdanilo** [comment]
@farmaazon good catches!

**Comment by Frizi** [comment]
@farmaazon Fixed mentioned issues, ready for second QA round.
image

Note that in above node with incorrect syntax, the right hand side "almost-vector" is not actually recognized as such due to how the expression is parsed. It is in fact not a even distinct subtree that could receive a single widget. Therefore it will not allow drag and drop.

Simplified span-tree:
```
[1, 2, 3] + var1 + [4, 6, "] Root
[1, 2, 3] + var1 + [4, 6, "]  ╰─Argument
[1, 2, 3] + var1 + [4, 6         ├─Argument
[1, 2, 3] + var1 + [4, 6         │  ╰─Argument
[1, 2, 3] + var1 + [4            │     ├─Argument
[1, 2, 3] + var1                 │     │  ├─Chained
[1, 2, 3]                        │     │  │  ├─Argument
[                                │     │  │  │  ├─Token
 1                               │     │  │  │  ├─Argument
  ,                              │     │  │  │  ├─Token
    2                            │     │  │  │  ├─Argument
     ,                           │     │  │  │  ├─Token
       3                         │     │  │  │  ├─Argument
        ]                        │     │  │  │  ╰─Token
          +                      │     │  │  ├─Operation
            var1                 │     │  │  ╰─Argument
                 +               │     │  ├─Operation
                   [4            │     │  ╰─Argument
                   [             │     │     ├─Operation       // This subtree looks weird, but all of those
                   [             │     │     │  ╰─Argument     // nodes received a distinct unique AST IDs.
                   [             │     │     │     ╰─Argument 
                   [             │     │     │        ╰─Token
                    4            │     │     ╰─Argument
                     ,           │     ├─Operation
                       6         │     ╰─Argument
                        ,        ├─Operation
                          "]     ╰─Argument
```

**Comment by farmaazon** [comment]
## QA report 2: :green_circle: 

Issues fixed, no more found.
