### PR TITLE
Ensure compilation is run with a compilation lock

### LINKED ISSUE #8296: `RedefinedMethodException` when evaluating visualization argument
```
[enso] Evaluation of visualization argument [['self', 'argument']] failed in module [local.Enso_Getting_Started_1.Main] with [RedefinedMethodException]: Methods cannot be overloaded, but you have tried to overload Main.main
```

No easy steps to reproduce and full stracktrace is missing. But likely a culprit for "stuck" visualizations on IDE.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Evaluating visualization expression may trigger a full compilation. A change in #7042 went a bit too far and led to a situation when there could be compilations running at the same time leading to a rather obscure `RedefinedMethodException` when the compilation on one thread already finished. This will make the logic correct again at the price of potentially slowing the processing of visualization.

Closes #8296.

### Important Notes

Should make visualizations a bit more stable as well.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala [hunk 1]
```diff
@@ -319,6 +325,7 @@ object UpsertVisualizationJob {
           )
 
         case error =>
+          error.printStackTrace()
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala]: I assume this is temporary. We should log the exception to the logger.

**Review by JaroslavTulach — APPROVED** [review]
Maybe you could add calls like `assert`
`ctx.locking.assertWriteCompilationLock()`
around the code base to make sure the places that need the lock, really have it.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala]: Sorry, leftover
