### PR TITLE
Fix implicit conversion of foreign JS object to Text

### LINKED ISSUE #7263: Implicit `to_text` method call on  Json `PolyglotProxy` object fails with an error
Reproduce with:
```
from Standard.Base import all

main =
    json = Json.parse <| '''
        {
          "headers": {
            "Content-Length": "0",
            "User-Agent": "Java-http-client/17.0.7"
          },
          "origin": "127.0.0.1",
          "url": "",
          "args": {}
        }
    json.get "headers"
```

Fails with:
```
Error in method `to_text` of [Value org.enso.interpreter.epb.runtime.PolyglotProxy@618fb1]: Expected Text but got {"Content-Length":"0","User-Agent":"Java-http-client/17.0.7"}
```

If the last line is replaced with `json.get "origin"` or `json.get "headers" . to_text`, it succeeds.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #7263

### Pull Request Description

Fixes implicit conversion of foreign JS object to `Text`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md)
- All code has been tested:
  - [X] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/JsInteropTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  }
+  
+  @After
+  public void disposeCtx() {
+    ctx.close();
+  }
+
+  @Test
+  public void testDefaultJSPrint() {
+    var src = """
```
Comment (Akirathan) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/JsInteropTest.java:30]: This test cannot be written in pure Enso - we need to invoke the `main` method externally. The `main` method returns `PolyglotProxy` for a foreign JS object, and we check that it is correctly converted to `Text` here.

**Review by JaroslavTulach — APPROVED** [review]
