### PR TITLE
Exclusive context policy ensures EnsoContext.get returns compilation constant

### LINKED ISSUE #6809: Type in Truffle Node breaks GraalVM semantics
What is the difference between _code and data_ in Truffle? Code is supposed to live longer and be more immutable than data. In short:
- code is represented by `com.oracle.truffle.api.nodes.Node`
- data are either primitive values or `TruffleObject` subclasses

In order for `Node` to live longer, be immutable, be reusable, , it is **forbidden** to reference data from `Node`. Rather than that `Node` shall reference a _"general shape of data"_. See the difference between [Function](https://github.com/enso-org/enso/blob/cbc3568cf324a4d02253aacf8f81ce7690633ac7/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java#L1) - the data and [FunctionSchema](https://github.com/enso-org/enso/blob/cbc3568cf324a4d02253aacf8f81ce7690633ac7/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/FunctionSchema.java) - something embedded in `Node`s. Global data are stored in `EnsoContext` - including `Type` instances.

There is at least few violations of this rule that needs to be fixed:
- [CatchTypeBranchNode](https://github.com/enso-org/enso/blob/cbc3568cf324a4d02253aacf8f81ce7690633ac7/engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchTypeBranchNode.java#L14)
- [ReadArgumentNode type check](https://github.com/enso-org/enso/pull/6790/files#r1202447581)

It is necessary to replace such references with **one level of indirection** - the actual `Type` must be obtained from `EnsoContext` - the `Node` can only hold something to **discover the type** effectively.

There is a branch [wip/jtulach/NoTypeInNodePlease_6809](https://github.com/enso-org/enso/commit/567f80218c66ae97154b1468478393a2b511ba91) which contains a failing test. The test creates one `Engine` and uses the same `Source` in two different `Context`s. Using the same engine & source means there is just one instance of AST nodes shared between the two contexts. The `CatchTypeBranchNode` embeds `Type` from the first context, so the first execution succeeds, but second fails as the `Type` for `Text` is different.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #6809 by giving up on any attempt to share `Node` among multiple `Context` via sharing a single `Engine`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Another [benchmark results are sane](https://github.com/enso-org/enso/actions/runs/5763694938)
  - [x] Final [benchmark results are OK](https://github.com/enso-org/enso/actions/runs/5793566254)
  - [x] `SharedContextTest` is passing

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
There is a [discussion about ContextReference](https://graalvm.slack.com/archives/CNQSB2DHD/p1691076832287559) at GraalVM slack. Technically `ContextReference` shall return a _compilation constant_, but it didn't so far. Using `EXCLUSIVE` context policy turn `EnsoContext.get` into _compilation constant_ - that might also speed up our benchmarks.

**Review by Akirathan — APPROVED** [review]
This is very cool. Not only the performance might be better, but also some asserts should stop failing.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SharedEngineTest.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+import org.enso.polyglot.RuntimeOptions;
+import org.graalvm.polyglot.Context;
+import org.graalvm.polyglot.Engine;
+import org.graalvm.polyglot.Source;
+import static org.junit.Assert.assertEquals;
+import org.junit.Before;
+import org.junit.BeforeClass;
+import org.junit.Test;
+
+public class SharedEngineTest extends TestBase {
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SharedEngineTest.java:15]: This is a test taken from branch [wip/jtulach/NoTypeInNodePlease_6809](https://github.com/enso-org/enso/commit/567f80218c66ae97154b1468478393a2b511ba91). The test seems to pass OK with `EXCLUSIVE` context policy.

**Comment by JaroslavTulach** [comment]
[SharedEngineTest](https://github.com/enso-org/enso/actions/runs/5763633639/job/15625876731?pr=7493#step:10:6278) fails on the CI trying to download an edition. Probably an `Engine` configuration problem.

**Comment by JaroslavTulach** [comment]
[DebuggingEnsoTest](https://github.com/enso-org/enso/actions/runs/5793131957/job/15700425003?pr=7493#step:10:6056) asserts - fixed in d1b5913e49d3a6785689b95bec88c7ad21d66be7

**Comment by JaroslavTulach** [comment]
The first [Benchmark results](https://github.com/enso-org/enso/actions/runs/5759320718) were not good, but the second [benchmark results are sane](https://github.com/enso-org/enso/actions/runs/5763694938). Running 3rd [benchmark results](https://github.com/enso-org/enso/actions/runs/5793566254) to confirm the result.

I think the results are OK and we can integrate.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java [hunk 2]
```diff
@@ -347,7 +348,7 @@ boolean hasType() {
   }
 
   @ExportMessage
-  Type getType(@CachedLibrary("this") TypesLibrary thisLib) {
+  Type getType(@CachedLibrary("this") TypesLibrary thisLib, @Cached("1") int ignore) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java:351]: Is the `@Cached("1")` here on purpose or is it a leftover?

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java:351]: I'm also curious what is the purpose of this added argument.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java:351]: It is on purpose to workaround https://github.com/oracle/graal/issues/7131

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java:351]: Wow! Interesting, thanks for the explanation.
So I assume we can remove it once that ticket is fixed?
