### PR TITLE
Some drop down fixes

### LINKED ISSUE #10185: Filter component's drop down bugs
First, one could see two arrows at once:
Screenshot from 2024-06-05 13-31-57

Then, once a number value is picked, it cannot be changed to anything else using drop down; the code does not change.

Screenshot from 2024-06-05 13-35-50

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #10185 

Fixed two bugs from above issue: multiple arrows and being unable to change value from numeric input. The first was just lack of implementation; the second was caused by WidgetNumeric not handling its edit handler properly - the numeric input blur was finishing edit before click at entry could be interpreted.

### Important Notes

There is still one issue with drop-down filtering; will file a bug report soon.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue [hunk 1]
```diff
@@ -318,6 +339,7 @@ function toggleVectorValue(vector: Ast.MutableVector, value: string, previousSta
 function expressionTagClicked(tag: ExpressionTag, previousState: boolean) {
   const edit = graph.startEdit()
   const tagValue = resolveTagExpression(edit, tag)
+  console.log('expressionTagClicked', tagValue)
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue]: Debug logging (here and 1 below)

File: app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue [hunk 2]
```diff
@@ -231,17 +233,36 @@ provideSelectionArrow(
...
+      return suppressArrow.value
+    },
+    set suppressArrow(value) {
+      suppressArrow.value = value
+    },
   }),
 )
 
+watch(
+  () => isHovered.value && !suppressArrow.value,
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue]: Putting this in a computed `showArrow` to use here and in the `v-if`/`v-else-if` would ensure that if our logic for when to show the arrow changes, it is still consistent with when we inhibit a parent arrow.

File: app/gui2/src/providers/selectionArrow.ts [hunk 3]
```diff
@@ -12,6 +12,10 @@ interface SelectionArrowInfo {
   /** Whether or not the arrow provided by this context instance was already requested.
    * Do not request the arrow twice, it will be stolen from other elements! */
   handled: boolean
+  /**
+   *
```
Comment (kazcw) [inline app/gui2/src/providers/selectionArrow.ts:17]: Missing docs

**Review by kazcw — APPROVED** [review]
