### PR TITLE
Provide missing arguments when stepping into a function

### LINKED ISSUE #10792: Strange error when entering unapplied collapsed method
When a collapsed method is missing an argument, upon entering it an error toast pops up with the message `"Execution Failed: "Execution of function main failed (Null receiver values are not supported by libraries.)."` This doesn't effectively explain the situation to the user.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #10792 

Changelog:
- update: replace missing arguments with `Nothing` when schedule a function execution in interactive mode

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java [hunk 1]
```diff
@@ -261,6 +262,24 @@ public void execute(
...
+   *
+   * @param functionCall the function call to update
+   */
+  private void substituteMissingArguments(
+      FunctionCallInstrumentationNode.FunctionCall functionCall) {
+    var arguments = functionCall.getArguments();
+    var argumentInfos = functionCall.getFunction().getSchema().getArgumentInfos();
+    for (var i = 0; i < arguments.length; i++) {
+      if (arguments[i] == null && !argumentInfos[i].hasDefaultValue()) {
+        arguments[i] = context.getBuiltins().nothing();
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:278]: Here you are modifying content of array in `functionCall`! Next time somebody uses the same instance of `functionCall` your modification will be there. Is that what you want?

Hint: `arguments.clone()` called just before the first modification can be your friend.

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java [hunk 2]
```diff
@@ -261,6 +262,24 @@ public void execute(
...
+  /**
+   * Replace the missing arguments of the provided function call with {@link
+   * org.enso.interpreter.node.expression.builtin.Nothing} to make sure that the function call can
+   * be invoked.
+   *
+   * @param functionCall the function call to update
+   */
+  private void substituteMissingArguments(
+      FunctionCallInstrumentationNode.FunctionCall functionCall) {
+    var arguments = functionCall.getArguments();
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java]: Didn't we wanted to change documentation of `getArguments()` method to mention:
- it can contain `null` values
- what's a meaning for `null` value
- it's array is shared and shall not be modified in place?

**Review by JaroslavTulach — APPROVED** [review]
