### PR TITLE
Visuali fixes in multiselect drop-down

### LINKED ISSUE #9617: Group rounded corners in multiselect options
- Rounded corners in multiselect should not be rounded between selected elements (only top and bottom one)
- Rounded corners in dropdown needs to be concentric
- Selected element background width needs to be uniform across all elements.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #9617 

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

~~- [ ] The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~

### CODE REVIEW

File: app/gui2/src/components/widgets/DropdownWidget.vue [hunk 1]
```diff
@@ -108,7 +108,7 @@ export interface DropdownEntry {
   margin-top: calc(0px - var(--dropdown-extend));
   padding-top: var(--dropdown-extend);
   background-color: var(--dropdown-bg);
-  border-radius: 16px;
+  border-radius: 19px;
```
Comment (kazcw) [inline app/gui2/src/components/widgets/DropdownWidget.vue]: It would be nice if these radii were `calc`ed, so that if padding is changed they are still correct.

**Review by kazcw — APPROVED** [review]
