### PR TITLE
Avoid "global" `value` when resolving `polyglot java import` in parallel

### LINKED ISSUE #14840: Method `expToNeg` of type `DepBClass` ... random `GuestJavaInteropTest` failure
There is a [random failure](https://github.com/enso-org/enso/actions/runs/22837567873/job/66237743527#step:14:6617) in
```
Test org.enso.interpreter.test.interop.GuestJavaInteropTest.multiThreadedAccess failed: 
java.util.concurrent.ExecutionException: Standard.Base.Panic.Panic: Method `expToNeg` of type org.enso.example.deps.two.DepBClass could not be found., 
      at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:568)
      at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:577)
      at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1019)
      at org.enso.interpreter.test.interop.JavaInteropTest.multiThreadedAccess(JavaInteropTest.java:531)
      at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
      at java.lang.reflect.Method.invoke(Method.java:565)
      ...
  Caused by: Standard.Base.Panic.Panic: Method `expToNeg` of type org.enso.example.deps.two.DepBClass could not be found.
      at <enso>.Unnamed.main(Unnamed:5)
      at org.graalvm.polyglot.Value.execute(Value.java:1047)
      at org.enso.test.utils.ContextUtils.evalModule(ContextUtils.java:214)
      at org.enso.test.utils.ContextUtils.evalModule(ContextUtils.java:203)
      at org.enso.test.utils.ContextUtils.evalModule(ContextUtils.java:207)
      at org.enso.interpreter.test.interop.JavaInteropTest.lambda$multiThreadedAccess$0(JavaInteropTest.java:528)
      at java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.compute(ForkJoinTask.java:1715)
      at java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1659)
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
      at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
      at 
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixing #14840 
   - removed `ForkJoinPool` because it has its own internal locks that are not `TruffleSafepoint` friendly
   - then the `GuestJavaInteropTest` started to deadlock
- realized #14687 is still rolled back
   - but it shouldn't be - the real problem was #14774
   - thus this PR reapplies #14687
 - I was able to simulate the test flakiness
    - see https://github.com/enso-org/enso/issues/14840#issuecomment-4175909475
 - and [here comes the fix](https://github.com/enso-org/enso/pull/14938/changes#discussion_r3029574568)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java [hunk 1]
```diff
@@ -508,28 +508,82 @@ public void catchCheckedSubExceptionThrownInJava() {
...
+        new Thread("Code2") {
+          double result;
+
+          @Override
+          public void run() {
+            result = ctx().evalModule(code2, "two").asDouble();
+          }
+        };
+    code1Thread.start();
+    awaitThread(code1Thread);
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java]: - removing this line allows us to [reproduce the failing test](https://github.com/enso-org/enso/issues/14840#issuecomment-4175909475)
- removal done in bfd891398b
- 220312b is the fix

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java [hunk 2]
```diff
@@ -508,28 +508,81 @@ public void catchCheckedSubExceptionThrownInJava() {
...
+        Source.newBuilder(
+                "enso",
+                """
+                from Standard.Base import all
+                plus =
+                    6 + 7
+                """,
+                "boot.enso")
+            .build();
+    var bootResult = ctx().evalModule(boot, "plus").asInt();
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java:521]: Without this _"booting"_ we get:
```
sbt:runtime-integration-tests> testOnly *GuestJavaInteropTest -- -z org.enso.interpreter.test.interop.GuestJavaInteropTest.multiThreadedAccess


Exception in thread "Code2" org.graalvm.polyglot.PolyglotException: org.enso.compiler.core.CompilerError: Non-parsed module Code2 used in ImportResolver
        at org.enso.runtime.compiler/org.enso.compiler.Implicits$AsMetadata.$anonfun$unsafeGetMetadata$1(Implicits.scala:127)
        at scala.library@2.13.15/scala.Option.getOrElse(Option.scala:201)
        at org.enso.runtime.compiler/org.enso.compiler.Implicits$AsMetadata.unsafeGetMetadata(Implicits.scala:127)
        at org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolver.liftedTree1$1(ImportResolver.scala:49)
        at org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolver.analyzeModule$1(ImportResolver.scala:45)
        at org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolver.go$1(ImportResolver.scala:173)
        at org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolver.mapImports(ImportResolver.scala:185)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.liftedTree1$1(Compiler.scala:560)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.runImportsAndExportsResolution(Compiler.scala:559)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$4(Compiler.scala:325)
        at scala.library@2.13.15/scala.collection.immutable.List.flatMap(List.scala:294)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:320)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.go$1(Compiler.scala:255)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.runInternal(Compiler.scala:262)
        at org.enso.runtime.compiler/org.enso.compiler.Compiler.run(Compiler.scala:122)
        at org.enso.runtime/org.enso.interpreter.runtime.TruffleCompilerContext$Module.compile(TruffleCompilerContext.java:931)
        at org.enso.runtime/org.enso.interpreter.runtime.Module.compileScope(Module.java:389)
        at org.enso.runtime/org.enso.interpreter.node.ProgramRootNode.execute(ProgramRootNode.java:94)
        at <enso> Code2(Unknown)
```
- our compiler is probably not ready for being used from multiple threads at once at all!
- however that isn't really a subject of this PR...

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmLoader.java [hunk 3]
```diff
@@ -61,18 +60,24 @@ final TruffleObject loadClassObject(String className) throws ClassNotFoundExcept
     var clazz = loadClass(className);
     var clazzValue1 = ctx.asValue(clazz);
     var clazzValue2 = clazzValue1.getMember("static");
-    ctx.asValue(this).execute(clazzValue2);
-    return (TruffleObject) value;
```
Comment (JaroslavTulach) [inline lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmLoader.java:65]: - the access to `value` field modified by previous `execute` call was source of the race condition
- multiple threads might be executing this code at once
- each writing to the same `value` variable
- with  220312b5a72ffe380c908515b144765705cdc637 we make sure each `execute` operates on different `value` location

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/GuestJavaInteropTest.java [hunk 4]
```diff
@@ -8,6 +8,7 @@ public final class GuestJavaInteropTest extends JavaInteropTest {
   public static final ContextUtils ctxRule =
       ContextUtils.newBuilder()
           .withModifiedContext((b) -> b.option("enso.classLoading", "guest"))
+          .assertGC(false)
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/GuestJavaInteropTest.java]: - without disabling the GC of `EnsoContext` we seem to have a leak:

EnsoContext Leak

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/GuestJavaInteropTest.java]: - Today's experiments indicate we can enable the assertGC again: abfb8f7
- Not sure why it was failing yesterday?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java [hunk 5]
```diff
@@ -156,61 +180,94 @@ static void close(EnsoContext ctx) {
...
-    return polyglotJava;
   }
 
   /**
    * This method ensure that hosted as well as guest classpath is the same. This is necessary until
    * real isolation between libraries is implemented.
    */
-  static void addToClassPath(EnsoContext ctx, Object whoIsIgnored, File path)
+  static void addToClassPath(
+      EnsoContext ctx, Object whoIsIgnored, File path, boolean polyglotContextEntered)
```
Comment (4e6) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java]: New boolean flag is unused

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java [hunk 6]
```diff
@@ -156,61 +180,94 @@ static void close(EnsoContext ctx) {
...
+    while (true) {
+      int indexToAdd;
+      synchronized (classPath) {
+        indexToAdd = classPathSize;
+        if (indexToAdd >= classPath.size()) {
+          break;
+        }
+      }
+
+      File elem = classPath.get(indexToAdd);
```
Comment (4e6) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java]: I suppose this works outside of synchronized block only because `classPath` is a `CopyOnWriteArrayList` but it is not obvious from the signature. It deserves a comment, or a more specific type annotation.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java [hunk 7]
```diff
@@ -156,61 +180,94 @@ static void close(EnsoContext ctx) {
...
+      try {
+        InteropLibrary.getUncached().invokeMember(pj, "findLibraries", new LibraryResolver());
+      } catch (InteropException ex) {
+        logger.warn("Cannot register findLibraries", ex);
+      }
+      synchronized (this) {
+        if (polyglotJava == this) {
+          polyglotJava = pj;
+        }
+      }
```
Comment (4e6) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java:213]: I imagine that `pj` produced by `createPolyglotJava()` can potentially leak in this code snippet. What can happen is 
- This thread gets `pj1` from `createPolyglotJava()` and runs `findLibraries` on `pj1`. 
- Other thread gets `pj2`, sets `polyglotJava = pj2`, loops, reads `pj2` and returns `pj2`. 
- Then this thread continues, skips `polyglotJava = pj1` because `polyglotJava == pj2`, and then `pj1` **falls out of scope**. Then loops, reads `pj2`, returns `pj2`

I suppose we should check `polyglotJava == this` before calling `createPolyglotJava`, something like
```java
  synchronized (this) {
    if (polyglotJava == this) {
      pj = createPolyglotJava(ctx);                                                                                                                                  
      polyglotJava = pj;
    } else {                                                                                                                                                         
      pj = polyglotJava;                                                                                                                                             
    }
  }
```

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java]: - thanks for the review
  - however it is basically a "re-review" of #14521
- but yeah, let's address the comments here
- documentation improved in 87d2d55347, OK?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java]: Good catch. Let's remove the flag: 4e7d778e1b

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java (hunk 7 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java:213]: - the code has originally been introduced by #14521

> can potentially leak in this code snippet.

- what do you mean by "leak"?
- what would be an observable problem of such a "leak"?
- we **cannot** call `createPolyglotJava` under `synchronized` lock
   - it could deadlock as #13907 and co. report...
- to mitigate that I am using [transactional data structure](http://wiki.apidesign.org/wiki/TransactionalDataStructure)
   - e.g. multiple insances of `pj` can be created
   - only one of them is then used
- that's **intentional**
   - do you question that?
   - do you see some other problem?
- reopen conversation in case of doubts

**Comment by 4e6** [comment]
> - that's intentional
> - e.g. multiple insances of pj can be created
> - only one of them is then used

That's not obvious at all and deserves a comment

**Review by 4e6 — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> That's not obvious at all and deserves a comment

documentation improved in 87d2d55347a4e2d9f2394190e5a122d406121c52

**Comment by 4e6** [comment]
Commit https://github.com/enso-org/enso/commit/87d2d55347a4e2d9f2394190e5a122d406121c52 does not clarify the behavior of `EnsoPolyglotJava.findPolyglotJava()` method
