### PR TITLE
Make extension method resolution deterministic

### LINKED ISSUE #1243: Conflicting Extension Methods Make Resolution Nondeterministic
> See [comment below](https://github.com/enso-org/enso/issues/1243#issuecomment-1959026431) for updated repro.

### General Summary

When multiple modules define extension methods with the same name and for the same type and both modules are imported, resolution of that method is not deterministic.

### Steps to Reproduce

1. Create new project (here called `Multitest`) with the following files:

- `File1.enso`:
```
from Base import all
Number.foo = 42
```

- `File2.enso`:
```
from Base import all
Number.foo = "answer"
```

- `Main.enso`:
```
from Base import all
import Multitest.File1 
import Multitest.File2

main =
  a = 23.foo
  IO.println a
```

Or download the project from here: [multitest.zip](https://github.com/enso-org/enso/files/5428888/multitest.zip)

2. Run it several times

### Expected Result

The above code should result in an ambiguity error.

Ideally, the error should be detected when importing the module that brings the ambiguous resolution. If that's not possible, executing that method in runtime should yield a runtime error indicating the ambiguity.

### Actual Result

The program sometimes prints `answer` and sometimes `42`, behaving nondeterministically.

### Enso Version

```
Enso Launcher
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/launcher-locking* @ 0bd1686264e50e55a07b73df27b9efb0cac0e37f
Built on:   Linux (amd64)
Current default Enso engine: 
Enso Compiler and Runtime
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/separate-component-manager* @ 746521f8b20de95f4300fb950207c12c8ee687c0
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-122-generic (amd64)
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #1243

### Pull Request Description

Fixes the non-deterministic method resolution in some cases. Normally, method resolution tries to lookup the method in:
1. In the scope where the type is defined
2. In the current module scope
3. In imported module scopes

The third step used to be non-deterministic. I have made it deterministic simply by replacing `java.util.HashMap` by `java.util.LinkedHashMap` in [ModuleScope](https://github.com/enso-org/enso/blob/71d2e97faa5236a626830e5ed4d2e04f18b5e6c6/engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java).

### Important Notes

I have attempted three times to implement this feature:
- In static compilation in a separate compiler pass
- Right after static compilation in `IrToTruffle`, just before execution.
- At runtime, just before method is executed in `UnresolvedSymbol`, as an error.
All these attempts failed. More details in [comment below](https://github.com/enso-org/enso/pull/9844#issuecomment-2122946274).

At the end, I have decided to fix this bug by **making the method resolution deterministic** and not throwing any errors.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ExtensionMethodResolutionTest.java [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+            .option(RuntimeOptions.DISABLE_IR_CACHES, "true")
+            .out(out)
+            .err(out)
+            .build()) {
+      var polyCtx = new PolyglotContext(ctx);
+      try {
+        polyCtx.getTopScope().compile(true);
+        fail("Expected compilation error: " + out);
+      } catch (PolyglotException e) {
+        assertThat(e.getMessage(), is(CompilationAbortedException.COMPILATION_ABORTED_MSG));
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ExtensionMethodResolutionTest.java]: Recognizing exceptions by their message? Unusual. I'd rather hardcode the message string directly into the test....


I think you can `assertTrue(e.isSyntax())`...

**Review by JaroslavTulach — APPROVED** [review]
Looks like you managed to detect this error during static compilation. Good!

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ExtensionMethodResolutionTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ExtensionMethodResolutionTest.java]: Refactored to `assertTrue(e.isSyntaxError())` in 3cd30ab464b200946fe37690e28a0ee1ac6122ff

**Comment by Akirathan** [comment]
All attempts to check extension method conflicts during compilation failed:
- `OverloadResolution` compiler pass does not have information from `org.enso.interpreter.runtime.scope.ModuleScope`, and without it, it is very difficult to query defined methods in imported modules.
- Checking this in `IrToTruffle` failed as well, because the imported modules there might not be compiled, i.e, their stage might not be `CompilationStage.AFTER_CODEGEN`. Initially, I suspected this is a bug in import/export resolution, that it orders the modules in non-topological order, so I have defined tests in https://github.com/enso-org/enso/blob/097f016741420cf921345f9cb143c6ae0e57f50e/engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportExportResolutionOrderTest.java, but it turns out that this is a "feature" not a bug. And changing the behavior of import export resolution is very tricky.

At the end, I have resolved to checks at runtime, inside [UnresolvedSymbol](f11ef4d11756362b6727bde3364c98175e3d7486).

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/097f016741420cf921345f9cb143c6ae0e57f50e/engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportExportResolutionOrderTest.java">enso/engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportExportResolutionOrderTest.java at 097f016741420cf921345f9cb143c6ae0e57f50e · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 2]
```diff
@@ -408,12 +407,12 @@ public void reset() {
    * @return a copy of this scope modulo the requested types
    */
   public ModuleScope withTypes(List<String> typeNames) {
-    Map<String, Object> polyglotSymbols = new HashMap<>(this.polyglotSymbols);
-    Map<String, Type> requestedTypes = new HashMap<>(this.types);
-    Map<Type, Map<String, Supplier<Function>>> methods = new ConcurrentHashMap<>();
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:413]: cc @hubertp. Note that I am getting rid of `ConcurrentHashMap` here and no tests are failing. This should be a proof that `ModuleScope` is intended to be single-threaded. Note that it would even not be possible to use it from more threads, as, e.g., in `reset` method in https://github.com/enso-org/enso/pull/9844/files#diff-c3869665e0ec34703f8e3eea0464924c0e4260eab392dbccdc202ec1f0270379L399, a normal `HashMap` is reassigned to the `methods` field instead of `ConcurrentHashMap`.
