### PR TITLE
Handle undefined arguments in Ydoc timer functions

### LINKED ISSUE #14343: undefined crashes Ydoc
```
 pw:browser [pid=14880][out] org.graalvm.polyglot.PolyglotException: Cannot convert 'undefined'(language: JavaScript, type: undefined)  using Value.asHostObject(): Value is not a host object. You can ensure that the value can be converted using Value.isHostObject(). +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.cannotConvert(PolyglotValueDispatch.java:1408) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.asHostObjectUnsupported(PolyglotValueDispatch.java:914) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.asHostObject(PolyglotValueDispatch.java:905) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.asHostObject(PolyglotValueDispatch.java:2631) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.asHostObject(Value.java:1597) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.Timers.execute(Timers.java:83) +0ms
  pw:browser [pid=14880][out] 	at <js>.globalThis.clearTimeout(timers.js:16) +0ms
  pw:browser [pid=14880][out] 	at <js>._clearTimeouts(ydoc.cjs:27592) +0ms
  pw:browser [pid=14880][out] 	at <js>.close(ydoc.cjs:27347) +0ms
  pw:browser [pid=14880][out] 	at <js>.close(ydoc.cjs:27634) +0ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:26845) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.executeVoid(Value.java:1074) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventTarget$EventStore.dispatchEvent(EventTarget.java:123) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventTarget.execute(EventTarget.java:74) +0ms
  pw:browser [pid=14880][out] 	at <js>.dispatchEvent(event-target.js:63) +0ms
  pw:browser [pid=14880][out] 	at <js>.abort(abort-controller.js:66) +0ms
  pw:browser [pid=14880][out] 	at <js>.dispose(ydoc.cjs:26639) +0ms
  pw:browser [pid=14880][out] 	at <js>.dispose(ydoc.cjs:27108) +0ms
  pw:browser [pid=14880][out] 	at <js>.release(ydoc.cjs:27100) +0ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:27894) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.executeVoid(Value.java:1074) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventTarget$EventStore.dispatchEvent(EventTarget.java:123) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventTarget.execute(EventTarget.java:74) +0ms
  pw:browser [pid=14880][out] 	at <js>.dispatchEvent(event-target.js:63) +0ms
  pw:browser [pid=14880][out] 	at <js>.abort(abort-controller.js:66) +0ms
  pw:browser [pid=14880][out] 	at <js>.dispose(ydoc.cjs:26639) +0ms
  pw:browser [pid=14880][out] 	at <js>.release(ydoc.cjs:28028) +0ms
  pw:browser [pid=14880][out] 	at <js>.release(ydoc.cjs:28019) +0ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:28593) +1ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:28591) +0ms
  pw:browser [pid=14880][out] 	at <js>._f(ydoc.cjs:4234) +0ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:4267) +0ms
  pw:browser [pid=14880][out] 	at <js>.emit(ydoc.cjs:4267) +0ms
  pw:browser [pid=14880][out] 	at <js>.close(ydoc.cjs:28712) +0ms
  pw:browser [pid=14880][out] 	at <js>.:=>(ydoc.cjs:28630) +0ms
  pw:browser [pid=14880][out] 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.executeVoid(Value.java:1074) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventEmitter$Store.lambda$emit$0(EventEmitter.java:123) +0ms
  pw:browser [pid=14880][out] 	at java.base@25.0.1/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4726) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventEmitter$Store.emit(EventEmitter.java:120) +0ms
  pw:browser [pid=14880][out] 	at org.enso.ydoc.polyfill.web.EventEmitter.execute(EventEmitter.java:74) +0ms
```
([src](https://github.com/enso-org/enso/actions/runs/19636128991/job/56234714090?pr=14311#step:15:680))

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

- close #14343

Changelog:
- update: timers implementation to handle undefined arguments correctly

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/Timers.java [hunk 1]
```diff
@@ -69,8 +69,10 @@ public Object execute(Value... arguments) {
         yield setInterval(func, normalizedDelay(delay), args);
       }
       case CLEAR_INTERVAL -> {
-        var intervalId = arguments[1].asHostObject();
-        clearInterval(intervalId);
+        if (arguments[1].isHostObject()) {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/Timers.java:72]: Alternative could be
```suggestion
        if (!arguments[1].isNull()) {
```
both variants are likely to pass the new test. As JavaScript `null` as well as `undefined` are `isNull()`.

**Review by JaroslavTulach — APPROVED** [review]
