### PR TITLE
Fix validation regexes

### LINKED ISSUE #7498: I cannot log in to Enso account with my unorthodox password.
### Discord username

_No response_

### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The password I have set when registering now is not accepted upon _login_:

image

There are two problems:
1. The offending password is `ÑéFÛÅÐåÒ.ú¿¼´N@aö¶U¹jÙÇ3`, so it theoretically meets all requirements.
2. When resetting the password, I got an email with a link leading to a form. The form happily accepted again the password from point 1. It should not.

### Expected behaviour

1. This password should work
2. The reset password form should have the same requirements as the login form.

Plus 3. I think checking the password should be done during registration, not during _login_.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

bc9cde65438ccfb912ed1a427f60a5a6d4a004d4

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes #7498
  - Validation regex previously disallowed non-ASCII characters, now fixed
- Changes every password input to use the correct regex. For old/new passwords, it uses the regular input. For password confirmations, it uses the new password, converted to a regex. This makes it so that the password confirmation input's validation only succeeds when it exactly matches the new password.

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
basic tests:
- :heavy_check_mark: example password (from linked issue) allowed in "change password" modal (all three fields)
- :heavy_check_mark: (new) regular password validation added for "old password" in the "change password" modal
- :heavy_check_mark: validation still rejects invalid passwords in "change password" modal
- :heavy_check_mark: "confirm password" validation still works in "change password" modal
- :heavy_check_mark: example password allowed in login form
- :heavy_check_mark: validation still works in login form
- :heavy_check_mark: example password allowed in registration form
- :heavy_check_mark: validation still works in registration form
- :heavy_check_mark: "confirm password" validation still works in registration form

fixed:
- :heavy_check_mark: example password allowed in password reset form
- :heavy_check_mark: validation works in password reset form
- :heavy_check_mark: "confirm password" validation still works in registration form

:warning: i have not tested the full auth flow from start to finish

**Comment by indiv0** [comment]
Some unit tests around password validation should be easy to add and quite helpful.

**Comment by somebody1234** [comment]
@indiv0 added a basic test runner, not sure if that's what you mean though. feel free to suggest improvements of course.

ideally we'd probably add a proper testing framework  - especially one that lets us to UI/e2e/component testing too, like playwright. but it's probably more complexity than we want to be pulling in for now

**Comment by indiv0** [comment]
✅ QA (almost) passed.

On the forgot password page, there's a double-period at the end of the password requirements message.

Screenshot 2023-08-16 at 23 15 43

Aside from that, full register/login/forgot flow works for me with no issues. All other validation messages appear fine.

File: app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts [hunk 1]
```diff
@@ -2,21 +2,12 @@
 
 /** Regex pattern for valid AWS Cognito passwords. */
 export const PASSWORD_PATTERN =
-    '(?=.*[0-9])(?=.*[A-Z])(?=.*[a-z])(?=.*[ ^$*.\\[\\]\\{\\}\\(\\)?"!@#%&\\/,><\':;\\|_~`=+\\-])' +
-    '[0-9A-Za-z ^$*.\\[\\]\\{\\}\\(\\)?"!@#%&\\/,><\':;\\|_~`=+\\-]{6,256}'
+    '(?=.*[0-9])(?=.*[A-Z])(?=.*[a-z])(?=.*[ ^$*.\\[\\]\\{\\}\\(\\)?"!@#%&\\/,><\':;\\|_~`=+\\-]).{6,256}'
```
Comment (indiv0) [inline app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts:16]: Some explanation of this regex or a link to where it comes from might be nice.

File: app/ide-desktop/package.json [hunk 2]
```diff
@@ -39,6 +39,7 @@
     "watch": "npm run watch --workspace enso-content",
     "watch-dashboard": "npm run watch --workspace enso-dashboard",
     "build-dashboard": "npm run build --workspace enso-dashboard",
+    "test": "npm run test --workspace enso-dashboard",
```
Comment (indiv0) [inline app/ide-desktop/package.json:42]: Would be nice to have this integrated into the CI potentially.

**Review by indiv0 — APPROVED** [review]
LGTM

File: app/ide-desktop/package.json (hunk 2 above)
Comment (somebody1234) [reply app/ide-desktop/package.json:42]: will probably do it in a separate PR because:
- it's a different part of the code so needs different reviewers
- it will be easy to revert in case it causes problems again ( :( )

Comment (indiv0) [reply app/ide-desktop/package.json:42]: 👍

File: app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts (hunk 1 above)
Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts:16]: i was under the impression that we were using [cognito passwords](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html)

but the issue that this PR fixes, has non-basic-latin characters... so i might have to look into things further

**Comment by somebody1234** [comment]
it *is* weird that non-ascii is allowed in passwords... might have to look into it further at some point in the future, *but* it fixes the linked bug so I think it's still fine to merge this

File: app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts (hunk 1 above)
Comment (indiv0) [reply app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts:16]: Indeed we are. I asked this question because I was confused. I had a gut feeling that this *shouldn't* be working, but it is. Cognito should be rejecting the password. But everything seems fine 🤷

**Review by indiv0 — APPROVED** [review]
