### PR TITLE
Fix nested submenus styles

### LINKED ISSUE #13886: Nested selection submenu is hard to distinguish
There is no distinct border or shadow, so overlapping menus look very confusing.

Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #13886

https://github.com/user-attachments/assets/08ad47f8-c6c6-4a12-b9c3-dffd0780bf3b

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue [hunk 1]
```diff
@@ -71,7 +71,9 @@ function nestedEntryToSubmenu(entry: SubmenuEntry<T>, target: HTMLElement): Subm
 
 function onClick(entry: T, keepOpen: boolean, htmlElement: HTMLElement) {
   if (isSubmenuEntry(entry) && entry.isNested) {
-    submenu.value = nestedEntryToSubmenu(entry, htmlElement)
+    // Change submenu in two steps to trigger the size transition.
+    submenu.value = null
+    nextTick(() => (submenu.value = nestedEntryToSubmenu(entry, htmlElement)))
```
Comment (vitvakatu) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue:76]: Is there a better way to trigger SizeTransition?

Comment (kazcw) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue:76]: Changing the `:key` should work

Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue:76]: It doesn’t work with floating styles for some reason; the position of the submenu gets reset. Besides, it doesn’t look like an easier solution.

**Review by kazcw — APPROVED** [review]
