### PR TITLE
Eliminate Blanks inside of Type.Ascription

### LINKED ISSUE #11090: Name.Blank causes "Unexpected internal error" after adding a return type
This change https://github.com/enso-org/enso/pull/11086/files has resulted in 

Error: de_ci::program::command: sbt ℹ️ [ERROR] [2024-09-16T13:11:10.305] [org.enso.runner.Main] Unexpected internal error
 INFO ide_ci::program::command: sbt ℹ️ org.graalvm.polyglot.PolyglotException: org.enso.compiler.core.CompilerError: Compiler Internal Error: Blanks should not be present during dataflow analysis.

https://github.com/enso-org/enso/actions/runs/10882555757/job/30193845599?pr=11086#step:7:1077

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #11090 by processing body of `Type.Ascription` in `LambdaShorthandToLambda` pass.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by jdunkerley — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala [hunk 1]
```diff
@@ -123,7 +121,6 @@ case object LambdaShorthandToLambda extends IRPass {
     freshNameSupply: FreshNameSupply
   ): Expression = {
     ir.transformExpressions {
-      case asc: Type.Ascription => asc
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala:126]: This is relatively nice pass, @Akirathan that could be good subject to
- #10981

This `case asc: Type.Ascription => asc` is currently a way to _"stop processing"_ the subtree.

**Review by GregoryTravis — APPROVED** [review]

**Review by Akirathan — APPROVED** [review]
