### PR TITLE
Exponential backoff in executeExpression request

### LINKED ISSUE #13719: Investigate and improve the issues with the Table viz loading the rows dynamically
While some improvements were made in #13583 and #13600, the table viz still errors with an ERR message on a regular basis.

Some changes to the TS code was suggested in the second PR: https://github.com/enso-org/enso/pull/13600#pullrequestreview-3050351762

Goal is to understand how we can make it more stable and implement as much as possible!
The Colorado Covid example seems to reproduce it regularly.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Modified hardcoded timeout when waiting for data in `executeExpression` request. Most errors in table visualizations were caused because computation was simply taking more time than allowed with a (short) timeout. `executeExpression` was never going to give any guarantees when it comes to returning data withing the specified timeframe. This is because it is dependent on the execution of the program and any possible delays related to it.

Rather than blindly increasing the timeout, added a retry with exponenential backoff. This fixes the frequent `ERR` problems in table visualizations.

Closes #13719.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by hubertp** [comment]
Please note that while I'm aware of potential [suggestions](https://github.com/enso-org/enso/pull/13600#discussion_r2227648513) to implementation in this PR I chose to address the root of the most pressing issue only - frequent presence of `ERR` message in table grid. We can (and should!) still continue with refactoring later but my lack of familiarity with this part of codebase would mean it will take much longer (potential candidate for the next release).

File: app/gui/src/project-view/stores/project/index.ts [hunk 1]
```diff
@@ -387,15 +384,31 @@ export function createProjectStore(
...
+              inProgress.value -= 1
+              state = 0 // Prevent further updates from this handler.
+              dataConnection.off(`${OutboundPayload.VISUALIZATION_UPDATE}`, dataHandler)
+              executionContext.off('visualizationEvaluationFailed', errorHandler)
+              reject(Err(`executeExpression: Execution timed out.`))
+            }
+          }
+        })
+      }
+      waitWithExponentialBackoff(0, timeoutMs)
```
Comment (kazcw) [inline app/gui/src/project-view/stores/project/index.ts]: This seems like a lot of complexity to schedule printing some debug messages.

I have some questions:
- Do we need this message at all? If I see it in the console I wouldn't know what I'm supposed to do about it.
- Does it need to be warning-level, with a stack trace?
- Do we need it in release builds, or could it be gated with `DEV:`?
- Would it not provide equally useful information to wait once, and in the log message include the elapsed time at success/cancelation?

Comment (hubertp) [reply app/gui/src/project-view/stores/project/index.ts]: True, this should be a dev warning.

Comment (hubertp) [reply app/gui/src/project-view/stores/project/index.ts]: Printed only in `DEV` now.
One reason why I would prefer it to leave exponential backoff is that it is possible to see that it is still waiting actively for some computation rather than silently staying in some spinning wheel. At least it gives me comfort that a problem is on the backend rather than in GUI.

File: app/gui/src/project-view/stores/project/index.ts [hunk 2]
```diff
@@ -387,15 +384,31 @@ export function createProjectStore(
...
+              const incRetryAttempt = retryAttempt + 1
+              DEV: console.warn(
+                'Waiting on data (expressionId=' +
+                  expressionId +
+                  ', visualizationId=' +
+                  visualizationId +
+                  '), retry attempt: ' +
+                  incRetryAttempt,
+              )
+              waitWithExponentialBackoff(incRetryAttempt, timeoutMs * 2 ** retryAttempt)
```
Comment (JaroslavTulach) [inline app/gui/src/project-view/stores/project/index.ts:400]: - **Q**: asking myself: What's the difference between setting the time out higher and retrying few times?
- **A**: a warning is printed in the console
- **Q**: Is that enough?
- **Q**: Shouldn't we find out why the engine is taking so long to process the request?
- **Q**: What is the engine actually doing meanwhile?
- **A**: Recently I relearned we have a #8309 capability built into the language server thanks to @4e6 
- for a while we were struggling to _find a suitable moment_ to turn the self sampling on
- **A**: Now we have it!
- Send `profiling/start` together with `console.warn`!

**Review by JaroslavTulach — APPROVED** [review]
- consider using #8309
- to provide deeper insight into what's happening in the engine
- while the IDE is starving to obtain a visualization result

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/stores/project/index.ts (hunk 2 above)
Comment (hubertp) [reply app/gui/src/project-view/stores/project/index.ts:400]: Follow up in #13765
