### PR TITLE
Fix header rename

### LINKED ISSUE #11150: Table Editor Widget - When switching editing between headers, the edit stops.
To reproduce, in any table input widget:
1. Click at header of some column to edit its name
2. Without accepting, click another column name

Expected: The previous edit should be accepted, and the next column should be edited.

Actual: The previous edit is accepted, but next column is not edited.

Cause: Accepting column name makes all headers to be re-mounted, so we loose the `edit` flag

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #11150 

The fix consist of two parts:
1. The state of editing is kept in the widget, not in particular header components; the communication is done in a vue fashion - the headers calls callback if they _want_ to be edited/not edited.
2. Copied the AgGridVue component and make it _not_ mount header components by itself, but use our VueComponentHost instead (which also as improved a bit, so we have more guarantees of preserving components).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue [hunk 1]
```diff
@@ -211,23 +237,50 @@ function processDataFromClipboard({ data, api }: ProcessDataFromClipboardParams<
...
-      onHeaderEditingStarted: headerEditHandler.headerEditedInGrid.bind(headerEditHandler),
-      onHeaderEditingStopped: headerEditHandler.headerEditingStoppedInGrid.bind(headerEditHandler),
-    },
-  },
+  headerComponentParams,
+}
+
+const vueComponentHost = ref<VueHost>()
+
+class TableHaderComponent implements IHeaderComp {
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue]:
```suggestion
class TableHeaderComponent implements IHeaderComp {
```

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue [hunk 2]
```diff
@@ -211,23 +237,50 @@ function processDataFromClipboard({ data, api }: ProcessDataFromClipboardParams<
...
+  private container: HTMLElement = document.createElement('div')
+  private handle: VueComponentHandle | undefined
+
+  init(params: ComponentProps<typeof TableHeader>) {
+    if (!vueComponentHost.value) {
+      console.error('Missing vue component host!')
+      // TODO[ao]: what's now?
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue]: We could make this case statically impossible by changing the relationship between the `VueHost` and its component. If `VueComponentHost` accepts a `VueHost` as a parameter and is only responsible for rendering it, then this component could own the `VueHost` datastructure.

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue [hunk 3]
```diff
@@ -1,95 +1,96 @@
...
+  inputElement,
+  (newVal, oldVal) => {
+    if (newVal != null && oldVal == null) {
+      // Whenever input field appears, focus and select text
+      newVal.focus()
+      newVal.select()
+    }
+  },
+  { immediate: true },
+)
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue]: I think this could be simpler:
- Why `immediate`? The `ref` will never have a value yet when this runs, right?
- Why check if the old value is nullish?

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue [hunk 4]
```diff
@@ -98,12 +99,12 @@ function onMouseRightClick(event: MouseEvent) {
 
 <template>
   <SvgButton
-    v-if="params.type === 'newColumn'"
+    v-if="columnParams.type === 'newColumn'"
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue:98]: It seems like more of this component is dependent on `columnParams.type` than not; would it make sense to split it into separate components?

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue (hunk 4 above)
Comment (farmaazon) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue:98]: I will leave it now; technically I could define a separate component for every column, but this is not easy after all refactoring & wrappers.

File: CHANGELOG.md [hunk 5]
```diff
@@ -8,11 +8,14 @@
   button protruding from the output port.][11836].
 - [Fixed nodes being selected after deleting other nodes or connections.][11902]
 - [Redo stack is no longer lost when interacting with text literals][11908].
+- [Fixed bug when clicking header in Table Editor Widgetdidn't start editing
```
Comment (kazcw) [inline CHANGELOG.md]:
```suggestion
- [Fixed bug when clicking header in Table Editor Widget didn't start editing
```

**Review by kazcw — APPROVED** [review]

**Review by MrFlashAccount — APPROVED** [review]
Approving `enso-common/utilities` changes

**Comment by farmaazon** [comment]
Sorry for notifying everyone, I mismanaged my git commits.

image
