### PR TITLE
Fix doc editor sync

### LINKED ISSUE #10527: Synchronization between code editor and documentation editor is not perfect
Some kinds of updates are not immediately propagated from the code editor to the documentation panel; see the attached video.

The code is after fixing https://github.com/enso-org/enso/issues/10471 TODO: add link to the commit.

https://github.com/enso-org/enso/assets/6566674/01c2d567-c108-43d5-b5d6-5dd26de1a542

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fixes #10527.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/components/lexical/sync.ts [hunk 1]
```diff
@@ -32,13 +32,15 @@ export function useLexicalSync<T>(
...
+  const getEditedContent = computed(() => {
     return state.value.read($read)
   })
 
+  const getContent = () => editor.getEditorState().read($read)
+
   return {
     content: {
-      state: getContent,
+      state: getEditedContent,
```
Comment (vitvakatu) [inline app/gui2/src/components/lexical/sync.ts]: `content.state` is still misleading, because it is not the actual _state_ of the editor, but rather a one-way view of user edits.

**Review by vitvakatu — APPROVED** [review]
Fixes the immediate issue, so I think we should merge it.
There is still the issue with AST edits when `SYNC_TAG` mechanism is disabled, though.
