### PR TITLE
Open multi-select when items are edited

### LINKED ISSUE #10233: Multi-select should open when clicking on items
image

Multi-select should open when clicking on "columns" or on "name_char"

Today it only opens when clicking on "columns"

### LINKED ISSUE #10338: After changing drop-down input variant, the drop-down is no longer displayed.
To reproduce: place `filter` component, pick `Equal` for filter condition and pick `<Number literal>` as `to` argument. Then, change it to `<Text literal>. Click the text input - there should be drop-down opened, but it is not.

The cause is a bug in edit handler; when picking another widget input, the AST has new ID, but edit handler of WidgetSelection on this AST still has old port ID. Starting interaction in inner widget will make the parent (selection) widget start interaction with old ID, which will be immediately canceled because the child will start different interaction.

As a solution, I think WidgetEditHandler should be simplified, and not rely on any portId: just if any widget starts interaction, it should start interaction on top-level parent, canceling any existing interaction

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Vector widget propagates child edits to parent.

Fixes #10233, #10338.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/providers/widgetRegistry/editHandler.ts [hunk 1]
```diff
@@ -187,6 +205,7 @@ class PortEditInteraction implements Interaction {
   readonly active: Ref<boolean>
   private readonly resumable: PortEditResumeData
   private readonly interactions = new Array<PortEditSubinteraction>()
+  private child: PortEditInteraction | undefined = undefined
```
Comment (farmaazon) [inline app/gui2/src/providers/widgetRegistry/editHandler.ts]: The docs say that `PortEditInteraction` is a 
> Top-level interaction active when a port is being edited by associated widgets.

But here child is also `PortEditInteraction`, and clearly it cannot be top-level, as it is a child. Also, we already have `interactions` field - why do we need additional `child` field?

File: app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue [hunk 2]
```diff
@@ -41,6 +42,62 @@ const value = computed({
...
+
+const { childEditHandler } = useChildEditForwarding('WidgetVector')
+
+function itemInput(ast: Ast.Ast): WidgetInput {
+  const baseInput = WidgetInput.FromAst(ast)
+  return {
+    ...baseInput,
+    dynamicConfig: itemConfig.value,
+    forcePort: true,
+    editHandler: childEditHandler(baseInput, ast.id),
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue]: So far, it was the _parent's_ edit handler which was passed in WidgetInput, so the constructor in WidgetHandler takes it and treats as a parent. I think it was better, because it was simpler; We just had one handler for each widget. Now we have handler of parent widget, then handlers for parent-widget relations, and finally the handler of the child itself (because the child might want to handle some interactions in its own way: `WidgetText` for example creates new WidgetHandler for this reason)

In my initial implementation, all hooks (including `edit` hook) presented portId as origin, to handle cases exactly like this (I was thinking about DateTime widget then). It was lost somewhere in the process, and sorry I didn't catch it on review. Let's restore it now.

File: app/gui2/src/providers/widgetRegistry/editHandler.ts [hunk 3]
```diff
@@ -106,6 +109,22 @@ export class WidgetEditHandler {
...
+    )
+    return new WidgetEditHandler(
+      widgetId as WidgetId,
+      myInteraction,
+      this,
+      getPortEdit,
+      input.portId,
+    )
+  }
+
```
Comment (farmaazon) [inline app/gui2/src/providers/widgetRegistry/editHandler.ts]: I think this should not be needed anymore, given my comment above; the children widget should have their parent in WidgetInput received in constructor,

**Review by farmaazon — CHANGES_REQUESTED** [review]

**Comment by farmaazon** [comment]
Sorry for late review, but I had hard time understanding again the editHandler code.

**Review by farmaazon — APPROVED** [review]
Accept to not block this PR for merging: I'm off till Wednesday, so let someone else re-review your changes.

File: app/gui2/src/providers/widgetRegistry/editHandler.ts
Comment (farmaazon) [inline app/gui2/src/providers/widgetRegistry/editHandler.ts:1]: Now this file looks sooo much better, thanks!

**Review by farmaazon — APPROVED** [review]
