### PR TITLE
Fix dropdowns in fullscreen viz

### LINKED ISSUE #13655: Dropdowns on Buttons not visible in Full Screen Viz
Guessing z-order but the dropdown is not available when a viz is maximised.
Fine when not full screen.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #13655 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/providers/popoverRoot.ts [hunk 1]
```diff
@@ -10,5 +10,5 @@ import { type Ref } from 'vue'
  */
 export const [providePopoverRoot, usePopoverRoot] = createContextStore(
   'popoverRoot',
-  identity<Ref<HTMLElement | undefined | null>>,
+  identity<ToValue<HTMLElement | undefined | null>>,
```
Comment (kazcw) [inline app/gui/src/project-view/providers/popoverRoot.ts]: I think usage of this API is simpler if the value it produces is a more specific type than `ToValue`--it looks like `Readonly<Ref<..>>` would suit the consumers and producer.

**Review by kazcw — COMMENTED** [review]
This seems worth an integration test--contexts and layers are the sort of thing that tend to break, and developers may not catch it before users do.

File: app/gui/src/project-view/components/DropdownMenu.vue [hunk 2]
```diff
@@ -52,7 +53,7 @@ const { floatingStyles } = useFloating(rootElement, floatElement, {
       class="arrow"
       :class="{ visible: alwaysShowArrow }"
     />
-    <ConditionalTeleport :target="popoverRoot">
+    <ConditionalTeleport :target="toValue(popoverRoot)">
```
Comment (kazcw) [inline app/gui/src/project-view/components/DropdownMenu.vue]: Unneeded toValue

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue [hunk 3]
```diff
@@ -111,7 +111,7 @@ export interface SubmenuComponent {
 </script>
 
 <template>
-  <ConditionalTeleport :target="rootElement">
+  <ConditionalTeleport :target="toValue(rootElement)">
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue]: Unneeded toValue

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/components/DropdownMenu.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/DropdownMenu.vue]: Yep

**Comment by vitvakatu** [comment]
Uh, whatever, sorry for force-push
