### PR TITLE
Graph editor breadcrumbs integration

### LINKED ISSUE #7788: Graph Editor Breadcrumbs
To be tested after #8068.

GE breadcrumbs should show the "stack trace" of the currently displayed graph. When clicked at crumb, all crumbs on the right should be grayed out, and we should jump to definition represented by crumb (updating the execution context accordingly).

For details, see how it works in the old GUI.

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Implements  #7788

[Peek 2023-12-12 10-46.webm](https://github.com/enso-org/enso/assets/1428930/7d1f45f6-8323-4adc-9a8c-f6f4bcaeb143)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor.vue [hunk 1]
```diff
@@ -15,6 +15,7 @@ import GraphMouse from '@/components/GraphMouse.vue'
 import PlusButton from '@/components/PlusButton.vue'
 import TopBar from '@/components/TopBar.vue'
 import { useDoubleClick } from '@/composables/doubleClick.ts'
+import { useStackNavigator } from '@/composables/stackNavigator.ts'
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue]: unnecessary trailing extension

File: app/gui2/src/composables/stackNavigator.ts [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+  })
+
+  const allowNavigationRight = computed(() => {
+    return projectStore.executionContext.desiredStack.length < breadcrumbs.value.length
+  })
+
+  function stackItemToLabel(item: StackItem): string {
+    switch (item.type) {
+      case 'ExplicitCall':
+        return item.methodPointer.name
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:35]: it'd be nice to have braces around this case too for consistency

File: app/gui2/src/composables/stackNavigator.ts [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+  const graphStore = useGraphStore()
+
+  const breadcrumbs = ref<StackItem[]>([])
+
+  const breadcrumbLabels = computed(() => {
+    const activeStackLength = projectStore.executionContext.desiredStack.length
+    return breadcrumbs.value.map((item, index) => {
+      const label = stackItemToLabel(item)
+      const isActive = index < activeStackLength
+      return { label, active: isActive } as BreadcrumbItem
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts]: type assertions `as T` are unsound. prefer `satisfies BreadcrumbItem` or `(item, index): BreadcrumbItem`

File: app/gui2/src/composables/stackNavigator.ts [hunk 4]
```diff
@@ -0,0 +1,118 @@
+import type { BreadcrumbItem } from '@/components/NavBreadcrumbs.vue'
+import { useGraphStore } from '@/stores/graph'
+import { useProjectStore } from '@/stores/project'
+import { qnLastSegment, tryQualifiedName } from '@/util/qualifiedName.ts'
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts]: trailing extension

File: app/gui2/src/composables/stackNavigator.ts [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+import { computed, onMounted, ref } from 'vue'
+import type { StackItem } from '../../shared/languageServerTypes.ts'
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts]: prefer `shared/` over `../../shared/`

File: app/gui2/src/composables/stackNavigator.ts [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+    const activeStackLength = projectStore.executionContext.desiredStack.length
+    return breadcrumbs.value.map((item, index) => {
+      const label = stackItemToLabel(item)
+      const isActive = index < activeStackLength
+      return { label, active: isActive } as BreadcrumbItem
+    })
+  })
+
+  const allowNavigationLeft = computed(() => {
+    return projectStore.executionContext.desiredStack.length > 1
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:25]: (optional) can remove the braces and `return`

File: app/gui2/src/composables/stackNavigator.ts [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+      }
+    }
+  }
+
+  function handleBreadcrumbClick(index: number) {
+    const activeStack = projectStore.executionContext.desiredStack
+    if (index < activeStack.length) {
+      const diff = activeStack.length - index - 1
+      for (let i = 0; i < diff; i++) {
+        projectStore.executionContext.pop()
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:50]: maybe prefer `projectStore.executionContext.splice(activeStack.length, Number.MAX_SAFE_INTEGER)` (or `projectStore.executionContext.length`, I think any sufficiently high number will do)

File: app/gui2/src/composables/stackNavigator.ts [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+      }
+    } else if (index >= activeStack.length) {
+      const diff = index - activeStack.length + 1
+      for (let i = 0; i < diff; i++) {
+        const stackItem = breadcrumbs.value[index - i]
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:55]: is this logic correct? or does this repeatedly add the same stack item?

File: app/gui2/src/composables/stackNavigator.ts [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+          console.warn('Cannot enter non-local call.')
+        }
+      }
+    }
+    graphStore.updateState()
+  }
+
+  function enterNode(id: ExprId) {
+    const expressionInfo = graphStore.db.getExpressionInfo(id)
+    if (expressionInfo == undefined || expressionInfo.methodCall == undefined) {
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts]: prefer `x == null` (or `!x` if we want to ignore all falsy values) over `x == undefined`

File: app/gui2/src/composables/stackNavigator.ts [hunk 10]
```diff
@@ -0,0 +1,118 @@
...
+      console.debug('Cannot enter node that has no method call.')
+      return
+    }
+    const definedOnType = tryQualifiedName(expressionInfo.methodCall.methodPointer.definedOnType)
+    if (!projectStore.modulePath?.ok) {
+      console.warn('Cannot enter node while no module is open.')
+      return
+    }
+    const openModuleName = qnLastSegment(projectStore.modulePath.value)
+    if (definedOnType.ok && qnLastSegment(definedOnType.value) != openModuleName) {
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts]: prefer `!==` over `!=`

File: app/gui2/src/composables/stackNavigator.ts [hunk 11]
```diff
@@ -0,0 +1,118 @@
...
+      console.debug('Cannot enter node that is not defined on current module.')
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:80]: is this supposed to be `console.debug` and not `console.warn` (or perhaps `console.info`?)

File: app/gui2/src/composables/stackNavigator.ts [hunk 12]
```diff
@@ -0,0 +1,118 @@
...
+
+  /// Enter the next node from the history stack. This is the node that is the first greyed out item in the breadcrumbs.
+  function enterNextNodeFromHistory() {
+    const nextNodeIndex = projectStore.executionContext.desiredStack.length
+    const nextNode = breadcrumbs.value[nextNodeIndex]
+    if (nextNode?.type === 'LocalCall') {
+      projectStore.executionContext.push(nextNode.expressionId)
+      graphStore.updateState()
+    } else {
+      console.warn('Cannot enter non-local call.')
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:98]: consider inverting the `if` condition so that the warning is more like an early return

File: app/gui2/src/composables/stackNavigator.ts [hunk 13]
```diff
@@ -0,0 +1,118 @@
...
+      return
+    }
+    const openModuleName = qnLastSegment(projectStore.modulePath.value)
+    if (definedOnType.ok && qnLastSegment(definedOnType.value) != openModuleName) {
+      console.debug('Cannot enter node that is not defined on current module.')
+      return
+    }
+    projectStore.executionContext.push(id)
+    graphStore.updateState()
+    breadcrumbs.value = projectStore.executionContext.desiredStack.slice()
```
Comment (somebody1234) [inline app/gui2/src/composables/stackNavigator.ts:85]: optional: `[...arr]` or `Array.from(arr)` may be clearer than `arr.slice()` - even though `.slice()` *is* a common way to do this

**Review by somebody1234 — APPROVED** [review]
mostly code style nits

File: app/gui2/src/composables/stackNavigator.ts (hunk 7 above)
Comment (MichaelMauderer) [reply app/gui2/src/composables/stackNavigator.ts:50]: `splice` does not exist, as `pop` is not just a generic container method, but does more work to actually modify the execution context.

File: app/gui2/src/composables/stackNavigator.ts (hunk 8 above)
Comment (MichaelMauderer) [reply app/gui2/src/composables/stackNavigator.ts:55]: This should be correct. `index` is the index of the item clicked, and we add each successive item.

File: app/gui2/src/composables/stackNavigator.ts (hunk 6 above)
Comment (MichaelMauderer) [reply app/gui2/src/composables/stackNavigator.ts:25]: That makes the line veeeeeery long.

Comment (somebody1234) [reply app/gui2/src/composables/stackNavigator.ts:25]: prettier should take care of that. specifically the formatting should be the same as it is now. i think it's worth a try at least? unless you already have, in which case you can mark this as resolved

File: app/gui2/src/components/GraphEditor.vue [hunk 14]
```diff
@@ -114,7 +114,9 @@ useEvent(window, 'keydown', (event) => {
 })
 useEvent(window, 'pointerdown', interactionBindingsHandler, { capture: true })
 
-onMounted(() => viewportNode.value?.focus())
+onMounted(() => {
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor.vue]: unnecessary change

**Review by Frizi — APPROVED** [review]
