### PR TITLE
TelemetryAppender is not stopped on first encountered failure

### LINKED ISSUE #12561: TelemetryAppender should retry to send previously failed requests
Follow-up of #12488

TelemetryAppender, introduced in #12488, stops any attempts to send any HTTP requests to the cloud once first failure is encountered. This logic was implemented in https://github.com/enso-org/enso/pull/12488/commits/79d9ad94b63a4b4d9166081a45f47916eb7b2544. This is wrong. The TelemetryAppender should retry sending some requests that failed previously later.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #12561

### Pull Request Description

TelemetryAppender is not stopped on first encountered failure.

### Important Notes

Failure to send a batch of log messages may occur:
- When `MAX_RETRIES` attempts to refresh an access token fails - cloud returns unexpected response.
- When `MAX_RETRIES` attempts to send the batch fails - cloud returns unexpected response.

In those cases, the batch is just dropped, and a warning is logged. The service continues to run and tries to send another batch.

Optimally, retries should be sent with a binary back off. I have not implemented the binary back off yet to keep this PR simple.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [X] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java [hunk 1]
```diff
@@ -220,6 +207,18 @@ private void sendLogRequest(HttpRequest request, int retryCount) throws RequestF
     }
   }
 
+  private AuthenticationData fetchNewAccessToken() {
+    for (int i = 0; i < MAX_RETRIES; i++) {
+      var refreshedAuthData = tokenRefresher.fetchNewAccessToken();
+      if (refreshedAuthData != null) {
+        return refreshedAuthData;
+      } else {
+        LOGGER.warn("Failed to refresh token. Retrying... (attempt {}/{})", i + 1, MAX_RETRIES);
```
Comment (hubertp) [inline lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java:216]: I would expect to see _some_ exponential backoff here.

File: lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+/**
+ * A custom jUnit {@link TestRule} that captures all the logs and prints them only if there is a
+ * test failure.
+ */
+public final class ConsumeLogs implements TestRule {
+  private static final Level LOG_LEVEL = Level.TRACE;
+  private final MemoryAppender appender = new MemoryAppender();
+
+  public ConsumeLogs() {
+    var context = (LoggerContext) LoggerFactory.getILoggerFactory();
```
Comment (JaroslavTulach) [inline lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java:24]: Use `ObservableMessage`. It already contains all the necessary logic.

File: build.sbt [hunk 3]
```diff
@@ -1144,7 +1144,7 @@ lazy val `logging-service-telemetry` = project
   .enablePlugins(JPMSPlugin)
   .configs(Test)
   .settings(
-    frgaalJavaCompilerSetting,
+    customFrgaalJavaCompilerSettings("21"),
```
Comment (JaroslavTulach) [inline build.sbt]: Why do we need JDK 21 APIs?

**Review by JaroslavTulach — APPROVED** [review]

File: lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java (hunk 1 above)
Comment (Akirathan) [reply lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java:216]: That was my original intent. But I have no idea how to simply implement that with JDK. Any suggestions?

Comment (hubertp) [reply lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java:216]: Something like https://github.com/enso-org/enso/blob/develop/distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso#L43 would suffice.
You can obviously avoid the hardcoded list by using `Math.pow(2, attempt)` etc.

File: lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java (hunk 2 above)
Comment (Akirathan) [reply lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java:24]: I tried
```diff
diff --git a/lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java b/lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java
index 31f78ed926..657811fe7a 100644
--- a/lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java
+++ b/lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java
@@ -2,10 +2,9 @@ package org.enso.logging.service.telemetry.test;
 
 import ch.qos.logback.classic.Level;
 import ch.qos.logback.classic.LoggerContext;
-import ch.qos.logback.classic.spi.ILoggingEvent;
-import ch.qos.logback.core.AppenderBase;
 import java.util.ArrayList;
 import java.util.List;
+import org.enso.logger.ObservedMessage;
 import org.junit.rules.TestRule;
 import org.junit.runner.Description;
 import org.junit.runners.model.Statement;
@@ -18,17 +17,14 @@ import org.slf4j.LoggerFactory;
  */
 public final class ConsumeLogs implements TestRule {
   private static final Level LOG_LEVEL = Level.TRACE;
-  private final MemoryAppender appender = new MemoryAppender();
+  private final List<ObservedMessage> logMessages = new ArrayList<>();
+  private final AutoCloseable logObserver;
 
   public ConsumeLogs() {
     var context = (LoggerContext) LoggerFactory.getILoggerFactory();
-    appender.setContext(context);
-    appender.setName("MemoryAppender");
     var rootLogger = context.getLogger(Logger.ROOT_LOGGER_NAME);
-    rootLogger.detachAndStopAllAppenders();
-    rootLogger.addAppender(appender);
     rootLogger.setLevel(LOG_LEVEL);
-    appender.start();
+    logObserver = ObservedMessage.observe(rootLogger, logMessages::add);
   }
 
   @Override
@@ -50,30 +46,18 @@ public final class ConsumeLogs implements TestRule {
       try {
         base.evaluate();
       } catch (Throwable e) {
-        System.err.println(
-            "Test "
-                + description.getDisplayName()
-                + " failed with "
-                + e.getClass().getName()
-                + ". Captured output from the logs:");
-        for (var event : appender.getEvents()) {
-          System.err.println("  " + event.getFormattedMessage());
+        System.err.println("Test "
+            + description.getDisplayName()
+            + " failed with "
+            + e.getClass().getName()
+            + ". Captured output from the logs:");
+        for (var log : logMessages) {
+          System.err.println("  " + log.getFormattedMessage());
         }
         throw e;
+      } finally {
+        logObserver.close();
       }
     }
   }
-
-  private static final class MemoryAppender extends AppenderBase<ILoggingEvent> {
-    private final List<ILoggingEvent> events = new ArrayList<>();
-
-    public List<ILoggingEvent> getEvents() {
-      return events;
-    }
-
-    @Override
-    protected void append(ILoggingEvent eventObject) {
-      events.add(eventObject);
-    }
-  }
 }
```

But that does not work - log messages are sent both to console and to the observer. This is because `ObservedMessage` does not _silence_ the other appenders. I would like to explicitly remove all the other appenders, so there are no logs in the console.

File: build.sbt (hunk 3 above)
Comment (Akirathan) [reply build.sbt]: It was needed for tests. But I removed it in beb3b4f4d21f29b729c182cb22f37ce85193db57
