### PR TITLE
Move output ports to edges level

### LINKED ISSUE #11922: Copy button on error messages not working
The copy button on error messages is not working (presumably because it is under the output port.)

image

Version 2024.5.1
Build 23cf258047f4391161b188ba520ca0b0929bb637
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #11922

https://github.com/user-attachments/assets/ea85bd95-a02b-4d41-a489-bfc55161e299

https://github.com/user-attachments/assets/167062b1-c490-4374-ad32-7e11cb2f8826

### Important Notes

See https://github.com/enso-org/enso/issues/12131 and https://github.com/enso-org/enso/issues/12132.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by vitvakatu** [comment]
Oops, not exactly what I wanted, sorry for ping.

File: app/gui/src/project-view/components/GraphEditor/GraphEdges.vue [hunk 1]
```diff
@@ -113,6 +119,12 @@ function createEdge(source: AstId, target: PortId) {
     }
   }
 }
+
+const nodeIdsWithOutputPorts = computed(() =>
+  Array.from(graph.db.nodeIdToNode.entries())
+    .filter(([_, node]) => node.type !== 'output')
+    .map(([id]) => id),
+)
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/GraphEdges.vue]: Why not use `graph.db.nodeOutputPorts`?

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue [hunk 2]
```diff
@@ -453,6 +463,10 @@ const { editingComment } = provideComponentButtons(
 )
 
 const showMenuAt = ref<{ x: number; y: number }>()
+onBlur(() => {
+  graph.setNodeHovered(nodeId.value, false)
+  updateNodeHover(undefined)
+})
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: Is it this component's blur or window/document blur? I think it should be the latter, but the name does not say it.

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue [hunk 3]
```diff
@@ -464,8 +478,8 @@ const showMenuAt = ref<{ x: number; y: number }>()
     :class="nodeClass"
     :data-node-id="nodeId"
     @pointerdown.stop
-    @pointerenter="((nodeHovered = true), updateNodeHover($event))"
-    @pointerleave="((nodeHovered = false), updateNodeHover(undefined))"
+    @pointerenter="(graph.setNodeHovered(nodeId, true), updateNodeHover($event))"
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/GraphNode.vue:483]: Perhaps `setNodeHovered` should be just a part of `updateNodeHover`? I think I see these two always called together.

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue [hunk 4]
```diff
@@ -232,14 +230,26 @@ const isVisualizationEnabled = computed({
...
+    !isVisualizationEnabled.value,
 )
 const isVisualizationVisible = computed(
   () => isVisualizationEnabled.value || isVisualizationPreviewed.value,
 )
+watch(isVisualizationVisible, (val) => {
+  if (!val) {
+    visualizationHovered.value = false
+  }
+})
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: It's strange this is needed; hiding visualization itself should emit "pointerleave", effectively setting visualizationHovered to false. Is this needed due to the modifiers problem? If yes, then add a comment here.

File: app/gui/src/project-view/composables/selection.ts [hunk 5]
```diff
@@ -237,6 +246,10 @@ function useSelectionImpl<T, PackedT>(
         if (packed) rawSelected.add(packed)
       }
     },
+    setSoleSelected: (element: T) => {
+      setSelection(new Set([element]))
+      onSoleSelected?.(element)
+    },
```
Comment (farmaazon) [inline app/gui/src/project-view/composables/selection.ts]: I think these names are a bit confusing. `setSoleSelected` technically should be the same as `setSelection` with a single node. But only the former calls `onSoleSelected`.

File: app/gui/src/project-view/util/autoBlur.ts [hunk 6]
```diff
@@ -138,3 +138,33 @@ function handleClick(
...
+ * Register a callback to be called when the window is blurred.
+ * The callback will be called when the window is blurred, and will be removed when the component is unmounted.
+ */
+export function onBlur(callback: () => void) {
+  blurHandlers.add(callback)
+  onUnmounted(() => {
+    blurHandlers.delete(callback)
+  })
+}
+
```
Comment (farmaazon) [inline app/gui/src/project-view/util/autoBlur.ts]: It's the same as `useEvent(window, 'blur')`, isn't it? Because `useEvent` also removes itself (on scope disposal, but it's effectively same as unmount).

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: Renamed to `onWindowBlur`, you are right.

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/GraphNode.vue:483]: `updateNodeHover` is used on its own once, though, on pointer move.

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue (hunk 4 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: Yeah, I wasn’t paying enough attention here. We’re not getting pointerleave for whatever reason. I just added a comment about it.

File: app/gui/src/project-view/composables/selection.ts (hunk 5 above)
Comment (vitvakatu) [reply app/gui/src/project-view/composables/selection.ts]: You are right, I removed `setSoleSelected`, `onSoleSelected` is now triggered if we pass a single element.

File: app/gui/src/project-view/util/autoBlur.ts (hunk 6 above)
Comment (vitvakatu) [reply app/gui/src/project-view/util/autoBlur.ts]: Yes, but here we have a single event handler per application instead of multiple event handlers per node. We use the same pattern for autoBlur, for performance reasons.

File: app/gui/src/project-view/components/GraphEditor/GraphEdges.vue (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/GraphEdges.vue]: I guess no particular reason, just reused the code from some other place. Changed it now as suggested.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/project-view/util/autoBlur.ts (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/project-view/util/autoBlur.ts]: Didn't know that handling a set of callbacks "by hand" is faster than multiple listeners (you may consider adding a note to someone as ill-informed as me)
