### PR TITLE
Native libraries from packages are not copied

### LINKED ISSUE #12557: Remove duplicated `.so` libraries from AppImage & other distributions
I've just tried [most recent AppImage](https://github.com/enso-org/enso/releases/tag/2025.1.1-nightly.2025.3.19) and it contains more than **120MB** in duplicated libraries. Steps to reproduce after download:
```bash
$ enso-linux-x86_64-2025.1.1-nightly.2025.2.26.AppImage --appimage-extract
$ find squashfs-root/ | grep "\.so$" | rev | cut -f1 -d / | rev | sort | uniq -cd
      2 libawt_headless.so
      2 libawt.so
      2 libawt_xawt.so
      2 libfontmanager.so
      2 libio_grpc_netty_shaded_netty_tcnative_linux_x86_64.so
      2 libio_grpc_netty_shaded_netty_transport_native_epoll_x86_64.so
      2 libjavajpeg.so
      2 libjava.so
      2 libjnidispatch.so
      2 libjsig.so
      2 libjvm.so
      2 liblcms.so
      2 libopencv_java470.so
      2 libtableauhyperapi.so
```
these libraries are duplicated because of 
- https://github.com/enso-org/enso/pull/11874#discussion_r1901474654

Time to remove the copying and _load dynamic libraries_ from the same location in both NI and JVM modes.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #12557

### Pull Request Description

Removes the copying of native libraries next to the generated NI binary. Native libraries of packages are loaded from the same location in both JVM and AOT modes.

**Old behavior:** [EnsoLibraryFeature](https://github.com/enso-org/enso/blob/7106fdd1cc32902554e7318e811d66e66cc6f3e4/engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java) copies all the native libraries within `**/polyglot/lib/**` next to the generated NI binary. The motivation for that is mentioned in the description of #11874.

**New behavior:** [EnsoLibraryFeature](https://github.com/enso-org/enso/blob/7106fdd1cc32902554e7318e811d66e66cc6f3e4/engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java) no longer copies native libraries. Instead, once a package is loaded in [DefaultPackageRepository.registerPackageInternal](https://github.com/enso-org/enso/blob/d369fcbe69f3eb1baa5fe7a5b8d24354b74067ad/engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala#L203-L247), paths to its native libraries are added to the native library search path via [NativeLibrarySearchPath](https://github.com/enso-org/enso/blob/9d8866944b145add67bbb944328ded1e3c4a3bba/engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java). Inspired by https://github.com/Akirathan/native-lib-loader.

### Important Notes

- In JVM mode, native libraries of packages are still loaded by [HostClassLoader.findLibrary](https://github.com/enso-org/enso/blob/7658faf64563ef25e8f04003892cfb074fd907c5/engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java#L86-L109).
- In AOT mode, [com.oracle.svm.core.jdk.NativeLibraries#usrPaths](https://github.com/oracle/graal/blob/91061cb6a151ffaa83e05f6852384537c2c85e6b/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NativeLibraries.java#L67) field is changed at runtime.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [X] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by Akirathan** [comment]
## Setting `java.library.path` system property does not work
In JVM mode, `java.library.path` system property is cached during bootstrap. Any subsequent change to the property is not reflected.

In AOT mode, `java.library.path` system property is cached in the first call to `System.loadLibrary`. If the property is changed before that call, it is reflected by SVM, but not after that.

**Conclusion:** Using `java.library.path` is not a good idea. It would work only if we could set all the path _before_ first call to `System.loadLibrary`. This is not possible - the first call to `System.loadLibrary` happens during parsing of enso modules. Changing the `java.llibrary.path` would happen once a Enso package is loaded.

**Comment by Akirathan** [comment]
## Setting `LD_LIBRARY_PATH` env var via native calls does not work

Trying to set `LD_LIBRARY_PATH` via something like:
```java
package org.mayfa.untitled.nativeenv;

import java.util.List;
import org.graalvm.nativeimage.c.CContext;
import org.graalvm.nativeimage.c.function.CFunction;
import org.graalvm.nativeimage.c.type.CCharPointer;
import org.graalvm.nativeimage.c.type.CTypeConversion;

@CContext(value = NativeEnv.Directives.class)
public final class NativeEnv {

  @CFunction
  static native int setenv(CCharPointer name, CCharPointer value, int overwrite);

  @CFunction
  static native CCharPointer getenv(CCharPointer name);

  public static void setEnv(String name, String value) {
    try (var namePtr = CTypeConversion.toCString(name);
        var valuePtr = CTypeConversion.toCString(value)) {
      var ret = setenv(namePtr.get(), valuePtr.get(), 1);
      if (ret != 0) {
        throw new AssertionError("Failed to set environment variable " + name + ", retcode = " + ret);
      }
    }
  }

  public static String getEnv(String name) {
    try (var namePtr = CTypeConversion.toCString(name)) {
      var ret = getenv(namePtr.get());
      if (ret.isNull()) {
        return null;
      }
      return CTypeConversion.toJavaString(ret);
    }
  }

  static final class Directives implements CContext.Directives {
    @Override
    public List<String> getHeaderFiles() {
      return List.of("<stdlib.h>");
    }
  }
}
```
suffers the same pitfall as [setting java.library.path system property](https://github.com/enso-org/enso/pull/13101#issuecomment-2890654922), i.e., if an attempt to find a native library is made _before_ `LD_LIBRARY_PATH` is set via `setenv` syscall, the subsequent changes to `LD_LIBRARY_PATH` env var are not reflected. Which is expected according to the POSIX standards.

**Comment by Akirathan** [comment]
After few discussions with @JaroslavTulach, I have arrived at a working solution demonstrated in https://github.com/Akirathan/native-lib-loader. Discussed also in [GraalVM Slack](https://graalvm.slack.com/archives/CN9KSFB40/p1747673077786669). This solution explicitly changes the [com.oracle.svm.core.jdk.NativeLibraries#usrPaths](https://github.com/oracle/graal/blob/91061cb6a151ffaa83e05f6852384537c2c85e6b/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NativeLibraries.java#L67) field at runtime.

Now, it is time to integrate this idea into Enso.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/Akirathan/native-lib-loader">GitHub - Akirathan/native-lib-loader: Simple project demonstrating how to change the native library search path at runtime.</a></strong></div><div>Simple project demonstrating how to change the native library search path at runtime. - Akirathan/native-lib-loader</div></blockquote>

**Comment by Akirathan** [comment]
I have downloaded the `built-distribution` artifact from https://github.com/enso-org/enso/actions/runs/15169686252/job/42689718870#step:12:100 and ensured that there is no relevant native library next to the generated binary:
```
$ ls -l built-distribution/enso-engine-2025.2.1-dev-linux-amd64/enso-2025.2.1-dev/bin/
total 487M
-rwxr-xr-x 1 pavel pavel 486M May 21 20:32 enso
-rw-r--r-- 1 pavel pavel 1.1M May 21 20:29 libsqlitejdbc.so
```
(`libsqlitejdbc.so` is not comming from any std lib native libs)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Native libraries from packages are not copied · enso-org/enso@9d88669</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Native libraries from packages are not copied · enso-org/enso@9d88669</div></blockquote>

**Comment by JaroslavTulach** [comment]
> ... solution demonstrated in https://github.com/Akirathan/native-lib-loader. ... explicitly changes the [com.oracle.svm.core.jdk.NativeLibraries#usrPaths](https://github.com/oracle/graal/blob/91061cb6a151ffaa83e05f6852384537c2c85e6b/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NativeLibraries.java#L67) field at runtime.

- The tough part is to guarantee this trick works in future versions of _native image_
- This would be an interesting library to publish at Maven Central
   - assuming the GraalVM guys don't want the functionality into GraalVM itself
   - assuming there is a way to guarantee it would work in the future
- The project would need nicer API
   - `NativeLibLoader.loadLibrary(String library, String... searchPaths)` maybe?
- the `main` method doesn't need to be public, I think
- or the `main` method needn't be there at all
- better to have some unit tests using standard _native image_ JUnit support

Just an idea for the long term sustainability vision. In any case I am glad you got it working with `MethodHandle`s!

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+   * @param path Directory to add to the search path.
+   */
+  public static void addToSearchPath(String path) {
+    if (ImageInfo.inImageRuntimeCode()) {
+      assert Files.isDirectory(Path.of(path));
+      addPath(path);
+    }
+  }
+
+  public static String[] getSearchPath() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java]: - Only used for debug logging... 
- not really needed otherwise, so I prefer to remove it
- if really necessary consider `addToSearchPath(path, Consumer<String> logger)`

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+  static final Object nativeLibsInstance = null;
+
+  /**
+   * Adds the given {@code path} directory to the search path for native libraries. Semantically, it
+   * is equivalent to changing the {@code java.library.path} system property. Only works in Native
+   * Image.
+   *
+   * @param path Directory to add to the search path.
+   */
+  public static void addToSearchPath(String path) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java:43]: Why not use a real type like `Path`?

File: engine/runtime/src/main/java/module-info.java [hunk 3]
```diff
@@ -28,6 +28,7 @@
   requires org.apache.tika.core;
   requires org.slf4j;
   requires org.graalvm.collections;
+  requires org.graalvm.nativeimage;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/module-info.java:31]: Maybe just:
```suggestion
  requires static org.graalvm.nativeimage;
```

File: engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java [hunk 4]
```diff
@@ -106,15 +84,6 @@ public void beforeAnalysis(BeforeAnalysisAccess access) {
               }
             }
           }
-          if (pkg.nativeLibraryDir().exists()) {
-            var nativeLibs =
-                NativeLibraryFinder.listAllNativeLibraries(pkg, FileSystem$.MODULE$.defaultFs());
-            for (var nativeLib : nativeLibs) {
-              var out = new File(nativeLibDir, nativeLib.getName());
-              Files.copy(nativeLib.toPath(), out.toPath(), StandardCopyOption.REPLACE_EXISTING);
```
Comment (JaroslavTulach) [inline engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java:114]: Heuréka, if the system continues to work even after removing these copies!

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java:43]: The only callsite uses `TruffleFile`. Better `String` than `TruffleFile`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java]: Removed in 041293cc35f62623f70c927b5185a76a7b713186

File: engine/runtime/src/main/java/module-info.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/module-info.java:31]: There are calls to `org.graalvm.nativeimage.ImageInfo#inImageRuntimeCode` in `org.enso.runtime` module.
