### PR TITLE
Fix #6287: wrong nested breadcrumb ordering

### LINKED ISSUE #6287: Bredcrumbs ordering issue (multiple of the same func displayed)
### Discord username

_No response_

### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Bredcrumbs behavior is sometimes unpredictable resulting in such path:
Project name -> Func1 -> Func2 -> Func1

can be observed here in 0:43:

https://user-images.githubusercontent.com/108271897/232108863-c3825d74-c1d0-4d72-bbd4-bd6b18b50e2c.mp4

### Expected behaviour

Not having 2 Func1 breadcrumbs placed in the path but rather going back and forth with navigation

### How we can reproduce it?

See attached video file.

### Screenshots or screencasts

_No response_

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Fixes #6287. When selecting a nested breadcrumb, a race condition would happen: all new breadcrumbs were being added in a separately spawned task whose execution was thus indeterministic.

https://github.com/enso-org/enso/assets/607786/73734805-292d-42ce-b08a-060a987d99bb

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/controller/graph/executed.rs [hunk 1]
```diff
@@ -216,28 +216,30 @@ impl Handle {
...
-    /// This will cause pushing a new stack frame to the execution context and changing the graph
-    /// controller to point to a new definition.
+    /// This will push new stack frames to the execution context and change the graph controller to
+    /// point to a new definition.
     ///
     /// ### Errors
     /// - Fails if method graph cannot be created (see `graph_for_method` documentation).
     /// - Fails if the project is in read-only mode.
-    pub async fn enter_method_pointer(&self, local_call: &LocalCall) -> FallibleResult {
+    pub async fn enter_stack(&self, stack: Vec<LocalCall>) -> FallibleResult {
```
Comment (vitvakatu) [inline app/gui/src/controller/graph/executed.rs:229]: Can we accept `&[LocalCall]` instead of Vec?

File: app/gui/src/presenter/graph/call_stack.rs [hunk 2]
```diff
@@ -61,70 +112,34 @@ impl Model {
...
+            }
         }
     }
 
-    fn add_breadcrumb_in_view(&self, frame: LocalCall) {
-        let definition = frame.definition.clone().into();
-        let call = frame.call;
-        let local_call = view::graph_editor::LocalCall { call, definition };
-        self.view.model.breadcrumbs.push_breadcrumb(local_call);
+    fn add_breadcrumbs_in_view(&self, stack: Vec<LocalCall>) {
```
Comment (vitvakatu) [inline app/gui/src/presenter/graph/call_stack.rs:134]: Same here.

File: app/gui/src/controller/graph/executed.rs (hunk 1 above)
Comment (Procrat) [reply app/gui/src/controller/graph/executed.rs:229]: I don't think so. We need an owned version both for pushing them to the stack in the model and for the notification back to the view.

In case you already realised that and were wondering about doing an extra `clone` here instead of at the call site, I'm trying to follow [this pattern](https://rust-lang.github.io/api-guidelines/flexibility.html#caller-decides-where-to-copy-and-place-data-c-caller-control) which helps make it clear when cloning is happening.

File: app/gui/src/controller/graph/executed.rs [hunk 3]
```diff
@@ -216,28 +216,30 @@ impl Handle {
...
-            let method_ptr = &local_call.definition;
-            let graph = controller::Graph::new_method(&self.project, method_ptr);
-            let graph = graph.await?;
-            self.execution_ctx.push(local_call.clone()).await?;
-            debug!("Replacing graph with {graph:?}.");
-            self.graph.replace(graph);
-            debug!("Sending graph invalidation signal.");
-            self.notifier.publish(Notification::EnteredNode(local_call.clone())).await;
-
+            for local_call in stack.clone() {
```
Comment (wdanilo) [inline app/gui/src/controller/graph/executed.rs]: Why do we need to clone the stack here?

File: app/gui/src/controller/graph/executed.rs (hunk 1 above)
Comment (wdanilo) [reply app/gui/src/controller/graph/executed.rs:229]: If we definitely need an owned version of vector inside, and we would be cloning it nevertheless if was provided as a slice, then yes, API telling explicitly about it is better.

File: app/gui/src/controller/graph/executed.rs [hunk 4]
```diff
@@ -216,28 +216,30 @@ impl Handle {
...
+                debug!("Entering node {}.", local_call.call);
+                self.execution_ctx.push(local_call).await?;
+            }
+            if let Some(inner_call) = stack.last() {
+                let graph =
+                    controller::Graph::new_method(&self.project, &inner_call.definition).await?;
+                debug!("Replacing graph with {graph:?}.");
```
Comment (wdanilo) [inline app/gui/src/controller/graph/executed.rs:247]: How big this debtg info can be? How big is the `{graph:?}` print?

File: app/gui/view/graph-editor/src/component/breadcrumbs.rs [hunk 5]
```diff
@@ -53,31 +53,19 @@ const TEXT_Y_OFFSET: f32 = 2.0;
...
-        /// the breadcrumb being pushed, any existing breadcrumb following the currently selected
-        /// breadcrumb is removed from the panel.
-        push_breadcrumb             (Option<LocalCall>),
-        /// Pops the selected breadcrumb.
-        pop_breadcrumb              (),
+        /// Pushes new breadcrumbs after the selected breadcrumb. Any breadcrumbs that are already
+        /// part of the stack are ignored. If the next breadcrumb isn't part of the breadcrumbs
+        /// being pushed, any existing breadcrumb following the currently selected breadcrumb is
+        /// removed from the panel.
+        push_breadcrumbs            (Vec<LocalCall>),
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/breadcrumbs.rs:66]: Do not use `Vec` in FRP API, this will clone it on every event, which can affect performance. Use `ImVec` (I think we have somewhere `ImVec` = `Rc<Vec<..>>`

File: app/gui/view/graph-editor/src/component/breadcrumbs.rs [hunk 6]
```diff
@@ -489,24 +474,27 @@ impl Breadcrumbs {
             frp.select_breadcrumb <+ model.project_name.frp.output.mouse_down.constant(0);
             model.project_name.frp.outside_press <+ frp.outside_press;
 
-            popped_count <= frp.output.breadcrumb_select.map(|selected| (0..selected.0).collect_vec());
-            local_calls  <= frp.output.breadcrumb_select.map(|selected| selected.1.clone());
-            frp.source.breadcrumb_pop <+ popped_count.constant(());
-            frp.source.breadcrumb_push <+ local_calls;
+            breadcrumbs_to_pop_count <- frp.output.breadcrumb_select.filter_map(|(pop_count, _)|
+                if *pop_count > 0 { Some(*pop_count) } else { None }
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/breadcrumbs.rs]: use `as_some`

File: app/gui/view/graph-editor/src/component/breadcrumbs.rs [hunk 7]
```diff
@@ -489,24 +474,27 @@ impl Breadcrumbs {
...
+            );
+            breadcrumbs_to_push <- frp.output.breadcrumb_select.filter_map(|(_, breadcrumbs_to_push)|
+                if !breadcrumbs_to_push.is_empty() {
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/breadcrumbs.rs]: use `as_some_from`

**Review by wdanilo — APPROVED** [review]
I'd also like someone who was implementing breadcrumb stack traversal to review this PR. I don't know how it was working and someone who implemented it would be the best person to check the new implementation.

File: app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs [hunk 8]
```diff
@@ -116,6 +115,18 @@ mod separator {
 
 
 
+// ========================
+// === RelativePosition ===
+// ========================
+
+#[derive(Debug, Clone, Copy)]
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs:124]: Docs needed. It's not obvious where this thing is used and what it is used for.

File: app/gui/src/controller/graph/executed.rs [hunk 9]
```diff
@@ -216,28 +216,30 @@ impl Handle {
...
+                self.graph.replace(graph);
+                debug!("Sending graph invalidation signal.");
+                self.notifier.publish(Notification::EnteredStack(stack)).await;
+            }
```
Comment (farmaazon) [inline app/gui/src/controller/graph/executed.rs]: We should be more careful when handling errors here.

Before, when we successfully pushed only some of the stack frames, we left a consistent state, where the engine and controllers state reflected the crumbs and graph in view.

Now, in such situation we just do an early return (due to `?`) without updating graph, but leaving some stack applied.

So let's stop pushing new frames in the controller on first error, but then update the view to reflect the successfully pushed frames.

File: app/gui/src/controller/graph/executed.rs [hunk 10]
```diff
@@ -255,21 +257,23 @@ impl Handle {
...
-            let frame = self.execution_ctx.pop().await?;
+            for _ in 0..frame_count {
+                self.execution_ctx.pop().await?;
+            }
             let method = self.execution_ctx.current_method();
             let graph = controller::Graph::new_method(&self.project, &method).await?;
             self.graph.replace(graph);
-            self.notifier.publish(Notification::SteppedOutOfNode(frame.call)).await;
+            self.notifier.publish(Notification::ExitedStack(frame_count)).await;
             Ok(())
```
Comment (farmaazon) [inline app/gui/src/controller/graph/executed.rs]: Same concerns as above.

**Review by farmaazon — CHANGES_REQUESTED** [review]

File: app/gui/src/presenter/graph/call_stack.rs (hunk 2 above)
Comment (Procrat) [reply app/gui/src/presenter/graph/call_stack.rs:134]: The `call` is an expression ID, which is `Copy`, but the definition (`MethodPointer`) isn't, so taking by reference would require a `clone` in this function, I think.

File: app/gui/src/controller/graph/executed.rs (hunk 3 above)
Comment (Procrat) [reply app/gui/src/controller/graph/executed.rs]: Because the stack is also passed on later later in this function to the notification back to the view (so we know which breadcrumbs to add).

File: app/gui/src/controller/graph/executed.rs (hunk 4 above)
Comment (Procrat) [reply app/gui/src/controller/graph/executed.rs:247]: No idea, this is old code.

File: app/gui/view/graph-editor/src/component/breadcrumbs.rs (hunk 5 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/component/breadcrumbs.rs:66]: Hmm, I can't seem to find that anywhere in the code. Where is it?

File: app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs (hunk 8 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs:124]: I just moved it to a more logical place, but I'll try to add some docs based on my understanding of its meaning.

File: app/gui/src/controller/graph/executed.rs (hunk 9 above)
Comment (Procrat) [reply app/gui/src/controller/graph/executed.rs]: Wow, well spotted! Thanks for the thorough review! I'll change it.

File: app/gui/src/controller/graph/executed.rs [hunk 11]
```diff
@@ -267,14 +274,22 @@ impl Handle {
...
+            let mut successful_pop_count = 0;
+            let mut result = Ok(());
             for _ in 0..frame_count {
-                self.execution_ctx.pop().await?;
+                if let Err(error) = self.execution_ctx.pop().await {
+                    result = Err(error);
+                    break;
+                }
+                successful_pop_count += 1;
             }
```
Comment (farmaazon) [inline app/gui/src/controller/graph/executed.rs]: I would rewrite it to `take_while(...).count()` so we avoid early returns from loop and one mutable variable.

File: app/gui/src/controller/graph/executed.rs [hunk 12]
```diff
@@ -228,19 +228,26 @@ impl Handle {
...
+            let mut successful_calls = Vec::new();
+            let mut result = Ok(());
+            for local_call in stack {
                 debug!("Entering node {}.", local_call.call);
-                self.execution_ctx.push(local_call).await?;
+                if let Err(error) = self.execution_ctx.push(local_call.clone()).await {
+                    result = Err(error);
+                    break;
+                }
+                successful_calls.push(local_call);
```
Comment (farmaazon) [inline app/gui/src/controller/graph/executed.rs]: Here as well, `take_while(...).collect_vec()`may be a bit more readable as we can make one variable immutable + one early return from loop is removed.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/controller/graph/executed.rs (hunk 11 above)
Comment (Procrat) [reply app/gui/src/controller/graph/executed.rs]: Discussed it in private with @farmaazon and rewrote it using the `Stream`/`TryStream` API.

**Comment by vitvakatu** [comment]
Oh damn, I posted a comment in the issue. QA 🟢
