### PR TITLE
Proper dropdown active area and arrow placement

### LINKED ISSUE #7423: Wrong placement of drop-downs
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/f3de6cb6-2fae-453a-b7ef-a7e42d3828e8

### Expected behavior

Drop-downs should be rendered in correct positions:
* Drop-down for "join_kind" should appear when hovering "join_kind" name, even when any value is picked.
* When value is picked, the drop-down should be displayed under the constructor (first segment of prefix chain).

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 28.07

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #7423

Refactored widget matching algorithm to allow creating wrapper widgets even in cases where the widget config override is present. That allowed the widgets to be reordered, such that the argument name ends up being inside the dropdown widget. That way clicking it opens the dropdown.

Added explicit manual layout for the dropdown arrow position. Now it is positioned on the center of a selected appropriate child widget. For prefix chains, the leftmost part of the prefix application (the method or constructor) is selected.

https://github.com/enso-org/enso/assets/919491/86678b9d-c04e-4545-8d11-2d1e85b9b951

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 1]
```diff
@@ -1624,17 +1654,27 @@ impl<'a> TreeBuilder<'a> {
...
+        // Note that the override can still be rejected if there is an available higher priority
+        // applicable widget that defines [`SpanWidget::QUERY_ON_OVERRIDE`] as `true` in its
+        // implementation. In that case, it is expected that the forcing widget will declare a child
+        // using the same span-tree node, so that the override can eventually be applied anyway.
+
+        let allowed_configs = !ptr_usage.disallowed_kinds;
         let parent_extensions_len = self.extensions.len();
 
+        // TODO: We always use `main_nodes` here right now, as widgets are never visible when the
+        // node in edit mode. Once this changes, we will need to use conditionally use `edit_nodes`.
```
Comment (vitvakatu) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]:
```suggestion
        // node is in the edit mode. Once this changes, we will need to use `edited_nodes` conditionally.
```

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 2]
```diff
@@ -165,6 +166,11 @@ pub struct OverrideKey {
 pub trait SpanWidget: display::Object {
     /// Configuration associated with specific widget variant.
     type Config: Debug + Clone + PartialEq;
+    /// Declare whether this widget should be considered for creation despite a config override
+    /// being present. Widgets that declare `true` here should always create a child widget on
+    /// the same span-tree node, so that the override can eventually be applied to it. Only widgets
+    /// declared before the widget selected by override will take priority over it.
+    const QUERY_ON_OVERRIDE: bool = false;
```
Comment (vitvakatu) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]: I don't understand the last sentence. They will take priority over what? What are the consequences of taking priority?
Also, the working of the second sentence is also confusing. I suggest to slightly rewrite it as follows:
```
Widgets that declare `true` here must create a child widget on the same span-tree node, so that the override can be applied to this child instead.
```

File: app/gui/view/graph-editor/src/component/node/input/widget.rs [hunk 3]
```diff
@@ -269,40 +275,54 @@ macro_rules! define_widget_modules(
...
             /// Return a single flag that determines the used widget kind.
-            fn flag(&self) -> DynKindFlags {
+            fn flag(&self) -> KindFlags {
                 match self {
-                    $(DynConfig::$name(_) => DynKindFlags::$name,)*
+                    $(DynConfig::$name(_) => KindFlags::$name,)*
                 }
             }
+
+            /// Return a bitfield that determines which widget kinds needs to be checked for a match
```
Comment (vitvakatu) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs]:
```suggestion
            /// Return a bitfield that determines which widget kinds need to be checked for a match
```

File: app/gui/view/graph-editor/src/component/node/input/widget/separator.rs [hunk 4]
```diff
@@ -98,9 +93,11 @@ impl SpanWidget for Widget {
             let _name_node = child_iter.next();
             let _token = child_iter.next();
             let Some(arg_node) = child_iter.next() else { return };
-            ctx.builder.child_widget_of_type(arg_node, level, child_config)
+            // make sure to not create another layer of separator for that nested node.
```
Comment (vitvakatu) [inline app/gui/view/graph-editor/src/component/node/input/widget/separator.rs]:
```suggestion
            // Make sure to not create another layer of separator for that nested node.
```

File: app/gui/view/graph-editor/src/component/node/input/widget.rs
Comment (vitvakatu) [inline app/gui/view/graph-editor/src/component/node/input/widget.rs:1]: Shouldn't we also modify the `Widget Configuration` section in the module documentation, to mention this `QUERY_ON_OVERRIDE` const?

**Review by vitvakatu — APPROVED** [review]
I'm not much familiar with the code, but after reading it and the docs carefully I even understood most of the things there! Nice job with it. A few minor nitpicks.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs (hunk 2 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs]: I've added more docs explaining the implicit ordering and where it is defined.

File: app/gui/view/graph-editor/src/component/node/input/widget.rs
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget.rs:1]: Indeed, I've added a section there. Also changed the const name to `PRIORITY_OVER_OVERRIDE`, since the old one didn't really make any sense. The `query` word in never otherwise used in this context.

**Comment by MichaelMauderer** [comment]
QA: :green_circle:
