### PR TITLE
Ensure slow shutdown of LS always kicks off hooks

### LINKED ISSUE #6515: Project folder renaming stopped working
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Renaming of folders stopped working:
image

### Expected behaviour

Folder to be named after the project name

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

This change fixes the rather elusive bug where shutdown hooks could not be fired when shutdown was taking too long and termination was forced.

Under the circumstances described in detail in ticket #6515 there was a small chance that we could have a shutdown race condition. Essentially the messages received when client was disconnected and language server forced the termination could lead to language server not sending the public `ProjectClosed` message which triggers shutdown hook. Now we always do.

Also made sure that multiple `ProjectClosed` messages don't lead to firing multiple shutdown hooks, which was another possibility.

No tests as one would have to be able to introduce different delays in various message handlers to simulate the problem.
Having ability to do such chaos testing would be nice but it is beyond the scope of this ticket. 
I was able to reproduce the problem 100% with my specially crafted setup so I'm fairly confident about the change.

Closes #6515.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerKiller.scala [hunk 1]
```diff
@@ -63,7 +67,13 @@ class LanguageServerKiller(
       }
 
     case KillTimeout =>
-      liveControllers.foreach(_ ! PoisonPill)
+      logger.warn(
+        s"Not all language servers' controllers finished on time. Forcing termination."
+      )
+      liveControllers.foreach { case (actorRef, projectId) =>
+        actorRef ! PoisonPill
+        context.system.eventStream.publish(ProjectClosed(projectId))
```
Comment (hubertp) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerKiller.scala:75]: If one was to reduce this fix to a single line, then this is it.

**Review by JaroslavTulach — APPROVED** [review]
From my high level Akka perspective the change makes sense and your conclusions seem valid.

**Review by 4e6 — APPROVED** [review]
