### PR TITLE
do not activate nested dropdowns together

### LINKED ISSUE #6825: Click a constructor field drop down makes both the field and constructor drop down open
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/c8cfd5e2-b7d3-48cc-a031-bc381d747ffc

### Expected behaviour

Just selected drop down should be opened

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 24.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #6825

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs [hunk 1]
```diff
@@ -192,7 +192,7 @@ impl Widget {
 
     fn init_dropdown_focus(&self, ctx: &super::ConfigContext) -> frp::Stream<bool> {
         let widgets_frp = ctx.frp();
-        let focus_receiver = self.display_object.clone_ref();
+        let focus_receiver = self.dropdown_wrapper.clone_ref();
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs]: Is the clone necessary?

**Review by kazcw — APPROVED** [review]

File: app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs (hunk 1 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs]: No, good catch :)
