### PR TITLE
Replace language server WebSocket connection with Ydoc

### LINKED ISSUE #14142: Avoid networking layer of Akka by `ydoc-server` talking directly to the engine+ls
### Related Prior Work
 
- now when #13178 has been integrated
- #5419 was dreaming about:
  - using Helidon to implement network communication
  - writing Language Server in JavaScript
- since #10783 & co. Helidon can be used for `WebSocket` emulation
- discussion about [using Y.js to simulate duplex network communication](https://discord.com/channels/401396655599124480/1425766988839653377/1425770149683789946)

### Task 1: Avoid two WebSocket Connections

- modify IDE & `ydoc-shared` code
- avoid IDE creating two `WebSocket` connections (one to `ydoc-server` another to language server_)
- let IDE connect to `ydoc-server` only and ...
- ... "send messages" by adding them to FIFO Y.js queue
- let the `ydoc-server` distribute these messages to language server
- sketch of necessary changes: [Connect MainModule.scala and languageServer.ts so they can all to each other](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:YdocDirect)

### Task 2: Ydoc Server Talks to Language Server Directly

- with #13178 the Ydoc server no longer has to send network messages
- but it can make direct calls into _language server_
- by doing so we can eliminate the _network Akka_ layer

### Future Work: Less Messages

- as @farmaazon puts it:
- _we could do even better. Many endpoints are for altering some state managed by LS (execution context, file contents...). We should just update structures representing that state._
- all that's going to be enabled once we finish tasks 1 and 2

### LINKED ISSUE #14746: akka.stream.BufferOverflowException: Buffer overflow (max capacity was: 100)!
- Following has appeared in a log that starts with `Initializing main module of the Language Server from [2026.1.1-nightly.2026.2.10`...
- is there an easy way to configure Akka to not throw this error?

```
[ERROR] [2026-02-10T09:20:53.004] [akka.actor.ActorSystemImpl] Websocket handler failed with Buffer overflow (max capacity was: 100)!
akka.stream.BufferOverflowException: Buffer overflow (max capacity was: 100)!
	at akka.stream.impl.ActorRefSource$$anon$1.$anonfun$ref$1(ActorRefSource.scala:115)
	at akka.stream.impl.ActorRefSource$$anon$1.$anonfun$ref$1$adapted(ActorRefSource.scala:55)
	at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:240)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1(GraphStage.scala:201)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1$adapted(GraphStage.scala:201)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:467)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:517)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base@25.0.1/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base@25.0.1/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base@25.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base@25.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
[ERROR] [2026-02-10T09:20:53.112] [org.enso.languageserver.protocol.binary.BinaryConnectionController] An error occurred during processing web socket connection [127.0.0.1:56741].
akka.http.scaladsl.model.ws.PeerClosedConnectionException: Peer closed connection with code 1011 'internal error'
	at akka.http.impl.engine.ws.WebSocket$PrepareForUserHandler$$anon$1.onPush(WebSocket.scala:116)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base@25.0.1/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base@25.0.1/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base@25.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base@25.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
```

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

- close #14142

PR replaces binary and JSON-RPC WebSockets with Yjs based communication.

```
+------------------+                +--------------------------------------------------------------+
|                  |                |                                                              |
| +--------------+ |    WebSocket   | +-----------------+   YjsChannel.Server  +-----------------+ |
| |  IDE Client  | |<-------------->| |  Ydoc Server    |<-------------------->| Language Server | |
| +--------------+ |                | +-----------------+                      +-----------------+ |
|     Electron     |                |                         GraalVM                              |
+------------------+                +--------------------------------------------------------------+
```

Workflow:
- IDE client creates a `YjsChannel` backed by Yjs `Y.Array` allowing bidirectional message passing
- IDE client connects to the Ydoc server using the [Yjs WebSocket provider](https://docs.yjs.dev/ecosystem/connection-provider/y-websocket)
- Ydoc server creates a corresponding `YjsChannel` that is synchronized with the client's channel and passes it to the Language server via `YjsChannelCallbacks` callback

This way IDE client and the Language Server establish `YjsChannel` connection and start exchanging messages.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: lib/java/ydoc-api/src/main/java/module-info.java [hunk 1]
```diff
@@ -0,0 +1,3 @@
+module org.enso.ydoc.api {
+  exports org.enso.ydoc.api;
```
Comment (JaroslavTulach) [inline lib/java/ydoc-api/src/main/java/module-info.java:2]: - There is no need for a new API module.
- there already is [YdocServerApi](https://github.com/enso-org/enso/pull/14438/files#diff-0803ce07fcddab22935457df18ed5ecbb770e7fe0b26b00117e5d2c370f752a8L7)
- please put the new interfaces there as inner classes of `YdocServerApi`.

File: lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/NoOpMessageCallbacks.java [hunk 2]
```diff
@@ -0,0 +1,13 @@
+package org.enso.ydoc.api;
+
+public class NoOpMessageCallbacks implements MessageCallbacks {
+  public static final NoOpMessageCallbacks INSTANCE = new NoOpMessageCallbacks();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/NoOpMessageCallbacks.java]: - Please don't put `NoOpMessagesCallbacks` implementation class into the API
- remove it
- if you have to have it, then encapsulate it
- put `public static final MessageCallbacks NO_OP` into `MessageCallbacks`  and make the implementation class package private

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 3]
```diff
@@ -67,6 +69,11 @@ public Builder parser(ParserPolyfill parser) {
       return this;
     }
 
+    public Builder hostAccessBuilder(HostAccess.Builder hostAccessBuilder) {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: - Why is this a builder? 
- Isn't just `HostAccess` instance good enough?

```suggestion
    public Builder hostAccess(HostAccess hostAccessBuilder) {
```

- without `WebEnvironment.defaultHostAccess` being public, one might need a builder
- but having both builder and `WebEnvironment.defaultHostAccess` seems unnecessary

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java [hunk 4]
```diff
@@ -54,10 +57,18 @@ public static AutoCloseable launch(String ydocHost, String ydocPort, MessageCall
       if (callbacks != null) {
         builder.callbacks(callbacks);
       }
+      var hostAccess =
+          WebEnvironment.defaultHostAccess
+              // allowImplementations is required to call methods on JS objects from Java, i.e. to
+              // call methods on `YjsChannel` object returned from JS
+              .allowImplementations(YjsChannel.class)
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java]: - allowing implementation of a well known interface is OK
- but opening up `allowAccess` to a random `callbacks.getClass()` class is a security flaw
- please create a proxy around `callbacks` and expose its methods 
   - preferrably via `@HostAccess.Explicit`
   - or via `allowAccess(ProxyMessageCallbacks.getDeclararedMethod(""))` but while hardcoding `ProxyMessageCallbacks` class

File: lib/java/ydoc-api/src/main/java/module-info.java (hunk 1 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-api/src/main/java/module-info.java:2]: - Possibly you can move `YdocServerApi` to the new `org.enso.ydoc.api` module.
- but the whole API needs to be co-located

**Review by JaroslavTulach — COMMENTED** [review]
- ideally `HostAccess` is configured internally
- and both tests and production code _just work_ with the default configuration
- possible trick to achieve that is to crate a proxy around interfaces passed to JavaScript

File: lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/YdocJsonRpcServer.scala [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+          new OutgoingMessageHandler(channel)
+        )
+      )
+      incomingMessageHandler ! MessageHandler.Connected(outgoingMessageHandler)
+    }
+
+    override def onMessage(message: Object): Unit = {
+      message match {
+        case m: String =>
+          val webMessage = MessageHandler.WebMessage(m)
```
Comment (JaroslavTulach) [inline lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/YdocJsonRpcServer.scala:129]: - @4e6 you mentioned last week that the Java part of this PR was _"suprisingly simple"_
- the change looks really small
   - it took me a while to locate where the essential Java part is 
- if this `ServerCallbacks` in `YdocJsonRpcServer` is all that's needed then I agree, yes, it seems surprisingly simple

File: app/ydoc-channel/src/YjsChannel.ts [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+
+    this.observeHandler = (event: Y.YArrayEvent<ChannelMessage<T>>) => {
+      // Process all added items
+      for (const delta of event.changes.delta) {
+        if (delta.insert) {
+          const items = Array.isArray(delta.insert) ? delta.insert : [delta.insert]
+          for (const item of items) {
+            // Only notify handlers if the message is from another sender
+            if (item.senderId !== this.senderId) {
+              this.notifyHandlers(item.payload)
```
Comment (JaroslavTulach) [inline app/ydoc-channel/src/YjsChannel.ts]: - As of 8713e6fcc7cdd6848b0756ade07e8a93da27c792 we are probably dealing with _ever growing_ `Y.Array`
- somehow we need to find out that the _"message has been delivered"_ to all handlers
   - that's kind of hard in a distributed framework
   - where handlers can appear and diappear
- one solution would be to add `receiverId` to `item` 
   - deliver the message only when `senderId` matches `receiverId`
   - e.g. `if (item.receiverId === this.senderId`)`
   - if there was _only one receiver_ of a message
   - then it'd be the receiver's responsibility to remove the `item` from `array`

File: app/ydoc-channel/src/YjsChannel.ts [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+   * Called when the channel is connected and ready to use.
+   * @param channel - The connected YjsChannel instance
+   */
+  onConnect(channel: YjsChannel<T>): void
+}
+
+/**
+ * A bidirectional communication channel backed by Y.Array.
+ *
+ * This class allows multiple parties to send and receive messages through a shared
```
Comment (JaroslavTulach) [inline app/ydoc-channel/src/YjsChannel.ts]: - really "multiple parties"?
- shouldn't the `YjsChannel` be just bidirectional?

File: app/ydoc-shared/src/util/net/__tests__/YjsTransport.test.ts [hunk 8]
```diff
@@ -0,0 +1,236 @@
...
+      jsonrpc: '2.0',
+      method,
+      ...(params === undefined ? { params: null } : { params }),
+    },
+  }
+}
+
+// Polyfill DOM event types for Node.js environment
+if (typeof globalThis.CloseEvent === 'undefined') {
+  ;(globalThis as any).CloseEvent = class CloseEvent extends Event {
```
Comment (JaroslavTulach) [inline app/ydoc-shared/src/util/net/__tests__/YjsTransport.test.ts:20]: Line prefixed by `;`?
```suggestion
  (globalThis as any).CloseEvent = class CloseEvent extends Event {
```

File: lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/YdocServerApi.java [hunk 9]
```diff
@@ -3,19 +3,23 @@
 import java.io.IOException;
 import java.net.URISyntaxException;
 import java.util.ServiceLoader;
+import org.enso.ydoc.api.MessageCallbacks;
 
 public abstract class YdocServerApi {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/YdocServerApi.java:7]: Why don't we put `YdocServerApi` into `org.enso.ydoc.api` module as well? As [this comment](https://github.com/enso-org/enso/pull/14438/files#r2605389264) suggests?

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+  public final class TestCallbacks implements MessageCallbacks {
+
+    private Consumer<YjsChannel> handler;
+
+    public TestCallbacks(Consumer<YjsChannel> handler) {
+      this.handler = handler;
+    }
+
+    @Override
+    public void onConnect(YjsChannel channel) {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java:29]:
```suggestion
    @Override
    @HostAccess.Export
    public void onConnect(YjsChannel channel) {
```

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+
+    var hostAccess =
+        WebEnvironment.defaultHostAccess
+            // allowImplementations is required to call methods on JS objects from Java,
+            // i.e. to call `YjsChannel::send` in the `TestCallbacks::onConnect` method
+            .allowImplementations(YjsChannel.class)
+            // public access is required to recognize Java lambdas passed to
+            // `YjsChannel::subscribe` method as JS functions.
+            .allowPublicAccess(true)
+            .allowAccess(TestCallbacks.class.getDeclaredMethod("onConnect", YjsChannel.class))
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java:46]:
```suggestion
            // no need for TestCallbacks registration
```
rather use `@HostAccess.Explicit`

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java [hunk 12]
```diff
@@ -0,0 +1,107 @@
...
+
+  @After
+  public void tearDown() throws InterruptedException {
+    super.tearDown();
+    context.close();
+  }
+
+  @Test
+  public void onConnectSend() throws Exception {
+    var res = new AtomicReference<>();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/api/CallbacksTest.java:62]: - I'd slightly prefer you to create `CountingTest` class and register its instance instead
- annotate its `set` method with `@HostAccess.Explicit`

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java [hunk 13]
```diff
@@ -25,21 +28,22 @@ public static void main(String[] args) throws Exception {
       var then = System.currentTimeMillis();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java]: - Is this `public static void main` still useful for anything?
- Shouldn't it be removed?

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java (hunk 4 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java]: The current state with:
```
.allowImplementations(YjsChannel.class)
.allowPublicAccess(true);
```
is certainly better than the original one. Thanks.

Still, it be good to remove `.allowPublicAccess(true)` and use `@HostAccess.Explicit` annotation instead.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 14]
```diff
@@ -135,6 +173,7 @@ public void start() throws ExecutionException, InterruptedException, IOException
                   var bindings = ctx.getBindings("js");
                   bindings.putMember("YDOC_HOST", hostname);
                   bindings.putMember("YDOC_PORT", port);
+                  bindings.putMember("YDOC_MESSAGE_CALLBACKS", callbacks);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: - registering non-primitive type as global symbol seems strange
- with `YDOC_HOST` one could post it as environment variable, but 
- one cannot register `callbacks` via environment variable
- why don't [create a initializeYdocServer function](https://github.com/enso-org/enso/pull/14438#discussion_r2651069134)
- and call it here directly with proper arguments?

File: app/ydoc-server-polyglot/src/main.ts [hunk 15]
```diff
@@ -6,14 +6,18 @@ const debug = typeof YDOC_LS_DEBUG != 'undefined'
 
 configureAllDebugLogs(debug)
 
+if (YDOC_MESSAGE_CALLBACKS == undefined) {
```
Comment (JaroslavTulach) [inline app/ydoc-server-polyglot/src/main.ts]: - this check makes `main.ts` unusable from command line
   - at least I believe usage from CLI was the motivation for these `YDOC_` (environment) variables
- why don't we define:
```js
function initializeYdocServer(YDOC_HOST, YDOC_PORT, YDOC_LS_DEBUG, YDOC_MESSAGE_CALLBACKS) {
```
- and then just call this method with proper arguments from Java?

**Review by JaroslavTulach — COMMENTED** [review]
It all looks quite decent. Few comments inline.

File: app/ydoc-shared/src/util/net/__tests__/YjsTransport.test.ts (hunk 8 above)
Comment (farmaazon) [reply app/ydoc-shared/src/util/net/__tests__/YjsTransport.test.ts:20]: This is needed in js. Otherwise it may try to apply () to previous line.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java [hunk 16]
```diff
@@ -2,44 +2,24 @@
...
-      log.debug("Ydoc server at {}:{} started in {} ms", hostname, port, took);
-    } else {
-      var hostname = System.getenv(ENSO_YDOC_HOST);
-      var port = System.getenv(ENSO_YDOC_PORT);
-      try (var ydoc = launch(hostname, port)) {
-        lock.acquire();
-      }
-    }
+  public static void main(String[] args) {
+    // main method declaration is required to build the native library
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java:12]: - GraalVM `native-image` doesn't need `main` method
- probably the invocation logic in [NativeImage.scala]() is wrong
- https://github.com/enso-org/enso/blob/a282b3a4b6702ddc1cc598053ca836663a40c42c/project/NativeImage.scala#L260
- when there is no `mainClass` then we shouldn't pass in any option
- especially when `shared=true`

File: lib/java/ydoc-server-registration/src/main/java/org/enso/ydoc/server/registration/YdocServerImpl.java [hunk 17]
```diff
@@ -40,8 +44,7 @@ protected AutoCloseable runYdocServer(String hostname, int port)
     var fqn = "org.enso.ydoc.server.Main";
     var impl = loader.loadClass(fqn);
     assert impl != null;
-    var arr = ProxyArray.fromArray(hostname, "" + port);
-    impl.invokeMember("main", arr);
+    impl.invokeMember("launch", hostname, port + "", jsonChannelCallbacks, binaryChannelCallbacks);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server-registration/src/main/java/org/enso/ydoc/server/registration/YdocServerImpl.java:46]: - the `launch` method is starting new `Thread` to form a JavaScript _event loop_ executor
- due to restrictions spelled out at #14264
   - _"only master can initialize connection on a new thread"_
   - _"then slave can reply on such a thread or any other thread which was initiated previously by the master"_
- thus we must _start the executor here_ and pass it to the other JVM
- btw. previously it wasn't a problem as there were no callbacks from JavaScript to Java

File: docs/infrastructure/ydoc.md [hunk 18]
```diff
@@ -0,0 +1,169 @@
...
+
+```
++------------------+                +--------------------------------------------------------------+
+|                  |                |                                                              |
+| +--------------+ |    WebSocket   | +-----------------+ YjsChannelCallbacks  +-----------------+ |
+| |  IDE Client  | |<-------------->| |  Ydoc Server    |<-------------------->| Language Server | |
+| +--------------+ |                | +-----------------+                      +-----------------+ |
+|     Electron     |                |                         GraalVM                              |
++------------------+                +--------------------------------------------------------------+
+```
```
Comment (JaroslavTulach) [inline docs/infrastructure/ydoc.md:44]: - Starting a dedicated documentation is a great decision!
- Nice drawing!

File: lib/java/ydoc-api/src/main/java/module-info.java (hunk 1 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-api/src/main/java/module-info.java:2]: Moved in d53f68a46e8f8fdc7c59833557b94e0b2fd35acf - that's OK

File: lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/YdocServerApi.java (hunk 9 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-api/src/main/java/org/enso/ydoc/api/YdocServerApi.java:7]: Done in d53f68a46e8f8fdc7c59833557b94e0b2fd35acf

File: lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebEnvironment.java [hunk 19]
```diff
@@ -60,7 +60,10 @@ public static Context.Builder createContext() {
 
   public static Context.Builder createContext(HostAccess hostAccess) {
     var contextBuilder =
-        Context.newBuilder("js").allowHostAccess(hostAccess).allowExperimentalOptions(true);
+        Context.newBuilder("js")
+            .allowHostAccess(hostAccess)
+            .allowExperimentalOptions(true)
+            .allowHostClassLookup(className -> className.equals("java.nio.ByteBuffer"));
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebEnvironment.java:66]: It would be better to:
- remove `allowHostClassLookup`
- inject the `ByteBuffer.class` into the JavaScript when initializing it

This is a minor comment.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 20]
```diff
@@ -125,30 +233,71 @@ public void start() throws ExecutionException, InterruptedException, IOException
...
+              var bindings = ctx.getBindings("js");
+              bindings.putMember("YDOC_HOST", hostname);
+              bindings.putMember("YDOC_PORT", port);
+              bindings.putMember(
+                  "YDOC_JSON_CHANNEL_CALLBACKS", getJsonChannelCallbacksSynchronized());
+              bindings.putMember(
+                  "YDOC_BINARY_CHANNEL_CALLBACKS", getBinaryChannelCallbacksSynchronized());
+              bindings.putMember("YDOC_LS_DEBUG", "false");
+
+              ctx.eval(ydocJs);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java:256]: This would rather be "injected into the JavaScript" than exposed as `globalThis` bindings:

```suggestion
              var initFn = ctx.eval(ydocJs);
              initFn.execute(hostname, port, getJsonChannelCallbacksSynchronized(), getJsonChannelCallbacksSynchronized());
```
that requires the `ydocJs` to evaluate to a function with arguments. Usually I do that as:
```js
(function (hostname, port, ydocJsonChannelCallbacks, ydocBinaryChannelCallbacks, ydocLsDebug) {
   // the original code that can access the "injected" variables
   // but the variables themselves aren't visible to anyone else than content of this function
})
```
usually that's safer approach which cannot be exploited by any JavaScript code running outside of the initialization function.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 21]
```diff
@@ -125,30 +233,71 @@ public void start() throws ExecutionException, InterruptedException, IOException
...
+
+    while (!initFuture.isDone()) {
+      executor.processPendingTasks();
+      try {
+        long delay = executor.getNextTaskDelayNanos();
+        executor.waitForTasks(delay);
+      } catch (InterruptedException e) {
+        Thread.currentThread().interrupt();
+        break;
+      }
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: Isn't this almost the same code as in `runEventLoopBlocking` method below?

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 22]
```diff
@@ -125,30 +233,71 @@ public void start() throws ExecutionException, InterruptedException, IOException
...
-                  return ctx;
-                },
-                executor)
-            .get();
+  /**
+   * Runs the event loop continuously until {@link #close()} is called. This method blocks and
+   * should typically be run in a dedicated thread.
+   */
+  public void runEventLoopBlocking() {
+    while (running.get()) {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: There already is an atomic variable in the executor. Maybe delete `running` and just:
```suggestion
    while (!executor.isShutdown()) {
```

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 23]
```diff
@@ -0,0 +1,650 @@
...
+ * #processPendingTasks()} must only be called from the owner thread.
+ */
+public final class YdocScheduledExecutorService implements ScheduledExecutorService {
+
+  private final long ownerThreadId;
+  private final ConcurrentLinkedQueue<Runnable> immediateTasks;
+  private final Object scheduledTasksLock = new Object();
+  private final PriorityQueue<ScheduledTask> scheduledTasks;
+  private final AtomicBoolean shutdown = new AtomicBoolean(false);
+  private final Object waitLock = new Object();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - Unify `waitLock` and `shceduledTasksLock` into one
- make sure that they really _guard access to internal structures_

```suggestion
  private final Object lock = new Object();
  /** @GuardedBy("lock") */
  private final ConcurrentLinkedQueue<Runnable> immediateTasks;
  /** @GuardedBy("lock") */
  private final PriorityQueue<ScheduledTask> scheduledTasks;
  /** not sure about the next variable, but if you @GuardBy("lock"), then it can be just boolean */
  private boolean shutdown = false;
```
- take the `lock` modify internal state of any of this variables
- never _call foreign code_ (all those `Runnable`s and `Callable`s) while holding the `lock`

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 24]
```diff
@@ -0,0 +1,650 @@
...
+
+  /** Creates a new execution service bound to the current thread. */
+  public YdocScheduledExecutorService() {
+    this.ownerThreadId = Thread.currentThread().threadId();
+    this.immediateTasks = new ConcurrentLinkedQueue<>();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - either you `@GuardBy("lock")` access to `immediateTasks`
- or you use `ConcurrentXyz` data structure
- if the access is guarded, then simple data structures are preferrable

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 25]
```diff
@@ -0,0 +1,650 @@
...
+   * @throws IllegalStateException if the service has been shut down
+   */
+  private void submitInternal(Runnable task) {
+    if (shutdown.get()) {
+      throw new IllegalStateException("Service has been shut down");
+    }
+    immediateTasks.offer(task);
+    synchronized (waitLock) {
+      waitLock.notifyAll();
+    }
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: Putting the whole code into single `synchronized` block makes it easier to reason about it:
```suggestion
    synchronized (lock) {
      if (shutdown.get()) {
        throw new IllegalStateException("Service has been shut down");
      }
      immediateTasks.offer(task);
      lock.notifyAll();
    }
```
only one running thread can be in the `synchronized` block at a time.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 26]
```diff
@@ -0,0 +1,650 @@
...
+    long executeAtNanos = System.nanoTime() + unit.toNanos(delay);
+    var cancellableTask = new CancellableTask(task, executeAtNanos);
+    synchronized (scheduledTasksLock) {
+      scheduledTasks.offer(new ScheduledTask(cancellableTask, executeAtNanos));
+    }
+    synchronized (waitLock) {
+      waitLock.notifyAll();
+    }
+    return cancellableTask;
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]:
```suggestion
  synchronized(lock) {
    if (shutdown.get()) {
      throw new IllegalStateException("Service has been shut down");
    }
    long executeAtNanos = System.nanoTime() + unit.toNanos(delay);
    var cancellableTask = new CancellableTask(task, executeAtNanos);
      scheduledTasks.offer(new ScheduledTask(cancellableTask, executeAtNanos));
      lock.notifyAll();
  }
  return cancellableTask;
```

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 27]
```diff
@@ -0,0 +1,650 @@
...
+    long executeAtNanos = System.nanoTime() + unit.toNanos(initialDelay);
+
+    var cancellableTask = new CancellableTask(repeatingTask, executeAtNanos);
+    synchronized (scheduledTasksLock) {
+      scheduledTasks.offer(new ScheduledTask(cancellableTask, executeAtNanos));
+    }
+    synchronized (waitLock) {
+      waitLock.notifyAll();
+    }
+    return cancellableTask;
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]:
```suggestion
    synchronized (lock) {
      if (shutdown.get()) {
        throw new IllegalStateException("Service has been shut down");
      }

      var repeatingTask = new RepeatingTask(task, unit.toNanos(period));
      long executeAtNanos = System.nanoTime() + unit.toNanos(initialDelay);

      var cancellableTask = new CancellableTask(repeatingTask, executeAtNanos);
      scheduledTasks.offer(new ScheduledTask(cancellableTask, executeAtNanos));
      lock.notifyAll();
    }
    return cancellableTask;
```

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 28]
```diff
@@ -0,0 +1,650 @@
...
+
+      // Reschedule for next execution
+      if (!shutdown.get()) {
+        long nextExecutionNanos = System.nanoTime() + periodNanos;
+        synchronized (scheduledTasksLock) {
+          scheduledTasks.offer(new ScheduledTask(this, nextExecutionNanos));
+        }
+        synchronized (waitLock) {
+          waitLock.notifyAll();
+        }
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - Move this into a method in `YdocScheduledExecutorService` itself
- use single `synchronized` block

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 29]
```diff
@@ -0,0 +1,650 @@
...
+      long delayNanos = executeAtNanos - System.nanoTime();
+      return unit.convert(delayNanos, TimeUnit.NANOSECONDS);
+    }
+
+    @Override
+    public int compareTo(java.util.concurrent.Delayed o) {
+      if (this == o) {
+        return 0;
+      }
+      long diff = getDelay(TimeUnit.NANOSECONDS) - o.getDelay(TimeUnit.NANOSECONDS);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - `getDelay` isn't a stable value, it is changing as `System.nanoTime()` progresses
   - with this code I'd bet you can get `this.compareTo(this) != 0` ;-)
- don't compare by `getDelay` 
- compare by `executeAtNanos`!

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 30]
```diff
@@ -0,0 +1,650 @@
...
+    private volatile Throwable exception;
+    private volatile boolean done = false;
+    private final Object lock = new Object();
+
+    CallableScheduledFuture(Callable<V> task, long executeAtNanos) {
+      this.executeAtNanos = executeAtNanos;
+    }
+
+    void complete(V result) {
+      synchronized (lock) {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java:346]: - In this class you are synchronizing whole methods. 
- It is easier to reason about it code now.
- Btw. you don't seem to be a fan of 
```java
synchronized complete(V result) {
  ...
}
```
- I know it has its drawbacks as the lock is accessible for foreign code
- but leads to more readable code as it was the original (and [slightly wrong](https://wiki.apidesign.org/wiki/Java_Monitor)) design goal of Java language

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 31]
```diff
@@ -0,0 +1,650 @@
...
+    }
+  }
+
+  /** A ScheduledFuture for Callable tasks that holds the result. */
+  private static final class CallableScheduledFuture<V> implements ScheduledFuture<V> {
+    private final long executeAtNanos;
+    private volatile V result;
+    private volatile Throwable exception;
+    private volatile boolean done = false;
+    private final Object lock = new Object();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]:
```suggestion
    private final Object lock = new Object();
    /** @GuardedBy("lock") */
    private V result;
    /** @GuardedBy("lock") */
    private Throwable exception;
    /** @GuardedBy("lock") */
    private boolean done = false;
```
- there is no point of using `volatile` when the access to the variables is shielded by `synchronized(lock)`
```

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 32]
```diff
@@ -0,0 +1,650 @@
...
+    }
+
+    @Override
+    public boolean isCancelled() {
+      return false;
+    }
+
+    @Override
+    public boolean isDone() {
+      return done;
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - this is correct if the variable is kept `volatile`
- without `volatile` one must write:
```suggestion
   synchronized(lock) {
      return done;
   }
```
- to make the code correct.
- I (slightly) prefer the `synchronized` over `volatile` here

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 33]
```diff
@@ -0,0 +1,650 @@
...
+    }
+
+    // Process scheduled tasks that are ready
+    synchronized (scheduledTasksLock) {
+      while (!scheduledTasks.isEmpty()) {
+        ScheduledTask scheduledTask = scheduledTasks.peek();
+        if (scheduledTask.executeAtNanos <= currentTime) {
+          scheduledTasks.poll();
+          try {
+            scheduledTask.task.run();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: - here you are running _a foreign code_ while holding a lock
- that leads to deadlocks - replace it with:
```java
for (;;) {
   Runnable toRun = null;
   synchronized (lock) {
      toRun = // obtain the task to run, if any
   }
   if (toRun != null) {
     // run the foreign code without holding your lock
     toRun.run();
   }
}
```

**Comment by JaroslavTulach** [comment]
### Mac OS X Startup

@4e6 asked me to compare the startup on my Mac mini. Here is the summary:
- develop version `2026.1.1-nightly.2026.2.4` starts in **6s**
- Ydoc version from d53f68a46e8f8fdc7c59833557b94e0b2fd35acf starts in **7s**

#### Methodology

I created a simple project with a trivial code and single table visualisation. After opening it I search for following two messages in the log:
- `Opening project bbff6028-68f8-41e1-9079-6557553fcb0a`
- `**** AG Grid Enterprise License ************************************************`
   - the other message seems to be printed roughly at the same time visualisation is shown
   - which makes sense as that's the first time the table grid library is used
- then I subtracted the timestamps of those messages `[2026-02-04T04:58:27.043Z]`
- and rounded it to seconds

#### Sample Project

```ruby
main =
    text1 = "Hello World!"
    vector1 = text1.split ' '
```

visualisation

#### Binaries

- both binaries were built by `./run ide build` command
- then executed by `./dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso`
- logs were printed on the console and then copied

##### Log of Develop Version

```
[LOG] [2026-02-04T04:45:31.316Z] Window created.
[LOG] [2026-02-04T04:45:31.317Z] Loading the window address 'https://localhost:8080/'.
[DEBUG] [2026-02-04T04:45:41.983Z] Opening project bbff6028-68f8-41e1-9079-6557553fcb0a
setupGatewayClient ws://127.0.0.1:30616 index
setupGatewayClient(lsUrl: ws://127.0.0.1:30616, docName: index)
setupGatewayClient ws://127.0.0.1:30616 2abf8780-3d8c-4b99-acf3-a9552984a6f1
setupGatewayClient(lsUrl: ws://127.0.0.1:30616, docName: 2abf8780-3d8c-4b99-acf3-a9552984a6f1)
[INFO] [2026-02-04T04:45:47.764Z] 'visualizations/' folder not found in project directory. If you have custom visualizations, please put them under 'visualizations/'.
[WARN] [2026-02-04T05:45:48.133] [enso.org.enso.interpreter.runtime.SerializationPool] Unable to load suggestions for library [local.HelloWorld].
[ERROR] [2026-02-04T04:45:48.181Z] ****************************************************************************************************************************
[ERROR] [2026-02-04T04:45:48.181Z] ************************************************ AG Grid Enterprise License ************************************************
```

- the startup time is `48.181 - 41.983` which is roughly **6s**

##### Log of Y.doc Version

```
[DEBUG] [2026-02-04T04:58:20.285Z] Opening project bbff6028-68f8-41e1-9079-6557553fcb0a
[WARN] [2026-02-04T04:58:22.119Z] Failed to initialize Language Server connection, retrying after 3ms...
 {
  payload: {
    cause: [Error: Cannot read properties of undefined (reading 'request')],
    request: 'session/initProtocolConnection',
    params: { clientId: '17f15809-d214-4c18-96bc-cea18eae33a9' }
  },
  context: []
}
setupGatewayClient(lsUrl: gui-rpc-d7c2119f-68b7-4afa-bf00-668843e82e78, dataUrl: gui-data-30fd9832-c70c-4bbf-9887-efc714699d5e docName: index), byteBuffer: class java.nio.ByteBuffer, jsonChannelCallbacks: org.enso.ydoc.server.YjsCallbacksSynchronized@333df545, binaryChannelCallbacks: org.enso.ydoc.server.YjsCallbacksSynchronized@9855f37
WARNING: A restricted method in java.lang.foreign.MemorySegment has been called
WARNING: java.lang.foreign.MemorySegment::reinterpret has been called by org.enso.languageserver.http.server.BinaryYdocServer$BinaryServerCallbacks in module org.enso.language.server (file:/Users/hudson/NetBeansProjects/enso/dist/ide/mac-arm64/Enso.app/Contents/Resources/enso/dist/2026.1.1-dev/bin/../component/language-server.jar)
WARNING: Use --enable-native-access=org.enso.language.server to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

setupGatewayClient(lsUrl: gui-rpc-d7c2119f-68b7-4afa-bf00-668843e82e78, dataUrl: gui-data-30fd9832-c70c-4bbf-9887-efc714699d5e docName: 92c0fceb-3f0f-4ffe-a4d0-66d3e8ce413d), byteBuffer: class java.nio.ByteBuffer, jsonChannelCallbacks: org.enso.ydoc.server.YjsCallbacksSynchronized@333df545, binaryChannelCallbacks: org.enso.ydoc.server.YjsCallbacksSynchronized@9855f37
[INFO] [2026-02-04T04:58:26.689Z] 'visualizations/' folder not found in project directory. If you have custom visualizations, please put them under 'visualizations/'.
[WARN] [2026-02-04T05:58:27.023] [enso.org.enso.interpreter.runtime.SerializationPool] Unable to load suggestions for library [local.HelloWorld].
[ERROR] [2026-02-04T04:58:27.042Z] ****************************************************************************************************************************
[ERROR] [2026-02-04T04:58:27.043Z] ************************************************ AG Grid Enterprise License ************************************************
``` 
- e.g. the time is `27.043 - 20.285` which is roughly **7s**

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 34]
```diff
@@ -0,0 +1,650 @@
...
+ * A single-threaded execution service that processes tasks on the thread where it was created.
+ *
+ * <p>This service maintains an event queue and executes tasks when {@link #processPendingTasks()}
+ * is called from the owner thread. It supports both immediate task execution and scheduled tasks
+ * with delays.
+ *
+ * <p><b>Thread Safety:</b> This service is thread-safe for submitting tasks, but {@link
+ * #processPendingTasks()} must only be called from the owner thread.
+ */
+public final class YdocScheduledExecutorService implements ScheduledExecutorService {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java]: These helpers classes shouldn't be public:
```suggestion
final class YdocScheduledExecutorService implements ScheduledExecutorService {
```

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsCallbacksSynchronized.java [hunk 35]
```diff
@@ -0,0 +1,36 @@
...
+
+/**
+ * Thread-safe {@link YjsChannelCallbacks} wrapper that provides synchronized channels to delegates.
+ *
+ * <p>GraalJS polyglot context requires all JavaScript interactions to occur on a single thread.
+ * When a connection is established, this wrapper creates a {@link YjsChannelSynchronized} around
+ * the raw channel before passing it to the delegate, ensuring the Language Server can safely
+ * interact with channels from any thread.
+ */
+public final class YjsCallbacksSynchronized implements YjsChannelCallbacks {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsCallbacksSynchronized.java]:
```suggestion
final class YjsCallbacksSynchronized implements YjsChannelCallbacks {
```
- or do we need this class to be public because of reflective access?

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java [hunk 36]
```diff
@@ -0,0 +1,38 @@
...
+import org.enso.ydoc.api.YjsChannel;
+
+/**
+ * Thread-safe {@link YjsChannel} wrapper that delegates operations to the Ydoc executor thread.
+ *
+ * <p>GraalJS polyglot context requires all JavaScript interactions to occur on a single thread.
+ * This wrapper queues channel operations to the {@link YdocScheduledExecutorService} to satisfy
+ * this constraint.
+ */
+public final class YjsChannelSynchronized implements YjsChannel {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java]:
```suggestion
final class YjsChannelSynchronized implements YjsChannel {
```
- or do we need this class to be public because of some reflective access?
- even if we mark `send` and subscribe methods with `@HostAccess.Explicit` annotation?

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java [hunk 37]
```diff
@@ -0,0 +1,298 @@
...
+    // Schedule a task with delay
+    service.schedule(() -> counter.incrementAndGet(), 50, TimeUnit.MILLISECONDS);
+
+    // Process immediately - should not execute yet
+    int executed1 = service.processPendingTasks();
+    assertEquals(0, executed1);
+    assertEquals(0, counter.get());
+
+    // Wait for the delay
+    Thread.sleep(60);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java]: - Please avoid `Thread.sleep` even in tests
- it is a bad coding practice
- possibly replace `AtomicInteger` with `CountDownLatch` - that's a very useful utility class in tests

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java [hunk 38]
```diff
@@ -0,0 +1,298 @@
...
+  @Test
+  public void testScheduledTaskWithDelay() throws InterruptedException {
+    YdocScheduledExecutorService service = new YdocScheduledExecutorService();
+    AtomicInteger counter = new AtomicInteger(0);
+
+    // Schedule a task with delay
+    service.schedule(() -> counter.incrementAndGet(), 50, TimeUnit.MILLISECONDS);
+
+    // Process immediately - should not execute yet
+    int executed1 = service.processPendingTasks();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java]: - Imagine a GC kicks in and suspends execution for 100ms
- then the assert will probably fail, right?

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java [hunk 39]
```diff
@@ -0,0 +1,298 @@
...
+    // Schedule tasks with different delays
+    service.schedule(() -> executionOrder.add(3), 60, TimeUnit.MILLISECONDS);
+    service.schedule(() -> executionOrder.add(1), 20, TimeUnit.MILLISECONDS);
+    service.schedule(() -> executionOrder.add(2), 40, TimeUnit.MILLISECONDS);
+
+    // Wait for all delays to pass
+    Thread.sleep(70);
+
+    // Process - should execute in order of delay
+    service.processPendingTasks();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java:113]: The most reliable way to really unit test this is to add another test only constructor that will inject in a `MockTimer` to be used instead of `System.nanoTime()` 

Then the test would then be in control of the `System.nanoTime()` and would appropriately change it instead of `sleep(70)` it would just say `MockTime.advance(70)`....

This kind of _mock timer_ is already used in `Runtime*Test`: https://github.com/enso-org/enso/blob/c3abdec33d02b17622478fef0f88eb29c342480e/engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java#L189

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocTest.java [hunk 40]
```diff
@@ -44,87 +34,96 @@ public class YdocTest {
...
+      }
+    }
 
-    var buffer = queue.take();
-    var uuid = BufferDataUtil.readUUID(buffer);
-    WsClient.builder().build().connect(ydocUrl(uuid.toString()), new DashboardConnection(queue));
+    Assert.assertTrue("Client should be connected", connected);
 
-    var ok2 = queue.take();
-    Assert.assertTrue(ok2.debugDataHex(), BufferDataUtil.isOk(ok2));
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocTest.java:100]: The changes in this package look like a simplification. However I assume we are also testing a bit less of functionality that we used to. Am I right or not?

File: lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala [hunk 41]
```diff
@@ -38,8 +38,8 @@ class MessageHandler(protocolFactory: ProtocolFactory, controller: ActorRef)
   ): Receive = {
     case MessageHandler.WebMessage(msg) =>
       handleWebMessage(msg, webConnection, awaitingResponses)
-    case MessageHandler.Disconnected(port) =>
-      controller ! MessageHandler.Disconnected(port)
```
Comment (JaroslavTulach) [inline lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala:42]: When running `enso --help` I still see:
```
    --data-port <data-port>                Data port for visualization
                                           protocol

    --secure-data-port <data-port>         A secure data port for
                                           visualization protocol
    --secure-rpc-port <rpc-port>           A secure RPC port for
                                           processing all incoming
                                           connections
```
I guess all these options should be removed now, when we ignore the `port` anyway. 

On the other hand, I don't see description of the Ydoc-server port value in the `enso --help` output!

**Review by JaroslavTulach — APPROVED** [review]
- congrats on getting this working!
- I left few comments inline, but overall
- I think this magnificent work should be integrated!

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocTest.java (hunk 40 above)
Comment (4e6) [reply lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocTest.java:100]: Correct,  I simplified the test

File: lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java (hunk 38 above)
Comment (4e6) [reply lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocScheduledExecutorServiceTest.java]: You're right. Updated

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 42]
```diff
@@ -125,30 +231,68 @@ public void start() throws ExecutionException, InterruptedException, IOException
...
+              parser.initialize(ctx);
+
+              var bindings = ctx.getBindings("js");
+              bindings.putMember("YDOC_HOST", hostname);
+              bindings.putMember("YDOC_PORT", port);
+              bindings.putMember(
+                  "YDOC_JSON_CHANNEL_CALLBACKS", getJsonChannelCallbacksSynchronized());
+              bindings.putMember(
+                  "YDOC_BINARY_CHANNEL_CALLBACKS", getBinaryChannelCallbacksSynchronized());
+              bindings.putMember("YDOC_LS_DEBUG", "false");
```
Comment (vitvakatu) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: Here we unconditionally put `false` into YDOC_LS_DEBUG, but in JS code the check is `typeof YDOC_LS_DEBUG  != 'undefined'`, so we always have logs enabled.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 43]
```diff
@@ -125,30 +231,68 @@ public void start() throws ExecutionException, InterruptedException, IOException
...
+
+              ctx.eval(ydocJs);
+
+              return ctx;
+            });
+
+    runEventLoopUntil(initFuture::isDone);
```
Comment (hubertp) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java:261]: Is there any timeout on this?

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java (hunk 42 above)
Comment (hubertp) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: Can we make this configurable via some env variable?

File: app/gui/src/project-view/util/net/dataServer.ts [hunk 44]
```diff
@@ -60,20 +61,22 @@ export class DataServer extends ObservableV2<DataServerEvents> {
...
-      if (!(rawPayload instanceof ArrayBuffer)) {
+      if (!ArrayBuffer.isView(rawPayload)) {
         console.warn('Data Server: Data type was invalid:', rawPayload)
         // Ignore all non-binary messages. If the messages are `Blob`s instead, this is a
         // misconfiguration and should also be ignored.
         return
       }
-      const binaryMessage = OutboundMessage.getRootAsOutboundMessage(new ByteBuffer(rawPayload))
+      const binaryMessage = OutboundMessage.getRootAsOutboundMessage(
+        new ByteBuffer(rawPayload.buffer),
```
Comment (vitvakatu) [inline app/gui/src/project-view/util/net/dataServer.ts]: Should be something like `rawPayload.buffer.slice(rawPayload.byteOffset, rawPayload.byteOffset + rawPayload.byteLength)`.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 45]
```diff
@@ -0,0 +1,656 @@
...
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.Future;
+import java.util.concurrent.ScheduledExecutorService;
+import java.util.concurrent.ScheduledFuture;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+import java.util.concurrent.atomic.AtomicBoolean;
+
+/**
+ * A single-threaded execution service that processes tasks on the thread where it was created.
```
Comment (hubertp) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java:17]: What's wrong with `Executors.newSingleThreadExecutor()`?

File: lib/java/ydoc-polyfill/src/main/resources/org/enso/ydoc/polyfill/web/event-target.js
Comment (vitvakatu) [inline lib/java/ydoc-polyfill/src/main/resources/org/enso/ydoc/polyfill/web/event-target.js]: Btw we seemingly try to invoke a number here, as it is assigned `this.#timeStamp = performance.now();` in the constructor.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java [hunk 46]
```diff
@@ -0,0 +1,656 @@
...
+  }
+
+  /**
+   * Shuts down this service. No new tasks will be accepted after shutdown.
+   *
+   * <p>Pending tasks can still be processed with {@link #processPendingTasks()}.
+   */
+  public void shutdown() {
+    synchronized (lock) {
+      shutdown = true;
```
Comment (hubertp) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YdocScheduledExecutorService.java:735]: I don't think this prevents an existing task from being aborted, does it? If it is stuck then nothing prevents it from being in a shutdown mode indefinitely.

File: app/ydoc-channel/src/YjsChannel.ts [hunk 47]
```diff
@@ -0,0 +1,266 @@
...
+ * Each sender has a unique ID used as transaction origin to filter out self-sent messages.
+ * Implements WebSocket-like event API for compatibility with existing code.
+ */
+export class YjsChannel<T = unknown> extends ObservableV2<WebSocketEventHandlers> {
+  private readonly senderId: string
+  private readonly doc: Y.Doc
+  private readonly array: Y.Array<T>
+  private readonly handlers: Set<MessageHandler<T>> = new Set()
+  private readonly observeHandler: (event: Y.YArrayEvent<T>, tr: Y.Transaction) => void
+  private hasMessageListeners = false
```
Comment (vitvakatu) [inline app/ydoc-channel/src/YjsChannel.ts]: I guess it can be a rare case, but `hasMessageListeners` is never reset to `false` again — we only set it to `true` in `on` method.

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherInteropType.java
Comment (vitvakatu) [inline lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherInteropType.java]: Not related to this PR, but shouldn't it be `iop.isIterator(obj)`?

**Review by hubertp — COMMENTED** [review]
Docker image needs an update re ports as well? It's in `tools/ci/docker`.
I would appreciate more info why we need to re-implement the wheel with a custom executor (motivation in the class description?).

Tested on Mac and Linux, the recent version seemed fine.

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala [hunk 48]
```diff
@@ -512,26 +528,39 @@ class MainModule(serverConfig: LanguageServerConfig, logLevel: Level) {
...
+    val ydocExecutor = Executors.newSingleThreadExecutor(r => {
+      val thread = new Thread(r)
+      thread.setName("Ydoc main thread")
+      // Ydoc should not prevent JVM from exiting
+      thread.setDaemon(true)
+      thread
+    })
+    ydocExecutor.execute(() =>
+      org.enso.ydoc.api.YdocServerApi
+        .launchYdocServer(
```
Comment (vitvakatu) [inline engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala:556]: This one returns `AutoCloseable`, but we never call `close()`, don't we?

File: app/ydoc-channel/src/YjsChannel.ts [hunk 49]
```diff
@@ -0,0 +1,266 @@
...
+          return
+        }
+        doc.transact(() => {
+          // Process all added items
+          for (const delta of event.changes.delta) {
+            if (delta.insert) {
+              const items = Array.isArray(delta.insert) ? delta.insert : [delta.insert]
+              for (const item of items) {
+                this.notifyHandlers(item)
+                this.array.delete(0)
```
Comment (vitvakatu) [inline app/ydoc-channel/src/YjsChannel.ts]: I believe current design can cause hard-to-track concurrency issues. The particular test that fails:
- `A` sends `A1` to the channel, but nobody reads it yet
- `B` sends `B1` to the channel, and `A` processes it, deleting message at index 0, i.e. its own `A1` message.
- `B` never receives `A1`.

```js
it('does not delete local pending message when remote inserts after it', () => {
  const docA = new Y.Doc()
  const docB = new Y.Doc()
  const a = new YjsChannel<string>(docA, 'chan')
  const b = new YjsChannel<string>(docB, 'chan')
  const receivedA: string[] = []
  a.subscribe((m) => receivedA.push(m))
  // b intentionally has no handlers, so it won’t consume/delete yet
  a.send('A1')
  Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA, Y.encodeStateVector(docB)), 'from-a')
  b.send('B1') // appends after A1 in docB => remote insert lands after local pending in docA
  Y.applyUpdate(docA, Y.encodeStateAsUpdate(docB, Y.encodeStateVector(docA)), 'from-b')
  expect(receivedA).toEqual(['B1'])
  // Correct behavior: A consumed+deleted B1, but kept its own A1 pending (B hasn’t consumed it).
  expect(docA.getArray<string>('chan').toArray()).toEqual(['A1'])
})
```

**Comment by JaroslavTulach** [comment]
I'd like to get this integrated. What's blocking us? I remember @jdunkerley saying he has seen

obrazek

on some project he has. According to the log files it is probably:
```
[ERROR] [2026-02-10T11:08:29.861] [org.enso.interpreter.instrument.execution.JobExecutionEngine] Error executing UpsertVisualizationJob(visualizationId=7f93fbac-4e70-4f2d-8da6-0925e9ffd398, expressionId=c6415566-dd68-457f-9d27-52199e8a992e)
java.lang.IllegalStateException: Unexpected FrameAnalysisMeta associated with IR CallArgument.Specified(diagnostics = null, passData = MetadataStorage[AliasMetadata.ChildScope, DataflowAnalysis.DependencyInfo, FrameVariableNames, TailCall.TailPosition.Tail], location = IdentifiedLocation[start=617, end=621, uuid=None], id = null, name = None, value = Name.Literal(diagnostics = null, passData = MetadataStorage[AliasMetadata.Occurrence, CachePreferenceAnalysis.Weights, DataflowAnalysis.DependencyInfo, Resolution, TailCall.TailPosition.Tail], location = IdentifiedLocation[start=617, end=621, uuid=None], id = dffd51ac-d691-4f0d-82f2-e4e56b0dc142, name = Data, isMethod = false, origName = null), isSynthetic = false)
Old: FrameVariableNames{names=[]} new FrameVariableNames{names=[]}
	at org.enso.compiler.pass.analyse.FrameAnalysisMeta.updateMetadata(FrameAnalysisMeta.java:21)
	at org.enso.compiler.pass.analyse.FrameAnalysisMeta.updateSymbolNames(FrameAnalysisMeta.java:37)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.$anonfun$maybAttachFrameVariableNames$2(FramePointerAnalysis.scala:254)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.$anonfun$maybAttachFrameVariableNames$2$adapted(FramePointerAnalysis.scala:253)
	at scala.library@2.13.15/scala.Option.foreach(Option.scala:437)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.maybAttachFrameVariableNames(FramePointerAnalysis.scala:253)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.$anonfun$processCallArguments$1(FramePointerAnalysis.scala:245)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.$anonfun$processCallArguments$1$adapted(FramePointerAnalysis.scala:240)
	at scala.library@2.13.15/scala.collection.immutable.List.foreach(List.scala:334)
	at org.enso.compiler.pass.analyse.FramePointerAnalysis$.processCallArguments(FramePointerAnalysis.scala:240)
```
e.g. [exception from](https://github.com/enso-org/enso/blob/bd23bf418e13a91595710b517706bfdf2f6e122e/engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameAnalysisMeta.java#L21) - I haven't seen that one for ages. Even when I saw the problem, it was only on my private branch. I would be very surprised if such an exception was triggered by changes in this PR. Rather a **debris in caches** is the trigger...

**Comment by JaroslavTulach** [comment]
- while running with James workflow ([more info](https://github.com/enso-org/enso/pull/14438#issuecomment-3907702361))
- I have noticed `UTFDataFormatException` - when encoding of JavaScript string would exceed 65535 bytes in length
- fixed in 85a176c358

**Comment by JaroslavTulach** [comment]
There is also an access error because JavaScript objects are used from multiple threads at the same time. The stack of the failure I managed to get is:
```
"logback-1"
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.toString(PolyglotValueDispatch.java:1568)
	at org.graalvm.polyglot.AbstractValue.toString(Value.java:2828)
	at org.graalvm.polyglot.Value.toString(Value.java:1970)
	at org.enso.logging.service.logback.DeferredProcessingSocketAppender.postProcessEvent(DeferredProcessingSocketAppender.java:183)
	at org.enso.logging.service.logback.DeferredProcessingSocketAppender.dispatchEvents(DeferredProcessingSocketAppender.java:240)
	at org.enso.logging.service.logback.DeferredProcessingSocketAppender.connectSocketAndDispatchEvents(DeferredProcessingSocketAppender.java:198)
	at org.enso.logging.service.logback.DeferredProcessingSocketAppender$1.run(DeferredProcessingSocketAppender.java:141)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.lang.Thread.runWith(Thread.java:1487)
	at java.lang.Thread.run(Thread.java:1474)
```
fails, because of too much _defered logging_. JavaScript **event loop thread** was meanwhile executing something like:
```
"Ydoc main thread"
	at java.text.DecimalFormat.expandAffixes(DecimalFormat.java:3288)
	at java.text.DecimalFormat.applyPattern(DecimalFormat.java:3976)
	at java.text.DecimalFormat.<init>(DecimalFormat.java:519)
	at sun.util.locale.provider.NumberFormatProviderImpl.getInstance(NumberFormatProviderImpl.java:193)
	at sun.util.locale.provider.NumberFormatProviderImpl.getNumberInstance(NumberFormatProviderImpl.java:151)
	at java.text.NumberFormat.getInstance(NumberFormat.java:1134)
	at java.text.NumberFormat.getInstance(NumberFormat.java:1120)
	at java.text.NumberFormat.getInstance(NumberFormat.java:597)
	at java.text.MessageFormat.subformat(MessageFormat.java:1530)
	at java.text.MessageFormat.format(MessageFormat.java:1093)
	at java.text.Format.format(Format.java:165)
	at java.text.MessageFormat.format(MessageFormat.java:1059)
	at org.enso.logging.config.systemlogger.SystemLoggerViaSlf4j$Bridge.log(SystemLoggerViaSlf4j.java:49)
	at java.lang.System$Logger.log(System.java:1194)
	at org.enso.persist.PerGenerator$Histogram.dump(PerGenerator.java:244)
	at org.enso.persist.PerGenerator.writeObject(PerGenerator.java:56)
	at org.enso.persist.Persistance$Pool.write(Persistance.java:300)
	at org.enso.jvm.channel.Channel.executeImpl(Channel.java:415)
	at org.enso.jvm.channel.Channel.execute(Channel.java:250)
	at org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:219)
	at org.enso.jvm.interop.impl.OtherJvmObject.send(OtherJvmObject.java:188)
	at org.enso.jvm.interop.impl.OtherJvmObjectGen$ReflectionLibraryExports$Uncached.send(OtherJvmObjectGen.java:97)
	at com.oracle.truffle.polyglot.OtherContextGuestObject.sendImpl(OtherContextGuestObject.java:157)
	at com.oracle.truffle.polyglot.OtherContextGuestObject$Send.doSlowPath(OtherContextGuestObject.java:121)
	at com.oracle.truffle.polyglot.OtherContextGuestObjectGen$ReflectionLibraryExports$Uncached.send(OtherContextGuestObjectGen.java:250)
	at com.oracle.truffle.api.interop.InteropLibraryGen$Proxy.readBufferByte(InteropLibraryGen.java:3244)
	at com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.readBufferByte(InteropLibraryGen.java:7410)
	at com.oracle.truffle.js.runtime.builtins.JSArrayBufferObject$Interop.readBufferByte(JSArrayBufferObject.java:666)
	at com.oracle.truffle.js.runtime.builtins.InteropGen$InteropLibraryExports$Uncached.readBufferByte(InteropGen.java:950)
	at com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.readBufferByte(InteropLibraryGen.java:7410)
	at com.oracle.truffle.js.runtime.array.TypedArray$InteropOneByteIntArray.readBufferByte(TypedArray.java:524)
	at com.oracle.truffle.js.runtime.array.TypedArray$InteropOneByteIntArray.getIntImpl(TypedArray.java:504)
	at com.oracle.truffle.js.runtime.array.TypedArray$InteropUint8Array.getIntImpl(TypedArray.java:626)
	at com.oracle.truffle.js.runtime.array.TypedArray$TypedIntArray.getInt(TypedArray.java:343)
	at com.oracle.truffle.js.runtime.array.TypedArray$TypedIntArray.getElement(TypedArray.java:322)
	at com.oracle.truffle.js.builtins.JSConstructTypedArrayNode.doTypedArray(JSConstructTypedArrayNode.java:319)
	at com.oracle.truffle.js.builtins.JSConstructTypedArrayNodeGen.execute_generic1(JSConstructTypedArrayNodeGen.java:299)
	at com.oracle.truffle.js.builtins.JSConstructTypedArrayNodeGen.execute(JSConstructTypedArrayNodeGen.java:212)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:610)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewReturnThis(JSNewNode.java:150)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:104)
	at com.oracle.truffle.js.nodes.function.JSFunctionOneArgumentNode.executeFillObjectArray(JSFunctionArgumentsNode.java:154)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewReturnThis(JSNewNode.java:149)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:104)
	at com.oracle.truffle.js.nodes.function.JSFunctionArgumentsNode.executeFillObjectArray(JSFunctionArgumentsNode.java:89)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewReturnThis(JSNewNode.java:149)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:104)
	at com.oracle.truffle.js.nodes.access.TemporalDeadZoneCheckNode.execute(TemporalDeadZoneCheckNode.java:80)
	at com.oracle.truffle.js.nodes.access.JSWriteScopeFrameSlotNodeGen.execute_generic3(JSWriteScopeFrameSlotNodeGen.java:138)
	at com.oracle.truffle.js.nodes.access.JSWriteScopeFrameSlotNodeGen.execute(JSWriteScopeFrameSlotNodeGen.java:69)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.SwitchNode.executeOrdered(SwitchNode.java:301)
	at com.oracle.truffle.js.nodes.control.SwitchNode.execute(SwitchNode.java:195)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.DirectBreakTargetNode.executeVoid(DirectBreakTargetNode.java:76)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeVoid(OptimizedBlockNode.java:137)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:68)
	at com.oracle.truffle.js.nodes.control.VoidBlockNode.execute(VoidBlockNode.java:61)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.control.SwitchNode.executeOrdered(SwitchNode.java:311)
	at com.oracle.truffle.js.nodes.control.SwitchNode.execute(SwitchNode.java:195)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.DirectBreakTargetNode.executeVoid(DirectBreakTargetNode.java:76)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeVoid(OptimizedBlockNode.java:137)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:68)
	at com.oracle.truffle.js.nodes.control.VoidBlockNode.execute(VoidBlockNode.java:61)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.control.IfNode.doBoolean(IfNode.java:183)
	at com.oracle.truffle.js.nodes.control.IfNodeGen.execute_boolean0(IfNodeGen.java:105)
	at com.oracle.truffle.js.nodes.control.IfNodeGen.execute(IfNodeGen.java:89)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.builtins.ArrayPrototypeBuiltins$ArrayForEachIndexCallOperation$DefaultCallbackNode.apply(ArrayPrototypeBuiltins.java:2256)
	at com.oracle.truffle.js.nodes.access.ForEachIndexCallNode.callback(ForEachIndexCallNode.java:205)
	at com.oracle.truffle.js.nodes.access.ForEachIndexCallNode$ForwardForEachIndexCallNode.executeForEachIndexFast(ForEachIndexCallNode.java:241)
	at com.oracle.truffle.js.nodes.access.ForEachIndexCallNode.executeForEachIndex(ForEachIndexCallNode.java:140)
	at com.oracle.truffle.js.builtins.ArrayPrototypeBuiltins$ArrayForEachIndexCallOperation.forEachIndexCall(ArrayPrototypeBuiltins.java:2271)
	at com.oracle.truffle.js.builtins.ArrayPrototypeBuiltins$JSArrayForEachNode.forEach(ArrayPrototypeBuiltins.java:2399)
	at com.oracle.truffle.js.builtins.ArrayPrototypeBuiltinsFactory$JSArrayForEachNodeGen.execute(ArrayPrototypeBuiltinsFactory.java:2067)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:723)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeVoid(OptimizedBlockNode.java:137)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:68)
	at com.oracle.truffle.js.nodes.control.VoidBlockNode.execute(VoidBlockNode.java:61)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:116)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.control.ReturnNode$TerminalPositionReturnNode.execute(ReturnNode.java:178)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:593)
	at com.oracle.truffle.runtime.OptimizedIndirectCallNode.call(OptimizedIndirectCallNode.java:70)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$GenericJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1688)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic3(JSWriteCurrentFrameSlotNodeGen.java:136)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:67)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.executeVoid(DiscardResultNode.java:86)
	at com.oracle.truffle.js.nodes.control.TryFinallyNode.executeVoid(TryFinallyNode.java:105)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:92)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:116)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:80)
	at com.oracle.truffle.js.nodes.control.IfNode.doBoolean(IfNode.java:183)
	at com.oracle.truffle.js.nodes.control.IfNodeGen.execute_boolean0(IfNodeGen.java:105)
	at com.oracle.truffle.js.nodes.control.IfNodeGen.execute(IfNodeGen.java:89)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:723)
	at com.oracle.truffle.js.nodes.control.ReturnNode$TerminalPositionReturnNode.execute(ReturnNode.java:178)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:116)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:593)
	at com.oracle.truffle.runtime.OptimizedIndirectCallNode.call(OptimizedIndirectCallNode.java:70)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$GenericJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1688)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic3(JSWriteCurrentFrameSlotNodeGen.java:136)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:67)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.executeVoid(DiscardResultNode.java:86)
	at com.oracle.truffle.js.nodes.control.TryFinallyNode.executeVoid(TryFinallyNode.java:105)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:92)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:116)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:527)
	at com.oracle.truffle.js.nodes.control.ReturnNode$TerminalPositionReturnNode.execute(ReturnNode.java:178)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:723)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.BlockScopeNode.execute(BlockScopeNode.java:87)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:610)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:723)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:165)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:78)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeVoid(OptimizedBlockNode.java:137)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:68)
	at com.oracle.truffle.js.nodes.control.VoidBlockNode.execute(VoidBlockNode.java:61)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:83)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:53)
	at com.oracle.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:94)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:70)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:38)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:155)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:610)
	at com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1330)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
	at com.oracle.truffle.js.nodes.interop.JSInteropInvokeNode.doCached(JSInteropInvokeNode.java:79)
	at com.oracle.truffle.js.nodes.interop.JSInteropInvokeNodeGen.execute(JSInteropInvokeNodeGen.java:92)
	at com.oracle.truffle.js.runtime.objects.JSObject.invokeMember(JSObject.java:256)
	at com.oracle.truffle.js.runtime.objects.JSObjectGen$InteropLibraryExports$Cached.invokeMember(JSObjectGen.java:509)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.invokeOrExecute(PolyglotObjectProxyHandler.java:253)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.doCachedMethod(PolyglotObjectProxyHandler.java:226)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ProxyInvokeNodeGen.execute(PolyglotObjectProxyHandlerFactory.java:204)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ObjectProxyNode.doDefault(PolyglotObjectProxyHandler.java:159)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ObjectProxyNodeGen.executeImpl(PolyglotObjectProxyHandlerFactory.java:99)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:678)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:610)
	at com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:573)
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:112)
	at jdk.proxy2.$Proxy59.send
	at org.enso.ydoc.server.YjsChannelSynchronized.lambda$send$0(YjsChannelSynchronized.java:30)
	at org.enso.ydoc.server.YjsChannelSynchronized$$Lambda/0x000000000fa3dc68.run
	at org.enso.ydoc.server.YdocScheduledExecutorService.processPendingTasks(YdocScheduledExecutorService.java:442)
	at org.enso.ydoc.server.Ydoc.runEventLoopUntil(Ydoc.java:274)
	at org.enso.ydoc.server.Ydoc.runEventLoopBlocking(Ydoc.java:290)
	at org.enso.ydoc.server.Ydoc.start(Ydoc.java:264)
	at org.enso.ydoc.server.Main.launch(Main.java:44)
	at java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(DirectMethodHandle$Holder)
	at java.lang.invoke.LambdaForm$MH/0x000000000f730c00.invoke(LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:372)
	at com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeHandle.executeImpl(GuestToHostCodeCache.java:88)
	at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:626)
	at com.oracle.truffle.runtime.OptimizedRuntimeSupport.callInlined(OptimizedRuntimeSupport.java:292)
	at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:408)
	at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:906)
	at com.oracle.truffle.host.HostExecuteNode.doSingleUncached(HostExecuteNode.java:252)
	at com.oracle.truffle.host.HostExecuteNodeGen$Uncached.execute(HostExecuteNodeGen.java:772)
	at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:465)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Uncached.invokeMember(HostObjectGen.java:8778)
	at com.oracle.truffle.api.interop.InteropLibraryGen.genericDispatch(InteropLibraryGen.java:328)
	at com.oracle.truffle.api.library.ReflectionLibraryDefault$Send.doSendGeneric(ReflectionLibrary.java:193)
	at com.oracle.truffle.api.library.ReflectionLibraryDefaultGen$ReflectionLibraryExports$Uncached.send(ReflectionLibraryDefaultGen.java:195)
	at com.oracle.truffle.api.library.ReflectionLibraryGen$UncachedDispatch.send(ReflectionLibraryGen.java:188)
	at org.enso.jvm.interop.impl.OtherJvmMessage.apply(OtherJvmMessage.java:56)
	at org.enso.jvm.interop.impl.OtherJvmMessage.apply(OtherJvmMessage.java:25)
	at org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:316)
	at org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:299)
	at org.enso.jvm.channel.Channel.toDirectMessage(Channel.java:378)
	at org.enso.jvm.channel.Channel.executeImpl(Channel.java:430)
	at org.enso.jvm.channel.Channel.execute(Channel.java:250)
	at org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:219)
	at org.enso.jvm.interop.impl.OtherJvmObject.send(OtherJvmObject.java:188)
	at org.enso.jvm.interop.impl.OtherJvmObjectGen$ReflectionLibraryExports$Cached.send(OtherJvmObjectGen.java:72)
	at com.oracle.truffle.api.interop.InteropLibraryGen$Proxy.invokeMember(InteropLibraryGen.java:2899)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4823)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:9167)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9119)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNode.doDefault(PolyglotValueDispatch.java:4863)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9316)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:678)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
	at com.oracle.truffle.runtime.OptimizedRuntimeSupport.callProfiled(OptimizedRuntimeSupport.java:308)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2682)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:1159)
	at org.enso.ydoc.server.registration.YdocServerImpl.runYdocServer(YdocServerImpl.java:46)
	at org.enso.ydoc.api.YdocServerApi.launchYdocServer(YdocServerApi.java:21)
	at org.enso.languageserver.boot.MainModule.$anonfun$ydoc$2(MainModule.scala:560)
	at org.enso.languageserver.boot.MainModule$$Lambda/0x000000000f68dd48.run
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.lang.Thread.runWith(Thread.java:1487)
	at java.lang.Thread.run(Thread.java:1474)
```

### Misconfigured Logger!

- The logging comes from `Histogram` in `org.enso.persist` framework. 
- however that logging should be **disabled**!
- instead the logger has `isTraceEnabled()`!
- how to reconfigure that @4e6?

```
"Ydoc main thread"
	at ch.qos.logback.classic.Logger.createChildByName(Logger.java:362)
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:156)
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:54)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:432)
	at org.enso.logging.config.systemlogger.SystemLoggerViaSlf4j.getLogger(SystemLoggerViaSlf4j.java:14)
	at jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:396)
	at jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:418)
	at java.lang.System.getLogger(System.java:1461)
	at org.enso.persist.PerUtils.<clinit>(PerUtils.java:8)
	at org.enso.persist.PerGenerator.writeObject(PerGenerator.java:40)
	at org.enso.persist.Persistance$Pool.write(Persistance.java:300)
	at org.enso.jvm.channel.Channel.executeImpl(Channel.java:415)
	at org.enso.jvm.channel.Channel.execute(Channel.java:250)
	at org.enso.jvm.interop.api.OtherJvmClassLoader.addPath(OtherJvmClassLoader.java:142)
	at org.enso.jvm.interop.api.OtherJvmClassLoader.addPath(OtherJvmClassLoader.java:85)
	at org.enso.ydoc.server.registration.YdocServerImpl.runYdocServer(YdocServerImpl.java:41)
	at org.enso.ydoc.api.YdocServerApi.launchYdocServer(YdocServerApi.java:21)
	at org.enso.languageserver.boot.MainModule.$anonfun$ydoc$2(MainModule.scala:560)
	at org.enso.languageserver.boot.MainModule$$Lambda/0x0000000093690fd8.run
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.lang.Thread.runWith(Thread.java:1487)
	at java.lang.Thread.run(Thread.java:1474)
```

File: app/ydoc-channel/src/YjsChannel.ts (hunk 49 above)
Comment (4e6) [reply app/ydoc-channel/src/YjsChannel.ts]: You're right. Fixed and added tests to YjsChannel test suite

**Comment by farmaazon** [comment]
I get these log on every project open:
 
image

**Comment by 4e6** [comment]
> I get these log on every project open

Before, the WebSocket server was ready right after the language server was started. And the gui was able to send `session/initProtocolConnection`
Now, the language server needs to wait until the truffle context is initialized (for Java/JS interop), and only then it can start to process messages. That's why the first couple of requests are timed out

**Comment by farmaazon** [comment]
> That's why the first couple of requests are timed out

Then maybe it's worth extending timeouts for WS connection?

File: app/gui/integration-test/mock/localApi.ts [hunk 50]
```diff
@@ -413,14 +383,85 @@ export async function mockLocalApi(page: Page) {
...
+    }
+
+    /** Set up the mock binary data channel handler */
+    function setupMockDataChannel(channel: YjsChannel<Uint8Array>) {
+      // Also set the global dataChannel for updateVisualization API
+      dataChannel = channel
+      channel.subscribe(async (messageRaw) => {
+        let data: ArrayBuffer
+        if (typeof messageRaw === 'string') {
+          data = new TextEncoder().encode(messageRaw).buffer as ArrayBuffer
```
Comment (farmaazon) [inline app/gui/integration-test/mock/localApi.ts]: The messageRaw has type UInt8Array, according to the typechecker. If it may be a string or ArrayBuffer, then there's something screwed in our types.

File: app/gui/integration-test/mock/localApi.ts [hunk 51]
```diff
@@ -413,14 +383,85 @@ export async function mockLocalApi(page: Page) {
...
+        } else if (messageRaw instanceof ArrayBuffer) {
+          data = messageRaw
+        } else if (messageRaw instanceof Uint8Array) {
+          // Important: Use slice to get a copy of just the relevant portion
+          // because messageRaw.buffer may include data beyond the Uint8Array's view
+          data = messageRaw.buffer.slice(
+            messageRaw.byteOffset,
+            messageRaw.byteOffset + messageRaw.byteLength,
+          ) as ArrayBuffer
```
Comment (farmaazon) [inline app/gui/integration-test/mock/localApi.ts]: I'd prefer instanceof assertion over this cast (at least in DEV:).

File: app/gui/integration-test/mock/localApi.ts [hunk 52]
```diff
@@ -413,14 +383,85 @@ export async function mockLocalApi(page: Page) {
...
+          channel.send(new Uint8Array(response))
+        }
+      })
+    }
+
     await page.routeWebSocket(`${ydocAddressBase}/**`, (wsRoute) => {
       const parsedUrl = new URL(wsRoute.url())
       const room = parsedUrl.pathname.substring('/project/'.length)
+      const lsUrl = parsedUrl.searchParams.get('ls')
+      const dataUrl = parsedUrl.searchParams.get('data')
```
Comment (farmaazon) [inline app/gui/integration-test/mock/localApi.ts]: What are these URLs? Cannot we have just a constant name for Yjs channels?

File: app/gui/src/project-view/util/net/dataServer.ts [hunk 53]
```diff
@@ -60,20 +61,27 @@ export class DataServer extends ObservableV2<DataServerEvents> {
   /** `websocket.binaryType` should be `ArrayBuffer`. */
   constructor(
     public clientId: string,
-    public websocket: WebSocket,
+    public websocket: YjsChannel,
```
Comment (farmaazon) [inline app/gui/src/project-view/util/net/dataServer.ts]: If this is no longer websocket, let's change that name.

**Comment by JaroslavTulach** [comment]
> > I get these log on every project open
> Then maybe it's worth extending timeouts for WS connection?

+1

> Before, the WebSocket server was ready right after the language server was started. And the gui was able to send `session/initProtocolConnection` Now, the language server needs to wait until the truffle context is initialized (for Java/JS interop), and only then it can start to process messages. That's why the first couple of requests are timed out

Yeah, the initialization of Y.js infrastructure certainly takes a bit more time. We can look at ways to speed it up, but increasing timeout is probably the best option if we want to get this integrated soon (I'd like to see this integrated).

File: app/ydoc-channel/src/YjsChannel.ts [hunk 54]
```diff
@@ -0,0 +1,294 @@
...
+  /**
+   * Subscribes to messages received from other parties.
+   * @param handler - The callback to invoke when a message is received
+   * @returns A function to unsubscribe the handler
+   */
+  subscribe(handler: MessageHandler<T>): () => void {
+    this.handlers.add(handler)
+
+    // Process any existing items in the array that arrived before subscription
+    // This handles the race condition where messages arrive before observers are attached
```
Comment (farmaazon) [inline app/ydoc-channel/src/YjsChannel.ts:153]: The fact we're processing old messages is worth mentioning in the method docs.

Also, the case of subscribing when they're already messages could be added to those nice unit tests.

File: app/ydoc-channel/src/YjsChannel.ts [hunk 55]
```diff
@@ -0,0 +1,294 @@
...
+    if (this.array.length > 0) {
+      this.doc.transact(() => {
+        while (this.array.length > 0) {
+          const item = this.array.get(0)
+          try {
+            handler(item)
+          } catch (e) {
+            const error = new Error(`Failed to handle existing message: ${e}`)
+            ;(error as any).target = e
```
Comment (farmaazon) [inline app/ydoc-channel/src/YjsChannel.ts]: Why do we put it as a `target` and not as a `cause`?

File: app/ydoc-server/src/ydoc.ts [hunk 56]
```diff
@@ -96,30 +98,45 @@ export class WSSharedDoc {
...
   docName: string,
+  byteBuffer: any,
+  jsonChannelCallbacks: YjsChannelCallbacks,
+  binaryChannelCallbacks: YjsChannelCallbacks,
 ): void {
-  console.log(`setupGatewayClient(${lsUrl ? 'lsUrl: ' + lsUrl : 'no lsUrl'}, docName: ${docName})`)
-  const lsSession = getSessionForUrl(lsUrl)
+  console.log(
+    `setupGatewayClient(${lsUrl ? 'lsUrl: ' + lsUrl : 'no lsUrl'}, ${dataUrl ? 'dataUrl: ' + dataUrl : 'no dataUrl'} docName: ${docName}), byteBuffer: ${byteBuffer}, jsonChannelCallbacks: ${jsonChannelCallbacks}, binaryChannelCallbacks: ${binaryChannelCallbacks}`,
+  )
```
Comment (farmaazon) [inline app/ydoc-server/src/ydoc.ts:109]: I'm not sure if this log was intended to stay :)

But we may at least making it more "readable" (like "Setting up Gateway Client:")

File: app/ydoc-server/src/YjsBinaryChannel.ts [hunk 57]
```diff
@@ -0,0 +1,82 @@
...
+}
+
+/**
+ * A {@link YjsChannel} for binary protocol communication with the Language Server.
+ *
+ * Extends YjsChannel to handle binary data by converting between JavaScript Uint8Array
+ * and Java direct ByteBuffer. This enables efficient binary message transfer between
+ * the Ydoc server (JavaScript) and the Language Server (Java/Scala).
+ */
+export class YjsBinaryChannel extends YjsChannel<any> {
```
Comment (farmaazon) [inline app/ydoc-server/src/YjsBinaryChannel.ts]: `unknown` is better than `any` because enfroces type checks.

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala (hunk 48 above)
Comment (JaroslavTulach) [reply engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala:556]: - @4e6 has inherited the API from me
- originally it made sense to return `AutoClosable` as a handle to close the _other JVM_
- but the behavior had to be changed to _never return_ from the `launchYdocServer` method
- the _calling thread_ is re-used inside the method as JavaScript's _event queue_
- returning Scala's `Nothing` would be the best value - but probably just return Java `void`

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala [hunk 58]
```diff
@@ -557,7 +557,8 @@ class MainModule(serverConfig: LanguageServerConfig, logLevel: Level) {
           c.hostname,
           c.port,
           jsonRpcServer.yjsChannelCallbacks,
-          binaryChannelCallbacks
+          binaryChannelCallbacks,
+          logLevel
```
Comment (JaroslavTulach) [inline engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala]: - the 61d6e25a42 change broke native image
```
app/gui dev:vite: Exception in thread "Ydoc main thread" org.graalvm.nativeimage.MissingReflectionRegistrationError: Cannot reflectively invoke method 'public static java.lang.AutoCloseable org.enso.ydoc.server.Main.launch(java.lang.String,java.lang.String,org.enso.ydoc.api.YjsChannelCallbacks,org.enso.ydoc.api.YjsChannelCallbacks,java.lang.String) throws java.io.IOException'. To allow this operation, add the following to the 'reflection' section of 'reachability-metadata.json' and rebuild the native image:
app/gui dev:vite:   {
app/gui dev:vite:     "type": "org.enso.ydoc.server.Main",
app/gui dev:vite:     "methods": [
app/gui dev:vite:       {
app/gui dev:vite:         "name": "launch",
app/gui dev:vite:         "parameterTypes": [
app/gui dev:vite:           "java.lang.String",
app/gui dev:vite:           "java.lang.String",
app/gui dev:vite:           "org.enso.ydoc.api.YjsChannelCallbacks",
app/gui dev:vite:           "org.enso.ydoc.api.YjsChannelCallbacks",
app/gui dev:vite:           "java.lang.String"
app/gui dev:vite:         ]
app/gui dev:vite:       }
app/gui dev:vite:     ]
app/gui dev:vite:   }
app/gui dev:vite: The 'reachability-metadata.json' file should be located in 'META-INF/native-image/<group-id>/<artifact-id>/' of your project. For further help, see https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection
app/gui dev:vite:       at org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:1159)
app/gui dev:vite:       at org.enso.ydoc.server.registration/org.enso.ydoc.server.registration.YdocServerImpl.runYdocServer(YdocServerImpl.java:48)
app/gui dev:vite:       at org.enso.ydoc.api/org.enso.ydoc.api.YdocServerApi.launchYdocServer(YdocServerApi.java:23)
app/gui dev:vite:       at org.enso.languageserver.boot.MainModule.$anonfun$ydoc$2(MainModule.scala:561)
app/gui dev:vite:       at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
app/gui dev:vite:       at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
app/gui dev:vite:       at java.base@25.0.1/java.lang.Thread.runWith(Thread.java:1487)
app/gui dev:vite:       at java.base@25.0.1/java.lang.Thread.run(Thread.java:1474)
app/gui dev:vite:       at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
app/gui dev:vite:       at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
```

Comment (JaroslavTulach) [reply engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala]: Fixed in 7ab0e914e

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmPool.java [hunk 59]
```diff
@@ -227,18 +235,7 @@ private final synchronized OtherJvmLoader loader(Channel<OtherJvmPool> channel)
    *    --vm.D=polyglot.enso.classLoading=guest
    *    --run test/Generic_JDBC_Tests
```
Comment (JaroslavTulach) [inline lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmPool.java:237]: - with the changes done in 610f0a2b6c the "profiling of messages" finally works on _native image_
- the problem was that the `org.enso.jvm.interop.limit` was only read at image build time, not at runtime
- running with
```
ENSO_ENGINE_ARGS=--vm.D=org.enso.jvm.interop.limit=1000 corepack pnpm dev:gui
```
- seems to print following into `~/.local/share/enso/log/enso-language-server-*.log` file:
```
======== Interop JVM Messages Chart in last 100953 ms ========
     989 Message[Object com.oracle.truffle.api.interop.InteropLibrary.invokeMember(Object,String,Object[])(Object, String, Object[])
          at jdk.proxy4/jdk.proxy4.$Proxy/s1c13a8ec.subscribe(Unknown Source)
          at org.enso.jsonrpc.YdocJsonRpcServer$ServerCallbacks.onConnect(YdocJsonRpcServer.scala:99)
          at java.base@25.0.1/java.lang.reflect.Method.invoke(Method.java:565)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.reflectInvoke(HostMethodDesc.java:306)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.invoke(HostMethodDesc.java:291)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeReflect.executeImpl(GuestToHostCodeCache.java:110)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
          at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
       5 Message[boolean com.oracle.truffle.api.interop.InteropLibrary.hasMembers(Object)(Object)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:329)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:312)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.acceptRequestFromHotSpotJvm(Channel.java:306)
          at org.enso.jvm.channel/org.enso.jvm.channel.JNI$CallStaticLongMethodA.call(JNI.java)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.toHotSpotMessage(Channel.java:356)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.executeImpl(Channel.java:437)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.execute(Channel.java:263)
          at org.enso.jvm.interop/org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:228)
       1 Message[long com.oracle.truffle.api.interop.InteropLibrary.asPointer(Object)(Object)
          at org.graalvm.polyglot/org.graalvm.polyglot.Value.asNativePointer(Value.java:1564)
          at org.enso.languageserver.http.server.BinaryYdocServer$BinaryServerCallbacks.onMessage(BinaryYdocServer.scala:67)
          at org.enso.languageserver.http.server.BinaryYdocServer$BinaryServerCallbacks.$anonfun$onConnect$1(BinaryYdocServer.scala:50)
          at java.base@25.0.1/java.lang.reflect.Method.invoke(Method.java:565)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.reflectInvoke(HostMethodDesc.java:306)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.invoke(HostMethodDesc.java:291)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeReflect.executeImpl(GuestToHostCodeCache.java:110)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
       1 Message[long com.oracle.truffle.api.interop.InteropLibrary.getBufferSize(Object)(Object)
          at org.graalvm.polyglot/org.graalvm.polyglot.Value.getBufferSize(Value.java:500)
          at org.enso.languageserver.http.server.BinaryYdocServer$BinaryServerCallbacks.onMessage(BinaryYdocServer.scala:69)
          at org.enso.languageserver.http.server.BinaryYdocServer$BinaryServerCallbacks.$anonfun$onConnect$1(BinaryYdocServer.scala:50)
          at java.base@25.0.1/java.lang.reflect.Method.invoke(Method.java:565)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.reflectInvoke(HostMethodDesc.java:306)
          at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.invoke(HostMethodDesc.java:291)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeReflect.executeImpl(GuestToHostCodeCache.java:110)
          at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
       1 Message[boolean com.oracle.truffle.api.interop.InteropLibrary.isInstantiable(Object)(Object)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:329)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:312)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.acceptRequestFromHotSpotJvm(Channel.java:306)
          at org.enso.jvm.channel/org.enso.jvm.channel.JNI$CallStaticLongMethodA.call(JNI.java)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.toHotSpotMessage(Channel.java:356)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.executeImpl(Channel.java:437)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.execute(Channel.java:263)
          at org.enso.jvm.interop/org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:228)
       1 Message[boolean com.oracle.truffle.api.interop.InteropLibrary.isBoolean(Object)(Object)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:329)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:312)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.acceptRequestFromHotSpotJvm(Channel.java:306)
          at org.enso.jvm.channel/org.enso.jvm.channel.JNI$CallStaticLongMethodA.call(JNI.java)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.toHotSpotMessage(Channel.java:356)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.executeImpl(Channel.java:437)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.execute(Channel.java:263)
          at org.enso.jvm.interop/org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:228)
       1 Message[boolean com.oracle.truffle.api.interop.InteropLibrary.isExecutable(Object)(Object)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:329)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:312)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.acceptRequestFromHotSpotJvm(Channel.java:306)
          at org.enso.jvm.channel/org.enso.jvm.channel.JNI$CallStaticLongMethodA.call(JNI.java)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.toHotSpotMessage(Channel.java:356)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.executeImpl(Channel.java:437)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.execute(Channel.java:263)
          at org.enso.jvm.interop/org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:228)
       1 Message[boolean com.oracle.truffle.api.interop.InteropLibrary.isNumber(Object)(Object)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannelThrow(Channel.java:329)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.handleWithChannel(Channel.java:312)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.acceptRequestFromHotSpotJvm(Channel.java:306)
          at org.enso.jvm.channel/org.enso.jvm.channel.JNI$CallStaticLongMethodA.call(JNI.java)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.toHotSpotMessage(Channel.java:356)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.executeImpl(Channel.java:437)
          at org.enso.jvm.channel/org.enso.jvm.channel.Channel.execute(Channel.java:263)
          at org.enso.jvm.interop/org.enso.jvm.interop.impl.OtherJvmObject.executeMessage(OtherJvmObject.java:228)
```
- with 428bc604b7 we should also see message counts from the YdocServer JVM

Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmPool.java:237]: ### Analysis of the Dumped Histogram

- please note the small limit - just `1000` - e.g. there isn't many messages 
- most of them is `invokeMember` at `YdocJsonRpcServer$ServerCallbacks.onConnect`
- e.g. exactly what we'd be expecting to see
- so far it doesn't seem the `org.enso.jvminterop` overhead would be the problem

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java [hunk 60]
```diff
@@ -55,6 +57,9 @@ public record OtherJvmMessage(long id, Message message, List<Object> args)
         var seg = MemorySegment.ofBuffer(buf);
         return new ReturnValue<>(seg.address());
       }
+      if (message == READ_BUFFER_BYTE) {
+        System.err.println("read buffer byte with " + args);
```
Comment (JaroslavTulach) [inline lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: I am seeing pretty much of these messages. Both in _native image_ as well as in `--jvm` mode. My engine is built with:
```
ENSO_LAUNCHER=debug,native sbt buildNativeImage
```
and then executed as:
```
ENSO_ENGINE_ARGS="--jvm" corepack pnpm dev:gui
```
or without the `ENSO_ENGINE_ARGS` being defined at all.

Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: First reading of 1024 bytes one by one is triggered by

reading byte by byte

probably it is the `Unit8Array` constructor (doing conversion?) from `c`. What type is `c`?

Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: Let's do the conversion to _direct byte buffer_ explicitly before passing the `ByteBuffer` to JavaScript: 2c947cb0496d4fac6e83d349ed498acd72ffe143 ... with additional 570f8a1 

~Scheduling [nightly release](https://github.com/enso-org/enso/actions/runs/23015725503) - is it faster, @4e6?~

A [nightly release](https://github.com/enso-org/enso/actions/runs/23047602417) scheduled.

Comment (4e6) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: For me visualizations are not displaying in that nightly. Need to debug

Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: - ~I don't see the visualization with `2026.1.1-nightly.2026.3.9.1` either!~
- trying to find a build where visualizations are working 
    - certainly they are working at `2026.1.1-nightly.2026.3.9`
    - I did all the `git bisect`ing just to find out I had _some debris on local disk_!
 - 570f8a1 - is the fix
 - scheduling [new nightly release](https://github.com/enso-org/enso/actions/runs/23047602417) from the 570f8a1 comit

Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: - I tried to open the huge project and wait until it renders all  the 570f8a1 version did it in `25:27.016 - 23:45.76` - e.g. roughly in **105s**
   - PS: It would really help to have a standardized benchmark that waits until all visualizations are rendered and measures that time properly
- the `2026.1.1-nightly.2026.3.11` version opened the project in roughly **60s**
- e.g. (if you see similar results), then we still have some things to speed up

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java [hunk 61]
```diff
@@ -27,7 +28,23 @@ final class YjsChannelSynchronized implements YjsChannel {
...
   @Override
   public void send(Object message) {
-    executor.submit(() -> channel.send(message));
+    executor.submit(
+        () -> {
+          Object toSent;
+          if (message instanceof String s) {
+            toSent = s;
+          } else {
+            var v = Value.asValue(message);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java:37]: - This is extracting the _other_ `ByteBuffer` from the `Value` 
- and creating own `ByteBuffer` at the same address. 
- just like https://github.com/enso-org/enso/blob/570f8a151de6bce0eb0952949d6912c085d4aeb3/engine/language-server/src/main/scala/org/enso/languageserver/http/server/BinaryYdocServer.scala#L67-L70 does when JavaScript is calling back

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java [hunk 62]
```diff
@@ -27,7 +28,23 @@ final class YjsChannelSynchronized implements YjsChannel {
...
+            if (v.hasBufferElements() && v.isNativePointer()) {
```
Comment (4e6) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java]: Btw, we don't need to check that because we know (by implementation) that the message is either a string or direct byte buffer

Comment (JaroslavTulach) [reply lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/YjsChannelSynchronized.java]: OK, done in d81929c3b9. Probably it would be better to get exception as soon as possible if the value wasn't a direct buffer with native pointer.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java (hunk 4 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Main.java]: - some work on such a removal is being done in #14871
- at least in the test: https://github.com/enso-org/enso/pull/14871/changes#r2934684951 - where it works
- removal from production code https://github.com/enso-org/enso/pull/14871/changes#r2936295987 still needs some bugfixing

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java (hunk 3 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: Done in 2bbc0020a5

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java (hunk 60 above)
Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java:61]: I believe there are no major issues anymore. The message transport is at the same "magnitude" as it was.

File: lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java [hunk 63]
```diff
@@ -113,12 +122,12 @@ public static final class DelegateYjsChannelCallbacks implements YjsChannelCallb
...
       @Override
       public void onConnect(YjsChannel channel) {
-        System.err.println("Enter onConnect[" + name + "] with " + channel + " for " + delegate);
+        log.trace("Enter onConnect[{}] with {} for {}", name, channel, delegate);
         if (delegate != null) {
           var wrap = new DelegateYjsChannel(channel);
           delegate.onConnect(wrap);
         }
-        System.err.println("Exit onConnect[" + name + "] with " + channel);
+        log.trace("Exit onConnect[{}] with {}", name, channel);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: - replacing `System.err.println` with proper logging is the right choice
- however I am not very happy seeing the dependencies changed in 61d6e25a4271419c304473ffb8eb4c61d4f30694
- it would be way better if the [logging worked](https://github.com/enso-org/enso/blob/68abf1196ac7cf97f0519fbda65463db1babad81/docs/infrastructure/logging.md#custom-log-levels) just by specifying some property like `-Dakka.actor.Logger.level=info`
- with #14853 & co. integrated...
- such a logging should work out of the box, without 61d6e25a4271419c304473ffb8eb4c61d4f30694
- but maybe it is broken - I'll investigate

Comment (JaroslavTulach) [reply lib/java/ydoc-server/src/main/java/org/enso/ydoc/server/Ydoc.java]: - logging from `ydoc-server` NI compiled module is being improved in #14878

File: app/ydoc-server/src/YjsBinaryChannel.ts [hunk 64]
```diff
@@ -71,7 +71,8 @@ export class YjsBinaryChannel extends YjsChannel<any> {
 
   /** Wraps the handler to convert incoming Uint8Array to Java direct ByteBuffer. */
   override subscribe(handler: MessageHandler<JavaByteBuffer>): () => void {
-    const f = (contents: Uint8Array) => {
+    const f = (message: unknown) => {
+      const contents = message as Uint8Array
```
Comment (farmaazon) [inline app/ydoc-server/src/YjsBinaryChannel.ts]: If we rely on message being Uint8Array, why we just don't extend `YjsChannel<Uint8Array>` above?

File: app/ydoc-server/src/languageServerSession.ts [hunk 65]
```diff
@@ -89,7 +89,7 @@ export class LanguageServerSession {
   static sessions: Map<string, LanguageServerSession> = new Map<string, LanguageServerSession>()
 
   /** Get a {@link LanguageServerSession} by its URL. */
-  static get(url: string, callbacks: YjsChannelCallbacks): LanguageServerSession {
+  static get(url: string, callbacks: YjsChannelServer): LanguageServerSession {
```
Comment (farmaazon) [inline app/ydoc-server/src/languageServerSession.ts:92]: If the type is called "server", the vars could also be renamed to server: here and in other places.

File: app/ydoc-server/src/YjsBinaryChannel.ts (hunk 64 above)
Comment (4e6) [reply app/ydoc-server/src/YjsBinaryChannel.ts]: We pass this channel to the Java that sends and receives (subscribes to) Java `ByteBuffer` represented as 
```ts
type JavaByteBuffer = number & { readonly __brand: 'JavaByteBuffer' }
```
Yjs does not understand `ByteBuffer` so we convert it to the `Uint8Array` before passing it to Yjs.

We still need to extend the `YjsChannel` to use it as `Observable` (methods like `on`, `off`)

File: app/ydoc-server/src/languageServerSession.ts (hunk 65 above)
Comment (4e6) [reply app/ydoc-server/src/languageServerSession.ts:92]: That was a leftover from the refactoring. Updated

File: app/ydoc-server/src/YjsBinaryChannel.ts (hunk 64 above)
Comment (4e6) [reply app/ydoc-server/src/YjsBinaryChannel.ts]: I refactored the code to avoid such type casts

File: docs/infrastructure/ydoc.md [hunk 66]
```diff
@@ -0,0 +1,169 @@
...
+```java
+public interface YjsChannel.Server {
+  void onConnect(YjsChannel channel);
+}
+```
+
+Two callback instances are passed to the Ydoc server at startup:
+
+- `YDOC_JSON_CHANNEL_CALLBACKS` - For JSON-RPC text messages
+- `YDOC_BINARY_CHANNEL_CALLBACKS` - For binary protocol messages
```
Comment (JaroslavTulach) [inline docs/infrastructure/ydoc.md:104]: - There is also `YDOC_LS_DEBUG` ...
- I don't know how it can be used and what it influences...
- it might be documented here ...
- or in the [debugging document](https://github.com/enso-org/enso/blob/bb77f57b70330892758d75fa9dc9faba7e097640/docs/debugger/README.md)

File: lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala (hunk 41 above)
Comment (JaroslavTulach) [reply lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala:42]: This one is still valid, but it can be addressed in a separate PR...

File: app/ydoc-channel/src/YjsChannel.ts [hunk 67]
```diff
@@ -23,7 +33,7 @@ export interface YjsChannelServer<T = unknown> {
    * Called when a new channel is established.
    * @param channel - The newly connected channel
    */
-  onConnect(channel: YjsChannel<T>): void
+  onConnect(channel: YjsChannel<T, any>): void
```
Comment (farmaazon) [inline app/ydoc-channel/src/YjsChannel.ts]: Can it be `unknown`?

File: app/ydoc-channel/src/YjsChannel.ts [hunk 68]
```diff
@@ -258,6 +274,14 @@ export class YjsChannel<T = unknown> extends ObservableV2<WebSocketEventHandlers
...
   }
 
+  private encode(message: TMessage): TStored {
+    return this.codec ? this.codec.encode(message) : (message as unknown as TStored)
+  }
+
+  private decode(stored: TStored): TMessage {
+    return this.codec ? this.codec.decode(stored) : (stored as unknown as TMessage)
+  }
+
```
Comment (farmaazon) [inline app/ydoc-channel/src/YjsChannel.ts]: I think I would prefer enforcing codec and creating a constant "identity" codec to this casting...

**Review by farmaazon — APPROVED** [review]

File: app/ydoc-channel/src/YjsChannel.ts (hunk 68 above)
Comment (4e6) [reply app/ydoc-channel/src/YjsChannel.ts]: Updated

File: lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala (hunk 41 above)
Comment (JaroslavTulach) [reply lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala:42]: - reported as #14889
