### PR TITLE
ResourceManagerTest to verify resources are cleaned on ctx.close()

### LINKED ISSUE #6472: Exception from ResourceManager at end of execution
Recently when running Enso I got:
```
Exception in thread "Thread-14" java.lang.IllegalStateException: Language environment is already disposed.
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.checkDisposed(TruffleLanguage.java:1671)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.submitThreadLocalInternal(TruffleLanguage.java:3462)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.submitThreadLocal(TruffleLanguage.java:3435)
        at org.enso.interpreter.runtime.ResourceManager.scheduleFinalizationAtSafepoint(ResourceManager.java:122)
        at org.enso.interpreter.runtime.ResourceManager$Runner.run(ResourceManager.java:201)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:65)
```

printed after all logs of my program.

The program exited with exit code 0, so it's not a big issue, but it may be a bit confusing.

The exception should probably be caught somewhere.

I'm not sure how I can repro it consistently but @JaroslavTulach said just the stacktrace will be sufficient for this report.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Demonstration of the ideal behavior of #6472 - the test seems to be working just fine.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/interpreter/runtime/ResourceManagerTest.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+                  .asHostObject();
+
+      ensoContext.getResourceManager().register(obj, fn);
+      assertNull("Not invoked yet", fn.args);
+    }
+
+    assertNotNull("Callback invoked when thread closed", fn.args);
+    assertNotNull("Callback invoked with one argument", fn.args.length);
+    assertEquals("Called by our thread", fn.thread, Thread.currentThread());
+    assertEquals("Callback called for SomeObject", obj, fn.args[0]);
```
Comment (radeusgd) [inline engine/runtime/src/test/java/org/enso/interpreter/runtime/ResourceManagerTest.java]: What is `SomeObject` here? It does not seem to refer to anything in this test which is slightly confusing.

Shall we rename this? e.g.
```suggestion
    assertEquals("Callback called for the registered `obj`", obj, fn.args[0]);
```

**Review by radeusgd — APPROVED** [review]

**Review by Akirathan — APPROVED** [review]
