### PR TITLE
Fixes from the Demo on 2nd March

### LINKED ISSUE #5809: Follow up on issues from Werner demo
- Format error getting swallowed.
- Millisecond parsing and common single format for all parsing.
- Performance of the parsing the column very slow (1.2s in Java - profile)
- CrossTab should allow Group_By columns.

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

- Fix issue with Geo Map viz.
- Handle invalid format strings better in `Data_Formatter`.
- New constants for the ISO format strings (and a special ENSO_ZONED_DATE_TIME)
- Consistent Date Time format for parsing in all places.
- Avoid throwing exception in datetime parsing.
- Support for milliseconds (well nanoseconds) in Date_Time and Time_Of_Day.
- `Column.map` stays within Enso.
- Allow `Aggregate_Column.Group_By` in `cross_tab` group_by parameter.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java [hunk 1]
```diff
@@ -72,11 +71,18 @@ public static EnsoDateTime now() {
...
-    TemporalAccessor time = TIME_FORMAT.parseBest(text, ZonedDateTime::from, LocalDateTime::from);
-    if (time instanceof ZonedDateTime) {
-      return new EnsoDateTime((ZonedDateTime) time);
-    } else if (time instanceof LocalDateTime) {
-      return new EnsoDateTime(((LocalDateTime) time).atZone(ZoneId.systemDefault()));
+    String iso = text;
+    if (text != null && text.length() > 10 && text.charAt(10) == ' ') {
+      var builder = new StringBuilder(iso);
+      builder.replace(10, 11, "T");
+      iso = builder.toString();
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java:78]: I hope my try at the shared Java project between `runtime` and `std-bits` will allow us to avoid this code duplication.

File: std-bits/base/src/main/java/org/enso/base/Time_Utils.java [hunk 2]
```diff
@@ -207,7 +162,7 @@ public static LocalTime parse_time(String text, String pattern, Locale locale) {
    * types is not supported, so this is a workaround.
    *
    * <p>TODO once the related issue is fixed, this workaround may be replaced with pattern matching
-   * in Enso; the related Pivotal issue: https://www.pivotaltracker.com/story/show/183219169
+   * in Enso; <a href="https://www.pivotaltracker.com/story/show/183219169">Pivotal issue.</a>
```
Comment (radeusgd) [inline std-bits/base/src/main/java/org/enso/base/Time_Utils.java]: If we are modifying this part then:
1. firstly, let's update the link to GH as the Pivotal one seems dead: https://github.com/enso-org/enso/issues/4597
2. ideally, we could remove this workaround and use the pattern matching, since the task has been completed ages ago. But that's lower priority I guess.

File: std-bits/table/src/main/java/org/enso/table/formatting/DateTimeFormatter.java [hunk 3]
```diff
@@ -10,7 +11,9 @@ public class DateTimeFormatter implements DataFormatter {
   private final java.time.format.DateTimeFormatter formatter;
 
   public DateTimeFormatter(String formatString, Locale locale) {
-    formatter = java.time.format.DateTimeFormatter.ofPattern(formatString, locale);
+    formatter = formatString.equals("ENSO_ZONED_DATE_TIME")
+            ? Time_Utils.default_output_date_time_formatter()
+            : Time_Utils.make_formatter(formatString, locale);
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/formatting/DateTimeFormatter.java]: minor nitpick: I don't like that this constant `"ENSO_ZONED_DATE_TIME"` is placed here.

Maybe we can move this whole logic to `Time_Utils` instead?

Maybe we could make a:

```
Time_Utils {
	DateFormatter make_output_formatter(String formatString, Locale locale) {
		return formatString.equals("ENSO_ZONED_DATE_TIME")
	            ? default_output_date_time_formatter()
	            : make_formatter(formatString, locale);
	}
}
```

File: std-bits/table/src/main/java/org/enso/table/parsing/BaseTimeParser.java [hunk 4]
```diff
@@ -12,22 +13,26 @@ protected interface ParseStrategy {
...
 
   protected BaseTimeParser(String[] formats, Locale locale, ParseStrategy parseStrategy) {
     this.parseStrategy = parseStrategy;
 
     formatters = new DateTimeFormatter[formats.length];
+    replaceSpaces = new boolean[formats.length];
     for (int i = 0; i < formats.length; i++) {
-      formatters[i] = DateTimeFormatter.ofPattern(formats[i], locale);
+      formatters[i] = Time_Utils.make_formatter(formats[i], locale);
+      replaceSpaces[i] = formats[i].endsWith("_DATE_TIME");
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/parsing/BaseTimeParser.java]: I'd prefer the logic needed to figure out if we need to replace the spaces to also reside in `Time_Utils` - I think it would be beneficial to gather all of this kind of logic in one place.

File: std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java [hunk 5]
```diff
@@ -17,11 +17,13 @@ public DateTimeParser(String[] formats, Locale locale) {
...
-      return ZonedDateTime.parse(text, formatter);
-    } catch (DateTimeParseException ignored) {
-      return LocalDateTime.parse(text, formatter).atZone(ZoneId.systemDefault());
+    var datetime = formatter.parseBest(text, ZonedDateTime::from, LocalDateTime::from);
+    if (datetime instanceof ZonedDateTime zdt) {
+      return zdt;
+    } else if (datetime instanceof LocalDateTime ldt) {
+      return ldt.atZone(ZoneId.systemDefault());
     }
+    throw new DateTimeParseException("Invalid date time", text, 0);
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java:26]: In hindsight, I don't know how I thought that throwing exceptions for every parsed date is good design... Well possibly I just didn't think of any other possible solution, but wow this would have never been efficient - glad that you figured out a solution without exceptions!

File: test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso [hunk 6]
```diff
@@ -98,10 +98,17 @@ spec =
             formatter.parse "2020-05-07" datatype=Date . should_equal (Date.new 2020 5 7)
             formatter.parse "1999-01-01 00:00:00" . should_equal (Date_Time.new 1999)
             formatter.parse "1999-02-03 04:05:06" . should_equal (Date_Time.new 1999 2 3 4 5 6)
+            formatter.parse "1999-02-03T04:05:06" . should_equal (Date_Time.new 1999 2 3 4 5 6)
+            formatter.parse "1999-02-03 04:05:06.123" . should_equal (Date_Time.new 1999 2 3 4 5 6 123)
+            formatter.parse "1999-02-03 04:05:06.000456" . should_equal (Date_Time.new 1999 2 3 4 5 6 0 456)
+            formatter.parse "1999-02-03 04:05:06.000000789" . should_equal (Date_Time.new 1999 2 3 4 5 6 0 0 789)
```
Comment (radeusgd) [inline test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso:104]: I like these tests :)

Comment (radeusgd) [reply test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso:104]: Could we also get a test where the date-time string also includes a timezone? I assume we expect it to be able to parse times with zones now, so I'd appreciate a test verifying that.

**Review by radeusgd — APPROVED** [review]
Awesome!

I expect we will have some conflicts with my PR on Column names (especially `Column.map`), you will likely merge first so I will just resolve them, but if I were to get merged first I'll happily try to help resolving these conflicts if needed.

File: distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso [hunk 7]
```diff
@@ -28,5 +28,5 @@ json_from_table table =
    - value: the value to be visualized.
 process_to_json_text : Any -> Text
 process_to_json_text value = case value of
-    Table.Value _ -> json_from_table value . to_text
+    _ : Table -> json_from_table value . to_text
     _ -> value.to_json
```
Comment (radeusgd) [inline distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso:32]: What happened here? Looking at this code I'd expect both the 'before' and 'after' to have basically the exactly same semantics, so I'm surprised this had to be changed to fix something (although I _do_ like the new code more, it is also prettier 🙂). But I'm wondering what was broken with the old code?

Comment (jdunkerley) [reply distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso:32]: I think something with the import changed. So `Table.Value` wasn't truly in scope. Switching to type match fixed it (and is cleaner).

Comment (radeusgd) [reply distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso:32]: It is cleaner I agree.

I'm confused.

When the type `Table` to be matched is in scope, then it is also in scope for taking its member `Table.Value`. I can't imagine a scenario where one would work but not the other.

(Not trying to argue there was no error, but I'm trying to understand the situation and I'm confused)

Comment (jdunkerley) [reply distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso:32]: `Table` is brought in via the export within `Standard.Table`, not directly imported.
I agree it should be available so something odd.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java:78]: We can create a shared library and include it in both `runtime` and `std-bits`, but the `.class` files will still be duplicated. I am afraid.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java [hunk 8]
```diff
@@ -267,20 +273,21 @@ public final Object toDisplayString(boolean allowSideEffects) {
...
-          .optionalStart()
-          .appendLiteral('[')
-          .parseCaseSensitive()
-          .appendZoneRegionId()
-          .appendLiteral(']')
-          .optionalEnd()
-          .toFormatter();
+  private static final DateTimeFormatter DATE_TIME_FORMATTER;
+
+  static {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java]: Why are we changing the initialization from static field to `static` block? Any benefits? Or just IDE preference?

File: std-bits/base/src/main/java/org/enso/base/Time_Utils.java [hunk 9]
```diff
@@ -25,58 +24,87 @@
...
+      case "ISO_ZONED_DATE_TIME" -> DateTimeFormatter.ISO_ZONED_DATE_TIME;
+      case "ISO_OFFSET_DATE_TIME" -> DateTimeFormatter.ISO_OFFSET_DATE_TIME;
+      case "ISO_LOCAL_DATE_TIME" -> DateTimeFormatter.ISO_LOCAL_DATE_TIME;
+      case "ISO_LOCAL_DATE" -> DateTimeFormatter.ISO_LOCAL_DATE;
+      case "ISO_LOCAL_TIME" -> DateTimeFormatter.ISO_LOCAL_TIME;
+      default -> DateTimeFormatter.ofPattern(format, locale);
+    };
   }
 
-  public enum AdjustOp {
```
Comment (JaroslavTulach) [inline std-bits/base/src/main/java/org/enso/base/Time_Utils.java:54]: This `enum` has been moved, but seems to remain unchanged. Why not keep it at existing location?

**Review by JaroslavTulach — APPROVED** [review]

File: std-bits/base/src/main/java/org/enso/base/Time_Utils.java (hunk 9 above)
Comment (jdunkerley) [reply std-bits/base/src/main/java/org/enso/base/Time_Utils.java:54]: git glitch - I didn't move it! Just deleted methods and stuff around it.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java (hunk 1 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java:78]: True, they will be. But I don't think this is an issue at all - firstly we should only put the very core stuff that needs to be shared, so it should have minimal footprint.

Secondly, it will still have _not greater_ footprint than duplicated code.

And ensuring we do not duplicate code will increase maintability - we will have a single source of truth for these implementations - easier to update (as otherwise it is easy to forget to update one of the copies when doing changes).
