### PR TITLE
Use foreign memory arena for big bindings cache

### LINKED ISSUE #13816: Consider using Foreign Memory API when reading `.bindings`
Our CI continues to report random IOExceptions on Windows, such as
```
2025-08-07T00:19:15.1493480Z  INFO ide_ci::program::command: sbt ℹ️ [0m[[0m[0minfo[0m] [0m[0mGenerating index for built-distribution\enso-engine-2025.2.1-dev-windows-amd64\enso-2025.2.1-dev\lib\Standard\AWS [0m
2025-08-07T00:19:53.7738276Z  INFO ide_ci::program::command: sbt ℹ️ [WARN] [2025-08-07T02:19:53+02:00] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization of bindings `Standard.AWS` failed: C:\runner\_work\enso\enso\built-distribution\enso-engine-2025.2.1-dev-windows-amd64\enso-2025.2.1-dev\lib\Standard\AWS\2025.2.1-dev\.enso\cache\bindings\2025.2.1-dev\Standard\AWS.bindings: The process cannot access the file because it is being used by another process`
2025-08-07T00:19:53.7814876Z  INFO ide_ci::program::command: sbt ℹ️ [ERROR] [2025-08-07T02:19:53+02:00] [org.enso.runner.Main] Unexpected internal error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.file.FileSystemException: C:\runner\_work\enso\enso\built-distribution\enso-engine-2025.2.1-dev-windows-amd64\enso-2025.2.1-dev\lib\Standard\AWS\2025.2.1-dev\.enso\cache\bindings\2025.2.1-dev\Standard\AWS.bindings: The process cannot access the file because it is being used by another process
2025-08-07T00:19:53.7819293Z  INFO ide_ci::program::command: sbt ℹ️ org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.file.FileSystemException: C:\runner\_work\enso\enso\built-distribution\enso-engine-2025.2.1-dev-windows-amd64\enso-2025.2.1-dev\lib\Standard\AWS\2025.2.1-dev\.enso\cache\bindings\2025.2.1-dev\Standard\AWS.bindings: The process cannot access the file because it is being used by another process
2025-08-07T00:19:53.7822154Z  INFO ide_ci::program::command: sbt ℹ️ 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
```
In the [discussion](https://github.com/enso-org/enso/pull/8924/files#r2268545357) on PR that mmapped `.bindings` this was mentioned as the potential source of the problem. @JaroslavTulach suggested recently that we could use [`Arena`](https://docs.oracle.com/en/java/javase/23/core/foreign-function-and-memory-api.html) from new Foreign Memory Api to correctly manage the access and thus fix the problem on Windows.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #13816

Blocked by https://github.com/enso-org/enso/issues/13918

### Pull Request Description

Using `java.lang.foreign.Arena` for mmapping a big cache file when loading the cache.

### Important Notes

- When [loading big cache file](https://github.com/enso-org/enso/blob/1de26ec037c3bc61330192a9ca24b35ba3a72159/engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java#L269-L282):
  - A previous Arena is closed. Which invalidates any byte buffers associated with that Arena.
  - New Arena is created.
  - Using [shared arena](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/foreign/Arena.html#ofShared()), and not [confined arena](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/foreign/Arena.html#ofConfined()).
    - See https://github.com/enso-org/enso/pull/13872#discussion_r2313983664
  - File is [mmapped](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/nio/channels/FileChannel.html#map(java.nio.channels.FileChannel.MapMode,long,long,java.lang.foreign.Arena)) via that new arena in READ_ONLY mode.
    - read only means that writing anything to the underlying `ByteBuffer` will result in `java.nio.ReadOnlyBufferException`.
- Both `load` and `save` closes previous arena.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
+package org.enso.interpreter.caches;
+
+import java.util.ArrayList;
+import java.util.List;
+
+/** Utility class to keep track of cache-related statistics. */
+public final class CacheStatistics {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java]: This can potentially be used to log when `--profiling-path` is specified.
- We have some cache-related logs done via some TruffleLoggers
- But not all, and not structured.
- This is useful for testing.
- Controlled via option in `RuntimeOptions` passed to `Context`.

File: build.sbt [hunk 2]
```diff
@@ -2664,7 +2664,8 @@ lazy val `runtime-test-instruments` =
 lazy val runtime = (project in file("engine/runtime"))
   .enablePlugins(JPMSPlugin)
   .settings(
-    frgaalJavaCompilerSetting,
+    // Needed for `java.lang.Foreign`.
+    customFrgaalJavaCompilerSettings("24"),
```
Comment (JaroslavTulach) [inline build.sbt:2864]: - I was afraid that this would be needed.
- I wanted to suggest to create a separate `runtime-caches` module:
   - move all the cache related code there
   - invoke it with requires (from `runtime`)/provides pattern
   - if the `runtime-caches` module is missing, then `runtime` would just avoid loading caches 
- Because such a change would prevent usage of `runtime` inside of IGV/VSCode on LTS JDK (e.g. JDK 21)
- but we don't need `runtime` in there anyway
   - the plans we have count with usage of `runtime-compiler` at max
   - and `runtime-compiler` can still run on JDK21, maybe even JDK17

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java]: - Why cannot caching infrastruture use normal logging?
- Why do we need new abstration?
- new runtime option?
- Using logging would be easier...

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 3]
```diff
@@ -158,6 +190,8 @@ private boolean saveCacheTo(
                 + "] to ["
                 + toMaskedPath(parentPath).applyMasking()
                 + "].");
+        recordCacheEvent(() -> new CacheEvent.Save(logName, bytesToWrite.length));
+        memoryArena.close();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: - Error!
- You need to close the mmapped file - e.g. the arena first and only then `writeBytesTo`

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheEvent.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
+package org.enso.interpreter.caches;
+
+public sealed interface CacheEvent {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/CacheEvent.java]: I find this overcomplicated and I suggest to replace all of this with simple logging.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
- close mmapped files first, only then write
- avoid _yet another level of indirection_ - e.g. remove statistics abstractions

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java]: I wanted to avoid capturing logs and checking their content from tests. I find that too fragile. On the other hand, if someone changes log message, there will be a failing test with (hopefully clear) error message and it will be clear that the log message should not have been changed. Moreover, we rely on log capturing from tests already anyway. I will revert this back and use just log captures for the tests. You are probably right that there is not enough justification for introducing this `CacheStatistics` abstraction.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java]: > I find that too fragile. On the other hand ... there will be a failing test

Hopefully the error messages can be made clear. Btw. you could move `CacheStatistics` to tests and construct that class from the log messages. Then it would be clear, but .... still with a potentially unnecessary layer of indication.

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheEvent.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/CacheEvent.java]: Rewritten in ae1d6875f85b20a6c29f6650f4fd86b2581a2eb9

File: engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/CacheStatistics.java]: Rewritten in ae1d6875f85b20a6c29f6650f4fd86b2581a2eb9

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: Done in 46b42e5941099dc9e85d220f06088c8f4b2d03ab

File: build.sbt (hunk 2 above)
Comment (Akirathan) [reply build.sbt:2864]: Tracked in https://github.com/enso-org/enso/issues/13898

File: engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties [hunk 5]
```diff
@@ -1 +1,2 @@
-Args=--features=org.enso.runner.EnsoLibraryFeature
+Args = --features=org.enso.runner.EnsoLibraryFeature \
```
Comment (JaroslavTulach) [inline engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: - This is not good idea.
- Foreign support doesn't work on Mac Arm
- we have to run without such a flag at least in GraalVM24
- rather we have to `if (!ImageInfo.inNativeRunCode())` do JIT version `else` use [malloc](https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/UnmanagedMemory.html#malloc(int)) and [asByteBuffer](https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/c/type/CTypeConversion.html#asByteBuffer(org.graalvm.word.PointerBase,int))

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 6]
```diff
@@ -85,13 +90,34 @@ private Cache(
...
       boolean needsSourceDigestVerification,
       boolean needsDataDigestVerification) {
     return new Cache<>(
-        spi, logLevel, logName, needsSourceDigestVerification, needsDataDigestVerification);
+        spi,
+        logLevel,
+        logName,
+        needsSourceDigestVerification,
+        needsDataDigestVerification,
+        Arena.ofShared());
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: - Didn't we wanted to try to use [ofConfined](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/foreign/Arena.html#ofConfined()) `Arena`?
- is it not working?

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 7]
```diff
@@ -85,13 +90,34 @@ private Cache(
...
+  }
+
+  static <T, M> Cache<T, M> create(
+      Spi<T, M> spi,
+      Level logLevel,
+      String logName,
+      boolean needsSourceDigestVerification,
+      boolean needsDataDigestVerification,
+      Arena memoryArena) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: I don't think we want to provide an `Arena` from outside. It is an internal thing - a new arena should be allocated when mmapping a file and closed before writing.

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 8]
```diff
@@ -259,9 +283,18 @@ private T loadCacheFrom(TruffleFile cacheRoot, EnsoContext context, TruffleLogge
...
       if (file.exists() && file.length() > threeMbs) {
-        logger.log(Level.FINEST, "Cache file " + file + " mmapped with " + file.length() + " size");
-        var raf = new RandomAccessFile(file, "r");
-        blobBytes = raf.getChannel().map(FileChannel.MapMode.READ_ONLY, 0, file.length());
+        logger.log(
+            Level.FINEST,
+            "Cache file {0} mmapped with {1} size",
+            new Object[] {file, file.length()});
+        try (var chan = FileChannel.open(file.toPath())) {
+          assert memoryArena.scope().isAlive();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:279]: - the previous `Arena` (if any) should be closed
- new `Arena` allocated and used for _mmapping_ the file

**Review by JaroslavTulach — COMMENTED** [review]
I'd suggest to keep allocate new `Arena` when _mmapping_.

File: engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties (hunk 5 above)
Comment (Akirathan) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: > Foreign support doesn't work on Mac Arm

Right. I can confirm that it is not. NI build fails with "Error: Support for the Foreign Function and Memory API is currently available only on the AMD64 architecture." on my Mac aarch64.

Unfortunately, without it, NI build fails with
```
Unexpected internal error: com.oracle.svm.core.jdk.UnsupportedFeatureError: Support for the Java Foreign Function and Memory API is not active: enable with -H:+ForeignAPISupport
```
(in https://github.com/enso-org/enso/actions/runs/17376926390/job/49325258733?pr=13872#step:10:3026)

Comment (Akirathan) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: It seems that for now, it is best to wait for the GraalVM 25 release, scheduled for 2025-09-16, which will include support for ARM64 (https://github.com/oracle/graal/issues/8113#issuecomment-2776044177). Otherwise, we will need to somehow conditionally enable/disable `-H:+ForeignAPISupport` for certain architectures.

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: Unfortunately, it does not work: Trying to replace this code with `Arena.ofConfined()` and compiling Standard.Table with `enso --compile distribution/lib/Standard/Table/0.0.0-dev` results in:
```
[ERROR] [2025-09-02T18:21:56+02:00] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization of bindings `Standard.Table` failed: Attempted access outside owning thread`
Listening for transport dt_socket at address: 8000
[ERROR] [2025-09-02T18:21:56+02:00] [org.enso.runner.Main] Unexpected internal error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.WrongThreadException: Attempted access outside owning thread
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.WrongThreadException: Attempted access outside owning thread
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScope$InvokeMember.compile(TopLevelScope.java:228)
	at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScope$InvokeMember.doInvoke(TopLevelScope.java:255)
	at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScopeGen$InteropLibraryExports$Cached.invokeMember(TopLevelScopeGen.java:67)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3596)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4823)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:9227)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9179)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNode.doDefault(PolyglotValueDispatch.java:4863)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9376)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:1159)
	at org.enso.polyglot.api/org.enso.polyglot.TopScope.compile(TopScope.scala:55)
	at org.enso.runner/org.enso.runner.Main.compile(Main.java:722)
	at org.enso.runner/org.enso.runner.Main.mainEntry(Main.java:1209)
	at org.enso.runner/org.enso.runner.Main.lambda$handleLaunch$0(Main.java:1705)
	at org.enso.runner/org.enso.runner.Main.withProfiling(Main.java:1347)
	at org.enso.runner/org.enso.runner.Main.handleLaunch(Main.java:1701)
	at org.enso.runner/org.enso.runner.Main.launch(Main.java:1625)
	at org.enso.runner/org.enso.runner.Main.main(Main.java:1127)
Unexpected internal error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.WrongThreadException: Attempted access outside owning thread
```

This happens during serialization of `.bindings` (`ImportExportCache`) of `Standard.Table`:
- Serialization of Standard.Table bindings is requested inside `SerializationPool` (different thread than the one that creates `Arena` in caches).
- Some objects are written
- Then `IRLazySeq$IRIter.next` is called, which calls into `Persistance$Reference.get`
  - In other words, while Persistance is writing bindings of Standard.Table, it tries to read bindings of Standard.Base. And there is already an opened mapped direct byte buffer for Standard.Base.
- This results in `WrongThreadException`.

File: engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: This is an example of different code on SVM and JVM:

- https://github.com/enso-org/enso/blob/b6fd95b42428a43d53d86852bcb03e55c7e5d5b5/lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/Channel.java#L388


On SubstrateVM you can directly invoke https://man7.org/linux/man-pages/man2/mmap.2.html, obtain the address and then convert raw memory to byte buffer via https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/c/type/CTypeConversion.html#asByteBuffer(org.graalvm.word.PointerBase,int)

You need `<T extends ByteBuffer & AutoClosable>` and one implementation on SVM and another one with `Arena`.

- found a prior art: #13230

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: - OK, no `ofConfined` arenas
- at the end _mmapped_ `ByteBuffer` is read only
- because they are read only it is safe to access from multiple threads
- e.g. no `ofConfined`

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 7 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java]: Changed to `Supplier<Arena>` called from a unit test in 72478c03585ecfc79a41d8c27df902741a18cf42

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 8 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:279]: In 72478c03585ecfc79a41d8c27df902741a18cf42 : 
- Previous arena is closed in `load` and `save`
- Before mmap, a new arena is created

File: engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties (hunk 5 above)
Comment (Akirathan) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: After our 1:1 meeting:
- Your suggestion deals with allocating new off-heap memory and copying bytes into it
- It does not deal with `mmap`.
- We would need to implement native calls of `mmap` ourselves
- Which seems difficult
- Conclusion: Waiting for the GraalVM 25 release and just use `Arena` for `mmap`.

Comment (JaroslavTulach) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: > * Conclusion: Waiting for the GraalVM 25 release

- OK, blocked by #13918

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties:1]: Looks like [maven bits of GraalVM 25](https://repo1.maven.org/maven2/org/graalvm/truffle/truffle-api/25.0.0/) are out. Unblocked...
