### PR TITLE
Clearer warnings in license review

### LINKED ISSUE #9120: Distinguish errors from warnings in license review tool
Currently the license review tool does not distinguish 'fatal' warnings (ones that will fail the `verify*` workflow) from 'informational' warnings (which are there to inform about something irregular but are not a problem to be solved). This is confusing.

- [x] We should rephrase the wording to distinguish the fatal ones as problems, and report the counts separately.
- [x] Additionally, we have a known warning about a missing information for a placeholder Guava dependency occurring in many subprojects. We should add this specific to a 'whitelist' and do not report it at all to avoid confusion.

Unrelated but small change:
- [x] Add expand button to the entries
- [x] make `verify*` last check on CI

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Closes #9120
- Reorders CI steps to do the license check last (to avoid it preventing tests from running which are more important than the license check)
- Tries to reword the warnings to be clearer
- Adds some CSS to the report to more clearly indicate which elements can be clicked.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: project/src/main/scala/licenses/DependencySummary.scala [hunk 1]
```diff
@@ -122,37 +123,47 @@ object ReviewedSummary {
...
       }
 
       val includedInfos =
         (dep.files.map(_._2) ++ dep.copyrights.map(_._2)).filter(_.included)
       if (includedInfos.isEmpty) {
-        warnings.append(
-          s"No files or copyright information are included for $name."
+        diagnostics.append(
+          Diagnostic.Problem(
+            s"No files or copyright information are included for $name. Generally every dependency should have _some_ copyright info, so this suggests all our heuristics failed. Please find the information manually and add it using `files-add` or `copyright-add`. Even if the dependency is public domain, it may be good to include some information about its source."
```
Comment (JaroslavTulach) [inline project/src/main/scala/licenses/DependencySummary.scala]: +1

**Review by Akirathan — APPROVED** [review]
Thanks for the improvements. The error messages as well as few style changes look neat.

**Review by AdRiley — APPROVED** [review]

**Review by mwu-tow — APPROVED** [review]
(approving Rust parts)

File: project/GatherLicenses.scala [hunk 2]
```diff
@@ -59,32 +58,42 @@ object GatherLicenses {
...
+
+      if (notices.nonEmpty) {
+        log.warn(s"Found ${notices.size} non-fatal notices in the report:")
+        notices.foreach(notice => log.warn(notice.message))
+      }
+
+      if (problems.isEmpty) {
+        log.info("No problems found in the report.")
+      } else {
+        log.error(s"Found ${problems.size} in the report:")
```
Comment (hubertp) [inline project/GatherLicenses.scala]:
```suggestion
        log.error(s"Found ${problems.size} fatal errors in the report:")
```

File: project/GatherLicenses.scala [hunk 3]
```diff
@@ -59,32 +58,42 @@ object GatherLicenses {
...
+      val (notices: Seq[Diagnostic.Notice], problems: Seq[Diagnostic.Problem]) =
+        Diagnostic.partition(allDiagnostics)
+
+      if (notices.nonEmpty) {
+        log.warn(s"Found ${notices.size} non-fatal notices in the report:")
+        notices.foreach(notice => log.warn(notice.message))
+      }
+
+      if (problems.isEmpty) {
+        log.info("No problems found in the report.")
```
Comment (hubertp) [inline project/GatherLicenses.scala]:
```suggestion
        log.info("No errors found in the report.")
```

File: project/GatherLicenses.scala [hunk 4]
```diff
@@ -59,32 +58,42 @@ object GatherLicenses {
...
-        log.warn(
-          s"There are too many warnings (${summaryWarnings.size}) to " +
-          s"display. Please inspect the generated report."
-        )
-      else allWarnings.foreach(log.warn(_))
+      val (notices: Seq[Diagnostic.Notice], problems: Seq[Diagnostic.Problem]) =
+        Diagnostic.partition(allDiagnostics)
+
+      if (notices.nonEmpty) {
+        log.warn(s"Found ${notices.size} non-fatal notices in the report:")
```
Comment (hubertp) [inline project/GatherLicenses.scala]:
```suggestion
        log.warn(s"Found ${notices.size} non-fatal warnings in the report:")
```

File: project/src/main/scala/licenses/DependencySummary.scala (hunk 1 above)
Comment (hubertp) [inline project/src/main/scala/licenses/DependencySummary.scala]:
```suggestion
            s"No files or copyright information are included for $name. Generally every dependency should have _some_ copyright info, so this suggests all our heuristics failed. Please find the information manually and add it using `files-add` or `copyright-add`. Even if the dependency is in public domain, it may be good to include some information about its source."
```

File: project/src/main/scala/licenses/DependencySummary.scala [hunk 5]
```diff
@@ -163,10 +174,12 @@ object ReviewedSummary {
...
                 if (licenseContent.strip != includedLicense.content) {
-                  warnings.append(
-                    s"A license file was discovered in $name that is different " +
-                    s"from the default license file that is associated with its " +
-                    s"license ${dep.information.license.name}."
+                  diagnostics.append(
+                    Diagnostic.Problem(
+                      s"A license file was discovered in $name that is different " +
+                      s"from the default license file that is associated with its " +
+                      s"license ${dep.information.license.name}, but a custom license was not expected. If this custom license should override the default one, create a `custom-license` config file. If both files are expected to be included, create an empty `default-and-custom-license` file."
```
Comment (hubertp) [inline project/src/main/scala/licenses/DependencySummary.scala]:
```suggestion
                      s"""|A license file was discovered in $name that is different 
                            |from the default license file that is associated with its 
                            |license ${dep.information.license.name}, but a custom license was not expected. If this custom license should override the default one, create a `custom-license` config file. If both files are expected to be included, create an empty `default-and-custom-license` file.""".stripMargin
```

File: project/src/main/scala/licenses/backend/GithubHeuristic.scala [hunk 6]
```diff
@@ -68,26 +76,39 @@ case class GithubHeuristic(info: DependencyInformation, log: Logger) {
...
               )
             } catch {
               case NonFatal(error) =>
-                log.warn(
-                  s"Found file $rawHref but cannot download it: $error"
+                WithDiagnostics(
+                  Seq(),
+                  Seq(
+                    Diagnostic.Problem(
+                      s"GitHub heuristic: Found file $rawHref but cannot download it: $error"
```
Comment (hubertp) [inline project/src/main/scala/licenses/backend/GithubHeuristic.scala]:
```suggestion
                      s"GitHub heuristic failure: Found file $rawHref but cannot download it: $error"
```

File: project/src/main/scala/licenses/backend/GithubHeuristic.scala [hunk 7]
```diff
@@ -68,26 +76,39 @@ case class GithubHeuristic(info: DependencyInformation, log: Logger) {
...
       }
     } catch {
       case NonFatal(error) =>
-        log.warn(s"GitHub backend for ${info.packageName} failed with $error")
-        Seq()
+        WithDiagnostics(
+          Seq(),
+          Seq(
+            Diagnostic.Problem(
+              s"GitHub heuristic: processing ${info.packageName} failed with error: $error"
```
Comment (hubertp) [inline project/src/main/scala/licenses/backend/GithubHeuristic.scala]:
```suggestion
              s"GitHub heuristic failure: processing ${info.packageName} failed with error: $error"
```

File: project/src/main/scala/licenses/report/Report.scala [hunk 8]
```diff
@@ -40,22 +40,29 @@ object Report {
...
+      if (notices.nonEmpty) {
+        writer.writeSubHeading("Notices")
+        writer.writeList(notices.map { notice => () =>
+          writer.writeText(notice.message)
+        })
+      }
+
+      if (problems.nonEmpty) {
+        writer.writeSubHeading(
+          f"There are ${problems.size} problems found in the review."
```
Comment (hubertp) [inline project/src/main/scala/licenses/report/Report.scala]:
```suggestion
          f"There are ${problems.size} fatal errors found in the review."
```
?

File: project/src/main/scala/licenses/report/Report.scala [hunk 9]
```diff
@@ -40,22 +40,29 @@ object Report {
...
         )
+        writer.writeList(problems.map { problem => () =>
+          writer.writeText(problem.message, Style.Red)
+        })
+      } else {
+        writer.writeParagraph("No problems found in the review.", Style.Green)
```
Comment (hubertp) [inline project/src/main/scala/licenses/report/Report.scala]:
```suggestion
        writer.writeParagraph("No errors found in the review.", Style.Green)
```

**Review by hubertp — APPROVED** [review]
Nit picks regarding the naming. I find the `notice` and `problem` a bit ambiguous. `warning` and `error` are less confusing.

**Review by JaroslavTulach — COMMENTED** [review]
I don't feel as a suitable reviewer.

File: project/src/main/scala/licenses/DependencySummary.scala (hunk 5 above)
Comment (radeusgd) [reply project/src/main/scala/licenses/DependencySummary.scala]: This will add newlines into the string, whereas before the string was a single line.

**Comment by radeusgd** [comment]
> Nit picks regarding the naming. I find the `notice` and `problem` a bit ambiguous. `warning` and `error` are less confusing.

Thanks @hubertp for the suggestions, I've applied them.
