### PR TITLE
Initialize suggestions database only once

### LINKED ISSUE #8033: Initialize suggestions database only once in the presence of multiple clients
Once initialization problems have been fixed in https://github.com/enso-org/enso/pull/7985 I discovered that suggestion database would often crash for no apparent reason:
```
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
[WARN] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Failed to initialize the suggestions database [/home/hubert/enso/projects/Unnamed_9/.enso/suggestions.db].
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table "suggestions" already exists)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:376)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:491)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:426)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:422)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:491)
	at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$4(JdbcActionComponent.scala:287)
	at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$4$adapted(JdbcActionComponent.scala:287)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2122)
	at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.run(JdbcActionComponent.scala:287)
	at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.run(JdbcActionComponent.scala:285)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Clear database file. Attempt #1.
[WARN] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Failed to delete the database file. Attempt #1. File does not exist [/home/hubert/enso/projects/Unnamed_9/.enso/suggestions.db].
[WARN] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Failed to initialize the suggestions database [/home/hubert/enso/projects/Unnamed_9/.enso/suggestions.db].
java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$3@7b87beaa rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@16cd07ec[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 7]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at slick.util.AsyncExecutor$$anon$1$$anon$4.execute(AsyncExecutor.scala:205)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:265)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:263)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:242)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:148)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:172)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:148)
	at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:142)
	at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:141)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:172)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Clear database file. Attempt #1.
[WARN] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Failed to delete the database file. Attempt #1. File does not exist [/home/hubert/enso/projects/Unnamed_9/.enso/suggestions.db].
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Retrying database initialization.
[INFO] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Retrying database initialization.
[ERROR] [2023-10-11T18:11:11+02:00] [org.enso.languageserver.boot.resource.RepoInitialization] Failed to initialize SQL suggestions repo [/home/hubert/enso/projects/Unnamed_9/.enso/suggestions.db].
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table "suggestions_version" already exists)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
```

To reproduce:
- start **new** GUI: `npm --workspace=enso-gui2 run dev` (and `npm install` if you haven't done it before)
- start project manager the usual way
- open [http://localhost:5173/](local browser)

The problem will occur either during a simple startup of a project or if you attempt to move around some of the nodes, causing edits.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #8033 

Changelog:
- update: run language server initialization once
- fix: issues with async `getSuggestionDatabase` message handling in new IDE
- update: implement unique background jobs
- refactor: initialization logic to Java
- refactor: `UniqueJob` to a marker interface

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by somebody1234** [comment]
just a heads up, it might be useful to merge with develop, there's a fix that should make the lint CI less flaky
(but also, the code formatting CI seems to be flaky on this PR anyway, so might as well fix that first before re-triggering CI)

File: engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+import org.enso.languageserver.data.ProjectDirectoriesConfig;
+import org.enso.languageserver.event.InitializedEvent;
+import org.enso.logger.masking.MaskedPath;
+import org.enso.searcher.sql.SqlDatabase;
+import org.enso.searcher.sql.SqlSuggestionsRepo;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import scala.jdk.javaapi.FutureConverters;
+
+public class RepoInitialization implements InitializationComponent {
```
Comment (hubertp) [inline engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java:23]: It would be nice to add some documentation while here. Like what "repo" actually means in this context.

File: engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponent.java [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+import java.util.concurrent.CompletableFuture;
+
+/** A component that should be initialized. */
+public interface InitializationComponent {
+
+  /** @return `true` if the component is initialized */
+  boolean isInitialized();
+
+  /** Initialize the component. */
+  CompletableFuture<Void> init();
```
Comment (hubertp) [inline engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponent.java:12]: Shouldn't `init` assume that `isInitialized` is `false` at the beginning of the execution?

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java [hunk 3]
```diff
@@ -25,17 +26,17 @@ public InvalidateModulesIndexCommand(Option<UUID> maybeRequestId) {
...
   @Override
+  @SuppressWarnings("unchecked")
   public Future<BoxedUnit> executeAsynchronously(RuntimeContext ctx, ExecutionContext ec) {
     return Future.apply(
         () -> {
           TruffleLogger logger = ctx.executionService().getLogger();
           long writeCompilationLockTimestamp = ctx.locking().acquireWriteCompilationLock();
           try {
-            ctx.jobControlPlane().abortAllJobs();
+            ctx.jobControlPlane().abortBackgroundJobs(DeserializeLibrarySuggestionsJob.class);
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java:36]: Isn't this related to the random deserialization problems you were seeing?

**Review by hubertp — APPROVED** [review]
Just by reading the code, this looks fine. I'd like to play around with it a bit more in a live setting

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java (hunk 3 above)
Comment (4e6) [reply engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java:36]: I think I've checked everything. It really shouldn't

File: engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponent.java (hunk 2 above)
Comment (4e6) [reply engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponent.java:12]: I implemented it in a higher-level initialization components

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala [hunk 4]
```diff
@@ -193,7 +217,18 @@ final class JobExecutionEngine(
 
   /** Submit background jobs preserving the stable order. */
   private def submitBackgroundJobsOrdered(): Unit = {
-    Collections.sort(delayedBackgroundJobsQueue)
+    Collections.sort(
+      delayedBackgroundJobsQueue,
+      BackgroundJob.BACKGROUND_JOBS_QUEUE_ORDER
+    )
+    runtimeContext.executionService.getLogger.log(
+      Level.INFO,
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala]: Too verbose. `DEBUG` at least

**Comment by hubertp** [comment]
:ship: it. I haven't seen any initialization problems anymore.

File: engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponentInitialized.java [hunk 5]
```diff
@@ -0,0 +1,19 @@
+package org.enso.languageserver.boot.resource;
+
+/** Object indicating that the initialization is complete. */
+public final class InitializationComponentInitialized {
+
+  private static final class InstanceHolder {
```
Comment (JaroslavTulach) [inline engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponentInitialized.java:6]: There is no need for `InstanceHolder` when the only method and `INSTANCE` field of the `InitializationComponentInitialized` class deal with holding and initializing the instance.

**Review by JaroslavTulach — COMMENTED** [review]
Many classes were rewritten to Java. Nice.
