### PR TITLE
Convert no such method Panic to UnknownIdentifierException

### LINKED ISSUE #7437: Calling `toString` on an Enso object implementing a Java interface causes Panic
Sometimes when passing Enso objects to Java, we can make them implement some interface by ensuring that the Enso object has all methods of that interface. This makes it easier to interact with Enso objects on the Java side (once can just use the interface instead of Polyglot methods).

It seems that `toString` which is expected from all Java objects is not picked up properly.

I'm not exactly sure if this is a bug in Enso or Graal itself.

### Repro

Let's create a file `Foo.java`:
```java
package foo;

public class Foo {
    public static interface Fooable {
        public long foo();
    }

    public static long callFoo(Fooable f) {
        long x = f.foo();
        System.out.println("Foo.foo() returned " + x);
        return x;
    }

    public static void showObject(Object o) {
        System.out.println("Object = " + o.toString());
    }

    public static long callFooAndShow(Fooable f) {
        long x = f.foo();
        System.out.println("{" + f.toString() + "}.foo() returned " + x);
        return x;
    }
}
```
and then put it in a polyglot project, with `src/Main.enso` being:
```
from Standard.Base import all

polyglot java import foo.Foo

type My_Fooable_Implementation
    Instance x

    foo : Integer
    foo self = 100+self.x

main =
   fooable = My_Fooable_Implementation.Instance 23
   IO.println fooable.foo
   IO.println fooable.to_text
   IO.println (Foo.callFoo fooable)
   IO.println (Foo.showObject fooable)
   IO.println (Foo.callFooAndShow fooable)
```

### Actual behaviour

The project as described above, when run yields:
```
123
(Instance 23)
Foo.foo() returned 123
123
Object = (Instance 23)
Nothing
Execution finished with an error: Method `toString` of type My_Fooable_Implementation could not be found.
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:105)
        at <java> jdk.proxy5/jdk.proxy5.$Proxy44.toString(Unknown Source)
        at <java> foo.Foo.callFooAndShow(Foo.java:20)
        at <enso> Main.main<arg-1>(src\Main.enso:17:16-41)
        at <enso> Main.main(src\Main.enso:17:4-42)
```

### Expected behaviour

The program should execute without errors and yield:

```
123
(Instance 23)
Foo.foo() returned 123
123
Object = (Instance 23)
Nothing
{(Instance 23)}.foo() returned 123
123
```

The `toString` call on the Proxy object should delegate to the `to_text` method of the Enso object. As we can see, if we pass it as an `Object` that correctly happens. But if we pass it as this 'interface proxy' - that fails.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

There is a [special handling of toString()](https://github.com/enso-org/enso/issues/7437#issuecomment-1662474235) and other methods in GraalVM SDK. However we need to throw standard `InteropException` to activate it. Converting `PanicException` that represents _no such method_ error on the boundary to `UnknownIdentifierException`. With such change one can call `.toString()` on proxies wrapping Enso objects.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by radeusgd** [comment]
Is `UnknownIdentifierException` internal or does it leak into Enso as well?

IIRC we have some code relying on `No_Such_Method`; will it still work? Is it possible to catch the "new" `UnknownIdentifierException`?

I.e. will this work fine?
```
from Standard.Base import all

type Foo
    Instance

main =
    i = Foo.Instance
    Panic.catch No_Such_Method i.nonexistent_method caught_panic->
        IO.println "OK! I caught it, the identifier is: "+(Meta.meta caught_panic.payload.symbol . name)
```

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java [hunk 1]
```diff
@@ -126,6 +148,24 @@ public Atom makeNoSuchMethod(Object target, UnresolvedSymbol symbol) {
     return noSuchMethod.newInstance(target, symbol);
   }
 
+
+  /** Verifies payload whether it represents {@link #makeNoSuchMethod(Object, UnresolvedSymbol)} atom.
+   * @param payload object to check
+   * @return {@code null} if the {@code payload} isn't recognized name of the unresolved symbol otherwise
+  */
+  public String findNoSuchMethod(Object payload) {
+    if (payload instanceof Atom atom && atom.getConstructor() == noSuchMethod.getUniqueConstructor()) {
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java]: I'm wondering - is there any way to avoid this logic for detecting `No_Such_Method`, if we want to replace it anyway?

Should we not e.g. just throw `UnknownIdentifierException` in the places where we used to do `makeNoSuchMethod`? Or is it the case that we want to replace `No_Such_Method` with `UnknownIdentifierException` only in some places?

I'm concerned that now we have essentially 2 errors to indicate the same situation (missing method). Does that mean that if I want to 'surely' catch a missing method I now have to catch 2 exceptions? Or do we guarantee that `UnknownIdentifierException` never leaks Enso and so I'm still fine just handling `No_Such_Method`?

**Comment by radeusgd** [comment]
Also - thanks for such a quick fix! Please don't take my comments as fussing for the sake of it - I'm just trying to understand what are the implications and if this changes how we should handle missing method errors in the libraries (in general handling such errors is most often not the best pattern, but due to lack of interfaces, it sometimes provides us useful workarounds, so we rely on this in a few places - I want to make sure we are safe in doing so).

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java]: > now we have essentially 2 errors to indicate the same situation

The goal of this `findNoSuchMethod` equilibristic is to avoid _two errors situation_. Internally we continue to represent these errors as `PanicException`.

>  ...replace No_Such_Method with UnknownIdentifierException only in some places?

Yes, exactly. Whenever the `PanicException` crosses the boundary and propagates outside of Enso, it may get converted, so other languages and systems like the one handling `Fooable` interface can recognize `UnknownIdentifierException` and handle it in better way.

When they saw just `PanicException` they treated it as _runtime error_ in user code, not as _unknown identifier_ - e.g. problem finding/invoking the `toString()` completely.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java]: > The goal of this `findNoSuchMethod` equilibristic is to avoid _two errors situation_. Internally we continue to represent these errors as `PanicException`.

So does it mean that in Enso, I will _always_ see the Panic `No_Such_Method` and never the `UnknownIdentifierException` which is only meant for other languages?

**Comment by JaroslavTulach** [comment]
> Is `UnknownIdentifierException` internal or does it leak into Enso as well?

No, `UnknownIdentifierException` isn't "visible" from Enso code.

**Comment by radeusgd** [comment]
> > Is `UnknownIdentifierException` internal or does it leak into Enso as well?
> 
> No, `UnknownIdentifierException` isn't "visible" from Enso code.

Perfect! ❤️

**Review by radeusgd — APPROVED** [review]
Looks good to me.

Can we extend the tests with one last check reproducing the scenario below?

```
from Standard.Base import all

polyglot java import foo.Foo

type Fooable_Class
    Instance x

    foo : Integer
    foo self = self.x+100

type Not_A_Number
    Instance

main =
    i = Fooable_Class.Instance (Not_A_Number.Instance)
    method_name caught_panic = Meta.meta caught_panic.payload.symbol . name
    IO.println <| Panic.catch No_Such_Method (i.foo) method_name
    IO.println <| Panic.catch No_Such_Method (Foo.callFoo i) method_name
```

I'm curious what will happen if we get an Enso `No_Such_Method` in Enso code which itself is called from within Java. Will the `No_Such_Method` be converted to the Java exception when crossing the boundary? I expect not, but I'd like to check it.

I'd expect both pure-Enso and polyglot lines to print the same result. Will that be the case?

**Review by 4e6 — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> Looks good to me.
> Can we extend the tests with one last check reproducing the scenario below?

I have taken code from the original bugreport #7437 and converted it into [JavaInteropTest](https://github.com/enso-org/enso/pull/7487/files#diff-51480514959831df9e4b9559504cc3def76e5f9e8f927656cddc0bde345971a8R175). I cannot easily integrate your code, I'd would have to rewrite it. I don't see a reason to do so as I don't believe anything is broken.

Feel free to provide/integrate an _applicable diff_, if you want new test that _just_ tests something that already works.

**Comment by radeusgd** [comment]
> > Looks good to me.
> > Can we extend the tests with one last check reproducing the scenario below?
> 
> I have taken code from the original bugreport #7437 and converted it into [JavaInteropTest](https://github.com/enso-org/enso/pull/7487/files#diff-51480514959831df9e4b9559504cc3def76e5f9e8f927656cddc0bde345971a8R175). I cannot easily integrate your code, I'd would have to rewrite it. I don't see a reason to do so as I don't believe anything is broken.
> 
> Feel free to provide/integrate an _applicable diff_, if you want new test that _just_ tests something that already works.

Ok, I will send a diff in a moment, or if you allow me I can push it onto the branch. I'm working on making this a JUnit test.

For now, I've got an Enso script:
```
from Standard.Base import all
import Standard.Base.Errors.Common.No_Such_Method

polyglot java import foo.Foo

type Fooable_Class
    Value

    foo : Integer
    foo self a = 
        IO.println "I'm already executing `"+self.to_text+".foo("+a.to_text+")`!"
        "".nonexistent_text_method

type Not_A_Number
    Nan

main =
    i = Fooable_Class.Value
    method_name caught_panic = Meta.meta caught_panic.payload.symbol . name
    IO.println <| Panic.catch No_Such_Method (i.foo 1000) method_name
    IO.println <| Panic.catch No_Such_Method (Foo.callFoo i) method_name
```

which yields
```
I'm already executing `Fooable_Class.Value.foo(1000)`!
nonexistent_text_method
Calling Foo.foo(2000)
I'm already executing `Fooable_Class.Value.foo(2000)`!
I'm already executing `Fooable_Class.Value.foo(2000)`!
Execution finished with an error: Unsupported operation identifier 'foo' and  object 'Fooable_Class.Value'(language: Enso, type: local.Poly_Project.Main.Fooable_Class). Identifier is not executable or instantiable.
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.unsupported(PolyglotEngineException.java:147)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotInteropErrors.invokeUnsupported(PolyglotInteropErrors.java:193)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.invokeOrExecute(PolyglotObjectProxyHandler.java:264)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.doCachedMethod(PolyglotObjectProxyHandler.java:214)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ProxyInvokeNodeGen.executeAndSpecialize(PolyglotObjectProxyHandlerFactory.java:308)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ProxyInvokeNodeGen.execute(PolyglotObjectProxyHandlerFactory.java:244)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ObjectProxyNode.doDefault(PolyglotObjectProxyHandler.java:150)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ObjectProxyNodeGen.executeAndSpecialize(PolyglotObjectProxyHandlerFactory.java:124)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ObjectProxyNodeGen.executeImpl(PolyglotObjectProxyHandlerFactory.java:110)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:105)
        at <java> jdk.proxy5/jdk.proxy5.$Proxy44.foo(Unknown Source)
        at <java> foo.Foo.callFoo(Foo.java:13)
        at <enso> Main.main<arg-2>(src\Main.enso:21:47-59)
        at <enso> Panic.catch(Internal)
        at <enso> Main.main<arg-1>(src\Main.enso:21:19-72)
        at <enso> Main.main(src\Main.enso:21:5-72)
```

As we can see there are several issues here.

1. We fail with a message that the `Fooable_Class.Value` does not support the method `foo`. That is not true, as can be seen in the code _and_ logs - in fact it is executed! The issue likely comes from the fact that the `No_Such_Method` from `"".nonexistent_text_method` gets converted into the `UnknownIdentifierException`, affecting how the method is being resolved.
2. Moreover, we can see that the method `foo` is executed by Graal **2 times**! That seems not very good. If that method was doing any side effects (like here, printing to screen), they will be repeated. Of course Enso is "supposed" to be pure, but as we all know we use side effects all around the place, so we should be careful about re-running a method when resolving it.

**Comment by radeusgd** [comment]
Patch for adding a test I'm interested in:
```diff
Subject: [PATCH] Add a test checking propagation of Panics through the polyglot call.
---
Index: engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java b/engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java
--- a/engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java	(revision 7381176053df7dc35e38d67a2eb86240621042d0)
+++ b/engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java	(revision 93ba3c602dbc6afacc86d9ca1546ed5cde543253)
@@ -2,6 +2,7 @@
 
 import java.io.ByteArrayOutputStream;
 import java.nio.charset.StandardCharsets;
+import java.util.Arrays;
 import java.util.List;
 
 import org.graalvm.polyglot.Context;
@@ -35,14 +36,17 @@
     out.reset();
   }
 
-  private void checkPrint(String code, List<String> expected) {
-    Value result = evalModule(ctx, code);
-    assertTrue("should return Nothing", result.isNull());
-    String[] logLines = out
+  private String[] getStdOutLines() {
+    return out
         .toString(StandardCharsets.UTF_8)
         .trim()
         .split(System.lineSeparator());
-    assertArrayEquals(expected.toArray(), logLines);
+  }
+
+  private void checkPrint(String code, List<String> expected) {
+    Value result = evalModule(ctx, code);
+    assertTrue("should return Nothing", result.isNull());
+    assertArrayEquals(expected.toArray(), getStdOutLines());
   }
 
   @Test
@@ -203,4 +207,55 @@
     assertEquals("obj.toString() = (Instance 23)", res.getArrayElement(3).asString());
     assertEquals("{(Instance 23)}.foo() = 123", res.getArrayElement(4).asString());
   }
+
+  @Test
+  public void testInterfaceProxyFailures() {
+    var code = """
+        from Standard.Base import all
+        import Standard.Base.Errors.Common.No_Such_Method
+
+        polyglot java import org.enso.example.ToString as Foo
+
+        type My_Exc
+            Error
+
+        type Fooable_Panic
+            Value
+
+            foo : Integer
+            foo self =
+                IO.println "Executing Fooable_Panic.foo"
+                Panic.throw My_Exc.Error
+
+        type Fooable_Unresolved
+            Value
+
+            foo : Integer
+            foo self =
+                IO.println "Executing Fooable_Unresolved.foo"
+                "".nonexistent_text_method
+
+        main =
+            a = Panic.catch My_Exc (Foo.callFoo Fooable_Panic.Value) (.payload)
+            b = Panic.catch No_Such_Method (Foo.callFoo Fooable_Unresolved.Value) (caught-> caught.payload.method_name)
+            [a, b]
+        """;
+
+    Value res;
+    try {
+      res = evalModule(ctx, code);
+    } catch (Exception e) {
+      System.err.println("The test code failed to execute with exception: " + e);
+      System.err.println("It has produced the following stdout so far:");
+      Arrays.stream(getStdOutLines()).forEach(System.err::println);
+      throw e;
+    }
+    assertTrue("It is an array", res.hasArrayElements());
+    assertEquals("Array with 2 elements", 2, res.getArraySize());
+    assertEquals("my panic payload message 1", res.getArrayElement(0).asString());
+    assertEquals("nonexistent_text_method", res.getArrayElement(1).asString());
+    var stdout = getStdOutLines();
+    var expectedLines = List.of("Executing Fooable_Panic.foo", "Executing Fooable_Unresolved.foo");
+    assertArrayEquals(expectedLines.toArray(), stdout);
+  }
 }
```

And as I have worried, it indeed fails:
```
[info] done compiling
[error] Test org.enso.interpreter.test.JavaInteropTest.testInterfaceProxyFailures failed: org.graalvm.polyglot.PolyglotException: Unsupported operation identifier 'foo' and  object 'Fooable_Unresolved.Value'(language: Enso, type: Unnamed.Fooable_Unresolved). Identifier is not executable or instantiable., took 0.539 sec
[error]     at com.oracle.truffle.polyglot.PolyglotEngineException.unsupported(PolyglotEngineException.java:147)
[error]     at com.oracle.truffle.polyglot.PolyglotInteropErrors.invokeUnsupported(PolyglotInteropErrors.java:193)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.invokeOrExecute(PolyglotObjectProxyHandler.java:264)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ProxyInvokeNode.doCachedMethod(PolyglotObjectProxyHandler.java:214)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ProxyInvokeNodeGen.execute(PolyglotObjectProxyHandlerFactory.java:228)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler$ObjectProxyNode.doDefault(PolyglotObjectProxyHandler.java:150)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandlerFactory$ObjectProxyNodeGen.executeImpl(PolyglotObjectProxyHandlerFactory.java:105)
[error]     at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
[error]     at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:105)
[error]     at jdk.proxy2.$Proxy50.foo(Unknown Source)
[error]     at org.enso.example.ToString.callFoo(ToString.java:12)
[error]     at <enso>.Unnamed.main<arg-2>(Unnamed:27)
[error]     at <enso>.Panic.catch(Unknown)
[error]     at <enso>.Unnamed.main(Unnamed:27)
[error]     at org.graalvm.polyglot.Value.execute(Value.java:879)
[error]     at org.enso.interpreter.test.TestBase.evalModule(TestBase.java:128)
[error]     at org.enso.interpreter.test.JavaInteropTest.testInterfaceProxyFailures(JavaInteropTest.java:246)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:568)
[error]     ...

The test code failed to execute with exception: org.graalvm.polyglot.PolyglotException: Unsupported operation identifier 'foo' and  object 'Fooable_Unresolved.Value'(language: Enso, type: Unnamed.Fooable_Unresolved). Identifier is not executable or instantiable.
It has produced the following stdout so far:
Executing Fooable_Panic.foo
Executing Fooable_Unresolved.foo
Executing Fooable_Unresolved.foo

[error] Failed: Total 12, Failed 1, Errors 0, Passed 11
[error] Failed tests:
[error]         org.enso.interpreter.test.JavaInteropTest
[error] (runtime / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 12 s, completed 3 sie 2023, 18:54:05
```

As we can see, a regular panic is propagated all fine.

But once we have a `No_Such_Method` error executed in some 'inner' Enso code (it could possibly be very deep in the call stack), it is actually 'mistakenly' converted into `UnknownIdentifierException`. Then Graal thinks that it failed to resolve `foo` - but that is not the case - as we can see `foo` was resolved and _executed already_. Even worse - it is being executed twice which really should not be happening.

**Review by radeusgd — CHANGES_REQUESTED** [review]
I think we need to verify before converting `No_Such_Method` that it is actually relying to the 'currently being resolved' method, on the current object, and not convert all such errors.

The fact that the error saying that `nonexistent_text_method` does not exist gets converted into an error that a completely different object does not support method `foo` is quite confusing.

But the fact that the method is actually executed twice because of this - I think we should revisit that before merging, as executing a method multiple times because of a bug in resolution seems very problematic in presence of side effects (as the test suggests).

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java [hunk 2]
```diff
@@ -126,6 +148,24 @@ public Atom makeNoSuchMethod(Object target, UnresolvedSymbol symbol) {
     return noSuchMethod.newInstance(target, symbol);
   }
 
+
+  /** Verifies payload whether it represents {@link #makeNoSuchMethod(Object, UnresolvedSymbol)} atom.
+   * @param payload object to check
+   * @return {@code null} if the {@code payload} isn't recognized name of the unresolved symbol otherwise
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java]:
```suggestion
   * @return {@code null} if the {@code payload} isn't recognized name or the unresolved symbol otherwise
```

**Review by Akirathan — APPROVED** [review]
Nice. Just a typo in docs.

**Comment by radeusgd** [comment]
Btw. interestingly [the results of the JavaInteropTest](https://github.com/enso-org/enso/actions/runs/5753708919/job/15597487932#step:10:6002) seem to be not appearing in the [test report uploaded on CI](https://github.com/enso-org/enso/runs/15598339257#r89). I wonder if we can do sth to fix this (possibly cc @mwu-tow)?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java [hunk 3]
```diff
@@ -224,6 +226,20 @@ Object resolveHostMethod(
               .error()
               .makeUnsupportedArgumentsError(e.getSuppliedValues(), e.getMessage()),
           this);
+    } catch (AbstractTruffleException ex) {
+      CompilerDirectives.transferToInterpreter();
+      if (ex.getMessage().contains("Unsupported operation identifier")) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java]: This code is trying to recognize `HostException` (a non-public Graal class) and extract enough information from it to re-create a `PanicException`.

This is pretty ugly and more over [it is wrong](https://github.com/enso-org/enso/pull/7487/files#r1284974978)...

File: engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java [hunk 4]
```diff
@@ -163,12 +165,96 @@ public void testImportNonExistingInnerNestedClass() {
...
+    var expectedLines = List.of("Executing Fooable_Panic.foo");
+    assertArrayEquals(expectedLines.toArray(), stdout);
+  }
+
+  @Test
+  public void testInterfaceProxyFailuresB() {
+    var result = evalInterfaceProxyFailures("b");
+    assertEquals("foo", result.asString());
+    var stdout = getStdOutLines();
+    var expectedLines = List.of("Executing Fooable_Unresolved.foo", "Executing Fooable_Unresolved.foo");
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java]: Invoking the `b` function fails with wrong (`foo`) identifier and moreover it runs the `foo` code twice! The [conversion](https://github.com/enso-org/enso/pull/7487/files#r1284974772) needs to differentiate between:
- unknown symbol on the boundary
- unknown symbol during execution

Only the boundary symbol shall be converted to `InteropException`.

**Comment by JaroslavTulach** [comment]
Thank you for the test, Radek.

> verify before converting `No_Such_Method` that it is actually relying to the 'currently being resolved' method, on the current object, and not convert all such errors.

Yes, that's what bd77383 does. It marks some `InvokeMethodNode`s as being `onBoundary`. Only those are then converted to `UnknownIdentifierException`.

All the tests are passing (feel free to commit new ones) and the code looks way better then some of the attempts tried previously. Please review.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InteropMethodCallNode.java [hunk 5]
```diff
@@ -60,7 +59,8 @@ InvokeMethodNode buildSorter(int length) {
         args,
         InvokeCallableNode.DefaultsExecutionMode.EXECUTE,
         InvokeCallableNode.ArgumentsExecutionMode.PRE_EXECUTED,
-        0);
+        0,
+        true);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InteropMethodCallNode.java:63]: `InteropMethodCallNode` does _interop call_ `onBoundary`. Thus passing `true` in.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java [hunk 6]
```diff
@@ -198,11 +205,19 @@ static Object doCached(
...
       System.arraycopy(arguments, 0, args, 1, arguments.length);
-      return symbols.execute(cachedSym, args);
+      try {
+        return symbols.execute(cachedSym, args);
+      } catch (PanicException ex) {
+        if (ex.getCause() instanceof UnknownIdentifierException interopEx) {
+          throw interopEx;
+        } else {
+          throw ex;
+        }
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java:219]: I think I don't fully understand why this piece of logic is needed here in particular?

Instead of 'converting' the exception here, couldn't we just at the throw-site, throw a different exception depending on the `onBoundary` value?

Or would it cause problems because the exception could leak "too much"?

-----

I guess my question is, is every `onBoundary=true` call, coupled with this particular place where we convert the exception, or if there are other places where it can be called.

And if the latter - is it deliberate that in these other places, the conversion _does not_ take place?

**Review by radeusgd — APPROVED** [review]
Looks great!

I have just one question trying to understand an aspect of the solution.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java:219]: > couldn't we just at the throw-site, throw a different exception depending on the onBoundary value?

I tried that, but it doesn't compile easily. The exception is constructed in `execute` method - that method cannot throw `UnknownIdentifierException` only `invokeMember` can throw such exception. As such I decided to wrap&extract the exception.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java:219]: > is it deliberate that in these other places, the conversion does not take place

If the conversion isn't done, then `PanicException` is thrown - there is nothing wrong on yielding `PanicException`s.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java:219]: Ok, thank you for the explanation.
