### PR TITLE
Show spinner when opening/creating a project

### LINKED ISSUE #5505: Users should see a spinner / loading indicator when opening a project
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/181585195).
<hr />

### Steps to reproduce
1. Open the IDE
2. Select a project

### Expected
A spinner should show up until the project is ready for interaction.

### Actual
A blank canvas is visible.

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Closes #5505: A spinner with the Enso logo is now shown for most of the duration when opening and creating a project.

https://user-images.githubusercontent.com/607786/234019207-e34096c7-2cb3-4ae3-abd3-291fcaf43084.mp4

### Important Notes

There's still a tiny bit of lag between the end of the spinner and when the nodes pop up, but that seemed less trivial to me to work around.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/controller/ide.rs [hunk 1]
```diff
@@ -150,18 +157,44 @@ pub trait ManagingProjectAPI {
...
+    }
+
+    /// Open a project by name or ID. If no project with the given name exists, it will be created.
+    fn open_or_create_project(&self, project_to_open: ProjectToOpen) -> BoxFuture<FallibleResult> {
+        async move {
+            match self.find_project(&project_to_open).await {
+                Ok(project_id) => self.open_project(project_id).await,
+                Err(error) =>
+                    if let ProjectToOpen::Name(name) = project_to_open {
+                        info!("Attempting to create project with name {}", name);
```
Comment (wdanilo) [inline app/gui/src/controller/ide.rs]: 1. Logs should be nicely formatted. See other logs in this file, they quote names.
2. Logs should use real English sentences, this one is missing dot. 

Please check all other places in this PR for similar issues.

File: app/gui/src/controller/ide.rs [hunk 2]
```diff
@@ -150,18 +157,44 @@ pub trait ManagingProjectAPI {
...
+                    },
             }
         }
         .boxed_local()
     }
+
+    /// Find a project by name or ID.
+    fn find_project<'a, 'b: 'a>(
+        &'a self,
+        project_to_open: &'b ProjectToOpen,
```
Comment (wdanilo) [inline app/gui/src/controller/ide.rs]: Why do we need so complex lifetime dependencies? I do not see in this code anything that would require it – it's very rare that something like that is needed.

File: app/gui/src/controller/ide/desktop.rs [hunk 3]
```diff
@@ -49,53 +47,16 @@ pub struct Handle {
...
-        // TODO[ao]: Reuse of initializer used in previous code design. It should be soon replaced
-        //      anyway, because we will soon resign from the "open or create" approach when opening
-        //      IDE. See https://github.com/enso-org/ide/issues/1492 for details.
-        let initializer = initializer::WithProjectManager::new(project_manager, project_to_open);
-        let model = initializer.initialize_project_model().await?;
-        Ok(model)
+    /// Create IDE controller.
+    pub fn new(project_manager: Rc<dyn project_manager::API>) -> FallibleResult<Self> {
+        Ok(Self {
+            current_project: Rc::new(CloneCell::new(None)),
```
Comment (wdanilo) [inline app/gui/src/controller/ide/desktop.rs]: this is default

File: app/gui/src/controller/ide/desktop.rs [hunk 4]
```diff
@@ -49,53 +47,16 @@ pub struct Handle {
...
+            project_manager: project_manager.clone_ref(),
+            status_notifications: default(),
+            parser: Parser::new(),
```
Comment (wdanilo) [inline app/gui/src/controller/ide/desktop.rs]: does it implement default?

File: app/gui/src/ide/initializer.rs [hunk 5]
```diff
@@ -94,26 +78,36 @@ impl Initializer {
         //      issues to user, such information should be properly passed
         //      in case of setup failure.
 
+        match self.initialize_ide_controller_with_retries().await {
+            Ok(controller) => {
+                let ide = Ide::new(ensogl_app, view.clone_ref(), controller);
+                if let Some(project) = &self.config.project_to_open {
+                    ide.open_or_create_project(project.clone());
+                }
+                info!("Setup done.");
```
Comment (wdanilo) [inline app/gui/src/ide/initializer.rs]: This log does not tell much. Seeing "setup done" in terminal I would not understand what it is about. I know it is from old code, but should be fixed here I think.

File: app/gui/src/presenter.rs [hunk 6]
```diff
@@ -29,6 +31,16 @@ pub use searcher::Searcher;
 
 
 
+// =================
+// === Constants ===
+// =================
+
+/// We don't know how long the project opening will take, but we still want to show a fake progress
+/// indicator for the user. This constant represents a progress percentage that will be displayed.
```
Comment (wdanilo) [inline app/gui/src/presenter.rs]: What do you mean by "fake progress indicator"? What is the difference between a "fake" and a "real" progress indicator?

File: app/gui/src/presenter.rs [hunk 7]
```diff
@@ -125,11 +138,37 @@ impl Model {
...
     }
+
+    /// Open a project by name or ID. If no project with the given name exists, it will be created.
+    #[profile(Task)]
+    fn open_or_create_project(&self, project: ProjectToOpen) {
+        let controller = self.controller.clone_ref();
+        crate::executor::global::spawn(with_progress_indicator(|| async move {
+            if let Ok(managing_api) = controller.manage_projects() {
+                if let Err(error) = managing_api.open_or_create_project(project).await {
+                    error!("Cannot open or create project: {error}.");
```
Comment (wdanilo) [inline app/gui/src/presenter.rs]: Is this error not producing double dot at the end?

File: app/gui/src/presenter.rs [hunk 8]
```diff
@@ -125,11 +138,37 @@ impl Model {
...
+                }
+            } else {
+                warn!("Project opening failed: no ProjectManagingAPI available.");
```
Comment (wdanilo) [inline app/gui/src/presenter.rs]: What is "ProjectManagingAPI" - is this a name of a struct? I don't see it imported anywhere. Anyway, errors should provide user-facing messages and putting there names of local structs does not make much sense.

File: app/gui/src/presenter.rs [hunk 9]
```diff
@@ -125,11 +138,37 @@ impl Model {
...
+
+/// Show a full-screen spinner for the exact duration of the specified function.
+async fn with_progress_indicator<F, T>(f: F)
+where
+    F: FnOnce() -> T,
+    T: Future<Output = ()>, {
+    let Ok(app) = js::app() else { return error!("Failed to get JavaScript EnsoGL app.") };
+    app.show_progress_indicator(OPEN_PROJECT_SPINNER_PROGRESS);
+    f().await;
+    app.hide_progress_indicator();
```
Comment (wdanilo) [inline app/gui/src/presenter.rs]: 1. We had an old code that was doing `js::app()` but I can't see it changed in this PR. What happened with it? 
2. I believe that we are doing `js::app()` somewhere in EnsoGL core already. Doing it twice probably does not make sense as it is more error prone. We need JS app there, so the app should already be initialized.

File: app/gui/view/src/project_list.rs [hunk 10]
```diff
@@ -196,6 +197,23 @@ mod background {
 
 
 
+// ===========
+// === FRP ===
+// ===========
+
+ensogl::define_endpoints! {
+    Input {
+        /// A list of projects (name, ID) to choose from
```
Comment (wdanilo) [inline app/gui/view/src/project_list.rs]: 1. Documentation should be real English sentences. Please fix it everywhere in this PR.
2. If this is a "list of projects", why this FRP endpoint is not named "list_projects"? Either the name or documentation is wrong.

File: app/gui/view/src/project_list.rs [hunk 11]
```diff
@@ -274,11 +293,35 @@ impl ProjectList {
...
+            frp.source.selected_project <+ grid.entry_selected.map2(
+                &frp.input.set_projects,
+                |selected_entry, projects| {
+                    let (row, _) = (*selected_entry)?;
+                    projects.get(row).cloned()
+                }
+            );
+            some_project_selected <- frp.output.selected_project
+                .filter_map(|selection| selection.clone());
+            grid.select_entry <+ some_project_selected.constant(None);
```
Comment (wdanilo) [inline app/gui/view/src/project_list.rs]: these FRP definitions are way more complex than any other FRP definition above. Could you try refactoring them to keep them simpler (shorter in the amount of lines per FRP definition), just as it's done in other places, please? Long FRP definitions require reader to spend a lot of time understanding every FRP binding, while the FRP code should focus on the interaction logic instead. Refactoring things to helper functions is often the best idea in such places.

**Review by wdanilo — CHANGES_REQUESTED** [review]
Beside the provided comments:
1. I think we should make the spinner progressing from x% -> 100% over some hardcoded amount of time. Otherwise, it looks like the app just hanged.
2. I don't think the 80% is a good choice here. Loading the app is still much faster than its initialization, so, if we try to make it closer to reality, this should be probably a lower number.

File: app/gui/src/controller/ide.rs (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/controller/ide.rs]: The returned `BoxFuture` captures `'a` "by default", so `'b: 'a` ensures that it can also safely capture `project_to_open`. But to make it more clear, I'd go with this signature:
```rust
    /// Find a project by name or ID.
    fn find_project<'a, 'b, 'c: 'a + 'b>(
        &'a self,
        project_to_open: &'b ProjectToOpen,
    ) -> BoxFuture<'c, FallibleResult<Uuid>>
```
(or `'a: 'c, 'b: 'c, 'c` - I don't remember how the lifetime bounds exactly work).

File: app/gui/src/ide.rs [hunk 12]
```diff
@@ -102,6 +108,7 @@ pub struct FailedIde {
 }
 
 
+
```
Comment (farmaazon) [inline app/gui/src/ide.rs]: I think we should have only one empty line here.

File: app/gui/src/presenter.rs (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/presenter.rs]: > What do you mean by "fake progress indicator"? What is the difference between a "fake" and a "real" progress indicator?

To me, it's quite obvious, especially in the context: the "fake progress" is a progress which is not real progress, i.e. 80% does not mean that 80% of the stuff is done.

File: app/gui/src/presenter.rs (hunk 7 above)
Comment (farmaazon) [reply app/gui/src/presenter.rs]: > Is this error not producing double dot at the end?

As a side note: this is why I think we should not make error messages (in any returned "Err") sentences (starting with capital and with dot at the end), because until they are not printed to the user we don't know if they are the entire sentence, or will become a part of another one.

File: app/gui/src/presenter.rs (hunk 8 above)
Comment (farmaazon) [reply app/gui/src/presenter.rs]: > What is "ProjectManagingAPI" - is this a name of a struct? I don't see it imported anywhere. Anyway, errors should provide user-facing messages and putting there names of local structs does not make much sense.

`ProjectManagingAPI` is returned by `manage_projects` function.

And I disagree: this is not a message for the user, but a log. The logs are not for users, but for developers to quickly realize what went wrong.

Here, the better message would be something like `The IDE controller has no ProjectManagingAPI defined`.

File: app/gui/src/presenter.rs (hunk 9 above)
Comment (farmaazon) [reply app/gui/src/presenter.rs]: > 1. We had an old code that was doing `js::app()` but I can't see it changed in this PR. What happened with it?
> 2. I believe that we are doing `js::app()` somewhere in EnsoGL core already. Doing it twice probably does not make sense as it is more error prone. We need JS app there, so the app should already be initialized.

`js::app` is a getter, isn't it? Not an initializer. If it's initialized, then I don't know how could we access it.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/presenter.rs (hunk 6 above)
Comment (wdanilo) [reply app/gui/src/presenter.rs]: Oh, this is about a "fake progress amount", not a "fake progress indicator"? The indicator is the spinner, I was wondering if we are talking here about a "fake spinner". So we are talking here about the real (not fake spinner) with a fake value, right?

File: app/gui/src/presenter.rs (hunk 7 above)
Comment (wdanilo) [reply app/gui/src/presenter.rs]: I think there is a simple solution for that. We can always use this instead:

```
error!("Cannot open or create project. {error}");
```

And now, you always have nicely formatted errors and you can always assume they are sentences.

File: app/gui/src/presenter.rs (hunk 8 above)
Comment (wdanilo) [reply app/gui/src/presenter.rs]: I think the old version was even better and still provide the necessary information to the developer: `Project Manager API not available, cannot open project.`. Why putting the name of the struct in the error message is better than just creating a sentence as the previous version? I'm talking about it to find a common ground here and make a decision about similar situations for the future.

File: app/gui/src/presenter.rs (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/presenter.rs]: Yes, I just read it as `((fake progress) indicator)` while you seemingly `(fake (progress indicator))` ;) We may make a clarification there.

File: app/gui/src/presenter.rs (hunk 9 above)
Comment (wdanilo) [reply app/gui/src/presenter.rs]: Right. It's a getter, but it is kind of an unsafe getter - it gets a variable from JS, casts it to a type, etc. Somewhere in EnsoGL we just have already a logic of getting app and throwing an error if it's not defined. This is a logic duplication. It would be good not to duplicate it.

Comment (farmaazon) [reply app/gui/src/presenter.rs]: Let's mark it as "TODO" right now to refactor properly, because we must move to more pressing issues.

File: app/gui/src/controller/ide.rs (hunk 1 above)
Comment (Procrat) [reply app/gui/src/controller/ide.rs]: This is just a line from the old code I added some words to. In the codebase I see a mix of unquoted, single quotes, backticks and `[]` (in the engine) being used. I couldn't find other logs in this file like you mentioned, so do you have a preference?

File: app/gui/src/controller/ide.rs (hunk 2 above)
Comment (Procrat) [reply app/gui/src/controller/ide.rs]: Thanks for explaining it, @farmaazon. I agree that the complexer signature makes it even more clear. I'll change it to that.

(It's indeed `'a: 'c, 'b: 'c, 'c`: you can remember it by reading `:` as "outlives".)

File: app/gui/src/presenter.rs (hunk 6 above)
Comment (Procrat) [reply app/gui/src/presenter.rs]: This was just a comment that I copied over from the existing code that showed the spinner when switching projects. I can change it if it helps you.

Comment (Procrat) [reply app/gui/src/presenter.rs]: Well, it will be removed when I change it to progress over a hard-coded amount of time.

File: app/gui/src/presenter.rs (hunk 7 above)
Comment (Procrat) [reply app/gui/src/presenter.rs]: Shall I just remove the period for now? Changing colons to periods would make it inconsistent with the rest of the codebase, right?

File: app/gui/src/presenter.rs (hunk 8 above)
Comment (Procrat) [reply app/gui/src/presenter.rs]: I just took that line from the similar functions above it. I'm happy to change it to whatever. I don't think it's important at all. I'll change it here and in the functions above to "Project Manager API not available, cannot open project."

File: app/gui/src/presenter.rs (hunk 7 above)
Comment (vitvakatu) [reply app/gui/src/presenter.rs]: Let's not preserve consistency but rather use `error!("Cannot open or create project. {error}");` in this PR. I little inconsistency in error messages is not a serious issue, and we don't have time to update the whole project.

File: app/gui/view/src/project_list.rs (hunk 10 above)
Comment (Procrat) [reply app/gui/view/src/project_list.rs]: 1. This isn't a sentence, is it?
2. I was mimicking the `set_` style I've seen for other FRP inputs. ([Example](https://github.com/enso-org/enso/blob/develop/lib/rust/ensogl/component/label/src/lib.rs#L69-L70))

File: app/gui/view/src/project_list.rs (hunk 11 above)
Comment (Procrat) [reply app/gui/view/src/project_list.rs]: Hmmm, I'm not sure in what sense you want them simplified. Could you give an example?

Most of the code here was moved here from `presenter::project`, but I can have a look at refactoring it if you can give some guidance.

File: app/gui/src/ide.rs (hunk 12 above)
Comment (Procrat) [reply app/gui/src/ide.rs]: Ah, that must have been an accident. Sorry!

File: app/gui/src/controller/ide/desktop.rs (hunk 4 above)
Comment (Procrat) [reply app/gui/src/controller/ide/desktop.rs]: It does. I changed it.

File: app/gui/view/src/project_list.rs (hunk 10 above)
Comment (wdanilo) [reply app/gui/view/src/project_list.rs]: 1. Exactly, it is not, but it should be a sentence.
2. The documentation tells that this FRP stream is "A list of projects". If it is "a list of projects", it should be named "project_list" or something like that. If this FRP stream is not designed to list projects, then the documentation is invalid, as the docs does not tell that this stream is used to set the list of the projects.

File: app/gui/view/src/project_list.rs (hunk 11 above)
Comment (wdanilo) [reply app/gui/view/src/project_list.rs]: I'll give a few examples here, but you need to go trough available FRP functions and see what can be applied here to simplify these definitions.

For example:

```
some_project_selected <- frp.output.selected_project
     .filter_map(|selection| selection.clone());
```

Is the same as

```
some_project_selected <= frp.output.selected_project;
```

Things such as this:

```
grid.reset_entries <+ frp.input.set_projects.map(|projects| {
                 let cols = 1;
                 let rows = projects.len();
                 (rows, cols)
             });
```

can be defined as:

```
// We are using `p` here, as it is obvious that it refers to `projects` as it is defined just 
// a few chars after the reference to `input.set_projects`. Ofc this comment is for you,
// should not land in the real code ;)
rows_and_cols <- frp.input.set_projects.map(|p| (p.len(), 1)); 
grid.reset_entries <+ rows_and_cols;
```

**Comment by wdanilo** [comment]
> Beside the provided comments:
> 
> 1. I think we should make the spinner progressing from x% -> 100% over some hardcoded amount of time. Otherwise, it looks like the app just hanged.
> 2. I don't think the 80% is a good choice here. Loading the app is still much faster than its initialization, so, if we try to make it closer to reality, this should be probably a lower number.

My comments from the previous review were not applied (or the video was not updated) and I was again requested to review this PR. What is the status of that? Are these comments applied, or we don't want to apply them for some reason?

**Comment by Procrat** [comment]
> > Beside the provided comments:
> > 
> > 1. I think we should make the spinner progressing from x% -> 100% over some hardcoded amount of time. Otherwise, it looks like the app just hanged.
> > 2. I don't think the 80% is a good choice here. Loading the app is still much faster than its initialization, so, if we try to make it closer to reality, this should be probably a lower number.
> 
> My comments from the previous review were not applied (or the video was not updated) and I was again requested to review this PR. What is the status of that? Are these comments applied, or we don't want to apply them for some reason?

I've updated the video for you now. Feel free to review the code.

File: app/gui/src/controller/ide.rs (hunk 1 above)
Comment (wdanilo) [reply app/gui/src/controller/ide.rs]: I think the nicest way of doing it would be to write `Attempting to create project with name '{name}'.` :)

File: app/gui/src/presenter.rs [hunk 13]
```diff
@@ -113,23 +129,75 @@ impl Model {
...
+        }));
+    }
+}
+
+/// Show a full-screen spinner for the exact duration of the specified function.
+async fn with_progress_indicator<F, T>(f: F)
+where
+    F: FnOnce() -> T,
+    T: Future<Output = ()>, {
+    // TODO: Use a safer variant of getting the JS app.
```
Comment (wdanilo) [inline app/gui/src/presenter.rs]: This TODO does not have initials and does not explain why it is unsafe. Every TODO/FIXME should always describe why it is bad and what is the right way of doing it, preferably linking to a ticket about it. I'm OK with not having the ticket, but the description should be understandable by any code reader after longer period of time. This tells about "safer variant" but does not describe what is the safer variant nor why this is unsafe.

**Review by wdanilo — APPROVED** [review]
Also a question - this new code works fine with debug scenes, right? Was it checked?

**Comment by Procrat** [comment]
> Also a question - this new code works fine with debug scenes, right? Was it checked?

I just checked again because I couldn't remember anymore whether I had done that. It all looks good. I wasn't expecting any issues since the spinners are driven from the project presenter and the debug scenes are just views without a presenter.

**Comment by vitvakatu** [comment]
# QA Report 🔴 

1. I noticed an issue when switching to a different project with the `Ctrl-o` shortcut. After the spinner is finished, the application dies (wasm part, the electron is still up, but our renderer stops working).

```
IPC error: "panicked at 'called `Option::unwrap()` on a `None` value', lib/rust/ensogl/component/text/src/font/glyph.rs:479:37\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:17612:17)\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[28991]:0x1533c22\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[13202]:0x11f1159\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[25227]:0x14a121e\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[19737]:0x1430e2a\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[12108]:0x1175db0\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[17333]:0x13b1c83\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[413]:0x1ae453\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[10853]:0x10e3e0a\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1752]:0x7edc23\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[11910]:0x1167039\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1752]:0x7edc23\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[15771]:0x1338e5f\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f0584\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[16158]:0x1368bc8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f050e\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[14001]:0x127a41d\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2193]:0x8bcdaf\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[6725]:0xe2dd2f\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1058]:0x605dda\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f0584\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[14547]:0x12bff71\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[421]:0x21b7d2\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2852]:0x9d5b16\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[15701]:0x1335575\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[16153]:0x1367d72\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[18407]:0x13fbe91\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[6001]:0xd5bfb8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[3485]:0xad3ff7\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[3197]:0xa6662d\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[4365]:0xba71c8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[17950]:0x13ed8a6\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[27362]:0x14d8f2c\n    at __wbg_adapter_89 (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16984:8)\n    at real (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16907:14)\n\n"
```

I can't reproduce this issue on the recent develop, but it might be a coincidence.

I also faced another issue, but it is happening on develop as well, reported here: https://github.com/enso-org/enso/issues/6438

**Comment by wdanilo** [comment]
> # QA Report 🔴
> 1. I noticed an issue when switching to a different project with the `Ctrl-o` shortcut. After the spinner is finished, the application dies (wasm part, the electron is still up, but our renderer stops working).
> 
> ```
> IPC error: "panicked at 'called `Option::unwrap()` on a `None` value', lib/rust/ensogl/component/text/src/font/glyph.rs:479:37\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:17612:17)\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[28991]:0x1533c22\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[13202]:0x11f1159\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[25227]:0x14a121e\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[19737]:0x1430e2a\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[12108]:0x1175db0\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[17333]:0x13b1c83\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[413]:0x1ae453\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[10853]:0x10e3e0a\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1752]:0x7edc23\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[11910]:0x1167039\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1752]:0x7edc23\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[15771]:0x1338e5f\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f0584\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[16158]:0x1368bc8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f050e\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[14001]:0x127a41d\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2193]:0x8bcdaf\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[6725]:0xe2dd2f\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1058]:0x605dda\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2326]:0x8f0584\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[14547]:0x12bff71\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[421]:0x21b7d2\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[2852]:0x9d5b16\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[15701]:0x1335575\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[16153]:0x1367d72\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[18407]:0x13fbe91\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[6001]:0xd5bfb8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[3485]:0xad3ff7\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[3197]:0xa6662d\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[4365]:0xba71c8\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[17950]:0x13ed8a6\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[27362]:0x14d8f2c\n    at __wbg_adapter_89 (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16984:8)\n    at real (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16907:14)\n\n"
> ```
> 
> I can't reproduce this issue on the recent develop, but it might be a coincidence.
> 
> I also faced another issue, but it is happening on develop as well, reported here: #6438

Ilya, amazing job with Q/A as always. The failing line is 

```
scene.context.borrow().as_ref().unwrap()
```

which basically means, that we do not get WebGL context anymore. Could you try reproducing it again? This might have been indeed an accidental thing, as it is possible to lose WebGL context anytime. However, this should be very rare and we should handle it better then. Anyway, if you could repro it, then it is an issue.

**Comment by vitvakatu** [comment]
I restarted my machine and tried again. Now it is even worse – not only it crashes when opening a project with `ctrl-o`, but it also crashes when:
1. I create a new node. The crash happens immediately after pressing enter to accept the suggestion. The node is created, though; after reopening the project, I see it.
2. I remove any node. The crash happens immediately after pressing backspace.

This is not reproducible on the most recent develop or other branches, so assume the issue is related to this PR.

I also retrieved logs from devtools:

[logs-context-loss.log](https://github.com/enso-org/enso/files/11340951/logs-context-loss.log)

**Comment by Procrat** [comment]
Good catch, @vitvakatu. And thanks for the logs. I'll investigate it.

Any ideas up front as to how the WebGL context might get lost?

**Comment by Procrat** [comment]
I tried reproducing it, but to no avail, unfortunately.

Looking into when WebGL contexts get lost, it sounds like most of them are external reasons [[1](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/isContextLost#usage_notes)][[2](https://www.khronos.org/webgl/wiki/HandlingContextLost#Handling_Lost_Context_in_WebGL)] and the only thing I can think of is that this PR is somehow putting extra pressure on the GPU. Any ideas why this might be the case? I'm a bit lost here.

**Comment by vitvakatu** [comment]
Not sure what can be the cause here. @wdanilo do you have any ideas? @Procrat let's check it with someone else's machine as well, preferably on MacOS/Windows. This might be an issue specific to my machine. It's quite serious so we can't just ignore it, unfortunately.

**Comment by kazcw** [comment]
@vitvakatu Could you copy the GPU report that opens with Ctrl+Alt+G, immediately after reproducing the context loss?

**Comment by vitvakatu** [comment]
@kazcw here it is: https://gist.github.com/vitvakatu/f4bd15728254555ef6866700bc1bb2f8

<blockquote><div> Gist</div><div><strong><a href="https://gist.github.com/vitvakatu/f4bd15728254555ef6866700bc1bb2f8">log.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by farmaazon** [comment]
> @Procrat let's check it with someone else's machine as well, preferably on MacOS/Windows. This might be an issue specific to my machine. It's quite serious so we can't just ignore it, unfortunately.

I'm checking the branch on macOS

**Comment by vitvakatu** [comment]
@kazcw I know you are busy with other stuff, but did you manage to look at my logs?

**Comment by wdanilo** [comment]
Actually, this might NOT be the context loss. Somewhere in EnsoGL we are initializing context. This PR changes a lot of logic regarding project starting. Could you please check if the code initializes EnsoGL scene correctly, as it was done before? You'd need to add some logs here and there in EnsoGL scene around context initialization to check if it is still initialized after your changes, before anything is drawn to the screen. I'm starting to believe that this is the cause.

**Comment by vitvakatu** [comment]
I'll check it

**Comment by wdanilo** [comment]
@vitvakatu I was asking @Procrat to check it, as he is the author. Of course you can check it if you want, but I'm just explaining my message above, as you might have understood that my request was for you. Sorry for writing it not explicitly enough :)

**Comment by vitvakatu** [comment]
Yeah, my idea was that only I can reliably reproduce this issue it seems :)

**Comment by wdanilo** [comment]
Ohh, I forgot about that, that only you can reproduce it always. Hmm, in `Scene` you have `set_context` method. Check if it is called with `Some` value before the crash

**Comment by kazcw** [comment]
@vitvakatu's log indicates that the render thread has crashed. Unfortunately, I don't see anything that could help explain why.

@vitvakatu, could you try this:
- Rename Enso's electron cache folder, so that the app can't find it (but we still have it for debugging later).
- Run the app and see if it's still happening.
Probably hiding the cache won't stop the bug from repeating, but if it does that would indicate that a nondeterministic failure may be appearing deterministically-associated with this branch because of cached Electron-internal data.

**Comment by wdanilo** [comment]
Oh, @kazcw is right. @vitvakatu ignore my requests above, this is clearly not the case here.

**Comment by vitvakatu** [comment]
>  Rename Enso's electron cache folder, so that the app can't find it (but we still have it for debugging later).
    Run the app and see if it's still happening.
    Probably hiding the cache won't stop the bug from repeating, but if it does that would indicate that a nondeterministic failure may be appearing deterministically-associated with this branch because of cached Electron-internal data.

I tried renaming the following directories:
1. `~/Library/Application Support/Electron`
2. `~/Library/Application Support/Enso`
3. `~/Library/Application Support/enso`

Neither has fixed the crash.

**Comment by kazcw** [comment]
This is hard to debug further without a debug build of electron. That requires building electron from source, though.

**Comment by vitvakatu** [comment]
Today I have found when the crash happens, but I didn't find the exact code location yet. It happens each time at the same place (when we call the `find_project` call to the project manager), but the crash happens in another async task when we switch to it on `await`. I'm tracking down the list of active async tasks now, and I hope to find the exact code location where it happens soon enough.

**Comment by wdanilo** [comment]
@vitvakatu what happens if your un chrome with `--disable-gpu-watchdog`? The same question with `--force-separate-egl-display-for-webgl-testing` and with `--full-memory-crash-report`.

Also, could you run Chrome with ` --enable-gpu-command-logging` and see what are the logs in the system console when the error happens?

**Comment by vitvakatu** [comment]
After running in Chrome with `--disable-gpu-watchdog`:

(context loss still happens)

```
2023-05-11 12:29:45.184 Google Chrome[14818:4338947] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
2023-05-11 12:30:39.835 Google Chrome[14818:4338947] +[CATransaction synchronize] called within transaction
[14818:259:0511/123043.911645:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=11
[14892:20227:0511/123059.073802:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

Running with `--force-separate-egl-display-for-webgl-testing` and with `--full-memory-crash-report`:

```
❯ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --force-separate-egl-display-for-webgl-testing --full-memory-crash-report
2023-05-11 12:33:16.392 Google Chrome[15146:4343049] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
2023-05-11 12:33:54.168 Google Chrome[15146:4343049] +[CATransaction synchronize] called within transaction
[15146:259:0511/123357.367790:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=11
```

When running with `--enable-gpu-command-logging` the logs are here:

[log.txt](https://github.com/enso-org/enso/files/11450262/log.txt)

I started opening the second project after line `124645.857599`, and we lost the context soon after. The logs continue till the WASM panic at the end. I think most of the messages are displayed because of the spinner animation, it doesn't seem to produce a lot of messages otherwise.

**Comment by kazcw** [comment]
That's very interesting. It seems like Chromium on MacOS has a bug when the script shows an SVG in the DOM too close in time to performing WebGL operations. We can probably work around it by flushing the WebGL pipeline before showing the SVG.

**Comment by vitvakatu** [comment]
@kazcw I don't think it is correct, I can reproduce the context loss even if no spinner is ever displayed:


https://github.com/enso-org/enso/assets/6566674/98de3a02-80ad-4dae-8cdd-6c735da8cca8

**Comment by kazcw** [comment]
> @kazcw I don't think it is correct, I can reproduce the context loss even if no spinner is ever displayed:
> 2023-05-11.18-46-03.mp4

The spinner is supposed to be displayed when opening a project. It isn't displayed because right when it should appear, the render process crashes. Right?

A definitive test of my hypothesis would be: Comment out the bodies of `showProgressIndicator` and `hideProgressIndicator` in `runner/index.ts`. If that prevents the crash, it is definitely a Chromium bug (probably of the nature I have described). If that doesn't prevent the crash, I'm wrong.

**Comment by vitvakatu** [comment]
> The spinner is supposed to be displayed when opening a project. It isn't displayed because right when it should appear, the render process crashes. Right?

No, I disabled showing the spinner by commenting relevant code. So on the video, no spinner is ever displayed, but the crash still happens. So it's not about rendering SVG.

**Comment by kazcw** [comment]
> > The spinner is supposed to be displayed when opening a project. It isn't displayed because right when it should appear, the render process crashes. Right?
> 
> No, I disabled showing the spinner by commenting relevant code. So on the video, no spinner is ever displayed, but the crash still happens. So it's not about rendering SVG.

Ah ok, I saw the IDE-loading spinner at 0:04 and thought it was an open-project spinner.

I'm surprised that isn't the problem, because: This PR doesn't change much other than when the spinner is shown; The `+[CATransaction synchronize] called within transaction` error sounds like a logic bug in low-level rendering code; The transaction error [apparently occurs when intermingling animations on MacOS](https://stackoverflow.com/questions/7196197/catransaction-synchronize-called-within-transaction). This would have all made sense :smile:

**Comment by vitvakatu** [comment]
So that was really funny. I was investigating what exact code change in this PR caused the regression and couldn't find it! It turns out the regression was present on the develop before this PR. How did I not notice it? Well, it is no longer reproducible on the most recent develop (and on develop 34+ commits old). So we had some regression that caused context loss when switching projects for some time, and then it was accidentally fixed in some PR.

That means this PR can finally be merged, I updated it to the latest develop, and QA tested it.

While investigating this bug, I created some infrastructure for debugging async tasks – I think it might be useful for similar investigations in the future, so I will open a separate PR with this code.
