### PR TITLE
Show error pop-up when failing to rename a project

### LINKED ISSUE #5065: Renaming project does not work if the name contains a space.
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184279582).
<hr />

### Steps to reproduce
1. Create a new project in the IDE
2. Edit the project name to something that contains a space (" "). 

### Expected
The project should be renamed (or an error should be shown if the name is illegal) and after re-opening the new name should be used. 

### Actual
The name is changed, but after restarting the project, the project has the old name.

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Closes #5065: when a project can't be renamed, it now shows an error pop-up and stays in edit mode.

https://user-images.githubusercontent.com/607786/234025360-6761f7d6-c13c-479c-a0ba-8af5d81f6e87.mp4

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/model/project/synchronized.rs [hunk 1]
```diff
@@ -708,7 +715,17 @@ impl model::project::API for Project {
             let project_manager = self.project_manager.as_ref().ok_or(ProjectManagerUnavailable)?;
             let project_id = self.properties.borrow().id;
             let project_name = ProjectName::new_unchecked(name);
-            project_manager.rename_project(&project_id, &project_name).await?;
+            project_manager.rename_project(&project_id, &project_name).await.map_err(|error| {
+                match error {
+                    RpcError::RemoteError(cause) =>
+                        if cause.code == 4001 {
```
Comment (kazcw) [inline app/gui/src/model/project/synchronized.rs]: Numbers should be named constants.

File: app/gui/src/model/project/synchronized.rs [hunk 2]
```diff
@@ -708,7 +715,17 @@ impl model::project::API for Project {
...
+                            failure::Error::from(ProjectNameInvalid { cause: cause.message })
+                        } else {
+                            RpcError::RemoteError(cause).into()
+                        },
+                    error => error.into(),
+                }
```
Comment (kazcw) [inline app/gui/src/model/project/synchronized.rs]: This logic would be simpler with a match guard.

**Review by wdanilo — CHANGES_REQUESTED** [review]
Instead of reverting to an old name, the error should appear and the name should not be accepted, leaving the text field in the edit mode. If someone tried renaming the project to "really_long_and_complex name" and made a typo, reverting the name without giving the user the ability to fix the typo is a really bad UX.

**Review by kazcw — APPROVED** [review]

**Comment by farmaazon** [comment]
> Instead of reverting to an old name, the error should appear and the name should not be accepted, leaving the text field in the edit mode. If someone tried renaming the project to "really_long_and_complex name" and made a typo, reverting the name without giving the user the ability to fix the typo is a really bad UX.

@Procrat So, this would need checking it on our side (We cannot keep edit mode waiting for the engine's response).

As the project's name must be a valid identifier, we could just check if it's parsed as Cons (Var also could be accepted, but I'm not sure).

Reverting name when engine returned error should be still kept.

File: app/gui/view/src/popup.rs [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+
+/// Text label that disappears after a predefined delay.
+#[derive(Debug, Clone, CloneRef)]
+struct Model {
+    label:           Label,
+    network:         frp::Network,
+    delay_animation: DelayedAnimation,
+    /// Show the pop-up with the given message.
+    pub show:        frp::Source<String>,
+}
```
Comment (farmaazon) [inline app/gui/view/src/popup.rs]: This is a bit strange, that Model has it's FRP input (`show`) and `network`. The main reason we're making this models it to separate them from network (so capturing model won't leak any networks). The logic should be in View::new.

File: app/gui/view/src/popup.rs [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+
+        frp::extend! { network
+            init <- source_();
+            let shape  = app.display.default_scene.shape();
+            _eval <- all_with(shape, &init, f!([model](scene_size, _init) {
+                let half_height = scene_size.height / 2.0;
+                let label_height = model.label_height();
+                let pos_y = half_height - PADDING_TOP - label_height / 2.0;
+                model.label.display_object().set_y(pos_y);
+            }));
```
Comment (farmaazon) [inline app/gui/view/src/popup.rs]: This could be a method of Model. This way we keep FRP construction shorter and easier to read.

**Review by farmaazon — CHANGES_REQUESTED** [review]

File: app/gui/src/model/project/synchronized.rs (hunk 2 above)
Comment (Procrat) [reply app/gui/src/model/project/synchronized.rs]: Oh yeah, good catch!

File: app/gui/view/src/popup.rs (hunk 3 above)
Comment (Procrat) [reply app/gui/view/src/popup.rs]: Ah yes, I was trying to simplify the structure by not having a separate `PopupLabel` abstraction, this got a bit mixed. I'll fix it.

**Review by farmaazon — APPROVED** [review]

**Comment by farmaazon** [comment]
@Procrat please update the PR description and the video with the new behavior.

**Comment by Procrat** [comment]
> @Procrat please update the PR description and the video with the new behavior.

Done.

File: CHANGELOG.md [hunk 5]
```diff
@@ -132,6 +132,11 @@
   quickly understand each button's function.
 - [File associations are created on Windows and macOS][6077]. This allows
   opening Enso files by double-clicking them in the file explorer.
+- [Feedback when renaming a project][6366]. When the user tries to rename the
+  project to an invalid name, a helpful error message is shown and the name is
+  reverted.
```
Comment (wdanilo) [inline CHANGELOG.md]: The name should not be reverted. I understand that this sentence is incorrect now, right?

File: app/gui/src/model/project/synchronized.rs [hunk 6]
```diff
@@ -30,6 +30,14 @@ use parser::Parser;
 
 
 
+// =================
+// === Constants ===
+// =================
+
+const ERROR_CODE_PROJECT_NAME_INVALID: i64 = 4001;
```
Comment (wdanilo) [inline app/gui/src/model/project/synchronized.rs]: Is this just a random number or it is synchronized with some backend API? There should be documentation about it here. If this is backend stuff, are there other error codes somewhere in our Rust codebase? If so, this constant should be defined next to other error codes.

File: app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs [hunk 7]
```diff
@@ -214,6 +216,24 @@ impl ProjectNameModel {
...
+        self.commit(name);
+        Ok(())
+    }
+
+    /// Check whether the given name is a valid project name.
+    fn validate(name: impl Str) -> Result<(), String> {
+        let parser = Parser::new();
+        match parser.parse_line_ast(name).map(|ast| ast.shape().clone()) {
+            Ok(ast::Shape::Cons(_)) => Ok(()),
+            _ => Err("The project name should be in Upper_Snake_Case.".to_owned()),
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs]: Minor thing, but I'd change it to `The project name should use the 'Upper_Snake' case.` This explains that this is a convention case in plain English rather than encoding the "case" information in the name.

File: app/gui/view/src/popup.rs [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+    /// Constructor.
+    pub fn new(app: &Application) -> Self {
+        let frp = Frp::new();
+        let network = &frp.network;
+        let model = Model::new(app, network);
+
+        frp::extend! { network
+            init <- source_();
+            let scene_shape = app.display.default_scene.shape();
+            _eval <- all_with(scene_shape, &init, f!([model] (scene_shape, _init)
```
Comment (wdanilo) [inline app/gui/view/src/popup.rs]: you don't need `[model]` here.

File: app/gui/view/src/popup.rs [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+    fn display_object(&self) -> &display::object::Instance {
+        self.model.label.display_object()
+    }
+}
+
+impl Deref for View {
+    type Target = Frp;
+
+    fn deref(&self) -> &Self::Target {
+        &self.frp
```
Comment (wdanilo) [inline app/gui/view/src/popup.rs]: you can derive it

**Review by wdanilo — APPROVED** [review]

File: CHANGELOG.md (hunk 5 above)
Comment (Procrat) [reply CHANGELOG.md]: Good catch

File: app/gui/src/model/project/synchronized.rs (hunk 6 above)
Comment (Procrat) [reply app/gui/src/model/project/synchronized.rs]: I didn't see it defined in [here](https://enso.org/docs/developer/enso/language-server/protocol-language-server.html#error), but I've put it in [here](https://github.com/enso-org/enso/blob/b5c1432fcc498a17fb4ff2fd1b980278780f7eb3/app/gui/controller/engine-protocol/src/common/error.rs). That seemed like the best place.

**Comment by vitvakatu** [comment]
## QA Report 🔴 

I assume the popup with the error should always be visible, even if the scene is panned. This is not the case.

Screenshot 2023-04-27 at 21 42 20

**Comment by Procrat** [comment]
Good catch, @vitvakatu. I've found the reason: I had changed the pop-up's layer to the default layer of `Label`, which is the tooltip, but that one moves along when panning. Now, the reason why I originally deleted the code that explicitly sets it to the panel layer, is because that created this super weird bug where the other text on that layer just disappears (status bar, project name, breadcrumbs, project switcher, ...). I had spent some time looking into what could cause it, but I'm all out of ideas really.

popup-layer-bug

**Comment by vitvakatu** [comment]
@kazcw @wdanilo do you have any ideas about what can cause this issue?

**Comment by Procrat** [comment]
You can try it out on this branch: `wip/procrat/temp-rename-project-with-space-5065-panel-layer`

**Comment by kazcw** [comment]
This is in the log:

> [WARN] lib/rust/ensogl/component/text/src/component/text.rs:1409 Internal error. Line metrics was not computed.

It might be relevant, as I've never seen it come up before

Edit: The bug always happens, this warning sometimes does not. Probably not related.

**Comment by kazcw** [comment]
It seems related to using multiple fonts in the same layer. If I remove `label.set_font(font)` from `Label`, the problem does not occur

**Comment by kazcw** [comment]
I have found the problem. I'll have a fix ready later today.

**Comment by Procrat** [comment]
It seems to work with the changes in #6477, so once that's merged, this PR should be good for another round of QA.

**Comment by sylwiabr** [comment]
@Procrat who is doing a QA here? can we merge it?

**Comment by Procrat** [comment]
> @Procrat who is doing a QA here? can we merge it?

@sylwiabr Ilya was going to do another round, but he's been delayed as you know. We can ask someone else if it's urgent.

**Comment by sylwiabr** [comment]
I think Ilia is quite overloaded and will be later today, @mwu-tow or @MichaelMauderer can you do QA here?

**Comment by MichaelMauderer** [comment]
I can have a look today.

**Review by vitvakatu — APPROVED** [review]
Sorry for the delay, QA passed. Next time please merge develop into this branch, it didn't work without fixes from there. I made a merge myself, please check for conflicts before merging this PR.
