### PR TITLE
Gather diagnostics from annotations

### LINKED ISSUE #8289: Wrong `@column Widget_Helpers.make_column_name_selector` yields no compiler error
There is a bug in 
[@column Widget_Helpers.make_column_name_selector](https://github.com/enso-org/enso/blob/6cf75daea9905dc266704e8c1d658cf4d87377b5/distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso#L74)
as `Widget_Helpers` isn't resolved symbol. That means the widget cannot be working.

There is also bug in the compiler. No error is reported during compilation either. **Expected**: compilation fails with symbol not found.

PS: I've realized that when working on [https://github.com/enso-org/enso/pull/8207/commits/f2886a26d4b9370bcd559fb239ab5ccdffd4e21d] - there was an `errors.Resolution` object in the caches. 
```
java.io.IOException: No persistance for org.enso.compiler.core.ir.expression.errors.Resolution
        at org.enso.compiler.core.Persistance$PersistanceMap.searchSupertype(Persistance.java:481)
        at org.enso.compiler.core.Persistance$PersistanceMap.searchSupertype(Persistance.java:474)
        at org.enso.compiler.core.Persistance$PersistanceMap.searchSupertype(Persistance.java:474)
        at org.enso.compiler.core.Persistance$PersistanceMap.forType(Persistance.java:491)
        at org.enso.compiler.core.Persistance$Generator.writeIndirect(Persistance.java:129)
        at org.enso.compiler.core.Persistance$ReferenceOutput.writeObject(Persistance.java:269)
        at org.enso.compiler.core.ir.PersistCallArgument_Specified.writeObject(PersistCallArgument_Specified.java:25)
```
Having errors in caches (of system libraries) isn't something we want.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #8289 

Changelog
- feat: `GatherDiagnostics` compiler pass works with annotations

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala [hunk 1]
```diff
@@ -109,6 +109,28 @@ class GatherDiagnosticsTest extends CompilerTest {
...
+        """@x bar
+          |foo x = x
+          |""".stripMargin.preprocessModule
+      val result = GatherDiagnostics.runModule(ir, moduleContext)
+      val diagnostics = result
+        .unsafeGetMetadata(GatherDiagnostics, "Impossible")
+        .diagnostics
+
+      diagnostics should have size 1
+      diagnostics.map(_.message(null)) should contain theSameElementsAs Seq(
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala:129]: Can you add a test to the [ErrorCompilerTest](https://github.com/enso-org/enso/blob/87dfb57f53a941c903cae66ceba6ce4bc4ab25a1/engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java#L12) - that'd be real unit test. The test here is more integration one.

**Review by JaroslavTulach — APPROVED** [review]
Please update the [ErrorCompilerTest](https://github.com/enso-org/enso/blob/87dfb57f53a941c903cae66ceba6ce4bc4ab25a1/engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java#L12)
