### PR TITLE
Display error message in status bar when execution failed

### LINKED ISSUE #6859: Let the user know that the engine has entered a 'bad state'
From time to time the engine fails with a fatal error that makes it unable to perform _any_ computations, essentially freezing the GUI as any new nodes that are added are not going to get their results computed.

Sometimes it suffices to remove some offending node that caused this state, sometimes a restart of the IDE is also required. But some action is needed. Currently, in the IDE the only indicator of this is that no new values are being computed - making the user confused as to why the IDE is frozen.

The only way to discover that engine entered such a state is to inspect the logs. This is usually accompanied by a log message `Execution of function main failed`.

The user cannot be expected to browse the logs to understand that the engine is failing. Instead, we should detect this situation and display some kind of a message to the user. Such message should disappear once the engine starts working and sending updates again.

This was [originally proposed on Discord](https://discord.com/channels/401396655599124480/1111327381924347914/1111343076884091013) by @Akirathan. There, he also suggested that ideally we should detect what node is causing such a fatal failure and highlight that node in the IDE - letting the user know that they may try to remove that node which could fix the issue. If detecting the 'offending' node is indeed feasible, it may be worth implementing as well.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #6859 

https://github.com/enso-org/enso/assets/6566674/326b4fd9-b26c-4252-aab6-3c205457a2fa

Latest state:

Screenshot 2023-06-02 at 12 34 23

### Important Notes

- ~~Is current message to the user correct? Do we need to say something more?~~

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/ide.rs [hunk 1]
```diff
@@ -28,6 +28,8 @@ pub use initializer::Initializer;
 /// Text that shows up in the statusbar when any of the backend connections is lost.
 pub const BACKEND_DISCONNECTED_MESSAGE: &str =
     "Connection to the backend has been lost. Please try restarting IDE.";
+/// Text that shows up in the statusbar when backend reports a failed execution.
+pub const EXECUTION_FAILED_MESSAGE: &str = "Execution failed. Please try restarting IDE.";
```
Comment (farmaazon) [inline app/gui/src/ide.rs]: We could also display the message received from the engine, making debugging user problems easier.

The question is if the messages are not too long.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/ide.rs (hunk 1 above)
Comment (hubertp) [reply app/gui/src/ide.rs]: "Please report this problem at `support@enso.org`" as well?

**Comment by wdanilo** [comment]
1. Why what you entered in the searcher kills engine? It should not kill it. Is it a special mode for testing it?
2. When the execution failed, after restarting the IDE, is the project re-opened with the current state or user is loosing their work? If the latter, we need to fix it somehow (probably outside of this PR).
3. Can we have a button there, like? "Critical backend error, click here to restart Enso." ? 
4. After clicking it, before restarting, there should be a pop-up asking if you want to report the error with optional text field for expalanation what happened, as @hubertp suggested. However, such reporting has to be automatic, so after clicking "report and restart" the error should be reported automatically. Again, this might be out of scope of this PR.

**Comment by farmaazon** [comment]
1. I think Ilya is triggering bug https://github.com/enso-org/enso/issues/6821
2. Failed execution should not prevent us from sending update, so no code is lost, perhaps the cached values only.
3. 4. Let's do small steps first. I would merge this (with an email address as @hubertp suggested) and make an epic issue for improving this further (and not only this but any potential bug, like panics as well).

File: app/gui/src/ide.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/ide.rs]: The message from the engine seems to be too long. I added the email address as suggested

**Comment by vitvakatu** [comment]
1. Correct, I just asked Hubert how I can trigger execution failure for testing.
2. In this particular case, the state of the project is preserved (and the execution fails again). I think there might be cases when we don't save the latest changes, though. It needs to be checked.

**Comment by wdanilo** [comment]
@farmaazon 
2. Ok, no code is lost, but you need to restart Enso, so the current project is not getting saved then, right? So in the end, after restarting Enso, you'd lose some part of your work, am I correct?

**Comment by farmaazon** [comment]
> you need to restart Enso, so the current project is not getting saved 

I don't understand this inference. You need to restart Enso because execution is failing for some reason. What does it have to do with saving projects?

Of course, it _may_ happen if the engine is thoroughly broken, but this is not because of execution fail.

**Comment by farmaazon** [comment]
## QA report :banana:

The message is displayed as it should. However, when playing with it, I realized there are some ways of improvement:
1. Having the new dashboard, there _probably_ is no need for restarting _IDE_, but just the _project_: user could go back to dashboard, click "stop" butting and run project again. It also would make more sense in cloud (where closing the IDE does not stop the engine, so restarting it may be pointless).
2. If the restarting Project would work, I think there are high odds that restarting the execution may help (just clicking play button).
3. If the failure is due to failing code (as tested in this PR), the user might make it working again (or just undo changes). So I think I'll be safe to hide "Execution failed" message upon successful execution. But I'm not sure what notification would help us - the executionComplete seems to be sent always, also after failing executions. You may ask @4e6 for guidance.

From the above points, I think we could change the second sentence to "Please try restarting project or IDE and..." or - if we would implement the point 3 - "Please try to re-execute graph, restart project or IDE..."

**Comment by 4e6** [comment]
> safe to hide "Execution failed" message upon successful execution

Currently, the engine sends `executionComplete` when the execution is finished, and `executionFailed` in case of failures. We can change the logic to indicate success & failure outcomes with these two messages. In other words, `executionFailed` will be sent in cases of failures (as before) and `executionComplete` otherwise. I.e. the IDE will receive only one of the two messages when the program execution finishes.

**Comment by vitvakatu** [comment]
I adjusted the text on the label as suggested and created additional issues for improvements, @farmaazon please confirm if we can merge it now.

**Comment by wdanilo** [comment]
image

I started to wonder what is banana-like approval :P

**Comment by farmaazon** [comment]
> I started to wonder what is banana-like approval :P

It's a variation of :yellow_circle: (not red, but also not entirely green).

**Comment by wdanilo** [comment]
> > I started to wonder what is banana-like approval :P
> 
> It's a variation of 🟡 (not red, but also not entirely green).

I know! It just made me laugh, that was a nice touch :D
