### PR TITLE
Fix clicking-out Component Browser

### LINKED ISSUE #11829: Can't cancel adding new Component by clicking away
If I try to add a new component, I can no longer cancel adding by clicking off the CB

Regressed between RC4 and RC5

Version 2024.5.1-rc5
Build 6d24ed0182be2186d9885a0a4f1c6d82609c6407
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-rc5 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #11829

There was implicit `any` on refs, so the typechecker didn't catch missing property.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- ~~[ ] The documentation has been updated, if necessary.~~
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/ComponentBrowser.vue [hunk 1]
```diff
@@ -72,9 +72,8 @@ const emit = defineEmits<{
 const cbRoot = ref<HTMLElement>()
 const componentList = ref<ComponentInstance<typeof ComponentList>>()
 
-defineExpose({ cbRoot })
-
 const clickOutsideAssociatedElements = (e: PointerEvent) => {
+  console.log(props.associatedElements)
```
Comment (Frizi) [inline app/gui/src/project-view/components/ComponentBrowser.vue]: remove log

**Review by Frizi — APPROVED** [review]
