### PR TITLE
Fix file browser on Linux and Windows

### LINKED ISSUE #9503: File browse defaults to folder browse
https://github.com/enso-org/enso/assets/1720119/d621e7a3-4f43-4a55-a164-c3e4b8931ebb

Should be a file browse.

Also should the file browse be modal?

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #9503 

[The `showFileBrowser` documentation has a note](https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogsyncbrowserwindow-options), that Linux and Windows don't support enabling picking dir and file.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - ~~[ ] Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
approving minimal changes to electron code

File: app/ide-desktop/lib/client/src/index.ts [hunk 1]
```diff
@@ -381,15 +381,18 @@ class App {
         })
         electron.ipcMain.handle(
             ipc.Channel.openFileBrowser,
-            async (_event, kind: 'any' | 'directory' | 'file') => {
+            async (_event, kind: 'default' | 'directory' | 'file') => {
+                logger.log('Request for opening browser for ', kind)
```
Comment (vitvakatu) [inline app/ide-desktop/lib/client/src/index.ts:385]: Do we need that?

**Review by vitvakatu — APPROVED** [review]
