### PR TITLE
Fix component browser interactions.

### LINKED ISSUE #8064: Adding a new node with searcher
Pressing enter should open component browser. Accepting CB expression should add a new node with this expression. 

The CB position should be placed properly according to functions implemented in #8069

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Fixes: #8064 

Fixes broken interactions with of the component browser. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/ComponentBrowser.vue [hunk 1]
```diff
@@ -316,6 +318,10 @@ const handler = componentBrowserBindings.handler({
     applySuggestion()
   },
   acceptInput() {
+    applySuggestion()
+    acceptInput()
```
Comment (farmaazon) [inline app/gui2/src/components/ComponentBrowser.vue:317]:
```suggestion
    applySuggestion()
```
~~Applying accepting~~ suggestion should also accept input, unless we want to enter module, in which case CB should _not_ close.

Also, I would rename it as `acceptSuggestion`, and `acceptInputRaw` could be just `acceptInput`.

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/components/GraphEditor.vue [hunk 2]
```diff
@@ -48,6 +48,38 @@ const nodeSelection = provideGraphSelection(navigator, graphStore.nodeRects, {
...
+    const targetPos = targetNode?.position ?? Vec2.Zero
+    const offset = new Vec2(20, 35)
+    return targetPos.add(offset)
+  } else if (hasNodeSelected) {
+    const gapBetweenNodes = 48.0
+    return previousNodeDictatedPlacement(nodeSize, placementEnvironment.value, {
+      gap: gapBetweenNodes,
+    }).position
+  } else {
+    return mouseDictatedPlacement(nodeSize, placementEnvironment.value).position
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue:73]: i'm testing this out during the bookclub and this doesn't work, since this value is continuously computed.
specifically, doing this makes the cb follow the mouse - which is kinda cool to see, *but* that makes it not very useful, as it would be no longer possible to click around in the CB entries, docs breadcrumbs, and the CB input.

Comment (somebody1234) [reply app/gui2/src/components/GraphEditor.vue:73]: i don't think this needs to be changed, but you'd need another ref
```ts
const realComponentBrowserPosition = ref<Vec2>()
watch(componentBrowserVisible, visible => {
  if (visible) realComponentBrowserPosition.value = componentBrowserPosition.value
  else realComponentBrowserPosition.value = undefined
})
```

File: app/gui2/src/components/ComponentBrowser.vue (hunk 1 above)
Comment (MichaelMauderer) [reply app/gui2/src/components/ComponentBrowser.vue:317]: The `applySuggestion` method, right now, adds the currently selected suggestion in the CB to the input. This is what happens when pressing `tab`.

I thought we had three interactions here: 
* `tab` only applies the selected suggestion but keeps the CB open
* `enter` chooses the applied the selected suggestion and closes the CB 
* `ctrl+enter` closes the CB with the current input, without applying the selected suggestion.

Comment (farmaazon) [reply app/gui2/src/components/ComponentBrowser.vue:317]: Sorry, I re-read my comment, and now I cannot say what have I had in mind. You are right, of course. Only the names:
* `tab` I usually name "applying suggestion"
* `enter` is "_accepting_ suggestion"
* `ctrl+enter` is "accepting _input_"

Comment (MichaelMauderer) [reply app/gui2/src/components/ComponentBrowser.vue:317]: That sounds good, I'll apply that naming to the code, add a doc and that should make it consistent and clear.

File: app/gui2/src/components/GraphEditor.vue (hunk 2 above)
Comment (farmaazon) [reply app/gui2/src/components/GraphEditor.vue:73]: I, in turn, would just make function "openComponentBrowserParams" which inter alia will just set computed position to `componentBrowserPosition` without using reactivity, and then set visible to true.

But if you stick to @somebody1234 solution for some reason, I prefer renaming `componentBrowserPosition -> openedComponentBrowserPosition` or `newComponentBrowserPosition` and `realComponentBrowserPosition -> ` just `componentBrowserPosition`.

Comment (MichaelMauderer) [reply app/gui2/src/components/GraphEditor.vue:73]: I went with refactoring it to a function `targetComponentBrowserPosition` which is used to update the `componentBrowserPosition` when required.

**Comment by MichaelMauderer** [comment]
@Frizi Just missing your review now.

**Review by Frizi — APPROVED** [review]

File: app/gui2/src/components/GraphEditor.vue [hunk 3]
```diff
@@ -51,6 +54,29 @@ const interactionBindingsHandler = interactionBindings.handler({
   click: (e) => (e instanceof MouseEvent ? interaction.handleClick(e) : false),
 })
 
+// This is where the component browser should be placed when it is opened.
+function targetComponentBrowserPosition() {
+  const editedInfo = graphStore.editedNodeInfo
+  const isEditingNode = editedInfo != null
+  const hasNodeSelected = nodeSelection.selected.size > 0
+  const nodeSize = new Vec2(0, 24)
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor.vue:62]: I'm not sure I understand this hardcoded value. This is the expected size of a node that is about to be created by the component browser? If so, it should be loaded from a predefined constant. Let's change that soon, but in separate PR to not block anything.

File: app/gui2/src/components/GraphEditor.vue [hunk 4]
```diff
@@ -51,6 +54,29 @@ const interactionBindingsHandler = interactionBindings.handler({
...
+  if (isEditingNode) {
+    const targetNode = graphStore.db.nodes.get(editedInfo.id)
+    const targetPos = targetNode?.position ?? Vec2.Zero
+    return targetPos.add(COMPONENT_BROWSER_TO_NODE_OFFSET)
+  } else if (hasNodeSelected) {
+    const gapBetweenNodes = 48.0
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor.vue:68]: Another thing that definitely should be a constant. Also, why isn't the default gap value used instead?
