### PR TITLE
Two fixes: hidden CB entry and scrolling in text vis.

### LINKED ISSUE #7405: Can't scroll a JSON/Text visualisation
If you have a long JSON visualization the scroll bar doesn't
image

Neither the scroll wheel nor the scroll bar work.

### LINKED ISSUE #7445: The first entry in Component Browser may is scrolled too low and hidden from vie
Probably best desribed with an image:

image

The entry is there, but it's scrolled too low so it is not visible.

I've been able to reproduce it very consistently on the example from video (load an Excel file and try searching for `sheet_names` on it).

https://github.com/enso-org/enso/assets/1436948/0d3b317d-ba00-43bf-8afd-1e91783f555e

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #7405 
Fixes #7445 

The "hidden entry" bug was caused by wrong component browser position and size set when all displayed entries fit the viewport.

The scrolling issue was due to change various "hover rectangles" order - some were above the scroll bars.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 1]
```diff
@@ -180,11 +179,11 @@ ensogl::define_endpoints_2! {
 pub struct View {
     display_object:  display::object::Instance,
     selection:       Rectangle,
-    overlay:         Rectangle,
+    hover_area:      Rectangle,
     /// Resize grip is a rectangle with the size of the container but with a slight offset from the
-    /// overlay shape so that it extends beyond the container at the bottom and right sides.
-    /// The ordering of `overlay`, `selection`, and `resize_grip` is controlled by partition layers
-    /// (see [`View::init`]).
+    /// hover_area shape so that it extends beyond the container at the bottom and right sides.
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: Quote `hover_area`.

**Review by kazcw — APPROVED** [review]

**Comment by kazcw** [comment]
# QA: :green_salad:

When a visualization is resized while it is selected, the selection rectangle gets out of sync with the visualization geometry, and stays wrong until deselected:

image

Prior to this PR, resizing a visualization caused it to be deselected. The new behavior, maintaining selection during resize, seems like an improvement--except for the visual glitch.

It fixes the two bugs, and looks good other than this issue.

**Comment by farmaazon** [comment]
I've fixed the problem with selection, and I assume from the salad that I can merge this PR.
