### PR TITLE
Fixes on vue-react boundaries

### LINKED ISSUE #13039: Vue Router Regression - blinking view when switching category.
https://github.com/user-attachments/assets/017c1a58-a8db-48b8-b61c-466b52999498

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

* Proper fix for worked-around problem with category switching - fixes #13039 
* To do that, created a new store with query params, which batches multiple single query param updates. This also makes transitions working when switching categories, but somewhat accidentally - I would prefer to prefetch lists during navigation, but that's bigger refactoring.
* Also made vue-react reactivity more granular - before a single update on a store fiel rerenderred all components using this store, even irrelevant of that field (or reactivity didn't  actually work).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/providers/queryParams.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+  watch(queryParams, (newQueryParams) => {
+    const navigate = () => {
+      const query = Object.fromEntries(newQueryParams.entries())
+      if (anyPushed.value) {
+        router.push({ query })
+      } else {
+        router.replace({ query })
+      }
+    }
```
Comment (kazcw) [inline app/gui/src/providers/queryParams.ts:65]: I don't see `anyPushed` ever being reset to `false`. This seems like the place to do it.

File: app/gui/src/providers/queryParams.ts [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+    for (const [key, value] of newQueryParams) {
+      if (route.query[key] !== value) return navigate()
```
Comment (kazcw) [inline app/gui/src/providers/queryParams.ts:69]: Is this missing `getQueryValue` array-unwrapping?

Comment (farmaazon) [reply app/gui/src/providers/queryParams.ts:69]: Clearly, tests are missing some paths if this got through...

Comment (farmaazon) [reply app/gui/src/providers/queryParams.ts:69]: After thinking about it, I decided this is by design. Left comment here.

**Review by kazcw — APPROVED** [review]
