### PR TITLE
Restart Language Server on crash

### LINKED ISSUE #14769: Project Manager - restart language server after crash
Old PM restarted Language Server when it crashed. We need same mechanism in new JS Project Manager.

- motivated by #14719 as a most generic way to mitigate similar problems
   - that crash has been avoided by #14774 meanwhile
- still, other (yet unknown) crashes would benefit from such an automatic restart

See also https://discord.com/channels/401396655599124480/1472809872696410122

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #14769 

Refactored also ensoRunner, so the single project logic is in a separate class.

Tested by `pkill -9 -f bin/enso`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/project-manager-shim/src/projectService/ensoRunner.ts [hunk 1]
```diff
@@ -5,10 +5,13 @@ import { createWriteStream } from 'node:fs'
 import * as os from 'node:os'
 import * as path from 'node:path'
 import { pipeline } from 'node:stream/promises'
+import { clearInterval } from 'node:timers'
 import * as portfinder from 'portfinder'
 import { extract } from 'tar'
 import { Path } from './types.js'
 
+const HEALTHCHECK_FAILURES_TO_RESTART = 3
```
Comment (JaroslavTulach) [inline app/project-manager-shim/src/projectService/ensoRunner.ts:12]: - the problem of #14774 doesn't really need _health check_
- the `enso` process just crashed
- such a situation can be detected differently than by a _health check_
- so I am surprised to see a solution based on _health check_

File: app/project-manager-shim/src/projectService/ensoRunner.ts [hunk 2]
```diff
@@ -62,23 +65,187 @@ export interface Socket {
...
+    }
+
+    this.process.on('exit', () => {
+      if (this.closed) return
+      console.error(
+        'Language Server process for project',
+        this.path,
+        ' exited unexpectedly, restarting',
+      )
+      restart(true)
```
Comment (JaroslavTulach) [inline app/project-manager-shim/src/projectService/ensoRunner.ts:176]: `this.process.on('exit', () => { restart(true); }` would be enough to address #14774

Comment (farmaazon) [reply app/project-manager-shim/src/projectService/ensoRunner.ts:176]: Yes, the process restarts immediately.

The healthcheck is for situations where LS process freezes, but is still officially running.

**Review by JaroslavTulach — APPROVED** [review]
> Tested by pkill -9 -f bin/enso

- I guess that is the scenario mimicking #14774 
- Can we make sure such an incident **appears in logs** sent to @PabloBuchu?
   - I mentioned I usually not pay attention to Sentry logs 
   - if `enso` crash was reported there (or elsewhere), I would certainly be more interested!
- Overall I see this as an important step towards robustness of the system

**Comment by farmaazon** [comment]
> * Can we make sure such an incident **appears in logs** sent to @PabloBuchu?
>   
>   * I mentioned I usually not pay attention to Sentry logs
>   * if `enso` crash was reported there (or elsewhere), I would certainly be more interested!

Tracked by https://github.com/enso-org/enso/issues/14862 It's not trivial, as we need to rearrange our configuration readers.

**Review by jdunkerley — APPROVED** [review]

File: app/project-manager-shim/src/projectService/ensoRunner.ts [hunk 3]
```diff
@@ -62,23 +65,187 @@ export interface Socket {
...
+      }
+    }
+  }
+
+  private loadingRoutine(): Promise<void> {
+    return new Promise((resolve, reject) => {
+      let resolved = false
+      const startHealthCheck = () => {
+        const pollInterval = setInterval(async () => {
+          const isReady = await this.checkServerHealth()
```
Comment (kazcw) [inline app/project-manager-shim/src/projectService/ensoRunner.ts]: `setInterval` doesn't handle long-running tasks well. If the HTTP request performed by `checkServerHealth` here takes more than 250ms, a new execution can be started before the previous is finished.

File: app/project-manager-shim/src/projectService/ensoRunner.ts [hunk 4]
```diff
@@ -62,23 +65,187 @@ export interface Socket {
...
+      console.error(
+        'Language Server process for project',
+        this.path,
+        ' exited unexpectedly, restarting',
+      )
+      restart(true)
+    })
+
+    let failures = 0
+    this.watchdogInterval = setInterval(async () => {
```
Comment (kazcw) [inline app/project-manager-shim/src/projectService/ensoRunner.ts]: Here also we could end up with a whole pack of watchdogs running if the server is responding slowly
