### PR TITLE
Avoid exposing `Runtime.current_execution_environment`

### LINKED ISSUE #12340: Remove `Runtime.current_execution_environment` & co.
Trying to replace the current `EnsoContext.getExecutionEnvironment` with a solution based on `State` as described at  [#12294](https://github.com/enso-org/enso/issues/12294#issuecomment-2672282354) reveals some issues.

According to the [specification](https://github.com/enso-org/design/blob/main/epics/basic-libraries/write-action-control/design.md) @jdunkerley wants to achieve:
- Mostly inside Enso we use if_enabled to control when we run code
- We use with_enabled to allow us to turn on for blocks of code.
- There is a play button at a node and workflow level in the GUI allowing temporary enabling via the language server - #11173

### current_execution_environment

I guess I have to start questioning the basics. Why do we have `Runtime.current_execution_environment`? When I look at the usages, I don't see **any reason** why such a method should exist:

Usages of current_execution_environment

- if I managed to remove this method
- then `environment` argument would have to go away as well

### environment argument

I am questioning the `environment` argument of the `Context.is_enabled` method
- we don't use it anywhere
- what does it suppose to mean?

is_enabled
if_enabled

If `Runtime.current_execution_environment` can be removed, then we can remove also `environment` argument.

### Environment vs. Contexts

My view of the system:
- various `Runtime.Context` instances (`Input`, `Output`, etc.) are the key concept
- environment is just a _"human friendly name"_ for a set of `Runtime.Context` instances
- environment is used from CLI (as an argument)
- environment is used from GUI (as a button)
- but:
- before passed to engine it is converted to _set of `RuntimeContext` instances_
- engine, libs code only works with `Context.Xyz.is_enabled` & co. methods
- never need to know anything about the _"human friendly names"_ of sets of `Runtime.Context`  instances

The implementation of #1173 is currently changing (the name of) the current environment. Now I believe that is not correct...

> Guessing Dmitry did that to enable running a single node with Write enabled (a very nice feature)

... rather than changing the environment (e.g. _human friendly name of set of `Runtime.Context` enabled instances_) the language server should turn on `Runtime.Context.Output` - e.g. temporarily calls `Context.Output.with_enabled` before evaluating the given node.

I believe it would look the same from user perspective and would be less braided internally than what we have right now.

### LINKED ISSUE #14570: Interop method invocation should respect default parameters
Invoking method via [Value.invokeMember](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Value.html#invokeMember(java.lang.String,java.lang.Object...)) without explicitly provided argument for default parameter results in `ArrayIndexOutOfBoundsException` (See this [failure](https://github.com/enso-org/enso/actions/runs/20715998535/job/59469207229#step:14:4493)).

It should not, the interop method invocation should apply defaults for non provided arguments.

Created from https://github.com/enso-org/enso/pull/14554#discussion_r2662274344

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #12340 by removing the `current_execution_environment` method ...
- ...and by putting `ExecutionEnvironment` status into `State`
- `EnsoContext.getGlobalExecutionEnvironment` is (almost) a **constant**
   - it is a constant in the CLI
   - it can be changed via `SetExecutionEnvironmentCommand` in the GUI
- the **runtime execution environment** is then encoded in `State`
- and manipulated directly via `GetStateNode` and `PutStateNode`  

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been updated.
- [x] Engine benchmarks are fine [run 1](https://github.com/enso-org/enso/actions/runs/25070622916)
- [x] Standard libraries benchmarks are fine [run 1](https://github.com/enso-org/enso/actions/runs/25070633151)
- [x] [nightly release](https://github.com/enso-org/enso/actions/runs/25096549677) seems fine

### CODE REVIEW

**Review by AdRiley — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java [hunk 1]
```diff
@@ -67,11 +67,12 @@ private void setExecutionEnvironment(
...
                                               () -> {
+                                                var env =
+                                                    ExecutionEnvironment.forName(
+                                                        executionEnvironment.name());
                                                 ctx.executionService()
                                                     .getContext()
-                                                    .setExecutionEnvironment(
-                                                        ExecutionEnvironment.forName(
-                                                            executionEnvironment.name()));
+                                                    .setGlobalExecutionEnvironment(env);
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java:75]: - _"global execution environment"_ is (almost) a **constant**
- it is a constant in CLI
- it can be changed in the GUI, but only by this `SetExecutionEnvironmentCommand` command
- all other changes are to _execution environment_ are **local** - e.g. made in `State` only

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java [hunk 2]
```diff
@@ -478,21 +494,6 @@ public CompletionStage<Object> typeOfValue(Object value) {
     return submitExecution(() -> TypeOfNode.getUncached().findTypeOrError(value));
   }
 
-  /**
-   * Sets global execution environment.
-   *
-   * @param env the execution envrionment to use
-   * @return old execution environment
-   */
-  public CompletionStage<ExecutionEnvironment> setExecutionInstrument(ExecutionEnvironment env) {
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:487]: - this was a fragile concept
- replaced by `envOrNull` in `execute` methods

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+@BuiltinMethod(
+    type = "Runtime",
+    name = "with_context_builtin",
+    description = "Enabled/disables a context in the specified scope.",
+    inlineable = true)
+final class RuntimeWithContextNode extends Node {
+  private @Child GetStateNode getNode = GetStateNode.create();
+  private @Child PutStateNode putNode = PutStateNode.create();
+  private @Child WithContextNode withNode = WithContextNode.create();
+  private @Child ThunkExecutorNode thunkExecutorNode = ThunkExecutorNode.build();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java:25]: - using _real nodes_ - e.g. not `getUncached()` 
- should make this really fast
- if there is a benchmark doing `Runtime.Output.with_context` then it will get faster

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithDisabledContextNode.java
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithDisabledContextNode.java:1]: Having two files that are its own copy felt a bit weird. Now there is the `RuntimeWithContextNode` with `enable` argument.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 4]
```diff
@@ -846,55 +844,8 @@ public ExecutionEnvironment getGlobalExecutionEnvironment() {
...
-
-  /**
-   * Enable execution context in the execution environment.
-   *
-   * @param context the execution context
-   * @param environmentName the execution environment name
-   * @return the execution environment version before modification
-   */
-  public ExecutionEnvironment enableExecutionEnvironment(Atom context, String environmentName) {
-    ExecutionEnvironment original = globalExecutionEnvironment;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:874]: - All this _local execution environment state_ handling just shouldn't be here in the `EnsoContext`
- only _global execution environment_ belongs to the `EnsoContext`

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    var ctx = EnsoContext.get(this);
+    var origEnv =
+        getNode.forClass(ExecutionEnvironment.class, EnsoContext::getGlobalExecutionEnvironment);
+    var newEnv = withNode.executeEnvironmentUpdate(origEnv, context, enable);
+    try {
+      putNode.executePut(ExecutionEnvironment.class, newEnv, true);
+      var state = ctx.currentState();
+      return thunkExecutorNode.executeThunk(frame, action, state, BaseNode.TailStatus.NOT_TAIL);
+    } finally {
+      PutStateNode.getUncached().executePut(ExecutionEnvironment.class, origEnv, false);
```
Comment (4e6) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java]: Using uncached here bypasses cached child `putNode` for no obvious reason. If intentional, worth a comment. Otherwise we can reuse `putNode`.

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java (hunk 2 above)
Comment (4e6) [reply engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:487]: If any node still reads `getGlobalExecutionEnvironment()` directly (rather than via `GetStateNode.forClass(...)` with the global as fallback), it won't observe per-node overrides set by `IdExecutionInstrument.setExecutionEnvironment`. Worth grep-confirming `getGlobalExecutionEnvironment` is only used as the fallback in forClass.

**Review by 4e6 — APPROVED** [review]
Sound approach

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:487]: The current state is OK, I think:

Image

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithContextNode.java]: Good catch. With e9ea0e8140 the code should be even faster.

**Comment by JaroslavTulach** [comment]
There seems to be a [Enso runtime crash](https://github.com/enso-org/enso/actions/runs/25069982175/job/73455926383?pr=14989#step:14:1913) in the CI:
```
at <java> org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:603)
at <java> org.graalvm.truffle/com.oracle.truffle.api.library.LibraryExport.assertAdopted(LibraryExport.java:133)
at <java> org.graalvm.truffle/com.oracle.truffle.api.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports.access$500(DynamicObjectLibraryImplGen.java:46)
at <java> org.graalvm.truffle/com.oracle.truffle.api.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports$Cached.containsKey(DynamicObjectLibraryImplGen.java:385)
at <java> org.graalvm.truffle/com.oracle.truffle.api.object.DynamicObjectLibraryGen$CachedDispatch.containsKey(DynamicObjectLibraryGen.java:1926)
at <java> org.enso.runtime/org.enso.interpreter.runtime.state.GetStateNodeGen.executeAndSpecialize(GetStateNodeGen.java:114)
at <java> org.enso.runtime/org.enso.interpreter.runtime.state.GetStateNodeGen.executeGet(GetStateNodeGen.java:95)
at <java> org.enso.runtime/org.enso.interpreter.runtime.state.GetStateNode.execute(GetStateNode.java:43)
at <java> org.enso.runtime/org.enso.interpreter.runtime.state.GetStateNode.forClass(GetStateNode.java:68)
at <java> org.enso.runtime/org.enso.interpreter.runtime.error.DataflowError.withDefaultTrace(DataflowError.java:69)
at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.error.ThrowErrorNode.execute(ThrowErrorNode.java:20)
at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.error.ThrowErrorMethodGen.handleExecute(ThrowErrorMethodGen.java:93)
at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.error.ThrowErrorMethodGen$1Inlineable.call(ThrowErrorMethodGen.java:74)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNode.callInlineable(ExecuteCallNode.java:64)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:135)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:98)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:56)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:176)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:109)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:116)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:132)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:94)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNode.invokeFunction(InvokeCallableNode.java:185)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNodeGen.executeAndSpecialize(InvokeCallableNodeGen.java:238)
at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNodeGen.execute(InvokeCallableNodeGen.java:226)
at <java> org.enso.runtime/org.enso.interpreter.runtime.data.Type$InvokeMember.doCached(Type.java:437)
at <java> org.enso.runtime/org.enso.interpreter.runtime.data.Type$InvokeMember.doUncached(Type.java:449)
at <java> org.enso.runtime/org.enso.interpreter.runtime.data.TypeGen$InteropLibraryExports$Cached.invokeMember(TypeGen.java:197)
at <java> org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3596)
at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4823)
at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9109)
at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNode.doDefault(PolyglotValueDispatch.java:4863)
at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9316)
at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
at <java> org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:1159)
at <java> org.enso.base.polyglot.EnsoMeta.asDataflowError(EnsoMeta.java:99)
at <java> org.enso.database.JDBCBatchInsert.wrapException(JDBCBatchInsert.java:203)
at <java> org.enso.database.JDBCBatchInsert.batchInsert(JDBCBatchInsert.java:51)
at <enso> JDBC_Connection.batch_insert.JDBC_Connection.batch_insert(JDBC_Connection.enso:171:13-248)
at <enso> Managed_Resource.with_builtin(Internal)
at <enso> Panic.catch(Internal)
```
- another [similar failure](https://github.com/enso-org/enso/actions/runs/25069982175/job/73454068831?pr=14989#step:14:1184) can be reproduced by
```
enso$ ./enso --run test/Base_Tests/src/Network/Http_Spec.enso
```
- attempt to [workaround the problem](https://github.com/enso-org/enso/pull/14989#discussion_r3158822286)
- but is is better to [properly fix it](https://github.com/enso-org/enso/pull/14989#discussion_r3159283780)!

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java [hunk 6]
```diff
@@ -17,6 +17,11 @@ public class ThrowErrorNode extends Node {
   private @Child HasContextEnabledNode hasContextEnabledNode = HasContextEnabledNode.create();
 
   public Object execute(VirtualFrame giveMeAStackFrame, Object payload) {
-    return DataflowError.withDefaultTrace(payload, this, stateNode, hasContextEnabledNode);
+    if (getRootNode() == null) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java]: - the node should always be adopted (e.g. have root node)
- the fact that it is not signals some deeper problems elsewhere
   - which apparently [happens](https://github.com/enso-org/enso/pull/14989#issuecomment-4340961660) at some situations
- e.g. this check is more a workaround than a fix
- thus....

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java [hunk 7]
```diff
@@ -426,15 +426,16 @@ static Object doCached(
         Object[] args,
         @Cached("member") String cachedMember,
         @Cached("findMethod(receiver, cachedMember)") Function func,
-        @Cached("buildInvokeCallableNode(func)") InvokeCallableNode invokeCallableNode) {
+        @Cached InteropApplicationNode invokeNode) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java:429]: - usage of `InteropApplicationNode` in b7a2efd59492470a01eea142e8db252ca76ff07b fixes #14570!
- tested in 2fd9cddc1d

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java]: - fixed properly in https://github.com/enso-org/enso/pull/14989#discussion_r3159283780

**Comment by JaroslavTulach** [comment]
- another [missing root node](https://github.com/enso-org/enso/actions/runs/25095506224/job/73533054781?pr=14989#step:14:2439) error, this time via `Atom` interop:
```
 ️ java.lang.AssertionError: no root node for GetStateNodeGen.Uncached@3958ff36
 ️ with section: null
 ️ with root nodes: null
 ️ 
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.reportSlowContextAccess(EnsoContext.java:314)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.get(EnsoContext.java:289)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.state.GetStateNode.forClass(GetStateNode.java:66)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.DataflowError.withDefaultTrace(DataflowError.java:69)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.DataflowError.withDefaultTrace(DataflowError.java:85)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.expression.builtin.resource.WithNode.execute(WithNode.java:44)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.expression.builtin.resource.WithMethodGen.execute(WithMethodGen.java:79)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:610)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:94)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:83)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode$RepeatedCallNode.executeRepeating(LoopingCallOptimiserNode.java:285)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:133)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.dispatch(LoopingCallOptimiserNode.java:97)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.cachedDispatch(LoopingCallOptimiserNode.java:70)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeDispatch(LoopingCallOptimiserNodeGen.java:83)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:70)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:176)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:109)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:116)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:76)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.InstanceInvokeMethodNode.doFunctionalDispatchCachedSymbol(InstanceInvokeMethodNode.java:123)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.InstanceInvokeMethodNodeGen.execute(InstanceInvokeMethodNodeGen.java:209)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.InteropMethodCallNode.callCached(InteropMethodCallNode.java:109)
 ️ 	at org.enso.runtime/org.enso.interpreter.node.callable.InteropMethodCallNodeGen.execute(InteropMethodCallNodeGen.java:73)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.callable.UnresolvedSymbol$Execute.doDispatch(UnresolvedSymbol.java:180)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.callable.UnresolvedSymbolGen$InteropLibraryExports$Cached.execute(UnresolvedSymbolGen.java:95)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.execute(InteropLibrary.java:3126)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.data.atom.Atom$InvokeMember.doCached(Atom.java:356)
 ️ 	at org.enso.runtime/org.enso.interpreter.runtime.data.atom.AtomGen$InteropLibraryExports$Cached.invokeMember(AtomGen.java:130)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3588)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4823)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9109)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.doDefault(PolyglotValueDispatch.java:4888)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9372)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:830)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:754)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:662)
 ️ 	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedRuntimeSupport.callProfiled(OptimizedRuntimeSupport.java:308)
 ️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2687)
 ️ 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:1157)
 ️ 	at org.enso.base.cache.ReloadDetector$ReloadSentinel.hasReloadOccurred(ReloadDetector.java:85)
 ️ 	at org.enso.base.cache.ReloadDetector.clearOnReload(ReloadDetector.java:33)
 ️ 	at org.enso.base.cache.LRUCache.getResult(LRUCache.java:93)
```
- probably similar fix to https://github.com/enso-org/enso/pull/14989#discussion_r3159283780
- but this time in `Atom$InvokeMember` - done in dcbef1d596

**Comment by JaroslavTulach** [comment]
From my point of view the [nightly release](https://github.com/enso-org/enso/actions/runs/25096549677) seems fine. I tried:

[OutputWrite.webm](https://github.com/user-attachments/assets/717eb023-46e2-4a22-a9dc-d24960269ce6)

And the output is by default off, but can be turned on with the Write button. Whatever I tried seemed to behave the same in `enso-linux-x86_64-2026.1.1-rc1`, I guess we can integrate.
