### PR TITLE
Attaching a warning to error is no op

### LINKED ISSUE #10736: Explicit return type with error causes type error when an error is thrown
(This bug refers to #10725)

This change to `Decimal.add` results in the error shown below, in the case of a thrown error:

```
-    add self (that : Decimal) (math_context : Math_Context | Nothing = Nothing) =
+    add self (that : Decimal) (math_context : Math_Context | Nothing = Nothing) -> Decimal ! Arithmetic_Error | Illegal_Argument =
```

Error:

```
    - [FAILED] should not allow mixed arithmetic (float) [68ms]
        Reason: An unexpected panic was thrown: Type error: expected the result of `add` to be Decimal, but got <ERR>.
        at <enso> Decimal.add(/Users/gmt/dev/enso/enso/built-distribution/enso-engine-0.0.0-dev-macos-aarch64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso:478-482)
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #10736 by avoiding attaching of warnings to `DataflowError`s.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
Looks like we have a failure when [executing test/Base_Tests](https://github.com/enso-org/enso/actions/runs/10270645209/job/28418831970?pr=10765#step:7:1675):
```
java.lang.AssertionError: Cannot attach warnings to Error Error:Already_Exists (Value (File C:\runner\_work\enso\enso\test\Base_Tests\data\transient\work.txt))
```
apparently we are trying to attach a warning to an error. Fixed in 843c893 - all paths that construct `WithWarnings` need to check for `DataflowError` now.

**Review by Akirathan — COMMENTED** [review]
Please wait until https://github.com/enso-org/enso/pull/10555 is merged. I am afraid you will have to re-implement it from scratch then. You will have to change the implementation of `AppendWarningNode`.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java [hunk 1]
```diff
@@ -156,4 +157,26 @@ private void assertWarningsForAType(Value v) {
...
+    err_warn -> Integer ! Illegal_Argument =
+        v = Warning.attach (Out_Of_Range.Error "qewr") 12
+        case v of
+            _ : Integer -> Error.throw (Illegal_Argument.Error "asdf")
+    """;
+
+    var module = ctx.eval(LanguageInfo.ID, code);
+    var errorWithWarning = module.invokeMember(MethodNames.Module.EVAL_EXPRESSION, "err_warn");
+    assertFalse("Something is returned", errorWithWarning.isNull());
+    assertTrue("But is represents an exception object", errorWithWarning.isException());
```
Comment (GregoryTravis) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java]:
```suggestion
    assertTrue("But it represents an exception object", errorWithWarning.isException());
```

**Review by GregoryTravis — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> ... you will have to re-implement it from scratch then. 

Re-implemented from scratch in 0e03d15

**Review by Akirathan — APPROVED** [review]
