### PR TITLE
Editing the node is not changing the placeholders and widgets

### LINKED ISSUE #7462: Editing the node is not changing the placeholders and widgets
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When user edit the node to non-existing function the widgets and placeholders are kept from the previous function.

### Expected behaviour

Node structure and view should be updated.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

Zrzut ekranu 2023-08-2 o 09 38 53

https://github.com/enso-org/enso/assets/12892578/c685e7b8-b197-42f8-ac4a-abf74e1f65bc

https://github.com/enso-org/enso/assets/12892578/6d979d92-e078-4ea5-b6cc-27899cc3594d

### Logs

_No response_

### Enso Version

nightly 1.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7462 

### Important Notes

https://github.com/enso-org/enso/assets/357683/c2e68042-f64c-419e-b36e-7e99f0b43cd8

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 1]
```diff
@@ -250,6 +250,7 @@ public void onReturnExceptional(VirtualFrame frame, Throwable exception) {
       }
     }
 
+    @CompilerDirectives.TruffleBoundary
```
Comment (hubertp) [inline engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java]: Shouldn't this be on `setExecuted` instead?

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala [hunk 2]
```diff
@@ -569,7 +569,9 @@ object ProgramExecutionSupport {
     */
   private def toMethodCall(value: ExpressionValue): Option[Api.MethodCall] =
     for {
-      call          <- Option(value.getCallInfo).orElse(Option(value.getCachedCallInfo))
+      call <-
+        if (Types.isPanic(value.getType)) Option(value.getCallInfo)
+        else Option(value.getCallInfo).orElse(Option(value.getCachedCallInfo))
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala:574]: I know that this logic has been here already but it kind of looks weird that first we ask for call info and if missing we are asking for the cached value. I would expect the opposite to happen.

**Review by hubertp — COMMENTED** [review]
nits

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java (hunk 1 above)
Comment (4e6) [reply engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java]: Right

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala (hunk 2 above)
Comment (4e6) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala:574]: This logic covers the case when the user comes back from the function (pops the execution frame). In this case, the expression does not have the call info because the result was cached and no function was called, but contains a cached call info.
I agree that it's weird but it always breaks some other cases when I try to come up with a workaround.

**Review by hubertp — APPROVED** [review]
