### PR TITLE
Fix fast typing leading to wrong component browser selection.

### LINKED ISSUE #6908: Typing `set` in CB and accepting it quickly is putting `at` or `select_columns` in the node
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/dd05cf45-f581-40e9-a85a-fad830676309

### Expected behaviour

node should contain method that was typed

### How we can reproduce it?

1. open CB connected to a table (occurs more repeatably on bigger workflows like Colorado COVID example)
2. type `set` and press `enter` quickly

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 31.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Fixes #6908

Fast typing leads to a race condition where the end of the node editing can happen where the state of the CB is not caught up yet. This leads to two issues:

1. The wrong selection is made, as the View of the Component Browser has not been updated yet, but the selection from there is used to determine how the node is created.
2. Processing of the keys is aborted early, while still waiting for additional key input. 

This is now fixed.

https://github.com/enso-org/enso/assets/1428930/dce82bb3-1c25-4a67-988a-d74469dc8fcd

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/src/project.rs [hunk 1]
```diff
@@ -47,7 +47,12 @@ pub mod project_view_top_bar;
 /// A time which must pass since last change of expression of node which is the searcher input
 /// to send `searcher_input_changed` event. The delay ensures we don't needlessly update Component
 /// Browser when user is quickly typing in the expression input.
-const INPUT_CHANGE_DELAY_MS: i32 = 200;
+///
+/// Note: This value is set to zero, which means that the event is processed as fast as possible,
+/// but still at the earliest in the next frame. This means that there is a minimal delay but
+/// other events can be processed in the meantime. This is important since the event can lead to
+/// a lot of processing in the Component Browser and we don't want to block the UI.
+const INPUT_CHANGE_DELAY_MS: i32 = 0;
```
Comment (kazcw) [inline app/gui/view/src/project.rs]: I have two questions:
1. How does this timing change fit into the solution? The change in `searcher.rs` fixes the race condition, right?
2. Does this negatively impact performance in some circumstances? The case I'm concerned about is: When the user is typing faster than we can process the changes, do we accumulate work that has to be done (processing states that have already passed) before we can catch up to the current state?

Comment (farmaazon) [reply app/gui/view/src/project.rs]: I would keep the input delay if possible, precisely for the case described by Kaz (in point 2):

> Does this negatively impact performance in some circumstances? The case I'm concerned about is: When the user is typing faster than we can process the changes, do we accumulate work that has to be done (processing states that have already passed) before we can catch up to the current state?

This is exactly what happened, and that's why the delay was introduced in the first place. We can consider lowering it, but still I'd catch several quick key presses for one update.

**Review by farmaazon — CHANGES_REQUESTED** [review]

**Comment by farmaazon** [comment]
@MichaelMauderer More precisely, the code which should handle the situation from point 2 of your description is:
```rust
            input_change <- searcher_input_change_opt.unwrap();
            input_change_delay.restart <+ input_change.constant(INPUT_CHANGE_DELAY_MS);
            update_input_on_commit <- frp.output.editing_committed.constant(());
            input_change_delay.cancel <+ update_input_on_commit;
            update_input <- any(&input_change_delay.on_expired, &update_input_on_commit);
```
(`init_searcher_input_changes_frp` method)
This part is set up before closing searcher, so the input shall be updated before emitting signals about accepting expression.

File: app/gui/view/src/project.rs (hunk 1 above)
Comment (MichaelMauderer) [reply app/gui/view/src/project.rs]: > How does this timing change fit into the solution? The change in searcher.rs fixes the race condition, right?

Only the combination of changes fixes the race condition, as we (a) need to be sure the CB is correctly refreshed and (b) we have processed all the keys before dropping the CB. 

> Does this negatively impact performance in some circumstances? The case I'm concerned about is: When the user is typing faster than we can process the changes, do we accumulate work that has to be done (processing states that have already passed) before we can catch up to the current state?

No, this does not accumulate work. The nice thing here is, that if the processing of the list takes longer, even this one-frame delay makes sure, that all key presses that occur during heavy load are then processed in the following frame together. So, all key presses during heavy load are collected together in the following frame and processed as one edit event in the frame following that. 

I have not observed any performance regressions during my testing, but we would definitely reconfirm during QA.

Comment (wdanilo) [reply app/gui/view/src/project.rs]: I don't think this is the only solution for the problem. Instead, when user is typing letters, they are put in a "queue" and component browser refreshes only knowing this queue is empty, or anything like that. 

Anyway, there is a very important info missing here - as stated above, how does it affect performance on a weak hardware? The delay was introduced to improve performance if I remember correctly. Of course, I'd prefer not to have this delay if we can be fast enough, and maybe we are now - but this needs to be checked and confirmed.

Comment (MichaelMauderer) [reply app/gui/view/src/project.rs]: There is now a solution that better addresses the underlying issue. It appears that changing the `INPUT_CHANGE_DELAY_MS` to zero only coincidentally fixed the issue. The new solution does away with that change and leaves the value untouched.

**Comment by MichaelMauderer** [comment]
@farmaazon The order of events should now be correct, and any refreshes are executed before an item is selected and confirmed.

File: app/gui/view/src/project.rs [hunk 2]
```diff
@@ -523,20 +517,79 @@ impl View {
...
+            // Since the input was updated, the selected item might have been replaced, so we need
+            // discard it and instead use the currently selected item. Note that this will be the
+            // default item, and we loose any selection that was made. But that is fine, as the
+            // user was typing and a change to the selection was to be expected.
+            frp.source.editing_committed <+ on_update_with_refresh.map3(
+                &committed_in_searcher,&grid.active,
+                |_, (node_id, _), &entry| Some((*node_id, entry?.as_entry_id()))).unwrap();
+
+            // If we have no outstanding key presses, we can accept the selection as is.
+            frp.source.editing_committed <+ committed_in_searcher.sample(&update_without_refresh);
```
Comment (farmaazon) [inline app/gui/view/src/project.rs:584]: This could belong to the next subsection (as committing edit closed the searcher).

If, if such separation is more readable to you, let's rename this section to "handling input and committing edit".

**Review by farmaazon — APPROVED** [review]
I rue for the merging of two "init" function, but I understand why it was necessary.

**Comment by xvcgreg** [comment]
@MichaelMauderer what's the holdup here?

**Comment by MichaelMauderer** [comment]
> @MichaelMauderer what's the holdup here?

It was just waiting on me to make the doc change as requested, and ask for QA (which has both been done).

Now awaiting QA.

**Review by wdanilo — APPROVED** [review]

**Comment by vitvakatu** [comment]
QA passed 🍏
