### PR TITLE
Fix adding nodes in collapsed functions

### LINKED ISSUE #9963: Adding new node to collapsed function breaks semantics
If we have the following function:
```
func1 =
    text = "1"
    number = text.length
    number
```

Adding a new node inside this collapsed function produces:

```
func1 =
    text = "1"
    number = text.length
    number
    number2 =  123
```

Which is incorrect and changes the return type.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Insert new nodes before the block's terminal expression-statement, if present.

Fixes #9963.

### Important Notes

- Fix a bug that caused any empty lines at the beginning of a module not to be printed.
- Remove a redundant data-property from `GraphNode`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/GraphNodes.vue [hunk 1]
```diff
@@ -48,7 +48,6 @@ const uploadingFiles = computed<[FileName, File][]>(() => {
     :node="node"
     :edited="id === graphStore.editedNodeInfo?.id"
     :graphNodeSelections="props.graphNodeSelections"
-    :data-node="id"
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphNodes.vue:51]: It is very helpful in debugging. We could use `:data-testid="node(${id})"` if you want to have something standardized.

File: app/gui2/src/composables/__tests__/nodeCreation.test.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+await initializeFFI()
+
+test.each([
+  ['node1 = 123', '*'],
+  ['node1 = 123', '*', 'node1'],
+  ['node1 = 123', '', '*', 'node1'],
+  ['*', 'node1'],
+  ['', '*', 'node1'],
+  ['*', '## Return value', 'node1'],
+  ['*', '## Return value', '', 'node1'],
```
Comment (farmaazon) [inline app/gui2/src/composables/__tests__/nodeCreation.test.ts:16]: Add a case of adding a node to an empty block.

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/components/GraphEditor/GraphNodes.vue (hunk 1 above)
Comment (kazcw) [reply app/gui2/src/components/GraphEditor/GraphNodes.vue:51]: This is a duplicate; the `GraphNode` component defines `data-node-id` with the same value.
