### PR TITLE
Fix list editor panics during insertion

### LINKED ISSUE #6522: Stabilize list editor
After initial implementation, List editor tends to behave erratically. Dropped elements sometimes aren't registered as part of node's expression, and in rare occasions drag or drop also causes a panic. Nested list editors are also completely not supported.

```[tasklist]
### Tasks
- [x] Make sure all drags and drops are registered and handled properly, fix panics.
- [ ] Add support for lists in lists.
- [x] Remove feature flag, permanently enabling the list editor.
```

### LINKED ISSUE #6549: Vector Add Pointer appears when selecting a project from the open project list
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

image

When selecting a project from the Open List if a Vector is behind you get a + pointer.

### Expected behaviour

Normal pointer.

### How we can reproduce it?

Put a vector under where the open file list appears

### Screenshots or screencasts

_No response_

### Enso Version

Current Develop as of 4th May

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Microsoft Windows [Version 10.0.22624.1680] Version 22H22

### Hardware you are using

AMD 6800HS 32GB RTX3050

### LINKED ISSUE #6640: The `Table.parse` method is not displayed correctly in IDE
### Discord username

_No response_

### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Given the expression
```py
operator8.parse 'Sales Timestamp' Value_Type.Date_Time 'dd/MM/yyyy HH:mm:ss'
```

IDE does not display first argument `'Sales Timestamp'`

### Expected behaviour

IDE displays the first argument of `Table.parse` method.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/357683/b0dde3a2-0dd4-4243-9bf5-40564fd39861

### Enso Version

3dd05c235953954e4f16a6ba9ff638b52d3d98a9

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.63

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #6657: Widgets fail to parse in the IDE if their label or code contains a double quote "
Repro:
- modify some custom widget to contain a `"`
- open the IDE with the widget displayed

I modified `Text_Sub_Range.default_widget` (currently on my PR #6641, should be merged soon, it can also be tested on any other widget):
```diff
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso	(revision 607a45525f30fdece328a8a58a308f345bc02b7c)
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso	(date 1683889513913)
@@ -58,7 +58,7 @@
     ## PRIVATE
     default_options : Vector Option
     default_options =
-        o1 = Option "Before" "(Text_Sub_Range.Before ' ')"
+        o1 = Option 'has a " quote' "(Text_Sub_Range.Before ' ')"
         o2 = Option "Before_Last" "(Text_Sub_Range.Before_Last ' ')"
         o3 = Option "After" "(Text_Sub_Range.After ' ')"
         o4 = Option "After_Last" "(Text_Sub_Range.After_Last ' ')"
```

Then I open a project that has a `Text.take` node in it:
image

I can see the issue in the logs:
image

And when I open the widget, I can see it fell back to default instead of my custom one, due to this issue:
image

### PR DESCRIPTION
**Pull request by Frizi**
Fixes #6522 

- Fixed occasional panics when inserting or moving elements around.
- Improved mouse events handling in list editor to behave correctly during box selection.
- Removed vectorEditor feature flag, enabling the list editor permanently.
- Replaced node background shape with `Rectangle` and removed unnecessary separation between hover area and background. Switched node hover state to use new mouse events system.
- Adjusted size of hover area of the list editor such that it is harder do accidentally insert a new element and easier to drag the nodes around.
- Fixed mouse down event propagation inside list editor when clicking without dragging. This allows dropdowns nested within list items to work correctly.
image
image
image

### Important Notes

The mouse handling changes involve an unfortunate huge hack, where we enable mouse events on the mouse shape during box selection. That way we know for sure that no other shape will be able to receive mouse enter event. Then the list editor widget is modified to only actually respond to events when its background is hovered. We will definitely want a more proper way to handle mouse event contention, but it's definitely out of scope for current bugfixing.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node.rs [hunk 1]
```diff
@@ -728,17 +689,28 @@ impl Node {
...
 
 
             // === Background Press ===
 
-            out.background_press <+ model.drag_area.events_deprecated.mouse_down_primary;
-            out.background_press <+ model.input.on_background_press;
+            let background_press = model.background.on_event::<mouse::Down>();
+            let input_press = model.input.on_event::<mouse::Down>();
+            input_as_background_press <- input_press.gate(&input.set_edit_ready_mode);
+            trace input_as_background_press;
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/component/node.rs]: trace - also check other places before merge, as its hard to catch all of them during review

File: lib/rust/ensogl/component/list-editor/src/lib.rs [hunk 2]
```diff
@@ -527,7 +531,7 @@ impl<T: display::Object + CloneRef + Debug> ListEditor<T> {
                 &frp.enable_last_insertion_point,
                 f!([model] (gap, gaps, pos, size, is_dragging, enable_all, enable_last) {
                     let is_close_x = pos.x > -gap && pos.x < size.x + gap;
-                    let is_close_y = pos.y > -gap && pos.y < size.y + gap;
+                    let is_close_y = pos.y > 0.0 && pos.y < size.y;
```
Comment (wdanilo) [inline lib/rust/ensogl/component/list-editor/src/lib.rs:513]: why this change? The gap was there to display `+` button when the mouse is cldse to the edge of lit editor. Without this change it will not be visible, right?

File: lib/rust/ensogl/component/list-editor/src/lib.rs [hunk 3]
```diff
@@ -1077,8 +1082,9 @@ impl<T: display::Object + CloneRef + 'static> Model<T> {
                 warn!("An element was inserted without a placeholder. This should not happen.");
                 index
             };
+            let index = self.item_or_placeholder_index_to_index(actual_index);
             self.reposition_items();
-            self.item_or_placeholder_index_to_index(actual_index)
+            index
```
Comment (wdanilo) [inline lib/rust/ensogl/component/list-editor/src/lib.rs:1091]: Does this change does any logic change or it was just syntactic one?

File: lib/rust/ensogl/core/src/display/object/instance.rs [hunk 4]
```diff
@@ -3012,6 +3012,14 @@ pub trait LayoutOps: Object {
         self.display_object().layout.margin.set(Vector2(margin, margin));
     }
 
+    /// Set vertical and horizontal margins of the object. Margin is the free space around the
+    /// object.
+    fn set_margin_vh(&self, vertical: impl Into<Unit>, horizontal: impl Into<Unit>) -> &Self {
+        let margin = Vector2(horizontal.into().into(), vertical.into().into());
+        self.display_object().layout.margin.set(margin);
+        self
+    }
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/object/instance.rs:3065]: why this function is needed? This object implements `display::Object` so you can directly do `.margin.set`? 
EDIT: oh, it sets it not on root but on layout - hmm, why? There should be a proper explanation what it does and why it exists if the whole object is a display object.

**Review by wdanilo — APPROVED** [review]

File: lib/rust/ensogl/component/list-editor/src/lib.rs (hunk 2 above)
Comment (Frizi) [reply lib/rust/ensogl/component/list-editor/src/lib.rs:513]: It is visible, the area is just intentionally made a little smaller. The gap was extending the active bounding box in both X and Y axis. Y axis extension wasn't desirable, as it made the insertions way too easy to do accidentally, especially when attempting to drag the node.

File: lib/rust/ensogl/component/list-editor/src/lib.rs (hunk 3 above)
Comment (Frizi) [reply lib/rust/ensogl/component/list-editor/src/lib.rs:1091]: It does change the logic. We have to reposition the items after calculating the item index. Repositioning will often delete collapsed placeholders, which made the index conversion incorrect and caused panics down the line.

File: lib/rust/ensogl/core/src/display/object/instance.rs (hunk 4 above)
Comment (Frizi) [reply lib/rust/ensogl/core/src/display/object/instance.rs:3065]: It's simply another convenience method to set margins using two values, one for verticals and one horizontals. We already have one to set all margins to given value, or to set all four independently. The vertical/horizontal one was missing from usual set you have in CSS.

File: lib/rust/ensogl/component/list-editor/src/lib.rs (hunk 2 above)
Comment (wdanilo) [reply lib/rust/ensogl/component/list-editor/src/lib.rs:513]: Wait, but dragging the node by clicking above / below list editor should be hardly supported / unsupported. I mean, there is just a few pixels for that and assuming someone would be able to find these pixels is bad. I prefer the drag areas to be bigger to easier initiate dragging / insertion of elements. Of course, currently there is problem with node dragging because we don't have the icons on the left, but it is not solvable by making this are smaller IMO.

File: lib/rust/ensogl/component/list-editor/src/lib.rs (hunk 3 above)
Comment (wdanilo) [reply lib/rust/ensogl/component/list-editor/src/lib.rs:1091]: oh!

File: lib/rust/ensogl/core/src/display/object/instance.rs (hunk 4 above)
Comment (wdanilo) [reply lib/rust/ensogl/core/src/display/object/instance.rs:3065]: Please ignore my previous comment. I totally missed that this is addition to display objects. I was 100% sure this is in the list editor code!

File: lib/rust/ensogl/core/src/display/object/event.rs [hunk 5]
```diff
@@ -18,12 +18,31 @@ use crate::display::object::instance::WeakInstance;
...
-#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
 pub enum State {
+    Running(Phase),
+    RunningNonCancellable(Phase),
+    // Event has been cancelled, but the event handler is still running.
+    Cancelled(Phase),
+    // Event has been cancelled and [`InstanceDef::emit_event_impl`] function has returned.
+    Stopped(Phase),
+    Finished,
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/object/event.rs:37]: 1. What is finished? It can be many things IMO, lack of dock makes it hard to understand.
2. If I understand the meaning correctly, I think the name `Stopped` should be refactored to `FinishedCancelled` to make it more obvious what is the distinction between the two last.

File: lib/rust/ensogl/core/src/display/object/event.rs [hunk 6]
```diff
@@ -49,11 +68,14 @@ pub struct SomeEvent {
...
+
+    fn from_event<T: 'static>(event: Event<T>) -> Self {
         let state = event.state.clone_ref();
         let current_target = event.current_target.clone_ref();
-        let captures = Rc::new(Cell::new(true));
-        let bubbles = Rc::new(Cell::new(true));
+        let captures = event.captures.clone_ref();
+        let bubbles = event.bubbles.clone_ref();
         Self { data: frp::AnyData::new(event), state, current_target, captures, bubbles }
     }
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/object/event.rs:88]: Why this is not From impl?

File: lib/rust/ensogl/core/src/display/object/instance.rs [hunk 7]
```diff
@@ -2538,40 +2536,58 @@ impl InstanceDef {
...
-        let rev_parent_chain = parent.map(|p| p.rev_parent_chain()).unwrap_or_default();
-        if event.captures.get() {
-            for object in &rev_parent_chain {
-                if !event.is_cancelled() {
-                    event.set_current_target(Some(object));
-                    object.event.capturing_fan.emit(&event.data);
-                } else {
-                    break;
-                }
+    fn emit_event_impl(&self, event: &event::SomeEvent) {
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/object/instance.rs:2554]: This needs proper docs now. The code inside is nicely documented, but this becomes really complex and I'd be very thankful for some docs explaining everything it does in the way it does.

**Review by wdanilo — APPROVED** [review]

**Comment by jdunkerley** [comment]
Quick feedback from trying this branch. The Vector Dropdowns now work :).

But has a detrimental affect on being able to connect links.

https://user-images.githubusercontent.com/4699705/236422595-8efca0c3-cab7-4548-8f44-cbd232ebd77d.mp4

**Comment by jdunkerley** [comment]
Stuff from my trying to use this build today:
- As above dragging to establish a connection is hard.
- Ctrl clicking into edit a node, then moving the cursor by clicking doesn't seem to work.
- If a Vector is pointed at a non-vector (e.g. single value or a function) then you just get a dot.
image
- Seemed to get extra dots on things that aren't vectors.
image
- The + to add the first item doesn't seem to work.
- Comma's seems to be sometimes visible and sometimes not.
image

File: lib/rust/ensogl/core/src/display/object/event.rs (hunk 6 above)
Comment (Frizi) [reply lib/rust/ensogl/core/src/display/object/event.rs:88]: It needs to be private.

**Comment by Frizi** [comment]
I have fixed the issues with edge dragging. My previous event resume implementation have broken the mouse down events in new event system. Now it works again and nodes can be connected as expected, including inside list editor. Ctrl clicking/edit mode is also fixed with that.

image

File: lib/rust/ensogl/component/list-editor/src/lib.rs (hunk 2 above)
Comment (Frizi) [reply lib/rust/ensogl/component/list-editor/src/lib.rs:513]: I will adjust that when working on new node design, as we will have slightly more area to work with. For now, it behaves much better that way. It is still not hard to drag the elements, you simply drag the text anywhere. Also, using `gap` to extend drag area vertically was a little surprising to me. I would prefer that to be a separate configuration input, if we need one.

**Comment by vitvakatu** [comment]
# QA Report 🔴 

1. Adding new elements to the empty vector is not working – the grey circle is unclickable.

Also, `split` does not have the first argument inside the array, see the video:

https://github.com/enso-org/enso/assets/6566674/7034024d-e429-4e2f-8931-2b0521e5e858

2. When dragging the edge over the vector editor, the cursor behaves weirdly, changing the shape to plus when between placeholders. Clicking on a free space with a `plus` cursor uses the nearest placeholder, but removing the connection also removes the element from the vector. It is asymmetrical behavior, I think dropping a new element with a `plus` shape should add the element, not reuse the nearest one.
Moreover, it requires exceptionally gentle positioning of the mouse pointer – a slight movement of a few pixels to the side completely changes the target port, which can confuse users. ("Damn, I hate this pixel-hunting just to connect the edge to the element").


https://github.com/enso-org/enso/assets/6566674/5a98be15-53dc-4b28-b0ae-46ef40011bfa

**Comment by sylwiabr** [comment]
@Frizi what is the status? I would love to test it :)

**Comment by vitvakatu** [comment]
## QA Report 🔴 

In general, looks much nicer. I like how dropping the edge to the vector looks and works now. 

There are still issues that I spotted, but they might be fixed separately, I suppose:

1. On the node `table.rename_columns Map.from_vector`, the `Map.from_vector` part is not visible.

Screenshot 2023-05-15 at 20 39 41

2. Adding elements to the vector after `Map.from_vector` adds `Boolean.True`. That is probably incorrect (it's probably an engine issue, though).
3. Connecting the edge to this vector is hard. It's hard to find a free place. It seems like the free place is right on top of the square bracket. That seems weird. In the video, you can see that I try to target that point for a very long time. Again, pixel-hunting is depressing.

https://github.com/enso-org/enso/assets/6566674/13f35e60-4a3f-4833-bfa6-5a692b29f8f6

4. Sometimes (almost every time for me), dropping the edge there adds two elements.

https://github.com/enso-org/enso/assets/6566674/0d45c438-f79f-4967-8e14-45d8443441dc

5. After recording the previous video, I removed the first element of the vector, and the cursor got stuck in the `red cross` state. Hovering the node again fixed it, so it is not that important.

Screenshot 2023-05-15 at 20 43 49

6. There is a place where the cursor turns green on this node, and pressing LMB produces bizarre code modifications. I don't see the same behavior for other functions, like `String.split`.


https://github.com/enso-org/enso/assets/6566674/a46eb5b0-81de-4e94-aab4-0ab8ff381cbd

**Comment by Frizi** [comment]
PR is now ready for another QA round.

**Comment by vitvakatu** [comment]
QA passed 💚
