### PR TITLE
Right panel visual fixes

### LINKED ISSUE #13222: Right Panel improvements.
* [ ] Top bar in Graph Editor should be more responsive. Buttons not fitting should go to the menu (or all should be there already).
* [x] Graph should not move when resizing right and bottom panel.
* [x] Icons in docpanel should be aligned with Graph Editor top bar.
* ~~Docpanel should be the top one~~
* [ ] Tab hover should look like a tab. No move-animation on switching, just opacity change.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #13222 

Tab highlight changes:

https://github.com/user-attachments/assets/c89a3ffc-c113-42ea-b4e2-d5b9305c0a4b

Responsible Top Bar:

https://github.com/user-attachments/assets/769fd3fb-6227-415d-b7e1-c5811b346d1c

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/ExtendedMenu.vue [hunk 1]
```diff
@@ -3,9 +3,13 @@ import ActionMenu from '@/components/ActionMenu.vue'
 import DropdownMenu from '@/components/DropdownMenu.vue'
 import SvgIcon from '@/components/SvgIcon.vue'
 import { type DisplayableActionName } from '@/providers/action'
+import ZoomControl from './ZoomControl.vue'
 
 const open = defineModel<boolean>('open', { default: false })
-const { actions } = defineProps<{ actions: DisplayableActionName[] }>()
+const { actions } = defineProps<{
```
Comment (kazcw) [inline app/gui/src/project-view/components/ExtendedMenu.vue]: Since `actions` and `zoomControls` are used similarly, let's destructure both or neither

```suggestion
defineProps<{
```

File: app/gui/src/project-view/components/TopBar.vue [hunk 2]
```diff
@@ -5,41 +5,78 @@ import ExtendedMenu from '@/components/ExtendedMenu.vue'
...
+
+const rootSize = useResizeObserver(rootElement)
+const leftGroupsSize = useResizeObserver(leftGroups)
+const zoomControlsSize = useResizeObserver(zoomControls)
+
+const zoomControlsHidden = computed(
+  () => leftGroupsSize.value.x + zoomControlsSize.value.x + 2 * GAP > rootSize.value.x,
+)
+
+const extendeMenuZoomControls = computed(() =>
```
Comment (kazcw) [inline app/gui/src/project-view/components/TopBar.vue]:
```suggestion
const extendedMenuZoomControls = computed(() =>
```

**Review by kazcw — APPROVED** [review]
