### PR TITLE
Make sure import and FQN behave the same

### LINKED ISSUE #9329: Inconsistent import and FQN
As of Mar 8, 2024 there seems to be an inconsistency between `import` and using _fully qualified name_ in certain cases.

### When Main Does not Reexport Submodule

When [Main](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso) in root of library doesn't re-export a submodule, then the module is not going to be accessible via FQN. Example where import works:
```ruby
import Standard.Table.Data.Table
main = Table
```
but where FQN access doesn't work:
```ruby
import Standard.Table
main = Standard.Table.Data.Table
```
and it yields
```bash
Execution finished with an error: Method `Data` of type Main could not be found.
        at <enso> i.main<arg-0>(i.enso:2:8-26)
        at <enso> i.main(i.enso:2:8-32)
```
The same type of problem is also reported as #6553 - the FQN in question is `Standard.Database.Connection.Postgres_Details.Postgres_Details.Postgres` in that case.

### Any Other Case?

Not known yet...
 
### Requested Behavior

If `x.y.z.A` can be imported by such name, one shall be able to use the same name as FQN.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #9329 by using `ImportResolver`'s _algorithm_ also in runtime when `InvokeMethodNode` can't find a `Function` using regular means.

### Important Notes

Cherry picks `ImportsAndFQNConsistencyTest` from #9367

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] [Align the resolution algorithm](https://github.com/enso-org/enso/pull/9539#discussion_r1538804104) in `InvokeMethodNode` and in `ImportResolver` - **done** in 590a1ae
  - [x] Compiler [benchmarks are fine](https://github.com/enso-org/enso/pull/9539#issuecomment-2025158736)

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java [hunk 1]
```diff
@@ -0,0 +1,230 @@
...
+  private static Context ctx;
+
+  /** Used for description in {@link PrintCodeRule} test rule. */
+  private static String code;
+
+  @Rule public final TestRule printCodeRule = new PrintCodeRule();
+
+  /**
+   * Gather all the exported symbols from Standard.Base library. Exclude builtin symbols, and
+   * modules with extension methods.
```
Comment (radeusgd) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java:49]: Why are modules with extension methods excluded?

Or does that just mean that we exclude modules that define _only_ ext methods and thus export no types on their own?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 2]
```diff
@@ -274,6 +298,17 @@ Object doFunctionalDispatchUncachedSymbol(
     return invokeFunctionNode.execute(function, frame, state, arguments);
   }
 
+  private static boolean isNamedAsAssociatedType(Type t) {
+    var at = t.getDefinitionScope().getAssociatedType();
+
+    // XXX doesn't work for Polyglot - it is there 3x times!
+    // return at == t;
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I don't think I understand what this comment is trying to tell.

File: test/Base_Tests/src/Network/Http_Spec.enso [hunk 3]
```diff
@@ -86,7 +86,7 @@ add_specs suite_builder =
             http = HTTP.new (version = version_setting)
             http.version.should_equal version_setting
 
-    url_get = base_url_with_slash + "get"
+    url_get = if base_url_with_slash.is_nothing.not then base_url_with_slash + "get"
```
Comment (radeusgd) [inline test/Base_Tests/src/Network/Http_Spec.enso]: We can use an 'idiom':

```suggestion
    url_get = base_url_with_slash.if_not_nothing <| base_url_with_slash + "get"
```

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: What is the associated type and why does it need special handling?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 4]
```diff
@@ -210,6 +210,30 @@ Object doFunctionalDispatchUncachedSymbol(
...
+          return optionType.get();
+        }
+        var module = scope.getModule();
+
+        var ctx = EnsoContext.get(this);
+        var moduleName =
+            module.getName().item().equals("Main")
+                ? module.getPackage().libraryName().toString()
+                : module.getName().toString();
+        var subModuleName = moduleName + "." + symbol.getName();
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: This is correct. We are in *FQN* resolution, so we are looking only for submodules (child modules). We are not looking for symbols that are exported from the module.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 5]
```diff
@@ -210,6 +210,30 @@ Object doFunctionalDispatchUncachedSymbol(
...
+        if (optionType.isPresent()) {
+          return optionType.get();
+        }
+        var module = scope.getModule();
+
+        var ctx = EnsoContext.get(this);
+        var moduleName =
+            module.getName().item().equals("Main")
+                ? module.getPackage().libraryName().toString()
+                : module.getName().toString();
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: It is probably known, but it is not immediately clear to me why the `Main` module is distinguished in any way and needs this special handling.

Also this looks suspicious to me - does this logic handle correctly cases like a module named `Main` nested deeper than at the top-level of a library?

e.g. `Standard.Base.My_Mod.My_Sub_Mod.Main`? Looking at the code it'd still get resolved to `Standard.Base` which seems wrong.

I know currently we only put `Main` in the top-level, but is that enforced in any way? If not, I think we should be careful not to break such a path OR disallow declaring such a module.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 6]
```diff
@@ -210,6 +210,30 @@ Object doFunctionalDispatchUncachedSymbol(
...
+        var subModuleName = moduleName + "." + symbol.getName();
+        var optionModule = ctx.getTopScope().getModule(subModuleName);
+        if (optionModule.isPresent()) {
+          var subType = optionModule.get().getScope().getAssociatedType();
+          if (subType != null) {
+            return subType;
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I have no idea how can this works. In this control-flow-path, we are not executing anything, we are just returning a Type, but this Java method should execute some Enso method.  I still have suspicion that this can break for some FQN method invocations. I will try to come up with some failing tests to see if my suspicion is correct.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: From Enso perspective, there is no difference between a *module* and a *type*. On both of these, you can execute methods. An `associatedType` is an internal engine way how to distinguish these cases. Every module, has an `associatedType`, which represents that module as a type. For example:
`My_Module.enso`
```
type My_Type
```
An associatedType for `My_Module` module would be a type with `My_Type` members.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Hmm, I don't see why we can be sure here that we are not deeper, but I'm just not familiar enough with this code. I may try to understand it deeper then.

Anyway - if we are so sure, let's add an assert here `assert symbol.getName().path().length() == 2` - that would make it clearer that we know what we are doing (which you probably do know, but I as a reader trying to get familiar with this part of the codebase - don't; and without such pointers it's much harder to get acquainted with it).

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: AH, thanks for the explanation.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Although btw. while not very relevant to this PR, it is not _entirely_ true that there is no difference. Types can be used in signatures, modules cannot. I just ran into it on my current task a few minutes ago:
```
error: The name AWS_Region resolved to a module, but modules are not allowed in type signature.
   36 |     With_Advanced_Properties (base_credential : AWS_Credential) (default_region : AWS_Region)
```

(I messed up an import and imported just the parent module, not the type define inside of it.)

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java:49]: > Why are modules with extension methods excluded?

This is just a limitation of my original testing code. I was not sure how to call extension methods properly directly, for example, from `Standard.Base.Data.Test.Extensions`. Any suggestions?

Note that this testing class is still a work-in-progress. Despite Jaroslav marking this PR as ready-for-review.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: That is probably a bug in type ascriptions. Modules should be allowed for type ascriptions as well. No?

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: It does not look like a bug given that the error message seems to be carefully written - more like a feature someone consciously implemented :)

I don't think we have a use-case for needing a module in a type ascription yet, so for now that does not seem like an issue.

**Comment by JaroslavTulach** [comment]
After @Akirathan new test provided in 635e510 we are facing three new [failures related](https://github.com/enso-org/enso/actions/runs/8431731355/job/23089631728?pr=9539#step:8:3966) to `Standard.Table.Delimited`:
```ruby
import Standard.Table
main = Standard.Table.Delimited.Delimited_Format.Delimited_Format.to_text
```
fails while
```ruby
import Standard.Table.Delimited.Delimited_Format.Delimited_Format
main = Delimited_Format.to_text
```
succeeds. The reason is this line:

https://github.com/enso-org/enso/blob/1872bb66eaad4cde966658b7789c28abc3894a27/distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso#L63

which **imports** a [constructor with all defaulted arguments](https://github.com/enso-org/enso/blame/7e6a9197379da6875f36ca01015166ecc5a0d622/distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso#L52) from `project.Delimited` and **exports** it as under the module name as `Delimited`!. No wonder `Standard.Table.Delimited.Delimited_Format` fails when `Standard.Table.Delimited` isn't a `Module`, but an `Atom`:
```
(Delimited ',' (Encoding.Value 'UTF-8') 0 Nothing (With_Quotes False '"' '"') Infer 
(Data_Formatter.Value True False Auto '' False [Date_Time_Formatter.default_enso_zoned_date_time] 
[Date_Time_Formatter.iso_date] [Date_Time_Formatter.iso_time] ['True', 'true', 'TRUE']
['False', 'false', 'FALSE'])  True Infer Nothing)
```
Library guys, @jdunkerley, @radeusgd you are pretty tough on the engine! I suggest to [restructure the libraries code](https://github.com/enso-org/enso/pull/9539/commits/53889888f272fa348379749d1a423ebaf2e0cd84) to avoid such pitfalls.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: > Modules should be allowed for type ascriptions as well. No?

Not right now. When @kustosz implemented proper type signature checking
- #3511

the biggest set of errors was related to the fact that we name _module and its type the same_. Many signature were just wrong because they referred to module, but wanted to refer to a type. As such Marcin made it an error.

I believe we can keep it this way for a foreseeable future.

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/ImportsAndFQNConsistencyTest.java:49]: The goal of this PR isn't to write a full featured set of tests, but to make sure _imports and FQNs_ behave the same in the runtime. I am using relevant @Akirathan tests from his #9367 to verify the _imports and FQNs consistency_ improves.

Given we now pass 180 new tests, the **consistency has clearly improved**. If there is a know case where FQNs and imports aren't consistent, let's write a test for it, but _increasing coverage just to increase coverage_ isn't goal of this PR.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I am not really satisfied with the code yet - it seems too brutally direct. When investigating what _import/export_ resolution does I found this stack:
```
ImportResolver.tryResolveImport() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:198)
ImportResolver.$anonfun$mapImports$3() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:85)
ImportResolver$$Lambda/0x00007f7c5c55a728.apply() (Unknown Source:0)
List.map() (List.scala:246)
ImportResolver.analyzeModule$1() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:83)
ImportResolver.go$1() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:150)
ImportResolver.mapImports() (runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala:162)
Compiler.liftedTree1$1() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:456)
Compiler.runImportsAndExportsResolution() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:455)
Compiler.$anonfun$runCompilerPipeline$2() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:273)
Compiler$$Lambda/0x00007f7c5c559120.apply() (Unknown Source:0)
List.flatMap() (List.scala:293)
Compiler.runCompilerPipeline() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:268)
Compiler.go$1() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:233)
Compiler.runInternal() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:240)
Compiler.run() (runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:131)
Module.compile() (runtime/src/main/java/org/enso/interpreter/runtime/Module.java:392)
```

### What the [ImportResolver.tryResolveImport](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L198) does?

- it finds the _library name_ [here](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L261)
- then it [ensures the library is loaded](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L269)
- asks the compiler to gives us the [right module for FQN](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L271)
   - that ends calling [TopScope.getModule("Standard.Table.Data")](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java#L240)
- that creates [ResolvedImport with ResolvedModule](https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala#L279)  

I'd say  the functionality of the above diff is similar. It also uses `TopScope.getModule` - just the way it computes the name to search for (with `Main` check) seems wild...

Let's unify these two algorithms a bit.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: When we invoke `Delimited_Format` on object representing `Standard.Table`, then 

> we are not executing anything, we are just returning a Type

we are supposed to return the same thing as `Standard.Table.Delimited_Format`. Which means to _execute nothing_ and _return the type_. Exactly as you say.

> come up with some failing tests to see if my suspicion is correct.

More tests is always welcomed, but I'd like to remind that we have already burned too much time on #9367 and there are more urgent things to fix once this PR gets merged and there is no known example of _FQN and imports_ inconsistency.

**Comment by JaroslavTulach** [comment]
Two tests are failing after 5388988 in `org.enso.interpreter.test.semantic.ImportsTest`:
- [should detect conflicts with the exported types sharing the namespace](https://github.com/enso-org/enso/actions/runs/8432915688/job/23092911110?pr=9539#step:8:2380)
- [should infer correct synthetic modules](https://github.com/enso-org/enso/actions/runs/8432915688/job/23092911110?pr=9539#step:8:2383)

Let's investigate the failures.

**Comment by Akirathan** [comment]
I have another few tests here:
```diff
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/package.yaml b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/package.yaml
new file mode 100644
index 000000000..20780a378
--- /dev/null
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/package.yaml
@@ -0,0 +1,6 @@
+name: Test_Fully_Qualified_Name_1
+license: APLv2
+enso-version: default
+version: "0.0.1"
+author: "Enso Team <contact@enso.org>"
+maintainer: "Enso Team <contact@enso.org>"
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Main.enso b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Main.enso
new file mode 100644
index 000000000..43961c47e
--- /dev/null
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Main.enso
@@ -0,0 +1,19 @@
+
+## We only export A_Type, such that it can be imported and used from other
+   projects with something like:
+     import local.Test_Fully_Qualified_Name_1
+     main = Test_Fully_Qualified_Name_1.A_Type
+
+   or:
+     from local.Test_Fully_Qualified_Name_1 import A_Type
+     main = A_Type
+
+   But we also have to ensure that it can be accessed via physical path:
+     import local.Test_Fully_Qualified_Name_1
+     main = Test_Fully_Qualified_Name_1.Synthetic_Mod.A_Mod.A_Type
+
+import project.Synthetic_Mod.A_Mod.A_Type
+from project.Synthetic_Mod.A_Mod import static_method
+
+export project.Synthetic_Mod.A_Mod.A_Type
+from project.Synthetic_Mod.A_Mod export static_method
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Synthetic_Mod/A_Mod.enso b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Synthetic_Mod/A_Mod.enso
new file mode 100644
index 000000000..e2414ffdd
--- /dev/null
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Synthetic_Mod/A_Mod.enso
@@ -0,0 +1,4 @@
+type A_Type
+
+static_method arg =
+    arg
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/package.yaml b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/package.yaml
new file mode 100644
index 000000000..e3c6c6e4a
--- /dev/null
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/package.yaml
@@ -0,0 +1,7 @@
+name: Test_Fully_Qualified_Name_2
+license: APLv2
+enso-version: default
+version: "0.0.1"
+author: "Enso Team <contact@enso.org>"
+maintainer: "Enso Team <contact@enso.org>"
+prefer-local-libraries: true
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/src/Main.enso b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/src/Main.enso
new file mode 100644
index 000000000..e7d4a1e9a
--- /dev/null
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_2/src/Main.enso
@@ -0,0 +1,14 @@
+import local.Test_Fully_Qualified_Name_1
+
+main =
+    # A_Type is directly exported from Test_Fully_Qualified_Name_1's Main module, so this
+    # expression will surely work
+    type_via_logical_path = Test_Fully_Qualified_Name_1.A_Type
+
+    # Try to use it also via physical FQN
+    type_via_physical_path = local.Test_Fully_Qualified_Name_1.Synthetic_Mod.A_Mod.A_Type
+
+    method_via_logical_path = Test_Fully_Qualified_Name_1.static_method "foo"
+    method_via_physical_path = local.Test_Fully_Qualified_Name_1.Synthetic_Mod.A_Mod.static_method "foo"
+
+    (type_via_logical_path == type_via_physical_path) && (method_via_logical_path == method_via_physical_path)
diff --git a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
index 57cd970e4..5f3a0d6ac 100644
--- a/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
+++ b/engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
@@ -4,4 +4,5 @@ from Standard.Base.Errors.Common import all
 
 main =
     Atom.A 1
+    # `local.Test_Fully_Qualified_Name_Conflict.Atom` should be resolved to a Type, not to a module
     local.Test_Fully_Qualified_Name_Conflict.Atom.Foo 1
diff --git a/engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala b/engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
index 142c77c42..73b71f7ef 100644
--- a/engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
+++ b/engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
@@ -5,7 +5,7 @@ import org.enso.compiler.core.ir.{Module, ProcessingPass, Warning}
 import org.enso.compiler.core.ir.expression.errors
 import org.enso.compiler.core.ir.module.scope.Import
 import org.enso.compiler.data.BindingsMap
-import org.enso.compiler.pass.analyse.BindingAnalysis
+import org.enso.compiler.pass.analyse.{BindingAnalysis, GatherDiagnostics}
 import org.enso.interpreter.runtime
 import org.enso.interpreter.runtime.EnsoContext
 import org.enso.persist.Persistance
@@ -46,6 +46,7 @@ class ImportExportTest
     .err(out)
     .option(RuntimeOptions.LOG_LEVEL, Level.WARNING.getName())
     .option(RuntimeOptions.DISABLE_IR_CACHES, "true")
+    .option(RuntimeOptions.STRICT_ERRORS, "false")
     .logHandler(System.err)
     .option(
       RuntimeOptions.LANGUAGE_HOME_OVERRIDE,
@@ -566,7 +567,7 @@ class ImportExportTest
     }
   }
 
-  "Import resolution from another library honor Main" should {
+  "Import resolution from another library from micro-distribution honor Main" should {
     "resolve Api from Main" in {
       val mainIr = """
                      |from Test.Logical_Export import Api
@@ -1226,4 +1227,27 @@ class ImportExportTest
       errors.size shouldEqual 0
     }
   }
+
+  "Fully qualified names" should {
+    "be able to resolve symbols from local project with import" in {
+      val modName = packageQualifiedName.createChild("Module")
+      """
+        |type Type
+        |""".stripMargin
+        .createModule(modName)
+
+      val mainIr =
+        s"""
+           |import $namespace.$packageName
+           |main = $namespace.$packageName.Type
+           |""".stripMargin
+          .createModule(packageQualifiedName.createChild("Main"))
+          .getIr
+
+      val diags = mainIr
+        .unsafeGetMetadata(GatherDiagnostics, "Should be included")
+        .diagnostics
+      diags.size shouldEqual 0
+    }
+  }
 }
diff --git a/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala b/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
index 3fab6e6f6..06e452d0c 100644
--- a/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
+++ b/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
@@ -209,6 +209,14 @@ class ImportsTest extends PackageTest {
     )
   }
 
+  "Fully qualified names" should "resolve symbols via physical FQN from other project" in {
+    val res = evalTestProject(
+      "Test_Fully_Qualified_Name_2"
+    )
+    res.isBoolean shouldBe true
+    res.asBoolean() shouldBe true
+  }
+
   "Deeply nested modules" should "infer correct synthetic modules" in {
     evalTestProject(
       "Test_Deeply_Nested_Modules"

```

They contain a test that invokes a static method via FQN.

**Comment by JaroslavTulach** [comment]
Test Failure in [reject qualified exports of the same module with conflicting hidden names](https://github.com/enso-org/enso/actions/runs/8438526718/job/23110909155?pr=9539#step:8:3060) ... fixed by 8c02280

**Comment by JaroslavTulach** [comment]
> I have another few tests here:
> They contain a test that invokes a static method via FQN.

Integrated as 1c9bdc4 - thank you, Pavel.

**Comment by JaroslavTulach** [comment]
After merging most recent `develop` which also includes #9559 we have [three failing test](https://github.com/enso-org/enso/actions/runs/8462338420/job/23183546484?pr=9539#step:8:4024) suites:
- `org.enso.interpreter.test.instrument.RuntimeVisualizationsTest`
- `org.enso.interpreter.test.instrument.AvoidIdInstrumentationTagTest`
- `org.enso.interpreter.test.instrument.RuntimeStdlibTest`

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: > handle correctly cases like a module named `Main` nested deeper than at the top-level of a library?

The code [has been rewritten](https://github.com/enso-org/enso/commit/177d402c464749c9323894c4731277895ac040af#diff-16a37c4f502f77bb7f85ed51a7a01b2ece12baf00aa72bfba5d39a4d048a3101R31) in  177d402c to be more _sane_.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Done in 177d402c

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java [hunk 7]
```diff
@@ -0,0 +1,201 @@
+package org.enso.compiler.phase;
+
+import java.io.IOException;
+import java.util.List;
+import java.util.Objects;
+import org.enso.compiler.core.CompilerError;
+import org.enso.editions.LibraryName;
+import scala.Tuple2;
+
+public abstract class ImportResolverAlgorithm<
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java:10]: Similar [coding pattern](http://wiki.apidesign.org/wiki/Singletonizer) to @radeusgd's https://github.com/enso-org/enso/pull/8652/files#diff-f506c17c22831ffcb09018cf21589de4094e513a434364b24a631ede4ce86f8eR28:
- keep the original code flow
- replace access to IR classes with generic type parameters
- trade method call on a removed class by `protected abstract` method

Then [create a subclass](https://github.com/enso-org/enso/pull/9539/files#diff-9034f9f42d0b7d9f8e8066f1ce9dfe5bf0545c3574d988825688cc3cad187aaeR23) that provides back all real types and implements the abstract methods by calling the real methods on the real IR classes.

Finally [create another subclass](https://github.com/enso-org/enso/pull/9539/files#diff-16a37c4f502f77bb7f85ed51a7a01b2ece12baf00aa72bfba5d39a4d048a3101R18) that works with completely different (runtime) classes, but _uses the same algorithm_ behind the hood.

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+    var last = parts.size() - 1;
+    var modName = String.join(".", parts.subList(0, last).stream().toList());
+    var compiler = this.getCompiler();
+    var optionMod = compiler.getModule(modName);
+    if (optionMod.isEmpty()) {
+      return null;
+    }
+    var mod = optionMod.get();
+    compiler.ensureParsed(mod);
+    var b = mod.getBindingsMap();
```
Comment (radeusgd) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]:
```suggestion
    var bindingsMap = mod.getBindingsMap();
```

I think we should prefer to use a bit more meaningful names than just 1-letter ones, it makes the code slightly easier to read, as [suggested by our Java style guide](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md#naming).

**Review by radeusgd — APPROVED** [review]
I'm really happy that we were able to avoid duplicating the imports resolution logic

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 8 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]: I have a long history of [using single letter identifiers](https://github.com/apache/netbeans/blob/e074d9d84e4213d016f47b487fc36deb47e773ff/platform/openide.util.lookup/src/org/openide/util/lookup/ProxyLookup.java#L397). However, of course, only in the implementation. Not as a part of the API. E.g. not in signatures that are visible to external users.

In this case the problem is really small, it is a local variable. In the [previous case](https://github.com/apache/netbeans/blob/e074d9d84e4213d016f47b487fc36deb47e773ff/platform/openide.util.lookup/src/org/openide/util/lookup/ProxyLookup.java#L397) it should have been the same (e.g. just a part of internal implementation), but it turned out that the _debugging was slightly complicated_ - my colleagues were not happy to see class called `R` in the debugger.

**Comment by JaroslavTulach** [comment]
The changes provided in this PR might affect [compiler benchmarks](https://github.com/enso-org/enso/actions/runs/8467856016) as introduced by 
- #9158

InlineCompilerErrorBenchmark_expressionWithErrors

After checking the results of the [benchmark run](https://github.com/enso-org/enso/actions/runs/8467856016)  there seem to be **no regressions** in the compiler benchmarks.

File: engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala [hunk 9]
```diff
@@ -46,6 +46,7 @@ class ImportExportTest
     .err(out)
     .option(RuntimeOptions.LOG_LEVEL, Level.WARNING.getName())
     .option(RuntimeOptions.DISABLE_IR_CACHES, "true")
+    .option(RuntimeOptions.STRICT_ERRORS, "false")
```
Comment (hubertp) [inline engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala:49]: This change seems spurious?

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+    var compiler = this.getCompiler();
+    var repo = compiler.packageRepository();
+    var foundLib = repo.ensurePackageIsLoaded(libraryName);
+    if (foundLib.isRight()) {
+      var moduleOption = compiler.getModule(moduleName);
+      if (moduleOption.isDefined()) {
+        return moduleOption.get();
+      } else {
+        return null;
+      }
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java:131]:
```suggestion
      return compiler.getModule(moduleName).getOrElse(null);
```

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java [hunk 11]
```diff
@@ -0,0 +1,163 @@
...
+    var entities = CollectionConverters.SeqHasAsJava(entitiesStream).asJava();
+    return entities;
+  }
+
+  @Override
+  protected final CompilerContext.Module loadLibraryModule(LibraryName libraryName, String moduleName) throws IOException {
+    var compiler = this.getCompiler();
+    var repo = compiler.packageRepository();
+    var foundLib = repo.ensurePackageIsLoaded(libraryName);
+    if (foundLib.isRight()) {
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java:125]: It's slightly annoying to see this `isRight`/`isLeft` logic. Better to just use `foundLib.fold` call.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java [hunk 12]
```diff
@@ -54,6 +57,12 @@ protected static Context.Builder defaultContextBuilder(String... languages) {
             Paths.get("../../distribution/component").toFile().getAbsolutePath());
   }
 
+  protected static EnsoContext leakContext(Context ctx) {
+    return ctx.getBindings(LanguageInfo.ID)
+        .invokeMember(TopScope.LEAK_CONTEXT)
+        .as(EnsoContext.class);
```
Comment (hubertp) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:63]: this logic has been repeated all over the place. We should probably put it in one place.

File: engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso [hunk 13]
```diff
@@ -4,4 +4,5 @@ from Standard.Base.Errors.Common import all
 
 main =
     Atom.A 1
+    # `local.Test_Fully_Qualified_Name_Conflict.Atom` should be resolved to a Type, not to a module
```
Comment (hubertp) [inline engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso:7]: That one is a bit surprising

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 14]
```diff
@@ -0,0 +1,139 @@
...
+    var associatedType = module.getScope().getType(name.getName());
+    var allRelativeTypes = module.getScope().getTypes().values();
+    return Stream.concat(associatedType.stream(), allRelativeTypes.stream()).toList();
+  }
+
+  @Override
+  protected Module loadLibraryModule(LibraryName libraryName, String moduleName)
+      throws IOException {
+    var optionModule = topScope.getModule(moduleName);
+    return optionModule.isPresent() ? optionModule.get() : null;
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java]:
```suggestion
    return optionModule.orElse(null);
```

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 15]
```diff
@@ -0,0 +1,139 @@
...
+  @Override
+  protected EnsoObject createErrorPackageCoundNotBeLoaded(
+      UnresolvedSymbol imp, String impName, String loadingError) {
+    return null;
+  }
+
+  @Override
+  protected EnsoObject createErrorModuleDoesNotExist(UnresolvedSymbol imp, String impName) {
+    return null;
+  }
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:109]: why are those returning `null`?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 16]
```diff
@@ -0,0 +1,139 @@
...
+    if (byType) {
+      return true;
+    }
+    var byName = at.getName().equals(t.getName());
+    if (!byName) {
+      return false;
+    }
+    var atq = at.getQualifiedName();
+    var tq = t.getQualifiedName();
+    var tqParentOption = tq.getParent();
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:124]: introducing those extra vars just to name them in a cryptic way is kind of confusing and not particularly usefull

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java [hunk 17]
```diff
@@ -0,0 +1,201 @@
...
+
+  /**
+   * @return {@code null} or list of named imports
+   */
+  protected abstract java.util.List<String> onlyNames(Export ex);
+
+  /**
+   * @return {@code null} or list of named imports
+   */
+  protected abstract java.util.List<String> hiddenNames(Export ex);
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java:34]: I don't like that one has to check if those methods return null. We could have a more predictable API by returning empty list and at the usage site use `flatMap` instead of filtering non-null values.

**Review by hubertp — APPROVED** [review]
Mostly style comments at the border of Scala/Java

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 10 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java:131]: I don't think this is correct. Such a code would lead to NPE in the else branch. `getOrElse` needs a function returning a value. E.g. it would be `getOrElse(() -> null)` - but I don't want to create lambda functions.

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 11 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java:125]: It is consistent with the [original Scala](https://github.com/enso-org/enso/pull/9539/files#diff-a3b518b6d9b41b5aec1a3c6c3a2153e38cfd594cd1c11304c094ececdd4cc6cbL270) code that was also checking for `Left` and `Right`. Moreover `fold` would require a lambda function while this code avoids the need for a lambda meta factory generated inner class.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java (hunk 12 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:63]: This is not my code, the code was taken from #9367.

> We should probably put it in one place.

That's what this `leakContext` method in `TestBase` does, I think. It puts the logic into one place where all tests using `TestBase` can find it.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java (hunk 15 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:109]: `null` means _not found_ and then [methodNotFound](https://github.com/enso-org/enso/pull/9539/files#diff-6bc7c2f8a27bdb61f738a75b6accb867d8b5336e3f7d1ea3c7128b26f36e2fa6R216) exception will be thrown.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java (hunk 16 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:124]: `tqPatternOption` is referenced twice on the next line. Giving the variable a name is standard pattern to avoid boilerplate. Áh, you mean: I should use `map` and lambda function - no, thank you - I don't want to use lambda functions in these simple situations.

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 8 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]: Your suggestion would create broken code. Properly renamed at 859ae93

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java (hunk 17 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java:34]: The code remained unchanged compared to Scala version. [hiddenNames](https://github.com/enso-org/enso/pull/9539/files#diff-a3b518b6d9b41b5aec1a3c6c3a2153e38cfd594cd1c11304c094ececdd4cc6cbL213) is an `Option` in Scala.

Java way to express option is to return `null`, callers have an option of `Optional.of(hiddenNames)` to convert it to an `Optional` when they find `if (hiddenNames != null` too old fashioned.

File: engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala (hunk 9 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala:49]: I have no idea. The code was inherited from #9367, CCing @Akirathan

File: engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso (hunk 13 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso:7]: The code was inherited from #9367, CCing @Akirathan. However I am not sure what shall be the problem? Following change works fine:
```diff
$ git diff
diff --git engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
index 5f3a0d6acc..c70cb5414f 100644
--- engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
+++ engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
@@ -5,4 +5,7 @@ from Standard.Base.Errors.Common import all
 main =
     Atom.A 1
     # `local.Test_Fully_Qualified_Name_Conflict.Atom` should be resolved to a Type, not to a module
-    local.Test_Fully_Qualified_Name_Conflict.Atom.Foo 1
+    atom1 = Atom.Foo 1
+    atom2 = local.Test_Fully_Qualified_Name_Conflict.Atom.Foo 1
+    if atom1 != atom2 then "Different" else
+        atom2
```
e.g. `Atom` and ` local.Test_Fully_Qualified_Name_Conflict.Atom` refer to the same `Type`.

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 8 above)
Comment (radeusgd) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]: > Your suggestion would create broken code. Properly renamed at [859ae93](https://github.com/enso-org/enso/commit/859ae93b38bc3c18b197520e01467c66e7d9d141)

The suggestion was just for the variable rename, of course all usages had to be updated.

**Comment by JaroslavTulach** [comment]
We are green. Few questions haven't been fully answered, but I'd like to finish this martyrdom. Let's integrate and move on.

File: engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java (hunk 8 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]: Using suggestions in such a case is a bit misleading. They come with "apply" button, but "applying" the suggestion would result in broken code. It was clear to me the code would be broken in this case, but there were situations in the past when I "applied" and only when CI started to fail I realized the suggestion wasn't a fix, but just a sketch.

I suggest to _not use suggestions_ for changes that would create apparently broken code.

Comment (radeusgd) [reply engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java]: > Using suggestions in such a case is a bit misleading. They come with "apply" button, but "applying" the suggestion would result in broken code. It was clear to me the code would be broken in this case, but there were situations in the past when I "applied" and only when CI started to fail I realized the suggestion wasn't a fix, but just a sketch.

I see, I did not realize that it would be confusing as I was usually applying these manually most of the time anyway - sorry for the confusion it has caused.

> I suggest to _not use suggestions_ for changes that would create apparently broken code.

Ok, I will try to keep that in mind.
