### PR TITLE
Transfer log message arguments in dual JVM mode

### LINKED ISSUE #14850: TelemetryLogFormatter throws NPE in `fast` native image
## Issue

TelemetryLogFormatter throws NullPointerException in native image built locally. Does not happen when built on CI.

1. Build native image locally with `ENSO_LAUNCHER=native,fast sbt buildEngineDistribution`
2. Start the project

```
Exception in thread "pool-5-thread-40" java.lang.NullPointerException
	at org.enso.logging.service.telemetry/org.enso.logging.service.telemetry.TelemetryLogFormatter.transform(TelemetryLogFormatter.java:58)
	at org.enso.logging.service.telemetry/org.enso.logging.service.telemetry.TelemetryLogJobsProcessor.buildPayload(TelemetryLogJobsProcessor.java:40)
	at org.enso.logging.service.common/org.enso.logging.service.common.LogJobsProcessor.buildRequest(LogJobsProcessor.java:149)
	at org.enso.logging.service.common/org.enso.logging.service.common.LogJobsProcessor.sendBatch(LogJobsProcessor.java:117)
	at org.enso.logging.service.common/org.enso.logging.service.common.LogJobsProcessor.logThreadEntryPoint(LogJobsProcessor.java:104)
	at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base@25.0.1/java.lang.Thread.runWith(Thread.java:1487)
	at java.base@25.0.1/java.lang.Thread.run(Thread.java:1474)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
```

- First appears after https://github.com/enso-org/enso/pull/14788

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #14850 by adding `null` check and treating that message as no argument one
- however it is _not enough_ the [problem is deeper](https://github.com/enso-org/enso/pull/14853/changes#r2915982289)
- hence this PR [properly implements transfer of arguments](https://github.com/enso-org/enso/pull/14853/changes#r2934721596) in _dual JVM_ logging system

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- implement [transfer of arguments](https://github.com/enso-org/enso/pull/14853/changes#r2915982289)  in _dual JVM_ logging system
   - [x] testing infrastructure for `SystemLoggerForSlf4j` - [done](https://github.com/enso-org/enso/pull/14853#issuecomment-4040278419)
   - [x] conversion of format string from `{}` to `{0}` - done in 4294fc5
   - [x] conversion backwards - done in f322c0b1520cb15247b4561641deaad1d9c50862
- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Manually tested to check it avoids the `NPE`

### CODE REVIEW

File: lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TelemetryLogFormatter.java [hunk 1]
```diff
@@ -55,15 +55,19 @@ public static ApiMessage.Log transform(LogMessage logMessage) {
       LOGGER.warn("Incorrect arguments format: {}", logEventToString(logMessage));
       return null;
     }
-    if (arguments.size() != logMessage.arguments().length) {
+    var logArgs = logMessage.arguments();
+    if (logArgs == null) {
+      logArgs = new Object[0];
+    }
+    if (arguments.size() != logArgs.length) {
```
Comment (JaroslavTulach) [inline lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TelemetryLogFormatter.java:62]: - with the a9ae3f6140a2e492dc73d4eeb5a4c7e446bb7e1b change the `NullPointerException` is gone
- but the code prints:
```
[WARN] [org.enso.logging.service.telemetry.TelemetryLogFormatter] 
Incorrect number of arguments: {loggerName='org.enso.telemetry.Excel_Workbook.read', message='Read sheet: format={}, output={}, row_count={}, column_count={}, xls_format={}, file_format={}', arguments=[]}
```
- the **missing arguments** are probably caused by following code, which could be modified
```diff
enso$ git diff
diff --git lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerForSlf4j.java lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerForSlf4j.java
index bbea8c87ec..9fed44ebc7 100644
--- lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerForSlf4j.java
+++ lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerForSlf4j.java
@@ -68,7 +68,11 @@ public final class SystemLoggerForSlf4j implements SLF4JServiceProvider, ILogger
         if (throwable != null) {
           delegate.log(at, messagePattern, throwable);
         } else {
-          delegate.log(at, messagePattern);
+          if (arguments != null && arguments.length != 0) {
+            delegate.log(at, messagePattern, arguments);
+          } else {
+            delegate.log(at, messagePattern);
+          }
         }
       }
```
- but even this isn't correct as sl4j and `System.Logger` _disagree on format_ of argument placeholders
   - sl4j is using `{}`
   - while JDK loggers are using `ResourceBundle` format with `{n}` where `n` is the index of the argument
- this will need testing infrastructure, proper code coverage, deeper code fixes

**Comment by JaroslavTulach** [comment]
- testing infrastructure created in 173744d
- and we have a [test failure](https://github.com/enso-org/enso/actions/runs/22959715920/job/66648906012?pr=14853#step:14:1137) as expected

File: lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TelemetryLogFormatter.java (hunk 1 above)
Comment (JaroslavTulach) [reply lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TelemetryLogFormatter.java:62]: Done:

> testing infrastructure for SystemLoggerForSlf4j - https://github.com/enso-org/enso/pull/14853#issuecomment-4040278419
> conversion of format string from {} to {0} - done in https://github.com/enso-org/enso/commit/4294fc5aca78bc8b9c1ffa76ee54b6b2fb21cebe
> conversion backwards - done in https://github.com/enso-org/enso/commit/f322c0b1520cb15247b4561641deaad1d9c50862

**Comment by JaroslavTulach** [comment]
- original report from #14850 seems to be fixed:

> TelemetryLogFormatter throws NullPointerException in native image built locally. Does not happen when built on CI.
>
>    Build native image locally with ENSO_LAUNCHER=native,fast sbt buildEngineDistribution
>    Start the project
>
> Exception in thread "pool-5-thread-40" java.lang.NullPointerException
>	at org.enso.logging.service.telemetry/org.enso.logging.service.telemetry.TelemetryLogFormatter.transform(TelemetryLogFormatter.java:58)
>	at org.enso.logging.service.telemetry/org.enso.logging.service.telemetry.TelemetryLogJobsProcessor.buildPayload(TelemetryLogJobsProcessor.java:40)
>	at org.enso.logging.service.common/org.enso.logging.service.common.LogJobsProcessor.buildRequest(LogJobsProcessor.java:149)
>	at org.enso.logging.service.common/org.enso.logging.service.common.LogJobsProcessor.sendBatch(LogJobsProcessor.java:117)

- I don't see any such exceptions anymore, @4e6.

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4ViaSystemProvider.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+import org.slf4j.IMarkerFactory;
+import org.slf4j.Logger;
+import org.slf4j.spi.MDCAdapter;
+import org.slf4j.spi.SLF4JServiceProvider;
+
+/**
+ * Bridges slf4j logger to {@link System.Logger}. Needs to be enabled by setting JVM properties.
+ * Those are set when booting <em>Other JVM</em> in the <em>dual JVM</em> mode.
+ */
+public final class Slf4ViaSystemProvider implements SLF4JServiceProvider, ILoggerFactory {
```
Comment (4e6) [inline lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4ViaSystemProvider.java]: Otherwise it is inconsistent with `Slf4jViaSystemLogger`
```suggestion
public final class Slf4jViaSystemProvider implements SLF4JServiceProvider, ILoggerFactory {
```

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmUtils.java [hunk 3]
```diff
@@ -76,7 +76,7 @@ public static String[] findJvmArgs(
     commandAndArgs.add("-Djdk.module.main=" + mainModule);
     // commandAndArgs.add("-Djdk.module.showModuleResolution=true");
     commandAndArgs.add(
-        "-Dslf4j.provider=org.enso.logging.config.systemlogger.SystemLoggerForSlf4j");
+        "-Dslf4j.provider=org.enso.logging.config.systemlogger.Slf4ViaSystemProvider");
```
Comment (4e6) [inline lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmUtils.java]: And here
```suggestion
        "-Dslf4j.provider=org.enso.logging.config.systemlogger.Slf4jViaSystemProvider");
```

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+  protected String getFullyQualifiedCallerName() {
+    return null;
+  }
+
+  @Override
+  protected void handleNormalizedLoggingCall(
+      Level level, Marker marker, String messagePattern, Object[] arguments, Throwable throwable) {
+    java.lang.System.Logger.Level at = at(level);
+    if (throwable != null) {
+      delegate.log(at, messagePattern, throwable);
```
Comment (4e6) [inline lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java]: I think you forgot to pass `arguments` here

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemViaSlf4jLogger.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+  }
+
+  @Override
+  public void log(Level level, ResourceBundle bundle, String formatOrMessage, Object... params) {
+    if (isLoggable(level)) {
+      var msg = readMsg(bundle, formatOrMessage);
+      var builder = delegate.atLevel(at(level));
+      if (params != null && params.length > 0) {
+        var nPlaceholders = Collections.nCopies(params.length, "{}").toArray();
+        var slf4jFmt = MessageFormat.format(msg, nPlaceholders);
```
Comment (4e6) [inline lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemViaSlf4jLogger.java]: [MessageFormat](https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html) has special handling of single quotes `'`

> Within a String, a pair of single quotes can be used to quote any arbitrary characters except single quotes. A single quote itself must be represented by doubled single quotes '' throughout a String.

i.e. if not closed, it escapes the rest of the string
```
scala> java.text.MessageFormat.format("It's value {0}", 42)
val res0: String = Its value {0}
```

File: lib/scala/logging-config/src/test/java/org/enso/logging/config/systemlogger/SystemViaSlf4jViaLoggerTest.java [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+    }
+
+    @Override
+    public boolean isInfoEnabled() {
+      return minLevel.compareTo(Level.INFO) >= 0;
+    }
+
+    @Override
+    public boolean isInfoEnabled(Marker marker) {
+      return minLevel.compareTo(Level.DEBUG) >= 0;
```
Comment (4e6) [inline lib/scala/logging-config/src/test/java/org/enso/logging/config/systemlogger/SystemViaSlf4jViaLoggerTest.java]:
```suggestion
      return minLevel.compareTo(Level.INFO) >= 0;
```

**Review by 4e6 — APPROVED** [review]
Approved but a few issues should be addressed before merge

**Comment by JaroslavTulach** [comment]
As reported at [this CI run](https://github.com/enso-org/enso/actions/runs/22966044038/job/66798768962?pr=14853#step:14:6896):
```
 INFO ide_ci::program::command: sbt ℹ️ [error] Failed: Total 27562, Failed 1, Errors 0, Passed 27561, Ignored 28, Pending 30
 INFO ide_ci::program::command: sbt ℹ️ [error] Failed tests:
 INFO ide_ci::program::command: sbt ℹ️ [error] 	org.enso.interpreter.runtime.progress.ObservedMessageTest
 INFO ide_ci::program::command: sbt ℹ️ [warn] javaOptions will be ignored, fork is set to false
 INFO ide_ci::program::command: sbt ℹ️ [warn] javaOptions will be ignored, fork is set to false
 INFO ide_ci::program::command: sbt ℹ️ [error] (library-manager / Test / test) sbt.TestsFailedException: Tests unsuccessful
 INFO ide_ci::program::command: sbt ℹ️ [error] (runtime-integration-tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
 INFO ide_ci::program::command: sbt ℹ️ [error] Total time: 804 s (13:24), completed Mar 12, 2026, 3:01:26 PM
```
- test adjusted in 7771ed5f90d0e13831d014acad329ac8daf5ff53

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4ViaSystemProvider.java (hunk 2 above)
Comment (JaroslavTulach) [reply lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4ViaSystemProvider.java]: Done in 80e96f7ebc

File: lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmUtils.java (hunk 3 above)
Comment (JaroslavTulach) [reply lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmUtils.java]: Done in 80e96f7ebc379d9420529004e5e73fdf8a28abc0

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java (hunk 4 above)
Comment (JaroslavTulach) [reply lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java]: The [System.Logger](https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/lang/System.Logger.html) does not support exception with formatted arguments and a throwable. The assumption probably is that when logging an exception, one doesn't need a to avoid concatenating the string ownself.

Thus when throwable is present, I just pass the `messagePattern` thru. Of course, if you have a logging sample you want to support, then we can enhance the bridge.

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemViaSlf4jLogger.java (hunk 5 above)
Comment (JaroslavTulach) [reply lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemViaSlf4jLogger.java]: I was thinking how to be as compatible with `MessageFormat` as possible and I got an idea: Why not use the real `MessageFormat.format` logic to create the new pattern? That's what the code does. Thus I believe escaping of `'` works!

Of course, if you have a failing test that you want me to get working, then please share the test.

File: lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java (hunk 4 above)
Comment (4e6) [reply lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java]: In that case you need to pass the formatted message (with the arguments applied) instead of the pattern

Comment (JaroslavTulach) [reply lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLogger.java]: Good idea. Done in e1aee5ad1f

File: lib/scala/logging-config/src/test/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLoggerTest.java [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+    slf4j.error("This will be OK!");
+    mock.assertLogged(System.Logger.Level.ERROR, "This will be OK!", null);
+
+    assertFalse("Debug is not loggable", slf4j.isDebugEnabled());
+    slf4j.debug("Not logged at all");
+    mock.assertLogged(null, null, null);
+  }
+
+  @Test
+  public void logMessageWithArguments() {
```
Comment (JaroslavTulach) [inline lib/scala/logging-config/src/test/java/org/enso/logging/config/systemlogger/Slf4jViaSystemLoggerTest.java:29]: Being able to properly log a message with arguments is essential for the telemetry support.
