### PR TITLE
Fix file uploading node expression.

### LINKED ISSUE #5051: File Upload progress indicator shows a Compile Error and never changes the node from 'in-progress' to 'complete' for large files
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184380082).
<hr />

I was testing drag and drop and it seems to sometimes work and sometimes not.

The biggest issue is - when I drop a file onto the stage, there is no immediate feedback that it has been accepted. So if nothing is happening for a while, i do not know if it is uploading and I should just wait or if something just failed.

I tried dragging and dropping multiple files. Small ones (<15KB) work most of the time. With bigger ones, it was a bit random. Usually the first try did nothing at all. After some retries, they do upload fine. But sometimes there are weird artifacts (see screeenshot) where there appears a `File_Uploading` node that is an unresolved reference. 

The biggest issue is lack of progress indicator so I'm not sure if the upload is taking place or if it was discarded for unknown reasons.

## Comments:
 (Radosław Waśko - Feb 2, 2023)
<hr />

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Partially fixes https://github.com/enso-org/enso/issues/5051 

Fix the expression of the node representing a file being uploaded after drag'n'dropping, so it relates to the actually existing standard library function.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by MichaelMauderer — APPROVED** [review]

**Review by wdanilo — APPROVED** [review]

**Comment by vitvakatu** [comment]
QA passed 🟢

File: app/gui/src/controller/upload.rs [hunk 1]
```diff
@@ -77,6 +77,8 @@ pub struct FileToUpload<DataProvider> {
 #[derive(Clone, Debug)]
 pub struct FileUploadProcess<DataProvider> {
     bin_connection:  Rc<binary::Connection>,
+    // See FIXME in upload_chunk method.
```
Comment (vitvakatu) [inline app/gui/src/controller/upload.rs:80]: Btw, where is this FIXME? I don't see it in the code.

Comment (farmaazon) [reply app/gui/src/controller/upload.rs:80]: I removed it accidentally in the last commit. Thanks for awareness!
