### PR TITLE
Fix numeric input widget.

### LINKED ISSUE #11557: Numeric Input Widget is broken
https://github.com/user-attachments/assets/a7bfd7c5-6f8e-461d-86ee-9ffa1475dc6a

### PR DESCRIPTION
**Pull request by Frizi**
Fixes #11557

The issue was caused by a recent parser change, where `is_numeric_literal` function was not adjusted properly and stopped recognizing any numbers as valid. That caused the numeric input widget to always reject any change.

### CODE REVIEW

File: app/rust-ffi/src/lib.rs [hunk 1]
```diff
@@ -48,18 +48,41 @@ pub fn is_numeric_literal(code: &str) -> bool {
...
+
+    #[test]
+    fn test_is_ident_or_operator() {
+        assert!(is_numeric_literal("1234"));
+        assert!(is_numeric_literal("-1234"));
+        assert!(!is_numeric_literal(""));
+        assert!(!is_numeric_literal("-"));
+        assert!(!is_numeric_literal("1-234"));
+        assert!(!is_numeric_literal("1234!"));
+        assert!(!is_numeric_literal("1234e5"));
```
Comment (vitvakatu) [inline app/rust-ffi/src/lib.rs:84]: floating point numbers can also be nice to check

File: app/rust-ffi/src/lib.rs [hunk 2]
```diff
@@ -48,18 +48,41 @@ pub fn is_numeric_literal(code: &str) -> bool {
...
+        };
+        match variant {
+            enso_parser::syntax::tree::Variant::Number(_) => true,
+            enso_parser::syntax::tree::Variant::UnaryOprApp(app) =>
+                app.opr.code == "-"
+                    && app.rhs.as_ref().map_or(false, |rhs| {
+                        matches!(rhs.variant, enso_parser::syntax::tree::Variant::Number(_))
+                    }),
+            _ => false,
+        }
```
Comment (kazcw) [inline app/rust-ffi/src/lib.rs]: We can return `false` earlier if it's not an `ExpressionStatement`:

```suggestion
    let Some(stmt) = &stmt.expression else { return false };
    let enso_parser::syntax::tree::Variant::ExpressionStatement(stmt) = &stmt.variant else {
        return false;
    };
    match &stmt.expression.variant {
        enso_parser::syntax::tree::Variant::Number(_) => true,
        enso_parser::syntax::tree::Variant::UnaryOprApp(app) =>
            app.opr.code == "-"
                && app.rhs.as_ref().map_or(false, |rhs| {
                    matches!(rhs.variant, enso_parser::syntax::tree::Variant::Number(_))
                }),
        _ => false,
    }
```

**Review by kazcw — APPROVED** [review]
I think we should also test editing a numeric input widget in Playwright.
