### PR TITLE
Fix Meta.get_qualified_type_name when run as single file

### LINKED ISSUE #10228: `Meta.get_qualified_type_name` does not work when run outside of project
Suppose we have a project `Proj` with the following files:
`package.yaml`:
```yaml
name: Proj
namespace: local
version: 0.0.1
license: ''
authors: []
maintainers: []
prefer-local-libraries: true
```

`src/Main.enso`:
```
from Standard.Base import all

type My_Type
    Value x

main =
    obj = My_Type.Value 42
    Meta.get_qualified_type_name obj
```

Running it with `enso --run Proj` correctly returns `local.Proj.Main.My_Type`, but when you run it directly with `enso --run Proj/src/Main.enso`, it returns just `Main.My_Type`, which is not a FQN.

The printed names should be the same.

Probably does not work since #8775.

```[tasklist]
### Tasks
- [x] Revert workaround https://github.com/enso-org/enso/pull/10192#discussion_r1631112033
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #10228

### Pull Request Description

`Meta.get_qualified_type_name` correctly returns fully qualified type name when running a single file from a project with `enso --run Proj/src/Main.enso`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/QualifiedNameTest.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+      """;
+
+  @Test
+  public void qualifiedTypeNameWorks_WhenRunningSingleFile() throws IOException {
+    var projDir = temporaryFolder.newFolder().toPath();
+    ProjectUtils.createProject("Proj", mainModSrc, projDir);
+    ProjectUtils.testProjectRun(
+        projDir,
+        (res) -> {
+          assertThat(res.asString(), is("local.Proj.Main.My_Type"));
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/QualifiedNameTest.java:34]: Now the value of `Meta.get_qualified_type_name` is going to be `local.Proj.Main.My_Type`. What was the value before? `Main.My_Type`?

**Review by JaroslavTulach — APPROVED** [review]
Please note there was a task:

> Revert workaround
https://github.com/enso-org/enso/pull/10192#discussion_r1631112033

in the original issue.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/QualifiedNameTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/QualifiedNameTest.java:34]: Yes, it used to be `Main.My_Type` - without the library name and library namespace.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java [hunk 2]
```diff
@@ -159,6 +163,27 @@ private Module(
...
+              + "'");
+    } else if (pkg == null && !name.isSimple()) {
+      throw new IllegalArgumentException(
+          "Qualified module name must be in a package, i.e., trying to initialize "
+              + "a module with a qualified name '"
+              + name
+              + "' without a package");
+    }
+  }
+
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java:186]: This sanity check is the gist of this PR

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala [hunk 3]
```diff
@@ -202,41 +239,41 @@ class TypeSignaturesTest
           |foo a = 42""".stripMargin
       val module = code.preprocessModule
       getSignature(module, "foo") should typeAs(
-        "Unnamed.Test.A" ->: "Unnamed.Test.B" ->: "Unnamed.Test.C" ->: "Unnamed.Test.C" ->: "Unnamed.Test.A"
+        "local.My_Lib.Test.A" ->: "local.My_Lib.Test.B" ->: "local.My_Lib.Test.C" ->: "local.My_Lib.Test.C" ->: "local.My_Lib.Test.A"
       )
     }
 
-    "resolve imported names" in {
+    "XX resolve imported names" in {
```
Comment (radeusgd) [inline engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala:246]: Why is this prefix added?

Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala:246]: Sorry, this is a leftover. I usually add "XX" prefix to a specific scala test so that I can run/debug it easily with a command like `test *TypeSignaturesTest -- -z XX`.

Reverted in another PR in https://github.com/enso-org/enso/pull/11468/commits/845e03040864dc25377c80b3e6bb121654298133
