### PR TITLE
Small visualization fixes

### LINKED ISSUE #9009: Visualization Small Fixes
```[tasklist]
### Tasks
- [x] Big white space above full screen viz.
- [x] Escape should close the full screen visualization.
- [x] Viz shortcuts (Shift-Space, Ctrl-Space) not working.
- [x] Serialize the width of visualizations.
```

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #9009 

- [x] Fixed big white space above full screen viz.
- [x] Escape closes the full screen visualization.
- [x] Viz shortcuts (Shift-Space for toggling fullscreen vis, Ctrl-Space for switching vis type) are implemented.
- [x] The width of visualizations is preserved across project reopens (do we need height as well?)

New video:

https://github.com/enso-org/enso/assets/6566674/d9036ce9-57a4-429b-9bd9-6392782136ea

Older videos:

https://github.com/enso-org/enso/assets/6566674/d7129307-0626-4343-8a76-b9bf764c6a5b

https://github.com/enso-org/enso/assets/6566674/0518d3d8-9ed1-4e6c-bbe0-b7ed00bf7db3

### Important Notes

- Metadata format changed in backward-compatible way

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor.vue [hunk 1]
```diff
@@ -237,6 +237,7 @@ const graphBindingsHandler = graphBindings.handler({
       document.activeElement.blur()
     }
     graphStore.stopCapturingUndo()
+    return false
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor.vue]: Why do we return false here?

File: app/gui2/src/components/GraphEditor/GraphVisualization.vue [hunk 2]
```diff
@@ -200,8 +208,11 @@ watchEffect(async () => {
 })
 
 const isBelowToolbar = ref(false)
-let width = ref<number | null>(null)
+let width = ref<Opt<number>>(props.width)
 let height = ref(150)
+// We want to debounce width changes, because they are saved to the metadata.
+const debouncedWidth = debouncedGetter(() => width.value, 300)
+watch(debouncedWidth, (value) => value != null && emit('update:width', value))
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphVisualization.vue:232]: I think it's not quite working properly. We have `prop.width`, `width` and `debouncedWith` - the `prop.width` will be updated only on debounce, but even then `width` is not updated (ref is only initialized).

I think the getter below should return `props.width`, and we could have a debounce version for events.

File: app/gui2/src/components/VisualizationContainer.vue [hunk 3]
```diff
@@ -49,7 +56,7 @@ function blur(event: Event) {
 const rootNode = ref<HTMLElement>()
 const contentNode = ref<HTMLElement>()
 
-onMounted(() => (config.width = Math.max(config.nodeSize.x, MIN_WIDTH_PX)))
+onMounted(() => (config.width = Math.max(config.width ?? config.nodeSize.x, MIN_WIDTH_PX)))
```
Comment (farmaazon) [inline app/gui2/src/components/VisualizationContainer.vue:52]: This is also a bit of strange mechanic: we update width in config (effectively updating it also in code's metadata if I read code properly) on mount, i.e. when showing visualization, possibly with the width the node happen to have ATM (it may depend even on the project loading stage). I think it's better when the metadata keeps the width set by user by resizing.

File: app/gui2/src/components/VisualizationContainer.vue [hunk 4]
```diff
@@ -88,6 +95,29 @@ const resizeBottomRight = usePointer((pos, _, type) => {
...
+      const allTypes = Array.from(config.types)
+      const currentIndex = allTypes.findIndex((type) => visIdentifierEquals(type, config.currentType))
+      const nextIndex = (currentIndex + 1) % allTypes.length
+      config.updateType(allTypes[nextIndex]!)
+    } else {
+      return false
+    }
+  },
+  exitFullscreen: () => {
+    console.log('exit fullscreen')
```
Comment (farmaazon) [inline app/gui2/src/components/VisualizationContainer.vue]: Do we want to keep this log?

**Review by farmaazon — CHANGES_REQUESTED** [review]

File: app/gui2/src/components/VisualizationContainer.vue (hunk 4 above)
Comment (vitvakatu) [reply app/gui2/src/components/VisualizationContainer.vue]: Debug leftover, thanks

File: app/gui2/src/components/GraphEditor/GraphVisualization.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui2/src/components/GraphEditor/GraphVisualization.vue:232]: I think it works fine. `props.width` is the “persistent” width of the visualization, the one we save and load from the config. `width` is a current width, it might not be equal to “props.width” because of debouncing, but they will sync eventually. When `width` is updated (user resizes the visualization), we sync `props.width` after timeout and everything is normal again.

File: app/gui2/src/components/VisualizationContainer.vue (hunk 3 above)
Comment (vitvakatu) [reply app/gui2/src/components/VisualizationContainer.vue:52]: The purpose of this code is a bit different:
If we have with from metadata (`config.width`), then
  - Set current width to at least `MIN_WIDTH_PX`
Else
  - Set current width and metadata width to current node size, or MIN_WIDTH_PX, whichever is larger.

Without this change, we won’t *load* the width initially, we would always use `config.nodeSize.x`.

**Comment by vitvakatu** [comment]
Huge update, refactoring of a lot of code places. Shortcuts and focusing is now working *almost* ideally. Added new screencast to the description. Now visualizations are focusable, and you can trigger `Shift+Space`, `Cmd+Space` shortcuts in two modes:
1. Visualization is focused (you clicked on it)
2. Node is selected and highlighted, and it is the only selected node on the scene

Escape also works for closing visualizations. Code editor and other graph editor shortcuts also work.

The one remaining issue is the behavior of Graph Editor which effectively ignores any shortcuts if any HTMLElement is focused at the moment. As visualizations can now be focused by mouse-clicking, it can give the user some confusion. 

See this code in graph editor:
```ts
useEvent(window, 'keydown', (event) => {
  ;(!keyboardBusy() && (interactionBindingsHandler(event) || graphBindingsHandler(event))) ||
    (!keyboardBusyExceptIn(codeEditorArea.value) && codeEditorHandler(event))
})
```

`keyboardBusy()` here checks if any HTMLElement is focused, and effectively disables shortcuts in such a case.

This possible change touches a lot of moving parts of the application, and I’m not comfortable enough doing so, especially because this code was recently touched to avoid issues with code editor.

File: app/gui2/src/components/GraphEditor/GraphVisualization.vue (hunk 2 above)
Comment (farmaazon) [reply app/gui2/src/components/GraphEditor/GraphVisualization.vue:232]: Ah, I could not find where do we set width, but it's in unchanged code.

File: app/gui2/src/bindings.ts [hunk 5]
```diff
@@ -25,6 +25,7 @@ export const graphBindings = defineKeybinds('graph-editor', {
   openComponentBrowser: ['Enter'],
   newNode: ['N'],
```
Comment (farmaazon) [inline app/gui2/src/bindings.ts:26]: We should remove this binding.

File: app/gui2/src/bindings.ts [hunk 6]
```diff
@@ -38,6 +39,12 @@ export const graphBindings = defineKeybinds('graph-editor', {
   exitNode: ['Mod+Shift+E'],
 })
 
+export const visualizationBindings = defineKeybinds('visualization', {
+  nextType: ['Mod+Space'],
+  toggleFullscreen: ['Shift+Space'],
+  exitFullscreen: ['Escape'],
+})
+
```
Comment (farmaazon) [inline app/gui2/src/bindings.ts:47]: Instead of duplicating bindings, I would make GraphEditor implement all handlers for visualizationBindings in similar way as toggleFullscreen is implemented (check for single selected node).

File: app/gui2/src/components/GraphEditor/GraphVisualization.vue [hunk 7]
```diff
@@ -273,10 +295,43 @@ const effectiveVisualization = computed(() => {
...
+    if (props.isFullscreen) {
+      emit('update:fullscreen', false)
+    } else {
+      return false
+    }
+  }
+})
+
+
+useEvent(window, 'keydown', (event) => keydownHandler(event))
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/GraphVisualization.vue:345]: If GraphEditor handles `nextType` event, then there's no need for every visualization listen at window level. Instead we could attach handler to it's div (but then let's make sure visualization is focused after going fullscreen).

**Review by farmaazon — APPROVED** [review]
I added some suggestions for improvements. But let's make them in a follow-up PR, as this one is waiting too long.
