### PR TITLE
Promote broken values instead of ignoring them

### LINKED ISSUE #5430: Avoid discarded (error) values in runtime
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/182651431).
<hr />

Whenever a function result is discarded (not assigned to a variable, passed as an argument or returned from the function) _but_ it is different from `Nothing`, it likely indicates a programming error.

For example, if we have:
```
# fun is expected to take two arguments and perform some side effects
foo fun x =
    IO.println "hello"
    fun x x
    IO.println "bye"

main =
    foo (a -> b -> c -> IO.println a+b+c) 10
    foo (a -> b -> IO.println a+b) 10
```

The first `foo` call within `main` will only print hello and bye, but the call to `fun` will not proceed because it expects more arguments. We can detect that a statement that was supposed to be side-effectful returned something else than a `Nothing` and thus know that likely a mistake has happened. The second `foo` call within `main` will indeed print `20` alongside hello and bye.

Of course in some situations it may make sense to discard a non-Nothing result of some action, but if this is intended behaviour, it can always be marked by assigning it to an unused variable name, like so:
```
_ = foo "bar"
```

In such case the intent to discard the value is clearly marked. In other cases, discarding values is most likely a programming error and so it may be worth to warn about such cases.

A runtime linter pass could check values of statements which discard the result and if the value is different from `Nothing` it can report a "runtime warning".

There are a few considerations to such runtime lints though:

1. While a static lint checks each code location once, a runtime check may fire every time some function is called. We definitely do not want thousands of warnings to be fired for the same code location if some specific function is called thousands of times. So the linting mechanism probably will need some way to ensure that the warning is reported only the first time the problem is encountered for a given location and all further warnings for that same location should be suppressed to avoid repetition.
2. It may be worth to completely suppress these checks in 'production' mode. It is important to consider if the checks influence performance in a measurable way.
3. In case of static lints, the code location is usually enough to understand why it fired - because the conditions checked only depend on statically known information present in the code (structure, type signatures). In case of run-time lints, whether the problematic condition is encountered or not may depend on actual values of variables in the context and other dynamic conditions, so just reporting a code location where the problem has happened may not be enough to diagnose it (although in many cases it may already provide enough information). To give a good diagnostic, it may be necessary to provide additional data like values of variables in scope and a stack trace. Alternatively, an ability to set a debugger breakpoint at the moment where the value is discarded could allow the user to interactively analyse the situation that caused  the problem.

## Comments:
To be reviewed as to whether this is the correct path forward. (James Dunkerley - Feb 3, 2023)
<hr />

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Partially fixes #5430 by propagating `DataflowError`s found during statement execution out of the method. 

### Important Notes

This change [may affect behavior](https://github.com/enso-org/enso/pull/11673/files#r1871128327) of existing methods that ignore `DataflowError` as [discussed here](https://github.com/enso-org/enso/pull/11673/files#r1871128327).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation [has been updated](https://github.com/enso-org/enso/pull/11777/commits/afedc71733f881bbd4a29d50ea6f480eadf0be8b), if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [x] Engine [benchmarks run](https://github.com/enso-org/enso/actions/runs/12178060361) is fine
- [x] StdLib [benchmarks run](https://github.com/enso-org/enso/actions/runs/12178083181) seems fine

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    var code =
+        """
+    from Standard.Base import all
+
+    private yield_error yes:Boolean -> Text =
+        if yes then Error.throw "Yielding an error" else
+            "OK"
+
+    suppress_error yes:Boolean value =
+        yield_error yes
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: This 49c628ef1f06e4b4659512964e8c806fe9d9cf12 commit changes the behavior on this line:
- previously the `Error` returned from `yield_error` was ignored
- previously the execution continued to next line and `value` was returned
- now the `Error` is detected and execution of this method ends immediately with the `Error`

To **suppress such behavior** one may simply prefix the call with a dummy `_ = yield_error yes` assignment. As assignments always return `Nothing` the _block statement_ will be considered OK as the `errorIsAssignedAndThatIsEnoughReturnValue` test demonstrates.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java [hunk 2]
```diff
@@ -55,8 +57,15 @@ public static BlockNode buildSilent(ExpressionNode[] expressions, ExpressionNode
   @Override
   @ExplodeLoop
   public Object executeGeneric(VirtualFrame frame) {
+    var ctx = EnsoContext.get(this);
+    var nothing = ctx.getBuiltins().nothing();
     for (ExpressionNode statement : statements) {
-      statement.executeGeneric(frame);
+      var result = statement.executeGeneric(frame);
+      if (result != nothing) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:71]: Why not get rid of this if statement and use simply just `if (result instanceof DataflowError err)`. If it is an instance of `DataflowError`, it cannot be nothing.

**Review by Akirathan — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
There are [two failed](https://github.com/enso-org/enso/runs/33967826266#r2s0) tests in standard libraries:
- [(Decimal_Spec) arithmetic](https://github.com/enso-org/enso/actions/runs/12177821698/job/33966503928?pr=11777#step:7:2048)
- [Date_Range](https://github.com/enso-org/enso/actions/runs/12177821698/job/33966503928?pr=11777#step:7:1960)

This is the kind of errors we can expect if we enable this `DataflowError` propagation. Can you fix the tests easily, @GregoryTravis, @radeusgd?

Btw. this change makes the `Decimal_Spec` error go away:
```diff
diff --git test/Base_Tests/src/Data/Decimal_Spec.enso test/Base_Tests/src/Data/Decimal_Spec.enso
index 3465ce9cd8..6e3a463b82 100644
--- test/Base_Tests/src/Data/Decimal_Spec.enso
+++ test/Base_Tests/src/Data/Decimal_Spec.enso
@@ -487,7 +487,7 @@ add_specs suite_builder =
             (Decimal.from_integer 7297927982888383 . multiply  (Decimal.from_integer 828737) (Math_Context.new 6)) . should_equal (Decimal.from_integer 6048060000000000000000 )
             (Decimal.new "893872388.3535345" . multiply  (Decimal.new "72374727737.23434535") (Math_Context.new 14)) . should_equal (Decimal.new "64693770738918000000")
 
-            (Decimal.new "909678645268840" . divide (Decimal.new "28029830") (Math_Context.new 6)) . should_equal (Decimal.new "32453900 ")
+            _ = (Decimal.new "909678645268840" . divide (Decimal.new "28029830") (Math_Context.new 6)) . should_equal (Decimal.new "32453900 ")
             (Decimal.new "384456406.7860325392609633764" . divide (Decimal.new "24556.125563546") (Math_Context.new 7)) . should_equal (Decimal.new "15656.23")
 
             (Decimal.from_integer 3948539458034580838458034803485 . add (Decimal.from_integer 237957498573948579387495837459837) (Math_Context.new 20)) . should_equal (Decimal.from_integer 241906038031983160230000000000000)
```
e.g. [exactly as expected](https://github.com/enso-org/enso/pull/11777#discussion_r1871119119) it is enough to add a dummy assignment and the problem goes away. I assume you want to do a better fix @GregoryTravis - please integrate it into my branch, so it gets green.
```diff
diff --git test/Base_Tests/src/Data/Time/Date_Range_Spec.enso test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
index b2b469ae1c..22843aa6cb 100644
--- test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
+++ test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
@@ -157,7 +157,7 @@ add_specs suite_builder =
                 r.partition p . should_equal (r.to_vector.partition p)
                 r.all p . should_equal (r.to_vector.all p)
                 r.any p . should_equal (r.to_vector.any p)
-                r.find p . should_equal (r.to_vector.find p)
+                _ = r.find p . should_equal (r.to_vector.find p)
                 r.index_of p . should_equal (r.to_vector.index_of p)
                 r.last_index_of p . should_equal (r.to_vector.last_index_of p)
                 count_mondays acc date =
@@ -170,7 +170,7 @@ add_specs suite_builder =
                 r.partition fc . should_equal (r.to_vector.partition fc)
                 r.all fc . should_equal (r.to_vector.all fc)
                 r.any fc . should_equal (r.to_vector.any fc)
-                r.find fc . should_equal (r.to_vector.find fc)
+                _ = r.find fc . should_equal (r.to_vector.find fc)
                 r.index_of fc . should_equal (r.to_vector.index_of fc)
                 r.last_index_of fc . should_equal (r.to_vector.last_index_of fc)
```
same for `Date_Range_Spec` @radeusgd.

**Review by radeusgd — APPROVED** [review]
Santa came early this year! 🎄
I'm so happy to finally see this change - deep down I knew we may be losing something due to the unhandled errors disappearing into the void. And you confirmed my suspicions. Thankfully that isn't that many errors and they look relatively harmless. But I'm happy that from now on I can keep writing code with the peace of mind that errors will go on unnoticed.

Also we can now remove most instances of `if_not_error` - yay! 🎉 It was basically a workaround for ensuring error propagation. I guess we want to keep the function because it is still useful when we want to control the propagation with 'more precision'. But in numerous cases it should be no longer needed and we can remove a lot of unnecessary indentation from the code.

I submitted commits that fix `should_equal` silently breaking if expected value provided is dataflow error (in that case `should_fail_with` is expected). I will add a commit fixing the `Date_Range_Spec` tests in a moment.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:71]: Indeed this seems redundant, can we remove it, or is there some reason that we don't see here?

**Comment by JaroslavTulach** [comment]
> we want to keep the function because ...

... we already published first customer releases and we are dedicated to **backward compatibility**, right?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:71]: The reason is the _other part_ of #5430:
- what should happen when the value is not `Nothing`
- and it is not `DataflowError` (which is immediately returned)
- #5430 talks about such values, but
- I don't know what to do with them (they are not as simple as `DataflowError`)
- related is #9944

 We don't need to solve it in this PR. Just my 2 Kč explanation of the `!= Nothing` check. In any case, that's for another PR.

**Comment by JaroslavTulach** [comment]
Engine [benchmarks run](https://github.com/enso-org/enso/actions/runs/12178060361) is fine - looks like nobody writes _benchmarks for errors_ ;-) I also glanced StdLib [benchmarks run](https://github.com/enso-org/enso/actions/runs/12178083181) and found nothing suspicious.

**Comment by JaroslavTulach** [comment]
@radeusgd, @GregoryTravis there are still failures in stdlib tests:
- [Date_Range](https://github.com/enso-org/enso/actions/runs/12180626146/job/33975415269?pr=11777#step:7:3945)
- [Decimal_Spec](https://github.com/enso-org/enso/actions/runs/12180626146/job/33975415269?pr=11777#step:7:4097)

Can you fix them?

**Review by jdunkerley — APPROVED** [review]
Approving the libs bits.

**Comment by JaroslavTulach** [comment]
Except these two errors:
> 
> * [Date_Range](https://github.com/enso-org/enso/actions/runs/12180626146/job/33975415269?pr=11777#step:7:3945)
> * [Decimal_Spec](https://github.com/enso-org/enso/actions/runs/12180626146/job/33975415269?pr=11777#step:7:4097)

There seem to be additional ones:
- [should provide various example tables](https://github.com/enso-org/enso/actions/runs/12236167560/job/34129031013?pr=11777#step:7:1996)
- [should be able to be created as a Table](https://github.com/enso-org/enso/actions/runs/12236167560/job/34129031013?pr=11777#step:7:2037)
- [should contain a latitude and longitude](https://github.com/enso-org/enso/actions/runs/12236167560/job/34129031013?pr=11777#step:7:2043)
- [Type names should match table visualization expectations](https://github.com/enso-org/enso/actions/runs/12236167560/job/34129031013?pr=11777#step:7:2257)

**Comment by GregoryTravis** [comment]
> Can you fix them?

I will look at these, after the release.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java (hunk 1 above)
Comment (GregoryTravis) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: Wouldn't we want assignment to *also* propagate errors in this way? This is another class of common missed errors, I would think. Only `catch` should allow you to stop propagation, I would think.

Comment (radeusgd) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: Could you elaborate and show some example where you think the behaviour is not what we want?

From my perspective, with the changes from this PR all is good - the _data**flow**_ errors **flow** with the dataflow, determined by dependencies between method calls. The problem was when the value was unassigned because the dataflow error would be lost unhandled. But if it's assigned to something, it should flow further and be propagated. Unless the name is unused - but we have 'unused warning' for that already.

I think that propagating 'more aggressively' upon assignment would make the dataflow error not much (if at all in practice?) different from a Panic. Also it may be problematic for the IDE. ~~The whole point of dataflow errors is that they _do not stop_ execution of other nodes if they are assigned to something, so that even if one node in the GUI errors, all the others can still be executed.~~

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: > assignment to also propagate errors in this way? 
> This is another class of common missed errors, I would think.

Can such an error be missed without a 

> we have 'unused warning' for that already.

warning being printed by the compiler? If not, then it is less critical scenario. Users get compilation warning and that might warn them enough.

Btw. I think there is a contra-example:
```ruby
x = Error.throw "OK"
x . catch Any h->h
```
the second line wouldn't even be invoked.

Comment (GregoryTravis) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: @radeusgd I definitely see your point -- assignments like this form the top-level spine of the entire program, so this would prevent execution after a dataflow error. For that case, I agree. For an assignment with a regular method call, one that does not represent a top-level node (from the user's point of view), it's still something that could be lost.

@JaroslavTulach I see your point here as well.  However, this case:

```
x = Error.throw "OK"
```

Will still mask errors, and hide them from the end user and the library developer. I don't have a suggestion for how to handle this, but it still should be handled. If something is called "error" then it should never be hidden.

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java:33]: > mask errors, and hide them from ... the library developer

No, it won't hide them. There will be a warning about _unused variable `x`_. E.g. library developer has been notified the code is smelly.

**Comment by GregoryTravis** [comment]
I have fixed the Decimal test failure [here](https://github.com/enso-org/enso/pull/11883) but to get the tests to run at all I had to make a [change to `Array_Like_Helpers.find`](https://github.com/enso-org/enso/pull/11883/files#diff-c5e24473d47930ce7b6fd3f7f643967fcb54fcb01df1e6803438203749988f70R219). This change has caused other test failures which I am looking into.

**Comment by JaroslavTulach** [comment]
There is a [standard libs test failure](https://github.com/enso-org/enso/actions/runs/12369021975/job/34520114002?pr=11777#step:7:11976):
```
test/Table_Tests/src/Util.enso:8:1: error: Cannot import private module 'Standard.Test.Helpers'
      8 | from Standard.Test.Helpers import should_equal_error_check
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:13:78: error: The name `that` could not be found.
     13 | Table.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
        |                                                                              ^~~~
  /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:19:79: error: The name `that` could not be found.
     19 | Column.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
        |                                                                               ^~~~
  /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:25:81: error: The name `that` could not be found.
     25 | DB_Table.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
        |                                                                                 ^~~~
  /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:31:82: error: The name `that` could not be found.
     31 | DB_Column.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
        |                                                                                  ^~~~
Aborting due to 5 errors and 0 warnings.
```
how this is supposed to work, @radeusgd?

**Comment by radeusgd** [comment]
> There is a [standard libs test failure](https://github.com/enso-org/enso/actions/runs/12369021975/job/34520114002?pr=11777#step:7:11976):
> 
> ```
> test/Table_Tests/src/Util.enso:8:1: error: Cannot import private module 'Standard.Test.Helpers'
>       8 | from Standard.Test.Helpers import should_equal_error_check
>         | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:13:78: error: The name `that` could not be found.
>      13 | Table.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
>         |                                                                              ^~~~
>   /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:19:79: error: The name `that` could not be found.
>      19 | Column.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
>         |                                                                               ^~~~
>   /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:25:81: error: The name `that` could not be found.
>      25 | DB_Table.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
>         |                                                                                 ^~~~
>   /runner/_work/enso/enso/test/Table_Tests/src/Util.enso:31:82: error: The name `that` could not be found.
>      31 | DB_Column.should_equal self expected frames_to_skip=0 = should_equal_error_check that <|
>         |                                                                                  ^~~~
> Aborting due to 5 errors and 0 warnings.
> ```
> 
> how this is supposed to work, @radeusgd?

Sorry, it must have been a typo. I thought I ran the tests and should have seen it. 

~~Anyway I will push a fix.~~ 7901a2519f8e55637b0d0a02056bcb387857a7f9 should get this fixed.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java [hunk 3]
```diff
@@ -55,8 +57,15 @@ public static BlockNode buildSilent(ExpressionNode[] expressions, ExpressionNode
...
+        if (result instanceof DataflowError err) {
+          return err;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:74]: @radeusgd suggests to capture the whole stacktrace here (in addition to existing `DataflowError` location) as this is an exceptional state anyway.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:74]: It would be easier to trace down where the error is (rather unexpectedly) rethrown.

This is based on my attempts at fixing the test errors this change has uncovered.

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:74]: Why not just convert it to `PanicError`  then? Just call something like `EnsoContext.raiseAssertionError`?

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:74]: That makes it fully exceptional indeed. If we want set a coding standard that the dataflow errors should never go unhandled, that would work OK.

But actually writing code that relies on this new auto-propagation of errors could allow us to simplify A LOT. For example,
```
a = f.copy_to g
a.if_not_error g
```
could become just
```
f.copy_to g
g
```
which is much simpler (the example above is simple overall but we have big chunks of code that are tied together with `if_not_error` that could get **vastly** simplified with the new propagation scheme).

Well, I guess you made me prove that actually we want to rely on this new propagation schema as _not that exceptional_, less than I initially thought.

**Comment by radeusgd** [comment]
I think I have fixed all the test failures in stdlib, let's see what the CI says.

I also scheduled a run of the nightly CI: https://github.com/enso-org/enso/actions/runs/12378958829 - not sure if Snowflake will run as it has failing tests on develop but we can at least see if there are no more failures than expected.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Extra Nightly Tests · enso-org/enso@434ba8a</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Extra Nightly Tests · enso-org/enso@434ba8a</div></blockquote>

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java:74]: > want to rely on this new propagation schema as _not that exceptional_, less than I initially thought.

OK, in such case there is going to be no change in stacktrace manipulation in this PR. There is:
- `-ea` to enable full stacktraces
- [Context.Dataflow_Stack_Trace](https://github.com/enso-org/enso/blob/7d3293cf4a1ff3a7467d74671d4594d343817c8e/distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso#L156) that could be enabled by the `Standard.Test` framework before running all the tests

In any case we leave it for another PR.

File: distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso [hunk 4]
```diff
@@ -70,23 +72,24 @@ Error.should_fail_with self matcher frames_to_skip=0 unwrap_errors=True =
...
-        additional_comment = case self of
-            _ : Vector -> case that of
-                _ : Vector ->
-                    case self.length == that.length of
-                        True ->
-                            diff = self.zip that . index_of p->
-                                p.first != p.second
-                            "; first difference at index " + diff.to_text + " "
-                        False -> "; lengths differ (" + self.length.to_text + " != " + that.length.to_text + ") "
+Any.should_equal self that frames_to_skip=0 = rhs_error_check that <|
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso]: Finally I see it. This wraps the original code in `rhs_error_check` helper function. It doesn't change API of `Any.should_equal` (it is not easy to see that when argument definition is mixed with code on the same line). As a result of the additional function call, the frames shift and thus `4+frame_to_skip`. The rest remains unchanged.

File: distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso [hunk 5]
```diff
@@ -294,15 +297,20 @@ Error.should_equal self that frames_to_skip=0 =
             1.00000001 . should_equal 1.00000002 epsilon=0.0001
 Number.should_equal : Float -> Float -> Integer -> Spec_Result
 Number.should_equal self that epsilon=0 frames_to_skip=0 =
-    matches = case that of
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso:297]: This change is way easier of parse, we the _function signature_ clearly stays unaffected.

File: distribution/lib/Standard/Test/0.0.0-dev/src/Extensions_Helpers.enso [hunk 6]
```diff
@@ -0,0 +1,14 @@
+from Standard.Base import all
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Test/0.0.0-dev/src/Extensions_Helpers.enso:3]: @radeusgd please use the `private` keyword!

Yes, I see the usage in `test/Table_Tests/src/Util.enso`. Copy the code! Or turn this into official API. My preference is to copy as just two copies aren't enough to benefit from the hassle of turning this into the API.

File: test/Table_Tests/src/Util.enso [hunk 7]
```diff
@@ -5,32 +5,35 @@ import Standard.Database.DB_Column.DB_Column
 from Standard.Table import Column, Table
 
 from Standard.Test import all
+from Standard.Test.Extensions_Helpers import rhs_error_check
```
Comment (JaroslavTulach) [inline test/Table_Tests/src/Util.enso]: I don't like this [friend API between Standard.Test and Table tests](http://wiki.apidesign.org/wiki/FriendDependencies). I'd rather copy the definition of `rhs_error_check` here.

**Review by JaroslavTulach — COMMENTED** [review]
Thank you guys for fixing the test failures. Radek, I don't like the `rhs_error_check` "friend API situation". We shouldn't be cheating like this (at least not in my PR ;-).

File: distribution/lib/Standard/Test/0.0.0-dev/src/Extensions_Helpers.enso (hunk 6 above)
Comment (radeusgd) [reply distribution/lib/Standard/Test/0.0.0-dev/src/Extensions_Helpers.enso:3]: Ok
