### PR TITLE
Log details when `to_display_text` invocation fails

### LINKED ISSUE #10770: Improve `to_display_text` for errors
Issues like https://github.com/enso-org/enso/issues/10750 are horrible to debug with a plain error atom name, e.g. `No_Such_Method`.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Closes #10770 by dumping out more information when `to_display_text` invocations fails.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been updated.

### CODE REVIEW

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java [hunk 1]
```diff
@@ -153,6 +158,7 @@ static Object handleExceptionMessage(
     try {
       return Text.create(strings.asString(text));
     } catch (UnsupportedMessageException e) {
+      ctx.getLogger().log(Level.WARNING, "Cannot convert " + text + " to string", e);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java:162]: @hubertp, is this the right way to dump additional info into CI log including:
- a message
- value of `text`
- exception `e` with its stacktrace

If not, can you please update the line to dump such an info so it appears in the CI log when the error happens?

**Comment by JaroslavTulach** [comment]
Should help addressing #10750

**Review by GregoryTravis — APPROVED** [review]
