### PR TITLE
Various fixes to visualizations

### LINKED ISSUE #10716: No suggestions for Snowflake
image

connection does work if I manually add components by typing them

image

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Closes #10716 by un-marking the `Snowflake_Connection` as `private`.
- Does the same to `SQLServer_Connection`.
- Makes sure that `Snowflake_Connection` has correct visualization and enables links for it.
- Adds a fallback in `to_default_visualization_data` and in Table's `prepare_visualization` so that if `to_js_object` of a given type is malformed, we still get some kind of visualization + debug info about the underlying error.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala [hunk 1]
```diff
@@ -626,7 +626,7 @@ object ProgramExecutionSupport {
               .getOrElse(expressionValue.getClass)
           ctx.executionService.getLogger.log(
             Level.WARNING,
-            "Execution of visualization [{0}] on value [{1}] of [{2}] failed. {3} | {4}",
+            "Execution of visualization [{0}] on value [{1}] of [{2}] failed. {3} | {4} | {5}",
```
Comment (radeusgd) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala:626]: We had 6 interpolations here but only 5 of them were being used. I've added the sixth. we can alternatively stop adding the `error` into the interpolation I guess?

**Comment by radeusgd** [comment]
~~I did not manage to test the change enabling links for `Snowflake_Connection` as [I'm unable to authenticate in the development mode GUI...](https://discord.com/channels/401396655599124480/1201853512409939968/1270001109838331996)~~

I managed to run the local GUI build and verify that the links work fine on Snowflake connection:

image

**Review by kazcw — APPROVED** [review]
Approving frontend-side change.

**Review by GregoryTravis — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

File: app/gui2/src/components/visualizations/TableVisualization.vue [hunk 2]
```diff
@@ -131,6 +131,8 @@ const SQLITE_CONNECTIONS_NODE_TYPE =
   'Standard.Database.Internal.SQLite.SQLite_Connection.SQLite_Connection'
 const POSTGRES_CONNECTIONS_NODE_TYPE =
   'Standard.Database.Internal.Postgres.Postgres_Connection.Postgres_Connection'
+const SNOWFLAKE_CONNECTIONS_NODE_TYPE =
```
Comment (JaroslavTulach) [inline app/gui2/src/components/visualizations/TableVisualization.vue:104]: Removing `private` from implementation classes isn't long term solution. What's the envisioned long term solution?

**Review by JaroslavTulach — COMMENTED** [review]
Removing `private` goes against attempts to encapsulate implementation.

File: app/gui2/src/components/visualizations/TableVisualization.vue (hunk 2 above)
Comment (radeusgd) [reply app/gui2/src/components/visualizations/TableVisualization.vue:104]: It turns out that `Snowflake_Connection` is not an implementation class. It is a public facing type that cannot be private because it is being used by users.

If we want to hide it, we'd probably need a way to have a generic `Connection` interface that is public and `Snowflake_Connection` would only implement it.

**However**, it is not that simple, as we do provide some 'additions' - e.g. `Snowflake_Connection` has additional `warehouse` method that is Snowflake-specific - no other DBs have it. So I think it is actually a public interface.

Though that suggests I should probably move it out of `Internal`.

Comment (JaroslavTulach) [reply app/gui2/src/components/visualizations/TableVisualization.vue:104]: OK. If it is needed by end users, than it shouldn't be in `Internal`.

Comment (radeusgd) [reply app/gui2/src/components/visualizations/TableVisualization.vue:104]: Indeed, I've moved it.
