### PR TITLE
Report AbstractTruffleException as a Panic

### LINKED ISSUE #5260: Throwing an unhandled exception in Polyglot Java results in a null in the UI and no caught error message
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184073253).
<hr />

Throwing a NPE within Java caused an error when command line:
```
Execution finished with an error: null
        at <java> org.enso.table.data.index.MultiValueIndex.makeCrossTabTable(MultiValueIndex.java:185)
        at <enso> case_branch(C:\Repos\Enso\ide\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Table\0.0.0-dev\src\Data\Table.enso:1299:21-122)
```

Within the UI get no error message and the viz shows `null`. Error from Language Server shown below.

## Comments:
 (James Dunkerley - Dec 20, 2022)
<hr />
```
from Standard.Base import Panic
polyglot java import java.lang.NullPointerException

main =
    x = NullPointerException.new
    Panic.throw x
```
Easily reproducible via cli
```
built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --no-ir-caches --run ~/work/repos/enso/test-cases/thrownpe.enso 
Execution finished with an error: null
        at <enso> Panic.throw(Internal)
        at <enso> thrownpe.main(thrownpe.enso:6:5-17)
```

It's because NPEs message is null. (Hubert Plociniczak - Dec 20, 2022)
<hr />

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Report `AbstractTruffleException` as a `Panic`. Fixes #5260.

### Checklist

Please include the following checklist in your PR:

- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
Now the
```
npe = Panic.throw NullPointerException.new
```
is reported by the IDE as
NPE

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 1]
```diff
@@ -246,11 +247,13 @@ public void onReturnExceptional(VirtualFrame frame, Throwable exception) {
...
       } else if (exception instanceof PanicSentinel) {
         onReturnValue(frame, exception);
+      } else if (exception instanceof AbstractTruffleException) {
+        onReturnValue(frame, exception);
       }
     }
 
     private void onExpressionReturn(Object result, Node node, EventContext context) throws ThreadDeath {
-      boolean isPanic = result instanceof PanicSentinel;
+      boolean isPanic = result instanceof AbstractTruffleException;
```
Comment (jdunkerley) [inline engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:254]: do we not need to check for `PanicSentinel` anymore?
Could we remove lines 248-249 as well then?

**Review by jdunkerley — APPROVED** [review]

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:254]: `PanicSentinel extends AbstractTruffleException` - so this check covers also `PanicSentinel`. Yes, lines 248-249 removed in 3cb499fb83.

**Review by 4e6 — APPROVED** [review]

**Review by GregoryTravis — APPROVED** [review]
