### PR TITLE
Convert `Array_Like_Helpers.map` to a builtin to reduce stack size

### LINKED ISSUE #11329: Convert `Array_Like_Helpers.map` to a builtin to reduce stack size
@jdunkerley complained about strange stacktraces when invoking `.map`:

> ```
> map : (Any -> Any) -> Problem_Behavior | No_Wrap -> Vector Any
> map self function on_problems:(Problem_Behavior | No_Wrap)=..Report_Error =
>        Array_Like_Helpers.map self function on_problems
>```
> we end up with 5 stack frames or so in debugger for each, map etc ? 

The stacktraces were much simpler prior to https://github.com/enso-org/enso/pull/8307/files#diff-c5e24473d47930ce7b6fd3f7f643967fcb54fcb01df1e6803438203749988f70R39 when all the logic was just a simple builtin. Now, when there is bunch of wrapper functions in Enso, we see them in the stack. The following program yields an exception:

```ruby
from Standard.Base import all

main =
    [1, 2, 3, 0, ""] . map (5/)
```
and the stacktrace is quite deep:

```
Execution finished with an error: Type error: expected `that` to be Integer, but got Text.
        at <enso> Integer./(Numbers.enso:897:5-60)
        at <enso> Array_Like_Helpers.map.Array_Like_Helpers.map(Array_Like_Helpers.enso:261:45-66)
        at <enso> Array_Like_Helpers.vector_from_function.wrapped_function(Array_Like_Helpers.enso:90:18-27)
        at <enso> Array_Like_Helpers.vector_from_function(Internal)
        at <enso> Array_Like_Helpers.vector_from_function(Array_Like_Helpers.enso:105:15-68)
        at <enso> Array_Like_Helpers.map(Array_Like_Helpers.enso:261:5-79)
        at <enso> Vector.map(Vector.enso:703:9-56)
        at <enso> m.main(m.enso:4:5-31)
```

**Goal**: rewrite the logic into a builtin and make the call appear as a single element on the stack - e.g. the above stack should compose of only **three lines**:

```
Execution finished with an error: Type error: expected `that` to be Integer, but got Text.
        at <enso> Integer./(Numbers.enso:897:5-60)
        at <enso> map(Internal)
        at <enso> m.main(m.enso:4:5-31)
```

Btw. such a _stack compression_ should also help with @AdRiley problem of too deep stacktraces as one `.map` invocation is more than hundred Java stack frames in the interpreter right now:

- #11327 

By having `.map` as a builtin we **lower the stack requirements** a lot given how frequently we are using `.map` & co.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #11329

### Pull Request Description

The ultimate goal is to reduce the method calls necessary for `Vector.map`.

### Important Notes

- I managed to reduce the number of Java stack frames needed for each `Vector.map` call from **150** to **22** (See https://github.com/enso-org/enso/pull/11363#issuecomment-2432996902)
- Introduced `Stack_Size_Spec` regression test that will ensure that Java stack frames needed for `Vector.map` method call does not exceed **40**.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Run (at least engine) benchmarks to ensure no regressions.
- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by Akirathan** [comment]
The experiment in [Stack_Size_Spec.enso](https://github.com/enso-org/enso/pull/11363/files#diff-52bc12c590e512ee827596e4557f09e8fb9dac182e201f6ca44f80a9670be5be) generates code for nested `Vector.map` calls and invokes enso subprocess with custom `-Xss` option (and with disabled Truffle compiler). The current output is:
```
{nesting: 3, stack_size: 256k} SUCCEEDED
{nesting: 6, stack_size: 256k} FAILED with StackOverflow
{nesting: 9, stack_size: 256k} SKIPPED (SO already encountered with the same stack size in lower nesting levels)
{nesting: 3, stack_size: 300k} SUCCEEDED
{nesting: 6, stack_size: 300k} SUCCEEDED
{nesting: 9, stack_size: 300k} FAILED with StackOverflow
```
Which means that, e.g., a `Vector.map` method called on nested `[[[[[[42]]]]]]` with `-Xss256k` failed with SO.
The code for "nesting: 3" looks for example like this:
```
from Standard.Base import all
main =
    vec = [[[42]]]
    vec.map e0->
        e0.map e1->
            e1.map e2->
                e2 + 1
```

I am not sure yet what to do with that experiment. We should probably integrate it somehow later as a regression test.

**Comment by Akirathan** [comment]
https://github.com/enso-org/enso/pull/11363/commits/990ee6a54431cd14e65291ac9bf223b3dae04e1d introduces a regression test `Stack_Size_Spec` that invokes enso as subprocess with some specific JVM options and counts the Java stack frames between invocations of `Vector.map`, and assumes that the count is less than 115. On develop, this test fails - there are **150** stack frames between calls. In this PR, it succeeds - there are **103** stack frames. With added `@Tail_Call` annotations to `Vector.map` and `Array_Like_Helpers.map`:
```diff
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
index 4ce7c5bdb4..27c9bed438 100644
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
@@ -700,7 +700,7 @@ type Vector a
              [1, 2, 3] . map +1
     map : (Any -> Any) -> Problem_Behavior | No_Wrap -> Vector Any
     map self function on_problems:(Problem_Behavior | No_Wrap)=..Report_Error =
-        Array_Like_Helpers.map self function on_problems
+        @Tail_Call Array_Like_Helpers.map self function on_problems
 
     ## ICON union
        Applies a function to each element of the vector, returning the `Vector`
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
index aaf2442940..416be3d4a5 100644
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
@@ -229,7 +229,7 @@ transpose vec_of_vecs =
             Vector.from_polyglot_array proxy
 
 map vector function on_problems =
-    vector_from_function vector.length (i-> function (vector.at i)) on_problems
+    @Tail_Call vector_from_function vector.length (i-> function (vector.at i)) on_problems
 
 map_with_index vector function on_problems =
     vector_from_function vector.length (i-> function i (vector.at i)) on_problems

```

the number of stack frames is **22**, with the disadvantage that the `Vector.map` call is not visible in `Runtime.get_stack_trace`. At the end, I have decided not to add the `@Tail_Call` annotations there for now. I think that the reduction of 35 Java stack frames per `Vector.map` method call is sufficient improvement.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+    } else {
+      return vector;
+    }
+  }
+
+  private OnProblems processOnProblemsArg(Object onProblems, TypesLibrary typesLib) {
+    var ctx = EnsoContext.get(this);
+    var problemBehaviorBuiltin = ctx.getBuiltins().getBuiltinType(ProblemBehavior.class);
+    var noWrapBuiltin = ctx.getBuiltins().getBuiltinType(NoWrap.class);
+    var typeError =
```
Comment (GregoryTravis) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java]: Will this get constructed on each call, or will it be optimized out if it's not used?

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java]: Yeah, what's the IGV graph for this method when it is used?

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java]: It might make sense to speculate on `onProblems` to be a constant - in most of the cases it would be...

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+      Function func,
+      Object onProblemsAtom,
+      @Cached("buildWithArity(1)") InvokeFunctionNode invokeFunctionNode,
+      @Cached("build()") AppendWarningNode appendWarningNode,
+      @CachedLibrary(limit = "3") WarningsLibrary warnsLib,
+      @CachedLibrary(limit = "3") TypesLibrary typesLib,
+      @Cached BranchProfile errorEncounteredProfile) {
+    var ctx = EnsoContext.get(this);
+    var onProblems = processOnProblemsArg(onProblemsAtom, typesLib);
+    var len = Math.toIntExact(length);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java]: What will happen on `ArithmeticException`? It shouldn't crash the interpreter.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+    var nothing = ctx.getNothing();
+    var target = ArrayBuilder.newBuilder(len);
+    var errorsEncountered = 0;
+    for (int i = 0; i < len; i++) {
+      var value = invokeFunctionNode.execute(func, frame, state, new Long[] {(long) i});
+      Object valueToAdd = value;
+      if (value instanceof DataflowError err) {
+        errorEncounteredProfile.enter();
+        switch (onProblems) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java:74]: It would help the size of IGV graph if `onProblems` was a constant when a single `DataflowError` appears.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoWrap.java [hunk 4]
```diff
@@ -0,0 +1,9 @@
+package org.enso.interpreter.node.expression.builtin.error;
+
+import org.enso.interpreter.dsl.BuiltinType;
+import org.enso.interpreter.node.expression.builtin.Builtin;
+
+@BuiltinType(name = "Standard.Base.Data.Vector.No_Wrap")
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoWrap.java:7]: Off-topic, but I'd like to know the answer: What is `name` attribute **optional**? It is specified on some of the builtins, but not on all. Shouldn't it be specified all the time? I am asking because of

- #8852

the proposed `Standard.Prelude` should include all the builtins and their methods, but we want to have their names exactly the same as in `Standard.Base` - can we generate such a `Prelude.enso` from these annotations?

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+            Panic.throw err
+
+    project_root = File.new enso_project.root.to_text
+    repository_root = project_root . parent . parent
+    built_distribution = find_prefix repository_root "built-distribution"
+    enso_engine = find_prefix built_distribution "enso-engine-"
+    enso = find_prefix enso_engine "enso-"
+    bin = find_prefix enso "bin"
+
+    exe = File.new bin / if Platform.os == Platform.OS.Windows then "enso.bat" else "enso"
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Runtime/Stack_Size_Spec.enso:39]: The execution in a separate file was necessary when we awaited `StackOverflowException`. However now, we are _just counting frames_ in Java stack trace. Can we just `Debug.eval` the generated code inside of the process?

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+   larger thread stack and also with larger stack trace element collected
+   (which is needed for `new RuntimeException().getStackTrace().length`)
+   as this value is by default set only to 1024.
+
+   The thread stack size is also set to a sufficiently large value
+   to ensure there is no StackOverflow.
+run_without_compiler enso_args:Vector -> Process_Result =
+    java_opts = "-Dpolyglot.engine.Compilation=false "
+                + "-XX:MaxJavaStackTraceDepth=18000 "
+                + "-Xms16M"
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Runtime/Stack_Size_Spec.enso:100]: Can we get back to the original, default value of `-Xms1M`? CCing @AdRiley 

- #11233

Now, when the stack size is so greatly reduced, I would prefer real fix than just increasing the consumption of precious resources. Btw. can we verify the `test/Microsoft_Tests` succeed (or at least initialize, I am not sure we want to wait for them to finish running in the interpreter without compilation) with `--vm.D=polyglot.engine.Compilation=false`?

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+    j_frames_line.split '=' . last . parse_integer
+
+
+add_specs suite_builder =
+    suite_builder.group "Stack size" \group_builder ->
+        group_builder.specify "Java stack size of nested Vector.map should be kept reasonably low" <|
+            nesting_10 = run 10
+            nesting_11 = run 11
+            stack_size = nesting_11 - nesting_10
+            (stack_size < 115) . should_be_true
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Runtime/Stack_Size_Spec.enso]: According to [following note](https://github.com/enso-org/enso/pull/11363#issuecomment-2432996902):

> the number of stack frames is 22 (or) ... 35 Java stack frames per `Vector.map` method call is sufficient improvement.

Shouldn't this number be at most `40`?

**Review by JaroslavTulach — COMMENTED** [review]
Few code comments inlined.

> At the end, I have decided not to add the @Tail_Call annotations there for now. I think that the reduction of 35 Java stack frames per Vector.map method call is sufficient improvement.

I don't think I agree with such decision. I am more concerned about performance and avoiding `StackoverflowError` than the shape of the stack. Moreover ...

> the number of stack frames is 22, with the disadvantage that the Vector.map call is not visible in Runtime.get_stack_trace. 

...if we want to see something that resembles `Vector.map` in the stack, then rename `Array_Like_Helpers` to `Vector_Impl` and `vector_from_function` to `map` and we'll get a reasonable stack names while keeping the stack size down to `22`.

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso (hunk 5 above)
Comment (Akirathan) [reply test/Base_Tests/src/Runtime/Stack_Size_Spec.enso:39]: I tried it with:
```diff
diff --git a/test/Base_Tests/src/Runtime/Stack_Size_Spec.enso b/test/Base_Tests/src/Runtime/Stack_Size_Spec.enso
index e9681c388d..20a6a459cf 100644
--- a/test/Base_Tests/src/Runtime/Stack_Size_Spec.enso
+++ b/test/Base_Tests/src/Runtime/Stack_Size_Spec.enso
@@ -13,118 +13,76 @@
 private
 
 from Standard.Base import all
-import Standard.Base.Runtime.Ref.Ref
 import Standard.Base.System.Process.Process_Builder.Process_Result
 
 from Standard.Test import all
 
-
-## Find the Enso binary under the `built-distribution` directory
-enso_bin -> File =
-    find_prefix dir prefix =
-        vec = dir.list name_filter=prefix+"*"
-        if vec.length == 1 then vec.at 0 else
-            msg = "Cannot find " + prefix + "* in " + dir.to_text + '\n'
-            err = dir.list.fold msg t-> f->
-                t + f.to_text + '\n'
-            Panic.throw err
-
-    project_root = File.new enso_project.root.to_text
-    repository_root = project_root . parent . parent
-    built_distribution = find_prefix repository_root "built-distribution"
-    enso_engine = find_prefix built_distribution "enso-engine-"
-    enso = find_prefix enso_engine "enso-"
-    bin = find_prefix enso "bin"
-
-    exe = File.new bin / if Platform.os == Platform.OS.Windows then "enso.bat" else "enso"
-
-    if exe.is_regular_file.not then Panic.throw "Cannot find "+exe.to_text
-
-    exe
+polyglot java import java.lang.RuntimeException
 
 ## Generates code for mapping over a vector with the given nesting level.
-   Returns code of the main method that is meant to be pasted into a separate module.
-   The code prints the count of Java frames to stdout in the deepest `Vector.map` call.
 
    Example of the code is (for nesting_level 2):
    ```
-   main =
-       vec = [[42]]
-       vec.map e0->
-           e0.map e1->
-               cnt = RuntimeException.new.getStackTrace.length
-               IO.println 'java_stack_frames='+cnt.to_text
+   vec = [[42]]
+   vec.map e0->
+       e0.map e1->
+           cnt = RuntimeException.new.getStackTrace.length
+           cnt
    ```
 
    Arguments:
    - nesting_level How many times should the vector be nested
 generate_code nesting_level:Integer -> Text =
     bldr = Vector.Builder.new
-    bldr.append "from Standard.Base import all"
-    bldr.append "polyglot java import java.lang.RuntimeException"
-    bldr.append '\n'
-    bldr.append <| "main = "
-    bldr.append <| "    "
-                   + "vec = "
+    bldr.append <| "vec = "
                    + ("[" * nesting_level)
                    + "42"
                    + ("]" * nesting_level)
-    bldr.append <| "    "
-                   + "vec.map e0->"
+    bldr.append <| "vec.map e0->"
     0.up_to (nesting_level - 1) . each \i ->
-        bldr.append <| ("    " * (i + 2))
+        bldr.append <| ("    " * (i + 1))
                        + "e"
                        + i.to_text
                        + ".map e"
                        + (i + 1).to_text
                        + "-> "
-    bldr.append <| ("    " * (nesting_level + 1))
+    bldr.append <| ("    " * nesting_level)
                    + "cnt = RuntimeException.new.getStackTrace.length"
-    bldr.append <| ("    " * (nesting_level + 1))
-                   + "IO.println <| 'java_stack_frames=' + cnt.to_text"
+    bldr.append <| ("    " * nesting_level)
+                   + "cnt"
                    + '\n'
     bldr.to_vector.reduce \first_line:Text second_line:Text ->
         first_line + '\n' + second_line
 
 
-## Runs Enso subprocess with disabled Truffle compiler, with
-   larger thread stack and also with larger stack trace element collected
-   (which is needed for `new RuntimeException().getStackTrace().length`)
-   as this value is by default set only to 1024.
-
-   The thread stack size is also set to a sufficiently large value
-   to ensure there is no StackOverflow.
-run_without_compiler enso_args:Vector -> Process_Result =
-    java_opts = "-Dpolyglot.engine.Compilation=false "
-                + "-XX:MaxJavaStackTraceDepth=18000 "
-                + "-Xms16M"
-    args = ["JAVA_OPTS="+java_opts, enso_bin.path] + enso_args
-    Process.run "env" (args + enso_args)
-
 
-## Runs enso as a subprocess with the specified nesting level of `Vector.map` calls.
+## Runs generated code via `Runtime.Debug.eval`.
    Returns count of Java stack frames from the deepest `Vector.map` call.
 
    Arguments:
    - nesting Level of nesting of `Vector.map` method calls.
 run nesting:Integer -> Integer =
-    tmp_file = File.create_temporary_file suffix=".enso"
     code = generate_code nesting
-    code.write tmp_file
-    proc_res = run_without_compiler ["--run", tmp_file.path]
-    # FInd and parse a specific line from the process stdout
-    j_frames_line = proc_res.stdout.split '\n' . find \line ->
-        line.contains "java_stack_frames"
-    j_frames_line.split '=' . last . parse_integer
+    # Result from the generated code is Java stack size inside a nested vector
+    res = Standard.Base.Runtime.Debug.eval code
+    stack_size = 0.up_to nesting . fold res \acc _ ->
+        acc.first
+    stack_size
 
 
 add_specs suite_builder =
     suite_builder.group "Stack size" \group_builder ->
         group_builder.specify "Java stack size of nested Vector.map should be kept reasonably low" <|
-            nesting_10 = run 10
-            nesting_11 = run 11
-            stack_size = nesting_11 - nesting_10
-            (stack_size < 115) . should_be_true
+            res_4 = run 4
+            res_3 = run 3
+            stack_size = res_4 - res_3
+            # 1024 is the mas number of stack trace elements from `RuntimeException.new.getStackTrace`.
+            Test.with_clue "res_3="+res_3.to_text+" " <|
+                (res_3 < 1024) . should_be_true
+            Test.with_clue "res_4="+res_4.to_text+" " <|
+                (res_4 < 1024) . should_be_true
+            Test.with_clue "Stack size should be low, but was "+stack_size <|
+                (stack_size < 40) . should_be_true
 
 
 main filter=Nothing =

```

But that is failing because the default stack trace elements, as returned by `java.lang.Throwable.getStackTraceElements()` is 1024 and that limit is exceeded in the test, because the `run 4` and `run 3` methods are called in an already deep stack. Besides, when you try to run it via `Debug.eval`, the number you get is unstable, probably because of the compiler.

Running those tests as a subprocess with explicitly set `-Dpolyglot.engine.Compiler=false` is the most reliable way currently.

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso (hunk 7 above)
Comment (Akirathan) [reply test/Base_Tests/src/Runtime/Stack_Size_Spec.enso]: In e0063aab6596fcdcdb7298e2d05250c63e243866, the `Vector.map` and `Array_Like_Helpers.map` are marked as `@Tail_Call`. Moreover, the test specifies `40` and succeeds.

**Comment by Akirathan** [comment]
> I don't think I agree with such decision. I am more concerned about performance and avoiding StackoverflowError than the shape of the stack.

@JaroslavTulach In e0063aab6596fcdcdb7298e2d05250c63e243866, the `Vector.map` and `Array_Like_Helpers.map` methods are marked as `@Tail_Call`. This further reduces the stack size needed between `Vector.map` calls to 22.

> .if we want to see something that resembles Vector.map in the stack, then rename Array_Like_Helpers to Vector_Impl and vector_from_function to map and we'll get a reasonable stack names while keeping the stack size down to 22.

 As you say, should there be a need to see the "original/real" stack trace, there are ways to do it. For now, let's keep those and tail calls and be glad for the stack size reduction and potential performance improvements. I am hesitant to do any renaming unless some test fails. If somebody from the libs team complains in the future about "weird stack trace", they can create a ticket for it, and we will deal with that later.

Note that I am still planning to schedule and compare benchmarks before integrating. But first, I would like to fix all the failing tests.

File: test/Base_Tests/src/Runtime/Stack_Size_Spec.enso (hunk 6 above)
Comment (Akirathan) [reply test/Base_Tests/src/Runtime/Stack_Size_Spec.enso:100]: Adam's PR reverted in 9c3d18fb3b8bceeb66662c603e0e9c1b90ecdd42. Note that the `"-Xms16M"` specified on this line is only for testing purposes.

**Review by JaroslavTulach — APPROVED** [review]
Please update description of the PR before merging.

**Review by AdRiley — APPROVED** [review]

**Comment by Akirathan** [comment]
- Engine benchmarks scheduled at https://github.com/enso-org/enso/actions/runs/11562719764
- stdlib benchmarks scheduled at https://github.com/enso-org/enso/actions/runs/11562731094

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@a445a31</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@a445a31</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java:74]: `onProblems` parameter is cached in 89b5e59f4d7fe38d063e4aeb598a138fc7aae350

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java]: `onProblems` parameter is cached in 89b5e59f4d7fe38d063e4aeb598a138fc7aae350. It helps with the performance.

**Comment by Akirathan** [comment]
Another benchmarks scheduled at:
- engine benches - https://github.com/enso-org/enso/actions/runs/11578739585
- stdlib benches: https://github.com/enso-org/enso/actions/runs/11578753258

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@6ac51d7</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@6ac51d7</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by Akirathan** [comment]
[Caching onProblems argument](https://github.com/enso-org/enso/pull/11363/commits/89b5e59f4d7fe38d063e4aeb598a138fc7aae350) apparently helped:
image

**Comment by Akirathan** [comment]
Locally verified regression of `IfVSCaseBenchmarks.ifBench6In`:
image

local develop results: **1.685 ± 0.534**
local results on this PR: **2.259 ± 0.320**

**Comment by JaroslavTulach** [comment]
> Locally verified regression of `IfVSCaseBenchmarks.ifBench6In`:...
> local develop results: **1.685 ± 0.534** local results on this PR: **2.259 ± 0.320**

I'd like to point out that #11365 is going to change the way we do `if/then/else`. Once #11365 is in, we will no longer try to invoke `if_then_else` method on the _condition_. However take a look at the `ifBench6In` benchmark:
```ruby
        if_bench_6_in vec =
            vec.fold 0 acc-> curr->
                curr.f1.not.if_then_else acc <|
                    curr.f2.not.if_then_else acc <|
                        curr.f3.not.if_then_else acc <|
                            curr.f4.not.if_then_else acc <|
                                curr.f5.not.if_then_else acc <|
                                    curr.f6.not.if_then_else acc <|
                                        acc + 1
```
The [ifBench6In benchmark](https://github.com/enso-org/enso/blob/2bbd90970547eed11b4c52f5b73c0bac785379f3/engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java#L89) is doing exactly that! It invokes the `if_then_else` method.

If _slowdown in ifBench6In benchmark_ is the only blocker, then I suggest to ignore it.

**Comment by Akirathan** [comment]
Another locally verified regression of `org.enso.interpreter.bench.benchmarks.semantic.TypePatternBenchmarks.matchOverAny` benchmark, after increasing the dataset size (so that one iteration takes more than 10E-6 ms):
```diff
diff --git a/engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java b/engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
index 9343bd153..97a742657 100644
--- a/engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
+++ b/engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
@@ -66,7 +66,7 @@ public class TypePatternBenchmarks {
 
     Function<String, Value> getMethod = (name) -> module.invokeMember(Module.EVAL_EXPRESSION, name);
 
-    var length = 100;
+    var length = 100_000;
     this.vec = getMethod.apply("gen_vec").execute(length, 1.1);
     switch (SrcUtil.findName(params)) {
       case "matchOverAny" -> this.patternMatch = getMethod.apply("match_any");
```

On develop: **0.213 ± 0.020**
On this PR: **0.411 ± 0.004**

**Comment by Akirathan** [comment]
Regressions resolved. Turns out I was caching the `Atom onProblems` argument incorrectly. Fixed by converting `No_Wrap` builtin type to uniquely constructible builtin and caching `AtomConstructor` directly in d2dcc04475176f813ccd991ecb8f7654fa8d3e44. That commit also introduces `LoopConditionProfile` which speeds up the benchmark tremendously. Local results of `org.enso.interpreter.bench.benchmarks.semantic.TypePatternBenchmarks.matchOverAny` is now 2x faster than on develop.

**Comment by Akirathan** [comment]
Wait for the tests to be green and then, let's schedule another round of benchmarks

**Comment by JaroslavTulach** [comment]
> Wait for the tests to be green and then, let's schedule another round of benchmarks

Benchmark may run even without tests to be fully green. Trying to run the benchmarks right now might speed things up.

**Comment by Akirathan** [comment]
Benchmarks scheduled:
- engine: https://github.com/enso-org/enso/actions/runs/11689582950
- stdlib: https://github.com/enso-org/enso/actions/runs/11689592733

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@2cbc1e9</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Benchmark Engine · enso-org/enso@2cbc1e9</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@2cbc1e9</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Benchmark Standard Libraries · enso-org/enso@2cbc1e9</div></blockquote>

**Comment by Akirathan** [comment]
All (stable) benchmarks are either the same, or better, let's integrate.
