### PR TITLE
Automatically apply tail call optimizations

### LINKED ISSUE #10956: Automatically detect suitable @Tail_Call optimization
Currently Enso requires one to use [@Tail_Call annotation](https://github.com/enso-org/enso/blob/da3490ebb75a7d0477b48a298936275b085f0417/docs/semantics/tail-call-optimization.md#usage)

> Enso does not currently perform automatic tail call detection and defers the
optimization decisions to the user. To mark a function call as a tail call, the
`@Tail_Call` annotation must be used.

This behavior is in place to prevent _megamorphic dispatch_ as:
- reported by #1217 
- implemented by #1219 

E.g. the problem isn't in detecting _tail call optimization possibilities_, but in **reducing them to** those that really **make a sense**. Classical approach:
- detect recursion
- when recursion is deep enough replace next call with `TailCallException`
- recursion is _only detected in interpreter_
- in a single thread (or via `ThreadLocal`) count how many times an `EnsoRootNode` is entered

Alternative approach:
- avoid _megamorphic dispatch_ by splitting the `catch (TailCallException)` site
- for each `throw TailCallException`  location generate a unique ID (make it a compilation constant)
- make sure the `catch` location is expanded according to this unique ID to build normal _polymorphic dispatch cache_

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #10956 
- duplicates benchmarks
   - the same code is executed _with_ and _without_ `@Tail_Call`
- automatically detects _too deeply recursive_ invocations
- and enabled _tail call invocation_ for them

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [x] engine benchmarks are OK
- [x] standard library benchmarks are OK

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java [hunk 1]
```diff
@@ -157,8 +157,10 @@ private Object doCall(
       State state,
       Object[] arguments) {
     return switch (getTailStatus()) {
-      case TAIL_DIRECT -> directCall.executeCall(frame, function, callerInfo, state, arguments);
-      case TAIL_LOOP -> throw new TailCallException(function, callerInfo, arguments);
+      case TAIL_DIRECT, // -> directCall.executeCall(frame, function, callerInfo, state, arguments);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java]: - the commit aad4b85d38c646fb8b0d035907b27f0ffe8e2e62 is an attempt to _gently revert_ #1219
   - basically it is inserting `@Tail_Call` annotation everywhere it makes sense
   - that should work, should it not?
- so we can see what was the _megamorphic behavior_ reported by #1217 that had to be fixed
- however the revert isn't working
   - the [enso runtime won't even run](https://github.com/enso-org/enso/actions/runs/23861663703/job/69569724551#step:10:2088)
   - can't find basic symbols on objects
- I am not yet sure what's going on...

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java]: Let's start from basics again:
```
sbt:runtime-benchmarks> benchOnly CallableBenchmarks
Benchmark                                    Mode  Cnt    Score    Error  Units
benchSumTCOfromCall                          avgt    5  749,231 ± 71,350  ms/op
benchSumTCOmethodCall                        avgt    5  410,419 ± 22,373  ms/op
benchSumTCOmethodCallWithDefaultedArguments  avgt    5  395,680 ± 20,531  ms/op
benchSumTCOmethodCallWithNamedArguments      avgt    5  400,371 ± 19,671  ms/op
```
is the basic result of TCO related benchmark from this branch. It is **indeed slow** the `develop` branch runs at:
```
Benchmark                                                       Mode  Cnt   Score   Error  Units
benchSumTCOfromCall                          avgt    5  75,386 ± 1,417  ms/op
benchSumTCOmethodCall                        avgt    5  75,965 ± 3,086  ms/op
benchSumTCOmethodCallWithDefaultedArguments  avgt    5  85,326 ± 6,681  ms/op
benchSumTCOmethodCallWithNamedArguments      avgt    5  75,170 ± 2,196  ms/op
```

File: engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java [hunk 2]
```diff
@@ -42,7 +51,10 @@ public class CallableBenchmarks {
   private static final String SUM_TCO_METHOD_CALL_CODE =
 """
 summator = acc -> current ->
-    if current == 0 then acc else @Tail_Call summator (acc + current) (current - 1)
+    if current == 0 then acc else
+        s = acc + current
+        c = current - 1
+        @Tail_Call summator s c
```
Comment (JaroslavTulach) [inline engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java:57]: @Akirathan pointed out that these refactorings might influence benchmarks. Let's [run them again](https://github.com/enso-org/enso/actions/runs/24352791591) to verify the state after 23bf009f76836cc2bdb48b765bcb04e53a022ccc. Expected result:
- benchmarks with `WithTailCall` suffix should be as fast as their original versions without the suffix
- benchmarks without the suffix shall be slower or even crash
- necessary fixes for automatic `@Tail_Call` detection will come tomorrow

If the expectations aren't met the changes to those `SUM_...CODE` blocks can be reverted. They were meant just to simplify orientation in IGV.

Btw. [one more run](https://github.com/enso-org/enso/actions/runs/24353106231) with  e510469 failed. Another [engine bench run](https://github.com/enso-org/enso/actions/runs/24388351161) with 0d6509c

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java]: - with 0d6509c I have following results locally
```
Benchmark                                                Score    Error  Units
benchSumTCOfromCall                                      71,632 ±  7,940  ms/op
benchSumTCOfromCallWithTailCall                          74,268 ± 10,342  ms/op
benchSumTCOmethodCall                                    77,010 ± 15,595  ms/op
benchSumTCOmethodCallWithDefaultedArguments              72,061 ±  3,377  ms/op
benchSumTCOmethodCallWithDefaultedArgumentsWithTailCall  68,628 ±  0,750  ms/op
benchSumTCOmethodCallWithNamedArguments                  69,425 ±  2,434  ms/op
benchSumTCOmethodCallWithNamedArgumentsWithTailCall      69,752 ±  0,438  ms/op
benchSumTCOmethodCallWithTailCall                        73,485 ±  4,974  ms/op
```
- verifying  with [engine bench run](https://github.com/enso-org/enso/actions/runs/24388351161)

**Review by jdunkerley — APPROVED** [review]

File: test/Base_Tests/src/Semantic/Error_Spec.enso [hunk 3]
```diff
@@ -186,10 +186,12 @@ add_specs suite_builder =
 
         group_builder.specify "Panic.rethrow with Dataflow_Stack_Trace enabled" <|
             deep_error n:Integer = if n <= 0 then Error.throw "Here is an error" else
-                deep_error n-1
+                x = deep_error n-1
+                x+1
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Semantic/Error_Spec.enso:190]: The need to capture `x` return value and return some other value is a demonstration of the success of automatic tail call optimization! Without these additional operations the `deep_xyz` call gets optimized and the [stack is one and not 21](https://github.com/enso-org/enso/actions/runs/24388186613/job/71228159138?pr=14933#step:14:1146):
```
Prior to #14480 the depth of Error.throw was ignored altogether
Expecting depth of 21, but was 1
``` 
If `x` is an error, then the execution will return the error as `x+1` will still yield an error. In case of `deep_throw` the panic is propagated and `x+1` code is skipped.

File: engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java:57]: These benchmark changes don't seem to have any effect on the benchmark results. Let's keep them for easier IGVing.

**Comment by JaroslavTulach** [comment]
- Engine benchmarks are perfectly fine with this PR!
- the same code **with** or **without** `@Tail_Call` 
- runs at the same speed in all TCO benchmarks!

TCO

**Comment by JaroslavTulach** [comment]
Some standard library benchmarks may get improved. For example Cross_Tab seems to indicate some improvements:

Cross_Tab

Maybe Table_Aggregate:

Table_Aggregate

but clearly there are no regressions - which was the biggest reason why `@Tail_Call` had to be introduced. E.g. all's working well.
