### PR TITLE
Fix visualization closing when cmd shortcut is pressed

### LINKED ISSUE #7457: Pressing `Cmd` is closing the visualization
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Hovering over visualization and pressing `Cmd` is causing visualization to hide when the cursor position change (move away from the visualization).

### Expected behaviour

`Cmd` should not hide the visualization

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 1.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #7457 

The issue was caused by the FRP logic that assumed we wanted to close the preview even if it wasn't opened in the first place.

https://github.com/enso-org/enso/assets/6566674/ceb4996b-c878-4ff1-8bca-7d2a0b817769

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node.rs [hunk 1]
```diff
@@ -785,6 +785,8 @@ impl Node {
         frp::extend! { network
             output_hover <- model.output.on_port_hover.map(|s| s.is_on());
             visualization_hover <- bool(&model.visualization.on_event::<mouse::Out>(), &model.visualization.on_event::<mouse::Over>());
+            is_preview <- visualization.view_state.map(|s| s.is_preview());
+            visualization_hover <- visualization_hover.gate(&is_preview);
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/node.rs]: I would rename `visualization_hover` to `preview_hover`.

**Review by farmaazon — APPROVED** [review]

File: app/gui/view/graph-editor/src/component/node.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/view/graph-editor/src/component/node.rs]: Done!

**Comment by vitvakatu** [comment]
I find the fix trivial, tested myself. Merging without QA.
