### PR TITLE
Get config from Cloud Config endpoint.

### LINKED ISSUE #14700: "Failed to start watching hybrid project"
Call to `api/watcher` returns an error:  "Request is missing search parameter apiUrl."

Regression introduced in https://github.com/enso-org/enso/pull/14526

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes https://github.com/enso-org/cloud-v2/issues/2280
Fixes #14700 

Contains also a bit of refactoring:
* The configuration is loaded in route guard - this way we display "Loading" screen while waiting. But because of that, `App.vue` cannot contain any code depending on config (use sessions, backends, etc).
* Moved LoadingScreen from react to vue.

Testing as in the issue description: use ENSO_IDE_API_URL env variable to set another endpoint (for example staging taken from `.env.staging`).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/providers/config.ts [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  const remoteConfig = useQuery<RemoteConfig>({
+    queryKey: ['config', remoteConfigUrl],
+    queryFn: ({ queryKey: [_, url] }) =>
+      fetch(`${url}/${CONFIGURATION_PATH}`).then((response) => response.json()),
+  })
+
+  watch(
+    () => remoteConfig.data.value?.ENSO_IDE_ENVIRONMENT,
+    (env) => {
+      console.log('Loaded config:', env)
```
Comment (vitvakatu) [inline app/gui/src/providers/config.ts:54]: It this a leftover debug code?

File: app/electron-client/src/backend.ts [hunk 2]
```diff
@@ -15,6 +16,7 @@ export async function createRemoteBackend() {
   if (API_URL == null) {
     throw new Error('API_URL is not set in the GUI config.')
   }
+  const config = await (await fetch(`${API_URL}/${CONFIGURATION_PATH}`)).json()
```
Comment (vitvakatu) [inline app/electron-client/src/backend.ts:19]: What happens if it fails?

File: app/gui/src/providers/config.ts [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    },
+    { flush: 'sync', immediate: true },
+  )
+
+  watch(
+    () => remoteConfig.data.value?.ENSO_IDE_API_URL,
```
Comment (vitvakatu) [inline app/gui/src/providers/config.ts:60]: This is actually unfortunate — if something happens before remote config loads, we never get any sentry notifications at all.

Comment (farmaazon) [reply app/gui/src/providers/config.ts:60]: No, the sentry is still initialized in entryPoint.

Here we only update tracing info, so the traces from cloud will be matched with the frontend calls.

File: app/electron-client/src/backend.ts (hunk 2 above)
Comment (farmaazon) [reply app/electron-client/src/backend.ts:19]: Exception is thrown, and headless execution fails (this code is used only in headless execution AFAIK)

File: app/gui/src/providers/config.ts (hunk 1 above)
Comment (farmaazon) [reply app/gui/src/providers/config.ts:54]: No, I assume it's quite useful to see in what actual environment the program runs.

**Review by vitvakatu — APPROVED** [review]

File: app/gui/src/components/LoadingScreen.vue [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+const SPINNER_SIZE_PX = 64
+
+const text = useText()
+const message = computed(() => text.getText('loadingAppMessage'))
+</script>
+
+<template>
+  <div
+    className="grid h-screen w-screen place-items-center text-primary"
```
Comment (vitvakatu) [inline app/gui/src/components/LoadingScreen.vue]:
```suggestion
    class="grid h-screen w-screen place-items-center text-primary"
```

File: app/gui/src/providers/config.ts [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+
+export type ConfigStore = ReturnType<typeof createConfigStore>
+
+function createConfigStore() {
+  const remoteConfigUrl = $config.API_URL ?? 'https://api.cloud.enso.org'
+
+  const remoteConfig = useQuery<RemoteConfig>({
+    queryKey: ['config', remoteConfigUrl],
+    queryFn: ({ queryKey: [_, url] }) =>
+      fetch(`${url}/${CONFIGURATION_PATH}`).then((response) => response.json()),
```
Comment (vitvakatu) [inline app/gui/src/providers/config.ts]: Let's check the response status before parsing it as JSON. We have a risk of getting `{ error: 'Config request failed' }` as our configuration. Even better — we can use `zod` to validate the config.

File: app/gui/src/authentication/service.ts [hunk 6]
```diff
@@ -115,23 +118,35 @@ export interface AuthService {
...
   const amplifyConfig = loadAmplifyConfig(
     console,
+    toRef(config, 'remoteConfig'),
     enableDeepLinks.value,
     (url) => void router.push(url),
   )
-  const cognito = new Cognito(console, enableDeepLinks.value, amplifyConfig)
+  const cognito = computed<Cognito | undefined>((oldValue) => {
+    if (oldValue != undefined) {
+      console.error('Remote config changed, but cannot update once initialized Cognito client.')
```
Comment (vitvakatu) [inline app/gui/src/authentication/service.ts:131]: This error will be printed even if config didn't meaningfully change (because the object instance is compared by reference).

**Review by vitvakatu — APPROVED** [review]

File: app/gui/src/authentication/service.ts (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/authentication/service.ts:131]: It's a bit hard to make better comparison, because we read many fields from config, and if I would list them here again, it would be quite bugprone.

Comment (vitvakatu) [reply app/gui/src/authentication/service.ts:131]: Yeah, I also don't think we can do much here.

**Review by jdunkerley — APPROVED** [review]
