### PR TITLE
Check type of `self` in static dispatch

### LINKED ISSUE #8706: Internal IR representation 'leaked' in stack trace of a dataflow error thrown from a suspended argument with default value
```
from Standard.Base import all

main =
    r = [].find (>0)
    IO.println r.get_stack_trace_text
```
prints
```
        at <enso> <default::Vector.find::Name.Literal(name = if_missing, isMethod = false, location = Some(IdentifiedLocation[location=Location[start=13071, end=13081], uuid=None]), passData = MetadataStorage[], diagnostics = DiagnosticStorage(diagnostics = List()), id = fee33391-2ebd-417a-9d3b-09d7708643e0)>(Internal)
```

We can see that the location contains a long-form text representation of the `if_missing` default argument. This makes the stack trace harder to read, if not to say a bit 'ugly'.

I think the expected behaviour would be something like:
```
        at <enso> <default::Vector.find::if_missing>(Internal)
```

### LINKED ISSUE #8805: Only allow the correct type to be used for `self` in the static method call syntax
A discussion during today's standup led me to try discussing this suggestion.

## Expectations

When I'm declaring member methods on a type, I **definitely** expect `self` within those methods to have that type:

```
type My_Type
    Ctor_A x
    Ctor_B x y

    sum self = case self of
        My_Type.Ctor_A x -> x
        My_Type.Ctor_B x y -> x + y

    my_method self z =
        self.sum + z
```

Within `sum`, I definitely expect that `self` has type `My_Type`, so that I know that my `case-of` statement covering the 2 constructors of it is definitely exhaustive.

Within `my_method`, I definitely expect that `self` has type `My_Type`, so that I know I can safely call the other method `sum` on it.

## Unexpected reality

We have static syntax for calling member methods, which allows us to replace `x.my_method 200` with `My_Type.my_method x 200`.

This syntax allows us to kind-of 'manually' specify the `self` parameter to the method, by referring to it statically.

However, it does not enforce that such-specified `self` has the correct type. Thus the following program:
```
from Standard.Base import all

type My_Type
    Ctor_A x
    Ctor_B x y

    sum self = case self of
        My_Type.Ctor_A x -> x
        My_Type.Ctor_B x y -> x + y

    my_method self z =
        self.sum + z

    simple_method self = self.x+1000

type Other_Type
    Value x

main =
    o = Other_Type.Value 23

    IO.println <| My_Type.simple_method o
    IO.println <| Panic.recover Any <| My_Type.my_method o 200
    IO.println <| Panic.recover Any <| My_Type.sum o
```
will yield
```
1023
(Error: (No_Such_Method.Error (Other_Type.Value 23) UnresolvedSymbol<sum>))
(Error: (Inexhaustive_Pattern_Match.Error (Other_Type.Value 23)))
```

The `simple_method` will _just work_, because `Other_Type` provides all it needs - a getter `x`. The other 2 methods however, will break in wonderful (read: harder to debug) ways somewhere within the internals of the implementation.

As @JaroslavTulach pointed out, this basically rules out the ability to infer `self : My_Type` inside of any of these methods, because as shown in this example, the `self` may be whatever type we put there. 

This defeats almost all of our type checking on member methods (which constitute most of Enso libraries). If I don't know the type of `self`, I cannot statically infer the type of any methods called on `self` as well. Thus if a member method relies on other member methods/fields, I cannot really perform type inference within it. And lots of methods _do_ refer to others in such a way.

I don't think this is good, so I'd suggest to change that.

## Proposal

Let's enforce the type of `self` by **checking** it during the static-syntax dispatch.

To keep sanity of our code, I think we need to ensure that `self` is what the developer expects it to be. The proposal is to add a check that will only allow the correct type within the static dispatch.

That is `My_Type.sum (My_Type.Ctor_A 2)` will happily work, however `My_Type.sum (Other_Type.Value 3)` will raise a `Type_Error`.

Then the behaviour of the program I pasted above would be following:
```
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
```

All these invocations would fail, because we cannot call a `My_Type` member method on a non-`My_Type` instance, even (ab)using the static call syntax.

I think this is the right thing to do, because then, within those member methods, we can safely assume that `self` is of the expected type. This is sane both for the developer and for the type system.

## Consequences of the change

I'm not aware of any _problematic_ consequences of this change. However, I may be missing something regarding the expected semantics of the static-syntax for member methods. If so, let's discuss.

The only usage of this pattern that I know of currently is within `Array.enso` where we dispatch statically the methods defined on `Vector` with the `Array` as their `self` parameter, to re-use the `Vector`'s implementation of these methods. This is a neat trick, but I don't think it's a thing that we really need at all, so I'd suggest to refactor it ([an alternative has already been suggested](https://github.com/orgs/enso-org/discussions/6216#discussioncomment-5579906)). We can move the common methods to be static methods on `Array_Like_Helpers` that take a `array_like` parameter (what used to be `self`). Then we can change the invocations to be:
```diff
-Array.insert self at=self.length item=Nothing = Vector.insert self at item
+Array.insert self at=self.length item=Nothing = Array_Like_Helpers.insert self at item
```

```[tasklist]
### Tasks
- [ ] Fix [staticWithRFirstAndZSecondNoConversionHappens](https://github.com/enso-org/enso/pull/8779/files#r1463856968) test
- [ ] Implement conversions for `self` to fix [staticWithRFirstArgumentIsConverted](https://github.com/enso-org/enso/pull/8779/files#r1463859288) test
```

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Fixes #8805 
- also btw. fixes #8706

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] Enable `*BinaryDispatchTest.staticWithRFirst*` tests
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala [hunk 1]
```diff
@@ -2254,7 +2254,7 @@ class IrToTruffle(
               moduleScope,
               defaultExpression,
               null,
-              s"<default::$scopeName::${arg.name}>",
+              s"<default::$scopeName::${arg.name.showCode()}>",
```
Comment (radeusgd) [inline engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:2283]: fix for https://github.com/enso-org/enso/issues/8706

TODO: add test

Comment (radeusgd) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:2283]: added

File: engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala [hunk 2]
```diff
@@ -208,5 +208,25 @@ class DataflowErrorsTest extends InterpreterTest {
...
+          |
+          |fn x ~y=(Error.throw My_Error.Value) =
+          |    if x == 0 then 0 else y
+          |
+          |main =
+          |    IO.println (fn 1).get_stack_trace_text
+          |""".stripMargin
+      eval(code)
+      consumeOut should contain(
+        "        at <enso> <default::Test.fn::y>(Test:7:10-35)"
```
Comment (radeusgd) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala]: The reported location checked by this test used to be:
```diff
-        at <enso> <default::Test.fn::Name.Literal(name = y, isMethod = false, location = Some(IdentifiedLocation[location=Location[start=89, end=90], uuid=None]), passData = MetadataStorage[], diagnostics = DiagnosticStorage(diagnostics = List()), id = null)>(Internal)
+        at <enso> <default::Test.fn::y>(Test:7:10-35)
```

1. the name was wrongly too long displaying IR internals
2. the location was `Internal` as it was not set correctly

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 3]
```diff
@@ -573,6 +612,46 @@ mul self (other : V) = V.Val self.a*other.a
...
+    assertEquals(1024, convertible.asInt());
+
+    try {
+      var invalid_static_call =
+          module.invokeMember(MethodNames.Module.EVAL_EXPRESSION, "static_inconvertible");
+      fail("Expecting an exception, not: " + invalid_static_call);
+    } catch (PolyglotException e) {
+      assertTypeError("`self`", "My_Type", "Inconvertible_Type", e.getMessage());
+    }
+  }
```
Comment (radeusgd) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: This test also ensures that not only values of requested type but also values _convertible_ to it are supported, if they go through the conversion.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 4]
```diff
@@ -573,6 +612,46 @@ mul self (other : V) = V.Val self.a*other.a
...
+    static_convertible = My_Type.f (Convertible_Type.A 23) 1000
+    static_inconvertible = My_Type.f (Inconvertible_Type.B 23) 1000
+    """,
+                uri.getAuthority())
+            .uri(uri)
+            .buildLiteral();
+
+    var module = ctx.eval(src);
+    var convertible = module.invokeMember(MethodNames.Module.EVAL_EXPRESSION, "static_convertible");
+    assertEquals(1024, convertible.asInt());
```
Comment (radeusgd) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: We see that the value is `1024` not `1023`, meaning that the conversion has been applied.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 5]
```diff
@@ -398,6 +398,45 @@ public void runtimeCheckOfAscribedLocalMethodSignature() throws Exception {
...
+
+    var static_call = module.invokeMember(MethodNames.Module.EVAL_EXPRESSION, "static_call");
+    assertEquals("Static call", 123, static_call.asInt());
+
+    try {
+      var invalid_static_call =
+          module.invokeMember(MethodNames.Module.EVAL_EXPRESSION, "invalid_static_call");
+      fail("Expecting an exception, not: " + invalid_static_call);
+    } catch (PolyglotException e) {
+      assertTypeError("`self`", "My_Type", "Other_Type", e.getMessage());
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: OK, the test looks fine.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: Probably better to turn this note into `assertEquals("messgage", ...)` message.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala [hunk 6]
```diff
@@ -100,19 +100,27 @@ case object MethodDefinitions extends IRPass {
           case Some(Resolution(ResolvedType(_, tp)))
               if canGenerateStaticWrappers(tp) =>
             val dup = method.duplicate()
+            // This is the self argument that will receive the `SelfType.type` value upon dispatch, it is added to avoid modifying the dispatch mechanism.
+            val fakeModuleSelfArg = DefinitionArgument.Specified(
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala]: Calling the argument `fake` is a bit scary. Maybe `synthetic`?

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala [hunk 7]
```diff
@@ -127,11 +135,43 @@ case object MethodDefinitions extends IRPass {
...
+        case (selfArg @ DefinitionArgument.Specified(
+              Name.Self(_, _, _, _),
+              _,
+              _,
+              _,
+              _,
+              _,
+              _
+            )) :: rest =>
+          selfArg.copy(ascribedType = Some(typ)) :: rest
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala]: I was expecting fix in the `IrToTruffle` rather than in the IR passes. Probably because I am more comfortable with the Truffle nodes than the IR...

**Review by JaroslavTulach — APPROVED** [review]
Tests seems to correctly request the desired behavior. The implementation is at surprising (to me) place, but it works and that's what counts.

**Comment by JaroslavTulach** [comment]
@radeusgd, you will need to stop delegating from `Array` to `Vector` methods statically: https://github.com/enso-org/enso/actions/runs/7660354279/job/20877478960?pr=8867#step:10:2883 and move the shared static implementations to `ArrayLikeHelpers.enso`.


However that's all good - it demonstrates your check really detects violations!

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Check type of `self` in static dispatch · enso-org/enso@6760aed</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: Ok, will do

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala (hunk 6 above)
Comment (radeusgd) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala]: Fair point, I will rename it

**Comment by radeusgd** [comment]
> @radeusgd, you will need to stop delegating from `Array` to `Vector` methods statically: [enso-org/enso/actions/runs/7660354279/job/20877478960?pr=8867#step:10:2883](https://github.com/enso-org/enso/actions/runs/7660354279/job/20877478960?pr=8867#step:10:2883) and move the shared static implementations to `ArrayLikeHelpers.enso`.
> 
> However that's all good - it demonstrates your check really detects violations!
> 
> >  GitHub**[Check type of `self` in static dispatch · enso-org/enso@6760aed](https://github.com/enso-org/enso)**Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.

oh, right, I completely forgot about it! Of course, so I will need to do a slight refactor to make this work. I will see to it when I have a moment.

**Comment by JaroslavTulach** [comment]
Once you merge with `develop`, please enable:
```
[info] Test org.enso.interpreter.test.BinaryDispatchTest.staticWithRFirstArgumentIsConverted ignored
[info] Test org.enso.interpreter.test.BinaryDispatchTest.staticWithRFirstAndZSecondNoConversionHappens ignored
```

**Comment by radeusgd** [comment]
> Once you merge with `develop`, please enable:
> 
> ```
> [info] Test org.enso.interpreter.test.BinaryDispatchTest.staticWithRFirstArgumentIsConverted ignored
> [info] Test org.enso.interpreter.test.BinaryDispatchTest.staticWithRFirstAndZSecondNoConversionHappens ignored
> ```

I enabled them and they seem to be passing 🙂

**Comment by radeusgd** [comment]
Benchmarks trial 1
https://github.com/enso-org/enso/actions/runs/7818863156
https://github.com/enso-org/enso/actions/runs/7818865699

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@e8f5afb</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@e8f5afb</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by radeusgd** [comment]
Stdlib Run after fixing remaining warning tests: https://github.com/enso-org/enso/actions/runs/7841630104

And one after changing to the simpler approach suggested by @jdunkerley (instead of extracting common vector/array logic, we just use the Vector methods by converting array by `Vector.from_polyglot_array` (O(1))), and some cleanups that should not influence benchmarks (just small compiler code refactor): https://github.com/enso-org/enso/actions/runs/7842961320

I was unable to run engine benchmarks as these have been failing for a while, I imagine it would be best to try checking these as well before merging this PR...

**Review by 4e6 — APPROVED** [review]

**Comment by radeusgd** [comment]
@JaroslavTulach I re-requested your review as I have added some additional changes and thought you may want to see them.

My initial solution was a bit of a hack apparently - I assumed the type I define methods on is always in scope so I can just refer to that type by its regular name. The test https://github.com/enso-org/enso/blob/wip/radeusgd/8805-self-type-check/test/Base_Tests/src/Semantic/Names_Spec.enso#L8-L12 showed me that we may define methods on a name that is not in the current scope - by extension methods on a type accessed by a (not-necessarily-fully) qualified name.

I then tried just using fully qualified names for that - but that failed due to a bug #8997. 

### Towards the `Self` Type

As I did not see a very immediate solution, instead I relied on the `Self` type. The concept was partially to introduced to Enso - we have IR for it although I think it is not fully supported in the parser yet, e.g. even with these changes, the following program:
```
type My_Type
    Value x y

    swap : Self
    swap self -> Self = Self.Value self.y self.x

main =
    (My_Type.Value 1 2).swap
```
still fails with
```
X:\NBO\repr\test4.enso:4:12: error: The name `Self` could not be found.
    4 |     swap : Self
      |            ^~~~
X:\NBO\repr\test4.enso:5:18: error: The name `Self` could not be found.
    5 |     swap self -> Self = Self.Value self.y self.x
      |                  ^~~~
Aborting due to 2 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

I did not aspire to implement the full scope of the Self type in this PR, as that far exceeded the scope of this PR and is not of immediate use anyway.

Instead, I added as much of self type resolution as was needed to get the type checks working.
Most of it happens in the `TypeNames` pass: https://github.com/enso-org/enso/blob/wip/radeusgd/8805-self-type-check/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala#L83-L120

Now, I am able to annotate the `self` argument in methods with the `Name.Self` IR which is resolved to the 'current' type and thus checked exactly in the way that we want.

### Refactoring Array

My first approach was as we discussed - I've split the logic of vector operations into `Array_Like_Helpers` (that do not have any type ascriptions so they don't check the types) and made both `Array` and `Vector` delegate to these.

Later, James suggested that a simpler solution may be possible and so I've tried it b40b5ef6477fdbf38144e189d012bd4a01b3f8aa - I'm converting the array (O(1) op) into a Vector and then passing it to the vector operations in the same way as before - but thanks to the conversion the operation now satisfies the type check.

I guess I could even try to avoid the static call convention altogether and just call the method on the converted vector... I will try that.

I'm not sure if I remember the rationale for that (@jdunkerley please correct me if I quote you wrongly), but I think it was to simplify the traces for Vector operations which are most common and could be a pain with debugging.

### Benchmarking

I wanted to see if there's any performance impact.

I ran benchmarks both with the `Array_Like_Helpers` version (run [7841630104](https://github.com/enso-org/enso/actions/runs/7841630104)) and the to-vector-conversion (run [7842961320](https://github.com/enso-org/enso/actions/runs/7842961320)).

I could not yet run engine benchmarks [as they are currently broken](https://discord.com/channels/@me/948519891961544714/1204665097562366002). Hopefully to be fixed by #8975. I guess I'd try to run the benchmarks again once that PR is merged.

Still, without #7927 it is relatively hard to be able to compare the benchmarks - apart from clear outliers, often it is hard to say if the difference is significant or just a random deviation within the usual variance.

Looking as much as I could at the results, it seems that the results fit in the usual benchmark variance, with either of the array-like-helper or vector-conversion approaches sometime being faster and sometime slower - no clear winners here.

**Comment by radeusgd** [comment]
> I guess I could even try to avoid the static call convention altogether and just call the method on the converted vector... I will try that.

Done in [28a4e34](https://github.com/enso-org/enso/pull/8867/commits/28a4e342b2a4760687ded840a43b9126038e70bc).
Another benchmark scheduled at https://github.com/enso-org/enso/actions/runs/7857761166

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@28a4e34</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso [hunk 8]
```diff
@@ -159,7 +159,7 @@ type Array
          If a `Range`, the selection is specified by two indices, from and to.
     @range Index_Sub_Range.default_widget
     take : (Index_Sub_Range | Range | Integer) -> Vector Any
-    take self range=(Index_Sub_Range.First 1) = Vector.take self range
+    take self range=(Index_Sub_Range.First 1) = (Vector.from_polyglot_array self).take range
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso]: What's the effect of `Vector.from_polyglot_array` wrapping on engine benchmarks? I am afraid some of them might slow down.

Wrapping all `Array` objects by `from_polyglot_array` isn't the expected fix. I was expecting all the static methods to move into `Array_Like_Helpers` and **both** the `Array` and `Vector` instance methods to delegate to the `Array_Like_Helpers` implementations.

`Array_Like_Helpers` solution would directly operate on the vector/array. Wrapping by `from_polyglot_array` creates a proxy object in memory. All the code accessing it needs to unwrap the original object and then perform the original operation. E.g. we allocate more memory on heap, we need bigger Truffle ASTs (not that we'd measure any such aspect) than `Array_Like_Helpers` solution would require.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
I don't like the `from_polyglot_array` wrapping. If _engine benchmarks_ are OK, then maybe... but the right fix was supposed to be to move the implementations into `Array_Like_Helpers`.

> rationale ... was to simplify the traces for Vector operations

I see. I still continue to like `Array_Like_Helpers` solution more.

**Comment by JaroslavTulach** [comment]
> I ran benchmarks both with the `Array_Like_Helpers` version (run [7841630104](https://github.com/enso-org/enso/actions/runs/7841630104)) and the to-vector-conversion (run [7842961320](https://github.com/enso-org/enso/actions/runs/7842961320)).

Those are StdLib benchmarks, not engine benchmarks! We need to compare the engine benchmarks (which are currently broken, being addressed by @Akirathan as part of his #8975). The engine benchmarks contain microbenchmarks comparing various _array-like_ implementations. They will tell us if the `from_polyglot_proxy` implementation is fast or not.

**Comment by Akirathan** [comment]
Fix of the engine benchmarks is tracked in #9026 with the highest priority.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso (hunk 8 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso]: I did implement the `Array_Like_Helpers` solution in the first place, but @jdunkerley suggested the wrapping one might be better.

If we decide to go back to `Array_Like_Helpers`, it's just the matter of reverting the commit [a8171168789d7252478cc334d82b2e29e51ee024](https://github.com/enso-org/enso/commit/a8171168789d7252478cc334d82b2e29e51ee024)

I guess either way we should wait for the fix of engine benchmarks and see how both solutions compare there.

I'm happy to go for either of these.

**Comment by radeusgd** [comment]
> > I ran benchmarks both with the `Array_Like_Helpers` version (run [7841630104](https://github.com/enso-org/enso/actions/runs/7841630104)) and the to-vector-conversion (run [7842961320](https://github.com/enso-org/enso/actions/runs/7842961320)).
> 
> Those are StdLib benchmarks, not engine benchmarks! We need to compare the engine benchmarks (which are currently broken, being addressed by @Akirathan as part of his #8975). The engine benchmarks contain microbenchmarks comparing various _array-like_ implementations. They will tell us if the `from_polyglot_proxy` implementation is fast or not.

As noted below, I ran what I was able to run, but yes I also want to see the engine benchmarks comparison once they are fixed.

**Comment by radeusgd** [comment]
_(Engine)_ benchmark run on current branch state: https://github.com/enso-org/enso/actions/runs/7886066367

Run after reverting the `Array_Like_Helpers` approach: https://github.com/enso-org/enso/actions/runs/7887354689

**Review by JaroslavTulach — APPROVED** [review]
I've just [checked the benchmarks](https://github.com/enso-org/enso/actions/runs/7886066367) and I see no slowdown. I still maintain slight preference in favor of `Array_Like_Helpers` approach, but approving even the _proxy way_.

**Review by GregoryTravis — APPROVED** [review]
