### PR TITLE
Speedup DataflowError.withDefaultTrace

### LINKED ISSUE #10702: stdlib benchmarks regression: DataflowError with stack
There are some big regressions in `*...Map_Id_All_Errors` benchmarks. In some cases, even 500%.

Screenshots:
image

image

image

https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html#org_enso_benchmarks_generated_Map_Error_Benchmark_Vector_ignore_Map_Id_All_Errors

-------------------

- Good commit: https://github.com/enso-org/enso/commit/f31c084f43c33e0d988d1bf2f02d5c93bd1f5db9
- Bad commit: https://github.com/enso-org/enso/commit/f0e9616d39d4fc24c8074bd4681fed182d0ede00
- Range: https://github.com/enso-org/enso/compare/f31c084f43c33e0d988d1bf2f02d5c93bd1f5db9...f0e9616d39d4fc24c8074bd4681fed182d0ede00

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #10702

### Pull Request Description

Improves the speed of `ExecutionEnvironment.hasContextEnabled`.

### Important Notes

Local speedup of `Map_Error_Benchmark_Vector_ignore.Map_Id_All_Errors` benchmark is roughly ???.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [X] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 1]
```diff
@@ -49,16 +50,19 @@ public final class DataflowError extends AbstractTruffleException implements Ens
...
+  public static DataflowError withDefaultTrace(
+      State state, Object payload, Node location, BranchProfile attachFullStackTraceProfile) {
     assert payload != null;
     boolean attachFullStackTrace =
         state == null
             || EnsoContext.get(location)
                 .getExecutionEnvironment()
                 .hasContextEnabled("Dataflow_Stack_Trace");
     if (attachFullStackTrace) {
+      attachFullStackTraceProfile.enter();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: This line fixes the problem? That is surprising:
- I can imagine it makes the compilation graph way smaller.
- I have no idea why it should make anything faster?

Are we getting bailout on compilation? Is the compilation still in progress when benchmarking?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 2]
```diff
@@ -49,16 +50,19 @@ public final class DataflowError extends AbstractTruffleException implements Ens
...
       var result = new DataflowError(payload, UNLIMITED_STACK_TRACE, location);
       TruffleStackTrace.fillIn(result);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java:67]: `fillIn` is behind `@TruffleBoundary` - maybe we can just wrap the whole `if true` branch into a method and put it being `@TruffleBoundary`.

The size of the compiler graph will be as reduced as now and we will not have to modify all the places around to pass in `BranchProfile`.

**Review by JaroslavTulach — APPROVED** [review]
Consider `@TruffleBoundary`. If you want to keep `BranchProfile` approach, then it might be  better to use the _nodes approach_ - e.g. replace the `withDefaultTrace` method by `class DataflowError.WithDefaultTraceNode` and keep the profile hidden in it.

Anyway you are building on top of 
- #11075

and that code is clearly wrong. I like the speed up, but maybe we should fix the broken code first and only then measure the speed.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 3]
```diff
@@ -49,16 +50,19 @@ public final class DataflowError extends AbstractTruffleException implements Ens
...
+   * @param attachFullStackTraceProfile
    * @return a new dataflow error
    */
-  public static DataflowError withDefaultTrace(State state, Object payload, Node location) {
+  public static DataflowError withDefaultTrace(
+      State state, Object payload, Node location, BranchProfile attachFullStackTraceProfile) {
     assert payload != null;
     boolean attachFullStackTrace =
         state == null
             || EnsoContext.get(location)
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: Ops, this code will have to be rewritten according to https://github.com/enso-org/enso/pull/11075#pullrequestreview-2314364236 and https://github.com/enso-org/enso/pull/11075#discussion_r1766136152!

**Comment by Akirathan** [comment]
Waiting for @4e6.

**Review by JaroslavTulach — DISMISSED** [review]
I am afraid right now this [PR isn't ready to be merged](https://github.com/enso-org/enso/pull/11153/files#r1771291604). Moreover it needs to be adjusted to changes by Dmitry.

**Comment by Akirathan** [comment]
> https://github.com/enso-org/enso/pull/11153#discussion_r1771291604 : This line fixes the problem? That is surprising

You are right. My [initial commit](https://github.com/enso-org/enso/pull/11153/commits/0569585fef790f35e2ca527f266dbde78c640df1) is clearly wrong. I will revert it, rebase on latest develop, and start over.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: Outdated - the implementation is now different.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 4]
```diff
@@ -53,11 +54,14 @@ public final class DataflowError extends AbstractTruffleException implements Ens
    */
   public static DataflowError withDefaultTrace(State state, Object payload, Node location) {
     assert payload != null;
+    var ensoCtx = EnsoContext.get(location);
+    var dataflowStacktraceCtx = ensoCtx.getBuiltins().context().getDataflowStackTrace();
+    // dataflowStacktraceCtx is a compiler constant, because it is a constructor of a builtin
+    // type.
+    CompilerAsserts.partialEvaluationConstant(dataflowStacktraceCtx);
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: This helps with the performance. The compiler is most probably not able to determine that `dataflowStacktraceCtx` is actually a constant (reference to a constructor of a builtin type).

**Comment by Akirathan** [comment]
With the changes in https://github.com/enso-org/enso/commit/243847c3ab36605142c03d3ce37b6113165c9314 I managed to get the performance of `Map_Error_Benchmark_Vector_ignore.Map_Id_All_Errors` from **1.179 ± 0.648** to **0.981 ± 0.073** (note that the standard deviation is also much lower, which is a good thing as it suggests the score is more reliable). Since the execution environment itself cannot be treated as a constant, I'd say this is a reasonable gain for such a small modification.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 5]
```diff
@@ -108,4 +92,9 @@ public static ExecutionEnvironment forName(String name) {
         throw new IllegalArgumentException("Unsupported Execution Environment `" + name + "`");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Looks like there is a missing case for `dataflowStacktrace`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: > This helps with the performance.

That would be surprising. It is a `CompilerAsserts` - e.g. not a directive, but only an assert that something is true. E.g. either `dataflowStacktraceCtx` is constant or the compilation is going to fail. The fact whether it is constant or not isn't changed by the assert. The fact whether compilation goes or not is influenced by the assert.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 6]
```diff
@@ -53,49 +47,39 @@ public ExecutionEnvironment withContextDisabled(Atom context) {
...
-        keyFound = i;
-      }
-    }
-    String[] keys1;
-    Boolean[] permissions1;
-    if (keyFound != -1) {
-      keys1 = cloneArray(keys, new String[keys.length]);
-      permissions1 = cloneArray(permissions, new Boolean[keys.length]);
-      permissions1[keyFound] = value;
+    var contextBuiltin = EnsoContext.get(null).getBuiltins().context();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: It may be better to hide this into a node rather than ask for `get(null)`. A node like:
```java
class WithContextNode extends Node {
  public ExecutionEnvironment executeEnvironmentUpdate(
    ExecutionEnvironment current, Atom context, boolean enabled
  );
}
```

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 7]
```diff
@@ -53,49 +47,39 @@ public ExecutionEnvironment withContextDisabled(Atom context) {
...
-    } else {
-      return false;
+  /**
+   * Checks if the context is enabled in this execution environment.
+   *
+   * @param runtimeCtx Constructor of {@code Standard.Base.Runtime.Context} builtin type.
+   * @return {@code true} if the context is enabled in this execution environment.
+   */
+  public boolean hasContextEnabled(AtomConstructor runtimeCtx, EnsoContext ensoCtx) {
+    var contextBuiltin = ensoCtx.getBuiltins().context();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: This might better be a node `HasContextEnabledNode` as well.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 8]
```diff
@@ -53,49 +47,39 @@ public ExecutionEnvironment withContextDisabled(Atom context) {
...
+    if (runtimeCtx == contextBuiltin.getInput()) {
+      return permissions.input;
+    } else if (runtimeCtx == contextBuiltin.getOutput()) {
+      return permissions.output;
+    } else if (runtimeCtx == contextBuiltin.getDataflowStackTrace()) {
+      return permissions.dataflowStacktrace;
     }
+    throw CompilerDirectives.shouldNotReachHere(
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Better to use `ctx.raiseAssertionXyz` method, in my opinion.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 9]
```diff
@@ -53,49 +47,39 @@ public ExecutionEnvironment withContextDisabled(Atom context) {
...
-    Boolean[] permissions1;
-    if (keyFound != -1) {
-      keys1 = cloneArray(keys, new String[keys.length]);
-      permissions1 = cloneArray(permissions, new Boolean[keys.length]);
-      permissions1[keyFound] = value;
+    var contextBuiltin = EnsoContext.get(null).getBuiltins().context();
+    assert context.getConstructor().getType() == contextBuiltin.getType();
+    var ctor = context.getConstructor();
+    Permissions newPermissions;
+    if (ctor == contextBuiltin.getInput()) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: The use of `Permissions` seems promising. Consider _moving this code_ into the `Permissions` class itself.

**Review by JaroslavTulach — COMMENTED** [review]
The use of `Permissions` seems to go the right way.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Execution environment handling implemented via nodes in dd25a6f256918a675898e23ca95172ab3d5d463a

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 7 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Execution environment handling implemented via nodes in dd25a6f256918a675898e23ca95172ab3d5d463a

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 8 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Fixed in dd25a6f256918a675898e23ca95172ab3d5d463a

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 9 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Refactored in dd25a6f256918a675898e23ca95172ab3d5d463a

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 5 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Fixed in dd25a6f256918a675898e23ca95172ab3d5d463a

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+   * @param runtimeCtxCtor Constructor of {@code Standard.Base.Runtime.Context}.
+   */
+  public abstract boolean executeHasContextEnabled(
+      ExecutionEnvironment executionEnvironment, AtomConstructor runtimeCtxCtor);
+
+  @Specialization(guards = "executionEnvironment == cachedEnv", limit = "3")
+  boolean doIt(
+      ExecutionEnvironment executionEnvironment,
+      AtomConstructor runtimeCtxCtor,
+      @Cached("executionEnvironment") ExecutionEnvironment cachedEnv) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java:38]: With cached `ExecutionEnvironment`, the performance improved from **1.179 ± 0.648 to 0.218 ± 0.014**.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java [hunk 11]
```diff
@@ -22,80 +18,48 @@ public class ExecutionEnvironment {
...
+      newPermissions =
+          new ContextPermissions(value, permissions.output(), permissions.dataflowStacktrace());
+    } else if (ctor == contextBuiltin.getOutput()) {
+      newPermissions =
+          new ContextPermissions(permissions.input(), value, permissions.dataflowStacktrace());
+    } else if (ctor == contextBuiltin.getDataflowStackTrace()) {
+      newPermissions = new ContextPermissions(permissions.input(), permissions.output(), value);
     } else {
-      return false;
+      throw CompilerDirectives.shouldNotReachHere("Unknown context `" + ctor.getName() + "`");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: `raiseAssertionError` please.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java [hunk 12]
```diff
@@ -0,0 +1,4 @@
+package org.enso.interpreter.runtime.state;
+
+/** Fields correspond to the constructors of {@code Standard.Base.Runtime.Context} builtin type. */
+record ContextPermissions(boolean input, boolean output, boolean dataflowStacktrace) {}
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java:4]: Such a simple class can certainly remain encapsulated in its only user - e.g. in `ExecutionEnvironment`.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java:4]: When I [asked for refactoring](https://github.com/enso-org/enso/pull/11153/files#r1803027966) I was talking about moving the code, not making the simple `record` its own `.java` file.

**Review by JaroslavTulach — APPROVED** [review]
The idea of replacing array with record with three fields looks fine. If [there is speed up](https://github.com/enso-org/enso/pull/11153/files#r1804911834), then we can probably integrate.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+    var ensoCtx = EnsoContext.get(this);
+    var contextBuiltin = ensoCtx.getBuiltins().context();
+    if (runtimeCtxCtor == contextBuiltin.getInput()) {
+      return cachedEnv.permissions.input();
+    } else if (runtimeCtxCtor == contextBuiltin.getOutput()) {
+      return cachedEnv.permissions.output();
+    } else if (runtimeCtxCtor == contextBuiltin.getDataflowStackTrace()) {
+      return cachedEnv.permissions.dataflowStacktrace();
+    } else {
+      throw ensoCtx.raiseAssertionPanic(this, "Unknown context: " + runtimeCtxCtor, null);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java:59]: String concatenation cannot be on fast path: https://github.com/enso-org/enso/actions/runs/11387183014/job/31745369546?pr=11153#step:7:1631

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java (hunk 11 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java]: Done in ee54f74d6b7d4d230c63e90f2fc83b41e955a401

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java (hunk 12 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java:4]: It is also used by `WithContextNode`. So we need to keep it package private.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java (hunk 13 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java:59]: Thanks for spotting this. Added `trasnferToInterpreter` in d3f4c8c812728cf8b5a60a91f664f9aba32a93e3

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java:59]: OK. No need to strive for performance in this case.
