### PR TITLE
Fixes for Language Server sync server

### LINKED ISSUE #8398: New IDE Backend Crash Opening Project
Using newest develop build as of 2023-11-17:

```
new session with ws://127.0.0.1:58020
LS connection initialized.
file:///C:/Repos/Enso/ide/app/gui2/vite.config.ts.timestamp-1701085461541-09ccfa0650ed3.mjs:332
        throw new LsRpcError(new RemoteRpcError(remoteError.data), method, params);
              ^

LsRpcError: Language server request 'text/openFile' failed.
    at LanguageServer.request (file:///C:/Repos/Enso/ide/app/gui2/vite.config.ts.timestamp-1701085461541-09ccfa0650ed3.mjs:332:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: RemoteRpcError {
    code: 1005,
    message: 'IO operation timeout',
    data: undefined
  },
  request: 'text/openFile',
  params: {
    path: {
      rootId: 'e5bb4720-184b-4025-9965-3b02556e5665
',
      segments: [ 'src', 'Main.enso' ]
    }
  }
}

Node.js v18.14.1
npm ERR! Lifecycle script `dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: enso-gui2@0.1.0
npm ERR!   at location: C:\Repos\Enso\ide\app\gui2
```

[Enso_Getting_Started_3.tar.gz](https://github.com/enso-org/enso/files/13473950/Enso_Getting_Started_3.tar.gz)

Crashes every time on mine.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes #8398

### Important Notes
- The original error caused by a failing `text/openFile` (`openTextFile`) is still present, but (seemingly?) harder to repro now

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] T~~he documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/shared/retry.ts [hunk 1]
```diff
@@ -18,6 +18,9 @@ export interface BackoffOptions<E> {
   ) => boolean | void
   /** Called right before returning. */
   onSuccess?: (retryCount: number) => void
+  /** Called right before throwing an error. Note that `onBeforeRetry` is called for all tries
+   * before the last one. */
```
Comment (farmaazon) [inline app/gui2/shared/retry.ts]: What does it mean, "all tries before last one"? From the name, I'd rather assume that the last one will also have called `onBeforeRetry` before.

File: app/gui2/shared/retry.ts [hunk 2]
```diff
@@ -49,15 +60,55 @@ export async function exponentialBackoff<T, E>(
...
     }
   }
 }
 
-export const onBeforeRetry: (message: string) => BackoffOptions<any>['onBeforeRetry'] =
-  (message) => (error, retryCount, maxRetries, delay) => {
-    console.error(message + ` (${retryCount}/${maxRetries} retries), retrying after ${delay}ms...`)
+export function onBeforeRetry(
+  description: string,
+): NonNullable<BackoffOptions<any>['onBeforeRetry']> {
```
Comment (farmaazon) [inline app/gui2/shared/retry.ts]: I know it's an old code, but I think it's a bit cryptic. I assume this is just a sort of "default" callback? The fact that the name collide with option name does not help. Same for `onFailure` below.

File: app/gui2/shared/retry.ts [hunk 3]
```diff
@@ -49,15 +60,55 @@ export async function exponentialBackoff<T, E>(
...
+      'Successfully ' +
+        description +
+        ` after ${retryCount} ${retryCount === 1 ? 'failure' : 'failures'}.`,
+    )
+  }
+}
+
+/** @param successDescription Should be in past tense, without an initial capital letter.
+ * @param successDescription Should be in present tense, without an initial capital letter. */
+export function exponentialBackoffMessages(successDescription: string, errorDescription: string) {
```
Comment (farmaazon) [inline app/gui2/shared/retry.ts]: Same @param name. And I would rename it to something like `printingCallbacks`.

File: app/gui2/shared/languageServer.ts [hunk 4]
```diff
@@ -131,7 +131,8 @@ export class LanguageServer extends ObservableV2<Notifications> {
         console.log(`LS [${uuid}] ${method}:`)
         console.dir(params)
       }
-      return await this.client.request({ method, params }, RPC_TIMEOUT_MS)
+      const ret = await this.client.request({ method, params }, RPC_TIMEOUT_MS)
+      return ret
```
Comment (farmaazon) [inline app/gui2/shared/languageServer.ts]: This was for debugging? I think we should not keep it.

File: app/gui2/shared/languageServer.ts [hunk 5]
```diff
@@ -402,27 +403,30 @@ export class LanguageServer extends ObservableV2<Notifications> {
...
+          })
         })
-      })
-      await retry(() => this.acquireReceivesTreeUpdates({ rootId, segments }))
-      if (!running) return
-    })()
-    return () => {
-      running = false
-      this.off('file/event', callback)
+        if (!running) return
```
Comment (farmaazon) [inline app/gui2/shared/languageServer.ts]: I know this is an older code, but why do we need this line? We return right after it anyway, don't we?

File: app/gui2/src/components/GraphEditor/upload.ts [hunk 6]
```diff
@@ -149,38 +149,43 @@ export class Uploader {
...
+      throw error
     }
   }
 
   private async pickUniqueName(suggestedName: string): Promise<string> {
     const files = await this.rpc.listFiles(this.dataDirPath())
     const existingNames = new Set(files.paths.map((path) => path.name))
-    const [stem, maybeExtension] = splitFilename(suggestedName)
-    const extension = maybeExtension ?? ''
+    const { name, extension = '' } = splitFilename(suggestedName)
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/upload.ts]: `stem` was better, because it was more precise. See https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem or https://en.cppreference.com/w/cpp/filesystem/path/stem

File: app/gui2/src/components/GraphEditor/upload.ts [hunk 7]
```diff
@@ -190,14 +195,12 @@ export class Uploader {
...
-function splitFilename(filename: string): [string, string | null] {
-  const dotIndex = filename.lastIndexOf('.')
-
+function splitFilename(fileName: string): { name: string; extension?: string } {
+  const dotIndex = fileName.lastIndexOf('.')
   if (dotIndex !== -1 && dotIndex !== 0) {
-    const stem = filename.substring(0, dotIndex)
-    const extension = filename.substring(dotIndex + 1)
-    return [stem, extension]
+    const name = fileName.substring(0, dotIndex)
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/upload.ts]: same here.

File: app/gui2/src/stores/visualization/index.ts [hunk 8]
```diff
@@ -206,12 +206,18 @@ export const useVisualizationStore = defineStore('visualization', () => {
...
       console.error('Could not load custom visualizations: Project directory not found.')
       return
     }
-    ls.watchFiles(projectRoot, [customVisualizationsDirectory], onFileEvent, rpcWithRetries)
+    try {
+      await ls.watchFiles(projectRoot, [customVisualizationsDirectory], onFileEvent, rpcWithRetries)
+        .promise
+    } catch {
+      // Ignored. It is very likely that the `visualizations/` directory is not present, however
+      // there would be a race condition if the existence of `visualizations` is checked first.
```
Comment (farmaazon) [inline app/gui2/src/stores/visualization/index.ts]: We should check if the error says it's not present, and fail in other cases (or print the error log). And even if this is an error we want to ignore, I would print a console.log, just in case.

File: app/gui2/ydoc-server/languageServerSession.ts [hunk 9]
```diff
@@ -64,76 +67,128 @@ export class LanguageServerSession extends ObservableV2<Events> {
...
+  }
+
+  private restartClient() {
+    // `this.client` WILL be undefined on the first call.
+    this.client?.close()
+    this.client = createOpenRPCClient(this.url)
+    // `this.ls` WILL be undefined on the first call.
+    this.ls?.destroy()
+    this.ls = new LanguageServer(this.client)
+    this.connection = undefined
```
Comment (farmaazon) [inline app/gui2/ydoc-server/languageServerSession.ts]: We could just make `setupClient` function with code from line 96 onwards. Then, the constructor could just initialize `client` and `ls` as here, and `restartClient` would do closing/destroying, reinitializing and call `setupClient`. This way we would avoid exclamation marks without being too repetitive.

File: app/gui2/shared/retry.ts (hunk 3 above)
Comment (somebody1234) [reply app/gui2/shared/retry.ts]: hmm... these aren't callbacks though

File: app/gui2/shared/retry.ts (hunk 2 above)
Comment (somebody1234) [reply app/gui2/shared/retry.ts]: this is actually new code, but yeah. i guess i'll rename to `defaultOnBeforeRetry` for now? i don't really have any good ideas for this one

File: app/gui2/shared/retry.ts (hunk 1 above)
Comment (somebody1234) [reply app/gui2/shared/retry.ts]: i guess the docs are confusing. this is called on the final retry, when there is no next retry (and so there is no delay). alternatively we can simply call `onBeforeRetry` with a `delay === null` and modify the interface as appropriate

File: app/gui2/shared/languageServer.ts (hunk 5 above)
Comment (somebody1234) [reply app/gui2/shared/languageServer.ts]: yeah... no clue what's up here, will remove it.

File: app/gui2/shared/retry.ts (hunk 3 above)
Comment (farmaazon) [reply app/gui2/shared/retry.ts]: > In [computer programming](https://en.wikipedia.org/wiki/Computer_programming), a callback or callback function is any reference to [executable code](https://en.wikipedia.org/wiki/Executable_code) that is passed as an [argument](https://en.wikipedia.org/wiki/Argument_(computer_science)) to another piece of code

So here we make functions, and set them as options for "retry" function. What is it if not callback? Or I misunderstand this code greatly.

Comment (somebody1234) [reply app/gui2/shared/retry.ts]: ahhhh, you mean rename the function, not the parameters

File: app/gui2/shared/retry.ts [hunk 10]
```diff
@@ -18,8 +18,9 @@ export interface BackoffOptions<E> {
   ) => boolean | void
   /** Called right before returning. */
   onSuccess?: (retryCount: number) => void
-  /** Called right before throwing an error. Note that `onBeforeRetry` is called for all tries
-   * before the last one. */
+  /** Called on the final retry, right before throwing an error.
+   * Note that `onBeforeRetry` is *not* called on the final retry, as there is nothing after the
```
Comment (farmaazon) [inline app/gui2/shared/retry.ts:21]: By `on the final retry` you mean `after final retry`? For me, `after` is more precise.

**Review by farmaazon — APPROVED** [review]

File: app/gui2/shared/languageServer.ts [hunk 11]
```diff
@@ -167,8 +167,8 @@ export class LanguageServer extends ObservableV2<Notifications> {
   }
 
   /** [Documentation](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#textopenfile) */
-  openTextFile(path: Path): Promise<response.OpenTextFile> {
-    return this.request('text/openFile', { path })
+  openTextFile(path: Path, meta?: string): Promise<response.OpenTextFile> {
+    return this.request('text/openFile', { path, meta })
```
Comment (Frizi) [inline app/gui2/shared/languageServer.ts]: There is no `meta` parameter in the linked documentation. Is this something new? If so, let's adjust the docs too.

File: app/gui2/shared/languageServerTypes.ts [hunk 12]
```diff
@@ -386,9 +386,7 @@ export namespace response {
     contentRoots: ContentRoot[]
   }
 
-  export interface FileContents {
```
Comment (Frizi) [inline app/gui2/shared/languageServerTypes.ts:389]: This was the `FileReadResult` type, but improperly named. According to docs it does have a nested `contents` field. So it was probably allright, bar the incorrect name.

https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#result-5

File: app/gui2/shared/retry.ts (hunk 3 above)
Comment (farmaazon) [reply app/gui2/shared/retry.ts]: Oh, my fault, my sentence wasn't precise. Yes, `it` meant `function`, not `parameter`.

**Review by Frizi — APPROVED** [review]

File: app/gui2/shared/languageServerTypes.ts (hunk 12 above)
Comment (somebody1234) [reply app/gui2/shared/languageServerTypes.ts:389]: actually i discovered this was *in*correct, when i was implementing this:

https://github.com/enso-org/enso/blob/2d2c9c9261030de504edf7a976fd36daea6b9715/app/gui2/ydoc-server/languageServerSession.ts#L585-L596

on that note... i'm not 100% sure about this. it doesn't affect the fix if it's removed - it's entirely possible that I've misunderstood what `reload` is supposed to do

File: app/gui2/shared/languageServer.ts (hunk 11 above)
Comment (somebody1234) [reply app/gui2/shared/languageServer.ts]: oh, nice catch... this was added for debugging :sweat_smile:

File: app/gui2/shared/languageServerTypes.ts (hunk 12 above)
Comment (somebody1234) [reply app/gui2/shared/languageServerTypes.ts:389]: note that there *is* a `FileContents` type: https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#filecontents

also note that `*Result` types were basically only added so that the `Result` interfaces are valid TS code - in GUI2 these should correspond to `response.*`
