### PR TITLE
PathProgressBodyHandler does not return immediately

### LINKED ISSUE #9221: HTTPDownloader fails to install new engine
Attempt to create a new project in IDE fails.

Regression introduced by #8953

Logs from project-manager:
```
Enso Project Manager
Version:    0.0.0-dev
Built with: scala-2.13.11 for GraalVM 21.0.2
Built from: wip/akirathan/fix-downloader @ 97033a2ff4367ff2191f777d5f03b5eaaf379734
Built on:   Linux (amd64)

[DEBUG] [2024-02-29T11:39:53+01:00] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerRegistry] started (org.enso.projectmanager.infrastructure.languageserver.LanguageServerRegistry@6807b98d)
[DEBUG] [2024-02-29T11:39:53+01:00] [org.enso.projectmanager.infrastructure.languageserver.ShutdownHookActivator] started (org.enso.projectmanager.infrastructure.languageserver.ShutdownHookActivator@5456bf08)
[DEBUG] [2024-02-29T11:39:53+01:00] [org.enso.projectmanager.infrastructure.languageserver.ShutdownHookActivator] now watched by Actor[akka://project-manager/system/eventStreamUnsubscriber-1#1273140297]
[INFO] [2024-02-29T11:39:53+01:00] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.jsonrpc.MessageHandlerSupervisor] started (org.enso.jsonrpc.MessageHandlerSupervisor@52a9291a)
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.jsonrpc.MessageHandler] started (org.enso.jsonrpc.MessageHandler@30ee003a)
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.jsonrpc.MessageHandlerSupervisor] now supervising Actor[akka://project-manager/user/message-handler-supervisor-c3a6b096-be99-479b-b157-10cb09f7e724/message-handler-69f9bc77-63f0-482a-a64f-3ca0f6223a6f#-116489347]
[INFO] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [69f9bc77-63f0-482a-a64f-3ca0f6223a6f]
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.protocol.ClientController] started (org.enso.projectmanager.protocol.ClientController@7afc6a86)
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.jsonrpc.MessageHandlerSupervisor] now watched by Actor[akka://project-manager/system/Materializers/StreamSupervisor-0/$$d#-1850246566]
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.protocol.ClientController] now supervising Actor[akka://project-manager/user/manager-client-controller-69f9bc77-63f0-482a-a64f-3ca0f6223a6f/request-handler-ProjectList-a2888a28-895e-44f0-8bc0-2c94ff3cf26a#1352221172]
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.protocol.ClientController] now supervising Actor[akka://project-manager/user/manager-client-controller-69f9bc77-63f0-482a-a64f-3ca0f6223a6f/request-handler-ProjectList-ed3701d7-d64d-49ff-a5c5-17849c5e4bb7#-2118321855]
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.requesthandler.ProjectListHandler] started (org.enso.projectmanager.requesthandler.ProjectListHandler@65e5e8e8)
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.requesthandler.ProjectListHandler] started (org.enso.projectmanager.requesthandler.ProjectListHandler@d93a0fe)
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.requesthandler.ProjectListHandler] stopped
[DEBUG] [2024-02-29T11:39:57+01:00] [org.enso.projectmanager.requesthandler.ProjectListHandler] stopped
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.protocol.ClientController] now supervising Actor[akka://project-manager/user/manager-client-controller-69f9bc77-63f0-482a-a64f-3ca0f6223a6f/request-handler-ProjectCreate-c4c9594f-1fd2-4526-98b5-fa939af7088b#290794730]
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] started (org.enso.projectmanager.requesthandler.ProjectCreateHandler@58b14ee2)
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Creating project [New Project 2, e481f00c-b28d-4ffa-be12-0294d78ca25d, None].
[INFO] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Created project with actual name [New Project 2].
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Project name [New Project 2] validated by [org.enso.projectmanager.service.validation.ProjectNameValidator@410bba2a].
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Checked if the project name [New Project 2] exists in [org.enso.projectmanager.infrastructure.repository.ProjectFileRepository@3107a596].
[DEBUG] [2024-02-29T11:40:00+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Found a path [/home/pavel/enso/projects/NewProject2] for a new project [New Project 2, e481f00c-b28d-4ffa-be12-0294d78ca25d].
[WARN] [2024-02-29T11:40:00+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Ignoring the minimum required engine version check [2023.2.1-nightly.2023.11.2] for the development version [0.0.0-dev].
[INFO] [2024-02-29T11:40:00+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [0.0.0-dev] found.
[INFO] [2024-02-29T11:40:00+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] GraalVM runtime [GraalVM 23.1.2 Java 21.0.2] not found.
[INFO] [2024-02-29T11:40:01+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Installing GraalVM runtime [GraalVM 23.1.2 Java 21.0.2].
[DEBUG] [2024-02-29T11:40:01+01:00] [org.enso.downloader.http.HTTPDownload] Fetching [https://api.github.com/repos/graalvm/graalvm-ce-builds/releases/tags/jdk-21.0.2].
[DEBUG] [2024-02-29T11:40:01+01:00] [org.enso.downloader.http.HTTPDownload] Downloading [https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz] to [/tmp/enso-install-runtime9055653635292685988/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz].
[DEBUG] [2024-02-29T11:40:01+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Downloading [graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz].
[DEBUG] [2024-02-29T11:40:02+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Extracting [/tmp/enso-install-runtime9055653635292685988/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz].
[DEBUG] [2024-02-29T11:40:02+01:00] [org.enso.downloader.archive.Archive] Opening [/tmp/enso-install-runtime9055653635292685988/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz].
[ERROR] [2024-02-29T11:40:02+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] Request ProjectCreate with Number(2) failed due to ProjectCreateFailed(null).
[DEBUG] [2024-02-29T11:40:02+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] stopped
[WARN] [2024-02-29T11:40:02+01:00] [org.enso.jsonrpc.MessageHandlerSupervisor] Resuming after error.
java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:319)
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:302)
	at io.circe.Json$JString.foldWith(Json.scala:369)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:369)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:302)
	at io.circe.Json$JObject.foldWith(Json.scala:431)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:369)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:302)
	at io.circe.Json$JObject.foldWith(Json.scala:431)
	at io.circe.Printer.unsafePrintToAppendable(Printer.scala:229)
	at io.circe.Printer.print(Printer.scala:197)
	at io.circe.Json.noSpaces(Json.scala:122)
	at org.enso.jsonrpc.JsonProtocol$.encode(JsonProtocol.scala:166)
	at org.enso.jsonrpc.MessageHandler.org$enso$jsonrpc$MessageHandler$$issueResponseError(MessageHandler.scala:74)
	at org.enso.jsonrpc.MessageHandler$$anonfun$org$enso$jsonrpc$MessageHandler$$established$1.applyOrElse(MessageHandler.scala:49)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.enso.jsonrpc.MessageHandler.aroundReceive(MessageHandler.scala:13)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[WARN] [2024-02-29T11:40:02+01:00] [akka.actor.OneForOneStrategy] Cannot invoke "String.length()" because "value" is null
[INFO] [2024-02-29T11:40:02+01:00] [akka.actor.LocalActorRef] Message [org.enso.cli.task.ProgressNotification$TaskUpdate] to Actor[akka://project-manager/user/manager-client-controller-69f9bc77-63f0-482a-a64f-3ca0f6223a6f/request-handler-ProjectCreate-c4c9594f-1fd2-4526-98b5-fa939af7088b#290794730] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://project-manager/user/manager-client-controller-69f9bc77-63f0-482a-a64f-3ca0f6223a6f/request-handler-ProjectCreate-c4c9594f-1fd2-4526-98b5-fa939af7088b#290794730] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

Logs from IDE:
```
Error creating new project: Input is not in the .gz format
```

## Reproducer
The simplest reproducer to try to download a new engine via launcher:
- `sbt launcher/assembly`
- Make sure there is no engine version `2024.1.1-nightly.2024.2.29` in `java -jar launcher.jar --launcher-log-level trace list`.
  - If there is, remove it from `$HOME/.local/share/enso/dist`
- Try to download the newest engine with: `java -jar launcher.jar --launcher-log-level trace install engine 2024.1.1-nightly.2024.2.29`
This fails with:
```
[INFO] [2024-02-29T11:35:16+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2024.1.1-nightly.2024.2.29] not found.
[INFO] [2024-02-29T11:35:16+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Installing the engine [2024.1.1-nightly.2024.2.29].
[DEBUG] [2024-02-29T11:35:16+01:00] [org.enso.downloader.http.HTTPDownload] Fetching [https://api.github.com/repos/enso-org/enso/releases/tags/2024.1.1-nightly.2024.2.29].
[DEBUG] [2024-02-29T11:35:17+01:00] [org.enso.downloader.http.HTTPDownload] Fetching [https://github.com/enso-org/enso/releases/download/2024.1.1-nightly.2024.2.29/manifest.yaml].
[WARN] [2024-02-29T11:35:18+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Ignoring the minimum required engine version check [2023.2.1-nightly.2023.11.2] for the development version [0.0.0-dev].
[DEBUG] [2024-02-29T11:35:18+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Downloading packages to [/tmp/enso-install7410196257632002202].
[DEBUG] [2024-02-29T11:35:18+01:00] [org.enso.downloader.http.HTTPDownload] Downloading [https://github.com/enso-org/enso/releases/download/2024.1.1-nightly.2024.2.29/enso-engine-2024.1.1-nightly.2024.2.29-linux-amd64.tar.gz] to [/tmp/enso-install7410196257632002202/enso-engine-2024.1.1-nightly.2024.2.29-linux-amd64.tar.gz].
[INFO] [2024-02-29T11:35:18+01:00] [launcher] Downloading enso-engine-2024.1.1-nightly.2024.2.29-linux-amd64.tar.gz.
[INFO] [2024-02-29T11:35:19+01:00] [launcher] Extracting the engine.
[DEBUG] [2024-02-29T11:35:19+01:00] [org.enso.downloader.archive.Archive] Opening [/tmp/enso-install7410196257632002202/enso-engine-2024.1.1-nightly.2024.2.29-linux-amd64.tar.gz].
[ERROR] [2024-02-29T11:35:19+01:00] [org.enso.launcher.cli.Main] A fatal error has occurred: null
[ERROR] [2024-02-29T11:35:19+01:00] [org.enso.launcher.cli.Main] A fatal error has occurred: null
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #9221

### Pull Request Description

Fixes downloading of files. It used to fail because it returned almost immediately. Also fixes progress reporting when fetching a String.

### Important Notes

Tested by removing appropriate engine and runtime from `$HOME/.local/share/enso` and with manually running:
```
java -jar launcher.jar --launcher-log-level trace install engine 2024.1.1-nightly.2024.2.29
```

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/scala/downloader/src/main/java/org/enso/downloader/http/PathProgressBodyHandler.java [hunk 1]
```diff
@@ -110,7 +125,7 @@ public void onComplete() {
 
     @Override
     public CompletionStage<Path> getBody() {
-      return CompletableFuture.completedFuture(destination);
+      return result;
```
Comment (Akirathan) [inline lib/scala/downloader/src/main/java/org/enso/downloader/http/PathProgressBodyHandler.java:128]: This was the gist of the problem. This handler claimed that the download was finished (returned `CompletableFuture.completedFuture` almost immediately.

File: lib/scala/downloader/src/main/java/org/enso/downloader/http/StringProgressBodyHandler.java [hunk 2]
```diff
@@ -64,7 +64,8 @@ public void onSubscribe(Flow.Subscription subscription) {
     public void onNext(List<ByteBuffer> items) {
       for (ByteBuffer item : items) {
         var len = item.remaining();
-        progress.reportProgress(len, total == null ? Option.empty() : Some.apply(total));
+        downloaded += len;
+        progress.reportProgress(downloaded, total == null ? Option.empty() : Some.apply(total));
```
Comment (JaroslavTulach) [inline lib/scala/downloader/src/main/java/org/enso/downloader/http/StringProgressBodyHandler.java]: Simplify to `Option.apply(total)`.

**Review by JaroslavTulach — APPROVED** [review]
Having an improved testing coverage would feel more comfortable.

**Comment by Akirathan** [comment]
> Having an improved testing coverage would feel more comfortable.

@JaroslavTulach  Test coverage improved in 0212393df873b6155cdb6bfd6bb28f20ee3376b6

File: lib/scala/downloader/src/main/java/org/enso/downloader/http/StringProgressBodyHandler.java (hunk 2 above)
Comment (Akirathan) [reply lib/scala/downloader/src/main/java/org/enso/downloader/http/StringProgressBodyHandler.java]: Done in c105401ef75381f88962811dba9cfd03f3171281
