### PR TITLE
Eager macro resolution.

### LINKED ISSUE #7691: Segmentation fault (presumably) when parsing Main.enso file
Using `2023.2.1-nightly.2023.8.30` I get:
```
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run Main.enso
Segmentation fault (core dumped)
```
Just before everything started to crash there was some external change in metadata and the IDE dropped layout of my nodes. As such my hypothesis is this is a bug in native part of the parser.

[Main.enso.gz](https://github.com/enso-org/enso/files/12472661/Main.enso.gz)

Removing the metadata section fixes the problem and my file can be executed again.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Resolve macros eagerly. Improves performance; allows parser to handle arbitrarily-long lines (fixes #7691).

### Important Notes

- A new utility, `lib/rust/parser/debug/tools/parse_all_enso_files.sh`, supports comparing ASTs parsed with different versions of the parser. This tool has been used to verify that this refactor doesn't change the result of parsing any standard library or test file.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/rust/parser/src/macros/built_in.rs [hunk 1]
```diff
@@ -62,14 +62,16 @@ fn register_import_macros(macros: &mut resolver::SegmentMap<'_>) {
     }
 }
 
-fn import_body(segments: NonEmptyVec<MatchedSegment>) -> syntax::Tree {
+fn import_body<'s>(
+    segments: NonEmptyVec<MatchedSegment<'s>>,
+    parser: &mut operator::Precedence<'s>,
```
Comment (farmaazon) [inline lib/rust/parser/src/macros/built_in.rs]: It looks strange that something of type `Precedence` is called `parser`. In other places, such argument is called `precedence`.

File: lib/rust/parser/src/macros/resolver.rs [hunk 2]
```diff
@@ -58,14 +57,16 @@ impl MacroMap {
...
+// === Context ===
+
 #[derive(Debug, PartialEq, Eq, Copy, Clone)]
 enum Context {
     Expression,
     Statement,
 }
 
 
-
```
Comment (farmaazon) [inline lib/rust/parser/src/macros/resolver.rs]: This line should remain AFAIK.

**Review by farmaazon — APPROVED** [review]
LGTM, I'm not a parser expert however (but who is besides @kazcw?)

**Comment by kazcw** [comment]
I'm going to skip QA because:
- A unit test covers an input previously exhibiting the bug.
- The `lib/rust/parser/debug/tools/parse_all_enso_files.sh` script has been used to verify that ASTs for all our `.enso` sources are unchanged by this PR.

File: lib/rust/parser/debug/tests/parse.rs [hunk 3]
```diff
@@ -1329,6 +1329,29 @@ fn skip() {
 
 
 
+// =========================
+// === Scalability Tests ===
```
Comment (JaroslavTulach) [inline lib/rust/parser/debug/tests/parse.rs:1333]: Great idea to have _scalability tests_.

File: lib/rust/parser/debug/tools/parse_all_enso_files.sh [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+# git checkout develop
+# ./lib/rust/parser/debug/tools/parse_all_enso_files.sh > develop.ast
+# diff develop.ast branch.ast
+
+set -e
+
+cargo build -p enso-parser-debug --bin enso-parser-debug
+
+ENSO_FILES=$(find distribution/ test/ -name '*.enso' -print | sort)
+for x in $ENSO_FILES; do echo -n "$x "; target/rust/debug/enso-parser-debug <$x; done
```
Comment (JaroslavTulach) [inline lib/rust/parser/debug/tools/parse_all_enso_files.sh:20]: Don't you want to make this part of CI?

**Review by JaroslavTulach — APPROVED** [review]
Can't comment on the actual code changes much, but the _scalability testing_ approach seems to prove the code changes are good.

File: lib/rust/parser/debug/tools/parse_all_enso_files.sh (hunk 4 above)
Comment (kazcw) [reply lib/rust/parser/debug/tools/parse_all_enso_files.sh:20]: That would be nice, but it's not trivial. The current simplistic implementation would fail any PR that modifies libs.
