### PR TITLE
Use TruffleLogger bound to the engine to prevent illegal usage

### LINKED ISSUE #8147: Using TruffleLogger outside of engine leads to crashes
As pointed out in https://github.com/enso-org/enso/pull/8014#discussion_r1351523293:

```diff
enso$ git diff
diff --git engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
index 8cb4b0b5c4..0b84019fd0 100644
--- engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
+++ engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
@@ -153,6 +153,8 @@ class ReentrantLocking(logger: TruffleLogger) extends Locking {
 
   /** @inheritdoc */
   override def acquireFileLock(file: File): Long = {
+    assertNotLocked(compilationLock, false, "wrong")
+    assertNotLocked(compilationLock, true, "wrong")
     // cannot have pendings lock as of EnsureCompiledJob.applyEdits
     assertNotLocked(
       pendingEditsLock,
$ sbt  runtime-with-instruments/test
```
and one gets:
```
java.lang.IllegalStateException: Thread using TruffleLogger has to have a current context or the TruffleLogger has to be bound to an engine., took 0.025 sec
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.noContext(TruffleLogger.java:1011)
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.isLoggable(TruffleLogger.java:993)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggableSlowPath(TruffleLogger.java:727)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggable(TruffleLogger.java:722)
[error]     at com.oracle.truffle.api.TruffleLogger.log(TruffleLogger.java:544)
[error]     at org.enso.interpreter.instrument.command.SynchronousCommand.execute(SynchronousCommand.scala:30)
[error]     at org.enso.interpreter.instrument.command.SynchronousCommand.execute(SynchronousCommand.scala:11)
[error]     at org.enso.interpreter.instrument.execution.CommandExecutionEngine.invoke(CommandExecutionEngine.scala:63)
[error]     at org.enso.interpreter.instrument.Handler.onMessage(Handler.scala:128)
[error]     at org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1(Handler.scala:66)
[error]     at org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1$adapted(Handler.scala:64)
[error]     at scala.Option.foreach(Option.scala:437)
[error]     at org.enso.interpreter.instrument.Endpoint.sendBinary(Handler.scala:64)
[error]     at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy.sendBinary(TruffleInstrument.java:1090)
[error]     at org.enso.interpreter.test.instrument.RuntimeServerEmulator.sendToRuntime(RuntimeServerEmulator.scala:53)
[error]     at org.enso.interpreter.test.instrument.RuntimeServerTest$TestContext.send(RuntimeServerTest.scala:94)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenFunctionBodyIsChanged(IncrementalUpdatesTest.java:202)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenFunctionBodyIsChangedBySettingValue(IncrementalUpdatesTest.java:150)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenTextIsChangedBySettingValue(IncrementalUpdatesTest.java:105)
```

Also noted similar problems when logging things in serializer. Can be simulated when problems occur in verbose mode.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Using a `TruffleLogger` in `SerializationManager` that is bound to the engine rather than the context prevents reaching an illegal state when using thread pools. 

Also cleaned up some tests for consistency. 

To verify the fix
```diff
--- a/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
+++ b/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
@@ -31,7 +31,7 @@ final class SerializationManager(compiler: Compiler) {
   import SerializationManager._
 
   /** The debug logging level. */
-  private val debugLogLevel = Level.FINE
+  private val debugLogLevel = Level.INFO
```
and run
`sbt:enso> runtime/test`

Closes #8147.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java [hunk 1]
```diff
@@ -115,6 +116,7 @@ private Context ensoContextForPackage(String name, File pkgFile, boolean disable
             .option(
                 RuntimeOptions.LANGUAGE_HOME_OVERRIDE,
                 Paths.get("../../distribution/component").toFile().getAbsolutePath())
+            .option(RuntimeOptions.LOG_LEVEL, Level.WARNING.getName())
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java:122]: I don't understand what is the idea of the fix? I don't see any change in the code, just in the tests. Thus the only idea I see is: _Increase logging level, so logging doesn't happen_. But I wanted the logging to happen when I faced the issue.

Comment (hubertp) [reply engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java:122]: Yes, this was only a _partial_ fix for some of the tests. It wasn't addressing the core of the problem. Now it does.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java [hunk 2]
```diff
@@ -40,14 +40,14 @@
...
-  private final TruffleLogger serializationManager;
+  private final TruffleLogger compilerLogger;
+  private final TruffleLogger serializationManagerLogger;
   private final RuntimeStubsGenerator stubsGenerator;
 
   TruffleCompilerContext(EnsoContext context) {
     this.context = context;
-    this.compiler = context.getLogger(Compiler.class);
-    this.serializationManager = context.getLogger(SerializationManager.class);
+    this.compilerLogger = context.getLogger(Compiler.class);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java]: I left this logger as-is as I haven't seen the same illegal state failures as with SerializationManager, potentially because (de-)serializationis is typically run in a separate thread. We could change it as well, I'm open for suggestions.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java]: I think we want to bound all loggers to engine. No need to have two `getLogger` and `getLoggerBoundToEngine` method.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 3]
```diff
@@ -774,6 +774,17 @@ public TruffleLogger getLogger(Class<?> klass) {
...
 
+  /**
+   * Gets a logger for the specified class that is bound to this engine.
+   * Such logger may then be safely used in threads defined in a thread-pool.
+   *
+   * @param clazz the class to name log entries with
+   * @return a new logger for the specified {@code path}
+   */
+  public TruffleLogger getLoggerBoundToEngine(Class<?> clazz) {
+    return environment.getLogger(clazz);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:775]: Let's just use this in the existing `getLogger` method without introducing a new one.

File: engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java [hunk 4]
```diff
@@ -28,6 +29,10 @@ public static void initEnsoContext() {
             Paths.get("../../distribution/component").toFile().getAbsolutePath()
         )
         .option(RuntimeOptions.STRICT_ERRORS, "false")
+        .option(
+                RuntimeOptions.LOG_LEVEL,
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java:33]: Why are these `LOG_LEVEL` changes needed?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 5]
```diff
@@ -774,6 +774,17 @@ public TruffleLogger getLogger(Class<?> klass) {
...
   }
 
+  /**
+   * Gets a logger for the specified class that is bound to this engine.
+   * Such logger may then be safely used in threads defined in a thread-pool.
+   *
+   * @param clazz the class to name log entries with
+   * @return a new logger for the specified {@code path}
+   */
+  public TruffleLogger getLoggerBoundToEngine(Class<?> clazz) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java]: Unrelated, but: Why not return `slf4j` logger from this method?

**Review by JaroslavTulach — COMMENTED** [review]
I don't see a reason to have `getLogger` and `getLoggerBoundToEngine` next to each other - especially when there is 1:1 mapping between `Engine` and `EnsoContext`.

File: engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java (hunk 4 above)
Comment (hubertp) [reply engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java:33]: Otherwise we rely on the parent logger to get the level, which is not obvious what it is. I also made sure that we no longer ignore the output in various places.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java (hunk 5 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java]: I tried **not** to use `slf4j` within runtime at all. To not tempt people to use it.

File: engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java:33]: Default configuration of `java.util.logging` is to log `Level.INFO` or higher to console. Not sure whether that applies to `TruffleLogger`, but I assume so, it was created with intention to mimic `java.util.logging`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java]: Using it as a simple facade over `TruffleLogger` would at least give us the same formatting of messages.

File: engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java [hunk 6]
```diff
@@ -38,7 +40,11 @@ public void initContext() {
             RuntimeOptions.LANGUAGE_HOME_OVERRIDE,
             Paths.get("../../distribution/component").toFile().getAbsolutePath()
         )
-        .logHandler(OutputStream.nullOutputStream())
+        .option(
+                RuntimeOptions.LOG_LEVEL,
+                Level.WARNING.getName()
+        )
+        .logHandler(System.err)
```
Comment (JaroslavTulach) [inline engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java:47]: Doesn't this pollute the `test` command output with a lot of debug messages? Ideally they should only be displayed when the test fails. There is no point in showing logged messages when the test succeeds, I think.

Comment (hubertp) [reply engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java:47]: Nope. I have not seen a lot of, if any, warnings being reported in our test suite.

File: engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java (hunk 4 above)
Comment (hubertp) [reply engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java:33]: That could be right, I wasn't able to verify it. I see no harm in specifying log level explicitly, other than being a bit more verbose. But if that's a dealbreaker for you, I can remove it.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:775]: I guess this is the core of the fix. It seems correct.

**Review by JaroslavTulach — APPROVED** [review]
Using `environment.getLogger(clazz)` seems like correct fix.

**Review by Akirathan — APPROVED** [review]
