### PR TITLE
Avoid _ after .

### LINKED ISSUE #7582: op1._ yields: Compiler Internal Error: Qualified names should not be present at codegen time
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When parsing columns in the table on the third node with `parse` the compiler error occurred:
```router.ts:62 [ERROR] app/gui/src/model/project/synchronized.rs:591 Execution failed in context ca4e82f0-e987-4ba2-9dce-d6f9265d37af. Error: Execution of function main failed (Compiler Internal Error: Qualified names should not be present at codegen time.)..```
and the node was missing values:
Zrzut ekranu 2023-08-15 o 08 10 06
After some time it recovers and it was possible to choose the proper column from the drop-down.

### Expected behaviour

The drop-down should work after appearing on the node.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

[20230815-055256-813-enso-project-manager.log](https://github.com/enso-org/enso/files/12341657/20230815-055256-813-enso-project-manager.log)

### Enso Version

nightly 15.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #7582 by generating a syntax error when there is `x._` - e.g. `_` after `.`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java [hunk 1]
```diff
@@ -27,6 +29,16 @@ public void unfinishedLiteral1() throws Exception {
     assertSingleSyntaxError(ir, IR$Error$Syntax$UnclosedTextLiteral$.MODULE$, "Unclosed text literal", 6, 28);
   }
 
+  @Test
+  public void dotUnderscore() throws Exception {
+    var ir = parse("""
+    run op =
+      op._
```
Comment (4e6) [inline engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java:36]: What happens if you write `op._.op`?

Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java:36]: That will yield the same error. `_` is only allowed at 1st segment, I think.

Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java:36]:
```ruby
t.enso:1:5: warning: Unused function argument op.
    1 | run op = op._.xDistribution 2s
      |     ^~
t.enso:1:13: error: Invalid use of _.
    1 | run op = op._.x
      |             ^
Aborting due to 1 errors and 1 warning
```

Comment (4e6) [reply engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java:36]: Let's add a test for this case as well

**Review by 4e6 — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java:36]: As you wish: 484c6d9
