### PR TITLE
Comment UI refinement

### LINKED ISSUE #9261: Component comments small fixes
```[tasklist]
### Tasks
- [x] Now that we have icons on the full wheel we need the ... option to expand the full wheel from the smaller one.
- [x] The comment icon is always visible when the small menu is open. It should only show when the full wheel is open.
- [ ] The comment widget shouldn't change height/font size when it is being edited
- [ ] There shouldn't be a rectangle when the comment widget is being edited
- [ ] Pressing enter when editing should exit edit mode (not add a new line)
- [ ] This one I think I got wrong in my original ticket, but now I can play with it I feel like you should be able to edit it just by clicking on it (without a CTRL modifier). In the same way you can edit a text widget.
```

### PR DESCRIPTION
**Pull request by kazcw**
- Eliminate edit mode:
  - Beginning edit does not change appearance
  - Edit text as rendered, not as formatted in code
  - Soft-wrap the editor
  - Click-to-edit sets cursor in editor
- Enter finishes edit
  - Shift+Enter inserts a newline
- Click begins edit regardless of Ctrl

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/GraphNodeComment.vue [hunk 1]
```diff
@@ -16,101 +15,141 @@ const emit = defineEmits<{
...
 })
 </script>
+<script lang="ts">
+export function rawTextToCooked(raw: string) {
+  return raw.replaceAll(/(?<!\n)\n(?!\n)/g, ' ').replaceAll(/\n(\n+)/g, '$1')
+}
+
+export function cookedTextToRaw(cooked: string) {
+  return cooked.replaceAll('\n', '\n\n')
+}
```
Comment (vitvakatu) [inline app/gui2/src/components/GraphEditor/GraphNodeComment.vue]: Could you please add little docs to explain what is the difference?

File: app/gui2/src/components/GraphEditor/GraphNodeComment.vue [hunk 2]
```diff
@@ -16,101 +15,148 @@ const emit = defineEmits<{
...
-    changes: textChangeToEdits(viewText, text).map(textEditToChangeSpec),
+    changes: textChangeToEdits(viewText, text.value).map(textEditToChangeSpec),
   })
 })
 
 watchEffect(() => {
-  if (contentElement.value && props.editing && !editor.value) startEdit()
+  if (!editor.value) return
+  if (props.editing) editor.value.focus()
+  else editor.value.contentDOM.blur()
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor/GraphNodeComment.vue:80]: This looks little strange as a `watchEffect`. Could this focus/blur be moved to the interaction methods? Or is there any reason for it being here in particular?

**Review by Frizi — APPROVED** [review]

File: app/gui2/src/components/GraphEditor/GraphNodeComment.vue (hunk 2 above)
Comment (kazcw) [reply app/gui2/src/components/GraphEditor/GraphNodeComment.vue:80]: @Frizi
Watching the prop ensures that focus/blur is updated when we begin/end editing for any reason, e.g:
- If the edit-comment menu icon is clicked, that sets the prop, so the comment is focused when editing begins
- There are various ways editing can be ended, some of them will set a new focus inherently but some don't; if there were any case where we missed unfocusing the comment, a weird state would result in which the app thinks the comment is not being edited but the user still sees a cursor.
