### PR TITLE
Fix Datalink inputs

### LINKED ISSUE #11370: Data Link modal: Missing fields of an optional entry wrongly highlighted red
The modal for editing data links now displays the widgets for optional fields.

An optional field may be a more complex entity - e.g. an object. Such object may contain required fields. 

If the optional field is 'enabled' (no longer greyed out, e.g. by clicking or partially filling in the data), such required fields are indeed required and should show up as red if empty.

image

### Expected behaviour

However, if the optional field is not enabled (meaning, it will be `null` in the JSON), then its required fields are expected to be missing and **should not** show up as read. 

### Actual behaviour

Currently, even if the field is disabled, the inner required fields are showing up as missing.

### Related

As one can see on the screenshot, it is not easy to see that the Username and Password fields are actually optional. Not only they currently have the (wrong) red border, but they are also in solid black colour. The only indicator that they are optional is the "Credentials" header that is in grey.

I don't think this is right. It suggests to the user that the credentials are required - but they are not.

I think the correct solution here would be to also grey-out all the inner fields of the 'complex' optional field. In the example above - if the 'Credentials' header is greyed out, its whole 'widget' containing Username and Password should also be greyed out. They should turn to solid color after clicking on 'Credentials' to enable the field, or after one of the Username/Password fields are filled-in by the user.

### LINKED ISSUE #11372: Data Link modal: widget for selecting Secret path opens automatically when a datalink preview is opened
Repro:
I just log-in to cloud and open a data link that contains secrets, and wait 1-3 seconds.

Then, _without clicking anything_, I get this:
image

### Actual behaviour

The path selector for the secret somehow opens up without any interactions.

### Expected behaviour

The preview of a data link should not open any widgets until I specifically interact with them. The path selector should only open once I click on that field.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix https://github.com/enso-org/enso/issues/11370
  - Disable validation for (and grey out) entries for children of disabled keys
- Fix https://github.com/enso-org/enso/issues/11372
  - Avoid opening `Autocomplete` dropdown automatically when `autoFocus` is not `true`
- Fix wrong default value being applied when editing a key that is currently absent

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~
- [x] ~~If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.~~

### CODE REVIEW

**Review by MrFlashAccount — APPROVED** [review]

**Comment by PabloBuchu** [comment]
1. If I type datalink name that already exists the modal is successfully submited but request ends with 400
2. Looks like for Postgres connectors all is now optional. I can create one with missing hostname, database name. Only port is required (similar to snowflake)
3. Can we make the red border around required attribute bit stronger? Is there enough space to also include something like "You need to provide URI" also we should change the validation text for name (will provide that with James)
Screenshot 2024-10-22 at 09 59 28

**Comment by somebody1234** [comment]
> If I type datalink name that already exists the modal is successfully submited but request ends with 400

i think this is out of scope unfortunately. the way the event handler currently works, we cannot `await` it to see if it succeeded. it's *possible* to fix but will require larger logic refactors

**Comment by radeusgd** [comment]
> 2\. Looks like for Postgres connectors all is now optional. I can create one with missing hostname, database name. Only port is required (similar to snowflake)

+1 to that - it seems that I can create a data link without hostname or database name - but these 2 fields are required. Such datalink gets created but then when I `.read` it in Enso it of course fails to open as its invalid.

File: app/gui/src/dashboard/components/JSONSchemaInput.tsx [hunk 1]
```diff
@@ -186,7 +200,7 @@ export default function JSONSchemaInput(props: JSONSchemaInputProps) {
               >
                 {propertyDefinitions.map((definition) => {
                   const { key, schema: childSchema } = definition
-                  const isOptional = !requiredProperties.includes(key)
+                  const isOptional = !requiredProperties.includes(key) || isAbsent
```
Comment (radeusgd) [inline app/gui/src/dashboard/components/JSONSchemaInput.tsx:214]: I think this may be too simple for the fix we need.

Fields that are themselves required, should still be marked red and not accepted if they are absent.

Only required **sub-fields** whose _parent field is optional_, do not have to be required.

Comment (somebody1234) [reply app/gui/src/dashboard/components/JSONSchemaInput.tsx:214]: i guess this is a bit of a misnomer - `isAbsent` means that the parent field is optional

Comment (somebody1234) [reply app/gui/src/dashboard/components/JSONSchemaInput.tsx:214]:
```
Foo (object field, optional, currently absent, isAbsent = false)
  Bar (isAbsent = true, not optional)
  Baz (isAbsent = true, not optional)
```

Comment (radeusgd) [reply app/gui/src/dashboard/components/JSONSchemaInput.tsx:214]: > i guess this is a bit of a misnomer - `isAbsent` means that the parent field is optional

Oh... Yeah so that name is a bit misleading indeed

**Comment by radeusgd** [comment]
Hmm, I see. It may be that the Postgres always allowed empty string for hostname/database name. So the fields are not actually missing, they are just `""`.

I guess we may want to change the schema to require at least `host` to be non-empty. Not sure if empty database string makes sense.

**Comment by PabloBuchu** [comment]
1. New datalink -> s3 -> authentication -> aws (profile) -> Start typing into `Profile` -> after the first letter focus jumps to close modal icon (it is the same with all inputs)
2.  It no longer true. The valid paths must start with `enso://Teams` or `enso://Users`.. btw shouldn't we have here a selector? 
Screenshot 2024-10-29 at 10 51 41

3. Enso Secret selector. Scrolling left right works but highlighting not
Screenshot 2024-10-29 at 10 53 38

**Comment by somebody1234** [comment]
> no longer true

@radeusgd i guess the text will need to be updated in the JSON Schema.

> shouldn't we have here a selector?

possibly, but probably out of scope. i assume it should list items in the current directory (based on the entered path?)

1: will investigate

3: will also investigate. i could swear highlighting worked properly once but i guess it regressed at some point.

**Comment by somebody1234** [comment]
@PabloBuchu should be addressed now

**Comment by PabloBuchu** [comment]
I still can type anything in EnsoFile path as long as it follows `enso://.*/.*` pattern. The `Users` and `Teams` validation are on frontend side or in libs?

Screenshot 2024-11-01 at 09 49 23

**Comment by somebody1234** [comment]
on the libs' JSON Schema. but we can change it in this PR, can do soon :tm:

**Review by PabloBuchu — APPROVED** [review]
