### PR TITLE
Fix help panel

### LINKED ISSUE #11392: Help panel doesn't change to new component when selected
In release version.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #11392

The issue was caused by somewhat cumbersome logic of updating/overriding displayed suggestion. I’m not sure if it even was working correctly at any time.

https://github.com/user-attachments/assets/51e6fcd4-2198-40a2-86e7-8fcfa8b8b8d5

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/ComponentDocumentation.vue [hunk 1]
```diff
@@ -19,20 +19,19 @@ function docsForSelection() {
   return Ok(suggestionId)
 }
 
-const displayedId = computed(() =>
-  props.displayedSuggestionId != null ? Ok(props.displayedSuggestionId) : docsForSelection(),
-)
+const docs = computed(() => docsForSelection())
+// When the selection changes, we cancel the displayed suggestion override that can be in place.
+watch(docs, (_) => (displayedId.value = null))
```
Comment (kazcw) [inline app/gui/src/project-view/components/ComponentDocumentation.vue]: Setting `displayId.value` to `null` to make it reflect `docs.value` (which isn't necessarily `null` here) is confusing. Why not reset `overrideDisplayed` directly?

File: app/gui/src/project-view/components/ComponentDocumentation.vue [hunk 2]
```diff
@@ -19,20 +19,19 @@ function docsForSelection() {
...
+
+const displayedId = computed<SuggestionId | null>({
+  get: () => overrideDisplayed.value ?? unwrapOr(docs.value, null),
+  set: (value) => (overrideDisplayed.value = value),
+})
```
Comment (kazcw) [inline app/gui/src/project-view/components/ComponentDocumentation.vue]: This `computed` doesn't have the property that, after setting its value, the getter will return an equivalent value. That being the case, I don't see the benefit of a R/W computed here vs passing separate a separate getter and setter to `DocumentationPanel`.

File: app/gui/src/project-view/components/ComponentDocumentation.vue [hunk 3]
```diff
@@ -19,20 +19,19 @@ function docsForSelection() {
...
-  <DocumentationPanel
-    v-if="displayedId?.ok"
-    :selectedEntry="displayedId.value"
-    @update:selectedEntry="emit('update:displayedSuggestionId', $event)"
-  />
-  <div v-else-if="displayedId?.ok === false" class="help-placeholder">
-    {{ displayedId.error.payload }}.
-  </div>
+  <DocumentationPanel v-if="displayedId" v-model="displayedId" />
+  <div v-else-if="!docs.ok" class="help-placeholder">{{ docs.error.payload }}.</div>
```
Comment (kazcw) [inline app/gui/src/project-view/components/ComponentDocumentation.vue]: It's not obvious that the `if/else-if` conditions are correct, but they are: If the value is `null`, then we would have tried to display `docs`, therefore it is correct to display the error for `docs`. Relying on the implementation details of `displayedId` here is fragile.

File: app/gui/src/project-view/components/ComponentDocumentation.vue (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/ComponentDocumentation.vue]: That’s an oversight, thank you

File: app/gui/src/project-view/components/ComponentDocumentation.vue (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/ComponentDocumentation.vue]: True, but I don’t see a clear way to express that. I added an additional condition `!displayedId` here that can probably help a little.

File: app/gui/src/project-view/components/ComponentDocumentation.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/ComponentDocumentation.vue]: I’m not aware of such requirement on mutable computed, but you’re probably right, reverted it back to getter/setter pair.

Comment (kazcw) [reply app/gui/src/project-view/components/ComponentDocumentation.vue]: It's not a technical requirement, but I think it's a good convention to follow to avoid surprising behavior

**Review by kazcw — APPROVED** [review]
