### PR TITLE
Fix arrow keys in text inputs

### LINKED ISSUE #10239: Arrow key defects
image

If I am editing a text widget then the left right arrow keys should move the text edit cursor inside the widget and not move the component.

Also if I put my cursor in a text edit widget and then enter code edit mode on the component the left right arrow keys should move the text edit cursor. Currently they do not. 

image

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #10239 

### Important Notes

This is a quick fix, but we may consider better focus handling - perhaps the graph editor should be focusable?

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by Frizi — APPROVED** [review]
Indeed looks like a quickfix that will need to soon be replaced with something better. We likely should be handling all `keydown` events locally on specific DOM nodes, so we can take advantage of focus and cancelation properly.

File: app/gui2/src/components/CodeEditor.vue [hunk 1]
```diff
@@ -331,6 +331,10 @@ const editorStyle = computed(() => {
     ref="rootElement"
     class="CodeEditor"
     :style="editorStyle"
+    @keydown.arrow-left.stop
+    @keydown.arrow-right.stop
+    @keydown.arrow-up.stop
+    @keydown.arrow-down.stop
```
Comment (kazcw) [inline app/gui2/src/components/CodeEditor.vue:337]: `LexicalContent` needs the same

**Review by kazcw — CHANGES_REQUESTED** [review]

**Review by kazcw — APPROVED** [review]
