### PR TITLE
Language server can download libraries from a server

### LINKED ISSUE #14319: Describe process of releasing non-`Standard` library
### Goal

Enso has been designed with support for extensible
   - [library repositories](https://github.com/enso-org/enso/blob/develop/docs/libraries/repositories.md)
   - [editions](https://github.com/enso-org/enso/blob/develop/docs/libraries/editions.md)

These features aren't however used when releasing recent versions of Enso. Instead, libraries like _Strava support_ are being stuffed into `Standard` namespace of libraries. Such a system doesn't scale as delivering high quality APIs for every niché problem is too time consuming and requires too high effort.

Instead: Let's get (existing) system for delivering non-`Standard` libraries working!

### Step 1:  Local Deployment

- create a project to compute something simple - factorial?
- package it and expose it via HTTP(S) server running on local machine
- create another pristine project
   - use editor to import the factorial functionality
- verify the imported function can be invoke and computes the right result
   - do this for CLI as well as GUI
- document necessary code changes and exact steps needed to reproduce the demo

### Step 2: Changes to the Release Process

- once the "local scenario" is working propose what needs to be changed to make a library like that part of release
   - perform necessary changes
   - built nightly release
- demonstrate a library missing on disk can be downloaded and used as in the "local scenario" case
- Step 2 is tracked in #14469

### PR DESCRIPTION
**Pull request by Akirathan**
Part of #14319.

### Pull Request Description

Necessary modification to make #14319 work in the IDE.

### Important Notes

Basically reverts #4117 which is now pointless anyway.

### How to download custom library in IDE?

Follow the steps from https://github.com/enso-org/enso/issues/14319#issuecomment-3613498086 with the only modification of step (5) - instead of running enso engine directly, just run the IDE (with modified [ENSO_ENGINE_PATH](https://github.com/enso-org/enso/blob/0a0be245967089fb7adbcaa346226d7e3567570b/docs/CONTRIBUTING.md#L578-L580).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by Akirathan** [comment]
I have confirmed that on this PR, on https://github.com/enso-org/enso/pull/14446/commits/353c4a5abc96c34b0c03e269ab7f965d83765e4b, the issue https://github.com/enso-org/enso/issues/5018 that was fixed by #4117, is not an issue: Trying to open a project with non-existing edition correctly falls back to the default edition and logs:
```
[WARN] [2025-12-08T18:15:52.579] [org.enso.interpreter.runtime.DefaultPackageRepository] Failed to resolve original edition. Trying fallback to the default one
org.enso.editions.EditionResolutionError$CannotLoadEdition: Cannot load edition [bullshit]: The edition was not found.
	at org.enso.editions/org.enso.editions.EditionResolver.$anonfun$resolveParent$1(EditionResolver.scala:157)
	at scala.library@2.13.15/scala.util.Either$LeftProjection.map(Either.scala:622)
	at org.enso.editions/org.enso.editions.EditionResolver.resolveParent(EditionResolver.scala:157)
	at org.enso.editions/org.enso.editions.EditionResolver.resolveEdition(EditionResolver.scala:39)
	at org.enso.editions/org.enso.editions.EditionResolver.resolve(EditionResolver.scala:29)
	at org.enso.editions.updater/org.enso.editions.updater.EditionManager.resolveEdition(EditionManager.scala:28)
	at org.enso.runtime/org.enso.interpreter.runtime.DefaultPackageRepository$.initializeRepository(DefaultPackageRepository.scala:706)
	at org.enso.runtime/org.enso.interpreter.runtime.DefaultPackageRepository.initializeRepository(DefaultPackageRepository.scala)
	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.initialize(EnsoContext.java:202)
...
```

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/MockLogHandler.java [hunk 1]
```diff
@@ -29,6 +29,13 @@ public void close() throws SecurityException {
     logs.clear();
   }
 
+  List<String> getRawLogMessages(String loggerName) {
```
Comment (hubertp) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/MockLogHandler.java:32]: I would also say that this should be a destructive operation and should clean `logs`.

**Review by hubertp — APPROVED** [review]

File: engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala [hunk 2]
```diff
@@ -322,7 +322,6 @@ class MainModule(serverConfig: LanguageServerConfig, logLevel: Level) {
     RuntimeOptions.LOG_MASKING,
     Masking.isMaskingEnabled.toString
   )
-  extraOptions.put(RuntimeOptions.EDITION_OVERRIDE, BuildVersion.currentEdition)
```
Comment (JaroslavTulach) [inline engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala:325]: - I don't have problem with this change, but I can't see its consequences
   - Hard to say what #4117 does these days...
- But setting "override" to `BuildVersion.currentEdition` - e.g. to "default value" is pretty strange

**Review by JaroslavTulach — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]
