### PR TITLE
Provide Forbidden_Operation.to_display_text

### LINKED ISSUE #6227: Context.if_enabled fails with AssertionError in interactive mode
Related #6129 

The program below fails in interactive mode 

```py
from Standard.Base import all
from Standard.Base.Runtime.Context import Output

main =
    res = Output.if_enabled 42
    res
```

The expression `Oubtput.if_enabled 42` should have an id assigned to be a subject of instrumentation. For a repro, see examples in the `RuntimeExecutionEnvironmentTest` suite.

<details>
<summary>

```
java.lang.AssertionError: Invariant contract violation for receiver Error Output(org.enso.interpreter.runtime.callable.atom.unboxing.Layout_Atom_0_1) and identifier to_display_text.
```

</summary>

```
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3462)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.invokeMember(InteropLibraryGen.java:7066)
	at org.enso.interpreter.service.ExecutionService.getExceptionMessage(ExecutionService.java:443)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.sendExpressionUpdate(ProgramExecutionSupport.scala:341)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$executeProgram$3(ProgramExecutionSupport.scala:74)
	at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.passExpressionValueToCallback(IdExecutionInstrument.java:301)
	at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onExpressionReturn(IdExecutionInstrument.java:278)
	at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:237)
	at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onReturnExceptional(IdExecutionInstrument.java:247)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnExceptional(ProbeNode.java:1387)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnExceptional(ProbeNode.java:1023)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnExceptionalOrUnwind(ProbeNode.java:288)
	at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:119)
	at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric_generic1(AssignmentNodeGen.java:57)
	at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:36)
	at org.enso.interpreter.node.scope.AssignmentNodeGen.executeVoid(AssignmentNodeGen.java:75)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:54)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
	at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:495)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
	at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:56)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:90)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:52)
	at org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:49)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:157)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:108)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:92)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:102)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:58)
	at org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:79)
	at org.enso.interpreter.node.callable.InteropApplicationNodeGen.executeAndSpecialize(InteropApplicationNodeGen.java:95)
	at org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:56)
	at org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
	at org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.executeAndSpecialize(FunctionCallGen.java:91)
	at org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:78)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.execute(InteropLibrary.java:3034)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
	at org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
	at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:181)
	at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:222)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:106)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:215)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:215)
	at scala.util.Either.flatMap(Either.scala:352)
	at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:209)
	at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:38)
	at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:15)
	at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: Attached Guest Language Frames (3)
```

</details>

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Added a missing `to_display_text` method which, by convention, is defined via a builtin method.

Also re-enabled and fixed pending tests.

Closes #6227.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- ~[ ] The documentation has been updated, if necessary.~
- ~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - ~[ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ForbiddenOperationToDisplayTextNode.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+@BuiltinMethod(type = "Forbidden_Operation", name = "to_display_text")
+public abstract class ForbiddenOperationToDisplayTextNode extends Node {
+  static ForbiddenOperationToDisplayTextNode build() {
+    return ForbiddenOperationToDisplayTextNodeGen.create();
+  }
+
+  abstract Text execute(Object self);
+
+  @Specialization
+  Text doAtom(Atom self, @CachedLibrary(limit = "3") StructsLibrary structs) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ForbiddenOperationToDisplayTextNode.java:23]: I know it is quite common to have these `XyzToDisplayTextNode` implementations spread around the code base, but is there a reason for that?

Why can't we simply write following?
```
Forbidden_Operation.to_display_text self = "Forbidden operation: "+self.why+"."
```
CCing @jdunkerley as he asked this question once.

**Review by JaroslavTulach — APPROVED** [review]
If in hurry, go on. But otherwise I'd like us to rethink the `XyzToDisplayTextNode` design and whether we can remove all that crap and replace each of the nodes with a single line of Enso code?

**Comment by hubertp** [comment]
> If in hurry, go on. But otherwise I'd like us to rethink the `XyzToDisplayTextNode` design and whether we can remove all that crap and replace each of the nodes with a single line of Enso code?

I'm happy to look into this cleanup straight after this PR, but this currently blocks most of IDE adoption.

**Review by 4e6 — APPROVED** [review]
