### PR TITLE
Documentation link interactions

### LINKED ISSUE #11692: Clicking links in documentation panel not working
image

clicking the link results in it editing as markdown now.

### LINKED ISSUE #11740: Fix code editor tooltips
Expected:

image

Actual:

No tooltips

Version 2024.5.1-rc2
Build e82ce1085b9f3c06b4870b839cf4dd8c9ce88579
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-rc2 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### LINKED ISSUE #11766: Code Editor steals focus if closed by `Ctrl+~`
When I use the keyboard shortcut to close the code editor, it keeps stealing the focus for typing. I can open the Component Browser, but anything I type does not show up. In fact, when I re-open the code editor, I can see that all these keystrokes were applied in the place where I last left my cursor in the editor - possibly messing up the file.

https://github.com/user-attachments/assets/a42ef6ad-9d2b-4adf-80aa-4729580a663a

The video is imperfect because it doesn't show mouse clicks. At first try, I click into the node editor before closing code editor - this switches focus and CB works correctly. In the second attempt, I don't click - I use solely the keyboard shortcut. That's when the focus becomes misaligned.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Ctrl+click to follow link; clicking link opens a popup. Fixes #11692.

https://github.com/user-attachments/assets/ff0eb399-73ea-4d68-a2ab-57d099a1dad5

- Ctrl+click to follow link (and add hover text)
- When editing, if the cursor is in a link a popup allows following the link.
- Text filters (e.g. recognizing links) now apply to text dragged into the editor, or pasted with the context menu, besides pasting with the keyboard (uses new feature from updated CM).
- Simplify CM editors by moving setup and reactivity patterns into shared helpers.
- Add integration tests for link interactions in component comments and documentation panel.
- Fix code editor tooltips (fixes #11740).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue [hunk 1]
```diff
@@ -17,58 +18,49 @@ import {
...
-          lintGutter(),
-          highlightSelectionMatches(),
-          ensoSyntax(),
-          updateListener,
-          ensoHoverTooltip(graphStore, suggestionDbStore),
-          ensoDiagnostics,
-        ],
-      }),
-    )
+    setExtraExtensions([updateListener, ensoDiagnostics])
```
Comment (farmaazon) [inline app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue]: Why these extensions need to be set in watch?

File: app/gui/src/project-view/components/DocumentationEditor.vue [hunk 2]
```diff
@@ -41,14 +41,14 @@ function handlePaste(raw: boolean) {
...
     if (!markdownEditor.value) return
     for (const item of items) {
+      if (tryUploadPastedImage(item)) return
       const textType = item.types.find((type) => type === 'text/plain')
       if (textType) {
         const blob = await item.getType(textType)
         const rawText = await blob.text()
         markdownEditor.value.putText(raw ? rawText : transformPastedText(rawText))
-        break
+        return
```
Comment (farmaazon) [inline app/gui/src/project-view/components/DocumentationEditor.vue:50]: Nitpick: Why do you think this is better? I thought the function should start with more typical case (which is text).

File: app/gui/src/project-view/util/dom.ts [hunk 3]
```diff
@@ -1,5 +1,5 @@
 /** TODO: Add docs */
-export function* elementHierarchy(element: Element, selectors: string) {
+export function* selectorHierarchy(element: Element, selectors: string) {
```
Comment (farmaazon) [inline app/gui/src/project-view/util/dom.ts:4]: Let's add missing docs here.

File: app/gui/src/project-view/util/codemirror/yCollab/y-undomanager.ts [hunk 4]
```diff
@@ -1,10 +1,10 @@
-import { type StackItemEvent } from '@/components/codemirror/yCollab/yjsTypes'
 import * as cmState from '@codemirror/state'
 import * as cmView from '@codemirror/view'
 import { createMutex } from 'lib0/mutex'
 import * as Y from 'yjs'
 import { type YRange } from './y-range'
 import { ySyncAnnotation, type YSyncConfig, ySyncFacet } from './y-sync'
+import { type StackItemEvent } from './yjsTypes'
```
Comment (farmaazon) [inline app/gui/src/project-view/util/codemirror/yCollab/y-undomanager.ts]: AFAIK we preferred full paths (with @) so far.

**Review by farmaazon — COMMENTED** [review]
Part I

File: app/gui/src/project-view/components/DocumentationEditor.vue (hunk 2 above)
Comment (kazcw) [reply app/gui/src/project-view/components/DocumentationEditor.vue:50]: If both are present, we can assume the text is a fallback.

Comment (farmaazon) [reply app/gui/src/project-view/components/DocumentationEditor.vue:50]: Yes, I think that's fair.

File: app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue (hunk 1 above)
Comment (kazcw) [reply app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue]: They don't--moved them.

File: app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue [hunk 5]
```diff
@@ -17,58 +18,49 @@ import {
...
-          updateListener,
-          ensoHoverTooltip(graphStore, suggestionDbStore),
-          ensoDiagnostics,
-        ],
-      }),
-    )
     connectModuleListener()
   },
   { immediate: true },
 )
```
Comment (farmaazon) [inline app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue]: `connectModuleListener` looks a bit odd: we need to call it _externally_ on every module change, despite the fact it does not take it as argument. Maybe this watch should be inside `useEnsoSourceSync`?

Comment (kazcw) [reply app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue]: Moved the `watch` inside `connectModuleListener`--currently it needs to be called after the extension is installed, so it can't be entirely inside `useEnsoSourceSync`.

**Review by farmaazon — APPROVED** [review]
