### PR TITLE
Fix CORS problems on built package

### LINKED ISSUE #8297: Cannot open project in GUI2
On newest develop (5baec46466283c02a04621dcce6323e18b66d72a) when I open project in the built electron package, I get

Screenshot from 2023-11-14 11-04-37

```Could not open editor: Unable to preload CSS for /assets/createApp-ecb8379f.css```

The package is built by `./run ide2 build` command.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #8297 

Some external resources were failing due to CORS policies. This is the simplest fix.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - ~~[] Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/stores/visualization/index.ts [hunk 1]
```diff
@@ -119,6 +119,9 @@ export const useVisualizationStore = defineStore('visualization', () => {
           loadedScripts.add(url)
           const node = document.createElement('script')
           node.src = url
+          // Some resources still set only "Access-Control-Allow-Origin" in the response.
+          // We need to explicit make a request CORS - see https://resourcepolicy.fyi
```
Comment (vitvakatu) [inline app/gui2/src/stores/visualization/index.ts]: nit:
```suggestion
          // We need to explicitly make a request CORS - see https://resourcepolicy.fyi
```

**Review by Frizi — APPROVED** [review]
