### PR TITLE
Fix async/reactive issues

### LINKED ISSUE #13351: Data races in usage of vue-query `useMutation`
Our usage of the `useMutation` function from the `@tanstack/vue-query` API is prone to data races. The race condition occurs when a mutation triggers invalidation of a query identified by a reactive key, and the value of the key may change between the initiation of the mutation and its successful completion. When this occurs, a different query will be invalidated than the query that the mutation actually affected. **We can expect this to present as various bugs in which the application occasionally continues to operate using outdated data.** This type of misbehaviour is difficult to debug, as it occurs non-deterministically and at API boundaries. Since we have been increasing our Vue usage of `useMutation`, we should address the root of the issue, before we start getting reports of mysterious, hard-to-reproduce bugs. The issue cannot be addressed by improving the usage or implementation of `useMutation`; it is inherent to that API[^1]. To prevent these bugs, **we should introduce an alternative `useMutation` that supports race-free query invalidation**. 

[^1]: The problem occurs when using the API as intended:
    - Vue query supports reactive query keys, and [recommends their use](https://tanstack.com/query/latest/docs/framework/vue/guides/query-keys#if-your-query-function-depends-on-a-variable-include-it-in-your-query-key).
    - The most obvious way to perform invalidations after a mutation is to use the `onSuccess` callback, and [this is Vue query's recommendation](https://tanstack.com/query/latest/docs/framework/vue/guides/invalidations-from-mutations).
    This combination of reactive keys and key-identified invalidation in an asynchronously-dispatched callback causes the race condition.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix async/reactive races (Fixes #13351)
- `meta.invalidates` logic now evaluates query keys at the time the mutation is performed, so the keys invalidated will be consistent with the mutation as long as the mutation itself is pure and operates on snapshotted state, as discussed in #13351.
- ~~In `auth`, separate the `usersMe` query from the reactive data, to avoid untracked reactive side-effects in the query.~~

Query maintainability cleanup:
- ~~In `FileBrowserWidget`, reuse `user` and `organization` queries defined elsewhere, rather than duplicating them.~~

Integration tests:
- Fix a test condition that was causing test flakiness on my machine (condition already passed before page navigation occurred).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by somebody1234** [comment]
as mentioned in the issue: is there a reason we can't return context from onMutate and use that in onSuccess?

might have missed a reply in the issue actually

edit: yeah i did, sad that it's like that but i guess it makes sense

File: app/common/src/queryClient.ts [hunk 1]
```diff
@@ -95,43 +98,20 @@ export function createQueryClient<TStorageValue = string>(
     })
   }
 
+  const invalidationKeys = new WeakMap<queryCore.Mutation<unknown, unknown>, InvalidationKeys>()
+
   const queryClient: QueryClient = new vueQuery.QueryClient({
     mutationCache: new queryCore.MutationCache({
+      onMutate: (_variables, mutation) => {
+        const keys = evaluateInvalidationKeys(mutation)
+        if (keys) invalidationKeys.set(mutation, keys)
```
Comment (farmaazon) [inline app/common/src/queryClient.ts]: If `mutation` is used as `key`, let's also call Vue's `toRaw`, because I learned that in Vue, Proxies lurk everywhere.

File: app/gui/src/providers/auth.ts [hunk 2]
```diff
@@ -56,25 +54,10 @@ export interface FullUserSession extends BaseUserSession {
...
-        return null
-      }
-
-      return remoteBackend.usersMe().then((user) => {
-        return user == null ?
-            ({ type: UserSessionType.partial, ...sessionVal } satisfies PartialUserSession)
-          : ({ type: UserSessionType.full, user, ...sessionVal } satisfies FullUserSession)
-      })
-    },
+    queryKey: [remoteBackend.type, 'usersMe'] as const,
```
Comment (farmaazon) [inline app/gui/src/providers/auth.ts]: The session's clientId as part of the key should remain here. Otherwise, we may receive from useQuery cached data related to different user. I think the cloud differentiates results for `users/me` basing on authToken we set in HttpClient (see https://github.com/enso-org/enso/blob/develop/app/gui/src/providers/session.ts#L201)

I assumed we don't expect races here, as the querFn won't be called after queryKey change... but that was bold assumption perhaps.

BUT there's another solution: we could just wrap both queryKey and queryFn in computed, where we get the user session id first, and then use it nonreactively in both queryKey and queryFn. Passing it to useQuery is possible, but without `vueQuery.queryOptions`. Tanstack updates all options at once https://github.com/TanStack/query/blob/main/packages/vue-query/src/useBaseQuery.ts#L133

Comment (farmaazon) [reply app/gui/src/providers/auth.ts]: > BUT there's another solution: we could just wrap both queryKey and queryFn in computed, where we get the user session id first, and then use it nonreactively in both queryKey and queryFn. Passing it to useQuery is possible, but without `vueQuery.queryOptions`. Tanstack updates all options at once https://github.com/TanStack/query/blob/main/packages/vue-query/src/useBaseQuery.ts#L133

With this solution, I think we want to check the actual current session anyway, because it specifies what session id will be sent in HTTP request. If there's mismatch, then the query should result in non-retriable error instead.

**Comment by kazcw** [comment]
I removed some of my original changes because they were requiring too much debugging for a task I got into incidentally; I created an issue to look in to async reactive effects: #13408

File: app/common/src/queryClient.ts [hunk 3]
```diff
@@ -70,6 +73,18 @@ export interface QueryClientOptions<TStorageValue = string> {
   }
 }
 
+declare const brandRaw: unique symbol
+/**
+ * A value that is known not to be a reactive proxy; this marker type can be used to ensure
+ * comparisons are free of identity hazards.
+ */
+type RawValue<T> = T & { [brandRaw]: true }
```
Comment (farmaazon) [inline app/common/src/queryClient.ts]: For brands, I've seen using `never` type instead of `true`. Which makes sense, because the value won't have `[brandRaw]` key.

File: app/common/src/utilities/data/reactive.ts [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+
+  return value as T
+}
+
+function cloneDeep<T>(
+  value: MaybeRefDeep<T>,
+  customize?: (val: MaybeRefDeep<T>, key: string, level: number) => T | undefined,
+): T {
+  return _cloneDeep(value, customize)
+}
```
Comment (farmaazon) [inline app/common/src/utilities/data/reactive.ts]: I don't know why we have separate `cloneDeep` and `_cloneDeep` since the former is just a wrapper for the latter disallowing some arguments, and both are private anyway.

File: app/common/src/utilities/data/reactive.ts [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+function _cloneDeep<T>(
+  value: MaybeRefDeep<T>,
+  customize?: (val: MaybeRefDeep<T>, key: string, level: number) => T | undefined,
+  currentKey: string = '',
+  currentLevel: number = 0,
+): T {
+  if (customize) {
+    const result = customize(value, currentKey, currentLevel)
+    if (result === undefined && isRef(value)) {
+      return result as T
```
Comment (farmaazon) [inline app/common/src/utilities/data/reactive.ts]: I don't understand this `if` Why do we cast `undefined` as T when the value happens to be a ref?

File: app/common/src/utilities/data/reactive.ts [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+
+/** Recursively clone the provided value, unwrapping any references found. */
+export function cloneDeepUnref<T>(obj: MaybeRefDeep<T>, unrefGetters = false): T {
+  return cloneDeep(obj, (val, key, level) => {
+    // Check if we're at the top level and the key is 'queryKey'
+    //
+    // If so, take the recursive descent where we resolve getters to values as well as refs.
+    if (level === 1 && key === 'queryKey') {
+      return cloneDeepUnref(val, true)
+    }
```
Comment (farmaazon) [inline app/common/src/utilities/data/reactive.ts]: We're inside utilities, so not in context of tanstack query. The docs do not suggest that `queryKey` is treated in a special way.

File: app/common/src/utilities/data/types.ts [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+ * {@link Ref}.
+ */
+export type ScalarOrRef =
+  | undefined
+  | number
+  | string
+  | boolean
+  | bigint
+  | symbol
+  | null
```
Comment (farmaazon) [inline app/common/src/utilities/data/types.ts]: In JS world this set of types is called rather ["primitive"](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) than "scalar".

**Review by farmaazon — COMMENTED** [review]
`cloneDeepUnref` should be unit tested, and `deepInspect` probably too.

**Review by farmaazon — APPROVED** [review]
I really appreciate refactoring in queryClient.ts
