### PR TITLE
Make sure Enso FrameDescriptors have non-null default value

### LINKED ISSUE #5500: Recursive definitions fail in a confusing way at runtime
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181652974).
<hr />

### Steps to reproduce

Run the following code:

```
from Standard.Base import all

main =
    op = if False then 42 else "Nope: "+op
    IO.println op
```

### Expected

~~I would expect it to fail at compile-time, saying that a recursive value definition is not permitted (because such definitions do not work, at least not currently).~~

I would expect to get an informative error about a cyclical reference.

### Actual

The code fails at runtime with:

```
Execution finished with an error: java.lang.NullPointerException: Null receiver values are not supported by libraries.
        at <java> org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:522)
        at <java> org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
        at <java> org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.specialize(InteropLibraryGen.java:9649)
        at <java> org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.asString(InteropLibraryGen.java:7733)
        (...)
        at <java> org.enso.interpreter.node.expression.builtin.text.ConcatMethodGen.execute(ConcatMethodGen.java:22)
        at <enso> Text.+(Internal)
        at <enso> argument<2>(loop.enso:4:32-42)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> loop.main(loop.enso:4:10-42)
```

## Comments:
Just realised that some kinds of recursive value definitions are currently permitted:

```
from Standard.Base import all

type Foo f

main =
    op = Foo (_ -> op)
    IO.println op
    IO.println (op.f 0)
    IO.println (((op.f 0).f 0).f 0)
```

will happily print

```
(Foo org.enso.interpreter.runtime.callable.function.Function@12f8682a)
(Foo org.enso.interpreter.runtime.callable.function.Function@12f8682a)
(Foo org.enso.interpreter.runtime.callable.function.Function@12f8682a)
```

Some further thought may be needed on how to proceed with this. (Radosław Waśko - Mar 23, 2022)
<hr />
	Because of the above, we cannot have a fully static check, because theoretically a lambda `_ -> op` can be passed to some function `bar` and there is no way to staticallly know for that function if the lambda will be just saved for later in the resulting value (which would be allowed, as after the initialization finishes `op` will be a valid reference) or if it will be called during initialization (and so `op` will still be invalid).

We need some dynamic solution to throw an error whenever the cyclical reference is encountered.

Still, it would be possible to have static (compile-time) checks for two cases:
- initialising an atom with the circular reference
- calling a function with the circular reference (not a lambda wrapping it, just direct reference) and the function argument not being suspended (Radosław Waśko - Mar 23, 2022)
<hr />
An even more subtle repro:
```
x = x
IO.println x
```

`x` gets actually successfully initialized to the `null` value (so the Assignment Node does not check that) and then can be passed around and break stuff in weird places. It makes for quite hard to track down NPEs. (Radosław Waśko - Apr 28, 2022)
<hr />
Another case
```
from Standard.Base import all

main =
    n = case n of
      _ : Nothing -> 0
      _ -> 1
    n
``` (Hubert Plociniczak - Dec 6, 2022)
<hr />

### LINKED ISSUE #6821: meta1 = meta1 triggers silent NPE
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Backend silently reports NPE when manually editing the node.
```
[warn] [2023-05-24T07:40:48.687Z] [enso] Execution of function main failed (Null receiver values are not supported by libraries.).
java.lang.NullPointerException: Some(Null receiver values are not supported by libraries.)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:528)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.specialize(InteropLibraryGen.java:9873)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.isTime(InteropLibraryGen.java:9211)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.executeAndSpecialize(TypeOfNodeGen.java:395)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.execute(TypeOfNodeGen.java:215)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.typeOf(IdExecutionInstrument.java:289)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onExpressionReturn(IdExecutionInstrument.java:257)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:237)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnValue(ProbeNode.java:1392)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnValue(ProbeNode.java:995)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnValue(ProbeNode.java:231)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:116)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric_generic1(AssignmentNodeGen.java:57)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:36)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:495)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
  at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:91)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:137)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:64)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode$RepeatedCallNode.executeRepeating(LoopingCallOptimiserNode.java:216)
  at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:154)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:105)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.dispatch(LoopingCallOptimiserNode.java:68)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeAndSpecialize(LoopingCallOptimiserNodeGen.java:59)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeDispatch(LoopingCallOptimiserNodeGen.java:44)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCall(IndirectCurryNode.java:132)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCurry(IndirectCurryNode.java:78)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.executeAndSpecialize(IndirectCurryNodeGen.java:65)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.execute(IndirectCurryNodeGen.java:47)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeUncached(InvokeFunctionNode.java:141)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:113)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:58)
  at org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:79)
  at org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:46)
  at org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
  at org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:75)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
  at org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:482)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:181)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:222)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:106)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:215)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:215)
  at scala.util.Either.flatMap(Either.scala:352)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:209)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:38)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:15)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: com.oracle.truffle.api.TruffleStackTrace.LazyStackTrace: None
```

### Expected behaviour

No exception.

### How we can reproduce it?

1. Create a new node with `Meta` contents and finish the creation by accepting with Enter
2. ctrl+click to enter manual edition of the node
3. Double click (with a ctrl?) on `Meta` to select the text
4. ... an exception should appear in the logs

### Screenshots or screencasts

[Kazam_screencast_00010.webm](https://github.com/enso-org/enso/assets/292128/a1754e2b-dc33-472a-90dd-3130dc62398f)

### Logs

[out11.txt](https://github.com/enso-org/enso/files/11551825/out11.txt)

### Enso Version

62fecfa474e3958ce6fda54c00ef91a86bfa2c2e

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Solves runtime problems with self assigned statements like `x = x` by making sure the initial value of each variable is initialized to non-null.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala [hunk 1]
```diff
@@ -162,6 +163,18 @@ class LocalScope(
...
+    val ctx =
+      try {
+        EnsoContext.get(null)
+      } catch {
+        case _: RuntimeException => null
+      }
+    val defValue = if (ctx != null) {
+      ctx.getBuiltins().error().dataFlowErrorUninitializedValue()
+    } else {
+      0L;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala]: This is a nasty part. Some `FrameDescriptor`s are created sooner than `EnsoContext` is initialized - for example for builtins. In such case we don't have the `dataFlowErrorUninitializedValue()` to put it in and we put `0L` there. Not ideal. On the other hand, errors in builtins are under our control and shall be fixed properly, not just by putting in default value.

Moreover sometimes `EnsoContext.get` can even throw an exception... hence the `try/catch` above.

Comment (Akirathan) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala]: Shouldn't we rather fix `ReadLocalVariableNode` to throw a `dataFlowErrorUnitializedValue` once it tries to read a frame slot that has `Illegal` kind? You wouldn't need to do this weird hack, because in `ReadLocalVariableNode`, you can be sure that there is an `EnsoContext`.

Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala]: Possible, but it will require a `null` check. The solution with _default value_ would be for "free".

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+                .out(out)
+                .allowAllAccess(true)
+                .build();
+
+        var engine = ctx.getEngine();
+        Map<String, Language> langs = engine.getLanguages();
+        assertNotNull("Enso found: " + langs, langs.get("enso"));
+
+        @SuppressWarnings("unchecked")
+        var fn = (Function<Source,AutoCloseable>) engine.getInstruments().get("insight").lookup(Function.class);
```
Comment (JaroslavTulach) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java:44]: Btw. the following shows how to programatically register [GraalVM Insight](https://www.graalvm.org/latest/tools/graalvm-insight/) script, @hubertp.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+        assertNotNull(fn);
+
+        var insightScript = Source.newBuilder("js", """
+        insight.on('enter', (ctx, frame) => {
+            print(`${ctx.name} at ${ctx.source.name}:${ctx.line}:`);
+            let dump = "";
+            for (let p in frame) {
+                dump += ` ${p}=${frame[p]}`;
```
Comment (JaroslavTulach) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java:52]: Previously (until this PR) this statement generated internal error. It was accessing uninitialized variables - now this "insight" no longer fails.

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala]: > This is a nasty part. Some `FrameDescriptor`s are created sooner than `EnsoContext`

Nasty code is gone in 40dfa45 - we use _context-less_ `DataflowError.UNINITIALIZED` value which is available all the time.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java:52]: Since 40dfa45 JavaScript also sees uninitialized values as `null`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java [hunk 4]
```diff
@@ -161,8 +161,12 @@ public Builtins(EnsoContext context) {
     duration = builtins.get(org.enso.interpreter.node.expression.builtin.date.Duration.class);
     timeOfDay = builtins.get(org.enso.interpreter.node.expression.builtin.date.TimeOfDay.class);
     timeZone = builtins.get(org.enso.interpreter.node.expression.builtin.date.TimeZone.class);
-    special = new Special(language);
     warning = builtins.get(Warning.class);
+
+    error = new Error(this, context);
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java:166]: Does this modification has any meaning? Is the order of the initialization of the builtins now important?

**Review by Akirathan — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java:166]: It was when I was trying to read `Nothing` from `Error` constructor. First of all I am initializing the _no code_ `builtins.get` and only then I am initializing objects with complex constructors that can make callbacks to `Builtins` again.

Not really necessary anymore, but probably more sane than the original version.
