### PR TITLE
Numeric input does not allow non-numeric value

### LINKED ISSUE #9838: Entering `'` in a numeric input widget breaks the node
By accident I typed `8'` in a number input widget and pressed enter.

https://github.com/enso-org/enso/assets/1436948/10c1862b-7264-49d5-9ccb-2d96e204fea9

### Actual behaviour

```
operator3158.filter 'Grade' ( ( (Filter_Condition.Equal) ( 8 ( '))))
```

image

This led to the node becoming unparseable and display wrongly in the GUI.

### Expected behaviour

The value should not be submitted, I probably should get some warning that `'` is not a valid character in the numeric input.

Definitely the node should not become unparseable.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #9838 (see the "backlog refinement" comment there).

When someone want's to accept invalid input, it gets reverted to last recorded valid value.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~

### CODE REVIEW

File: app/gui2/shared/ast/tree.ts [hunk 1]
```diff
@@ -1825,6 +1826,10 @@ export class MutableNumericLiteral extends NumericLiteral implements MutableAst
 export interface MutableNumericLiteral extends NumericLiteral, MutableAst {}
 applyMixins(MutableNumericLiteral, [MutableAst])
 
+export function isNumericLiteral(s: string) {
+  return is_numeric_literal(s.trim())
```
Comment (Frizi) [inline app/gui2/shared/ast/tree.ts]: Not sure about trim here. Submitting code expresisons with trailing spaces can cause issues, so effectively ignoring them in this method seems bad. If you want to trim the inputted code, do it before calling this method.

File: app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue [hunk 2]
```diff
@@ -10,9 +10,9 @@ import { computed, ref, type ComponentInstance } from 'vue'
 const props = defineProps(widgetProps(widgetDefinition))
 const inputComponent = ref<ComponentInstance<typeof NumericInputWidget>>()
 
-function setValue(value: number | string) {
+function setValue(value: string | undefined) {
   props.onUpdate({
-    portUpdate: { value: value.toString(), origin: props.input.portId },
+    portUpdate: { value: value ?? '', origin: props.input.portId },
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue]: `undefined` probably should be propagated as such, as it correctly signals a removal of an argument. Using empty string here can introduce issues by retaining unnecessary extra spaces.

**Review by Frizi — CHANGES_REQUESTED** [review]

File: app/gui2/src/components/widgets/NumericInputWidget.vue [hunk 3]
```diff
@@ -21,6 +22,16 @@ const MIN_CONTENT_WIDTH = 56
 
 // Edited value reflects the `modelValue`, but does not update it until the user defocuses the field.
 const editedValue = ref('')
+// Last value which is a parseable number. It's a string, because the Enso number literals differ from js
+// representations.
+const lastValidValue = ref<string>()
+watch(editedValue, (newValue, oldValue) => {
+  if (newValue != oldValue) {
```
Comment (kazcw) [inline app/gui2/src/components/widgets/NumericInputWidget.vue]: The watcher will not be called if this condition is false.

File: app/gui2/src/components/widgets/NumericInputWidget.vue [hunk 4]
```diff
@@ -91,13 +102,14 @@ const inputStyle = computed<CSSProperties>(() => {
 })
 
 function emitUpdate() {
-  if (valueString.value !== editedValue.value) {
-    emit('update:modelValue', editedValue.value)
+  if (props.modelValue !== lastValidValue.value) {
```
Comment (kazcw) [inline app/gui2/src/components/widgets/NumericInputWidget.vue]: A `number` and a `string` will never be strictly equal.

**Review by Frizi — APPROVED** [review]

File: app/gui2/src/components/widgets/NumericInputWidget.vue [hunk 5]
```diff
@@ -21,6 +22,16 @@ const MIN_CONTENT_WIDTH = 56
 
 // Edited value reflects the `modelValue`, but does not update it until the user defocuses the field.
 const editedValue = ref('')
+// Last value which is a parseable number. It's a string, because the Enso number literals differ from js
+// representations.
+const lastValidValue = ref<string>()
+watch(editedValue, (newValue, oldValue) => {
+  if (newValue != oldValue) {
+    if (newValue == '' || is_numeric_literal(newValue)) {
```
Comment (kazcw) [inline app/gui2/src/components/widgets/NumericInputWidget.vue]: I think it would be nice to re-export `is_numeric_literal` from a higher level module with our JS naming convention. Whether it is an FFI call is an implementation detail.

**Review by kazcw — COMMENTED** [review]
Two general notes:
- Should we give the user some kind of feedback before/after discarding their invalid input?
- I think committing a previous value is odd; for example, if a user types a number, selects it, pastes something invalid (replacing the previous number), and commits, then we would commit a value that the user never attempted to commit and that has no relation to the value the user attempted to commit.

**Review by kazcw — CHANGES_REQUESTED** [review]
(Previous review)

**Comment by farmaazon** [comment]
> * I think committing a previous value is odd; for example, if a user types a number, selects it, pastes something invalid (replacing the previous number), and commits, then we would commit a value that the user never attempted to commit and that has no relation to the value the user attempted to commit.

I may refer to the previously committed value. I just wanted to keep user's input in case of trivial typos, like typing `'` or anything else right before pressing enter, and do something simpler than trying to somehow "fix" the input myself.

> Should we give the user some kind of feedback before/after discarding their invalid input?

The reverting value is sufficient feedback _after_ IMO. As for feedback _before_, I feel it's a bit hard to implement in every case, because we commit on defocus, and we may be defocused with the entire window (so it would be impossible to give focus back). The only way I could think is make some highlight, but I'm not sure how to make it looking nice.

**Review by kazcw — APPROVED** [review]
