### PR TITLE
Detect conflicts between exported types and FQNs

### LINKED ISSUE #5902: Fully qualified names including same type and module names are not resolved properly
When attempting to use a fully qualified name inside an expression, some FQNs are triggering an unexpected error, failing to resolve. It hapens whenever the path contain a module, which itself contain a type of the same name (e.g. `Error`, `Problem_Behavior`).

image

The resolution is eagerly resolving a type when its name matches module name. For example, following node is resolved to a type, even though the path only resolves to a module (this is likely an expected behavior):
image

When resolving longer paths with subpaths matching this scenario, the whole resolution fails.

Example code:
```
main =
  Standard.Base.Error.Problem_Behavior.Problem_Behavior.Ignore
```

Reported error:
```
Method `Problem_Behavior` of Error could not be found.
```

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Exporting types named the same as the module where they are defined in `Main` modules of library components may lead to accidental name conflicts. This became apparent when trying to access `Problem_Behavior` module via a fully qualified name and the compiler rejected it. This is due to the fact that `Main` module exported `Error` type defined in `Standard.Base.Error` module, thus making it impossible to access any other submodules of `Standard.Base.Error` via a fully qualified name.

This change adds a warning to FullyQualifiedNames pass that detects any such future problems.
While only `Error` module was affected, it was widely used in the stdlib, hence the number of changes.

Closes #5902.

### Important Notes

I left out the potential conflict in micro-distribution, thus ensuring we actually detect and report the warning.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] ~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala [hunk 1]
```diff
@@ -680,7 +680,7 @@ class Compiler(
     * Given module A/B/C.enso
     * ````
     *   type C
-    *       type C a
+    *       C a
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala:721]: If we can catch this now, then great!

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala:721]: This documentation was using the outdated syntax

File: distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
Comment (jdunkerley) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: Can we move the `throw` method up from the type to the module so we keep `Error.throw` please.

**Review by jdunkerley — CHANGES_REQUESTED** [review]

File: distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
Comment (hubertp) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: We can, sure. Although I understood that this would be deprecated eventually.

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: No we use `Error.throw` everywhere - we are minimising panics but we use errors all the time.

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: And I think while we are minimising panics, we are not planning to deprecate them either, right? We don't want to expose them to users, but they are a necessary part of internal error handling.

Comment (hubertp) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: Actually, it's not as straightforward as it seems. This is because, again, of the name conflict with the exported `project.Error` in `Main.enso`

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: how about the following then ...
Lets rename `Standard.Base.Error.*` to `Standard.Base.Errors.*` (Common etc...) and keep `Standard.Base.Error.Error` (i.e. the Error.enso file) as is,

I feel that is the cleaner?

Comment (hubertp) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: > And I think while we are minimising panics, we are not planning to deprecate them either, right? We don't want to expose them to users, but they are a necessary part of internal error handling.

I was referring to having (static) module methods.

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: ah ok - I thought you were meaning throwing errors :)

Comment (hubertp) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:1]: done

**Review by jdunkerley — APPROVED** [review]
