### PR TITLE
 Cache dataflow errors

### LINKED ISSUE #7140: If a node fails with dataflow error in batch run, it immediately falls back to a dry run afterwards
See the video below:

https://github.com/enso-org/enso/assets/1436948/e9bfa027-737c-482e-91c7-5fe479055808

The Main file of the project used is as follows:
```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all

import Standard.Base.Errors.Common.Dry_Run_Operation
import Standard.Base.Errors.Illegal_Argument.Illegal_Argument
import Standard.Base.Runtime.Context
import Standard.Visualization

my_operation name =
    case Context.Output.is_enabled of
        True -> if name == "will error" then Error.throw (Illegal_Argument.Error "The operation failed due to some reason.") else "Batch run succeeded"
        False ->
            result = "Dry run succeeded"
            warning = Dry_Run_Operation.Warning "But this is just a dry run"
            Warning.attach warning result

main =
    name1 = "foobar"
    op1 = my_operation name1
    text1 = "will error"
    operator1 = my_operation text1
```

We can see that first the nodes are in dry run mode - because we are live editing.

Once we hit the play button, both nodes do run. The first one runs and succeeds, returning a changed message. But the second one is more curious - it runs and results in an error (as planned). We can see that the error is reported as the node border turns red for a brief moment. But before we can even try to hover mouse over it, we can see that it is **re run again** back in dry-run mode and the error disappears, being replaced with the result of the dry run.

This makes it impossible to inspect any errors that occurred during a batch run. I also don't think this is what should happen in general - intuitively - I'd think that after the batch run the workflow should stay as it completed the batch run - any further updates of the workflow should be triggered by the user editing some nodes/inputs - **not automatically**.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

The logic in instrumentation specifically prohibited caching of panics (added in https://github.com/enso-org/enso/pull/1611).
Except it seems that the restriction was too aggressive because dataflow errors could be cached.
This indirectly fixes the problem with dataflow error in the context of a (temporary) change in execution context, which should keep around the old value.

Closes #7140.

After the fix:
[fix_7140.webm](https://github.com/enso-org/enso/assets/292128/b8d522db-985a-4e57-bbf1-a075d14d39a2)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

~~- [ ] The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by radeusgd** [comment]
Any reason we are _not_ caching panics then?

It appears that if we keep not caching them, the same issue as described in #7140 will persist whenever a function panics.

**Comment by radeusgd** [comment]
I see now [`02f801b` (#1611)](https://github.com/enso-org/enso/pull/1611/commits/02f801bd69ba09947533bd33fb19e9f1beeb4cab#diff-509f098ab5960683c864835d027738aed40b00f9dcc4a4c4a3c7395df53e5f14R385-R387).

So it seems we have a conflict:
- caching Panics will cause issues with rerunning problematic nodes, especially when adding an import to resolve the problem,
- not caching them, will cause problems of the workflow being recomputed if a dry-run panics.

**Comment by hubertp** [comment]
> I see now [`02f801b` (#1611)](https://github.com/enso-org/enso/pull/1611/commits/02f801bd69ba09947533bd33fb19e9f1beeb4cab#diff-509f098ab5960683c864835d027738aed40b00f9dcc4a4c4a3c7395df53e5f14R385-R387).
> 
> So it seems we have a conflict:
> 
> * caching Panics will cause issues with rerunning problematic nodes, especially when adding an import to resolve the problem,
> * not caching them, will cause problems of the workflow being recomputed if a dry-run panics.

Yes, that's the reason. I knew that Panics can still cause problems but this is a much more tricky/less common issue than regular dataflow errors. I would suggest that we file a separate ticket instead, just for tracking panics.

**Comment by radeusgd** [comment]
> I would suggest that we file a separate ticket instead, just for tracking panics.

I started a discussion then so we can decide how we want to handle this: https://github.com/orgs/enso-org/discussions/7203

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/7203">Caching results of a node if they panic · enso-org · Discussion #7203</a></strong></div><div>The discussion under the PR fixing caching of dataflow errors (#7193) highlights a 'conflict' between two functionalities that we want. We are caching regular results, and with #7193 we will be (ar...</div></blockquote>

File: engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala [hunk 1]
```diff
@@ -1964,4 +1977,106 @@ class RuntimeErrorsTest
...
+    val mainRes1Id = metadata.addItem(209, 1)
+
+    val code =
+      """import Standard.Base.Error.Error
+        |import Standard.Base.Errors.Illegal_Argument.Illegal_Argument
+        |
+        |main =
+        |    x = Error.throw (Illegal_Argument.Error "The operation failed due to some reason.")
+        |    x
+        |""".stripMargin.linesIterator.mkString("\n")
```
Comment (JaroslavTulach) [inline engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala:1998]: Should the code use `mkString(newline)`? Or what is the point of defining `newline` variable, when it is not used?

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 2]
```diff
@@ -250,7 +251,7 @@ public void onReturnExceptional(VirtualFrame frame, Throwable exception) {
     }
 
     private void onExpressionReturn(Object result, Node node, EventContext context) throws ThreadDeath {
-      boolean isPanic = result instanceof AbstractTruffleException;
+      boolean isPanic = result instanceof AbstractTruffleException && !(result instanceof DataflowError);
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:254]: Is there any system in these checks at all (another example at https://github.com/enso-org/enso/pull/7205/files#diff-bfe95bc1ca4b016dccbab4fc97f23809a6c83d040de6ca8a6a615f02378e1a59R357)?

I am afraid we are just patching random parts of the Enso system without having a consistent classification of the objects and their roles. Everything seems to hold together just with some unit tests. At least we have them, but still...

**Review by JaroslavTulach — APPROVED** [review]
Sane & tested.

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:254]: I don't see a connection between this and the mentioned PR other than that we deal with DataFlowError. Yes, it's patching (not so random) parts of the Enso system and so what is wrong with that?
Alternatively we shouldn't match on `AbstractTruffleException` at all and wrap it into something we can control. Is it a better solution? That's debatable.

File: engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala:1998]: `newline` is used in other parts in string interpolation. Having said that, it seems `linesIterator.mkString("\n")` is spurious in this and other locations.

**Comment by hubertp** [comment]
@radeusgd could I get a :+1: while the discussion considers the, much less frequent, case of panics?

**Review by radeusgd — APPROVED** [review]
Sure.

The fix looks ok, but I agree with the notion brought up by @JaroslavTulach - the complexity of the system grows and there is a lot of special cases and it does not seem like we have a systematic way of handling them - that feels a bit worrying in terms of extending it in the future - but that is a topic not for this PR.

@JaroslavTulach shall we start a discussion about this? You are probably better suited to express the issue clearly (I have more like a vague intuition here)

**Review by GregoryTravis — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

**Comment by hubertp** [comment]
I will see if I can extract some of the special logic for panics and other errors so that it is defined in a single place, if possible. But as a follow up PR.

File: engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala:1998]: Reverted my cleanup of `linesIterator.mkString("\n")`. I think Windows doesn't like it.

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java:254]: > what is wrong with that?

It is perfectly _pragmatic behavior_. I am a huge fan of [pragmatism](http://wiki.apidesign.org/wiki/Pragmatic). However sometimes I a masking myself - shouldn't we be more [rationalistic]http://wiki.apidesign.org/wiki/Rationalism) when designing a language?

Possibly more consistency than patching would make the language better...
