### PR TITLE
Vue entrypoint

### LINKED ISSUE #11185: Change IDE entry point to Vue App
* Let the project be a Vue project which uses react component inside (at the moment, just entire dashboard) - move plugins there, and some stuff (like logging setup) from `app/gui2/src/App.vue`
* There should be main.js mounting `App.vue` which in turn sets up react component.
* React should mount `ProjectView` component.

### LINKED ISSUE #11923: Extra search query param on the editor tab breaks the whole editor
Recently we got a bug request from a User, with broken `Project view` because it failed to recognize the search param 'starModalDefaultOpen`

Proposing to make the `Project view` less strict on extra search params in the URL.

User's issue: https://github.com/enso-org/enso/issues/11912

Related discussion: https://discord.com/channels/401396655599124480/1201853512409939968/1226854319983300728

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #11185 
Fixes #11923

I moved (and simplified) some setup. Mostly, the entry point sets up general behavior on page load, App.vue is the root, and the react-specific setups are now in `ReactRoot` component. The old App.vue is now just the ProjectView.vue.

Removed some options which are no longer relevant since there's just a single GUI package.

I tried to put the ProjectView component into dashboard layout, but unfortunately, veaury is not helpful here, as it unsets all styles in its wrapper.

Also, GUI no longer displays Help view; if there's an unrecognized option we just print a warning and continue.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/entrypoint.ts [hunk 1]
```diff
@@ -1,57 +1,154 @@
...
+    persisterStorage: {
+      getItem: async (key) => idbKeyval.get(key, store),
+      setItem: async (key, value) => idbKeyval.set(key, value, store),
+      removeItem: async (key) => idbKeyval.del(key, store),
+      clear: async () => idbKeyval.clear(store),
+    },
+  })
+}
+
+function imNotSureButPerhapsFixingRefreshingWithAuthentication() {
```
Comment (farmaazon) [inline app/gui/src/entrypoint.ts:151]: @somebody1234 I don't know what exactly the snippet below fixes. The Note is not clear to me.
I tracked that you are the original author, could you explain (and make a better name for this method :) )

File: app/gui/src/ReactRoot.tsx [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+  const ydocUrl = (config.engine.ydocUrl || resolveEnvUrl(YDOC_SERVER_URL)) ?? null
+  const initialProjectName = config.startup.project || null
+  invariant(portalRoot, 'PortalRoot element not found')
+
+  return (
+    // TODO [ao]: This wrapping element should be in App.vue, but veaury's wrapper for react sets
+    //  `style="all: unset"` breaking our layout.
+    //  See https://github.com/gloriasoft/veaury/issues/158
+    <div
+      id="enso-dashboard"
```
Comment (MrFlashAccount) [inline app/gui/src/ReactRoot.tsx]: Do we need `enso-dashboard` wrapper though? We use this selector only in a few places - define base styles, and in utils, where we detect whenever an element should be hidden by click: `app/gui/src/dashboard/components/AriaComponents/Dialog/utilities.ts`

Guess we can safely migrate from `enso-dashboard` to `enso-app` and remove the wrapper

File: app/gui/src/ReactRoot.tsx [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+      className={`${['App', 'enso-dashboard', ...props.classSet.keys()].join(' ')}`}
```
Comment (MrFlashAccount) [inline app/gui/src/ReactRoot.tsx]: What's these classes stand for?

File: app/gui/src/dashboard/layouts/Editor.tsx [hunk 4]
```diff
@@ -244,16 +196,18 @@ function EditorInternal(props: EditorInternalProps) {
...
     remoteBackend,
   ])
+  // EsLint does not handle types imported from vue files and their dependences.
+  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
+  const key: string = appProps.projectId
 
   // Currently the GUI component needs to be fully rerendered whenever the project is changed. Once
   // this is no longer necessary, the `key` could be removed.
-  return AppRunner == null ? null : <AppRunner key={appProps.projectId} {...appProps} />
+  return <ProjectView key={key} {...appProps} />
```
Comment (MrFlashAccount) [inline app/gui/src/dashboard/layouts/Editor.tsx]: For the future: can we wrap the editor into [KeepAlive](https://vuejs.org/guide/built-ins/keep-alive.html) ?

We're looking into unmounting dom nodes when user switch tabs

**Review by MrFlashAccount — APPROVED** [review]
LGTM, left a few comments

File: app/gui/src/dashboard/layouts/Editor.tsx (hunk 4 above)
Comment (farmaazon) [reply app/gui/src/dashboard/layouts/Editor.tsx]: I'm not sure if KeepAlive would do what you want? Its docs say about persisting _dynamic_ component (i.e. an instance inside vue's <component>) - so if the tabs would not be rewritten to vue, the component would still be lost.

File: app/gui/src/ReactRoot.tsx (hunk 3 above)
Comment (farmaazon) [reply app/gui/src/ReactRoot.tsx]: We have a context allowing just add any class to application root, so far used only when dragging elements.

File: app/gui/src/dashboard/layouts/Editor.tsx (hunk 4 above)
Comment (MrFlashAccount) [reply app/gui/src/dashboard/layouts/Editor.tsx]: We'll pass the `hidden` prop to vue and won't unmout the tab content (this is what we do now). So unmounting will be on the vue side, within the `<KeepAlive/>` boundary

**Comment by farmaazon** [comment]
Addressed the comments + applied a hack discovered with @Frizi avoiding issues with veaury wrappers (and allowing reducing number of position: absolutes).

File: app/gui/src/App.vue [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+  if (appConfigValue.value.window.vibrancy) {
+    document.body.classList.add('vibrancy')
+  }
+})
+</script>
+
+<template>
+  <Teleport to="body">
+    <TooltipDisplayer :registry="appTooltips" />
+  </Teleport>
```
Comment (Frizi) [inline app/gui/src/App.vue]: Do we still need this teleport? The tooltip displayer could probably be rendered just at the bottom of this template.

File: app/gui/src/dashboard/layouts/Editor.tsx [hunk 6]
```diff
@@ -1,67 +1,33 @@
...
-
-// =================
-// === Constants ===
-// =================
-
-const IGNORE_PARAMS_REGEX = new RegExp(`^${appUtils.SEARCH_PARAMS_PREFIX}(.+)$`)
+// eslint-disable-next-line no-restricted-syntax
+const ProjectViewTab = applyPureVueInReact(ProjectViewTabVue) as (
+  props: ProjectViewTabProps,
+) => JSX.Element
```
Comment (Frizi) [inline app/gui/src/dashboard/layouts/Editor.tsx:31]: Why is this cast necessary?

File: app/gui/src/project-view/ProjectView.vue [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+  cursor: grab;
+}
+
+:deep(.clickable) {
+  cursor: pointer;
+}
+
+:deep([data-use-vue-component-wrap]) {
+  display: contents !important;
+}
```
Comment (Frizi) [inline app/gui/src/project-view/ProjectView.vue]: This is a repeat of style from App.

File: app/gui/src/project-view/ProjectViewTab.vue [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+
+const _props = defineProps<{
+  hidden: boolean
+  projectViewProps: ComponentProps<typeof ProjectView>
+}>()
+</script>
+
+<template>
+  <KeepAlive>
+    <component :is="hidden ? null : ProjectView" v-bind="projectViewProps"></component>
```
Comment (Frizi) [inline app/gui/src/project-view/ProjectViewTab.vue]: Could this be simplified to this?
```
<ProjectView v-if="!hidden" v-bind="projectViewProps" />
```

File: app/gui/src/project-view/stores/project/index.ts [hunk 9]
```diff
@@ -112,36 +105,29 @@ export const [provideProjectStore, useProjectStore] = createContextStore(
     const doc = new Y.Doc()
     const awareness = new Awareness(doc)
 
-    const config = injectGuiConfig()
```
Comment (Frizi) [inline app/gui/src/project-view/stores/project/index.ts:115]: YES thank you! This really needed to go.

File: app/gui/src/project-view/stores/project/index.ts [hunk 10]
```diff
@@ -103,7 +89,14 @@ export type ProjectStore = ReturnType<typeof useProjectStore>
...
   'project',
-  (props: { projectId: string; renameProject: (newName: string) => void }) => {
+  (props: {
+    projectId: string
+    projectName: string
+    projectDisplayedName: string
+    projectNamespace?: string | undefined
+    renameProject: (newName: string) => void
+    engine: LsUrls
+  }) => {
```
Comment (Frizi) [inline app/gui/src/project-view/stores/project/index.ts]: I think it's time to move that type to a separate `interface`.

**Review by Frizi — APPROVED** [review]

File: app/gui/src/dashboard/layouts/Editor.tsx (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/dashboard/layouts/Editor.tsx:31]: Otherwise I get a typecheck error.
```
src/dashboard/layouts/Editor.tsx:212:11 - error TS2786: 'ProjectViewTab' cannot be used as a JSX component.
  Its type 'Function' is not a valid JSX element type.

212   return <ProjectViewTab key={key} {...appProps} />
              ~~~~~~~~~~~~~~
```
JSX element cannot be just any `Function`, and this is what is returned from veaury. If you know better way to fix this error, please let me know.

Comment (Frizi) [reply app/gui/src/dashboard/layouts/Editor.tsx:31]: That's annoying, but I guess fine for now. It looks like a typing bug in veaury.
