### PR TITLE
Log nothing when class is found

### LINKED ISSUE #7895: Spurious warning when loading inner Java classes into Enso
https://github.com/enso-org/enso/commit/6cbd111bad50afeeb6bac97791be667ab7f54c22 Added support for Espresso.
It also improved support for loading inner classes.

Unfortunately since then we can get spurious warnings:
```
[WARN] [2023-09-20T14:06:50+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class com.ibm.icu.text.Normalizer2.Mode is not allowed or does not exist.
[WARN] [2023-09-20T14:06:51+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class java.net.http.HttpRequest.BodyPublisher is not allowed or does not exist.
```

Steps to reproduce:
```
> cat hello-world.enso 
from Standard.Base import all

main =
  IO.println "Hello World!"
```
```
> built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso  --run hello-world.enso
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class com.ibm.icu.text.Normalizer2.Mode is not allowed or does not exist.
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class java.net.http.HttpRequest.BodyPublisher is not allowed or does not exist.
Hello World!
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.compiler.SerializationManager] Serialization manager has been shut down.
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #7895.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Verified manually

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 1]
```diff
@@ -478,9 +480,12 @@ public Object lookupJavaClass(String className) {
           return lookupHostSymbol(pkgName, fullInnerClassName);
         }
       } catch (RuntimeException | InteropException ex) {
-        logger.log(Level.WARNING, null, ex);
+        collectedExceptions.add(ex);
       }
     }
+    for (var ex : collectedExceptions) {
+      logger.log(Level.WARNING, null, ex);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:487]: Print out all collected exceptions, return `null` and the system to throw Enso `PanicException`

**Review by radeusgd — APPROVED** [review]

**Review by Akirathan — APPROVED** [review]

**Review by hubertp — APPROVED** [review]
