### PR TITLE
Import polyglot java inner classes

### LINKED ISSUE #6678: Cannot polyglot java import innerclasses and use them in type signatures
We had to mitigate [74c6f99](https://github.com/enso-org/enso/pull/6655/commits/74c6f99070fa5c5fd71bb04a7960cb5faaf6a30c) as one cannot:
- import inner class d434ec5
- import outer class and reference inner class
- importing `Outer$Inner` yields an Enso compiler problem.

The `d434ec5` commit was:
```diff
enso$ git show d434ec5963b637c5f0f1131c33cfd85f19681921
commit d434ec5963b637c5f0f1131c33cfd85f19681921
Author: Jaroslav Tulach <jaroslav.tulach@enso.org>
Date:   Sat May 13 07:45:54 2023 +0200

    Importing HeaderBehavior innerclass directly

diff --git distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
index 61a74c22ef..69f338adfc 100644
--- distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
+++ distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
@@ -10,6 +10,7 @@ import project.Excel.Excel_Section.Excel_Section
 from project.Errors import Invalid_Location, Duplicate_Output_Column_Names, Invalid_Output_Column_Names, Empty_Sheet_Error
 
 polyglot java import org.enso.table.excel.ExcelHeaders
+polyglot java import org.enso.table.excel.ExcelHeaders.HeaderBehavior
 polyglot java import org.enso.table.read.ExcelReader
 polyglot java import org.enso.table.error.InvalidLocationException
 
@@ -30,7 +31,7 @@ prepare_reader_table on_problems result_with_problems =
 
 ## PRIVATE
    Convert Boolean|Infer to the correct HeaderBehavior
-make_java_headers : (Boolean | Infer) -> ExcelHeaders.HeaderBehavior
+make_java_headers : (Boolean | Infer) -> HeaderBehavior
 make_java_headers headers = case headers of
         True -> ExcelHeaders.HeaderBehavior.USE_FIRST_ROW_AS_HEADERS
         Infer -> ExcelHeaders.HeaderBehavior.INFER
```

### PR DESCRIPTION
**Pull request by Akirathan**
### Pull Request Description

Adds the ability to import nested inner classes in `polyglot java import` imports.

### Important Notes

The nested inner class (arbitrary many levels of nesting) is loaded in `IrToTruffle.scala` when scanning polyglot imports of a module. The algorithm just iterates the FQN of the imported class, and tries to resolve the package name, the class name and the inner class name.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala [hunk 1]
```diff
@@ -32,5 +32,57 @@ class JavaInteropTest extends InterpreterTest {
           |""".stripMargin
       eval(code) shouldEqual 21
     }
+
+    "allow importing static inner class and call methods on them" in {
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala]: A test in Java, like `PrintTest`, would be closer to my heart.

Comment (Akirathan) [reply engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala]: The `JavaInteropTest.scala` had already existed. Shall I migrate it to Java then? It should not be difficult, these are just a few tests.

Comment (Akirathan) [reply engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala]: Migrated to Java in e9dad1ddfa7fa1d2c5bc03c1d835623b243875e2

Comment (JaroslavTulach) [reply engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala]: Thank you, Pavel. It feels so much _warmer_ and _welcoming_!

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 2]
```diff
@@ -21,14 +22,7 @@ import org.enso.compiler.pass.analyse.{
...
 import org.enso.compiler.pass.optimise.ApplicationSaturation
-import org.enso.compiler.pass.resolve.{
-  ExpressionAnnotations,
-  GenericAnnotations,
-  GlobalNames,
-  MethodDefinitions,
-  Patterns,
-  TypeSignatures
-}
+import org.enso.compiler.pass.resolve._
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: In Java I prefer explicit imports rather than wild card ones - they give the code more clarity. I guess Scala deserves the same treatment.

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 3]
```diff
@@ -703,6 +699,76 @@ class IrToTruffle(
...
+    */
+  private def tryLookupHostSymbol(name: String): Object = {
+    val items = name.split("\\.")
+    for (idx <- (items.length - 1).to(0) by -1) {
+      val pkgName   = items.take(idx).mkString(".")
+      val className = items(idx)
+      // The rest of the name is interpreted as nested class name
+      val nestedClassPart = items.drop(idx + 1)
+      Try(
+        context.getEnvironment.lookupHostSymbol(pkgName + "." + className)
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: This (e.g. Scala code) is an unexpected place for the fix. I think it would be better to "fix" `lookupHostSymbol`. Except my _"Scala problem"_, we want to make sure all **host symbols resolution** behaves the same. I know there is another place that is using `lookupHostSymbol` and now those two would behave inconsistently.

Please replace `context.getEnvironment.lookupHostSymbol` with `EnsoContext.lookupJavaClass` and move all the logic there. Make sure nobody calls `lookupHostSymbol` directly anymore.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
Please introduce `EnsoContext.lookupJavaClass` and use it instead of `lookupHostSymbol` everywhere in the codebase.

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: Done in 74c6cfe5ca1bb7c09727bf5ff5bce5823101b546 - now we have `EnsoContext.lookupJavaClass`.

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: I changed my IDE settings now. The imports, in general, seem not to be mandated by `scalafmt` or `javafmt`. We should ensure on our own that our IDEs don't replace imports with wildcard imports.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 4]
```diff
@@ -345,6 +353,35 @@ public Optional<Module> findModuleByExpressionId(UUID expressionId) {
...
+  /**
+   * Tries to lookup a Java class (host symbol in Truffle terminology) by its fully qualified name.
+   * This method also tries to lookup inner classes. More specifically, if the provided name
+   * resolves to an inner class, then the import of the outer class is resolved, and the inner class
+   * is looked up by iterating the members of the outer class via Truffle's interop protocol.
+   *
+   * @param className Fully qualified class name, can also be nested static inner class.
+   * @return The java class or Optional.empty if not found.
+   */
+  public Optional<Object> lookupJavaClass(String className) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java]: Wish: no `Optional` please!

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java]: Removed in a7d41ffff96c25c8dd5c529809b9f2ba3f45054b - I wanted to be consistent with the rest of the public methods in `EnsoContext`. But I prefer standard `null` usage in Java to `Optional` as well.

**Review by hubertp — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
[NI build is failing](https://github.com/enso-org/enso/actions/runs/5090249830/jobs/9148831908?pr=6818#step:10:1247):
```
at parsing sun.awt.X11.XSelection.<clinit>(XSelection.java:107)
at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
```
I am not sure what's the case, but certainly it'd be better to compile our executables without dependencies on X11.

**Comment by Akirathan** [comment]
> [NI build is failing](https://github.com/enso-org/enso/actions/runs/5090249830/jobs/9148831908?pr=6818#step:10:1247):
> 
> ```
> at parsing sun.awt.X11.XSelection.<clinit>(XSelection.java:107)
> at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
> ```
> 
> I am not sure what's the case, but certainly it'd be better to compile our executables without dependencies on X11.

I have looked into that, and it seems that `sun.awt.X11.XSelection.<clinit>` is now transitively called on this PR, but is not on latest develop. I have simply compared the output directories when running `native-image` with `--diagnostics-mode`.

Dependencies on X11, e.g., `sun.awt.X11.XToolkit` (a transitive dependency of java.awt?) are included even on develop. I am not sure where are they used from.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 5]
```diff
@@ -345,6 +353,35 @@ public Optional<Module> findModuleByExpressionId(UUID expressionId) {
...
+  /**
+   * Tries to lookup a Java class (host symbol in Truffle terminology) by its fully qualified name.
+   * This method also tries to lookup inner classes. More specifically, if the provided name
+   * resolves to an inner class, then the import of the outer class is resolved, and the inner class
+   * is looked up by iterating the members of the outer class via Truffle's interop protocol.
+   *
+   * @param className Fully qualified class name, can also be nested static inner class.
+   * @return If the java class is found, return it, otherwise return null.
+   */
+  public Object lookupJavaClass(String className) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:367]: Hide this behind `@TruffleBoundary`. It is too complex code to be PEed.

**Review by JaroslavTulach — APPROVED** [review]
Nice!

**Comment by Akirathan** [comment]
I have "fixed" native-image building by including all the classes in `--initialize-at-buildtime` by default in https://github.com/enso-org/enso/pull/6818/commits/e250a89d74d9c52c6923a3a2d9717f71430d0741. This should, theoretically, give us better startup performance of our native image, since the native image, by default, initializes all the classes at runtime. Moreover, we used to pass `--initialize-at-buildtime=` (i.e. empty option) to `native-image`, which is deprecated. More information in #6879.

File: project/NativeImage.scala [hunk 6]
```diff
@@ -122,7 +151,7 @@ object NativeImage {
         quickBuildOption ++
         debugParameters ++ staticParameters ++ configs ++
         Seq("--no-fallback", "--no-server") ++
-        Seq("--initialize-at-build-time=") ++
```
Comment (Akirathan) [inline project/NativeImage.scala:125]: This option was deprecated. Moreover, it has never included all the classes for build time initialization. In fact, it seems that the effect of this option was a no-op. At least for the GraalVM native-image since version 21.3.0.

File: project/NativeImage.scala [hunk 7]
```diff
@@ -16,6 +16,25 @@ object NativeImage {
...
   private val includeDebugInfo: Boolean = false
 
+  /**
+   * List of classes that should be initialized at build time by the native image.
+   * Note that we strive to initialize as much classes during the native image build
+   * time as possible, as this reduces the time needed to start the native image.
+   * One wildcard could theoretically be used instead of the list, but to make things
+   * more explicit, we use the list.
+   */
+  private val defaultBuildTimeInitClasses = Seq(
```
Comment (Akirathan) [inline project/NativeImage.scala:25]: @JaroslavTulach Do you want to move this to `native-image.properties` inside `engine-runner` project? I think it is a bit better here, since all the other information for native image is kept in this source.

Comment (JaroslavTulach) [reply project/NativeImage.scala:25]: I don't know.

All I see is that this is a long list with very wide wildcards - `scala`, `java`, `sun`! `com`! `org`! - if it works for our purposes, then great, but it is _blank check_ that matches almost everything.

Comment (Akirathan) [reply project/NativeImage.scala:25]: > but it is blank check that matches almost everything.

Isn't that the purpose? We want to match as many classes as possible for `--initialize-at-buildtime`.

I "tested" the native image on:
```
./runner --run engine/runner/src/test/resources/Factorial.enso 6
```
and it works as expected.

Comment (Akirathan) [reply project/NativeImage.scala:25]: @JaroslavTulach Do you have any other ideas what to test? Importing anything from `Standard.Base` does not work, neither on the latest `develop`. The size of the generated binary seems to be the same. The only other thing that is worth checking is code size and heap size (e.g. by GraalVM dashboard). Last time I have checked that, it did not work out of the box. I am uncertain whether I should spend any more time checking something on the native image. Can we merge this?

Comment (JaroslavTulach) [reply project/NativeImage.scala:25]: > We want to match as many classes as possible for `--initialize-at-buildtime`.

As many Enso interpreter classes, true. I don't care about the other ones and certainly I _don't want to force them_ to be initialized in build time. I just want to _allow them to be initialized_ when they are needed transitively.

> Do you have any other ideas what to test?

There has always been just a single test:
```
./runner --run engine/runner/src/test/resources/Factorial.enso <a number>
```
that's all we have until #4877 or similar allows us to use standard libraries.

Comment (JaroslavTulach) [reply project/NativeImage.scala:25]: > Can we merge this?

Of course! How can support for polyglot inner classes (hidden behind `@TruffleBoundary`)  influence native binary? 

> what to test? 
> - The size of the generated binary seems to be the same. 
> - code size and heap size

It is an interesting insight into our native image version of Enso, but...
 
> - I should spend any more time checking something on the native image. 

...I don't think it is relevant for this PR. Just merge.

Comment (Akirathan) [reply project/NativeImage.scala:25]: > As many Enso interpreter classes, true. I don't care about the other ones and certainly I don't want to force them to be initialized in build time. I just want to allow them to be initialized when they are needed transitively.

Right. This is precisely how this list originated - I added `org.enso` first to the `--initialize-at-buildtime`, and then added all the classes that are initialized from any class from `org.enso`. I understand that this list seems almost like a wildcard, but is there any other, simpler, solution?
