### PR TITLE
Table of `Persistance.Reference` at the end of the stream

### LINKED ISSUE #9361: Support cycles in the serialized IR structure
As part of #8652 I'm extending the bindings map with additional metadata that results in a cycle within the IR. Currently, that causes the IR serialization to fail with `StackOverflow`, because there is no support for cycles.

We want to expand our IR serialization to support such looping.

I've added a few tests demonstrating the expected behaviour on the branch [wip/persistance-loops](https://github.com/enso-org/enso/compare/wip/persistance-loops?expand=1).

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #9361 by delaying storing of `Persistance.Reference` instances and creating their table at the end of the stream.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java [hunk 1]
```diff
@@ -171,5 +173,84 @@ public record IntegerSupply(Supplier<Integer> supply) {}
...
+    var obj1 = new LongerLoop1(1, Persistance.Reference.of(obj2));
+    obj3.y = Persistance.Reference.of(obj1);
+
+    var loaded1 = serde(LongerLoop1.class, obj1, -1);
+    var r2 = loaded1.y().get(LongerLoop2.class);
+    var r3 = r2.y().get(LongerLoop3.class);
+    var r1 = r3.y().get(LongerLoop1.class);
+
+    assertFalse(
+        "Currently the loaded1 reference isn't shared with r3.y() reference", loaded1 == r1);
```
Comment (JaroslavTulach) [inline lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java]: The current behavior isn't ideal, but this situation is unlikely to happen in practice. It is unlikely the root of the deserialized graph would be part of the loop and for references inside of deserialized graph the cycle works well as the `for` loop below demonstrates.

Comment (JaroslavTulach) [reply lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java]: The condition is reverted since 03494b8 - the root object can now be part of the `Reference` cycle.

File: engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java [hunk 2]
```diff
@@ -508,4 +509,44 @@ public record RefHolder(Persistance.Reference<UUID> id) {
...
+  @Test
+  public void testLoop1() throws Exception {
+    Looper looper = new Looper(null);
+    looper.seq = join(looper, nil());
+
+    Looper out = serde(Looper.class, looper, -1);
+    assertSame(out, out.seq().apply(0));
+  }
+
+  @Ignore
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java]: These tests are tricky. `Seq` is _eager on serialization_ and only **lazy on deserialization**. As such these tests are testing something that is not really working per (current) design. I don't want to change `Seq` to be _lazy on serialization_ as that would expand the "indirect references" table at the end of the file. OK to disable/remove these tests, @radeusgd?

Comment (radeusgd) [reply engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java]: Yes it is probably fine.

I think I was adding them because the practical use-case I have in the Types PR relied on Seq and I thought that it could be possible for it to work. But as long as it is possible to rewrite that use-case to still work (which I assume should be possible by breaking the cycle through a `Persistance.Reference` in there), it will be all I need.

Comment (JaroslavTulach) [reply engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java]: OK, the `Seq` looping test removed in 35feca4

> relied on `Seq` .. possible by breaking the cycle through a `Persistance.Reference`

Yes, `Persistance.Reference` shall help you do what's needed. I don't want to modify `Seq` to use `Persitance.Reference` behind the scene, as that comes with additional cost and could significantly increases the size of generated `.bindings` caches.

**Review by Akirathan — APPROVED** [review]

File: engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java]: > Yes, `Persistance.Reference` shall help you do what's needed. 

Awesome!

> I don't want to modify `Seq` to use `Persitance.Reference` behind the scene, as that comes with additional cost and could significantly increases the size of generated `.bindings` caches.

That sounds reasonable indeed.

File: lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java [hunk 3]
```diff
@@ -1,21 +1,28 @@
...
 
+import java.io.IOException;
 import org.enso.persist.PerInputImpl.InputCache;
 import org.enso.persist.Persistance.Reference;
 
 final class PerBufferReference<T> extends Persistance.Reference<T> {
   private final Persistance<T> p;
   private final PerInputImpl.InputCache cache;
   private final int offset;
+  private Object cached;
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java:23]: What is the meaning of the `cached` field? I'm not sure if I understand it.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java [hunk 4]
```diff
@@ -117,6 +182,15 @@ private static final class ReferenceOutput extends DataOutputStream
...
     @Override
     public <T> void writeInline(Class<T> clazz, T t) throws IOException {
+      if (Persistance.Reference.class == clazz) {
+        if (t instanceof Persistance.Reference<?> ref) {
+          var id = this.generator.registerReference(ref);
+          writeInt(id);
+          return;
+        } else {
+          throw new ClassCastException("Expecting Refernece");
+        }
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]:
```suggestion
        Persistance.Reference<?> ref = (Persistance.Reference<?>) t;
        var id = this.generator.registerReference(ref);
        writeInt(id);
        return;
```

nitpick: I think we could rewrite this to a direct cast without the check - the behaviour is the same - if we the type is incorrect, a `ClassCastException` will be thrown - with a more detailed message (the default message not only tells us the expected type but also the actual type which may help recognize the problem source).

File: lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java [hunk 5]
```diff
@@ -241,17 +254,55 @@ static <T> Reference<T> readIndirectAsReference(
...
+      this.readResolve = readResolve;
+      this.map = map;
+      this.refs = new Reference[refs.length];
+      for (var i = 0; i < refs.length; i++) {
+        if (refs[i] < 0) {
+          this.refs[i] = this.refs[0];
+        } else {
+          this.refs[i] = PerBufferReference.cached(null, this, refs[i]);
+        }
+      }
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java]: Can we get some short documentation summary describing the idea behind the `PerBufferReference.cached` and this `InputCache`?

I don't quite see what is the reasoning here, what does it mean for `refs[i] < 0` and why then it's replaced with `refs[0]` etc.

I guess if I took 1-2 hours to try to understand this code I could reverse engineer the idea what is happening here, but I think there should be at least minimal documentation describing the intent here, so that anyone reading the code can have at least a general idea of what is happening here.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java [hunk 6]
```diff
@@ -106,6 +114,63 @@ final int versionStamp() {
...
+      pendingReferences.clear();
+      for (var entry : round) {
+        count++;
+        if (obj == entry.getKey()) {
+          refsData.writeInt(-1);
+          continue;
+        }
+        var at = writeObject(entry.getKey());
+        assert count == entry.getValue() : "Expecting " + count + " got " + entry.getValue();
+        refsData.writeInt(at);
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]:
```suggestion
        if (obj == entry.getKey()) {
          refsData.writeInt(-1);
          continue;
        } else {
          var at = writeObject(entry.getKey());
          assert count == entry.getValue() : "Expecting " + count + " got " + entry.getValue();
          refsData.writeInt(at);
        }
```

This is a very subjective suggestion, but IMHO in this case an `if-else` is much easier to follow than an `if+continue`. It is clearer that this is a 2-way branch from the overall structure - whereas currently at first glance it is unclear if the code after `if` may also be executed if the `if` was hit (it's not because of the `continue`, but that's not visible at first glance).

I'm sorry if I'm too annoying with such suggestions, but the clearer the intent of the code is, the easier it is to understand it as the mental load needed to understand the overall structure decreases, freeing more "brain RAM" to actually think about the underlying concepts. For super easy code that may not matter too much, but this one is not immediately obvious, so making it easier to understand would is IMO beneficial.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java [hunk 7]
```diff
@@ -106,6 +114,63 @@ final int versionStamp() {
...
+   * @param obj the object to write down
+   * @return location of the table {@code int size and then int[size]}
+   */
+  private int writeObjectAndReferences(Object obj) throws IOException {
+    var objAt = writeObject(obj);
+
+    var refsOut = new ByteArrayOutputStream();
+    var refsData = new DataOutputStream(refsOut);
+    refsData.writeInt(-1); // space for size of references
+    refsData.writeInt(objAt); // the main object
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:143]: I appreciate such comments a lot. With such a low-level binary format it is really not immediately clear what is what. Either creating small functions like `writePlaceholder() { refsData.writeInt(-1); }` OR adding comments like this helps immensely with understanding this code.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 6 above)
Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]: Anyway, the above is just a nitpick.

My major problem is - I don't think I understand why adding the `-1` here works. I understand we add -1 because we don't yet know the offset for `obj`. But when do we 'come back' and fix-up these -1s to actual proper ids?

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 7 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:143]: > small functions

This PR introduces [putIntToArray](https://github.com/enso-org/enso/pull/9972/files#diff-9d27b6bd14cc82cf4c3817f34013a7b88be171835fc553b522bf61d255bf0680R56), at least.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 6 above)
Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]: Oh, or is THAT related to the code I asked about moments before - the `InputCache`'s `if (refs[i] < 0) { refs[i] = refs[0]; }` rewrite? I guess most likely YES!

I really think some explanation is needed here. I understood this correlation after carefully reading the whole code and trying to deeply understand the serialization process - but at first look it seemed like just some magic numbers. It would be good if understanding this code did not require guessing.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 7 above)
Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:143]: I'm very happy that it was introduced.

Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:143]: In my ideal world, we'd try to [split the levels of abstraction](https://www.fluentcpp.com/2016/12/15/respect-levels-of-abstraction/) even more and have separate protocol-level semantic `putMainObjectReference` functions delegating to lower-level byte-buffer manipulation `putIntToArray` and `writeInt` functions.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 6 above)
Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]: Also a style thing, so feel free to ignore, but I think it makes more sense to do this `-1` reference fix-up at write time.

While performance-wise it probably does not matter at all, it just seems (to me) to make more sense 'philosophically' for the writer to handle the looping complexity - the reader IMHO should be as dumb as possible, just reading offsets and recreating the necessary structure.

The benefit of that is that the _whole_ logic for the reference reconstruction would be in one module, one place, making it easier to understand what was meant here (although I still think there should be some comment describing the idea). But when it's split over multiple modules like now, and there's no comments, it's much harder to find out what this logic is all about. I'm still lucky that I'm reviewing a single PR so I just see in the diff the relevant changes - if I was reading these modules in the context of the _whole_ codebase, deciphering what this algorithm scattered through multiple files is meant to do would be even harder.

**Review by radeusgd — COMMENTED** [review]
I'm _really really_ happy that the reference loops problems is finally getting addressed! :heart: I will finally be able to proceed with #9361 :)

The logic for resolving the reference loops may not be the most complicated algorithm, but it is non-trivial enough that I think some comments on what was meant are needed - so that it is easier to understand the whole IR caching system that is getting more and more complex.

I'd also suggest considering moving the `-1` reference reconstruction to write-time, not read-time, to make this part of algorithm more localized - thus easier to see 'in whole' at once and thus easier to understand.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java [hunk 8]
```diff
@@ -106,6 +114,63 @@ final int versionStamp() {
...
+          });
+      pendingReferences.clear();
+      for (var entry : round) {
+        count++;
+        if (obj == entry.getKey()) {
+          refsData.writeInt(-1);
+          continue;
+        }
+        var at = writeObject(entry.getKey());
+        assert count == entry.getValue() : "Expecting " + count + " got " + entry.getValue();
```
Comment (radeusgd) [inline lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:158]: tbh I don't think I understand what guarantees that in every iteration this assertion is true.

Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:158]: Hmm, is it a general assumption that the local variable `count` and the field `countReferences` are kept in-sync (i.e. the `countReferences` has the same value when the reference is first created as `count` has when it is written)?

Comment (radeusgd) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:158]: But to my understanding that would suggest that `writeObjectAndReferences` can only be called once for each instance. Is my assumption correct? If so, can we enforce it? (e.g. `if (countReferences > 0) { throw ... }` at the start? Or if not correct, what mistake in understanding am I making?

File: lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java [hunk 9]
```diff
@@ -1,21 +1,28 @@
...
     this.p = p;
     this.cache = buffer;
     this.offset = offset;
+    this.cached = allowCaching ? null : this;
   }
 
   @SuppressWarnings(value = "unchecked")
-  final <T> T readObject(Class<T> clazz) {
+  final <T> T readObject(Class<T> clazz) throws IOException {
+    if (cached != this && clazz.isInstance(cached)) {
```
Comment (hubertp) [inline lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java:35]: Similarly to @radeusgd, I probably don't understand how `cached` is supposed to be used/what it represents. This makes this condition hard to decipher

**Review by hubertp — COMMENTED** [review]
I have similar concerns as @radeusgd re lack of documentation for some magic values/array manipulation

File: lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java (hunk 5 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java]: The idea is clearly visible in this commit 03494b8979d536f6d7493f8565c81269f1e45077 which is associated with following comment https://github.com/enso-org/enso/pull/9972#discussion_r1604813584

> took 1-2 hours to try to understand this code

No need to spend so much time. Enough to use `git blame` and see [it](https://github.com/enso-org/enso/pull/9972/commits/03494b8979d536f6d7493f8565c81269f1e45077) immediately.

Anyway replacing the `-1` with a named constant in a958804348 should make the connection between places that use the constant clearer.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 6 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java]: Yes Radek, you "dissassembled" the idea correctly. Since a958804348 it shall be clearer that these two places are connected.

> fix-up at write time.

That's even better! Done in d0b0d16140.

File: lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java (hunk 8 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java:158]: It is a private method. Nobody outside of this class can call it multiple times and the class does it exactly once.

File: lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java (hunk 3 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java:23]: It is a tri-state value. Explained in 0b09978841

File: lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java (hunk 9 above)
Comment (JaroslavTulach) [reply lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java:35]: It is a tri-state value as explained in 0b09978841

**Comment by JaroslavTulach** [comment]
Thank you @radeusgd for pushing me towards better implementation. Namely, I am very satisfied with d0b0d16 it is clearly better and more easily understandable than the previous version. I believe this PR is ready for integration.
