### PR TITLE
Fix incremental compilation of runtime/test

### LINKED ISSUE #8973: Incremental compilation of `runtime/test` is broken
`runtime/test` does not recompile changed sources in `runtime/Compile`. One has to do `runtime/clean` to be sure that the `runtime/test` command picks the latest changes. This is most probably due to our unnecessarily complicated structure of the `runtime` project, where `runtime/Test` depends on `runtime-fat-jar`, which, in turn, depends on `runtime/Compile`.

Let's simplify this structure, and fix the incremental compilation, by moving the tests from `runtime/Test` to a separate project `runtime-tests` that depends on `runtime-fat-jar`.

While at it, let's also create a separate project for benchmarks in `runtime-benchmarks`.

```[tasklist]
### Tasks
- [ ] Remove all dependencies from `runtime` to `runtime-fat-jar`.
```

### LINKED ISSUE #9026: Fix "Benchmark Engine" daily job
The [Benchmark Engine GH Action](https://github.com/enso-org/enso/actions/workflows/engine-benchmark.yml)  is broken since circa 1st of February 2024. The failure is `ClassNotFoundException` in `std-benchmarks/Bench/compile`, e.g., in https://github.com/enso-org/enso/actions/runs/7865542616/job/21458602621#step:8:1407.

Interestingly, [Benchmark Standard Libraries](https://github.com/enso-org/enso/actions/workflows/std-libs-benchmark.yml) are still OK. (Probably because `std-benchmarks/bench` depends on `buildEngineDistribution`).

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #8973 and https://github.com/enso-org/enso/issues/9026

### Pull Request Description

Fixes incremental compilation issues of `runtime/Test` by introducing a separate `runtime-integration-tests` project. Also move runtime benchmarks to a new `runtime-benchmarks` project and provide an easier way how to run the benchmarks.

For now, let's move all the tests from `runtime/Test` to `runtime-integration-tests`, just to be sure that all the tests run with all the dependencies. In the future, we can add standard unit tests, that do not require the Enso runtime, to `runtime/Test`.

### Important Notes

- Introduced `runtime-benchmarks` project
  - Contains all benchmarks previously from `runtime/bench`.
  - Refactored some Scala bits to Java
- Introduced `runtime-integration-tests` project
  - Contains all tests previously from `runtime/test`.
- Quality of life improvements to the benchmark running. 
  - `bench` and `benchOnly` commands work as they used to.
  - All source code is under `src/main/java`, no more `bench` directory.
  - There is a main class that delegates to the JMH launcher, you can use `run -h` to see all the available cmd line options for the launcher.
  - No more `RegressionTest.scala`.
  - See the updated [benchmarks.md](https://github.com/enso-org/enso/pull/8975/files#diff-4ff08021836e69e22a9946fe768f81531b9e22622fb0c07f652f01ce9011489e).
- Simplification of `std-benchmarks` project
  - Remove the Bench configuration
  - Use `JPMSPlugin`.

### How I tested the changes?

Incremental compilation of `runtime-tests` tested by:
- Modification of sources in `pkg`, `runtime`, and `runtime-instrument-common` and then re-running `runtime-tests/testOnly`.

Tested other commands:
- `sbt:runtime-integration-tests> withDebug --debugger`
- `sbt:runtime-benchmarks> run - i 1 -wi 1 org.enso.interpreter.bench.benchmarks.semantic.AtomBenchmarks.benchSumList`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] Make sure there are no regressions in the engine benchmarks

### CODE REVIEW

File: project/JPMSPlugin.scala [hunk 1]
```diff
@@ -114,8 +114,6 @@ object JPMSPlugin extends AutoPlugin {
         )
     }.toSeq
 
-    ensureDirectoriesExist(modulePath, log)
```
Comment (Akirathan) [inline project/JPMSPlugin.scala:117]: These warnings are annoying and they are not useful. Java does not mandate that the directories passed into, e.g., `--module-path` option exist.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/asserts/AssertionsTest.java [hunk 2]
```diff
@@ -49,6 +49,17 @@ public void resetOutput() {
     out.reset();
   }
 
+  @Test
+  public void jvmAssertionsAreEnabled() {
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/asserts/AssertionsTest.java:53]: I have spent ridiculous amount of time debugging `RuntimeErrorsTest` just to realize that I have not enabled JVM assertions, so the DataFlow errors did not contain stack traces. Let's add this test so that nobody encounters something similar in the future.

**Review by mwu-tow — APPROVED** [review]
Reviewed Rust parts only. 🟢

File: build.sbt [hunk 3]
```diff
@@ -1650,109 +1617,6 @@ lazy val runtime = (project in file("engine/runtime"))
       necessaryModules ++ langs ++ tools
     }
   )
-  .settings(
```
Comment (JaroslavTulach) [inline build.sbt:1653]: I was hoping the setup of `runtime` project will be simpler. Removal of these lines matches my expectations.

File: build.sbt [hunk 4]
```diff
@@ -1833,8 +1653,212 @@ lazy val runtime = (project in file("engine/runtime"))
...
   .dependsOn(`connected-lock-manager`)
   .dependsOn(testkit % Test)
-  .dependsOn(`logging-service-logback` % "test->test")
-  .dependsOn(`runtime-test-instruments` % "test->compile")
+
+/** A project holding all the runtime integration tests. These tests require, among other things,
+  * the `org.enso.runtime` JPMS module, so it is easier to keep them in a separate project.
+  * For standard unit tests, use `runtime/Test`.
+  */
+lazy val `runtime-integration-tests` =
```
Comment (JaroslavTulach) [inline build.sbt:1661]: Configuration of this project remains complicated, but at the end, they are _integration tests_ - they can be complicated.

File: engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java [hunk 5]
```diff
@@ -0,0 +1,285 @@
...
+@Fork(1)
+@Warmup(iterations = 5)
+@Measurement(iterations = 5)
+@OutputTimeUnit(TimeUnit.MILLISECONDS)
+@State(Scope.Benchmark)
+public class AtomBenchmarks {
+
+  private static final Long MILLION = 1_000_000L;
+  private static final String MILLION_ELEMENT_LIST =
+      """
```
Comment (JaroslavTulach) [inline engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java:34]: Looks like a removal of [AtomFixtures.scala](https://github.com/enso-org/enso/pull/8975/files#diff-3688c5fc8771c88594bed8b2395086c29af838bc81b948383a5415dab588496e). Replaced by Java code - great!

**Review by JaroslavTulach — APPROVED** [review]
Hard to review such a huge shuffling of code, but the intentions I have spotted are good.

**Review by 4e6 — APPROVED** [review]

File: engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java (hunk 5 above)
Comment (Akirathan) [reply engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java:34]: Yes, along with all the other Scala sources that were previously in `runtime/src/bench/scala`

File: build.sbt [hunk 6]
```diff
@@ -1869,7 +1869,7 @@ lazy val `runtime-benchmarks` =
           (Compile / run).toTask("").tag(Exclusive).value
         }
         .dependsOn(
-          `runtime-fat-jar` / assembly
+          buildEngineDistribution
```
Comment (JaroslavTulach) [inline build.sbt:1872]: +1

**Comment by Akirathan** [comment]
Scheduling engine benchmarks at https://github.com/enso-org/enso/actions/runs/7873980506/job/21482523287, and stdlib benchmarks at https://github.com/enso-org/enso/actions/runs/7873983053

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@f873840</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@f873840</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

File: build.sbt [hunk 7]
```diff
@@ -1833,8 +1653,238 @@ lazy val runtime = (project in file("engine/runtime"))
   .dependsOn(`runtime-compiler`)
   .dependsOn(`connected-lock-manager`)
   .dependsOn(testkit % Test)
-  .dependsOn(`logging-service-logback` % "test->test")
-  .dependsOn(`runtime-test-instruments` % "test->compile")
+
+/** A project holding all the runtime integration tests. These tests require, among other things,
+  * the `org.enso.runtime` JPMS module, so it is easier to keep them in a separate project.
+  * For standard unit tests, use `runtime/Test`.
```
Comment (radeusgd) [inline build.sbt:1659]: shouldn't this be lowercase?
```suggestion
  * For standard unit tests, use `runtime/test`.
```

Note that running uppercase results in:
```
[IJ]runtime/Test
[error] Expected ':'
[error] Expected '/'
[error] Not a valid key: Test (similar: test, testOnly, state)
[error] runtime/Test
```

**Review by radeusgd — APPROVED** [review]

**Review by radeusgd — APPROVED** [review]

File: build.sbt (hunk 7 above)
Comment (Akirathan) [reply build.sbt:1659]: `runtime/Test` refers to the Test *configuration*, not to a command. This configuration is located, under the directory `engine/runtime/src/test`

**Comment by Akirathan** [comment]
Encountered some problems with `bench-report.xml` uploading in the last bench runs. Starting a new engine bench at https://github.com/enso-org/enso/actions/runs/7875921777/job/21488889969

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@00fb45e</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Review by hubertp — COMMENTED** [review]
LGTM (sorry for late review)
