### PR TITLE
Sort handling of Nothing within Column || and &&

### LINKED ISSUE #8653: Correct handling of OR and AND when one is a Nothing
Currently in the in-memory table when a operating on a Boolean column if one is Nothing the result is incorrect.

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

Follows the database logic:
image

Results:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [X] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by radeusgd** [comment]
I'm curious - any idea why the last column is rendered as text and not with checkboxes?

**Review by GregoryTravis — APPROVED** [review]

File: std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java [hunk 1]
```diff
@@ -352,29 +359,41 @@ public BoolStorage runZip(
...
+                } else if (v.negated) {
+                  out.flip(0, storage.size);
+                  out.and(storage.values);
+                  negated = false;
+                } else {
+                  out.and(storage.values);
+                  negated = false;
+                }
+
+                BitSet missing = storage.isMissing.get(0, storage.size);
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java]: We were usually using `BitSets.makeDuplicate` for this purpose I think.

File: std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java [hunk 2]
```diff
@@ -402,30 +428,42 @@ public BoolStorage runZip(
...
+                  var value = negated != out.get(current);
+                  if (value
+                      && (storage.getItemBoxed(current) == Boolean.TRUE
+                          || v.getItemBoxed(current) == Boolean.TRUE)) {
+                    missing.clear(current);
+                  }
+                  current = missing.nextSetBit(current + 1);
+                }
+
+                return new BoolStorage(out, missing, storage.size, negated);
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java]: This is getting quite complicated (I admit it was complicated before too, but when it was my own code, I didn't feel that as much since I remembered the context better - now coming to it after a while it makes it a bit harder).

I suggest maybe we should split the And and Or operations into separate files? As the `BoolStorage.java` is quite large already.

Then, I'm wondering if it may be good to add some explanations in the comments what each piece is doing, e.g. I assume the `nextSetBit` loop is used to un-mark the part that is no longer undefined, because `true || null` made it into a proper value.

File: test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso [hunk 3]
```diff
@@ -162,12 +162,43 @@ spec setup =
...
                 (x || y.not).to_vector . should_equal [True, True, True]
 
-        Test.specify "should return null if one of arguments is missing" pending="TODO null handling" <|
-            t = table_builder [["X", [True, False, True]]]
-            x = t.at "X"
-            nulls = [Nothing, Nothing, Nothing, Nothing]
-            (x && Nothing).to_vector . should_equal nulls
-            (x || Nothing).to_vector . should_equal nulls
+        Test.specify "should handle nulls correctly in not" <|
+            t = table_builder [["A", [True, True, True, False, False, False, Nothing, Nothing, Nothing]]]
```
Comment (radeusgd) [inline test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso]: any reason these are repeated 3x?

**Comment by jdunkerley** [comment]
> I'm curious - any idea why the last column is rendered as text and not with checkboxes?

ag-grid checks the first value I think so if it is Nothing it doesn't checkbox it.

**Comment by radeusgd** [comment]
> > I'm curious - any idea why the last column is rendered as text and not with checkboxes?
> 
> ag-grid checks the first value I think so if it is Nothing it doesn't checkbox it.

ah, I see. I guess at some point we'll want the visualization to rely on the `.value_type`s from `.info` instead.

File: std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java (hunk 2 above)
Comment (jdunkerley) [reply std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java]: I agree but would rather leave for a wider refactor of how we do Storage and Operations.

**Comment by jdunkerley** [comment]
> > > I'm curious - any idea why the last column is rendered as text and not with checkboxes?
> > 
> > 
> > ag-grid checks the first value I think so if it is Nothing it doesn't checkbox it.
> 
> ah, I see. I guess at some point we'll want the visualization to rely on the `.value_type`s from `.info` instead.

Yep was thinking the same but didn't want to until was on GUI2 and working on new Table Viz.

File: test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso (hunk 3 above)
Comment (jdunkerley) [reply test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso]: as I copied from the && example with the full set.

**Review by radeusgd — APPROVED** [review]
