### PR TITLE
Fix vue router regression

### LINKED ISSUE #13039: Vue Router Regression - blinking view when switching category.
https://github.com/user-attachments/assets/017c1a58-a8db-48b8-b61c-466b52999498

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

A workaround for #13039

The problems were caused by two factors:
1. I missed a place where we already navigated in a react transition; 
2. The searchParams were modified "in place" in useSearchParamsState what caused unpredictable effects.

See PR comments to see what should be improved to close the task.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
~~- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
~~- [ ] Unit tests have been written where possible.~~
~~- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]

**Comment by farmaazon** [comment]
The integration tests discovered a regression with pre-populate email fields in forms. Added a fix, and re-requested review to just make sure you're ok with it.

File: app/gui/src/dashboard/pages/authentication/Registration.tsx [hunk 1]
```diff
@@ -89,6 +89,10 @@ export default function Registration() {
     },
   })
 
+  useEffect(() => {
```
Comment (MrFlashAccount) [inline app/gui/src/dashboard/pages/authentication/Registration.tsx]: This is clearly a bad thing

When you add use 'useEffect' to set initial values - you better ask yourself, where the root cause, and solve it first.

**Review by MrFlashAccount — CHANGES_REQUESTED** [review]

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts [hunk 2]
```diff
@@ -49,16 +49,28 @@ export function useSearchParamsState<T = unknown>(
...
       const query = Object.fromEntries(nextSearchParams.entries())
-      void router.push({ query, ...options })
+      // TODO[ao]: router.push/router.replace are asynchronous, but we want window.location.href
+      // to be updated immediately, so any subsequent query changes won't override this one.
+      //
+      // This keeps the old way of doing (before #12803), but I think the more elegant solution
+      // would be keeping the "intermediate" state by ourselves and leave window.location.search
+      // management to router.
+      if (options.replace ?? false) {
+        window.history.replaceState(null, '', `?${nextSearchParams.toString()}`)
```
Comment (MrFlashAccount) [inline app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: This can't be a solution.

**Review by MrFlashAccount — CHANGES_REQUESTED** [review]

File: app/gui/src/dashboard/pages/authentication/Registration.tsx (hunk 1 above)
Comment (farmaazon) [reply app/gui/src/dashboard/pages/authentication/Registration.tsx]: [The root cause](https://react-hook-form.com/docs/useform#defaultValues):

> defaultValues are cached. To reset them, use the [reset](https://react-hook-form.com/docs/useform/reset) API.

with the fact that query search is deferred now, so we initialize it with old value

So I assumed this fix is just "a way of doing" in react forms. Additionally, it has an effect that query navigation inside page will also update the email field (not sure if desirable, but I think it is neat).

Do you prefer making navigating to login page non-transitional? Or have another solution in mind?

Comment (MrFlashAccount) [reply app/gui/src/dashboard/pages/authentication/Registration.tsx]: Initial value is supposed to be present by the moment of initial rendering. Otherwise you'll keep facing issues like this one. Also, React transitions should be preserved as well, as you claimed in the vue router PR.

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: What exactly cannot be a solution?

If "using window.location.search" to keep state of current query, then it is how it worked before: https://github.com/enso-org/enso/blob/7b7890dc5e0c76e10516a324b3f3a2679731600c/app/gui/src/dashboard/hooks/searchParamsStateHooks.ts#L56 It just relied on navigate updating window.location.search synchronously, while now it is asynchronous.

I may implement better solution, not relying on window.location.search (as in TODO), but wanted to merge a quick fix first.

File: app/gui/src/dashboard/pages/authentication/Registration.tsx (hunk 1 above)
Comment (farmaazon) [reply app/gui/src/dashboard/pages/authentication/Registration.tsx]: Changed the fix. Now no useEffects are needed.

>  Also, React transitions should be preserved as well, as you claimed in the vue router PR.

This is not what I've written, BTW. [I said that these use cases for react transitions may be implemented differenttly](https://github.com/enso-org/enso/pull/12803#issuecomment-2826747423)

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 2 above)
Comment (MrFlashAccount) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: Could you add a reference to a code where we update window.location directly?

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts [hunk 3]
```diff
@@ -40,7 +40,8 @@ export function useSearchParamsState<T = unknown>(
   defaultValue: T | (() => T),
   predicate: (unknown: unknown) => unknown is T = (unknown): unknown is T => true,
 ): SearchParamsStateReturnType<T> {
-  const { router, searchParams } = useRouterInReact()
+  const { router, searchParams: searchParamsRaw } = useRouterInReact()
+  const searchParams = React.useDeferredValue(searchParamsRaw)
```
Comment (MrFlashAccount) [inline app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: Why did you add 'useDefferedValue' here? It exists for a different purpose

File: app/gui/src/dashboard/pages/authentication/Registration.tsx (hunk 1 above)
Comment (MrFlashAccount) [reply app/gui/src/dashboard/pages/authentication/Registration.tsx]: Second point is not an option for us

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 3 above)
Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: Different purpose than what?

Comment (MrFlashAccount) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: You clearly _don't_ need it here because the only purpose for this hook is _deferring_ rendering for the parts of the UI.  Why do you want to _defer_ here?

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: > Could you add a reference to a code where we update window.location directly?

There is no such code. Please, re-read my message carefully: I said _keeping_ state of current query. Previous code was relying on `navigate` setting `window.location.search` synchronously. This is not something guaranteed, according to my research (but I might be wrong).

Comment (MrFlashAccount) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: In react-router it's always synchronous, same true for `window.replaceState(...)`. In the code you mentioned it serves a different purpose - in some edge cases we can have an outdated value in react (because react update states in batch), see: https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

react-router doesn't provide an option to get the current pending value so we need to read the location directly.

---

My initial comment was about the workaround with `window.history.replaceState` and it's _obviously_ not a solution and I won't let it merged that way.

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 3 above)
Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: When changing category or current id (the state being kept in search params) we want to defer updating asset table. I thought that it should be the default for every query update. But perhaps you're right, I should use it near actual suspense queries.

**Comment by MrFlashAccount** [comment]
CleanShot 2025-05-06 at 18 01 39@2x

I'm not even talking about _2_ heavy rerenders instead of one previously

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: > In react-router it's always synchronous

I wasn't sure, when reading documentation. `navigate` may return `Promise<void>`: https://reactrouter.com/api/hooks/useNavigate#signature

> in some edge cases we can have an outdated value in react (because react update states in batch), 

Yes, I know. This is exactly what I meant by "we want window.location.href to be updated immediately, so any subsequent query changes won't override this one." 

> My initial comment was about the workaround with window.history.replaceState and it's obviously not a solution and I won't let it merged that way.

For me is no so obvious. Why _reading_ window.location.search is ok, but _writing_ window.location.search is not ok?

Comment (MrFlashAccount) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:75]: 1. It's indirect.
2. It happens outside of the router context
3. It runs states out-of-sync
4. It's not ideomatic.
5. This is clearly a hack
6. I spent the last year getting rid of code like this.

--- 

Reading is fine because we use it only as a pending state.

File: app/gui/src/dashboard/hooks/searchParamsStateHooks.ts (hunk 3 above)
Comment (MrFlashAccount) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: In that case we should wrap category change in 'startTransition' (I'm sure we do this already)

Deferred state has completely different purpose compared to 'startTransition'

Comment (farmaazon) [reply app/gui/src/dashboard/hooks/searchParamsStateHooks.ts:49]: > Deferred state has completely different purpose compared to 'startTransition'

Didn't know that. I was just reading in [`startTransition` docs](https://react.dev/reference/react/startTransition#caveats), that:

> You can wrap an update into a Transition only if you have access to the set function of that state. If you want to start a Transition in response to some prop or a custom Hook return value, try [useDeferredValue](https://react.dev/reference/react/useDeferredValue) instead.

ATM the category is based on the context change coming from vue.

**Review by MrFlashAccount — APPROVED** [review]

**Review by PabloBuchu — APPROVED** [review]
