### PR TITLE
Propagate parser error messages

### LINKED ISSUE #13954: Backend should report syntax error messages
The parser's error messages are [usually fairly specific](https://github.com/enso-org/enso/blob/60134a7c17ac8b4b4f42254ee16a4318febab623/lib/rust/parser/src/syntax/tree.rs#L947-L981). Currently, in `TreeToIr`, there are many cases where these syntax errors are translated to more generic errors. I think we should update the backend's types and tests to allow all syntax errors to be reported using the messages produced by the parser.

For example:

```
$ cat Test.enso
main = 1 +
    2 + 
    3
```

The parser's error message: 
```
$ cargo run -p enso-parser-debug --bin check_syntax Test.enso
E <stdin> 2:4-2:7: This expression would define an unused function; if you would like to create an operator block, each indented line must begin with an operator followed by a space:     2 +
```

The backend's error message:
```
$ ./dist/backend/dist/2025.3.1-dev/bin/enso --run Test.enso
/Users/kaz/repo/enso-backend/Test.enso:2:5: error: Unexpected expression.
    2 |     2 +
      |     ^~~
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #13954
- by propagating the parser error messages
- instead of reporting _dummy_ `Syntax.UnexpectedExpression`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
- [x] Unit tests have been written where possible.
- [x] Remove [sanity check](https://github.com/enso-org/enso/pull/13986/files#r2338745731) - done in 3fa0ecd6974ca307f68f01bcfa929ace9baeca52

### CODE REVIEW

File: lib/rust/parser/src/syntax/tree.rs [hunk 1]
```diff
@@ -1100,9 +1100,9 @@ pub fn to_ast(token: Token) -> Tree {
         token::Variant::Wildcard(wildcard) => Tree::wildcard(token.with_variant(wildcard), default()),
         token::Variant::SuspendedDefaultArguments(t) => Tree::suspended_default_arguments(token.with_variant(t)),
         token::Variant::OpenSymbol(s) =>
-            Tree::group(Some(token.with_variant(s)), default(), default()).with_error("Unmatched delimiter"),
+            Tree::group(Some(token.with_variant(s)), default(), default()).with_error("Unmatched delimiter."),
         token::Variant::CloseSymbol(s) =>
-            Tree::group(default(), default(), Some(token.with_variant(s))).with_error("Unmatched delimiter"),
+            Tree::group(default(), default(), Some(token.with_variant(s))).with_error("Unmatched delimiter."),
```
Comment (JaroslavTulach) [inline lib/rust/parser/src/syntax/tree.rs]: - some of the provided messages end with `.` some don't...

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala [hunk 2]
```diff
@@ -165,9 +165,8 @@ object Syntax {
       s"$number is not valid in $base"
   }
 
-  case class UnsupportedSyntax(syntaxName: String) extends Reason {
-    override def explanation: String =
-      s"Syntax is not supported yet: $syntaxName"
+  case class UnsupportedSyntax(override val explanation: String) extends Reason {
+    if (explanation.length < 5) throw new IllegalStateException("Missing description: " + explanation)
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala]: - just a sanity check we always provide some explanation
- TBD: remove

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java [hunk 3]
```diff
@@ -406,21 +427,21 @@ public void malformedExport8() throws Exception {
   public void malformedExport9() throws Exception {
     var ir = parse("from export all");
     assertSingleSyntaxError(
-        ir, Syntax.UnexpectedExpression$.MODULE$, "Unexpected expression", 0, 15);
+        ir, new Syntax.UnsupportedSyntax("`all` not allowed in `export` statement"), null, 0, 15);
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java]: - Is this _markdown inspired_ usage of "`" really something we want in the error messages?

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java [hunk 4]
```diff
@@ -2020,6 +2020,11 @@ Comment.Documentation translateComment(Tree where, DocComment doc) throws Syntax
   }
 
   Syntax translateSyntaxError(Tree where, Syntax.Reason reason) {
+      if (reason == Syntax.UnexpectedExpression$.MODULE$ && where instanceof Tree.Invalid invalid) {
+        if (!invalid.getError().startsWith("Unexpected token:")) {
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: - Without this check I was getting:

```

[error] Test org.enso.compiler.test.ErrorCompilerTest.invalidToken2 failed: java.lang.AssertionError: 
expected:<UnsupportedSyntax(Unclosed parenthesis in expression)> but 
was:<UnsupportedSyntax(Unexpected token: Token { left_offset: Offset { visible: VisibleOffset { 
width_in_spaces: 1 }, code: Code { repr: StrRef(" "), start: Location { utf8: 21, utf16: 21, line: 0, col16: 21 }, 
len: Length { utf8: 1, utf16: 1, newlines: 0, line_chars16: 1 } } }, code: Code { repr: StrRef("`"), 
start: Location { utf8: 22, utf16: 22, line: 0, col16: 22 }, len: Length { utf8: 1, utf16: 1, newlines: 0, line_chars16: 1 } }, 
variant: Invalid })>, took 0.4 sec
```

- e.g. the Rust parser is providing wrong `getError()` value
- @kazcw feel free to suggest a fix or push changes into this branch directly

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java:1]: - @kazcw I suggest you to take a look at the remaining `Syntax.UnexpectedExpression$.MODULES$` in this file
- they indicate places where the Rust parser _does not provide_ `Tree.Invalid`

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java (hunk 4 above)
Comment (kazcw) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: Am I understanding this right?
- The test input is `` splice_outside_text = ` ``
- The parser's actual error is unexpected token (the backtick)
- But the expected error is "Unclosed parenthesis..."

The parser seems right. Why is the expected error "Unclosed parenthesis"?

Comment (kazcw) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: Oh, I see the Token internals are part of the error message... I'll remove that

File: lib/rust/parser/src/syntax/tree.rs (hunk 1 above)
Comment (kazcw) [reply lib/rust/parser/src/syntax/tree.rs]: I think we should omit it, it can easily be added when printing.

Fixed in https://github.com/enso-org/enso/pull/13920/commits/e22dab6bb92b92fa45308505e8addad9165e3bf2

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java (hunk 3 above)
Comment (kazcw) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java]: I don't see why not, but I could go either way. Changed to `"` in https://github.com/enso-org/enso/pull/13920/commits/e22dab6bb92b92fa45308505e8addad9165e3bf2

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java (hunk 4 above)
Comment (kazcw) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: Error message omits debug nonsense in: https://github.com/enso-org/enso/pull/13920/commits/e22dab6bb92b92fa45308505e8addad9165e3bf2

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
Comment (kazcw) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java:1]: Some of these are already invalid-node test cases in the parser, and seem to have reasonable error messages.

There are a couple of cases that seem quite safe to make into syntax errors.

In the rest of the cases, treating them as syntax errors would be a change from a previous decision or plan (which may well be outdated!). I wrote [parser test cases for them, showing how they are *currently* parsed](https://github.com/enso-org/enso/pull/13920/commits/e22dab6bb92b92fa45308505e8addad9165e3bf2#diff-6c20c8a3bb483a4f3b739dea12dbce048ebd951b8d389cc7fb53d351edee6ddfR1681-R1718) (link points to the lines but you may need to click "Load diff" to see them)--I'd like to discuss those cases when you have a chance.

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala]: Reformatted and removed in 29919b71528cea269dc4cabcb407bc353d074782

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: - just trying to bring that commit to my branch with ` git show e22dab6 | patch -p0`
- doesn't work: I guess I should wait for your PR to merge...

Comment (JaroslavTulach) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java]: Merged and the previous workaround removed in 3fa0ecd6974ca307f68f01bcfa929ace9baeca52

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java]: - I wasn't sure about it either.
- it's just too markdown/github centric
- and Enso audience isn't likely very github knowledgable

**Review by kazcw — APPROVED** [review]

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala [hunk 5]
```diff
@@ -165,10 +165,8 @@ object Syntax {
       s"$number is not valid in $base"
   }
 
-  case class UnsupportedSyntax(syntaxName: String) extends Reason {
-    override def explanation: String =
-      s"Syntax is not supported yet: $syntaxName"
-  }
+  case class UnsupportedSyntax(override val explanation: String)
+      extends Reason {}
```
Comment (hubertp) [inline engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala]:
```suggestion
      extends Reason
```

**Review by hubertp — APPROVED** [review]
