### PR TITLE
Small GUI fixes

### LINKED ISSUE #14440: Passing in external parameter causing component freak out
Connecting to a parameter with a value causes it to switch back and forth

https://github.com/user-attachments/assets/ea3e4d0b-4b5d-4cee-b4ef-76055ca5639a

### LINKED ISSUE #14470: Stuck edge when starting creation from new node button area
Can be tricky to reproduce, happens when first click is near the plus button.

https://github.com/user-attachments/assets/720eef34-5c1f-4ac3-b50a-cbeaabd2f160

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #14440 
Fixes #14470 

- Fixes accessibility warnings in console from ProgressBar React component.
- Fixes errors in console about `ResizeObserver`
- Dropdown width no longer depends on port width, because it introduces unpleasant jumping when hovering the port.
- Animation of scrolling text when hovering long items in dropdown is restored

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/styles.ts [hunk 1]
```diff
@@ -31,10 +27,12 @@ function sizeOptions(limitWidth: boolean): () => SizeOptions {
...
       const minWidth = `${Math.max(portWidth - screenOverflow, 0)}px`
-      const maxWidth = getMaxWidth(portWidth, limitWidth)
+      const maxWidth = limitWidth ? `${MAX_DROPDOWN_OVERSIZE_PX}px` : null
 
-      Object.assign(elements.floating.style, { minWidth, maxWidth })
-      elements.floating.style.setProperty('--dropdown-max-width', maxWidth)
+      requestAnimationFrame(() => {
+        Object.assign(elements.floating.style, { minWidth, maxWidth })
+        elements.floating.style.setProperty('--dropdown-max-width', maxWidth)
+      })
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/styles.ts:36]: I feel either here in comment, or in function docs, there should be an information that something is done in RAF

File: app/gui/src/project-view/components/widgets/DropdownWidget.vue [hunk 2]
```diff
@@ -170,7 +170,7 @@ export interface DropdownEntry {
   display: inline-block;
   max-width: 100%;
   white-space: nowrap;
-  overflow: hidden;
+  overflow: clip;
```
Comment (farmaazon) [inline app/gui/src/project-view/components/widgets/DropdownWidget.vue:173]: Why this change? At least for me, it's not obvious what do we want to achieve here.

**Review by farmaazon — APPROVED** [review]
LGTM, I only need some explanation here and there.

File: app/gui/src/project-view/components/widgets/DropdownWidget.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/widgets/DropdownWidget.vue:173]: Actually, I’m not sure of the the exact reason. It just fixes the text scrolling. I assume it is somehow related to the fact that `clip` does not create scroll container, while `hidden` does, and the interaction between nested scrolling containers inside the list… But I don’t have a solid explanation.


https://github.com/user-attachments/assets/4c21e217-9522-49ec-b89c-308189e23ba7

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/styles.ts (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/styles.ts:36]: Done
