### PR TITLE
Fix right panel context for hybrid projects

### LINKED ISSUE #13577: Documentation and Help Panel Not working for hybrid projects
Image

Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #13577

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/providers/container.ts [hunk 1]
```diff
@@ -54,53 +54,58 @@ LocalStorage.registerKey('launchedProjects', {
...
-      return isValidTab(name) ? name : 'drive'
-    },
-    set: (page) => {
-      router.push({ params: { path: page.split('/') }, query: route.query })
-    },
-  })
+    const tab = computed<TabId>({
+      get: () => {
+        const name = normalizeRouteParamToString(route.params.path)
+        return isValidTab(name) ? name : fallbackTab
```
Comment (vitvakatu) [inline app/gui/src/providers/container.ts:80]: The formatter is stupid; the only line that has been changed is this one.

Comment (Frizi) [reply app/gui/src/providers/container.ts:80]: You added ’fallbackTab’ as an argument, so it pushed the whole closure parameter to the next line. This seems correct, though a little unfortunate.

Comment (vitvakatu) [reply app/gui/src/providers/container.ts:80]: Yeah, I understand, I’m just annoyed that the whole file changed :)

**Review by Frizi — APPROVED** [review]

**Review by Frizi — APPROVED** [review]

File: app/gui/src/project-view/components/GraphEditor.vue [hunk 2]
```diff
@@ -374,7 +373,7 @@ const displayedDocs = computed(() =>
 
 watchEffect(() => {
   const projectId = projectStore.id
-  rightPanel.setContext(props.tab, {
+  rightPanel.setContext(containerData.tab, {
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor.vue:376]: I don't quite like this change. The ProjectViews are kept-alive across mutliple tabs; it's not guaranteed that the containerData.tab will be equal to this project tab id -- now it is, but I would call it accidental.
