### PR TITLE
Entering and leaving nodes

### LINKED ISSUE #8068: Entering and leaving nodes
Should work exactly as in the old GUI: double-clicking a node should make us "enter" to the definition called by this node - we check the `MethodPointer` received from the engine in expression update. After entering, the graph of the definition should be displayed (without input and output ports), and a stack frame should be pushed to execution context.

Double-clicking the background is leaving the node - going one level up in stack trace. 

We should be able to enter definitions from the currently opened project only. 

Entering selected node and leaving node should be also possible by shortcuts.

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Implements #8068 

[Peek 2023-12-07 13-28.webm](https://github.com/enso-org/enso/assets/1428930/85da0dd6-0c08-4bef-b8e1-ba9573a3e6cd)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
:0

i guess the breadcrumb being the expression id is a known issue? or out of scope?

**Comment by farmaazon** [comment]
> :0
> 
> i guess the breadcrumb being the expression id is a known issue? or out of scope?

The breadcrumbs shall be fixed in #7788

File: app/gui2/src/components/GraphEditor.vue [hunk 1]
```diff
@@ -484,7 +528,7 @@ function handleNodeOutputPortDoubleClick(id: ExprId) {
       :modes="EXECUTION_MODES"
       :breadcrumbs="breadcrumbs"
       @breadcrumbClick="console.log(`breadcrumb #${$event + 1} clicked.`)"
-      @back="console.log('breadcrumbs \'back\' button clicked.')"
+      @back="projectStore.executionContext.pop()"
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor.vue]: Is `graphStore.updateState()` needed in `exitNode` but not here?

**Review by kazcw — APPROVED** [review]

File: app/gui2/src/components/GraphEditor.vue (hunk 1 above)
Comment (MichaelMauderer) [reply app/gui2/src/components/GraphEditor.vue]: Good point, this should use the `exitNode` function.

File: app/gui2/src/components/GraphEditor.vue [hunk 2]
```diff
@@ -202,8 +204,27 @@ const graphBindingsHandler = graphBindings.handler({
...
 })
 
+const handleClick = useDoubleClick(
+  (e) => {
+    graphBindingsHandler(e)
+  },
+  () => {
+    exitNode()
+  },
+).handleClick
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor.vue:227]: I feel like we should add double-click support to the bindings system. Then it would become another aliased binding for the `exitNode` handler. But it doesn't necessarily need to be addressed in this PR, as its kinda unrelated.

File: app/gui2/src/components/GraphEditor.vue [hunk 3]
```diff
@@ -213,6 +234,26 @@ const codeEditorHandler = codeEditorBindings.handler({
...
+  const expressionInfo = graphStore.db.getExpressionInfo(id)
+  if (expressionInfo == undefined || expressionInfo.methodCall == undefined) {
+    console.debug('Cannot enter node that has no method call.')
+    return
+  }
+  const definedOnType = tryQualifiedName(expressionInfo.methodCall.methodPointer.definedOnType)
+  if (definedOnType.ok && qnLastSegment(definedOnType.value) != 'Main') {
+    console.debug('Cannot enter node that is not defined on Main.')
+    return
+  }
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor.vue]: Instead of checking for `Main` as a last segment, this should be a check if the function is defined in any project-local module. For now, it could be a check if that matches the module that is currently opened (i.e. one from the top of the execution stack). Eventually we would support switching between project files, so that check could then be relaxed.

**Review by Frizi — APPROVED** [review]
