### PR TITLE
Fix displaying of host values in chrome devtools

### LINKED ISSUE #7890: Java Values are displayed differently in the Chrome Devtools debugger
Consider the following program:
```
from Standard.Base import all

main =
    d_enso = Date.new 2011 12 13
    d_java = Date.parse "2014-12-15"
    
    IO.println d_enso
    IO.println d_java
```
run it with `--inspect` and set the breakpoint at `IO.println d_java`.

We will see the following Scope:
image

We can see that the value coming from Java is displayed differently than the one from Enso, even though both are a `Date`. It is probably because Enso did not manage yet to perform its polyglot conversions. Shall they be performed before displaying the object?

Another issue can be seen when we interact with the REPL:
image

We can see that values coming from polyglot calls (e.g. `next`) behave Java-like and the ones that are 'correctly' displayed come from builtin methods (e.g. `Date_Time.date`) which ensure the Enso polyglot conversion happens.

----

I'm not sure if this is a bug - although ideally the behaviour of the Debugger should be consistent regardless of where the value is coming from.

What may be especially misleading is that the Java values display all kinds of Java methods they have:
image

But these methods won't work, because of how the Enso interop works (once we do a call, we _do_ the polyglot conversion and it's no longer a Java `LocalDate` but an `EnsoDate`):
image
image

That is quite misleading, so I think ideally we should fix it and show the value for what it is to the user - an Enso date. I'm not sure how big of a priority this is though.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #7890

### Pull Request Description

Chrome inspector now displays polyglot objects that have a corresponding Enso builtin type as enso objects:

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java [hunk 1]
```diff
@@ -76,13 +85,26 @@ public void initContext() {
...
     engine.close();
     engine = null;
   }
 
+  /** Only print warnings from the compiler if a test fails. */
+  @Rule
+  public TestWatcher testWatcher =
+      new TestWatcher() {
+        @Override
+        protected void failed(Throwable e, Description description) {
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:101]: Interesting. If this could be the default for `defaultContextBuilder`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java [hunk 2]
```diff
@@ -188,15 +193,56 @@ boolean isMemberReadable(String memberName) {
...
+        var interopUncached = InteropLibrary.getUncached();
+        var firstMember = readFirstMember(value);
+        if (firstMember != null) {
+          var builtinsScope = EnsoContext.get(interop).getBuiltins().getScope();
+          var symbol = UnresolvedSymbol.build(firstMember, builtinsScope);
+          var polyglotCallType =
+              HostMethodCallNode.getPolyglotCallType(value, symbol, interopUncached);
+          try {
+            switch (polyglotCallType) {
+              case CONVERT_TO_DATE -> {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: Here is the main idea. Chrome inspector instrument builds `DebugLocalScope` which holds a materialized frame with all the bindings. If a binding is a host object that can/should be converted to an appropriate Enso builtin type before sending back to the inspector, it is converted here. This is pretty much the same kind of conversion that is done inside [InvokeMethodNode](https://github.com/enso-org/enso/blob/8e765953a4d6caed716f5ed536a00f527cb7ecd6/engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java) on the `self` argument before any kind of method dispatch is done.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java [hunk 3]
```diff
@@ -246,6 +269,86 @@ public void testHostValues() {
...
+                  DebugValue javaDateTime = scope.getDeclaredValue("dt_java");
+                  assertSameProperties(ensoDateTime.getProperties(), javaDateTime.getProperties());
+
+                  DebugValue ensoString = scope.getDeclaredValue("str_enso");
+                  DebugValue javaString = scope.getDeclaredValue("str_java");
+                  assertSameProperties(ensoString.getProperties(), javaString.getProperties());
+
+                  DebugValue ensoList = scope.getDeclaredValue("list_enso");
+                  DebugValue javaList = scope.getDeclaredValue("list_java");
+                  assertSameProperties(ensoList.getProperties(), javaList.getProperties());
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:356]: Nice test.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java [hunk 4]
```diff
@@ -117,6 +117,46 @@ public boolean isInteropLibrary() {
...
 
+  /**
+   * Given a polyglot (foreign) object, this enum represents a target Enso type that the object
+   * should be converted to before further dispatch.
+   *
+   * <p>For example, a {@code java.lang.String}, or any other polyglot object that {@link
+   * InteropLibrary#isString(Object) is a string}, should be converted to the {@link
+   * org.enso.interpreter.runtime.data.text.Text} builtin Enso type.
+   */
+  public enum PolyglotConversionType {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java]: - Why do we have `PolyglotConversionType` instead of existing `PolyglotCallType`?
- Well, it is not instead, it is in addition to. Cannot we integrate those two somehow?
- What are the differences preventing such an integration of these two types?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java [hunk 5]
```diff
@@ -188,15 +205,78 @@ boolean isMemberReadable(String memberName) {
...
-      throws UnknownIdentifierException {
+      throws UnknownIdentifierException, UnsupportedMessageException {
     if (!allBindings.containsKey(member)) {
       throw UnknownIdentifierException.create(member);
     }
     FramePointer framePtr = allBindings.get(member);
     var value = getValue(frame, framePtr);
+    if (value != null && isHostObject(value)) {
+      // Determine if the host object can be converted to corresponding Enso value.
+      var interopUncached = InteropLibrary.getUncached();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: What is we just invoke `value.to Any` or some other well known method invocation on the value? Unless I am mistaken most of the conversions happen for `self` argument before the dispatch happens.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java [hunk 6]
```diff
@@ -188,15 +205,78 @@ boolean isMemberReadable(String memberName) {
...
+      try {
+        switch (conversionType) {
+          case CONVERT_TO_DATE -> {
+            var localDate = interopUncached.asDate(value);
+            return new EnsoDate(localDate);
+          }
+          case CONVERT_TO_ARRAY -> {
+            return ArrayLikeHelpers.asVectorFromArray(value);
+          }
+          case CONVERT_TO_BIG_INT -> {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: I am still not sure why these conversion aren't in [EnsoLanguage.getLanguageView](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java#L370)?

Because what is defined here is _Enso language view_ of these generic values. E.g. it should be in the `getLanguageView` method and this method can delegate to it, if necessary.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java [hunk 7]
```diff
@@ -188,15 +205,78 @@ boolean isMemberReadable(String memberName) {
...
   @TruffleBoundary
   Object readMember(String member, @CachedLibrary("this") InteropLibrary interop)
-      throws UnknownIdentifierException {
+      throws UnknownIdentifierException, UnsupportedMessageException {
     if (!allBindings.containsKey(member)) {
       throw UnknownIdentifierException.create(member);
     }
     FramePointer framePtr = allBindings.get(member);
     var value = getValue(frame, framePtr);
+    if (value != null && isHostObject(value)) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: `isHostObject` is probably not correct check. What about the same object coming from JavaScript? Or Python? They all should look the same, shouldn't they?

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java [hunk 8]
```diff
@@ -246,6 +269,86 @@ public void testHostValues() {
...
+
+                  DebugValue ensoDict = scope.getDeclaredValue("dict_enso");
+                  DebugValue javaDict = scope.getDeclaredValue("dict_java");
+                  assertSameProperties(ensoDict.getProperties(), javaDict.getProperties());
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:364]: But shouldn't the test also check for JavaScript, Python & co. objects? Maybe use `ValuesGenerator.dates()`, etc.?

**Review by JaroslavTulach — COMMENTED** [review]
- I'd expand this to other languages than Java - e.g. Python & co.
- I don't understand the different between `PolyglotCall` & the other `enum`
- I still believe the code should be in `EnsoLanguage.getLanguageView`

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: [DebugValue](https://github.com/oracle/graal/blob/a4af3090d8788b4983c76b51b278bebbbeaa65c1/truffle/src/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/DebugValue.java#L1181) calls into the `getLanguageView` method - at least to handle some cases like _to string_.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java]: The easiest thing to do would be possible if enums were allowed inheritance in Java. 

You use `PolyglotConversionType` when you have a single object and you are interested whether it can be converted to some Enso builtin. On the other hand, you use `PolyglotCallType` when you are about to *invoke a method* on a foreign object. As such, `PolyglotCallType` has just 4 enum values in addition: `CALL_METHOD`, `GET_MEMBER`, `INSTANTIATE` and `NOT_SUPPORTED`.

I though that splitting this into a separate enum would be more readable. But if it is not, I could change the semantics of `getPolyglotCallType` slightly and allow it to receive `null` `symbol`.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java (hunk 8 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:364]: Tests for `py` and `js` objects added in 2c46980beecdddbd33a5ecaec87e416198edc83e

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: Polyglot/foreign object conversion functionality moved into `EnsoLanguage.getLanguageView` in 9134e528a7101c25606f9a57b8d4cff37c4bd558

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java (hunk 7 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: `isHostObject` check removed, and all the functionality moved to `EnsoLanguage.getLanguageView` in 9134e528a7101c25606f9a57b8d4cff37c4bd558

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java]: I reverted this file to the develop version in 19e37984ff41e9ef7cd982d2e5d46ab374a6f252

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java (hunk 5 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java]: Implemented via your suggestion in 19e37984ff41e9ef7cd982d2e5d46ab374a6f252

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java [hunk 9]
```diff
@@ -242,6 +244,16 @@ String toDisplayString(boolean ignore) {
     return "Array_Builder";
   }
 
+  @ExportMessage
+  boolean hasLanguage() {
+    return true;
+  }
+
+  @ExportMessage
+  Class<? extends TruffleLanguage<?>> getLanguage() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java]: Can we add a test (based on `ValuesGenerator` that verifies all values of `EnsoObject` respond to this message?

**Review by JaroslavTulach — APPROVED** [review]
Having all of this in `getLanguageView` should show beneficial in the future. Hopefully.

**Comment by Akirathan** [comment]
Blocked by #11538

**Comment by JaroslavTulach** [comment]
> Blocked by #11538

How exactly this is blocked by
- #11538

?

**Comment by Akirathan** [comment]
> How exactly this is blocked by
> 
>     * [Implement hasLanguage interop message for all enso objects #11538](https://github.com/enso-org/enso/pull/11538)
> 
> 
> ?

The test in https://github.com/enso-org/enso/blob/339c2753383ef149748993c7039037f2bb08c191/engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java#L148 started to fail on this PR for a Value of primitive 42L. On this PR, `v.getMetaObject()` on that value returns non-null, but on develop it returns null. And for some reason, `warning2.getMetaObject()` returns null, thus the test fails. I figured out it would be just easier to first ensure that we stick to correct Truffle contracts and do that in a separate PR.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:101]: I was thinking the same way. But I am afraid that in order to implement this, [ContextUtils](https://github.com/enso-org/enso/blob/fb821303ab2818c4ce2d8482612584497f2e2014/lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java) would need to be an abstract class and all the test classes would need to extend it.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java [hunk 10]
```diff
@@ -177,4 +179,39 @@ public void doubleBigInteger() throws Exception {
...
+  }
+
+  @Test
+  public void everyValueSmallerThanLongMaxVal_IsPrimitiveLong() {
+    var almostMaxLong = Long.toString(Long.MAX_VALUE - 1);
+    var longVal = ContextUtils.evalModule(ctx, "main = " + almostMaxLong);
+    assertThat("Is a number", longVal.isNumber(), is(true));
+    assertThat("Does not fit in int", longVal.fitsInInt(), is(false));
+    assertThat("Fits in long", longVal.fitsInLong(), is(true));
+    assertThat("Does not fit in double (but could)", longVal.fitsInDouble(), is(false));
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java]: This is surprising. A value that fits in `Long`, but does not fit in `Double` (according to Enso) ??

Note that all of these 3 tests pass in develop

Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java]: Moreover, the `receiver` is `java.lang.Long`:
image

Seems like there is something funny in `PolyglotValueDispatch$PrimitiveValues` for Enso language.

**Comment by JaroslavTulach** [comment]
Right now I see following [four failures](https://github.com/enso-org/enso/actions/runs/12036354857/job/33557398231?pr=11468#step:7:6604):
- [DebuggingEnsoTest](https://github.com/enso-org/enso/actions/runs/12036354857/job/33557398231?pr=11468#step:7:6002) fails on _NullPointerException: Cannot invoke "java.util.Collection.size()" because the return value of "com.oracle.truffle.api.debug.DebugValue.getProperties()" is null_
- [testAtomFieldsAreReadable](https://github.com/enso-org/enso/actions/runs/12036354857/job/33557398231?pr=11468#step:7:6026) fails on _NullPointerException: Cannot invoke "com.oracle.truffle.api.debug.DebugValue.isReadable()" because "field1Prop" is null_
- [InsightForEnsoTest.computeFactorial](https://github.com/enso-org/enso/actions/runs/12036354857/job/33557398231?pr=11468#step:7:6067) fails with assertion error at `org.enso.interpreter.test.InsightForEnsoTest.computeFactorial(InsightForEnsoTest.java:90)`
- [WarningsTest](https://github.com/enso-org/enso/actions/runs/12036354857/job/33557398231?pr=11468#step:7:6084) fails on _Types without and with warnings are the same expected:<Integer> but was:<null>_

This is a fix that helps at least with the `WarningsTest`:
```diff
diff --git engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
index 4b23c33002..5b2288e9c2 100644
--- engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
+++ engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
@@ -445,7 +445,9 @@ public final class ValuesGenerator {
     }
 
     for (var v : collect) {

    assertTrue("It's a number" + v, v.isNumber());

+      if (!v.isNumber()) {
+        assertTrue("It's a number" + v, v.isNumber());
+      }
     }
     return collect;
   }
@@ -504,7 +506,9 @@ public final class ValuesGenerator {
     }
 
     for (var v : collect) {

    assertTrue("It is an boolean" + v, v.isBoolean());

+      if (!v.isBoolean()) {
+        assertTrue("It is an boolean" + v, v.isBoolean());
+      }
     }
     return collect;
   }
diff --git engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
index 3167895cb7..9ec91872a3 100644
--- engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
+++ engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
@@ -397,6 +397,9 @@ public final class EnsoLanguage extends TruffleLanguage<EnsoContext> {
       var cons = b ? bool.getTrue() : bool.getFalse();
       return AtomNewInstanceNode.getUncached().newInstance(cons);
     }
+    if (value instanceof Double d) {
+        return  new LanguageViewWrapper(d);
+    }
     var interop = InteropLibrary.getUncached();
     // We want to know if the value can be converted to some Enso builtin type.
     // In order to do that, we are trying to infer PolyglotCallType of value.to method.
```

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java (hunk 10 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java]: > A value that fits in Long, but does not fit in Double (according to Enso) ??

Every long value bigger than 2^52 that is not power of 2 doesn't fit into `double`. It doesn't fit because _it would loose precision_.

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java]: @GregoryTravis is our expert on `BigInteger`, `BigDecimal`, `Float`, `Integer` conversions...

Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BigNumberTest.java]: Fixed the issue by [not converting double to BigInt every time](1d012215e4ebdb42e13fc8eb98f96d1ca2f6ca27)

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java:101]: Tracked in https://github.com/enso-org/enso/issues/11683
