### PR TITLE
Fix serialization of alias analysis graph

### LINKED ISSUE #8431: `executeExpression` sometimes gives `Compiler Internal Error: ID 3 defined in multiple scopes.`
To reproduce: 

1. check out `wip/farmaazon/cb-preview` branch,
2. run new GUI with opened dev-tools 
3. Open project with the following Main.enso:
```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization.Preprocessor

main =
    operator1 = "Press ENTER key to create a new node"    
    operator13289 = operator1.length 
```
4. Open Component Browser

At this point, GUI always receives a message: 
```
{
    "jsonrpc": "2.0",
    "method": "executionContext/visualizationEvaluationFailed",
    "params": {
        "contextId": "ba7d1bfa-7475-45e5-b77d-60c846fe821e",
        "visualizationId": "e821316a-794d-4519-b0ff-f0144c3cb8f0",
        "expressionId": "d5cf4c57-9e05-4148-a0a6-301cca5ef277",
        "message": "Compiler Internal Error: ID 3 defined in multiple scopes.",
        "diagnostic": null
    }
}
```
And no value is send by binary connection.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #8431 

Fixes the scenario:
- user sends `executionContext/executeExpression`
- program execution is scheduled
- during the compilation the already compiled `IR` is loaded from the cache (reading invalid alias analysis graph)
- during the codegen the local scope with that aliasing graph is propagated to the runtime
- `EvalNode` compiles the expression to execute with the local scope containing an invalid aliasing graph
- compilation fails in the `AliasAnalysis` pass because of the clashing IDs in the graph

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java [hunk 1]
```diff
@@ -168,6 +172,7 @@ protected Graph readObject(Input in) throws IOException {
     protected void writeObject(Graph obj, Output out) throws IOException {
       out.writeObject(obj.rootScope());
       out.writeInline(scala.collection.immutable.Set.class, obj.links());
+      out.writeInt(obj.nextIdCounter());
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java:175]: You have to change the `id` of the persisted object to signal that old caches can no longer be read.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
Change the ID as described in [portability & versioning](https://github.com/enso-org/enso/blob/b5c995a7bfe7f0a58beee2d34686dedc04afb145/docs/runtime/ir-caching.md#portability-and-versioning) documentation. Otherwise OK - thanks for finding this omission of mine.

**Review by JaroslavTulach — APPROVED** [review]

**Review by hubertp — APPROVED** [review]
