### PR TITLE
Rearrange CB panels

### LINKED ISSUE #7244: Rearrange panels in Component Browser
Having a new single-column Component List Grid, and possibly new CB breadcrumbs, it's time to finish the visual part of the new CB design.

image

The navigator should be removed, and a new icon bar should be created on top. The icon bar should contain (functional) icon for showing/hiding documentation panel and "add library" icon, which should only display a caption similarly as it does in the old Component Browser. Other icons are not in scope of this task.

### LINKED ISSUE #7284: Opened projects are empty
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening a project (new or old does not matter), the IDE stays blank.

### Expected behaviour

The project should open. 

### How we can reproduce it?

Run IDE with `./run ide watch --skip-wasm-opt  --ide-option -debug.dev-tools=true --ide-option -debug --backend-source release --backend-release latest --ide-option `
Create a new project
Open the project

### Screenshots or screencasts

_No response_

### Logs

There are many errors about the shader compilation in the developer console:
image

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Manjaro 

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #7244 

- Section navigator removed
- Added a button panel on top of the documentation
- Show/hide documentation panel button is functional, documentation panel has animation.
- All other buttons are read-only (unclickable).
- "Hovered item preview" caption was removed from the documentation panel
- Breadcrumbs are flying in the temporary position. They should be functional but will be moved to the documentation panel in a separate task.
- Sizes and layouts of the CB panels match the design.
- The color of the application background changed. Also fixed a bug because of which the stylesheet setting of the background was not taken into account.

Known issues:
- ~~The buttons panel partially hides the topmost entry in the list. To fix that, we would need API changes to the grid view, I decided not to do that as part of the PR. We need to add padding on top of the scroll area content.~~
- Scrollbar is not rendered correctly at the bottom – the scroll area mask should crop it.
- Component list entries are not exactly as in design – I didn't touch this part of the code.
- Breadcrumbs are in the wrong position.

https://github.com/enso-org/enso/assets/6566674/409bebb5-572a-4760-852d-f666124689a2

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]

File: app/gui/view/component-browser/component-list-panel/grid/src/lib.rs [hunk 1]
```diff
@@ -505,6 +524,7 @@ impl component::Frp<Model> for Frp {
             grid_position <- style_and_content_size.map(Model::grid_position);
             eval grid_position ((pos) model.grid.set_xy(*pos));
             grid_scroll_frp.set_corner_radius_bottom_right <+ all(&corners_radius, &style.init)._0();
+            grid_scroll_frp.set_corner_radius_bottom_left <+ all(&corners_radius, &style.init)._0();
```
Comment (Frizi) [inline app/gui/view/component-browser/component-list-panel/grid/src/lib.rs]: The expression `all(&corners_radius, &style.init)._0()` is repeated, creating unnecessary FRP nodes. It should be given a name and used for both corners.

```suggestion
            init_corners_radius <- all(&corners_radius, &style.init)._0();
            grid_scroll_frp.set_corner_radius_bottom_right <+ init_corners_radius;
            grid_scroll_frp.set_corner_radius_bottom_left <+ init_corners_radius;
```

File: app/gui/view/component-browser/component-list-panel/src/button_panel.rs [hunk 2]
```diff
@@ -0,0 +1,211 @@
+//! The [button panel](Model). This is a narrow bar on the top of the Component List Panel
+//! that contains various buttons for controlling the Component Browser.
+
+use ensogl_core::display::shape::*;
+use ensogl_core::prelude::*;
+
+use crate::grid::entry::icon;
+
+use enso_frp as frp;
```
Comment (Frizi) [inline app/gui/view/component-browser/component-list-panel/src/button_panel.rs]: I believe that this is a part of prelude, so the import isn't necessary. Please also check other imports.

File: app/gui/view/component-browser/component-list-panel/src/button_panel.rs [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+
+
+            // === Initial state ===
+
+            model.side_panel.set_state <+ init.constant(true);
+            // Buttons below are not implemented.
+            model.local_scope.set_read_only <+ init.constant(true);
+            model.shortcuts.set_read_only <+ init.constant(true);
+            model.unstable.set_read_only <+ init.constant(true);
+            model.marketplace.set_read_only <+ init.constant(true);
```
Comment (Frizi) [inline app/gui/view/component-browser/component-list-panel/src/button_panel.rs]: Instead of using `init.constant`, the values can be emitted directly. This saves on creating multiple unnecessary FRP nodes and creating connections with them.
```suggestion
            model.side_panel.set_state(true);
            // Buttons below are not implemented.
            model.local_scope.set_read_only(true);
            model.shortcuts.set_read_only(true);
            model.unstable.set_read_only(true);
            model.marketplace.set_read_only(true);
```

File: app/gui/view/component-browser/src/lib.rs [hunk 4]
```diff
@@ -87,7 +76,7 @@ impl Model {
     ) -> Vector2 {
         let half_node_height = NODE_HEIGHT / 2.0;
         let panel_left = -size.x / 2.0;
-        let panel_bottom = -size.y / 2.0;
+        let panel_bottom = 0.0;
```
Comment (Frizi) [inline app/gui/view/component-browser/src/lib.rs:77]: `panel_bottom` variable is now unnecessary

File: app/gui/view/documentation/src/lib.rs [hunk 5]
```diff
@@ -236,7 +223,12 @@ ensogl::define_endpoints! {
     Input {
         /// Display documentation of the specific entry from the suggestion database.
         display_documentation (EntryDocumentation),
-        show_hovered_item_preview_caption(bool),
+        /// Open documentation panel with animation.
+        show(),
+        /// Close documentation panel with animation.
+        hide(),
```
Comment (Frizi) [inline app/gui/view/documentation/src/lib.rs]: How about using `set_visible (bool)` instead of `show/hide`? It looks like it would be both easier to use (since it is converted from bool at usage point anyway) and result in less FRP nodes created.

File: app/gui/view/documentation/src/lib.rs [hunk 6]
```diff
@@ -315,29 +312,26 @@ impl View {
...
 
             eval style.update((style) model.update_style(*style));
 
 
+            // === Show/hide animation ===
+
+            width_anim.target <+ frp.show.constant(1.0);
+            width_anim.target <+ frp.hide.constant(0.0);
+            width_anim.skip <+ frp.skip_animation;
+            width_anim.target <+ init.constant(1.0);
```
Comment (Frizi) [inline app/gui/view/documentation/src/lib.rs]: Instead of using this `init.constant`, the state could be initialized by emitting `show()` (or `set_visible(true)`) at the bottom of this `init` function.

File: lib/rust/ensogl/component/toggle-button/src/lib.rs [hunk 7]
```diff
@@ -48,6 +48,33 @@ pub trait ColorableShape: ShapeWithDefaultableData {
     fn set_color(&self, color: color::Rgba);
 }
 
+/// A shape that can be parametrized by any cached icon. Same as
+/// [`display::shape::compound::from_cache::recolorized`], but has an overlay for capturing mouse
+/// events and implements [`ColorableShape`].
+pub mod any_cached {
```
Comment (Frizi) [inline lib/rust/ensogl/component/toggle-button/src/lib.rs]: Instead of creating a whole new shape, it would be better to implemenet `ColorableShape` for `recolorized`. Same goes for mouse capture overlay. Alternatively, a dedicated rectangle shape could be used for mouse event capture.

**Review by Frizi — CHANGES_REQUESTED** [review]

File: app/gui/view/documentation/src/lib.rs (hunk 6 above)
Comment (farmaazon) [reply app/gui/view/documentation/src/lib.rs]: Even better, we can create `Animation` with `new_with_init` constructor.

File: app/gui/view/component-browser/src/lib.rs (hunk 4 above)
Comment (farmaazon) [reply app/gui/view/component-browser/src/lib.rs:77]: I believe it contributes much for code readability.

**Review by Frizi — APPROVED** [review]

**Comment by Frizi** [comment]
QA Report: 🧧 
---

1. It is possible to navigate using keyboard to a non-existent entry at the top of the list. After doing that, it is not possible to go back. Instead, it looks like the selection wraps around to the bottom.

https://github.com/enso-org/enso/assets/919491/f1b72bde-7770-4af7-8eed-3477f4ead0f5

2. Not sure if this is intended, but it looks wrong to me. The documentation show/hide animation is doing a full relayout every frame to adopt to the new width. Not only it looks unnecessarily busy, but it will also likely cause performance issues, as relayout of bigger documentations will take significant time. I believe that instead the animation should clip out the panel, without actually changing the internal CSS layout.

https://github.com/enso-org/enso/assets/919491/5b3204ba-4880-4316-a49a-81da80875ebc

**Comment by farmaazon** [comment]
Both comments are addressed. @Frizi please check again.

After all, I removed "fake entry" workaround and just added margins support for scrollable grid view.

**Comment by Frizi** [comment]
QA report: 🟡 
---

1. is adressed, the list now behaves correctly.
2. The animation is better, but missing rounded corners in the clipped region are a bit jarring to me. But it can be that way if implementing that is hard. The bigger issue is that the breadcrumbs panel background seems to be still present when the documentation is collapsed. If this is to be addressed separately, then I'd give it a pass.

image

**Comment by farmaazon** [comment]
The breadcrumbs will be fixed on [new docpanel style PR](7372 )
