### PR TITLE
Fix update info

### LINKED ISSUE #12207: Stale type of a value information
_As reported internally_
```
If it recalculates from an error to a valid table the type value isn't getting calculated.
```

Image

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #12207 

Removes temporary fix introduced in https://github.com/enso-org/enso/pull/12163

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/stores/project/computedValueRegistry.ts [hunk 1]
```diff
@@ -86,6 +79,7 @@ function updateInfo(
 ) {
   const newInfo = combineInfo(info, update, projectNames)
   if (newInfo.typename !== info.typename) info.typename = newInfo.typename
+  if (newInfo.rawTypename !== info.rawTypename) info.rawTypename = newInfo.rawTypename
```
Comment (JaroslavTulach) [inline app/gui/src/project-view/stores/project/computedValueRegistry.ts:82]: I was looking at this line today! And I haven't noticed missing `rawTypename` assignment in this "copy" updater.

**Review by JaroslavTulach — APPROVED** [review]

**Review by kazcw — COMMENTED** [review]
This fixes the bug, but the code is still fragile. Here's a trick I've used in a similar situation:

https://github.com/enso-org/enso/blob/a90a3e6727be00a20581914d5f5699185779eb32/app/gui/src/project-view/stores/graph/graphDatabase.ts#L375-L386

If a new field is added to the type, the unused object will no longer satisfy the type constraint, ensuring the code is kept up-to-date.

**Review by farmaazon — APPROVED** [review]
