### PR TITLE
Fix `ensoup` launcher upgrade mechanism

### LINKED ISSUE #11821: `ensoup` self-upgrade is broken
The self-upgrade mechanism of the launcher has been broken by #10535 - there we renamed the executable from `enso` to `ensoup` but we forgot to update the relevant parts of update logic (and include necessary migration release that would guarantee us a continuity of the 'upgrade path').

Unfortunately this was not detected by our tests, because they consist of mock executables and these are still called `enso`.

We need to:
- [x] update the upgrade mechanism to use the new name.
- [x] update mocks in tests so that the old name would actually fail.
- ~~consider adding some check that ensures the mock is aligned with real distribution?~~ _That's not what the problem was, the problem was disabled tests..._
- ~~(optional) consider releasing a 'migration' release that would contain both `enso` and `ensoup` so that older launcher versions could still upgrade?~~ _Probably not much useful as the launcher is not widely used so manual upgrade at this point is acceptable._

### LINKED ISSUE #11831: `ensoup upgrade` fails to upgrade development build and enters an infinite cycle if no upgrade path was found
I just tested `ensoup upgrade` and it fails because as one of its steps it lists all available releases to find the most appropriate one to upgrade to.

However, since we have been publishing nightly releases for several years, the list of releases is so big that the the launcher exceeds the unauthenticated GH API limits and fails with:
```
[ERROR] [2024-12-11T12:04:23+01:00] [org.enso.launcher.cli.Main] A fatal error has occurred: GitHub Release API rate limit exceeded for your IP address. Please try again in a while.
```

To make `ensoup upgrade` work again we need to either:
- remove some old nightly releases
- OR avoid listing all releases, perhaps we only need to find the latest one?

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Closes #11821 by updating the upgrade logic to the new executable name
- Re-enables the long disabled `UpgradeSpec` to make sure this remains tested.
	- If the tests were enabled we would have caught the regression in #10535
	- The tests have been heavily outdated due to being disabled, many small details changed and had to be amended.
	- The tests are still marked as Flaky - they were known to be problematic on CI so their failures will not stop CI for now. But at least they are run and we can see if they succeed or not. Plus when running tests locally they will fail (as all tests marked as Flaky - the failure is only ignored on CI).
- Fixes another issue with an infinite cycle when no upgrade path can be found and adds a test for this case.
	- If running a development build, the minimum version check can be ignored, as the check does not really make sense for `0.0.0-dev` build.
	- Thus it closes #11831 also.
- Makes sure that `GithubAPI` caches the list of releases as fetching it can take time.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala [hunk 1]
```diff
@@ -331,7 +331,7 @@ class LauncherUpgrader(
 
       val temporaryExecutable = temporaryExecutablePath("new")
       FileSystem.copyFile(
-        extractedRoot / "bin" / OS.executableName("enso"),
+        extractedRoot / "bin" / OS.executableName(Constants.name),
```
Comment (radeusgd) [inline engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:409]: This change is the core of the fix - after changing the package structure, we need to use the right executable name for the copy. We forgot to update it earlier.

**Review by Akirathan — APPROVED** [review]

**Review by GregoryTravis — APPROVED** [review]

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala [hunk 2]
```diff
@@ -97,7 +97,39 @@ class LauncherUpgrader(
...
+              s"a development version, the minimum version check can be " +
+              s"ignored. However, please be warned that the upgrade " +
+              s"may fail due to incompatibility."
+            )
+            CLIOutput.askConfirmation(
+              "Do you want to continue upgrading to this version " +
+              "despite the warning?"
+            )
+          }
+        } else false
```
Comment (radeusgd) [inline engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:130]: If direct update cannot be performed due to version check, but this is a development build we ask the user what to do (or rely on auto-confirm as everywhere).

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala [hunk 3]
```diff
@@ -217,28 +266,53 @@ class LauncherUpgrader(
...
+    // We look at older versions that are satisfying the minimum version
+    // required to upgrade to currentTargetRelease.
+    val recentEnoughVersions =
+      availableVersions.filter { possibleVersion =>
+        val canUpgradeToTarget = possibleVersion.isGreaterThanOrEqual(
+          currentTargetRelease.minimumVersionToPerformUpgrade
+        )
+        val isEarlierThanTarget =
+          possibleVersion.isLessThan(currentTargetRelease.version)
+        canUpgradeToTarget && isEarlierThanTarget
```
Comment (radeusgd) [inline engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:288]: Adding the second condition `isEarlierThanTarget` makes sure we 'progress' in going backwards in 'time'. Thus it breaks the infinite cycle - if we cannot find an earlier version that can upgrade to the current target, we will fail.

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala [hunk 4]
```diff
@@ -217,28 +266,53 @@ class LauncherUpgrader(
...
       throw UpgradeError(
-        s"Upgrade failed: To continue upgrade, a version at least " +
-        s"${release.minimumVersionToPerformUpgrade} is required, but no " +
-        s"valid version satisfying this requirement could be found."
+        s"Upgrade failed: To continue upgrade, at least version " +
+        s"${currentTargetRelease.minimumVersionToPerformUpgrade} is required, " +
+        s"but no upgrade path has been found from the current version " +
+        s"${CurrentVersion.version}. " +
+        s"Please manually download a newer release from " +
+        s"${LauncherRepository.websiteUrl}"
```
Comment (radeusgd) [inline engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:301]: Added a note that links to the GH repository where the user can manually download a new release.

**Comment by radeusgd** [comment]
On development version we ask the user if they want to ignore the version check for upgrade:
image


https://github.com/user-attachments/assets/200c443a-9539-4222-a2e4-74a2c29c867d

**Comment by radeusgd** [comment]
Also improved the error paths a little bit when the release does not exist:

Before:
```
[ERROR] [2024-12-12T15:38:53+01:00] [org.enso.launcher.cli.Main] A fatal error has occurred: The server has responded with 404 status.
```
After:
```
[ERROR] [2024-12-12T15:56:24+01:00] [org.enso.launcher.cli.Main] A fatal error has occurred: Cannot find release `0.0.0-nonexistent`.
```

**Review by Akirathan — APPROVED** [review]
How stable are the `UpgradeSpec` tests on the CI?

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala [hunk 5]
```diff
@@ -120,11 +153,13 @@ class LauncherUpgrader(
...
-      logger.debug("Cleaning temporary files from a previous upgrade.")
+      logger.debug(
+        s"Cleaning ${temporaryFiles.size} temporary files from a previous upgrade."
+      )
     }
     for (file <- temporaryFiles) {
       try {
-        Files.delete(file)
+        tryHardToDelete(file)
         logger.debug(s"Upgrade cleanup: removed `$file`.")
```
Comment (GregoryTravis) [inline engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:163]: It would be good to log whether or not the file actually got deleted, or if it gave up after 30 attempts.

**Review by GregoryTravis — APPROVED** [review]

**Comment by radeusgd** [comment]
> How stable are the `UpgradeSpec` tests on the CI?

Hard to say, last time they were run was ages ago, CI was completely different. But they are marked as flaky so even if they fail they should not make CI fail - just report the tests as pending.

File: engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala (hunk 5 above)
Comment (radeusgd) [reply engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala:163]: But isn't it exactly what we are doing?

Just below there's `catch` that logs "Cannot remove temporary file" if it failed after the retries.

**Review by AdRiley — APPROVED** [review]
