### PR TITLE
Fix ClassCastException when builtin is invoked with wrong args

### LINKED ISSUE #11774: Runtime crash: Function cannot be cast DataflowError
While trying to simulate https://github.com/enso-org/enso/pull/11673/files/a041045046c7ab0dded3e1920649fa357ecfe5b3#r1870576716 I wrote following `ref.enso` program:

```ruby
from Standard.Base import all

import Standard.Base.Runtime.Ref.Ref

from Standard.Base.IO import println

main =
    r = Ref.new 0
    println r
    Error.catch Any (Error.throw "No longer valid") err->
        println err
        ref.put err
    println r
```

it crashes the engine with:
```
Execution finished with an error: java.lang.ClassCastException: class org.enso.interpreter.runtime.callable.function.Function cannot be cast to class org.enso.interpreter.runtime.error.DataflowError (org.enso.interpreter.runtime.callable.function.Function and org.enso.interpreter.runtime.error.DataflowError are in module org.enso.runtime of loader 'app')
        at <java> org.enso.runtime/org.enso.interpreter.runtime.type.TypesGen.asDataflowError(TypesGen.java:180)
        at <java> org.enso.runtime/org.enso.interpreter.node.expression.builtin.error.CatchErrorMethodGen.execute(CatchErrorMethodGen.java:116)
        at <enso> Error.catch_primitive(Internal)
        at <enso> ref.main(ref.enso:10-12)
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #11774

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  public void invokeBuiltinWithWrongArguments_ShouldNotCrash() {
+    var src =
+        """
+        from Standard.Base import all
+
+        main =
+            Error.catch Any (Error.throw "No longer valid") x->x
+        """;
+    var res = ContextUtils.evalModule(ctx, src);
+    assertThat("Should not crash - should return something", res, is(notNullValue()));
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java]: `assertNotNull` would be shorter.

I am starting to use `assertThat` for various checks, but in this case I'd stick to old good `assertNotNull` ;-)

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+  }
+
+  @Test
+  public void invokeBuiltinWithWrongArguments_ShouldNotCrash() {
+    var src =
+        """
+        from Standard.Base import all
+
+        main =
+            (Error.catch_primitive self=(y->y)) (x->x)
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java:34]: Would it be too much to ask for the `catch_primitive` builtin to be moved outside of `Error` class? Place it into some `Error_Helpers` or `Error_Builtins` module which is marked as `private` and probably in `Internal` namespace? Make it a `error_catch_builtin` static method?

**Review by JaroslavTulach — APPROVED** [review]
Assuming the test failed originally and now works, feel free to move on and integrate. One wish whispered inline...

**Comment by Akirathan** [comment]
> Assuming the test failed originally and now works, feel free to move on and integrate.

Yes, that is the case. On develop, the new test is failing.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java:34]: Not at all. Done in d4cebfb65d63678daf053fc316054b6ea5a5a131. I will remember in the future, that we want to slowly start putting builtin methods inside internal private modules.

**Review by AdRiley — APPROVED** [review]

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java:34]: I was afraid it might not be [completely easy](https://github.com/enso-org/enso/actions/runs/12767063859/job/35584681142?pr=12033#step:7:5587):
```
Test org.enso.interpreter.test.builtins.BuiltinsInvocationTest.invokeBuiltinWithWrongArguments_ShouldNotCrash failed: java.lang.AssertionError: Should have Type error as payload
Expected: (a string containing "Type error" and a string containing "Dataflow_Error")
      but: a string containing "Dataflow_Error" was "Type error: expected a function, but got Error.", took 1.479 sec
     at org.enso.interpreter.test.builtins.BuiltinsInvocationTest.invokeBuiltinWithWrongArguments_ShouldNotCrash(BuiltinsInvocationTest.java:42)
     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
     at java.lang.reflect.Method.invoke(Method.java:580)
     ...
```

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java:34]: I believe this is the expected error message. Updated in https://github.com/enso-org/enso/pull/12033/commits/e2a2dc0b416ee4ed59b3d814e917f05eca138dc8
