### PR TITLE
Pattern match does not evaluate suspended atom fields

### LINKED ISSUE #10465: Pattern matching with `_` forces computation of lazy fields too eagerly
Let me show this on example:
```
from Standard.Base import all

type My_Ref
    Lazy ~lazy
    Eager eager

    get_if_eager self = case self of
        My_Ref.Eager x -> x
        My_Ref.Lazy _ -> Nothing

    get self should_compute:Boolean = case self of
        My_Ref.Eager x -> x
        My_Ref.Lazy x -> if should_compute then x else Nothing

    tricky_get_if_eager self =
        atom = Meta.meta self
        if atom.constructor.name == "Eager" then atom.value else Nothing

main =
    v1 = My_Ref.Lazy <|
        IO.println "Computing v1"
        42
    
    IO.println (v1.get_if_eager)

    v2 = My_Ref.Lazy <|
        IO.println "Computing v2"
        44

    IO.println (v2.get False)

    v3 = My_Ref.Lazy <|
        IO.println "Computing v3"
        46

    IO.println (v3.tricky_get_if_eager)
```

The current behaviour is as follows:
```
Computing v1
Nothing
Computing v2
Nothing
Nothing
```

As we can see both `v1` and `v2` are computed. I think this is wrong.

Ideally, neither of them should be computed as we don't use either value. 

It seems acceptable to compute `v2` as we are binding the value to `x` so it seems OK to force it to compute. However ideally, the variable `x` could 'inherit' the laziness and only be computed if it is actually demanded (as if it were an `~suspended` argument). It could possibly be marked by using `My_Ref.Lazy ~x -> ...` in the pattern match. Currently I have checked and adding the `~` to `x` and `_` does not change the behaviour.

However, for `_` it should really be noted to not be computed as we explicitly ignore the value. This makes decomposing a value without triggering execution quite hard - as shown in `tricky_get_if_eager` - the only variant that currently works as desired.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #10465

### Pull Request Description

Structural pattern match with `_` does no longer force the lazy fields to be evaluated.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Revert https://github.com/enso-org/enso/commit/81b2c82e72249c91c636e248db02f37aa97b18bb
- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md)
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java [hunk 1]
```diff
@@ -175,6 +179,63 @@ public void toTextOnAtomWithLazyField() throws URISyntaxException {
...
+        main =
+            v2 = My_Ref.Lazy <|
+                IO.println "Computing v2"
+                42
+
+            should_compute = False
+
+            case v2 of
+                My_Ref.Eager e -> e
+                My_Ref.Lazy l ->
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java:228]: - I'd be interested in ensuring that `My_Ref.Lazy l:Integer` case match does work as expected (e.g. it does evaluate the `l` field)
- Maybe also that `My_Ref.Lazy l:Text` fails

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java [hunk 2]
```diff
@@ -85,9 +89,41 @@ private static Object[] fieldsFromObject(
       Object obj, AtomConstructor cons, StructsLibrary structsLib) {
     CompilerAsserts.partialEvaluationConstant(cons);
     var arr = new Object[cons.getArity()];
+    var fields = cons.getFields();
     for (var i = 0; i < arr.length; i++) {
-      arr[i] = structsLib.getField(obj, i);
+      // Wrap suspended fields in functions, so that they are not evaluated
+      // too eagerly.
+      if (fields[i].isSuspended() && obj instanceof Atom atom) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java:96]: - idea: Shouldn't there be `structsLib.isSuspended(obj, i)`?

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java [hunk 3]
```diff
@@ -85,9 +89,41 @@ private static Object[] fieldsFromObject(
...
     return arr;
   }
+
+  @TruffleBoundary
+  private static Function createSuspendedFieldFunction(Atom atom, int fieldIdx) {
+    var getFieldNode = new GetSuspendedFieldNode(atom, fieldIdx);
+    return Function.fullyApplied(getFieldNode.getCallTarget());
+  }
+
+  private static final class GetSuspendedFieldNode extends RootNode {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java:112]: - there already is [LazyCheckRootNode](https://github.com/enso-org/enso/blob/773511ae3766924402510da33c5001f67eea4a96/engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/LazyCheckRootNode.java#L13) which is quite similar
- is some unification possible/desirable?
- why is this a `RootNode` and not `ClosureEnsoNode`?
- will it be properly represented in stacktraces? `LazyCheckRootNode` probably isn't...

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala [hunk 4]
```diff
@@ -1801,6 +1830,62 @@ private[runtime] class IrToTruffle(
...
     }
 
+    /** Case branch of a [[Pattern.Constructor]] is represented as a function with parameters matching the
+      * fields of the constructor. This method converts those fields into function arguments.
+      * If a field is suspended, the corresponding argument is marked as suspended too.
+      * @param cons Constructor pattern.
+      * @param resolvedCons The actual constructor resolved at runtime.
+      * @return
+      */
+    private def atomFieldsAsArguments(
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:1840]: Shouldn't this be a method in `AtomConstructor`? Not taking `Pattern.Constructor`, but for example `String[] fieldsAsName` argument? It seems to me this is quite _constructor specific behavior_ that'd be better encapsulated in `AtomConstructor`.

**Review by JaroslavTulach — APPROVED** [review]
- Nice
- If we are green, then let's go!

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java:228]: Added tests for it in a403dabcc44bdaa33bbbb4ec416e786611c7c734. Currently, they are failing, because the type assertion forces the field to be evaluated. I will need to implement also lazy type checking for this.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java:96]: That seems like a better idea than this hack with `instanceof`. I will implement this new message.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java:228]: - I think you can change the tests, to "materialize" the lazy field.
- we need the real value to perform the type check
- so "materializing" the field is OK
- I just wanted to cover that behavior with a test

Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java:228]: Yes, you are right. The lazy field needs to b e materialized in order for the type check to work. Changed in 8a2ddd370c2226e67cb6fc59e6447aa409d5c1f7

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java:96]: Tried that. But I would also need a message like `getFieldGetterFunction` which would return a function that would materialize the field. Which turned out to be too complicated.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java:112]: > is some unification possible/desirable?

I don't think so. `LazyCheckRootNode` wraps field getter Function with a type check. It is specific for type checking.

> will it be properly represented in stacktraces? 

Not really. None of the field getter functions are. That is, from the stack trace, it is not visible that you are in a field getter. If that is desirable, we should change that in all the field getters.

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:1840]: Tough to say. It is specific to the constructor, but only to the IR of the constructor. `AtomConstructor` represents the constructor from the runtime perspective, not its IR. Therefore, I don't think it should be located in `AtomConstructor`.

Most likely, the `AtomConstructor` would not even be [initialized](https://github.com/enso-org/enso/blob/5fd485066fd3b2d8c769de8a7e8f4c8f6a1442f7/engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java#L94-L101).

Note that `resolvedCons` is an `AtomConstructor` that is fetched from some IR metadata.

**Review by GregoryTravis — APPROVED** [review]
