### PR TITLE
Always write Config's namespace and dashboard accepts a default one

### LINKED ISSUE #10564: Lack of `namespace` field in project's `package.yaml` makes PM classify it as a plain directory
If `package.yaml` has no
```
namespace: "local"
```
entry:
Screenshot from 2024-07-16 12-43-01

Once added, it magically changes to
Screenshot from 2024-07-16 12-43-25

I think the regression was introduced when serializing default values of YAML files, as part of https://github.com/enso-org/enso/commit/c54c3b7e9da42a3c6fc0578c5f2c7437deba890d.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Closes #10564. Dashboard accepts only projects with non-empty namespace.
The change in project-manager ensures that we serialize `namespace` even if it is a default one.
The change in dashboard ensures that namespace can be empty.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]

**Review by MrFlashAccount — APPROVED** [review]

**Review by JaroslavTulach — APPROVED** [review]

File: app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts [hunk 1]
```diff
@@ -460,7 +460,7 @@ function extractProjectMetadata(yamlObj: unknown, jsonObj: unknown): ProjectMeta
             'lastOpened' in jsonObj && typeof jsonObj.lastOpened === 'string'
                 ? validDateString(jsonObj.lastOpened)
                 : null
-        if (name != null && namespace != null && id != null && created != null) {
+        if (name != null &&  id != null && created != null) {
```
Comment (somebody1234) [inline app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts]: double space

**Review by kazcw — APPROVED** [review]
