### PR TITLE
Compute the exception message sooner than context is closed

### LINKED ISSUE #11127: `AssertionError` with `payload Error Error.type UnresolvedSymbol<==>` when executing Base_Tests
More info has been added to the reported missing polyglot context assertion (#11113) which resulted in
```
 INFO ide_ci::program::command: cmd ⚠️ Caused by: java.lang.AssertionError: Failed to log failed conversion of null to string and payload Error Error.type UnresolvedSymbol<==>
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.computeMessage(PanicException.java:95)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:76)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.runtime/org.enso.interpreter.runtime.error.PanicException.toString(PanicException.java:106)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.lang.Throwable.<init>(Throwable.java:319)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.lang.Exception.<init>(Exception.java:103)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/java.io.IOException.<init>(IOException.java:98)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.withProfiling(Main.java:1205)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.launch(Main.java:1450)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.launch(Main.java:1402)
 INFO ide_ci::program::command: cmd ⚠️ 	at org.enso.IsolatedClassLoader//org.enso.runner.Main.main(Main.java:1019)
 INFO ide_ci::program::command: cmd ⚠️ 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 INFO ide_ci::program::command: cmd ⚠️ 	... 2 more
 INFO ide_ci::program::command: cmd ⚠️ Caused by: java.lang.AssertionError: No polyglot context is entered. A language or context reference must not be used if there is no polyglot context entered.
 INFO ide_ci::program::command: cmd ⚠️ 	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.assertValidGet(PolyglotFastThreadLocals.java:481)
 ```
- at https://github.com/enso-org/enso/actions/runs/10926101745/job/30329191172#step:7:1251
- at https://github.com/enso-org/enso/actions/runs/11036714355/job/30655819392?pr=10823#step:7:2605

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

There is a problem with logging when `TruffleLoggger` is used after its _context is closed_. Alas, that's exactly happening when `PanicException` is thrown. The context is closed first and only then the exception's [getMessage() method](https://github.com/enso-org/enso/blob/a2c853c6e31926807b7e44470ae4d5bbdc68aac9/engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java#L87) is invoked trying to call into the _context again_. Following fixes to this problem are provided:
- let's use `slf4j` logger instead of `TruffleLogger` - then the `catch (AssertionError)` dealing with `assert` from Truffle logger can be removed
- let's materialize `PanicException.getMessage()` before we leave the context
- as a bonus also log stacktrace of `StackOverflowError` before leaving the context (observed when `getMessage()` was computed in `PanicException` constructor)

### Important Notes

Accessing Truffle's [ctx.getLogger().log(Level.WARNING however asserts](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLogger.java#L1014) at that moment. That's pretty bad, @tzezula, @chumer, as that means the **actual exception is lost** instead of logged! I used to blame our logging implementation for _swallowing exceptions_ - looks like (at least in this case), `TruffleLogger` is to blame. _Exceptions shouldn't be swallowed_. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java [hunk 1]
```diff
@@ -202,8 +203,21 @@ static Object doCall(
...
         @Cached InteropApplicationNode interopApplicationNode,
         @CachedLibrary("function") InteropLibrary thisLib) {
-      return interopApplicationNode.execute(
-          function, EnsoContext.get(thisLib).emptyState(), arguments);
+      try {
+        return interopApplicationNode.execute(
+            function, EnsoContext.get(thisLib).emptyState(), arguments);
+      } catch (StackOverflowError err) {
+        CompilerDirectives.transferToInterpreter();
+        var asserts = false;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:214]: Yesterday I noticed @AdRiley had problems to analyze `StackOverflowError` to find out where it happens because `PolyglotException` wrapping the error **hides the stack over flow error stacktrace**. There doesn't seem to be any way to dig the stack from the `PolyglotException` without hacky reflection, but we can log the stack before it gets converted - log it at this moment:
```
	at org.enso.interpreter.runtime.callable.function.Function$Execute.doCall(Function.java:205)
	at org.enso.interpreter.runtime.callable.function.FunctionGen$InteropLibraryExports$Cached.executeAndSpecialize(FunctionGen.java:122)
	at org.enso.interpreter.runtime.callable.function.FunctionGen$InteropLibraryExports$Cached.execute(FunctionGen.java:108)
	at com.oracle.truffle.api.interop.InteropLibrary$Asserts.execute(InteropLibrary.java:3132)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedExecuteNode.doDefault(PolyglotValueDispatch.java:4607)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedExecuteNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:9528)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedExecuteNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9480)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteNoArgsNode.doDefault(PolyglotValueDispatch.java:4714)
	at com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$ExecuteNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9987)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at com.oracle.truffle.runtime.OptimizedRuntimeSupport.callProfiled(OptimizedRuntimeSupport.java:266)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.execute(PolyglotValueDispatch.java:2642)
	at org.graalvm.polyglot.Value.execute(Value.java:928)
	at org.enso.polyglot.Function.execute(Function.scala:17)
	at org.enso.runner.Main.runMain(Main.java:904)
	at org.enso.runner.Main.runPackage(Main.java:857)
	at org.enso.runner.Main.handleRun(Main.java:753)
	at org.enso.runner.Main.mainEntry(Main.java:1134)
	at org.enso.runner.Main.lambda$launch$22(Main.java:1477)
	at org.enso.runner.Main$$Lambda/0x0000710df011ca00.call
	at org.enso.runner.Main.withProfiling(Main.java:1224)
	at org.enso.runner.Main.launch(Main.java:1473)
	at org.enso.runner.Main.launch(Main.java:1425)
	at org.enso.runner.Main.main(Main.java:1040)
```
if we are running with _assertions enabled_ (like on CI), let's dump the stack with high severity. When running without asserts on, use `enso --log-level debug --run over.enso` to dump the stack.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java [hunk 2]
```diff
@@ -201,9 +204,28 @@ static Object doCall(
...
+        if (asserts) {
+          logger.error("StackOverflowError detected", err);
+        } else {
+          logger.debug("StackOverflowError detected", err);
+        }
+        throw err;
+      } catch (PanicException ex) {
+        panicProfile.enter(thisLib);
+        // materialize the exception message
+        ex.getMessage();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:226]: Make sure `PanicException.cachedMessage` is computed before leaving the Enso boundary - e.g. most probably before leaving the `org.graalvm.polyglot.Context`.

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/PanicsTest.scala [hunk 3]
```diff
@@ -49,6 +49,29 @@ class PanicsTest extends InterpreterTest {
...
+          |
+          |    to_display_text self =
+          |        res = self.txt + " from exception"
+          |        Panic.throw res
+          |
+          |main = Panic.throw (LM.V "Hi")
+          |""".stripMargin
+
+      try {
+        eval(code)
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/PanicsTest.scala:67]: `eval(code)` is expected to throw `InterpreterException`, right? Shouldn't you add `fail("Exception expected")` after this line then?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java [hunk 4]
```diff
@@ -201,9 +204,28 @@ static Object doCall(
...
         @Cached InteropApplicationNode interopApplicationNode,
-        @CachedLibrary("function") InteropLibrary thisLib) {
-      return interopApplicationNode.execute(
-          function, EnsoContext.get(thisLib).emptyState(), arguments);
+        @CachedLibrary("function") InteropLibrary thisLib,
+        @Cached InlinedBranchProfile panicProfile) {
+      try {
+        return interopApplicationNode.execute(
+            function, EnsoContext.get(thisLib).emptyState(), arguments);
+      } catch (StackOverflowError err) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:212]: How is JVM even able to call any methods after catching `StackOverflowError`? Is the stack of the current thread that caused the SO temporarily increased? Are you entirely sure that the stacktrace will be printed on SO? Have you tested it?

**Review by Akirathan — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:212]: Yes, I did manual testing. `StackOverflowError` isn't caught when it happens, but after the stack is unrolled. The stack when the error is caught [can be seen here](https://github.com/enso-org/enso/pull/11241#discussion_r1787254091) and is actually pretty shallow.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:226]: Done in 7c0472b

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/PanicsTest.scala (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/PanicsTest.scala:67]: Done in 7c0472b

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java [hunk 5]
```diff
@@ -81,21 +82,13 @@ public String getMessage() {
...
-        var ctx = EnsoContext.get(null);
-        ctx.getLogger().log(Level.WARNING, "Cannot convert " + info + " to string", e);
-        msg = TypeToDisplayTextNode.getUncached().execute(payload);
-      } catch (AssertionError assertionError) {
-        throw new AssertionError(
-            "Failed to log failed conversion of " + info + " to string and payload " + payload,
-            assertionError);
-      }
+    } catch (StackOverflowError | AssertionError | UnsupportedMessageException e) {
+      logger().atError().log("Cannot compute message for " + payload, e);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java:90]: Reports stacktrace with error even in production. Is that what we want @hubertp? Or do we just want a one line note being logged and stacktrace only with `--log-level debug`? What's the right way to log in such case?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:214]: @hubertp, if there is a _more standard pattern for logging_ with stacktrace on CI and not logging the stacktrace in production by default, but only with bigger verbosity that doesn't involve `assert`, please advice what it is. I'll be glad to use it instead.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java [hunk 6]
```diff
@@ -81,21 +82,13 @@ public String getMessage() {
...
-      try {
-        var ctx = EnsoContext.get(null);
-        ctx.getLogger().log(Level.WARNING, "Cannot convert " + info + " to string", e);
-        msg = TypeToDisplayTextNode.getUncached().execute(payload);
-      } catch (AssertionError assertionError) {
-        throw new AssertionError(
-            "Failed to log failed conversion of " + info + " to string and payload " + payload,
-            assertionError);
-      }
+    } catch (StackOverflowError | AssertionError | UnsupportedMessageException e) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java:89]: @AdRiley based on today's _pair debugging_ session I decided to catch `StackOverflowError` here when computing `to_display_text`. If that recurses too deep, we catch it and the original panic should be thrown with a simplified message. Unit test seems to work. Can you verify it also works in your case?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java:214]: The problem is that CI simply uses `enso` as a CLI, with no additional options. So cli used by regular users would behave the same way. I will see if I can add customize it further for CI via some env var.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java (hunk 5 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java:90]: I had another look at our CLI. It appears that somehow *no* logging setup is being done and it does not use our own configuration. Not sure if this broke over the many refactorings that happened or has not been implemented (as it wasn't a priority). Filed https://github.com/enso-org/enso/issues/11265.
For now, feel free to merge as is.

**Review by hubertp — APPROVED** [review]
Re logging format and printing in CLI I filed a separate ticket #11265

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java:90]: OK. Merging. Notes:

- CI is running with `-ea` maybe there could be more verbose configuration when `-ea` is on
- you don't want to show stacktraces for `enso` users regardless log level used, OK.
- I just like to know the right code snippet that shows message and also exception stacktrace on CI
- I'd like to know the right code snippet to show message without exception stacktrace on CI
- I'd like to know value for `--log-level` that shows stacktrace even for exception that doesn't show stacktrace in default config
