### PR TITLE
Fix doubled named arguments bug

### LINKED ISSUE #6228: Last named argument gets doubled when the first argument is removed
How to reproduce:

1. Create a `Data.fetch` node
2. Connect `uri`, `method` and `headers` to it
3. Delete the `uri` node
4. the `headers` argument is `headers=headers=var2` now

[headers_headers.webm](https://user-images.githubusercontent.com/357683/230677071-eac9046a-92da-4bd5-899c-ad257b9fa454.webm)

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #6228 

An annoying issue was hidden deep in the code for updating named arguments after input port disconnection.

Kudos to @Frizi for help with investigating it and the initial implementation of the fix.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/language/span-tree/src/action.rs [hunk 1]
```diff
@@ -286,8 +286,39 @@ impl<'a, T> Implementation for node::Ref<'a, T> {
...
+                    // We are iterating over the old span tree, while modifying an expression that
+                    // constantly changes. The assumption here is that as we go, we only modify AST
+                    // tree deeper than we will look in future iterations. That way we can be sure
+                    // that the "outer layers" of AST still corresponds to the original span-tree.
+                    // It is done that way, because we have no way of actually reconstructing the
+                    // span-tree to be entirely correct on every step. The new AST is after all
+                    // wrong and needs to be fixed for a reason. Rebuilding the span-tree before
+                    // replacing named arguments will give you wrong assignments on everything.
+                    // The loop propagates up the old span tree, knowing that the outer layers of
+                    // the AST will still corresponds to it.
```
Comment (farmaazon) [inline app/gui/language/span-tree/src/action.rs]: I must admit, I have a strong difficulty in understanding this paragraph:

> We are iterating over the old span tree, while modifying an expression that constantly changes

I suppose the expression is actually an `ast` variable?

> The new AST is after all wrong and needs to be fixed for a reason.

What does it mean, "AST" is wrong? What AST? The old one, or that after applying a change? 

> Rebuilding the span-tree before replacing named arguments will give you wrong assignments on everything.

What is "replacing named arguments"? Looking at the code, I thought we actually are adding new named arguments, or rather: replace the named with the unnamed.

I guess this just to say we change the arguments to named starting from the last one (as it's in the deepest level)? I think such introductory sentence would help me a lot.

**Review by farmaazon — APPROVED** [review]
I approve it to not block the important fix, but the comment should be improved.

File: app/gui/language/span-tree/src/action.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/language/span-tree/src/action.rs]: Updated the paragraph, I hope it is better now.

> I suppose the expression is actually an ast variable?

Yes

> What does it mean, "AST" is wrong? What AST? The old one, or that after applying a change?

Sorry, it was a mistake. The span tree is meant here, not the AST.

> What is "replacing named arguments"?

I removed this sentence. The better word is `rewriting`, though. We rewrite named arguments to a different form.

> I guess this just to say we change the arguments to named starting from the last one (as it's in the deepest level)? I think such introductory sentence would help me a lot.

This is actually the opposite. The last argument is on the top of the tree, see attached ASCII graphics. I added an additional note about it.

**Comment by Procrat** [comment]
QA: Looks good to me! I've hit this bug a couple of times in the past, so it's great to see it fixed!
