### PR TITLE
Fix layout when editing existing node

### LINKED ISSUE #12760: Edges to non-self ports displayed incorrectly during component editing
https://github.com/user-attachments/assets/8e79ba56-807c-4a66-9a49-d04eaa600e37

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #12760 

The issue is addressed by keeping WidgetPorts rects when starting editing + make minimum width of Component Browser, so no edges will be dangling.

https://github.com/user-attachments/assets/cdd4bb70-54e1-4174-85ec-4d2b31892986

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue [hunk 1]
```diff
@@ -730,4 +730,8 @@ onWindowBlur(() => {
 .dragged {
   cursor: grabbing !important;
 }
+
+.edited {
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/GraphNode.vue:736]: I think it would be useful to comment here why this instead of `v-show`

**Review by kazcw — APPROVED** [review]
