### PR TITLE
Multiflavor layers

### LINKED ISSUE #6460: Entering debug mode disappears text rendered in top bar and code window
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When entering debug mode project title, breadcrumbs and code disappears instantly. Code can still be selectable, so it's there but rendered transparent?

Vid fragment demonstrating the issue:

https://user-images.githubusercontent.com/108271897/234951056-a801918c-3e6f-45f5-aada-6beeaeee948c.mp4

### Expected behaviour

After entering debug mode no text disappears.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

Entire session (with logs recorded on previous than shared above attempts):

https://user-images.githubusercontent.com/108271897/234951266-70086715-1a25-4f83-8ca8-dda8de4fd429.mp4

### Enso Version

2023.4.27 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Support rendering multiple flavors of a shape system in the same layer. Fixes bugs seen as text disappearing when multiple fonts are used together (#6460 and issue discussed in #6366).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~Unit tests have been written where possible.~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/rust/ensogl/core/src/display/scene/layer.rs [hunk 1]
```diff
@@ -696,35 +688,56 @@ impl LayerModel {
...
-                    if out.is_none() {
-                        warn!("Trying to perform depth-order of non-existing element '{:?}'.", id)
-                    }
-                    out
+        let elements = self.elements.borrow();
+        let mut order_items = elements.iter().map(|&e| LayerOrderItem::from(e)).collect_vec();
+        order_items.dedup();
+        let dependency_sorted_elements = graph.into_unchecked_topo_sort(order_items);
+        let mut result = Vec::with_capacity(self.elements.borrow().len());
+        for element in dependency_sorted_elements {
```
Comment (farmaazon) [inline lib/rust/ensogl/core/src/display/scene/layer.rs]: I liked sorted_symbols more than `result`.

**Review by farmaazon — APPROVED** [review]

**Comment by farmaazon** [comment]
**QA**
For some reason, I don't see icons in Component Browser anymore.

**Comment by farmaazon** [comment]
> **QA** For some reason, I don't see icons in Component Browser anymore.

The issue was fixed after merging in develop, QA green.

Also, confirmed it fixes the problem in https://github.com/enso-org/enso/issues/5065
