### PR TITLE
Workaround crashes during regular execution

### LINKED ISSUE #7766: Node evaluation is hanging
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When selecting columns the node evaluation is hanging. Opening CB is triggering node evaluation to be completed.

### Expected behaviour

Node should be evaluated.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/1279c23a-5150-4de6-a551-cb0760b4e3a2

[enso-project-manager-2023-09-07.0.log](https://github.com/enso-org/enso/files/12549488/enso-project-manager-2023-09-07.0.log)
[New_Project_18.enso-project.zip](https://github.com/enso-org/enso/files/12549508/New_Project_18.enso-project.zip)

### Logs

_No response_

### Enso Version

Nightly 07.09.2023

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

This PR addresses two problems mentioned in #7766:
1. A random integer overflow, likely caused by a bug in Rust parser
2. A concurrent access to a methods' map

Re 1: Unable to reproduce but it doesn't mean it won't happen again. Added a try/catch to get in the logs source code that caused it **and** not crash hard when it occurs.

Re 2: Changing methods map from `HashMap` to `ConcurrentHashMap`. Due to a poor design we leaked the underlying structure in a number of places, unnecessairly. `ConcurrentHashMap` does not accept `null` keys therefore due to leaking implementation had to ensure that `methods` of `ModuleScope` never escapes as-is.

Both workarounds should ensure that we don't crash hard when they appear.

Closes #7766 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 1]
```diff
@@ -262,9 +271,15 @@ public Optional<Type> getType(String name) {
     return Optional.ofNullable(types.get(name));
   }
 
-  /** @return the raw method map held by this module */
-  public Map<Type, Map<String, Function>> getMethods() {
-    return methods;
+  /** @return a map of methods for the given type */
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: Hiding `Map<Type, ?>` is a step towards good direction.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 2]
```diff
@@ -262,9 +271,15 @@ public Optional<Type> getType(String name) {
...
+  public Map<String, Function> getMethodsForType(Type tpe) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: What it would take to hide this (mutable) `Map<String, Function>`? It is the same encapsulation problem as with `getMethods()` - jut one level down?

Alternatively `Map<String,Function` could return an _immutable map_. However whatever operation is needed to perform a modification would still be encapsulated in `ModuleScope`. Such an encapsulation would make the code more understandable.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java [hunk 3]
```diff
@@ -91,7 +91,7 @@ boolean simpleUpdate(SimpleUpdate update) {
     }
     if (collect.isEmpty()) {
       // only search for new literals when none have been found
-      updateFunctionsMap(update, methods.values(), collect);
+      updateFunctionsMap(update, methods, collect);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java:90]: This place uses `method.values()` just to obtain list of all `Function` and their `RootNode` instances. E.g. possibly `getAllMethods()` could return just `Collection<Function>`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 4]
```diff
@@ -262,9 +271,15 @@ public Optional<Type> getType(String name) {
...
+    Type tpeKey = tpe == null ? noTypeKey : tpe;
+    return methods.get(tpe);
+  }
+
+  /** @return methods mappings for all registered types */
+  public Collection<Map<String, Function>> getAllMethods() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: This is a strange return type. Simpler `Collection<Function>` would be more better, if found sufficient.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 5]
```diff
@@ -295,7 +310,7 @@ public void reset() {
   public ModuleScope withTypes(List<String> typeNames) {
     Map<String, Object> polyglotSymbols = new HashMap<>(this.polyglotSymbols);
     Map<String, Type> requestedTypes = new HashMap<>(this.types);
-    Map<Type, Map<String, Function>> methods = new HashMap<>();
+    Map<Type, Map<String, Function>> methods = new ConcurrentHashMap<>();
     Map<Type, Map<Type, Function>> conversions = new HashMap<>();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: Thru-out our code base the support for `conversion` is usually direct copy of support for methods. Whatever solution we choose for `methods`, we should do the same for `conversions`.

File: engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala [hunk 6]
```diff
@@ -244,7 +244,24 @@ class Compiler(
...
+    modules.foreach(m =>
+      try {
+        parseModule(m)
+      } catch {
+        case e: Throwable =>
+          context.log(
+            Level.SEVERE,
+            "Encountered a critical failure while parsing module {0}: {1}",
+            m.getName,
+            e.getMessage
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala]: Please don't swallow the stacktrace.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
Few suggestions & request to apply the same fix to `conversions`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java (hunk 5 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: Not entirely, `conversions` were unlikely to have a concurrent access from what I saw so I didn't feel like there is a need to change it. But we can take the same approach, sure.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java]: It's possible, I think

File: engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala (hunk 6 above)
Comment (hubertp) [reply engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala]: Yeah, unfortunately `TruffleLogger` is not particularly friendly to do that **and** provide parameters.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java [hunk 7]
```diff
@@ -279,7 +278,7 @@ long hashCodeForAtomWithCustomComparator(
 
   @TruffleBoundary
   static Function findHashMethod(Type comparator) {
-    var fn = comparator.getDefinitionScope().getMethods().get(comparator).get("hash");
+    var fn = comparator.getDefinitionScope().getMethodForType(comparator, "hash");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java:281]: Yup, this seems encapsulated enough.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java [hunk 8]
```diff
@@ -51,10 +47,10 @@ private synchronized void performUpdates(
     if (values == null) {
       var scope = module.getScope();
       values = new HashMap<>();
-      var methods = scope.getMethods();
+      var methods = scope.getAllMethods();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java:50]: Simpler.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java [hunk 9]
```diff
@@ -114,11 +110,9 @@ boolean simpleUpdate(SimpleUpdate update) {
     return true;
   }
 
-  private static void updateFunctionsMap(SimpleUpdate edit, Collection<? extends Map<?, Function>> values, Map<Node, Predicate<Expression>> nodeValues) {
-    for (Map<?, Function> map : values) {
-      for (Function f : map.values()) {
-        updateNode(edit, f.getCallTarget().getRootNode(), nodeValues);
-      }
+  private static void updateFunctionsMap(SimpleUpdate edit, List<Function> values, Map<Node, Predicate<Expression>> nodeValues) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java:113]: `List` or `Collection` ;-?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java [hunk 10]
```diff
@@ -68,6 +68,10 @@ public static Type create(
     return result;
   }
 
+  public static Type noType() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java:71]: What's this? You need a `null`-like key into `ConcurrentHashMap`! But such a key should not be publicly visible - it should be private to the usage class.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 11]
```diff
@@ -27,6 +29,12 @@ public final class ModuleScope implements EnsoObject {
   private Set<ModuleScope> imports;
   private Set<ModuleScope> exports;
 
+  private static final Type noTypeKey;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:32]: change to
```
private static final Object NO_TYPE_KEY = new Object()
```
and use `ConcurrentHashMap<Object, ...>`. Ugly Java style, I know. But when it comes to clarity of the code I prefer encapsulation over type system.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 12]
```diff
@@ -262,19 +272,54 @@ public Optional<Type> getType(String name) {
...
+  /**
+   * Returns the names of methods for the given type.
+   *
+   * @param tpe the type in the scope
+   * @return names of methods
+   */
+  public Set<String> getMethodNamesForType(Type tpe) {
+    Type tpeKey = tpe == null ? noTypeKey : tpe;
+    Map<String, Function> allTpeMethods = methods.get(tpeKey);
+    return allTpeMethods == null ? null : allTpeMethods.keySet();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:291]: `Collection.unmodifiableSet(...)` to enforce the encapsulation.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java [hunk 13]
```diff
@@ -262,19 +272,54 @@ public Optional<Type> getType(String name) {
...
+  public void registerAllMethodsOfTypeToScope(Type tpe, ModuleScope scope) {
+    Type tpeKey = tpe == null ? noTypeKey : tpe;
+    Map<String, Function> allTypeMethods = methods.get(tpeKey);
+    if (allTypeMethods != null) {
+      allTypeMethods.forEach((name, fun) -> scope.registerMethod(tpeKey, name, fun));
+    }
+  }
+
+  /** @return methods for all registered types */
+  public List<Function> getAllMethods() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java:309]: A nice trick to enforce immutability during compile time is `Collections<? extends Function>` - then the compiler refuses to call any `.add(obj)` except `.add(null)`.

**Review by JaroslavTulach — APPROVED** [review]
Few more suggestions, but good enough already.
