### PR TITLE
Fix `on` argument for Vector.sort

### LINKED ISSUE #7702: `sort on=` is broken
While working on #7697 I realized there is a strange code in [SortVectorNode.CompareFromUnresolvedSymbol](https://github.com/enso-org/enso/blob/b49cc25d3879ca5fbc4810a3dd83809680f5f086/engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java#L740). In my opinion it cannot work properly with heterogeneous vectors. Thus I decided to write a test:
```ruby
from Standard.Base import all

main =
    arr = [ 1, 1.3, "hi", Date.today, Date_Time.now, [ 0 ] ]
    sort0 = arr.map .to_text . sort
    sort1 = arr.sort on=(.to_text) . map .to_text
    sort2 = arr.sort on=(_.to_text) . map .to_text

    IO.println sort0
    IO.println sort1
    IO.println sort2
```
I assume sorting by `to_text` first and then converting `to_text` should yield the same result as converting to `to_text` first and then calling `sort`. But the results are different:
```
[1, 1.3, 2023-08-31, 2023-08-31T08:32:00.217487246+02:00[Europe/Prague], [0], hi]
[1, 1.3, hi, 2023-08-31, 2023-08-31T08:32:00.217487246+02:00[Europe/Prague], [0]]
[1, 1.3, hi, 2023-08-31, 2023-08-31T08:32:00.217487246+02:00[Europe/Prague], [0]]
```
Before the behavior gets correct, it makes little sense to work on #6361 - e.g. deliver some performance improvements.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #7702

### Pull Request Description

Fix treatment of the `on` argument of `Vector.sort`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md)
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 1]
```diff
@@ -732,22 +730,15 @@ private CompareFromUnresolvedSymbol(UnresolvedSymbol unresolvedSymbol,
 
     @Override
     boolean hasFunctionSelfArgument(Object definedOn) {
-      ensureSymbolIsResolved(definedOn);
+      var resolvedFunction = methodResolverNode.expectNonNull(definedOn, typesLibrary.getType(definedOn), unresolvedSymbol);
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:733]: We could be smarter here and cache the `resolvedFunction` based on `typesLibrary.getType(definedOn)`. But I don't think it's worth the effort, since this whole code is behind TruffleBoundary.

**Review by JaroslavTulach — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

File: test/Tests/src/Data/Vector_Spec.enso [hunk 2]
```diff
@@ -765,6 +765,12 @@ type_spec name alter = Test.group name <|
     Test.specify "should return a vector containing only unique elements up to some criteria" <|
         alter [Pair.new 1 "a", Pair.new 2 "b", Pair.new 1 "c"] . distinct (on = _.first) . should_equal [Pair.new 1 "a", Pair.new 2 "b"]
 
+    Test.specify "should be able to sort a heterogenous vector" <|
+        arr = [ 1, 1.3, "hi", Date.today, Date_Time.now, [ 0 ] ]
+        (arr.map .to_text . sort) . should_equal (arr.sort on=(.to_text) . map .to_text)
+        (arr.map .to_text . sort) . should_equal (arr.sort on=(_.to_text) . map .to_text)
+        (arr.map .to_text . sort) . should_equal (arr.sort on=(x-> x.to_text) . map .to_text)
```
Comment (radeusgd) [inline test/Tests/src/Data/Vector_Spec.enso]: nitpick on tests style:

I'd flip the order of arguments here.

It's usually `tested_feature . should_equal expected_result`.

We are testing here the `on=`, so IMO it should be on the left-hand-side.

**Review by radeusgd — APPROVED** [review]
Awesome!

File: test/Tests/src/Data/Vector_Spec.enso (hunk 2 above)
Comment (Akirathan) [reply test/Tests/src/Data/Vector_Spec.enso]: Done in 653da76f3c8c0e34793f60ce1b12225658438193

File: test/Tests/src/Data/Vector_Spec.enso [hunk 3]
```diff
@@ -765,6 +765,12 @@ type_spec name alter = Test.group name <|
     Test.specify "should return a vector containing only unique elements up to some criteria" <|
         alter [Pair.new 1 "a", Pair.new 2 "b", Pair.new 1 "c"] . distinct (on = _.first) . should_equal [Pair.new 1 "a", Pair.new 2 "b"]
 
+    Test.specify "should be able to sort a heterogenous vector" <|
+        arr = [ 1, 1.3, "hi", Date.today, Date_Time.now, [ 0 ] ]
```
Comment (JaroslavTulach) [inline test/Tests/src/Data/Vector_Spec.enso:769]: We should have used `alter` here.
