### PR TITLE
Track self argument as a dependent of application

### LINKED ISSUE #14412: Naming UDC on creation doesn't work without restarting the project
https://github.com/user-attachments/assets/505f474a-b492-4a3b-a922-27e80acbaf9a

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Self arguments are cached. This means that if the type definition or its methods change, then any method invocation on that type also needs to be invalidated.
This is now possible, as invalidating the whole application will also invalidate the self argument and ensure that types' module scope is updated.

Caching self argument probably hid more of similar caching bugs and this change should ensure that we don't see them.

Closes #14412.

### Important Notes

The change involves some (small) cost, as can be seen in the changed tests. But whatever hack we would add, it would be inevitable to some extent.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala [hunk 1]
```diff
@@ -351,6 +351,16 @@ case object DataflowAnalysis extends IRPass {
         val fnDep     = asStatic(prefix.function)
         val prefixDep = asStatic(prefix)
         info.dependents.updateAt(fnDep, Set(prefixDep))
+        prefix.arguments().headOption.map(_.value()).foreach {
+          case literalSelfArg: Name.Literal =>
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala:355]: I limited it to `Name.Literal` but the type restriction is a bit artificial. I initially felt that it would limit the scope of this change given the need for the quick fix. But other than adapting some tests in `DataflowAnalysisTest` everything else works so it is _safe_ to drop it.

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala [hunk 2]
```diff
@@ -1420,4 +1420,181 @@ class RuntimeRefactoringTest
...
+          idMap   = None
+        )
+      )
+    )
+    val afterModificationResponse =
+      context.receiveNIgnorePendingExpressionUpdates(
+        4,
+        timeoutSeconds = 10
+      )
+    afterModificationResponse should contain allOf (
```
Comment (hubertp) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala:1564]: This would previously fail with `function2` method not found failure.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala [hunk 3]
```diff
@@ -1420,4 +1420,181 @@ class RuntimeRefactoringTest
...
+          edits,
+          execute = true,
+          idMap   = None
+        )
+      )
+    )
+    val afterModificationResponse =
+      context.receiveNIgnorePendingExpressionUpdates(
+        4,
+        timeoutSeconds = 10
```
Comment (4e6) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala:1562]: I'd leave the default timeouts here and above. It can cause timeouts on CI
