### PR TITLE
Fix pattern matching on Java integer field

### LINKED ISSUE #14426: Numerical value fails to pattern match on a  polyglot symbol's field of the same value
```
> cat  foo.enso 

from Standard.Base import all
polyglot java import java.sql.Types

main =
    x = 2014
    case x of
        Types.TIMESTAMP_WITH_TIMEZONE -> 1
        _ -> 0
```

```
> enso --no-ir-caches --run foo.enso 
0
```

Discovered while investigating https://github.com/enso-org/enso/pull/14423.
Surprisingly this only happens for constants > 2000 (or so) from `java.sql.Types`.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #14426

### Pull Request Description

Fixes pattern matching on Java integer and long fields.

### Important Notes

Fallback case branch in `DuckDB_Type_Mapping.enso` no longer necessary - removed in 2a84ac477d406873fc2145b929ba9c81002a526c. See https://github.com/enso-org/enso/pull/14423#issuecomment-3606581070

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by hubertp — COMMENTED** [review]
What about `Byte`, `Short`, `Double`?

**Review by jdunkerley — APPROVED** [review]

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
- I don't think `IsSameObjectNode` is the right place to handle non-`long` integers
- values allowed to flow in Enso interpreter are
   - `long`, `double`, `boolean`, `TruffleObject`
- I am not sure what exactly is `left` or `right` in [this case](https://github.com/enso-org/enso/pull/14458/files#diff-3623dfd86f0536de4ee77ff950e0592f7ff7ea841309ad296c8362637e5bf0ffR45)
- but we certainly don't want any other values than the allowed ones

**Comment by Akirathan** [comment]
> values allowed to flow in Enso interpreter are: long, double, boolean, TruffleObject

Yes. The failure was happening when there were two `java.lang.Long`. Specialization simplified in 3bfd0bc928e10c385ed2b85d5ff558cdfca6117e

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java [hunk 1]
```diff
@@ -36,6 +36,11 @@ boolean isSameDouble(double left, double right) {
     }
   }
 
+  @Specialization
+  boolean isSameLong(long left, long right) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java:40]: This looks like the right specialization.

**Review by JaroslavTulach — APPROVED** [review]
