### PR TITLE
fix special characters in hyperlink in ag grid 

### LINKED ISSUE #11283: Vizualisation Hyperlink breaks on special characters
image

Version 2024.4.2-rc2
Build 1a0ae7c84d8d79c9b6d825c34557a5cd2ac97954
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.4.2-rc2 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### PR DESCRIPTION
**Pull request by marthasharkey**
- closes #11283 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/visualizations/TableVisualization.vue [hunk 1]
```diff
@@ -438,10 +442,7 @@ function toLinkField(fieldName: string, options: LinkFieldOptions = {}): ColDef
       params.node?.rowPinned === 'top' ?
         null
       : `Double click to view this ${tooltipValue ?? 'value'} in a separate component`,
-    cellRenderer: (params: ICellRendererParams) =>
```
Comment (marthasharkey) [inline app/gui/src/project-view/components/visualizations/TableVisualization.vue:441]: Removing this as it is no longer needed- the pinned row was the original set up of the data metrics and this has been leftover from that

File: app/gui/src/project-view/components/visualizations/TableVisualization.vue [hunk 2]
```diff
@@ -197,7 +197,11 @@ function formatText(params: ICellRendererParams) {
     .replaceAll('>', '&gt;')
 
   if (textFormatterSelected.value === 'off') {
-    return htmlEscaped.replace(/^\s+|\s+$/g, '&nbsp;')
+    const replaceLinks = htmlEscaped.replace(
+      /https?:\/\/([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+)(:[0-9]+)?(\/[-()_.!~*';/?:%@&=+$,A-Za-z0-9]*)?/,
```
Comment (kazcw) [inline app/gui/src/project-view/components/visualizations/TableVisualization.vue]: This regexp could use some test cases. `test.each` may be helpful. I would test what the RE matches rather than the expected result of inserting the `<a>` tag so that it is independent of the details of link rendering.

File: app/gui/src/project-view/components/visualizations/TableVisualization.vue [hunk 3]
```diff
@@ -219,7 +223,7 @@ function formatText(params: ICellRendererParams) {
       })
 
   const replaceLinks = replaceSpaces.replace(
-    /https?:\/\/([-()_.!~*';/?:@&=+$,A-Za-z0-9])+/g,
+    /https?:\/\/([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+)(:[0-9]+)?(\/[-()_.!~*';/?:%@&=+$,A-Za-z0-9]*)?/,
     (url: string) => `<a href="${url}" target="_blank" class="link">${url}</a>`,
   )
```
Comment (kazcw) [inline app/gui/src/project-view/components/visualizations/TableVisualization.vue]: This is complex enough to warrant extraction to a function rather than duplicating it.

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/components/visualizations/TableVisualization.vue (hunk 2 above)
Comment (kazcw) [reply app/gui/src/project-view/components/visualizations/TableVisualization.vue]: Actually, we have a `LINKABLE_URL_REGEX` that might be appropriate here
