### PR TITLE
Fix Component Browser Preview

### LINKED ISSUE #6999: Visualizations not restored after dataflow errors are resolved
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

If an edit to the graph causes dataflow errors that result in a visualization being hidden, the visualization does not come back after the errors are resolved.

### Expected behaviour

Once a visualization has been enabled for a node, the visualization should be displayed any time it is possible to do so.

### How we can reproduce it?

1. Create a graph with multiple nodes.
2. Enable the visualization on the last node.
3. Edit an input to the node, so as to cause an error. (The visualization disappears.)
4. Reverse the change made in (3), to resolve the error. (The visualization does not come back.)

### Screenshots or screencasts

[vokoscreenNG-2023-06-08_15-13-10.webm](https://github.com/enso-org/enso/assets/1047859/da227065-334b-4f89-8dc4-5b759c43a2d1)

### Logs

_No response_

### Enso Version

develop (fcc57e4)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #7006: Visualization previews are blank
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating or editing a node, a visualization preview is shown. This preview currently doesn't show any data.

### Expected behaviour

The preview should show the same visualization that would be enabled by accepting the current CB suggestion, then clicking the show-visualization-button on the node.

### How we can reproduce it?

1. Start creating a node that should have some data to show.
2. No data is visualized.

### Screenshots or screencasts

image

### Logs

_No response_

### Enso Version

recent develop (ff51347)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #7006 
Fixes #6999

Fixed several issues around visualizations:
1. The visualizations of previewed CBs are displayed. For some reason, the code which showed them wasn't there.
1. The AST ID is assigned to view ID before attaching visualization. This makes previews work in the first place.
2. The visualizations are restored after fixing an error on node.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
the `electron` version was bumped
(not sure if this was intentional though)

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 1]
```diff
@@ -115,13 +118,26 @@ impl ViewState {
     /// Indicates whether the visualization is visible in the graph editor. It is always visible
     /// when not disabled.
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: Docs no longer accurate.

**Review by kazcw — APPROVED** [review]

**Comment by MichaelMauderer** [comment]
QA: :green_circle: Passed
