### PR TITLE
Fixed node icons and colors, derived from suggestions DB groups

### LINKED ISSUE #8015: Nodes' icons and colors

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes #8015
  - Note that the (few) fallback icons are still present, as most CB entries are still missing icons. *However*, now the `iconName` from the libraries take priority over the fallback icon names.
- Also fixes a minor regression, where nodes pending execution were no longer faded out. This was introduced in #7988 because the wrong CSS variable was set.

### Important Notes
None
### Screenshot

image

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

File: app/gui2/src/components/GraphNode.vue [hunk 1]
```diff
@@ -414,12 +417,35 @@ const dragPointer = usePointer((pos, event, type) => {
...
+  const method = expressionInfo.value?.methodCall?.methodPointer
+  if (method == null) return undefined
+  const filtering = new Filtering({
+    pattern: method.name,
+    qualifiedNamePattern: method.module,
+    selfType: method.definedOnType as QualifiedName,
+    showLocal: true,
+    showUnstable: true,
+  })
+  if (filtering == null) return undefined
```
Comment (farmaazon) [inline app/gui2/src/components/GraphNode.vue]: When filtering could be null? Don't constructor always return an object?

**Review by farmaazon — APPROVED** [review]
Nice for a start, but I think we cannot afford to iterate over the entire suggestion database for every node. @MichaelMauderer we may merge it, or you may start working from this branch.

File: app/gui2/src/components/GraphNode.vue (hunk 1 above)
Comment (somebody1234) [reply app/gui2/src/components/GraphNode.vue]: nice catch, thanks. this is probably a leftover from an earlier iteration, when `method` was not yet refactored out.

**Comment by somebody1234** [comment]
review addressed (?)
basic testing indicates that the colors are still the same so... it's not broken at the very least

**Comment by somebody1234** [comment]
on a tangent: is it just me or does the node graph look a bit like Scratch now? :sweat_smile:

**Comment by somebody1234** [comment]
Thoughts on permanently keeping fallback icons based on the method name? It would probably have to be formally specified somewhere, which names fallback to which icons.

I don't think this behavior is necessarily a bad thing - for example if someone implements a custom `.set`, it's *probably* relatively unambiguous what they mean.

*Maybe* this could be discussed with the libs team

File: app/gui2/src/stores/suggestionDatabase/index.ts [hunk 2]
```diff
@@ -85,7 +86,20 @@ class Synchronizer {
 export const useSuggestionDbStore = defineStore('suggestionDatabase', () => {
   const entries = reactive(new SuggestionDb())
   const groups = ref<Group[]>([])
+  const methodPointerToEntry = reactive(new Map<string, Map<string, SuggestionEntry>>())
+
+  watchEffect(() => {
```
Comment (Frizi) [inline app/gui2/src/stores/suggestionDatabase/index.ts:92]: This watcher will be triggered on every database modification, making it really inefficient. Temporarily this is OK, since we will soon have reactive database indexing (currently being worked on by @vitvakatu). Once it's in, this code will have to be updated to make use of it. Please leave a FIXME comment to not miss it later.
```suggestion
  // FIXME: Replace this inefficient watcher with reactive index, once we have it developed.
  watchEffect(() => {
```

**Review by Frizi — APPROVED** [review]
