### PR TITLE
Multi-component color picker fix

### LINKED ISSUE #14604: Color multi-components not working

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #14604

This was broken in https://github.com/enso-org/enso/pull/13726 and the simpler fix is to set overflow: visible; on .TopBar in TobBar.vue. But that then breaks the hiding that menu when too narrow.

This solution is more complex but seems to keep both functionalities

https://github.com/user-attachments/assets/f3aede45-d2dc-4b50-b24f-38afd950d930

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/SelectionMenu.vue [hunk 1]
```diff
@@ -3,36 +3,60 @@ import ActionButton from '@/components/ActionButton.vue'
...
+  middleware: [offset(6), flip(), shift({ padding: 8 })],
+})
+
+watch(
+  () => toValue(pickColorMulti.toggled),
+  async (opened) => {
+    if (!opened) return
+    await nextTick()
+    update()
+  },
```
Comment (kazcw) [inline app/gui/src/project-view/components/SelectionMenu.vue]:
```suggestion
 (opened) => {
    if (opened) nextTick(update)
  },
```

**Review by kazcw — COMMENTED** [review]
Since this broke and we didn't catch it, maybe we should have an integration test for it

File: app/gui/src/project-view/components/SelectionMenu.vue (hunk 1 above)
Comment (AdRiley) [reply app/gui/src/project-view/components/SelectionMenu.vue]: Done

**Review by kazcw — APPROVED** [review]
