### PR TITLE
HashMapNode supports atoms with custom comparators

### LINKED ISSUE #7161: Problem with Map and a custom comparator
When we use the Enso Map with a custom comparator it appears to fail after a period of time (maybe when inlined?).

The below code should produce 5 entries in both distinct function.

```
from Standard.Base import all

type My_Key
    Value hash_code:Integer value:Text idx:Integer

    to_text self = "My_Key(" + self.values.to_text + ")"

## PRIVATE
type My_Key_Comparator
    ## PRIVATE
    compare x y =
        if x.hash_code != y.hash_code then Nothing else
            if x.value == y.value then Ordering.Equal else Nothing

    ## PRIVATE
    hash x = x.hash_code

Comparable.from (_:My_Key) = My_Key_Comparator

main =
    keys = 0.up_to 5000 . map ix->
        value = ["A","B","C","D","E"].at (ix % 5)
        hash_code = Comparable.from value . hash value
        My_Key.Value hash_code value ix
    IO.println keys.distinct.length
    IO.println (keys.map _.value . distinct . length)
```

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #7161.

### Pull Request Description

Add proper handling for atoms with custom comparators into the hashing machinery.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [X] Unit tests have been written where possible.
  - [X] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java:1]: The specializations for `Atom` follow the same pattern as in `EqualsAtomNode`. This adds handling for atoms with custom comparators. In the future, we might think about splitting this node into multiple ones in the same way as we did for `EqualsNode`. However, since the performance benefit was negligible, we shall skip it for now.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java [hunk 1]
```diff
@@ -165,14 +165,15 @@ Type getMetaObject(@CachedLibrary("this") InteropLibrary thisLib) {
...
+  Object toDisplayString(
+      boolean allowSideEffects, @CachedLibrary(limit = "5") InteropLibrary interop) {
     var sb = new StringBuilder();
     sb.append("{");
     boolean empty = true;
     for (StorageEntry entry : mapBuilder.getStorage().getValues()) {
       if (isEntryInThisMap(entry)) {
         empty = false;
-        sb.append(entry.key()).append("=").append(entry.value()).append(", ");
+        sb.append(entryToString(entry, interop)).append(", ");
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:176]: This ensures that calling `map.to_text` will invoke `to_text` methods on keys and values, if necessary.

**Review by jdunkerley — APPROVED** [review]
Thank you for solving this so quickly :)

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java [hunk 2]
```diff
@@ -81,7 +81,7 @@ boolean equalsAtoms(
         "cachedComparator != null",
       },
       limit = "10")
-  boolean equalsAtoms(
+  boolean equalsAtomsWithCustomComparator(
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java:84]: Does this rename has any functional meaning (e.g. have I made a mistake when introducing the `EqualsAtomNode`?) or is it just stylistic? I hope the latter...

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java [hunk 3]
```diff
@@ -165,14 +165,15 @@ Type getMetaObject(@CachedLibrary("this") InteropLibrary thisLib) {
 
   @ExportMessage
   @TruffleBoundary
-  Object toDisplayString(boolean allowSideEffects) {
+  Object toDisplayString(
+      boolean allowSideEffects, @CachedLibrary(limit = "5") InteropLibrary interop) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:169]: Don't use `@CachedLibrary` for `@TruffleBoundary` message - use `InteropLibrary.getUncached()`.

**Review by JaroslavTulach — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java:84]: This is just a stylistic issue. I thought that having `equalsAtomsWithCustomComparator`  and `equalsAtomWithDefaultComparator` specializations is better than two specializations with the same name `equalsAtoms` that have different guards.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:169]: Good point. Specializations behind `@TruffleBoundary` initialize all the `@Cached` and `@CachedLibrary` annotated parameters with their uncached variants anyway.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:169]: > Specializations behind @TruffleBoundary initialize all the @Cached and @CachedLibrary annotated parameters with their uncached variants anyway.

I don't think they do. Looking at `EnsoHashMapGen.java` I see:
```java
            private Object toDisplayStringNode_AndSpecialize(EnsoHashMap arg0Value, boolean arg1Value) {
                Lock lock = getLock();
                boolean hasLock = true;
                lock.lock();
                try {
                    int state_0 = this.state_0_;
                    this.toDisplayStringNode__toDisplayString_interop_ = super.insert((INTEROP_LIBRARY_.createDispatched(5)));
                    this.state_0_ = state_0 = state_0 | 0b10 /* add-state_0 toDisplayString(EnsoHashMap, boolean, InteropLibrary) */;
                    lock.unlock();
                    hasLock = false;
                    return arg0Value.toDisplayString(arg1Value, this.toDisplayStringNode__toDisplayString_interop_);
```
which seems to call `createDispatched`.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:169]: Please remove the `InteropLibrary interop` parameter from the `toDisplayString` method. Instead use `var interop = InteropLibrary.getUncached()` inside of the method.

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java:169]: Done in my upcomming PR - cba65de7c8d70a73126f6bc0126a8c9b7d7d33b8
