### PR TITLE
Syntax error shall contain location of the error

### LINKED ISSUE #8735: CompilerError isn't syntax error (required by Truffle TCK)
Work on #8685 had to disable one TCK test by ca08bf82c20cbf49765f87145bbeb55121c2c96a commit. Enable it as
```diff
diff --git engine/runtime/src/test/java/org/enso/interpreter/test/tck/EnsoTckInvalidSyntaxTest.java
new file mode 100644
index 0000000000..ca5ab05ccb
--- /dev/null
+++ engine/runtime/src/test/java/org/enso/interpreter/test/tck/EnsoTckInvalidSyntaxTest.java
@@ -0,0 +1,9 @@
+package org.enso.interpreter.test.tck;
+
+import org.graalvm.polyglot.Source;
+
+public class EnsoTckInvalidSyntaxTest extends com.oracle.truffle.tck.tests.InvalidSyntaxTest {
+  public EnsoTckInvalidSyntaxTest(String n, Source s) {
+    super(n, s);
+  }
+}
```
This test is failing for two reasons. First of all the TCK expects that `Context.eval` produces _syntax errors_ immediatelly- that's not Enso case right now. Second, once the errors are produced the TCK complains that [CompilerError](https://github.com/enso-org/enso/blob/fc0361f50231220b4c645f6ffe3888ba6d0b2b86/engine/runtime-parser/src/main/java/org/enso/compiler/core/CompilerError.java#L3) isn't _syntax error_. To fix that compiler error must subclass [AbstractTruffleException](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/exception/AbstractTruffleException.html).

- #8210

On the other hand there is issue #8210 - it doesn't want `runtime-compiler` to depend on Truffle. E.g. we cannot just change `CompilerError` to extend `AbstractTruffleException`.

The **solution** is based on _yet another level of abstraction_: Introduce `RuntimeException CompilerContext.createCompilerError(Module src, String msg, Location where)` method to be implemented by [TruffleCompilerContext](https://github.com/enso-org/enso/blob/fc0361f50231220b4c645f6ffe3888ba6d0b2b86/engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java#L33) and create proper Truffle exception with all properties requested by the TCK.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #8735 by making sure compilation errors contain `SourceSection` identifying location where they occurred. This behavior is required by Truffle TCK. The TCK allocates its own `Context` without any other configuration and still requires a syntax error to be reported. Thus changing the default mode to _strict errors_.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala [hunk 1]
```diff
@@ -85,6 +86,7 @@ class EvalTest extends InterpreterTest {
       val code =
         """import Standard.Base.Runtime.Debug
           |import Standard.Base.Any.Any
+          |import Standard.Base.Data.Numbers
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala:89]: How is this import related to this PR?

File: engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java [hunk 2]
```diff
@@ -62,6 +62,9 @@ public Object execute(VirtualFrame frame) {
         module = new Module(name, null, sourceCode.getCharacters().toString());
       }
       ctx.getPackageRepository().registerModuleCreatedInRuntime(module.asCompilerModule());
+      if (ctx.isStrictErrors()) {
+        module.compileScope(ctx);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java:66]: Truffle TCK would like us to throw the _syntax error_ from `ctx.eval` as a result of that we seem to have [these test failures](https://github.com/enso-org/enso/actions/runs/8965563388/job/24619295460?pr=9864#step:7:4822):
```
org.enso.interpreter.test.SignatureTest
org.enso.interpreter.test.EqualsTest
org.enso.interpreter.test.HashCodeTest
org.enso.interpreter.test.tck.EnsoTckInvalidSyntaxTest
org.enso.interpreter.runtime.ModuleTest
org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeTest
org.enso.interpreter.test.DiagnosticFormatterTest
org.enso.interpreter.test.IntegerTest
org.enso.interpreter.test.AtomConstructorTest
org.enso.interpreter.test.FindExceptionMessageTest
org.enso.interpreter.test.BinaryOpIntegerTest
org.enso.compiler.ExecStrictCompilerTest
org.enso.interpreter.test.BinaryOpFloatTest
```
those tests will need to be adjusted to the fact that `CompilationAbortedException` is thrown sooner than it used to be.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java:66]: Addressed by 0effcd7, 7ccab76 and 747fd5c

File: engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java [hunk 3]
```diff
@@ -16,7 +16,7 @@ public class RuntimeOptions {
       OptionDescriptor.newBuilder(PROJECT_ROOT_KEY, PROJECT_ROOT).build();
 
   public static final String STRICT_ERRORS = optionName("strictErrors");
-  public static final OptionKey<Boolean> STRICT_ERRORS_KEY = new OptionKey<>(false);
+  public static final OptionKey<Boolean> STRICT_ERRORS_KEY = new OptionKey<>(true);
```
Comment (JaroslavTulach) [inline engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java:19]: With the most recent change 747fd5c it is possible to run `sbt runtime-integration-tests/test` with `false` as well as `true` default value of `STRICT_ERRORS_KEY` - e.g. all our tests override the default or don't care - except the single test from the Truffle TCK:
```
[error] Test org.enso.interpreter.test.tck.EnsoTckInvalidSyntaxTest.testInvalidSyntax
  [enso::unknown_x.enso] failed: java.lang.AssertionError: Expected exception.
[error]     at com.oracle.truffle.tck.tests.InvalidSyntaxTest.testInvalidSyntax(:116)
```
which uses the default - as the `org.graalvm.polyglot.Context` isn't created by us, but rather by the TCK itself and doesn't specify value of `STRICT_ERRORS_KEY`.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java [hunk 4]
```diff
@@ -71,7 +71,7 @@ protected static EnsoContext leakContext(Context ctx) {
    */
   protected static Value executeInContext(Context ctx, Callable<Object> callable) {
     // Force initialization of the context
-    ctx.eval("enso", "42");
+    ctx.eval("enso", "value = 0");
```
Comment (radeusgd) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: I'm curious - why is the code here changed?

**Review by radeusgd — APPROVED** [review]
Good to see more detailed tests of the errors reported by the compiler 😀

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: Because `42` is not a valid Enso code.

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala:89]: Without this import the symbols `+` & co. ware not available. This is the error:
```
[info]   - should return a value usable in the caller scope *** FAILED *** (27 milliseconds)
[info]     org.enso.interpreter.test.InterpreterException: No_Such_Method.Error
[info]     at <enso>.<eval>(Unknown)
[info]     at <enso>.Debug.eval(Unknown)
[info]     at <enso>.Test.main(Test:7)
[info]     at org.graalvm.polyglot/org.graalvm.polyglot.Value.execute(Value.java:928)
[info]     at org.enso.polyglot.Function.execute(Function.scala:20)
[info]     at org.enso.runtime/org.enso.interpreter.test.InterpreterRunner.$anonfun$eval$1(InterpreterTest.scala:200)
[info]     at org.enso.runtime/org.enso.interpreter.test.InterpreterException$.rethrowPolyglot(InterpreterException.scala:25)
[info]     at org.enso.runtime/org.enso.interpreter.test.InterpreterRunner.eval(InterpreterTest.scala:198)
[info]     at org.enso.runtime/org.enso.interpreter.test.InterpreterRunner.eval$(InterpreterTest.scala:195)
[info]     at org.enso.runtime/org.enso.interpreter.test.semantic.EvalTest.eval(EvalTest.scala:5)
```

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala [hunk 5]
```diff
@@ -816,8 +816,8 @@ class Compiler(
       .diagnostics
     val module    = inlineContext.getModule()
     val hasErrors = reportDiagnostics(errors, module)
-    if (hasErrors && inlineContext.compilerConfig.isStrictErrors) {
-      throw context.throwAbortedException()
+    if (hasErrors.nonEmpty && inlineContext.compilerConfig.isStrictErrors) {
+      throw hasErrors.head
     }
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala]:
```suggestion
    hasErrors match {
        case error :: _ if inlineContext.compilerConfig.isStrictErrors =>
            throw error
        case _ =>
    }
```
would be more Scala'ish to write it

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala [hunk 6]
```diff
@@ -953,14 +949,21 @@ class Compiler(
...
+        val formattedDiag =
+          context.formatDiagnostic(compilerModule, diag, isOutputRedirected)
+        printDiagnostic(formattedDiag.getMessage)
+        if (diag.isInstanceOf[Error]) {
+          formattedDiag
+        } else {
+          null
+        }
+      }
+      .filter(_ != null)
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala]: `flatMap` on `Option` would be more Scala'ish

**Review by hubertp — APPROVED** [review]

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala (hunk 1 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala:89]: I see. So previously, every Scala test that extended [InterpreterTest.scala](https://github.com/enso-org/enso/pull/9864/files/da3a3660ea7c3175818d304c12d58216e8aa1f41#diff-32c8ed154d7f32b9dd7e20543f2493a97e07c46a18eac33681cb1c392e78b83e) created a Context with `STRICT_ERRORS` set to false (the default setting). That seems wrong. Good thing that you have set `STRICT_ERRORS` to be true by default.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: It would even be better to replace this line with:
```java
ctx.initialize(LanguageInfo.ID);
```

Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: How is `42` not a valid Enso code by the way, and how were you able to find out?

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: There were [failing tests](https://github.com/enso-org/enso/pull/9864#discussion_r1590766402) claiming [42 is unexpected expression](https://github.com/enso-org/enso/actions/runs/8965563388/job/24619295460?pr=9864#step:7:4775).

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java [hunk 7]
```diff
@@ -55,17 +55,20 @@ public static void closeEnsoContext() throws Exception {
...
-    var module = ctx.eval("enso", """
-    type My_Type
-        Value a b c a
-    """);
     try {
+      var module = ctx.eval("enso", """
+      type My_Type
+          Value a b c a
+      """);
       var run = module.invokeMember("eval_expression", "My_Type.Value");
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: Is this line even reachable? Shouldn't it be deleted and replaced by the `fail("Expecting no returned value: " + run);` line? I though that the compilation exception should be thrown from `ctx.eval` now, and now from `module.invokeMember("eval_expression")`?

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java [hunk 8]
```diff
@@ -89,14 +92,14 @@ public void testUnknownConstructorLocation() throws Exception {
                 """,
                 "wrong_cons.enso")
             .build();
-    var module = ctx.eval(code);
     try {
+      var module = ctx.eval(code);
       var run = module.invokeMember("eval_expression", "foo 10");
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: Remove this line? See [my other comment](https://github.com/enso-org/enso/pull/9864/files#r1592020735).

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java [hunk 9]
```diff
@@ -106,4 +109,15 @@ public void testUnknownConstructorLocation() throws Exception {
       assertNotEquals("Location defined " + errors, -1, errors.indexOf("wrong_cons:2:5"));
     }
   }
+
+  static void assertContains(String expected, String actual) {
```
Comment (Akirathan) [inline engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: I can see that you are still fighting hard against adopting hamcrest's simpler `assertThat(text, containsString("...")` or even better pattern for checking multiple substring:
```java
assertThat(someText, allOf(
  containsString("some text"),
  containsString("some other substring")
));
```

Not forcing you to adopt it. Just putting a note that with hamcrest, you don't need to define this `assertContains` method yourself, and you even have better error messages.

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java:74]: Could you please try to replace it with `ctx.initialize(LanguageInfo.ID);`?

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java (hunk 9 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: Done 19f11b3495

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java (hunk 8 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: 5b7038f01a

File: engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java (hunk 7 above)
Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java]: 5b7038f01a

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala]: Yes, it is nicer: cda1a598e9 (if it does the same).
