### PR TITLE
Adjust generateCheckedArgumentRead to return correct expected type

### LINKED ISSUE #5690: Type error causes NullPointerException
I'm getting `Execution of function main failed (class java.lang.NullPointerException).` when I execute a program like the following:
```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.Table.Data.Table import Table
import Standard.Visualization

main =
    operator1 = (((Data.read "/home/ubuntu/BookClub Week3.csv").get 4).at 1)
    operator2 = Date.parse operator1
```

`operator1` reads a CSV, and obtains a `Date` object from it. `operator2` tries to parse the `Date` object, which should be an error(?); however, execution fails. The problem is particular to the kind of `Date` created by `Data.read`--if I do the same thing with `Date.new` instead of reading a CSV, the exception does not occur.

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

Correctly get the expected type and return an IllegalArgument if no Enso type.

image

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java [hunk 1]
```diff
@@ -496,9 +501,7 @@ protected void storeMetadata(Writer writer, Map<String, MethodMetadataEntry> pas
     for (Filer f : builtinMethods.keySet()) {
       for (Map.Entry<String, String[]> entry : builtinMethods.get(f).entrySet()) {
         writer.append(entry.getKey() + ":" + String.join(":", Arrays.asList(entry.getValue())) + "\n");
-        if (pastEntries.containsKey(entry.getKey())) {
-          pastEntries.remove(entry.getKey());
-        }
+        pastEntries.remove(entry.getKey());
```
Comment (hubertp) [inline lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java]: That doesn't seem right. The condition prevents double entries

File: lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/TypeProcessor.java [hunk 2]
```diff
@@ -101,21 +107,25 @@ protected void storeMetadata(Writer writer, Map<String, TypeMetadataEntry> pastE
                 + ":"
                 + constr.getFullName()
                 + "\n");
-        if (pastEntries.containsKey(entry.getKey())) {
-          pastEntries.remove(entry.getKey());
-        }
+        pastEntries.remove(entry.getKey());
```
Comment (hubertp) [inline lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/TypeProcessor.java]: same as before, this doesn't seem right

**Review by hubertp — COMMENTED** [review]
I think those 2 checks should be brought back or incremental compilation will be broken

**Review by hubertp — APPROVED** [review]
LGTM. Fixes some non-obvious separate compilation issues.
