### PR TITLE
Attempt to fix space in path hyper issue

### LINKED ISSUE #13933: Hyper read/write broken on MacOS if the application is renamed to a name with a space
If I have renamed Enso application with a space then hyper read/write does not work

Image

Image

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #13933 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by GregoryTravis — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

File: std-bits/tableau/src/main/java/org/enso/tableau/HyperFormat.java [hunk 1]
```diff
@@ -132,7 +132,9 @@ private static HyperProcess getProcess() throws IOException {
         LOGGER.log(Level.INFO, "Starting Hyper process: {0}.", HYPER_PATH);
         try {
           if (jnaPath != null) {
-            System.setProperty("jna.boot.library.path", new File(jnaPath.getFile()).getParent());
+            // Use URI to correctly handle spaces and other encoded characters.
+            System.setProperty(
+                "jna.boot.library.path", Path.of(jnaPath.toURI()).getParent().toString());
```
Comment (JaroslavTulach) [inline std-bits/tableau/src/main/java/org/enso/tableau/HyperFormat.java:137]: - That's a [correct fix](https://github.com/enso-org/enso/issues/13933#issuecomment-3257368990) 
- Surprise, surprise.
