### PR TITLE
Inline doc comment is a compiler error

### LINKED ISSUE #11276: A simple inline comment crashes compiler with NPE
```
main args =
    v = 42 ## meh
    v
```
will blow up:
```
> ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run simple-crash.enso

[ERROR] [enso.org.enso.compiler.Compiler] Encountered a critical failure while parsing module
java.lang.NullPointerException: Cannot invoke "org.enso.compiler.core.ir.Expression.transformExpressions(scala.PartialFunction)" because "x$1" is null
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.$anonfun$transformExpressions$1(Expression.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.CallArgument$Specified.mapExpressions(CallArgument.scala:124)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.CallArgument$Specified.mapExpressions(CallArgument.scala:43)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.expression.Application$Prefix.$anonfun$mapExpressions$1(Application.scala:144)
	at scala.library@2.13.11/scala.collection.immutable.List.map(List.scala:246)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.expression.Application$Prefix.mapExpressions(Application.scala:144)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.expression.Application$Prefix.mapExpressions(Application.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions(Expression.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions$(Expression.scala:18)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.expression.Application$Prefix.transformExpressions(Application.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.$anonfun$transformExpressions$1(Expression.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression$Binding.mapExpressions(Expression.scala:280)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression$Binding.mapExpressions(Expression.scala:192)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions(Expression.scala:24)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions$(Expression.scala:18)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression$Binding.transformExpressions(Expression.scala:192)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:83)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.$anonfun$applyOrElse$1(DocumentationComments.scala:86)
	at scala.library@2.13.11/scala.collection.immutable.List.map(List.scala:246)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:86)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:83)
	at scala.library@2.13.11/scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions(Expression.scala:22)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression.transformExpressions$(Expression.scala:18)
	at org.enso.runtime.parser/org.enso.compiler.core.ir.Expression$Block.transformExpressions(Expression.scala:57)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:83)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$.resolveDefinition(DocumentationComments.scala:167)
	at org.enso.runtime.compiler/org.enso.compiler.pass.resolve.DocumentationComments$.$anonfun$resolveModule$5(DocumentationComments.scala:211)
	at scala.library@2.13.11/scala.collection.immutable.List.map(List.scala:246)
...
```

### PR DESCRIPTION
**Pull request by Akirathan**
### Pull Request Description

Fix NPE thrown when compiling source with inline documentation comments, like
```
main args =
    v = 42 ## meh
    v
```

### Important Notes

- Handled by the rust parser as syntax error
- When translating the input from the rust parser, we treat it as an unexpected expression - added tests.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by kazcw** [comment]
This should be a syntax error, so I added some parser changes.

**Review by Frizi — APPROVED** [review]
approving the JS test change

**Review by hubertp — APPROVED** [review]

File: lib/rust/parser/src/syntax/treebuilding/compound_token.rs [hunk 1]
```diff
@@ -89,6 +92,7 @@ impl<'s, Inner: TreeConsumer<'s>> CompoundTokens<'s, Inner> {
         if let Some(tree) = self.compounding.take().and_then(|builder| builder.flush()) {
             self.inner.push_tree(tree);
         }
+        self.has_preceding_item = default();
```
Comment (farmaazon) [inline lib/rust/parser/src/syntax/treebuilding/compound_token.rs:95]: Personally, I'd prefer `false`, as more "readable"

File: lib/rust/parser/src/syntax/treebuilding/compound_token.rs [hunk 2]
```diff
@@ -260,18 +277,21 @@ impl<'s> CompoundTokenBuilder<'s> for TextLiteralBuilder<'s> {
     }
 
     fn flush(self) -> Option<Tree<'s>> {
-        let Self { open, newline, elements } = self;
+        let Self { open, newline, elements, has_preceding_item: _ } = self;
```
Comment (farmaazon) [inline lib/rust/parser/src/syntax/treebuilding/compound_token.rs:280]: A shorter form would be 
```suggestion
        let Self { open, newline, elements, .. } = self;
```
Unless you really want to have an error here when another field will be added.

**Review by farmaazon — APPROVED** [review]
Reviewed the rust part. Nitpicks only, quite optional

**Review by JaroslavTulach — APPROVED** [review]
Test written and CI is green. Good!

File: lib/rust/parser/src/syntax/treebuilding/compound_token.rs (hunk 1 above)
Comment (kazcw) [reply lib/rust/parser/src/syntax/treebuilding/compound_token.rs:95]: `false` would be simpler, but IMO it's more important here to express that the field is reset to its initial state than to emphasize the value of that state. I'd reinitialize the whole struct here, if it weren't for performance.

File: lib/rust/parser/src/syntax/treebuilding/compound_token.rs (hunk 2 above)
Comment (kazcw) [reply lib/rust/parser/src/syntax/treebuilding/compound_token.rs:280]: Fields that can correctly be ignored here are the exception.
