### PR TITLE
Ensure correct BouncyCastle initialization for NI

### LINKED ISSUE #12813: bouncycastle issues when generating keypairs in Native Image
```
[FAILED] [Snowflake] Key-pair authentication: [0/2, 4437ms]           

    - [FAILED] using local private key [4141ms]
        Reason: An unexpected error was returned: (Illegal_State.Error 'The provided private key file is not supported by the Snowflake driver. We recommend generating the key using `generate_key_pair` method and storing it as a Secret in Enso Cloud. The original error was: Private key provided is invalid or not supported: /tmp/snowflake-key1824189743119320818.p8: java.security.InvalidKeyException: Unable to decode key' There was an SQL error: Private key provided is invalid or not supported: /tmp/snowflake-key1824189743119320818.p8: java.security.InvalidKeyException: Unable to decode key.)
        at <enso> Snowflake_Details._enhance_connection_errors.result<arg-1>(...enso/distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso:105:13-271)


    - [FAILED] using local private key encrypted with passphrase [295ms]
        Reason: An unexpected panic was thrown: com.oracle.svm.core.jdk.UnsupportedFeatureError: Trying to verify a provider that was not registered at build time: BC version 1.78.1. All providers must be registered and verified in the Native Image builder. 
        at <Unknown Location> related to com.oracle.truffle.host.HostObject.doInvoke
        at <enso> Auth_Spec.generate_local_key_pair(...enso/test/Snowflake_Tests/src/Auth_Spec.enso:30:5-97)
        at <enso> Auth_Spec.add_specs.Auth_Spec.add_specs<arg-1>(...enso/test/Snowflake_Tests/src/Auth_Spec.enso:53:24-68)
        at <enso> case_branch.case <internal-147>(...enso/distribution/lib/Standard/Test/0.0.0-dev/src/Group.enso:30:61-64)
        at <enso> Helpers.execute_spec_code<arg-1>(...enso/distribution/lib/Standard/Test/0.0.0-dev/src/Helpers.enso:56:18-34)
```

Potentially regressed when we switched Native Image on and/or started using thin client in https://github.com/enso-org/enso/pull/12743

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

BouncyCastle hardly works out-of-the-box in NI. Instead one has to make sure that it is initialized at build time, with an exception of some classes that need to be done during runtime.
This change fixes key generation issues in `Auth_Spec`.

Cleaned up warnings related to wrong entries in nested enums:
```
...
[info] Warning: Could not register complete reflection metadata for org.openxmlformats.schemas.spreadsheetml.x2006.main.STSortMethod$Enum. Reason(s): java.lang.NoClassDefFoundError: org/openxmlformats/schemas/spreadsheetml/x2006/main/STSortMethod.
[info] Warning: Could not register complete reflection metadata for org.openxmlformats.schemas.spreadsheetml.x2006.main.STTableType$Enum. Reason(s): java.lang.NoClassDefFoundError: org/openxmlformats/schemas/spreadsheetml/x2006/main/STTableType.
...
```

Follow up  to #12804.  Closes #12813. 

### Important Notes

Snowflake's and other tests appear to be fixed.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package org.enso.snowflake;
+
+import java.security.Security;
+import org.bouncycastle.jce.provider.BouncyCastleProvider;
+
+public class BouncyCastleInitializer {
+  static {
+    System.out.println("TEST KEY GENERATOR IS RUN AT BUILD TIME!");
```
Comment (radeusgd) [inline std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java]: Should this print statement be kept?

Comment (hubertp) [reply std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java]: No, of course not :p

File: test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java [hunk 2]
```diff
@@ -19,6 +19,13 @@
 import org.bouncycastle.operator.OutputEncryptor;
 
 public class TestKeyGenerator {
+
+  static {
+    if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
+      Security.addProvider(new BouncyCastleProvider());
+    }
+  }
```
Comment (radeusgd) [inline test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java:27]: Ideally the `TestKeyGenerator` at some point would not be shipped with the production release as it is only needed for testing.

However I guess this bit may actually be worth keeping - as perhaps it initializes the cryptographic components that are then needed by Snowflake to be able to accept private keys.

If it is indeed needed to load private keys (would need to test by removing it and running the GUI trying to use some manually created key), then it could be worth to move this bit into `std-snowflake`.

**Review by radeusgd — APPROVED** [review]

File: test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java (hunk 2 above)
Comment (hubertp) [reply test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java:27]: It is not being shipped with the release. It is only included when building NI for testing i.e., `ENSO_LAUNCHER=native,test`. Similarly with base tests' helper jar. I changed that in #12804.

Native Image will do this initialization at build time. This change is only added so that things work if you are running in JVM mode.

Comment (radeusgd) [reply test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java:27]: Oh great to know.

File: std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package org.enso.snowflake;
+
+import java.security.Security;
+import org.bouncycastle.jce.provider.BouncyCastleProvider;
+
+public class BouncyCastleInitializer {
```
Comment (JaroslavTulach) [inline std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java]:
```suggestion
public final class BouncyCastleInitializer {
  private BouncyCastleInitializer() {}
```

**Review by JaroslavTulach — APPROVED** [review]
If it improves something, then let it improve it.

**Review by jdunkerley — APPROVED** [review]
