### PR TITLE
Retry `Future.get()` when `InterruptedException` appears

### LINKED ISSUE #14324: Internal Ydoc error blocks further edits
Not really possible to reproduce consistently but the scenario was that I was removing a bunch of nodes and at one point got:

Image

From the on the project was unusable and always returning an error.
Noticed the corresponding stacktrace in the logs:
```
[WARN] [2025-11-19T00:01:36.253] [io.helidon.webserver.http1.Http1Connection] Internal server error
io.helidon.http.RequestException: Internal error
        at io.helidon.http@4.2.2/io.helidon.http.RequestException$Builder.build(RequestException.java:139)
        at io.helidon.webserver@4.2.2/io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:249)
        at io.helidon.webserver@4.2.2/io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:175)
        at io.helidon.common.task@4.2.2/io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
        at io.helidon.webserver@4.2.2/io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
        at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.WebSocket.lambda$execute$0(WebSocket.java:152)
        at io.helidon.webserver.websocket@4.2.2/io.helidon.webserver.websocket.WsRoute.listener(WsRoute.java:56)
        at io.helidon.webserver.websocket@4.2.2/io.helidon.webserver.websocket.WsUpgrader.upgrade(WsUpgrader.java:171)
        at io.helidon.webserver@4.2.2/io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:193)
        ... 4 common frames omitted
Caused by: java.lang.InterruptedException: null
        at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:482)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.WebSocket.lambda$execute$0(WebSocket.java:149)
        ... 7 common frames omitted
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- Fixes #14324 by differentiating between `InterruptedException` and `ExecutionException`
- when interrupted, just ask again for the `Future.get()`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketConnectionInterruptedTest.java [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+import org.graalvm.polyglot.HostAccess;
+import org.graalvm.polyglot.Value;
+import org.junit.Test;
+
+public class WebSocketConnectionInterruptedTest {
+
+  @Test
+  public void interruptThreadBeforeExecution() throws Exception {
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketConnectionInterruptedTest.java:30]: - Running this test without 52b8c4c136a92383306e206cddc1f930c29d3649 fix yields following error:
```
java.lang.InterruptedException: null
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:430)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2094)
        at org.enso.ydoc.polyfill.web.WebSocket.lambda$execute$0(WebSocket.java:149)
        at io.helidon.webserver.websocket.WsRoute.listener(WsRoute.java:56)
        at io.helidon.webserver.websocket.WsUpgrader.upgrade(WsUpgrader.java:171)
        at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:193)
        at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:175)
        at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
        at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)
lis 25, 2025 5:22:55 ODP. io.helidon.webserver.http1.Http1Connection handleRequestException
WARNING: Internal server errortestOnly 0s
io.helidon.http.RequestException: Internal error
        at io.helidon.http.RequestException$Builder.build(RequestException.java:139)
        at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:249)
        at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:175)
        at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
        at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
        at org.enso.ydoc.polyfill.web.WebSocket.lambda$execute$0(WebSocket.java:152)
        at io.helidon.webserver.websocket.WsRoute.listener(WsRoute.java:56)
        at io.helidon.webserver.websocket.WsUpgrader.upgrade(WsUpgrader.java:171)
        at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:193)
        ... 4 more
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:430)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2094)
        at org.enso.ydoc.polyfill.web.WebSocket.lambda$execute$0(WebSocket.java:149)
        ... 7 more
```
- such an error looks quite similar to #14324
- that makes me believe this change is a fix of the problem

File: lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebSocket.java [hunk 2]
```diff
@@ -142,17 +142,24 @@ yield new WebSocketConnection(
...
+                        WebSocketConnection connection;
+                        try {
+                          log.trace("Waiting for connection");
+                          connection = connectionFuture.get();
+                        } catch (InterruptedException e) {
+                          log.debug("Interrupted", e);
+                          continue;
+                        } catch (ExecutionException e) {
+                          log.error("Connection error", e);
+                          throw new RuntimeException(e);
```
Comment (4e6) [inline lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebSocket.java:159]: How can an `InterruptException` even occur in the ydoc thread? Shouldn't then all the websocket logic be fenced like that?

**Review by 4e6 — APPROVED** [review]
It's good enough IMO

File: lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebSocket.java (hunk 2 above)
Comment (JaroslavTulach) [reply lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebSocket.java:159]: - The test simulates the problem by explicitly calling `Thread.currentThread().interrupt()` in `submit`
- how exactly this happens in the reality I am not sure

**Comment by hubertp** [comment]
We are [seeing](https://github.com/enso-org/enso/actions/runs/19982252991/job/57311406075#step:14:1886) some spurious errors related to this one
```
 INFO ide_ci::program::command: sbt ℹ️ [error] Test org.enso.ydoc.polyfill.web.WebSocketConnectionInterruptedTest.interruptThreadBeforeExecution failed: java.io.UncheckedIOException: java.net.ConnectException: Connection refused, took 0.189 sec
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.api.Proxy$ProxyType$2.connect(Proxy.java:547)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.api.Proxy.tcpSocket(Proxy.java:283)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.api.TcpClientConnection.connect(TcpClientConnection.java:115)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1ConnectionCache.keepAliveConnection(Http1ConnectionCache.java:149)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1ConnectionCache.connection(Http1ConnectionCache.java:77)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1CallChainBase.obtainConnection(Http1CallChainBase.java:296)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1CallChainBase.proceed(Http1CallChainBase.java:137)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:429)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeWithServices(Http1ClientRequestImpl.java:225)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeRequestWithEntity(Http1ClientRequestImpl.java:215)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:49)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:40)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.http1.Http1ClientRequestImpl.upgrade(Http1ClientRequestImpl.java:150)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.websocket.WsClientImpl.connect(WsClientImpl.java:122)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.websocket.WsClientImpl.connect(WsClientImpl.java:163)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.ydoc.polyfill.web.WebSocketConnectionInterruptedTest.interruptThreadBeforeExecution(WebSocketConnectionInterruptedTest.java:54)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at java.lang.reflect.Method.invoke(Method.java:565)
 INFO ide_ci::program::command: sbt ℹ️ [error]     ...
 INFO ide_ci::program::command: sbt ℹ️ [error] Caused by: java.net.ConnectException: Connection refused
 INFO ide_ci::program::command: sbt ℹ️ [error]     at sun.nio.ch.Net.pollConnect(Native Method)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at sun.nio.ch.Net.pollConnectNow(Net.java:639)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:543)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at java.net.Socket.connect(Socket.java:659)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at io.helidon.webclient.api.Proxy$ProxyType$2.connect(Proxy.java:544)
 INFO ide_ci::program::command: sbt ℹ️ [error]     ... 50 more
 INFO ide_ci::program::command: sbt ℹ️ [info] Test run org.enso.ydoc.polyfill.web.WebSocketConnectionInterruptedTest finished: 1 failed, 0 ignored, 1 total, 0.196s
 ```

**Comment by 4e6** [comment]
I think the problem is that `wss.start()` https://github.com/enso-org/enso/blob/f4581d53e9cd45b68eb1988874b25d2a99d6371c/lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketConnectionInterruptedTest.java#L34-L43
does not wait until the server is started, and then 
https://github.com/enso-org/enso/blob/f4581d53e9cd45b68eb1988874b25d2a99d6371c/lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketConnectionInterruptedTest.java#L51-L62
the test tries to esablish connection before the server is started resulting in `java.net.ConnectException: Connection refused`
