### PR TITLE
Project Manager fails to create directory when one exists

### LINKED ISSUE #11758: Renaming local assets side effects
PM is using `mv` for renaming assets without any validation for existing assets titles. This leads to potentially weird behaviour and giving some side effects for end user.

case A:
1. Create a directory and rename it to `foo`
2. Create another directory and rename it to `FOO` (or any capitalised letter variation)
3. The 2nd dir will be moved to the 1st one with old name

case B:
1. Create new project and call it `ABC`
2. Create new catalog and also rename it to `ABC` because you can
3. The directory will vanish from the asset list (on system it will be moved to the projects directory)

case C:
1. Create a directory and rename it to `XYZ`
2. Create a project and rename it to `XYZ`
3. Here the PM works fine and both assets are preserved (the projects directory will have `XYZ_1` in file system)

https://github.com/user-attachments/assets/ec05a456-a012-4e67-bb9d-b6bf1d5f51ef

Also not sure is it related but after multiple such merges, renames my project manager ends in error state (not responding to any create / update commands) with lots of error logs like this

```
Could not read initial state (1/3 retries), retrying after 2000ms...
ResultError {
  payload: 'Missing project root',
  context: [ [Function (anonymous)] ]
}
Language Server transport error: ErrorEvent {
  type: 'error',
  defaultPrevented: false,
  cancelable: false,
  timeStamp: 52796.402583
}
Language Server transport error: ErrorEvent {
  type: 'error',
  defaultPrevented: false,
  cancelable: false,
  timeStamp: 52798.449125
}
Could not read initial state (2/3 retries), retrying after 4000ms...
ResultError {
  payload: 'Missing project root',
  context: [ [Function (anonymous)] ]
}
Language Server transport error: ErrorEvent {
  type: 'error',
  defaultPrevented: false,
  cancelable: false,
  timeStamp: 55688.3125
}
Could not restart RPC client (1/3 retries), retrying after 2000ms...
ResultError {
  payload: LsRpcError {
    cause: 'LanguageServer disposed',
    request: 'capability/acquire',
    params: { method: 'file/receivesTreeUpdates', registerOptions: [Object] }
  },
  context: [ [Function (anonymous)] ]
}
Could not read initial state (3/3 retries), throwing error.
ResultError {
  payload: 'Missing project root',
  context: [ [Function (anonymous)] ]
}
Could not read initial state: Missing project root
When reading initial state
Language Server transport error: ErrorEvent {
  type: 'error',
  defaultPrevented: false,
  cancelable: false,
  timeStamp: 57055.5325
}
```

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #11758 

Changelog:
- update: FileSystemService fails to create directory if one exists

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala [hunk 1]
```diff
@@ -73,7 +73,10 @@ class BlockingFileSystem[F[+_, +_]: Sync: ErrorChannel](
   /** @inheritdoc */
   override def createDir(path: File): F[FileSystemFailure, Unit] =
     Sync[F]
-      .blockingOp { FileUtils.forceMkdir(path) }
+      .blockingOp {
+        if (path.exists()) throw new FileExistsException()
```
Comment (4e6) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala:77]: `exists` also works as expected on case-insensitive file systems. No other checks needed

**Review by hubertp — APPROVED** [review]

**Review by JaroslavTulach — APPROVED** [review]
