### PR TITLE
Fix detection of bundled runtime with --jvm option

### LINKED ISSUE #12302: Native `enso` bundle contains GraalVM, but `--jvm` cannot find it
While testing `enso-bundle` download as [described here](https://github.com/enso-org/enso/pull/12296#issuecomment-2664635744) I realized that while [running tests in native mode works](https://github.com/enso-org/enso/pull/12296#issuecomment-2664635744) when calling it with `--jvm` argument, it fails:
```bash
$ ./enso/dist/2025.1.1-nightly.2025.2.18/bin/enso --jvm --run /enso/test/Table_Tests
[WARN] [2025-02-18T06:59:58+01:00] [org.enso.runtimeversionmanager.components.GraalVersionManager] Runtime search path `/home/devel/.local/share/enso/runtime` is not a directory
[WARN] [2025-02-18T06:59:58+01:00] [org.enso.runner.JavaFinder] No appropriate JDK found in the distribution runtimes. Trying system-wide JDK.
[WARN] [2025-02-18T06:59:58+01:00] [org.enso.runner.JavaFinder] No JDK found in JAVA_HOME. Trying java on PATH.
[WARN] [2025-02-18T06:59:58+01:00] [org.enso.runner.JavaFinder] No JDK found on PATH. Cannot start the runtime.
Cannot find java executable
```
that's unfortunate as `ensoup` (part of the same [bundle download](https://github.com/enso-org/enso/releases/download/untagged-aed0b8c4d7d0b238bf33/enso-bundle-2025.1.1-nightly.2025.2.18-linux-amd64.tar.gz)) is **able to find JVM**:
```bash
$ ./enso/bin/ensoup run /enso/test/Table_Tests
```
What's wrong? 

- #11500

Probably `ensoup` is using the [portable distribution layout](https://github.com/enso-org/enso/blob/3d6f2ec8ec57010bc8de22bcada0e7915f829ca0/docs/distribution/distribution.md#portable-enso-distribution-layout) while the handling of `--jvm` switch isn't - maybe ignoring `.enso.portable`. CCing @radeusgd

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #12302

### Pull Request Description

Running
```
$ ./enso-linux-x86_64-2025.1.1-nightly.2025.2.18.AppImage --appimage-extract
$ ./squashfs-root/resources/enso/dist/2025.1.1-nightly.2025.2.18/bin/enso --jvm --run tmp.enso
```
from the extracted AppImage correctly finds the bundled runtime.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 1]
```diff
@@ -68,7 +69,10 @@ private static boolean isOnWindows() {
    */
   private static Path findJavaExecutableInDistributionRuntimes() {
     var env = new Environment() {};
-    var distributionManager = new DistributionManager(env);
+    var distributionManager = new PortableDistributionManager(env);
```
Comment (4e6) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java:72]: There should not be a `PortableDistributionManager`. The `DistributionManager` itself should decide whether it deals with the portable distribution or not.

Comment (4e6) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java:72]: I know it's kind of unrelated, just quite surprised that the `DistributionManager` can't do that.

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 2]
```diff
@@ -89,6 +93,9 @@ private static Path findJavaExecutableInDistributionRuntimes() {
           versionUsedForBuild);
       return newerRuntime.get().javaExecutable();
     }
+    logger.trace("No appropriate runtime found in the distribution.");
+    logger.trace("graalVersionManager.getAllRuntimes() = {}", graalVersionManager.getAllRuntimes());
+    logger.trace("Paths of distributionManager = {}", distributionManager.paths());
```
Comment (4e6) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: It's better to use a single log line. Multiple lines can be mixed up with other logs making the output less clear

**Review by JaroslavTulach — APPROVED** [review]
- I was hoping the fix to be related to distribution manager
- Any change to write a test for this? 
- We don't want to verify this manually with every release...

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java (hunk 2 above)
Comment (Akirathan) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: Good point. Fixed in 268be333960e110ddb27688d723f4331d0b4efbb

**Comment by Akirathan** [comment]
> Any chance to write a test for this? We don't want to verify this manually with every release...

@JaroslavTulach This can be tested only as an "engine integration test". The test needs some valid asset that we release - like the whole (extracted) AppImage or some kind of engine-bundle. We already have `--jvm` option testing in `Engine Checks` workflow - see https://github.com/enso-org/enso/blob/3d6f2ec8ec57010bc8de22bcada0e7915f829ca0/build_tools/build/src/engine/context.rs#L767.

Unfortunately, we don't have any "engine integration test" yet, so we will have to keep an eye out for this after every release.
