### PR TITLE
Handle pending dynamic configs

### LINKED ISSUE #13792: Join `on` argument has sometimes wrong widget
When a Project is big [like this one](https://github.com/farmaazon/Homm3BG-mod), and we wait some time for widget configuration, "on" argument in `join` component gets a selection widget, which then does not provide further assistance with column names.

https://github.com/user-attachments/assets/409257eb-adfb-4a13-a25e-0eb9f969cc9f

When waited for dynamic config, I get proper array in "on" argument, where I do get column names

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #13792

The case from the issue, with an artificial 10-second delay for receiving dynamic config:

https://github.com/user-attachments/assets/d1a0e291-dfe3-4c97-8017-3fbafed0dd86

I considered all widget types that currently use dynamic configuration and found that they can be split into two groups:
1. We don’t want to match the widget when we know that dynamic config is expected and has not yet arrived. This is Selection (the case from the issue), MultiSelection, and AnyToTarget.
2. We still want to match the widget, because it is generally applicable even without dynamic config. This is FileBrowser, Number, Text, and Vector. All these can still be used without correct dynamic configuration, although some functionality can be limited.

Because no general solution is possible, I added a new widget config kind called `Pending` that can be checked manually when matching a widget.

Changes covered with integration tests. It is now possible to override widget configuration on a per-argument basis in integration tests (some restrictions apply ©). I also fixed a weird issue with inherited config that wasn’t actually inherited but was overriding more accurate ‘child’ configurations.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts [hunk 1]
```diff
@@ -177,7 +186,14 @@ export function useWidgetFunctionCallInfo(
     } else if (data != null && !data.ok) {
       data.error.log('Cannot load dynamic configuration')
     }
-    return inheritedConfig.value
+    const parameters: FunctionCall['parameters'] = inheritedConfig.value?.parameters ?? new Map()
+    annotatedArguments.value?.forEach((name) => {
+      if (parameters.get(name) == null) parameters.set(name, pending())
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts:191]: Mutating data that belongs to a `computed`

**Review by kazcw — APPROVED** [review]
