### PR TITLE
Correctly display connections to lambdas

### LINKED ISSUE #7261: Connection to the lambdas are appearing on the left side on the node
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

K-means example from the template
image

### Expected behaviour

We are not going to support the connections inside lambdas at this point.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 11.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #7261

It's impossible to connect to the lambda arguments, but they are displayed as in code, and the correct span tree is generated for the lambda body. (hence you can connect to items inside)

https://github.com/enso-org/enso/assets/6566674/60af6413-e1b9-4e8c-a958-2906b5534d62

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/language/span-tree/src/generate.rs [hunk 1]
```diff
@@ -818,11 +817,53 @@ fn generate_trailing_expected_arguments(
     })
 }
 
+/// A single child node produced out of the lambda argument and the `->` token.
+#[derive(Debug)]
+struct FoldedLambdaArguments {
+    /// Both the lambda argument and the `->` token, as a single [`node::Kind::Token`] node.
+    child:          node::Child,
```
Comment (Frizi) [inline app/gui/language/span-tree/src/generate.rs:824]: I'm a little afraid of the consequences of folding all arguments and the arrow together into a single token. That means we won't be able to create any useful widgets there, like the ability to add more arguments or apply custom styling. But I guess we can expand this logic once we need it, and likely the span-tree will be removed at this point anyway. So I think it's fine as is.

File: app/gui/language/span-tree/src/generate.rs [hunk 2]
```diff
@@ -1158,7 +1213,18 @@ mod test {
...
+            .add_leaf(0, 3, node::Kind::Token, TreeCrumb { index: 0 })
+            .add_child(4, 5, node::Kind::argument(), TreeCrumb { index: 3 })
+            .add_empty_child(0, BeforeArgument(0))
+            .add_leaf(0, 1, node::Kind::argument(), InfixCrumb::LeftOperand)
+            .add_leaf(2, 1, node::Kind::Operation, InfixCrumb::Operator)
+            .add_empty_child(3, BeforeArgument(1))
+            .add_leaf(4, 1, node::Kind::argument(), InfixCrumb::RightOperand)
+            .add_empty_child(5, Append)
+            .done()
+            .done()
```
Comment (farmaazon) [inline app/gui/language/span-tree/src/generate.rs:1221]: Please add also a test case for lambda like `a -> b -> a + b`

File: app/gui/language/span-tree/src/generate.rs [hunk 3]
```diff
@@ -818,11 +817,53 @@ fn generate_trailing_expected_arguments(
...
+        .iter()
+        .take(arrow_index + 1)
+        .map(|raw_span_info| match raw_span_info {
+            SpanSeed::Space(ast::SpanSeedSpace { space }) => Ok(*space),
+            SpanSeed::Token(ast::SpanSeedToken { token }) => Ok(token.len()),
+            SpanSeed::Child(ast::SpanSeedChild { node }) => {
+                let kind = node::Kind::argument().with_removable(false);
+                let node = node.generate_node(kind, context);
+                node.map(|node| node.size.as_usize())
+            }
```
Comment (farmaazon) [inline app/gui/language/span-tree/src/generate.rs]: Do I understand correctly that we generate node only to discard it and read its size?

Are there no better options for measuring new AST node size? Like `repr_len` or `char_count` in the old AST? I believe generating span tree does much more things.

**Review by farmaazon — APPROVED** [review]
Approve to not block it, but I strongly recommend to not build span tree only to count AST node length.

**Review by Frizi — APPROVED** [review]

File: app/gui/language/span-tree/src/generate.rs (hunk 2 above)
Comment (vitvakatu) [reply app/gui/language/span-tree/src/generate.rs:1221]: Done

File: app/gui/language/span-tree/src/generate.rs (hunk 3 above)
Comment (vitvakatu) [reply app/gui/language/span-tree/src/generate.rs]: Yep, `repr_len` is better here, thanks for noting. I changed the code.

File: app/gui/language/span-tree/src/generate.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/language/span-tree/src/generate.rs:824]: Keep in mind that we were not planning to support connections to lambdas at all, so yes, let's think about it when the time comes :)

**Comment by Frizi** [comment]
# 🌈 QA Passed 🟢 

Nice work!
