### PR TITLE
Avoid nulls in Array.items

### LINKED ISSUE #5494: Builtin Array Is Exposing Nulls to Surface Language
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181935648).
<hr />

### General Summary

It is possible to encounter pure `null` values in the surface language if `Array` elements are accessed when they are not initialized.

### Steps to Reproduce

1. Launch `enso repl`.
2. Do the following steps and observe the output:
```
> a = Array.new 1
>>> Nothing
> b = a.at 0
>>> Nothing
> IO.println b
null
Evaluation failed with: java.lang.NullPointerException
java.lang.Exception: java.lang.NullPointerException
    at org.enso.interpreter.runtime.callable.atom.Atom.lambda$toString$0(Atom.java:80)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    (...)
```
### Expected Result

`null`s should not leak to the user. Printing missing values should not result in a crash.

`Array` API should be designed in such a way to never expose pure `null`s to the user.

### Actual Result

An exception is thrown.

### Enso Version

```
Enso Launcher
Version:    0.2.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: enso-0.2.0 @ d2df28bc43fcfee614fb31780cd46a59ebb16127
Built on:   Linux (amd64)
Current default Enso engine: 
Enso Compiler and Runtime
Version:    0.2.2-SNAPSHOT
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/database-library* @ 7e9d7e0ef10a609ead816375386b86f473219bcd
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-132-generic (amd64)
```

Migrated from https://github.com/enso-org/enso/issues/1424

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Put `Nothing` into an empty array rather than `null`. When running with `assert` on (unit tests), check the content of the array and `AssertError` quickly when a `null` is found.

### Checklist

Please include the following checklist in your PR:

- [x] All code conforms to the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java [hunk 1]
```diff
@@ -49,9 +50,24 @@ public Array(Object... items) {
    */
   @Builtin.Method(
       description = "Creates an uninitialized array of a given size.",
-      autoRegister = false)
-  public Array(long size) {
-    this.items = new Object[(int) size];
+      autoRegister = false, name = "new")
+  public static Array empty(long size) {
+    var arr = new Object[(int) size];
+    var ctx = EnsoContext.get(null);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java:57]: Now I see why you asked about it :)

**Review by hubertp — APPROVED** [review]
