### PR TITLE
Show only fields from current atom constructor in the debugger

### LINKED ISSUE #10675: Debugger doesn't show atom fields when there are multiple constructors
From the `InteropLibrary` perspective, an `Atom` lists all field for all constructors as *members*. But it should list just fields for the constructor that was used to construct that atom.

The `Atom` members are, e.g., displayed as fields in the chrome inspector debugger. For the following atom:
```
type My_Type
  Cons_1 f1 f2
  Cons_2 g1 g2

main =
  My_Type.Cons_1 1 2
```
we would like to see only `f1` and `f2` fields, not any other.

An example of wrongly listed fields in the debugger:
image

All field accessors for all constructors are registered in [AtomConstuctor.collectFieldAccessors](https://github.com/enso-org/enso/blob/db4f7ab3b5976fef33a4b0c9c57d3ad243540ca4/engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java#L317).

```[tasklist]
### Tasks
- [ ] Enable tests in [AtomInteropTest.java](https://github.com/enso-org/enso/blob/196506c114e95445daad19ad9b1db92abd80110c/engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AtomInteropTest.java)
- [ ] Enable test in [DebugEnsoTest.java](https://github.com/enso-org/enso/blob/e54d47d8fb510250d43a2ef4c955ac2d2016c608/engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java#L484)
```

Related to:
- #10144

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #10675

### Pull Request Description

Debugger shows only fields of the current atom constructor: (internal members shown in gray, "public" members shown in bold purple)
image

(Note that `static_method` is not displayed as a member of `My_Type` - not in scope of this PR)

### Important Notes

The *interop* contract for `Atom` is changed as follows:
- Members are all methods and fields of the current constructor.
- All methods are internal members.
- If the constructor is project-private, fields are internal members.
- All the members are both readable, and invocable.
  - Fields are field getters, that is, they are just methods.
- Fields are not invocable
- Constructors and static methods are **not** members of an atom. They should be members of the type.
- Note that methods used to be atom members before #9692

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [X] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java [hunk 1]
```diff
@@ -175,54 +216,65 @@ protected boolean isMethodProjectPrivate(Type type, String methodName) {
...
-        return true;
+    if (!hasProjectPrivateConstructor()) {
+      for (int i = 0; i < constructor.getArity(); i++) {
+        if (member.equals(constructor.getFields()[i].getName())) {
+          return true;
+        }
       }
     }
-    return false;
+    var publicMethodNames =
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java]: Using streams & lambda's in a PE method annotated with `@ExplodeLoop`!?

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java]: Stream methods are hidden behind TruffleBoundary in 71366f130d4dee4697d5c10015dedceacd44f357

**Comment by Akirathan** [comment]
Request for comments @radeusgd @jdunkerley @GregoryTravis @JaroslavTulach @hubertp @4e6 and anybody else using Chrome Inspector for debugging.

Atom now has methods as members. This means that all the methods will be (alphabetically) displayed in the debugger:
inspector-all-methods

An advantage of it is that, inside the console, tab completion works:
inspector_tab_completion

There may be a way to hide the methods from the debugger, display only fields, with the tab completion in the console still working. What are your opinions? Is the list of methods (displayed alphabetically) on the atom something that you consider useful? Let's vote:
- Thumbs up: it is useful, display methods, fields and have tab completion for methods and fields in console
- Thumbs down: it is not useful. Diplay only fields and have tab completion for methods and fields in console.

**Comment by radeusgd** [comment]
If we can still get tab completions for methods without displaying them, IMO that's best.

Displaying methods, where their representation is just `f ()` is not that helpful and it can obscure the view of fields the instance has - whose values may actually aid in debugging.

It's nice to see method names, but if as you say - tab completions still help with those - that will be IMO enough.

**Comment by Akirathan** [comment]
The current situation is as follows:
- All methods are *internal members* - they are displayed by the inspector in gray color.
- Only fields from public constructor is a proper member - displayed in bold purple by the inspector.
- Table completion works only on public members, not for internal members.

image

I don't know how to convince the inspector to not display *internal members*, and to provide proper tab completion. However, as you can see from the screenshot above, the situation is at least better than before - all methods are in gray and so you can immediately see the "important stuff". Unless there are strong opinions against, I would like to merge this PR and optionally create new tickets to improve the debugging experience. I believe the promised fix of this PR is delivered.

**Comment by radeusgd** [comment]
Sounds good.

I need to convince myself to use the debugger more, since it's getting such cool new features 😃

**Review by GregoryTravis — APPROVED** [review]
Approving .enso changes.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java [hunk 2]
```diff
@@ -1,55 +1,29 @@
...
-import com.oracle.truffle.api.nodes.RootNode;
-import org.enso.interpreter.runtime.EnsoContext;
+import org.enso.interpreter.EnsoLanguage;
 import org.enso.interpreter.runtime.callable.function.Function;
 import org.enso.interpreter.runtime.data.Type;
-import org.enso.interpreter.runtime.data.text.Text;
-import org.enso.interpreter.runtime.error.PanicException;
+import org.enso.interpreter.runtime.scope.ModuleScope;
 
 @NodeInfo(shortName = "get_field", description = "A base for auto-generated Atom getters.")
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java]: This description seems outdated?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java [hunk 3]
```diff
@@ -317,8 +317,11 @@ public static AtomConstructor accessorFor(Function fn) {
   public static Map<String, RootNode> collectFieldAccessors(EnsoLanguage language, Type type) {
     var constructors = type.getConstructors().values();
     var roots = new TreeMap<String, RootNode>();
-    if (constructors.size() != 1) {
+    if (constructors.size() > 1) {
       var names = new TreeMap<String, List<GetFieldWithMatchNode.GetterPair>>();
+      // We assume that all the constructors have the same definition scope. So we
+      // take just the first one.
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java:323]: Should/could be verified with an assert?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java [hunk 4]
```diff
@@ -137,96 +155,179 @@ boolean hasMembers() {
...
     }
     for (int i = 0; i < constructor.getArity(); i++) {
       if (member.equals(constructor.getFields()[i].getName())) {
-        return true;
+        // Fields of public constructor are not internal.
+        return false;
       }
     }
-    return false;
+    // All methods are internal.
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java:283]: That appears to contradict `InteropLibrary.isMemberInternal` which says the default is `false`?

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java]: Right. Updated docs in c902ccda6bda5b9126335bd728ea3dbe5bdc5bd4

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java:283]: This method returns `false` only for fields of a public constructor. All the other members, including all methods, are considered internal. That is, fields are "public members", methods are internal members. This is compatible with what we used to have before #9692.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java (hunk 3 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java:323]: I tried to have an assert for this. But it did not work, because every invocation of `getDefinitionScope()` creates a different object with same contents. Could be verified with a proper `equals` method on `ModuleScope` but that feels like an overkill for this PR. Hence, I have only written this comment here.
