### PR TITLE
Fix for table viz float filtering

### LINKED ISSUE #14304: Filter in Table Viz not working for floating point columns
Image

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #14304 

Before

https://github.com/user-attachments/assets/b9b1b377-32df-4131-9aaa-6b6edcb84ef8

After

https://github.com/user-attachments/assets/83fc98ad-931b-4dae-80c3-164a7c5ea200

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/visualizations/TableVisualization/TableVizDataSourceUtils.ts [hunk 1]
```diff
@@ -44,6 +53,9 @@ const parseFilterValues = (
       return pattern.instantiateCopied([Ast.TextLiteral.new(value.value, tempModule)])
     }
     case 'Integer':
+    case 'Float':
+    case 'Decimal':
+    case 'Byte':
       return Ast.parseExpression(value.value, tempModule)!
```
Comment (kazcw) [inline app/gui/src/project-view/components/visualizations/TableVisualization/TableVizDataSourceUtils.ts:59]: Are all these types safe to interpret as Enso values? Enso doesn't have E notation for floats, for example--but I don't know what the string representations for these types look like; if they're all in plain decimal notation it should be fine

Comment (AdRiley) [reply app/gui/src/project-view/components/visualizations/TableVisualization/TableVizDataSourceUtils.ts:59]: Looks like they get resolved before being passed over

image

image

**Review by kazcw — APPROVED** [review]
