### PR TITLE
Table Visualization and display text changes.

### LINKED ISSUE #5480: Table visualization incorrectly renders custom Enso objects
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/182263745).
<hr />

See Discord thread https://discord.com/channels/401396655599124480/978315597400145920/978316216408092763

### Steps to reproduce
1. Make sure that `import Standard.Table` is included at the beginning.
2. Create a node `Table.new [["foo", [Ordering.Less, Ordering.Equal]]]`.
3. Show the visualization and switch it to `Table`.

### Expected

The visualization cells should display `Less` and `Equal`.

### Actual

They display `[object Object]` instead.

### Comment

For comparison, if we add a node `. at "foo" . to_vector` and show the `Table` visualization on the Vector type, it is displayed correctly. So the logic for vectors seems to be correct and the logic for tables seems to lack something, but it should be fairly easy to just adapt the logic from vectors.

## Comments:
Screenshots of the described repro. (Radosław Waśko - May 23, 2022)
<hr />

### LINKED ISSUE #6375: Random viz is broken
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

image
image

### Expected behaviour

Properly working Random.new function

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

 27be43204c4df1e0217ebeabc98df0f90340c93d

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

- Missing tests from number parsing.
- Fix type signature on some warning methods.
- Fix warnings on `Standard.Database.Data.Table.parse_values`.
- Added test for `Nothing` and empty string on `use_first_row_as_names`.
- New API for `Number.format` taking a simple format string and `Locale`.
- Add ellipsis to truncated `Text.to_display_text`.
- Adjusted built-in `to_display_text` for numbers to not include type (but also to display BigInteger as value).
- Remove `Noise.Generator` interface type.
- Json: Added `to_display_text` to `JS_Object`.
- Time: Added `to_display_text` for `Date`, `Time_Of_Day`, `Date_Time`, `Duration` and `Period`.
- Text: Added `to_display_text` to `Locale`, `Case_Sensitivity`, `Encoding`, `Text_Sub_Range`, `Span`, `Utf_16_Span`.
- System: Added `to_display_text` to `File`, `File_Permissions`, `Process_Result` and `Exit_Code`.
- Network: Added `to_display_text` to `URI`, `HTTP_Status_Code` and `Header`.
- Added `to_display_text` to `Maybe`, `Regression`, `Pair`, `Range`, `Filter_Condition`.
- Added support for `to_js_object` and `to_display_text` to `Random_Number_Generator`.
- Verified all error types have `to_display_text`.
- Removed `BigInt`, `Date`, `Date_Time` and `Time_Of_Day` JS based rendering as using `to_display_text` now.
- Added support for rendering nested structures in the table viz.

### Adjusted Viz

**Custom Values Rendering:**
image

**Nested Table:**
image

**Variable size Matrix view:**
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js [hunk 1]
```diff
@@ -65,44 +65,8 @@ class TableVisualization extends Visualization {
...
                 const type = content.type
-                if (type === 'BigInt') {
-                    return BigInt(content.value)
-                } else if (content['_display_text_']) {
+                if (content['_display_text_']) {
                     return content['_display_text_']
-                } else if (type === 'Date') {
-                    return new Date(content.year, content.month - 1, content.day)
-                        .toISOString()
-                        .substring(0, 10)
```
Comment (radeusgd) [inline app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js:75]: IMO this is so much better now that this part of the logic is handled by Enso 👍

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso [hunk 2]
```diff
@@ -55,6 +56,17 @@ type Index_Sub_Range
          input, an error is raised.
     Every (step:Integer) (first:Integer=0)
 
+    ## PRIVATE
+       Convert to a display representation of this Index_Sub_Range.
+    to_display_text : Text
+    to_display_text self = case self of
+        Index_Sub_Range.First count -> "First " + count.to_display_text
+        Index_Sub_Range.Last count -> "Last " + count.to_display_text
+        Index_Sub_Range.While _ -> "While <predicate>"
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso]: Why not?

```suggestion
        Index_Sub_Range.While f -> "While "+f.to_display_text
```

I see that currently `to_display_text` of a `Function` returns `"Function"`. That is not helpful indeed. But if we changed it to return the same thing as `to_text`, then it could actually be useful - function's `to_text` shows the _name_ and _source location_ of the function. It can be of some help to identify the predicate.

Not a big deal though, just a suggestion of an improvement I thought of.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso [hunk 3]
```diff
@@ -199,6 +199,34 @@ type Filter_Condition
...
+    to_display_text self =
+        condition = case self of
+            Less value -> "<" + value.to_display_text
+            Equal_Or_Less value -> "<=" + value.to_display_text
+            Equal value -> "==" + value.to_display_text
+            Equal_Or_Greater value -> ">=" + value.to_display_text
+            Greater value -> ">" + value.to_display_text
+            Not_Equal value -> "!=" + value.to_display_text
+            Between lower upper -> "between " + lower.to_display_text + " and " + upper.to_display_text
+            Starts_With prefix case_sensitivity -> "starts with " + prefix.to_display_text + case_sensitivity.to_display_text
```
Comment (GregoryTravis) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso]: Do we need a space between the text and case_sensitivity?

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso [hunk 4]
```diff
@@ -248,6 +250,17 @@ type Pair
         f self.second
         Nothing
 
+    ## PRIVATE
+       Convert to a display representation of this Pair.
+    to_display_text : Text
+    to_display_text self =
+        first = self.first.to_display_text
+        second = self.second.to_display_text
+        if first.length + second.length < 75 then "Pair(" + first + ", " + second + ")" else
```
Comment (GregoryTravis) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso]: It might be nice to eventually have helpers for constructing these strings.

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java [hunk 5]
```diff
@@ -48,7 +47,7 @@ Text convertText(Text self) {
   @CompilerDirectives.TruffleBoundary
   private static Text takePrefix(Text self, final int limit) {
     var prefix = Core_Text_Utils.take_prefix(self.toString(), limit);
-    return Text.create(prefix);
+    return Text.create(prefix + " …");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:68]: When the limit is 80 and we add 4 characters, should we ask for `Core_Text_Utils.take_prefix(self.toString(), limit - 4)` to never exceed the limit?

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java [hunk 6]
```diff
@@ -38,11 +38,11 @@ String doDisplay(
       // Most likely it should be removed once that is implemented.
       return "null";
     } else if (TypesGen.isLong(value)) {
-      return value + " (Integer)";
+      return value.toString();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java]: This is going to cause problems with #6211 - the error message is not going to be as clear as _"Method `=` of 5 (Integer) could not be found"_.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java [hunk 7]
```diff
@@ -38,11 +38,11 @@ String doDisplay(
...
     } else if (TypesGen.isEnsoBigInteger(value)) {
-      return "Integer";
+      return value.toString();
     } else if (TypesGen.isDouble(value)) {
-      return value + " (Decimal)";
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java]: I think the proper way is to add new `@Specialization doDouble(double value)` and convert in there. Same for other primitive types.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso [hunk 8]
```diff
@@ -248,6 +250,17 @@ type Pair
...
+            first_trim = if first.length > 38 then first.take 37 + " …" else first
+            second_trim = if second.length > 38 then second.take 37 + " …" else second
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso]: While 37 + 37 is 74, together with the three dots added there the whole messages is going to exceed the 80 characters limit.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso [hunk 9]
```diff
@@ -40,6 +40,15 @@ type Text_Sub_Range
        Select an empty string if the input does not contain `delimiter`.
     After_Last (delimiter : Text)
 
+    ## PRIVATE
+       Convert to a display representation of this Index_Sub_Range.
+    to_display_text : Text
+    to_display_text self = case self of
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso:46]: There shall be generic implementation for these types with few atoms that would fit the default needs. At least I see some pattern that could be handled in a generic way via `Meta` or in the engine itself.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso [hunk 10]
```diff
@@ -170,3 +171,49 @@ type HTTP_Status_Code
     ## Does the status code represent a successful response?
     is_success : Boolean
     is_success self = self.code >= 200 && self.code < 300
+
+    ## PRIVATE
+       Convert to a display representation of this HTTP_Status_Code.
+    to_display_text : Text
+    to_display_text self = case self.code of
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso:178]: Wow. That's a huge case.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso [hunk 11]
```diff
@@ -53,6 +55,17 @@ type Random_Number_Generator
...
+    ## PRIVATE
+       Serialise to JS_Object (note it will contain the original seed not the current).
+    to_js_object : JS_Object
+    to_js_object self =
+        JS_Object.from_pairs [["type", "Random_Number_Generator"], ["constructor", "new"], ["seed", self.seed]]
+
+    ## PRIVATE
+       Convert to a display representation of this Random_Number_Generator.
+    to_display_text : Text
+    to_display_text self = "Random_Number_Generator(" + self.seed.to_text + ")"
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso]: Exposing `seed` may be a security hole, in my opinion.

**Review by JaroslavTulach — APPROVED** [review]
Massive PR. I left few comments there and elsewhere, but probably on the `.java` ones deserve some attention.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 5 above)
Comment (jdunkerley) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:68]: The three dots are a single character but yes should make it limit - 2. Will update.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java (hunk 6 above)
Comment (jdunkerley) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java]: This was already the case with `Text` values (which have identity (well truncation) as to_display_text) - we should amend the error message to report the type not the value.

**Review by farmaazon — APPROVED** [review]
Approving table.js

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java (hunk 7 above)
Comment (jdunkerley) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java]: Add specializations to `AnyToDisplayTextNode` and reverted the changes to `TypeToDisplayTextNode`.
I have amended the `to_display_text` of `No_Such_Method` to get the type object instead of the value.

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js [hunk 12]
```diff
@@ -158,22 +126,47 @@ class TableVisualization extends Visualization {
...
-            rowData = parsedData.json
+        } else if (parsedData.type === 'Matrix') {
+            let defs = [{ field: '#' }]
+            for (let i = 0; i < parsedData.column_count; i++) {
+                defs.push({ field: i.toString() })
+            }
+            columnDefs = defs
+            rowData = addRowIndex(parsedData.json)
+            dataTruncated = parsedData.all_rows_count !== parsedData.json.length
+        } else if (parsedData.type === 'Object_Matrix') {
```
Comment (radeusgd) [inline app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js:137]: Why are the cases `isObjectMatrix(...)` and `parsedData.type == 'Object_Matrix'` distinguished? They look very similar. I think it would be good to add some comment explaining what is the difference between these cases, as it may be very confusing - reading this code I see the "same" case handled twice in a slightly different way and I just don't know why.

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js:137]: Legacy support for the old engine.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso [hunk 13]
```diff
@@ -199,6 +199,38 @@ type Filter_Condition
...
+        condition = case self of
+            Less value -> "<" + value.to_display_text
+            Equal_Or_Less value -> "<=" + value.to_display_text
+            Equal value -> "==" + value.to_display_text
+            Equal_Or_Greater value -> ">=" + value.to_display_text
+            Greater value -> ">" + value.to_display_text
+            Not_Equal value -> "!=" + value.to_display_text
+            Between lower upper -> "Between " + lower.to_display_text + " And " + upper.to_display_text
+            Starts_With prefix case_sensitivity ->
+                "Starts With " + prefix.to_display_text + (if case_sensitivity == Case_Sensitivity.Default then "" else " Case " + case_sensitivity.to_display_text)
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso]: I'd extract this into a local helper at the top of this function:
```
render_case case_sensitivity =
    if case_sensitivity == Case_Sensitivity.Default then "" else " Case " + case_sensitivity.to_display_text
```
and then do
```suggestion
                "Starts With " + prefix.to_display_text + (render_case case_sensitivity)
```

I think it will be cleaner than repeating this 4 times.

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js (hunk 12 above)
Comment (radeusgd) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js:137]: Ah, I see. Makes sense - can we have a comment in the code? Preferably with an explanation when can we remove this legacy support? (I assume we don't want to keep it forever)

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso [hunk 14]
```diff
@@ -52,7 +52,7 @@ Number.to_js_object self = case self of
         ## JS Safe Integer range -(2^53 - 1) to (2^53 - 1)
         js_max_integer = 9007199254740991
         if self >= -js_max_integer && self < js_max_integer then self else
-            JS_Object.from_pairs [["type", "BigInt"], ["value", self.to_text]]
+            JS_Object.from_pairs [["type", "BigInt"], ["value", self.to_text], ["_display_text_", self.to_display_text]]
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso]: Not sure if something to tackle in this PR, but looking at this I feel like we may be making an architecture mistake and I'd like to discuss at least in terms of possible follow-up.

We are including "display" (view) data in `to_js_object` which to me sounds more like a "serialization" thing. I assume I will want to use `to_js_object` when writing a Table or any other object to a `.json` file, right? And in such a serialized format, I really doubt I want a `_display_text_` field - at least by default.

I think the issue is `to_js_object` is trying to do too many things at the same time. The JSON representation for _serialization_ and for _view_ are just two different concepts and mixing them sounds like not the best idea.

What if instead, we kept `to_js_object` as is and relied on a _separate_ method for the visualization? It can either be `to_default_visualization_data` or some new `to_js_object_for_display` or something.

What do you think?

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso]: Have removed this from the two places outside of the Table Viz.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso [hunk 15]
```diff
@@ -95,6 +95,12 @@ type Span
     to_utf_16_span self =
         Utf_16_Span.Value (range_to_char_indices self.parent self.range) self.parent
 
+    ## PRIVATE
+       Convert to a display representation of this Span.
+    to_display_text : Text
+    to_display_text self = self.text
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso:101]: Hm, shouldn't we indicate that this is a `Span` and not just regular `Text`?

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso [hunk 16]
```diff
@@ -584,6 +584,13 @@ type Date_Time
                 Time_Utils.datetime_adjust self Time_Utils.AdjustOp.MINUS period.internal_period
         ensure_in_epoch result result
 
+    ## PRIVATE
+       Convert to a display representation of this Date_Time.
+    to_display_text : Text
+    to_display_text self =
+        time_format = if self.nanosecond == 0 then "HH:mm:ss" else "HH:mm:ss.n"
+        self.format "yyyy-MM-dd "+time_format+" Z"
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: Is the `Z` correct here? I think the `Date_Time` can have a different timezone, no?

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: Z is the format string from Time Zone Offset
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

Seemed a reasonable format.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso [hunk 17]
```diff
@@ -262,3 +263,10 @@ type Duration
         if self.milliseconds==0 . not then b.append ["milliseconds", self.milliseconds]
         if self.nanoseconds==0 . not then b.append ["nanoseconds", self.nanoseconds]
         JS_Object.from_pairs b.to_vector
+
+    ## PRIVATE
+       Convert Duration to a friendly string.
+    to_display_text : Text
+    to_display_text self =
+        seconds = self.seconds + self.nanoseconds/1000000000
+        self.hours.to_text + "h" + self.minutes.format "00" + "m" + seconds.format "00.##########"
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso]: This will yield stuff like `0h 00m 12.34567` shouldn't it be `0h 00m 12.34567s`?

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso]: I think it would be good if we had at least 1 unit test case for these, to make sure that they at least compile (knowing how easy it used be to break `to_display_text` by refactors in the past).

Can we get it? If not in this PR, can we plan a followup?

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso [hunk 18]
```diff
@@ -128,3 +128,17 @@ type Period
                 case err of
                     DateTimeException -> Error.throw Time_Error.Error "Period subtraction failed"
                     ArithmeticException -> Error.throw Illegal_Argument.Error "Arithmetic error"
+
+    ## PRIVATE
+       Convert Period to a friendly string.
+    to_display_text : Text
+    to_display_text self =
+        years = self.years + (self.months/12).floor
+        y = if years = 0 then "" else years.to_text + "Y"
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso]: wouldn't `year/years` be more friendly than `Y`?

Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso]: I think the denser format is better (it was "PT12M"). Will add spaces like in Duration though.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso (hunk 17 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso]: Also ideally, I think it would be good if we can be consistent with `Time_Of_Day` handling of nanoseconds, i.e. if `nanoseconds == 0`, we should have `0h 05m 09s` and not `0h 05m 09.000000000s`. Do the `#` in the format achieve that? I don't know well enough how this format works - would be good to have a test for it as then this knowledge would not be required - we'd have a practical 'proof'.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso (hunk 16 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: oh! My bad! I thought it's a constant piece of text.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso (hunk 17 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso]: Yes the `#` automatically adds digits as needed (including trimming the `.`).

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso (hunk 16 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: Looks all good then!
Still - I think worth having a test - just to illustrate - then in the test I'd see there is some `Europe/Warsaw` suffix or sth like that and would not make this mistake :)

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso (hunk 18 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso]: ok

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso (hunk 16 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: `V` is probably better so will switch to V and add a test or two.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso [hunk 19]
```diff
@@ -161,7 +162,9 @@ type No_Such_Method
     ## PRIVATE
        Convert the No_Such_Method error to a human-readable format.
     to_display_text : Text
-    to_display_text self = "Method `"+self.method_name+"` of "+self.target.to_display_text+" could not be found."
+    to_display_text self =
+        target_type = Meta.type_of self.target
+        "Method `"+self.method_name+"` of type "+target_type.to_display_text+" could not be found."
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso]: Note that to make this work well with Polyglot Values we should fix how `to_display_text` is rendered on Java classes - currently it is `java.lang.Class` instead of the class name.
image

So with this change we will be getting:
```
Method `foo` of type `java.lang.Class` could not be found.
```
when running stuff like `NumberFormatException.new.foo`.

I think we should be getting:
```
Method `foo` of type `java.lang.NumberFormatException` could not be found.
```

To get that, we need to fix `to_display_text` for Java types.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso (hunk 16 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso]: Perfect, thanks

File: distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso (hunk 19 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso]: what did we get before?
Guessing only worked as inside builtins.

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso]: The screenshot is from _before_ this PR. It worked more or less OK relying on the weird behaviour of `to_display_text` returning the _type_ for unknown values.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso [hunk 20]
```diff
@@ -174,6 +177,10 @@ type No_Such_Field
        - field_name: The name of the field that was being accessed.
     Error value field_name
 
+    ## PRIVATE
+       Convert the No_Such_Method error to a human-readable format.
+    to_display_text : Text
+    to_display_text self = "Field `"+self.field_name+"` of "+self.value.to_display_text+" could not be found."
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso]: Shouldn't this have the same `Meta.type_of` logic as `No_Such_Method`? These errors are essentially twins, so IMO they should be consistent.

File: distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso (hunk 10 above)
Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso:178]: Indeed, wow 🙂

File: distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso [hunk 21]
```diff
@@ -188,6 +188,11 @@ type URI
     to_text : Text
     to_text self = self.internal_uri.toString
 
+    ## PRIVATE
+       Convert to a display representation of this UTI.
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso]:
```suggestion
       Convert to a display representation of this URI.
```

File: distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso (hunk 19 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso]: `target_type_name = if Meta.is_polyglot self.target then self.to_display_text else (Meta.type_of self.target).to_display_text`

should make it work for now.

File: distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso [hunk 22]
```diff
@@ -108,3 +109,12 @@ type File_Permissions
             others.append Permission.Execute
 
         File_Permissions.Value owner.to_vector group.to_vector others.to_vector
+
+    ## PRIVATE
+       Convert to a display representation of this File_Permissions.
+    to_display_text : Text
+    to_display_text self =
+        owner = "Owner: " + (if self.owner_execute then "x" else "-") + (if self.owner_write then "w" else "-") + (if self.owner_read then "r" else "-")
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso]: `xwr`? I was always used to `rwx`

Any reason for that choice?

File: distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso [hunk 23]
```diff
@@ -39,3 +40,10 @@ type Exit_Code
     to_number self = case self of
         Exit_Code.Success -> 0
         Exit_Code.Failure code -> code
+
+    ## PRIVATE
+       Convert to a display representation of this Exit_Code.
+    to_display_text : Text
+    to_display_text self = case self of
+        Exit_Code.Success -> "Success"
+        Exit_Code.Failure code -> "Failure " + code.to_display_text
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso:49]:
```suggestion
        Exit_Code.Success -> "Exit_Code.Success"
        Exit_Code.Failure code -> "Exit_Code.Failure " + code.to_display_text
```

I'm wondering if in this case it would be good to clearly indicate in the text that these are _exit code_ statuses.

File: distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso (hunk 22 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso:117]: incompetence with shuffle

File: distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso [hunk 24]
```diff
@@ -78,3 +78,10 @@ type Process_Builder
 type Process_Result
     ## PRIVATE
     Value exit_code:Exit_Code stdout:Text stderr:Text
+
+    ## PRIVATE
+       Convert to a display representation of this Process_Result.
+    to_display_text : Text
+    to_display_text self = case self.exit_code of
+        Exit_Code.Success -> "Success(" + self.stdout.to_display_text + ")"
+        _ -> self.exit_code.to_display_text + "(" + self.stderr.to_display_text + ")"
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso:87]: Interesting choice. I guess makes sense

File: distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso [hunk 25]
```diff
@@ -1497,6 +1497,7 @@ type Table
        suffixing strategy.
     parse_to_columns : Text | Integer -> Text -> Case_Sensitivity -> Boolean -> Problem_Behavior -> Table
     parse_to_columns self column pattern="." case_sensitivity=Case_Sensitivity.Sensitive parse_values=True on_problems=Report_Error =
+        _ = [column, pattern, case_sensitivity, parse_values, on_problems]
```
Comment (radeusgd) [inline distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso:1500]: Also adding this in my PR 😅 
I think it would be cool to have the `--warnings-as-errors` option to enable it on CI. Shall we create a ticket?

File: test/Table_Tests/src/In_Memory/Table_Spec.enso [hunk 26]
```diff
@@ -525,12 +525,14 @@ spec =
...
+            c_00 = ['AA', ["", "B", "C"]]
             c_1 = ['B', [Date.new 1980, Date.new 1979, Date.new 2000]]
             c_2 = ['x', [1, 2, 3]]
             c_3 = ['Y', [5.3, 56.2, 6.3]]
             c_4 = ['Z', [True, False, True]]
-            table = Table.new [c_0, c_1, c_2, c_3, c_4]
-            expect_column_names ["H", "1980-01-01", "1", "5.3", "True"] <| table.use_first_row_as_names
+            c_5 = ['ZZ', [Nothing, False, True]]
+            table = Table.new [c_0, c_00, c_1, c_2, c_3, c_4, c_5]
+            expect_column_names ["H", "Column_1", "1980-01-01", "1", "5.3", "True", "Column_2"] table.use_first_row_as_names
```
Comment (radeusgd) [inline test/Table_Tests/src/In_Memory/Table_Spec.enso:535]: I'm wondering if we should actually attach some warning in this case?

File: distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso (hunk 23 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso:49]: This is consistent with our other constructor formats where we just show the constructor name. The type is shown when hovering on the node so I think is ok.

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso:49]: Weren't we chatting that we may want to start adding the type more? Maybe I remember something wrongly.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java [hunk 27]
```diff
@@ -35,6 +35,21 @@ Text showExceptions(
     }
   }
 
+  @Specialization
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:38]: This is what I had in mind. You may need to add `@TruffleBoundary` - text concatenations aren't suitable for PE.

**Review by radeusgd — APPROVED** [review]
The changes look very good to me.

I think we should add some tests for the `to_display_text` methods, especially ones doing formatting of numbers/dates/times - as these are not _that_ trivial. We had experience of easily breaking `to_display_text` when refactoring. This is really problematic as if we don't detect it, we can very easily introduce regressions into the IDE display that may be noticed too late.

I'm ok with not having tests in this PR as we want to move forward and I assume it was tested manually, but I think in that case we should plan a follow up ticket to add these tests - as we definitely want these `to_display_text` to work correctly and avoid any regressions there.

File: test/Table_Tests/src/In_Memory/Table_Spec.enso (hunk 26 above)
Comment (jdunkerley) [reply test/Table_Tests/src/In_Memory/Table_Spec.enso:535]: It does but it also seems to error when rendering so will look at that.

Comment (radeusgd) [reply test/Table_Tests/src/In_Memory/Table_Spec.enso:535]: Then we should have this test checking this warning.
