### PR TITLE
Fix some Maximum call stack exceeded issues on the release branch

### LINKED ISSUE #14519: Spurious(?) error when switching to JSON visualization
1. Select `Getting Started with Enso` sample project
2. Go to node with scatterplot
3. Select JSON visualization rather than Scatterplot
4. Get
`Range Error: Maximum call stack size exceeded`

Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #14519

We observe various variations of `Maximum call stack exceeded` errors. At least two cases are fixed by this PR:
- #14519, caused by stale visualization data received, trying to build too large tree of Vue components from JSON visualization.
- Error when opening multiple projects at the same time. It is also fixed in #14807, but this PR allows a quickfix for the previous release.

Also fixed warnings in console about missing `title` prop in `DocumentationVideo` component, and added more guards to prevent possible call stack busts in a few places, notably in local storage infrastructure.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/shared/AgGridTableView/Utils.ts [hunk 1]
```diff
@@ -84,7 +84,9 @@ export const getAgGridProperties = (): [Properties, Properties, Properties] => {
 
         _processOnChange({ rowData: currentValue }, this.api)
       },
-      deep: true,
+      // `deep: true` can recurse through nested Maps/Sets and blow the stack. We only need to
+      // observe the immediate shape (top-level fields / array elements) for prop updates.
+      deep: 1,
```
Comment (farmaazon) [inline app/gui/src/project-view/components/shared/AgGridTableView/Utils.ts]: Add a note to licence information at top of the file (similarly as we have in AgGridVue.ts)

File: app/gui/src/project-view/composables/syncLocalStorage.ts [hunk 2]
```diff
@@ -112,16 +115,18 @@ export function useSyncLocalStorage<StoredState extends object>(
...
-      for (const key of storageMap.value.keys()) {
+    if (next.size > MAX_STORED_GRAPH_STATES) {
+      let toRemove = next.size - MAX_STORED_GRAPH_STATES / 2
+      for (const key of next.keys()) {
         if (toRemove-- <= 0) break
-        storageMap.value.delete(key)
+        next.delete(key)
       }
     }
+    storageMap.value = next
```
Comment (farmaazon) [inline app/gui/src/project-view/composables/syncLocalStorage.ts:130]: Why do we need this change? Add a comment, please.

File: app/gui/src/project-view/composables/syncLocalStorage.ts [hunk 3]
```diff
@@ -152,7 +159,9 @@ export function useSyncLocalStorage<StoredState extends object>(
       const stateBlob = storageMap.value.get(oldKey)
       if (stateBlob != null) {
         const newKey = encodeKey(newKeyEncoder)
-        storageMap.value.set(newKey, stateBlob)
+        const next = new Map(storageMap.value)
+        next.set(newKey, stateBlob)
+        storageMap.value = next
```
Comment (farmaazon) [inline app/gui/src/project-view/composables/syncLocalStorage.ts:166]: And here also.

File: app/gui/src/providers/queryParams.ts [hunk 4]
```diff
@@ -53,25 +53,28 @@ export function createQueryParams(
...
 
-  watch(queryParams, (newQueryParams) => {
-    const navigate = () => {
-      const query = Object.fromEntries(newQueryParams.entries())
-      if (anyPushed.value) {
-        router.push({ query })
-      } else {
-        router.replace({ query })
+  watch(
+    () => Array.from(queryParams.entries()),
```
Comment (farmaazon) [inline app/gui/src/providers/queryParams.ts]: Why this change? queryParams is a map of plan strings (or nulls), isn't it?

File: app/gui/src/utils/reactivity.ts [hunk 5]
```diff
@@ -147,14 +148,16 @@ export class LazySyncEffectSet {
  */
 export function useWatchContext(): { watchEffect: (f: () => void) => WatchStopHandle } {
   const queued = new Set<object>()
-  const jobs = reactive(new Array<() => void>())
-  watch(jobs, () => {
+  // Do not make the queue reactive: `watch(reactiveArray, ...)` deep-traverses its contents, and
+  // our queued runners reference large/cyclic graphs (effects, deps, Maps/Sets), which can blow
+  // the call stack inside Vue's `traverse()`.
+  const jobs: Array<() => void> = []
```
Comment (farmaazon) [inline app/gui/src/utils/reactivity.ts]: Wouldn't `shalowReactive` do its job here?

File: app/gui/src/project-view/components/shared/AgGridTableView/Utils.ts (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/shared/AgGridTableView/Utils.ts]: Done

File: app/gui/src/project-view/composables/syncLocalStorage.ts (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/composables/syncLocalStorage.ts:130]: Added a comment. To prevent watching arbitrarily deep and big structures in local storage we use shallow watcher, so need to update the root reference.

File: app/gui/src/project-view/composables/syncLocalStorage.ts (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/composables/syncLocalStorage.ts:166]: Added a comment.

File: app/gui/src/providers/queryParams.ts (hunk 4 above)
Comment (vitvakatu) [reply app/gui/src/providers/queryParams.ts]: Yeah, it is, I decided to revert this change after some consideration. I believe query params can be arbitrarily big and deeply nested in theory, but in practice we are protected by TS quite well, which I have missed.

File: app/gui/src/utils/reactivity.ts (hunk 5 above)
Comment (vitvakatu) [reply app/gui/src/utils/reactivity.ts]: Reverting this change as well. Yeah `shallowReactive` would help, but also I missed that we are storing function pointers, and Vue would not traverse into them voluntarily.

**Comment by vitvakatu** [comment]
This PR is retargeted to release branch, and another one created for develop: #14854

**Review by farmaazon — APPROVED** [review]

**Comment by vitvakatu** [comment]
A better fix for stale visualization data was implemented, rather utilizing the prexisting `preprocessorLoading` flag in `visualizationData` module. Hopefully it will make the tests pass.
