### PR TITLE
initProtocol endpoint returns success when already initialized

### LINKED ISSUE #9347: GUI2 times out  connecting to Language Server on large projects
### Repro steps
1. Create a new project from "Colorado COVID" template on the Cloud backend
2. Wait for the project to open

### Expected result
No errors

### Actual result
Connecting to Language Server times out

### Details
Console logs:
[localhost-1709807376658.log](https://github.com/enso-org/enso/files/14556006/localhost-1709807376658.log)

WebSocket messages:
Note that the first reply from the backend arrives 17 (!) seconds after the request. This is higher than the 15 second limit, which is demonstrated by the second request being sent after roughly 16 seconds.
image

Console logs (screenshots):
image

image

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

This PR makes initSession call return just the success message with content roots instead of a failure without. This allow IDE getting information on retries.

Fixes #9347 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala [hunk 1]
```diff
@@ -275,7 +275,7 @@ class JsonConnectionController(
     rootsSoFar: List[ContentRootWithFile]
   ): Receive = LoggingReceive {
     case ContentRootManagerProtocol.ContentRootsAddedNotification(roots) =>
-      val allRoots = roots ++ rootsSoFar
+      val allRoots = (roots ++ rootsSoFar).map(_.toContentRoot).toSet
```
Comment (4e6) [inline engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala]: I'd calculate `allRoots` inside the if branch. Because only the `true` outcome uses it.

Comment (4e6) [reply engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala]: I'll update it together with the test related fixes

**Review by 4e6 — APPROVED** [review]
