### PR TITLE
Report type of expressions returning polyglot values

### LINKED ISSUE #5026: Polyglot values are not recognized as their Enso equivalents by the IDE
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184336928).
<hr />

If you have a Java Date that comes to the IDE from the polyglot world it's type is not recognized and so you get no help from the CB etc.

The engine side works fine so the functions do work but you need to know them rather than it guiding you.

This is true for a simple

```
polyglot java import java.time.LocalDate

main = 
    operator1 = LocalDate.now
```

but it occurred from parsing a table with dates in it.

The same is true if I embed a simple JS function and call it:

```
foreign js hello = """
    return "Hello World!"
```

The text returned's type is not known.
If the polyglot returns a number the type is known as normal.

## Comments:
 (James Dunkerley - Jan 27, 2023)
<hr />
In a debugging session, I compared what is sent over the websocket between IDE and LS when editing a node to `Date.now` or `LocalDate.now`. The difference seems to be in "executionContext/expressionUpdates" message sent from LS which has `type: null` in its `updates` field for `LocalDate.now`. Apart from that, I was not yet able to pinpoint the exact point where the type of a node is resolved. (Pavel Marek - Jan 31, 2023)
<hr />
This is a log, with trace enabled, when I tried to add nodes to an empty project (with just imports) with `LocalDate.now`, `Date.now` and `My_Type.Value 42`. (Pavel Marek - Feb 1, 2023)
<hr />
Removed regression tag - it's been like that since inception. (Hubert Plociniczak - Feb 3, 2023)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2023-02-02):

**Progress:** Investigating suboptimal JGit performance at startup which was leading to occasional timeouts. Improvement is ready in a PR but will be eventually replaced by git itself due to unsatisfactory performance. It should be finished by 2023-02-03.

**Next Day:** Next day I will be working on the [#184336928 task](https://www.pivotaltracker.com/story/show/184336928). Go back to fixing reporting types for polyglot values, based on Jaroslav's feedback. (Enso Bot - Feb 3, 2023)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for the last Wednesday (2023-02-01):

**Progress:** Investigating why the typo of polyglot values isn't shown for polyglot values. Draft PR ready for some discussion. Ongoing stability issues investigations. It should be finished by 2023-02-03.

**Next Day:** Next day I will be working on the [#184359934 task](https://www.pivotaltracker.com/story/show/184359934). Needs discussion with Jaroslav regarding the approach (currently assertions fail), investigating timeouts happening at startup (Enso Bot - Feb 3, 2023)
<hr />

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Expressions returning polyglot values were not reporting the type of the result because we have to do additional magic that infers the correct Enso type. Since this is exactly what `TypeOfNode` does, I re-used the logic.

Straightforward solution failed in tests because of assertions:
```
[enso] WARNING: Execution of function main failed (Invalid library usage. Cached library must be adopted by a RootNode before it is executed.).
java.lang.AssertionError: Invalid library usage. Cached library must be adopted by a RootNode before it is executed.
```

That is why this PR replaces `ExecutionEventListener` with `ExecutionEventNodeFactory`.

### Important Notes

Usage of `TypeOfNode` for programs that **do not** import stdlib means that we report types that do not involve stdlib e.g.
`Standard.Builtins.Main.Integer` instead of `Standard.Base.Data.Numbers.Integer`. While surprising, this is correct and I would say desirable. While reviewing the code, notice the difference in expectations in our runtime tests.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 1]
```diff
@@ -64,6 +66,7 @@ private static class IdExecutionEventListener implements ExecutionEventListener
     private final UUID nextExecutionItem;
     private final Map<UUID, FunctionCallInfo> calls = new HashMap<>();
     private final Timer timer;
+    private final TypeOfNode typeOfNode;
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java]: Using node in an instrument is completely fine. But instead of `ExecutionEventListener` we should rewrite the code to [ExecutionEventNodeFactory](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/instrumentation/ExecutionEventNodeFactory.html) - then the `TypeOfNode` will get _"mounted"_ (and adopted) in the tree of other nodes.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java [hunk 2]
```diff
@@ -187,6 +191,13 @@ private void onExpressionReturn(Object result, Node node, EventContext context)
         boolean isPanic = result instanceof PanicSentinel;
         UUID nodeId = ((ExpressionNode) node).getId();
         String resultType = Types.getName(result);
+        if (resultType == null && result != null) {
+            // Slow path
+            Object typeResult = typeOfNode.execute(result);
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java]: The whole method is behind `@TruffleBoundary` right now. I suggest to change it and call `typeOfNode.execute` in PE mode. It should be quite fast.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java [hunk 3]
```diff
@@ -50,6 +54,21 @@ Object doString(String value) {
...
+  }
+
+  @Specialization
+  Object doPanicSentinel(PanicSentinel value) {
+    return EnsoContext.get(this).getBuiltins().panic();
+  }
+
+  @Specialization
+  Object doWarning(WithWarnings value) {
+    return execute(value.getValue());
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java:69]: @JaroslavTulach The type of the Warning is the type of the underlying value - that is the expected semantics, right? Nothing broke because of that so I'm assuming this is OK.

File: engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala [hunk 4]
```diff
@@ -319,7 +319,7 @@ class BuiltinTypesTest
       3
     ) should contain theSameElementsAs Seq(
       Api.Response(requestId, Api.PushContextResponse(contextId)),
-      TestMessages.update(contextId, idMain, "Enso_Test.Test.Main.Foo.Bar"),
+      TestMessages.update(contextId, idMain, ConstantsGen.FUNCTION_BUILTIN),
```
Comment (hubertp) [inline engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala:322]: This might seem like a weird change at first sight but consider that `Bar` is a constructor taking an argument. So the type of it is a Function. `Types.getName` had a special case for `AtomConstructor` and I think now we are more consistent.

File: engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java [hunk 5]
```diff
@@ -77,8 +77,10 @@ public void checkAllConstantGenValuesArePresent() throws Exception {
     var g = ValuesGenerator.create(ctx);
     var expecting = new HashSet<String>();
     for (var f : ConstantsGen.class.getFields()) {
-      var s = (String) f.get(null);
-      expecting.add(s);
+      if (!f.getName().endsWith("_BUILTIN")) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java:80]: What is this?

**Review by JaroslavTulach — APPROVED** [review]
Usage of `ExecutionEventNodeFactory` seems correct. Using nodes from instruments is a good thing - and it is also fast. Sharing such _"utility nodes"_ like `TypeOfNode` at various places is the way to go.

File: engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java (hunk 5 above)
Comment (hubertp) [reply engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java:80]: This is so that we don't have to write (by hand) FQN of builtin types. We generate `ConstantsGen` for types from stdlib but if one does not import stdlib builtin types are essentially `Standard.Builtin.Main.XYZ`. So every type which is in stdlib, say `Standard.Base.Foo.Bar.XYZ` has an equivalent in `Standard.Builtin.Main.XYZ`. Rather than trying to keep those up-to-date, processor adds those to `ConstantsGen`.

You might ask why do we need this at all?
Well, in tests (but also in a real application), if you don't import stdlib you operate only on builtins and the reported type shouldn't really be some type from stdlib, should it? That is why the type reported by `TypeOfNode` is an actual type, not some hardcoded string (like `Types.getName`). Hence the changes in tests (the changed ones don't import stdlib). 

Also, the test assumes that stdlib is imported. It does not operate on builtins.
