### PR TITLE
Dynamic app resampling and better performance measurements.

### LINKED ISSUE #6636: Debug logs left in the console
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When working with the workflow the console is polluted with:
image

### Expected behaviour

Meaningful informations displayed in the console

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

nightly 10.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by wdanilo**
# Pull Request Description

This PR introduces several new tools for GPU-related performance measurements and a new, low-resolution rendering mode which should increase the GUI speed on old, weak hardware.

</br>

## Proper measurement of GPU performance.

**WARNING! Currently (2023) this extension is only available in Chrome Desktop.**

A new way to measure GPU performance have been introduced. It bases on the [ExtDisjointTimerQueryWebgl2 WebGL extension](https://developer.mozilla.org/en-US/docs/Web/API/EXT_disjoint_timer_query), which is pretty tricky to use. First of all, it was banned from all browsers some time ago because of the ["GLitch" exploit] (https://www.vusec.net/projects/glitch). However, as Site Isolation shipped in Chrome on Desktop, the extension was re-enabled there because the only data that could be read was data that came from the same origin. To learn more, see: https://bugs.chromium.org/p/chromium/issues/detail?id=1230926. 

<br/>

## Automatic low/high resolution modes.
The application resolution mode is automatically switched between low and hight. In the low resolution mode, the [device pixel ratio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) will be set to `1.0` even on high-dpi screens. This will result in faster rendering (every 4-th pixel) and a more blurry image of the GUI. I believe that the blurriness of the fonts can be decreased in this mode by tweaking shaders, and it can be performed in a separate PR. The switch happens after a few frames were rendered slow/fast enough. The performance of the rendering is measured using the new performance measurements described above. In case the app is run not in Chrome, the FPS will be used instead of the proper measurements, which might cause the app to switch to low-resolution mode even if the bottleneck is CPU, not GPU.

https://user-images.githubusercontent.com/1623053/236707705-2379ac44-bcf0-47e5-a5f9-210f9ee5f6b1.mov

<br/>

## Improvements to the performance monitor.
The performance monitor was extended with additional information:
- The "frame time" was renamed to "GPU + CPU time".
- The "CPU time" is a new measurements which reports the time spent on CPU-related operations, excluding GPU ones.
- The "GPU time" is a new measurement which reports the time spent on GPU-related operations, excluding CPU ones.
- Idle time is a new measurement which reports how much free time was left during rendering of the frame. Please note, that currently this measurement is broken and it can report negative values, as we need to enable high-resolution timers in Enso.

Please note, that the division between CPU and GPU time is not known immediately and we can get it with a few frames delay. That's why you can observe sometimes in the performance monitor a greyed-out value for a few frames, which turns into a real value after some time:

https://user-images.githubusercontent.com/1623053/236707998-f47b7b5a-a4b3-47fe-9095-98114d02b57d.mov

<br/>

# Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/rust/data-structures/src/circular_vec.rs [hunk 1]
```diff
@@ -0,0 +1,96 @@
+//! Definition of a circular vector, a vector with a constant max size, that if full, keeps its
+//! element in a loop.
+
+use std::collections::VecDeque;
+
+
+
+/// A vector with a constant max size, that if full, keeps its element in a loop.
```
Comment (vitvakatu) [inline lib/rust/data-structures/src/circular_vec.rs]: I don't understand this line. It does not `keep` elements, but rather drops the old ones when the capacity is full, doesn't it?

File: lib/rust/data-structures/src/circular_vec.rs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    pub fn get(&self, index: usize) -> Option<&T> {
+        self.vec.get(index)
+    }
+
+    /// Get a mutable reference to the element at the given index.
+    pub fn get_mut(&mut self, index: usize) -> Option<&mut T> {
+        self.vec.get_mut(index)
+    }
+
+    /// get the last element of the vector, if any.
```
Comment (vitvakatu) [inline lib/rust/data-structures/src/circular_vec.rs]:
```suggestion
    /// Get the last element of the vector, if any.
```

File: lib/rust/ensogl/core/src/debug/monitor/sampler.rs [hunk 3]
```diff
@@ -96,36 +107,37 @@ impl Debug for Sampler {
...
-    /// Check the current value in order to draw it with warning or error if it exceeds the allowed
-    /// thresholds.
+    /// Check the current value in order to draw it with warning or error color if it exceeds the
+    /// allowed thresholds.
     pub fn check(&self, stats: &StatsData) -> ValueCheck {
         let value = self.value(stats);
         ValueCheck::from_threshold(self.warn_threshold, self.err_threshold, value)
     }
 
     /// Minimum size of the size the sampler should occupy in the performance monitor view.
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/debug/monitor/sampler.rs:138]: `size of the size` (not new code, but let's fix it)

File: lib/rust/ensogl/core/src/display/scene.rs [hunk 4]
```diff
@@ -1167,6 +1182,18 @@ impl Scene {
         }
     }
 
+    /// Run the GPU profiler. If the result is [`None`], either the GPU context is not initialized
+    /// ot the profiler is not available at the current platform. In case the resulting vector
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/display/scene.rs]:
```suggestion
    /// or the profiler is not available at the current platform. In case the resulting vector
```

File: lib/rust/ensogl/core/src/debug/stats.rs [hunk 5]
```diff
@@ -164,7 +158,7 @@ macro_rules! emit_if_integer {
     ($other:ty, $($block:tt)*) => ();
 }
 
-/// Emits the StatsData struct, and extends StatsWithTimeProvider with accessors to StatsData
+/// Emits the StatsData struct, and extends Stats with accessors to StatsData
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/debug/stats.rs]:
```suggestion
/// Emits the [`StatsData`] struct, and extends [`Stats`] with accessors to [`StatsData`]
```

File: lib/rust/ensogl/core/src/display/world.rs [hunk 6]
```diff
@@ -42,6 +42,24 @@ pub use crate::display::symbol::types::*;
...
+// === Constants ===
+// =================
+
+/// The number of frames that need to be rendered slow/fast before the resolution mode is switched
+/// to low/high one.
+const FRAME_COUNT_CHECK_FOR_SWITCHING_RESOLUTION_MODE: usize = 8;
+
+/// The time threshold for switching to low resolution mode. It will be used on platforms which
+/// allow proper GPU time measurements (currently only Chrome).
+const LOW_RESOLUTION_MODE_GPU_TIME_THRESHOLD: f64 = 1000.0 / 30.0;
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/display/world.rs]: What are the units of this value?

**Review by kazcw — APPROVED** [review]
I have one concern: If the user's hardware renders slower than the slow-frame threshold in high-resolution mode, but faster than the slow-frame threshold in low-resolution mode, would we switch modes every 8 frames?

**Comment by vitvakatu** [comment]
## QA Report 🔴 

Opening the performance monitor (`ctrl+alt+~`) with open DevTools immediately triggers unwrap: 

https://github.com/enso-org/enso/pull/6595/files#diff-9d7b5a2d329a89fe5b9eb16627c503593a7db720088eb79f993d1e58bd4828b6R693

Everything else looks fine, I didn't manage to get a significant FPS drop to trigger the downscaling, though.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/6595">Dynamic app resampling and better performance measurements. by wdanilo · Pull Request #6595 · enso-org/enso</a></strong></div><div>Pull Request Description
This PR introduces several new tools for GPU-related performance measurements and a new, low-resolution rendering mode which should increase the GUI speed on old, weak hard...</div></blockquote>

**Comment by kazcw** [comment]
I just tested this on the 2020 M1 Air. No blockers, other than the same panic Ilya has encountered.
- GPU time shows as N/A. Maybe the API isn't supported on this machine's drivers.
- I don't think the reduced-pixel-ratio is threshold is reached on this hardware. FPS rarely goes below 30 for more than one consecutive frame, no matter what I'm doing.
- It would be nice to have a chart in the performance panel showing pixel-ratio history. Not essential though, could be added in future.

Side notes on the Air, since this is my first performance testing on it: It's not a FPS problem. We're hitting reasonable frame times under all workloads. The application feels slow because the component browser is reacting to hover changes slowly. The faster I pass over the entries with the mouse, the farther it lags behind. This indicates that events triggered by the mouseover are queuing, and we're trying to process all of them even if they are related to outdated inputs. If we remove whatever mechanism is causing hover-initiated events to queue and only try to draw whatever is currently appropriate, that will fix the sluggishness on this machine.

**Comment by wdanilo** [comment]
@kazcw thanks for all the information. I will fix the things and reply more later. For now just a short note – as you are working on lowering draw call amount, let's finish this first. Then, having these machines, let's carefully investigate all slowdowns (probably CPU-related) and let's focus on fixing them. I'll be doing that starting later today – I'll probably start with the issue with component browser.

**Comment by sylwiabr** [comment]
@wdanilo what is the status here?

**Comment by wdanilo** [comment]
@sylwiabr ready for re-testing!

**Comment by vitvakatu** [comment]
# QA Report 🟢 

Looks good to me!

I'm unsure if it is correct, but I only see `CPU + Idle` and `GPU` timings if the dev-tools console is opened. Otherwise, they show `N/A`.

**Comment by sylwiabr** [comment]
@wdanilo can we merge it?

**Comment by wdanilo** [comment]
Yes, sorry Sylwia, I stared doing another task and this slipped somehow. I need to refresh it, I will do it before Monday.
