### PR TITLE
`HelloWorldCacheTest` CI failures fix + more logging

### LINKED ISSUE #11196: Could not load the cache metadata at `Hello_World.meta` in `HelloWorldCacheTest`
The PR makes simple build.sbt cleanups yet we get an assertion failure in `runtime-integration-tests`:

```
 INFO ide_ci::program::command: sbt ℹ️ [error] Test org.enso.interpreter.caches.HelloWorldCacheTest.loadingHelloWorldTwiceUsesCaching failed: java.lang.AssertionError: Contains hello world:
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::Compiler] FINE: Parsing module [Hello_World].
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::Cache] FINE: Could not load the cache metadata at [***\Hello_World.meta].
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::Cache] FINE: Could not load the cache metadata at [***\Hello_World.meta].
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::SerializationPool] FINE: Unable to load a cache for module [Hello_World].
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::SerializationPool] FINE: Deserializing module Hello_World from IR file: false
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::Compiler] FINE: Loading module [Hello_World] from source.
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::Compiler] FINE: Generating code for module [Hello_World].
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::SerializationPool] FINE: Requesting serialization for module [Hello_World].
 INFO ide_ci::program::command: sbt ℹ️ [error] Hello World
 INFO ide_ci::program::command: sbt ℹ️ [error] [enso::SerializationPool] FINE: Running serialization for module [Hello_World]., took 2.205 sec
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.interpreter.caches.HelloWorldCacheTest.loadingHelloWorldTwiceUsesCaching(HelloWorldCacheTest.java:26)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at java.lang.reflect.Method.invoke(Method.java:580)
 INFO ide_ci::program::command: sbt ℹ️ [error]     ...
 INFO ide_ci::program::command: sbt ℹ️ [info] Test run org.enso.interpreter.caches.HelloWorldCacheTest finished: 1 failed, 0 ignored, 1 total, 2.205s
 ```
 https://github.com/enso-org/enso/actions/runs/11057308790/job/30720802542?pr=11170#step:7:6304

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Closes #11196 by adding more logging and delivering reasons (via `IOException` and its message) explaining why cache loading failed. Very likely a6b67e4c469f2d985d65a75c249f3e25ebc7820b - e.g. `RuntimeOptions.WAIT_FOR_PENDING_SERIALIZATION_JOBS, "true"` fixes #11196 at the end.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests continue to pass.
- [x] Unit test output in case of failure improved

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java [hunk 1]
```diff
@@ -487,11 +487,18 @@ public boolean deserializeModule(Compiler compiler, CompilerContext.Module modul
...
-    if (pool.isWaitingForSerialization(module.getName())) {
-      pool.abort(module.getName());
+    var moduleName = module.getName();
+    var awaitingSerialization = pool.isWaitingForSerialization(moduleName);
+    logSerializationManager(
+        Level.FINE,
+        "deserializing module [{0}]. Awaiting serialization: {1}",
+        moduleName,
+        awaitingSerialization);
+    if (awaitingSerialization) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:497]: - possibly one of the reasons behind #11196 failure is `awaitingSerialization` being `false`
- let's log its value so it shows in the test output next time

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 2]
```diff
@@ -318,11 +305,11 @@ private Optional<T> loadCacheFrom(
    * @param path location of the serialized metadata
    * @return deserialized metadata, or [[None]] if invalid
    */
-  private Optional<M> loadCacheMetadata(TruffleFile path, TruffleLogger logger) throws IOException {
+  private M loadCacheMetadata(TruffleFile path, TruffleLogger logger) throws IOException {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: The problem with `Optional` is that it doesn't specify reason why it is `Optional.empty()`. To track the `HelloWorldCacheTest` random CI failures down, we'd rather understand the reasons why a cache file isn't loaded, thus:
- returning _non-null_ value from the method or
- throwing `IOException` with a message describing the reason why we cannot load the cache file

Hopefully this uncovers the reason why the `HelloWorldCacheTest` randomly fails.

Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: That's pretty much a definition of `Either`

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java [hunk 3]
```diff
@@ -191,65 +192,64 @@ public final Optional<T> load(EnsoContext context) {
...
                         logLevel,
                         "Using cache for ["
                             + logName
                             + " at location ["
                             + toMaskedPath(roots.localCacheRoot()).applyMasking()
                             + "].");
-                    return loadedCache;
+                    return Optional.of(localCache);
+                  } catch (IOException localEx) {
+                    logCacheLoadFailure(
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:218]: The loading first tries:
- global cache
- if that fails, it remembers the `globalEx` and
- tries local cache
- if that fails, it logs both exceptions

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: Right, that is true. I read an article arguing in favor of `Either` over `Option` as the former can provide reason for the failure. However we are in Java and I believe the Java equivalent of `Either` are [checked exceptions](http://wiki.apidesign.org/wiki/Either).

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: - technically we need just a6b67e4c469f2d985d65a75c249f3e25ebc7820b to fix #11196 
- Java doesn't have `Either` as far as I know
- rewriting to `scala.Either` goes opposite direction than we are moving to
- I can back out 691136dc6cb5924a3c86ba60e3f6fd75dd8b5d65 to smooth the review process

Vote +1 if you want to me to back 691136dc6cb5924a3c86ba60e3f6fd75dd8b5d65 out, but you approve the rest of changes. Thank you.

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: I am in favor of the plain old Java style - return `null` or the object or throw `IOException`. Just update the docs please.

**Review by Akirathan — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: Done as:
```diff
-   * @return the cached data if available, otherwise an empty [[Optional]].
+   * @return the cached data if available, otherwise throw exception
```

Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:312]: Fair enough. We are in Java and Java is no friends with FP.

File: engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java (hunk 3 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:218]: I kind of had an impression we wanted the opposite order, i.e. local first and only on failure the global one?
It also sounds a bit more intuitive with other configurations I'm aware of.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java:218]: - reported as #12027
- the bug is still open
- it was reported after the work on this PR was finished
- as such this PR doesn't reflect/fixes the #12027 bug
