### PR TITLE
Wip/farmaazon/chromatic in package tests

### LINKED ISSUE #11710: Screenshot testing in package tests.
Currently, we have no tests which would actually check the edges positions and graph layout. To catch regressions in those, we may extend the package test a bit (to add collapsing and entering nodes there) add making graph screenshots and upload this to chromatic.

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #11710

Improved visual stability of electron testing scenario, reworked the electron-based test definition to use API that's compatible with chromatic snapshots. Added upload of snapshots, though they are not yet verified as required for PRs due to still existing visual stability issues.

### CODE REVIEW

File: app/ide-desktop/client/tests/electronTest.ts [hunk 1]
```diff
@@ -1,57 +1,95 @@
...
+  },
+  projectsDir: async function ({ testRunId }, use) {
+    const projectsDir = path.join(os.tmpdir(), 'enso-test-projects', testRunId)
+    await use(projectsDir)
+  },
+
+  /**
+   * Setup for all tests: checks if and where electron exec is.
+   * @throws when no Enso package could be found.
+   */
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/electronTest.ts]: Is this docs still relevant? To me all fields (`testRunId`, `projectsDir`) have something from being "setup"

File: app/ide-desktop/client/tests/localWorkflow.spec.ts [hunk 2]
```diff
@@ -60,22 +80,15 @@ electronTest('Local Workflow', async ({ page, app, projectsDir }) => {
   await expect(writeNode.locator('.TableVisualization')).toContainText('output_ensodryrun')
 
   expect(await fs.readdir(PROJECT_PATH)).not.toContain(OUTPUT_FILE)
-
+  await expect(page.locator('.GraphEditor .GraphNode.pending')).toHaveCount(0)
   // Press `Write once` button.
   await writeNode.locator('.More').click()
   await writeNode.getByTestId('recompute').click()
+  await page.mouse.move(0, 0) // Avoid showing a tooltip
+  await expect(page.locator('.GraphEditor .GraphNode.pending')).toHaveCount(0)
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/localWorkflow.spec.ts:120]: This check may pass before finishing execution, because we may run this check before the first "pending" updates arrive from the engine.

We may add expectation to have _some_ node non-pending first, but I'm not sure how it would behave in really fast computations.

File: app/ide-desktop/client/tests/localWorkflow.spec.ts [hunk 3]
```diff
@@ -60,22 +80,15 @@ electronTest('Local Workflow', async ({ page, app, projectsDir }) => {
...
-    await expect(writeNode.locator('.TableVisualization')).toContainText(OUTPUT_FILE)
-  } catch {
-    // TODO[ao]
-    // The above check is flaky, because sometimes the additional engine run overrides node output back to "dry run".
-    // To confirm if this should be expected.
-    console.error(
-      'Didn\'t see the visualization update after "Write once" action; assuming it\'s already done',
-    )
-  }
+  await expect(writeNode.locator('.TableVisualization')).toContainText(OUTPUT_FILE)
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/localWorkflow.spec.ts:123]: Given the above, I still think this check is flaky and keep the try/catch.

File: app/ide-desktop/client/tests/localWorkflow.spec.ts [hunk 4]
```diff
@@ -106,6 +119,9 @@ electronTest('Local Workflow', async ({ page, app, projectsDir }) => {
   expect(projectFiles).toContain('images')
   const images = await fs.readdir(pathModule.join(PROJECT_PATH, 'images'))
   expect(images).toContain('image.png')
+  await expect(page.locator('.GraphEditor .GraphNode.pending')).toHaveCount(0)
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/localWorkflow.spec.ts:158]: This is a strange check - we don't touch code after last such check - if it's needed, please add info why.

File: package.json [hunk 5]
```diff
@@ -164,6 +164,9 @@
           "@types/ws": "*"
         }
       }
+    },
+    "patchedDependencies": {
+      "@chromatic-com/playwright": "patches/@chromatic-com__playwright.patch"
```
Comment (farmaazon) [inline package.json:171]: Shouldn't we set _exact version_ requirement on chromatic dependency if we patch it?

File: app/ide-desktop/client/tests/electronTest.ts [hunk 6]
```diff
@@ -1,57 +1,95 @@
...
+      value: function browser() {
+        return (
+          __browserFn.apply(this) ?? {
+            browserType: () => ({
+              name: () => 'chromium',
+            }),
+          }
+        )
+      },
+    })
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/electronTest.ts]: 1. Why double underscore?
2. Why this is needed? Could you add a comment?

**Review by farmaazon — COMMENTED** [review]
This PR adds over 1000 more lines to pnpm-lock.yaml. After reviewing it briefly, I discovered duplicated webpack (different versions) and duplicated storybook (same versions but different deps). May you take a look if we could improve that?

File: app/ide-desktop/client/tests/localWorkflow.spec.ts (hunk 3 above)
Comment (Frizi) [reply app/ide-desktop/client/tests/localWorkflow.spec.ts:123]: I don't think this is flaky anymore, as I didn't observe that happening. If there is a problem, we have to fix it instead of masking it out through this catch, because it influences the snapshot anyway and would cause instability there.

File: package.json (hunk 5 above)
Comment (Frizi) [reply package.json:171]: Pinned the version to `0.10.2`.

**Comment by Frizi** [comment]
> I discovered duplicated webpack (different versions) and duplicated storybook (same versions but different deps).

I don't see that anymore, there is only one version of webpack (5.97.1) and storybook (8.5.0) in the lockfile. There are multiple "snapshots", due to different dependency chains asking for them using slightly different constraints, but they are resolved to the same actual dependency.

File: app/ide-desktop/client/tests/localWorkflow.spec.ts (hunk 2 above)
Comment (Frizi) [reply app/ide-desktop/client/tests/localWorkflow.spec.ts:120]: There are cases when pending status don't show up at all, so I don't know how to adjust that. This check did stabilize the cases where nodes were still pending for a split second after the run, but I didn't see the inverse problem in practice.

File: app/ide-desktop/client/tests/localWorkflow.spec.ts [hunk 7]
```diff
@@ -148,6 +148,10 @@ test('Local Workflow', async ({ page, app, projectsDir }, testInfo) => {
   expect(projectFiles).toContain('images')
   const images = await fs.readdir(pathModule.join(PROJECT_PATH, 'images'))
   expect(images).toContain('image.png')
+
+  // Ensure that the graph is stable before doing the snapshot. Some nodes might still
+  // be pending at the time the image upload finishes, which can cause the snapshot to
+  // be unstable.
```
Comment (farmaazon) [inline app/ide-desktop/client/tests/localWorkflow.spec.ts:157]: I assumed before, that nodes cannot become pending after docs change, but if it's not true, then this comment perhaps is not needed. (Or just briefly mention, that pasting image might have turned some nodes pending again).

**Review by farmaazon — APPROVED** [review]

**Review by somebody1234 — APPROVED** [review]

**Review by AdRiley — APPROVED** [review]
