### PR TITLE
Fix reconnecting after hibernation on Windows

### LINKED ISSUE #11716: Duplicate context creation on re-connection
Upon successfully addressing #11389 in #11712, suspend no longer leads to app crash on Windows.
Unfortunately re-connection appears to fail as GUI appears to re-create context more than once, which is (correctly) rejected by Language Server.

Screenshot from the exchange:
Zrzut ekranu (9)

Not reproducible on Linux.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #11716

The previoud implementation of restoring execution context assumed, that any synchronization in progress on connection close will fail - but actually if the synchronization just waited for executionContext/create, it might be successfull and effective after reconnecting.

Also, show "Language Server connection lost" when the actual language server connection is lost, and dismiss the message on reconnect.

### Important Notes

The hibernation still does not work properly - connection to Project Manager is not restored.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/GraphEditor/toasts.ts [hunk 1]
```diff
@@ -16,9 +16,10 @@ export function useGraphEditorToasts(projectStore: ProjectStore) {
   toastStartup.show('Initializing the project. This can take up to one minute.')
   projectStore.firstExecution.then(toastStartup.dismiss)
 
-  useEvent(document, 'project-manager-loading-failed', () =>
+  projectStore.lsRpcConnection.on('transport/closed', () =>
     toastConnectionLost.show('Lost connection to Language Server.'),
   )
+  projectStore.lsRpcConnection.on('transport/connected', () => toastConnectionLost.dismiss())
```
Comment (Frizi) [inline app/gui/src/project-view/components/GraphEditor/toasts.ts]: Those events needs a corresponding `off` call on scope dispose.

File: app/gui/src/project-view/stores/project/executionContext.ts [hunk 2]
```diff
@@ -487,25 +495,55 @@ export class ExecutionContext extends ObservableV2<ExecutionContextNotification>
...
-      this.emit('newVisualizationConfiguration', [new Set(this.visualizationConfigs.keys())])
-      await syncVisualizations()
-      this.emit('visualizationsConfigured', [
-        new Set(state.status === 'created' ? state.visualizations.keys() : []),
-      ])
-      if (this.syncStatus === SyncStatus.SYNCING) {
-        this.syncStatus = SyncStatus.SYNCED
+      this.syncStatus = SyncStatus.CREATING
+      try {
+        if (this.abort.signal.aborted) return newState
```
Comment (Frizi) [inline app/gui/src/project-view/stores/project/executionContext.ts:528]: Should we introduce a separate `syncStatus` for aborted? It's not really `CREATING` anymore when that branch hits.

File: app/gui/src/project-view/stores/project/executionContext.ts [hunk 3]
```diff
@@ -487,25 +495,55 @@ export class ExecutionContext extends ObservableV2<ExecutionContextNotification>
...
+        const createResult = await create()
+        if (!createResult.ok) return newState
+        this.syncStatus = SyncStatus.SYNCING
```
Comment (Frizi) [inline app/gui/src/project-view/stores/project/executionContext.ts:533]: I know this state kinda mimicks what was already there, but I think the status logic is still problematic. The `sync` method can be called at any point (because of `pushItem` being callable through external API), and it will queue another sync if the state is not `QUEUED` (and also change the state to `QUEUED` again, masking the ongoing `CREATING`/`SYNCING` state). That means there might be multiple sync promises running in parallel, slightly out of phase. I believe that throws off a lot of assumptions that this code makes.

**Review by Frizi — CHANGES_REQUESTED** [review]

File: app/gui/src/project-view/stores/project/executionContext.ts (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/project-view/stores/project/executionContext.ts:528]: In the finally block it will be set to NOT_SYNCED.

**Review by Frizi — APPROVED** [review]

**Comment by farmaazon** [comment]
I still need to test it: let nobody attach "Ready to merge" label too eagerly!

**Comment by farmaazon** [comment]
Tested: the fix works fine.
