### PR TITLE
Extend the range of int/float arguments to outside the range of Java `long`, in `ceil`, `floor`, and `truncate`

### LINKED ISSUE #10904: `ceil`, `floor`, and `truncate` are incorrect on `Integer`s and `Float`s outside the java `Long` range (in-memory)
The `Integer` failure comes from the fact that large integers are treated as value type `Decimal` in all backends; the Decimal implementation does not handle `BigIntegerStorage`.
The `Float` failure comes from the assumption that the result will be a long, and not `BigInteger`, in `UnaryRoundOperation`.

### PR DESCRIPTION
**Pull request by GregoryTravis**
Unifies `UnaryRoundOperation` and `UnaryDecimalRoundOperation`. Uses an `InferredBuilder` for constructing output columns for `Float` input columns.

Closes #10904.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by GregoryTravis** [comment]
Benchmarks look good after adding `InferredIntegerBuilder` instead of `InferredBuilder`.

File: std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    } else if (o instanceof BigInteger bi) {
+      retypeToBigIntegerMaybe();
+      bigIntegerBuilder.append(bi);
+    } else if (o instanceof Long lng) {
+      if (bigIntegerBuilder != null) {
+        bigIntegerBuilder.append(BigInteger.valueOf(lng));
+      } else {
+        longBuilder.append(lng);
+      }
+    }
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java]: Note that in the `LongBuilder*` classes this is rather done by: 
```
Long x = NumericConverter.tryConvertingToLong(o);
```

That's because it was possible in some cases (not sure exactly which tbh) to have `Short` or other Java integer types flying around. And more importantly, because adding `2.0` to an integer builder used to _not_ change its type to decimal - it was kept as integers if the floating point value was a whole integer.

Comment (radeusgd) [reply std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java]: Also I see no `else` branch here.

What happens if someone tries to append a non-numeric value here? It looks that `currentSize` is incremented but the underlying builder is not really updated. That seems to break the 'synchronization' between the `currentSize` and the underlying builder. Note that in `InferredBuilder` every increment of `currentSize` is associated with _some_ append operation on the `currentBuilder` - the only exception is if `currentBuilder == null` - but then we explicitly ensure the synchronization in `initBuilderFor` by the line `currentBuilder.appendNulls(currentSize);`. I imagine this builder would need a similar logic.

Comment (radeusgd) [reply std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java]: There is a lot of edge cases here, `InferredBuilder` had a few bugs related to this complexity. If we are adding a separate builder that has similar but differing logic, I think it would be good to add some more tests for edge cases in cases where this builder is being used - e.g. starting with many `Nothing` results first and only later getting actual numbers, checking what happens if a few values are long and only later we get a big integer etc.

Comment (radeusgd) [reply std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java]: > Note that in the `LongBuilder*` classes this is rather done by:
> 
> ```
> Long x = NumericConverter.tryConvertingToLong(o);
> ```
> 
> That's because it was possible in some cases (not sure exactly which tbh) to have `Short` or other Java integer types flying around. And more importantly, because adding `2.0` to an integer builder used to _not_ change its type to decimal - it was kept as integers if the floating point value was a whole integer.

As for this comment - I realize that this may not be necessary here if the builder is used only for the round operations and we assume it only takes Long or BigInteger. But then we should throw an exception if an unexpected value is appended - so that if anyone violates this assumption they will know this builder does not support it / would need to be extended.

Comment (GregoryTravis) [reply std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java]: I changed it to use `tryConvertingToLong` and throw an exception if the type is wrong.

File: std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java [hunk 2]
```diff
@@ -36,29 +63,34 @@ public boolean canApply(ColumnStorage storage) {
...
+      return storage;
     }
 
     return super.apply(storage, problemAggregator);
   }
 
   @Override
   protected void applyObjectRow(
-      Object value, LongBuilder builder, MapOperationProblemAggregator problemAggregator) {
+      Object value, Builder builder, MapOperationProblemAggregator problemAggregator) {
```
Comment (jdunkerley) [inline std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java:76]: given we know the builder is an `InferredIntegerBuilder`, we could add an appendLong method which avoid the boxing.
(and yes we should test performance of the whole boxing game).

**Review by jdunkerley — APPROVED** [review]

**Review by AdRiley — APPROVED** [review]

File: std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java (hunk 2 above)
Comment (GregoryTravis) [reply std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java:76]: Given that this implementation is benchmarking well, I would rather not add yet another specialization path to this, since we're expecting to refactor it soon.
