### PR TITLE
Set edition when starting language server

### LINKED ISSUE #5018: Engine version mismatch in YAML file causes project to fail on open
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184303109).
<hr />

On the mismatch of installed engine version with one specified in YAML file:
- we should try to open the project 
- with information logged and displayed to the user

``[error] [2023-01-24T07:35:33.718Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Failed to initialize the resources. org.enso.editions.EditionResolutionError$CannotLoadEdition: Cannot load edition [2022.7.1]: The edition was not found.``

Discussions:
https://discord.com/channels/401396655599124480/1064989125314347098

https://discord.com/channels/401396655599124480/1067350451718201375

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (2023-01-30):

**Progress:** Started working on the task. Was able to reproduce the issue. It happens because the edition in question can be found by the project-manager but cannot be loaded during the language server startup. Started to debug the logic that loads the revisions. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Jan 30, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** Continue working on the task. Tried to look into the issue of loading the revision but it looks like that such revision does not exist indeed. Started investigating the revision manager to see how to load the fallback. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 1, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2023-02-01):

**Progress:** Continue working on the task. Found that the fallback logic exists in the project manager but does not work for some reason. So far it looks like the issue is with the engine release provider. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 1, 2023)
<hr />
**Dmitry Bushev** reports a new **🔴 DELAY** for today (2023-02-02):

**Summary:** There is **1 day** delay in implementation of the [Engine version mismatch in YAML file causes project to fail on open (#184303109) task](https://www.pivotaltracker.com/story/show/184303109).
It **will cause 1 day delay** for the delivery of this weekly plan.

**Delay Cause:** Investigation of the issue took longer than I expected. (Enso Bot - Feb 2, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2023-02-02):

**Progress:** Continue working on the task. Added the edition override to the language server paramters that will be used to configure the execution context of the language server. Did manual testing in the Enso app. Created the PR It should be finished by 2023-02-02.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 2, 2023)
<hr />

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

When the `project.yaml` specifies an unknown edition, the project is started with the fallback edition (current engine version). It works this way:

- IDE sends project/open request to project manager (specifying only which project to open)
- project manager resolves the project edition (based on `project.yaml`) or selects the fallback if the requested edition cannot be loaded
- project manager starts the language server specifying the edition with the `--server-edition` command line parameter
- language server specifies the correct edition when creates the runtime context

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: engine/runner/src/main/scala/org/enso/runner/Main.scala [hunk 1]
```diff
@@ -183,6 +184,13 @@ object Main {
       .longOpt(LANGUAGE_SERVER_PROFILING_EVENTS_LOG_PATH)
       .desc("The path to the runtime events log file.")
       .build()
+    val lsEdition = CliOption.builder
+      .hasArg(true)
+      .numberOfArgs(1)
+      .argName("edition")
+      .longOpt(LANGUAGE_SERVER_EDITION)
+      .desc("Override edition specified in the project config.")
```
Comment (JaroslavTulach) [inline engine/runner/src/main/scala/org/enso/runner/Main.scala]: What is the exact use-case for this option? Can we have some documentation explain how people are supposed to use it and why?

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala [hunk 2]
```diff
@@ -108,7 +108,10 @@ object ExecutorWithUnlimitedPool extends LanguageServerExecutor {
         .flatMap(path =>
           Seq("--server-profiling-events-log-path", path.toString)
         )
+    val serverEdition =
+      Seq("--server-edition", descriptor.engineVersion.toString())
```
Comment (JaroslavTulach) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala]: Why is the option called `--server-edition`? I don't think it explains its purpose. At least I am not getting it.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
I need more documentation or at least explanation. This issue is called _"Set edition when starting language server"_ - where that is done? Is it done all the time? Why do we need an edition in `package.yaml` at all?

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala (hunk 2 above)
Comment (4e6) [reply lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala]: All language server related options are prefixed with the `server`. Maybe `--server-override-edition` will be more clear

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 1 above)
Comment (4e6) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: The edition specified in the project config can be unavailable which leads to a failure when opening a project. This option allows to workaround the failure by supplying the fallback version.

Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: However opening a project with different edition may lead to "failures when opening a project" - different editions have different language features and different standard libraries APIs.

>  workaround the failure by supplying the fallback version.

Is it correct from a UX perspective?
- You start the IDE
- select a project to open
- it says "wrong edition"
- you shut the IDE down
- start the IDE with new option (which one, btw.?)
- and then the project opens without an error

I don't find such workflow satisfactory from UX.

Comment (4e6) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: These options are passed to the language server when you select the project in IDE. They are not user-facing

Comment (hubertp) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: > However opening a project with different edition may lead to "failures when opening a project" - different editions have different language features and different standard libraries APIs.

I would say this is a valid point. Can we make sure that IDE is aware of this override and can report this to the user? Or at least that we log this in our logs (I didn't see anything in this PR)?Otherwise I'm afraid one of us will be chasing this ghost, being unable to reproduce.

Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala]: >  IDE is aware of this override and can report this to the user?

Essential! IDE has to tell the user that wrong edition is used to open the project. E.g. the message needs to be shown.

Ideally it would be a question: _"go on and open with Engine XYZ or give up?"_ - before I can review the API (well CLI) changes, I need to understand the workflow. Can we start from describing the UX and only then do API changes?

CCing @jdunkerley

**Comment by JaroslavTulach** [comment]
#5018 requests:

> On the mismatch of installed engine version with one specified in YAML file:
>
>    we should try to open the project
>    with information logged and displayed to the user

I have feeling this PR only implements the first part - e.g. _"try to open the project"_. I don't see any code that would communicate with the user. Moreover I question the need for all the new switches given the _"try to open the project"_ is unconditional.

I have just tried to provide a QA today morning, but when I:
- create new project
- close the IDE
- remove `edition` line from `package.yaml`
- restart the IDE and open the project

I am still seeing the same behavior:

IDE still complains about wrong engine version

The engine process seems to be started with `--server-edition 0.0.0-dev` - but I don't see any improvement in the behavior. I am not able to provide QA. Someone else has to.

**Comment by JaroslavTulach** [comment]
Note for (future) myself: The stacktrace that yields the `CannotLoadEdition` exception when the problem happens is:
```
"scala-execution-context-global-25"
	at org.enso.editions.EditionResolutionError$CannotLoadEdition.<init>(EditionResolutionError.scala:14)
	at org.enso.editions.EditionResolver.$anonfun$resolveParent$1(EditionResolver.scala:149)
	at org.enso.editions.EditionResolver$$Lambda$3170.1192780988.apply
	at scala.util.Either$LeftProjection.map(Either.scala:614)
	at org.enso.editions.EditionResolver.resolveParent(EditionResolver.scala:149)
	at org.enso.editions.EditionResolver.resolveEdition(EditionResolver.scala:40)
	at org.enso.editions.EditionResolver.resolve(EditionResolver.scala:30)
	at org.enso.editions.updater.EditionManager.resolveEdition(EditionManager.scala:26)
	at org.enso.compiler.PackageRepository$.initializeRepository(PackageRepository.scala:686)
	at org.enso.compiler.PackageRepository.initializeRepository(PackageRepository.scala)
	at org.enso.interpreter.runtime.EnsoContext.initialize(EnsoContext.java:159)
	at org.enso.interpreter.EnsoLanguage.initializeContext(EnsoLanguage.java:160)
	at org.enso.interpreter.EnsoLanguage.initializeContext(EnsoLanguage.java:64)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3514)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:280)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:710)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1416)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1425)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.initializeLanguage(PolyglotContextDispatch.java:58)
	at org.graalvm.polyglot.Context.initialize(Context.java:576)
	at org.enso.languageserver.boot.resource.TruffleContextInitialization.$anonfun$init$1(TruffleContextInitialization.scala:28)
```

**Review by JaroslavTulach — APPROVED** [review]
One changed file only!? That's simpler.
