### PR TITLE
Fix serialization of FQNs

### LINKED ISSUE #5037: Usage of fully qualified names causes the engine to crash.
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184390155).
<hr />

When a node is added or modified to contain a fully qualified name, the engine crashes and a project needs to be restarted. If the file was saved with the fully qualified name in script, the project immediately crashes on startup as well.

Minimal code example :
```
main = 
    Standard.Base.Data.Boolean.True
```

Engine logs after fresh startup:
```
[info] [2023-02-03T14:20:03.797Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-03T14:20:03.8Z] [org.enso.projectmanager.service.versionmanagement.ControllerInterface] Installed Enso Engine 2023.1.1-nightly.2023.2.3.
[info] [2023-02-03T14:20:03.836Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine 2023.1.1-nightly.2023.2.3 has already been installed by a different process.
[info] [2023-02-03T14:20:03.837Z] [org.enso.projectmanager.service.versionmanagement.ControllerInterface] The engine 2023.1.1-nightly.2023.2.3 has already been installed by a different process.
[info] [2023-02-03T14:20:03.891Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-03T14:20:03.891Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server [LanguageServerDescriptor(language-server-83952581-b1bc-4e4f-889c-116286530bb3,0cd25208-695e-41a6-a19e-5417b3225d74,C:\Users\Frizi\enso\projects\ReproProject,NetworkConfig(127.0.0.1,49152,65535),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@24ddb377,2023.1.1-nightly.2023.2.3,JVMSettings(None,List()),false,None,None,None,Future(Success(Some(ws://localhost:60274/))))].
[info] [2023-02-03T14:20:03.892Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:63199, binary:127.0.0.1:50301].
[info] [2023-02-03T14:20:03.894Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1-nightly.2023.2.3] found.
[info] [2023-02-03T14:20:03.895Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-03T14:20:03.95Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.0-java11].
[info] [2023-02-03T14:20:04.686Z] [org.enso.languageserver.boot.LanguageServerComponent] Starting Language Server...
[info] [2023-02-03T14:20:04.693Z] [org.enso.languageserver.boot.MainModule] Initializing main module of the Language Server from [LanguageServerConfig(127.0.0.1,63199,50301,0cd25208-695e-41a6-a19e-5417b3225d74,C:\Users\Frizi\enso\projects\ReproProject,ProfilingConfig(None,None,None),language-server,scala.concurrent.impl.ExecutionContextImpl$$anon$3@4b3ed2f0[Running, parallelism = 24, size = 2, active = 1, running = 1, steals = 0, tasks = 0, submissions = 0]), info]
[info] [2023-02-03T14:20:05.775Z] [org.enso.languageserver.runtime.RuntimeConnector] Starting the runtime connector.
[info] [2023-02-03T14:20:05.775Z] [org.enso.languageserver.runtime.RuntimeConnector] Runtime connector established connection with the message endpoint [com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy@791d12].
[info] [2023-02-03T14:20:05.896Z] [org.enso.languageserver.text.BufferRegistry] Starting initialization.
[info] [2023-02-03T14:20:05.903Z] [org.enso.languageserver.search.SuggestionsHandler] Starting suggestions handler from [Config(projectContentRoot=***\ReproProject, fileManager=FileManagerConfig(3 seconds,24), vcsManager=VcsManagerConfig(5 seconds,3 seconds), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***\ReproProject)), org.enso.searcher.sql.SqlSuggestionsRepo@5a4eebac, org.enso.searcher.sql.SqlVersionsRepo@2b331c8].
[info] [2023-02-03T14:20:06.347Z] [org.enso.languageserver.boot.MainModule] Main module of the Language Server initialized with config [Config(projectContentRoot=***\ReproProject, fileManager=FileManagerConfig(3 seconds,24), vcsManager=VcsManagerConfig(5 seconds,3 seconds), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***\ReproProject))].
[info] [2023-02-03T14:20:06.403Z] [org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:63199, binary:127.0.0.1:50301
[info] [2023-02-03T14:20:06.628Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted [LanguageServerConnectionInfo(127.0.0.1,63199,50301)].
[info] [2023-02-03T14:20:06.689Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Initializing resources.
[info] [2023-02-03T14:20:06.69Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initializing directories...
[info] [2023-02-03T14:20:06.691Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initialized directories.
[info] [2023-02-03T14:20:06.693Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing suggestions repo [***\suggestions.db]...
[info] [2023-02-03T14:20:06.898Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized Suggestions repo [***\suggestions.db].
[info] [2023-02-03T14:20:06.899Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing versions repo [***\suggestions.db]...
[info] [2023-02-03T14:20:06.9Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: suggestions repo initialized.
[info] [2023-02-03T14:20:06.907Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized Versions repo [***\suggestions.db].
[info] [2023-02-03T14:20:06.908Z] [org.enso.languageserver.text.BufferRegistry] Initiaized.
[info] [2023-02-03T14:20:06.908Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initializing Runtime context...
[info] [2023-02-03T14:20:08.011Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initialized Runtime context.
[info] [2023-02-03T14:20:08.011Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: Truffle context initialized.
[info] [2023-02-03T14:20:08.011Z] [org.enso.languageserver.protocol.json.JsonConnectionController] RPC session initialized for client [a2233080-5534-4504-9852-16748fc88bfd].
[info] [2023-02-03T14:20:08.042Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Data session initialized for client: a2233080-5534-4504-9852-16748fc88bfd [127.0.0.1:60393].
[info] [2023-02-03T14:20:08.066Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: project name is updated to [ReproProject].
[info] [2023-02-03T14:20:08.175Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
[info] [2023-02-03T14:20:08.218Z] [org.enso.languageserver.search.SuggestionsHandler] Verifying: got verification response.
[info] [2023-02-03T14:20:08.24Z] [org.enso.languageserver.search.SuggestionsHandler] Verified.
[info] [2023-02-03T14:20:08.607Z] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for [path:Path(0cd25208-695e-41a6-a19e-5417b3225d74,Vector(src, Main.enso)), client:a2233080-5534-4504-9852-16748fc88bfd].
[info] [2023-02-03T14:20:09.178Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Visualization @ 2023.1.1-nightly.2023.2.3 at [***\2023.1.1-nightly.2023.2.3].
[info] [2023-02-03T14:20:09.247Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Base @ 2023.1.1-nightly.2023.2.3 at [***\2023.1.1-nightly.2023.2.3].
[info] [2023-02-03T14:20:09.393Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Table @ 2023.1.1-nightly.2023.2.3 at [***\2023.1.1-nightly.2023.2.3].
Exception in thread "Thread-9" java.lang.IllegalStateException: There is no current context available.
      at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:135)
      at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requireContext(PolyglotContextImpl.java:720)
      at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.createLanguageSystemThread(EngineAccessor.java:1940)
      at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1847)
      at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1813)
      at org.enso.compiler.SerializationManager.$anonfun$pool$1(SerializationManager.scala:54)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:623)
      at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:912)
      at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1005)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at java.base/java.lang.Thread.run(Thread.java:829)
      at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:65)
[error] [2023-02-03T14:20:17.836Z] [org.enso.languageserver.requesthandler.vcs.StatusVcsHandler] Status project request [Number(9)] for [a2233080-5534-4504-9852-16748fc88bfd] failed with: null.
```

## Comments:
 (Paweł Grabarz - Feb 3, 2023)
<hr />
Maybe a duplicate of #184389924  (Hubert Plociniczak - Feb 3, 2023)
<hr />

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Serialization of FQNs' metadata was broken - we attempted to serialiaze concrete modules and that's against the design.

Added a test illustrating the problem which would previously fail during serialization.

Closes #5037 

### Important Notes

It is still hard to discover problems like this because SerializationManager creates system threads; when the exception occurs, it is typically not the real cause. Creating regular threads via `createThread` seems to be problematic for `native-image`. There is a simple workaround for the former but will leave it out for another PR to simplify the review.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+    var compiler = ensoContext.getCompiler();
+    var module = mainModuleOpt.get();
+
+    ctx.enter();
+    var result = compiler.run(module);
+    assertEquals(result.compiledModules().exists(m -> m == module), true);
+    var serializationManager = new SerializationManager(ensoContext.getCompiler());
+    serializationManager.serialize(module, true);
+    Thread.sleep(1000); // Ensure module is serialized
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java]: Can we modify `serialize` to return a future and let the test wait for it? Something like:
```diff
diff --git a/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala b/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
index 973c93a91..36ad0862a 100644
--- a/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
+++ b/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
@@ -15,6 +15,8 @@ import java.util.concurrent.{
 }
 import java.util.logging.Level
 import scala.collection.mutable
+import java.util.concurrent.Future
+import java.util.concurrent.CompletableFuture
 
 class SerializationManager(compiler: Compiler) {
 
@@ -79,10 +81,10 @@ class SerializationManager(compiler: Compiler) {
     * mutated beneath it.
     *
     * @param module the module to serialize
-    * @return `true` if `module` has been scheduled for serialization, `false`
+    * @return Future if `module` has been scheduled for serialization, `null`
     *         otherwise
     */
-  def serialize(module: Module, useGlobalCacheLocations: Boolean): Boolean = {
+  def serialize(module: Module, useGlobalCacheLocations: Boolean): Future[_] = {
     logger.log(
       debugLogLevel,
       s"Requesting serialization for module [${module.getName}]."
@@ -103,12 +105,11 @@ class SerializationManager(compiler: Compiler) {
     )
     if (compiler.context.getEnvironment.isCreateThreadAllowed) {
       isWaitingForSerialization.put(module.getName, task)
-      pool.execute(task)
+      pool.submit(task)
     } else {
       task.run()
+      CompletableFuture.completedFuture(true)
     }
-
-    true
   }
 
   /** Deserializes the requested module from the cache if possible.
```

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java]: I was hesitant to change the API of `SerializationManager` but sounds like a good idea.

File: engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala [hunk 2]
```diff
@@ -82,7 +85,10 @@ class SerializationManager(compiler: Compiler) {
     * @return `true` if `module` has been scheduled for serialization, `false`
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala]: The `@return` tag description no longer fully match the return type.
