### PR TITLE
Report more errors to the user

### LINKED ISSUE #8524: Report errors to the user
Currently, not all errors in our application are clearly reported to the user, what could make our bug reports harder to investigate.

Known missing messages:
* Lost connection with the engine or y-docs server
* Execution failures
* ~~Attaching visualization failures~~ - to be designed and done in a separate task.
* ~~Edits applying errors~~ - also separate task.

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Closes #8524 .

[Screencast from 21-12-23 14:52:20.webm](https://github.com/enso-org/enso/assets/1428930/c1703844-2b17-435b-b8ff-0ef4a858d875)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor.vue [hunk 1]
```diff
@@ -51,24 +52,53 @@ const componentBrowserUsage = ref<Usage>({ type: 'newNode' })
...
   })
   onUnmounted(() => {
-    if (startupToast != null) {
-      toast.remove(startupToast)
-    }
+    toast.dismiss(startupToast)
+  })
+}
+
+function initiConnectionLostToast() {
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue]: typo?

File: app/gui2/package.json [hunk 2]
```diff
@@ -62,6 +62,7 @@
     "semver": "^7.5.4",
     "sucrase": "^3.34.0",
     "vue": "^3.3.4",
+    "vue-react-wrapper": "^0.3.1",
```
Comment (somebody1234) [inline app/gui2/package.json]: i think this should be a `devDependency` (`npm i -D vue-react-wrapper`) right? since it's only used during development (histoire)

File: app/gui2/src/components/GraphEditor.vue [hunk 3]
```diff
@@ -29,9 +29,10 @@ import { colorFromString } from '@/util/colors'
 import { Rect } from '@/util/data/rect'
 import { Vec2 } from '@/util/data/vec2'
 import * as set from 'lib0/set'
+import { toast } from 'react-toastify'
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue:32]: a bit surprised that this works, but i guess it makes sense

File: app/gui2/src/components/GraphEditor.vue [hunk 4]
```diff
@@ -51,24 +52,53 @@ const componentBrowserUsage = ref<Usage>({ type: 'newNode' })
...
+  let connectionLostToast = 'connectionLostToast'
+  document.addEventListener(
+    ProjectManagerEvents.loadingFailed,
+    () => {
+      toast.error('Lost connection to Language Server.', {
+        autoClose: false,
+        toastId: connectionLostToast,
+      })
+    },
+    { once: true },
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue:76]: how did i not know about this option o_o

File: app/gui2/src/components/GraphEditor.vue [hunk 5]
```diff
@@ -51,24 +52,53 @@ const componentBrowserUsage = ref<Usage>({ type: 'newNode' })
...
+  )
+  onUnmounted(() => {
+    toast.dismiss(connectionLostToast)
   })
 }
 
+projectStore.lsRpcConnection.catch((err) => {
```
Comment (somebody1234) [inline app/gui2/src/components/GraphEditor.vue]: you can provide the `catch` callback as the second argument to the `.then()` below.

File: app/gui2/stories/GraphEditor.story.vue [hunk 6]
```diff
@@ -32,6 +35,20 @@ main =
     result = run_main benches
     third_node = 2 + 2
 `)
+
+/// Note: These props should be synced with the props in
```
Comment (somebody1234) [inline app/gui2/stories/GraphEditor.story.vue]: jsdocs are formatted like this:
```ts
/**
 * docs here
 */
```
otherwise just a double slash on the first line is fine

File: app/gui2/stories/GraphEditor.story.vue [hunk 7]
```diff
@@ -32,6 +35,20 @@ main =
...
+// `app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx`.
+// We need this here, as the rect component is not part of the dashboard and not usually available in the demo scenes.
```
Comment (somebody1234) [inline app/gui2/stories/GraphEditor.story.vue]: is `rect` a typo?

File: app/gui2/stories/GraphEditor.story.vue [hunk 8]
```diff
@@ -32,6 +35,20 @@ main =
...
+// Using this wrapper enables us to see toasts in the absence of the dashboard/React.
+const toastProps = reactive({
+  position: 'top-center',
+  theme: 'light',
+  closeOnClick: false,
+  draggable: false,
+  toastClassName: 'text-sm leading-170 bg-frame-selected rounded-2xl backdrop-blur-3xl',
+  limit: 3,
+})
+const JSONView = createReactWrapper(ToastContainer, toastProps)
```
Comment (somebody1234) [inline app/gui2/stories/GraphEditor.story.vue]: just want to confirm that name of `JSONView` is intentional?

**Review by somebody1234 — APPROVED** [review]
approving the (minimal) dashboard changes. also minor nits as usual

File: app/gui2/stories/GraphEditor.story.vue (hunk 8 above)
Comment (Frizi) [reply app/gui2/stories/GraphEditor.story.vue]: I don't think this is at all necessary. The react app already renders toast container, so issued toasts will already be linked to it automatically. We don't need to render additional container.

Comment (MichaelMauderer) [reply app/gui2/stories/GraphEditor.story.vue]: Changed the name to something more sensible.

@Frizi This is our test environment. There is otherwise no react app running there, as we don't initialise the dashboard here, and thus no toast appears. Adding this, ensures the toast container is initialised in the demo scene and allows them to appear. Unless I am missing something?

**Comment by MichaelMauderer** [comment]
@PabloBuchu @indiv0 Could you have a brief look, as this requires your code owner approval?
