### PR TITLE
Import/export syntax error have more specific messages

### LINKED ISSUE #6425: Confusing import error
Run:
```
from Standard.Table import Table as My_Table

main = 43
```

It will print:
```
In module local.Project_123.Main:
Compiler encountered errors:
Main.enso[1:28-1:44]: Imports must have a valid module path.
Aborting due to 1 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
        at <java> org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:971)
        at <java> org.enso.polyglot.Module.getAssociatedType(Module.scala:19)
        at <java> org.enso.runner.Main$.runMain(Main.scala:802)
        at <java> org.enso.runner.Main$.runPackage(Main.scala:725)
        at <java> org.enso.runner.Main$.run(Main.scala:610)
        at <java> org.enso.runner.Main$.main(Main.scala:1111)
        at <java> org.enso.runner.Main.main(Main.scala)
```

I don't understand what _Imports must have a valid module path._ means in this context. The path is valid.

The **real issue** is that I think renaming imports are not supported this way.
Instead to make this work I'd have to write:
```
import Standard.Table.Data.Table.Table as My_Table
```

OK, but the error telling me that the first syntax I tried is not supported should ideally be a bit clearer - there is no module path issue.

I think this boils down to the issue that we have:
```
case object InvalidImport extends Reason {
  override def explanation: String =
    s"Imports must have a valid module path"
}
```
so this seems to be a constant message for `InvalidImport`, but apparently there is more than this one way for an import to be invalid - I think we may need more granular error reporting here.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #6425

### Pull Request Description
Import and export syntax errors have more specific messages. For example, trying to compile this import:
```
from Standard.Table import Table as My_Table
```
now results in:
```
Compiler encountered errors:
tmp.enso[2:28-2:44]: Invalid Import: Expected identifier..
Aborting due to 1 errors and 0 warnings.
```
and before it was:
```
Compiler encountered errors:
tmp.enso[2:28-2:44]: Imports must have a valid module path.
Aborting due to 1 errors and 0 warnings.
```

There are more examples of these *better* error messages in [ErrorCompilerTest.java](https://github.com/enso-org/enso/pull/6808/files#diff-7097760cf88cf9ce8d83fb6a540241a28910b075f5cc449680cbcddf9ad24ebc)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java [hunk 1]
```diff
@@ -1583,7 +1599,11 @@ hidingNames, getIdentifiedLocation(exp), false,
         meta(), diag()
         );
     } catch (SyntaxException err) {
-      return err.toError(IR$Error$Syntax$InvalidImport$.MODULE$);
+      if (err.where instanceof Invalid invalid) {
+        return err.toError(invalidExportReason(invalid.getError()));
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java:1603]: The underlying reason comes directly from the parser.

**Review by JaroslavTulach — APPROVED** [review]
Test modifications show some improvements. Good.
