### PR TITLE
Fixing project rename

### LINKED ISSUE #13531: Renaming Project jumps back to the old name before then renaming to the new name
https://github.com/user-attachments/assets/754fdfb8-e9d1-434d-ab39-00851dacd79a

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #13531

- Implemented optimistic update for the renameProject mutation. It is necessary because the tanstack query provides the “displayed” project name, and it takes some time for the query to refetch.
- Fixed error handling on rename inside the graph editor.
- Copied `nameValidation` module from the engine to update the project identifier even if the user entered a non-identifier string.

https://github.com/user-attachments/assets/82316dac-cf9c-4f5f-9b1e-9053407e6bb7

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/dashboard/hooks/projectHooks.ts [hunk 1]
```diff
@@ -397,6 +398,40 @@ export function useRenameProjectMutation() {
...
+        queryKey,
+      })
+      // Optimistically update the project name.
+      const previousProjectDetails = client.getQueryData<backendModule.Project>(queryKey)
+      if (previousProjectDetails) {
+        client.setQueryData<backendModule.Project>(queryKey, {
+          ...previousProjectDetails,
+          name: newName,
+        })
+      }
```
Comment (kazcw) [inline app/gui/src/dashboard/hooks/projectHooks.ts]: `setQueryData` accepts an updater function for this get/modify pattern

File: app/gui/src/dashboard/hooks/projectHooks.ts [hunk 2]
```diff
@@ -397,6 +398,40 @@ export function useRenameProjectMutation() {
...
+
+      return { queryKey }
+    },
+    onError: (_err, _variables, context) => {
+      if (context?.queryKey) {
+        const toInvalidate = [
+          {
+            predicate: (query: reactQuery.Query) =>
+              reactQuery.matchQuery({ queryKey: ['listDirectory'] }, query),
+          },
```
Comment (kazcw) [inline app/gui/src/dashboard/hooks/projectHooks.ts]: Isn't constructing a predicate that calls `matchQuery` with a filter equivalent to passing the filter directly? (And likewise below)

```suggestion
          {
            queryKey: ['listDirectory'],
          },
```

**Review by kazcw — COMMENTED** [review]
In this design we maintain the "pending" name in two places--as an optimistic update in the tanstack query, and in the project name store. Would it be possible for the project name store to obtain the current effective name from tanstack?

File: app/gui/src/dashboard/hooks/projectHooks.ts (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/dashboard/hooks/projectHooks.ts]: Yep, you are right, I confused it.

**Comment by vitvakatu** [comment]
> In this design we maintain the "pending" name in two places--as an optimistic update in the tanstack query, and in the project name store. Would it be possible for the project name store to obtain the current effective name from tanstack?

Sounds like a good idea, but I didn’t find a good way to do that.
The problem is that even with an optimistic update, the breadcrumbs are not updated _immediately_ to the new value. Because of async, the execution of the mutation and propagation of the displayed project name value through all these React-Vue boundaries takes some visible time. The only way to prevent it is to store the pending name in the names store and update it before issuing a mutation.

I think adjusting breadcrumbs behavior would help here, but I’m too tired of this task for now, so I would prefer merge it as it is. I’ll create a separate ticket for future improvements and link it here.

**Review by kazcw — APPROVED** [review]
