### PR TITLE
Text.to_display_text is (shortened) identity

### LINKED ISSUE #5971: Text.to_display_text returns `Text`
Especially when handling exceptions it is important to have proper implementation of `to_display_text` (which is invoked from `PanicException.getMessage()`. However Text! has some wrong implementation. Try:

```
main = IO.println "Ahoj".to_display_text
```

and it prints `Text`. That's wrong. I should print `Ahoj`.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #5971. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java [hunk 1]
```diff
@@ -32,6 +33,24 @@ Text showExceptions(
...
+    } else {
+      var b = BreakIterator.getWordInstance();
+      b.setText(self.toString());
+      var l = b.preceding(limit);
+      if (l == BreakIterator.DONE) {
+        l = limit;
+      } else {
+        l--;
+      }
+      return Text.create(self.toString().substring(0, l));
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java]: I think I don't understand this logic.

Why are we doing `l--`? It feels like this can get us in the middle of a grapheme cluster, no? If `l` is originally at a boundary position, if we have multi-codepoint cluster before it, my intuition (aided with reading the docs of `BreakIterator::preceding` says that `l--` can put us in the middle of it.

But maybe I don't understand something here. I'd appreciate a comment (in the code) shortly explaining why this `l--` operation is correct.

File: test/Tests/src/Data/Text/Utils_Spec.enso [hunk 2]
```diff
@@ -89,4 +89,15 @@ spec =
...
+    Test.group "to_display_text" <|
+        Test.specify "simple conversion" <|
+            "Hello".to_display_text . should_equal "Hello"
+
+        Test.specify "long text conversion" <|
+            long = "Hello World! ".repeat 1024
+            disp = long.to_display_text
+            disp.length . should_equal 77
+            disp.characters.take (First 5) . should_equal [ 'H', 'e', 'l', 'l', 'o' ]
+            disp.characters.take (Last 6) . should_equal [ 'W', 'o', 'r', 'l', 'd', '!' ]
```
Comment (radeusgd) [inline test/Tests/src/Data/Text/Utils_Spec.enso]: I think we should add a test where we use multi-codepoint grapheme clusters, ideally such that the default split would end up in the middle of it, to ensure that the clusters are not broken.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 1 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java]: I think it could be much simpler to move the method `take_prefix` from `Text_Utils` to `Core_Text_Utils` and use it here. What do you think?

The less places we have logic for splitting strings on graphemes scattered around, the better.

It has similar functionality and is already tested.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java]: `l` points after a space. Hence `l--`.

File: test/Tests/src/Data/Text/Utils_Spec.enso (hunk 2 above)
Comment (JaroslavTulach) [reply test/Tests/src/Data/Text/Utils_Spec.enso]: Can you give me an example of a string you'd like me to test?

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 1 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java]: It does, but in `substring(start, end)` the `end` is also supposed to be _after_ the last codepoint we will take right? So IMO it looks like the `--` is unnecessary.

Anyway - I think just best to reuse `take_prefix` - any reasons not to?

File: test/Tests/src/Data/Text/Utils_Spec.enso (hunk 2 above)
Comment (radeusgd) [reply test/Tests/src/Data/Text/Utils_Spec.enso]: Sure, let's do three (but I care most about the first one):
```
'a\u0321\u0302'*100
'\u0915\u094D\u0937\u093F'*100
'\u{1F926}\u{1F3FC}\u200D\u2642\uFE0F'*100
```

Comment (radeusgd) [reply test/Tests/src/Data/Text/Utils_Spec.enso]: They are all 100 graphemes in length (the thing I put in `''` is always a single grapheme cluster here)

Comment (JaroslavTulach) [reply test/Tests/src/Data/Text/Utils_Spec.enso]: Added the tests in 4bc2353

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java]: Using `take_prefix` since 4bc2353

**Review by radeusgd — APPROVED** [review]

**Review by JaroslavTulach — COMMENTED** [review]
I think this change is ready for integration. Can you agree with that @4e6, @hubertp?

**Review by 4e6 — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java [hunk 3]
```diff
@@ -32,6 +35,22 @@ Text showExceptions(
     }
   }
 
+  @Specialization
+  Text convertText(Text self) {
+    final var limit = 80;
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:40]: shouldn't that be lifted to a (`private static final`) constant ?

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 3 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:40]: +1

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java [hunk 4]
```diff
@@ -32,6 +35,22 @@ Text showExceptions(
...
+    if (self.length() < limit) {
+      return self;
+    } else {
+      return takePrefix(self, limit);
```
Comment (jdunkerley) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:44]: should we an ellipsis here `…` (U+2026)

**Review by jdunkerley — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:44]: Sounds like a good idea indeed.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:40]: Originally the `limit` was only used locally in a single method. Then I had to move the iterator manipulation behind `@TruffleBoundary`...

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java:44]: > should we an ellipsis here

_"should we add an ellipsis?"_ is the question?
