### PR TITLE
More informative type error message for intersection types

### LINKED ISSUE #13106: More informative Type Error for intersection types would be useful
When constructing an intersection type, e.g. `(x : A & B)` from a value `x` of type `X`, sometimes only one of the 'paths' may be missing. E.g. there may be a conversion `X -> A` but we may lack a conversion `X -> B`. However currently the type error only says `expected A & B but got X` with no hint which 'part' was missing.

This is more visible in bigger examples, e.g. let's try running:
```
from Standard.Base import all

type X
    X_Ctor x

type A
    A_Ctor a

type B
    B_Ctor b

type C
    C_Ctor c

type D
    D_Ctor d

A.from (that:X) = A.A_Ctor that
B.from (that:X) = B.B_Ctor that
D.from (that:X) = D.D_Ctor that

main =
    x = X.X_Ctor 1
    ab = (x : A & B)
    IO.println "A&B = "+ab.to_text

    abcd = (x : A & B & C & D)
    IO.println "A&B&C&D = "+abcd.to_text
```

this yields us
```
A&B = (A_Ctor (X_Ctor 1))
Execution finished with an error: Type error: expected expression to be A & B & C & D, but got X.
        at <enso> file.main(file.enso:27:13-13)
Type error: expected expression to be A & B & C & D, but got X.
```

We get a message that the expected type was `A & B & C & D` and `X` did not match it. But the message does not tell us which part did not match. It could be helpful if the type error could be more specific, e.g.:
```
Type error: expected expression to be A & B & C & D, but got X. No conversion from X to C could be found.
```

This would tell us that the `C` part of the intersection is the culprit - so we no longer need to doubt possibly missing conversions to `A` or `B`, but can focus on figuring out why the conversion from `C` is not resolved.

In bigger codebases where conversions may not be resolved e.g. because lack of imports, a more specific error message makes the debugging much easier.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #13106 
- by creating the error message for _exactly the type check_ that fails in case of _intersection type_
- the _union type_ type check continues to list all alternatives: `Text | Nothing`, etc.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

changes, a screencast is preferred.
- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [x] [engine benchmarks](https://github.com/enso-org/enso/actions/runs/22571775861) are fine
- [x] [library benchmarks](https://github.com/enso-org/enso/actions/runs/22571782105) are fine

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/SingleTypeCheckNode.java [hunk 1]
```diff
@@ -34,7 +34,16 @@ abstract non-sealed class SingleTypeCheckNode extends AbstractTypeCheckNode {
     this.expectedType = expectedType;
   }
 
-  abstract Object executeConversion(VirtualFrame frame, Object value);
+  final Object executeConversion(
+      VirtualFrame frame, Object value, AbstractTypeCheckNode[] failingCheck) {
+    var res = executeHandleConversion(frame, value);
+    if (res == null && failingCheck != null) {
+      failingCheck[0] = this;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/SingleTypeCheckNode.java:41]: - fills in the "evidence" of failing type check
- only in case the parent node is interested in knowing which check actually failed

File: engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/OneOfTypesCheckNode.java [hunk 2]
```diff
@@ -28,9 +28,9 @@ final Object findDirectMatch(VirtualFrame frame, Object value) {
 
   @Override
   @ExplodeLoop
-  Object executeConversion(VirtualFrame frame, Object value) {
+  Object executeConversion(VirtualFrame frame, Object value, AbstractTypeCheckNode[] failingCheck) {
     for (var n : checks) {
-      var result = n.executeConversion(frame, value);
+      var result = n.executeConversion(frame, value, null);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/OneOfTypesCheckNode.java:33]: - in the case of _union types_ we request _no evidence_
- all of the alternative checks failed if the result is `null`
- e.g. no need to [fill the evidence](https://github.com/enso-org/enso/pull/14819/changes#r2872307418)
- better to say `expected expression to be A | B | C`

File: test/Base_Tests/src/Semantic/Multi_Value_Spec.enso [hunk 3]
```diff
@@ -178,6 +178,20 @@ add_specs suite_builder =
...
+            x = (a : B & X)
+            x.is_nothing . should_be_false 
+            
+        group_builder.specify "Missing conversion to C error" <|
+            a = A
+            extract_err_msg caught_panic =
+                caught_panic.payload.to_text
+            err = Panic.catch Type_Error handler=extract_err_msg <|
+                (a : B & X & C)
+            err . should_equal 'Type error: expected expression to be C, but got A.'
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Semantic/Multi_Value_Spec.enso:193]: - `a` can be converted to `B & X` (as the previous test demonstrates)
- so the error message shall only talk about `C`
- as #13106 requests

**Review by 4e6 — APPROVED** [review]
Looks good

**Review by jdunkerley — APPROVED** [review]
