### PR TITLE
Fix hybrid documentation

### LINKED ISSUE #14314: Documentation broken for hybrid projects
Image

Works OK for local projects

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #14314 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- ~~[ ] The documentation has been updated, if necessary.~~
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/DocumentationEditor/DocumentationEditor.vue [hunk 1]
```diff
@@ -2,12 +2,14 @@
...
 import { useRightPanelData } from '$/providers/rightPanel'
 import { providePopoverRoot } from '@/providers/popoverRoot'
-import { useTemplateRef } from 'vue'
+import { useTemplateRef, watchEffect } from 'vue'
 import ClosedProjectDocumentationEditor from './ClosedProjectDocumentationEditor.vue'
 import OpenedProjectDocumentationEditor from './OpenedProjectDocumentationEditor.vue'
 
 const rightPanel = useRightPanelData()
 
+watchEffect(() => console.debug('focused project', rightPanel.focusedProject))
```
Comment (Frizi) [inline app/gui/src/project-view/components/DocumentationEditor/DocumentationEditor.vue]: left out log

**Review by vitvakatu — APPROVED** [review]
