### PR TITLE
Custom type conversion to double from large long

### LINKED ISSUE #5012: Statistics fails for large Integer values
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184203977).
<hr />

When working with large integer values a type coercion error occurs when trying to add the value to the stats.

Ideally, the Java aggregator would not cast the value unnecessarily to a double.

Specifically `std-bits/base/src/main/java/org/enso/base/statistics/Moments.java` needs to be adjusted.
Currently it takes a `double` when adding a point to the accumulator.

There is an issue that is a large long (beyond what a double can exactly represent) is passed in an error is raised about a lossy conversion.

## Comments:
Is this related to [big integer](https://github.com/enso-org/enso/pull/3865/files#r1030410966) support? Wasn't the statistics rewritten to Enso to avoid conversion problems? (jaroslavtulach - Jan 18, 2023)
<hr />
No - it's the issue with the little polyglot Java based aggregator used behind the scenes of it. (James Dunkerley - Jan 19, 2023)
<hr />
The actual error (if you replace `.reduce (+)` with `.compute Statistic Sum`  in Vector Sum benchmark):
```
Execution finished with an error: Cannot convert '6907338656278321365'(language: Java, type: java.lang.Long) to Java type 'double': Invalid or lossy primitive coercion.
        at <enso> case_branch(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:354:27-43)
        at <enso> Statistics.compute_fold<arg-2>(Internal)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> Statistics.compute_fold<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:353-355)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> Statistics.compute_fold(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:340-355)
        at <enso> <anonymous>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:162:54-87)
        at <enso> f(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso:203:26-50)
        at <enso> go<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso:243:31-50)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> go(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso:242-244)
        at <enso> Range.fold<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso:245:13-30)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> Range.fold(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso:239-245)
        at <enso> Vector.fold(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso:204:9-41)
        at <enso> Statistic.type.compute_bulk(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:162:18-87)
        at <enso> Vector.compute_bulk(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:328:5-42)
        at <enso> Vector.compute<arg-0>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:320:5-33)
        at <enso> Vector.compute(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso:320:5-41)
        at <enso> Operations.bench<arg-1>(Operations.enso:33:20-51)
        at <enso> Runtime.no_inline(Internal)
        at <enso> single_call(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:28:13-33)
        at <enso> go<arg-1>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:35-44)
        at <enso> go<arg-0>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:24-53)
        at <enso> go<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:9-63)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> go(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:107-108)
        at <enso> Bench.times<arg-1>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:109:25-41)
        at <enso> Bench.times(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:109:11-42)
        at <enso> iteration(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:33:19-43)
        at <enso> go<arg-1>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:35-44)
        at <enso> go<arg-0>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:24-53)
        at <enso> go<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:108:9-63)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> go(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:107-108)
        at <enso> Bench.times<arg-1>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:109:25-41)
        at <enso> Bench.times(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:109:11-42)
        at <enso> Bench.measure<arg-2>(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:43:13-49)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> Bench.measure(<path-to-enso>enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Test/0.0.0-dev/src/Bench.enso:42-45)
        at <enso> Operations.bench(Operations.enso:33:5-83)
        at <enso> Operations.main(Operations.enso:48:8-12)

``` (Hubert Plociniczak - Jan 24, 2023)
<hr />
Shouldn't `'6907338656278321365'(language: Java, type: java.lang.Long` (probably of type `HostObject`) be converted to `long` or `java.lang.Long` when passed to Enso? (jaroslavtulach - Jan 26, 2023)
<hr />
So I wonder if providing a custom `targetTypeMapping` from long to double would do the trick here? @jtulach need your advice on whether that's acceptable

Otherwise I'm afraid we have to be explicit in https://github.com/enso-org/enso/blob/develop/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso#L354
and do the conversion by hand with `_ : Number -> current.add value.to_decimal`. But this is obviously only patching the problem here as I'm sure somebody else will encounter similar problems at the polyglot boundary. (Hubert Plociniczak - Jan 27, 2023)
<hr />
So a custom `targetTypeMapping` seems to work (i.e. it doesn't crash anymore).
I need to verify the perf of that approach though. (Hubert Plociniczak - Jan 30, 2023)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for the last Friday (2023-01-27):

**Progress:** Investigating the problem with lossy conversion in Statistics. There is a quick way to fix it (`to_decimal`) and the `right way` to fix it. After some digging looks like Truffle added some way to provide custom type conversions (will need confirmation). Looking at some planning and ongoing stability issues. It should be finished by 2023-01-30.

**Next Day:** Next day I will be working on the [#184203977 task](https://www.pivotaltracker.com/story/show/184203977). Test the theory extensively and if correct prepare the PR. (Enso Bot - Jan 30, 2023)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2023-01-30):

**Progress:** PR is ready with a fix that uses `targetTypeMapping` (don't anticipate problems with the review). Created a followup ticket for libs (#184351393) which shows statics being pretty small. Investigating stability issues, such as #184350069, #184349284 and #184350020 It should be finished by 2023-01-30.

**Next Day:** Next day I will be working on the [#184350020 task](https://www.pivotaltracker.com/story/show/184350020). Looking into jgit failure (Enso Bot - Jan 31, 2023)
<hr />
> statics being pretty small

slow. obviously. (Hubert Plociniczak - Jan 31, 2023)
<hr />
The `BigInteger` support #182962982 could be fixed by  [targetMapping](https://github.com/enso-org/enso/pull/4099) conversion as well. (jaroslavtulach - Feb 1, 2023)
<hr />

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

When a large long would be passed to a host call expecting a double, it would crash with a
```
Cannot convert '<some long>'(language: Java, type: java.lang.Long) to Java type 'double': Invalid or lossy primitive coercion
```

That is unlikely to be expected by users. It also came up in the Statistics examples during Sum. One could workaround it by forcing the conversion manually with `.to_decimal` but it is not a permanent solution.

Instead this change adds a custom type mapping from Long to Double that will do it behind the scenes with no user interaction. The mapping kicks in only for really large longs.

### Important Notes

Note that the _safe_ range is hardcoded in Truffle and it is not accessible in enso packages. Therefore a simple c&p for that max safe long value was necessary.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+        .allowArrayAccess(true)
+        .allowListAccess(true)
+        .allowBufferAccess(true)
+        .allowIterableAccess(true)
+        .allowIteratorAccess(true)
+        .allowMapAccess(true)
+        .allowAccessInheritance(true)
+        .targetTypeMapping(
+            Long.class,
+            Double.class,
```
Comment (JaroslavTulach) [inline engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java:26]: Adding a `targetTypeMapping` was considered when doing the `BigInteger` support: #3865 - at the end I haven't used it as that only works with engine properly set up - e.g. it is only going to work when one calls `allWithTypeMapping` - it is not going to work in other tests or when one embeds Enso language into own application.

**Review by JaroslavTulach — APPROVED** [review]
If we are going the `targetTypeMapping` route, when we can fix `assert` problems of `EnsoBigInteger` discovered in #4074 by using target type mapping as well. There is a [pivotal](https://www.pivotaltracker.com/story/show/183934416) calling for resolving the `BigInteger` issue by upgrade to (not yet known) version of GraalVM. But `targetTypeMapping` would address those issues as well.

File: engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java (hunk 1 above)
Comment (hubertp) [reply engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java:26]: Yes, I didn't add it to tests on purpose. We don't seem to use the same context definition in all of them anyway and I believe that's OK.
I looked at the sources of Truffle and it seems that `targetTypeMapping` is the only way to resolve the problem of this ticket without replicating some dispatch logic from Truffle in our backend (which would be horrible).

**Review by 4e6 — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

File: engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java:26]: True. Truffle doesn't support _"loosely conversion"_ which is what we want here.
