### PR TITLE
Fix performance deterioration after many external or code-editor edits.

### LINKED ISSUE #10768: Improve efficiency of code editor synchronization
`applyTextEditsToAst` parses the edited text into the current module before synchronizing. This causes unused nodes to be added to the Y.Js doc. The edited text should be parsed into a temporary module, and needed nodes copied.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix performance issue reported by @JaroslavTulach on Discord.

- Fix accumulation of unreferenced AST objects when reconciling module content with `syncToCode`.
- Add a unit test checking that `syncToCode` does not allocate unneeded objects in the module.

Fixes #10768.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/ydoc-shared/src/ast/parse.ts [hunk 1]
```diff
@@ -536,12 +536,12 @@ export function setExternalIds(edit: MutableModule, spans: SpanMap, ids: IdMap):
  * context.
  */
 export function parseInSameContext(
-  module: MutableModule,
   code: string,
   ast: Ast,
+  { module }: { module?: MutableModule } = {},
```
Comment (farmaazon) [inline app/ydoc-shared/src/ast/parse.ts]: Why not just an optional argument?

**Review by farmaazon — APPROVED** [review]
