### PR TITLE
Fix Google Analytics integration

### LINKED ISSUE #14913: Google Analytics integration is broken

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #14913 

Google analytics integration with the front end gui was broken. This MR restores that functionality.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/utils/analytics/gtag.ts [hunk 1]
```diff
@@ -28,9 +31,6 @@ gtag('js', new Date())
 // eslint-disable-next-line camelcase
 gtag('set', 'linker', { accept_incoming: true })
 gtag('config', GOOGLE_ANALYTICS_TAG)
-if (GOOGLE_ANALYTICS_TAG === 'G-CLTBJ37MDM') {
```
Comment (AdRiley) [inline app/gui/src/utils/analytics/gtag.ts:31]: Have updated this in github so no longer require the override

**Review by jdunkerley — APPROVED** [review]

**Review by PabloBuchu — APPROVED** [review]
