### PR TITLE
Dependency tracking between nodes is too coarse grained

### LINKED ISSUE #11237: Dependency tracking between nodes is too coarse grained
Consider a scenario described in the video below:
- node that is about to be deleted is defined **before** the other nodes **in the code**
- that node is also **not connected** in any way to other nodes

Screenshot from 2024-10-02 18-15-34

Yet, when deleting the node, we re-trigger execution of everything that has been be defined after the node **in the code** suggesting incorrect/too coarse grained dependency tracking info.
[Kazam_screencast_00013.webm](https://github.com/user-attachments/assets/603a6084-ad6e-47ad-adda-d38c69f2282f)

This issue has been reported in the past and claimed to be fixed, so marking as a potential `regression`.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #11237 

Changelog:
- update: implement special case for a line removal when calculating the changeset

### Important Notes

Note that the graph is still re-calculated when the node is re-added (by pressing `ctrl-z`). The reason is that the engine processes edits on the textual level and there is not enough information to do similar workarounds. The issue becomes irrelevant when we switch to the direct tree manipulation in Ydoc.

https://github.com/user-attachments/assets/c85afde8-6386-44df-82b5-6fb0cca5205b

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by hubertp — APPROVED** [review]
LGTM

File: engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala [hunk 1]
```diff
@@ -221,6 +221,27 @@ class ChangesetBuilderTest
       )
     }
 
+    "multiline remove node" in {
+      val code =
+        """x ->
+          |    y = foo 5
+          |    z = foo 7
+          |    y + x""".stripMargin.linesIterator.mkString("\n")
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala:229]: Shouldn't the `z = ...` line be followed with another _node definition_ line and not just an expression? What exactly should the `invalidated(ir, code, edit)` code return when the last line doesn't have any _node id_?

Comment (4e6) [reply engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala:229]: > Shouldn't the z = ... line be followed with another node definition line

it doesn't matter, the line can contain just a return statement

> What exactly should the invalidated(ir, code, edit) code return when the last line doesn't have any node id?

The algorithm tracks node dependencies based on internal node ids. `invalidated` method returns the set of nodes (internal node ids) affected by the edit. In this particular test scenario, removing of the `z = foo 7` line should invalidate only the `z` node.
