### PR TITLE
Fix context lock removal

### LINKED ISSUE #10254: IllegalMonitorStateException on shutdown
Happens fairly regularly when closing the application:
```
[enso.org.enso.interpreter.service.ExecutionService] An error occurred during execution of DestroyContextCmd command
java.lang.IllegalMonitorStateException: null
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1059)
	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
	at org.enso.runtime/org.enso.interpreter.instrument.execution.ReentrantLocking.removeContextLock(ReentrantLocking.scala:251)
	at org.enso.runtime/org.enso.interpreter.instrument.command.DestroyContextCmd.removeContext(DestroyContextCmd.scala:48)
	at org.enso.runtime/org.enso.interpreter.instrument.command.DestroyContextCmd.$anonfun$executeAsynchronously$1(DestroyContextCmd.scala:26)
	at org.enso.runtime/scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.enso.runtime/scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at org.enso.runtime/scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:106)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:140)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:131)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:102)
```

### LINKED ISSUE #10354: Fail to open the project when pressing New Empty Project button
## Issue

When pressing the `New Empty Project` button on the dashboard, the error is displayed and the project is not opened:

https://github.com/enso-org/enso/assets/357683/41e4fd75-3469-493b-a73b-53cd08adeadb

I tracked the issue to the #10256 commit. It is the first comit that shows this behavior.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Removal of context lock assumed that one still holds a lock on it. This is no longer the case when using a `withContextLock` block that correctly manages the resource. This change fixes the `IllegalMonitorStateException`.
Closes #10254.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala [hunk 1]
```diff
@@ -248,7 +248,10 @@ class ReentrantLocking(logger: TruffleLogger) extends Locking {
     contextMapLock.lock()
     try {
       if (contextLocks.contains(contextId)) {
-        contextLocks(contextId).unlock()
+        assertNotLocked(
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala:226]: I don't understand the desired behavior. Why do we have `removeContextLock` at all? Because of [this line](https://github.com/enso-org/enso/blob/dee9e079d40b1df72731cc5dc7a44d1212fb4c68/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala#L48)? Then just remove it!

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
The _context lock_ is automatically created by `withContextLock` - why it is not cleaned at the end of the `withContextLock` method? That's the intended behavior of `withXyz` methods - we should delete the `removeContextLock` method.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala:226]: Yes. I suppose it was added to avoid creating new instances of `ReentrantLock`. Once the lock is created it is re-used. It saves roughly 10ms per command (as that particular lock is required quite often).

Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala:226]: Everywhere, where `ctx.locking.withContextLock(` is used, there is an instance of `RuntimeContext`. To 

> avoid creating new instances of ReentrantLock

the `RuntimeContext` shall obtain some object instance via `ctx.locking.createContextLock` and then use it via `ctx.locking.withContextLock(` until it is needed. At the end it should _close it_ (`removeContextLock`).

Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala:226]: Possible API could look like:
```diff
diff --git engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java
index fc6e3f6389..b223ce34fb 100644
--- engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java
+++ engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java
@@ -37,21 +37,25 @@ public interface Locking {
   <T> T withPendingEditsLock(Class<?> where, Callable<T> callable);
 
   /**
-   * Executes `callable` while holding a context lock
+   * Allocates new handle for use in {@link #withContextLock} associated with given context ID.
    *
-   * @param contextId context id for which the lock is being requested
-   * @param where the class requesting the lock
-   * @param callable code to be executed while holding the lock
-   * @return the result of calling `callable` or null, if no result is expected
+   * @param contextId context ID
+   * @return an object to pass to {@link #withContextLock} and to {@link AutoCloseable#close()} when
+   *     no longer needed
    */
-  <T> T withContextLock(UUID contextId, Class<?> where, Callable<T> callable);
+  AutoCloseable createContextLock(UUID contextId);
 
   /**
-   * Removes a context lock.
+   * Executes `callable` while holding a context lock
    *
-   * @param contextId a context to remove
+   * @param contextLockHandle handle created by {@link #createContextLock(UUID)}
+   * @param where the class requesting the lock
+   * @param callable code to be executed while holding the lock
+   * @return the result of calling `callable` or null, if no result is expected
+   * @throws ClassCastException if {@code contextLockHandle} isn't coming from {@link
+   *     #createContextLock(UUID)}
    */
-  void removeContextLock(UUID contextId);
+  <T> T withContextLock(AutoCloseable contextLockHandle, Class<?> where, Callable<T> callable);
 
   /**
    * Executes `callable` while holding a file lock
```
More advanced tricks with generics (to hide `ClassCastException` from the docs) are possible, but probably unnecessary.

**Review by JaroslavTulach — COMMENTED** [review]
Hopefully the `AutoCloseable` solution will be easy to implement.

**Comment by hubertp** [comment]
Tried to address your comment @JaroslavTulach, didn't really see the need for `AutoCloseable`. If still not good, please feel free to send a patch to this PR

**Comment by JaroslavTulach** [comment]
> If still not good, please feel free to send a patch to this PR

More encapsulation in c8b5111. Feel free to go with or without c8b5111 change.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala [hunk 2]
```diff
@@ -35,17 +35,18 @@ class DestroyContextCmd(
 
   private def removeContext()(implicit ctx: RuntimeContext): Unit = {
     ctx.jobControlPlane.abortJobs(request.contextId)
+    val contextLock = ctx.locking.getOrCreateContextLock(request.contextId)
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala:38]: Why isn't the `contextLock` a field in `RuntimeContext`?

**Review by JaroslavTulach — APPROVED** [review]
Unblocking.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala (hunk 2 above)
Comment (hubertp) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala:38]: `RuntimeContext` is not per context id, therefore we would have to have a map of those. Besides `RuntimeContext` is a case class, so immutable and it didn't seem appropriate to stick one more lock info to it.

Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala:38]: > `RuntimeContext` is not per context id .... `RuntimeContext` is a case class, so immutable

I see. `RuntimeContext` holds `locking`, the `contextId` isn't part of `RuntimeContext`. In such case, there is no point of putting `contextLock` into `RuntimeContext`. I must have seriously confused myself. Sorry.
