### PR TITLE
Fix numeric slider

### LINKED ISSUE #10090: Numeric slider widget not working
We seemed to have broken the numeric slider widget somehow...

image

image

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Prevent default pointerdown action from interfering with slider.

https://github.com/enso-org/enso/assets/1047859/736a01ca-9cdb-4163-8cd5-e3c1d7e15552

Fixes #10090.

### Important Notes

- Also fix drag detection when the slider is dragged and returned to its original position.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/components/widgets/NumericInputWidget.vue [hunk 1]
```diff
@@ -25,20 +25,29 @@ watch(
...
 
-    if (eventType === 'start') return
-
     if (inputFieldActive.value || props.limits == null) return false
 
+    if (eventType === 'start') {
+      event.preventDefault()
+      dragState = { thresholdMet: false }
+      return
+    }
```
Comment (farmaazon) [inline app/gui2/src/components/widgets/NumericInputWidget.vue]: Add a comment here that we want to forbid input selection - it may be not obvious to someone new to our codebase.

**Review by farmaazon — APPROVED** [review]
