### PR TITLE
Propagate context from real node to DataflowError constructor

### LINKED ISSUE #14532: Frequent assertion failure JS_Interop_Spec
```
java.lang.AssertionError: no root node for null
with section: null
with root nodes: null
```
started showing up frequently in [Extra Nightly Checks](https://github.com/enso-org/enso/actions/runs/20404103796/job/58631612971#step:14:1859). Another example [available to see](https://github.com/enso-org/enso/actions/runs/20358940317/job/58500846572#step:14:1131) on CI.

Based on the stacktrace it seems to originate from `JS_Interop_Spec`.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #14532 
- by propagating `EnsoContext` from a real `Node`
- to the `DataflowError` constructor 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests continue to pass

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 1]
```diff
@@ -110,11 +112,11 @@ private DataflowError(Object payload, Node location) {
     this.ctx = EnsoContext.get(location);
   }
 
-  private DataflowError(Object payload, AbstractTruffleException prototype) {
+  private DataflowError(EnsoContext ctx, Object payload, AbstractTruffleException prototype) {
     super(prototype);
     this.payload = payload;
     this.ownTrace = false;
-    this.ctx = prototype instanceof PanicException panic ? panic.ctx() : EnsoContext.get(null);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java:117]: - this _fallback call_ to `EnsoContext.get(null)`
- was yielding the `AssertionError` when `-ea` was on
- the assert is there since #7493
- the functionality wasn't affected, but such a call couldn't be on _fast path_ - hence the `assert`
- passing the real `ctx` around (as done by this PR) seems safer

**Review by 4e6 — APPROVED** [review]
