### PR TITLE
Fix clashing project ids in ProjectManager

### LINKED ISSUE #14803: Cloned Project cannot be opened at the same time as the original
If you duplicate project in Cloud, and then try to open both the original and the copy, the second opened project will have "Module.AST loading timeout" error. Closing the tab will break LS connection in the first project.

This is caused by project's having the same "local version" project id, what seemingly confuses our Project Manager.

This should be fixed on GUI side, as we should handle a situation when user just duplicates local project "by hand". Project Manager cannot rely on ProjectId stored in `.enso/project.json` for identifying projects, it should include a path to project as well.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #14803

- Fix local project identity collisions by keying project state with `projectsDirectory` + `projectId`, not project ID alone.
- Switch local telemetry and session-log lookup from raw internal project ID to hashed local project key derived from parent directory + project ID. **Breaking change**, local project session logs won’t be available.
- Apply duplicate-ID resolution both in project repository loading and filesystem listing used by local project discovery.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/common/src/services/ProjectManager/projectIdentity.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+/** Create cache key for project-service local identity. */
+export function makeProjectCacheKey(params: {
+  readonly projectId: UUID | string
+  readonly projectsDirectory: Path | string
+}) {
+  return `${params.projectsDirectory}${PROJECT_IDENTITY_SEPARATOR}${params.projectId}`
+}
+
+/** Create opaque local key used for logs and telemetry. */
+export async function makeLocalProjectKey(
```
Comment (farmaazon) [inline app/common/src/services/ProjectManager/projectIdentity.ts]: localKey sounds a bit ambiguous to me (cache key are technically also for local projects, aren't they?) What about "telemetry key"?

File: app/common/src/services/ProjectManager/ProjectManager.ts [hunk 2]
```diff
@@ -374,11 +379,20 @@ export class ProjectManager {
     }
   }
 
-  /** List project sessions by scanning engine log files for the given project UUID. */
-  async listProjectSessions(projectId: string) {
+  /** Return opaque local key used for local logs and telemetry. */
+  async getLocalProjectKey(projectPath: Path) {
```
Comment (farmaazon) [inline app/common/src/services/ProjectManager/ProjectManager.ts]: Similar situation here.

File: app/gui/src/providers/openedProjects/projectStates.ts [hunk 3]
```diff
@@ -507,9 +507,8 @@ export function useProjectStates() {
   /** Create an event logger for given project. */
   function eventLogger(project: Opened, runDetails: ProjectDetails) {
     const logProjectId =
-      project.info.mode === 'local' ?
-        `project-${runDetails.internalId?.replaceAll('-', '')}`
-      : project.info.id
+      project.info.mode === 'local' ? runDetails.localProjectKey : project.info.id
+    assertDefined(logProjectId)
```
Comment (farmaazon) [inline app/gui/src/providers/openedProjects/projectStates.ts:511]: I wonder if it would be possible to make this assertion in type system? Perhaps "LocalBackend" could return more strictly-typed localProjectKey. Of course this is not worth too much effort.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/providers/openedProjects/projectStates.ts (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/providers/openedProjects/projectStates.ts:511]: It is not simple, `runDetails` is not parametrized by backend type, and I don’t think it worth the complication.

File: app/common/src/services/ProjectManager/projectIdentity.ts (hunk 1 above)
Comment (vitvakatu) [reply app/common/src/services/ProjectManager/projectIdentity.ts]: Yeah… I think telemetry key sounds good, the initial name comes from “LOCAL_PROJECT_ID” that is passed to the engine.
