### PR TITLE
Do not run visualizations on InterruptedException

### LINKED ISSUE #11243: Thread interruption may happen while constructing a log message
SafePoint execution may sometimes happen at undesired places, such as when constructing arguments for a log message.
As I am actively working on #11084 I added more info to print stacktraces. While browsing through a simple Enso project I encountered the `ThreadInterruptedException` in the popup for no apparent reason.
Turned out safe point kicked in while sending a correct visualization update:
```
org.enso.interpreter.runtime.control.ThreadInterruptedException
	at org.enso.runtime/org.enso.interpreter.runtime.ThreadManager$1.perform(ThreadManager.java:78)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.performTLAction(LanguageAccessor.java:565)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AsyncEvent.acceptImpl(PolyglotThreadLocalActions.java:649)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AbstractTLHandshake.accept(PolyglotThreadLocalActions.java:601)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AbstractTLHandshake.accept(PolyglotThreadLocalActions.java:546)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake$Handshake.perform(ThreadLocalHandshake.java:219)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.processHandshakes(ThreadLocalHandshake.java:368)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake.processHandshake(ThreadLocalHandshake.java:159)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotThreadLocalHandshake.poll(HotSpotThreadLocalHandshake.java:79)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleSafepoint.poll(TruffleSafepoint.java:155)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:746)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:550)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedRuntimeSupport.callInlined(OptimizedRuntimeSupport.java:250)
	at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:407)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:877)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doSingleUncached(HostExecuteNode.java:238)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen$Uncached.execute(HostExecuteNodeGen.java:825)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:465)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Uncached.invokeMember(HostObjectGen.java:8967)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObject.toStringImpl(HostObject.java:2833)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObject.toDisplayString(HostObject.java:2808)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Uncached.toDisplayString(HostObjectGen.java:9217)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.toDisplayString(InteropLibraryGen.java:5138)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.toDisplayString(InteropLibraryGen.java:7726)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary.toDisplayString(InteropLibrary.java:2529)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLoggers$ImmutableLogRecord.safeValue(PolyglotLoggers.java:740)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLoggers$ImmutableLogRecord.<init>(PolyglotLoggers.java:661)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLoggers$LoggerCache.createLogRecord(PolyglotLoggers.java:279)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.createLogRecord(EngineAccessor.java:1373)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLogger.doLog(TruffleLogger.java:747)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLogger.log(TruffleLogger.java:529)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.sendVisualizationUpdate(ProgramExecutionSupport.scala:648)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$executeProgram$6(ProgramExecutionSupport.scala:126)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionCallbacks.callOnExecutedVisualizationCallback(ExecutionCallbacks.java:186)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionCallbacks.executeOneshotExpressions(ExecutionCallbacks.java:180)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionCallbacks.updateCachedResult(ExecutionCallbacks.java:118)
	at org.enso.runtime.instrument.id.execution/org.enso.interpreter.instrument.id.execution.IdExecutionInstrument$IdEventNodeFactory$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:252)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnValue(ProbeNode.java:1509)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnValue(ProbeNode.java:1062)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnValue(ProbeNode.java:245)
	at org.enso.runtime/org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:45)
	at org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:61)
	at org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:61)
	at org.enso.runtime/org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:535)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:94)
	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:86)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:56)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:161)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:107)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:155)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:81)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:84)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:79)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:97)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7952)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:567)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:205)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:250)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:148)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:274)
	at scala.library@2.13.11/scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.library@2.13.11/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:274)
	at scala.library@2.13.11/scala.util.Either.flatMap(Either.scala:352)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:269)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$2(ExecuteJob.scala:80)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$2$adapted(ExecuteJob.scala:70)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.ReentrantLocking.withReadCompilationLock(ReentrantLocking.scala:140)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$1(ExecuteJob.scala:70)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$1$adapted(ExecuteJob.scala:67)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.ReentrantLocking.withContextLock(ReentrantLocking.scala:217)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.runImpl(ExecuteJob.scala:67)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:33)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:17)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:145)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:106)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:140)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:131)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:102)
[DEBUG] [2024-10-03T11:43:22.016] [org.enso.languageserver.protocol.json.JsonConnectionController] now supervising Actor[akka://language-server/user/json-connection-controller-6aaba2c9-5574-41b9-a4a2-ae394ed3b11b/request-handler-ApplyEdit-1fe589ca-9533-4ce1-b576-1e4c700c79d1#1898164456]
[DEBUG] [2024-10-03T11:43:22.016] [org.enso.languageserver.requesthandler.text.ApplyEditHandler] started (org.enso.languageserver.requesthandler.text.ApplyEditHandler@72100f9)
[DEBUG] [2024-10-03T11:43:22.017] [org.enso.languageserver.requesthandler.text.ApplyEditHandler] stopped
[TRACE] [2024-10-03T11:43:22.017] [enso.org.enso.interpreter.service.ExecutionService] Execution finished: Left(Some(Diagnostic(Error,Some(org.enso.interpreter.runtime.control.ThreadInterruptedException),None,None,None,Vector())))
[DEBUG] [2024-10-03T11:43:22.017] [enso.org.enso.interpreter.service.ExecutionService] Executing command synchronously: EditFileCmd...
[TRACE] [2024-10-03T11:43:22.018] [enso.org.enso.interpreter.service.ExecutionService] Waited [EditFileCmd] 0ms for the file lock
```

Can we do better? If not, then how do we guard against all those (undesired) places where this may appear.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

There is no point in running visualization for the expression value that is InterruptedException. The latter is likely to bubble up the exception or create erroneous value that will be confusing to the user.

### Important Notes

Closes #11243 and partially addresses some of the symptomes of #11084.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java [hunk 1]
```diff
@@ -43,6 +43,14 @@ public static String findExceptionMessage(Throwable ex) {
...
   }
 
+  public static boolean isInterruptedExceptionValue(Object object) {
+    if (object instanceof Throwable ex) {
+      return isInterruptedException(ex);
+    } else {
+      return false;
+    }
+  }
+
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java:54]: Is it necessary to introduce new `isInterruptedExceptionValue` method? Isn't it easier to change the argument of existing `isInterruptedException` to `Object`?

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java:54]: Instance check didn't feel right, hence another method. But I don't have a preference tbh.

Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java:54]: There is no need to perform an instance check. `isInterruptedException(Object ex, InteropLibrary iop)` accepts `Object`.
