### PR TITLE
Exporting non-existing symbols fails with compiler error

### LINKED ISSUE #7867: Exporting non-existing symbols should result in an error
Running: (just one export of non-existing type)
```
from project.Main export Non_Existing_Type
```
does not result in any error, neither any warning. Since we already generate errors for importing non-existing symbols, we should generate an error for the case of exporting symbols as well.

### PR DESCRIPTION
**Pull request by Akirathan**
Closes #7867

### Pull Request Description

Adds a new compiler analysis pass that ensures that all the symbols exported via `export ...` or `from ... export ...` statements exist. If not, generates an IR Error.

### Important Notes
We already have such a compiler pass for the version with imports in [ImportSymbolAnalysis.scala](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ImportSymbolAnalysis.scala)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+            exportedSymbols.foreach(exportedSymbol -> {
+              var foundSymbols = foundResolvedExp.target().findExportedSymbolsFor(exportedSymbol.name());
+              if (foundSymbols.isEmpty()) {
+                exportErrors.add(
+                    ImportExport.apply(
+                        exportedSymbol,
+                        new ImportExport.SymbolDoesNotExist(exportedSymbol.name(), moduleOrTypeName.name()),
+                        ImportExport.apply$default$3(),
+                        ImportExport.apply$default$4()
+                    )
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java:90]: It makes me sad to see this done in not-Scala, but I know this is the general direction. But it still makes me sad 🙁

File: engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala [hunk 2]
```diff
@@ -450,12 +591,17 @@ class ImportExportTest
...
         .getIr
 
+      mainIr.imports.size shouldEqual 1
+      mainIr.imports.head.isInstanceOf[errors.ImportExport] shouldBe true
       mainIr.imports.head
         .asInstanceOf[errors.ImportExport]
         .reason
-        .message should include(
-        "The symbol Impl (module or type) does not exist in module Test.Logical_Export.Main."
-      )
```
Comment (radeusgd) [inline engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala:458]: Why are we no longer testing what the message is?

I'd like the tests to verify that the message is informative and comprehensible.

**Review by radeusgd — APPROVED** [review]
Looks good

File: distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso [hunk 3]
```diff
@@ -175,7 +175,6 @@ from project.Data.Numbers export Float, Integer, Number
 from project.Data.Range.Extensions export all
 from project.Data.Statistics export all hiding to_moment_statistic, wrap_java_call, calculate_correlation_statistics, calculate_spearman_rank, calculate_correlation_statistics_matrix, compute_fold, empty_value, is_valid
 from project.Data.Text.Extensions export all
-from project.Data.Time.Conversions export all
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:184]: This file does not exist, right?

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:184]: Yep.

It's my fault, I forgot to remove this export after removing the file, sorry.

Thanks for adding a pass that catches such errors! ❤️

Comment (Akirathan) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso:184]: Yes, exactly. This is why it is now removed - the compilation now fails with this pass.

File: engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala (hunk 2 above)
Comment (Akirathan) [reply engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala:458]: The message is defined in https://github.com/enso-org/enso/blob/dec8dac8a01d29f9a3a18431ddc5179142a97167/engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala#L158-L164
 and is likely to change from time to time - which is what happened in this PR. This `ImportExportTest.scala` tests that the errors are of `SymbolDoesNotExist` type and checks the `symbolName` field. Repeating the message constant ten times in this test does not seem as a good idea to me.

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java:90]: Apart from some weird perks, like calling methods with default arguments, or methods on objects, there is nothing stopping us from calling Scala stuff from Java stuff anymore. It does not look nice, but it is the most viable compromise for now.

File: engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala:458]: Ok

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java [hunk 4]
```diff
@@ -30,15 +30,11 @@
  * Inserts errors into imports/exports IRs if the above conditions are violated.
  */
 public final class PrivateModuleAnalysis implements IRPass {
-  private static final PrivateModuleAnalysis singleton = new PrivateModuleAnalysis();
+  public static final PrivateModuleAnalysis INSTANCE = new PrivateModuleAnalysis();
   private UUID uuid;
 
   private PrivateModuleAnalysis() {}
 
-  public static PrivateModuleAnalysis getInstance() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java:38]: Isn't [getter better than a field](http://wiki.apidesign.org/wiki/GettersAndSetters)?

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+    this.uuid = v;
+  }
+
+  @Override
+  public Seq<IRPass> precursorPasses() {
+    List<IRPass> passes = List.of(
+        BindingAnalysis$.MODULE$,
+        ImportSymbolAnalysis$.MODULE$
+    );
+    return CollectionConverters.asScala(passes).toList();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java]: Yes, we shall compute this lazily or again and again.

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+            });
+          }
+        }
+        yield null;
+      }
+      default -> export;
+    });
+    return moduleIr.copy(
+        moduleIr.imports(),
+        exportErrors.isEmpty() ? moduleIr.exports() : CollectionConverters.asScala(exportErrors).toList(),
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java]: If there are no `exportErrors`, do no copy, return original `moduleIr`.

**Review by JaroslavTulach — APPROVED** [review]
Nice to see we detected an error in standard library.

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java:38]: In most scenarios, I would say so. But here, I wanted to get as closest to `scalac` as possible - which creates `$MODULE$` public static final field for `object`. Just my preference. I could refactor it to getter once more.

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java]: Good point. Refactored in 0b8b8872deeb01de6814abd7d465ab8a73fac7f4

File: engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java (hunk 5 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java]: Oh, right. In Scala, this is `lazy val`. I introduced ` private static final` field in 430691420847f8bf62808384c42f09f53d38e8a0 to simulate that here, so that it's lazy as well.
