### PR TITLE
Retry IDE controller initialization.

### LINKED ISSUE #5627: IDE timeouts when trying to connect with the cloud
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening Enso Cloud IDE timeouts on the first opening

### Expected behaviour

Project is opened

### How we can reproduce it?

1. open enso cloud
2. start and the open a project
3. wait for project to initialize 

### Enso Version

 2023.1.1-nightly.2023.2.9

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 109.0.5414.119 (Official Build) (x86_64)

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

This mainly fixes #5627 in both scenarios: when the initProtocol method takes too long time and also when we run GUI before LS listens for new connections.

If the IDE initialization fails (e.g. due to above two reasons), it is retried 3 times, waiting some time.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: app/gui/src/ide/initializer.rs [hunk 1]
```diff
@@ -81,17 +90,29 @@ impl Initializer {
...
+                    let ide = Ide::new(ensogl_app, view.clone_ref(), controller);
+                    info!("Setup done.");
+                    break Ok(ide);
+                }
+                Err(error) => {
+                    let message = format!("Failed to initialize application: {error}");
+                    error!("{message}");
+                    match retry_after.next() {
+                        Some(time) => {
+                            info!("Retrying after {} seconds", time.as_secs_f32());
```
Comment (kazcw) [inline app/gui/src/ide/initializer.rs]: I would log this at `error` level--it's important information about the error.

**Review by kazcw — APPROVED** [review]

**Review by MichaelMauderer — APPROVED** [review]

**Comment by MichaelMauderer** [comment]
QA Approved ✅
