### PR TITLE
Fix entering node failure handling

### LINKED ISSUE #6763: Backend stops evaluation with a `File_Not_Found` error.
Starting with a new project, add a `Meta.meta Any` node.
This will evaluate.
Edit the node the to `Meta.meta Pair`.

The evaluation will stop with a `File not found` error in the IDE logs.
image

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #6763 

The bug was caused by pushing stack frames in the engine first, then failing to get graph controller - in that case we didn't update graph, but kept the stack, so graph was not synchronized with stack.

This PR changes the approach: we try to open graph first, only then push frames to stack. If _any_ frame will fail, we try to pop those we pushed so far, to restore the previous state. The same fix was applied for leaving nodes.

Also, I realized, that running several "enter node" / "leave node" actions could mix push/pop operations, making a mess with our execution context state. I've added a mutex to ensure we won't do this: the contesting operation will simply fail.

### Important Notes

In case when _restoring_ state fails, I did not have any better idea than just trying until it succeed.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/retry.rs [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+    #[test]
+    fn operation_always_failing() {
+        let mut call_index = 0;
+        let operation = move || {
+            call_index += 1;
+            async move { Err(call_index) }
+        };
+        let retry_times = [10, 20, 30, 40, 50].into_iter().map(Duration::from_millis);
+        let mut future =
+            retry_operation(operation, retry_times, "One does not simply walk into Mordor.")
```
Comment (wdanilo) [inline app/gui/src/retry.rs:170]: well :D

**Review by wdanilo — APPROVED** [review]

**Comment by vitvakatu** [comment]
QA passed 🍏
