### PR TITLE
Fix static methods in dropdowns

### LINKED ISSUE #7824: Dropdown widgets mangling inserted code for 0-argument method / `Locale.default_widget` is broken
I have noticed that it is impossible to create a dropdown which once selected will insert a 0-argument method as its value.

We can easily insert a function taking arguments, as well a 0-argument constructor. However, once I try to insert a 0-argument function - the 'prefix' is stripped - but with the stripped prefix the function no longer resolves, so the whole node fails with an error.

The easiest illustration of this behaviour is the `Locale` widget not working:

image

https://github.com/enso-org/enso/assets/1436948/59a75fce-4f08-497f-a852-3a82405c8d2f

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #7824

The issue was caused by me who didn't think that we can use static methods in dropdowns.

https://github.com/enso-org/enso/assets/6566674/5045c5ce-e33b-48ff-9488-4228c016b563

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/suggestion-database/src/entry.rs [hunk 1]
```diff
@@ -973,10 +973,11 @@ where
                 let label = chain_to_label(&chain);
                 let qualified_name = entry.qualified_name();
                 let required_import = Some(qualified_name.to_string());
-                // As we don't generate `this`, we will never follow the code path where
-                // `in_module` is used. That's why passing `default()` is valid.
+                // Passing some meaningful module name instead of `default()` is preferable, but we
+                // can't access it in this method. This means we never use `Main` instead of
+                // project name in dropdowns.
```
Comment (farmaazon) [inline app/gui/suggestion-database/src/entry.rs]: We use `Main` instead of project name, because it is more resilient to project renaming. No chance of propagating current module from somewhere?

Comment (vitvakatu) [reply app/gui/suggestion-database/src/entry.rs]: It was a bit painful, but done.

**Review by farmaazon — APPROVED** [review]

**Comment by vitvakatu** [comment]
Merging without QA as the change is trivial
