### PR TITLE
When opening the project for a second time suggestion database is not sent

### LINKED ISSUE #7413: When opening the project for a second time, suggestion database is not sent.
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [x] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening a project multiple times in the same engine session, the suggestion database is sent only on the first visit. After that, the `search/getSuggestionsDatabase` endpoint seems to have no effect.

### Expected behaviour

The full suggestion database should be sent to IDE every time it uses `search/getSuggestionsDatabase` endpoint.

### How we can reproduce it?

1. Open a project in IDE. Take note that component browser offers many suggestions.
2. Refresh IDE.
3. Open the same project again.
4. Open component browser, notice missing suggestions.

### Screenshots or screencasts

Notice only small responses containing suggestion updates.
image

### Logs

_No response_

### Enso Version

2023.2.1-nightly.2023.7.24.1

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

electron

### Operating System

Windows

### Operating System Version

11

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7413 

Changelog:
- update: the language server listens for the client disconnection event and invalidates the suggestions index

### Important Notes

The component browser contains suggestion entries after the refresh

https://github.com/enso-org/enso/assets/357683/bcebb8bf-e09f-4fb0-86cf-95ced58413f3

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala [hunk 1]
```diff
@@ -434,6 +455,30 @@ final class SuggestionsHandler(
           state.suggestionLoadingComplete()
         )
       )
+
+    case JsonSessionTerminated(_) =>
+      logger.info("Processing JsonSessionTerminated")
```
Comment (hubertp) [inline engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala]:
```suggestion
      logger.trace("Processing JsonSessionTerminated")
```

Feels more like `trace` or `debug` kind of thing

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala [hunk 2]
```diff
@@ -30,6 +30,13 @@ trait JobControlPlane {
     */
   def startBackgroundJobs(): Boolean
 
+  /** Stops background jobs processing.
+    *
+    * @return `true` if the background jobs were stopped and `false` if they are
+    * already stopped.
+    */
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala]:
```suggestion
    * @return `true` if the call stopped background job, `false` if they are
    * already stopped.
    */
```

**Review by hubertp — APPROVED** [review]
