### PR TITLE
Move markdown link popup to floating layer

### LINKED ISSUE #13553: Hyperlinks in comments are broken
https://github.com/user-attachments/assets/7d94e0f0-c5e9-4d83-9768-7d826c337170

Which presumably is why this test has gone flakey 

integration-test/project-view/nodeComments.spec.ts:86:1 › URL added to comment is rendered as link 

https://github.com/enso-org/enso/actions/runs/16352300162/job/46201926753?pr=13525#step:9:128

Tests FTW!

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #13553

Markdown link popups now teleport out of the markdown editor, so they can be rendered outside of codemirror's scroll area.

image

### CODE REVIEW

File: app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue [hunk 1]
```diff
@@ -120,7 +120,7 @@ const { editorView, setExtraExtensions } = useCodeMirror(editorRoot, {
   scrollerTestId,
 })
 
-useLinkTitles(editorView, { readonly })
+useLinkTitles(editorView, { readonly: () => readonly })
```
Comment (kazcw) [inline app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue:123]: Why the lambda?

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue (hunk 1 above)
Comment (Frizi) [reply app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue:123]: Because the `readonly` value is a prop, and we awant to pass it as reactive `toValue`. Previously we only passed the initial prop value. In case editor becomes readonly dynamically, the links would not know about it.

Comment (kazcw) [reply app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue:123]: Oh, it's a prop 👍
