### PR TITLE
Always call instance methods on Any

### LINKED ISSUE #5612: Equality on types with `Any` as LHS does not work
`Any == Boolean` returns a function `Any.type.==` instead of `False`. This is because it resolves as `Any.type.== Any Boolean` method call (which expects 3 arguments rather than 2). Note that `Boolean == Any` returns `False` as expected, because it resolves to `Any.== Boolean Any`

May be related to https://github.com/enso-org/enso/pull/4077

Related pending test: https://github.com/enso-org/enso/blob/develop/test/Tests/src/Semantic/Equals_Spec.enso#L172

### LINKED ISSUE #6473: Meta.meta Any . methods doesn't work
One can list all methods of every type like `Boolean`:
```
> Meta.meta Boolean . methods
>>> ['&&', '||', 'not', 'if_then', 'if_then_else']
```
but one cannot do the same with `Any` type:
```
> Meta.meta Any . methods
Evaluation failed with: Type error: expected `type` to be Type, but got Function.
java.lang.Exception: Type error: expected `type` to be Type, but got Function.
        at <enso>.Type.methods<arg-1>(Meta.enso:42)
        at <enso>.Standard.Base.Meta::Standard.Base.Meta.Type::methods(Meta.enso:41)
```
probably related to #6300 and or #5612. Tested on 0dc9f3742cc52ac091b0338672fe02039931e097

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #5612 and #6473.

Fixes some static method invocations on `Any`, like `Any == Boolean`, or `Any.to_text`.

### Pull Request Description

Previously, static method calls on `Any` have not worked as expected. For example, `Any.to_text` returned Function instead of Text. That is because the function resolution for `Any.to_text` finds `Any.type.to_text` method on eigentype which expects two `self` arguments, but only one argument is provided.

Note that `Boolean.to_text` worked previously, and returned "Boolean" as expected. This is because the method resolution finds `Any.to_text` method that takes just one `self` argument.

This PR solves this issue by introducing special handling for static method dispatch on `Any`. Simply put, an additional `self` argument is prepended to the argument list.

### Important Notes
A new child node is introduced to `InvokeMethodNode`. This child node is a copy of the current `invokeFunctionNode` with one more `CallArgumentInfo` in its schema.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 1]
```diff
@@ -154,29 +168,81 @@ private boolean typeCanOverride(MethodRootNode node, EnsoContext ctx) {
...
+        // Prepend self=Any to the arguments and shift
+        assert resolvedFuncArgCount - 1 <= invokeFuncSchema.length
+            && invokeFuncSchema.length <= resolvedFuncArgCount;
+        assert arguments.length == invokeFuncSchema.length;
+
+        CallArgumentInfo[] newInvokeFuncSchema = new CallArgumentInfo[resolvedFuncArgCount];
+        newInvokeFuncSchema[0] = new CallArgumentInfo("self");
+        newInvokeFuncSchema[1] = new CallArgumentInfo("self");
+        int toCopyLen = Math.min(newInvokeFuncSchema.length - 2, invokeFuncSchema.length);
+        System.arraycopy(invokeFuncSchema, 0, newInvokeFuncSchema, 2, toCopyLen);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Last time I tried to do similar manipulation of arguments I was (rightfully) reminded that this approach is really bad and sounds like a hack, not to mention perf penalty.

**Review by hubertp — COMMENTED** [review]
I don't think such manipulation is the right approach but I will defer to @kustosz to have the last word on this.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I don't think either, this is an elegant solution. It's the only one that I was able to come up with. Why do you think there will be any perf penalty? The penalty is paid just in the very first invocation of such a special static method invocation on `Any`, which will construct `invokeAnyFunctionNode`. Once this node is constructed, all the subsequent calls should have negligible perf penalty.

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Nevertheless, I will be more than happy for any other suggestions

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 2]
```diff
@@ -42,19 +42,64 @@ spec =
             My_Type.Value 33 . x . should_equal "Any:(My_Type.Value 33)"
             With_X.Value 44 . x . should_equal "With_X:(With_X.Value 44)"
             With_Y.Value 44 . x . should_equal "With_Y:With_Y(44)"
-            Any.x . to_text . should_equal "Any.type.x[Any_Types.enso:6-26]"
             My_Type.x . should_equal "Any:My_Type"
             With_X.x . to_text . should_equal "Any:With_X"
-            With_X.y . to_text . should_equal "With_X.type.y[Any_Types.enso:12-32]"
+            Meta.is_a With_X.y Function . should_be_true
```
Comment (Akirathan) [inline test/Tests/src/Semantic/Any_Spec.enso]: This is a more persistent and maintainable way to check if something is a `Function`. If you convert it to text via `to_text`, it will be different every time you fiddle with `Any_Types.enso` source, which is very inconvenient.

File: engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala [hunk 3]
```diff
@@ -1085,10 +1085,14 @@ class Compiler(
...
-          // We dont have location information, so we just print the message
+          // There is no source section associated with the diagnostics
           var str = fansi.Str()
+          val fileLocation = diagnostic.location match {
+            case Some(_) => fileLocationFromSection(diagnostic.location, source)
+            case None    => source.getPath
+          }
           str ++= fansi
-            .Str(fileLocationFromSection(diagnostic.location, source))
+            .Str(fileLocation)
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala:1104]: Unrelated change. This fixes the compiler diagnostic output when there is no source available. It used to print `path:: error`, i.e., two consecutive colons. Which was weird.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 4]
```diff
@@ -154,29 +174,81 @@ private boolean typeCanOverride(MethodRootNode node, EnsoContext ctx) {
...
     Function function = resolveFunction(symbol, selfTpe, methodResolverNode);
     if (function == null) {
       throw new PanicException(
-              EnsoContext.get(this).getBuiltins().error().makeNoSuchMethod(self, symbol), this);
+          EnsoContext.get(this).getBuiltins().error().makeNoSuchMethod(self, symbol), this);
+    }
+    var resolvedFuncArgCount = function.getSchema().getArgumentsCount();
+    CallArgumentInfo[] invokeFuncSchema = invokeFunctionNode.getSchema();
+    // Check if this is a static method call on Any
+    if (isAnyEigenType(selfTpe) && arguments.length == resolvedFuncArgCount - 1) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I think this is correct. We want to find out if a method is defined on `Any` and treat it in a special way.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 5]
```diff
@@ -154,29 +174,81 @@ private boolean typeCanOverride(MethodRootNode node, EnsoContext ctx) {
...
+      // function is a static method on Any, so the first two arguments in `invokeFuncSchema`
+      // represent self arguments.
+      boolean selfArgSpecified = false;
+      if (invokeFuncSchema.length > 1) {
+        selfArgSpecified =
+            invokeFuncSchema[1].getName() != null && invokeFuncSchema[1].getName().equals("self");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: There is a class with `Constants`. Use it instead of hardcoding `"self"` in here.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 6]
```diff
@@ -154,29 +174,81 @@ private boolean typeCanOverride(MethodRootNode node, EnsoContext ctx) {
...
+
+      if (selfArgSpecified) {
+        // If there is a self named argument in the method call, we fall back to the old
+        // behavior - there will be no prepended Any.type self argument
+        assert arguments.length == invokeFunctionNode.getSchema().length;
+        return invokeFunctionNode.execute(function, frame, state, arguments);
+      }
+
+      Object[] argsWithPrependedSelf = new Object[arguments.length + 1];
+      argsWithPrependedSelf[0] = EnsoContext.get(this).getBuiltins().any().getEigentype();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java:232]: OKeyish if it works, but: Ideally the `self` should be set to the actual type which we are calling the function upon. When one does `Boolean.to_text` the `self` should be `Boolean`. I am not exactly sure what would be the consequences, but such behavior would fit the model I have in my had more and it could potentially simplify some code introduced by @hubertp to allow calling `Boolean.to_text`.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java [hunk 7]
```diff
@@ -154,29 +174,81 @@ private boolean typeCanOverride(MethodRootNode node, EnsoContext ctx) {
...
+      System.arraycopy(arguments, 0, argsWithPrependedSelf, 1, arguments.length);
+
+      if (invokeAnyStaticFunctionNode == null) {
+        CompilerDirectives.transferToInterpreter();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I think you want to also _invalidate_. Otherwise a compiled version of this method might remain in the JVM without noticing a new node `insert`ed...

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 8]
```diff
@@ -42,19 +42,64 @@ spec =
...
+            Any.x . to_text . should_equal "Any:Any"
+            Any.x self=Any . to_text . should_equal "Any:Any"
             Any.x self=With_X . should_equal "Any:With_X"
             Any.x self=With_Y . should_equal "Any:With_Y"
             Any.x (My_Type.Value 22) . should_equal "Any:(My_Type.Value 22)"
             Any.x (With_X.Value 22) . should_equal "Any:(With_X.Value 22)"
             Any.x (With_Y.Value 22) . should_equal "Any:With_Y(22)"
             Date.to_display_text . should_equal "Date"
 
+        Test.specify "static method calls on Any should have defaulted self argument to Any" <|
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Any_Spec.enso:61]: Regardless of my other comments, these tests are the most important thing. If they work & define the expected behavior, then we have a system we wanted.

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 9]
```diff
@@ -42,19 +42,64 @@ spec =
...
+            (Any.== Any Boolean) . should_be_false
+            (Any.== Boolean) . should_be_false
+            (Any.== Any) . should_be_true
+            (Any == Boolean) . should_be_false
+            (Any == Any) . should_be_true
+
+            # Any.to_text is a method that takes one argument (self)
+            Any.to_text . should_equal "Any"
+            Any.to_text self=Any . should_equal "Any"
+            Any.to_text self=Vector . should_equal "Vector"
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Any_Spec.enso:75]: +1

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 10]
```diff
@@ -42,19 +42,64 @@ spec =
...
+            Any.to_text self=[1,2,3] . should_equal "[1, 2, 3]"
+            Any.to_text Any . should_equal "Any"
+            Any.to_text Vector . should_equal "Vector"
+            Any.to_text [1,2,3] . should_equal "[1, 2, 3]"
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Any_Spec.enso:79]: I'd like to see a test with a method define on `Any` that takes additional arguments.

**Review by JaroslavTulach — APPROVED** [review]
I am not completely sure I get the implementation but the "observable effect" - e.g. how it looks to the are relatively fine. I'd like to see behavior of an `Any` method with argument however - we have to make sure that non-self arguments are applied first, and only when `self=something` is used, we specify the `self` argument.

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 10 above)
Comment (Akirathan) [reply test/Tests/src/Semantic/Any_Spec.enso:79]: What do you mean by additional arguments? A few lines down (https://github.com/enso-org/enso/pull/7033/files#diff-633d071799e116a57d56ddb9efdc589afaafaeea1ef615a7c07dff7b916242e3R81), there are tests for `Any.spec_method` that takes three arguments. Isn't that what you mean?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java:232]: `argsWithPrependedSelf` is `Object[]` that is passed to a `InvokeFunctionNode` that represents a static method call. These nodes expect *two self arguments* - the first one is always the eigen type of the type where the method is defined - in this case `Any.type`, the second `self` can be set by the user.

> When one does Boolean.to_text the self should be Boolean

And it is. This is the second `self` argument. In this line, I am setting the first `self` argument, which should be Any eigen type.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 5 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: Fixed in 43fbab3cd53fa2cf793a190550b6ecbe24b647e5

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java (hunk 7 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java]: I also think it is a better idea. Done in 45d7fa55777b6cb317dcee57ca653261c56f1888

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 2 above)
Comment (radeusgd) [inline test/Tests/src/Semantic/Any_Spec.enso]:
```suggestion
            Meta.should_be_a With_X.y Function
```

We have a more specific test for `is_a` that will provide better error messages, please use it. `should_be_true` should only be used as last resort, as currently it gives a pretty bad error message (`Expected False to be True at ...`) - we probably should add some `assert_true` that allows to add a custom message there.

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 11]
```diff
@@ -42,19 +42,64 @@ spec =
...
             Any.x (With_X.Value 22) . should_equal "Any:(With_X.Value 22)"
             Any.x (With_Y.Value 22) . should_equal "Any:With_Y(22)"
             Date.to_display_text . should_equal "Date"
 
+        Test.specify "static method calls on Any should have defaulted self argument to Any" <|
+            # Any.== is a method that takes two arguments (self other)
+            Meta.is_a (Any.==) Function . should_be_true
+            Meta.is_a (Any.== self=Boolean) Function . should_be_true
+            (Any.== self=Any Boolean) . should_be_false
+            (Any.== Any Boolean) . should_be_false
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Any_Spec.enso]:
```suggestion
            (Any.== Any Any) . should_be_true
```

Would be good to add a 'paired' one to match

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 12]
```diff
@@ -42,19 +42,64 @@ spec =
...
+            (Any == Boolean) . should_be_false
+            (Any == Any) . should_be_true
+
+            # Any.to_text is a method that takes one argument (self)
+            Any.to_text . should_equal "Any"
+            Any.to_text self=Any . should_equal "Any"
+            Any.to_text self=Vector . should_equal "Vector"
+            Any.to_text self=[1,2,3] . should_equal "[1, 2, 3]"
+            Any.to_text Any . should_equal "Any"
+            Any.to_text Vector . should_equal "Vector"
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Any_Spec.enso:78]: This is an interesting case and worth testing but I think these few more practical cases would be good to be tested too:

```
Vector.to_text . should_equal "Vector"
Text.to_text . should_equal "Text"
Number.to_text . should_equal "Number"
Integer.to_text . should_equal "Integer"
```

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 13]
```diff
@@ -42,19 +42,64 @@ spec =
...
+
+            # Any.spec_method is a method that takes three arguments (self, arg1, arg2)
+            Meta.is_a (Any.spec_method) Function . should_be_true
+            Meta.is_a (Any.spec_method Boolean) Function . should_be_true
+            Meta.is_a (Any.spec_method self=Boolean) Function . should_be_true
+            Meta.is_a (Any.spec_method self=Boolean Vector) Function . should_be_true
+            Any.spec_method Boolean Vector . should_equal "Any.spec_method:{Any}{Boolean}{Vector}"
+            Any.spec_method Any Boolean Vector . should_equal "Any.spec_method:{Any}{Boolean}{Vector}"
+            Any.spec_method Date Boolean Vector . should_equal "Any.spec_method:{Date}{Boolean}{Vector}"
+            Any.spec_method self=Any Boolean Vector . should_equal "Any.spec_method:{Any}{Boolean}{Vector}"
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Any_Spec.enso]: This behaviour looks very weird, but I guess it is the best we can do to satisfy the requirements we want from the static methods.

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 14]
```diff
@@ -42,19 +42,64 @@ spec =
...
+
+
+        Test.specify "instance methods on different types should not have defaulted self argument" <|
+            # Vector.contains has two arguments (self elem)
+            Vector.contains . to_text . contains "Vector.type.contains" . should_be_true
+            (Vector.contains 42) . to_text . contains "Vector.type.contains" . should_be_true
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Any_Spec.enso]:
```suggestion
            (Vector.contains [42]) . to_text . contains "Vector.type.contains" . should_be_true
```

Just to ensure this does not blow up with a type error in the future.

**Review by radeusgd — APPROVED** [review]
The Enso changes look good to me.

Please add a few more test cases that were requested.

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 12 above)
Comment (Akirathan) [reply test/Tests/src/Semantic/Any_Spec.enso:78]: Added in b4b93bc0ccf4f48b6bf93f679a15846f859e4c1b

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 15]
```diff
@@ -42,19 +42,69 @@ spec =
...
+            Text.to_text . should_equal "Text"
+            Number.to_text . should_equal "Number"
+            Integer.to_text . should_equal "Integer"
+
+            # Any.spec_method is a method that takes three arguments (self, arg1, arg2)
+            Meta.should_be_a (Any.spec_method) Function
+            Meta.should_be_a (Any.spec_method Boolean) Function
+            Meta.should_be_a (Any.spec_method self=Boolean) Function
+            Meta.should_be_a (Any.spec_method self=Boolean Vector) Function
+            Any.spec_method Boolean Vector . should_equal "Any.spec_method:{Any}{Boolean}{Vector}"
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Any_Spec.enso:91]: This is correct. `self` is defaulted and `Boolean` and `Vector` are the two arguments.

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 13 above)
Comment (JaroslavTulach) [reply test/Tests/src/Semantic/Any_Spec.enso]: I'd add:
```
Any.spec_method self=Date Boolean Vector . should_equal "Any.spec_method:{Date}{Boolean}{Vector}"
```
that's my preferred way to invoke `Any` method with explicit `self`.

File: test/Tests/src/Semantic/Any_Spec.enso [hunk 16]
```diff
@@ -42,19 +42,69 @@ spec =
...
+            Any.spec_method Any Boolean Vector . should_equal "Any.spec_method:{Any}{Boolean}{Vector}"
+            Any.spec_method Date Boolean Vector . should_equal "Any.spec_method:{Date}{Boolean}{Vector}"
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Any_Spec.enso:93]: I am surprised this works and `self=Date` - but probably that is OKeyish behavior.

Comment (radeusgd) [reply test/Tests/src/Semantic/Any_Spec.enso:93]: Indeed, I think it could be clearer if the `self` always had to be named if specified like this. What do you think?

Comment (Akirathan) [reply test/Tests/src/Semantic/Any_Spec.enso:93]: But this is the same semantics as for any other static method, e.g.:
```
> Vector.contains [42] 42
>>> true
> Vector.contains self=[42] 42
>>> true
```

I am surprised you find it confusing. To me, this is the least confusing part.

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 13 above)
Comment (Akirathan) [reply test/Tests/src/Semantic/Any_Spec.enso]: Added in d4f0b6d239a750aba1aa3291145b315e7ee47851

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 15 above)
Comment (Akirathan) [reply test/Tests/src/Semantic/Any_Spec.enso:91]: Exactly. This is the most important difference from "normal" static method invocation.

File: test/Tests/src/Semantic/Any_Spec.enso (hunk 16 above)
Comment (radeusgd) [reply test/Tests/src/Semantic/Any_Spec.enso:93]: Ah, right!

**Review by hubertp — APPROVED** [review]
