### PR TITLE
Fix missing edges

### LINKED ISSUE #8420: No connections and wrong types under nodes
In the below project, the connection is missing, and the second node consists of a single port (I cannot connect to the `this` argument). Moreover, the types under the nodes seem wrong (and they are right in the Code Editor diagnostics).

https://github.com/enso-org/enso/assets/3919101/4e00019e-a99b-440e-918f-4ae56bc30a2d

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes #8420
  - Fix missing edges
  - Fix displayed output type of node
  - Verify that undos properly restore edges

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue [hunk 1]
```diff
@@ -136,6 +136,7 @@ export const widgetDefinition = defineWidget(
       Ast.Tree.Type.UnaryOprApp,
       Ast.Tree.Type.Wildcard,
       Ast.Tree.Type.TextLiteral,
+      Ast.Tree.Type.Ident,
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue]: This will introduce unwanted ports on the right side of the access operator chains, e.g. expression `foo.bar.baz` should have 3 ports:
- `foo.bar.baz`
- `foo.bar`
- `foo`

With this change, the `bar` and `baz` alone will also have ports assigned, which is incorrect.

Comment (somebody1234) [reply app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue]: oh... i can't think of a way to make this work. do you have any ideas?

Comment (somebody1234) [reply app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue]: it seems like the problem is: we need to bail out of selecting *just `WidgetPort`s*, but not other widget types because we still need to render the actual AST subtree?

i was thinking that maybe we'd need to be able to un-bail-out of selecting `WidgetPort`s?
on one hand, *theoretically* they shouldn't be valid ASTs...
on the other hand, i'm assuming they're entirely possible to have, if they were already present when the file was originally opened.

Comment (somebody1234) [reply app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue]: it'd always be an option to create an extra class to mark something as needing to bypass `WidgetPort`, like `ForcePort` already does, but I'm not sure that's an ideal option...

it'd also be an option to be able to attach arbitrary metadata to an `AstExtended`... that for some reason should get passed to children. i don't imagine it'd be too bad implementation-wise... but it sounds like a headache to conceptualize.

**Comment by somebody1234** [comment]
@Frizi 
https://github.com/enso-org/enso/blob/b2a593fc7cb0113e3e6cf145c386161aa036316b/app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue#L69-L78

is it intentional that these are different? if so, it might be useful to add a comment explaining the difference

**Comment by farmaazon** [comment]
@somebody1234 could we quickly push a fix for output types in different PR?

**Comment by somebody1234** [comment]
@farmaazon can do. will extract out to another PR as soon as i can

**Comment by somebody1234** [comment]
now using an alternative approach.

requesting review from @kazcw as he may have a better idea which other AST nodes may require a `ForcePort`
(for now i think that's just any AST node that may be a parent of an `Ident`)

:warning: Note: Currently it is widgets themselves that create `ForcePort`s. for now I don't think there's an alternative as we MUST check the parent node type to have the correct behavior
  - I don't think it is feasible to include `ForcePort` as a new node type? although, it's possible to have a new custom node type like how we currently have `RawCode`
  - however, that means that *all* new widgets must remember to create `ForcePort`s as appropriate

The currently checked cases are:
- Vector literals (by `WidgetVector`)
- `PropertyAccess` (LHS only), `OprApp`, and `UnaryOprApp` (by `WidgetHierarchy`)

File: app/gui2/src/util/ast/extended.ts [hunk 2]
```diff
@@ -32,14 +32,28 @@ export class AstExtended<T extends Tree | Token = Tree | Token, HasIdMap extends
...
+  public static isTree<T extends OneOrArray<Ast.Tree.Type>>(
+    type?: T,
+    predicate?: (node: AstExtended<ExtractType<Ast.Tree, T>, boolean>) => boolean,
+  ) {
+    const ret = (obj: unknown): obj is AstExtended<ExtractType<Ast.Tree, T>, boolean> =>
       obj instanceof AstExtended && obj.isTree(type)
+    return predicate
+      ? (obj: unknown): obj is AstExtended<ExtractType<Ast.Tree, T>, boolean> =>
+          ret(obj) && predicate(obj)
+      : ret
```
Comment (Frizi) [inline app/gui2/src/util/ast/extended.ts]: Is this change used anywhere? Since we are planning to get rid of `AstExtended` rather soon, I'd like to avoid complicating it unnecessarily.

**Review by Frizi — APPROVED** [review]

File: app/gui2/src/util/ast/extended.ts (hunk 2 above)
Comment (somebody1234) [reply app/gui2/src/util/ast/extended.ts]: indeed it is not - i added it because i was planning on using it for a previous solution, will fix soon
