### PR TITLE
Fix visualisation FRP bugs.

### LINKED ISSUE #6561: Visualizations updates are not stable and leaving visualizations blank
### Discord username

_No response_

### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

During building up use-cases and demos we observed the decrease in visualizations stability. That include:
- [ ] visualization is blanked after finishing editing a node
- [ ] blank visualizations after nodes collapsing,
- [ ] blank visualization on an existing node with viz opened while uploading the new file,
- [ ] no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening,
- [ ] clicking on the drop-down to select a visualization is vanishing the visualization. 
### Expected behaviour

Visualizations should be updated with the data as soon as data are available.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

nightly 04.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #6770: Full-screen visualization is blank when opening it for the first time
Select an arbitrary node, and open a full-screen visualization before normal visualization - that will display blank full screen.
You need first to toggle normal visualization in order for the full-screen visualization to show anything. All the nodes seem to be affected.

[blank-full-viz.webm](https://github.com/enso-org/enso/assets/14013887/723d25eb-32ce-4878-a500-4b72ac722537)

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Fixes 
* Empty Visualization when opening a full-screen visualization directly without opening the visualization before. #6770

https://github.com/enso-org/enso/assets/1428930/5812ed03-652c-4a27-8e33-b85512ca11b6

* Empty visualization when opening the full-screen visualization before the data for the visualization has arrived. #6561

https://github.com/enso-org/enso/assets/1428930/d8e58f2d-f1b6-4b70-84fa-e917f6c0af1f

* Visualization is reset to default when reconnecting nodes #6673

https://github.com/enso-org/enso/assets/1428930/ac6cf79a-7147-4f13-9045-52599fb39900

* Redundant internal open/lose events caused by logic loops around the show/hide button, as well as many redundant layer setting/unsetting issues internal to the visualization code. 

Generally improves the logic around the visualization API by avoiding decentralized logic in different places and removing old code that is no longer needed. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 1]
```diff
@@ -125,29 +134,63 @@ pub mod background {
 // === Frp ===
 // ===========
 
-ensogl::define_endpoints! {
+/// Indicates the visibility state of the visualisation.
+#[derive(Clone, Copy, Debug, PartialEq)]
+pub enum ViewState {
+    /// Visualisation is permanently enabled and visible in thw graph editor. It is attached to a
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]:
```suggestion
    /// Visualisation is permanently enabled and visible in the graph editor. It is attached to a
```

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 2]
```diff
@@ -125,29 +134,63 @@ pub mod background {
...
+    /// Visualisation is enabled and visible in the graph editor in fullscreen mode. It occludes
+    /// the whole graph and can be interacted with.
+    Fullscreen,
+}
+
+impl Default for ViewState {
+    fn default() -> Self {
+        ViewState::Disabled
+    }
+}
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: Derivable.

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 3]
```diff
@@ -125,29 +134,63 @@ pub mod background {
...
+    /// Indicates whether the visualisation is visible in the graph editor. It is always visible
+    /// when not disabled.
+    pub fn visible(&self) -> bool {
+        !matches!(self, ViewState::Disabled)
+    }
+
+    /// Indicates whether the visualisation is fullscreen mode.
+    pub fn is_fullscreen(&self) -> bool {
+        matches!(self, ViewState::Fullscreen)
+    }
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: Inconsistent `is_`

**Review by kazcw — APPROVED** [review]

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 4]
```diff
@@ -1,4 +1,12 @@
-//! This module defines the `Container` struct and related functionality.
+//! This module defines the `Container` struct and related functionality. This represent the view
+//! a visualisation int he graph editor and includes a visual box that contains the visualisaiton,
+//! a action bar that allows setting the visualisation type.
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]:
```suggestion
//! a visualisation in the graph editor and includes a visual box that contains the visualisaiton,
//! and the action bar that allows setting the visualisation type.
```

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 5]
```diff
@@ -1,4 +1,12 @@
...
+//!
+//! The `[Container]` struct is responsible for managing the visualisation and action bar and
+//! providing a unified interface to the graph editor. This includes ensuring that the visualisation
+//! is correctly positioned, sized and layouted in its different `ViewState`s (which include the
+//! `Enabled`, `Fullscreen` and `Preview` states). Importantly, this also includes layer management
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: You can put `ViewState` in [] (`[ViewState]`) making them link to the structure; then I think it's not necessary to list enum variants.

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 6]
```diff
@@ -1,4 +1,12 @@
...
+//!  and ensuring that the visualisation is correctly layered with respect to other scene objects.
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: I don't quite understand the "layer management". Does visualization create new layers? What "correct layering" means? Is visualization split into layers?

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 7]
```diff
@@ -125,29 +134,63 @@ pub mod background {
...
-ensogl::define_endpoints! {
+/// Indicates the visibility state of the visualisation.
+#[derive(Clone, Copy, Debug, PartialEq)]
+pub enum ViewState {
+    /// Visualisation is permanently enabled and visible in thw graph editor. It is attached to a
+    /// single node and can be moved and interacted with when selected.
+    Enabled,
+    /// Visualisation is disabled and hidden in the graph editor.
+    Disabled,
+    /// Visualisation is temporarily enabled and visible in the graph editor. It should be placed
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs:147]: Is any difference between "enabled" and "visible"? Before, "enabled" meant that the visualization "eye" was toggled on. Visualization could be visible and not enabled (in case of Preview) and enabled but not visible (if there's error on the node - I think we miss that variant here).

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 8]
```diff
@@ -536,30 +564,25 @@ impl Container {
...
+
+            visualisation_uninitialised <- input.set_visualization.map(|t| t.is_none());
+            input_type_uninitialised <- input.set_vis_input_type.is_some().not();
+            uninitialised <- visualisation_uninitialised && input_type_uninitialised;
+            default_visualisation <- uninitialised.on_change().on_true().map(|_| {
                 Some(visualization::Registry::default_visualisation())
             });
-            vis_input_type <- frp.set_vis_input_type.on_change();
+            vis_input_type <- input.set_vis_input_type.on_change();
             vis_input_type <- vis_input_type.gate(&visualisation_uninitialised).unwrap();
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: I know it's an older code, but the name is bad, as it says nothing about the type being updated only when visualization is uninitialized.

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 9]
```diff
@@ -536,30 +564,25 @@ impl Container {
...
-            visualisation_uninitialised <- frp.set_visualization.map(|t| t.is_none());
-            default_visualisation <- visualisation_uninitialised.on_true().map(|_| {
+            eval input.set_view_state((state) model.apply_view_state(*state));
+            output.view_state <+ input.set_view_state.on_change();
+            output.fullscreen <+ output.view_state.map(|state| state.is_fullscreen()).on_change();
+            output.visible <+ output.view_state.map(|state| state.visible()).on_change();
+            output.size <+ input.set_size.on_change();
+
+            visualisation_uninitialised <- input.set_visualization.map(|t| t.is_none());
+            input_type_uninitialised <- input.set_vis_input_type.is_some().not();
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: The name "visualization_uninitialized" is a bit unfortunate. I think "non-chosen" says better what it is.

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 10]
```diff
@@ -570,16 +593,16 @@ impl Container {
...
-            chooser.frp.set_vis_input_type <+ frp.set_vis_input_type;
+            chooser.frp.set_vis_input_type <+ input.set_vis_input_type;
         }
 
 
         // === Cycling Visualizations ===
 
         frp::extend! { network
-            vis_after_cycling <- frp.cycle_visualization.map3(&frp.visualisation,&frp.vis_input_type,
+            vis_after_cycling <- input.cycle_visualization.map3(&output.visualisation,&output.vis_input_type,
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]:
```suggestion
            vis_after_cycling <- input.cycle_visualization.map3(&output.visualisation, &output.vis_input_type,
```

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 11]
```diff
@@ -589,19 +612,19 @@ impl Container {
...
-                frp.set_visualization,
+                input.set_visualization,
                 selected_definition,
                 vis_after_cycling,
                 default_visualisation);
             new_vis_definition <- vis_definition_set.on_change();
-            let preprocessor   =  &frp.source.preprocessor;
-            frp.source.visualisation <+ new_vis_definition.map(f!(
-                [model,action_bar,app,preprocessor](vis_definition) {
+            let preprocessor =  &output.preprocessor;
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]:
```suggestion
            let preprocessor = &output.preprocessor;
```

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 12]
```diff
@@ -685,6 +705,16 @@ impl Container {
...
             }));
+
+
+            // === Data Update ===
+
+            data <- input.set_data.unwrap();
+            has_data <- input.set_data.is_some();
+            reset_data <- data.sample(&new_vis_definition).gate(&has_data);
+            data_update <- any(&data,&reset_data);
+            eval  data_update ((t) model.set_visualization_data(t));
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]:
```suggestion
            eval data_update ((t) model.set_visualization_data(t));
```

File: app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs [hunk 13]
```diff
@@ -389,7 +389,11 @@ impl ActionBar {
             hide              <- any(mouse_out_no_menu,remote_click);
             eval_ hide (model.hide());
 
-            frp.source.visualisation_selection <+ visualization_chooser.chosen_entry;
+            // The action bar does not allow to deselect the visualisation, so we prohibit these
+            // events, which can occur on re-initialization.
+            has_selection <- visualization_chooser.chosen_entry.is_some();
+            frp.source.visualisation_selection
+                <+ visualization_chooser.chosen_entry.gate(&has_selection);
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs]: `.filter_map(|entry| *entry)` does it in one line. And I use it a lot - maybe we could make `filter_some` node?

**Review by farmaazon — APPROVED** [review]
The code looks good, with some comments below. But I'm worried we have regressions in displaying errors (the visualization should be hidden on error). Should be checked during QA.

**Review by wdanilo — APPROVED** [review]
Amazing that it's here! Skipping my code review seeing code reviews of Kaz and Adam :)

File: app/gui/view/graph-editor/src/component/visualization/container.rs (hunk 6 above)
Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/component/visualization/container.rs]: This is about EnsoGL layers and management of occlusion. I clarified this now.

File: app/gui/view/graph-editor/src/component/visualization/container.rs (hunk 7 above)
Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/component/visualization/container.rs:147]: This logic is now decoupled; thus, the visualization is either visible or not. While the button's state is managed independently. I will double-check the button has the correct state during preview.

File: app/gui/view/graph-editor/src/component/visualization/container.rs (hunk 8 above)
Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/component/visualization/container.rs]: I've updated the naming. But it does get a bit verbose.

File: app/gui/view/graph-editor/src/component/visualization/container.rs (hunk 9 above)
Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/component/visualization/container.rs]: I've updated the naming.

File: app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs (hunk 13 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs]: I think `.unwrap()` already does exactly that.

**Comment by vitvakatu** [comment]
# QA Report 🔴 

Most importantly, error visualization is indeed affected, as @farmaazon noticed in his review.

Hovering the output with the mouse displays both the error message and a visualization. Switching visualization with the icon doesn't work, but using `space` or `shift-space` shortcuts toggles it.

https://github.com/enso-org/enso/assets/6566674/60e34015-5c36-43df-aa85-98ec88249e0d


Also, I noticed that on complex projects a lot of visualizations disappear after loading. For example, for COVID project on my machine:


https://github.com/enso-org/enso/assets/6566674/74430157-508c-458c-aaac-7cf8c90f784d

**Comment by MichaelMauderer** [comment]
> Most importantly, error visualization is indeed affected, as @farmaazon noticed in his review.

This should now be fixed.

> Also, I noticed that on complex projects a lot of visualizations disappear after loading. For example, for COVID project on my machine:

I can reproduce this also on develop and this seems to be #6724.

**Comment by vitvakatu** [comment]
@MichaelMauderer `shift-tab` hotkey still opens fullscreen vis on a node with error. Is this intentional?

**Comment by MichaelMauderer** [comment]
> @MichaelMauderer `shift-tab` hotkey still opens fullscreen vis on a node with error. Is this intentional?

I think that does not make sense, even if it works like that on develop. So, it is fixed now to stop the empty vis from opening.

**Comment by vitvakatu** [comment]
QA: passed 🟢
