### PR TITLE
Equality does not swallow errors

### LINKED ISSUE #9283: Equality is 'swallowing' dataflow errors
## Actual behavior

```
> 42 == (Error.throw "foo")
>>> false
> 42 != (Error.throw "foo")
>>> true
> (Error.throw "foo") == 42
>>> (Error: 'foo')
> (Error.throw "foo") != 42
>>> (Error: 'foo')
> (Error.throw "foo") == (Error.throw "foo")
>>> (Error: 'foo')
```

I have just noticed that I can compare dataflow errors with values and it just treats the error as any other value.

Note that this only works if the dataflow error is on the right side of equality.

## Expected behavior

First of all, the equality operation (and `!=` as well, of course) should be symmetrical.

I think the dataflow error should be propagated like in all other cases.

For example, for comparisons the error is obviously propagated:
```
> 42 < (Error.throw "foo")
>>> (Error: 'foo')
> (Error.throw "foo") < 42
>>> (Error: 'foo')
```

### Motivation

The error should be propagated by default. If the user really wants to compare error payload, they can use `.catch`.

I encountered this when I was working on this piece of code:
```
if organization_name != Enso_User.current.name then Error.throw (Unimplemented.throw "Currently only resolving paths for the current user is supported.") else
    ... do stuff...
```

I was surprised why I get the `Unimplemented` error instead of `Unauthorized` when I was not logged in.

So `Enso_User.current` raised `Unauthorized` dataflow error, but it was swallowed by `!=` and instead entered this error branch.

I had to work around that by:
```
current_user_name = Enso_User.current.name
current_user_name.if_not_error <|
	if organization_name != current_user_name then ... else ...
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #9283

### Pull Request Description

`42 == (Error.throw "foo")` now correctly returns an `Error` rather than False

### Important Notes

The error was in the wrong usage of the `org.enso.interpreter.dsl.AcceptsError` DSL annotation.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java [hunk 1]
```diff
@@ -82,8 +81,7 @@ public static EqualsNode getUncached() {
    * @param other the other object
    * @return {@code true} if {@code self} and {@code that} seem equal
    */
-  public boolean execute(
-      VirtualFrame frame, @AcceptsError Object self, @AcceptsError Object other) {
+  public boolean execute(VirtualFrame frame, Object self, Object other) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java:84]: If a builtin method does not handle `DataflowError` itself, it should not annotate parameters with `@AcceptsError`. In other words, if `@AcceptsError` annotation is used, there should be a specialization that handles DataflowErrors.

**Review by radeusgd — APPROVED** [review]

**Comment by radeusgd** [comment]
Could you please also remove the workaround that was added because of the bug?

It should be enough to revert this commit: https://github.com/enso-org/enso/commit/32f876d803599587d453e5fe5cda044fa150529f

**Comment by Akirathan** [comment]
> Could you please also remove the workaround that was added because of the bug?
> 
> It should be enough to revert this commit: [32f876d](https://github.com/enso-org/enso/commit/32f876d803599587d453e5fe5cda044fa150529f)

@radeusgd Reverted in 805785dfcba47fb109cb5d13eaa845ac9c08b1c5

**Review by JaroslavTulach — APPROVED** [review]
