### PR TITLE
Detect background libgraal compilations in `ContextUtils.close()`

### LINKED ISSUE #14293: Memory leak on nightly checks
We are seeing some random OOMs when running our nightly extra tests on Mac runners e.g.,
```
 INFO ide_ci::program::command: sbt ℹ️ [info] Test run org.enso.interpreter.test.EqualsTest finished: 0 failed, 0 ignored, 19 total, 3.341s
 INFO ide_ci::program::command: sbt ℹ️ java.lang.OutOfMemoryError: Java heap space
 INFO ide_ci::program::command: sbt ℹ️ Dumping heap to <redacted>/enso/engine/runtime-integration-tests/target/scala-2.13/java_pid49785.hprof ...
 INFO ide_ci::program::command: sbt ℹ️ Heap dump file created [4323755974 bytes in 6.489 secs]
 INFO ide_ci::program::command: sbt ℹ️ [error] Test org.enso.interpreter.test.VectorSortTest failed: java.lang.AssertionError: EnsoContext can be GCed when context is closed ref still alive: org.enso.interpreter.runtime.EnsoContext@47d1bf07, took 0.0 sec
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.test.utils.MemoryUtils.assertReference(MemoryUtils.java:43)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.test.utils.MemoryUtils.assertGC(MemoryUtils.java:35)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.test.utils.ContextUtils.close(ContextUtils.java:149)
 INFO ide_ci::program::command: sbt ℹ️ [error]     at org.enso.test.utils.ContextUtils$CustomStatement.evaluate(ContextUtils.java:560)
 INFO ide_ci::program::command: sbt ℹ️ [error]     ...
```

Thanks to https://github.com/enso-org/enso/pull/14251 we now have [heap dumps](https://github.com/enso-org/enso/actions/runs/19285357400) in summaries so can investigate further where do we have leaks.
It's possible leaks not only happen on MacOS but also on other runners but Mac's are a bit underpowered which in this case is to our advantage.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- to address #14293
- as analyzed in the [November 17 Summary](https://github.com/enso-org/enso/issues/14293#issuecomment-3540267080)
- let's detect [background libgraal compilations](https://github.com/enso-org/enso/issues/14293#issuecomment-3533283116) and wait until they are over
- collect a log of `assertGC` progress to provide some insight into the garbage collecting process for further analysis

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
- guys, if you see these errors more frequently (I don't) then please do some testing
- I tried some tricks with `VectorSortTest` (it is known to require a lot of compilations):
```
sbt:enso> runtime-integration-tests/testOnly *VectorSortTest
[info] Test run org.enso.interpreter.test.VectorSortTest finished: 0 failed, 0 ignored, 1 total, 6.12s
```
- e.g. by default it runs fine and requires 6s to finish
- let's enable `assertGC` now:
```diff
$ git diff
diff --git engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java
index 5809700275..f34579dd0b 100644
--- engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java
+++ engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java
@@ -23,7 +23,7 @@ import org.junit.runner.RunWith;
 @RunWith(Theories.class)
 public class VectorSortTest {
   @ClassRule
-  public static final ContextUtils ctxRule = ContextUtils.newBuilder().assertGC(false).build();
+  public static final ContextUtils ctxRule = ContextUtils.newBuilder().assertGC(true).build();
 
   private static Value sortFunc;
   private static Value equalsFunc;
```
- and the run also succeeds, but it takes **17s** and prints a lot of info from the collected log:
```
System.gc()
Allocating 16384 bytestion-tests / Test / testOnly 16s
Found running compiler thread: TruffleCompilerThread-49
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.doCompile(Native Method)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.doCompile(LibGraalHotSpotTruffleCompiler.java:101)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedTruffleRuntime.compileImpl(OptimizedTruffleRuntime.java:898)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedTruffleRuntime.doCompile(OptimizedTruffleRuntime.java:881)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:66)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:60)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.CompilationTask.call(CompilationTask.java:251)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.CompilationTask.call(CompilationTask.java:58)
  at java.base@25.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:328)
  at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
  at java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
  at java.base@25.0.1/java.lang.Thread.runWith(Thread.java:1487)
  at java.base@25.0.1/java.lang.Thread.run(Thread.java:1474)
  at app/org.graalvm.truffle.runtime/com.oracle.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:418)
Sleeping
Slept 1s, trying again.

System.gc()
Allocating 32768 bytes
Creating and closing org.graalvm.polyglot.Context@6b9071ac

[info] Test run org.enso.interpreter.test.VectorSortTest finished: 0 failed, 0 ignored, 1 total, 17.007s
```
- we don't want to slow the CI down by eleven seconds, so let's leave `assertGC(false)` in the `VectorSortTest`
- but this experiment shows the _libgraal compilation detector_ infrastructure is working fine

File: lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java [hunk 1]
```diff
@@ -11,18 +13,23 @@ final class MemoryUtils {
...
+    var log = new PrintWriter(buffer);
     var memory = expectGC ? new ArrayList<>() : null;
     var retry = 3;
     for (var i = 1L; ; i *= 2) {
       try {
         var size = (int) Math.min(i, Integer.MAX_VALUE / 2);
         if (i >= 64) {
-          tryHarderToGc();
+          tryHarderToGc(log);
+          flushLog(buffer);
```
Comment (JaroslavTulach) [inline lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java:25]: - this is a _diagnostic_ `flushLog` 
- with it we can see in the logs that some tests are struggling to `assertGC`, but succeed at the end
- otherwise we'd only see the log on `OutOfMemoryError` and then the `.hprof` file is better source of info
- btw. read here on [instructions to analyze](https://github.com/enso-org/enso/pull/14219#discussion_r2476452008) the `.hprof` file

Comment (JaroslavTulach) [reply lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java:25]: - I see no traces of this `flushLog` in https://github.com/enso-org/enso/actions/runs/19422046657?pr=14301 run
- neither on Linux, nor Windows
- I don't see any Mac OS X runs however

File: lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java [hunk 2]
```diff
@@ -59,20 +65,53 @@ private static void assertReference(
...
+        if (foundCompilation) {
+          log.println("Found running compiler thread: " + threadName);
+          for (var frame : t.getValue()) {
+            log.println("  at " + frame);
+          }
+          try {
+            log.println("Sleeping");
+            Thread.sleep(1000);
+            log.println("Slept 1s, trying again.");
+            return;
```
Comment (hubertp) [inline lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java:101]: I think it would be best to have some retry mechanism to reduce chances of this error. But let's see if this change helps.

**Review by hubertp — APPROVED** [review]

**Comment by dougxc** [comment]
Reminds me a bit of the type of problem mitigated by https://github.com/openjdk/jdk/pull/18044.

**Review by Akirathan — APPROVED** [review]

File: lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java (hunk 2 above)
Comment (JaroslavTulach) [reply lib/java/test-utils/src/main/java/org/enso/test/utils/MemoryUtils.java:101]: There is a [retry mechanism](https://github.com/enso-org/enso/pull/14301/files#diff-b20a1f29a95701c115ff273b1858c857a4a3c95f5ca0b35895bff9aadd1cf2ecR20)
