### PR TITLE
--jvm tries to find Java executable system-wide.

### LINKED ISSUE #11274: enso --jvm fails with InvalidModuleDescriptorException
Enso built with `engine-runner/buildNativeImage` fails when given `--jvm` cmd line opt with:
```
$ enso --jvm --run tmp.enso
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/helidon-webclient-websocket-4.0.8.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 65.0
```

Broken with #10823.

```[tasklist]
### Tasks
- [x] Fix the `--jvm` cmd line opt for native image
- [ ] Add test that this works on a simple script
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #11274

### Pull Request Description

Fixes `--jvm` option, given to the native image. This was failing on my machine, because when given `--jvm` option, the runner was trying to find the `java` executable from the distribution manager's runtime (on my system located in `~/.local/share/enso/runtime`) and it used the first runtime found. But the first runtime on my system is JDK 17.

The `--jvm` option now tries to:
- Find a JDK from the distribution manager that has the same version as the JDK used for building the engine.
  - If there is not an exact version match, it tries to find a runtime from distribution manager that is *newer*.
  - If none, fallback to system-wide search
- System-wide search tries to find `java` from `$JAVA_HOME` and from `$PATH`. But this is just a fallback.

### Important Notes

- Added test to Engine CI jobs that pass `--jvm` argument to a native image of engine-runner
  - ea3af5ffbca6dc439690142251426b4c167bca98
- `runtime-version-manager` sbt project migrated to a JPMS module
- `engine-runner` now depends on `runtime-version-manager`.
- Removed unnecessary stuff in `runtime-version-manager` dealing with outdated `gu` Graal Updater utility.
- Extracted [GraalVersionManager](https://github.com/enso-org/enso/blob/1455b025cb8e5141409ea96b75577e8884265a70/lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java) from [RuntimeVersionManager](https://github.com/enso-org/enso/blob/d2e8994700fd36228f7873f040668013e643190a/lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by JaroslavTulach — COMMENTED** [review]
> The --jvm option now tries to find java executable from JAVA_HOME and from PATH. If that is not found, the distribution manager's runtimes are used as a fallback.

I'd say that this is the **wrong order**. The target audience of Enso users is unlikely to have proper JVM installed in the system. Searching for a system JVM is good for us, developers, but not for our target audience.

> trying to find the java executable from the distribution manager's runtime (on my system located in ~/.local/share/enso/runtime) and it used the first runtime found. But the first runtime on my system is JDK 17.

It is good we have such a failing example! What is the layout of your Enso JVM runtimes? That is an important information for your #11274 bug report.

Anyway, the `enso` launcher should:
- search _managed runtimes_ (in `~/.local/share/enso/runtime`) first
- ignore the outdated ones - e.g. having JVM spec version lower than `21` (right now)
- select the exact match, if found
- select acceptable match (e.g. newer JDK), if found - probably with some warning printed
- if no match found among _managed runtimes_, fallback to system JVM - with some warning printed, if the JDK isn't exactly the one we expect

Would the above steps work for your system setup, Pavel?

**Comment by Akirathan** [comment]
> Searching for a system JVM is good for us, developers, but not for our target audience.

That is a good point.

> It is good we have such a failing example! What is the layout of your Enso JVM runtimes? That is an important information for your https://github.com/enso-org/enso/issues/11274 bug report.

```
$ ls -l ~/.local/share/enso/runtime
drwxrwxr-x 1 pavel pavel 612 Nov  1  2023 graalvm-ce-java17.0.7-23.0.0
drwxrwxr-x 1 pavel pavel 114 Nov 28  2023 graalvm-ce-java21.0.1-23.1.0
drwxrwxr-x 1 pavel pavel 114 Feb 29  2024 graalvm-ce-java21.0.2-23.1.2
drwxrwxr-x 1 pavel pavel 114 Apr 16  2024 graalvm-ce-java21.0.2-24.0.0
```

> Would the above steps work for your system setup, Pavel?

Certainly. Sounds like a good plan. I will see what I can do.

**Comment by JaroslavTulach** [comment]
> ```
> $ ls -l ~/.local/share/enso/runtime
> drwxrwxr-x 1 pavel pavel 612 Nov  1  2023 graalvm-ce-java17.0.7-23.0.0
> drwxrwxr-x 1 pavel pavel 114 Nov 28  2023 graalvm-ce-java21.0.1-23.1.0
> drwxrwxr-x 1 pavel pavel 114 Feb 29  2024 graalvm-ce-java21.0.2-23.1.2
> drwxrwxr-x 1 pavel pavel 114 Apr 16  2024 graalvm-ce-java21.0.2-24.0.0
> ```

It would be great, if we selected the same JDK as used for the build (however that's `graalvm-community-openjdk-21.0.2+13.1` and I don't see it) and then try any JDK21 (probably the highest - e.g. `graalvm-ce-java21.0.2-24.0.0`) maybe with a warning...

> Sounds like a good plan. I will see what I can do.

[DistributionManager](https://github.com/enso-org/enso/blame/867c77d5cc91056d0fe9987906b54af6696fa13b/lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala#L134) shall do most of the selection logic. CCing @radeusgd to give us an _expert guidance_.

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    }
+    if (isJavaOnPath()) {
+      return "java";
+    }
+    var javaInRuntime = findJavaExecutableInDistributionRuntimes();
+    if (javaInRuntime != null) {
+      return javaInRuntime.toAbsolutePath().toString();
+    }
+    return null;
+  }
```
Comment (radeusgd) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: I think the precedence should actually look into distribution _first_ and only afterwards use system JVM.

The whole purpose of `ensoup` was to manage JVMs related to the engine versions, so that the engine is run with the right compatible JVM and not a random version that may be incompatible with it (I guess it used to be more important before Truffle 'got unchained').

I think ideally we should first to run the JVM version _required by the engine_ if it's found in the distribution. Then we can fallback to using the logic of searching `JAVA_HOME` and `Path`.

Ideally I'd also check the JVM version and log a warning if the version required by engine does not match the version that has been found.

Comment (radeusgd) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: > JVMs related to the engine versions

This version is stored in the engine's manifest - see for example `built-distribution/enso-engine-0.0.0-dev-windows-amd64/enso-0.0.0-dev/manifest.yaml`.

It contains fields: `graal-vm-version` and `graal-java-version`.
You can see `lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/Manifest.scala` for the logic of loading the manifest and extracting the `GraalVMVersion` from it. 

We have a `GraalCEReleaseProvider` which translates this `GraalVMVersion` into a strategy for downloading it from GitHub - but you probably don't need this.

The function `graalDirectoryForVersion` in `RuntimeVersionManager` takes `GraalVMVersion` and gives you back the directory name under which this JVM version will be sitting in the `$ENSO_DATA_DIRECTORY/runtime` (installed by `ensoup`).

I guess you could factor out the `Manifest` and `graalDirectoryForVersion` utilities to a common package and you could use it to figure out the JVM version tied to the engine.

----

Btw. the manifest also contains a `jvm-options` field. I'd be very happy if we could keep the _(sometimes changing)_ options in a single place.

Comment (radeusgd) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: I guess if you want to check if the JVM version is correct you need to call `java --version` and somehow parse its output and compare with `graal-java-version`.

e.g. I get
```
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)
```

I guess I want to extract the second word from the first line. At least for now that seems to work. But we can update the logic whenever the version format of expected JVM changes - unexpected format just means it's not the JVM we expect :)

**Comment by Akirathan** [comment]
As of 586fc73aa3e6a8706cbc2e4353a2286ff2c169a6:
- I have extracted [GraalVersionManager](https://github.com/enso-org/enso/blob/1455b025cb8e5141409ea96b75577e8884265a70/lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java) from [RuntimeVersionManager](https://github.com/enso-org/enso/blob/d2e8994700fd36228f7873f040668013e643190a/lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala)
  - Among other things, `GraalVersionManager` is able to list, and sort, all the installed runtimes in the distribution (in my case, it is inside `~/.local/share/enso/runtime`)
- `engine-runner` depends on `runtime-version-manager`
  - For that, I had to convert `runtime-version-manager` project to JPMS module.
- Removed unnecessary stuff in `runtime-version-manager` dealing with outdated `gu` Graal Updater utility.
- JavaFinder knows the exact version that was used for building - https://github.com/enso-org/enso/blob/1455b025cb8e5141409ea96b75577e8884265a70/engine/runner/src/main/java/org/enso/runner/JavaFinder.java#L58
  - And tries to find the runtime from the distribution with the exact version, or newer version

Only when there is no newer runtime found in the managed distribution runtimes, `JAVA_HOME` and system `java` is tried.

File: lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+    if (pathOpt != null) {
+      GraalRuntime runtime;
+      try {
+        runtime = loadGraalRuntime(pathOpt);
+      } catch (Exception e) {
+        throw new UnrecognizedComponentError(
+            "The runtime "
+                + version
+                + "is already installed, but cannot be "
+                + "loaded du to "
```
Comment (radeusgd) [inline lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java]:
```suggestion
                + "loaded due to "
```

**Review by radeusgd — APPROVED** [review]
Looks great!

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: Possibly better way than parsing output of `java -version` is to run a small program on the JVM:
```java
public static void main(String... args) {
  System.out.prinltn(System.getProperty("java.vm.version"));
  // etc.
}
```
and just read the output line by line without the need to parse words.

File: build.sbt [hunk 3]
```diff
@@ -4328,15 +4332,34 @@ lazy val `connected-lock-manager-server` = project
...
-      "org.scalatest"              %% "scalatest"        % scalatestVersion % Test,
-      akkaHttp
+      "org.scalatest"              %% "scalatest"        % scalatestVersion % Test
+    ),
+    Compile / moduleDependencies ++= Seq(
+      "org.apache.commons" % "commons-compress" % commonsCompressVersion,
+      "org.slf4j"          % "slf4j-api"        % slf4jVersion
+    ),
+    Compile / internalModuleDependencies := Seq(
+      (`cli` / Compile / exportedModule).value,
```
Comment (JaroslavTulach) [inline build.sbt:4361]: `cli`? Is that really needed?

File: build.sbt [hunk 4]
```diff
@@ -4328,15 +4332,34 @@ lazy val `connected-lock-manager-server` = project
...
+      (`distribution-manager` / Compile / exportedModule).value,
+      (`downloader` / Compile / exportedModule).value,
```
Comment (JaroslavTulach) [inline build.sbt:4363]: `downloader`? Right now all downloads should be disabled. Necessary?

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+   */
+  static String findJavaExecutable() {
+    var javaInRuntime = findJavaExecutableInDistributionRuntimes();
+    if (javaInRuntime != null) {
+      return javaInRuntime.toAbsolutePath().toString();
+    }
+    logger.warn("No appropriate JDK found in the distribution runtimes. Trying system-wide JDK.");
+    var javaHome = System.getenv("JAVA_HOME");
+    if (javaHome != null) {
+      var java = new File(javaHome, "bin/java").getAbsoluteFile();
```
Comment (JaroslavTulach) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: This is not Windows `\` friendly. Try: `new File(new File(javaHome, "bin"), "java")` - btw. where is the `.exe` extension for Windows!?

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+      if (java.exists()) {
+        return java.getAbsolutePath();
+      }
+    }
+    if (isJavaOnPath()) {
+      return "java";
```
Comment (JaroslavTulach) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: Does that work on Windows?

File: lib/scala/runtime-version-manager/src/main/java/module-info.java [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+  requires org.enso.semver;
+  requires org.enso.scala.yaml;
+  // For com.typesafe.scalalogging.Logger
+  requires org.enso.scala.wrapper;
+  requires org.enso.version.output;
+
+  exports org.enso.runtimeversionmanager;
+  exports org.enso.runtimeversionmanager.cli;
+  exports org.enso.runtimeversionmanager.components;
+  exports org.enso.runtimeversionmanager.runner;
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager/src/main/java/module-info.java:21]: That's a lot of exported packages. Shouldn't the API be cleaned and put into a single package?

File: lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+import org.enso.distribution.DistributionManager;
+import org.enso.distribution.Environment;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import scala.jdk.javaapi.CollectionConverters;
+
+/**
+ * Utility class that finds installed managed runtimes (Graal JDK) from {@link DistributionManager}.
+ */
+public class GraalVersionManager {
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java]: `
```suggestion
public final class GraalVersionManager {
```

**Review by JaroslavTulach — APPROVED** [review]
Overall it looks very nice and clean. Some doubts:
- does it work on Windows?
- possibly too many exports from the new `module-info`

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java (hunk 1 above)
Comment (radeusgd) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: Cool - that indeed sounds better, I didn't think of that

File: build.sbt (hunk 3 above)
Comment (Akirathan) [reply build.sbt:4361]: This dependency has been there for ages: https://github.com/enso-org/enso/blob/b89db13046a174b815afb95e90143de5698b80d2/build.sbt#L4376. And yes, it is needed, because `runtime-version-manager` uses types from `cli`.

File: build.sbt (hunk 4 above)
Comment (Akirathan) [reply build.sbt:4363]: `runtime-version-manager` contains [GithubAPI](https://github.com/enso-org/enso/blob/f3bc88b91e5f694467935a417552d65daf92bb86/lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/github/GithubAPI.scala) that uses stuff from `downloader`. But it is not actually called. Strictly speaking, it is not necessary, but I don't want to try to split the code right now.

File: lib/scala/runtime-version-manager/src/main/java/module-info.java (hunk 7 above)
Comment (Akirathan) [reply lib/scala/runtime-version-manager/src/main/java/module-info.java:21]: It should. Like all the other Scala-only projects that are now historical remnants. I suggest revisiting this once we take a look into `launcher` (`ensoup`) and related projects.

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java (hunk 6 above)
Comment (Akirathan) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: I don't expect it to work on windows. This is a fallback that is currently only usable for devs and not anyone else. For all the other use-cases, the java exe should be found in the installed distribution runtimes.

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java (hunk 5 above)
Comment (Akirathan) [reply engine/runner/src/main/java/org/enso/runner/JavaFinder.java]: Made Windows friendly in fd52bbf63a3ea7a0c05d66243bbf18dfe8b210a8

File: build/build/src/engine/context.rs [hunk 9]
```diff
@@ -686,7 +687,25 @@ pub async fn runner_sanity_test(
             .run_ok()
             .await;
 
-        test_base.and(test_internal_base).and(test_geo)
+        let all_cmds = test_base.and(test_internal_base).and(test_geo);
+
+        // The following test does not actually run anything, it just checks if the engine
+        // can accept `--jvm` argument and evaluates something.
+        if TARGET_OS != OS::Windows {
```
Comment (Akirathan) [inline build/build/src/engine/context.rs:694]: When the test runs on the CI, there is nothing inside `ENSO_DATA_DIRECTORY`. The `--jvm` argument first tries to find any appropriate JDK in the `ENSO_DATA_DIRECTORY/runtime` directory, but on the CI, it is empty. The fallback is to search in `JAVA_HOME` env var or on `PATH`, but that works only on Linux. Let's just keep this sanity check on Linux for now.

Comment (Akirathan) [reply build/build/src/engine/context.rs:694]: Trying to run the tests also on Windows again in https://github.com/enso-org/enso/pull/11500/commits/fb25d57ed8cad3f563489440353444eaec4d6706

**Comment by Akirathan** [comment]
Windows CI does not have `java.exe` on PATH - https://github.com/enso-org/enso/actions/runs/11840014687/job/32992849858?pr=11500#step:7:2539 . Removing this test from Windows again in 049b991eaa4c4a699c43a9a73ac2f3fa43de5219

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">--jvm tries to find Java executable system-wide. · enso-org/enso@fb25d57</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - --jvm tries to find Java executable system-wide. · enso-org/enso@fb25d57</div></blockquote>

**Comment by radeusgd** [comment]
> Windows CI does not have `java.exe` on PATH - [enso-org/enso/actions/runs/11840014687/job/32992849858?pr=11500#step:7:2539](https://github.com/enso-org/enso/actions/runs/11840014687/job/32992849858?pr=11500#step:7:2539) . Removing this test from Windows again in [049b991](https://github.com/enso-org/enso/commit/049b991eaa4c4a699c43a9a73ac2f3fa43de5219)
> 
> >  GitHub**[--jvm tries to find Java executable system-wide. · enso-org/enso@fb25d57](https://github.com/enso-org/enso)**Enso Analytics is a self-service data prep and analysis platform designed for data teams. - --jvm tries to find Java executable system-wide. · [fb25d57](https://github.com/enso-org/enso/commit/fb25d57)

What about `JAVA_HOME/bin`?

File: build/build/src/engine/context.rs (hunk 9 above)
Comment (hubertp) [reply build/build/src/engine/context.rs:694]: So that didn't work?

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+        return javaExe.toAbsolutePath().toString();
+      }
+    }
+    logger.warn("No JDK found in JAVA_HOME. Trying java on PATH.");
+    if (isJavaOnPath()) {
+      var javaExe = isOnWindows() ? "java.exe" : "java";
+      logger.warn("Falling back to java on PATH: {}", javaExe);
+      return javaExe;
+    }
+    logger.warn("No JDK found on PATH. Cannot start the runtime.");
```
Comment (hubertp) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java:55]: Shouldn't you be checking `ENSO_JVM_PATH` as well?

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 11]
```diff
@@ -0,0 +1,110 @@
...
+    return null;
+  }
+
+  private static boolean isOnWindows() {
```
Comment (hubertp) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java:59]: Could just use `OS.isWindows()` instead? It's already a dependency, right?

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+      return newerRuntime.get().javaExecutable();
+    }
+    return null;
+  }
+
+  private static boolean isJavaOnPath() {
+    try {
+      ProcessBuilder processBuilder;
+      if (isOnWindows()) {
+        processBuilder = new ProcessBuilder("java.exe", "-h");
```
Comment (hubertp) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java:99]: nit: 
```suggestion
        processBuilder = new ProcessBuilder("java.exe", "-v");
```

File: engine/runner/src/main/java/org/enso/runner/JavaFinder.java [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+      } else {
+        processBuilder = new ProcessBuilder("java", "-h");
```
Comment (hubertp) [inline engine/runner/src/main/java/org/enso/runner/JavaFinder.java:101]:
```suggestion
        processBuilder = new ProcessBuilder("java", "-v");
```

**Review by hubertp — APPROVED** [review]
I'm a bit surprised this fails Windows PR check. What's the reason?

**Comment by JaroslavTulach** [comment]
Congratulation to getting thru CI checks.
