### PR TITLE
Autoscoping should not escape True and False

### LINKED ISSUE #9765: Autoscoping should not escape `True` and `False`.
The tag values produced should not auto-scope `Boolean.True`  and `Boolean.False` they should be entered just as `True` and `False`.

Currently it results in an error:
image

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #9765 

Changelog:
- fix: do not use autoscope syntax for Boolean constructors

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala [hunk 1]
```diff
@@ -1,3 +1,5 @@
+package org.enso.compiler.test.context
+
```
Comment (4e6) [inline engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala:2]: Removed probably by mistake https://github.com/enso-org/enso/commit/931baa42768febf7003455081c5354c22efe6b6e#diff-351fde5aa2d3fd1c17f0af68d70d9c7ab9f959effec19078b1949d86da36502d

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala [hunk 2]
```diff
@@ -658,8 +658,10 @@ final class SuggestionBuilder[A: IndexedSource](
       Identifier.Qualified(name)
     def mkAutoScopeCall(identifier: Identifier): String =
       identifier match {
-        case Identifier.Qualified(name)   => name.toString
-        case Identifier.Unqualified(name) => s"..$name"
+        case Identifier.Qualified(name)      => name.toString
+        case Identifier.Unqualified("True")  => "True"
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala]: Can we avoid hardcoding `True` and `False`? Cannot the builder detect that the `name` is actually re-exported from the library under the same name?

Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala]: Yes, this smells fishy. Hardcoded values in otherwise constant-free logic.

Comment (4e6) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala]: The issue was about the True and False constructors.

> Cannot the builder detect that the name is actually re-exported from the library under the same name?

I'll try and see if there is enough info to implement this

Comment (4e6) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala]: > Cannot the builder detect that the name is actually re-exported from the library under the same name?

@JaroslavTulach re-exports are computed after the suggestions are built https://github.com/enso-org/enso/blob/32c3f5f3e8936ac5fb98c5c4adfe4feb87d62df3/engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java#L558-L578

To make this logic work, I need to make the tag values calculation as a third step:
- build suggestions
- compute re-exports
- compute tag values

I can return to this issue after the ydoc is finished

Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala]: OK, feel free to integrate the "quick fix".

**Review by JaroslavTulach — APPROVED** [review]
I don't like the fact that `True` and `False` are hardcoded... but [feel free to integrate the fix](https://github.com/enso-org/enso/pull/9797#discussion_r1584355744).
