### PR TITLE
Fix `NumberParser` to avoid `thousandSeparator==decimalPoint` and prefer US decimal format

### LINKED ISSUE #7930: Ensure that numbers `#.###` are parsed as float, not int by default
Run the following example:
```
from Standard.Base import all
from Standard.Table import all

my_file_content = """
    txt,num-var,num-fix2,num-fix3
    A,  1.1,    1.20,    1.300
    B,  2.22,   2.22,    2.222
    C,  3.333,  3.33,    3.333

main =
    f = File.new "tmp.csv"
    IO.println (my_file_content+'\n' . write f)

    IO.println "Plain text:"
    IO.println (f.read Plain_Text)

    IO.println "Default config (Delimited):"
    f.read.print

    IO.println "Delimited - custom decimal point, no thousand separator (default):"
    value_formatter_1 = Data_Formatter.Value decimal_point="."
    f.read (Delimited value_formatter=value_formatter_1) . print

    IO.println "Delimited - custom decimal point:"
    value_formatter_2 = Data_Formatter.Value decimal_point="." thousand_separator="_"
    f.read (Delimited value_formatter=value_formatter_2) . print

    f.delete
```

### Actual behaviour

```
{working_dir}\tmp.csv
Plain text:
txt,num-var,num-fix2,num-fix3
A,  1.1,    1.20,    1.300
B,  2.22,   2.22,    2.222
C,  3.333,  3.33,    3.333

Default config (Delimited):
   | txt | num-var | num-fix2 | num-fix3
---+-----+---------+----------+----------
 0 | A   | 1.1     | 1.2      | 1300
 1 | B   | 2.22    | 2.22     | 2222
 2 | C   | 3.333   | 3.33     | 3333

Delimited - custom decimal point, no thousand separator (default):
   | txt | num-var | num-fix2 | num-fix3
---+-----+---------+----------+----------
 0 | A   | 1.1     | 1.2      | 1300
 1 | B   | 2.22    | 2.22     | 2222
 2 | C   | 3.333   | 3.33     | 3333

Delimited - custom decimal point:
   | txt | num-var | num-fix2 | num-fix3
---+-----+---------+----------+----------
 0 | A   | 1.1     | 1.2      | 1.3
 1 | B   | 2.22    | 2.22     | 2.222
 2 | C   | 3.333   | 3.33     | 3.333
```

### Expected behaviour

I'm not sure about the default behaviour - maybe indeed the current behaviour of treating this as integers with `.` thousand separator is OK.

But surely, the `Delimited - custom decimal point, no thousand separator (default):` is wrong.
Currently it still parses the values as integers, even though **I have explicitly set** `decimal_point='.'`. This is completely unintuitive.

Apparently, to make the change effective, I also had to change the `thousand_separator='_'` (by default it is supposed to be none `thousand_separator=''`).

There should be no need to **additionally** change the `thousand_separator`. Just setting `decimal_point='.'` should be enough to parse the third column as decimals:
```
Delimited - custom decimal point, no thousand separator (default):
   | txt | num-var | num-fix2 | num-fix3
---+-----+---------+----------+----------
 0 | A   | 1.1     | 1.2      | 1.3
 1 | B   | 2.22    | 2.22     | 2.222
 2 | C   | 3.333   | 3.33     | 3.333
```

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

Closes #7930 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java [hunk 1]
```diff
@@ -10,331 +10,392 @@
...
 import org.graalvm.polyglot.Context;
 
+import java.util.ArrayList;
 import java.util.HashMap;
+import java.util.List;
 import java.util.Map;
+import java.util.Objects;
 import java.util.regex.Pattern;
 
-/** A parser for numbers.
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java:17]: Ugh, I accidentally clicked reformat and lots of indentation changed here.

Please view this file with ['Hide whitespace changes'](https://github.com/enso-org/enso/pull/7946/files?diff=unified&w=1), sorry for the inconvenience.

I could try to revert them but 1. good to keep the formatting in sync and 2. I don't have a separate commit so it will not be that easy.

Comment (radeusgd) [reply std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java:17]: Hmm apparently I was able to undo the formatting :)

**Review by jdunkerley — APPROVED** [review]
Great to get this fixed.

File: std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java (hunk 1 above)
Comment (somebody1234) [reply std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java:17]: speaking of hiding whitespace changes though, i use this chrome extension to permanently enable it:
https://chrome.google.com/webstore/detail/github-whitespace/fnpkdafamnbjoldglihkjjdicofghccm

**Review by GregoryTravis — APPROVED** [review]
