### PR TITLE
Stateless parser API

### LINKED ISSUE #11121: Parser crashing in native code due to multi-threaded access
```
C  [libenso_parser.dylib+0x2e81c]  alloc::collections::btree::search::_$LT$impl$u20$alloc..collections..btree..node..NodeRef$LT$BorrowType$C$K$C$V$C$alloc..collections..btree..node..marker..LeafOrInternal$GT$$GT$::search_tree::h2955aec13fd254fd+0x90
C  [libenso_parser.dylib+0x23e98]  Java_org_enso_syntax2_Parser_getUuidHigh+0x2c
j  org.enso.syntax2.Parser.getUuidHigh(JJJ)J+0 org.enso.syntax
j  org.enso.syntax2.Message.getUuid(JJ)Ljava/util/UUID;+6 org.enso.syntax
j  org.enso.syntax2.Tree.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Tree;+940 org.enso.syntax
j  org.enso.syntax2.Tree.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Tree;+1902 org.enso.syntax
```
or 
```
Stack: [0x0000000287a38000,0x0000000287c3b000],  sp=0x0000000287c38920,  free space=2050k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libenso_parser.dylib+0x2e81c]  alloc::collections::btree::search::_$LT$impl$u20$alloc..collections..btree..node..NodeRef$LT$BorrowType$C$K$C$V$C$alloc..collections..btree..node..marker..LeafOrInternal$GT$$GT$::search_tree::h2955aec13fd254fd+0x90
C  [libenso_parser.dylib+0x23e98]  Java_org_enso_syntax2_Parser_getUuidHigh+0x2c
j  org.enso.syntax2.Parser.getUuidHigh(JJJ)J+0 org.enso.syntax
j  org.enso.syntax2.Message.getUuid(JJ)Ljava/util/UUID;+6 org.enso.syntax
j  org.enso.syntax2.Tree.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Tree;+940 org.enso.syntax
j  org.enso.syntax2.Tree.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Tree;+1902 org.enso.syntax
j  org.enso.syntax2.MultiSegmentAppSegment.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/MultiSegmentAppSegment;+17 org.enso.syntax
j  org.enso.syntax2.Tree.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Tree;+3350 org.enso.syntax
j  org.enso.syntax2.Line.deserialize(Lorg/enso/syntax2/Message;)Lorg/enso/syntax2/Line;+17 org.enso.syntax
```
[hs_err_pid90180.log](https://github.com/user-attachments/files/17040248/hs_err_pid90180.log)
[hs_err_pid90473.log](https://github.com/user-attachments/files/17040249/hs_err_pid90473.log)

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Stateless (static) parser interface. Buffer-reuse optimization is now hidden within `Parser` implementation. Fixes #11121 and prevents similar bugs.

### Important Notes

- Also simplify `EnsoParser` API, exposing only a higher-level interface.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java [hunk 1]
```diff
@@ -6,48 +6,23 @@
...
-  public EnsoParser() {
-    Parser p;
-    try {
-      p = Parser.create();
-    } catch (LinkageError err) {
-      err.printStackTrace();
-      throw err;
-    }
-    this.parser = p;
+public final class EnsoParser {
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java:10]: Please put here `private EnsoParser() {}` so nobody can create instances of this class - without explicit `private`  constructor a default `public` constructor is generated. The _"beauty"_ of API design in OOP...

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java [hunk 2]
```diff
@@ -6,48 +6,23 @@
...
-  }
-
-  public Module generateModuleIr(Tree t, Map<Location, UUID> idMap) {
-    var treeToIr = new TreeToIr(idMap);
-    return treeToIr.translate(t);
-  }
-
-  public scala.Option<Expression> generateIRInline(Tree t) {
-    return TreeToIr.MODULE.translateInline(t);
+  public static scala.Option<Expression> compileInline(CharSequence src) {
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java:26]: Making these methods `static` is a nice simplification of the usage.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala [hunk 3]
```diff
@@ -97,14 +96,12 @@ final class ChangesetBuilder[A: TextEditor: IndexedSource](
...
           val source = Source.newBuilder("enso", value, null).build
-          Using(new EnsoParser) { compiler =>
-            compiler
-              .generateIRInline(compiler.parse(source.getCharacters()))
-              .flatMap(_ match {
-                case ir: Literal => Some(ir.setLocation(oldIr.location))
-                case _           => None
-              })
-          }.get
+          EnsoParser
```
Comment (JaroslavTulach) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala:99]: Is this the place that triggered parallel usage of `EnsoParser`, @4e6, @hubertp? Edits are probably coming into the system in different thread than execution thread... e.g. they might cause the [parallel access to the parser](https://github.com/enso-org/enso/issues/11121#issuecomment-2362502673)

File: engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala [hunk 4]
```diff
@@ -31,42 +31,6 @@ trait CompilerTest extends AnyWordSpecLike with Matchers with CompilerRunner
 trait CompilerRunner {
   // === IR Utilities =========================================================
 
-  /** An extension method to allow converting string source code to IR as a
-    * module.
-    *
-    * @param source the source code to convert
-    */
-  implicit class ToIrModule(source: String) {
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala:39]: I am glad to see removal of such a huge boiler plate code in our testing infrastructure thanks to making the methods `static`.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 5]
```diff
@@ -5,11 +5,22 @@
 import java.nio.ByteBuffer;
 import java.nio.ByteOrder;
 import java.nio.charset.StandardCharsets;
-
-public final class Parser implements AutoCloseable {
-  private static void initializeLibraries() {
+import java.util.concurrent.atomic.AtomicBoolean;
+
+public final class Parser {
+  static AtomicBoolean initialized = new AtomicBoolean(false);
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: `private` and `final` in addition to `static`.

Comment (JaroslavTulach) [reply lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: Or rather: `private volatile boolean initialized` - we don't need any _atomic_ operations and their behavior.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 6]
```diff
@@ -5,11 +5,22 @@
...
+
+  private static void ensureInitialized() {
+    // Optimization: Skip finding and initializing the library when it's definitely already been
+    // done.
+    // Note that this inexpensive check may produce false negatives: Nothing prevents multiple
+    // threads from proceeding to library initialization concurrently (before any thread has
+    // completed initialization), but that is harmless; library initialization is thread-safe and
+    // idempotent.
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: I am afraid we will have problems in _native image_ - e.g. `engine-runner/buildNativeImage`. Native image may run initialization during _build time_ - before taking snapshot of the heap. Then (during runtime of the EXE file) the field could already be `true` and no library loaded yet.

Build of `engine-runner/buildNativeImage` is included in the CI - e.g. once we get green, things are ok...

File: lib/rust/parser/jni/src/lib.rs [hunk 7]
```diff
@@ -16,6 +16,7 @@ use jni::objects::JClass;
 use jni::sys::jobject;
 use jni::sys::jstring;
 use jni::JNIEnv;
+use std::cell::UnsafeCell;
```
Comment (JaroslavTulach) [inline lib/rust/parser/jni/src/lib.rs]: "Unsafe" Rust!? Wouldn't it be better to use some "safe" data structure? `Vector`?

File: lib/rust/parser/jni/src/lib.rs [hunk 8]
```diff
@@ -165,34 +146,11 @@ pub extern "system" fn Java_org_enso_syntax2_Parser_getMetadata(
...
-pub extern "system" fn Java_org_enso_syntax2_Parser_freeState(
-    _env: JNIEnv,
-    _class: JClass,
-    state: u64,
-) {
-    if state != 0 {
-        let state = unsafe { Box::from_raw(state as usize as *mut State) };
-        drop(state);
-    }
+pub extern "system" fn Java_org_enso_syntax2_Parser_freeBuffers(_env: JNIEnv, _class: JClass) {
```
Comment (JaroslavTulach) [inline lib/rust/parser/jni/src/lib.rs]: Is it still necessary to `freeBuffers` from Java usage? I don't see it happening in all the places that do some parsing...

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 9]
```diff
@@ -75,82 +88,58 @@ private static boolean searchFromDirToTop(Throwable chain, File root, String...
...
-
-  private Parser(long stateIn) {
-    stateUnlessClosed = stateIn;
-  }
-
-  private static native long allocState();
+  private Parser() {}
 
-  private static native void freeState(long state);
+  private static native void freeBuffers();
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: This method seems to be unused!

**Review by JaroslavTulach — COMMENTED** [review]
Allowing use of the Rust parser from multiple threads at (some small cost) will simplify its (clueless) usage from JVM.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala (hunk 3 above)
Comment (4e6) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala:99]: I can see that the compilation and applying edits use different locks, so they can potentially overlap. On the other hand, the whole compilation job is locked preventing parallel executions, so I don't see how it can happen

File: lib/rust/parser/jni/src/lib.rs (hunk 7 above)
Comment (kazcw) [reply lib/rust/parser/jni/src/lib.rs]: Globally-scoped data (such as thread-local state in this case) is not inherently `safe` to mutate in Rust; some kind of `Cell` is needed to allow it. The options here are `RefCell` (which is essentially a runtime-checked *single-threaded* mutex) or `UnsafeCell` (which allows access without any runtime checks).
The soundness requirement of `UnsafeCell` is that it is not used to establish multiple references to its contained data concurrently with any of the references being mutators; in this case that property is ensured by limiting the scope of borrows from `STATE`--no borrow derived from `STATE` escapes the function that obtains it. Rust lifetimes make this easy to enforce, so we don't need the runtime overhead of the assertion that `RefCell` would use to make this `safe`.

**Comment by kazcw** [comment]
I moved the thread-local buffer-recycling logic to the Java bindings, to keep the Rust code threading-agnostic in case we would like to compile it to WASM in the future.

File: lib/rust/parser/jni/src/lib.rs (hunk 8 above)
Comment (kazcw) [reply lib/rust/parser/jni/src/lib.rs]: I think the Rust library should offer a way to free the resources (offering allocate but not free just seems wrong on principle), but as currently used on the Java side there's not much reason to do so (at most one state is maintained per thread, and they will simply be forgotten with the rest of the heap when the process exits).

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 10]
```diff
@@ -8,81 +8,174 @@
...
+        return Tree.deserialize(message);
+      } catch (BufferUnderflowException | IllegalArgumentException e) {
+        LoggerFactory.getLogger(this.getClass())
+            .error("Unrecoverable parser failure for: {}", input, e);
+        throw e;
+      }
+    }
+
+    @Override
+    public void close() {
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: I don't think there is anyone who can call `close()` now! We need to associated an instance of Worker with `ReferenceQueue` and clean it up when a `Thread` finishes or it is not used for a long time. Otherwise we'll be leaking Rust memory...

File: lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java [hunk 11]
```diff
@@ -0,0 +1,54 @@
+package org.enso.syntax2;
+
+import java.lang.ref.*;
+import java.util.Collections;
+import java.util.IdentityHashMap;
+import java.util.Set;
+
+public final class FinalizationManager {
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java]: I assume this is not a `public` API - please remove the `public` keywords in this file.

File: engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserMultiThreadedTest.java [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+            main = %n
+            """
+              .replace("%n", "" + number);
+      cases.add(
+          () -> {
+            return EnsoParser.compile(code);
+          });
+    }
+
+    var results = ForkJoinPool.commonPool().invokeAll(cases);
```
Comment (JaroslavTulach) [inline engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserMultiThreadedTest.java:29]: This is a port of a test introduced by
- #11174

into this branch. It just replaces the `EnsoParser` instance with a static method call.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala [hunk 13]
```diff
@@ -69,7 +70,6 @@ class Compiler(
     if (config.outputRedirect.isDefined)
       new PrintStream(config.outputRedirect.get)
     else context.getOut
-  private lazy val ensoCompiler: EnsoParser = new EnsoParser()
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:72]: Looks like the original code was buggy. The `Compiler` should have implemented `Closable` interface and call `ensoCompiler.close()` on the `EnsoParser`. I am not sure what's the overhead of a single `EnsoParser` instance and its natively allocated memory, but this must have leaked a lot during unit test execution!
- #10793

@hubertp did reduce the memory, but the Rust parser native part might now even have been visible in the JVM heap dump - only in RSS...

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 14]
```diff
@@ -1,88 +1,190 @@
...
+  /* Worker-thread state */
 
-    var whereAmI = Parser.class.getProtectionDomain().getCodeSource().getLocation();
-    File root;
-    try {
-      root = new File(whereAmI.toURI()).getParentFile();
-    } catch (URISyntaxException ex) {
-      root = new File(".").getAbsoluteFile();
+  private static final FinalizationManager finalizationManager = new FinalizationManager();
+  private static final Thread finalizationThread = new Thread(finalizationManager.createRunner());
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: This thread is unfortunate overhead. These are some options to avoid it:
- check the `FinalizationManager` queue before parsing starts - used by [WeakHashMap.exprungeStaleEntries()](https://github.com/openjdk/jdk/blob/47c10694c66bc131c8a5e1572340415b8daaba08/src/java.base/share/classes/java/util/WeakHashMap.java#L375)
- use [Cleaner](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ref/Cleaner.html)
- leave the cleanup up to the user - e.g. continue to provide instances and `close()` operations

Own `Thread` adds overhead. The `Cleaner` might be better, but there [seems to be a thread](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java#L110) per each `Cleaner` anyway. `exprungingStaledParser` might be good, but may leave some of the latest parser(s) pending for cleanup. We do get a [shutdown callback in the interpreter](https://github.com/enso-org/enso/blob/2fbd0aa92b7cb0c557dc37480ddb267ce8ad1fb9/engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java#L290) - e.g. we can explicitly request cleanup of `EnsoContext.getCompiler()` parser workers...


#### Best Option? Exprunging stale & Close

Having `exprungeStaleParsers()` check and a way to trigger it (or request shutdown of all existing) when `EnsoContext.shutdown()` would do the trick too without need for any special `Thread` or decisions of GC.

Comment (hubertp) [reply lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: Can we name it? I often look into thread dump and hunting down unnamed ones is a real PITA.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala [hunk 15]
```diff
@@ -700,7 +696,7 @@ class Compiler(
     * @return A Tree representation of `source`
     */
   def parseInline(source: CharSequence): Tree =
-    ensoCompiler.parse(source)
+    Parser.parse(source)
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:699]: Having `EnsoParser` a few lines above and here `Parser` it really begs a question: "What's the difference?"/"Which one should I use?" Wouldn't it better for `EnsoParser.parse` to simply forward to `Parser.parse` to hide that?

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala (hunk 3 above)
Comment (hubertp) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala:99]: I would rather bet that it is related to visualizations.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala (hunk 15 above)
Comment (kazcw) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala:699]: I prefer not to expose two different levels of abstraction from `EnsoParser`, so that `EnsoParser` methods output `IR` but not `Tree`. Backend parser-users work with `IR` exclusively, except the single caller of this `parseInline` method. The caller uses the `Tree` API to validate whether an input is *inline*. If we were to rewrite those few lines of code to use the `IR` API, we would be able to treat the entire `Tree` API as an internal implementation detail of the parser.

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala [hunk 16]
```diff
@@ -1351,6 +1351,17 @@ class RuntimeVisualizationsTest extends AnyFlatSpec with Matchers {
       )
     )
 
+    val attachVisualizationResponses =
```
Comment (kazcw) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:1354]: This test is [failing in CI](https://github.com/enso-org/enso/actions/runs/11057235037/job/30720561171#step:7:3916). It looks to me like it is a nondeterministic failure related to `sequentialExecution = false` command delays, and not related to this changeset. The observed failure mode is for all execution updates to show the result of executing the post-modification module. I think this would occur if delaying is applied to the `attachVisualization` commands, and not to the `textEdit` command, so that the edit is performed before the visualizations are attached.

Comment (JaroslavTulach) [reply engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:1354]: CCing @4e6

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala:99]: Yes, [this stacktrace](https://github.com/enso-org/enso/issues/11121#issuecomment-2368849241) proofs the problem is in visualizations invoking `DebugEvalNode`

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 17]
```diff
@@ -6,159 +6,237 @@
...
+        threadWorker.set(worker);
       }
-      System.load(path.getAbsolutePath());
-    } catch (NullPointerException | IllegalArgumentException | LinkageError e) {
-      if (searchFromDirToTop(e, root, "target", "rust", "parser-jni", name)) {
+    }
+    return worker;
+  }
+
+  private static final ThreadLocal<Worker> threadWorker = new ThreadLocal<>();
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: There is [initialValue](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ThreadLocal.html#initialValue()) method that might be useful for handling the initialization.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 18]
```diff
@@ -6,159 +6,237 @@
...
+
+  public static void freeAll() {
+    for (var finalizer : finalizationManager.getRegisteredFinalizers()) finalizer.run();
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java:70]: I'd move this code into `FinalizationManager.runAllFinalizers()` to keep more of encapsulation.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java [hunk 19]
```diff
@@ -0,0 +1,60 @@
...
+      ref = referenceQueue.poll();
+    }
+  }
+
+  /**
+   * @return The finalizers that have been registered, and have not yet been run.
+   *     <p>This does not de-register the finalizers; they will still be run as usual after their
+   *     reference objects become unreachable.
+   */
+  Iterable<Runnable> getRegisteredFinalizers() {
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java:38]: I guess we want to guarantee that each finalizer is executed only once. That wouldn't be guaranteed if we two threads call `Parser.freeAll()` at the same time. My solution would be:
```
FinalizationReference[] toClean;
synchronized (finalizers) {
  toClean = finalizers.toArray(new FinalizationReference[0]);
  finalizers.clean();
}
for (var f : toClean) {
  // clean
}
```
Still we need to guarantee that no `runPendingFinalizers` is called at the same time and calls the same `f.run()`.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 20]
```diff
@@ -6,159 +6,237 @@
...
+  }
+
+  /* Worker-thread state */
+
+  private static final FinalizationManager finalizationManager = new FinalizationManager();
+
+  private static Worker getWorker() {
+    var worker = threadWorker.get();
+    if (worker == null) {
+      finalizationManager.runPendingFinalizers();
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java]: I am surprised the cleanup of `runPendingFinalizers()` is called only when a new `Worker` for a thread is created. I would assume `runPendingFinalizers()` should be called more frequently - whenever `getWorker()` is called.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java [hunk 21]
```diff
@@ -6,159 +6,237 @@
...
 
-  private static native ByteBuffer parseTree(long state, ByteBuffer input);
+      private Finalizer(AtomicLong state) {
+        this.state = state;
+      }
 
-  private static native ByteBuffer parseTreeLazy(long state, ByteBuffer input);
+      @Override
+      public void run() {
+        freeState(state.getAndSet(0));
```
Comment (JaroslavTulach) [inline lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java:155]: I see. This guarantees each Rust pointer is cleaned only once.

**Review by JaroslavTulach — APPROVED** [review]
I'd call `runPendingFinalizers()` more frequently. Anyway overall it looks fine.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java (hunk 18 above)
Comment (kazcw) [reply lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java:70]: This is intentionally using a low-level API:
`freeAll` is designed to be safe to call at any time. It drops current retained buffers, without clearing the registry. This way, we can call it from `EnsoContext::shutdown` without relying too much on the expectation that there will be only one `EnsoContext` in the process and nothing will use the parser after it shuts down. If that assumption became incorrect in the future, dropping buffers unnecessarily would have some performance impact, but wouldn't result in any state corruption or memory leak.
To support this `getRegisteredFinalizers` exposes the finalizers, allowing the caller here to make use of a property that it knows holds of its finalizers: Calling them more than once would be harmless. `FinalizationManager` could offer a `runAllFinalizersWithoutDeregistering`, but I'd prefer it to provide one low-level method that allows the caller to make use of any known special properties of the finalizers.

File: lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java (hunk 19 above)
Comment (kazcw) [reply lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java:38]: Double-free/free-during-use are prevented locklessly.

**Comment by JaroslavTulach** [comment]
What happens when there is a Rust code working on a buffer and some other thread drops it?

File: lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java (hunk 18 above)
Comment (JaroslavTulach) [reply lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java:70]: The fact that finalizers can be called multiple time isn't easily to spot from the code...

**Comment by kazcw** [comment]
> What happens when there is a Rust code working on a buffer and some other thread drops it?

The parsing thread "checks out" the `state` for the duration of the operation:
https://github.com/enso-org/enso/pull/11147/files#diff-e237fc34931809c65628b8bcde58e32add8959b8e66940c46a5f63f557530302R169-R181

So that particular parsing thread's buffer won't be dropped by the `freeAll` call, but will eventually dropped if the parser becomes unreferenced.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/11147">Stateless parser API by kazcw · Pull Request #11147 · enso-org/enso</a></strong></div><div>Pull Request Description
Stateless (static) parser interface. Buffer-reuse optimization is now hidden within Parser implementation. Fixes #11121 and prevents similar bugs.
Important Notes

Also sim...</div></blockquote>
