### PR TITLE
Vector.map & State

### LINKED ISSUE #6656: State is lost inside of `Vector.map`
Run the following repro:
```
from Standard.Base import all
import Standard.Base.Runtime.State

main =
    State.run Number 0 <|
        IO.println (State.get Number)
        ["A", "B"].each x->
            IO.println "Vector.each: "+x+": "+(State.get Number).to_text
        ["X", "Y"].map x->
            IO.println "Vector.map: "+x+": "+(State.get Number).to_text
```

## Actual result

```
0
Vector.each: A: 0
Vector.each: B: 0
Execution finished with an error: State is not initialized for type Number.
        at <enso> <anonymous><arg-0>(state_is_lost.enso:10:47-62)
        at <enso> <anonymous><arg-1>(state_is_lost.enso:10:46-71)
        at <enso> <anonymous><arg-1>(state_is_lost.enso:10:24-71)
        at <enso> <anonymous>(state_is_lost.enso:10:13-71)
        at <enso> <anonymous>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Vector.enso:519:36-55)
        at <enso> Vector.map(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Vector.enso:519:9-55)
        at <enso> state_is_lost.main<arg-1>(state_is_lost.enso:9-10)
        at <enso> state_is_lost.main(state_is_lost.enso:5-10)
```

## Expected result

```
0
Vector.each: A: 0
Vector.each: B: 0
Vector.map: X: 0
Vector.map: Y: 0
```

### LINKED ISSUE #6955: @widgets for extension functions of `Table` may not be found
As experienced in #6925, the `primary_key` annotation on `select_into_database_table` operation seems to be not registered.

### Actual behaviour

image

The widget on `primary_key` is a Vector Editor but it only allows to add a `Nothing`, not the actual column names as expected. Checking `Widgets.get_widget_json` we can see that the annotation for `@primary_key` seems to not be applied for some reason.

### Expected behaviour

The `"primary_key"` widget JSON should not be `null` - it is defined to be `Widget_Helpers.make_column_name_vector_selector`.

The above should then allow the vector editor to display the proper column selector dropdown.

### Context

We checked if this may be due to the fact that `select_into_database_table` was defined on renamed types:
```
import Standard.Table.Data.Table as In_Memory_Table

...

@primary_key ...
In_Memory_Table.select_into_database_table : ...
In_Memory_Table.select_into_database_table self ... primary_key ... =
    ...
```
but we split the extensions file into separate versions for in-memory and Database Tables, allowing to get rid of the renames and the issue persisted, so it is probably something else.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #6656 by invoking the function with `InvokeFunctionNode` and not `InteropLibrary`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java [hunk 1]
```diff
@@ -57,23 +62,46 @@ public boolean isInstrumentable() {
...
+     * @param arguments the arguments passed to the function.
+     */
+    public FunctionCall(Node ctx, Function function, State state, Object[] arguments) {
+      this(findModuleScope(ctx), function, state, arguments);
+    }
+
+    private static ModuleScope findModuleScope(Node ctx) {
+      return switch (ctx.getRootNode()) {
+        case EnsoRootNode root -> root.getModuleScope();
+        case null -> null;
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: is this case needed at all?

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java [hunk 2]
```diff
@@ -85,23 +113,31 @@ boolean isExecutable() {
...
+        @Cached InteropApplicationNode interopApplicationNode,
+        @CachedLibrary(limit = "10") DynamicObjectLibrary objects
+      ) {
+        var args = Arrays.copyOf(
+          functionCall.getArguments(), functionCall.getArguments().length + arguments.length
+        );
+        System.arraycopy(arguments, 0, args, functionCall.getArguments().length, arguments.length);
+
+        var state = functionCall.state;
+        var old = objects.getOrDefault(state.getContainer(), 43L, null);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: Where is this `43L` magic constant coming from?

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: I think this should be a constant somewhere in the source code, so that we can easily find all of its usages.

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: Probably a unique key for the state. Create a constant for that?

**Review by GregoryTravis — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
With a24134d I can see

image

I hope that's correct. Now we need to _"just"_ write some tests and polish the implementation.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: `getRootNode()` may return `null`. It shouldn't, but it may. `switch` statement would yield `NullPointerException` when that would happen without this `case null` line as `default` doesn't match `null` values by default.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: The benefit of `43L` is:
- it is a valid Enso value
- anyone can type it without worrying about (compile or runtime) dependencies

E.g. `43L` is good enough for prototyping, but yes, we need a real constant instead of `43L`:
- where to put it?
- how to make it accessible from all the places we needed it?
- how to make it unique (unlike `43L` which anyone can use)?
- how to make it inaccessible from other places?

File: lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java [hunk 3]
```diff
@@ -70,6 +70,7 @@ public void generate(
               + "\"\"\""
               + moduleOwnerInfo
               + ")");
+      out.println("@ImportStatic(" + ownerClazz.fullyQualifiedName() + ".class)");
```
Comment (JaroslavTulach) [inline lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java:73]: This allows us to call `Vector.createValueForIndexNode()` from the generated node class.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java [hunk 4]
```diff
@@ -38,23 +42,31 @@ private Vector(Object storage) {
     this.storage = storage;
   }
 
+  public static InvokeFunctionNode createValueForIndexNode() {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java]: We could have `InvokeFunctionNode.buildWithArity(int)` factory method and use it instead....

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java [hunk 5]
```diff
@@ -38,23 +42,31 @@ private Vector(Object storage) {
...
+  public static Object newFromFunction(
+      VirtualFrame frame,
+      long length,
+      Function fun,
+      State state,
+      @Cached("createValueForIndexNode()") InvokeFunctionNode invokeFunctionNode) {
     Object[] target = new Object[Math.toIntExact(length)];
     for (int i = 0; i < target.length; i++) {
-      try {
-        final Object value = interop.execute(fun, (long) i);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java:50]: The consequence of (the need for) this change is: whenever we call into polyglot, then a _callback looses `State`_ - is that OK, @kustosz?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java [hunk 6]
```diff
@@ -38,23 +42,31 @@ private Vector(Object storage) {
     this.storage = storage;
   }
 
+  public static InvokeFunctionNode createValueForIndexNode() {
+    return InvokeFunctionNode.build(
+        new CallArgumentInfo[] {new CallArgumentInfo()},
+        InvokeCallableNode.DefaultsExecutionMode.EXECUTE,
+        InvokeCallableNode.ArgumentsExecutionMode.EXECUTE);
```
Comment (kustosz) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java]: You can probably experiment with removing arguments execution mode. It's a leftover from a bygone era and the only thing it potentially does is a tiny performance improvement. But I'm not sure it does, so better check.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: gotta love java

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: For it appears to be used only in `runtime` projects so I think it's safe to just save it somewhere there.

**Comment by JaroslavTulach** [comment]
@kustosz : Why is `select_into_database_table` a `Text` and not an `UnresolvedSymbol`:
```
Meta.get_annotation object .annotation_name
```
There is an API to evaluate any expression in any module.

**Comment by JaroslavTulach** [comment]
This PR has been simplified to fix just the `Vector.map` & `State`. Fix for annotations on extension functions is now part of #7115.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java]: done in [2932377](https://github.com/enso-org/enso/pull/7078/commits/29323772dfb73e623ef6c5d019f509e779a72195)

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java]: I removed all the `State` manipulation in favor of - #7115

**Comment by radeusgd** [comment]
I've just found a slightly related issue #7117 showing that while definitely a step in the right direction, this may still not be enough.

File: lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java (hunk 3 above)
Comment (radeusgd) [reply lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java:73]: Where do we use this?

**Review by radeusgd — APPROVED** [review]

**Review by hubertp — APPROVED** [review]
