### PR TITLE
DataflowError.withoutTrace shall not store a trace

### LINKED ISSUE #8137: Try to improve performance of Dataflow Errors
The benchmarks in #8130 show that our handling of Panics is _super fast_, however the dataflow errors are _far_ behind them - being **200x - 8500x slower**.

It would be good if we could get the dataflow errors performance a bit closer to that of panics, because dataflow errors _are_ the _primary_ way of reporting errors in Enso standard library.

While at it, it would be good to still retain the ability to query the stack trace of a dataflow error, when needed. In most scenarios the stack trace is ignored (so the computational effort used to create it is wasted), but in some cases the stack trace may be very helpful - e.g. when reporting test suite failures or debugging. Somehow, Panics seem to be able to retain on-demand stack traces while also being fast - ideally it would be great to have the same for dataflow errors, if possible.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #8137 by storing only `Error.throw` location in `DataflowError`. There is a `getStackTrace` message in `InteropLibrary`, so using it to take full control over the `DataflowError` stacktrace. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated in c67879978a
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] `Runtime*Test` have been updated
  - [x] [Benchmark run](https://github.com/enso-org/enso/actions/runs/7290472567) shows speedup
  - [x] Enable richer stack traces via an option - [done](https://github.com/enso-org/enso/pull/8608#issuecomment-1867346712)
  - [x] **Not done**: [reasons for different stacktraces](https://github.com/enso-org/enso/pull/8608/commits/891b08d766eacf7e3b043c57d62a9aabd9e619e4#r1434248537)

### CODE REVIEW

**Comment by radeusgd** [comment]
As [mentioned (pt. 2)](https://github.com/enso-org/enso/issues/8137#issuecomment-1864067147) full stack traces of dataflow errors are really quite invaluable for debugging.

Can we at least add some option (e.g. environment variable, engine runner option?) that re-enables the full traces at the cost of performance? Something like a 'debug' mode?

**Comment by JaroslavTulach** [comment]
> As [mentioned (pt. 2)](https://github.com/enso-org/enso/issues/8137#issuecomment-1864067147) full stack traces of dataflow errors are really quite invaluable for debugging. 

While I hear you I don't think there is a way to have _exactly correct_ stacktraces and excellent performance for `DataflowError`. As soon as the `DataflowError` is assigned to some variable, it needs to materialize to have correct stacktrace. Following example creates a `Vector`:

```ruby
deep_arr n =
    err = Error.throw (Illegal_Argument.Error "Problem"+n.to_text)
    if n <= 0 then [err] else deep_arr n-1 + [err]
```

and such a `Vector` can _fly thru the program_ for a very long time before its `DataflowError` stacktraces are printed or ignored.

> Can we at least add some option (e.g. environment variable, engine runner option?) that re-enables the full traces at the cost of performance? Something like a 'debug' mode?

Knowing (at `Error.throw`) site whether a stacktrace is needed or not isn't possible _in advance_. There are two options:
- a hint from the developer
- optimize subsequent executions based on their prior behavior

In any case tracking _exact stacktraces_ cannot be default & automatic, if the performance shall be on par with `Panic`.

**Comment by JaroslavTulach** [comment]
Right now there are:
- one failure in [RuntimeVisualizationTest](https://github.com/enso-org/enso/actions/runs/7278383961/job/19832454123?pr=8608#step:10:6507)
- three failures in [RuntimeErrorsTest](https://github.com/enso-org/enso/actions/runs/7278383961/job/19832454123?pr=8608#step:10:6446)

**Comment by radeusgd** [comment]
> In any case tracking _exact stacktraces_ cannot be default & automatic, if the performance shall be on par with `Panic`.

I understand.

That's why I suggested relying on an environment variable or runner option allowing us to 'enable detailed dataflow stack traces'. This can be a compile-time constant, that can be checked at `Error.throw`. By default we can keep the short trace (I guess for users the error message is far more important than location anyway), but us developers can enable (globally) more detailed traces (at the cost of performance).

**Comment by Akirathan** [comment]
> > In any case tracking _exact stacktraces_ cannot be default & automatic, if the performance shall be on par with `Panic`.
> 
> I understand.
> 
> That's why I suggested relying on an environment variable or runner option allowing us to 'enable detailed dataflow stack traces'. This can be a compile-time constant, that can be checked at `Error.throw`. By default we can keep the short trace (I guess for users the error message is far more important than location anyway), but us developers can enable (globally) more detailed traces (at the cost of performance).

What about enabling deep stack traces when JVM assertions (`-ea`) are enabled? They are enabled in unit tests and Enso tests, both on the CI and locally, but they are disabled in the production.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java [hunk 1]
```diff
@@ -23,34 +28,83 @@ public static GetStackTraceNode create() {
...
+      throws UnsupportedMessageException {
+    var size = iop.getArraySize(elements);
+    var count = 0;
+    for (long i = 0; i < size; i++) {
+      try {
+        var element = iop.readArrayElement(elements, i);
+        if (includeFrame(iop, element)) {
+          count++;
+        }
+      } catch (InvalidArrayIndexException ex) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java:70]: Instead of a complete empty catch body, what about at least throwing `throw new AssertionError(ex);`? To convey that this is an unexpected exception.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java [hunk 2]
```diff
@@ -28,6 +30,7 @@ public final class DataflowError extends AbstractTruffleException {
   public static final DataflowError UNINITIALIZED = new DataflowError(null, (Node) null);
 
   private final Object payload;
+  private final boolean without;
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: minor: Rename to `withoutTrace`

**Review by Akirathan — APPROVED** [review]
Consider enabling full stack traces when assertions enabled (https://github.com/enso-org/enso/pull/8608#issuecomment-1865942002). But that might be too complicated to implement. At least in this PR. Looks fine otherwise. Also, don't forget to report the performance changes pls.

**Comment by radeusgd** [comment]
> But that might be too complicated to implement. At least in this PR.

I don't think we can merge a PR that disables stack traces and does not give us a way to enable them in debug mode. That would hinder developer UX horribly.

I would very much appreciate being able to get stack traces in some 'debug' mode, I really need it much for my day-to-day work. Trying to summarize my day-to-day work, I think I browse tens of traces a day on average (maybe more), some of which are from panics but a significant part of these are from dataflow errors. Losing that capability will make it harder to implement new features and will slow us down.

File: engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala [hunk 3]
```diff
@@ -1877,8 +1877,9 @@ class RuntimeVisualizationsTest
               message =
                 "Method `does_not_exist` of type Main could not be found.",
               stack = Vector(
-                Api.StackTraceElement("<eval>", None, None, None),
-                Api.StackTraceElement("Debug.eval", None, None, None)
+// empty stack for now
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:1880]: Unfortunate change. Result of trying to unify working with stacktraces behind `InteropLibrary`. Let's see if it can be somewhat mitigated tomorrow.

**Comment by JaroslavTulach** [comment]
We have [four FAILED tests](https://github.com/enso-org/enso/actions/runs/7290403185/job/19867121520?pr=8608#step:10:9538) in `test/Tests` suite.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java]: Renamed to `ownTrace` in c06840783e

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java:70]: 9d4c333fe4 will report unexpected exceptions when `-ea`

**Comment by JaroslavTulach** [comment]
[Benchmark run](https://github.com/enso-org/enso/actions/runs/7290472567) indicates the `Panics_And_Errors_10000_Dataflow_Error` test (created by #8130 pull request) has been sped up significantly: 

7000x speedup

Previously it took `329ms`, now it runs in `0,045ms`.

**Comment by JaroslavTulach** [comment]
Since 10a8452 the following `x.enso` program:
```ruby
from Standard.Base import all
import Standard.Base.Errors.Illegal_Argument.Illegal_Argument

deep n = if n <= 0 then Error.throw (Illegal_Argument.Error "Problem") else deep n-1

main =
    d = deep 10
    d.get_stack_trace_text
```
produces just:
```bash
$ enso --run x.enso
        at <enso> x.deep<arg-1>(x.enso:4:25-70)
```
and full thread dump when executed with assertions:
```bash
$ JAVA_OPTS=-ea enso --run x.enso
        at <enso> x.deep<arg-1>(x.enso:4:25-70)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.deep<arg-2>(x.enso:4:77-84)
        at <enso> x.deep(x.enso:4:10-84)
        at <enso> x.main(x.enso:7:9-15)
```
I believe this addresses [Radek's complain](https://github.com/enso-org/enso/pull/8608#issuecomment-1866499798) - or at least provides the basics to mitigate it for now.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala [hunk 4]
```diff
@@ -867,7 +867,12 @@ object Main {
             )
           val res = main.execute(parsedArgs: _*)
           if (!res.isNull) {
-            out.println(res);
+            val textRes = if (res.isString) {
+              res.asString
+            } else {
+              res.toString
+            }
+            out.println(textRes);
```
Comment (radeusgd) [inline engine/runner/src/main/scala/org/enso/runner/Main.scala:875]: Out of curiosity - what does this change?

File: engine/runtime/src/test/java/org/enso/interpreter/test/FindExceptionMessageTest.java [hunk 5]
```diff
@@ -67,6 +70,71 @@ public void testThrowNPEWithName() {
...
+    var res = evalModule(ctx, src);
+    assertTrue("Expecting error: " + res, res.isException());
+    assertEquals("Standard.Base.Error.Error", res.getMetaObject().getMetaQualifiedName());
+
+    try {
+      throw res.throwException();
+    } catch (PolyglotException ex) {
+      assertNotNull("Has source location", ex.getSourceLocation());
+      var throwCode = ex.getSourceLocation().getCharacters().toString();
+      assertNotEquals("Throw code found in the source code: " + throwCode, src.indexOf(throwCode));
```
Comment (radeusgd) [inline engine/runtime/src/test/java/org/enso/interpreter/test/FindExceptionMessageTest.java]: This assert looks suspicious.

It seems to essentially do
```
assert ("Throw code found in the source code: " + throwCode) != src.indexOf(throwCode);
```
This seems to be trivially true. Aren't you missing one more argument in that assert?

File: test/Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso [hunk 6]
```diff
@@ -76,7 +76,7 @@ spec =
 
         Test.group "Enso_User - local mock integration tests" pending=pending_has_url <|
             # These tests should be kept in sync with tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/UsersHandler.java
-            Test.specify "current user can be fetched from mock API" <|
+            Test.specify "current user can be fetched from mock API" pending=pending_has_url <|
```
Comment (radeusgd) [inline test/Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso:79]: Sorry I missed that 🤦 

I fixed that in the #8591 PR which has been merged recently.

**Review by radeusgd — APPROVED** [review]
Changes look good.

Thank you **very much** for addressing my concerns and ensuring that developer UX is not significantly worsened - the debug mode will really be invaluable for us!

The performance improvements are awesome (expectably 🙂).

**Comment by radeusgd** [comment]
I have a suggestion (for another followup PR perhaps).

Given that we have the `withTrace` and `withoutTrace` methods - why not expose this to users (i.e. lib devs)?

I think it could be good to give us control over whether a given error will hold the trace or not - this way we can decide when we want better performance vs better diagnostics. I think there are definitely places where both make sense:
1. in places like `Map.get` - `Error.throw Not_Found` should likely be fast and the stack trace may not be that needed. So we could keep using the fast `Error.throw` (as I assume lack of traces would be the default).
2. in places like `handle_sql_errors` - I think we may want to prefer a `Error.throw_with_trace`. As I told before - the error location of `handle_sql_errors` will tell the user nothing useful - so here including the full trace will be more helpful. And an SQL error is not a performance-intensive kind of error - it is unlikely to happen in a loop; it will have collected the trace on the original Host Java exception _anyway_ - so the performance difference will not be noticeable, but we could regain better diagnostics.

I think this could be the best compromise we can get.

File: engine/runner/src/main/scala/org/enso/runner/Main.scala (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala:875]: 1152e3d21edc84fcd086a62fc9970dfe8d0da7a0

Comment (JaroslavTulach) [reply engine/runner/src/main/scala/org/enso/runner/Main.scala:875]: Without that change the multiline output of https://github.com/enso-org/enso/pull/8608#issuecomment-1867346712 wouldn't be that nice.

File: engine/runtime/src/test/java/org/enso/interpreter/test/FindExceptionMessageTest.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/interpreter/test/FindExceptionMessageTest.java]: Thank you: 80dc1cb19a

**Comment by JaroslavTulach** [comment]
> I have a suggestion (for another followup PR perhaps).

Certainly a follow up PR and issue. Feel free to record it/implement it.

> Given that we have the `withTrace` and `withoutTrace` methods - why not expose this to users (i.e. lib devs)?

Yes, I was also thinking about `Error.throw withTrace=False`. However I am not conviced that it is exactly what users want...

> I think it could be good to give us control over whether a given error will hold the trace or not - this way we can decide when we want better performance vs better diagnostics. I think there are definitely places where both make sense:
> 
>     1. in places like `Map.get` - `Error.throw Not_Found` should likely be fast and the stack trace may not be that needed. So we could keep using the fast `Error.throw` (as I assume lack of traces would be the default).
> 
>     2. in places like `handle_sql_errors` - I think we may want to prefer a `Error.throw_with_trace`. As I told before - the error location of `handle_sql_errors` will tell the user nothing useful - so here including the full trace will be more helpful. And an SQL error is not a performance-intensive kind of error - it is unlikely to happen in a loop; it will have collected the trace on the original Host Java exception _anyway_ - so the performance difference will not be noticeable, but we could regain better diagnostics.

The issue is:
- it is not the author of the `Error.throw` who should decide whether to capture the stack trace or not
- It is the user of some library code that than accidentally calls `Error.throw`
- E.g. there should be a way to turn stack trace capture even for code which isn't doing that by default
- Currently we have `-ea` for that, but yes, the meaning of `-ea` is becoming a bit too overloaded

I was rather thinking about something associated with `State` (at the end the tracing behavior is associated with state of the execution, not the code itself). Something like `Runtime.Context.Tracing.with_enabled`, maybe? Anyway that's for another issue/discussion/PR.
