### PR TITLE
Expect failure when parsing external Qualified Names

### LINKED ISSUE #12168: Parsing qualified name crashes when reading drop-down configuration
In nodes like `JS_Object.from_pairs`, clicking at `Nothing` causes and unhandled exception.

We make assertions about incoming paths being proper fully qualified names.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #12168 

Change `parseProjectPath` family of functions, so they return `Result`. Handle all translators from LS to handle cases when qualified names are not actual qualified name.

Fixed WildgetSelection, so it accepts qualified names which are not absolute.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/stores/projectNames.ts [hunk 1]
```diff
@@ -64,8 +78,15 @@ function useProjectNameStore(
     return path.path ? qnJoin(project, path.path) : project
   }
 
+  function pathSegments(projectPath: ProjectPath) {
```
Comment (kazcw) [inline app/gui/src/project-view/stores/projectNames.ts]: I'm not sure this fits in the scope of the `ProjectNameStore`. The store API exposes an important distinction between parse/print/serialize. This helper is equivalent to `qnSegments(printProjectPath(...))`, but hides which type of printing is being used. It is more convenient and potentially more efficient than using the two functions separately, but I think for those benefits to justify the cognitive overhead of expanding this API, it would need to be used a lot.

File: app/gui/src/project-view/components/DocumentationPanel.vue [hunk 2]
```diff
@@ -107,9 +108,10 @@ const breadcrumbs = computed<Breadcrumb[]>(() => {
 
 function handleBreadcrumbClick(index: number) {
   if (name.value) {
-    const qName = qnSlice(name.value, 0, index + 2)
-    if (qName.ok) {
-      const id = db.entries.findByProjectPath(projectNames.parseProjectPath(qName.value))
+    const pathSlice = name.value.path ? qnSlice(name.value.path, 0, index) : Ok(undefined)
+    if (pathSlice.ok) {
+      const qName = name.value.withPath(pathSlice.value)
```
Comment (kazcw) [inline app/gui/src/project-view/components/DocumentationPanel.vue]: The name `qName` is no longer accurate

**Review by kazcw — APPROVED** [review]
