### PR TITLE
Fix importing `.enso-project` files

### LINKED ISSUE #10282: Cannot open .enso-project files
When importing a .enso-project file by clicking on it (tested on Mac), Enso opens and the newly imported project appears in the dashboard, but the imported project fails to open.

Screenshot 2024-06-13 at 09 17 16

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix #10282

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
pinging @MrFlashAccount for CR - the code isn't pretty but it works... but feedback would be appreciated

and @PabloBuchu for testing on macos and @jdunkerley for testing on windows?
i could repro on linux (`./enso.AppImage ~/path/to/thing.enso-project`) which is where i tested

File: app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx [hunk 1]
```diff
@@ -173,62 +184,109 @@ export default function Dashboard(props: DashboardProps) {
...
     const savedProjectStartupInfo = localStorage.get('projectStartupInfo')
-    if (initialProjectName != null) {
+    if (initialLocalProjectId != null) {
+      if (localBackend != null) {
+        const projectId = initialLocalProjectId
+        const parentId = localBackend.rootDirectoryId()
+        const title = 'imported project'
+        // Assume it is a project to be opened on the Local Backend.
+        const project = localBackend
+          .openProject(
```
Comment (MrFlashAccount) [inline app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx]: This might lead to issues because this code doesn't guarantee the order and doesn't save the promise outside of the component, we might end up with problems like when we have multiple promises that resolve in any order(the first might resolve after the last one) and memory leak problems, because promise keep the closures. So this is 100% a codesmell and we should refactor it in the meantime. but as a quick fix, it's okay. Can we create an issue for refactoring and plan it?

**Review by MrFlashAccount — APPROVED** [review]

File: app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx (hunk 1 above)
Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx]: i think *this* promise is fine, we don't care about the result, only `Editor.tsx` does

the *next* promise is probably an issue though but i dunno whether it's possible to fix it

Comment (MrFlashAccount) [reply app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx]: If moving this to react-query / pulling this data up the tree is hard, we can postpone the refactoring

Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx]: oh right, i guess we can move it into a suspense?

**Comment by PabloBuchu** [comment]
1. When Enso opens can it open on local tab because thats the place where project is starting? Currently always starts with cloud 
2. Redirect to opened project is also not working. I see its spins for a while and then its ready (but I stay on dashboard)
3. Are we able to rename it if there is project with the same name?
4. Sometimes it spins indefinitely. Double click on a file then immediately switch to local or recent then check the project. It will stay loading

**Comment by somebody1234** [comment]
1. done (and simplified the code again)
2. done as a side effect of the above
3. TODO. will involve messing around with the code to import projects on the Electron side
4. can't repro after changes made in (1) - didn't test before changes made in (1)

**Comment by somebody1234** [comment]
@PabloBuchu (3) should also be addressed now

**Comment by jdunkerley** [comment]
Works on my Windows box again - thank you.
We need to make it open in the same session if possible but thats a separate issue!
