### PR TITLE
Use Actions for all keyboard bindings

### LINKED ISSUE #12954: c&p doesn't work in code editor
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [x] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

It is not possible to c&p any code in code editor.
When ctrl+v is pressed the cursor disappears and nothing happens. 

### Expected behaviour

c&p should work.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 2024.04.25

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #13002: Refactor shortcut handlers in Vue
* merge the current shortcuts handlers with actions
* action are now registered "globally", not for current subtree, but components may specify/modify context for ActionButtons in its subtree.
* keyboard events should be handled globally, in VSCode manner:
   * actions have contexts. extend it information about current node, panel etc.
   * every component may alter the context for global shortcut handling (e.,g. when docpanel becomes in focus)
   * action's conditions are hard-coded.
* mouse events are handled locally in component, as it is right now.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Refactor all keyboard bindings to use Actions (part 2 of #13002).

Also fixes #12954.

### Important Notes

- When clicking a boolean `MenuButton`, the value is now toggled based its state *before the `pointerdown` event*. This ensures the button's response matches the user's intent, even if another event handler reacted to the same `pointerdown` or `click` (e.g. some `endOnClickOutside` logic).
- Introduced a "popover root" context store allowing a component to define the DOM root element for floats in its subtree.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/components/AppContainer.vue [hunk 1]
```diff
@@ -137,6 +137,7 @@ const onSignOut = () => {
           </KeepAlive>
         </div>
         <RightPanel />
+        <div ref="fullscreenRoot" class="FullscreenRoot" @wheel.stop.passive />
```
Comment (kazcw) [inline app/gui/src/components/AppContainer.vue:140]: Introducing a container for fullscreen content so that we can catch events here

File: app/gui/src/project-view/util/vueDom.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import type { Ref } from 'vue'
+
+/**
+ * The type of event handlers for HTMLElement Events, in the naming scheme used by Vue.
+ *
+ * This can be used to generalize a `ComponentProps` type to allow passed-through event handlers
+ * passed-through to the component's DOM element.
+ */
```
Comment (farmaazon) [inline app/gui/src/project-view/util/vueDom.ts]: Too many `passed-through`?

File: app/gui/src/project-view/util/codemirror/index.ts [hunk 3]
```diff
@@ -381,3 +371,51 @@ export const selectOnMouseFocus = [
...
+export function putTextAtCoords(view: EditorView, text: string, coords: Vec2) {
+  const pos = view.posAtCoords(coords, false)
+  putTextAt(view, text, pos, pos)
+}
+
+/**
+ * @returns the editor's reactive focused state, maintained by attaching the returned event handlers
+ * to the editor's root element.
+ */
+export function useEditorFocus(view: EditorView) {
```
Comment (farmaazon) [inline app/gui/src/project-view/util/codemirror/index.ts]: Add a short note about "scrollbar handling" so we know _why_ we should use this function.

File: app/gui/src/project-view/providers/globalEventRegistry.ts [hunk 4]
```diff
@@ -0,0 +1,63 @@
+import type { WindowEventTarget } from '@/composables/events'
+import { createContextStore } from '@/providers'
+import { identity } from '@vueuse/core'
+
+interface GlobalEventRegistry {
+  globalEventRegistry: WindowEventTarget
+  globalEventRegistryPre: WindowEventTarget
+}
```
Comment (farmaazon) [inline app/gui/src/project-view/providers/globalEventRegistry.ts]: What does it mean, that registry is `Pre`? Also this interface should be exported, as it is returned from exported function.

If you just want to improve that in next PR, then add TODO to this file.

File: app/gui/src/project-view/providers/globalEventRegistry.ts [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+ * Create a {@link GlobalEventRegistry} and make is available to the component's children.
+ * @returns the created registry
+ */
+export function provideGlobalEventRegistry(): GlobalEventRegistry {
+  const globalEventRegistryPre = eventRegistry()
+  const globalEventRegistry = eventRegistry(window, globalEventRegistryPre)
+  const registry = { globalEventRegistry, globalEventRegistryPre }
+  provideRegistry(registry)
+  return registry
+}
```
Comment (farmaazon) [inline app/gui/src/project-view/providers/globalEventRegistry.ts]: We could make use of createContextStore "factory" parameter:

```suggestion
export const [provideGlobalEventRegistry, useGlobalEventRegistry] = createContextStore(
  'GlobalEvent',
  () => {
    const globalEventRegistryPre = eventRegistry()
    const globalEventRegistry = eventRegistry(window, globalEventRegistryPre)
    return { globalEventRegistry, globalEventRegistryPre }
  },
)
```

Also, here should be a documentation of GlobalEventRegistry

File: app/gui/src/project-view/providers/action.ts [hunk 6]
```diff
@@ -251,26 +258,129 @@ const actions = {
...
+
+  'textEditor.moveLeft': {},
+  'textEditor.moveRight': {},
+  'textEditor.deleteBack': {},
+  'textEditor.deleteForward': {},
+  'textEditor.newline': {},
+
+  // === Interactions ===
+
+  'interaction.cancel': {},
```
Comment (farmaazon) [inline app/gui/src/project-view/providers/action.ts:358]: Why these don't have shortcuts?

File: app/gui/src/project-view/composables/events.ts [hunk 7]
```diff
@@ -140,6 +154,8 @@ export function modKey(e: KeyboardEvent | MouseEvent): boolean {
   return isMacLike ? e.metaKey : e.ctrlKey
 }
 
+export type UnrefElement = ToValue<Element | undefined | null | VueInstance>
```
Comment (farmaazon) [inline app/gui/src/project-view/composables/events.ts]: Type seems like being something returned from `unrefElement`, but it's not the case - it isn't even mentioned in the method's signature.

File: app/gui/src/project-view/components/SelectionDropdown.vue [hunk 8]
```diff
@@ -8,13 +8,15 @@ import SvgIcon from '@/components/SvgIcon.vue'
 import type { SelectionMenuOption } from '@/components/visualizations/toolbar'
 import { ref, toValue } from 'vue'
 
-type Key = number | string | symbol
+type Key = string
+
 const selected = defineModel<Key>({ required: true })
-const _props = defineProps<{
+const { options, title, labelButton, alwaysShowArrow, entriesTestId } = defineProps<{
```
Comment (farmaazon) [inline app/gui/src/project-view/components/SelectionDropdown.vue]: If they are used in template only, we may also not declare return vars at all:
```suggestion
defineProps<{
```

File: app/gui/src/project-view/components/MenuButton.vue [hunk 9]
```diff
@@ -27,12 +28,13 @@ const style = computed(() =>
...
+const { stateBeforeClick } = useStateBeforePointerdown(button, () => toggledOn.value)
+
 function onActivate() {
-  if (tooltipTrigger.value) {
-    tooltipTrigger.value.hideTooltip()
-  }
+  tooltipTrigger.value?.hideTooltip()
   if (props.disabled) return
-  if (toggledOn.value != null) toggledOn.value = !toggledOn.value
+  if (stateBeforeClick.value != null && isRef(toggledOn)) toggledOn.value = !stateBeforeClick.value
```
Comment (farmaazon) [inline app/gui/src/project-view/components/MenuButton.vue]: Why `toggledOn` might not be a ref?

File: app/gui/src/project-view/components/ComponentBrowser.vue [hunk 10]
```diff
@@ -328,48 +329,44 @@ const actions = registerHandlers({
     action: () => acceptComponent(),
   },
   'componentBrowser.acceptInputAsCode': {
-    enabled: insideComponentBrowsing,
+    available: () => input.mode.mode === 'codeEditing',
```
Comment (farmaazon) [inline app/gui/src/project-view/components/ComponentBrowser.vue:337]: This is wrong. This is action is intended for component browsing to accept input as-is (ignoring selected list entry) without having to switch to code edit mode.

File: app/gui/src/project-view/components/widgets/AutoSizedInput.vue [hunk 11]
```diff
@@ -3,7 +3,7 @@ import { useAutoBlur } from '@/util/autoBlur'
 import { getTextWidthByFont } from '@/util/measurement'
 import { computed, ref, type StyleValue } from 'vue'
 
-const model = defineModel<string>()
+const model = defineModel<string>({ required: true })
```
Comment (farmaazon) [inline app/gui/src/project-view/components/widgets/AutoSizedInput.vue]: Does it have to be required? Maybe defaulted to "" like the html input.

File: app/gui/src/project-view/components/GraphEditor/WidgetTreeRoot.vue [hunk 12]
```diff
@@ -45,9 +45,11 @@ const anyLayoutAnimationActive = computed(
...
 )
 
+const rootElement = toRef(props, 'rootElement')
+
 const tree = provideWidgetTree(
   toRef(props, 'externalId'),
-  toRef(props, 'rootElement'),
+  rootElement,
   toRef(props, 'conditionalPorts'),
   toRef(props, 'extended'),
```
Comment (farmaazon) [inline app/gui/src/project-view/components/GraphEditor/WidgetTreeRoot.vue]: I think this change is not needed?

File: app/gui/src/project-view/providers/action.ts (hunk 6 above)
Comment (kazcw) [reply app/gui/src/project-view/providers/action.ts:358]: Currently the `shortcut` field is only used for displaying the shortcut hint in button titles and dropdown entry text, so it doesn't matter for these. I will be making changes to this area of the API in the next PR.

File: app/gui/src/project-view/components/ComponentBrowser.vue (hunk 10 above)
Comment (kazcw) [reply app/gui/src/project-view/components/ComponentBrowser.vue:337]: That's `acceptInput`, which is bound to `Mod+Enter` and is available in all modes. `acceptInputAsCode` is the `Enter` handler when in code edit mode.

Comment (kazcw) [reply app/gui/src/project-view/components/ComponentBrowser.vue:337]: These action names and the mode management here are a bit confusing, I'll see if I can fit cleaning it up into my next PR

Comment (farmaazon) [reply app/gui/src/project-view/components/ComponentBrowser.vue:337]: Indeed, I confused them both.

**Review by farmaazon — APPROVED** [review]
