### PR TITLE
Serialize UUID for non-library modules

### LINKED ISSUE #8689: Language Server breaks on page refresh.
To reproduce
1. Open any project locally
2. Refresh page (ctrl/cmd+r in electron works)

Expected: page refreshes and loads project properly
Actual: language server reports exception, no node is colored.

The reported exception is 
```
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "a" is null
	at org.enso.IsolatedClassLoader//io.circe.Encoder$$anon$20.apply(Encoder.scala:307)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$$anon$20.apply(Encoder.scala:306)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$515.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$515.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder$$anon$1.encodeObject(DerivedAsObjectEncoder.scala:13)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply$(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder.apply(DerivedAsObjectEncoder.scala:6)
	at org.enso.IsolatedClassLoader//io.circe.MidPriorityEncoders$IterableAsArrayEncoder.encodeArray(Encoder.scala:934)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsArray.apply(Encoder.scala:759)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsArray.apply$(Encoder.scala:759)
	at org.enso.IsolatedClassLoader//io.circe.MidPriorityEncoders$IterableAsArrayEncoder.apply(Encoder.scala:926)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$514.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$514.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder$$anon$1.encodeObject(DerivedAsObjectEncoder.scala:13)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply$(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder.apply(DerivedAsObjectEncoder.scala:6)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:293)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler.org$enso$jsonrpc$MessageHandler$$issueNotification(MessageHandler.scala:94)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler$$anonfun$org$enso$jsonrpc$MessageHandler$$established$1.applyOrElse(MessageHandler.scala:51)
	at org.enso.IsolatedClassLoader//akka.actor.Actor.aroundReceive(Actor.scala:537)
	at org.enso.IsolatedClassLoader//akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler.aroundReceive(MessageHandler.scala:13)
	at org.enso.IsolatedClassLoader//akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at org.enso.IsolatedClassLoader//akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
It always appears when the problem occurs. Here is full log from several launches, some reproducing the issue.

[enso-project-manager-2024-01-05.0.log](https://github.com/enso-org/enso/files/13841934/enso-project-manager-2024-01-05.0.log)

### LINKED ISSUE #8941: Failing test `runEngineDistribution --run test/Base_Tests Instrument` on subsequent execution
One needs the filter capability provided by #8940, but then executing following test _often fails_:
```bash
$ runEngineDistribution --run test/Base_Tests Instrument
[FAILED] Instrument fibonacci: [0/3, 127ms]
    - [FAILED] collect and filter on return updates [99ms]
        Reason: 0 did not equal 1 (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:34:17-41).
    - [FAILED] access local variables  [14ms]
        Reason: 0 did not equal 3 (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:66:17-41).
    - [FAILED] replay with caches and specify different result [14ms]
        Reason: 89 did not equal 42 (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:89:17-40).
[FAILED] Instrument @Tail_Call fibonacci: [2/6, 69ms]
    - check fib & fib2 are the same [14ms]
    - [FAILED] call and collect on return updates [16ms]
        Reason: [] did not equal [[1, 1], [1, 2], [2, 3], [3, 5], [5, 8], [8, 13], [13, 21], [21, 34], [34, 55], [55, 89]]; lengths differ (0 != 10)  (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:128:17-122).
    - [FAILED] * instead of + on return updates [9ms]
        Reason: 89 did not equal 17179869184 (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:157:17-50).
    - [FAILED] Caching in on_enter prevents on_call [9ms]
        Reason: 89 did not equal 90 (at /enso/enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:182:17-41).
    - [FAILED] Access (even default) arguments of calls [10ms]
        Reason: 89 did not equal 155 (at /enso/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso:214:17-42).
    - GC disables Instrumentor [8ms]
2 tests succeeded.
7 tests failed.
0 tests skipped.
0 groups skipped.
```
turn out this has something to do with **caching** as removing the `.ir` caches and running again succeeds (for the first time):
```bash
enso$ rm -rf "$HOME/Library/Application Support/org.enso/cache/"
enso$ ./built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/bin/enso --run test/Base_Tests/ Instrument
Instrument fibonacci: [3/3, 336ms]
    - collect and filter on return updates [154ms]
    - access local variables  [48ms]
    - replay with caches and specify different result [133ms]
Instrument @Tail_Call fibonacci: [6/6, 1077ms]
    - check fib & fib2 are the same [7ms]
    - call and collect on return updates [34ms]
    - * instead of + on return updates [19ms]
    - Caching in on_enter prevents on_call [10ms]
    - Access (even default) arguments of calls [30ms]
    - GC disables Instrumentor [974ms]
9 tests succeeded.
0 tests failed.
0 tests skipped.
0 groups skipped.
```
however it **only succeeds once**. Subsequent execution of the `enso --run test/Base_Tests/ Instrument` fail again as reported before.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Missing ID's in IR meant that instrumentation wouldn't be applied for loaded modules. This is the reason why after a restart engine wouldn't send **any** expression updates.

Closes #8689.

### Important notes

After the change
[Kazam_screencast_00038.webm](https://github.com/enso-org/enso/assets/292128/4249287b-6c41-4c9d-b138-e7af59512566)

The video somehow doesn't show that all nodes are loaded after the restart, but once I moved the screen they are there. This appears to be a bug in the recording somehow.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.
  - [ ]  Change caches version ID

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]

**Comment by hubertp** [comment]
Should also fix https://github.com/enso-org/enso/issues/8941

**Comment by JaroslavTulach** [comment]
> Should also fix #8941

Yes, the [problem is going to be fixed](https://github.com/enso-org/enso/issues/8941#issuecomment-1945373561), but only after **clearing local caches**. That's not fully ideal.

Please **change caches version ID** as the serialized form for `.ir` files has changed and previous caches shall not be used.

**Comment by hubertp** [comment]
I gave up on adding a unit test. It looks like UUIDs aren't added to `IdentifierLocation` by default in tests which makes it particularly hard to set it up without changing the parser. This change is really annoying and I already wasted too much time on it.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala [hunk 1]
```diff
@@ -23,7 +23,7 @@ import scala.annotation.unused
   */
 
 @SerialVersionUID(
-  8160L // Use BindingsMap
+  9057L // Use BindingsMap
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala:26]: We are no longer using `serialVersionUID` as we have our own `Persistance` framework. Instructions to [version caches are here](https://github.com/enso-org/enso/blob/f2d2f73e8941b5cfaaa3edfdfe0c05f4b8117d47/docs/runtime/ir-caching.md#portability-and-versioning).

Sorry for not stating that more clearly when requesting you to _"Change caches version ID"_, but the last change to the documentation was [done by you](https://github.com/enso-org/enso/blame/f2d2f73e8941b5cfaaa3edfdfe0c05f4b8117d47/docs/runtime/ir-caching.md#L170), so I expected you to remember the context.

As a result of not versioning the caches properly, I have to clean `rm -rf ~/.local/shared/enso/caches/ir` to fix 
- #8941
