### PR TITLE
Fix small component menu

### LINKED ISSUE #12431: Visualisation icon appears disabled
The visualisation icon is greyed out and appears disabled

Image

Version 2025.1.1-nightly.2025.3.6
Build <snapshot>
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2025.1.1-nightly.2025.3.6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### LINKED ISSUE #12432: Tooltips broken on component small menu
Image

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Fixes #12431 
Fixes #12432 

Before:

image

image

After:

image

image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/ActionButton.vue [hunk 1]
```diff
@@ -11,22 +10,13 @@ const action = computed(() =>
...
 
 <template>
-  <ToggleIcon
-    v-if="action.toggled != null"
-    :modelValue="toValue(action.toggled)"
-    :icon="toValue(action.icon)"
-    :disabled="toValue(action.disabled)"
-    :title="descriptionWithShortcut"
-    @click.stop="action.action"
-  />
```
Comment (farmaazon) [inline app/gui/src/project-view/components/ActionButton.vue:27]: This effectively hides the information from toggle-able actions if they are toggled on or off.

It affects _all_ action buttons, like color picker. Currently, it has more vivid color when toggled on:

https://github.com/user-attachments/assets/d19c863a-36cf-42a3-91a2-8cd13cdb8697

While this one is not very important for the user, but the actions are meant to be very generic, and I guess the lack of feedback that the action is toggleable is concerning.

Also, I think the color-picker button itself does _not_ look disabled; perhaps we could just use the same tone in visualization button?

image

**Review by farmaazon — CHANGES_REQUESTED** [review]

File: app/gui/src/project-view/components/ActionButton.vue (hunk 1 above)
Comment (AdRiley) [reply app/gui/src/project-view/components/ActionButton.vue:27]: Yes I thought about this. The counter argument is that in both of these cases the user can see that it is toggled on as there is a new pane that is opened.

But yes the other option is to make untoggled the same color as the other buttons and then do something else for toggled on (perhaps we can go even darker)

Comment (AdRiley) [reply app/gui/src/project-view/components/ActionButton.vue:27]: Or this for toggled on?
image

Comment (farmaazon) [reply app/gui/src/project-view/components/ActionButton.vue:27]: Yes, we can just make `ToggleButton` has different behavior (like the highlight instead of icon color change).

**Review by farmaazon — APPROVED** [review]
After a call: for now, `ActionButton` will not have any "toggled" indicator (in Menu Entry still remains)
