### PR TITLE
Meta.get_constructor_fields works for Type

### LINKED ISSUE #5805: `Meta.meta` returns a broken value for Types
See the following example:
```
from Standard.Base import all

type My_Type
    My_Ctor x

main =
    v1 = My_Type.My_Ctor 42
    IO.println (Meta.is_atom v1)
    m1 = Meta.meta v1
    IO.println m1
    IO.println m1.constructor.fields

    v2 = My_Type
    IO.println (Meta.is_atom v2)
    m2 = Meta.meta v2
    case m2 of
        Meta.Atom.Value _ ->
            IO.println m2
            IO.println m2.constructor.fields
```

### Expected behaviour

- A) it should print:
```
True
(Atom.Value (My_Ctor 42))
[x]
True
(Atom.Value My_Type)
[]
```

- B) it should print sth like:
```
True
(Atom.Value (My_Ctor 42))
[x]
False
(Type.Value My_Type)
```

The variant **B** is my personal preference - I'm not sure if `My_Type` is and should be an Atom? I think we should introduce a separate `Meta.Type` to hold the types. This would make our life easier also in regards to #5792, allowing us to check if the second `is_a` argument is a `Type` and reject invalid arguments easily.

### Current behaviour

```
True
(Atom.Value (My_Ctor 42))
[x]
True
(Atom.Value My_Type)
Execution finished with an error: Unsupported argument for arg1 expected a AtomConstructor
        at <enso> Meta.get_constructor_fields(Internal)
        at <enso> Constructor.fields<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Meta.enso:64:37-60)
        at <enso> Constructor.fields(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Meta.enso:64:9-61)
        at <enso> case_branch<arg-1>(metatype.enso:19:24-44)
        at <enso> case_branch(metatype.enso:19:13-44)
        at <enso> metatype.main(metatype.enso:16-19)
```

The `fields` method crashes. This is definitely not desirable.

I'd suggest to fix this by going (B) and not making types Atoms if that is OK. But a fix that will go the (A) route sounds acceptable too. We just shouldn't crash.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #5805 by returning `[]` as list of fields of `Type`.

### Important Notes

`Type` is recognized as `Meta.is_atom` since #3671. However `Type` isn't an `Atom` internally. We have to provide special handling for it where needed. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java [hunk 1]
```diff
@@ -13,12 +13,16 @@
     description = "Gets the field names of a constructor.",
     autoRegister = false)
 public class GetConstructorFieldNamesNode extends Node {
-  Array execute(AtomConstructor atom_constructor) {
-    ArgumentDefinition[] fields = atom_constructor.getFields();
-    Object[] result = new Object[fields.length];
-    for (int i = 0; i < fields.length; i++) {
-      result[i] = Text.create(fields[i].getName());
+  Array execute(Object obj) {
+    if (obj instanceof AtomConstructor atom_constructor) {
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java]: Shouldn't we specialize instead? Seems more Truffle-friendly, I think

**Comment by radeusgd** [comment]
Why do we want to treat Type as an Atom? Why not introduce a Meta.Type? I think it could be quite useful to distinguish Atom instances from their Types. They really are different things in the language and the merging of them looks artificial.

**Comment by JaroslavTulach** [comment]
Only one [[FAILED test](https://github.com/enso-org/enso/actions/runs/4375646576/jobs/7656634108#step:10:9594) after bd9916e? In such case we can consider implementing `Meta.Type`. That will require a bit more work, however. 

> Why not introduce a Meta.Type?

I guess we should fix the error first, and then start design work on the new `Meta.Type` API. @radeusgd please discuss this with James and if approved and scheduled for any time soon, report an issue for me to address it.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java]: Redone in [0a6ac0a](https://github.com/enso-org/enso/pull/5869/commits/0a6ac0ae980312bcc3ce69194673f548bd3a8840)

**Review by jdunkerley — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

File: test/Tests/src/Semantic/Meta_Spec.enso [hunk 2]
```diff
@@ -199,6 +199,18 @@ spec =
...
+            typ = Boolean
+
+            Meta.is_atom typ . should_be_true
+            meta_typ = Meta.meta typ
+            meta_typ . should_be_a Meta.Atom
+            fields = case meta_typ of
+                Meta.Atom.Value _ -> meta_typ.constructor.fields
+                _ -> Test.fail "Should be a Meta.Atom.Value: " + meta_typ.to_text
+
+            fields . should_equal []
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Meta_Spec.enso:212]: Can we also add a test where `typ` is not a regular type but a module, like `Meta`?

[As mentioned](https://github.com/enso-org/enso/issues/5805#issuecomment-1465822727), this also used to fail on modules and I'd like to ensure it doesn't crash there too.

Looks like the fix should apply there just fine, but good to have a test to avoid regressions.

Comment (JaroslavTulach) [reply test/Tests/src/Semantic/Meta_Spec.enso:212]: The fallback applies to `Module` as well: https://github.com/enso-org/enso/pull/5869/files#diff-63d4533fccf2dfeb8e87e9ccba516458b86d82dd6f4ee9d9a4b7cc6dec4e667bR35 - too late to do changes to the #5869 PR, but feel free to add a test in its own PR.

**Comment by JaroslavTulach** [comment]
> Why not introduce a Meta.Type?

@radeusgd please take a look at #5956

**Comment by radeusgd** [comment]
> > Why not introduce a Meta.Type?
> 
> @radeusgd please take a look at #5956

I did. And I'm really glad we went this way 😁 Thanks for implementing it!
