### PR TITLE
Fix inline compilation benchmarks and Improve searching Graph.Link performance

### LINKED ISSUE #9237: Analyze and improve the performance of inline compilation
Related to:
- #9235 
- #9236 

Benchmark added in #9158.

The benchmark `org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression` (run with `sbt:runtime-benchmarks> benchOnly org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression`) measures the performance of `Compiler.runInline`. As this method is used frequently by various instruments in the IDE, we would like to focus on it.

This **benchmark is a bit suspicious (unstable)**, as the very first sets of warmup iterations run faster than all the subsequent ones. Output of running the benchmark locally:
```
[info] running (fork) org.enso.interpreter.bench.benchmarks.RuntimeBenchmarksRunner org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression
[info] # JMH version: 1.36
[info] # VM version: JDK 21.0.2, OpenJDK 64-Bit Server VM, 21.0.2+13-jvmci-23.1-b30
[info] # VM invoker: /home/pavel/.sdkman/candidates/java/21.0.2-graalce/bin/java
[info] # VM options: -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -Dslf4j.provider=org.slf4j.nop.NOPServiceProvider -Dbench.compileOnly=false --module-path=/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/sdk/nativeimage/23.1.2/nativeimage-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/sdk/word/23.1.2/word-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/sdk/jniutils/23.1.2/jniutils-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/sdk/collections/23.1.2/collections-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/polyglot/polyglot/23.1.2/polyglot-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/truffle/truffle-api/23.1.2/truffle-api-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/truffle/truffle-runtime/23.1.2/truffle-runtime-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/truffle/truffle-compiler/23.1.2/truffle-compiler-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/js/js-language/23.1.2/js-language-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/regex/regex/23.1.2/regex-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/shadowed/icu4j/23.1.2/icu4j-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/python/python-language/23.1.2/python-language-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/python/python-resources/23.1.2/python-resources-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.76/bcutil-jdk18on-1.76.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk18on/1.76/bcpkix-jdk18on-1.76.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.76/bcprov-jdk18on-1.76.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/llvm/llvm-api/23.1.2/llvm-api-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/truffle/truffle-nfi/23.1.2/truffle-nfi-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/truffle/truffle-nfi-libffi/23.1.2/truffle-nfi-libffi-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/tools/profiler-tool/23.1.2/profiler-tool-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/graalvm/shadowed/json/23.1.2/json-23.1.2.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/home/pavel/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-nop/2.0.9/slf4j-nop-2.0.9.jar:/home/pavel/dev/enso/runtime.jar --add-modules=org.enso.runtime --add-exports=org.slf4j.nop/org.slf4j.nop=org.slf4j
[info] # Blackhole mode: compiler (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
[info] # Warmup: 6 iterations, 10 s each
[info] # Measurement: 4 iterations, 10 s each
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Average time, time/op
[info] # Benchmark: org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression
[info] # Run progress: 0.00% complete, ETA 00:01:40
[info] # Fork: 1 of 1
[info] OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
[error] SLF4J: Attempting to load provider "org.slf4j.nop.NOPServiceProvider" specified via "slf4j.provider" system property
[info] # Warmup Iteration   1: 42.978 ms/op
[info] # Warmup Iteration   2: 99.519 ms/op
[info] # Warmup Iteration   3: 134.974 ms/op
[info] # Warmup Iteration   4: 161.004 ms/op
[info] # Warmup Iteration   5: 189.944 ms/op
[info] # Warmup Iteration   6: 218.136 ms/op
[info] Iteration   1: 225.969 ms/op
[info] Iteration   2: 257.387 ms/op
[info] Iteration   3: 315.345 ms/op
[info] Iteration   4: 329.106 ms/op
[info] Result "org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression":
[info]   281.952 ±(99.9%) 313.836 ms/op [Average]
[info]   (min, avg, max) = (225.969, 281.952, 329.106), stdev = 48.566
[info]   CI (99.9%): [≈ 0, 595.788] (assumes normal distribution)
[info] # Run complete. Total time: 00:01:43
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] NOTE: Current JVM experimentally supports Compiler Blackholes, and they are in use. Please exercise
[info] extra caution when trusting the results, look into the generated code to check the benchmark still
[info] works, and factor in a small probability of new VM bugs. Additionally, while comparisons between
[info] different JVMs are already problematic, the performance difference caused by different Blackhole
[info] modes can be very significant. Please make sure you use the consistent Blackhole mode for comparisons.
[info] Benchmark                               Mode  Cnt    Score     Error  Units
[info] InlineCompilerBenchmark.longExpression  avgt    4  281.952 ± 313.836  ms/op
[info] Benchmark results reported into /home/pavel/dev/enso/engine/runtime-benchmarks/./bench-report.xml
[success] Total time: 105 s (01:45), completed Mar 1, 2024, 1:50:39 PM
```

Attaching VisualVM and CPU sampler shows that most CPU time is consumed by AliasAnalysis, as expected:
image

Looking into memory usage of this benchmark, there does not seem to be any major leak.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

As benchmarks show, a significant amount of time is spent traversing `Set` of `Graph.Link`s. That's unfortunate and unnecessary. We can equally keep helper maps that make search constant time.

Fixed inline compilation benchmarks by properly cleaning up scopes after runs.

Closes #9237.

### Important Notes

Things like
Screenshot from 2024-03-22 11-23-01
Screenshot from 2024-03-22 11-13-19
are all gone. There is plenty of it those are just samples.

Benchmarks are back in order:
```
[info] # Warmup Iteration   1: 2.702 ms/op
[info] # Warmup Iteration   2: 3.080 ms/op
[info] # Warmup Iteration   3: 2.818 ms/op
[info] # Warmup Iteration   4: 3.334 ms/op
[info] # Warmup Iteration   5: 2.448 ms/op
[info] # Warmup Iteration   6: 2.583 ms/op
[info] Iteration   1: 2.908 ms/op
[info] Iteration   2: 2.915 ms/op
[info] Iteration   3: 2.774 ms/op
[info] Iteration   4: 2.601 ms/op
[info] Result "org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression":
[info]   2.799 ±(99.9%) 0.953 ms/op [Average]
[info]   (min, avg, max) = (2.601, 2.799, 2.915), stdev = 0.148
[info]   CI (99.9%): [1.846, 3.753] (assumes normal distribution)
```

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.

### CODE REVIEW

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 1]
```diff
@@ -5,14 +5,17 @@ import org.enso.syntax.text.Debug
...
 
 /** A graph containing aliasing information for a given root scope in Enso. */
 sealed class Graph extends Serializable {
-  var rootScope: Graph.Scope = new Graph.Scope()
-  var links: Set[Graph.Link] = Set()
-  var nextIdCounter          = 0
+  var rootScope: Graph.Scope                              = new Graph.Scope()
+  private var links: Set[Graph.Link]                      = Set()
+  private var sourceLinks: Map[Graph.Id, Set[Graph.Link]] = new HashMap()
+  private var targetLinks: Map[Graph.Id, Set[Graph.Link]] = new HashMap()
```
Comment (4e6) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:17]: There is an implementation of serialization logic for the `Graph` https://github.com/enso-org/enso/blob/6665c22eb9d5d8b1fd16ead769acaa3c31dda57b/engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java#L153-L157

Please make sure that it works correctly with the newly added fields and probably update the serialization id

Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:17]: Should work correctly as I'm reproducing `sourceLinks` and `targetLinks` from `links` when deserialized. I'm not serializing those fields as there is no need for that (`links` continues to be serialized).

**Review by 4e6 — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 2]
```diff
@@ -5,14 +5,17 @@ import org.enso.syntax.text.Debug
...
+import scala.collection.immutable.HashMap
 import scala.collection.mutable
 import scala.reflect.ClassTag
 
 /** A graph containing aliasing information for a given root scope in Enso. */
 sealed class Graph extends Serializable {
-  var rootScope: Graph.Scope = new Graph.Scope()
-  var links: Set[Graph.Link] = Set()
-  var nextIdCounter          = 0
+  var rootScope: Graph.Scope                              = new Graph.Scope()
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:14]: If `initXyz` is better pattern than calling `g.rootScope_$eq(rootScope);` - then `rootScope` could be made private as well, possibly.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 3]
```diff
@@ -24,11 +27,26 @@ sealed class Graph extends Serializable {
...
     copy.rootScope     = this.rootScope.deepCopy(scope_mapping)
     copy.links         = this.links
+    copy.sourceLinks   = this.sourceLinks
+    copy.targetLinks   = this.targetLinks
     copy.globalSymbols = this.globalSymbols
     copy.nextIdCounter = this.nextIdCounter
     copy
   }
 
+  def initLinks(links: Set[Graph.Link]): Unit = {
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:37]: Shouldn't `initLinks` also populate `getLinks`? I don't see such behavior and I believe that calling:
```scala
val set = Set(l1, l2, l3);
g.initLinks();
assert g.getLinks() == set
```
would fail.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 4]
```diff
@@ -24,11 +27,26 @@ sealed class Graph extends Serializable {
...
+    links.foreach { link =>
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala]: Shouldn't `sourceLinks` and `targetLinks` be cleared first? Otherwise calling `initLinks` multiple times will accumulate the results. Either:
- allow `initLinks` to be called only once
- clear the content if called multiple times
- rename to `addLinks`

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 5]
```diff
@@ -24,11 +27,26 @@ sealed class Graph extends Serializable {
...
+      sourceLinks = sourceLinks.updatedWith(link.source)(v =>
+        v.map(s => s + link).orElse(Some(Set(link)))
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala]: According to [scaladoc](https://www.scala-lang.org/api/2.13.7/scala/collection/immutable/Map.html#updatedWith[V1%3E:V](key:K)(remappingFunction:Option[V]=%3EOption[V1]):CC[K,V1]) this is going to add to the `Set` associated with `link.source`. _Just a note_ to be able to read what's happening.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 6]
```diff
@@ -129,7 +155,10 @@ sealed class Graph extends Serializable {
     * @return a list of links in which `id` occurs
     */
   def linksFor(id: Graph.Id): Set[Graph.Link] = {
-    links.filter(l => l.source == id || l.target == id)
+    sourceLinks.getOrElse(id, Set.empty[Graph.Link]) ++ targetLinks.getOrElse(
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:158]: Great finding. Good fix. Thank you.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 7]
```diff
@@ -85,6 +105,12 @@ sealed class Graph extends Serializable {
   ): Option[Graph.Link] = {
     scopeFor(occurrence.id).flatMap(_.resolveUsage(occurrence).map { link =>
       links += link
+      sourceLinks = sourceLinks.updatedWith(link.source)(v =>
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala]: Looks like the same code as in `initLinks`. Maybe really rename `initLinks` to `addLinks` and call it here?

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 8]
```diff
@@ -24,11 +27,26 @@ sealed class Graph extends Serializable {
...
+        v.map(s => s + link).orElse(Some(Set(link)))
+      )
+      targetLinks = targetLinks.updatedWith(link.target)(v =>
+        v.map(s => s + link).orElse(Some(Set(link)))
+      )
+    }
+  }
+
+  def getLinks(): Set[Graph.Link] = links
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:44]: Wouldn't it be better to remove the `links` field all together and just compute the links from `sourceLinks` and `targetLinks`? The logic between `initLinks` and `getLinks` & co. would be simpler and possibly `getLinks()` isn't on critical path. Otherwise the [inconsistency](https://github.com/enso-org/enso/pull/9520#discussion_r1537195157) must have been caught somewhere, right?

**Review by JaroslavTulach — APPROVED** [review]
Glad to see a speedup. Some comments related to the code left inline.

**Review by Akirathan — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala (hunk 2 above)
Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:14]: I tried and looks like a lot more stuff depends on it being public. I tried to keep the PR succinct for now.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala (hunk 4 above)
Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala]: Yes, if you call it multiple times that will be the case. I guess clearing things sounds OK.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala (hunk 8 above)
Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:44]: I kind of like that `links` is the source of truth and `sourceLinks/targetLinks` serve as aux indexes for quicker access. It also simplifies serde.

**Comment by hubertp** [comment]
With the last change the inline compilation benchmarks are back in order:
```
[info] # Warmup Iteration   1: 2.702 ms/op
[info] # Warmup Iteration   2: 3.080 ms/op
[info] # Warmup Iteration   3: 2.818 ms/op
[info] # Warmup Iteration   4: 3.334 ms/op
[info] # Warmup Iteration   5: 2.448 ms/op
[info] # Warmup Iteration   6: 2.583 ms/op
[info] Iteration   1: 2.908 ms/op
[info] Iteration   2: 2.915 ms/op
[info] Iteration   3: 2.774 ms/op
[info] Iteration   4: 2.601 ms/op
[info] Result "org.enso.compiler.benchmarks.inline.InlineCompilerBenchmark.longExpression":
[info]   2.799 ±(99.9%) 0.953 ms/op [Average]
[info]   (min, avg, max) = (2.601, 2.799, 2.915), stdev = 0.148
[info]   CI (99.9%): [1.846, 3.753] (assumes normal distribution)
```

File: engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResource.java [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+ */
+public record InlineContextResource(InlineContext inlineContext) implements AutoCloseable {
+  @Override
+  public void close() throws IOException {
+    inlineContext
+        .localScope()
+        .foreach(
+            s -> {
+              s.scope().close();
+              return BoxedUnit.UNIT;
```
Comment (JaroslavTulach) [inline engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResource.java]: Please simplify and use `null`. That will remove needless dependency on Scala core libraries.

File: engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResourceBuilder.java [hunk 10]
```diff
@@ -0,0 +1,28 @@
+package org.enso.compiler.benchmarks.inline;
+
+import org.enso.compiler.PackageRepository;
+import org.enso.compiler.context.InlineContext;
+import org.enso.interpreter.node.MethodRootNode;
+import org.enso.interpreter.runtime.EnsoContext;
+import org.enso.interpreter.runtime.data.Type;
+import org.enso.interpreter.runtime.scope.ModuleScope;
+
+public record InlineContextResourceBuilder(
```
Comment (JaroslavTulach) [inline engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResourceBuilder.java]: Builder pattern has setter methods that return `this` and mutate its internal state. According to the previous description `record` cannot be a _builder_ - it might be a [cumulative factory](http://wiki.apidesign.org/wiki/CumulativeFactory), however.

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala [hunk 11]
```diff
@@ -675,6 +675,17 @@ object Graph {
 
       isDirectChildOf || isChildOfChildren
     }
+
+    private def removeScope(scope: Scope): Unit = {
+      childScopes = childScopes.filter(_ != scope)
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:680]: Just a _threading note_: this is probably not thread safe... in case we want to evaluate _visualizations_ in parallel, we may face issues like this at various places.

File: engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResourceBuilder.java (hunk 10 above)
Comment (hubertp) [reply engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResourceBuilder.java]: Fair enough, thanks

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala (hunk 11 above)
Comment (hubertp) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala:680]: Yeah, we are likely to open a can of worms.
