### PR TITLE
Fix redundant imports when selecting options from the dropdown widget

### LINKED ISSUE #6816: IDE inserts import for `Boolean` when `True` is selected from the dropdown
### What type of issue is this?

Permanent – Occurring repeatably

### What issue are you facing?

IDE inserts a new import for `Boolean` when `True` is selected from the dropdown, even though the `Boolean` type is reexported from `Standard.Base.Main`.

```
from Standard.Base.Data.Boolean import Boolean
```

This does not happen when `True` is selected from the Component Browser.

### Expected behaviour

IDE does not insert additional imports when `True` is selected from the dropdown.

### How we can reproduce it?

- Create `Statistic.Skew` node
- Select `True` from the dropdown
- See the new `from Standard.Base.Data.Boolean import Boolean` import

### Screenshots or screencasts

2023-05-23-002251_992x632_scrot

### Logs

The engine sends suggestion updates with the proper `reexport` field for `Boolean` type and constructors:
```json
{"type":"Add","id":1615,"suggestion":{"type":"type","module":"Standard.Base.Data.Boolean","name":"Boolean","params":[],"parentType":"Standard.Base.Any.Any","documentation":" A type with only two possible values.\n\nThe boolean type represents the two truth values of boolean logic. It is\nprimarily used for control-flow.","reexport":"Standard.Base.Main"}}

{"type":"Add","id":1616,"suggestion":{"type":"constructor","module":"Standard.Base.Data.Boolean","name":"True","arguments":[],"returnType":"Standard.Base.Data.Boolean.Boolean","reexport":"Standard.Base.Main"}}

{"type":"Add","id":1617,"suggestion":{"type":"constructor","module":"Standard.Base.Data.Boolean","name":"False","arguments":[],"returnType":"Standard.Base.Data.Boolean.Boolean","reexport":"Standard.Base.Main"}}
```

[project-manager.log.zip](https://github.com/enso-org/enso/files/11537224/project-manager.log.zip)

### Enso Version

b353b35f5

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.126

### Operating System

Linux

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #6816.

The code for adding imports for dropdown widgets was unified with CB. The code was moved from the searcher controller to the graph controller.

Also, I changed the signature for a few `lookup_*` methods of the suggestion database, because I have always found it weird that they return `Option` instead of `Result`. They now work nicely with the surrounding code.

https://github.com/enso-org/enso/assets/6566674/49125f8d-096e-4cca-a922-4811ed717a4d

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/controller/graph.rs [hunk 1]
```diff
@@ -670,24 +697,81 @@ impl Handle {
...
+            .filter_map(|requirement| match requirement {
+                RequiredImport::Entry(entry) => Some(
+                    entry.required_imports(&self.suggestion_db, module_qualified_name.as_ref()),
+                ),
+                RequiredImport::Name(name) => {
+                    let (_id, entry) = self.suggestion_db.lookup_by_qualified_name(&name).ok()?;
+                    let defined_in = module_qualified_name.as_ref();
+                    Some(entry.required_imports(&self.suggestion_db, defined_in))
+                }
+            })
```
Comment (kazcw) [inline app/gui/src/controller/graph.rs]: I think there's some common code here, `Some(entry.required_imports(&self.suggestion_db, ..`. Extracting it would make the branches easier to read.

File: app/gui/src/controller/graph.rs [hunk 2]
```diff
@@ -670,24 +697,81 @@ impl Handle {
 
     /// Add a necessary unqualified import (`from module import name`) to the module, such that
     /// the provided fully qualified name is imported and available in the module.
-    pub fn add_import_if_missing(
+    pub fn add_import_if_missing(&self, qualified_name: QualifiedName) -> FallibleResult {
+        self.add_required_imports(iter::once(RequiredImport::Name(qualified_name)), true)
+    }
+
+    /// Add imports to the module, but avoid their duplication. Temporary imports added by passing
+    /// `permanent: false` can be removed by calling [`Self::clear_temporary_imports`].
```
Comment (kazcw) [inline app/gui/src/controller/graph.rs]: Could use some higher-level docs explaining the need for temporary imports.

File: app/gui/src/controller/graph.rs [hunk 3]
```diff
@@ -670,24 +697,81 @@ impl Handle {
...
+    #[profile(Debug)]
+    pub fn add_required_imports<'a>(
         &self,
-        qualified_name: double_representation::name::QualifiedName,
+        import_requirements: impl Iterator<Item = RequiredImport>,
+        permanent: bool,
```
Comment (kazcw) [inline app/gui/src/controller/graph.rs]: An `enum` to make this self-describing would be nice, since this is used from other modules.

**Review by kazcw — APPROVED** [review]
Looks good. A few nits.

File: app/gui/src/controller/graph.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/controller/graph.rs]: Done

File: app/gui/src/controller/graph.rs (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/controller/graph.rs]: Done

File: app/gui/src/controller/graph.rs (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/controller/graph.rs]: Done

**Comment by xvcgreg** [comment]
@vitvakatu What's the status here?

**Review by wdanilo — APPROVED** [review]
Nice solution!

**Comment by vitvakatu** [comment]
@xvcgreg QA requested, @Frizi will report results.

File: app/gui/suggestion-database/src/lib.rs [hunk 4]
```diff
@@ -476,22 +480,29 @@ impl SuggestionDatabase {
...
+    ) -> FallibleResult<(SuggestionId, Rc<Entry>)> {
         let name = name.into();
         let segments = name.segments().map(CloneRef::clone_ref);
-        let id = self.qualified_name_to_id_map.borrow().get(segments);
-        id.and_then(|id| Some((id, self.lookup(id).ok()?)))
+        let id = self
+            .qualified_name_to_id_map
+            .borrow()
+            .get(segments)
+            .ok_or(NoSuchEntryWithName(name.to_string()))?;
```
Comment (Frizi) [inline app/gui/suggestion-database/src/lib.rs]: This eagerly allocates the string even if the lookup succeeded. You could use `ok_or_else` to prevent that.

File: app/gui/suggestion-database/src/lib.rs [hunk 5]
```diff
@@ -1328,7 +1339,7 @@ pub mod test {
 
     fn lookup_id_by_name(db: &SuggestionDatabase, name: &str) -> Option<entry::Id> {
         let name = QualifiedName::from_text(name).ok()?;
-        let (id, _) = db.lookup_by_qualified_name(&name)?;
+        let (id, _) = db.lookup_by_qualified_name(&name).ok()?;
```
Comment (Frizi) [inline app/gui/suggestion-database/src/lib.rs]: This method could also return a `FallibleResult`. I know it's a test helper, but actually not throwing away the errors here might aid some future debugging when the tests fail.

File: app/gui/suggestion-database/src/lib.rs [hunk 6]
```diff
@@ -818,7 +829,7 @@ pub mod test {
     /// is [`None`].
     fn lookup_and_verify_empty_result(db: &SuggestionDatabase, fully_qualified_name: &str) {
         let lookup = db.lookup_by_qualified_name_str(fully_qualified_name);
-        assert_eq!(lookup, None);
+        assert!(lookup.is_err());
```
Comment (Frizi) [inline app/gui/suggestion-database/src/lib.rs]: should this be a downcast and `assert_matches!` instead? Just to make sure that it's the specific error kind that we expect here.

**Comment by Frizi** [comment]
QA Status: 💚 
===
Looks great, barely anything now gets imported when `from Standard.Base import all` is present. And when I manually remove that import, the appropriate gets correctly imported on demand.
