### PR TITLE
Fix Java log initialization in `std-table`

### LINKED ISSUE #8363: Initialization of Java logging inside `std-table` fails.
`std-table` uses `org.apache.poi` for reading Excel files. And `org.apache.poi` tries to initialize loggers. After #7991, all the classes loaded from `std-table` polyglot directory are loaded via our custom `HostClassLoader`, so `org.apache.poi` is loaded via this class loader as well, and the logging initialization fails. Because the `org.slf4j` module is on the module-path, therefore, loaded by the system class loader.

Therefore, `org.apache.poi` most likely does not see the default SLF4J provider and uses NOOP as a fallback.

Reproduce with, e.g.:
```
from Standard.Base import all
from Standard.Table import all

main =
    f = File.new "test/Table_Tests/data/TestSheet.xlsx" . read
    IO.println f
```

Output:
```
+ env JAVA_OPTS=  /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run /home/pavel/tmp/tmp.enso
Nov 22, 2023 12:32:35 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
(Excel_Workbook.Value Name: /xl/workbook.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml (File /home/pavel/dev/enso/test/Table_Tests/data/TestSheet.xlsx) False Infer)
```

Note that because of this, there is no way how to get logs from `org.apache.poi`.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #8363

### Pull Request Description
When executing:
```
from Standard.Base import all
from Standard.Table import all


main =
    fil = "./test/Table_Tests/data/TestSheet.xlsx"
    f = File.new fil . read
    IO.println f

```
with `--log-level TRACE`, I can now see logs from, e.g., `org.apache.xmlbeans` that most likely come from polyglot Java sources in `std-table`. Moreover, there is no longer any warning message about using NOP org.slf4j logger as a fallback.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [X] Unit tests have been written where possible.
  - [X] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package org.enso;
+
+import java.util.List;
+
+public class ClassLoaderConstants {
+
+  public static final List<String> RESOURCE_DELEGATION_PATTERNS = List.of("org.slf4j", "ch.qos");
+  public static final List<String> CLASS_DELEGATION_PATTERNS =
+      List.of("org.graalvm", "java", "org.slf4j", "ch.qos");
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java]: It would be good to add some doc explaining what these patterns are for.

e.g. I assume these are patterns that determine packages which are always loaded using the system class loader? A comment saying that would make it easier to understand.

**Review by 4e6 — APPROVED** [review]
Some docs would be helpful indeed

**Review by radeusgd — APPROVED** [review]
Thanks for the fix!

Integrating this into my current branch, I can again see Apache POI logs.

File: engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java (hunk 1 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java]: Docs added in cb6c6a18c592e27d1d67676d75ce807c0b023321
