### PR TITLE
Fix loading images and CORS error logs

### LINKED ISSUE #14052: Dashboard calls remote backend when tries to get asset details of a local project
## Issue
When opening a project, there are these errors in console:

```
Access to fetch at 'https://kb6aej61n3.execute-api.eu-west-1.amazonaws.com/assets/project-%2Fhome%2Fdbushev%2FDocuments%2Fenso-projects%2Fcloud-project-339KjlTXGFeCADVAQTnp4AarHlK%2Fproject_root' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I.e. the `/assets/{project-id}` endpoint is called with the local project id.

## Details

GIt bisecting showed that the issue starts appearing in b62d7c7572

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #14052, at least partially. I haven't found anymore CORS

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
CR ✅ 
:shipit:

File: app/gui/src/providers/rightPanel.ts [hunk 1]
```diff
@@ -214,23 +214,18 @@ function useRightPanel(
     return typeof currentItem === 'object' ? currentItem : undefined
   })
 
-  const backendType = computed(() => context.value?.category?.backend ?? BackendType.remote)
+  const backendType = computed(() => context.value?.category?.backend)
+  watchEffect(() => console.error('RP backendType', backendType.value), { flush: 'sync' })
```
Comment (vitvakatu) [inline app/gui/src/providers/rightPanel.ts]: Is this a debug log?

**Review by vitvakatu — APPROVED** [review]
