### PR TITLE
Add various NI reflection and JNI configs to fix connection to Azure storage

### LINKED ISSUE #12448: Remove `libio_grpc_netty_shaded_netty_tcnative_linux_x86_64.so` resource from the distribution
- Since @Akirathan was working on #11483
- and integrated #11874
- we no longer shall include `.so` files inside of JARs and also inside of `enso` _native image_
- however there  are still some:

.so resources
 
- by analyzing _native image_ data collected as part of #12446 
- collected in [this ZIP file](https://github.com/user-attachments/files/19148055/enso-build-report.zip)
- it seems that more than **2.5MB** is wasted in _Google's copy of netty library_

Such a library shall not be present inside of any JAR (but be extracted) and it shall not be present inside of the `enso` native executable.

### LINKED ISSUE #13424: Native library loading issues with Netty for Azure in IDE
```
[DEBUG] [io.netty.handler.ssl.OpenSsl] Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]
    at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
    at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:682)
    at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:108)
```
Confirmed to be an issue on Windows in NI. Can be reproduced via CLI. Affects Linux as well, but with slightly different underlying issue.

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #13424

Probably closes https://github.com/enso-org/enso/issues/12448

Supersedes #13418

### Pull Request Description

Add various reflection and jni NI reachability metadata so that it is possible to list blob storage without any errors (on Linux NI). Windows NI still fails with timeout exception. Will be tackled in a separate PR.

### Important Notes

- Added a test that tries to connect to `ensostorage` Azure blob storage with dummy token.
  - This test used to fail on Windows in NI, now it succeeds.
- Extract `libnetty_tcnative` and `libnetty_transport_native_epoll` native libs from Standard.Microsoft.
  - Previously, `libnetty_tcnative` library could not be loaded on Linux neither on Windows. This is fixed now.
- Add [AzureNativeImageFeature](https://github.com/enso-org/enso/blob/b572eedc3af8ee4fd262e1295419fa91bcf770c7/std-bits/microsoft/src/main/java/org/enso/microsoft/nativeimage/AzureNativeImageFeature.java)
  - This feature scans all the `azure-*.jar` files on classpath.
  - For each of these, it looks for classes that implement `com.azure.xml.XmlSerializable` interface and registers them for reflection
  - Not optimal, but it works.
- Add bunch of `jni` and `reflection` entries to [std-bits/microsoft/.../reachability-metadata.json](https://github.com/enso-org/enso/blob/c64259435dd0874b2cd175c86f3dac8813e29882/std-bits/microsoft/src/main/resources/META-INF/native-image/org/enso/microsoft/reachability-metadata.json)
  - It is now possible to list real blob storage on Linux in NI without any errors with these entries.
  - Windows NI still fails on timeout exception. Will be tackled in separate PR.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by Akirathan** [comment]
`enso --jvm --run test/Microsoft_Tests/src/Azure_Storage_Spec.enso` passes, but `enso --run test/Microsoft_Tests/src/Azure_Storage_Spec.enso` fails with:
```
- [FAILED] Connect to dummy blob storage should fail with connection error [532ms]
        Reason: Expected Authentication error, but actual panic was: (Panic java.lang.LinkageError: Package versions: jackson-core=2.15.2, jackson-databind=2.15.2, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.17.2, azure-core=unknown, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot java.lang.LinkageError: Package versions: jackson-core=2.15.2, jackson-databind=2.15.2, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.17.2, azure-core=unknown, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot)Expected False to be True (at Microsoft_Tests/src/Azure_Storage_Spec.enso:16:17-75).
```

The beginning of the stacktrace of the `LinkageError` is:
```
com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper(ObjectMapperShim.java:87)
   com.azure.core.util.serializer.JacksonAdapter$GlobalXmlMapper.<clinit>(JacksonAdapter.java:65)
   com.azure.core.util.serializer.JacksonAdapter.getXmlMapper(JacksonAdapter.java:469)
   com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$9(JacksonAdapter.java:351)
   com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:488)
   com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:346)
   com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:176)
   com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:150)
   com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:67)
com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)
   com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:131)
   com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:211)
   com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:86)
   com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:124)
   com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:95)
   jdk.proxy4/jdk.proxy4.$Proxy/s1c4e4982.getPropertiesSync(Unknown Source)
   com.azure.storage.blob.implementation.ContainersImpl.getPropertiesWithResponse(ContainersImpl.java:1471)
   com.azure.storage.blob.BlobContainerClient.lambda$getPropertiesWithResponse$2(BlobContainerClient.java:672)
   com.azure.storage.common.implementation.StorageImplUtils.sendRequest(StorageImplUtils.java:494)
   com.azure.storage.blob.BlobContainerClient.getPropertiesWithResponse(BlobContainerClient.java:674)
   com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:345)
   com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:324)
   org.enso.microsoft.azure.AzureBlobStorage.listBlob(AzureBlobStorage.java:53)
```

This is a different stack trace than on JVM. On JVM, for XML (de)serialization, Azure relies on reflection. More specifically, the [com.azure.core.implementation.ReflectionSerializable.supportsXmlSerializable](https://github.com/Azure/azure-sdk-for-java/blob/5c44ca3a81075bc2e3d5bba4b6c2f0002564a484/sdk/core/azure-core/src/main/java/com/azure/core/implementation/ReflectionSerializable.java#L177) returns true for all the classes. In NI, this is not true, because the classes are probably not registered for reflection, and so Azure tries to create a serializer for XML with [com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper](https://github.com/Azure/azure-sdk-for-java/blob/5c44ca3a81075bc2e3d5bba4b6c2f0002564a484/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/ObjectMapperShim.java#L82), and that fails.

By the way, calling [com.azure.core.implementation.jackson.ObjectMapperShim.createXmlMapper](https://github.com/Azure/azure-sdk-for-java/blob/5c44ca3a81075bc2e3d5bba4b6c2f0002564a484/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/ObjectMapperShim.java#L82) directly in JVM fails as well with the same exception.

**Comment by Akirathan** [comment]
Adding dependency `com.faster4xml.jackson.dataformat:jackson-dataformat-xml` with:
```patch
diff --git a/build.sbt b/build.sbt
index 344637625f..d6a722598e 100644
--- a/build.sbt
+++ b/build.sbt
@@ -5314,7 +5314,10 @@ lazy val `std-microsoft` = project
       "com.microsoft.sqlserver"   % "mssql-jdbc"              % mssqlserverJDBCVersion,
       "com.azure"                 % "azure-identity"          % azureIdentityVersion exclude ("net.java.dev.jna", "jna") exclude ("net.java.dev.jna", "jna-platform"),
       "com.azure.resourcemanager" % "azure-resourcemanager"   % azureResourceVersion,
-      "com.azure"                 % "azure-storage-blob"      % azureBlobStorageVersion
+      "com.azure"                 % "azure-storage-blob"      % azureBlobStorageVersion,
+      // Using the version of dataformat-xml that azure-core depends on.
+      // So no `jacksonVersion` on purpose.
+      "com.fasterxml.jackson.dataformat" % "jackson-dataformat-xml" % "2.18.1",
     ),
     extractNativeLibs := Def.task {
       import sbt.util.CacheImplicits._
```
does not work. The test fails with:
```
[WARN] [2025-07-02T19:31:57+02:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Candidate library enso_dev.Benchmarks at [***/Benchmarks] may not be AOT ready! Use --jvm option when encoutering problems.
[WARN] [2025-07-02T19:31:57+02:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Candidate library enso_dev.Table_Tests at [***/Table_Tests] may not be AOT ready! Use --jvm option when encoutering problems.
[WARN] [2025-07-02T19:31:57+02:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Candidate library enso_dev.Base_Tests at [***/Base_Tests] may not be AOT ready! Use --jvm option when encoutering problems.
[WARN] [2025-07-02T19:31:57+02:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Candidate library enso_dev.Snowflake_Tests at [***/Snowflake_Tests] may not be AOT ready! Use --jvm option when encoutering problems.
[WARN] [2025-07-02T19:31:57+02:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Candidate library enso_dev.Generic_JDBC_Tests at [***/Generic_JDBC_Tests] may not be AOT ready! Use --jvm option when encoutering problems.
[WARN] [2025-07-02T19:32:02+02:00] [org.enso.microsoft.azure.AzureBlobStorage] List Blob Storage: ensostorage : {}
[ERROR] [2025-07-02T19:32:02+02:00] [com.azure.core.implementation.jackson.ObjectMapperShim] Package versions: jackson-core=2.15.2, jackson-databind=2.15.2, jackson-dataformat-xml=2.18.1, jackson-datatype-jsr310=2.17.2, azure-core=unknown, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
[FAILED] Azure_Storage: [0/1, 498ms]                                  

    - [FAILED] Connect to dummy blob storage should fail with authentication error [498ms]
        Reason: Expected Authentication error, but actual panic was: (Panic java.lang.LinkageError: Package versions: jackson-core=2.15.2, jackson-databind=2.15.2, jackson-dataformat-xml=2.18.1, jackson-datatype-jsr310=2.17.2, azure-core=unknown, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot java.lang.LinkageError: Package versions: jackson-core=2.15.2, jackson-databind=2.15.2, jackson-dataformat-xml=2.18.1, jackson-datatype-jsr310=2.17.2, azure-core=unknown, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot)Expected False to be True (at Microsoft_Tests/src/Azure_Storage_Spec.enso:16:17-75).


0 tests succeeded.
1 tests failed.
0 tests skipped.
0 groups skipped.

Failed tests: 'Connect.to.dummy.blob.storage.should.fail.with.authentication.error'
```

**Comment by Akirathan** [comment]
With d125725fc67a57f847dca60f4f3a07aa87f3f53a, `Azure_Storage_Spec` tests passes on NI in Linux. [AzureNativeImageFeature](https://github.com/enso-org/enso/blob/d125725fc67a57f847dca60f4f3a07aa87f3f53a/std-bits/microsoft/src/main/java/org/enso/microsoft/nativeimage/AzureNativeImageFeature.java) adds all the necessary classes for reflection. There are 101 classes registered for reflection in that feature. It is probably unnecessarily many, but we can scale that down in subsequent commits. Good thing is that the test is now working. At least on Linux.

**Comment by Akirathan** [comment]
`Azure_Storage_Spec` also passes on Windows CI Native tests - https://github.com/enso-org/enso/actions/runs/16049267549/job/45290085685#step:14:854

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Test Azure SAS Token support · enso-org/enso@12a80eb</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Test Azure SAS Token support · enso-org/enso@12a80eb</div></blockquote>

**Comment by Akirathan** [comment]
With b572eedc3af8ee4fd262e1295419fa91bcf770c7, there should be fewer methods registered for reflection. I tested it locally and it works, let's wait for Windows Native test one more time.

**Comment by Akirathan** [comment]
Logs when attempting to connect to a real Azure storage:
- Windows NI: [james-project-manager-2025-07-03.0.ni.log](https://github.com/user-attachments/files/21063694/james-project-manager-2025-07-03.0.ni.log)
- Linux NI: [pavel-cli-2025-07-04.0.ni.log](https://github.com/user-attachments/files/21063795/pavel-cli-2025-07-04.0.ni.log)

Observations from logs:
- Both Windows and Linux are unable to load `netty_tcnative` native library and fallback to the "default" OpenSSL engine.
  - Windows timeouts during handshake, but Linux does not. Maybe the "default" OpenSSL engine for Windows is "slower".
- Both Windows and Linux have multiple `NoSuchMethodException` thrown for various methods from `reactor-netty-core-1.0.48.jar`.
  - Should be fixed by https://github.com/enso-org/enso/pull/13420/commits/e273b28cc48855dcdf800365b39d55d930f7924d

Another issue to tackle: **Ensure that `netty_tcnative` native lib is loaded**. Will extract this native library from `netty-tcnative-boringssl-static-2.0.70.Final-linux-x86_64.jar`.

**Comment by Akirathan** [comment]
With https://github.com/enso-org/enso/pull/13420/commits/b0f978c0325aa0a44bc781c5d44f56561051f764, both `libnetty_tcnative_linux_x86_64.so` and `libnetty_transport_native_epoll_x86_64.so` are extracted into `built-distribution/**/Standard/Microsoft/0.0.0-dev/polyglot/lib` directory.

Trying to explicitly load `System.loadLibrary("netty_tcnative_linux_x86_64")` with:
```patch
Subject: [PATCH] [WIP] myAzureTest
---
Index: std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureBlobStorage.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureBlobStorage.java b/std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureBlobStorage.java
--- a/std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureBlobStorage.java	(revision a85e8c60862fc6e042cfcc1a3646a98da5d4abb9)
+++ b/std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureBlobStorage.java	(date 1751647736727)
@@ -87,4 +87,17 @@
     LOGGER.trace("Downloaded blob to: {}", tempFile);
     return tempFile.toString();
   }
+
+  public static void myAzureTest() {
+    System.out.println("[AzureBlobStorage] myAzureTest");
+    var libName = "netty_tcnative_linux_x86_64";
+    try {
+      System.loadLibrary(libName);
+    } catch (Throwable e) {
+      System.err.println("[AzureBlobStorage] Failed to load native library: " + libName);
+      System.err.println("Error: " + e.getMessage());
+      e.printStackTrace(System.err);
+      throw new AssertionError("Native library '" + libName + "' could not be loaded");
+    }
+  }
 }
Index: engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java b/engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java
--- a/engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java	(revision a85e8c60862fc6e042cfcc1a3646a98da5d4abb9)
+++ b/engine/runtime/src/main/java/org/enso/interpreter/runtime/nativeimage/NativeLibrarySearchPath.java	(date 1751646977983)
@@ -3,6 +3,7 @@
 import java.lang.invoke.MethodHandle;
 import java.nio.file.Files;
 import java.nio.file.Path;
+import java.util.Arrays;
 import org.graalvm.nativeimage.ImageInfo;
 import org.graalvm.nativeimage.ImageSingletons;
 
@@ -43,6 +44,7 @@
   public static void addToSearchPath(String path) {
     if (ImageInfo.inImageRuntimeCode()) {
       assert Files.isDirectory(Path.of(path));
+      System.out.println("[NativeLibrarySearchPPath] Adding path " + path + " to native library search path.");
       addPath(path);
     }
   }
@@ -60,6 +62,8 @@
     var newValue = new String[oldValue.length + 1];
     System.arraycopy(oldValue, 0, newValue, 0, oldValue.length);
     newValue[newValue.length - 1] = path;
+    System.out.println("[NativeLibrarySearchPath] Setting newValue = "
+        + Arrays.toString(newValue));
     setFieldValue(newValue);
   }
 
Index: distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso b/distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso
--- a/distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso	(revision b572eedc3af8ee4fd262e1295419fa91bcf770c7)
+++ b/distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso	(date 1751624767444)
@@ -1,4 +1,9 @@
 export project.Connection.SQLServer_Details.SQLServer_Details
 
 export project.Azure.Azure
-export project.Azure_Storage.Azure_Storage
\ No newline at end of file
+export project.Azure_Storage.Azure_Storage
+
+polyglot java import org.enso.microsoft.azure.AzureBlobStorage
+
+my_azure_test =
+    AzureBlobStorage.myAzureTest
\ No newline at end of file

```

And executing
```
from Standard.Microsoft import all
main = my_azure_test
```
, JVM works just fine, but NI fails with:
```
[NativeLibrarySearchPPath] Adding path /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib to native library search path.
[NativeLibrarySearchPath] Setting newValue = [/usr/lib64, /lib64, /lib, /usr/lib, /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib]
[NativeLibrarySearchPPath] Adding path /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Database/0.0.0-dev/polyglot/lib/amd64/linux to native library search path.
[NativeLibrarySearchPath] Setting newValue = [/usr/lib64, /lib64, /lib, /usr/lib, /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib, /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Database/0.0.0-dev/polyglot/lib/amd64/linux]
[AzureBlobStorage] myAzureTest
[AzureBlobStorage] Failed to load native library: netty_tcnative_linux_x86_64
Error: Unsupported JNI version 0xffffffff, required by /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib/libnetty_tcnative_linux_x86_64.so
java.lang.UnsatisfiedLinkError: Unsupported JNI version 0xffffffff, required by /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib/libnetty_tcnative_linux_x86_64.so
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:120)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:128)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:84)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibrary0(NativeLibraries.java:147)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryRelative(NativeLibraries.java:133)
	at java.base@24.0.1/java.lang.ClassLoader.loadLibrary(ClassLoader.java:100)
	at java.base@24.0.1/java.lang.Runtime.loadLibrary0(Runtime.java:822)
	at java.base@24.0.1/java.lang.System.loadLibrary(System.java:1663)
	at org.enso.microsoft.azure.AzureBlobStorage.myAzureTest(AzureBlobStorage.java:95)
	at java.base@24.0.1/java.lang.reflect.Method.invoke(Method.java:565)
	at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.reflectInvoke(HostMethodDesc.java:306)
	at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MethodReflectImpl.invoke(HostMethodDesc.java:291)
	at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeReflect.executeImpl(GuestToHostCodeCache.java:110)
	at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:819)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:615)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedRuntimeSupport.callInlined(OptimizedRuntimeSupport.java:275)
	at org.graalvm.truffle/com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at org.graalvm.truffle/com.oracle.truffle.host.HostMethodDesc$SingleMethod$ReflectBase.invokeGuestToHost(HostMethodDesc.java:260)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:877)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doFixed(HostExecuteNode.java:140)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen$Inlined.executeAndSpecialize(HostExecuteNodeGen.java:385)
	at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen$Inlined.execute(HostExecuteNodeGen.java:345)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:465)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:7007)
	at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:6993)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8497)
	at org.enso.interpreter.node.callable.resolver.HostMethodCallNode.resolveHostMethod(HostMethodCallNode.java:223)
	at org.enso.interpreter.node.callable.resolver.HostMethodCallNodeGen.executeAndSpecialize(HostMethodCallNodeGen.java:152)
	at org.enso.interpreter.node.callable.resolver.HostMethodCallNodeGen.execute(HostMethodCallNodeGen.java:114)
	at org.enso.interpreter.node.callable.InvokeMethodNode.doPolyglot(InvokeMethodNode.java:562)
	at org.enso.interpreter.node.callable.InvokeMethodNodeGen.executeAndSpecialize(InvokeMethodNodeGen.java:868)
	at org.enso.interpreter.node.callable.InvokeMethodNodeGen.execute(InvokeMethodNodeGen.java:525)
	at org.enso.interpreter.node.callable.InvokeCallableNode.invokeDynamicSymbol(InvokeCallableNode.java:286)
	at org.enso.interpreter.node.callable.InvokeCallableNodeGen.executeAndSpecialize(InvokeCallableNodeGen.java:274)
	at org.enso.interpreter.node.callable.InvokeCallableNodeGen.execute(InvokeCallableNodeGen.java:226)
	at org.enso.interpreter.node.callable.ApplicationNode.executeGeneric(ApplicationNode.java:97)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:819)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:743)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:667)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:124)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:232)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:106)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:599)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:94)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:168)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:98)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:160)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:108)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:157)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:132)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:94)
	at org.enso.interpreter.node.callable.InvokeMethodNode.doFunctionalDispatchCachedSymbol(InvokeMethodNode.java:161)
	at org.enso.interpreter.node.callable.InvokeMethodNodeGen.executeAndSpecialize(InvokeMethodNodeGen.java:604)
	at org.enso.interpreter.node.callable.InvokeMethodNodeGen.execute(InvokeMethodNodeGen.java:525)
	at org.enso.interpreter.node.callable.InvokeCallableNode.invokeDynamicSymbol(InvokeCallableNode.java:286)
	at org.enso.interpreter.node.callable.InvokeCallableNodeGen.executeAndSpecialize(InvokeCallableNodeGen.java:274)
	at org.enso.interpreter.node.callable.InvokeCallableNodeGen.execute(InvokeCallableNodeGen.java:226)
	at org.enso.interpreter.node.callable.ApplicationNode.executeGeneric(ApplicationNode.java:97)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:37)
	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:78)
	at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:819)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:743)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:667)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:124)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:232)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:106)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:599)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:94)
	at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:94)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:168)
	at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:98)
	at org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:56)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:162)
	at org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:108)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:157)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:132)
	at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:94)
	at org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:84)
	at org.enso.interpreter.node.callable.InteropApplicationNodeGen.executeAndSpecialize(InteropApplicationNodeGen.java:144)
	at org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:95)
	at org.enso.interpreter.runtime.callable.function.Function$Execute.doCall(Function.java:254)
	at org.enso.interpreter.runtime.callable.function.FunctionGen$InteropLibraryExports$Cached.executeAndSpecialize(FunctionGen.java:133)
	at org.enso.interpreter.runtime.callable.function.FunctionGen$InteropLibraryExports$Cached.execute(FunctionGen.java:119)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedExecuteNode.doDefault(PolyglotValueDispatch.java:4649)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedExecuteNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:8317)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedExecuteNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:8269)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteNoArgsNode.doDefault(PolyglotValueDispatch.java:4756)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$ExecuteNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:8714)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:819)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:743)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:667)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:124)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:232)
	at org.graalvm.truffle.runtime.svm/com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:106)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedRuntimeSupport.callProfiled(OptimizedRuntimeSupport.java:291)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.execute(PolyglotValueDispatch.java:2662)
	at org.graalvm.polyglot/org.graalvm.polyglot.Value.execute(Value.java:1047)
	at org.enso.polyglot.Function.execute(Function.scala:17)
	at org.enso.runner.Main.runMain(Main.java:958)
	at org.enso.runner.Main.runSingleFile(Main.java:921)
	at org.enso.runner.Main.handleRun(Main.java:818)
	at org.enso.runner.Main.mainEntry(Main.java:1193)
	at org.enso.runner.Main.lambda$handleLaunch$24(Main.java:1661)
	at org.enso.runner.Main.withProfiling(Main.java:1305)
	at org.enso.runner.Main.handleLaunch(Main.java:1657)
	at org.enso.runner.Main.launch(Main.java:1588)
	at org.enso.runner.Main.main(Main.java:1096)
	at java.base@24.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Execution finished with an error: Native library 'netty_tcnative_linux_x86_64' could not be loaded
        at <java> org.enso.microsoft.azure.AzureBlobStorage.myAzureTest(AzureBlobStorage.java:100)
        at <enso> Main.my_azure_test(Main.enso:9:5-32)
        at <enso> tmp.main(tmp.enso:19:5-17)
Native library 'netty_tcnative_linux_x86_64' could not be loaded
```

## TL;DR
Loading `netty_tcnative_linux_x86_64` native library in NI fails with **Unsupported JNI version 0xffffffff, required by /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Microsoft/0.0.0-dev/polyglot/lib/libnetty_tcnative_linux_x86_64.so**

**Comment by Akirathan** [comment]
It seems that `JNI_OnLoad` inside `libnetty_tcnative.so` is failing. Defined most probably in https://github.com/netty/netty-tcnative/blob/53102a197cb92c554fda59f7893fddbd65b6c1f7/openssl-dynamic/src/main/c/jnilib.c#L297

**Comment by Akirathan** [comment]
I successfully reproduced the problem on a separate project, which I have pushed to https://github.com/Akirathan/netty-playground. In the [Native Image logs](https://github.com/Akirathan/netty-playground/blob/master/ni.log), you can see that it fails with the exact same failures that we have in Enso:
- [netty_tcnative lib fails to load](https://github.com/Akirathan/netty-playground/blob/9470949408fd97980bab6b2d05a48968f29eeaf3/ni.log#L47)
- Multiple `NoSuchMethodException` for methods inside `reactor-netty-core-1.0.48.jar`, for example at https://github.com/Akirathan/netty-playground/blob/9470949408fd97980bab6b2d05a48968f29eeaf3/ni.log#L326

Minimal reproduced for the failing `JNI_OnLoad` function is in https://github.com/Akirathan/netty-playground/pull/1

**Comment by Akirathan** [comment]
Inspired by the fix in https://github.com/Akirathan/netty-playground/pull/1#issuecomment-3049463926, adding some `io.netty.internal` classes in `jni` entry inside `reachability-metadata.json` in e588f92ec019b8b0958a069b4962185f4e71dd5b gets us further:

[pavel-cli-2025-07-08.ni.log](https://github.com/user-attachments/files/21126798/pavel-cli-2025-07-08.ni.log)

`libnetty_tcnative` now successfully loads. There is a different error now:
```
[ERROR] [2025-07-08T19:23:15+02:00] [reactor.netty.tcp.TcpClientSecure] Failed to build default ssl provider
[WARN] [2025-07-08T19:23:15+02:00] [reactor.core.Exceptions] throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
[WARN] [2025-07-08T19:23:15+02:00] [reactor.core.Exceptions] throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
[WARN] [2025-07-08T19:23:15+02:00] [reactor.core.Exceptions] throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
[WARN] [2025-07-08T19:23:15+02:00] [reactor.core.Exceptions] throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
Result: (Panic java.lang.ExceptionInInitializerError java.lang.ExceptionInInitializerError)

```

**Comment by Akirathan** [comment]
On https://github.com/enso-org/enso/pull/13420/commits/c64259435dd0874b2cd175c86f3dac8813e29882, I am happy to announce that **it works on my machine!!**:
[pavel-cli-2025-07-08.02.ni.log](https://github.com/user-attachments/files/21129226/pavel-cli-2025-07-08.02.ni.log)

That is, listing Azure blob storage succeeds without any NI-related errors.

Once NI is build for Windows, @jdunkerley please test it.

File: std-bits/microsoft/src/main/java/org/enso/microsoft/nativeimage/AzureNativeImageFeature.java [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+        access.findClassByName("com.azure.core.exception.HttpResponseException");
+    if (httpExceptionClass == null) {
+      throw new IllegalStateException(
+          "HttpResponseException class not found: com.azure.core.exception.HttpResponseException");
+    }
+
+    for (var path : access.getApplicationClassPath()) {
+      var fileName = path.getFileName().toString();
+      if (fileName.startsWith("azure") && fileName.endsWith(".jar")) {
+        var xmlClasses = findImplementationClasses(access, path, xmlSerializableClass);
```
Comment (JaroslavTulach) [inline std-bits/microsoft/src/main/java/org/enso/microsoft/nativeimage/AzureNativeImageFeature.java:52]: Consider scanning only the classes that get included in Native image:
```java
   @Override
    public void duringSetup(DuringSetupAccess access) {
        access.registerObjectReplacer((obj) -> {
            if (obj instanceof Type type) {
                var str = type.toString();
                if (str.startsWith("class ")) {
                    var typeName = str.substring(6);
                    /// fdafds
                }
                alreadyProcessed.add(type);
            }
            return obj;
        });
    }
```
- once https://github.com/oracle/graal/issues/11503 allows you to work with `Type` and `AnnotatedElement`

**Review by JaroslavTulach — APPROVED** [review]
Being able to load the library is a step forward. Let's integrate that!

**Review by jdunkerley — APPROVED** [review]
