### PR TITLE
Stability improvements in visualizations.

### LINKED ISSUE #5651: Table and error visualization seem to be randomly not working
### Discord username

_No response_

### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When trying to preview nodes, sometimes the visualization shows up empty white box.

image
image

It seems like warnings attached to the value may have a play in this, but it is inconsistent, so it is hard to say.

### Expected behaviour

The visualization should show up.

### How we can reproduce it?

Add nodes as shown on the screenshots.

### Screenshots or screencasts

image
image

### Enso Version

https://github.com/enso-org/enso/pull/5605

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11

### Hardware you are using

Thinkpad X1 Carbon G10, i7-1280P, 32GB RAM

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

- Handle `WithWarnings` in `IndirectInvokeCallableNode`.
- Handle no RootNode in `ErrorResolver`.
- Allow table vizualisation to cope if no `data` passed.
- Add `Warning.has_warnings` to check if warnings present.
- Adjust `set_value` for `JS_Object` so creates a new object each time.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]
Approve for the js visualization file

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java [hunk 1]
```diff
@@ -52,6 +52,37 @@ public abstract Object execute(
       InvokeCallableNode.ArgumentsExecutionMode argumentsExecutionMode,
       BaseNode.TailStatus isTail);
 
+  @Specialization
+  Object invokeWithWarnings(
+          WithWarnings warnings,
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java]: Rather than expecting a value of type `WithWarnings` you should specialize on `Object` with a guard `warnings.Library.hasWarnings(obj)`.
The result is the same but I believe it's less likely to cause bugs in the future.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java [hunk 2]
```diff
@@ -16,9 +18,7 @@
 import org.enso.interpreter.runtime.callable.atom.Atom;
 import org.enso.interpreter.runtime.callable.atom.AtomConstructor;
 import org.enso.interpreter.runtime.callable.function.Function;
-import org.enso.interpreter.runtime.error.DataflowError;
-import org.enso.interpreter.runtime.error.PanicException;
-import org.enso.interpreter.runtime.error.PanicSentinel;
+import org.enso.interpreter.runtime.error.*;
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java]: Try to avoid wildcards.

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala [hunk 3]
```diff
@@ -39,7 +39,10 @@ object ErrorResolver {
     node.map(x => {
       x.getEncapsulatingSourceSection match {
         case null =>
-          Api.StackTraceElement(x.getRootNode.getName, None, None, None)
+          x.getRootNode match {
+            case null => null
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala]: I would change that to `node.flatMap(... ` and return `None`/`Some` as appropriate with a guard
```
case null if x.getRootNode == null => None
case null => Some(Api.Stack...)
case section => Some(...)
``` 
and not do filtering

**Review by hubertp — APPROVED** [review]
Mostly style nits

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso [hunk 4]
```diff
@@ -114,12 +114,13 @@ type JS_Object
...
     from_pairs : Vector -> JS_Object
     from_pairs pairs =
-        js_object = pairs.fold new_object current->pair->
+        js_object_fn = pairs.fold new_object current->pair->
             case pair.first of
                 text : Text ->
                     js_value = pair.second.to_js_object
                     set_value current text js_value
                 _ -> Error.throw (Illegal_Argument.Error "JS_Object.from_pairs: key must be a Text value")
+        js_object = js_object_fn
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso]: I'd like to understand what this changes. To my intuition this should be the same before and after, no?

Is `js_object_fn` a zero-argument function block? From my understanding it should be a simple value.

**Review by hubertp — APPROVED** [review]

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso [hunk 5]
```diff
@@ -286,8 +287,7 @@ foreign js get_value object key = """
     return object[key]
 
 foreign js set_value object key value = """
-    object[key] = value
-    return object
+    return {...object, [key]: value}
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:289]: My intuition would tell me to write 
```suggestion
    return {...object, key: value}
```

Could you tell me what is the purpose of `[_]` here?

File: distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso [hunk 6]
```diff
@@ -25,6 +25,12 @@ type Warning
         origin = Runtime.get_stack_trace
         attach_with_stacktrace value warning (origin.drop (Index_Sub_Range.First 1))
 
+    ## UNSTABLE
+
+       Are any warnings attached to the value?
+    has_warnings : Any -> Boolean
+    has_warnings value = has_warnings value
```
Comment (radeusgd) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso]: I know this follows our name resolution conventions correctly, but wow that looks so much like it would infinite-loop.

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso]: Maybe worth adding a comment inside of the method explaining this or just renaming the builtin to be safe? But please feel free to ignore, as it's not a priority thing.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java [hunk 7]
```diff
@@ -52,6 +57,37 @@ public abstract Object execute(
       InvokeCallableNode.ArgumentsExecutionMode argumentsExecutionMode,
       BaseNode.TailStatus isTail);
 
+  @Specialization(guards = "warnings.hasWarnings(warning)")
+  Object invokeWithWarnings(
+      Object warning,
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java:67]: My first thought here was that the specialization guard is not disjunctive - how do we ensure for example that `invokeFunction` will not still get a value containing warnings if it was selected before.

But I realised that values with warnings will never have a type `Function` directly, they will have a type `WithWarnings`, so they can only match this branch.

So it looks ok.

But because this is a non-trivial implicit assumption, I'd suggest to add a short comment note around here.

Maybe
```suggestion
  /** Only this specialization will match objects with warnings attached as they will have type `WithWarnings` which is not a subtype of `Function` or other types from specializations below; and the last specialization is a `Fallback`. */
  @Specialization(guards = "warnings.hasWarnings(warning)")
  Object invokeWithWarnings(
      Object warning,
```

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala [hunk 8]
```diff
@@ -36,17 +36,17 @@ object ErrorResolver {
     element: TruffleStackTraceElement
   )(implicit ctx: RuntimeContext): Option[Api.StackTraceElement] = {
     val node = Option(element.getLocation)
-    node.map(x => {
+    node.flatMap(x => {
       x.getEncapsulatingSourceSection match {
-        case null =>
-          Api.StackTraceElement(x.getRootNode.getName, None, None, None)
+        case null if x.getRootNode == null => None
+        case null => Some(Api.StackTraceElement(x.getRootNode.getName, None, None, None))
```
Comment (radeusgd) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala]: Wow this looks like it may have been a pain to debug.

**Review by radeusgd — APPROVED** [review]
Glad that we are getting better stability

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso (hunk 5 above)
Comment (jdunkerley) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:289]: otherwise JS treats key as the name of the field. The `[_]` makes it read the value of the variable.

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:289]: Ah! thanks for the explanation

Comment (radeusgd) [reply distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:289]: I think I often confuse the object syntax between JS and Python in how they handle variables there.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java [hunk 9]
```diff
@@ -85,6 +85,25 @@ public static WithWarnings attach(EnsoContext ctx, Object value, Object warning,
     return new WithWarnings(value, new Warning(warning, origin, ctx.clockTick()));
   }
 
+  @Builtin.Method(
+      name = "has_warnings_builtin",
+      description = "Are any warnings attached to the value.",
+      autoRegister = false)
+  @Builtin.Specialize
+  @CompilerDirectives.TruffleBoundary
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java:93]: Placing this check behind `@TruffleBoundary` will slow the check down significantly.
