### PR TITLE
Fix errors when changing tabs

### LINKED ISSUE #13688: When navigating between the graph editor and the data catalog, I am frequently getting errors and need to quit and restart enso
Have also attached the console log screenshots in case this is helpful.

Image

Image

Image

### PR DESCRIPTION
**Pull request by kazcw**
Fix errors when changing tabs by working around a bug in Veaury.

The Veaury `onBeforeUnmount` hook fails if it is run when the `onMounted` hook was not. Vue may run the unmounting hooks without running `onMounted` when a component is unmounted before its `onMounted` hook has been run. In `reactComponent`, patch the component created by `applyPureVueInReact` to skip running the cleanup logic if it was never actually mounted. Add a lint rule to ensure the buggy function is never used directly.

Fixes #13688.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/util/react.tsx [hunk 1]
```diff
@@ -2,18 +2,31 @@ import { Dialog as DialogReact } from '#/components/Dialog'
...
+import { applyPureReactInVue, type magicOptions } from 'veaury'
 import type { DefineComponent } from 'vue'
+import type { Opt } from 'ydoc-shared/util/data/opt'
 
 /**
  * Creates a Vue component wrapping a React component.
  *
- * This adds type information to {@link applyPureReactInVue}.
+ * This should always be used in preference to {@link applyPureReactInVue}; its type information
+ * more precise, and it works around a bug.
```
Comment (somebody1234) [inline app/gui/src/project-view/util/react.tsx:15]: `more precise` -> `is more precise`

File: app/gui/src/components/ReactLayoutWrapper.vue
Comment (farmaazon) [inline app/gui/src/components/ReactLayoutWrapper.vue:1]: I think this is not used anymore, may be just deleted.

**Review by farmaazon — APPROVED** [review]
