### PR TITLE
Fixing file browser

### LINKED ISSUE #13332: Data.read returns an error on datalink
Image

The datalink points to csv file.
Nightly 4th of June

### LINKED ISSUE #13693: Creating a Data Link to Enso File put wrong path in
Using the Cloud Browse to create a datalink to an Enso file.
- Doubled the user name `enso://Users/james.dunkerley@ensoanalytics.com/james.dunkerley@ensoanalytics.com/Clients_dataset.csv`

When editing the link (probably as path was wrong) the editor had a file type filter of `com`

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #13693 #13332

Although I didn’t reproduce #13693, these code changes can fix the issue. Also adjusting behavior to insert datalink extension (and avoid filtering by `.datalink` extension).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts [hunk 1]
```diff
@@ -94,11 +94,8 @@ export function usePathBrowsing({
         const result = await getChildDirectory(title, prevDir)
         if (!result.ok) {
           const breakReason = result.error.payload.reason
-          if (
-            breakReason === 'notDir' ||
-            (breakReason === 'notFound' && i === path.segments.length - 1)
-          ) {
-            unenteredPathSuffix.value = title
+          if (breakReason === 'notDir' || breakReason === 'notFound') {
+            unenteredPathSuffix.value = path.segments.slice(i).join('/')
```
Comment (farmaazon) [inline app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts:98]: Are there tests for this path? If yes, should not they change?

File: app/gui/src/project-view/components/widgets/FileBrowserWidget.vue [hunk 2]
```diff
@@ -109,15 +109,27 @@ const { currentDirPath, chosenFilename, setPath, enterDir, popTo, append } = use
   home: () => ensoPath(toValue(userFiles.value?.home ?? [])),
   enteredPath,
 })
+// Set initial path when opening the file browser.
 watchEffect(() => setPath(parseEnsoPath(props.choosenPath)))
```
Comment (farmaazon) [inline app/gui/src/project-view/components/widgets/FileBrowserWidget.vue]: Well, if this is watchEffect, the path is set not only when opening, but when property changes? Similarly, other watchEffects' comments say "set something when something changes" but more precise would be "keep synced when something changes", if I read this code properly.

Or maybe normal watches are better here? I think they could be more expressive in what is actually watched.

File: app/gui/src/project-view/components/widgets/FileBrowserWidget/nameBar.ts [hunk 3]
```diff
@@ -20,8 +20,13 @@ export function useNameBar() {
     fileExtensionFilter,
     setFilename: (filename: string) => {
       const [name, extension] = splitFilename(filename)
-      filenameInput.value = name
-      extensionInput.value = extension
+      // Filtering datalinks does not make much sense, and we should probably change behavior for other extensions as well in the future.
+      if (extension === 'datalink') {
+        filenameInput.value = filename
```
Comment (kazcw) [inline app/gui/src/project-view/components/widgets/FileBrowserWidget/nameBar.ts:25]: Should `extensionInput` be cleared here?

**Review by kazcw — COMMENTED** [review]
The file browser logic could benefit from more unit test coverage

File: app/gui/src/project-view/components/widgets/FileBrowserWidget/nameBar.ts (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/widgets/FileBrowserWidget/nameBar.ts:25]: I think not, because it provides a slightly better user experience without unnecessary changes to filtering. However, the entire filtering system, by extension, can be significantly improved.

File: app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts:98]: Yep, tests were broken, fixed now.

File: app/gui/src/project-view/components/widgets/FileBrowserWidget.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/widgets/FileBrowserWidget.vue]: Refactored this code and covered it with basic unit tests.

**Comment by vitvakatu** [comment]
Added more smoke tests for basic functionality of the file browser.

**Review by kazcw — APPROVED** [review]
