### PR TITLE
Add dashboard tests to GUI2 CI; fix dashboard tests

### LINKED ISSUE #8911: Add E2E tests for dashboard to CI
The command to run the tests is `npm run test:e2e` in `app/ide-desktop/lib/dashboard/`.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close #8911
  - Add dashboard unit tests to GUI2 CI
  - Add dashboard E2E tests to GUI2 CI
  - Fix (minor) issues in dashboard unit tests

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

File: build/cli/src/lib.rs [hunk 1]
```diff
@@ -350,7 +350,10 @@ impl Processor {
         match gui.command {
             arg::gui2::Command::Build(job) => self.build(job),
             arg::gui2::Command::Get(source) => self.get(source).void_ok().boxed(),
-            arg::gui2::Command::Test => gui2::tests(&self.repo_root),
+            arg::gui2::Command::Test =>
+                try_join(gui2::tests(&self.repo_root), gui2::dashboard_tests(&self.repo_root))
```
Comment (mwu-tow) [inline build/cli/src/lib.rs:354]: Is it safe to run both tests in parallel?

The `npm install` fails if run in parallel — build script will avoid this here by a lock, but I'm not sure about the tests themselves?

**Review by mwu-tow — APPROVED** [review]

File: build/cli/src/lib.rs (hunk 1 above)
Comment (somebody1234) [reply build/cli/src/lib.rs:354]: i *think* so, the unit tests shouldn't interact with each other, and the e2e tests should be using different ports.

(typechecking might not be safe to run in parallel... but tests shouldn't be typechecking)

Comment (somebody1234) [reply build/cli/src/lib.rs:354]: the tests are very quick to run anyway so it shouldn't hurt to re-run a few times just to be a bit safer

**Review by PabloBuchu — APPROVED** [review]
