### PR TITLE
Ignore port updates on removed nodes

### LINKED ISSUE #10888: Intermittent deletion failures
Sometimes when deleting multiple components, some components are only partially deleted, and remain in the graph in a non-functional state.

I think this is probably related to the `Changed the client-id because another client seems to be using it.` that appears in the logs when multiple components are deleted.

(Reported by @jdunkerley; I have been able to reproduce it once, but not since)

### LINKED ISSUE #10925: Deleting Multiple Nodes only works if nodes selected in right order
If selecting in the correct order it deletes.

https://github.com/user-attachments/assets/acdf834a-fe96-4467-81ac-5b0748192ca9

If selecting in the opposite order only one node correctly gets deleted.

https://github.com/user-attachments/assets/b2cb29f3-718d-46ff-93eb-f62d0b45674c

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #10888, Fixes #10925

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/stores/graph/index.ts [hunk 1]
```diff
@@ -312,16 +312,24 @@ export const { injectFn: useGraphStore, provideFn: provideGraphStore } = createC
 
     function deleteNodes(ids: Iterable<NodeId>) {
       edit((edit) => {
+        const deletedNodes = new Set()
```
Comment (Frizi) [inline app/gui2/src/stores/graph/index.ts:315]: I think we should collect all `ids` ahead of the main loop avoid modifying nodes that we are about to delete as well.

**Review by Frizi — APPROVED** [review]
