### PR TITLE
More descriptive function information

### LINKED ISSUE #7359: Confusing handling of named arguments
Enso reconciles currying, named arguments and argument default values. This however introduces some trade-offs.

#### TL;DR

There is a [specification of named arguments behavior](https://enso.org/docs/developer/enso/syntax/function-arguments.html#named-arguments) and to quote it:

> Named arguments are applied in the order they are given.
> This means that if you positionally apply to an argument `foo` and
> then try to later apply to it by name, this will fail due to currying of functions.

@JaroslavTulach interprets that as a confirmation the current behavior is correct and all we can do is to improve error reporting as [Radek concludes](https://github.com/enso-org/enso/issues/7359#issuecomment-1644476947) too.

#### Original Report

Here I encountered one such issue where the various trade-offs make the behaviour _very_ confusing to the user.

```
from Standard.Base import all

fun a b c =
    IO.println "a = "+a.to_display_text
    IO.println "b = "+b.to_display_text
    IO.println "c = "+c.to_display_text
    a+b+c

main =
    IO.println '\n1:'
    IO.println <| fun "A" "B" "C"
    IO.println '\n2:'
    IO.println <| fun  b="B" "A" "C"
    IO.println '\n3:'
    IO.println <| fun "A" "C" b="B"
    IO.println '\n4:'
    IO.println <| Panic.recover Any <| (fun "A" "C" b="B").length
    IO.println '\n5:'
    IO.println <| fun "A" "C" b="B" "D"
```

yields us:

```
1:
a = A
b = B
c = C
ABC

2:
a = A
b = B
c = C
ABC

3:
named-args.fun[named-args.enso:3-22]

4:
(Error: (No_Such_Method.Error named-args.fun[named-args.enso:3-22] UnresolvedSymbol<length>))

5:
a = A
b = C
c = D
Execution finished with an error: Type error: expected a function, but got ACD.
        at <enso> named-args.main<arg-1>(named-args.enso:19:19-39)
        at <enso> named-args.main(named-args.enso:19:5-39)
```

Let's unpack what is happening here.

1. We just provide all arguments positionally - all is well.
2. We provide the `b` argument as named - it is correctly reordered.
3. We provide the 3 arguments, but now the named `b` argument comes last. This is the most interesting example showing the issue. Due to how our argument resolution works (and this is not fully avoidable if we want to support currying, at least not without some careful limitations), what the system sees: I see argument `"A"`, I pass it to parameter `a`, then I see `"C"`, I've got a function waiting for an argument named `b` - OK all looks good - let's take it. Then I see a _named_ argument `b="B"`. OK but I have a function taking a parameter `c` only - no match - the resolver "suspends" this argument, hoping that once more arguments are provided, maybe our function will return a new function taking more arguments and one of its names will match my pending `b`? Maybe. For now I return a value containing a Function waiting for one parameter - that is what is printed. Note that this 'suspended pending argument' `b="B"` is hidden and it is impossible to see that we are waiting for this argument.
4. Actually I want to come to this in a moment, below.
5. Here we see the same behaviour as in (3), just continued. What happened is that we _did_ provide another argument `"D"`. So my function from step (3) was waiting for one more parameter (named `c`). I got an unnamed argument `"D"` - OK - that sounds good - I provide this argument for the parameter `c`. This runs my function `fun` with args `a="A"`, `b="C"` and `c="D"` - it executes and returns a `Text` value `"ACD"`. But the resolution continues - I'm still pending a named argument `b="B"`. Ok but what the function returned is a `Text` value, **not** a `Function` - so a type error is invoked.

The case (5) alone is problematic, as I get a weird type error which does not really tell me what went wrong. That case is actually an instance of #5219.

But (4) shows something even more concerning. What I do is I expect `fun` to return me a `Text`, so I call `length` on it. What happens then is that my resolution is currently suspended. It resolved to a function that is waiting for one parameter named `c` and is also waiting to apply one named argument `b="B"`. The object returned is a `Function` holding all that 'state'. I call `length` on this and I get a message that a `Function` does not have a method called `length`. Well, fair - functions don't have those. But I have not expected a Function, I've provided 3 arguments to my function `fun` and I expect it to return a `Text`. Instead, I see I'm getting a function - so this looks like a usual case of "not enough arguments" - if I have a function `f x y` and provide just `IO.println (f 1)` I get a function. But wait - I look at the code - `fun` is expecting 3 parameters and **I did provide 3 arguments!**. The issue is that the argument `b="B"` did not match and is silently suspended, with no way to see it.

I've just lost about 30-40 minutes trying to track down a case in my code when this was happening. It is a very confusing kind of error message, because it suggests we do not have enough arguments, but we have all the arguments that we need!

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #7359 by printing more information about the function including partially applied arguments and over-saturated arguments.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 1]
```diff
@@ -353,6 +354,73 @@ public void binaryWithVec() throws Exception {
...
+            .uri(uri)
+            .buildLiteral();
+
+    var module = ctx.eval(src);
+    var mix = module.invokeMember("eval_expression", "mix");
+
+    try {
+      var res = mix.execute(7);
+      fail("No result expected: " + res);
+    } catch (PolyglotException ex) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:381]: After 8014806e6d046bc53fafe20936423cf49bb300d0 it prints error:
```
Type error: expected `x` to be V, but got V.Val[partial:4-4] a=1 b=7 c=_.
```

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 2]
```diff
@@ -353,6 +354,73 @@ public void binaryWithVec() throws Exception {
...
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:415]: Prints following error:
```
Type error: expected `x` to be Integer, but got oversaturated.fn[oversaturated:3-6] self=oversaturated a=2 b=3 +a=4.
```
The `+a` means over-saturated `a` argument.

**Update**: After 8014806e6d046bc53fafe20936423cf49bb300d0 it also includes missing `c=_` argument.

**Comment by radeusgd** [comment]
This looks really awesome and will be immensely helpful! 🎉 

I think we should still add some additional comment in case the RHS is a Function or constructor, to be more friendly to less advanced users. Perhaps [taking inspiration from `Index_Sub_Range` special handling](https://github.com/enso-org/enso/blob/d078a37a6a98022e8374b3273ec078982ecaccd8/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso#L283-L292) we could hint to the user that the function/constructor is likely missing some arguments?

Maybe also if over-saturated arguments show up we should explain it? I don't think anyone seeing this error message will be able to dig up this PR to figure out what `+` means there.

This is a potentially complicated error for beginners so I think it's better for it to be more verbose than to be difficult to understand.

--------

If possible, it would also be cool to add a test to the Enso-side tests checking this in a 'practical scenario'.

Perhaps:
```diff
Index: test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso b/test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
--- a/test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso	(revision 72031726a6181887f62691c194161199382958eb)
+++ b/test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso	(date 1692717513911)
@@ -377,6 +377,13 @@
                 problems3 = [Floating_Point_Equality.Error "Z", Floating_Point_Equality.Error "X"]
                 Problems.test_problem_handling action3 problems3 tester3
 
+        Test.specify "should report a user-friendly type error if the constructor is missing some arguments" <|
+            t1 = table_builder [["Text", ["a", "b"]]]
+            r1 = Panic.recover Any (t1.join t1 on=[Join_Condition.Equals] on_problems=Problem_Behavior.Ignore)
+            r1.should_fail_with Type_Error
+            r1.catch.to_display_text . should_contain "missing argument"
+            r1.catch.to_display_text . should_contain "Join_Condition.Equals"
+
         Test.specify "should correctly handle nulls in equality conditions" pending=db_todo <|
             t1 = table_builder [["X", ["A", Nothing, "a", Nothing, "ą"]], ["Y", [0, 1, 2, 3, 4]]]
             t2 = table_builder [["X", ["a", Nothing, Nothing]], ["Z", [10, 20, 30]]]
```

**Comment by Akirathan** [comment]
Very nice. I have another suggestion. What about displaying unapplied arguments as well? The behavior on this PR:
```
my_func x y =
  x + y

main = my_func
```
Prints
```
tmp.my_func[tmp.enso:1-2] self=tmp
```

With the following patch:
```diff
diff --git a/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java b/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
index 8516bd4b4..025ed0961 100644
--- a/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
+++ b/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
@@ -423,9 +423,11 @@ public final class Function implements EnsoObject {
         .append(end)
         .append("]");
     for (var i = 0; i < schema.getArgumentsCount(); i++) {
+      sb.append(" ").append(schema.getArgumentInfos()[i].getName()).append("=");
       if (preAppliedArguments != null && preAppliedArguments[i] != null) {
-        sb.append(" ").append(schema.getArgumentInfos()[i].getName()).append("=");
         sb.append(iop.toDisplayString(preAppliedArguments[i], false));
+      } else {
+        sb.append("_");
       }
     }
     if (schema.getOversaturatedArguments() != null) {
```

It prints
```
tmp.my_func[tmp.enso:1-2] self=tmp x=_ y=_
```
To visualize that `x` and `y` arguments were not provided. The `_` placeholder is just an idea, it could be different. What do you think @radeusgd @JaroslavTulach ?

**Review by GregoryTravis — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> It prints
> 
> ```
> tmp.my_func[tmp.enso:1-2] self=tmp x=_ y=_
> ```
Good idea to use `_`. I've just integrated your patch as 8014806

**Comment by JaroslavTulach** [comment]
> it would also be cool to add a test to the Enso-side tests checking this in a 'practical scenario'.

Probably better to add such integration tests when we agree on the format of error message.

I tried to apply your patch, but it is not compilable (missing import), neither working (after fixing the import). Yields:
```
   - [FAILED] should report a user-friendly type error if the constructor is missing some arguments [7ms]
        Reason: Expected error Type_Error, but error (Inexhaustive_Pattern_Match.Error Constructor<Equals>) has been returned (at /home/devel/NetBeansProjects/enso/enso.master/test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso:384:13-42).
```
If you get your test working, feel free to commit. Easier and more reliable than sending _"sketch only"_ not fully working patches.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 3]
```diff
@@ -353,6 +354,109 @@ public void binaryWithVec() throws Exception {
...
+            .buildLiteral();
+
+    var module = ctx.eval(src);
+    var mix = module.invokeMember("eval_expression", "mix");
+
+    try {
+      var res = mix.execute(0);
+      fail("No result expected: " + res);
+    } catch (PolyglotException ex) {
+      assertContains("Type error", ex.getMessage());
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:450]: Yields following single line message:
```
Type error: expected `x` to be Integer, but got 
suspended.fn[suspended:3-5] 
self=suspended 
a=_ 
b=suspended.mix<arg-b>[suspended:9:28-30] 
c=suspended.mix<arg-c>[suspended:9:20-22].
```
I assume we want _single line_ messages although the description of arguments may be pretty looong.

**Review by Akirathan — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> we could hint to the user that the function/constructor is likely missing some arguments?

Done in 4105f51b05

File: test/Tests/src/Semantic/Error_Spec.enso [hunk 4]
```diff
@@ -341,4 +342,23 @@ spec =
...
+
+        neg n:Number = -n
+
+        Test.specify "everything is ok" <|
+            neg (my_func -5 -2) . should_equal 7
+
+        Test.specify "try to apply one argument" <|
+            r = Panic.recover Type_Error <| neg (my_func -5)
+            r . should_fail_with Type_Error
+            r.to_display_text.contains "Try to apply y argument" . should_be_true
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Error_Spec.enso]: This will yield nicer message if it ever failed :)
```suggestion
            r.to_display_text.should_contain "Try to apply y argument."
```

File: test/Tests/src/Semantic/Error_Spec.enso [hunk 5]
```diff
@@ -341,4 +342,23 @@ spec =
...
+
+        Test.specify "try to apply two arguments" <|
+            r = Panic.recover Type_Error <| neg my_func
+            r . should_fail_with Type_Error
+            r.to_display_text.contains "Try to apply x, y arguments" . should_be_true
```
Comment (radeusgd) [inline test/Tests/src/Semantic/Error_Spec.enso]:
```suggestion
            r.to_display_text.should_contain "Try to apply x, y arguments."
```

**Comment by radeusgd** [comment]
I pushed a commit ([5c2ef16](https://github.com/enso-org/enso/pull/7629/commits/5c2ef16c42b7efe52f48d968258ba091211ba441)) with a proposed test.

It is currently failing one case:
```
Type Errors:  [4/5, 452ms]
    - everything is ok [1ms]
    - try to apply one argument [253ms]
    - try to apply two arguments [62ms]
    - [FAILED] report unapplied constructor nicely [77ms]
        Reason: The value (Error: Type error: expected `x` to be My_Type, but got Constructor<My_Type.Value>.) did not contain the element (Try to apply foo argument.) (at C:\NBO\enso\test\Tests\src\Semantic\Error_Spec.enso:370:13-73).
    - report partially applied constructor nicely [56ms]
```

Do you think we can extract the argument names from the constructor? (we may need some special case for this, since normally when calling `to_text` on a constructor, we probably don't want them, we'd probably only want them when displayed in the `Type_Error`).

If this is not implementable, we can change the test a bit, but ideally I think it would be great if it could work like this. Note that once one argument in the ctor is applied, it acts as a function and the missing arguments _do show up_ (the latter test case that is passing). And IMO a ctor with 0 vs 1 arguments applied does not differ that much so it shouldn't probably behave much differently in this error - which these tests try to enforce.

File: test/Tests/src/Semantic/Error_Spec.enso [hunk 6]
```diff
@@ -341,4 +344,66 @@ spec =
...
+
+        Test.specify "report unapplied constructor nicely" <|
+            r = Panic.recover Type_Error <| extract My_Type.Value
+            r . should_fail_with Type_Error
+            r.to_display_text.should_contain "Try to apply foo argument."
+
+        Test.specify "report unapplied constructor with default value nicely" <|
+            r = Panic.recover Type_Error <| extract My_Type.Default_Value
+            r . should_fail_with Type_Error
+            r.to_display_text.should_contain "Try to apply bar argument."
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Error_Spec.enso:384]: This message is certainly correct. 
```ruby
type My_Type
    Default_Value foo=2 bar
```
We don't want to encourage users to specify defaulted arguments with the _"Try to apply..."_ message.

However we don't include the defaulted arguments in display of functions neither atom constructors at all. Missing such a slick `x=_` syntax. Moreover default value is specified as AST and I don't want to evaluate it...

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java [hunk 7]
```diff
@@ -318,7 +318,14 @@ Atom instantiate(Object... arguments) throws ArityException {
   @ExportMessage
   @TruffleBoundary
   String toDisplayString(boolean allowSideEffects) {
-    return "Constructor<" + getDisplayName() + ">";
+    var sb = new StringBuilder();
+    sb.append("Constructor<").append(getDisplayName()).append(">");
+    for (var f : getFields()) {
+      if (!f.hasDefaultValue()) {
+        sb.append(" ").append(f.getName()).append("=_");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java:325]: This is a fix for [Radek's test](https://github.com/enso-org/enso/pull/7629#issuecomment-1689700450). Adds enough `field=_` so the `Type_Error` can pick it up and assemble proper _"Try..."_ message.

**Review by radeusgd — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 8]
```diff
@@ -353,6 +354,109 @@ public void binaryWithVec() throws Exception {
...
+    try {
+      var res = mix.execute(7);
+      fail("No result expected: " + res);
+    } catch (PolyglotException ex) {
+      assertContains("Type error", ex.getMessage());
+      assertContains("expected `x` to be V", ex.getMessage());
+      assertContains("got V.Val[partial", ex.getMessage());
+      assertContains("a=1", ex.getMessage());
+      assertContains("b=7", ex.getMessage());
+      assertContains("c=_", ex.getMessage());
```
Comment (hubertp) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:387]: can't we just make it a single line? This feels a bit old to split it into numerous "contains" asserts. Same comment in other cases.

**Review by hubertp — APPROVED** [review]
minor nit re test definition

**Review by 4e6 — APPROVED** [review]
