### PR TITLE
Fix scrolling in file browser widget

### LINKED ISSUE #13633: file browser for credential on Google Analytics read does not scroll, so I can't see my credential file
Image

Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #13633

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserContent.vue [hunk 1]
```diff
@@ -218,6 +218,7 @@ defineExpose({
     class="FileBrowserContent"
     :class="{ centerContent: isEmpty }"
     @click.stop="focused = undefined"
+    @wheel.stop
```
Comment (kazcw) [inline app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserContent.vue]:
```suggestion
    @wheel.stop.passive
```

**Review by kazcw — APPROVED** [review]

**Review by Frizi — APPROVED** [review]
