### PR TITLE
Fix issues with missing sourcemaps

### LINKED ISSUE #6559: Source Map Loading Timeout Warnings in Console When Creating a New Project
Open IDE, and create a new project. The following warning appears in the DevTools console:
```
DevTools failed to load source map: Could not load content for http://localhost:8080/preload.cjs.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for http://localhost:8080/pkg.js.map: Load canceled due to load timeout
```

There should be no warning.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fixes #6559:
```
DevTools failed to load source map: Could not load content for http://localhost:8080/preload.cjs.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for http://localhost:8080/pkg.js.map: Load canceled due to load timeout
```

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
oh @mwu-tow you might want to check that this fixes the issue.
note that the current fix for `preload.cjs` puts the sourcemap inline inside the js file, which will probably slow down startup, but hopefully shouldn't be noticeable

**Comment by mwu-tow** [comment]
@somebody1234 
Why the preload map needs to be inline, while we can ship pkg.js.map?

We've been really very aggressively trying to keep the size down, so increasing the core download size might be somewhat iffy.

**Comment by somebody1234** [comment]
@mwu-tow we don't serve `preload.cjs` - in fact i can't even see it in devtools. i can do some further research into whether we can get it working, but note that `preload.cjs.map` *does* exist beside `preload.cjs`, but for some reason it's trying to fetch `/preload.cjs.map` when `preload.cjs` isn't even served by the server

**Comment by somebody1234** [comment]
alternatively i can just take the `preload.cjs` stuff out of this PR and create a new one if i find a better solution

**Comment by mwu-tow** [comment]
@somebody1234 
> we don't serve preload.cjs - in fact i can't even see it in devtools. i can do some further research into whether we can get it working, but note that preload.cjs.map does exist beside preload.cjs, but for some reason it's trying to fetch /preload.cjs.map when preload.cjs isn't even served by the server

The preload script is loaded by the Electron before loading the actual site, it is shipped and served. I think it does not show up because the server does not serve files from the root of the resources but only from the `assets` subdirectory.

See the resources in the Electron bundle:
obraz

File: app/ide-desktop/lib/client/src/bin/server.ts [hunk 1]
```diff
@@ -22,14 +24,11 @@ const HTTP_STATUS_OK = 200
...
+/** Construct a URL query string with the given parameters. For each `key` - `value` pair,
  * `key=value` will be added to the query. */
 export function urlParamsFromObject(obj: Record<string, string>) {
-    const params = []
-    for (const [key, value] of Object.entries(obj)) {
-        params.push(`${key}=${encodeURIComponent(value)}`)
-    }
-    return params.length === 0 ? '' : '?' + params.join('&')
+    const params = new URLSearchParams(obj).toString()
+    return params ? '?' + params : ''
```
Comment (mwu-tow) [inline app/ide-desktop/lib/client/src/bin/server.ts]: This is a really neat change, yet at the same time, it got me thinking, about whether we need this function at all. It being `string`-ly typed is a code smell to me.
Perhaps we can construct URL by using the URL API rather than by pretty-printing pieces of text together.

File: app/ide-desktop/lib/client/src/bin/server.ts [hunk 2]
```diff
@@ -110,7 +109,10 @@ export class Server {
         } else {
             const url = requestUrl.split('?')[0]
             const resource = url === '/' ? '/index.html' : requestUrl
-            const resourceFile = `${this.config.dir}${resource}`
+            const resourceFile =
+                resource === '/preload.cjs.map'
```
Comment (mwu-tow) [inline app/ide-desktop/lib/client/src/bin/server.ts:105]: Please add a comment on why this single file needs special treatment here.

**Review by mwu-tow — APPROVED** [review]

**Comment by mwu-tow** [comment]
🟢  Did QA, the issue is fixed. Thanks for taking care of it!

File: app/ide-desktop/lib/client/src/bin/server.ts (hunk 1 above)
Comment (somebody1234) [reply app/ide-desktop/lib/client/src/bin/server.ts]: unfortunately it seems even the url api requires properties to be `string`s... but i think it might be a good idea to completely remove `urlParamsFromObject` anyway as the URL APIs can do the same thing?

**Review by PabloBuchu — APPROVED** [review]
