### PR TITLE
Fix rendering of redefined Conversion error

### LINKED ISSUE #7853: Compiler crash when ambiguous `from` conversions are encountered
I wanted to see what currently happens when the user defines 'colliding' from converions (i.e. conversions for the same type from the same type).
```
from Standard.Base import all

type My_A
    Inner x
	Outer x

My_A.from (that:Text) = My_A.Inner that

My_A.from (that:Text) = My_A.Outer that

foo (m:My_A) = m.to_text

main =
    IO.println (foo "TEST")
```

Currently, this code crashes the compiler with the following stack trace:
```
Execution finished with an error: java.lang.IllegalArgumentException: requirement failed: end:40 must be less than or equal to length:39
        at <java> scala.Predef$.require(Predef.scala:337)
        at <java> fansi.Str.$anonfun$overlayAll$2(Fansi.scala:187)
        at <java> fansi.Str.$anonfun$overlayAll$2$adapted(Fansi.scala:179)
        at <java> scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at <java> scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at <java> scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at <java> scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at <java> fansi.Str.overlayAll(Fansi.scala:179)
        at <java> fansi.Str.overlay(Fansi.scala:167)
        at <java> org.enso.compiler.Compiler$DiagnosticFormatter.oneLineFromSourceColored(Compiler.scala:1190)
        at <java> org.enso.compiler.Compiler$DiagnosticFormatter.format(Compiler.scala:1090)
        at <java> org.enso.compiler.Compiler.$anonfun$reportDiagnostics$2(Compiler.scala:1029)
        at <java> org.enso.compiler.Compiler.$anonfun$reportDiagnostics$2$adapted(Compiler.scala:1028)
        at <java> scala.collection.immutable.List.foreach(List.scala:333)
        at <java> org.enso.compiler.Compiler.reportDiagnostics(Compiler.scala:1028)
        at <java> org.enso.compiler.Compiler.$anonfun$reportDiagnostics$1(Compiler.scala:1010)
        at <java> org.enso.compiler.Compiler.$anonfun$reportDiagnostics$1$adapted(Compiler.scala:1008)
        at <java> scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
        at <java> scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
        at <java> scala.collection.immutable.List.foldLeft(List.scala:79)
        at <java> org.enso.compiler.Compiler.reportDiagnostics(Compiler.scala:1008)
        at <java> org.enso.compiler.Compiler.runErrorHandling(Compiler.scala:912)
        at <java> org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:388)
        at <java> org.enso.compiler.Compiler.go$1(Compiler.scala:232)
        at <java> org.enso.compiler.Compiler.runInternal(Compiler.scala:238)
        at <java> org.enso.compiler.Compiler.run(Compiler.scala:135)
        at <java> org.enso.interpreter.runtime.Module.compile(Module.java:372)
        at <java> org.enso.interpreter.runtime.Module.compileScope(Module.java:299)
        at <java> org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:644)
        at <java> org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.executeAndSpecialize(ModuleGen.java:115)
        at <java> org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:104)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4553)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeAndSpecialize(PolyglotValueDispatchFactory.java:10292)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:10244)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.doDefault(PolyglotValueDispatch.java:4618)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:10528)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at <java> org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:972)
        at <java> org.enso.polyglot.Module.getAssociatedType(Module.scala:19)
        at <java> org.enso.runner.Main$.runMain(Main.scala:834)
        at <java> org.enso.runner.Main$.runSingleFile(Main.scala:764)
        at <java> org.enso.runner.Main$.run(Main.scala:646)
        at <java> org.enso.runner.Main$.main(Main.scala:1149)
        at <java> org.enso.runner.Main.main(Main.scala)
```

If I comment out any of the two conversions, it works fine, e.g.:
```
(Outer 'TEST')
```

So it seems that the compiler cannot handle seeing two colliding conversions next to each other.

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Fixes #7853

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java [hunk 1]
```diff
@@ -251,7 +251,7 @@ private List<Definition> translateModuleSymbolImpl(Tree inputAst, List<Definitio
           methodRef,
           args,
           body,
-          getIdentifiedLocation(inputAst, 0, 1, null),
+          getIdentifiedLocation(inputAst, 0, 0, null),
```
Comment (radeusgd) [inline engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java:254]: @JaroslavTulach was there any reason why we had this `+1` offset here?

It meant that a one-line method definition like
```
Foo.from (that : Bar) = 42
```
had its span taken _together_ with the newline at the end of the line. This was then causing problems when rendering the error / constructing its associated `SourceSection` with asserts on (violating `SourceSection.isValid()` if that statement was at the end of the source code, because the additional character was getting out of bounds of the source).

It was inconsistent with other entities, like e.g. imports - where I checked that the entity's source section is created _without_ the trailing newline.

----

So I have removed it here. It seems that all tests are passing so I assume it's OK.

I will add a multiline test just to be sure.

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala [hunk 2]
```diff
@@ -195,7 +195,7 @@ object Redefined {
 
     /** @inheritdoc */
     override def message(source: Source): String =
-      s"Method overloads are not supported: ${targetType.map(_.name + ".").getOrElse("")}from " +
+      s"Ambiguous conversion: ${targetType.map(_.name + ".").getOrElse("")}from " +
```
Comment (radeusgd) [inline engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:198]: I think that this error message may be clearer - conversions work a bit differently than method overloads - they **do overload** the `from` method, just with different types of `that`.

File: engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala [hunk 3]
```diff
@@ -102,7 +102,7 @@ class ReplTest
           result.toString shouldEqual "Error in method `to_text` of [Bar 1]: Expected Text but got 42"
         }
         inside(executor.evaluate("C.Baz 1")) { case Right(result) =>
-          result.toString shouldEqual "Error in method `to_text` of [Baz 1]: Expected Text but got C.to_text[Test:18:1-29]"
+          result.toString shouldEqual "Error in method `to_text` of [Baz 1]: Expected Text but got C.to_text[Test:18:1-28]"
```
Comment (radeusgd) [inline engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala:105]: The relevant line indeed has _only_ 28 characters, so I think that this is an evidence that the fix of the `+1` offset was correct.

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala [hunk 4]
```diff
@@ -230,7 +230,7 @@ object Redefined {
 
     /** @inheritdoc */
     override def showCode(indent: Int): String =
-      s"(Redefined (Conversion ${targetType.map(_.showCode() + ".").getOrElse("")}from $sourceType))"
+      s"(Redefined (Conversion ${targetType.map(_.showCode() + ".").getOrElse("")}from ${sourceType.showCode()}))"
```
Comment (radeusgd) [inline engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:233]: Small irrelevant fix - before printing the redefined conversion as code was leaking a lot of information by using `toString` instead of `showCode` for the `sourceType`. With that it is more compact and closer to what I think `showCode` is supposed to be.

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java:254]: > span taken _together_ with the newline at the end of the line.

It was necessary to be compatible with the old parser and its tests. Now, when the old parser was removed, we see no inconsistency.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java [hunk 5]
```diff
@@ -1,24 +1,45 @@
...
   private static Context ctx;
+  private static Context nonStrictCtx;
+
+  private static final ByteArrayOutputStream out = new ByteArrayOutputStream();
 
   @BeforeClass
   public static void initCtx() {
-    ctx = createDefaultContext();
+    ctx = createDefaultContext(out);
+    nonStrictCtx = createNonStrictContext(out);
```
Comment (JaroslavTulach) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java]: Wouldn't it be better to have another test class? Mixing two contexts inside of one class seems confusing.

File: engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java [hunk 6]
```diff
@@ -32,6 +32,14 @@ protected static Context createDefaultContext() {
     return context;
   }
 
+  protected static Context createNonStrictContext(OutputStream out) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java]: Is there only single usage of this method? Consider using `createDefaultContext` and apply the `STRICT_ERRORS` option to it.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java (hunk 6 above)
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java]: Can I apply options to a Context _after_ it was constructed?

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java (hunk 5 above)
Comment (radeusgd) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java]: Sure, I can split it

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/NonStrictConversionMethodTests.java [hunk 7]
```diff
@@ -86,8 +74,6 @@ public void testAmbiguousConversionUsage() {
 
     Value res = evalModule(nonStrictCtx, src);
     assertEquals(142, res.asInt());
-    // But we should still get the diagnostic!
-    MatcherAssert.assertThat(getStdOut(), Matchers.containsString("Unnamed:7:1: error: Ambiguous conversion: Foo.from Bar is defined multiple times in this module."));
```
Comment (radeusgd) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/NonStrictConversionMethodTests.java]: I had to remove this check, because currently apparently the diagnostics are _not reported at all in the non-strict mode_.

e.g. https://github.com/enso-org/enso/blob/24c0804596dd76c5ce87238f8557243857deb770/engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala#L899-L918

cc: @JaroslavTulach @hubertp is this preferred for some reason? Do we not report the diagnostics, because non-strict mode is essentially _interactive_ mode and these error messages are supposed to reach the IDE through 'other means' (i.e. errors baked in the IR)? Or is this just an oversight?

My intuition is that actually logging these kinds of diagnostics may make it easier to debug issues when IDE fails to execute something, so I'd be happy to enable them, but I first need to know if there is some reason for not-enabling them that I'm not aware of.

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala (hunk 2 above)
Comment (Akirathan) [reply engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:198]: What if I accidentaly do something like this:
```
method x y = x + y
method x = x
```

Would the error message say "Ambiguous conversion" in that case as well? Isn't that misleading? What about trying to distinguish between those two cases - "Ambiguous conversion" VS "Method overload"?

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java [hunk 8]
```diff
@@ -101,4 +119,26 @@ public void testDispatchOnJSDateTime() {
...
+       Foo.from (that:Bar) = Foo.Mk_Foo that.x+1000
+       
+       main = 42
+       """;
+    try {
+      Value res = evalModule(ctx, src);
+      fail("Expected an exception, but got " + res);
+    } catch (Exception e) {
+      assertEquals("Compilation aborted due to errors.", e.getMessage());
+      MatcherAssert.assertThat(getStdOut(), Matchers.containsString("Unnamed:7:1: error: Ambiguous conversion: Foo.from Bar is defined multiple times in this module."));
```
Comment (Akirathan) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java:141]: minor: I believe static methods from `org.hamcrest.MatcherAssert` should follow the same convention as methods from `org.junit.Assert`. That is, they should be directly imported, so that one can write jus `assertThat(..., containsString("...")`.

**Review by Akirathan — APPROVED** [review]
minors. Otherwise LGTM.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java (hunk 8 above)
Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java:141]: Simple `assertNotEquals(getStdOut().indexOf(....), -1)` would be my favorite alternative.

Comment (radeusgd) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java:141]: We already have the dependency available, so I don't see why we shouldn't use it - using the specialized matcher yields much better error messages than '-1 did equal -1'.

File: engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala (hunk 2 above)
Comment (radeusgd) [reply engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:198]: We _do_ distinguish these cases already.

The error message I have edited was only relevant for conversions, method overloads have a separate error class - I assume the error message for conversions was copy-pasted from overloads and that's why it used to say the same thing.

Comment (radeusgd) [reply engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:198]: You can see [here](https://github.com/enso-org/enso/blob/b9328bd03d7bda5650c27788682b0370bcb3db4d/engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala#L40) a test verifying that the behaviour is exactly as you'd expect it to be.

https://github.com/enso-org/enso/blob/b9328bd03d7bda5650c27788682b0370bcb3db4d/engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala#L33-L42

Comment (radeusgd) [reply engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala:198]: Well, the above test was for member methods - so just to be comprehensive I added a test case like the one you mentioned:
 [2a37e54](https://github.com/enso-org/enso/pull/8245/commits/2a37e540383c9753e6c3bf2c42b1feb5ad43427f)
