### PR TITLE
Fix dangling node connection

### LINKED ISSUE #8871: Dangling node connection after opening a project
After opening the project [Unbooked_Seats.zip](https://github.com/enso-org/enso/files/14062289/Unbooked_Seats.zip), I have a dangling node connection that I cannot get rid of. Closing the project and reopening does not fix this issue. Shutting down the whole IDE and restarting does not fix this issue as well.

Version from https://github.com/enso-org/enso/releases/tag/2024.1.1-nightly.2024.1.25

[Screencast from 2024-01-26 09-52-15.webm](https://github.com/enso-org/enso/assets/14013887/c5562388-7b97-4853-bfe0-787411dcea0a)

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #8871

The issue was caused by invalid port registration. Because of the existing context switch expression (which is not visible in GUI),  the port incorrectly considered itself to belong to another node. This happened because the port was only aware of the visible part of the node’s AST and considered it the whole node.

There are two fixes in this PR. Either of them fixes the issue, and they are both implemented for robustness:
1. We provide `nodeId` information to the widget tree, so it no longer assumes the node ID from AST.
2. The order of checks in `getPortNodeId` is swapped. Now we first search by AST, only then try to look up the port. It makes sense to me because the AST is a single root of truth, and we should only rely on registered ports if AST does not exist (which happens for unconnected ports).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/stores/graph/index.ts [hunk 1]
```diff
@@ -418,7 +418,7 @@ export const useGraphStore = defineStore('graph', () => {
   }
 
   function getPortNodeId(id: PortId): NodeId | undefined {
-    return getPortPrimaryInstance(id)?.nodeId ?? db.getExpressionNodeId(id as string as Ast.AstId)
+    return db.getExpressionNodeId(id as string as Ast.AstId) ?? getPortPrimaryInstance(id)?.nodeId
```
Comment (farmaazon) [inline app/gui2/src/stores/graph/index.ts:387]: I'm not sure about this change. If we have port instances, and they define their nodeId, they could have a reason to change it from AST?

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/stores/graph/index.ts (hunk 1 above)
Comment (vitvakatu) [reply app/gui2/src/stores/graph/index.ts:387]: They don’t really “define” their nodeid, they use the node id derived from AST. In which case will they change it?

Comment (farmaazon) [reply app/gui2/src/stores/graph/index.ts:387]: so, the node id is derived from AST at some point, but not necessarily from _Port_ Id. PortId is a broader than just AstId. Technically (even if it's an awful idea), some widget could create portIds which also resembles AstId, but are not bound to them. In that case, I would say the port information from PortId is more accurate than what we deduce from AstId. `getExpressionNodeId` feels more like a fallback than the main route.

Of course this all is nitpicking because it will probably make no difference in real scenarios.
