### PR TITLE
Exception message may not be specified

### LINKED ISSUE #5683: NPE in  io.circe.Printer$PrintingFolder.onString from Client.processMessage(
### Discord username

Jaroslav Tulach#1623

### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While developing I am seeing:
```
java.lang.NullPointerException
        at io.circe.Printer$PrintingFolder.onString(Printer.scala:319)
        at io.circe.Printer$PrintingFolder.onString(Printer.scala:302)
        at io.circe.Json$JString.foldWith(Json.scala:364)
        at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
        at io.circe.Printer$PrintingFolder.onObject(Printer.scala:369)
        at io.circe.Printer$PrintingFolder.onObject(Printer.scala:302)
        at io.circe.Json$JObject.foldWith(Json.scala:426)
        at io.circe.Printer.unsafePrintToAppendable(Printer.scala:229)
        at io.circe.Printer.print(Printer.scala:197)
        at io.circe.Json.noSpaces(Json.scala:117)
        at org.enso.loggingservice.internal.service.Client.processMessage(Client.scala:91)
        at org.enso.loggingservice.internal.service.ThreadProcessingService.runQueue(ThreadProcessingService.scala:70)
        at org.enso.loggingservice.internal.service.ThreadProcessingService.$anonfun$startQueueProcessor$1(ThreadProcessingService.scala:50)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected behaviour

I have a feeling this is related to encoding exceptions with `null` message that cannot be serialized, but I am not able to verify that in debugger.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

dev as of Feb 17, 2023

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

Browser

### Operating System

Linux

### Operating System Version

Ubuntu

### Hardware you are using

AMD Radeon

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Getting ready for `null` values in `WSLogMessage`. Closes #5683.

### Checklist

Please include the following checklist in your PR:

- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/DefaultLogMessageRenderer.scala [hunk 1]
```diff
@@ -70,5 +70,6 @@ class DefaultLogMessageRenderer(printExceptions: Boolean)
       case LogLevel.Debug   => "debug"
       case LogLevel.Trace   => "trace"
       case LogLevel.Off     => "off"
+      case _                => "error";
```
Comment (hubertp) [inline lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/DefaultLogMessageRenderer.scala:73]: I don't think that's necessary since the pattern match here is exhaustive

**Review by hubertp — APPROVED** [review]
Minor nit, otherwise lgtm

File: lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/DefaultLogMessageRenderer.scala (hunk 1 above)
Comment (JaroslavTulach) [reply lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/DefaultLogMessageRenderer.scala:73]: Exhaustive, except not covering `null`. However you are right, that's not where the #5683 exception comes from.
