### PR TITLE
Prevent re-entrant execution of finalizers

### LINKED ISSUE #10211: StackOverflow when multiple Managed Resources are being cleaned up at the same time
Try running the following script:
```
from Standard.Base import all
import Standard.Base.Runtime.Managed_Resource.Managed_Resource
import Standard.Base.Runtime.Ref.Ref

type My_Resource
    Value counter:Ref

    close self =
        self.counter.modify (x-> x-1)
        Nothing

    allocate counter:Ref =
        counter.modify (+1)
        Managed_Resource.register (My_Resource.Value counter) close_resource

close_resource resource = resource.close

repeat_cleanup_until_done counter =
    go i =
        if counter.get == 0 then Nothing else
            if i % 100 == 0 then
                IO.println "Still "+counter.get.to_text+" resources to clean up..."
            Runtime.gc
            @Tail_Call go i+1
    go 1

main =
    n = 10
    counter = Ref.new 0
    IO.println "Allocating resources..."
    0.up_to n . each _->
        My_Resource.allocate counter
    
    IO.println "Cleaning up..."
    repeat_cleanup_until_done counter
    IO.println "All cleaned up! "+counter.get.to_text
```
With `n = 10` it will happily allocate and then clean up resources:
```
Allocating resources...
Cleaning up...
All cleaned up! 0
```

Now, try changing `n` to `10000`:
```diff
-    n = 10
+    n = 10000
```
and running it again.

I'm consistently getting a StackOverflow failure:
```
Allocating resources...
Cleaning up...
Execution finished with an error: Resource exhausted: Stack overflow
```

### LINKED ISSUE #10610: Unexpected comparator warning in `Vector_Spec`
I've been getting a following test failure intermittently:
```
Use a slice of an array as vectors ► should report only a limited number of warnings for incomparable values

(sorted - warnings = [Different comparators: [Standard.Base.Internal.Ordering_Helpers.Default_Comparator], Values NaN and 162 are incomparable, Values 00:00:00 and Date.type.new[Date.enso:103-105] self=Date year=_ are incomparable, Values 429 and NaN are incomparable, Values 319 and 'foo261' are incomparable, Values 'foo261' and 259 are incomparable, Values 242 and 'foo241' are incomparable, Values 00:00:00 and Nothing are incomparable, Values 'foo451' and Nothing are incomparable, Values [] and 392 are incomparable, Values 112 and NaN are incomparable]) 11 did not equal 10 (at C:\runner\_work\enso\enso\test\Base_Tests\src\Data\Vector_Spec.enso:917:13-45).
```

After adding the `with_clue` showing the warnings, I think the problem is that we are getting an additional, unexpected warning: `Different comparators: [Standard.Base.Internal.Ordering_Helpers.Default_Comparator]`.

The message itself is weird - it says there are different comparators - but it lists only one comparator (so what is different? I imagine there can be different ones if there is at least 2) and it is the `Default_Comparator` anyway.

After a clean build, I was no longer able to reproduce this locally, but I was [again getting it on CI](https://github.com/enso-org/enso/runs/27657983323?pr=10576) for https://github.com/enso-org/enso/pull/10576

Ideally we should try to understand why this was happening and if a fix is needed.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #10211 by avoiding re-entrant execution of finalizers.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: build/build/src/engine/context.rs [hunk 1]
```diff
@@ -274,6 +274,9 @@ impl RunContext {
         // sbt:warning: java.lang.ClassNotFoundException:
         // org.enso.interpreter.node.expression.builtin.bool.True
         ide_ci::fs::remove_if_exists(&self.paths.repo_root.engine.runtime.target)?;
+        // cleanup distribution from previous build
+        // it is fast to assemble it again
+        ide_ci::fs::remove_if_exists(&self.paths.repo_root.built_distribution)?;
```
Comment (JaroslavTulach) [inline build/build/src/engine/context.rs:279]: Fix exit code `126` - [cannot execute binary file](https://github.com/enso-org/enso/actions/runs/10003911884/job/27651628322?pr=10602#step:7:984) by removing `built-distribution` debris before starting the build. 

How does the problem happen? 
When I configured `engine-runner/buildNative` to override output of buildEngineDistribution in
- #10374

I knew I was asking for problems. The _"override"_ only happens in certain CI jobs and only at the end of their execution. However, as previous output often stays around for next executor, we may face a _"debris problem"_ - the binary `enso` stays where `bash` `enso` script is expected.

Cleaning the `build-distribution` directory every time shall fix the problem.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java [hunk 2]
```diff
@@ -174,12 +161,66 @@ public void shutdown() {
...
-   * spawned in order for this module to be operational.
+   * Processes {@link Item}s eligible for GC. Plays two roles. First of all cleans {@link
+   * #referenceQueue} in {@link #run()} method running in its own thread. Then it invokes finalizers
+   * in {@link #perform} method inside of Enso execution context.
    */
-  private class Runner implements Runnable {
+  private final class ProcessItems extends ThreadLocalAction implements Runnable {
+    /**
+     * @GuardedBy("pendingItems")
+     */
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:157]: What does this mean?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java [hunk 3]
```diff
@@ -174,12 +161,66 @@ public void shutdown() {
...
+        Item[] toProcess;
+        synchronized (pendingItems) {
+          if (pendingItems.isEmpty() || pendingItems.get(0) == null) {
+            // nothing to process or already processing
+            // avoids re-entrant calls into this method
+            return;
+          }
+          toProcess = pendingItems.toArray(Item[]::new);
+          // mark as being processed
+          pendingItems.set(0, null);
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java]: Why use 'magic value' `null` to mark `alreadyProcessing`? Cannot we use an explicit `boolean` flag instead? It would be much more clear what is happening IMO.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:157]: Just a note inspired by https://errorprone.info/bugpattern/GuardedBy

**Review by radeusgd — COMMENTED** [review]
I look at the `scheduleFinalizationAtSafepoint` method and wonder - does it still do what it says? Looking at the code, the `submitThreadLocal` call was removed from it. It seems that this method is now actually doing `finalizeAndUnregisterFromList` or something like that, but not quite `scheduleFinalizationAtSafepoint`.

Can we get the method name updated to reflect its current meaning? Otherwise it is just misleading

**Comment by radeusgd** [comment]
The Enso tests look good. Out of curiosity, how long does it take to allocate and clean the 100k resources?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java]: I had `boolean` flag in one of previous versions.  However this is simpler.

> more clear what is happening

C'mon. Just read comment on line 193, 194 and 198 and you can figure it out!

**Comment by JaroslavTulach** [comment]
> The Enso tests look good. Out of curiosity, how long does it take to allocate and clean the 100k resources?

```bash
enso$ time ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/e
nso-0.0.0-dev/bin/enso --run test/Base_Tests/src/Runtime/GC_Example.enso 100000
Allocating 100000 resources...
Cleaning up...
All cleaned up! Remaining: 0
0

real    0m6,252s
user    0m26,125s
sys     0m3,088s
```
vs.
```bash
enso$ time ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run test/Base_Tests/src/Runtime/GC_Example.enso 1
Allocating 1 resources...
Cleaning up...
All cleaned up! Remaining: 0
0

real    0m5,300s
user    0m18,851s
sys     0m2,424s
```

**Comment by radeusgd** [comment]
Looks good but I think the `scheduleFinalizationAtSafepoint` method should be renamed to reflect what it is actually doing. Unless I highly misunderstood something?

**Comment by JaroslavTulach** [comment]
> Can we get the method name updated to reflect its current meaning? Otherwise it is just misleading

Let's remove the method altogether. Then we don't need to care about naming: 0cc2288bc2!

**Review by radeusgd — APPROVED** [review]
Thanks for addressing the misleading method name, it looks better now.

**Review by GregoryTravis — APPROVED** [review]

**Review by Akirathan — APPROVED** [review]
I don't understand the code entirely, but I trust the tests.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java]: At the end I am using request field 8ad8117f98 to signal whether processing is over.

**Comment by JaroslavTulach** [comment]
There is a test failure:
- [should report only a limited number of warnings for incomparable values](https://github.com/enso-org/enso/actions/runs/10035924662/job/27732736452?pr=10602#step:7:1150) on all platforms

```
Reason: (sorted - warnings = [Different comparators: [
  Standard.Base.Internal.Ordering_Helpers.Default_Comparator], Values NaN and 162 are incomparable, 
  Values 00:00:00 and Date.type.new[Date.enso:103-105] self=Date year=_ are incomparable, 
  Values 429 and NaN are incomparable, Values 319 and 'foo261' are incomparable, 
  Values 'foo261' and 259 are incomparable, Values 242 and 'foo241' are incomparable, 
  Values 00:00:00 and Nothing are incomparable, Values 'foo451' and Nothing are incomparable, 
  Values [] and 392 are incomparable, Values 112 and NaN are incomparable
]) 11 did not equal 10 (at /Users/runner/work/enso/enso/test/Base_Tests/src/Data/Vector_Spec.enso:917:13-45).
```

**Comment by radeusgd** [comment]
> There is a test failure:
> 
> * [should report only a limited number of warnings for incomparable values](https://github.com/enso-org/enso/actions/runs/10035924662/job/27732736452?pr=10602#step:7:1150) on all platforms
> 
> ```
> Reason: (sorted - warnings = [Different comparators: [
>   Standard.Base.Internal.Ordering_Helpers.Default_Comparator], Values NaN and 162 are incomparable, 
>   Values 00:00:00 and Date.type.new[Date.enso:103-105] self=Date year=_ are incomparable, 
>   Values 429 and NaN are incomparable, Values 319 and 'foo261' are incomparable, 
>   Values 'foo261' and 259 are incomparable, Values 242 and 'foo241' are incomparable, 
>   Values 00:00:00 and Nothing are incomparable, Values 'foo451' and Nothing are incomparable, 
>   Values [] and 392 are incomparable, Values 112 and NaN are incomparable
> ]) 11 did not equal 10 (at /Users/runner/work/enso/enso/test/Base_Tests/src/Data/Vector_Spec.enso:917:13-45).
> ```

Related ticket: https://github.com/enso-org/enso/issues/10610

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java [hunk 4]
```diff
@@ -174,21 +147,82 @@ public void shutdown() {
...
+     * #pendingItems}. If there are any remaining, continues processing them. Otherwise finishes.
+     *
+     * @param access not used for anything
+     */
+    @Override
+    protected void perform(ThreadLocalAction.Access access) {
+      for (; ; ) {
+        Item[] toProcess;
+        synchronized (pendingItems) {
+          request.cancel(false);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: `request` is guaranteed to be non-null at this point?

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: It should be non-`null`. To get into this `process` method, a call to [submitThreadLocal](https://github.com/enso-org/enso/pull/10602/files#diff-8afe630a7fa9f76767a43dadee9ce42219dce2d752c325909006cc527809c178R222) must be made and it assigns the `request`.

The `request` is only assigned back to `null` in this method, just before `return` - after this check.

E.g. unless there is some re-entrant invocation of the `process` method (it was there, but I hopefully fixed it), `request` shall not be `null` at this point.

Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: Yes, I can see that gets set there along with adding to `pendingItems`. But it wasn't obvious that `perform` can't be called with an empty `pendingItems` and then it would crash.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: Shall we maybe include an assert at least?

File: test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso [hunk 5]
```diff
@@ -57,6 +58,10 @@ add_specs suite_builder = suite_builder.group "Managed_Resource" group_builder->
         r_3 = Panic.recover Any <| Managed_Resource.bracket 42 (_-> Nothing) (_-> Panic.throw "action")
         r_3.catch . should_equal "action"
 
+    group_builder.specify "allocate lots of resources at once" <|
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso:61]: This test was disabled by 
- #10642

Attempt to diagnose what the problem was is at 
- #10665

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 4 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: What's a difference between `NullPointerException` and `AssertionError`?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java [hunk 6]
```diff
@@ -174,21 +147,82 @@ public void shutdown() {
...
         try {
           Reference<? extends ManagedResource> ref = referenceQueue.remove();
           if (!killed) {
             if (ref instanceof Item it) {
-              it.isFlaggedForFinalization().set(true);
-              scheduleFinalizationAtSafepoint(it);
+              it.flaggedForFinalization.set(true);
+              synchronized (pendingItems) {
+                if (request == null) {
+                  request = context.submitThreadLocal(null, this);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:222]: Here is the [submitThreadLocal javadoc](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.Env.html#submitThreadLocal(java.lang.Thread%5B%5D,com.oracle.truffle.api.ThreadLocalAction)).

>  If the threads array is null then the thread local action will be performed on all alive threads

Right now, when we run _single threaded_, one thread will pick the action. In the future, multiple threads may execute the `perform` method. In such situation the [request may actually become null](https://github.com/enso-org/enso/pull/10602/files#r1686584872) for some (slower) threads.

> Using recurring events should be preferred

The `ProcessItems` constructor marks the `ThreadLocalAction` as **recurring** to make sure _some thread will pick_ our action up.

[ThreadLocalAction javadoc](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/ThreadLocalAction.html) is also available.

> Asynchronous thread-local actions might start and complete to perform independently of each other.

Yes, we want **asynchronous** action, as we only want to run the action on a single thread. We don't care about others.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:222]: Continues at the [next PR](https://github.com/enso-org/enso/pull/10665/files#r1691010351).

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java:183]: Usually the NPE can be delayed and happen somewhere down the line, making debugging harder.

In this case I guess you are right - no meaningful difference. I just don't like NPEs so that was by habit :)
