### PR TITLE
Disable buffer compaction

### LINKED ISSUE #6320: Join throws many "GL errors"
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Whenever I'm placing Join method I'm getting bunch of GL errors:

```[26212:0417/215009.751:ERROR:gl_utils.cc(398)] [.WebGL-00003AFC06691B00] GL_INVALID_OPERATION: Error: 0x00000502, in ..\..\third_party\angle\src\libANGLE\renderer\d3d\VertexDataManager.cpp, reserveSpaceForAttrib:520. Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.
[26212:0417/215009.751:ERROR:gl_utils.cc(398)] [.WebGL-00003AFC06691B00] GL_INVALID_OPERATION: Error: 0x00000502, in ..\..\third_party\angle\src\libANGLE\renderer\d3d\VertexDataManager.cpp, reserveSpaceForAttrib:520. Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.
[26212:0417/215009.766:ERROR:logger.cc(46)] Too many GL errors, not reporting any more for this context. use --disable-gl-error-limit to see all errors.
```

eventually (usually 3rd or 4th join) engine crashes i get this partial line:

```
[29508:0417/215657.798:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```

and no further working with Enso is possible.

### Expected behaviour

Join working

### How we can reproduce it?

read some large CSV file like one from BC10
and try to inner join it 

### Screenshots or screencasts

_No response_

### Enso Version

2023.04.15

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fixes #6320.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] ~The documentation has been updated, if necessary.~
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~Unit tests have been written where possible.~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/rust/ensogl/core/src/system/gpu/data/attribute.rs [hunk 1]
```diff
@@ -218,7 +218,8 @@ impl {
     pub fn update(&mut self) {
         debug_span!("Updating.").in_scope(|| {
             if self.used_size * 2 < self.size() {
-                self.shrink_to_fit();
+                // FIXME
+                //self.shrink_to_fit();
```
Comment (farmaazon) [inline lib/rust/ensogl/core/src/system/gpu/data/attribute.rs]: Add a bit more info to this FIXME, at least the issue number.

**Review by farmaazon — APPROVED** [review]
