### PR TITLE
Inline execution should support FQNs

### LINKED ISSUE #8428: Inline execution cannot resolve fully qualified names
When trying to execute an expression containing a fully qualified name, for example

```
Standard.Base.Visualization.Preprocessor.default_preprocessor 85
```

using the `executionContext/executeExpression` method, it is unable to perform a resolution

```
[enso::ExecutionService] WARNING: Execution of visualization [e038bab8-e733-46f3-9945-2a3030547984] on value [260fe20c-fe22-4384-8d8d-487daab34ccd] of [Nothing] failed. Compile error: The name `Standard` could not be found.
```

If you change the expression to

```
Preprocessor.default_preprocessor 85
```

it works.

[Main.enso.txt](https://github.com/enso-org/enso/files/13512126/Main.enso.txt)

This commit provides an example test case https://github.com/enso-org/enso/commit/811628e33afb2b9eb784f297131adae63996cc0d

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Previously, there was no requirement that inline execution should allow
for FQNs. This meant that the omission of Package Repository info went
unnoticed.

Closes #8428.

### Important Notes

In order to be able to refer to `Standard.Visualization.Preprocessor` it
has to be exported as well in `Standard.Visualization.Main`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala [hunk 1]
```diff
@@ -3880,4 +3880,184 @@ class RuntimeVisualizationsTest
...
+    val requestId       = UUID.randomUUID()
+    val visualizationId = UUID.randomUUID()
+    val moduleName      = "Enso_Test.Test.Main"
+    val metadata        = new Metadata
+
+    val idMain = metadata.addItem(90, 6)
+
+    val code =
+      """import Standard.Visualization
+        |import Standard.Visualization.Preprocessor
```
Comment (4e6) [inline engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:3984]: Should be already re-exported from `Standard.Visualization`

**Review by 4e6 — APPROVED** [review]

File: engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:3984]: Actually it does not appear to be the case. Importing `Standard.Visualization.Preprocessor` does not mean that `Standard.Visualization.Main` is imported.

**Review by GregoryTravis — APPROVED** [review]

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala:3984]: A more elaborate explanation is here https://github.com/enso-org/enso/blob/develop/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala#L366
