### PR TITLE
UnresolvedSymbol is now accepted by Vector.sort

### LINKED ISSUE #6276: `on` argument of `Vector.sort` does not support `UnresolvedSymbol`
```
type My_Type
  Value f1 f2

main =
  [(My_Type.Value 1 2), (My_Type.Value 2 1)].sort on=(.f2)
```
Fails with 
```
Execution finished with an error: java.lang.IllegalArgumentException: Unsupported argument for `on`, expected a method with one argument, got UnresolvedSymbol<f2>
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNode$GenericSortComparator.checkAndConvertFunction(SortVectorNode.java:797)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNode$GenericSortComparator.checkAndConvertOnFunc(SortVectorNode.java:787)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNode$GenericSortComparator.<init>(SortVectorNode.java:722)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNode.sortGeneric(SortVectorNode.java:232)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNodeGen.executeAndSpecialize(SortVectorNodeGen.java:110)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorNodeGen.execute(SortVectorNodeGen.java:65)
        at <java> org.enso.interpreter.node.expression.builtin.ordering.SortVectorMethodGen.execute(SortVectorMethodGen.java:217)
        at <enso> Vector.sort_builtin(Internal)
        at <enso> Vector.sort(/home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso:922:9-82)
        at <enso> tmp.main(tmp.enso:14:14-30)
```

Because `(.f2)` is parsed as `UnresolvedSymbol`, rather than a `Function`. Calling it with `on=(_.f2)` works as expected.

We should add the support to provide it with UnresolvedSymbol arguments.

```[tasklist]
### Tasks
- [ ] Revert https://github.com/enso-org/enso/pull/5998#discussion_r1165769115
```

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

`Vector.sort` does some custom method dispatch logic which always expected a function as `by` and `on` arguments. At the same time, `UnresolvedSymbol` is treated like a (to be resolved) `Function` and under normal circumstances there would be no difference between `_.foo` and `.foo` provided as arguments.

Rather than adding an additional phase that does some form of eta-expansion, to accomodate for this custom dispatch, this change only fixes the problem locally. We accept `Function` and `UnresolvedSymbol` and perform the resolution on the fly. Ideally, we would have a specialization on the latter but again, it would be dependent on the contents of the `Vector` so unclear if that is better.

Closes #6276,

### Important Notes

There was a suggestion to somehow modify our codegen to accomodate for this scenario but I went against it. In fact a lot of name literals have `isMethod` flag and that information is used in the passes but it should not control how (late) codegen is done. If we were to make this more generic, I would suggest maybe to add separate eta-expansion pass. But it could affect other things and could be potentially a significant change with limited potential initially, so potential future work item.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 1]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
+     * @param arg the value on which the function is defined on.
+     * @return a non-null comparator function.
+     */
+    abstract Function get(Object arg);
+
+  }
+
+  private final class CompareFromFunction extends Compare {
+
+    private Function function;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java]: Missing `final`.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 2]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
   }
 
+  /**
+   * Helper class that returns the comparator function.
+   *
+   * The class is introduced to handle the presence of {@code UnresolvedSymbol},
+   * as the comparator function, which has to be first resolved before it
+   * can be used to compare values.
+   */
+  private abstract class Compare {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:664]: The "Truffle way" of doing this would be to have a `class Compare extends Node` and insert the right one (or more) into the AST somehow.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 3]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
+
+    private Function function;
+
+    private CompareFromFunction(Function function) {
+      this.function = function;
+    }
+
+    @Override
+    boolean hasFunctionSelfArgument(Object definedOn) {
+      if (function.getSchema().getArgumentsCount() > 0) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:694]: The `function.getSchema()` is a candidate for speculating that it is a constant. However done this way, it is certainly not going to be a constant.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 4]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
+        return function.getSchema().getArgumentInfos()[0].getName().equals("self");
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:695]: Can `equals` be used on fast-path? Probably this code isn't on fast-path, right?

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 5]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
+    }
+  }
+
+  private class CompareFromUnresolvedSymbol extends Compare {
+
+    private final UnresolvedSymbol unresolvedSymbol;
+    private final MethodResolverNode methodResolverNode;
+    private final TypesLibrary typesLibrary;
+
+    private Function resolvedFunction;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java]: Technically this could be `@CompilationFinal`

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java [hunk 6]
```diff
@@ -647,6 +654,94 @@ private int getPrimitiveValueCost(Object object) {
...
+    @Override
+    Function get(Object arg) {
+      return function;
+    }
+  }
+
+  private class CompareFromUnresolvedSymbol extends Compare {
+
+    private final UnresolvedSymbol unresolvedSymbol;
+    private final MethodResolverNode methodResolverNode;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:710]: We should avoid having references to `Node` from a "data". Or is `Compare` supposed to be "code"? Then it should be `Node`... This feels like mixing apples and oranges...

You could also go the slow-path route and use `MethodResolverNode.getUncached()` at usage sites of `methodResolverNode`.

File: test/Tests/src/Data/Vector_Spec.enso [hunk 7]
```diff
@@ -579,6 +579,7 @@ type_spec name alter = Test.group name <|
         small_vec = alter [T.Value 1 8, T.Value 1 3, T.Value -20 0, T.Value -1 1, T.Value -1 10, T.Value 4 0]
         small_expected = [T.Value -20 0, T.Value 4 0, T.Value -1 1, T.Value 1 3, T.Value 1 8, T.Value -1 10]
         small_vec.sort (on = _.b) . should_equal small_expected
+        small_vec.sort (on = .b) . should_equal small_expected
```
Comment (JaroslavTulach) [inline test/Tests/src/Data/Vector_Spec.enso:582]: I'd be interested in seeing a result of a benchmark comparing a regular sort without `on` specified with `on = (x -> x)` - there is no reason why there should be a performance difference, right? However I am afraid, there is going to be a massive slowdown as the `Compare` code doesn't seem to be ready for being executed on fast-path.

**Review by JaroslavTulach — APPROVED** [review]
I assume the primary goal is to make the `(on = .b)` syntax work. Approving.

However I'd be also interested in making it run (reasonably) fast. Or (at least) not to do such wild things where a `Node` is held and used by a non-node object. There should be a clear separation between "code" (represented by `Node` hierarchy) and "data" - however with `Compare` I am not sure where to draw the line - it feels like a mixture of both.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java (hunk 4 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:695]: Right, this is not on fast-path. It is called from `sortGeneric` specialization that is behind boundary. If it would be on fast-path, native-image build test should fail, I believe.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java (hunk 6 above)
Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:710]: This, indeed, feels weird. I think that optimally, this whole `Compare` class hierarchy should work like "InvokeCompareFunctionNode". The method resolution from the `UnresolvedSymbol` could be done straight away in `GenericSortComparator` constructor.

File: test/Tests/src/Data/Vector_Spec.enso (hunk 7 above)
Comment (Akirathan) [reply test/Tests/src/Data/Vector_Spec.enso:582]: I'd be interested too. There is a benchmark in `test/Benchmark/src/Sorting.enso` that you can run, just replace one of the parameters. These benchmarks are unfortunately not tracked in the results that are published at https://enso-org.github.io/engine-benchmark-results/.

**Comment by hubertp** [comment]
> I assume the primary goal is to make the `(on = .b)` syntax work. Approving.

Thanks.

> However I'd be also interested in making it run (reasonably) fast. Or (at least) not to do such wild things where a `Node` is held and used by a non-node object. There should be a clear separation between "code" (represented by `Node` hierarchy) and "data" - however with `Compare` I am not sure where to draw the line - it feels like a mixture of both.

I assume that given that `SortVectorNode` was already reviewed and merged, and already does that kind of magic in `GenericSortComparator` then pushing it slightly further would "do no harm". I will happily look into making it more Truffle-friendly.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java (hunk 6 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:710]: > The method resolution from the UnresolvedSymbol could be done straight away in GenericSortComparator constructor.

Not really. Constructor has no knowledge (yet) of the values on which one should dispatch the unresolved symbol on.

Comment (Akirathan) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:710]: Sorry, I misinterpreted that. You are right. I guess that is fine then.

File: test/Tests/src/Data/Vector_Spec.enso (hunk 7 above)
Comment (hubertp) [reply test/Tests/src/Data/Vector_Spec.enso:582]: I run the (slightly modified) [benchmark](https://github.com/enso-org/enso/blob/develop/test/Benchmarks/src/Vector/Sort.enso#L68) and it appears that the difference is negligible. I run it with `on=(x -> x)` vs `(on=.identity)`, where `identity` is the method I added to numbers.

Comment (JaroslavTulach) [reply test/Tests/src/Data/Vector_Spec.enso:582]: Then everything is fine and feel free to integrate.

**Comment by JaroslavTulach** [comment]
> I assume that given that `SortVectorNode` was already reviewed and merged, 

Well, the code is a bit complex. During recent discussions we realized that there is a `@Specialization` that is also `@TruffleBoundary` and it "happily" calls into `Node` instances. That's wrong, it should use `CallTarget` to return back to PE mode just like #5782 does. 

However it is a deeper problem and it can wait for another PR.

**Comment by hubertp** [comment]
> > I assume that given that `SortVectorNode` was already reviewed and merged,
> 
> Well, the code is a bit complex. During recent discussions we realized that there is a `@Specialization` that is also `@TruffleBoundary` and it "happily" calls into `Node` instances. That's wrong, it should use `CallTarget` to return back to PE mode just like #5782 does.
> 
> However it is a deeper problem and it can wait for another PR.

Yeap, agreed. Thanks for the pointers regarding Truffle. I will create a follow up ticket.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:664]: Will revisit in future work, as discussed.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java (hunk 3 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java:694]: Will revisit in future work, as discussed.

**Review by jdunkerley — APPROVED** [review]
Approving the enso side.
