### PR TITLE
Implement fix for duplicate entries in visualisation list.

### LINKED ISSUE #5708: Duplicated entries in visualisations list
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The regression that was previously fixed is back - we have `Table` visualization listed twice on visualizations list. Switching between them causes visualization blanc.

### Expected behaviour

Just one Table visualization available on the list

### How we can reproduce it?

_No response_

### Screenshots or screencasts

image

### Enso Version

2023.1.1-nightly.2023.2.18

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Fixes duplicate entries in the visualization chooser. The issue was caused by entries added twice, once matching the `Any` type and once matching the concrete type. Closes #5708.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/visualization/registry.rs [hunk 1]
```diff
@@ -70,7 +70,11 @@ impl Registry {
             type_map.get(tp).cloned().unwrap_or_default();
         if tp != &any_type {
             if let Some(vis_for_any) = type_map.get(&any_type) {
-                result.extend(vis_for_any.iter().cloned());
+                for vis in vis_for_any {
+                    if !result.contains(vis) {
+                        result.push(vis.clone_ref());
+                    }
+                }
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/registry.rs]: We may easily speed it up by keeping hash set of paths. AFAIK the path identifies the visualization.

**Review by farmaazon — APPROVED** [review]

**Review by farmaazon — APPROVED** [review]

**Review by farmaazon — APPROVED** [review]
QA green
