### PR TITLE
Fix displayed project name in graph editor

### LINKED ISSUE #13427: Renaming a project inside a project changed a name in a Tab not in the field inside the graph editor
Image

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #13427

https://github.com/user-attachments/assets/226f7131-1a58-4928-af7b-1adc75735368

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/ProjectView.vue [hunk 1]
```diff
@@ -56,7 +66,10 @@ provideSettings()
 
 const visible = ref(false)
 provideVisibility(visible)
-openedProjects.registerProject(props)
+openedProjects.registerProject({
+  ...props,
+  projectDisplayedName: readonly(toRef(props, 'projectDisplayedName')),
+})
```
Comment (farmaazon) [inline app/gui/src/project-view/ProjectView.vue]: I think it would be safer to call `toRefs` on props here (changing also arg type of `registerProject` to `ToRefs<RegisterProject>`), and unref value if necessary inside.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/project-view/ProjectView.vue (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/ProjectView.vue]: Is https://github.com/enso-org/enso/pull/13458/commits/e1056742b2113a30cb0cef6d15f0af309d98ec3c what you had in mind?

Comment (farmaazon) [reply app/gui/src/project-view/ProjectView.vue]: Yes. If you think it's a bit noisy, we may also revert it, but then I would rather make `registerProject` taking `Ref` in place of `ToValue`, so we better track what should be reactive.
