### PR TITLE
Fix mouse hover events.

### LINKED ISSUE #6850: Sometimes when in 'connection mode' the ports are not attachable and instead I can move nodes with my mouse
Let me explain with a video:

https://github.com/enso-org/enso/assets/1436948/9dd416e2-25c0-4513-9cae-a3aa9a120a39

When I drag a node output port my mouse is in 'connection mode' - I see a line from the node to the cursor. Normally, I can then attach that line to an input port and create a connection.

But as you can see on the video, this does not work - the ports do not highlight and instead I can actually move the nodes around with the cursor - as if it was in 'normal mode'. The expected behaviour is the usual one - the ports will 'accept' such an incoming connection and I should not be able to interact moving nodes around when in this 'mode'.

I'm not sure if this is a known issue but searching 'ports' did not yield anything.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #6850 - at least scenario described in the issue's description. Probably many other issues with unclickable/unhoverable elements will go.

https://github.com/enso-org/enso/assets/3919101/69b07ede-bb89-4e0b-ad16-977cb08dd213

Plainly, the solution described in [this comment](https://github.com/enso-org/enso/issues/6850#issuecomment-1576754037) was implemented. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/component/node/output/port.rs [hunk 1]
```diff
@@ -520,18 +520,18 @@ impl Model {
...
 
             let mouse_down = shape.on_event::<mouse::Down>();
-            let mouse_out = shape.on_event::<mouse::Out>();
-            let mouse_over = shape.on_event::<mouse::Over>();
+            let mouse_enter = shape.on_event::<mouse::Enter>();
+            let mouse_leave = shape.on_event::<mouse::Leave>();
             mouse_down_primary <- mouse_down.filter(mouse::is_primary);
 
-            frp.source.on_hover <+ bool(&mouse_out,&mouse_over);
+            frp.source.on_hover <+ bool(&mouse_leave,&mouse_enter);
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/node/output/port.rs]:
```suggestion
            frp.source.on_hover <+ bool(&mouse_leave, &mouse_enter);
```

File: lib/rust/ensogl/core/src/display/scene.rs [hunk 2]
```diff
@@ -289,19 +293,35 @@ impl Mouse {
...
+                for d in left {
                     let out_event = event.clone().unchecked_convert_to::<mouse::Out>();
                     let leave_event = event.clone().unchecked_convert_to::<mouse::Leave>();
                     d.emit_event(out_event);
                     d.emit_event_without_bubbling(leave_event);
-                });
-                self.pointer_target_registry.with_mouse_target(new_target, |t, d| {
-                    t.mouse_over.emit(());
+                }
+                let entered = new_hovered.iter().filter(|t| !currently_hovered.contains(t));
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/display/scene.rs]: The `O(N x M)` scaling of these `Vec` set operations worries me a little. The display object hierarchy is already deep, and it could reach a depth where it suddenly becomes a performance problem.

Comment (farmaazon) [reply lib/rust/ensogl/core/src/display/scene.rs]: I just assumed that even if object hierarchy is 50 or so levels deep, iterating over 50 elements may be still better than allocating additional `HashMaps`.

But actually, we can easily avoid allocation while improving complexity by just sorting the vecs. I'll push changes soon.

File: lib/rust/ensogl/core/src/display/scene.rs [hunk 3]
```diff
@@ -138,6 +138,8 @@ pub struct Mouse {
     /// sampled and the most recent sample is stored here. Please note, that this sample may be
     /// from a few frames back, as it is not guaranteed when we will receive the data from GPU.
     pub pointer_target_encoded:  Uniform<Vector4<u32>>,
+    /// The display objects which believe they are currently hovered by mouse.
```
Comment (MichaelMauderer) [inline lib/rust/ensogl/core/src/display/scene.rs]: Is there a reason that we ever believe one is hovered while if it is not hovered? If so we should mention the caveats here. Or just say that this are the currently hovered items.

**Review by MichaelMauderer — APPROVED** [review]

File: lib/rust/ensogl/core/src/display/scene.rs (hunk 3 above)
Comment (farmaazon) [reply lib/rust/ensogl/core/src/display/scene.rs]: The caveat is that their information may be outdated (we read what shape is under the mouse with some offset, no greater than several frames). I'll extend the comment here.

**Review by wdanilo — APPROVED** [review]

**Comment by vitvakatu** [comment]
QA passed 🍏
