### PR TITLE
Fix SQL and JSON visualization selection

### LINKED ISSUE #14016: SQL and json visualisation needs to be scrollable and copyable

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #14016 

https://github.com/user-attachments/assets/0845b849-50f0-49bb-a8ac-50418888491a

Also fixes text and date values displayed in SQL visualization interpolated parameters.

https://github.com/user-attachments/assets/0bd65d4a-552c-4194-b6e7-c38cca3334ff

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/visualizations/JSONVisualization/JSONVisualization.vue [hunk 1]
```diff
@@ -63,12 +63,19 @@ function createProjection(path: (string | number)[][]) {
     ),
   )
 }
+
+function stopCopy(event: KeyboardEvent) {
+  if (event.ctrlKey && event.code === 'KeyC') {
```
Comment (vitvakatu) [inline app/gui/src/project-view/components/visualizations/JSONVisualization/JSONVisualization.vue]: This does not work on Mac because the copy uses the Meta key. Also, on a non-QWERTY keyboard layout, copy can be a different key code as well.

**Review by vitvakatu — CHANGES_REQUESTED** [review]

**Review by vitvakatu — APPROVED** [review]
