### PR TITLE
BenchmarksRunner does not override jvm args of forked processes.

### LINKED ISSUE #11808: Javascript benchmarks in stdlib benchmarks are not running
Latest failure in https://github.com/enso-org/enso/actions/runs/12226462185/job/34101757695#step:7:8321 :
```
    INFO ide_ci::program::command: sbt ℹ️ [info] # Warmup Iteration   1: <failure>
   INFO ide_ci::program::command: sbt ℹ️ [info] org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: No language for id epb found. Supported languages are: [python, arrow, js, enso, internal/nfi-native, regex, nfi]
```

Running `std-benchmarks/run org.enso.benchmarks.generated.Sieve.Java_Script_File` locally works just fine.

Created from comment in https://github.com/enso-org/enso/issues/5077#issuecomment-2527542392

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #11808

### Pull Request Description

Fixes "PolyglotException: No language of id epb found". Turns out that we have accidentally overridden all the arguments to forked JVMs of JMH to just `-Dbench.all=true`.

Now, `sbt std-benchmarks/bench` works also locally. Before this PR, they also failed locally.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java [hunk 1]
```diff
@@ -27,7 +27,7 @@ public class BenchmarksRunner {
 
   public static void run(String[] args) throws RunnerException {
     if (args.length == 0) {
-      args = new String[] {"--jvmArgs=-Dbench.all=true"};
```
Comment (Akirathan) [inline lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java:30]: Because of this cmd line arg that we used, the JMH runner used to spawn forks only with `-Dbench.all=true` and did not pass any of other args to the current JVM (like `--module-path`, `--add-modules`, etc.). By using `--jvmArgsPrepend`, most of the arguments passed to the forks are inherited from the current JVM process.

**Review by JaroslavTulach — APPROVED** [review]
Thanks for discovering and fixing my mistake.
