### PR TITLE
Tab View Fixes

### LINKED ISSUE #13059: Fix visuals in Tab Panel
Fix some odd looks, and restore some icons:
* [x] tab highlight animation is sometimes above text
* [x] Settings lost its icon
* [x] Loading indicator should be restored
* [x] Icon for closing should be restored
* [x] Text is misaligned with icon.
* [ ] Tooltip for long project names.

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Part of #13059

* Change Vue spinner to be same as react spinner. It restores loading indicator on tabs
* Restored the close button from react tab panel
* Other fixes

https://github.com/user-attachments/assets/d0da1a5b-b9b6-464c-ac81-097609fa4de8

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/components/TabView.vue [hunk 1]
```diff
@@ -83,11 +91,19 @@ const onSignOut = () => {
           @update:selected="$event && setPage(project.id)"
         >
           <SvgIcon v-if="readyProjects.has(project.id)" name="graph_editor" />
-          <LoadingSpinner v-else :size="16" />
+          <GrowingSpinner v-else :state="loadingProjectSpinnerState(project)" :size="16" />
```
Comment (kazcw) [inline app/gui/src/components/TabView.vue]: I think `state` is a bit abstract, and in the context of a spinner sounds like it would include progress.

File: app/gui/src/components/TabView.vue [hunk 2]
```diff
@@ -83,11 +91,19 @@ const onSignOut = () => {
...
           <span>{{ projectNames.get(project.id) }}</span>
-          <SvgIcon name="close" @click="closeProject(project)" />
+          <SvgButton
+            class="closeButton"
+            :class="{ onMacOs: isOnMacOS() }"
```
Comment (kazcw) [inline app/gui/src/components/TabView.vue]: A `computed` would be slightly more efficient (due to less need for Vue prop diffing), and more obviously right (A function being run on every component update could be a performance bug; looking at the implementation, this function is probably ok to call frequently, but I'd prefer to be able to see that it's ok without needing to check the function implementation.)

File: app/gui/src/components/TabView.vue [hunk 3]
```diff
@@ -136,6 +152,7 @@ const onSignOut = () => {
 .tablist {
   display: flex;
   flex-direction: row;
+  z-index: 0;
```
Comment (kazcw) [inline app/gui/src/components/TabView.vue]: Is this to create a stacking context? A comment about what problem this prevents would be useful

File: app/gui/src/components/TabView.vue [hunk 4]
```diff
@@ -147,4 +164,30 @@ const onSignOut = () => {
...
+.closeButton {
+  --button-padding: 0px;
+  --icon-width: 12px;
+  --icon-height: 12px;
+
+  &:hover {
+    background-color: rgba(239, 68, 68, 0.8);
+  }
+
+  &.onMacOs {
```
Comment (kazcw) [inline app/gui/src/components/TabView.vue]: Since this will not vary from one element to another, maybe we should specify it higher up the DOM?

File: app/gui/src/project-view/components/shared/LoadingSpinner.vue [hunk 5]
```diff
@@ -1,32 +1,108 @@
...
-  }
-})
+import { ROTATING_ELEMENT_SIZE } from '#/components/Spinner'
+import { twJoin } from '#/utilities/tailwindMerge'
+
+const SVG_VIEWBOX_SIZE = '24'
+/* NOTE: Due to some bug in vue, when a component is used both as web components and normally,
+  It's styles are applied only on the former. Therefore the tailwind classes are applied here 
+  as well */
+const SPINNER_CSS_CLASSES = {
```
Comment (kazcw) [inline app/gui/src/project-view/components/shared/LoadingSpinner.vue:9]: Why not import this from `Spinner.tsx`?

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/components/shared/LoadingSpinner.vue (hunk 5 above)
Comment (farmaazon) [reply app/gui/src/project-view/components/shared/LoadingSpinner.vue:9]: The classes are a bit different.

File: app/gui/src/components/TabView.vue (hunk 2 above)
Comment (farmaazon) [reply app/gui/src/components/TabView.vue]: I had a different vision of how vue compute properties: I assumed they're not recomputed if there was no reactive dependency change. Here we have no reactive dependencies. I mean, if _I_ would be a vue developer, probably this is the way I would implement that :)

even if I'm wrong, a constant in setup should be as good as computed.

File: app/gui/src/components/TabView.vue (hunk 1 above)
Comment (farmaazon) [reply app/gui/src/components/TabView.vue]: The term is taken from react implementation: https://github.com/enso-org/enso/blob/wip/farmaazon/tab-view-fixes/app/gui/src/dashboard/components/Spinner.tsx#L9. Frankly, I cannot make any better name ATM. Any ideas?

File: app/gui/src/components/TabView.vue (hunk 3 above)
Comment (MrFlashAccount) [reply app/gui/src/components/TabView.vue]: For stacking context it's better to use 'isolation: isolate'

File: app/gui/src/components/TabView.vue (hunk 1 above)
Comment (somebody1234) [reply app/gui/src/components/TabView.vue]: possibly `Phase` instead of `State`

File: app/gui/src/dashboard/components/Spinner.tsx [hunk 6]
```diff
@@ -63,7 +63,7 @@ export const Spinner = React.memo(function Spinner(props: SpinnerProps) {
         strokeLinecap="round"
         strokeWidth={thickness}
         className={twJoin(
-          'pointer-events-none origin-center !animate-spin-ease transition-stroke-dasharray [transition-duration:var(--spinner-slow-transition-duration)]',
```
Comment (farmaazon) [inline app/gui/src/dashboard/components/Spinner.tsx:66]: @MrFlashAccount @somebody1234 I removed it, because it effectively overrode the information from state. If it was a conscious decision, let me know and I restore it.

**Comment by MrFlashAccount** [comment]
https://github.com/user-attachments/assets/bbcc4d79-5aca-4c02-a824-67148a8a2509

I see a huge regression in the tabs implementation

**Comment by MrFlashAccount** [comment]
1. Long names break tabs layout
CleanShot 2025-05-12 at 13 22 25@2x

2. Navigation between tabs should work using right and left arrows
3. Text and icon are not alighned
4. Text element should fit the grid: https://www.figma.com/design/f2BPtUosNq71xH0Jqc0W7X/ide3-v10?node-id=90-407&t=jMzKxcx2g9gCL3Bo-4

Will update the list later

File: app/gui/src/dashboard/components/Spinner.tsx (hunk 6 above)
Comment (MrFlashAccount) [reply app/gui/src/dashboard/components/Spinner.tsx:66]: If the animation remains the same then I'm fine with the solution

File: app/gui/src/project-view/components/SvgButton.vue [hunk 7]
```diff
@@ -4,16 +4,17 @@ import SvgIcon from '@/components/SvgIcon.vue'
 import type { URLString } from '@/util/data/urlString'
 import type { Icon } from '@/util/iconMetadata/iconName'
 
-const _props = defineProps<{
+defineProps<{
   name?: Icon | URLString | undefined
   label?: string | undefined
   disabled?: boolean | undefined
   title?: string | undefined
+  extendedHover?: number | undefined
```
Comment (MrFlashAccount) [inline app/gui/src/project-view/components/SvgButton.vue]: It's an `extraClickZone`, not an extended hover zone.

File: app/gui/src/project-view/components/MenuButton.vue [hunk 8]
```diff
@@ -37,6 +41,11 @@ function onClick() {
         @click.stop="onClick"
       >
         <slot />
+        <div
+          v-if="extendedHover"
+          class="hoverArea"
+          :style="{ '--extendedHover': `${extendedHover}px` }"
```
Comment (MrFlashAccount) [inline app/gui/src/project-view/components/MenuButton.vue]: extended click zone should be a preset instead.

File: app/gui/src/components/TabView.vue [hunk 9]
```diff
@@ -147,4 +163,30 @@ const onSignOut = () => {
...
+  --button-padding: 0px;
+  --icon-width: 12px;
+  --icon-height: 12px;
+
+  &:hover {
+    background-color: rgba(239, 68, 68, 0.8);
+  }
+}
+
+.App.onMacOs .closeButton {
```
Comment (MrFlashAccount) [inline app/gui/src/components/TabView.vue]: Using styles like these you're entering the danger zone of:
1. Copy-pasting styles (they are _not_ reusable) 
2. Style overrides and specificity calculations.

File: app/gui/src/components/TabView.vue [hunk 10]
```diff
@@ -147,4 +163,30 @@ const onSignOut = () => {
...
+  color: rgba(0, 0, 0, 0);
+  &:not(:hover) {
+    background-color: rgba(0, 0, 0, 0.3);
+  }
+  &:hover {
+    color: rgba(0, 0, 0, 0.9);
+  }
+}
+
+.SelectableTab span {
```
Comment (MrFlashAccount) [inline app/gui/src/components/TabView.vue]: These styles are very slow and fragile, prefer classes instead

File: app/gui/src/components/TabView.vue [hunk 11]
```diff
@@ -147,4 +163,30 @@ const onSignOut = () => {
...
+  /* Trim the text box, so the span will align with icons properly*/
+  text-box: trim-both cap alphabetic;
```
Comment (MrFlashAccount) [inline app/gui/src/components/TabView.vue]: Avoid using text-box since it has very limited availability across the browsers: https://developer.mozilla.org/en-US/docs/Web/CSS/text-box-trim

(even our electron doesn't support it)

File: app/gui/src/components/TabView/SelectableTab.vue [hunk 12]
```diff
@@ -28,10 +28,9 @@ const selected = defineModel<boolean>('selected')
   position: relative;
   display: flex;
   flex-direction: row;
-  align-items: center;
   height: 100%;
-  z-index: 0;
   padding: 8px;
+  text-wrap-mode: nowrap;
```
Comment (MrFlashAccount) [inline app/gui/src/components/TabView/SelectableTab.vue]: IDE doesn't support the text-wrap-mode css property yet

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue [hunk 13]
```diff
@@ -39,10 +39,11 @@ export const widgetDefinition = defineWidget(
   <div :class="{ WidgetIcon: true, noGap: props.input[DisplayIcon].noGap === true }">
     <div class="iconContainer">
       <Transition>
-        <LoadingSpinner
+        <GrowingSpinner
```
Comment (MrFlashAccount) [inline app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue:42]: Please keep the prop names the same

File: app/gui/src/project-view/components/MenuButton.vue [hunk 14]
```diff
@@ -51,10 +60,11 @@ function onClick() {
   justify-content: center;
   align-items: center;
   min-width: max-content;
-  padding: 4px;
+  padding: var(--button-padding, 4px);
```
Comment (MrFlashAccount) [inline app/gui/src/project-view/components/MenuButton.vue:65]: We should have sizes in the first place

File: app/gui/src/project-view/components/shared/GrowingSpinner.vue [hunk 15]
```diff
@@ -0,0 +1,20 @@
...
+ * @file A LoadingSpinner, which starts from 'initial' state and then animates to the passed state.
+ */
+import LoadingSpinner, { SpinnerProps } from '@/components/shared/LoadingSpinner.vue'
+import { computed, onMounted, ref } from 'vue'
+
+const props = defineProps<SpinnerProps>()
+const synchronized = ref(false)
+const phase = computed(() => (synchronized.value ? props.phase : 'initial'))
+onMounted(() => {
+  requestAnimationFrame(() => {
```
Comment (MrFlashAccount) [inline app/gui/src/project-view/components/shared/GrowingSpinner.vue]: Raf should have a cleanup

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue (hunk 13 above)
Comment (farmaazon) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue:42]: It was requested by Kaz in https://github.com/enso-org/enso/pull/13070#discussion_r2081803515 and the change makes sense, doesn't it?

File: app/gui/src/project-view/components/SvgButton.vue (hunk 7 above)
Comment (farmaazon) [reply app/gui/src/project-view/components/SvgButton.vue]: But it reacts also on hover?

File: app/gui/src/components/TabView.vue (hunk 9 above)
Comment (farmaazon) [reply app/gui/src/components/TabView.vue]: As a rule, I assume if anyone would need to use same styles, they will generalize them (this is not hard to do in this case). But I may also make CloseButton component as in rect.

As for specificity calculations... these are scoped styles, so I guess it's not something unmanageable?

**Comment by farmaazon** [comment]
> I see a huge regression in the tabs implementation

I cannot reproduce that. Is this 100% reproducible on your side?

**Comment by MrFlashAccount** [comment]
Yes, 100%

IIRC I launched a hybrid project with 3g network slowdown

File: app/gui/src/project-view/components/SvgButton.vue (hunk 7 above)
Comment (MrFlashAccount) [reply app/gui/src/project-view/components/SvgButton.vue]: Hover is secondary here, main purpose is extending the click zone.

File: app/gui/src/components/TabView.vue (hunk 9 above)
Comment (MrFlashAccount) [reply app/gui/src/components/TabView.vue]: Scoped styles have nothing to do with the specificity, it's only encapsulation.

FWIW On dashboard we use tailwind + tailwind-variants to make styles with constant specificity(0,1,0) and a great customization

File: app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue (hunk 13 above)
Comment (MrFlashAccount) [reply app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue:42]: Then lets rename it in react as well

File: app/gui/src/components/TabView.vue (hunk 9 above)
Comment (farmaazon) [reply app/gui/src/components/TabView.vue]: What I meant is that having styles scoped to a single component, it's easier to handle all cases handled to specificity - it's not like your stile will hover something set in a completely different place.

Comment (MrFlashAccount) [reply app/gui/src/components/TabView.vue]: Agree it's easiear, but doesn't solve the specificity issue.

File: app/gui/src/dashboard/components/Spinner.tsx (hunk 6 above)
Comment (farmaazon) [reply app/gui/src/dashboard/components/Spinner.tsx:66]: Well, it's not the same: before, the animation was always slow, regardless if the passed state was `loading-fast`, `loading-medium` or `loading-slow`. I assumed this was an overlooked bug.

**Comment by farmaazon** [comment]
@MrFlashAccount I don't reproduce it... at lest not the same way.

Indeed, the animation is not entirely smooth, as we have one or two frames taking ~80ms, right when Editor is displayed. But the same result I get also in old implementation, before Vue Tab view - so it's not a _regression_.

The only difference is, that the slow frames are somewhat delayed in old implementation, because we spend significant time with loader, while new implementation displays Editor immediately. I would be happy to debug it together. So far I saw the time is spent on React rendering, but don't know what exactly is underneath.

**Comment by MrFlashAccount** [comment]
> Indeed, the animation is not entirely smooth, as we have one or two frames taking ~80ms, right when Editor is displayed. But the same result I get also in old implementation, before Vue Tab view - so it's not a regression.

Not sure we had two tabs shown simultaneously, do you have any evidence ?

File: app/gui/src/components/TabView.vue (hunk 9 above)
Comment (farmaazon) [reply app/gui/src/components/TabView.vue]: Well, I assume, unless we would start making many very specific global css selectors, it shouldn't be problem at all? The scoped always would have priority and inside a single component specificity should be manageable. In Vue we never had problems with it.

File: app/gui/src/project-view/components/MenuButton.vue (hunk 8 above)
Comment (farmaazon) [reply app/gui/src/project-view/components/MenuButton.vue]: So far, we don't use tailwind in Vue classes, as we were happy with its scoped styling. 

I could make a global class for adding extended hover, but we don't have any case outside buttons (output port area has different positions).

**Comment by farmaazon** [comment]
Fixed the regression. There's two thing missing:
1. Arrow navigation
2. tooltip for too long names
I want to add them in the next PR, to not delay this one.

**Review by MrFlashAccount — APPROVED** [review]
