### PR TITLE
Fix autoscoped constructor dynamic widget config

### LINKED ISSUE #10238: locale dropdown not working
image

If I join with an ignore case I should be able to choose a locale from a dropdown, but I cannot.

Potentially related to autoscoping changes

Version 2024.2.1-nightly.2024.6.11
Build f12e985b3a0cfc08a5b88e15bf1a58d9171a3b06
Electron 25.7.0
Chrome 114.0.5735.289
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.2.1-nightly.2024.6.11 Chrome/114.0.5735.289 Electron/25.7.0 Safari/537.36

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #10238 

Updated the way we construct `get_widget_json` visualization configuration to take into account cases when there is no known self argument.

As this is a bit of logic, I moved parts of WidgetFunction to a separate composable for easier testing. Most if it was just moved: meaningful changes were only in selfArgumentExternalId and visualizationConfig.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+        },
+        positionalArgumentsExpressions,
+      }
+    } else {
+      // In the case when no self argument is present (for example in autoscoped constructor),
+      // we assume that this is a static function call.
+      return {
+        expressionId: toValue(inputAst).externalId,
+        visualizationModule: WIDGETS_ENSO_MODULE,
+        expression: `a -> ${WIDGETS_ENSO_MODULE}.${GET_WIDGETS_METHOD} ${info.suggestion.definedIn}`,
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts]: If the argument is unused there's a syntax for that:
```suggestion
        expression: `_ -> ${WIDGETS_ENSO_MODULE}.${GET_WIDGETS_METHOD} ${info.suggestion.definedIn}`,
```

File: app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue [hunk 2]
```diff
@@ -24,16 +25,11 @@ import {
...
   getMethodCallInfoRecursively,
-  interpretCall,
 } from '@/util/callTree'
 import { partitionPoint } from '@/util/data/array'
-import type { Opt } from '@/util/data/opt'
 import { isIdentifier } from '@/util/qualifiedName.ts'
-import type { ExternalId } from 'shared/yjsModel.ts'
-import { computed, proxyRefs } from 'vue'
-import { FunctionName } from './WidgetFunctionName.vue'
+import { computed, proxyRefs, toRef } from 'vue'
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue]: `toRef` unused.

File: app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue [hunk 3]
```diff
@@ -53,26 +49,23 @@ provideFunctionInfo(
...
 )
 
-const methodCallInfo = computed(() => {
-  return getMethodCallInfoRecursively(props.input.value, graph.db)
-})
-
-const interpreted = computed(() => {
-  return interpretCall(props.input.value, methodCallInfo.value == null)
-})
+const { methodCallInfo, interpreted, visualizationConfig, selfArgumentPreapplied, subjectInfo } =
```
Comment (kazcw) [inline app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue]: I think this API could be simplified a bit.

The responsibility of `useWidgetFunctionCallInfo` is to analyze AST and ExpressionUpdates data; however, fully interpreting ExpressionUpdates requires some dynamicConfig information. Because the composable doesn't have this information, some of its outputs seem like intermediate values that require some context to understand.

If the composable were to take `widgetConfiguration` as an additional argument, it could return `application` instead of `interpreted`, `selfArgumentPreapplied`, and `subjectInfo`.

**Review by kazcw — APPROVED** [review]
