### PR TITLE
Remove warnings before calling into AbstractTypeCheckNode

### LINKED ISSUE #12177: Attaching Warnings discards the 'hidden part' of an intersection type
As [requested](https://github.com/enso-org/enso/pull/12170#issuecomment-2621157937) by @JaroslavTulach, reporting this as a separate issue.

Whenever an intersection type `A & B` is cast to `A` (hiding the `B` part), the `B` part should still be possible to be uncovered by a cast. However attaching a warning to a value makes it impossible to do so.

We already have pending tests demonstrating the issue:
https://github.com/enso-org/enso/blob/54ccd1a6ef92b35a5460c65c51a2a93550554e17/test/Base_Tests/src/Semantic/Multi_Value_As_Type_Refinement_Spec.enso#L297-L334

### LINKED ISSUE #12180: Unexpected `ClassCastException` upon atom field access when intersection types and warnings are combined
I was hitting an unexpected `ClassCastException` when running Table tests during development of my #12165 PR.

I was able to distill the issue into a small repro:
```
from Standard.Base import all

type My_Atom
    Value my_field

type My_Refinement
    Value x

My_Refinement.from (that : My_Atom) -> My_Refinement =
    My_Refinement.Value that

prepare_atom =
    x = Warning.attach "warn" <|
        My_Atom.Value 42
    x : My_Atom & My_Refinement

main =
    x = prepare_atom
    IO.println x.my_field
```

### Expected behaviour

The code should just print:
```
42
```

### Actual behaviour

The interpreter crashes with `ClassCastException`:
```
Execution finished with an error: java.lang.ClassCastException: class org.enso.interpreter.runtime.warning.WithWarnings cannot be cast to class org.enso.interpreter.runtime.data.atom.Atom (org.enso.interpreter.runtime.warning.WithWarnings and org.enso.interpreter.runtime.data.atom.Atom are in module org.enso.runtime of loader 'app')
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.atom.GetFieldNode.execute(GetFieldNode.java:38)
        at <enso> my_field(Internal)
        at <enso> err.main<arg-1>(err.enso:19:16-25)
        at <enso> err.main(err.enso:19:5-25)
```

### LINKED ISSUE #13108: Assertion error in dispatch when multi value types meet warnings
I encountered situations like this that were blocking my fixing of errors during the DB_Column part of #12994.

I tried to distill this into a minimal example and what I was able to find is following:
```ruby
from Standard.Base import all
import Standard.Base.Errors.Illegal_State.Illegal_State

type Base_Column
    Value underlying

type In_Memory_Column
    Value vec

type My_Warning
    Warning msg

Base_Column.from (that:In_Memory_Column) =
    Base_Column.Value that

In_Memory_Column.from (that:Base_Column) =
    if that.underlying.is_a In_Memory_Column then that.underlying else
        Error.throw (Illegal_State.Error "In_Memory_Column.from: that is not an In_Memory_Column")

refine base:Base_Column =
    (base : Base_Column & In_Memory_Column)

new_column vec:Vector -> Base_Column =
    refine (In_Memory_Column.Value vec)

main =
    col = new_column [1,2,3]
    col_warn = Warning.attach (My_Warning.Warning "My warning") col
    col_as_in_mem = col_warn:In_Memory_Column
    col_as_base = col_as_in_mem:Base_Column
    col_as_both = col_as_base:(Base_Column & In_Memory_Column)
    col_back = col_as_both:In_Memory_Column
    col_back.to_text
```

### Expected behaviour

Printing
```
col_warn = Base_Column & In_Memory_Column
 ! (My_Warning.Warning 'My warning')
col_as_in_mem = Base_Column & In_Memory_Column
 ! (My_Warning.Warning 'My warning')
col_as_base = Base_Column & In_Memory_Column
 ! (My_Warning.Warning 'My warning')
(In_Memory_Column.Value [1, 2, 3])
```

### Actual behaviour

If running with `-ea`, this fails with assertion error:
```
Execution finished with an error: java.lang.AssertionError: Dispatch (MultiType{types=[Base_Column]}) and extra (MultiType{types=[Base_Column]}) should be disjoin!
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.EnsoMultiValue$NewNode.newValue(EnsoMultiValue.java:107)
        at <java> org.enso.runtime/org.enso.interpreter.runtime.data.EnsoMultiValue$CastToNode.findTypeOrNull(EnsoMultiValue.java:618)
        at <java> org.enso.runtime/org.enso.interpreter.node.typecheck.SingleTypeCheckNode.findDirectMatch(SingleTypeCheckNode.java:121)
        at <java> org.enso.runtime/org.enso.interpreter.node.typecheck.SingleTypeCheckNode.doCheckNoConversionNeeded(SingleTypeCheckNode.java:68)
        at <java> org.enso.runtime/org.enso.interpreter.node.typecheck.SingleTypeCheckNodeGen.executeCheckOrConversion(SingleTypeCheckNodeGen.java:100)
        at <java> org.enso.runtime/org.enso.interpreter.node.typecheck.TypeCheckValueNode.handleCheckOrConversion(TypeCheckValueNode.java:56)
        at <java> org.enso.runtime/org.enso.interpreter.node.typecheck.TypeCheckExpressionNode.executeGeneric(TypeCheckExpressionNode.java:23)
        at <java> org.enso.runtime/org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:48)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:70)
        at <java> org.enso.runtime/org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
        at <enso> In_Memory_Column.from(Internal)
        at <enso> test-assert.main(test-assert.enso:32:16-26)
java.lang.AssertionError: Dispatch (MultiType{types=[Base_Column]}) and extra (MultiType{types=[Base_Column]}) should be disjoin!
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- Fixes #13108 by `WarningsLibrary.removeWarnings` before processing type checks
- If the check returns the same value (without warnings), returns the same value (prior warnings being removed)
- If the check converts to different value, the [original warnings are re-attached](https://github.com/enso-org/enso/pull/13118#discussion_r2099972524) to the new value

### Important Notes

Such a removal however has deep consequences. The attempt to address them outgrew the scope of the original change magnificently. Thus starting from scratch and leaving the following for later:

- however turns out that `Array.removeWarnings` actually removes warnings from all its values as well!
   - that's very likely wrong
   - but without it we [have trouble](https://github.com/enso-org/enso/pull/13118#issuecomment-2895098807) when passing `Array` with elements with warnings to _host interop_
- also `Vector.Builder` isn't behaving properly 
   - [long & double fixes](https://github.com/enso-org/enso/pull/13118/files#r2097037793) needed - not anymore that fix was reverted as converting from `long` to `double` changes the _type of the number_ behind the scene
- adds `runEngineDistribution --env` support in e8ba79e340 - separated into #13131 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [ ] Benchmarks are fine
   - [ ] [engine run](https://github.com/enso-org/enso/actions/runs/15158954505) and [run after latest fix](https://github.com/enso-org/enso/actions/runs/15163565475)
   - [ ] [stdlibs run](https://github.com/enso-org/enso/actions/runs/15158961404) and [run after latest fix](https://github.com/enso-org/enso/actions/runs/15163603627)

### CODE REVIEW

**Review by AdRiley — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
- there is a [failure in tests](https://github.com/enso-org/enso/runs/42461692767#r2s14)
- it can be workarounded by the diff below

> ❌ Accepts deprecated use_bankers boolean argument, with a warning
	round(-3.5, 0, rounding_mode=True) -> Expected the result to contain a warning: Deprecated, but it did not. The warnings were []

```diff
diff --git test/Base_Tests/src/Data/Round_Spec.enso test/Base_Tests/src/Data/Round_Spec.enso
index 9d0a8b4f74..ed783b1c5e 100644
--- test/Base_Tests/src/Data/Round_Spec.enso
+++ test/Base_Tests/src/Data/Round_Spec.enso
@@ -24,7 +24,8 @@ type Batch_Runner
         epsilon_vec  = configs.map c-> c.at 3
         warning_vec  = configs.map c-> c.at 4
         got_vec = self.run_batch values_vec dps_vec rounding_mode
-        got_vec.each_with_index ix-> got->
+        got_vec.each_with_index ix-> _->
+            got = got_vec.at ix
             expected = expected_vec.at ix
             value = values_vec.at ix
             dp = dps_vec.at ix
```
- something must be wrong with the `each_with_index` that seems to drop the warnings when passing value to callback.
- something is wrong with `Array.each` as 6986953 shows

**Review by GregoryTravis — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
- JUnit tests seem to be fixed by 6dfb172
- standard libs are still failing
   - ❌ Accepts deprecated use_bankers boolean argument, with a warning
	- round(-3.5, 0, rounding_mode=True) -> Expected the result to contain a warning: Deprecated, but it did not. The warnings were [] (at Base_Tests/src/Data/Round_Spec.enso:36:21-55).
   - Warnings and each - Expected False to be True (at Base_Tests/src/Data/Vector_Spec.enso:1023:13-32). fails for
        - ❌ [Use a slice of an array as vectors](https://github.com/enso-org/enso/runs/42504077801#r2s277)
        - ❌ [Use Java ArrayList as vectors](https://github.com/enso-org/enso/runs/42504077801#r2s280)

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java [hunk 1]
```diff
@@ -68,6 +68,23 @@ void add(Object e, WarningsLibrary warnings) {
         longArray[size++] = l;
       } else {
         CompilerDirectives.transferToInterpreter();
+        TRY_DOUBLE:
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java]: - The change is getting complicated
- after [problems with propagation of warnings](https://github.com/enso-org/enso/runs/42526347007#r2s286) in a `Vector.Builder`: 
   - Builder should not propagate warnings attached to an item `with .append_vector_range with propagate_warnings=False`
	- `[Error err] did not equal []; lengths differ (1 != 0)  (at Base_Tests/src/Data/Vector_Spec.enso:1220:13-47).`
- I decided to write `VectorBuilderTest` to check the warnings
- but it turns out we don't create effective backing for mixed `long` and `double` values
   - that may affect us badly and mixed values like that may be pretty common
   - hence fixes like 8fb3cbc and b7eb0a2

File: distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso [hunk 2]
```diff
@@ -1562,7 +1561,7 @@ type Builder
         without_warnings = self.elements_java_builder.toArray
         if self.propagate_warnings.not then without_warnings else
             warnings_vector = self.warnings_java_builder.toArray
-            Warning.attach_multiple warnings_vector without_warnings
+            Warning.set without_warnings warnings_vector
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso]: This `Warning.set` deduplicates warnings from elements and the `Vector`.

File: project/EnsoProjects.scala [hunk 3]
```diff
@@ -10,9 +10,10 @@ import java.nio.file.Path
 object EnsoProjects {
   case class Project(namespace: Option[String], name: String, path: Path) {
     def usesPrivateAccess: Boolean =
-      path.getParent.getFileName.toString == "test" && name.contains(
-        "_Internal_"
-      ) && name.endsWith("_Tests")
+      path.getParent != null && path.getParent.getFileName.toString == "test" && name
```
Comment (JaroslavTulach) [inline project/EnsoProjects.scala]: Unrelated, but:
```
sbt:enso> runEngineDistribution --run r.enso 
```
was causing NPE as `Path` representing `r.enso` probably had no parent.

**Comment by JaroslavTulach** [comment]
There are still [Microsoft_Test failures](https://github.com/enso-org/enso/runs/42566829224#r6s37) at:
- ❌ by float operations An unexpected panic was thrown: (Unsupported_Argument_Types.Error [[org.enso.table.data.table.Column]] 'Cannot convert \'org.enso.table.data.table.Column@3c41f0c7\'(language: Enso, type: org.enso.table.data.table.Column) to Java type \'org.enso.table.data.table.Column\': Unsupported target type.')
- ❌ should report issues: floating point equality An unexpected panic was thrown: (Unsupported_Argument_Types.Error [[org.enso.table.data.table.Column]] 'Cannot convert \'org.enso.table.data.table.Column@6e5ca7df\'(language: Enso, type: org.enso.table.data.table.Column) to Java type \'org.enso.table.data.table.Column\': Unsupported target type.')
- ❌ already existing warnings should not be escalated to errors in error handling mode - An unexpected panic was thrown: (Unsupported_Argument_Types.Error [[org.enso.table.data.table.Column]] 'Cannot convert \'org.enso.table.data.table.Column@63c0d9f7\'(language: Enso, type: org.enso.table.data.table.Column) to Java type \'org.enso.table.data.table.Column\': Unsupported target type.')

all of them are caused by calling a Java method that needs `Column[]` with `Array(WithWarnings(Column))` and the `WithWarnings(Column)` cannot be converted to `Column`...

- that's because of 698695373c3ec7d19f4ebeba627244b979affe9a - `Array.each` _shouldn't be loosing warnings for its elements_
- but when it doesn't loose the warnings, then we pass `Array(WithWarnings(Column))` to the Java interop
- the proper fix would be something like oracle/graal#4916 on the GraalVM side
- now I am just about to clean up the warnings at the single call side manually
   - **done** in f5b2606d03860b6e68d8b0da9451e31632d37f03

File: distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso [hunk 4]
```diff
@@ -151,13 +151,14 @@ type Table
...
         cols = columns.map on_problems=No_Wrap.Value c->
-            column = case c of
+            column_with_warning = case c of
                 v : Vector -> case v.length of
                     2 -> Column.from_vector (v.at 0) (v.at 1)
                     3 -> Column.from_vector (v.at 0) (v.at 1) (v.at 2)
                     _ -> invalid_input_shape
                 col : Column -> col
                 _ -> invalid_input_shape
+            column = Warning.clear column_with_warning
```
Comment (JaroslavTulach) [inline distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso]: Workaround for https://github.com/enso-org/enso/pull/13118#issuecomment-2895098807

File: docs/CONTRIBUTING.md [hunk 5]
```diff
@@ -23,12 +23,14 @@ sections of this document are linked below:
...
-  - [Getting Set Up \(Rust\)](#getting-set-up-rust)
-  - [Getting Set Up \(JVM\)](#getting-set-up-jvm)
-  - [Getting Set Up \(Documentation\)](#getting-set-up-documentation)
-  - [Building Enso](#building-enso)
-  - [Testing Enso](#testing-enso)
-  - [Running Enso](#running-enso)
+  - Configuration
+    - [Set Up Rust)](#getting-set-up-rust)
+    - [Set Up Documentation](#getting-set-up-documentation)
+  - Enso Engine CLI
```
Comment (JaroslavTulach) [inline docs/CONTRIBUTING.md]: - separating the changes in 6a7159b3f6c67328de2101675f99f7a969209d58
- into own #13131 
- read the [rendered documentation](https://github.com/enso-org/enso/blob/b653828adf50f9a39cf40578fd67a2a0a2907bf8/docs/CONTRIBUTING.md#building-enso-engine)

File: engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorTest.java [hunk 6]
```diff
@@ -139,6 +142,90 @@ public void passingListOrArrayToEnsoAsArray() throws Exception {
     assertEquals("Hundred elements", 100, hundred.asInt());
   }
 
+  @Test
+  public void vectorWithWarningViaForEach() throws Exception {
+    warningsInContainer(1, 1);
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorTest.java]: Use `testOnly *VectorTest` to debug behavior of warnings in an _isolation_ (from the `Standard.Test` harness):

- warnings behavior depends on every detail
- there are deeper nuances elsewhere,
- thinking about warnings from Enso code macroscopic perspective is hard,
   - it is "black box testing" (without clear specification),
- one needs to **debug the interpreter** to really know what's going on

**Comment by JaroslavTulach** [comment]
The current set of commits in this PR is:
- 6a7159b3f6c67328de2101675f99f7a969209d58 -      Focus on using runEngineDistribution  
- ee30f00c1459be7ba4aa71a9cbee907060da3fd6 -      Remove warnings from Column before calling into Java  
- 475d367af4bfd382092d6b449ab82de007567e1d -  delete mode 100644 lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/TelemetryAppender.java  create mode 100644 std-bits/table/src/main/java/org/enso/table/data/column/operation/IfOperation.java  create mode 100644 std-bits/table/src/main/java/org/enso/table/data/column/operation/binary/LogicalOperations.java 
- e8ba79e340230f35ba6d824473d2f95b6dcbae38 -      Support --env for runEngineDistribution  
- f5b2606d03860b6e68d8b0da9451e31632d37f03 -      Remove warnings from Column before calling into Java  
- 357041b7c5dda578d47e796801a0584f7a45205c -      add_warnings is private now  
- 163c1bce38a554c4cd382ebce32187eebd21f665 -          * Fix dropdown?  
- ef89b0bee379e9b7dec8b86c90d2e3b98c29974b -      Avoid NPE when parent is null  
- 58b145c7b1e1feef599d73182f68d9edfd8d30c7 -      Explicitly ask for array without warnings  
- 0b11a26390c73a904e46d9550e9a9d95b6dc2f0a -     Array.removeWarnings sets withWarnings flag to false   create mode 100644 engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ArrayTest.java 
- 3fb6fa35c9028ca1b0a2e9cd3672baac8837e399 -  create mode 100644 app/gui/src/dashboard/components/AriaComponents/ContextualHelp/index.ts  create mode 100644 app/gui/src/dashboard/components/AriaComponents/Form/components/Field.stories.tsx  create mode 100644 app/gui/src/dashboard/components/AriaComponents/Inputs/Input/Input.stories.tsx 
- a38c674b645cfb28ff80b269b1148c0867e78080 -      Fix setting operator argument (fixes #12827) (#13125)  
- cce6dc6168485906a40132ed6c7f458e1fbba9fb -          https://github.com/user-attachments/assets/56916134-b5bc-450f-bcd9-c55beca512a7  
- 5b3d5993e42507274d32ce408ae4b267af2477f3 -  rename app/gui/src/dashboard/layouts/Settings/{index.tsx => Settings.tsx} (91%)  create mode 100644 app/gui/src/dashboard/layouts/Settings/index.ts  create mode 100644 app/gui/src/dashboard/providers/AuthProvider/authStore.ts 
- 6ccc75ce155857023b1ab6963e70dc6e43fe4790 -      Refactor (#13119)  
- 733124f2382b99563c6b7af75d10be08dce0aa9a -      Skip the test with ArrayList  
- 2b35532d6f4e02cd29d3ca2b91238c90f37d9f0c -      Reverting special long&double support. Down to three failures in test/Base_Tests  
- e1c86689c3004cf92884a9a0a4dec2e33c40fdf1 -  delete mode 100644 app/gui/src/dashboard/components/styled/withFocusScope.tsx  create mode 100644 app/gui/src/dashboard/typings.d.ts  delete mode 100644 app/gui/src/dashboard/utilities/react.ts 
- 5efeb9eca4b1b07b1c1787393804bb6f80f129bb -      Build texts while not propagating warning  
- f1672dd84334a14b1c77090deb7caf3940b02ce5 -      Builder on Text test  
- b0f2d2f0aa2048b3c1ef1968ad8e77b93fe5d1e0 -      Don't propagate warnings when propagation disabled  
- feb13b3c608307903a81cc496244a5faf033b166 -      Re-add exact warning instances, not their copies  
- 6ded717ce9f1238ed8c0c8c27af08f6e61ac73bb -      Build vector with a warning  
- b7eb0a2b3669946648c5ef4fc2c5bafe8e02c35a -      doubles followed by longs may still form Vector.Double  
- 8fb3cbc654d62b7a98b21b653366ddbe81b974ce -     Mixing longs and doubles should lead to Vector.Double   create mode 100644 engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorBuilderTest.java 
- 36434d2ba90552eeeec5889d0965cb4e33e2a784 -      Operations on Vector and Array keep warnings on their elements  
- 6dfb172191c1737959dba85f8ed9e1f0ce362821 -      Keep warnings on elements when Vector.from_polyglot_array  
- 3eeb7947524619e4ef14bddebabc2ea8c656236e -      Testing also .map with warning  
- 74c66a191516fcaf304f1288d40390bad80eefe2 -  create mode 100644 app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts  delete mode 100644 app/gui/src/project-view/components/widgets/FileBrowserWidget/paths.ts  create mode 100644 app/gui/src/project-view/components/widgets/FileBrowserWidget/userFiles.ts 
- 83ffdb6c695982e4a4495997c95a34048c15d225 -      VectorTest.arrayWithWarningViaForEach shows difference in behavior compared to Vector  
- 698695373c3ec7d19f4ebeba627244b979affe9a -      Array.each seems to loose warnings  
- 1ca6cbb0bce0d0f6b040f7ea5cebbae906ec3492 -     This doesn't change the fact that logic of audit/telemetry/remote logs     should be merged but that's a topic for #12564.  
- 9b87f8ca29cd2f9863695828bd7a44c71d4cfc42 -      Test to show #12180 is fixed  
- f342ba9639d12f25ac0d2589dffb1602e78908ab -      Enabling test as #12177 seems to be fixed  
- 43b878ff23ea99bda8f443f57a4ca83e87364e81 -     Remove warnings before calling into AbstractTypeCheckNode   create mode 100644 test/Base_Tests/src/Semantic/Multi_Value_Column_Like_Spec.enso 

However I believe I am going to **start from scratch** - clearly 698695373c3ec7d19f4ebeba627244b979affe9a and its _transitive scope_ is too huge - so let's start from its parent 9b87f8ca29cd2f9863695828bd7a44c71d4cfc42 again.

- created  #13139
- based on [code in the above commits](https://github.com/enso-org/enso/compare/6a7159b3f6c67328de2101675f99f7a969209d58)

File: test/Base_Tests/src/Data/Round_Spec.enso [hunk 7]
```diff
@@ -24,7 +24,8 @@ type Batch_Runner
         epsilon_vec  = configs.map c-> c.at 3
         warning_vec  = configs.map c-> c.at 4
         got_vec = self.run_batch values_vec dps_vec rounding_mode
-        got_vec.each_with_index ix-> got->
+        0.up_to got_vec.length . each \ix ->
+            got = got_vec.at ix
```
Comment (JaroslavTulach) [inline test/Base_Tests/src/Data/Round_Spec.enso]: This fix is necessary to workaround [all the transitive closure of problems](https://github.com/enso-org/enso/pull/13118#issuecomment-2896884673).

**Review by Akirathan — APPROVED** [review]

File: test/Base_Tests/src/Data/Round_Spec.enso (hunk 7 above)
Comment (JaroslavTulach) [reply test/Base_Tests/src/Data/Round_Spec.enso]: With 388d5736b4 the change 8ecb0a0 is no longer needed, which is great!

It makes me feel way more confident. There shall be no problems with warnings, when the _type check_ returns the _same value_ - e.g. with plain type checks. Only when doing conversions the warnings _get reattached_ - e.g. only then we could see some divergence in the behavior.

**Comment by JaroslavTulach** [comment]
Engine benchmarks exhibit some changes:

Faster ifBench6

Faster ifBench6In

Faster multivalue benchmarks

Faster averageOverSlice

We are good to integrate from engine point of view!
