### PR TITLE
Do not crash on empty main function body.

### LINKED ISSUE #10976: Deleting last component from canvas is breaking the project
https://github.com/user-attachments/assets/b73edebb-5671-4eb2-8d98-35cc0671e3ae

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #10976 

https://github.com/user-attachments/assets/00b2279d-2acf-468b-8c3c-aa6885cba23d

Addressed issue of empty body block being incorrectly "repaired" into an empty group, geneating invalid `()` syntax. Appending nodes to an empty function now actually replaces its body block, instead of creating a temporary orphan body block node.

Note that empty main function is still considered an error on the engine side, but it doesn't impact the IDE in negative way. Things work again as soon as a node is inserted.

Also fixed a few issues causing hot-reloading to break. Now edited AST code properly hot-reloads all affected modules without breaking the app.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/ydoc-shared/src/ast/parse.ts [hunk 1]
```diff
@@ -705,6 +705,7 @@ export function repair(
   const fixes = module ?? root.module.edit()
   for (const ast of lostInline) {
     if (ast instanceof Group) continue
+    if (ast instanceof BodyBlock) continue
```
Comment (kazcw) [inline app/ydoc-shared/src/ast/parse.ts]: I think it would be better to handle this case earlier so that it doesn't trigger error recovery.
When we call `checkSpans`, we could pass a filtered version of `printed.info.nodes`, with any 0-length entries corresponding to nodes of type `BodyBlock` removed.
*This could alternatively be handled by the block printing logic; I prefer this post-print filtering solution to keep the print API simpler (printing a node always adds it to the span map) and make this function the one place where allowed divergence between the AST and the code is defined (currently, that would be only this 0-length block case).*

Comment (Frizi) [reply app/ydoc-shared/src/ast/parse.ts]: Ended up moving the condition to `checkSpans`, as I wanted to avoid filtering the whole nested map of sets ahead of time. Since we are already looping through "lost" nodes, it is much cheaper to exclude them during that loop. I think that still matches your intention of having this "valid mismatches" logic in one place and it never hitting repair in the first place.

**Review by kazcw — APPROVED** [review]
