### PR TITLE
project-manager can start without prior GraalVM installation

### LINKED ISSUE #8396: Language Server fails to start
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

when trying to create a project an error occurs: ```Error creating new project: The runner used to create the project returned exit code 1.```

### Expected behaviour

Project should be created

### How we can reproduce it?

Open Ań electron package and try to create a new project

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/f0e68731-e02d-44ed-bba1-84e161628993

### Logs

_No response_

### Enso Version

nightly 27.11

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #8396

### Pull Request Description

This is a follow-up of #7991. #7991 broken `runtime-version-manager`. This is mostly reverts.

### Important Notes

Launcher now correctly recognizes that the newest engine needs some runtime:
```sh
> java -jar launcher.jar list
Enso 2023.2.1-nightly.2023.10.31 -> GraalVM 23.0.0-java17.0.7
Enso 0.0.0-dev -> GraalVM 23.1.0-java21.0.1
```
(this has not worked before)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by Akirathan** [comment]
Tested by:
- Building `project-manager` with `project-manager/buildNativeImage`.
- Locally build GUI sources with `./run gui build --skip-wasm-opt && ./run gui watch --wasm-source local`
- Make sure there are no runtimes in `~/.local/share/applications/enso/runtime`
- Create a new project

The output from `project-manager` is:
```
[INFO] [2023-11-28T19:01:32+01:00] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[INFO] [2023-11-28T19:01:41+01:00] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [1881c2c8-d731-4bf8-b015-15bdeeaf2d97]
[INFO] [2023-11-28T19:02:20+01:00] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [1881c2c8-d731-4bf8-b015-15bdeeaf2d97]
[INFO] [2023-11-28T19:02:22+01:00] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [dc05f420-b4a5-4e5d-b0ee-0aa2a7156d32]
[WARN] [2023-11-28T19:02:24+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Ignoring the minimum required engine version check [2023.2.1-nightly.2023.11.2] for the development version [0.0.0-dev].
[INFO] [2023-11-28T19:02:24+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [0.0.0-dev] found.
[INFO] [2023-11-28T19:02:24+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] GraalVM runtime [GraalVM 23.1.0 Java 21.0.1] not found.
[INFO] [2023-11-28T19:02:24+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Installing GraalVM runtime [GraalVM 23.1.0 Java 21.0.1].
[INFO] [2023-11-28T19:02:37+01:00] [org.enso.projectmanager.service.versionmanagement.ControllerInterface] Installed GraalVM 23.1.0-java21.0.1.
[INFO] [2023-11-28T19:02:38+01:00] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server [LanguageServerDescriptor(language-server-f240b3eb-b2c2-4e43-bdcd-2aa3e0b395e8,dbf4ffb4-8c5c-4b31-8907-b0bee0d1de22,/home/pavel/enso/projects/New_Project_3,NetworkConfig(127.0.0.1,49152,65535,false),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@7c6d55f6,0.0.0-dev,JVMSettings(None,List()),false,None,None,Future(Success(Some(//localhost:6000))),false)].
[INFO] [2023-11-28T19:02:38+01:00] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:50001:none, binary:127.0.0.1:49459:none].
[WARN] [2023-11-28T19:02:38+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Ignoring the minimum required engine version check [2023.2.1-nightly.2023.11.2] for the development version [0.0.0-dev].
[INFO] [2023-11-28T19:02:38+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [0.0.0-dev] found.
[INFO] [2023-11-28T19:02:38+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 23.1.0-java21.0.1].
```

i.e., project-manager correctly resolves that engine `0.0.0-dev`  needs runtime "GraalVM 23.1.0 Java 21.0.1", downloads it from graalvm-ce release GH pages and boots the language server with it.

File: lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala [hunk 1]
```diff
@@ -56,4 +57,26 @@ trait MissingComponentBehavior {
...
+    "make sure to check if the runtime is installed even if the engine was " +
+      "already installed" in {
+      uninstallRuntime(GraalVMVersion("23.2.0", "21.0.0"))
+
+      val client = new WsTestClient(address)
+      client.send(
+        buildRequest(defaultVersion, MissingComponentAction.Install)
+      )
+
+      /** We do not check for success here as we are concerned onyl that the
```
Comment (JaroslavTulach) [inline lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala:75]:
```suggestion
      /** We do not check for success here as we are concerned only that the
```

File: lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala [hunk 2]
```diff
@@ -56,4 +57,26 @@ trait MissingComponentBehavior {
...
+       * installation is attempted. Installation and creating/opening projects
```
Comment (JaroslavTulach) [inline lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala]: Why do we check whether an installation is attempted? The current requested behavior is to *download nothing*.

File: lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala [hunk 3]
```diff
@@ -42,19 +43,44 @@ class RuntimeVersionManagerSpec
       )
 
       val runtime = componentsManager.findGraalRuntime(engine)
-      runtime shouldBe empty
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala:45]: Is this the core of the fix? Previously no `runtime` was found and now we find the latest GraalVM?

File: lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala [hunk 4]
```diff
@@ -42,19 +43,44 @@ class RuntimeVersionManagerSpec
...
 
-    "list installed engines" in {
+    "list installed engines and runtimes" in {
       val componentsManager = makeRuntimeVersionManager()
       val engineVersions =
-        Set(SemVer(0, 0, 0), SemVer(0, 0, 1), SemVer(0, 0, 1, Some("pre")))
+        Set(SemVer(0, 0, 0), SemVer(0, 0, 1), SemVer(0, 1, 0))
+      val runtimeVersions =
+        Set(
+          components.GraalVMVersion("1.0.0", "11"),
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala:59]: Why do we find `1.0.0` at `11`?

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/Engine.scala [hunk 5]
```diff
@@ -29,17 +29,6 @@ case class Engine(version: SemVer, path: Path, manifest: Manifest) {
     */
   def graalRuntimeVersion: GraalVMVersion = manifest.runtimeVersion
 
-  /** The GraalVM distribution policy changed a lot since GraalVM 23.0.0 for JDK 21.
-    * The newest GraalVM is now distributed as artifacts from the Maven central, and therefore,
-    * does not need to be downloaded at runtime.
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/Engine.scala:34]: Yes, removing this aligns with what I [wrote here](https://github.com/enso-org/enso/issues/8280#issuecomment-1825371861).

File: lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMVersion.scala [hunk 6]
```diff
@@ -32,10 +29,11 @@ case class GraalVMVersion(graalVersion: String, javaVersion: String) {
     }
   }
 
-  /** The GraalVM distribution policy changed a lot since GraalVM 23.0.0 for JDK 21.
-    * The newest GraalVM is now distributed as artifacts from the Maven central, and therefore,
-    * does not need to be downloaded at runtime.
-    * @see https://medium.com/graalvm/truffle-unchained-13887b77b62c
+  /** The GraalVM distribution policy changed a lot since GraalVM 23.1.0 for JDK 21.
+   * Most of the components for the newest GraalVM distributions are distributed as
+   * artifacts from the Maven central. This mens there is no longer `gu` tool.
```
Comment (JaroslavTulach) [inline lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMVersion.scala]:
```suggestion
   * artifacts from the Maven central. There is no longer any `gu` tool.
```

**Review by JaroslavTulach — APPROVED** [review]
Questions left as I don't understand the consequences. However it looks fine from highlevel perspective.

File: lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala (hunk 3 above)
Comment (Akirathan) [reply lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala:45]: Yes. More specifically, we don't find the *latest* GraalVM, but rather the one that is specified in [fake-releases/enso-0.0.1/manifest.yaml](https://github.com/enso-org/enso/blob/226ccb742043179b8b5620d35bcfb5bd0edfc6d8/lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.1/manifest.yaml)

File: lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala (hunk 4 above)
Comment (Akirathan) [reply lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala:59]: Because it is specified in [fake-releases/enso-0.0.0/manifest.yaml](https://github.com/enso-org/enso/blob/5a7ad6bfe4fe6c0a945e1afb7c3ec3e58b937293/lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.0/manifest.yaml). Note that runtime-version-manager tests uses a fake release provider that fetches the data from the [fake-releases](https://github.com/enso-org/enso/blob/226ccb742043179b8b5620d35bcfb5bd0edfc6d8/lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases) directory in resources

File: lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala (hunk 2 above)
Comment (Akirathan) [reply lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala]: Because the installation was explicitly requested by the client at line 72 [here](https://github.com/enso-org/enso/blob/851fabf06fafbb989e92c62f7ae73b75ab99c765/lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala#L72).

**Review by hubertp — APPROVED** [review]
Looks alright, haven't tested it though

**Comment by jdunkerley** [comment]
Tested on a M2 Pro with no Java and work fine.
