### PR TITLE
Fix inconsistency when building a Mixed column, fixes to Union

### LINKED ISSUE #7352: Creating Mixed type columns converts Integers to Decimal in an inconsistent manner
Let's see a few examples (all statements that return a boolean are in form of assertions - I'm writing only statements that in current situation return True):

When I mix Integers and Decimals, they are upcasted to a Float column based on DoubleStorage. That seems OK.

```
c1 = Column.from_vector "X" [1, 2.0, 1.5]
c1.value_type == Value_Type.Float
c1.at 0 . is_a Decimal
c1.at 1 . is_a Decimal
c1.at 2 . is_a Decimal
```

When I add in a Text value, it gets Mixed type
```
c2 = Column.from_vector "X" ["a", 1, 2.0]
c2.value_type == Value_Type.Mixed
c2.at 0 . is_a Text
# now since we are in Mixed mode, there is no finding of common numeric types, 
# so the values are preserved as is, the Integer stays an Integer:
c2.at 1 . is_a Integer
c2.at 2 . is_a Decimal
```

Ok, but what if we change the order??
```
c3 = Column.from_vector "X" [1, 2.0, "a"]
c3.value_type == Value_Type.Mixed
c3.at 0 . is_a Integer . not # (!)
c3.at 0 . is_a Decimal # The integer got coerced to a Decimal
c3.at 1 . is_a Decimal # That is because we first were constructing an integer column, 
                       # but when encountered the `2.0`, we switched to a floating-point, changing the type of the Integer
c3.at 2 . is_a Text    # Only when we encountered the Text, we switched to the 'general' Mixed type. 
                       # But at this point the `1` was already converted to the Decimal and has not been revisited.
```

Ok but what if we spice it up even more?
```
c4 = Column.from_vector "X" [1, 2.0, "a", 3]
c4.at 0 . is_a Decimal # as in the example above, since 2.0 is encountered, 
                       # 1 gets converted to 1.0 decimal - because we are not yet in full mixed mode at this point.
c4.at 1 . is_a Decimal
c4.at 2 . is_a Text
c4.at 3 . is_a Integer # (!) And this one is probably most shocking. The `1` got converted to a Decimal,
                       # because we were in numeric mode. After encountering "a" we switch to Mixed mode
                       # and then when we see 3 we are in Mixed mode so the Integer type is kept preserved.
```

I think the last example is worst - on the input we had values of type Integer, Decimal and Text. At the output we also have these 3 types, but _some_ integers got converted to Decimal, whereas others did not - depending if they came _before or after_ the first _non-numeric_ value.

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Fixes #7352 by remembering original value types in type inference mode to be able to reconstruct them for Mixed.
   - Added more benchmarks for comparing performance of constructing columns.
- Fixes missing implementations that caused `Table.union` crashing on some type pairs.
- Ensures that `Loss_Of_Integer_Precision` warning is not swallowed when numeric columns are unioned to create a `Float` column.
- Adds test for all of the above cases.
- Allow to output benchmark results to a CSV by setting an environment variable - useful for quickly comparing benchmarks, e.g. in Enso.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: std-bits/table/src/main/java/org/enso/table/data/column/builder/InferringDoubleBuilder.java [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+  /**
+   * Specifies at which indices we encountered integers.
+   * <p>
+   * This is used for reconstructing the original values when retyping to mixed. Integers that are small enough can be
+   * reconstructed from their double values, so we do not need to store them as `rawData`, instead we only mark that
+   * they need to be converted back into integers when retyping. This allows us to completely avoid allocating the
+   * `rawData` array for most practical scenarios when the integers are not too large. The cost of allocating this
+   * BitSet should be significantly lower than allocating the `rawData` array.
+   */
+  private final BitSet isLongCompactedAsDouble;
```
Comment (radeusgd) [inline std-bits/table/src/main/java/org/enso/table/data/column/builder/InferringDoubleBuilder.java]: The `rawData` allows for reconstructing original values with original types when retyping back to Mixed.

It has to be `Object`/`Number` because we can get either `Long` or `BigInteger`, so an unboxed array wouldn't suffice.

---

The `isLongCompactedAsDouble` is an optimization that allows us to avoid allocating the potentially large `rawData` array in case all encountered `long` values are not too large - in this case they fit into `double` without losing precision, so we can reconstruct them without the helper array.

The additional logic does make the thing slower in case of encountering lots of big integer values, but it improves the 'most common' (only floats, or only floats and relatively small integers) case significantly.

The measurements are as follows:
image

Comment (radeusgd) [reply std-bits/table/src/main/java/org/enso/table/data/column/builder/InferringDoubleBuilder.java]: We can see that with the common path optimization our results in `Auto` mode are basically as fast as the old (incorrect) implementation - whereas the fixed implementation _without_ the optimization is even 2x slower (see `Floats_type_Auto` for 2x slower, `Integers_type_Auto` is just slightly slower).

In the case of mixed numbers - integers and floats; if the integers are relatively small (e.g. less than 2^50 or so - so a huge range anyway) the optimized case behaves roughly as fast as the old incorrect implementation vs the unoptimized one which is almost 2x slower (see `Numeric_Mix_Small_type_Auto`).

Finally, the last case - `Numeric_Mix_Large_type_Auto` - the case where we encounter `BigInteger` values and `long` values that cannot be exactly represented in `double`. This is the case where the 'optimized' approach can be as much as 2x slower than the 'simple' fixed solution. This is however the rarest occurrence - we don't expect to get such big numbers often. Weirdly, the 'old' implementation also had this relatively slower speed (I'm not sure why).

---

In case we know the expected type `*_type_Float`, performance of all approaches is comparable - this path is largely unaffected by these changes.

----

I think the optimization is beneficial, because it allows our most common paths to run much faster, at the cost of complicating rarely used paths.

**Review by Akirathan — APPROVED** [review]
Thanks for the bits and pieces for the bench framework. That will make running the benchmarks only from Enso and analyzing it later better.

**Review by GregoryTravis — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]
