### PR TITLE
Fix CB interaction with record-mode override and add tests

### LINKED ISSUE #7976: Context switch expression is put to CB input when editing nodes
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When the context switch expression is present, and you edit the node, the expression is removed.

### Expected behaviour

Edits should touch only a modifiable part of the node's expression. Any execution context switch state must be preserved.

### How we can reproduce it?

1. Disable output context for the node using a button next to it
2. Edit the node
3. Observe context switch is no longer present.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

0228022809cb2f5a11b9ae7e8b2db4497e2c103b

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fixes #7976.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui2/src/components/GraphEditor/GraphNode.vue [hunk 1]
```diff
@@ -430,7 +430,7 @@ const documentation = computed<string | undefined>({
     <div class="binding" @pointerdown.stop v-text="node.pattern?.code()" />
     <button
       v-if="!menuVisible && isRecordingOverridden"
-      class="overrideRecordButton"
+      class="overrideRecordButton recording-overridden"
```
Comment (Frizi) [inline app/gui2/src/components/GraphEditor/GraphNode.vue]: lets use `data-testid` instead of classes when all you want to do is to locate a thing in tests. It is even nicely supported by playwright: https://playwright.dev/docs/locators#locate-by-test-id

File: app/gui2/src/stores/graph/index.ts [hunk 2]
```diff
@@ -327,11 +327,12 @@ export const useGraphStore = defineStore('graph', () => {
...
     if (!node) return
     edit((edit) => {
-      edit.getVersion(node.rootExpr).syncToCode(content)
+      const editExpr = edit.getVersion(node.innerExpr)
+      editExpr.syncToCode(content)
       if (withImports) {
         const conflicts = addMissingImports(edit, withImports)
         if (conflicts == null) return
-        const wholeAssignment = edit.getVersion(node.rootExpr)?.mutableParent()
+        const wholeAssignment = editExpr.mutableParent()
```
Comment (Frizi) [inline app/gui2/src/stores/graph/index.ts:336]: I really don't understand the interaction of `getVersion` and `syncToCode` here. What caused the original issue? Why calling `getVersion` again causes things to break, especially since its return value is not really used other than for error reporting?

**Review by Frizi — DISMISSED** [review]

File: app/gui2/src/stores/graph/index.ts (hunk 2 above)
Comment (kazcw) [reply app/gui2/src/stores/graph/index.ts:336]: Calling `getVersion` once is just a refactor. The functional change is using `node.innerExpr` instead of `node.rootExpr`.

**Review by farmaazon — APPROVED** [review]
