### PR TITLE
Fix record once

### LINKED ISSUE #10103: Record Once button not working
Record Once button doesn't seem to do anything.
Record button still seems to work OK.

https://github.com/enso-org/enso/assets/1720119/044ddbbc-5d6a-4e92-8dfb-76f3d49dd122

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #10103

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by Frizi — APPROVED** [review]

File: app/gui2/src/components/RecordControl.vue [hunk 1]
```diff
@@ -17,8 +17,14 @@ const emit = defineEmits<{ recordOnce: []; 'update:recordMode': [enabled: boolea
...
     </div>
-    <div class="control right-end" @click.stop="() => emit('recordOnce')">
-      <SvgButton title="Record Once" class="iconButton" name="record_once" draggable="false" />
+    <div class="control right-end">
+      <SvgButton
+        title="Record Once"
+        class="iconButton"
+        name="record_once"
+        draggable="false"
+        @click.stop="() => (console.log('CLICK'), emit('recordOnce'))"
```
Comment (Frizi) [inline app/gui2/src/components/RecordControl.vue]: Remove log
