### PR TITLE
Fix formatting for "About App" modal

### LINKED ISSUE #10111: About box renders with truncated text and scroll bar
image

Version 2024.1.1-nightly.2024.5.28
Build 8edf49343f3a8e3b5ede9e264af562789da81eed
Electron 25.7.0
Chrome 114.0.5735.289
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.1.1-nightly.2024.5.28 Chrome/114.0.5735.289 Electron/25.7.0 Safari/537.36

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix #10111
  - Wrap text when the commit hash is too long

### Important Notes
None

### Screenshots
Before:
image

After:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

File: app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ const MODAL_STYLES = twv.tv({
 
 const DIALOG_STYLES = twv.tv({
   extend: variants.DIALOG_STYLES,
-  base: '',
+  base: 'text-xs text-primary',
```
Comment (MrFlashAccount) [inline app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: What's the purpose of making Dialog opinionated on the text size/color?

**Review by MrFlashAccount — APPROVED** [review]

File: app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx (hunk 1 above)
Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: that's just the default size/color for the app. i assume this shouldn't be an issue in practice since it can be (or is) overridden by twMerge anyway right?

Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: i suppose the alternative is to add these two rules as default CSS for `.enso-dashboard` in `tailwind.css`?

Comment (MrFlashAccount) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: Not really, If it's default, then we probably should pull these classes up to the document level. Otherwise, it's strange if an element looks differently whether it's inside a dialog or not. Also, since our font letters are weirdly aligned inside a line, we had to use a custom(hacky, actually) approach to align the text in the grid(see: https://github.com/enso-org/enso/blob/develop/app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx#L38). 

Also note: since when we have the Text component, we no longer need to manually assign classes or something. Just instead of using `aria.Text` use `ariaComponents.Text`, or use TEXT_STYLES: https://github.com/enso-org/enso/pull/10087/files#diff-b2bf8fd6a3d76eb3615adda79e6a8d40d3e9dc3fd92d706aa2f24a9adda5377aR15

All in all, I think it's not a good idea to specify font size/color on a Dialog level.

(Small note - all texts have `text-primary/60` color)

In your scenario, it's best to either specify the text-size/color on the table level or use `ariaComponents.Text`

**Comment by MrFlashAccount** [comment]
Sorry I removed the `ready to merge` label

File: app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx (hunk 1 above)
Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: > hacky approach

not sure this is needed - usually text uses `leading-snug` which follows the figma's approach to aligning the text

Comment (MrFlashAccount) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: > i suppose the alternative is to add these two rules as default CSS for .enso-dashboard in tailwind.css?

Yeah, probably, though this won't be a one-size-fits-all solution, because we still need to use TEXT_STYLES to properly align text in grid, see screenshot attached.

image

Comment (somebody1234) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: > all texts have `text-primary/60` color

note that `text-primary/60` *is* `text-primary`.

**Comment by somebody1234** [comment]
(assuming it's now ready to merge for real. there may be remaining issues with text alignment but IMO is out of scope for this PR)

File: app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx (hunk 1 above)
Comment (MrFlashAccount) [reply app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx]: Oh missed that, Thanks!
