### PR TITLE
Checking ascribed expression types for existence

### LINKED ISSUE #6848: `x : Text` is valid syntax, but doesn't check runtime type of the expression
Following code shall compile, but then yield a runtime error:
```haskell
from Standard.Base import Text

main =
    x = 10
    y = x : Text
    y
```
however it doesn't even compile and produces strange syntax error:
```
t.enso[4:5-4:5]: Unused variable x.
Compiler encountered errors:
t.enso[5:5-5:10]: Syntax is not supported yet: qualifiedNameSegment.
t.enso[6:5-6:5]: The name `y` could not be found.
Aborting due to 2 errors and 1 warnings.
```
Related to #6682 and @radeusgd comment https://github.com/enso-org/enso/issues/6682#issuecomment-1547503369 to allow us to verify elements of types like `Vector Number`, etc.
```[tasklist]
### Tasks
- [x] Check conversions
- [x] When the type name is mistyped, generate a compilation error
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #6848 by:
- making sure type in `a:Xyz` exists or yielding an error otherwise
- making sure type in `a:Integer` is checked at runtime
- [simplifies conversions](https://github.com/enso-org/enso/pull/7796/files#r1322812082) by using these _inlined type check_ expressions 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 1]
```diff
@@ -621,10 +657,9 @@ public void andConversions() throws Exception {
           self.dict.mul self.value that.value
 
     compute (a : Plus & Mul) (b : Plus & Mul) =
-      add (x:Plus) (y:Plus) = x+y
-      p = add a b
+      p = a+b
       m = a*b
-      add p m
+      p:Plus + m:Plus
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:662]: Simplifies requesting conversions into desired types by using inline expressions `p:Plus` and `m:Plus`. Simpler than defining `add (x:Plus) (y:Plus)` method and requesting conversion of its arguments.

**Review by radeusgd — APPROVED** [review]

File: test/Tests/src/Semantic/Conversion_Spec.enso [hunk 2]
```diff
@@ -202,6 +212,19 @@ spec =
             to_6 (v : Number & Decimal & Integer) = v
             to_6 m . should_equal 1.5
 
+        Test.specify "Requesting Integer & Fool" <|
+            do_stuff (x : Integer & Fool) =
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Conversion_Spec.enso]: Copy of [test provided](https://github.com/enso-org/enso/pull/7769#pullrequestreview-1619920748) by @radeusgd with slight modifications using `x:Integer` to _hint the system_.

Implementing `==` for _multi value_ was a bit tricky - it is a method on `Any` and thus each value supports it. But at least the `==` and `to_text` work fine since 2bc7dd3 - the solution is to invoke all `Any` methods on the _multi value_ as a whole.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java [hunk 3]
```diff
@@ -55,6 +62,25 @@ Object doBigIntegerLong(EnsoBigInteger self, long that) {
     return self.asDouble() + that;
   }
 
+  @Specialization(guards = "isForeignNumber(iop, that)")
+  Object doInterop(
+      Object self,
+      TruffleObject that,
+      @CachedLibrary(limit = "3") InteropLibrary iop,
+      @Cached AddNode delegate) {
+    try {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java]: I will have to add this code into all arithmetic nodes, so @Akirathan, @hubertp & co. please review if [dad0fb1](https://github.com/enso-org/enso/pull/7796/commits/dad0fb1348fae7659c86298ef9aee136d5d4711b) is OK.

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 4]
```diff
@@ -1009,8 +1012,20 @@ class IrToTruffle(
...
+        case _: Expression.Binding =>
+        case _ =>
+          val types = ir.getMetadata(TypeSignatures)
+          if (types.isDefined) {
+            val checkNode = extractAscribedType(null, types.get.signature);
+            if (checkNode != null) {
+              runtimeExpression =
+                ReadArgumentCheckNode.wrap(runtimeExpression, checkNode)
+            }
+          }
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]:
```suggestion
          types.foreach { tpe =>
            val checkNode = extractAscribedType(null, tpe.signature);
            if (checkNode != null) {
              runtimeExpression =
                ReadArgumentCheckNode.wrap(runtimeExpression, checkNode)
            }
          }
```

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java [hunk 5]
```diff
@@ -55,6 +62,25 @@ Object doBigIntegerLong(EnsoBigInteger self, long that) {
...
+      if (iop.fitsInLong(that)) {
+        return delegate.execute(self, iop.asLong(that));
+      } else if (iop.fitsInDouble(that)) {
+        return delegate.execute(self, iop.asDouble(that));
+      } else if (iop.fitsInBigInteger(that)) {
+        return delegate.execute(self, new EnsoBigInteger(iop.asBigInteger(that)));
+      }
+    } catch (UnsupportedMessageException ex) {
+    }
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java]: Shouldn't ignore the exception

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java [hunk 6]
```diff
@@ -82,12 +375,17 @@ public final Object castTo(Type type) {
...
       MethodResolverNode node, UnresolvedSymbol symbol) {
+    var ctx = EnsoContext.get(node);
+    Pair<Function, Type> foundAnyMethod = null;
     for (Type t : types) {
-      var fn = node.execute(t, symbol);
-      if (fn != null) {
-        return Pair.create(fn, t);
+      var fnAndType = node.execute(t, symbol);
+      if (fnAndType != null) {
+        if (fnAndType.getRight() != ctx.getBuiltins().any()) {
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java:383]: So this is the only reason why we introduce the `Pair`?
I vaguely remember having a need for such info as well when dealing with `hasWarning` for `Any`. Maybe `resolveWarningFunction` could be simplified now?

**Review by hubertp — APPROVED** [review]
nits

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java]: It isn't ignored (that much). It then calls into `doOther` which yields an exception.

File: engine/runtime/src/test/java/org/enso/interpreter/test/NumbersTest.java [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+import org.junit.AfterClass;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.fail;
+import org.junit.BeforeClass;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.junit.runners.Parameterized;
+
+@RunWith(Parameterized.class)
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/NumbersTest.java]: @Akirathan, originally I was using `@Theories`, but after reading this [stackoverflow post](https://stackoverflow.com/questions/8779982/why-does-junit-run-test-cases-for-theory-only-until-the-first-failure):
> A Theory is wrong if a single test in it is wrong, according to the definition of a Theory. If your test cases don't follow this rule, it would be wrong to call them a "Theory".

and after realizing _theories_ are in `experimental` package, I [decided to switch to @Parametrized](https://github.com/enso-org/enso/pull/7796/commits/0ab53f9534ba1dea2485d74d2c904d56d6ed5845). The way to specify `parameters()` isn't as nice as in case of theories, but unlike the [academical theory activists](https://stackoverflow.com/a/13754931) I believe running all the test is what real developers want. I seem to like proper error reports more then purity.

Don't you want to migrate to `@Parametrized` too?

File: engine/runtime/src/test/java/org/enso/interpreter/test/NumbersTest.java [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+    " +", " -", " ^", " *", " %", " <=", " <", " >=", " >", " /",
+    ".div", ".bit_xor", ".bit_shift", ".bit_shift_r", ".bit_or", ".bit_and"
+  };
+
+  @Parameterized.Parameters(name="({1}){0} ({2})")
+  public static Object[][] parameters() {
+    var r = new Random();
+    var ops = Arrays.asList(OPERATIONS).stream().map(
+      (op) -> new Object[] { op, r.nextLong(), switch (op) {
+        case " ^" -> r.nextLong(10);
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/NumbersTest.java]: It is a bit dangerous to let the right hand side argument of `^` to be `Long.MAX_VALUE` ;-)

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java (hunk 6 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java:383]: I did a bit of cleanup in 8954f5c921- now sure how much simplification is that, but one method is gone.

**Comment by JaroslavTulach** [comment]
I tried to update documentation, but this [types document](https://github.com/enso-org/enso/blob/04a1d14fc5b37af2fc7f5892387124fb72fa06d1/docs/types/hierarchy.md) is just completely off:

> Enso is a statically typed language

;-)

> Atoms are the fundamental building blocks

`atom` is no longer a keyword. And so on, so on... This is my small [documentation update](https://github.com/enso-org/enso/pull/7796/commits/04a1d14fc5b37af2fc7f5892387124fb72fa06d1).
