### PR TITLE
Reverse order of stack frames and test the result

### LINKED ISSUE #9934: Stack trace when Enso script finishes with a Panic is upside down
Try running the following example file:
```
from Standard.Base import all

a = b
b = c
c = Panic.throw "foo"

main = a
```

### Actual behaviour

```
Execution finished with an error: foo
        at <enso> stack-test.main(stack-test.enso:7:8-8)
        at <enso> stack-test.a(stack-test.enso:3:5-5)
        at <enso> stack-test.b(stack-test.enso:4:5-5)
        at <enso> stack-test.c(stack-test.enso:5:5-21)
        at <enso> Panic.throw(Internal)
```

### Expected behaviour

The panic-throw location should be at the top of the trace, the order should be reversed.

```
Execution finished with an error: foo
        at <enso> Panic.throw(Internal)
        at <enso> stack-test.c(stack-test.enso:5:5-21)
        at <enso> stack-test.b(stack-test.enso:4:5-5)
        at <enso> stack-test.a(stack-test.enso:3:5-5)
        at <enso> stack-test.main(stack-test.enso:7:8-8)
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #9934 by reversing the order of `dropInitJava` frames.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runner/src/main/java/org/enso/runner/Utils.java [hunk 1]
```diff
@@ -66,4 +73,86 @@ static scala.Tuple3<Boolean, File, String> findFileAndProject(String path, Strin
...
+    for (var e : stack) {
+      fullStackReversed.addFirst(e);
+    }
+
+    var dropInitJava =
+        new ArrayList<S>(
+            fullStackReversed.stream()
+                .dropWhile(f -> !LanguageInfo.ID.equals(fnLangId.apply(f)))
+                .toList());
+    Collections.reverse(dropInitJava);
```
Comment (JaroslavTulach) [inline engine/runner/src/main/java/org/enso/runner/Utils.java:97]: This is the changed line. The rest is just a refactoring to make things testable.

**Review by Akirathan — APPROVED** [review]

**Review by somebody1234 — APPROVED** [review]

**Review by MrFlashAccount — APPROVED** [review]
