### PR TITLE
Avoid SVM `Deoptimizer.rewriteStackStub` crash

### LINKED ISSUE #14719: Crash in `Deoptimizer.rewriteStackStub`
- c3abdec33d02b17622478fef0f88eb29c342480e (e.g. `2026.1.1-nightly.2026.2.3`+) crashed in `Deoptimizer.rewriteStackStub` on Windows
   - this version is using GraalVM 25.0.1
   - it contains the revert #14687
   - yet the failure looks the same as the one we were observing on the 2025.3.3 release branch
- happens with the IDE after 10-15 minutes of usage

after the crash

### Steps to Reproduce

**With debug symbols:**
- Install the nightly GUI.
- Download and extract the debug Native Image from https://drive.google.com/file/d/1CJ4EHY6vsERj0v-_pUqX6bZd0PPVaqrp/view?usp=drive_link
- Set an environment variable of "ENSO_ENGINE_PATH" set to the `enso.exe` within the extracted zip file.

- open project - an example project: [Read SelectFields from YXMD Tool.zip](https://github.com/user-attachments/files/25053016/Read.SelectFields.from.YXMD.Tool.zip)
  - [challenge_234_jd.zip](https://github.com/user-attachments/files/25053062/challenge_234_jd.zip)
  - **Note this is not believed to be particularly relevant.**
- use for 10-15 minutes, editing and changing xpath and adding/removing components
- observe the crash

### Logs & Dumps

- dump of a sample crash can be [_"downloaded here"_](https://drive.google.com/file/d/1Jk562hrVsUo6N2KmjhyhHTfXScLGh7Tf/view?usp=sharing)
   - open it in visual studio community or pro
- logs of a crash are [_"downloadable here"_](https://drive.google.com/file/d/1a3TKcTYYpRXQS9ZxGLFfm6lxKG9nXe32/view?usp=sharing)

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- `ScheduledThreadPoolExecutor..allowCoreThreadTimeOut` allows the _guest code_ thread to terminate when idle
- new one is then started when another request arrives
- looks like GraalVM 25.0.1 for Windows has problems with such an approach
- keep the thread(s) running once started

### Hypothesis

- the `release/2025.3` branch and especially [2025.3.1](https://github.com/enso-org/enso/releases/tag/2025.3.1) is known to be **good**
- the branch point `2025.3.1-nightly.2025.12.1` is **bad**
- the issue has been fixed in this range: https://github.com/enso-org/enso/compare/2025.3.1-nightly.2025.12.1...2025.3.1 
- hypothesis: #14516 is the fix

### Process of Bisecting

- this PR starts at **bad** `2025.3.1-nightly.2025.12.1` and backports f235fff3bbd60e14a1f0a22d42674875b6075608
   - [nightly build](https://github.com/enso-org/enso/actions/runs/22100079118) should be **good** if #14516 is really the fix!
   - **good** according to @jdunkerley 
- 303398d105779b2da6f25deab2da760162ed74a1 merges with `2026.1.1-nightly.2026.1.1`
   - [nightly build](https://github.com/enso-org/enso/actions/runs/22105428205) scheduled.
   - **good** according to @jdunkerley 
- bb1324f9ca3e5f4eaa5bb33a858cbdd64f72554f merges with `2026.1.1-nightly.2026.2.1` 
   - [nightly build](https://github.com/enso-org/enso/actions/runs/22170394564) scheduled
   - **good** according to @jdunkerley
- final check at 7ad00f40e32380a379220995edc63c175b725ec3 after merging with `2026.1.1-nightly.2026.2.18`
   - [nightly release](https://github.com/enso-org/enso/actions/runs/22189806791) scheduled
   - Seems **good**!

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java [hunk 1]
```diff
@@ -41,8 +41,7 @@ ExecutorService newCachedThreadPool(
   }
 
   ScheduledExecutorService newScheduledThreadPool(int cnt, String name, boolean systemThread) {
-    var s = new ScheduledThreadPoolExecutor(cnt, new Factory(name, systemThread));
-    s.allowCoreThreadTimeOut(true);
+    var s = Executors.newScheduledThreadPool(cnt, new Factory(name, systemThread));
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java:44]: @hubertp wrote:

> I imagine we could be having deadlocks with this change? Safepoints don't like parked threads...

That's correct! I guess the most important goal right now is to eliminate the Windows crash, but ...

> ...if we increase guest parallelism...

then using `Executors.newScheduledThreadPool` is probably not an option as @hubertp points out!

**Comment by jdunkerley** [comment]
Used the newest version all day without an issue on Windows.

**Review by jdunkerley — APPROVED** [review]

**Review by AdRiley — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]
