### PR TITLE
Ensure Table Visualisation is the Default Visualization for Tables

### LINKED ISSUE #5033: Table Vis is not the default visualization for Tables
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184267396).
<hr />

### Steps to reproduce
1. Newly create a node that has type “Table” or "Vector"
2. Open the visualization.

### Expected
The visualization opened should be a table visualization. 

### Actual
The visualization shown is a text visualization.

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description

Adds a mechanism for the GUI to choose an appropriate default visualization for a newly created node. 

https://user-images.githubusercontent.com/1428930/216641714-2410d2c9-44d2-45f0-856d-1f995421c94b.mp4

### Important Notes
This is a workaround for [missing functionality](https://www.pivotaltracker.com/story/show/184390437) that would take much longer to implement. 

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ loadStyleFromString(scrollbarStyle)
 // ===========================
 
 class TableVisualization extends Visualization {
-    static inputType = 'Any'
+    static inputType = 'Standard.Table.Data.Table.Table'
```
Comment (JaroslavTulach) [inline app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: > Unit tests have been written where possible.

Is there a test to fail if the `Table` type is renamed? Types get renamed quite frequently in the stdlib and I'd be sad to see this functionality stop working without a warning/failing test.

**Review by JaroslavTulach — APPROVED** [review]
Yup, having tables on by default will make life of everyone way easier.

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js (hunk 1 above)
Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: > > Unit tests have been written where possible.
> 
> Is there a test to fail if the `Table` type is renamed? Types get renamed quite frequently in the stdlib and I'd be sad to see this functionality stop working without a warning/failing test.

That is a good point. But I am somewhat unsure how to do this, as we don't currently have working integration tests.
Do you think it would be sensible to put in a test in the standard library that checks the name of the type of `Table` and says something like "If you need to change this test, also update `visualization/java_script/table.js:14`? "

File: app/gui/view/graph-editor/src/component/visualization/container.rs [hunk 2]
```diff
@@ -449,7 +449,8 @@ impl ContainerModel {
                 vis_list.iter().skip_while(|x| vis.signature.path != x.signature.path);
             from_current.nth(1)
         });
-        next_on_list.or_else(|| vis_list.first()).cloned()
+        let result = next_on_list.or_else(|| vis_list.first()).cloned();
+        result
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/container.rs]: Return directly. Linter should complain about it.

File: app/gui/view/graph-editor/src/component/visualization/registry.rs [hunk 3]
```diff
@@ -76,6 +76,19 @@ impl Registry {
...
 
+    /// Return the `visualization::Definition` that should be used as default for the given type.
+    pub fn default_visualization_for_type(
+        &self,
+        tp: &enso::Type,
+    ) -> Option<visualization::Definition> {
+        // Visualisations are order by "matching the type" first, followed by and then "matching any
+        // type". So we just take the first one, which should be the most appropriate one.
+        // This should be replaced with the proper solution described in
+        // https://www.pivotaltracker.com/story/show/184390437
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/component/visualization/registry.rs]: Please add TODO mark in this comment.

**Review by farmaazon — APPROVED** [review]

File: app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js (hunk 1 above)
Comment (radeusgd) [inline app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: I tried building the IDE to verify this, but after wasting a lot of time I'm still having some troubles using the new build script on Windows (I will try figure this out in due course).

In the meantime, I have a hunch (the one I wanted to verify before posting, but got impatient): if we specify the inputType of visualization to be `Standard.Table.Data.Table.Table`, will the Table visualization even **show at all** for Database Tables whose type is `Standard.Database.Data.Table.Table`? I think it is important to not break the Table visualization on the Database module and would consider breaking it as a regression.

I'm not sure if this PR causes it (as I was unable to verify empirically), but looking at the code I'm afraid it may.

btw. cc @jdunkerley I think this is another argument for why we should migrate towards a single _facade_ Table type that will only then delegate to the proper backend (be it DB backend or in-memory) under the hood. Having one Table type instead of 2 (or more) will be much better. Will probably be worth doing as part of the SQL IR improvements.

For now though, it would be good to ensure if we can keep the Table visualization on Database Tables too. Can we use sum types in `inputType`?

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: While this is only a temporary solution until such time as we have the method calling `default_visualization`, @radeusgd is correct we need this on a few more types. Could we make the inputType an array of types instead of a single value?

For now, Table viz should be the default for Vector, Array, In Memory Column and In Memory Table.
And SQL should be the default for Database Column and Database Table.

We are **very** likely to increase this list over the next few days (I want to name Map and JS Object for example default to the Table) so this mechanism is critical assuming that #5195 will not be completed for a while.

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: @radeusgd - I don't think the facade type has anything to do here. 

And at least so far attempts to use such a type within Enso have been annoying. I tried this for the database connection type with a facade calling onto a backing true connection but the approach was very unpleasant and didn't work well. Either way, a discussion for a different space.

Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: There can be any number of types, but there is one limitation: the matching is done on the name as a string. The only special handling is done for `Any`. So I can add that back in to ensure this stays usable for all types. And I can add more types for which it makes sense for this to be the default.

So the list of types to add is

* `Standard.Database.Data.Table.Table`
* `Vector`
* `Array`
* `In Memory Column`
*  `In Memory Table`

Any other ones that come to mind? @jdunkerley @radeusgd

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: yes please. For the first pass:

Table:
- `Standard.Base.Data.Vector.Vector`
- `Standard.Base.Data.Array.Array`
- `Standard.Table.Data.Table.Table`
- `Standard.Table.Data.Column.Column`

and lets make SQL viz the default for:
- `Standard.Database.Data.Table.Table`
- `Standard.Database.Data.Column.Column`

We can then hopefully easily add to this as we need later on. (ideally without bugging your team!)

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: @MichaelMauderer / @farmaazon  is #5195 planned for the release?

Comment (radeusgd) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: I'd just like to ensure that while for
- `Standard.Database.Data.Table.Table`
- `Standard.Database.Data.Column.Column`
we have the SQL visualization as the default, the `Table` visualization should still be available to choose for these types.

Comment (jdunkerley) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: yes the Table viz should definitely be available for it.

Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: > 



> Table:
> 
>     * `Standard.Base.Data.Vector.Vector`
> 
>     * `Standard.Base.Data.Array.Array`
> 
>     * `Standard.Table.Data.Table.Table`
> 
>     * `Standard.Table.Data.Column.Column`
All added. 


> and lets make SQL viz the default for:
> 
>     * `Standard.Database.Data.Table.Table`
> 
>     * `Standard.Database.Data.Column.Column`

Already seem to be defined as the input for SQL vis, so they should have it as default now.

Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: > @MichaelMauderer / @farmaazon is #5195 planned for the release?

I don't think it is. @farmaazon ?

Comment (MichaelMauderer) [reply app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js]: > I'd just like to ensure that while for
> 
>     * `Standard.Database.Data.Table.Table`
> 
>     * `Standard.Database.Data.Column.Column`
>       we have the SQL visualization as the default, the `Table` visualization should still be available to choose for these types.

I've re-added “Any” to Table Vis can be chosen for every node. This might be the best compromise here until we get the proper system.

**Review by jdunkerley — APPROVED** [review]
This is a great step forward. Thanks for getting this in place.
