### PR TITLE
Fix missing AWS region in S3 operations

### LINKED ISSUE #9284: Missing region in AWS setup (e.g. datalink)
I have noticed that because I've created a datalink to an S3 file, containing my AWS key credentials. So I should be able to read this datalink without setting up any additional credentials on my machine, right? Because the credentials are inside of the datalink itself.

Well, unfortunately - this uncovered that something is missing.
Reading the datalink I get:
```
(Error: (AWS_SDK_Error.Error 'Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@7a79a5d6: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@22decfa2: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@4d50f682: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@1315d910: Unable to contact EC2 metadata service.]'))
```

- [x] We need an ability to set region for all of our AWS operations (not only the datalinks). 
  - I think it will be easiest to keep it part of the `AWS_Credential` although we could make it a separate property as well.
- [x] We should change our test setup. 
  - By setting the default AWS environment variables on the CI, our tests run in a special environment. Our users may not have these environment variables set up, or they can point to different data. Tests need to be independent of that and ensure that e.g. the S3 data link has all the information needed to access the file and does not depend on user setup.
  - Let's rename the env vars to `ENSO_AWS_*` prefix, so that AWS tooling does not pick them up automatically. Then we can manually set up our `AWS_Credential` for use in the tests.
  - This will prove some difficulty with testing the `AWS_Credential.Default` variant.

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Closes #9284
- Now our tests run without the default `AWS_` config, thus ensuring that the tested setups work in a clean environment.
- After all, more complicated logic was needed for buckets access - apparently the AWS SDK only allows for some operations on buckets to happen if the client is connected to the correct region. Thus detection of bucket regions had to be implemented.
- Added `AWS_Region` widget based on autoscoping.
- Fixed `AWS_Credential.profile_names` crashing if no AWS config was found. Now it returns no profiles if not found. Added a regression test.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by mwu-tow — APPROVED** [review]

File: std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+      }
+
+      var inferredRegion = Region.of(locationConstraint.toString());
+      boolean isKnown = Region.regions().contains(inferredRegion);
+      if (isKnown) {
+        return inferredRegion;
+      } else {
+        Logger.getLogger("S3-BucketLocator").fine("AWS returned a location constraint that cannot be mapped to a known region: " + locationConstraint);
+        return null;
+      }
```
Comment (radeusgd) [inline std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java]: It seems that sometimes `getBucketLocation` may not be able to find out the true bucket location.

In such case, we will fall back to the region set in credentials which seems our best bet - as the user can always amend that region to be right. If the region is wrong, the user will be getting failures like: `The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.` (message coming from AWS SDK)

**Review by somebody1234 — APPROVED** [review]
We should probably remove the `index.html` symlink that points to a nonexistent file (causing issues when formatting)

File: std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java (hunk 1 above)
Comment (radeusgd) [reply std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java]: The AWS docs [seem to suggest using `HeadBucket` instead of `GetBucketLocation`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html#:~:text=We%20recommend%20that%20you%20use%20HeadBucket%20to%20return%20the%20Region%20that%20a%20bucket%20resides%20in.%20For%20backward%20compatibility%2C%20Amazon%20S3%20continues%20to%20support%20GetBucketLocation) but I could not get it to work, because ironically `HeadBucket` fails with the above error:
```
((S3_Error.Error 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.' 'PermanentRedirect'))
```
even on the same configuration that allows `GetBucketLocation` to work...


<details>
<summary>The patch was</summary>

```diff
Index: std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java b/std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java
--- a/std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java	(revision fc80d4d118f4e2797a281b95ba96ffae68afe26a)
+++ b/std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java	(date 1711457551132)
@@ -1,9 +1,10 @@
 package org.enso.aws;
 
 import software.amazon.awssdk.regions.Region;
-import software.amazon.awssdk.services.s3.model.BucketLocationConstraint;
+import software.amazon.awssdk.services.s3.model.HeadBucketResponse;
 
 import java.util.HashMap;
+import java.util.Optional;
 import java.util.logging.Logger;
 
 /**
@@ -35,25 +36,9 @@
     DefaultRegionProvider defaultRegionProvider = new DefaultRegionProvider(null, Region.US_EAST_1);
     var clientBuilder = new ClientBuilder(associatedCredential, defaultRegionProvider.getRegion());
     try (var client = clientBuilder.buildGlobalS3Client()) {
-      BucketLocationConstraint locationConstraint = client.getBucketLocation(builder -> builder.bucket(bucketName)).locationConstraint();
-      if (locationConstraint == null) {
-        // Weird edge case: documentation says that buckets in region us-east-1 return null
-        return Region.US_EAST_1;
-      }
-
-      if (locationConstraint == BucketLocationConstraint.UNKNOWN_TO_SDK_VERSION) {
-        Logger.getLogger("S3-BucketLocator").fine("AWS returned an unknown location constraint.");
-        return null;
-      }
-
-      var inferredRegion = Region.of(locationConstraint.toString());
-      boolean isKnown = Region.regions().contains(inferredRegion);
-      if (isKnown) {
-        return inferredRegion;
-      } else {
-        Logger.getLogger("S3-BucketLocator").fine("AWS returned a location constraint that cannot be mapped to a known region: " + locationConstraint);
-        return null;
-      }
+      HeadBucketResponse response = client.headBucket(builder -> builder.bucket(bucketName));
+      Optional<String> regionId = response.sdkHttpResponse().firstMatchingHeader("x-amz-bucket-region");
+      return regionId.map(Region::of).orElse(null);
     } catch (Exception e) {
       Logger.getLogger("S3-BucketLocator").fine("Failed to locate bucket " + bucketName + ": " + e.getMessage());
       return null;
```


</details>

**Review by GregoryTravis — APPROVED** [review]

**Comment by radeusgd** [comment]
After troubles with the AWS_Region widget, I went for using autoscoping and it seems to work :)

image

File: std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java (hunk 1 above)
Comment (radeusgd) [reply std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java]: After all I figured out we can extract the region from the `S3Exception` that happens when `HeadBucket` fails, so I switched to this strategy.

I thought to keep the legacy strategy as a fallback just in case - if the headers ever disappear from the exception for example.

Comment (radeusgd) [reply std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java]: OTOH I'm wondering if that's not introducing unnecessary maintenance burden.

What do you'all think? Shall I keep the fallback, or shall we remove it, knowing that we can add it if we ever run into issues with the current way of fetching regions?

File: distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso [hunk 2]
```diff
@@ -23,16 +27,68 @@ type AWS_Credential
...
 
+    ## PRIVATE
+       Allows to override additional properties of the AWS credential.
+
+       Arguments:
+       - base_credential: The base credential to use. It should be one of:
+         Default, Profile, Key.
+       - default_region: The default region to use for operations that may
+         require a region but it is not explicitly specified (e.g. S3 operations).
+    With_Advanced_Properties (base_credential : AWS_Credential) (default_region : AWS_Region)
```
Comment (jdunkerley) [inline distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso]:
```suggestion
    With_Configuration (base_credential : AWS_Credential) (default_region : AWS_Region)
```

AWS calls it `config` in the profile?

File: std-bits/aws/src/main/java/org/enso/aws/ClientBuilder.java [hunk 3]
```diff
@@ -1,32 +1,60 @@
...
+import java.net.URI;
+import java.util.function.Supplier;
 import org.enso.base.enso_cloud.ExternalLibrarySecretHelper;
 import org.enso.base.enso_cloud.HideableValue;
-import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
-import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
-import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
-import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider;
-import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
+import software.amazon.awssdk.auth.credentials.*;
```
Comment (jdunkerley) [inline std-bits/aws/src/main/java/org/enso/aws/ClientBuilder.java]: can we avoid the * import.

**Review by jdunkerley — APPROVED** [review]
Looks good - couple of minor suggestions.

File: std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java (hunk 1 above)
Comment (jdunkerley) [reply std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java]: I don't think any harm leaving the fallback - my guess is it will never be fired but not a big burden and nice to have the fallback if response format changes.
