### PR TITLE
Stable order for filtered components

### LINKED ISSUE #7591: No-filter component order inconsistent with matched-filter order
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The order of elements in the Component Browser when a filter is applied is not consistent with the order without a filter. Without a filter, the best match is `Data.read`. However, if I type `read`, the best match for that is `File_Access.Read`.

### Expected behaviour

Typing `read` shouldn't replace `Data.read` with a different best match. We could avoid this kind of inconsistency by using the no-filter sort key to break ties between components with the same match score.

### How we can reproduce it?

1. Press `Enter` to create a node; the suggested component is `Data.read`.
2. Type `read`; a different fuzzy match of equal match quality is suggested, such as `File_Access.read`.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #7591 

https://github.com/enso-org/enso/assets/6566674/ddde9f3a-cff8-4c15-a0fe-b7468c917b6a

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/controller/searcher/component/builder.rs [hunk 1]
```diff
@@ -200,6 +200,9 @@ impl<'a> Builder<'a> {
             .displayed_by_default
             .sort_by(|lhs, rhs| ComponentOrderingKey::of(lhs).cmp(&ComponentOrderingKey::of(rhs)));
         self.built_list
+            .components
+            .sort_by(|lhs, rhs| ComponentOrderingKey::of(lhs).cmp(&ComponentOrderingKey::of(rhs)));
+        self.built_list
```
Comment (farmaazon) [inline app/gui/src/controller/searcher/component/builder.rs:205]: It's not enough, unfortunately.

The `components` list is re-sorted every time the filtering changes. The sort is stable, so we can rely on this in a single case, but when some filtering will reorder elements (because their score will differ), then this new order will be preserved on each other filter.

As example: we can have two entries: [`foo_foobar`, `foo_foobaz`]. For `foo` pattern they have same score, so their order is remains. But then if user add 'baz', their order changes, as foobaz is no longer matched (and unmatched elements are put at the end).

It's a rare scenario, however, so anyway this PR improves a state of things.

**Review by farmaazon — APPROVED** [review]

File: app/gui/src/controller/searcher/component/builder.rs (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/controller/searcher/component/builder.rs:205]: Nice catch, you're right. It can only be solved by storing the original components list separately and never sorting it. It is both inefficient and requires substantial refactoring to do things in the right way.

**Comment by vitvakatu** [comment]
I also fixed the issue with the non-alphabetical sorting of entries in the last commit.

Before:
image

After:
Screenshot 2023-09-14 at 5 30 15 PM

(`delete_rows` has no group assigned, hence its order)

**Comment by farmaazon** [comment]
> I also fixed the issue with the non-alphabetical sorting of entries in the last commit.

If requested by @jdunkerley then ok, but I want to point out that this is not as in the design: https://github.com/enso-org/design/blob/main/epics/component-browser/design2.md#order-of-results-when-no-nodes-are-selected-and-no-query-has-been-provided-yet

The idea is that - if two entities are defined in the same module - the entity declared first will be below. This way the library author can decide what should be the top priority in the CB list.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.</div></blockquote>

Bringing attention of @wdanilo because it was his idea.

**Comment by jdunkerley** [comment]
Yes, this was what we had in the design. As the library name isn't shown, sortung alphabetically felt correct within a type.

Once we play with it more in anger, we might change this but that change would only be in the TS GUI.
