### PR TITLE
Ensure that IO.println does not fail if `to_text` returned a non-Text value.

### LINKED ISSUE #5961: IO.println: Type error: expected `str` to be Text, but got Function
I am trying to use `IO.println` to "debug" my #5956 program. However the `println` statement is causing my program to fail with:
```
Execution finished with an error: Type error: expected `str` to be Text, but got Function.
        at <enso> IO.println(Internal)
        at <enso> Function.<|(Internal)
```
It is not really productive when debugging of something turns into hunting for a reason why the debugging itself does not work. I believe the `IO.println` method should never fall and always print something.

The reproducer is:
```haskell
from Standard.Base import all
import Standard.Base

main = 
    raw = Vector.from_polyglot_array []
    IO.println <| (Meta.type_of raw).to_text
    IO.println <| (Meta.type_of raw)
    Meta.type_of raw
```

surprisingly the 1st `IO.println` statement succeeds and prints:
```
Vector.type.to_text[Vector.enso:601-1763]
```
however the second statement yields the exception `Type error: expected `str` to be Text, but got Function.`.

### PR DESCRIPTION
**Pull request by radeusgd**
Alternative fix for #5961 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java [hunk 1]
```diff
@@ -54,17 +55,37 @@ Object doPrint(
...
-    var str = invokeCallableNode.execute(symbol, frame, state, new Object[] {message});
+      @Cached("buildInvokeCallableNode()") InvokeCallableNode invokeCallableNode) {
+    Object probablyStr = invokeCallableNode.execute(symbol, frame, state, new Object[] {message});
+    if (warnings.hasWarnings(probablyStr)) {
+      try {
+        probablyStr = warnings.removeWarnings(probablyStr);
+      } catch (UnsupportedMessageException e) {
+        throw CompilerDirectives.shouldNotReachHere(e);
+      }
+    }
```
Comment (jdunkerley) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: we can do this with a specialization.

```
  @Specialization(guards = "warnings.hasWarnings(warning)")
```

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: I was thinking about it, but `probablyStr` is computed inside of the node, it's not an argument. So I'm not sure how to do that.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: With my understanding, I don't think creating specializations here is possible.

I need to actually compute the `invokeCallableNode` node and this is actually the _most costly_ part of this node. So this is a kind of computation that will run once a specialization is selected. But then, the specialization is already selected, so we cannot use result of that computation in the specialization selection criteria. Am I getting this right @JaroslavTulach ?

File: engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java [hunk 2]
```diff
@@ -0,0 +1,244 @@
...
+        to_text self = "MyObj{" + self.x.to_text + "}"
+
+    test =
+        a = My_Object
+        IO.println a
+    """;
+
+    checkPrint(code, "My_Object.type.to_text[test:6-16]");
+    // We would want the following result:
+    //checkPrint(code, "My_Object");
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: This is now being discussed here: https://github.com/orgs/enso-org/discussions/6216

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: That's correct. The guard doesn't have access to `probablyStr`. The proper way to make this fast-path ready would be to split the code into two nodes - one that extracts the `probablyStr` and another one that processes that. With the `probablyStr` being available, one could use it in the `guards` of the second node.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: But this is probably OK. `println` is I/O and I/O cannot be fast-path anyway...

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: I mean, I think regardless of the outcome of the discussion, in an ideal world, I would like `IO.println My_Type` to print `My_Type` (or some representation of the type, for example a qualified name) and definitely not a string-representation of a _function_. We may get there through different routes though, along with a special handling for types in `println` (but that would IMO be pushing the problem to a different place).

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: Still, better to get `My_Object.type.to_text[test:6-16]` than a Type Error 😁

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java (hunk 1 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java:68]: Note that this specialization will only be executed with `hasWarnings = true`, and I'm pretty sure that warnings are usually not fast-path either.

File: engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: > I would like `IO.println My_Type` to print `My_Type`

Easy. Add `@Specialization` for `Type` into `PrintlnNode`! Then there is no need to wait for a result of the above discussion.

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: Fair point, I will try to do it.

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: How can I add the `@Specialization` for `Type` so that it doesn't clash with:
```
  @Specialization(guards = "!strings.isString(message)")
  Object doPrint(
      VirtualFrame frame,
      State state,
      Object message,
```
?

`Type <: Object` so I need to somehow add to this specialization a condition that `message </: Type`, how do I do this in Truffle? Just `guards = "!(message instanceof Type)"`?

Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: I would add:
```java
@Specialization
Object doPrintTypeName(VirtualFrame frame, State state, Type message) {
...
}
```
and possibly expanded the `guards = { ...., "!(message instanceof Type)" }` as you propose

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: Ok, I will try that

**Review by jdunkerley — APPROVED** [review]

File: engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java (hunk 2 above)
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: After all it turned out to be a bit more complicated, and I think there's little sense in adding such a specific (and tbh not _that_ often used) specialization which just fixes a small part of the problem (it would fix `IO.println Type` but if I do `IO.println "Hello: "+Type.to_text` it would still be broken and I think the latter is used even more often).

The whole problem will be fixed anyway by #6300 which is scheduled to be done soon, so there is no sense in keeping a specialized fix for a small case (especially as I'd need a bit more time to get it right).

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java:242]: We just need to remember to update this test once #6300 is done.
