### PR TITLE
Display error message when viewed graph doesn't exist.

### LINKED ISSUE #11211: Grouped Components - Undoing node collapsing inside collapsed functions breaks graph editor
To reproduce:
1. Create a collapsed function.
2. Enter it
3. Press Undo (`⌘+Z`)
4. Observe broken graph editor and errors in console.

We discussed that we want to manage undos better (let's consider separate undo stacks for different graphs), but we also need to make sure the graph shows something reasonable when the function gets deleted.

https://github.com/user-attachments/assets/af5715d3-f56b-436c-8263-4ad572c5748b

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #11211

image

When the "go back" button is clicked, the user is sent back to the `main` function graph. The breadcrumbs are also present on that view and can be used for navigation.

Current design of the error state is improvised, likely to be changed once we have some design guidance about it.

### CODE REVIEW

File: app/gui/src/project-view/components/SvgButton.vue [hunk 1]
```diff
@@ -1,11 +1,12 @@
+f
```
Comment (vitvakatu) [inline app/gui/src/project-view/components/SvgButton.vue]: Missed typo

File: app/gui/src/project-view/components/StandaloneButton.vue [hunk 2]
```diff
@@ -0,0 +1,27 @@
+f
```
Comment (kazcw) [inline app/gui/src/project-view/components/StandaloneButton.vue]: Typo

File: app/gui/src/project-view/components/GraphMissingView.vue [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+function goToMain() {
+  project.executionContext.desiredStack = [project.executionContext.getStackBottom()]
+}
+</script>
+
+<template>
+  <div class="GraphMissingView">
+    <SvgIcon class="header-icon" name="error" />
+    <span>This component You are viewing no longer exists.</span>
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphMissingView.vue]:
```suggestion
    <span>The component you are viewing no longer exists.</span>
```

**Review by kazcw — APPROVED** [review]
