### PR TITLE
Fix crash when editing certain names in the CB

### LINKED ISSUE #6119: IDE freezes when selecting certain expression
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

At some point, I accidentally ended up with the following, ill-formed expression: `operator16.map (match -> [Integer.parse(_.join .group 1, match.group 2])`. Upon selecting `_.join` to turn it back to `match`, the whole window froze.

freeze

The logs had these two panics:
```
IPC error:

panicked at 'size is zero', /rustc/1e4f90061cc4bc566f99ab21b1f101182b10cf0c/library/core/src/slice/mod.rs:787:44

Stack:

Error
    at eval (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17793:19)
    at logError (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:16936:14)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17792:12)
    at console_error_panic_hook::Error::new::h089d5da412a450cc (http://localhost:8080/pkg-opt.wasm:wasm-function[413696]:0x4d554b8)
    at console_error_panic_hook::format_panic_impl::h81fa303ff68f5b78 (http://localhost:8080/pkg-opt.wasm:wasm-function[84922]:0x2d2b40e)
    at console_error_panic_hook::format_panic::hd347a3ec156114f0 (http://localhost:8080/pkg-opt.wasm:wasm-function[472960]:0x4e34e2d)
    at enso_web::report_panic::he0fbc91535466bec (http://localhost:8080/pkg-opt.wasm:wasm-function[19435]:0x1966046)
    at core::ops::function::Fn::call::he49ee373b556e9fa (http://localhost:8080/pkg-opt.wasm:wasm-function[329181]:0x4a8bd7f)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8080/pkg-opt.wasm:wasm-function[92656]:0x2ec0cfe)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8080/pkg-opt.wasm:wasm-function[150424]:0x39030af)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8080/pkg-opt.wasm:wasm-function[339591]:0x4b146ce)
    at rust_begin_unwind (http://localhost:8080/pkg-opt.wasm:wasm-function[280314]:0x4750909)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8080/pkg-opt.wasm:wasm-function[330758]:0x4aa3011)
    at core::panicking::panic_display::hf1bfbeab90bf4dd7 (http://localhost:8080/pkg-opt.wasm:wasm-function[285536]:0x47b9553)
    at core::panicking::panic_str::hacb805faa711b6b7 (http://localhost:8080/pkg-opt.wasm:wasm-function[344228]:0x4b461cf)
    at core::option::expect_failed::h46dbf58c483f9509 (http://localhost:8080/pkg-opt.wasm:wasm-function[465317]:0x4e1b2c8)
    at core::slice::<impl [T]>::windows::h582338afe761bc3b (http://localhost:8080/pkg-opt.wasm:wasm-function[142598]:0x37d0cd0)
    at enso_gui::controller::searcher::input::InsertContext::segments_to_replace::h07d4561afbe1bc74 (http://localhost:8080/pkg-opt.wasm:wasm-function[823]:0x460ce8)
    at enso_gui::controller::searcher::input::InsertContext::code_to_insert::h2ccbe856757f5d63 (http://localhost:8080/pkg-opt.wasm:wasm-function[2548]:0x9f9a09)
    at enso_gui::controller::searcher::input::Input::after_inserting_suggestion::h4dcb225cd4990688 (http://localhost:8080/pkg-opt.wasm:wasm-function[1877]:0x842433)
    at enso_gui::controller::searcher::Searcher::preview_suggestion::hb0c5b84763d851cd (http://localhost:8080/pkg-opt.wasm:wasm-function[1689]:0x7ab098)
    at enso_gui::presenter::searcher::Model::suggestion_selected::h4c31de41244538d8 (http://localhost:8080/pkg-opt.wasm:wasm-function[2651]:0xa33c93)
    at enso_gui::presenter::searcher::Searcher::new::{{closure}}::h2e53db33f874db52 (http://localhost:8080/pkg-opt.wasm:wasm-function[199373]:0x3f810b2)
    at enso_frp::nodes::<impl enso_frp::network::Network>::map_::{{closure}}::h7384e1c67db98df2 (http://localhost:8080/pkg-opt.wasm:wasm-function[313352]:0x499e07b)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::MapData<T,F>>>::on_event::h22170f25879c26f0 (http://localhost:8080/pkg-opt.wasm:wasm-function[249665]:0x449e2cc)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::hefd081aedee12c89 (http://localhost:8080/pkg-opt.wasm:wasm-function[182718]:0x3d83cf1)
    at core::option::Option<T>::map::h338839171636fef7 (http://localhost:8080/pkg-opt.wasm:wasm-function[71850]:0x2a49420)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h8a0c540f7ecd61f3 (http://localhost:8080/pkg-opt.wasm:wasm-function[136143]:0x36c59f2)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h1948a6fae58be9dc (http://localhost:8080/pkg-opt.wasm:wasm-function[1220]:0x5f24b3)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h43623d1fcc482040 (http://localhost:8080/pkg-opt.wasm:wasm-function[371241]:0x4c3927b)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h9cb32c16d8202f4a (http://localhost:8080/pkg-opt.wasm:wasm-function[419859]:0x4d702de)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::FilterMapData<T,F>>>::on_event::h5c2c5235b7208bee (http://localhost:8080/pkg-opt.wasm:wasm-function[26444]:0x1c9df3f)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h373baac1287d3dbe (http://localhost:8080/pkg-opt.wasm:wasm-function[182614]:0x3d808f2)
    at core::option::Option<T>::map::hd1ed01451b291ce9 (http://localhost:8080/pkg-opt.wasm:wasm-function[71949]:0x2a4ef01)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h2cc6a4f504bd70c0 (http://localhost:8080/pkg-opt.wasm:wasm-function[136092]:0x36c3814)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hd15fcb1afdc2430c (http://localhost:8080/pkg-opt.wasm:wasm-function[1071]:0x55e8cc)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hbf39a0c8a11b0884 (http://localhost:8080/pkg-opt.wasm:wasm-function[371267]:0x4c395d5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::hba07b166d08955be (http://localhost:8080/pkg-opt.wasm:wasm-function[435553]:0x4dab2c5)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::SamplerData<Out>>>::on_event::hf8e4a00ca609ab0b (http://localhost:8080/pkg-opt.wasm:wasm-function[57087]:0x269e673)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h84de0047cd27af68 (http://localhost:8080/pkg-opt.wasm:wasm-function[184491]:0x3dbb56d)
    at core::option::Option<T>::map::h257ee1034b3caa76 (http://localhost:8080/pkg-opt.wasm:wasm-function[73433]:0x2aa4226)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h45e7db743556fca9 (http://localhost:8080/pkg-opt.wasm:wasm-function[137781]:0x3709a16)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hd15fcb1afdc2430c (http://localhost:8080/pkg-opt.wasm:wasm-function[1071]:0x55e8cc)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hbf39a0c8a11b0884 (http://localhost:8080/pkg-opt.wasm:wasm-function[371267]:0x4c395d5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h91879eda458ec99d (http://localhost:8080/pkg-opt.wasm:wasm-function[435485]:0x4daaf0d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::ProfileData<T>>>::on_event::heff252ccf8e0ea1d (http://localhost:8080/pkg-opt.wasm:wasm-function[107892]:0x31cea9f)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h62061e02b2928273 (http://localhost:8080/pkg-opt.wasm:wasm-function[184427]:0x3db9570)
    at core::option::Option<T>::map::hb59c9b715af56266 (http://localhost:8080/pkg-opt.wasm:wasm-function[73707]:0x2ab3dac)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h44c1c56bb3ebf02f (http://localhost:8080/pkg-opt.wasm:wasm-function[137780]:0x370996c)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hd15fcb1afdc2430c (http://localhost:8080/pkg-opt.wasm:wasm-function[1071]:0x55e8cc)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hbf39a0c8a11b0884 (http://localhost:8080/pkg-opt.wasm:wasm-function[371267]:0x4c395d5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h8c70e2a60cb0310a (http://localhost:8080/pkg-opt.wasm:wasm-function[435476]:0x4daae8f)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::AnyData<Out>>>::on_event::hb90818189c9a5783 (http://localhost:8080/pkg-opt.wasm:wasm-function[434845]:0x4da88d3)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h3ff850306f55aa4a (http://localhost:8080/pkg-opt.wasm:wasm-function[184356]:0x3db71f5)
    at core::option::Option<T>::map::hca09dfc2150dc9d6 (http://localhost:8080/pkg-opt.wasm:wasm-function[73741]:0x2ab5ce2)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::he05f918d59a63cb1 (http://localhost:8080/pkg-opt.wasm:wasm-function[138073]:0x3715bfe)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hd15fcb1afdc2430c (http://localhost:8080/pkg-opt.wasm:wasm-function[1071]:0x55e8cc)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hbf39a0c8a11b0884 (http://localhost:8080/pkg-opt.wasm:wasm-function[371267]:0x4c395d5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h2b43119f98748a45 (http://localhost:8080/pkg-opt.wasm:wasm-function[435341]:0x4daa72d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::MapData<T,F>>>::on_event::h6f98225f51ea502f (http://localhost:8080/pkg-opt.wasm:wasm-function[205549]:0x4034611)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h8361b1f71884ca46 (http://localhost:8080/pkg-opt.wasm:wasm-function[184489]:0x3dbb46d)
    at core::option::Option<T>::map::h879ca03147114384 (http://localhost:8080/pkg-opt.wasm:wasm-function[73617]:0x2aaeb0e)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h4331e8c831e6aa11 (http://localhost:8080/pkg-opt.wasm:wasm-function[137776]:0x37096c4)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h84b02af2041d1973 (http://localhost:8080/pkg-opt.wasm:wasm-function[435467]:0x4daae11)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::SamplerData<Out>>>::on_event::h5290c4fd52de01c7 (http://localhost:8080/pkg-opt.wasm:wasm-function[84043]:0x2cfb818)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h1dcd82bbbe7541d9 (http://localhost:8080/pkg-opt.wasm:wasm-function[184282]:0x3db4cf9)
    at core::option::Option<T>::map::hf41a74a5f2b9155a (http://localhost:8080/pkg-opt.wasm:wasm-function[73817]:0x2aba2a6)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h14fbd9c3dfc2fce5 (http://localhost:8080/pkg-opt.wasm:wasm-function[137697]:0x370624e)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::hee5f00bddb66b9a4 (http://localhost:8080/pkg-opt.wasm:wasm-function[435636]:0x4dab74f)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::ProfileData<T>>>::on_event::h26b4d5f63e993cf7 (http://localhost:8080/pkg-opt.wasm:wasm-function[107900]:0x31cf13f)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::he6c2e3affd8b4fed (http://localhost:8080/pkg-opt.wasm:wasm-function[184641]:0x3dc0065)
    at core::option::Option<T>::map::h7ffa6b84f191424c (http://localhost:8080/pkg-opt.wasm:wasm-function[73603]:0x2aade34)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hb0614f2247926536 (http://localhost:8080/pkg-opt.wasm:wasm-function[137974]:0x3711a40)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h627c6c721e4c732e (http://localhost:8080/pkg-opt.wasm:wasm-function[435421]:0x4daab8d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::AnyData<Out>>>::on_event::hc1b0a632331087ed (http://localhost:8080/pkg-opt.wasm:wasm-function[434856]:0x4da896d)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::hb6a7ea5b84908ba9 (http://localhost:8080/pkg-opt.wasm:wasm-function[184560]:0x3dbd7ea)
    at core::option::Option<T>::map::h4070e9e0c731a3b5 (http://localhost:8080/pkg-opt.wasm:wasm-function[73486]:0x2aa72cd)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hf99bf7088d616377 (http://localhost:8080/pkg-opt.wasm:wasm-function[138115]:0x37177e2)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::hee5f00bddb66b9a4 (http://localhost:8080/pkg-opt.wasm:wasm-function[435636]:0x4dab74f)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::ProfileData<T>>>::on_event::h26b4d5f63e993cf7 (http://localhost:8080/pkg-opt.wasm:wasm-function[107900]:0x31cf13f)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::he6c2e3affd8b4fed (http://localhost:8080/pkg-opt.wasm:wasm-function[184641]:0x3dc0065)
    at core::option::Option<T>::map::h7ffa6b84f191424c (http://localhost:8080/pkg-opt.wasm:wasm-function[73603]:0x2aade34)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hb0614f2247926536 (http://localhost:8080/pkg-opt.wasm:wasm-function[137974]:0x3711a40)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h627c6c721e4c732e (http://localhost:8080/pkg-opt.wasm:wasm-function[435421]:0x4daab8d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::AnyData<Out>>>::on_event::hc1b0a632331087ed (http://localhost:8080/pkg-opt.wasm:wasm-function[434856]:0x4da896d)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::hb6a7ea5b84908ba9 (http://localhost:8080/pkg-opt.wasm:wasm-function[184560]:0x3dbd7ea)
    at core::option::Option<T>::map::h4070e9e0c731a3b5 (http://localhost:8080/pkg-opt.wasm:wasm-function[73486]:0x2aa72cd)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hf99bf7088d616377 (http://localhost:8080/pkg-opt.wasm:wasm-function[138115]:0x37177e2)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::hafc366d372dd887f (http://localhost:8080/pkg-opt.wasm:wasm-function[1225]:0x5f73f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h77a237e7dbbbda35 (http://localhost:8080/pkg-opt.wasm:wasm-function[371260]:0x4c394ee)


IPC error:

panicked at 'already borrowed: BorrowMutError', app/gui/src/controller/searcher.rs:558:53

Stack:

Error
    at eval (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17793:19)
    at logError (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:16936:14)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17792:12)
    at console_error_panic_hook::Error::new::h089d5da412a450cc (http://localhost:8080/pkg-opt.wasm:wasm-function[413696]:0x4d554b8)
    at console_error_panic_hook::format_panic_impl::h81fa303ff68f5b78 (http://localhost:8080/pkg-opt.wasm:wasm-function[84922]:0x2d2b40e)
    at console_error_panic_hook::format_panic::hd347a3ec156114f0 (http://localhost:8080/pkg-opt.wasm:wasm-function[472960]:0x4e34e2d)
    at enso_web::report_panic::he0fbc91535466bec (http://localhost:8080/pkg-opt.wasm:wasm-function[19435]:0x1966046)
    at core::ops::function::Fn::call::he49ee373b556e9fa (http://localhost:8080/pkg-opt.wasm:wasm-function[329181]:0x4a8bd7f)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8080/pkg-opt.wasm:wasm-function[92656]:0x2ec0cfe)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8080/pkg-opt.wasm:wasm-function[150424]:0x39030af)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8080/pkg-opt.wasm:wasm-function[339591]:0x4b146ce)
    at rust_begin_unwind (http://localhost:8080/pkg-opt.wasm:wasm-function[280314]:0x4750909)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8080/pkg-opt.wasm:wasm-function[330758]:0x4aa3011)
    at core::result::unwrap_failed::h8df12878c980b977 (http://localhost:8080/pkg-opt.wasm:wasm-function[161654]:0x3aaf258)
    at core::cell::RefCell<T>::borrow_mut::h39628e7e440248f2 (http://localhost:8080/pkg-opt.wasm:wasm-function[113279]:0x32d6321)
    at enso_gui::controller::searcher::Searcher::set_input::h41d1b21c57b83eb9 (http://localhost:8080/pkg-opt.wasm:wasm-function[2886]:0xab11e6)
    at enso_gui::presenter::searcher::Model::input_changed::hf42ac5954548bae8 (http://localhost:8080/pkg-opt.wasm:wasm-function[5466]:0xea8b03)
    at enso_gui::presenter::searcher::Searcher::new::{{closure}}::hdcb19d9fbf52b381 (http://localhost:8080/pkg-opt.wasm:wasm-function[102701]:0x30ccf86)
    at enso_frp::nodes::<impl enso_frp::network::Network>::map_::{{closure}}::hd039193a7402dabb (http://localhost:8080/pkg-opt.wasm:wasm-function[313375]:0x499e60d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::MapData<T,F>>>::on_event::hf857ddc06175eee1 (http://localhost:8080/pkg-opt.wasm:wasm-function[249611]:0x449cec2)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h0fb13ff47ab523cc (http://localhost:8080/pkg-opt.wasm:wasm-function[182594]:0x3d7fef2)
    at core::option::Option<T>::map::hc166c12c76e749cd (http://localhost:8080/pkg-opt.wasm:wasm-function[71940]:0x2a4e6be)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::heb7375b305189d4c (http://localhost:8080/pkg-opt.wasm:wasm-function[136201]:0x36c8076)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h3a20e43937f14139 (http://localhost:8080/pkg-opt.wasm:wasm-function[1149]:0x5abe66)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hdab86b9044f63202 (http://localhost:8080/pkg-opt.wasm:wasm-function[371647]:0x4c3c9c5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h692175577c656f73 (http://localhost:8080/pkg-opt.wasm:wasm-function[451177]:0x4de657d)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::SamplerData<Out>>>::on_event::hf800e3085d5574ac (http://localhost:8080/pkg-opt.wasm:wasm-function[71040]:0x2a1ac80)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h87724bf7f156c58e (http://localhost:8080/pkg-opt.wasm:wasm-function[185514]:0x3ddb62a)
    at core::option::Option<T>::map::h7fa4f1c85fcd690b (http://localhost:8080/pkg-opt.wasm:wasm-function[74575]:0x2ae5cf2)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h645cd7f97b11f533 (http://localhost:8080/pkg-opt.wasm:wasm-function[138753]:0x37320bc)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h3a20e43937f14139 (http://localhost:8080/pkg-opt.wasm:wasm-function[1149]:0x5abe66)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hdab86b9044f63202 (http://localhost:8080/pkg-opt.wasm:wasm-function[371647]:0x4c3c9c5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h1bbae8126a42a85a (http://localhost:8080/pkg-opt.wasm:wasm-function[450818]:0x4de51db)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::AnyData<Out>>>::on_event::h27ae854549b7471f (http://localhost:8080/pkg-opt.wasm:wasm-function[449449]:0x4ddfd8b)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h43d15a50495148d3 (http://localhost:8080/pkg-opt.wasm:wasm-function[185173]:0x3dd0baa)
    at core::option::Option<T>::map::h1b9f58f12a97ff64 (http://localhost:8080/pkg-opt.wasm:wasm-function[74095]:0x2aca452)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hcc89c30fa4949b72 (http://localhost:8080/pkg-opt.wasm:wasm-function[139261]:0x3747214)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h3a20e43937f14139 (http://localhost:8080/pkg-opt.wasm:wasm-function[1149]:0x5abe66)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hdab86b9044f63202 (http://localhost:8080/pkg-opt.wasm:wasm-function[371647]:0x4c3c9c5)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h6f226049ab8bb815 (http://localhost:8080/pkg-opt.wasm:wasm-function[430163]:0x4d96e54)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::FilterMapData<T,F>>>::on_event::hc194b4c53cdfe33d (http://localhost:8080/pkg-opt.wasm:wasm-function[30904]:0x1e5e346)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::hb8ccb895b18b8f8b (http://localhost:8080/pkg-opt.wasm:wasm-function[183631]:0x3da0675)
    at core::option::Option<T>::map::h0a3487cc75bb385b (http://localhost:8080/pkg-opt.wasm:wasm-function[72628]:0x2a75ef7)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h8c1785cab06e9551 (http://localhost:8080/pkg-opt.wasm:wasm-function[137065]:0x36ebe9c)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h3940bd940b91bbb1 (http://localhost:8080/pkg-opt.wasm:wasm-function[921]:0x4c799e)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hb09f932fd7035cf5 (http://localhost:8080/pkg-opt.wasm:wasm-function[370907]:0x4c3652a)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::hb26390e7954de4e3 (http://localhost:8080/pkg-opt.wasm:wasm-function[430230]:0x4d971fe)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<<T2 as enso_frp::node::HasOutput>::Output> for enso_frp::stream::Node<enso_frp::nodes::SampleData<T1,T2>>>::on_event::ha3623986612a6bef (http://localhost:8080/pkg-opt.wasm:wasm-function[187801]:0x3e23152)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::hbba3474655f4bd06 (http://localhost:8080/pkg-opt.wasm:wasm-function[183637]:0x3da0975)
    at core::option::Option<T>::map::hcd612a4987de6427 (http://localhost:8080/pkg-opt.wasm:wasm-function[72848]:0x2a828eb)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::heb51feeed3d61ff7 (http://localhost:8080/pkg-opt.wasm:wasm-function[137171]:0x36f0500)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h63e3d835c8e3d99e (http://localhost:8080/pkg-opt.wasm:wasm-function[1513]:0x71069d)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h596bbb46c6c71c0c (http://localhost:8080/pkg-opt.wasm:wasm-function[372578]:0x4c4481f)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h91f4c70c198ca39e (http://localhost:8080/pkg-opt.wasm:wasm-function[463463]:0x4e1442a)
    at enso_frp::nodes::<impl enso_frp::stream::EventConsumer<Out> for enso_frp::stream::Node<enso_frp::nodes::AnyData<Out>>>::on_event::h3d9373b1e8d28806 (http://localhost:8080/pkg-opt.wasm:wasm-function[463462]:0x4e1441c)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::{{closure}}::h3ce404ff7cee2b80 (http://localhost:8080/pkg-opt.wasm:wasm-function[187126]:0x3e0df18)
    at core::option::Option<T>::map::he1b65fae04d7233c (http://localhost:8080/pkg-opt.wasm:wasm-function[76287]:0x2b48731)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hbeb414d589409884 (http://localhost:8080/pkg-opt.wasm:wasm-function[140599]:0x377e9a2)
    at <enso_frp::stream::NodeData<Out> as enso_frp::stream::EventEmitter>::emit_event::h63e3d835c8e3d99e (http://localhost:8080/pkg-opt.wasm:wasm-function[1513]:0x71069d)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h596bbb46c6c71c0c (http://localhost:8080/pkg-opt.wasm:wasm-function[372578]:0x4c4481f)
    at <enso_frp::stream::Stream<Out> as enso_frp::stream::EventEmitter>::emit_event::{{closure}}::h6e18ed4cd2f8e1ae (http://localhost:8080/pkg-opt.wasm:wasm-function[198340]:0x3f620bf)
    at <core::option::Option<T> as enso_prelude::option::OptionOps>::for_each::hc69a8ff860d0b0cd (http://localhost:8080/pkg-opt.wasm:wasm-function[37660]:0x20b792a)
    at <enso_frp::stream::Stream<Out> as enso_frp::stream::EventEmitter>::emit_event::hf677c3dfa1849486 (http://localhost:8080/pkg-opt.wasm:wasm-function[282073]:0x477570e)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::EventEmitter>::emit_event::h07cc40d88d828483 (http://localhost:8080/pkg-opt.wasm:wasm-function[463458]:0x4e143e4)
    at enso_frp::nodes::<impl enso_frp::stream::WeakNode<enso_frp::nodes::AnyData<Out>>>::emit::h150f6506407920e4 (http://localhost:8080/pkg-opt.wasm:wasm-function[210298]:0x40b53c1)
    at enso_frp::io::timer::timeout::Timeout::new::{{closure}}::h0f3d55d9cfc0686d (http://localhost:8080/pkg-opt.wasm:wasm-function[504637]:0x4e826bd)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0f9200bad88708f3 (http://localhost:8080/pkg-opt.wasm:wasm-function[180679]:0x3d3fba8)
    at __wbg_adapter_88 (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17087:8)
    at real (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:16922:14)
```

### Expected behaviour

I expect the screen to not freeze.

### How we can reproduce it?

1. Enter the expression above.
2. Select `_.join` part.

### Screenshots or screencasts

_No response_

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #6119 #6117 

The issue was caused by the usage of `slice::windows`, which panics if the input is `0`. After two modifications of the code that should never happen again. Technically any of the two would work fine without the other.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/src/controller/searcher/input.rs [hunk 1]
```diff
@@ -425,7 +426,11 @@ impl InsertContext<'_> {
                 .flatten()
                 .filter_map(|opr| ast::identifier::name(&opr.item.arg).map(ImString::new))
                 .collect_vec();
-            Some(name_segments)
+            if name_segments.is_empty() {
+                Some(name_segments)
+            } else {
+                None
+            }
```
Comment (kazcw) [inline app/gui/src/controller/searcher/input.rs]: This looks like it should be `if !name_segments.is_empty()`?

Comment (vitvakatu) [reply app/gui/src/controller/searcher/input.rs]: Sure, thank you!

**Review by kazcw — APPROVED** [review]

File: app/gui/src/controller/searcher/input.rs [hunk 2]
```diff
@@ -425,7 +426,11 @@ impl InsertContext<'_> {
                 .flatten()
                 .filter_map(|opr| ast::identifier::name(&opr.item.arg).map(ImString::new))
                 .collect_vec();
-            Some(name_segments)
+            if !name_segments.is_empty() {
+                Some(name_segments)
+            } else {
+                None
```
Comment (wdanilo) [inline app/gui/src/controller/searcher/input.rs]: there is a function for that on bool, like `.as_some` or something like that. Use it instead, please to make these 5 lines, 1 line :)

**Review by wdanilo — APPROVED** [review]

**Comment by Procrat** [comment]
QA: Looks good to me! I can't reproduce the original bug with this change :)
