### PR TITLE
Handle Ydoc shutdown correctly 

### LINKED ISSUE #14225: Exception in Ydoc during shutdown
```
app/gui dev:vite: [ERROR] [2025-10-30T10:53:35+01:00] [org.enso.ydoc.polyfill.web.EventEmitter] Error emitting event of close [[1000, com.oracle.truffle.api.strings.TruffleString]] on () => this.close()
app/gui dev:vite: org.graalvm.polyglot.PolyglotException: java.net.SocketException: Socket closed
app/gui dev:vite: 	at io.helidon.common.buffers@4.2.2/io.helidon.common.buffers.GrowingBufferData.writeTo(GrowingBufferData.java:69)
app/gui dev:vite: 	at io.helidon.common.socket@4.2.2/io.helidon.common.socket.PlainSocket.write(PlainSocket.java:136)
app/gui dev:vite: 	at io.helidon.common.socket@4.2.2/io.helidon.common.socket.SocketWriter.writeNow(SocketWriter.java:81)
app/gui dev:vite: 	at io.helidon.webserver.websocket@4.2.2/io.helidon.webserver.websocket.WsConnection.send(WsConnection.java:342)
app/gui dev:vite: 	at io.helidon.webserver.websocket@4.2.2/io.helidon.webserver.websocket.WsConnection.close(WsConnection.java:205)
app/gui dev:vite: 	at io.helidon.webserver.websocket@4.2.2/io.helidon.webserver.websocket.WsConnection.terminate(WsConnection.java:210)
app/gui dev:vite: 	at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.WebSocket.execute(WebSocket.java:199)
app/gui dev:vite: 	at <js>.close(websocket.js:234)
app/gui dev:vite: 	at <js>.close(ydoc.cjs:28769)
app/gui dev:vite: 	at <js>.:=>(ydoc.cjs:28688)
app/gui dev:vite: 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.executeVoid(Value.java:1074)
app/gui dev:vite: 	at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.EventEmitter$Store.lambda$emit$0(EventEmitter.java:123)
app/gui dev:vite: 	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4725)
app/gui dev:vite: 	at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.EventEmitter$Store.emit(EventEmitter.java:120)
app/gui dev:vite: 	at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.EventEmitter.execute(EventEmitter.java:74)
app/gui dev:vite: 	at <js>.emit(event-emitter.js:34)
app/gui dev:vite: 	at <js>.#handle_close(websocket.js:264)
app/gui dev:vite: 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.executeVoid(Value.java:1074)
app/gui dev:vite: 	at org.enso.ydoc.polyfill/org.enso.ydoc.polyfill.web.WebSocket$WebSocketConnection.lambda$onClose$0(WebSocket.java:328)
app/gui dev:vite: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
app/gui dev:vite: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
app/gui dev:vite: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:309)
app/gui dev:vite: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
app/gui dev:vite: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
app/gui dev:vite: 	at java.base/java.lang.Thread.run(Thread.java:1447)
```

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #14225 

Changelog:
- update: handle the case when WebSocket was closed by the server during shutdown

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java [hunk 1]
```diff
@@ -236,6 +237,67 @@ public void ping() throws Exception {
...
+          lock.release();
+        });
+        """;
+
+    context.getBindings("js").putMember("lock", lock);
+    context.getBindings("js").putMember("res", res);
+
+    CompletableFuture.supplyAsync(() -> context.eval("js", code), executor).get();
+
+    lock.acquire();
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java:263]: - rename the lock to express its meaning
- maybe `notifyAsynchronousOpenIsOver`?

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java [hunk 2]
```diff
@@ -236,6 +237,67 @@ public void ping() throws Exception {
...
+
+    Assert.assertTrue(res.get());
+  }
+
+  @Test
+  public void handleSocketClosed() throws Exception {
+    var lock1 = new Semaphore(0);
+    var lock2 = new Semaphore(0);
+    var lock3 = new Semaphore(0);
```
Comment (JaroslavTulach) [inline lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java:272]: - There three locks would really benefit from having distinguishable names

**Review by JaroslavTulach — APPROVED** [review]

File: lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java (hunk 2 above)
Comment (4e6) [reply lib/java/ydoc-polyfill/src/test/java/org/enso/ydoc/polyfill/web/WebSocketTest.java:272]: Yeah, it's hard to come up with reasonable names for those barriers. I added comments that should clarify the test logic.
