### PR TITLE
Throw panic on "no currying for conversions"

### LINKED ISSUE #6897: Cannot enter collapsed function that failed the execution
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I declared the following function:

```
func4 operator3 =
    operator4 = Data.fetch operator3 headers=[] parse=Boolean.False
    operator1 = operator4.body
    operator2 = operator1.bytes
    operator5 = Table.from
```
But the node `Main.func4` on my scene never evaluates, and I cannot enter it.

The dev console reports the following error:
```
router.ts:48 [ERROR] app/gui/src/model/project/synchronized.rs:560 Execution failed in context 5bc17fc6-5b10-4c78-be59-0689f8a2e71b. Error: Execution of function main failed (Conversion currying without `this` or `that` argument is not supported.)..
```

### Expected behaviour

I can enter node, even if it's erroneous.

### How we can reproduce it?

Try to collapse any function with `Table.from` and enter it.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

ab159238ddb27a3a2d1ea228b2dd23a4e19694f6 on 2022-05-26 engine

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Previously, a `RuntimeException` would be thrown when an attempt would be made to curry a conversion function. That is problematic for IDE where `executionFailed` means we can't enter functions due to lack of method pointers info.

Closes #6897.

Screenshot from 2023-06-02 20-31-03

### Important Notes

A more generic solution that allows to recover from execution failures will need a follow up.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by GregoryTravis — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]
:heart:

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java [hunk 1]
```diff
@@ -224,8 +224,8 @@ public Object invokeConversion(
           callerFrame, state, conversion, selfArgument, thatArgument, arguments);
     } else {
       CompilerDirectives.transferToInterpreter();
-      throw new RuntimeException(
-          "Conversion currying without `this` or `that` argument is not supported.");
+      var ctx = EnsoContext.get(this);
+      throw new PanicException(ctx.getBuiltins().error().makeNoConversionCurrying(canApplyThis, canApplyThat, conversion), this);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java:228]: `RuntimeException` is completely inappropriate for reporting errors in user code. Throwing `PanicException` is certainly more desirable for such situations.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java [hunk 2]
```diff
@@ -25,6 +25,7 @@ public class Error {
   private final UninitializedState uninitializedState;
   private final NoSuchMethod noSuchMethod;
   private final NoSuchConversion noSuchConversion;
+  private final NoConversionCurrying noConversionCurrying;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java:28]: There already is `NoConversionCurrying` builtin!? That'd be surprising.

I don't think we should introduce new builtin (the less builtins, the better). Especially if this is not a permanent state (the description indicates follow up work is going to be needed).

Just reuse `NoSuchConversion` with different message, in my opinion.

File: test/Tests/src/Semantic/Conversion_Spec.enso [hunk 3]
```diff
@@ -112,4 +112,7 @@ spec =
             meta_from.rename "foo" 123 . should_equal "foo called"
             meta_from.rename "foo" . should_equal .foo
 
+        Test.specify "should not allow currying" <|
+            Panic.recover Any (Foo.from) . catch Any .to_display_text . should_equal "Conversion currying without `that` argument is not supported."
```
Comment (JaroslavTulach) [inline test/Tests/src/Semantic/Conversion_Spec.enso:116]: Wouldn't `should_fail_with` be better suited for the test? Or do you want the test to pass even when no exception happen?

**Review by JaroslavTulach — APPROVED** [review]
Avoiding `RuntimeException` is good. Some **TCA**s inline...

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java (hunk 2 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java:28]: I forgot to add it to git, fixed.

I'm not entirely convinced about merging it into one. No conversion vs no conversion currying are two different things really.

**Review by Akirathan — APPROVED** [review]

File: test/Tests/src/Semantic/Conversion_Spec.enso (hunk 3 above)
Comment (radeusgd) [inline test/Tests/src/Semantic/Conversion_Spec.enso:116]: Where is this `Conversion currying without ...` message coming from? I don't see it defined in the code anywhere now. 🪄

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoConversionCurrying.java [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+  @Override
+  protected String getConstructorName() {
+    return "Error";
+  }
+
+  @Override
+  protected List<String> getConstructorParamNames() {
+    return List.of("has_this", "has_that", "conversion");
+  }
+}
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoConversionCurrying.java:19]: Unless I'm missing something, I don't see the corresponding definition in `Errors/Common.enso`. Please add it, as each builtin should have a definition in Enso code. Also that's where we can define the `to_display_text` for it.

Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoConversionCurrying.java:19]: Accidentally put in `built-distribution/...` that's why it worked for me. Fixed

File: test/Tests/src/Semantic/Conversion_Spec.enso (hunk 3 above)
Comment (hubertp) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: Wanted to test the actual message. But checking the error is sufficient, I guess.

Comment (hubertp) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: > Wouldn't should_fail_with be better suited for the test?

Actually that won't work with Panics.

Comment (radeusgd) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: I would appreciate if we do test the message.

Comment (radeusgd) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: `should_fail_with` will work if you first do `Panic.recover` - `recover` will convert the Panic into dataflow error and then `should_fail_with` can handle it.

Comment (radeusgd) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: And using `catch` you can then check the error message. Like this:
```suggestion
            r = Panic.recover Any (Foo.from)
            r.should_fail_with No_Conversion_Currying
            r.catch . to_display_text . should_equal "Conversion currying without `that` argument is not supported."
```

Comment (radeusgd) [reply test/Tests/src/Semantic/Conversion_Spec.enso:116]: Alternatively, you can use `Test.expect_panic_with` directly - this is a function meant for testing panics. But it won't allow you to check the error message and I think checking it is good - we had lots of places where `to_display_text` would crash because of typos and that went undetected only until the IDE was unable to display error properly. We want to go in the direction of having `to_display_text` of every error unit tested to ensure no regressions of error display can get into the IDE.
