### PR TITLE
Change full-screen visualisation shortcut to shift-space

### LINKED ISSUE #6260: Pressing double space to open full screen vis is closing it first
### Discord username

_No response_

### What type of issue is this?

Transient – Occuring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Having the visualization under the node open and pressing double space to have it full screen is closing it and then reopening. This causes the settings of the visualization (like custom columns width for table) to reset.

### Expected behaviour

Opening the full screen visualization should not close it.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

2023.1.1-nightly.2023.4.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Fixes #6260: The shortcut to open the full-screen visualisation is now `shift-space` so it doesn't interfere with the `space` shortcut to toggle the mini-visualisation.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/lib.rs [hunk 1]
```diff
@@ -562,14 +562,13 @@ ensogl::define_endpoints_2! {
...
-        /// Simulates a visualization open double press event. This event toggles the visualization
-        /// fullscreen mode.
-        double_press_visualization_visibility(),
         /// Simulates a visualization open release event. See `press_visualization_visibility` to
         /// learn more.
         release_visualization_visibility(),
         /// Cycle the visualization for the selected nodes.
         cycle_visualization_for_selected_node(),
+        /// Opens the visualization for the selected node in full-screen mode.
+        open_fullscreen_visualization (),
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/lib.rs]: Extra space.

File: app/gui/view/graph-editor/src/lib.rs [hunk 2]
```diff
@@ -3536,7 +3535,7 @@ fn new_graph_editor(app: &Application) -> GraphEditor {
     //     - If it was long, disable vis which were disabled (preview mode).
 
     let viz_press_ev      = inputs.press_visualization_visibility.clone_ref();
-    let viz_d_press_ev    = inputs.double_press_visualization_visibility.clone_ref();
+    let viz_open_fs_ev = inputs.open_fullscreen_visualization.clone_ref();
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/lib.rs:3538]: Missing aligning spaces. It's not our convention to use them everywhere, but let's maintain consistency with the rest of the block.

File: app/gui/view/graph-editor/src/lib.rs [hunk 3]
```diff
@@ -3581,7 +3580,7 @@ fn new_graph_editor(app: &Application) -> GraphEditor {
     viz_disable_by_press <= viz_tgt_nodes.gate(&viz_tgt_nodes_all_on);
     viz_disable          <- any(viz_disable_by_press,inputs.disable_visualization);
     viz_preview_disable  <= viz_tgt_nodes_off.sample(&viz_preview_mode_end);
-    viz_fullscreen_on    <= viz_d_press_ev.map(f_!(model.nodes.last_selected()));
+    viz_fullscreen_on <= viz_open_fs_ev.map(f_!(model.nodes.last_selected()));
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/lib.rs:3583]: Missing aligning spaces.

File: app/gui/view/graph-editor/src/shortcuts.rs [hunk 4]
```diff
@@ -21,10 +21,10 @@ pub const SHORTCUTS: &[(ensogl::application::shortcut::ActionType, &str, &str, &
     (Press, "!read_only", "cmd g", "collapse_selected_nodes"),
     // === Visualization ===
     (Press, "!node_editing", "space", "press_visualization_visibility"),
-    (DoublePress, "!node_editing", "space", "double_press_visualization_visibility"),
+    (Press, "!node_editing", "shift space", "open_fullscreen_visualization"),
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/shortcuts.rs]: Should this condition be `!node_editing & !is_fs_visualization_displayed` to avoid sending a spurious `open_fullscreen_visualization` event along with the `close_fullscreen_visualization` event?

**Review by kazcw — APPROVED** [review]

File: app/gui/view/graph-editor/src/lib.rs (hunk 2 above)
Comment (farmaazon) [inline app/gui/view/graph-editor/src/lib.rs:3538]: We can take a chance and remove alignment of `<-` in this code block.

File: app/gui/view/graph-editor/src/shortcuts.rs [hunk 5]
```diff
@@ -21,10 +21,10 @@ pub const SHORTCUTS: &[(ensogl::application::shortcut::ActionType, &str, &str, &
...
     (Release, "!node_editing", "space", "release_visualization_visibility"),
     (Press, "", "cmd i", "reload_visualization_registry"),
-    (Press, "is_fs_visualization_displayed", "space", "close_fullscreen_visualization"),
+    (Press, "is_fs_visualization_displayed", "shift space", "close_fullscreen_visualization"),
```
Comment (farmaazon) [inline app/gui/view/graph-editor/src/shortcuts.rs:32]: We can also add `escape` as an alternative to `shift space` as it may be greatly more intuitive for the users.

**Review by farmaazon — APPROVED** [review]

File: app/gui/view/graph-editor/src/lib.rs (hunk 2 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/lib.rs:3538]: I had comments on other PRs of mine where I tried to maintain consistency and was told to follow the style guide. I don't like it either though. What Adam suggests might be the best compromise.

File: app/gui/view/graph-editor/src/shortcuts.rs (hunk 4 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/shortcuts.rs]: Good call

File: app/gui/view/graph-editor/src/shortcuts.rs (hunk 5 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/shortcuts.rs:32]: Yeah, sounds good!

**Comment by farmaazon** [comment]
### QA Report: :red_circle: 

I was unable to close the visualization with escape. It wasn't technically requested by the issue (only in the review), but I think it will be a great UX enhancement (otherwise user could have no clue how to exit FS visualization).

**Comment by Procrat** [comment]
> I was unable to close the visualization with escape. It wasn't technically requested by the issue (only in the review), but I think it will be a great UX enhancement (otherwise user could have no clue how to exit FS visualization).

@farmaazon: I just tried it out again and it seems to work fine for me. What OS are you using? Do any of other `escape` shortcuts in the app work for you, e.g. exiting from editing text?

**Comment by farmaazon** [comment]
Huh, after pulling changes (merge?) I'm also able to hide visualization with escape, so

## QA :green_apple:

**Comment by somebody1234** [comment]
whoops, wrong PR number
