### PR TITLE
Re-fetch Warnings in Warning.getWarnings() to correctly wrap them

### LINKED ISSUE #8910: Warnings are not wrapped with Map_Error
During the migration of `Base_Tests` to the new builder Test API in #8890, the following test fails https://github.com/enso-org/enso/blob/dc8f562b6228f36134742e2c06e7414c965a1014/test/Base_Tests/src/Semantic/Warnings_Spec.enso#L319

The failure is in https://github.com/enso-org/enso/actions/runs/7710597347/job/21014244070?pr=8890#step:10:25728.

In https://github.com/enso-org/enso/pull/8890/commits/4b5417447133c1ff9b87d23c3a4282b8d42345ba, I have marked the test as pending.

```[tasklist]
### Tasks
- [ ] Revert https://github.com/enso-org/enso/pull/8890/commits/4b5417447133c1ff9b87d23c3a4282b8d42345ba
```

### PR DESCRIPTION
**Pull request by GregoryTravis**
Fixes #8910 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java [hunk 1]
```diff
@@ -106,6 +106,20 @@ public WithWarnings append(EnsoContext ctx, ArrayRope<Warning> newWarnings) {
...
+    if (warningsLibrary != null && warningsLibrary.hasWarnings(value)) {
+      try {
+        return warningsLibrary.getWarnings(value, null, true);
+      } catch (UnsupportedMessageException e) {
+        throw EnsoContext.get(warningsLibrary).raiseAssertionPanic(warningsLibrary, null, e);
+      }
+    } else {
+      return Warning.fromSetToArray(warnings);
+    }
+  }
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java]: I'm not sure if I understand.

I assume the problem scenario of this bug was:
1. warnings are fetched without wrapping
2. the result is cached
3. warnings are fetched with wrapping, but the cached unwrapped value is wrongly returned

Is my understanding correct?

----

I'm not sure if I get why the special handling _only_ applies for `shouldWrap=true`.

What if I first fetch warnings with wrapping and _that_ gets cached? Won't a subsequent fetch of warnings without wrapping also mistakenly get wrapped warnings because of them getting cached? Shouldn't we somehow keep separate caches for either case?

Comment (GregoryTravis) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java]: I don't think that the caching happens during the call to `Warning.get_all`. `shouldWrap=True` only happens during `get_all`, so I don't think the possibility you describe is possible. `shouldWrap` is always false during normal evaluation and propagation. The `WithWarnings` caching happens during evaluation, and whether or not it happens seems very dependent on specialization details -- or, in this case, setting the environment variables that cause this bug to be reproducible. `WithWarnings` isn't just straightforward memoization of `getWarnings()`, it's just something that is constructed in some evaluation paths and not others.

The warnings stored in `WithWarnings` are gathered by the normal warning propagation that happens during evaluation, and wrapping never happens during that propagation, because wrapping is specific to the relationship between a particular container and its contents, and normal propagation just copies / transfers warnings to every downstream value. The wrapping only happens after evaluation and after warnings are attached to values, while traversing the resulting value for `get_all`, and so we have special-case handling for array-likes during this traversal, to add the wrappers.

At some point we may need to redesign the Warning propagation so that warnings describe not only what went wrong (the warning itself), but also information about the context it which it happened (the wrapper). The solution we have for this right now works, but if in the future we want to get more useful information to the user, we might need to add more logic to the propagation itself, such as where the warning came from. Then this special-case path won't be needed.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java]: I see, thanks for the explanation.

This seems to be very complicated indeed, I'm concerned that could bite us - it may be worth to try to take a step back and see if the logic could be overall simplified (when we have some time...). Maybe the way we want the warnings to behave just _is_ complex so maybe there isn't that much that we can do to simplify it, I don't know.

For now your explanation seems to imply that the fix is OK, so I'm ok with that.

File: test/Base_Tests/src/Semantic/Warnings_Spec.enso [hunk 2]
```diff
@@ -319,6 +319,11 @@ add_specs suite_builder = suite_builder.group "Dataflow Warnings" group_builder-
...
         Warning.get_all (res.at 2) . map .value . should_equal [3, 2, 1, 0, 2, 1, 0, 1, 0, 0]
 
+    group_builder.specify "should wrap errors with even deeper nesting" <|
+        Warning.get_all [[[Warning.attach "warning" 10]]] wrap_errors=True . map .value . should_equal [Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 "warning"))]
+        Warning.get_all [[[[Warning.attach "warning" 10]]]] wrap_errors=True . map .value . should_equal [Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 "warning")))]
+        Warning.get_all [[[[[Warning.attach "warning" 10]]]]] wrap_errors=True . map .value . should_equal [Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 (Map_Error.Error 0 "warning"))))]
```
Comment (radeusgd) [inline test/Base_Tests/src/Semantic/Warnings_Spec.enso:325]: curious: why was this test added?

Did it reproduce the original issue without the convoluted way I originally found? Or is it something else?

**Review by radeusgd — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java [hunk 3]
```diff
@@ -106,6 +106,20 @@ public WithWarnings append(EnsoContext ctx, ArrayRope<Warning> newWarnings) {
         value, ctx.getWarningsLimit(), warnings, newWarnings.toArray(Warning[]::new));
   }
 
+  // Ignore the warnings cache in .value and re-fetch them using the WarningsLibrary.
+  // This is only used for shouldWrap=true.
+  public Warning[] getWarningsNoCache(WarningsLibrary warningsLibrary) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java]: Why is this method public?

**Review by JaroslavTulach — APPROVED** [review]

File: test/Base_Tests/src/Semantic/Warnings_Spec.enso (hunk 2 above)
Comment (GregoryTravis) [reply test/Base_Tests/src/Semantic/Warnings_Spec.enso:325]: I added this just for extra coverage; I had no reason to think it would fail. But (as I discovered when implementing this in the first place) the warning propagation is very dependent on complex details of specialization, so I want to cover as many cases as possible, including ones that seem like they wouldn't be an issue.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java (hunk 3 above)
Comment (GregoryTravis) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java]: Mistake -- removed.

**Review by hubertp — APPROVED** [review]
