### PR TITLE
Run Enso tests with assertions enabled

### LINKED ISSUE #5087: Invalid Sharing of AST nodes in EpbContext
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184321951).
<hr />

#183546453 enabled asserts in engine unit tests, but not in runtime-with-polyglot project. There is [invalid sharing of AST nodes](https://github.com/enso-org/enso/pull/4074#discussion_r1086255799) `AssertionError` which requires deeper investigation.

```
at com.oracle.truffle.polyglot.PolyglotSharingLayer.invalidSharingError(PolyglotSharingLayer.java:649)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals.validSharing(PolyglotFastThreadLocals.java:266)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals.getLanguageContext(PolyglotFastThreadLocals.java:236)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:457)
at org.enso.interpreter.epb.EpbContext.get(EpbContext.java:57)
at org.enso.interpreter.epb.node.ForeignEvalNode.getEpbContext(ForeignEvalNode.java:186)
at org.enso.interpreter.epb.node.ForeignEvalNode.parseJs(ForeignEvalNode.java:118)
```

This failure is caused by upgrading to GraalVM 22.2 and newer. GraalVM 22.2 introduced concept of "sharing layers" - that concept wasn't existing when `EpbContext` was created. Hence the new assertion error. Moreover the concept of "sharing layers" probably replaces all the work done in `EpbLanguage` - possibly the code isn't needed anymore.

## Tasks:
- [ ] Change the existing code to avoid the asserts
- [ ] Investigate if we can replace Epb by "sharing layers" and if so, plan that work

## Blockers:
[#183546453](https://www.pivotaltracker.com/story/show/#183546453) resolved

### LINKED ISSUE #5184: Simplify EpbLanguage by using TruffleLanguage.ParserRequest.getArgumentNames + support Ruby & co.
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182435117).
<hr />

`EpbLanguage` has special _envelope_ code for interop with JavaScript, Python and R. There is however a standard Truffle API: https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.ParsingRequest.html#getArgumentNames-- that allows to achieve (almost) the same and work across languages. Let's investigate whether we can simplify `EpbLanguage` implementation.

Initial discussion with Marcin lead to a fundamental question: Can we support JavaScript `this`? Pictures as well as description is below. The following two files `parseself` program seem to indicate providing `self` is possible. E.g. simplification of Python is possible right now. Dropping special _envelope_ support for `R` shall work as well, as `R` doesn't have any 1st class object oriented features anyway. 

Moreover, by basing our support on `getArgumentNames`, we open up to other, unknown languages that support it. Btw. [GraalVM Insight](https://github.com/oracle/graal/tree/master/docs/tools/insight) is using `getArgumentNames` - e.g. we'd be using exactly the same mechanism. Any language ready for **Insight** would also work for Enso.

Compiling and executing these two classes as `/graalvm-ce-java11-21.3.0/bin/java -cp . -Dtruffle.class.path.append=. org.apidesign.netbeans.parseself.Main` provides some insight into the behavior of `parse` with argument names.

```
package org.apidesign.netbeans.parseself;

import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.TruffleContext;
import com.oracle.truffle.api.instrumentation.ContextsListener;
import com.oracle.truffle.api.instrumentation.TruffleInstrument;
import com.oracle.truffle.api.nodes.LanguageInfo;
import com.oracle.truffle.api.source.Source;
import java.io.IOException;
import java.util.function.BiConsumer;

@TruffleInstrument.Registration(id = "parseself", name = "Parse Self", services = BiConsumer.class)
public class Parseself extends TruffleInstrument {
    final void defineSelf(TruffleInstrument.Env env, String lang, String text) {
        String selfName = "nic";
        switch (lang) {
            case "js": selfName = "this"; break;
            case "python": selfName = "self"; break;
        }
        try {
            Source src = Source.newBuilder(lang, text, "sample.py").build();
            CallTarget target = env.parse(src, selfName);
            target.call("hello");
        } catch (IOException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private TruffleContext ctx;

    @Override
    protected void onCreate(Env env) {
        BiConsumer<String, String> c = (lang, text) -> {
            Object p = ctx.enter();
            defineSelf(env, lang, text);
            ctx.leave(p);
        };
        env.registerService(c);
        env.getInstrumenter().attachContextsListener(new ContextsListener() {
            @Override
            public void onContextCreated(TruffleContext context) {
            }

            @Override
            public void onLanguageContextCreated(TruffleContext context, LanguageInfo language) {
                ctx = context;
            }

            @Override
            public void onLanguageContextInitialized(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onLanguageContextFinalized(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onLanguageContextDisposed(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onContextClosed(TruffleContext context) {
            }
        }, true);
    }
    
}
```

and `Main.java`: 

```
package org.apidesign.netbeans.parseself;

import java.util.function.BiConsumer;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Engine;

public class Main {
    public static void main(String[] args) {
        Context ctx = Context.create();
        Engine engine = ctx.getEngine();
        ctx.eval("js", "print('regular JavaScript initialized');");
        
        BiConsumer c = engine.getInstruments().get("parseself").lookup(BiConsumer.class);
        c.accept("python", "print(self);");
        c.accept("js", "print(this);");
        
        ctx.eval("js", "print('regular JavaScript finished');");
    }
}
```

## Comments:
The current functionality supports JavaScript `this` as well as Python's `self`. The `parseself` program (in the description of this issue) seems to indicate replacing `self` with `getArgumentNames()` shall be doable. Replacing JavaScript's `this` doesn't seem to be possible with `getArgumentNames()` functionality. However (as Enso is planning to replace `this` with `self`) we want to use `self` in JavaScript as well and that shall be no problem. (jaroslavtulach - Jun 10, 2022)
<hr />
Re: move from `this` to `self` – I think we should still stick to what the original language does – so `self` in py and `this` in js. This is how it works now anyway. (Marcin Kostrzewa - Jun 10, 2022)
<hr />
I've just installed `gu install ruby` into my GraalVM and then tried to use:
```
foreign ruby hello = """
    'Hello '
```
and got
```
now.enso[20:1-21:12]: Invalid foreign definition. Language ruby is not a supported polyglot language.
```
by using the `getArgumentNames()` approach, all the GraalVM languages would be supported. (jaroslavtulach - Jul 15, 2022)
<hr />

### LINKED ISSUE #5585: Enable Assertions in Enso Tests
### How important is this feature to you?

3 – Lack of it makes using Enso slightly harder

### Describe the idea you'd like to see implemented.

Recently we finally [got assertions enabled in the engine tests](https://github.com/enso-org/enso/pull/4074). This is great, because now we will be less likely to break Truffle invariants and we can also have our own assertions.

However, engine tests are not everything, a lot of interesting interactions also happen in our 'integration tests' written directly in Enso - in the `test/` directory.

Currently, running `test/Tests` yields:
```
[info] [2023-02-07T17:03:46.864Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Base @ 0.0.0-dev at [***\0.0.0-dev].
[info] [2023-02-07T17:03:46.921Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Test @ 0.0.0-dev at [***\0.0.0-dev].
Exception in thread "Thread-7" java.lang.IllegalStateException: There is no current context available.
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:135)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requireContext(PolyglotContextImpl.java:720)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.createLanguageSystemThread(EngineAccessor.java:1940)      
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1847)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.createSystemThread(TruffleLanguage.java:1813)
        at org.enso.compiler.SerializationManager.$anonfun$pool$1(SerializationManager.scala:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:623)
        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:912)
        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1005)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:65)
Execution finished with an error: java.lang.AssertionError: Invalid sharing of AST nodes detected. The current context uses a different sharing layer than the executed node. A common cause of this are CallTargets that are reused across different contexts in an invalid way.Stack trace: 
  <<current-context>>
    <-- Sharing Layer Change: 0x386708CF => 0xB3A8455 -->
  <epb>.(Unknown)(ForeignEvalNode@5c930fc3)
  <epb>.(Unknown)
  <enso>.Array_Polyglot_Spec.data(Array_Polyglot_Spec.enso:68)
  <enso>.Array_Polyglot_Spec.spec<arg-0>(Array_Polyglot_Spec.enso:10)
  <enso>.Array_Polyglot_Spec.spec<arg-1>(Array_Polyglot_Spec.enso:10)
  <enso>.Panic.catch(Unknown)
  <enso>.Panic.type.recover(Panic.enso:156)
  <enso>.Test.expect_panic_with(Test.enso:94)
  <enso>.Array_Polyglot_Spec.spec<arg-1>(Array_Polyglot_Spec.enso:10)
  <enso>.Test.run_spec<arg-1>(Test.enso:190)
  <enso>.Panic.catch(Unknown)
  <enso>.Panic.type.recover(Panic.enso:156)
  <enso>.Function.<|(Unknown)
  <enso>.Test.run_spec(Test.enso:189)
  <enso>.case_branch<arg-3>(Test.enso:70)
  <enso>.State.run(Unknown)
  <enso>.case_branch<arg-1>(Test.enso:70)
  <enso>.Runtime.no_inline(Unknown)
  <enso>.Duration.type.time_execution(Duration.enso:124)
  <enso>.case_branch(Test.enso:70)
  <enso>.Test.specify(Test.enso:69)
  <enso>.Function.<|(Unknown)
  <enso>.Array_Polyglot_Spec.spec<arg-1>(Array_Polyglot_Spec.enso:9)
  <enso>.case_branch<arg-1>(Test.enso:33)
  <enso>.State.run(Unknown)
  <enso>.Function.<|(Unknown)
  <enso>.case_branch(Test.enso:32)
  <enso>.Test.group<arg-1>(Test.enso:30)
  <enso>.Boolean.if_then(Unknown)
  <enso>.Test.group(Test.enso:29)
  <enso>.Function.<|(Unknown)
  <enso>.Array_Polyglot_Spec.spec(Array_Polyglot_Spec.enso:8)
  <enso>.Main.main<arg-1>(Main.enso:85)
  <enso>.Test_Suite.type.run<arg-1>(Test_Suite.enso:69)
  <enso>.State.run(Unknown)
  <enso>.Function.<|(Unknown)
  <enso>.Test_Suite.type.run<arg-1>(Test_Suite.enso:68)
  <enso>.Test_Reporter.wrap_junit_testsuites(Test_Reporter.enso:17)
  <enso>.Function.<|(Unknown)
  <enso>.Test_Suite.type.run(Test_Suite.enso:67)
  <enso>.Test_Suite.type.run_main(Test_Suite.enso:40)
  <enso>.Function.<|(Unknown)
  <enso>.Main.main(Main.enso:81)
  <Unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSharingLayer.invalidSharingError(PolyglotSharingLayer.java:641)      
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.validSharing(PolyglotFastThreadLocals.java:266)     
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.getLanguageContext(PolyglotFastThreadLocals.java:236)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:457)
        at <java> org.enso.interpreter.epb.EpbContext.get(EpbContext.java:57)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.parseJs(ForeignEvalNode.java:118)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.lockAndParse(ForeignEvalNode.java:83)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.ensureParsed(ForeignEvalNode.java:64)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.execute(ForeignEvalNode.java:53)
        at <epb> <epb> null(Unknown)
        at <enso> Array_Polyglot_Spec.data(src\Data\Array_Polyglot_Spec.enso:68-82)
        at <enso> Array_Polyglot_Spec.spec<arg-0>(src\Data\Array_Polyglot_Spec.enso:10:36-39)
        at <enso> Array_Polyglot_Spec.spec<arg-1>(src\Data\Array_Polyglot_Spec.enso:10:36-47)
        at <enso> Panic.catch(Internal)
        at <enso> Panic.type.recover(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Panic.enso:156-161)
        at <enso> Test.expect_panic_with(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:94:15-38)
        at <enso> Array_Polyglot_Spec.spec<arg-1>(src\Data\Array_Polyglot_Spec.enso:10:13-68)
        at <enso> Test.run_spec<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:190:18-25)
        at <enso> Panic.catch(Internal)
        at <enso> Panic.type.recover(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Panic.enso:156-161)
        at <enso> Function.<|(Internal)
        at <enso> Test.run_spec(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:189-193)
        at <enso> case_branch<arg-3>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:70:73-89)
        at <enso> State.run(Internal)
        at <enso> case_branch<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:70:49-90)
        at <enso> Runtime.no_inline(Internal)
        at <enso> Duration.type.time_execution(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Time\Duration.enso:124:18-43)
        at <enso> case_branch(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:70:24-91)
        at <enso> Test.specify(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:69-71)
        at <enso> Function.<|(Internal)
        at <enso> Array_Polyglot_Spec.spec<arg-1>(src\Data\Array_Polyglot_Spec.enso:9-10)
        at <enso> case_branch<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:33:25-33)
        at <enso> State.run(Internal)
        at <enso> Function.<|(Internal)
        at <enso> case_branch(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:32-34)
        at <enso> Test.group<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:30-39)
        at <enso> Boolean.if_then(Internal)
        at <enso> Test.group(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test.enso:29-39)
        at <enso> Function.<|(Internal)
        at <enso> Array_Polyglot_Spec.spec(src\Data\Array_Polyglot_Spec.enso:8-64)
        at <enso> Main.main<arg-1>(src\Main.enso:85:5-28)
        at <enso> Test_Suite.type.run<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test_Suite.enso:69:17-21)
        at <enso> State.run(Internal)
        at <enso> Function.<|(Internal)
        at <enso> Test_Suite.type.run<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test_Suite.enso:68-70)
        at <enso> Test_Reporter.wrap_junit_testsuites(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test_Reporter.enso:17:14-19)
        at <enso> Function.<|(Internal)
        at <enso> Test_Suite.type.run(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test_Suite.enso:67-70)
        at <enso> Test_Suite.type.run_main(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Test\0.0.0-dev\src\Test_Suite.enso:40:13-39)
        at <enso> Function.<|(Internal)
        at <enso> Main.main(src\Main.enso:81-147)
```

So we are still breaking Truffle assertions.

Moreover, ideally we should be able to use and verify `assert`s within `std-bits`. Currently, even if we add these, they cannot really be checked because if we run with `-ea` the run will fail due to the broken Truffle assertions.

Ideally we should also have `-ea` enabled for the Enso tests on the CI. Currently, that is only the case for the engine tests.

### Problem this is solving

1. We should not be breaking Truffle invariants checked in the asserts. Apparently, the engine test checks are not enough - we are still breakin these invariants 'in the wild'.
2. Because of (1), I cannot run Enso test suite with assertions enabled, because it will always fail due to the Truffle invariants being broken. So I cannot verify `assert`s in `std-bits` code (because the runs will fail due to (1)). Having the ability to add asserts is helpful as it allows us to verify invariants in our code and write it more correctly. We were also thinking of including an `assert` construct into Enso directly. Such assertions not only allow us to more confidently verify correctness of our code but also serve as documentation purposes explaining what a given function expects.
```[tasklist]
### Tasks
- [ ] Check that assertions in `com.oracle.truffle.api.source.Source#assertValid` are not failing - the issue is probably in how `Location` is initialized from `TreeToIr.java`
```

### PR DESCRIPTION
**Pull request by Akirathan**
Closes:
- #5585
- #5087
- #5184 by implementing `GenericForeignNode`

### Pull Request Description

This PR removes most of the Enso homemade `Proxy` functionality in `EpbLanguage`. Rather than that is uses new features in GraalVM that allow access to `OtherContextTruffleObject`. That fixes various `assert` checks in `EpbLanguage` and `runtime-with-polyglot` tests.  Now the whole Enso system can be executed with `-ea` checks on.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: build/build/src/enso.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ impl From<bool> for Boolean {
 }
 
 ide_ci::define_env_var! {
-    ENSO_JVM_OPTS, String;
```
Comment (Akirathan) [inline build/build/src/enso.rs:33]: `ENSO_JVM_OPTS` works only for project-manager or for launcher, but not when we run Enso via built engine distribution. For that, we need to pass the JVM flags via `JAVA_OPTS`.

**Comment by Akirathan** [comment]
Encountered AssertionErrors in https://github.com/enso-org/enso/actions/runs/6297283538/job/17093926525?pr=7882:
- [Examples_Tests](https://github.com/enso-org/enso/actions/runs/6297283538/job/17093926525?pr=7882#step:10:4667): Multiple failures. For example: [Array.java:41](https://github.com/enso-org/enso/blob/7a272ec15212f70decb57a510d65bd75ab2ee8da/engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Array.java#L41)
- [Table_Tests](https://github.com/enso-org/enso/actions/runs/6297283538/job/17093926525?pr=7882#step:10:4892): Invalid sharing of AST nodes detected

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Run Enso tests with assertions enabled · enso-org/enso@a8d28a4</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by Akirathan** [comment]
Let's wait for the merge of #7991 - that should help with the invalid sharing of nodes assertion error.

File: lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java [hunk 2]
```diff
@@ -69,28 +70,36 @@ public class BenchProcessor extends AbstractProcessor {
...
+    // Note that ensoHomeOverride does not have to exist, only its parent directory
+    ensoHomeOverride = ensoDir.toPath().resolve("distribution").resolve("component").toFile();
+  }
+
+  /**
+   * Locates the root of the Enso repository. Heuristic: we just keep going up the directory tree
+   * until we are in a directory containing ".git" subdirectory. Note that we cannot use the "enso"
+   * name, as users are free to name their cloned directories however they like.
+   */
+  private File locateRootDirectory() {
```
Comment (Akirathan) [inline lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java]: An unrelated change. This fixes the command `std-benchmarks/Bench/compile` if your root dir's name is not `enso`.

**Comment by Akirathan** [comment]
As of today, I am abandoning the PR once again. I am now stuck on [Multi-threaded access requested by thread ... but is not allowed for js](https://github.com/enso-org/enso/actions/runs/6907156456/job/18793725504?pr=7882#step:10:3701).

I have pushed my latest investigation in 09fa46360a80406dbf6062a193a2bb1d70040615 that contains some testing instruments that might be useful. The simplest way to reproduce the error is just with `runtime-with-polyglot> testOnly *RuntimeVisualizationsTest -- -z [1]`, or `runtime-with-polyglot> withDebug --debugger testOnly -- *RuntimeVisualizationsTest -- -z [1]`. I have tried to do a global lock of `EpbContext` but with no success.

cc @JaroslavTulach

**Comment by JaroslavTulach** [comment]
> I have pushed my latest investigation in [09fa463](https://github.com/enso-org/enso/commit/09fa46360a80406dbf6062a193a2bb1d70040615) that contains some testing instruments that might be useful. The simplest way to reproduce the error is just with `runtime-with-polyglot> testOnly *RuntimeVisualizationsTest -- -z [1]`, or `runtime-with-polyglot> withDebug --debugger testOnly -- *RuntimeVisualizationsTest -- -z [1]`. 

I can simulate the failure. According to last week's discussion with @4e6 - there should be no multi-threaded access to the context. Yet there is. Here is the list of the three `getSeenThreads()`:

```
Thread[#43,pool-1-thread-1-ScalaTest-running-RuntimeVisualizationsTest,5,main]=com.oracle.truffle.polyglot.PolyglotThreadInfo@64dd5b37[thread=Thread[#43,pool-1-thread-1-ScalaTest-running-RuntimeVisualizationsTest,5,main], enteredCount=0, cancelled=false, leaveAndEnterInterrupted=false], 

Thread[#66,sequential-command-pool-1,5,main]=com.oracle.truffle.polyglot.PolyglotThreadInfo@7ec8efc7[thread=Thread[#66,sequential-command-pool-1,5,main], enteredCount=1, cancelled=false, leaveAndEnterInterrupted=false], 

Thread[#65,job-pool-1,5,main]=com.oracle.truffle.polyglot.PolyglotThreadInfo@61cd1f20[thread=Thread[#65,job-pool-1,5,main], enteredCount=1, cancelled=false, leaveAndEnterInterrupted=false]}
```

that block access to JavaScript (which claims to be single threaded). If there was just a single thread, the JavaScript initialization would succeed.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java [hunk 3]
```diff
@@ -106,86 +98,44 @@ private void lockAndParse() throws IllegalStateException {
 
   private void parseJs() {
     EpbContext context = EpbContext.get(this);
-    GuardedTruffleContext outer = context.getCurrentContext();
-    GuardedTruffleContext inner = context.getInnerContext();
```
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java:110]: @Akirathan, you removed this code in 29d7963af518a13ba055d66fa952894232012b4d, but how that's supposed to work? JavaScript probably needs its own context unless we want to make Enso single-threaded-only!

We might fix the `RuntimeVisualizationTest` to be single threaded (and then JavaScript invocation from the same context could work), but that'd be just a test. As soon as we allow multi-threaded Enso execution somewhere, we'd be in the same problem - `JavaScriptLanguage` refusing to start in multiple threads context.

Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java:110]: I think the inner context is still needed. Returning it back in https://github.com/enso-org/enso/pull/7882/commits/6ce3a1b0b2dd5d0984b17480717e9a22447426be

**Comment by JaroslavTulach** [comment]
Per [advice by Christian Humer](https://graalvm.slack.com/archives/CNQSB2DHD/p1702416910144029?thread_ts=1622389879.037500&cid=CNQSB2DHD) we can simplify a lot of our `Epb` infrastructure by cc8df8b.

**Comment by JaroslavTulach** [comment]
I wonder what's the effect of these changes on Enso/JavaScript benchmarks:
- running [stdlib benchmarks](https://github.com/enso-org/enso/actions/runs/7192528274)
- running [engine benchmarks](https://github.com/enso-org/enso/actions/runs/7192541964)

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java [hunk 4]
```diff
@@ -74,4 +75,38 @@ public void testInteropWithJavaScript() throws Exception {
...
+  @Ignore
+  @Test
+  public void testParallelInteropWithJavaScript() throws Exception {
+    var source = """
+        from Standard.Base import all
+
+        polyglot java import java.lang.Thread
+
+        foreign js js_array t f = \"\"\"
+            f(300)
```
Comment (JaroslavTulach) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java:88]: Calls `java.lang.Thread.sleep(300)` giving the rest of the test a chance to run in parallel. Alas, that's not supported by current `OtherContextGuestObject.sendImpl` and there is no way in GraalVM 23.1 to hook into that. As such the test is currently `@Ignore`d and I propose to track this as a future work on Enso as well as GraalVM side.

**Comment by JaroslavTulach** [comment]
Since 1d4107a there is a failing [VerifyJavaScriptIsAvailableTest](https://github.com/enso-org/enso/actions/runs/7197297365/job/19604100296?pr=7882#step:10:4011) - running [std libs benchmarks](https://github.com/enso-org/enso/actions/runs/7203981895) to verify influence of such change on startup.

File: build.sbt [hunk 5]
```diff
@@ -1375,11 +1370,15 @@ lazy val instrumentationSettings = frgaalJavaCompilerSetting ++ Seq(
...
       inConfig(Compile)(truffleRunOptionsSettings),
       truffleDslSuppressWarnsSetting,
-      instrumentationSettings
+      instrumentationSettings,
+      libraryDependencies ++= Seq(
+        "org.graalvm.truffle" % "truffle-api"           % graalMavenPackagesVersion % "provided",
+        "org.graalvm.truffle" % "truffle-dsl-processor" % graalMavenPackagesVersion % "provided"
+      )
     )
-    .dependsOn(`polyglot-api`)
```
Comment (JaroslavTulach) [inline build.sbt:1382]: There is no need why `EpbLanguage` shall depend on Scala & other heavyweight dependencies in the `polyglot-api` project. Test written in f87c1f6a46 shall verify some of the enormous set of dependencies of `polyglot-api` aren't present.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java [hunk 6]
```diff
@@ -39,10 +33,68 @@ public abstract class PyForeignNode extends ForeignFunctionCallNode {
...
+      // a foreign object, rather than 'str' type.
+      if (iop.isString(arguments[i])) {
+        arguments[i] = iop.asTruffleString(arguments[i]);
+      }
+    }
+    var res = super.execute(arguments);
+    if (iop.hasMetaObject(res)) {
+      var meta = iop.getMetaObject(res);
+      var name = iop.getMetaQualifiedName(meta);
+      if ("module".equals(name)) {
```
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java:78]: Workaround to support [make_null](https://github.com/enso-org/enso/blob/9fb3d9a2fa9e618c4052c15dcaff49bb6348b011/test/Tests/src/Semantic/Python_Interop_Spec.enso#L74) - e.g. `return None` which currently returns its module rather than `None`.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+  static JsForeignNode build(Object jsFunction, int argumentsCount) {
+    return JsForeignNodeGen.create(jsFunction, argumentsCount);
+  }
+
+  @Specialization
+  Object doExecute(Object[] arguments, @CachedLibrary("foreignFunction") InteropLibrary iop)
+      throws InteropException {
+    var args = new ArgumentsArray(arguments);
+    var self = arguments[0];
+    var raw = iop.invokeMember(getForeignFunction(), "apply", self, args);
```
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java:39]: I'd like to get rid of (most of) `JsForeignNode`, but I cannot. This `apply` trick to set `this` is one (small) reason.

The bigger problem is that Graal.js doesn't like `return` inside of _parse with arguments_ that is used by `parseGeneric` - that's in my opinion fixable on Graal.js side.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java [hunk 8]
```diff
@@ -21,10 +18,7 @@
 import com.oracle.truffle.api.library.ExportMessage;
 import com.oracle.truffle.api.source.Source;
 
-@NodeField(name = "foreignFunction", type = Object.class)
-public abstract class PyForeignNode extends ForeignFunctionCallNode {
-  @Child
-  private CoercePrimitiveNode coercePrimitiveNode = CoercePrimitiveNode.build();
+final class PyForeignNode extends GenericForeignNode {
```
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java:21]: Python integration can in general reuse `GenericForeignNode`, but it has to do additional conversions:
- reported as #7655
- improved as https://github.com/oracle/graalpython/issues/354
- another reported as https://github.com/oracle/graalpython/issues/353
- and others

New versions of GraalPy shall (incrementally) remove the need for these conversions.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java:1]: `RForeignNode` shall no longer be needed as it is covered by `GenericForeignNode`.

File: build.sbt [hunk 9]
```diff
@@ -1178,11 +1178,6 @@ val truffleRunOpts = Seq(
   "-Dpolyglot.compiler.BackgroundCompilation=false"
 )
 
-val truffleRunOptionsNoAssertSettings = Seq(
```
Comment (JaroslavTulach) [inline build.sbt:1181]: Removed as we always run with `-ea`.

File: engine/polyglot-api/src/main/java/org/enso/polyglot/ForeignLanguage.java
Comment (JaroslavTulach) [inline engine/polyglot-api/src/main/java/org/enso/polyglot/ForeignLanguage.java:1]: Cannot use `enum` anymore when we support any installed language via `GenericForeignNode`

File: engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/EpbLanguageDependenciesTest.java [hunk 10]
```diff
@@ -0,0 +1,49 @@
+import static org.junit.Assert.fail;
+
+import org.junit.Test;
+
+public class EpbLanguageDependenciesTest {
+  public EpbLanguageDependenciesTest() {}
+
+  @Test(expected = ClassNotFoundException.class)
+  public void avoidFlatbuffers() throws Exception {
```
Comment (JaroslavTulach) [inline engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/EpbLanguageDependenciesTest.java:9]: There are the dependencies one gets when one `dependsOn(polyglot-api)`. Checking that most of them is now gone.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java [hunk 11]
```diff
@@ -173,8 +173,15 @@ public boolean hasTag(Class<? extends Tag> tag) {
   /** @return the source section of this node. */
   @Override
   public SourceSection getSourceSection() {
-    Node parent = getParent();
-    return parent == null ? null : parent.getSourceSection();
+    var parent = getParent();
+    while (parent != null) {
+      var ss = parent.getSourceSection();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java:178]: Fixes an `assert` that: if `RootNode` has `SourceSection` any `Node` instrumented by `StandardsTag` has to have a `SourceSection` as well.

**Review by JaroslavTulach — APPROVED** [review]
I am fine with the changes. Please review as well. Once the CI gets stable, I'd like to integrate.

**Comment by JaroslavTulach** [comment]
> running [std libs benchmarks](https://github.com/enso-org/enso/actions/runs/7203981895) to verify influence of such change on startup.

Previous benchmarks timed out (on endless loop in Sieve's `Java_Script_Filter` test involving `is_same_object` - e.g 3fa992a). New [run scheduled](https://github.com/enso-org/enso/actions/runs/7206166182).

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala [hunk 12]
```diff
@@ -161,7 +160,7 @@ case object GenerateMethodBodies extends IRPass {
           case lam @ Function.Lambda(_, body, _, _, _, _)
               if findForeignDefinition(
                 body,
-                lang = Some(ForeignLanguage.JS)
+                lang = Some("js")
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala:163]: Can we keep that as a constant somewhere, please?

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java [hunk 13]
```diff
@@ -45,32 +44,39 @@ public void initialize(String preInitializeLanguages) {
...
-                    .build(),
-                true);
+            env.newInnerContextBuilder()
+                .initializeCreatorContext(true)
+                .inheritAllAccess(true)
+                .config(INNER_OPTION, "yes")
+                .build();
       }
-      initializeLanguages(env, innerContext, preInitializeLanguages);
+      // initializeLanguages(env, innerContext, preInitializeLanguages);
```
Comment (hubertp) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: Can be removed?

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java [hunk 14]
```diff
@@ -45,32 +44,39 @@ public void initialize(String preInitializeLanguages) {
...
     }
   }
 
   private static void initializeLanguages(
```
Comment (hubertp) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: Where is that method called from if not from `initialize`?

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java [hunk 15]
```diff
@@ -2,42 +2,19 @@
...
- * and when this wrapping is done.
- *
- * <p>With the structure outlined above, EPB is the only language that is initialized in both inner
- * and outer contexts and thus it is very minimal. Its only role is to manage both contexts and
- * provide context-switching facilities.
- */
+/** An internal language that serves as a bridge between Enso and other supported languages. */
 @TruffleLanguage.Registration(
-    id = ForeignLanguage.ID,
+    id = "epb",
```
Comment (hubertp) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java:9]: `EpbLanguage` constant?

File: build.sbt [hunk 16]
```diff
@@ -1375,11 +1370,23 @@ lazy val instrumentationSettings = frgaalJavaCompilerSetting ++ Seq(
...
+      frgaalJavaCompilerSetting,
       inConfig(Compile)(truffleRunOptionsSettings),
       truffleDslSuppressWarnsSetting,
-      instrumentationSettings
+      commands += WithDebugCommand.withDebug,
+      fork := true,
+      Test / javaOptions ++= Seq(
+        "-Dgraalvm.locatorDisabled=true",
+        s"--upgrade-module-path=${file("engine/runtime/build-cache/truffle-api.jar").absolutePath}"
+      ),
```
Comment (Akirathan) [inline build.sbt]: Please remove these lines. Either remove them altogether, or replace them with `-Dpolyglotimpl.DisableClassPathIsolation=true`.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java [hunk 17]
```diff
@@ -55,11 +32,29 @@ protected void initializeContext(EpbContext context) {
...
+        ForeignEvalNode.build(this, request.getSource(), request.getArgumentNames());
     return foreignEvalNode.getCallTarget();
   }
 
+  static String truffleId(Source langAndCode) {
+    var seq = langAndCode.getCharacters();
+    return seq.subSequence(0, splitAt(seq)).toString().toLowerCase();
+  }
+
+  private static int splitAt(CharSequence seq) {
```
Comment (hubertp) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java]: I think this has been like that forever but it would be nice if we threw some useful error when there is no `#`

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java [hunk 18]
```diff
@@ -0,0 +1,96 @@
...
+    if (foreign == null) {
+      CompilerDirectives.transferToInterpreterAndInvalidate();
+      String truffleLangId = EpbLanguage.truffleId(code);
+      var context = EpbContext.get(this);
+      var installedLanguages = context.getEnv().getInternalLanguages();
+      if (!installedLanguages.containsKey(truffleLangId)) {
+        this.parseException = new ForeignParsingException(truffleLangId, installedLanguages.keySet(), this);
+      } else {
+        switch (truffleLangId) {
+          case "js" -> parseJs();
```
Comment (hubertp) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java]: kind of the reason why I would prefer to have constants

File: project/WithDebugCommand.scala [hunk 19]
```diff
@@ -19,7 +19,7 @@ object WithDebugCommand {
     "-agentlib:jdwp=transport=dt_socket,server=n,address=localhost:5005,suspend=y";
 
   val truffleNoBackgroundCompilationOptions = Seq(
-    "-Dpolyglot.engine.BackgroundCompilation=false"
```
Comment (Akirathan) [inline project/WithDebugCommand.scala]: Revert, this will be fixed in https://github.com/enso-org/enso/pull/8467

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala [hunk 20]
```diff
@@ -1958,12 +1957,13 @@ class IrToTruffle(
...
     private def buildForeignBody(
-      language: ForeignLanguage,
+      language: String,
       code: String,
       argumentNames: List[String],
       argumentSlotIdxs: List[Int]
     ): RuntimeExpression = {
-      val src       = language.buildSource(code, scopeName)
+      val src =
+        Source.newBuilder("epb", language + "#" + code, scopeName).build()
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:1966]: Use something like `EpbLanguage.ID` instead of hard-coding "epb"?

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java (hunk 6 above)
Comment (hubertp) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java:78]: So we can't use `iop.isNull` ?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java [hunk 21]
```diff
@@ -210,7 +208,7 @@ public void initialize() {
 
     var preinit = environment.getOptions().get(RuntimeOptions.PREINITIALIZE_KEY);
     if (preinit != null && preinit.length() > 0) {
-      var epb = environment.getInternalLanguages().get(ForeignLanguage.ID);
+      var epb = environment.getInternalLanguages().get("epb");
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:211]: Do no hardcode "epb". Use `EpbLanguage.ID`. In `build.sbt`, `runtime` project should depend on `runtime-language-epb`, right?

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java [hunk 22]
```diff
@@ -41,11 +41,13 @@ public static void initEnsoContext() {
   public static void closeEnsoContext() throws Exception {
     ctx.close();
 
+    /* XXX: Is this needed for startup?
```
Comment (hubertp) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java]: Why were we even doing that in `AfterClass`? This should probably go completely

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java (hunk 13 above)
Comment (Akirathan) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: Leftover? Remove `initializeLanguages`?

**Review by hubertp — APPROVED** [review]

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java [hunk 23]
```diff
@@ -0,0 +1,99 @@
...
+import com.oracle.truffle.api.interop.TruffleObject;
+import com.oracle.truffle.api.interop.UnsupportedMessageException;
+import com.oracle.truffle.api.library.CachedLibrary;
+import com.oracle.truffle.api.library.ExportLibrary;
+import com.oracle.truffle.api.library.ExportMessage;
+import java.util.Arrays;
+
+/** A node responsible for performing foreign JS calls. */
+@NodeField(name = "foreignFunction", type = Object.class)
+@NodeField(name = "arity", type = int.class)
```
Comment (Akirathan) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java]: This NodeField is not used anywhere?

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java (hunk 22 above)
Comment (Akirathan) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java]: Remove the commented code. I would most likely get rid of that in https://github.com/enso-org/enso/pull/8467 anyway

**Review by Akirathan — COMMENTED** [review]
OK. Would be nice to get rid of some hardcoded strings though.

**Comment by JaroslavTulach** [comment]
There is a [failure in Table_Tests](https://github.com/enso-org/enso/actions/runs/7205787196/job/19629380241#step:10:6025) which can be simulated locally as:
```bash
enso$ JAVA_OPTS=-ea ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --in-project test/Table_Tests --run test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
```

Don't forget that **the CI runs with `-ea` now** and you may need to turn it on locally to see the same failure!

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala (hunk 12 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala:163]: Too much overhead to do so. We would need a new project sharable between all that were using `ForeginLanguage.JS`. But I want to get rid of the heavyweight `polyglot-api` dependency (in `EpbLanguage` at least). I don't want to create new project just to host `js` constant.

Btw. the real constant is defined in `graal-js` and we don't compile against such module. E.g. there was never any guarantee (except tests) that we are using the right constant.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java (hunk 15 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java:9]: Needless. There is only one use of such a constant. Others are in modules that don't compile against this module:

image

They wouldn't be able to use the constant anyway. The fact that this all holds together is ensured by tests.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java (hunk 22 above)
Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java]: Because this used to check that during the existence of `ctx`, the right message is called.

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala (hunk 20 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala:1966]: Too much overhead as explained to Hubert: https://github.com/enso-org/enso/pull/7882#discussion_r1426620505

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java (hunk 21 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java:211]: No. These two projects providing their languages shall be independent and loosely coupled. _The harm is limitted_ to four occurrences https://github.com/enso-org/enso/pull/7882#discussion_r1426623105 and tests exist to ensure it all works together.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java (hunk 23 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java]: It was used [here](https://github.com/enso-org/enso/pull/7882/files/3fa992a7e115ee6f0e3f64af3c52de353448aef5#diff-a2e3756dfa68e081d43ee49566f83821651587e059be6bac47bf1383351b2e25L37).

Good catch. Removed in 3f63d9ec04

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java (hunk 22 above)
Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java]: Updated in ef1c79825a

Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java]: Removed in ef1c79825a

File: project/WithDebugCommand.scala (hunk 19 above)
Comment (JaroslavTulach) [reply project/WithDebugCommand.scala]: Done in 8fda9f5700

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java (hunk 13 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: Removed in ef1c79825a48414f0e9678a4917faf4bcc6d53be

File: build.sbt (hunk 16 above)
Comment (JaroslavTulach) [reply build.sbt]: Removed in 8f08e618d8

**Review by mwu-tow — APPROVED** [review]

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java [hunk 24]
```diff
@@ -2,42 +2,19 @@
...
- * inner context, and inner context values need rewrapping for use in the outer context. See {@link
- * org.enso.interpreter.epb.runtime.PolyglotProxy} and {@link ContextRewrapNode} for details of how
- * and when this wrapping is done.
- *
- * <p>With the structure outlined above, EPB is the only language that is initialized in both inner
- * and outer contexts and thus it is very minimal. Its only role is to manage both contexts and
- * provide context-switching facilities.
- */
+/** An internal language that serves as a bridge between Enso and other supported languages. */
 @TruffleLanguage.Registration(
```
Comment (radeusgd) [inline engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java:8]: Why is this whole block of documentation removed?

**Review by jdunkerley — APPROVED** [review]
Just reviewed the enso files.

**Review by radeusgd — APPROVED** [review]

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java (hunk 24 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java:8]: Done by @Akirathan, but I'd say it no longer reflects reality. Times changed and we no longer have to implement this ourselves, but rather rely on Truffle to do it for us.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java (hunk 18 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java]: I assure you that changing the text to some other value doesn't pass CI. I tried.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java (hunk 17 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java]: Reimplemented in 78d603badb - I like the new structure way more. Thanks for encouraging me to do the cleanup.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java (hunk 14 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: The method is now gone.

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java (hunk 13 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java]: Done [ef1c798](https://github.com/enso-org/enso/pull/7882/commits/ef1c79825a48414f0e9678a4917faf4bcc6d53be)

File: engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java (hunk 24 above)
Comment (JaroslavTulach) [reply engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java:8]: Btw. @kustosz asked why do we need this `EpbLanguage` anymore? True, possibly we could do without it.

**Comment by JaroslavTulach** [comment]
Another [benchmarks run scheduled](https://github.com/enso-org/enso/actions/runs/7213028965) just _to be sure_ - no problems expected however.

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java [hunk 25]
```diff
@@ -44,4 +47,66 @@ public void testForeignFunctionParseFailure() {
...
+
+    var res2 = Executors.newSingleThreadExecutor().submit(() -> {
+      return third.execute(12);
+    }).get();
+
+    assertTrue("It is an array2", res2.hasArrayElements());
+    assertEquals(12, res2.getArrayElement(2).asInt());
+  }
+
+  @Ignore
```
Comment (JaroslavTulach) [inline engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java:79]: I've reported https://github.com/oracle/graal/issues/8033 to describe why this test has to be `@Ignore`d right now.

**Comment by JaroslavTulach** [comment]
Looks like we have a **significant regression** in [Sieve_Java_Script_Filter](https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html) benchmark:

Sieve_Java_Script_Filter

Caused by something in between b5c995a7bfe7f0a58beee2d34686dedc04afb145...940b8f7d511162ccccff26d2fe7cfd095d734d59 and the most likely cause is this PR. Alas.

`Sieve_Java_Script_Natural` benchmark hasn't regressed, so the cause isn't switching from Enso to JavaScript (done a lot to increment a number in the `Sieve_Java_Script_Natural` benchmark), but probably accessing JavaScript objects from Enso (which is what `Sieve_Java_Script_Filter` does).

File: engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java (hunk 25 above)
Comment (JaroslavTulach) [reply engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java:79]: With `onDeniedThreadAccess` as proposed by https://github.com/oracle/graal/pull/8266 we have a way to [act like an Ethernet on collision](https://github.com/enso-org/enso/pull/8885/commits/160f2b81617f459a1a2bf198f940c78e7e7db9ed#diff-a84ceb8a331a33ef55d986aac04b55c48c52f2daddf6bea30911823ab24ff3a7R24) and successfully orchestrate the two threads accessing the same context to run into completion.

More info on [Ethernet collision detection and behavior](https://en.wikipedia.org/wiki/Carrier-sense_multiple_access_with_collision_detection) - most important _"Calculate and wait the random backoff"_.

Continue [discussion at](https://github.com/enso-org/enso/pull/8885/files#r1470552562)...
