### PR TITLE
Problematic warning & suspended return

### LINKED ISSUE #10605: Suspended application of default arguments playing badly with warnings and causing weird behaviour
Consider the following repro `suspending-defaults.enso`:
```ruby
from Standard.Base import all

type My_Table
    Value x

    union self (tables : My_Table | Vector) arg1=1 arg2=2 arg3=3 =
        IO.println "Called ("+self.to_text+").union "+tables.to_text+" with "+arg1.to_text+" "+arg2.to_text+" "+arg3.to_text
        My_Table.Value [self.x, tables, arg1+arg2+arg3]

    columns self =
        "{Columns = "+self.x.to_text+"}"

call_union tables =
    first = tables.first
    rest = tables.drop 1
    first.union rest ...

main =
    check table =
        IO.println table.columns
    check <| call_union [My_Table.Value 1]
    tw = Warning.attach "foo" (My_Table.Value 2)
    check <| call_union [tw]
	check <| call_union [tw] arg2=1000
```

### Actual behaviour

Running the above script yields:
```
Called ((My_Table.Value 1)).union [] with 1 2 3
{Columns = [1, [], 6]}
Called ((My_Table.Value 2)).union [] with 1 2 3
Called ((My_Table.Value 2)).union [] with 1 2 3
Called ((My_Table.Value 2)).union [] with 1 2 3
Execution finished with an error: Method `columns` of type My_Table could not be found.
        at <enso> suspending-defaults.main.check<arg-1>(suspending-defaults.enso:20:20-32)
        at <enso> suspending-defaults.main.check(suspending-defaults.enso:20:9-32)
        at <enso> suspending-defaults.main(suspending-defaults.enso:23:5-28)
```

We can see 2 anomalies here:
1. The second call to `union` is executed **3 times (!)** (as indicated by the prints) even though it should only happen once. We have a problem with re-running a side-effecting computation - that should never happen!
2. Afterwards, the return value is somehow broken and we cannot call the `columns` method on it. Even though in the exactly same scenario above such call has worked all fine.

The difference between first and second calls is only that the second one contains warnings.

### Expected behaviour

The program should print
```
Called ((My_Table.Value 1)).union [] with 1 2 3
{Columns = [1, [], 6]}
Called ((My_Table.Value 2)).union [] with 1 2 3
{Columns = [2, [], 6]}
Called ((My_Table.Value 2)).union [] with 1 1000 3
{Columns = [2, [], 1004]}
```

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- fixes #10605
- provides new test in b6a31868fb01dcc2666595c2f61fad8426957b18
- and then seeks some acceptable solution

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [x] Engine Benchmarks remain fast
    - [first run](https://github.com/enso-org/enso/actions/runs/19730468552)
    - [faster run](https://github.com/enso-org/enso/actions/runs/19759800153)
    - [done](https://github.com/enso-org/enso/pull/14387#discussion_r2573068746)
- [x] StdLib Benchmarks remain fast
    - [first run](https://github.com/enso-org/enso/actions/runs/19730499264)
    - [faster run](https://github.com/enso-org/enso/actions/runs/19759825158)
    - [done](https://github.com/enso-org/enso/pull/14387#discussion_r2573068746)

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java [hunk 1]
```diff
@@ -350,7 +350,10 @@ Object doWarning(
     Object selfWithoutWarnings;
     EnsoHashMap warnsMap;
     try {
-      selfWithoutWarnings = warnings.removeWarnings(self);
+      var selfNoWarnings = warnings.removeWarnings(self);
+      selfWithoutWarnings =
+          ThunkExecutorNode.getUncached()
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java]: - using _uncached node_ here as 72ee7526d7835143c5690243e1011b7de3fe2462 does
   - may affect benchmarks 
- checking [engine benchmarks](https://github.com/enso-org/enso/actions/runs/19730468552)
- checking [stdlib benchmarks](https://github.com/enso-org/enso/actions/runs/19730499264)

**Review by jdunkerley — APPROVED** [review]
Approving the test so libs out the way

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java]: Maybe the `WarningBenchmarks_diffWarningRandomElementsVecSum` engine benchmark is slower:

WarningBenchmarks_diffWarningRandomElementsVecSum

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java]: This stdlib `Map_Error_Benchmark_Array_Proxy_report_warning_Map_Id_All_Errors` benchmark is slower:

Map_Error_Benchmark_Array_Proxy_report_warning_Map_Id_All_Errors

- so is `Map_Error_Benchmark_Array_report_warning_Map_Id_All_Errors`
- and `Map_Error_Benchmark_JavaArrayList_report_warning_Map_Id_Ten_Percent_Errors`
- and `Map_Error_Benchmark_Slice_report_warning_Map_Id_All_Errors`
- and `Map_Error_Benchmark_Vector_report_warning_Map_Id_All_Errors`

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java]: With 8661627 the execution of `WarningBenchmarks` seems back to its original speed locally. 
    - engine [faster run](https://github.com/enso-org/enso/actions/runs/19759800153)
    - stdlib [faster run](https://github.com/enso-org/enso/actions/runs/19759825158)

were scheduled.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InstanceInvokeMethodNode.java]: - Engine benchmarks are fine:

engine

- standard library benchmarks are fine too. For example:

stdlib

**Review by hubertp — APPROVED** [review]
