### PR TITLE
Force pending saves if client closes abruptly

### LINKED ISSUE #6395: Component Browser creates node not visible in the graph editor until Enso restart
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open project that I have worked previously on it opens with one additional node in the scene. It seems that the Component Browser on close with esc key leaves something behind that's not shown in the graph editor. I have managed to reproduce it when I have opened project created on earlier version of Enso (2023.3.25) with a newer one (this time it was 2023.4.18). Also I have noticed it on several other occasions but always assumed I have closed the CB wrongly, please watch attached video when I restart Enso several times and the node appears back.

### Expected behaviour

When I delete a node it stays that way - deleted.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/234004034-f8643df9-b6f4-46f2-ab52-e00a17697a09.mp4

### Enso Version

2023.4.18

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Force pending saves when JsonSession is terminated for the client.

Potentially closes #6395.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala [hunk 1]
```diff
@@ -292,6 +292,11 @@ class LanguageServerController(
         maybeRequester.foreach(_ ! ServerShutdownTimedOut)
         stop()
 
+      case ClientDisconnected(clientId) =>
```
Comment (hubertp) [inline lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala:295]: Extra change that deals with unexpected messages during shutdown:
```
INFO ide_ci::program::command: enso⚠️ [warn] [2023-05-01T10:29:13.187Z] [org.enso.projectmanager.boot.ProjectManager$] Failed to read line.
 INFO ide_ci::program::command: enso⚠️ [info] [2023-05-01T10:29:13.187Z] [org.enso.projectmanager.boot.ProjectManager$] Stopping server...
 INFO ide_ci::program::command: enso⚠️ [info] [2023-05-01T10:29:13.188Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] Killing all servers [List(Actor[akka://project-manager/user/language-server-registry/language-server-controller-21260df1-f569-43d3-b2b2-d70944d8db8b#1107631448])].
 INFO ide_ci::program::command: enso⚠️ [info] [2023-05-01T10:29:13.19Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [9388d3fc-ac7d-4158-96b5-aea97429966b]
 INFO ide_ci::program::command: enso⚠️ [warn] [2023-05-01T10:29:13.19Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Received unknown message: class org.enso.projectmanager.event.ClientEvent$ClientDisconnected
 ```

**Review by JaroslavTulach — APPROVED** [review]
Flushing pending save requests is certainly a good idea.

**Review by Akirathan — APPROVED** [review]
