### PR TITLE
Static parameter in search/completion request affects only methods

### LINKED ISSUE #7805: ls/completion request returns not enough entries.
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While investigating https://github.com/enso-org/enso/issues/7591, I noticed that my CB contains ridiculously small amount of entries.

After investigation, it turns out that the engine never returns us a single Constructor, Module, or Type. The only kind of entry in the response is Method. The statistics look the following:
(engine 9.11, default new project, creating new node without inputs and with zero input from the user)
```
Results: total=1049, modules=0, methods=1049, constructors=0, types=0, never=871, always=31, when_filtered=178, private=871
```

This means we received 1049 entries, all of which are methods. 871 are private (marked with a documentation tag), so we never show them. We show 31 entries by default and can show 178 in total when the user types something.

The issue also happens with the engine `8.16`.

### Expected behaviour

The `ls/completion` response must return modules and constructors as well (I'm not sure about types).

### How we can reproduce it?

You can use https://github.com/enso-org/enso/tree/wip/vitvakatu/debug-ls-completion branch with additional debug logging to get the similar output.

1. Create and open a new project
2. Press Enter to open CB
3. See the output in the console, also observe the list of displayed entries in the CB itself.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

e5425d35a05cc04cb36ea853b42ad6ce330f42a1

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7805 

Changelog:
update: `isStatic` parameter in the `search/completion` request only affects method suggestions

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by hubertp — APPROVED** [review]

File: lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala [hunk 1]
```diff
@@ -765,7 +765,8 @@ final class SqlSuggestionsRepo(val db: SqlDatabase)(implicit
         )
       }
       .filterOpt(isStatic) { case (row, value) =>
-        row.isStatic === value
+        (row.kind === SuggestionKind.METHOD && row.isStatic === value) ||
+        (row.kind =!= SuggestionKind.METHOD)
```
Comment (JaroslavTulach) [inline lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala:769]: `=!=`!

File: lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala [hunk 2]
```diff
@@ -1176,11 +1177,10 @@ class SuggestionsRepoTest
               None,
               Some(true)
             )
-        } yield (id3, res._2)
+        } yield (Seq(id0, id1, id2, id3, id5, id6, id7), res._2)
```
Comment (JaroslavTulach) [inline lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala:1180]: OK, `suggestion.instanceMethod` is missing.

**Review by JaroslavTulach — APPROVED** [review]
