### PR TITLE
Fix uninterpolated-text newline-insertion case

### LINKED ISSUE #9494: Failed property test
https://github.com/enso-org/enso/actions/runs/8343933574/job/22835196642

```
❯ src/util/ast/__tests__/abstract.test.ts > AST text literal rawTextContent (with seed=-684993761)
 INFO ide_ci::program::command: npmℹ️      → Property failed after 89 tests
```

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fixes #9494.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]

File: app/gui2/shared/ast/tree.ts [hunk 1]
```diff
@@ -1428,7 +1428,7 @@ export class MutableTextLiteral extends TextLiteral implements MutableAst {
   setRawTextContent(rawText: string) {
     let boundary = this.boundaryTokenCode()
     const isInterpolated = this.isInterpolated()
-    const mustBecomeInterpolated = !isInterpolated && (!boundary || rawText.includes(boundary))
+    const mustBecomeInterpolated = !isInterpolated && (!boundary || rawText.match(/["\n\r]/))
```
Comment (Frizi) [inline app/gui2/shared/ast/tree.ts:1431]: I suppose we will eventually want to transform those multiline strings to `"""` blocks instead, but this does work for now.

**Review by Frizi — APPROVED** [review]
