### PR TITLE
Fix cut-off in text visualisations

### LINKED ISSUE #6196: JSON visualization does not show the last row
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

It seems that the default visualization cuts slightly the visualization of the last row.
I would expect scrolling to show the missing bits but that doesn't work either.

### Expected behaviour

Should be able to see all data.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

Screenshot from 2023-04-04 16-55-39

See the cut `1` and missing brackets.

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Closes #6196.

Three things were going wrong:
- Not directly contributing, but adding confusion was the fact that padding of 5px was added in two different places. Since the 10px we've had up until now looked better, especially given the size of the rounded corners, I've kept it at 10px, but only applied in one place.
- The main issue was that the length the scrollbars scroll over didn't take padding into account. At the same time, I changed the `max` and `thumb_size` variables to the coordinate system of the content. This is also how they're being used in `ScrollArea`, which is the only other place where `Scrollbar`s are being used.
- The line height of text grid entries was set to the default of 1.2. That's the default line height in browsers, which is great for multi-line text and elements whose height is greater than the line height. In this case, however, where the height and the font size are set to the same value, the default setting of 1.2 pushes the text below the allotted space.

https://user-images.githubusercontent.com/607786/234297411-8c0b3851-5977-4ca5-b3b4-5b0782510e14.mp4

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs [hunk 1]
```diff
@@ -77,6 +77,7 @@ impl Entry {
         let mut style = "position: absolute; white-space: pre; pointer-events: auto;".to_string();
         write!(style, "left: {left}px; top: {top}px;").ok();
         write!(style, "width: {width}px; height: {height}px;").ok();
+        write!(style, "line-height: 1").ok();
```
Comment (wdanilo) [inline app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: What is this? Looks magical. If we need it, it should have doc comment with explanation.

**Review by farmaazon — APPROVED** [review]
Add explanation, as @wdanilo asked.

File: app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs (hunk 1 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: I explained in the PR description, but I'll copy-paste it into a comment.

**Comment by vitvakatu** [comment]
QA passed 🟢

File: app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs (hunk 1 above)
Comment (wdanilo) [reply app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: Hmm, if you are referring to this explanation:

> The line height of text grid entries was set to the default of 1.2. That's the default line height in browsers, which is great for multi-line text and elements whose height is greater than the line height. In this case, however, where the height and the font size are set to the same value, the default setting of 1.2 pushes the text below the allotted space.


Then I do not understand it. I was reading it several times and it's not clear to me. default of 1.2 is great for multi-line text readability, like in our case. We should not change it to 1.0. 

Anyway, you've written "In this case, however, where the height and the font size are set to the same value, the default setting of 1.2 pushes the text below the allotted space":
- Height of what is the same as the font size?
- What is "allotted space"?
- Why these things are "pushed below" this space?

Can we make it working with default line-height?

**Review by wdanilo — CHANGES_REQUESTED** [review]
The text with line-height of 1.0 looks too dense. We should keep the browser's default to make it easy to read. We need to resolve the discussion before merging this PR.

File: app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs (hunk 1 above)
Comment (Procrat) [reply app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: > * Height of what is the same as the font size?

The height of the element this part of the code is defining: the grid view entry.

> * What is "allotted space"?

The vertical space that is available for the text in this element which is fixed by the height which is explicitly set in the line above.

> * Why these things are "pushed below" this space?

Because with a font size of 12px and a line height of 1.2, there's not a enough room in an element that's only 12px high. It needs something like `1.2 * 12px ~= 14px`.

> Can we make it working with default line-height?

Another option might be to make the entry size higher: not set it to any value and let the browser derive it from the font size and line height. Looking at the code, however, it looks like we always let the entry size be set externally, by the component that uses the text grid. That might be substantial change because the grid view is used in a bunch of places. Any other ideas?

Comment (vitvakatu) [reply app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: Wait, can't we just change this line:
https://github.com/enso-org/enso/blob/develop/lib/rust/ensogl/app/theme/hardcoded/src/lib.rs#L590 ?

It sets the height of the grid entry as far as I can see.

Comment (Procrat) [reply app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs:84]: @wdanilo: To make sure there's no confusion here, this PR doesn't change the distance between lines of text. The grid view entries are still fixed to the same height. This just changes where the text appears in relation to the grid view entry div.

**Comment by farmaazon** [comment]
@wdanilo this PR does not worsen the state we have already on develop, so I think we should merge it and make an issue for line spacing in text visualization. The new issue can be added as a fixme in the line you commented. Please unblock the PR.

**Review by wdanilo — APPROVED** [review]
