### PR TITLE
Fix Geo Map visualization

### LINKED ISSUE #8300: GeoMap visualization is not working in gui2
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening GeoMap visualization, it shows nothing and an error is displayed in the console:

image

image

### Expected behaviour

Map visualization shows.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

develop - 5baec46466283c02a04621dcce6323e18b66d72a

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

119.0.6045.123

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fixes #8300
  - Fixes Geo Map visualization being completely broken
  - Fixes Mapbox attribution icon in bottom right being invisible
  - Fixes Mapbox attribution button being unclickable

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

File: app/gui2/src/components/visualizations/GeoMapVisualization.vue [hunk 1]
```diff
@@ -404,18 +404,26 @@ function pushPoints(newPoints: Location[]) {
...
+}
+
+:deep(.mapboxgl-ctrl-attrib.mapboxgl-compact) {
+  min-height: 24px;
+}
+
+/* Copied from mapbox-gl CSS. */
+:deep(.mapboxgl-ctrl-attrib-button.mapboxgl-ctrl-attrib-button) {
+  background-color: hsla(0, 0%, 100%, 0.5);
+  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg width='24' height='24' viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg' fill-rule='evenodd'%3E%3Cpath d='M4 10a6 6 0 1012 0 6 6 0 10-12 0m5-3a1 1 0 102 0 1 1 0 10-2 0m0 3a1 1 0 112 0v3a1 1 0 11-2 0'/%3E%3C/svg%3E");
```
Comment (farmaazon) [inline app/gui2/src/components/visualizations/GeoMapVisualization.vue]: Why is it needed? We link mapbox-gl CSS in index.html. Add a broader explanation, please.

**Review by farmaazon — APPROVED** [review]

File: app/gui2/src/components/visualizations/GeoMapVisualization.vue (hunk 1 above)
Comment (somebody1234) [reply app/gui2/src/components/visualizations/GeoMapVisualization.vue]: added explanation.

**Review by Frizi — APPROVED** [review]
