### PR TITLE
Suspended arguments need one more child scope

### LINKED ISSUE #8937: Suspended default arguments cannot access previous arguments (including `self`)
This was a really nasty one to track down.

This repro demonstrates the problem:
```
from Standard.Base import all

type My_Type
    Value field
    
    member_method self regular_arg ~suspended_default_arg=("Text: {"+self.to_display_text+"}") =
        case regular_arg of
            "B" -> suspended_default_arg
            _ -> "OK"

    other_method self regular_arg not_suspended_default_arg=("Text: {"+self.to_display_text+"}") =
        case regular_arg of
            "B" -> not_suspended_default_arg
            _ -> "OK"

main =
    o = My_Type.Value 100

    IO.println ("With suspended default:")
    IO.println (o.member_method "A")
    IO.println (o.member_method "B")

    IO.println ("With regular default:")
    IO.println (o.other_method "A")
    IO.println (o.other_method "B")
```

## Actual behaviour

```
With suspended default:
OK
Text: {Error: Uninitialized value}
With regular default:
OK
Text: {My_Type.Value}
```

As we can see, if the default argument is not suspended it all works OK - `self` is correct.

However, once the argument is suspended, the `self` within it now is _uninitialized_.

## Expected behaviour

The behaviour should be the same regardless of if the argument is suspended or not.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #8937. Suspended arguments are (unlike normal arguments) evaluated as _thunk_ in its own `VirtualFrame`. They access the other arguments via `MaterializedFrame` closure. That means they need one more _child scope_.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by radeusgd — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala [hunk 1]
```diff
@@ -575,8 +575,13 @@ case object AliasAnalysis extends IRPass {
             name.name
           )
         if (!nameOccursInScope) {
+          val argScope = if (susp) {
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala]: I know how you love my style comments so... this really asks for ternary operator.

**Review by hubertp — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala]: There are no ternary operators in Scala! One has to use `if then else`!

Comment (JaroslavTulach) [reply engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala]: Or are you asking for a one-liner? 2ed8104

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala [hunk 2]
```diff
@@ -575,16 +575,19 @@ case object AliasAnalysis extends IRPass {
...
+            )
 
           val occurrenceId = graph.nextId()
           val definition = alias.Graph.Occurrence.Def(
             occurrenceId,
             name.name,
             arg.getId(),
             arg.getExternalId,
-            susp
+            suspended
```
Comment (4e6) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala:590]: :heart:

**Review by 4e6 — APPROVED** [review]
