### PR TITLE
Fix disappearing cached shapes

### LINKED ISSUE #6125: Component Browser Icons are not on an external screen with different zoom level in Windows 11 Pro
Icons are visible on the laptop main screen but on the external screen they are just squares.

image

Main screen at 150%, external at 175%.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix cached-shapes disappearance when resizing window or moving to differently-shaped monitor (#6125).

The bug:
`CacheShapesPass` relied on old behavior of `display_object.update(..)`: The update used to be finished when the call returned, but now it spawns an asynchronous task. It is now necessary to schedule a task to update the layer's camera after the scene's display object update has propagated its transformation matrix to the pass's layer.

Additional optimization:
- Don't re-render cached shapes when the canvas size changes.

Some cleanups:
- Fix dangling GL texture objects.
- Fix GL framebuffer leak.
- Fix mixed-up GL texture parameters.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~Unit tests have been written where possible.~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs [hunk 1]
```diff
@@ -83,14 +90,32 @@ impl pass::Definition for CacheShapesPass {
...
             instance.new_texture(&output, self.texture_size_device.x, self.texture_size_device.y);
         self.framebuffer = Some(instance.new_framebuffer(&[&texture]));
+        self.texture = Some(texture);
     }
 
     fn run(&mut self, instance: &Instance, _update_status: UpdateStatus) {
+        if !self.camera_ready.get() {
+            // We cannot render before the camera's transformation matrix has been set.
+            return;
+        }
```
Comment (farmaazon) [inline lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs]: I think it won't hurt to make if-else instead of early return.

**Review by farmaazon — APPROVED** [review]

File: lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs [hunk 2]
```diff
@@ -83,14 +90,32 @@ impl pass::Definition for CacheShapesPass {
...
+        // previously-initiated FRP events finish being processed.
+        let handle = frp::microtasks::next_microtask({
+            let camera = self.layer.camera();
+            let scene = self.scene.clone_ref();
+            let camera_ready = Rc::clone(&self.camera_ready);
+            move || {
+                camera.update(&scene);
+                camera_ready.set(true);
+            }
+        });
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs:104]: Hmm, we are updating cameras in `Scene::update_layout` How does this code relate to the update functions in Scene? Everything is probably fine, but I do not understand yet why we are handling the same thing in two places (or maybe my knowledge about the (EnsoGL) world is not up to date now ;)

File: lib/rust/ensogl/core/src/display/render/pass.rs [hunk 3]
```diff
@@ -170,7 +173,7 @@ impl OutputDefinition {
     /// Constructor of the RGBA u8 output with default texture parameters. It is the most popular
     /// option and you should use it to render colors with your passes.
     pub fn new_rgba<Name: Str>(name: Name) -> Self {
-        let internal_format = texture::Rgba;
+        let internal_format = texture::Rgba8;
```
Comment (wdanilo) [inline lib/rust/ensogl/core/src/display/render/pass.rs:176]: Wait, if we've been using wrong format, how on earth was it working? :O

**Review by wdanilo — APPROVED** [review]

File: lib/rust/ensogl/core/src/display/render/pass.rs (hunk 3 above)
Comment (kazcw) [reply lib/rust/ensogl/core/src/display/render/pass.rs:176]: `Rgba` isn't wrong; used with `u8` channel values, it is usually equivalent to using `Rgba8`. However, in some situations the more specific `Rgba8` value can produce a complete texture, when `Rgba` would not; and there are driver (and browser)-specific differences between handling of incomplete textures... So, although there should be more difference here, I think it is safest to provide the most specific value possible.

File: lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs (hunk 2 above)
Comment (kazcw) [reply lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs:104]: The update finishes asynchronously now, due to the `batch` FRP used in layer updates. Other layers work OK because we poll their dirty flags unconditionally when processing all updates, so they eventually see the results of all microtasks--but this layer is only updated once, and its draws only occur once, so we need to know when it's ready.
