### PR TITLE
Use ExternalId for NodeId and preserve it through argument deletions.

### LINKED ISSUE #10311: Tabbing across widgets not working for newly added components
- Add a Date.new component using the CB
- Click into the year widget
- Enter 2024
- Press tab

Expected behaviour:
Focus moves to the year widget

Actual behaviour:
Component is deselected

Interestingly if I click back into the same year widget on my already created component and change the year to 2023 and press tab it now works as expected.

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #10311

Using `ExternalId` for `NodeId` allows us to match the idea of node identity with engine. That means any bugs that would cause the identity to change will be immediately visible on UI due to misplaced metadata or node being unnecessarily rerendered from scratch. This change and an addional bugfix of argument deletion handling makes the node view stable on edits and allows tabbing through arguments.

https://github.com/enso-org/enso/assets/919491/72d9ec29-54ed-4899-aac1-6678a001a21d

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: app/gui2/src/components/CircularMenu.vue [hunk 1]
```diff
@@ -90,8 +90,8 @@ function readableBinding(binding: keyof (typeof graphBindings)['bindings']) {
       />
       <ToggleIcon
         icon="record"
-        class="overrideRecordingButton slot7"
-        data-testid="overrideRecordingButton"
+        class="slot7 record"
```
Comment (vitvakatu) [inline app/gui2/src/components/CircularMenu.vue:93]: What is the reason for this change? It’s not mentioned in PR description, and `record` class is not used in CSS rules.

File: app/gui2/src/components/RecordControl.vue [hunk 2]
```diff
@@ -11,7 +11,7 @@ const emit = defineEmits<{ recordOnce: []; 'update:recordMode': [enabled: boolea
     <div class="control left-end">
       <ToggleIcon
         icon="record"
-        class="iconButton"
+        class="iconButton record"
```
Comment (vitvakatu) [inline app/gui2/src/components/RecordControl.vue]: Here as well

File: app/gui2/src/components/ToggleIcon.vue [hunk 3]
```diff
@@ -27,7 +27,20 @@ const _props = defineProps<{ icon: Icon; label?: string }>()
...
-.toggledOff {
+.toggledOff svg {
   opacity: 0.4;
 }
+
+:is(.toggledOff, .toggledOn):active svg {
+  opacity: 0.7;
+}
+
+.record {
```
Comment (vitvakatu) [inline app/gui2/src/components/ToggleIcon.vue:38]: I see `record` is defined here, but it’s a scoped?

Comment (Frizi) [reply app/gui2/src/components/ToggleIcon.vue:38]: It is scoped, the class is assigned on icon component usage and it applies to the button element.

File: app/gui2/src/components/CircularMenu.vue (hunk 1 above)
Comment (Frizi) [reply app/gui2/src/components/CircularMenu.vue:93]: The record class is defined inside `ToggleIcon` intentionally. I just moved it around a bit, because the style was duplicated.  An alternative to this would be to make a prop for "button type", and select styles based on that. If we had a few more of them, I'd prefer that. But current approach is simpler and we don't need anything more complicated for icons now.

File: app/gui2/src/composables/stackNavigator.ts [hunk 4]
```diff
@@ -44,13 +44,12 @@ export function useStackNavigator(projectStore: ProjectStore, graphStore: GraphS
     graphStore.updateState()
   }
 
-  function enterNode(id: AstId) {
-    const externalId = graphStore.db.idToExternal(id)
-    if (externalId == null) {
+  function enterNode(id: NodeId) {
+    if (id == null) {
```
Comment (kazcw) [inline app/gui2/src/composables/stackNavigator.ts]: Not possible.

File: app/gui2/src/stores/graph/graphDatabase.ts [hunk 5]
```diff
@@ -224,7 +225,7 @@ export class GraphDb {
   })
 
   getNodeFirstOutputPort(id: NodeId): AstId {
-    return set.first(this.nodeOutputPorts.lookup(id)) ?? id
+    return set.first(this.nodeOutputPorts.lookup(id)) ?? this.idFromExternal(id)
```
Comment (kazcw) [inline app/gui2/src/stores/graph/graphDatabase.ts]: This can now return nullish if the input `NodeId` is for a node that hasn't been committed. The typechecker doesn't catch it because `set.first` is wrongly-typed as infallible.

**Review by kazcw — APPROVED** [review]
