### PR TITLE
Fix matching JS strings

### LINKED ISSUE #9202: `case of` fails to match a constant string against a string coming from JS
Repro showing the issue:
```
from Standard.Base import all
import Standard.Base.Errors.Illegal_Argument.Illegal_Argument

get_required_field key js_object = case js_object of
    _ : JS_Object -> js_object.get key if_missing=(Error.throw (Illegal_Argument.Error "Missing required field `"+key+"` in "+js_object.to_display_text+"."))
    _ -> Error.throw (Illegal_Argument.Error "Expected a JSON object, but got "+js_object.to_display_text+".")

foo json =
    x = get_required_field "type" json
    IO.println (x == "aws_auth")
    IO.println ("aws_auth" == x)
    v1 = case x of
        "aws_auth" -> "OK"
        other -> "not ok: "+other.to_display_text

    v2 = case ""+x+"" of
        "aws_auth" -> "OK"
        other -> "not ok: "+other.to_display_text

    [v1, v2]

main =
    j = """
        { "type": "aws_auth" }
    IO.println <| foo j.parse_json
```

### Actual behaviour

```
True
True
[not ok: aws_auth, OK]
```

While `==` works we can see that `case of` fails to match the constant.

However, when we concatenate `""`, the JS string gets converted into Enso `Text` and then the match successfully works.

### Expected behaviour

The script above should yield:
```
True
True
[OK, OK]
```

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

- Fixes #9202 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java [hunk 1]
```diff
@@ -39,9 +42,35 @@ void doText(
     }
   }
 
+  @Specialization
+  void doJavaString(VirtualFrame frame, Object state, String target) {
+    if (textProfile.profile(equalStrings(literal, target))) {
+      accept(frame, state, new Object[0]);
+    }
+  }
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: I'm not exactly sure if this specialization is needed.

I added it as I imagine it would cover a 'fast-path' for Java `String`. The `doInteropString` should also cover that, but I imagine that `asString` may be more expensive.

OTOH, even without the fix - I could not find a failure scenario with a Java String (do we convert them to Enso `Text` more eagerly than JS??), so it feels like it may have been already handled by `doText`.

So I'm not sure if this specialization is useful at all. @JaroslavTulach do you think I should remove or keep it?

**Comment by radeusgd** [comment]
Before adding the fix, the JS test would fail:
image

Afterwards, it is succeeding.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: `HostValueToEnsoNode`?

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java [hunk 2]
```diff
@@ -39,9 +42,35 @@ void doText(
...
+      VirtualFrame frame,
+      Object state,
+      Object target,
+      @CachedLibrary("target") InteropLibrary targetInterop) {
+    try {
+      if (textProfile.profile(equalStrings(literal, targetInterop.asString(target)))) {
+        accept(frame, state, new Object[0]);
+      }
+    } catch (UnsupportedMessageException e) {
+      // `UnsupportedMessageException` should only be thrown if `isString` returned false, but we
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: I think the comment is spurious (we don't add it in other places as the meaning is implied)

**Review by AdRiley — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: I think this one is spurious/redundant but wait on @JaroslavTulach 's opinion

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: Updated:

> Yes, all _string like_ objects should be wrapped into `Text` in Enso. E.g. the bug/fix should really be in `HostValueToEnsoNode`

Looks like `HostValueToEnsoNode` does a conversion of `String` to `Text`, but there is no such conversion for `TruffleObject`. Moreover there probably shouldn't be any such conversion - `TruffleObject` instances are supposed to flow thru the interpreters unchanged (as the Truffle TCK checks)...

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: So I should remove the `doJavaString` branch, but after all I _should keep_ the `doInteropString` branch, as the `HostValueToEnsoNode` is already doing everything it can do - and we just have to keep in mind that we must not only accept `Text` but also `isString` interop objects.

Is my understanding correct @JaroslavTulach ?

**Comment by JaroslavTulach** [comment]
I believe this is the correct fix. We should remove `CoerceNothing` and use :
```diff
diff --git engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
index 76fdc55715..c59b2e90e8 100644
--- engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
+++ engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
@@ -7,10 +7,14 @@ import com.oracle.truffle.api.dsl.NeverDefault;
 import com.oracle.truffle.api.dsl.ReportPolymorphism;
 import com.oracle.truffle.api.dsl.Specialization;
 import com.oracle.truffle.api.interop.InteropLibrary;
+import com.oracle.truffle.api.interop.UnsupportedMessageException;
 import com.oracle.truffle.api.library.CachedLibrary;
 import com.oracle.truffle.api.nodes.Node;
-import org.enso.interpreter.node.expression.foreign.CoerceNothing;
+import com.oracle.truffle.api.profiles.CountingConditionProfile;
+import org.enso.interpreter.runtime.EnsoContext;
 import org.enso.interpreter.runtime.data.text.Text;
+import org.enso.interpreter.runtime.error.WarningsLibrary;
+import org.enso.interpreter.runtime.error.WithWarnings;
 
 /**
  * Converts a value returned by a polyglot call back to a value that can be further used within Enso
@@ -66,12 +70,23 @@ public abstract class HostValueToEnsoNode extends Node {
     return Text.create(txt);
   }
 
-  @Specialization(guards = {"o != null", "iop.isNull(o)"})
+  @Specialization(guards = {"value != null", "iop.isNull(value)"})
   Object doNull(
-      Object o,
+      Object value,
       @CachedLibrary(limit = "3") InteropLibrary iop,
-      @Cached CoerceNothing coerceNothing) {
-    return coerceNothing.execute(o);
+      @CachedLibrary(limit = "3") WarningsLibrary warningsLibrary,
+      @Cached CountingConditionProfile nullWarningProfile) {
+    var ctx = EnsoContext.get(this);
+    var nothing = ctx.getBuiltins().nothing();
+    if (nothing != value && nullWarningProfile.profile(warningsLibrary.hasWarnings(value))) {
+      try {
+        var attachedWarnings = warningsLibrary.getWarnings(value, null, false);
+        return WithWarnings.wrap(ctx, nothing, attachedWarnings);
+      } catch (UnsupportedMessageException e) {
+        return nothing;
+      }
+    }
+    return nothing;
   }
 
   @Fallback
diff --git engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java
index 048c145206..c1a34913ad 100644
--- engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java
+++ engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java
@@ -6,19 +6,20 @@ import com.oracle.truffle.api.nodes.DirectCallNode;
 import com.oracle.truffle.api.nodes.ExplodeLoop;
 import com.oracle.truffle.api.profiles.BranchProfile;
 import org.enso.interpreter.node.ExpressionNode;
+import org.enso.interpreter.node.expression.builtin.interop.syntax.HostValueToEnsoNode;
 import org.enso.interpreter.runtime.error.DataflowError;
 
 /** Performs a call into a given foreign call target. */
 public class ForeignMethodCallNode extends ExpressionNode {
   private @Children ExpressionNode[] arguments;
   private @Child DirectCallNode callNode;
-  private @Child CoerceNothing coerceNothingNode;
+  private @Child HostValueToEnsoNode coerceNode;
   private final BranchProfile[] errorProfiles;
 
   ForeignMethodCallNode(ExpressionNode[] arguments, CallTarget foreignCt) {
     this.arguments = arguments;
     this.callNode = DirectCallNode.create(foreignCt);
-    this.coerceNothingNode = CoerceNothing.build();
+    this.coerceNode = HostValueToEnsoNode.build();
 
     this.errorProfiles = new BranchProfile[arguments.length];
     for (int i = 0; i < arguments.length; i++) {
@@ -48,6 +49,6 @@ public class ForeignMethodCallNode extends ExpressionNode {
         return args[i];
       }
     }
-    return coerceNothingNode.execute(callNode.call(args));
+    return coerceNode.execute(callNode.call(args));
   }
 }

```
for some reason `ForeignMethodCallNode` wasn't doing `HostValueToEnsoNode` conversions. It is surprising Enso even worked!

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java [hunk 3]
```diff
@@ -39,9 +42,26 @@ void doText(
...
+    try {
+      if (textProfile.profile(equalStrings(literal, targetInterop.asString(target)))) {
+        accept(frame, state, new Object[0]);
+      }
+    } catch (UnsupportedMessageException e) {
+      throw CompilerDirectives.shouldNotReachHere(e);
+    }
+  }
+
   @CompilerDirectives.TruffleBoundary
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:62]: `equalStrings` is behind `@TruffleBoundary`, that cannot be fast.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java [hunk 4]
```diff
@@ -39,9 +42,26 @@ void doText(
     }
   }
 
+  @Specialization(
+      guards = {"targetInterop.isString(target)"},
+      limit = "3")
+  void doInteropString(
+      VirtualFrame frame,
+      Object state,
+      Object target,
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:51]: With [my changes](https://github.com/enso-org/enso/pull/9203#issuecomment-1968896105) this specialization isn't needed. It may be needed in other cases, but we don't have a test for it yet. If a `TruffleObject` from other language which `isString` is passed in, then such a specialization might get triggered.

I'd probably change the `target` type to `TruffleObject` and added a guard `!target instanceof EnsoObject`... but it is just a speculation without having a real test.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
Please remove `CoerceNothing` node and apply [this diff](https://github.com/enso-org/enso/pull/9203#issuecomment-1968896105).

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:51]: I was mostly inspired by `EqualsSimpleNode`.

There we **do have** a `equalsStrings` that is relying on `selfInterop.isString`.

I think that case-of should be consistent with Equals in that regard, even if we don't have a test showing it.

Alternatively, if the `coerceNode` is supposed to be enough of a fix, maybe that means that we could remove this specialization from `EqualsSimpleNode`? What do you think?

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: > HostValueToEnsoNode is already doing everything it can do

It does, when it gets called. Which it apparently didn't until [these changes](https://github.com/enso-org/enso/pull/9203#issuecomment-1968896105).

> we must not only accept `Text` but also `isString` interop objects.

Probably we should rewrite `ToJavaStringNode` to accept not only `Text`, but _also `isString` interop objects_.

> should keep the `doInteropString` branch,

Yes, very likely we should keep it.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java]: > Probably we should rewrite `ToJavaStringNode` to accept not only `Text`, but _also `isString` interop objects_.

But `ToJavaStringNode` is described as `"Converts Enso Text to a Java String."`.

We probably will still keep separate execution paths for `Text` type and `isString`, so I'm not sure if we should be modifying `ToJavaStringNode`. At least it does not seem needed for this PR, if I understand things correctly.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 3 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:62]: This has not been changed in this PR at all.

I only made us use the single entry-point `Core_Text_Utils.equals` that should be used for _all_ string equality in Enso (and is used almost everywhere). It still delegates to exactly the same `Normalizer.compare` as before, but now we use the same entry point, so in case we ever change the equality logic we only have to modify one place.

File: engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java (hunk 4 above)
Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:51]: > I'd probably change the `target` type to `TruffleObject` and added a guard `!target instanceof EnsoObject`... but it is just a speculation without having a real test.

As I'm unable to test it, I'd just keep it as is. If without the guard it catches a `Text` it will still work as `Text` should support `asString` anyway. But since we don't even know if it can ever be triggered, it will probably never catch it anyway.

Comment (radeusgd) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:51]: Is that OK?

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java:51]: It's okeyish.

**Review by JaroslavTulach — APPROVED** [review]
