### PR TITLE
More robust work with caches

### LINKED ISSUE #8384: Unused arguments cause `buildEngineDistribution` to generate invalid caches and prevent tests requiring the affected file from running
I have noticed a bug with serialization of `org.enso.compiler.core.ir.expression.warnings.Unused$FunctionArgument`. At first it looked innocuous - just preventing some IR caches from loading - but of course it should just then parse the original source and all should be fine.

Well - unfortunately I have found that for some reason instead of doing that and recovering - in some scenarios (described below) the invalid cache causes the program to fail altogether.

The repro is following:
1. Checkout `develop` and `buildEngineDistribution` in `sbt`.
2. Add a function `foo bar = 42` at the end of `File.enso` - the `bar` argument is unused causing a warning. See patch at the bottom.
3. Again, do `buildEngineDistribution`.
4. Run `.\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\bin\enso --run .\test\Tests\src\System\File_Spec.enso`.

The (4) run fails with:
```
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso: error: The symbol Existing_File_Behavior (module, type, or constructor) does not exist in File.
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso: error: The symbol File_Access (module, type, or constructor) does not exist in File.
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso: error: The symbol File_Permissions (module, type, or constructor) does not exist in File.
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso: error: The symbol Write_Extensions (module, type, or constructor) does not exist in File.
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:47:14: error: The name `Vector` could not be found.
   47 | file_types : Vector
      |              ^~~~~~

(...)

C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:802:39: error: The name `Nothing` could not be found.
  802 |         if file.is_directory.not then Nothing else
      |                                       ^~~~~~~
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:804:40: error: The name `Option` could not be found.
  804 |             options = children.map c-> Option c.name c.name.pretty
      |                                        ^~~~~~
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:805:13: error: The name `Widget` could not be found.
  805 |             Widget.Single_Choice values=options display=Display.Always
      |             ^~~~~~
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:805:57: error: The name `Display` could not be found.
  805 |             Widget.Single_Choice values=options display=Display.Always
      |                                                         ^~~~~~~
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:807:5: warning: Unused function argument bar.
  807 | foo bar = 42
      |     ^~~
Aborting due to 186 errors and 1 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

We can see that constructors like `Nothing` are not resolved correctly - but they are obviously _imported_ at the top of the `File.enso`...

Apparently, adding the unused argument has broken the whole file.

For context, this is what is written out when running the second `buildEngineDistribution`:
```
(...)

[info] Assembly jar up to date: runner.jar
[info] Regenerating manifest for [distribution\lib\Standard\Base\0.0.0-dev].
[info] Generating index for built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base
C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\System\File.enso:807:5: warning: Unused function argument bar.
  807 | foo bar = 42
      |     ^~~
[ERROR] [2023-11-24T13:29:49+01:00] [enso.org.enso.interpreter.caches.ModuleCache] Failed to save cache for Standard.Base.System.File.
java.io.IOException: No persistance for org.enso.compiler.core.ir.expression.warnings.Unused$FunctionArgument
        at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:63)
        at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:56)
        at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:56)
        at org.enso.runtime/org.enso.persist.PerMap.forType(PerMap.java:73)
        at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:67)
        at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:192)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:180)
        at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
        at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
        at org.enso.runtime/org.enso.compiler.pass.analyse.PersistGatherDiagnostics_DiagnosticsMeta.writeObject(PersistGatherDiagnostics_DiagnosticsMeta.java:18)
        at org.enso.runtime/org.enso.compiler.pass.analyse.PersistGatherDiagnostics_DiagnosticsMeta.writeObject(PersistGatherDiagnostics_DiagnosticsMeta.java:4)
        at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
        at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:72)
        at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaMap.writeObject(IrPersistance.java:225)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaMap.writeObject(IrPersistance.java:210)
        at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
        at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistMetadataStorage.writeObject(IrPersistance.java:385)
        at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistMetadataStorage.writeObject(IrPersistance.java:370)
        at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
        at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
        at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:29)
        at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:4)
        at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
        at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:51)
        at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:33)
        at org.enso.runtime/org.enso.persist.Persistance.write(Persistance.java:173)
        at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:147)
        at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:26)
        at org.enso.runtime/org.enso.interpreter.caches.Cache.saveCacheTo(Cache.java:127)
        at org.enso.runtime/org.enso.interpreter.caches.Cache.lambda$save$0(Cache.java:97)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.enso.runtime/org.enso.interpreter.caches.Cache.save(Cache.java:85)
        at org.enso.runtime/org.enso.interpreter.runtime.TruffleCompilerContext.saveCache(TruffleCompilerContext.java:186)
        at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1(SerializationManager.scala:611)
        at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1$adapted(SerializationManager.scala:591)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:68)
[info] Engine package created at built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev
[success] Total time: 67 s (01:07), completed 24 lis 2023, 13:29:51
```

---

<details>
<summary>The patch for `File.enso`</summary>

```diff
Index: distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso	(revision b33285c634984d9270ab05e35c94f1abe3963899)
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso	(date 1700828913032)
@@ -803,3 +803,5 @@
             children = file.list
             options = children.map c-> Option c.name c.name.pretty
             Widget.Single_Choice values=options display=Display.Always
+
+foo bar = 42
```

</details>

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #8384 by making the work with caches more robust.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides. 
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala [hunk 1]
```diff
@@ -578,15 +578,15 @@ private class DefaultPackageRepository(
     val cache = ensurePackageIsLoaded(libraryName).toOption.flatMap { _ =>
       if (!loadedLibraryBindings.contains(libraryName)) {
         loadedPackages.get(libraryName).flatten.foreach(loadDependencies(_))
-        context
+        val cachedBindingOption = context
           .asInstanceOf[TruffleCompilerContext]
           .getSerializationManager()
           .deserializeLibraryBindings(libraryName)
-          .foreach(cache => loadedLibraryBindings.addOne((libraryName, cache)))
+        loadedLibraryBindings.addOne((libraryName, cachedBindingOption))
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala:585]: When I tried to move away a `.bindings` file with:
```bash
enso$ mv ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/.enso/cache/bindings/0.0.0-dev/Standard/Base.bindings x
```
and reading the cache generated `IOException` I noticed that the load is attempted many times. Avoiding it by storing even `None` into the cache. 

CCing @hubertp. Would you recommend a simple way to write a test for this behavior, Hubert?

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java [hunk 2]
```diff
@@ -276,7 +275,7 @@ public void shutdown(boolean waitForPendingJobCompletion) {
 
   private final class ModuleUpdater implements Updater, AutoCloseable {
     private final Module module;
-    private BindingsMap map;
+    private BindingsMap[] map;
```
Comment (radeusgd) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:279]: Why did this become an array?

I can see only the 0-th element is ever accessed.

Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:279]: To allow setting `null` value. I need to differentiate between `null` (e.g. no change) and `null` being set. Hence one argument array.

Comment (hubertp) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:279]: Can you add a comment, please? I would expect having some kind of a flag for that, normally. Someone might accidentally "optimize" this if they don't see the real intention. It being a `record` would probably serve as a sufficient documentation.

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala (hunk 1 above)
Comment (hubertp) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala:585]: dunno about anything simple. So far we don't seem to have **any** framework for testing this functionality.

Comment (hubertp) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala:585]: So this looks _mostly_ like a cosmetic change because either way we `flatMap` on the result.

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala:585]: I don't think it is cosmetic. I need to run my code even on `None`. `None.foreach` is no-op (isn't it?) - e.g. it wouldn't record the `None` result into the map.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:279]: This is just repeating the same (undocumented) pattern as used on the next line with `org.enso.compiler.core.ir.Module[] ir`. Array is certainly less heavyweight in terms of bytecode than `record`. I was considering to use `AtomReference<BindingsMap>`, but then I decided that single element array is the simplest.

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java [hunk 3]
```diff
@@ -389,23 +393,15 @@ public PersistDiagnosticStorage() {
     }
 
     @Override
-    protected void writeObject(DiagnosticStorage obj, Output out) throws IOException {}
+    protected void writeObject(DiagnosticStorage obj, Output out) throws IOException {
+      out.writeInline(List.class, obj.toList());
```
Comment (Akirathan) [inline engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java:397]: Now that the `DiagnosticStorage` is persisted again, how will this affect the overall size of serialized IR? I have a feeling that originally, you said that we do not want to serialize `DiagnosticStorage` as the size of serialized IR would explode.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java (hunk 2 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java:279]: Test written in 7ab2ed2

File: engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java (hunk 3 above)
Comment (JaroslavTulach) [reply engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java:397]: A task for #8323

A quick check shows increase of size from 6618628 to 6685750 for the biggest `Standard/Database/Data/Table.ir`.
