### PR TITLE
Avoid loading Python classes during context initialization

### LINKED ISSUE #13760: Regression in JVM startup benchmarks due to Python initialization
354ms in Python initialization

- setting this property is likely causing premature initialization of `PythonLanguage` 
- when Truffle finds `python.*` option, it must initialize the language
- but in majority of Enso usages, we don't need Python (unless there is `foreign python method` definition)
- how can one tell Python where its home is, but **delay initialization** of the `PythonLanguage`?
- first observed in https://github.com/enso-org/enso/pull/13723#issuecomment-3173348371

Startup_Slowdown

- all JVM `Startup_Xyz` benchmarks are slowed down
- Native Image startup isn't affected (as Python is missing)

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #13760

### Pull Request Description

Previously, 12 thousand classes from `com.oracle.graal.python` were loaded during context creation even if no python code was executed. With this PR, only 3 classes are loaded.

### Important Notes

- Avoid unnecessary loading of thousands of classes from `com.oracle.graal.python` by not setting `python` option in https://github.com/enso-org/enso/blob/28bcb2cb25f01bbedf747bd5b19203718e5bed8d/engine/common/src/main/java/org/enso/common/ContextFactory.java#L203-L205
- An empty [PythonResourceProvider](https://github.com/enso-org/enso/blob/61713edc88f23af29e917d64f04c456cfdb5b163/engine/python-resource-provider/src/main/java/org/enso/python/resource/provider/PythonResourceProvider.java) needs to be provided for this machinery to work. See its docs.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Check startup benchmarks for improvement.
- [X] The documentation has been updated, if necessary.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [X] Unit tests have been written where possible.

### CODE REVIEW

**Comment by Akirathan** [comment]
## How to ensure that python-home resource is loaded at runtime?

Either set `polyglotimpl.TraceInternalResources` system prop to true. See https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/InternalResourceRoots.java#L348

or:
```diff
diff --git a/engine/common/src/main/java/org/enso/common/ContextFactory.java b/engine/common/src/main/java/org/enso/common/ContextFactory.java
index 0a0418ec30..5abfc6ed5f 100644
--- a/engine/common/src/main/java/org/enso/common/ContextFactory.java
+++ b/engine/common/src/main/java/org/enso/common/ContextFactory.java
@@ -208,6 +208,9 @@ public final class ContextFactory {
             .allowExperimentalOptions(true)
             .allowAllAccess(true)
             .allowHostAccess(allWithTypeMapping())
+            .option("log.python.com.oracle.graal.python.builtins.Python3Core.level", "FINEST")
+            .option("log.python.com.oracle.graal.python.PythonLanguage.level", "FINEST")
+            .option("log.python.com.oracle.graal.python.runtime.PythonContext.level", "FINEST")
             .option(RuntimeOptions.STRICT_ERRORS, Boolean.toString(strictErrors))
             .option(RuntimeOptions.DISABLE_LINTING, Boolean.toString(disableLinting))
             .option(RuntimeOptions.WAIT_FOR_PENDING_SERIALIZATION_JOBS, "true")
diff --git a/engine/runner/src/main/resources/application.conf b/engine/runner/src/main/resources/application.conf
index eadd3e22e4..c7deca153d 100644
--- a/engine/runner/src/main/resources/application.conf
+++ b/engine/runner/src/main/resources/application.conf
@@ -8,6 +8,7 @@ logging-service {
     akka.stream = error
     org.apache.poi.openxml4j.opc = warn
     Standard.Base.Logging.Progress = error
+    python.com.oracle.graal.python = trace
   }
   appenders = [
       {
```

and make sure there are no WARN messages from `com.oracle.graal.python.PythonLanguage`

**Comment by Akirathan** [comment]
## How to ensure no unnecessary Python classes are loaded?

Either simply wait for benchmark results mentioned in #13760, or use JFR:
- Use JFR profile with event name `jdk.ClassLoadingStatistics` enabled:
```
    <event name="jdk.ClassLoadingStatistics">
      <setting name="enabled">true</setting>
      <setting name="period">1000 ms</setting>
    </event>
```
- Run Enso with `JAVA_TOOL_OPTIONS="-XX:+FlightRecorder -XX:StartFlightRecording=filename=flight.jfr,settings=my-profile.jfc"`
- Inspect loaded classes either via JDK Mission Control. or via something like this:
```java
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import jdk.jfr.consumer.RecordedClass;
import jdk.jfr.consumer.RecordedEvent;
import jdk.jfr.consumer.RecordedFrame;
import jdk.jfr.consumer.RecordingFile;
import java.nio.file.Path;

class ReadJFR {

  public static void main(String[] args) throws IOException {
    Path jfrPath;
    if (args.length == 0) {
      jfrPath = Path.of("/Users/pavel/dev/enso/flight.jfr");
    } else {
      jfrPath = Path.of(args[0]);
    }
    var pythonClassesLoaded = new HashSet<String>();
    try (RecordingFile recordingFile = new RecordingFile(jfrPath)) {
      while (recordingFile.hasMoreEvents()) {
        var event = recordingFile.readEvent();
        if (event.getEventType().getName().equals("jdk.ClassLoad")) {
          var recordedClass = (RecordedClass) event.getValue("loadedClass");
          var className = recordedClass.getName();
          if (className.startsWith("com.oracle.graal.python")) {
            pythonClassesLoaded.add(className);
          }
        }
      }
    }
    System.out.println("Loaded Python classes (" + pythonClassesLoaded.size() + "): ");
  }
}
```

On develop, the number of loaded classes with prefix `com.oracle.graal.python` is more than 12 thousand, even without executing any Python code. On this PR, only 3 such classes are loaded.

**Comment by Akirathan** [comment]
Startup benchmarks scheduled at https://github.com/enso-org/enso/actions/runs/17076575633

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@37039ec</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Benchmark Standard Libraries · enso-org/enso@37039ec</div></blockquote>

**Comment by Akirathan** [comment]
The startup slowdown is fixed:
image

image

image

File: engine/common/src/main/java/org/enso/common/ContextFactory.java [hunk 1]
```diff
@@ -193,8 +200,8 @@ public Context build() {
         engineOptions.put(runtimerServerKey, "true");
       }
     }
-    if (pythonHome != null) {
-      options.put("python.PythonHome", pythonHome);
```
Comment (JaroslavTulach) [inline engine/common/src/main/java/org/enso/common/ContextFactory.java:197]: Replacing one property by another (as @eregon suggested, thanks) seems like an easy fix.

**Comment by JaroslavTulach** [comment]
> ## How to ensure that python-home resource is loaded at runtime?

- Why don't you turn this into a JUnit test?
- Use `ObservedMessage` to collect logs from `log.python.com.oracle.graal.python` & co.
- initialize context
- check there are no _"extraction messages"_
- check there is no _sign of python classloading_
- FYI: tutorial [Advanced Usage of Logging](https://wiki.apidesign.org/wiki/FlowControllingTest#Advanced_usage_of_Logging) in tests

**Review by JaroslavTulach — APPROVED** [review]
- Good to see the startup time regression fixed. 
- I'd add a unit test.

**Comment by Akirathan** [comment]
> I'd add a unit test

It was a bit tough. But I think I have finally managed to do it in 3f68bc1d692fe9473824df839b906bef1f0c45b6.

**Comment by JaroslavTulach** [comment]
> > I'd add a unit test
> 
> It was a bit tough. But I think I have finally managed to do it in [3f68bc1](https://github.com/enso-org/enso/commit/3f68bc1d692fe9473824df839b906bef1f0c45b6).

- that's enormously huge piece of Enso code!
- I don't like it is spawning a new process
   - it is slow and running `test/Base_Tests` already takes ages
   - we have `org.graalvm.polyglot` API and we can do better
- I was asking for:

> - Why don't you turn this into a **JUnit** test?
> - Use `ObservedMessage` to collect logs from log.python.com.oracle.graal.python & co.
> - initialize context
> - check there are no "extraction messages"
> - check there is no sign of python classloading

- the checking/processing of the logs is correct in 3f68bc1d692fe9473824df839b906bef1f0c45b6
- however can it be a **JUnit** test?
- can it run in the same JVM?
- can the logs be collected in memory (for example by `ObservedMessage`)

**Comment by Akirathan** [comment]
> however can it be a JUnit test? can it run in the same JVM?

It cannot. One important thing that I wanted to test is that the Python's language home is resolved inside `built-distribution`. When JUnit tests run, there is no `built-distribution` yet. For example, `runtime-integration-tests` run with `python-resources.jar` on the module-path, which means that the Python's language home in that case will be resolved to the directory that GraalPy unpacks at runtime. This is not the behavior we desire in our product.

I can see the controversy about putting this [Python_Resource_Spec](https://github.com/enso-org/enso/blob/3f68bc1d692fe9473824df839b906bef1f0c45b6/test/Base_Tests/src/System/Python_Resource_Spec.enso) into Base_Tests. I was thinking that maybe Examples_Tests would be a better place. **But `Examples_Tests` are not executed at all on the CI**. They were disabled in https://github.com/enso-org/enso/pull/12948/commits/2a8c686696782e431b0f0aee9a8faed8da90328c.

TL;DR:
- It is not possible to test this behavior in JUnit test
- Moving it to Examples_Tests is equivalent to not having any tests at all, since Examples_Tests are not executed at all.

**Comment by Akirathan** [comment]
Increase verbosity of test failure in 3c848cb74a4ddeaa6f7404ce2a0d40905d647a23 to help debug Windows failure at https://github.com/enso-org/enso/actions/runs/17125894196/job/48586384414?pr=13812#step:14:1229.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Avoid loading Python classes during context initialization · enso-org/enso@a56f618</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Avoid loading Python classes during context initialization · enso-org/enso@a56f618</div></blockquote>

**Comment by JaroslavTulach** [comment]
> **But `Examples_Tests` are not executed at all on the CI**. They were disabled in [2a8c686](https://github.com/enso-org/enso/commit/2a8c686696782e431b0f0aee9a8faed8da90328c).

The answer to this isn't to give up, but ask @4e6 to enable the tests again!

**Comment by 4e6** [comment]
Examples_Tests are still failing https://github.com/enso-org/enso/pull/13845

**Review by AdRiley — APPROVED** [review]
