### PR TITLE
Tooltips fixes

### LINKED ISSUE #10999: Tooltip Issues with Viz dropdown buttons
If I make the tooptip display for the table viz dropdown buttons (The formatting ones) there are 2 issues

1. I *think* when I click the button the tooltip should disappear. (I might be wrong)
2. When I change between options in the dropdown the tooltip flashes in the very top left of my screen

https://github.com/user-attachments/assets/7756abb8-f4dc-4d8c-b83c-14fdc311a0f9

Version 2024.4.1-nightly.2024.9.6
Build 6c80f8f05eac7ebe5dfd8479e81458f5ba2f1185
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.4.1-nightly.2024.9.6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Closes #10999

Fixes three issues with tooltips:
- Tooltips for buttons (in fact the only place where they are used) are now hidden when the button is clicked.
- Tooltips no longer jump to random locations when the target element is unmounted.
- Elements without tooltips no longer contribute to timeouts.

https://github.com/user-attachments/assets/9af25d7c-2d0c-48dc-8be6-66d6db98278f

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/MenuButton.vue [hunk 1]
```diff
@@ -13,14 +14,18 @@ import TooltipTrigger from '@/components/TooltipTrigger.vue'
 
 const toggledOn = defineModel<boolean>({ default: undefined })
 const props = defineProps<{ disabled?: boolean | undefined; title?: string | undefined }>()
+const tooltipTrigger = ref<typeof TooltipTrigger>()
```
Comment (farmaazon) [inline app/gui/src/project-view/components/MenuButton.vue]: Wait, so you don't need `ComponentInstance` or `ComponentExposed` here?

File: app/gui/src/project-view/components/TooltipDisplayer.vue [hunk 2]
```diff
@@ -11,37 +10,91 @@ const TOOLTIP_SHOW_DELAY_MS = 1500
...
+  ) {
+    return activeTooltip.value
+  }
+  if (
+    previousTooltip.value != null &&
+    !previousTooltip.value.entry.isHidden &&
+    previousTooltip.value.element.isConnected
+  ) {
+    return previousTooltip.value
+  }
```
Comment (farmaazon) [inline app/gui/src/project-view/components/TooltipDisplayer.vue:71]: Please add a comment explaining why we sometimes display the tooltip at the previous element - I think it's not obvious without the context of the bug you're fixing.

File: app/gui/src/project-view/providers/tooltipRegistry.ts [hunk 3]
```diff
@@ -46,20 +52,32 @@ export const [provideTooltipRegistry, useTooltipRegistry] = createContextStore(
...
             registeredElements.add(target)
           },
           onTargetLeave(target: HTMLElement) {
             const entriesSet = hoveredElements.get(target)
-            entriesSet?.delete(entry)
+            if (entriesSet) {
+              for (const e of entriesSet) {
+                if (e.key === key) entriesSet.delete(e)
+              }
+            }
```
Comment (farmaazon) [inline app/gui/src/project-view/providers/tooltipRegistry.ts:76]: We may have quite a lot of entries in this set - could it be a map?

Also, why didn't the previous approach work? In general I feel a bit more documentation would be helpful; for example I don't get why `hoveredElements` is map of HTMLElement  -> Set - do we have many tooltips registered for single HTML element?

**Review by farmaazon — APPROVED** [review]
I miss some docs, otherwise is good to go.

File: app/gui/src/project-view/components/MenuButton.vue (hunk 1 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/MenuButton.vue]: Well, not really, tsc is happy 🤷🏻‍♂️ I added just for consistency.

File: app/gui/src/project-view/providers/tooltipRegistry.ts (hunk 3 above)
Comment (vitvakatu) [reply app/gui/src/project-view/providers/tooltipRegistry.ts:76]: The set is usually just one element long. But in case of nested tooltip triggers (which are extremely rare) it can be longer.

File: app/gui/src/project-view/components/TooltipDisplayer.vue (hunk 2 above)
Comment (vitvakatu) [reply app/gui/src/project-view/components/TooltipDisplayer.vue:71]: Done
