### PR TITLE
Runtime check of ascribed types

### LINKED ISSUE #6682: Clearly report type errors on API boundary
Currently Enso is using _"duck typing"_ - e.g. one can invoke a function with any argument and if such argument has the right methods, fields, etc. as expected, the execution goes on. Such a behavior is causing issues in the IDE - when a wrong node is connected as an argument (a `Text` instead of `Number` for example), the execution isn't rejected immediately, but proceeds until the _"duck typing"_ fails. However that is often late, deeply in the standard libraries internals and produces _hard to understand errors_. It'd be way better if the _typing error_ was caught right on the **API boundary**.

```
type Num
    All a
    Value (x : Num)
```

Let's use the _ascribed types_ for real type checks. With the above type definition, the following would execute OK: `Num.All "ok"`, but invoking `Num.Value "error"` would rise a `Type_Error`. Similarly with a

```
check (n : Num) = n
```

Invoking `check "error"` shall yield an error while `check (Num.All "ok")` shall be fine. There is a [proof of concept branch](https://github.com/enso-org/enso/compare/wip/jtulach/AscribedTypes_6682) demonstrating it can all work.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Implements #6682 - by adding a (raw) type check at each ascribed type. 

### Important Notes

The check is only performed for `(x : X)` ascription -  both in constructor definitions as well as function definitions. That means the check is _opt-in for functions_ - as our functions don't use such ascription so far or only at few places.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides. 
- All code has been tested and improved:
  - [x] Unit tests have been written where possible.
  - [x] Type error: expected `column` to be `Text | Integer`, but got `Column`. **Done** in: 89a5150e7396
  - [x] QA: verify positive effect on UX in the IDE - it [has positive effect](https://github.com/enso-org/enso/pull/6790#issuecomment-1567947723)

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
[ConversionMethodsTest](https://github.com/enso-org/enso/actions/runs/5043954872/jobs/9046393944?pr=6790#step:10:5577) is failing for polyglot `Map` values. The Enso code is:
```haskell
 polyglot java import java.util.Map as Java_Map
 import Standard.Base.Data.Map.Map

 type Foo
    Mk_Foo data

 Foo.from (that:Map) = Foo.Mk_Foo that

 main =
     jmap = Java_Map.of "A" 1 "B" 2 "C" 3
     Foo.from jmap . data . size
```
the problem is `that` is `java.util.Map` and not Enso `Map` and the type check fails. CCing @Akirathan - there may be some inconsistency:
```haskell
polyglot java import java.util.Map as Java_Map
import Standard.Base.Data.Map.Map
import Standard.Base.Meta

main =
    jmap = Java_Map.of "A" 1 "B" 2 "C" 3
    r1 = Meta.type_of jmap
    r2 = jmap.is_a Java_Map
    r3 = jmap.is_a Map
    [r1, r2, r3]
```
returns `[java.util.ImmutableCollections$MapN, True, False]` - e.g. `Java_Map` is not `Map`, but the conversion works!

Some consistency is needed:
- if something `hasHashEntries`, then it is a map: b5125a3
- `ValuesGenerator` shall create some polyglot maps: done in - #6803
- similar `is_a` checks are likely needed for other polyglot conversions

**Comment by JaroslavTulach** [comment]
Failure after recent integration:
* [MetaIsATest.consistencyWithCase](https://github.com/enso-org/enso/actions/runs/5056072441/jobs/9073092502?pr=6790#step:10:5381)

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java [hunk 1]
```diff
@@ -9,155 +17,207 @@
...
+      return checkParentTypes(numbers.getBigInteger(), expectedType);
+    }
 
-  @ExplodeLoop
-  private boolean checkParentTypes(Type actual, Type expected) {
-    for (; ; ) {
-      if (actual == null) {
-        return false;
+    @Specialization
+    boolean doUresolvedSymbol(Type expectedType, UnresolvedSymbol value) {
```
Comment (GregoryTravis) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]: Typo: doUnresolvedSymbol

**Review by GregoryTravis — APPROVED** [review]

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 2]
```diff
@@ -240,7 +241,22 @@ class IrToTruffle(
...
+            val tpe = unprocessedArg.ascribedType
+              .map(t => {
+                t.getMetadata(TypeNames) match {
+                  case Some(
+                        BindingsMap
+                          .Resolution(BindingsMap.ResolvedType(mod, tpe))
+                      ) => {
+                    val t = mod.unsafeAsModule().getScope.getTypes.get(tpe.name)
+                    t
+                  }
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]:
```suggestion
                      ) =>
                  mod.unsafeAsModule().getScope.getTypes.get(tpe.name)
```

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 3]
```diff
@@ -1651,7 +1667,20 @@ class IrToTruffle(
...
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]:
```suggestion
                      ) =>
                  mod.unsafeAsModule().getScope.getTypes.get(tpe.name)
```

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala [hunk 4]
```diff
@@ -44,7 +44,20 @@ case object TypeNames extends IRPass {
...
+      doResolveType(
+        Nil,
+        bindingsMap,
+        mapped match {
+          case typ: IR.Module.Scope.Definition.Type =>
+            typ.members.foreach(m => {
+              m.arguments.foreach(a => {
+                doResolveType(typ.params.map(_.name), bindingsMap, a)
+              })
+            })
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala]:
```suggestion
            typ.members.foreach(m =>
              m.arguments.foreach(a =>
                doResolveType(typ.params.map(_.name), bindingsMap, a)
              )
            )
```

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala [hunk 5]
```diff
@@ -86,6 +86,11 @@ case object TypeSignatures extends IRPass {
         res
       case meth: IR.Module.Scope.Definition.Method =>
         val newMethod = meth.mapExpressions(resolveExpression)
+        val arr = newMethod.body match {
+          case fn: IR.Function => verifyAscribedArguments(fn.arguments)
+          case _               => newMethod
+        }
+        arr.getClass()
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala:93]: ?

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala [hunk 6]
```diff
@@ -130,6 +135,9 @@ case object TypeSignatures extends IRPass {
         lastSignature = None
         res
       case ut: IR.Module.Scope.Definition.Type =>
+        ut.members.foreach(d => {
+          verifyAscribedArguments(d.arguments)
+        })
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala]:
```suggestion
        ut.members.foreach(d =>
          verifyAscribedArguments(d.arguments)
        )
```

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala [hunk 7]
```diff
@@ -164,6 +172,22 @@ case object TypeSignatures extends IRPass {
...
+    * @param fn the function to check arguments for
+    */
+  private def verifyAscribedArguments(
+    arguments: List[IR.DefinitionArgument]
+  ): Unit = {
+    arguments.foreach(arg => {
+      arg.ascribedType.map(t => {
+        arg.updateMetadata(this -->> Signature(t))
+      })
+    })
```
Comment (hubertp) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala]:
```suggestion
    arguments.foreach(arg =>
      arg.ascribedType.map(t =>
        arg.updateMetadata(this -->> Signature(t))
      )
    )
```

**Review by hubertp — APPROVED** [review]
LGTM minus some stye changes

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentNode.java [hunk 8]
```diff
@@ -14,22 +20,31 @@
 public class ReadArgumentNode extends ExpressionNode {
   private final int index;
   @Child ExpressionNode defaultValue;
+  @Child IsValueOfTypeNode checkType;
   private final ConditionProfile defaultingProfile = ConditionProfile.createCountingProfile();
+  // XXX: Type in a Node is wrong!!!!!
+  private final Type expectedType;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentNode.java]: This is wrong as described in 
- #6809

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java [hunk 9]
```diff
@@ -9,155 +17,207 @@
...
 
-      while (tpe != superTpe && superTpe != null) {
-        boolean testSuperTpe = isSameObject.execute(expectedType, superTpe);
-        if (testSuperTpe) {
-          return true;
-        }
-        tpe = superTpe;
-        superTpe = superTpe.getSupertype();
+    @Specialization(guards = {"isMapType(expectedType, iop)", "iop.hasHashEntries(payload)"})
+    boolean doMap(
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]: I am no longer sure this is good idea. We'd rather concentrate all the logic of checking the type into a single node. I guess I revert changes in this file and just treat everything that `hasHashElements` as `Map` in `TypeOfNode`. While trying to do so I decided to do a bit of cleanup: 
- #6819

**Review by jdunkerley — APPROVED** [review]
Just approving the enso stuff.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 10]
```diff
@@ -98,4 +100,56 @@ public void ascribedWithAParameter() throws Exception {
...
+    } catch (PolyglotException ex) {
+      assertEquals("Type_Error.Error", ex.getMessage());
+    }
+    try {
+      var v = module.invokeMember("eval_expression", "Bin.One Zero");
+      fail("Expecting an error, not " + v);
+    } catch (PolyglotException ex) {
+      assertEquals("Type_Error.Error", ex.getMessage());
+    }
+  }
```
Comment (radeusgd) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: I see a typechecking test for the type ascriptions in the constructor.

From the PR description, this also implements typechecking for ascriptions in methods, right? But I don't see any tests showing it.

Unless I'm missing something, can we get a test case for functions?

Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: Btw. do you think it could be useful to also allow syntax like:
```
foo (v : Vector Integer) =
    x : Integer = v.first
    y : Integer = v.first
    x + y
```
i.e. an ascription at local variable definition could also verify the type.

Not for this PR, since I checked and currently:
```
> (x : Integer) = 42
Evaluation failed with: Syntax error: Syntax is not supported yet: qualifiedNameSegment.
```
so we would need some parser improvements first.

But I think it could be a good next step to allow us to easily 'assert' types, not only in public signatures but also in the implementation.

**Comment by radeusgd** [comment]
So if I understand correctly, if I write:
```
foo (x : Integer) = ...
```
the `x` will be checked to be `Integer` when the function is called.

but if I write:
```
foo : Integer -> Nothing
foo x = ...
```
no check is performed. Correct?

I assume we will want to migrate many (most?) of our public methods to the `(x : X)` syntax then. Does that mean we should try to integrate #5987 soon? (I'm looking if there is an issue related to this discussion) Otherwise we'd have to lose the return type, which while not needed by the engine, is a very useful piece of documentation. Or shall we temporarily 'duplicate' type signatures and write signatures like:
```
    zip : Table -> Boolean | Report_Unmatched -> Text -> Problem_Behavior -> Table
    zip self (right : Table) (keep_unmatched:Boolean|Report_Unmatched = Report_Unmatched) (right_prefix:Text = "Right ") (on_problems:Problem_Behavior=Report_Warning) =
```
?

**Comment by JaroslavTulach** [comment]
> So if I understand correctly, if I write:
> 
> ```
> foo (x : Integer) = ...
> ```
> 
> the `x` will be checked to be `Integer` when the function is called.
> 
> but if I write:
> 
> ```
> foo : Integer -> Nothing
> foo x = ...
> ```
> 
> no check is performed. Correct?

That's correct for this PR, but the ultimate goal is different.

> I assume we will want to migrate many (most?) of our public methods to the `(x : X)` syntax then. 

Using the ascribed type is a nice **opt-in**. We don't use such syntax now for function definitions and we can incrementally migrate to using it.

> Does that mean we should try to integrate #5987 soon? 

Not really necessary. Wojciech explained to me that the former type signatures aren't going away. Imagine you have a variable `fn` and you want to type it. The `Any -> Any -> Any -> Text` syntax is still going to be needed. E.g. #5987 is just an alternative.

The ultimate goal is to turn the runtime checking into **opt-out** - e.g. make sure that even in 

```
foo : Integer -> Nothing
foo x = ...
```

the type of `x` is subject to runtime check. However that's going to take way more work and isn't subject of this PR.

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java [hunk 11]
```diff
@@ -9,85 +17,40 @@
...
-        return true;
-      }
-      actual = actual.getSupertype();
-    }
+  @Specialization(guards = {"!types.hasType(payload)"})
+  boolean doPolyglot(
+      Object expectedType,
+      Object payload,
+      @CachedLibrary(limit = "3") TypesLibrary types,
+      @Cached Untyped typed) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]:
```suggestion
      @Cached Untyped untyped) {
```

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java [hunk 12]
```diff
@@ -9,85 +17,40 @@
...
   }
 
-  @Specialization(guards = {"!isArrayType(expectedType)", "!isAnyType(expectedType)"})
-  boolean doType(Type expectedType, Object payload) {
+  private static boolean typeAndCheck(
+      Object payload,
+      Object expectedType,
+      TypeOfNode typeOfNode,
+      IsSameObjectNode isSameObject,
+      ConditionProfile profile) {
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]:
```suggestion
      ConditionProfile isSameObjectProfile) {
```

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 13]
```diff
@@ -240,7 +241,22 @@ class IrToTruffle(
 
           for (idx <- atomDefn.arguments.indices) {
             val unprocessedArg = atomDefn.arguments(idx)
-            val arg            = argFactory.run(unprocessedArg, idx)
+            val tpe = unprocessedArg.ascribedType
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: minor: rename to `expectedType`?

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala [hunk 14]
```diff
@@ -240,7 +241,22 @@ class IrToTruffle(
...
+                        BindingsMap
+                          .Resolution(BindingsMap.ResolvedType(mod, tpe))
+                      ) => {
+                    val t = mod.unsafeAsModule().getScope.getTypes.get(tpe.name)
+                    t
+                  }
+                  case _ => null
+                }
+              })
+              .getOrElse(null)
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]:
```suggestion
              .orNull
```

File: engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala [hunk 15]
```diff
@@ -66,6 +66,15 @@ case object GatherDiagnostics extends IRPass {
...
         List(err)
+      case arg: IR.DefinitionArgument =>
+        val typeSignatureDiagnostics =
+          arg
+            .getMetadata(TypeSignatures)
+            .map(_.signature.preorder.collect { case err: IR.Diagnostic =>
+              err
+            })
+            .getOrElse(Nil)
+        typeSignatureDiagnostics ++ arg.diagnostics.toList
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala:77]: Can't we merge these two case branches into just one case branch? Since this code is the same copy of the code from the case branch below. Maybe at least separate the case branch body into a method?

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala [hunk 16]
```diff
@@ -164,6 +172,22 @@ case object TypeSignatures extends IRPass {
     )
   }
 
+  /** Attaches {@link Signature} to each arguments of a function
```
Comment (Akirathan) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala:173]:
```suggestion
  /** Attaches [[Signature]] to each arguments of a function
```

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Comment (Akirathan) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:1]: Can we also add a test for compound types like `x: Vector Integer` pls?

**Review by Akirathan — APPROVED** [review]
Just minor nitpicks. I would also add a test for a compound type like `x: Vector Integer` to `SignatureTest`. LGTM otherwise

**Comment by radeusgd** [comment]
> > Does that mean we should try to integrate #5987 soon?
> 
> Not really necessary. Wojciech explained to me that the former type signatures aren't going away. Imagine you have a variable `fn` and you want to type it. The `Any -> Any -> Any -> Text` syntax is still going to be needed. E.g. #5987 is just an alternative.

Of course, but if for the time being we can only opt-in into typechecks by changing the type signature format into `(x : X)`, we cannot express the _return type_ of the function. So to keep the return types we do need #5987.

Unless we want to duplicate signatures, i.e. write:
```
foo : X -> Y
foo (x : X) = ...
```
but then what happens if we do a typo and get an inconsistent signature:
```
foo : X -> Y
foo (x : Z) = ...
```

So ideally, we should be able to convert a function
```
foo : X -> Y
foo x = ...
```
into
```
foo (x : X) -> Y = ...
```
to be able to opt-in into the typechecks, without losing the return type information.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:1]: (i.e. tests checking that the 'erased' type is not checked)

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]: Done in e17f619c5a

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java (hunk 12 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]: Done in e17f619c5a

File: engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java (hunk 11 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java]: Thanks: e17f619c5a

File: engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala (hunk 5 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala:93]: Workaround for annoying _"Unused variable warning"_ that fails Scala compilation. Left over some experiments.

Comment (radeusgd) [inline engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala:93]: Why not
```suggestion
        newMethod.body match {
          case fn: IR.Function => verifyAscribedArguments(fn.arguments)
          case _               =>
        }
```

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java (hunk 10 above)
Comment (JaroslavTulach) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: Reported as #6848

**Comment by jdunkerley** [comment]
> Unless we want to duplicate signatures, i.e. write:

For the minute that is what we will end up with when we opt in to this checking. 
No question we should eventually end with the new syntax.
 
> but then what happens if we do a typo and get an inconsistent signature:

Ideally, I'd like this to error if at all possible but appreciate that is a separate task

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java (hunk 10 above)
Comment (radeusgd) [reply engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java]: > Reported as #6848

Thanks, that is one part of the question.

Another is:

> From the PR description, this also implements typechecking for ascriptions in methods, right? But I don't see any tests showing it.
> 
> Unless I'm missing something, can we get a test case for functions?

I looked through the PR and cannot find such test cases. I still might have missed something. But if not, can we get a test case?

Currently, it looks as if the PR only adds checking to _constructors_ - which is **great** but it also says it adds checking to regular methods - but I cannot see any test verifying that.

File: engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala (hunk 13 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala]: It is called `runtimeTypes` in the most recent version of the code.

**Comment by JaroslavTulach** [comment]
I believe this PR is ready for QA - @radeusgd, @jdunkerley, @GregoryTravis - please try this and let me know what needs to change (_TCR_ - technical change required), what would better be fixed (_TCA_ - technical change adviced) now or in a future PR, plus few wishes and _opinions_. I'll go thru your findings and try to address them during next week.

**Comment by JaroslavTulach** [comment]
What do you think about [this type error](https://github.com/enso-org/enso/actions/runs/5091086882/jobs/9150681860?pr=6790#step:10:3195), @radeusgd? `Aggregate_Column.Max` accepts `Integer` or `Text` and something is feeding it with `Column` - is it good, bad, what should be the fix?

**Comment by radeusgd** [comment]
> What do you think about [this type error](https://github.com/enso-org/enso/actions/runs/5091086882/jobs/9150681860?pr=6790#step:10:3195), @radeusgd? `Aggregate_Column.Max` accepts `Integer` or `Text` and something is feeding it with `Column` - is it good, bad, what should be the fix?

Haha, I knew it will come back to bite me.

It was a conscious decision, incompatible with the current state of things. The official public API only allows Integer or Text, but in the internal processing it is sometimes useful to replace that with a Column before further processing, so I sneaked that in, violating the types knowing that no one checks them - not anymore!

Please add a `| Column` to the signature and possibly a TODO, I will create an issue to follow up on this.

**Comment by radeusgd** [comment]
> Please add a `| Column` to the signature and possibly a TODO, I will create an issue to follow up on this.

I created a task for the follow-up cleanup #6866. Please add a reference to this task somewhere in the aggregate columns, for example at the top level:

```
## TODO the type signatures should only allow for identifying columns as `Text | Integer`. Due to an internal hack, `| Column` had to be added to make the typechecker happy. This is a temporary band-aid that needs a proper fix: #6866
```

**Review by radeusgd — APPROVED** [review]

**Review by radeusgd — COMMENTED** [review]
This looks great and I'm glad we are finally getting some type checking. That should make it **so much easier** to find many errors! 🎉 🎉 

If I understand correctly from our catch-up, @jdunkerley, you suggested that we should raise these `Type_Error`s as dataflow errors, not panics? Right?

> (I think the rationale was that we don't want exposing panics to the user, at least too often, and these errors are going to happen relatively often if the user does something wrong; so indeed a dataflow error may be safer here).

> On other hand I'd be actually cautious. Personally I do prefer the **current** state of things - panicking on type error. That is because for effectful computations (not common in the GUI but pretty common in our libraries), if the type error is a dataflow error, we may not notice it (if we discard the result)  - the **only** but pretty important difference will be that the function did not actually run. This may **lead to hard to debug errors**.
>
> I'm quite worried that by using dataflow errors instead of panics, we can make it harder to debug issues in our libraries. If it is a necessary sacrifice, so be it. But is it really necessary?

So I'd propose that maybe we should integrate this change keeping these panics as-is for now and we can see how this plays out in the IDE and if it causes any trouble? And if it causes problems we can revisit turning these into dataflow errors in a separate PR?

**Comment by radeusgd** [comment]
> What do you think about [this type error](https://github.com/enso-org/enso/actions/runs/5091086882/jobs/9150681860?pr=6790#step:10:3195), @radeusgd? `Aggregate_Column.Max` accepts `Integer` or `Text` and something is feeding it with `Column` - is it good, bad, what should be the fix?

One comment about it.

The error is:
```
Execution finished with an error: Type error: expected `Argument #1` to be [Text, Integer], but got Column.
```

Can we do something to make `Argument #1` actually be the name of the constructor argument?? That would be much more readable than a number.

Moreover, this is a bit of a nitpick, but to be consistent with the 'Enso-style', we have a proper syntax for sum types, so why write `[Text, Integer]` if it is not too much effort to write `Text | Integer` - which will be actually much closer to what was actually in the type signature.

So overall, I think it would be great if we can make the error say:
```
Execution finished with an error: Type error: expected `column` to be Text | Integer, but got Column.
```

Can we have that? 🙂

**Comment by radeusgd** [comment]
And this inspires me that we should have a few more tests, just to make sure the logic works (if something doesn't work and cannot be fixed in this PR, please let's still add a test, mark it as pending and create a follow up ticket)

I'd like to see a test for:
```
foo (x : ((Integer | Decimal) | (Integer | Decimal) | (Decimal | Integer) | Integer)) = x+x
```
with calls
```
foo 42
foo 1.5
foo "TEXT"
```

The `|` operator can be arbitrarily nested - I'm wondering if the current typechecker can correctly deal with that and what the expected type in the printed error will look like (so ideally it would be nice if the test also inspected the type error message).

Also I'm not sure if we have a test for `Any`, but definitely worth having some:
```
foo (x : Any) = x
bar (x : Text|Any) = x
...
# These should all work:
foo 42
foo "X"
bar 42
bar "X"
bar Nothing
```

**Comment by GregoryTravis** [comment]
I agree with treating type errors as Panics for now, and we'll see how it goes. It's tricky to have one policy for everything, because we really want our library internals to always type-check perfectly, and we don't want to risk having type errors lost because a dataflow error was missed. But we don't want end users to experience this strictness.

**Comment by JaroslavTulach** [comment]
There is five `[FAILED]` tests in the latest test run:

`Example_Tests` are [failing](https://github.com/enso-org/enso/actions/runs/5092796023/jobs/9154616600?pr=6790#step:10:7501) because of:
```
 - [FAILED] should provide various example tables [116ms]
         Reason: An unexpected panic was thrown: (Type_Error.Error Line_Ending_Style Infer 'Argument #9')
         at <enso> Delimited_Format.Delimited(Internal)
         at <enso> case_branch(/Standard/Table/2023.2.1-dev/src/Delimited/Delimited_Format.enso:60:23-52)
         at <enso> Delimited_Format.type.for_file_read(Standard/Table/2023.2.1-dev/src/Delimited/Delimited_Format.enso:59-63)
```
addressed in 31dff3cdfdab40f6b3498cf2a33bf4b94637e9f8

**Comment by JaroslavTulach** [comment]
There are many failures in `Table` like [failure](https://github.com/enso-org/enso/actions/runs/5092796023/jobs/9154616600?pr=6790#step:10:7971): 
```
- [FAILED] by an Is_In check, on various types of columns [8ms]
          Reason: An unexpected panic was thrown: (Type_Error.Error Vector (In-Memory Column str) 'Argument #1')
          at <enso> Filter_Condition.Is_In(Internal)
          at <enso> Table_Spec.spec<arg-2>(/runner/_work/enso/enso/test/Table_Tests/src/In_Memory/Table_Spec.enso:752:46-82)
          at <enso> Table_Spec.spec<arg-0>(/runner/_work/enso/enso/test/Table_Tests/src/In_Memory/Table_Spec.enso:752:13-83)
          at <enso> Table_Spec.spec<arg-0>(/runner/_work/enso/enso/test/Table_Tests/src/In_Memory/Table_Spec.enso:752:13-95)
```
I don't have expertise to know what to do with them. I am adding `Any` where I can, but that's probably not the right direction. Library guys, your help is needed!

**Update on May 30**: Done in [5ca27c6](https://github.com/enso-org/enso/pull/6790/commits/5ca27c66d93e6133ae67be346c863e5e2b3fd427)

**Comment by JaroslavTulach** [comment]
> Execution finished with an error: Type error: expected `column` to be Text | Integer, but got Column.

OK, added that as a *TCR* - a checkbox in the description of the PR.

> inspires me that we should have a few more tests

Feel free to add more tests into my branch. More passing tests is always helpful. (Correct) tests that fail would be useful too.

> maybe we should integrate this change keeping these panics as-is

@radeusgd, the biggest problem of the PR aren't missing test. We wanted these ascribed types to work as an **opt-in** and they do - for methods. However the syntax is already _heavily used for constructors_ and thus they are **opt-out** for constructors!

> There are many failures in `Table`

I don't have expertise to fix them. Ideally I need you to _go thru the runtime type errors and fix them_. Or we need to find a way to make these _constructor checks opt-in_ too.

**Comment by radeusgd** [comment]
Regarding the issues with the tests that you mentioned, they all are related. This is a bit of an issue that we were trying to express stuff that currently Enso does not allow us to. So we either need to add the `|Any` workaround as you did, or opt-out of typechecking OR figure our something better.

Let me first describe the concrete problems we saw:
1. `Is_In` is supposed to take a `Vector` for `Vector.filter` operations, but for `Table.filter` it needs to accept a `Vector` as well as a `Column`. We agreed to expose only `Vector` in type signature, as `Filter_Condition` is defined in `Base` from which the `Column` type is not accessible - so we just describe the situation in the comment. We do not want to introduce a dependency on `Table` to `Base` - `Base` is the basic library that should not have any dependencies.
2. I'm not sure what happened with `Unsupported_Output_Type`, TODO we will need to investigate it. This one may be a simple case, possibly.
3. The `Connection | Any` case. Here we are simply lacking some form of common type expression. E.g. interfaces could solve this. We have a generic `Connection` type and want to show on methods/ctors that they accept _any_ connection. But then we have particular connection _implementations_ - `Postgres_Connection`, `SQLite_Connection` etc. that have DB-specific behaviour. Currently there is no way to express a common type, so we just define a common type and children with similar names and pretend that `Postgres_Connection <: Connection` but in reality that is not the case as it's impossible
to express such a notion in Enso.
4. The last one is the `Aggregate_Column`s. I'm tracking a fix for them in #6866. But the `|Column` should be enough of a workaround. Turns out it isn't and you need to add `|Any`. The reason is simple and mostly the same as (3). Enso lacks interfaces. We currently have 2 column types - one from the `Table` library (for in-memory) and one from `Database`. They both (are meant to) provide the same public API, but have different underlying implementations. So we need a way to express a common `Column` type but currently there is none.

One ugly workaround for 4 could be to do a sum type: `Table.Column | Database.Column`. But that will not work either, because we do not want to introduce a circular dependency of `Table` depending on `Database`.

Ideally, we need some kind of better abstraction like interfaces or typeclasses with which we can indicate that both `Table.Column` and `Database.Column` implement some kind of common `Column` API, defined in the `Table` library. That would also fix the `Connection` issue from (3).

Alternatively, I think a solution that is available to us without modifying the language, is to create a facade `Column` type (defined in `Table`) that has only one field, untyped `column_implementation`. The facade's only job would be to delegate every operation to `column_implementation`. Thus we'd have only a single column type but allow for multiple implementations. I personally like this solution. It has the benefit that we can easily check if a given thing is a column regardless of what backend it comes from (as they have the same user-facing type). Then, a very big (IMO) advantage is that this would be the place where we 'store' the API docs for Column operations - since there is just one public entry point - that's the place where the doc comments need to reside in. Currently, for every `Column` operation we actually need to duplicate all documentation between both implementations (`Table.Column` and `Database.Column`). That is quite annoying, because every change of the docs in one backend needs to be reflected in the other one. It is easy to get out of sync. On the other hand, the current state gives us the ability to add some backend-specific documentation, that shows e.g. only for DB columns. However, IMO this is not really a good thing, as if we want to provide a uniform API, the documentation should be synchronized too.

So as for (3) and (4), I'd suggest a rewrite to this form. IMO it would actually improve the clarity of our libraries. @jdunkerley what do you think about that? I remember that you were a bit skeptical about this idea some time ago, although I'm not sure exactly which parts seemed problematic?

As for (1) - I don't know what the right fix is, we probably don't want to move `Column` to `Base`. IMO ideally I'd add some parent interface like `Can_Be_Used_As_Filter` which will be implemented by both `Vector` and `Column`, but we currently have no language capacity to do this.

**Comment by JaroslavTulach** [comment]
> ... some kind of better abstraction like interfaces or typeclasses ... That would also fix the `Connection` issue from (3).

This is the way to [implement Type classes](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:wip/jtulach/interfaces) manually in current Enso. All one needs to do is to have two argument `Value` with data & implementation.

With `Set.from (v: Vector)` conversions one also gets a nice way to hide factory methods.

File: engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java [hunk 17]
```diff
@@ -98,4 +131,124 @@ public void ascribedWithAParameter() throws Exception {
...
+    """, uri.getHost())
+            .uri(uri)
+            .buildLiteral();
+
+    var module = ctx.eval(src);
+    var some = module.invokeMember("eval_expression", "Maybe.Some 10");
+    assertEquals("Can read ten", 10, some.getMember("unwrap").asInt());
+    var lazy = module.invokeMember("eval_expression", "Maybe.Some (2 * 5)");
+    assertEquals("Can read first time ", 10, lazy.getMember("unwrap").asInt());
+    assertEquals("Can read second time", 10, lazy.getMember("unwrap").asInt());
```
Comment (JaroslavTulach) [inline engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java:153]: Further work tracked as #6883

**Comment by JaroslavTulach** [comment]
> Please add a `| Column` to the signature and possibly a TODO, ...  issue to follow up on this.
> you need to add |Any

@radeusgd you can use:
```
$ curl -L https://github.com/enso-org/enso/pull/6790.patch | grep "| *Any"
```
to identify the places where I had to **opt-out** from the _runtime type checks_. Currently I get 34 lines of output.

**Comment by jdunkerley** [comment]
> So as for (3) and (4), I'd suggest a rewrite to this form. IMO it would actually improve the clarity of our libraries. @jdunkerley what do you think about that? I remember that you were a bit skeptical about this idea some time ago, although I'm not sure exactly which parts seemed problematic?

If we can implement a facade type cleanly (not using the map builder set up of Dialect) - and without a massive amount of time as we are very resource light at the moment and velocity is low - am happy for us to prototype for Column.

For 3 (and also things requiring "File_Format" types), implementing them as a "Connection" with overrides removes the possibility of having type specific methods. Likewise it made the implementation far less clear as you end up with needing to have things done the way the Dialect is built with maps building up functions and plugging bits and bobs in here and there. I spent a fair while playing with this when we started on Postgres/SQLite connections. 

For the facade of these type, it needs to be straight forward to add new implementations for things and allow for specific methods for the end types. I think this means a facade wouldn't work here and we are back on needing interfaces/typeclasses (which is the correct solution here).

As for 4, we knew that one would bite us when we did it. I think we can restructure the resolve_aggregate easily to return the resolved columns either as a differet type or as a pair with the original Aggregate_Column.

**Comment by JaroslavTulach** [comment]
I can write `fn (x:Number)` function and I get early error when I call it in the IDE:

Type check in the IDE
