### PR TITLE
Fix Table Input Resizing

### LINKED ISSUE #12520: Resizing Table.input via Viz width doesn't resize input grid
https://github.com/user-attachments/assets/edac6269-4405-470a-a3b7-47262f09ef04

Image

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #12520 

https://github.com/user-attachments/assets/983065fb-d406-491f-ba76-bd6c07539294

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/components/ResizeHandles.vue [hunk 1]
```diff
@@ -20,25 +21,28 @@ function resizeHandler(resizeX: 'left' | 'right' | false, resizeY: 'top' | 'bott
...
         if (!initialBounds) break
-        bounds.value = initialBounds.withBoundsClamped(
-          selectFields(resizing, {
-            top: initialBounds.top + pos.relative.y,
-            bottom: initialBounds.bottom + pos.relative.y,
-            left: initialBounds.left + pos.relative.x,
-            right: initialBounds.right + pos.relative.x,
-          }),
-        )
+        else {
```
Comment (kazcw) [inline app/gui/src/project-view/components/ResizeHandles.vue]: Could be simplified to `if (initialBounds)`

File: app/gui/src/project-view/components/GraphEditor/GraphNode.vue [hunk 2]
```diff
@@ -257,6 +263,16 @@ watch(isVisualizationPreviewed, (newVal, oldVal) => {
...
+const scale = computed(() => navigator?.scale ?? 1)
+provideResizableWidgetRegistry(
+  computed({
+    get: () => visualizationWidth.value && visualizationWidth.value * scale.value,
+    set: (width) => (visualizationWidth.value = width && width / scale.value),
+  }),
+  () => CONTENT_PADDING * scale.value,
+  () => widgetTreeSize.value.x,
+)
+
```
Comment (kazcw) [inline app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: I think this may cause a performance problem in large graphs--adding a reactive dependency on `navigator.scale` will require Vue to update every `GraphNode` every frame while zooming the graph. Wouldn't it be more efficient for the registry to use scene coordinates?

Comment (farmaazon) [reply app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: GraphNode components should not be updated; `nodeWidth` change in resizableWidgetRegistry will trigger a watch calling `adjustToNodeWidth`, but here we would just compute exactly the same widget size, which is discarded before writing to metadata.

And because I rely on `useResizeObserver`, the code would be launched anyway on zoom in/out. The optimized solution would require a completely different solution. I assume what is so far is enough - but I test it with 100 nodes yet.

Comment (farmaazon) [reply app/gui/src/project-view/components/GraphEditor/GraphNode.vue]: I tested it on 100 Table.input nodes. It's laggy, but same way as on develop. Interestingly, AgGrid is refreshed there when zooming - probably worth checking at some point.

**Review by kazcw — APPROVED** [review]
