### PR TITLE
Ensure module sources are initialized

### LINKED ISSUE #13324: Race-condition between `OpenFileCmd` and `EnsureCompiledJob` leads to spurious `Main.main source not found` errors
On startup `EnsureCompiledJob` and `OpenFileCmd`, both compete for compilation lock.
If the former _wins_ first, it reports (initially) a spurious error that quickly disappears:

Image

There is no rule to how often the situation happens. It _seems_ a bit more frequent when trying out a new nightly with no cache (yet) available for the `Main.enso` module.

See the transcript of a broken run:
```
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [EnsureCompiledJob] 0ms for the file
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [EnsureCompiledJob] 0ms for the pending edit
[TRACE] [org.enso.interpreter.instrument.job.EnsureCompiledJob] Applying pending file [/home/hubert/Documents/enso-projects/NewProject43/src/Main.enso] edits [0] idMap [None]
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept pending edits lock [EnsureCompiledJob] for 1ms
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept file lock [EnsureCompiledJob] for 1ms
[TRACE] [org.enso.interpreter.instrument.job.AnalyzeModuleJob$] Analyzing not-indexed module local.NewProject43.Main
[DEBUG] [org.enso.languageserver.search.SuggestionsHandler] Got module update [local.NewProject43.Main].
[DEBUG] [org.enso.languageserver.search.SuggestionsHandler] Complete module update [local.NewProject43.Main]
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept write compilation lock [EnsureCompiledJob] for 3288ms
[TRACE] [org.enso.interpreter.instrument.execution.JobExecutionEngine] Job org.enso.interpreter.instrument.job.EnsureCompiledJob@64e0a95 finished in 3288 ms.
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [ExecuteJob] 3288ms for the read compilation
[TRACE] [org.enso.interpreter.instrument.execution.JobExecutionEngine] Number of remaining pending jobs: 1
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [OpenFileCmd] 3270ms for the read compilation
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [OpenFileCmd] 0ms for the file
[TRACE] [org.enso.interpreter.instrument.job.ProgramExecutionSupport$] Run program 7cd136bf-8dbb-47e9-9a36-ce954723ee7f
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept file lock [OpenFileCmd] for 0ms
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept read compilation lock [OpenFileCmd] for 0ms
[TRACE] [org.enso.interpreter.instrument.command.Command] Command OpenFileCmd finished.
[TRACE] [org.enso.interpreter.instrument.job.ProgramExecutionSupport$] Execution finished: Left(Some(Failure(The Main.main source not found.,None)))
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept read compilation lock [ExecuteJob] for 5ms
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Kept context lock [ExecuteJob] for 3293ms
[TRACE] [org.enso.interpreter.instrument.job.ExecuteJob] Finished ExecuteJob[555050dd-9cc0-4e9e-942d-2cdf75176b9e]
[TRACE] [org.enso.interpreter.instrument.execution.JobExecutionEngine] Job ExecuteJob(contextId=7cd136bf-8dbb-47e9-9a36-ce954723ee7f, jobId=555050dd-9cc0-4e9e-942d-2cdf75176b9e) finished in 3293 ms.
[TRACE] [org.enso.interpreter.instrument.execution.JobExecutionEngine] Number of remaining pending jobs: 0
[TRACE] [org.enso.languageserver.runtime.ContextRegistry] receive handled ExecutionFailed(7cd136bf-8dbb-47e9-9a36-ce954723ee7f,Failure(The Main.main source not found.,None)) from Actor[akka://language-server/deadLetters]
[DEBUG] [org.enso.interpreter.instrument.command.Command] Command PushContextCmd finished.
[DEBUG] [org.enso.interpreter.instrument.command.Command] Executing command synchronously: EditFileCmd...
[TRACE] [org.enso.interpreter.instrument.execution.ReentrantLocking] Waited [EditFileCmd] 0ms for the file
```

Most importantly `Waited [OpenFileCmd] 3270ms for the read compilation`. To fix, we have to ensure that `EnsureCompiledJob` is only run after `OpenFileCmd`.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

If Module sources where loaded from a disk but not (yet) sent by a GUI we had a potential race-condition in the execution. A safety check that was retrieving sources of a method to-be-called could have module's sources not yet initialized and ignoring the fact that they had been loaded from a disk.

The most problematic situation was to reproduce the problem which only happened on
1) first load of a project
2) no caches are yet available
3) NI build

The three conditions were not yet sufficient to have the "Missing Main.main" error to happen every time. Had to introduce an artifical sleep in `textFile/open` to create the necessary race-condition to appear every time.
Native Image was technically not required but because startup was much faster it increased the chances of a race condition.

We could potentially remove the src condition check altogether, as it is now covered in other places.

Closes #13324.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by hubertp** [comment]
Not yet sure whether it makes sense to spend time on trying to re-create this rather non-trivial setup in some test.

**Comment by JaroslavTulach** [comment]
> Native Image was technically not required but because startup was much faster it increased the chances of a race condition.

Yes, that want _native image_ does. I've seen problems like that in the past as well.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java [hunk 1]
```diff
@@ -383,11 +383,17 @@ public Source getSource() throws IOException {
    */
   @TruffleBoundary
   public final SourceSection createSection(int sourceStartIndex, int sourceLength) {
-    var src = sources.source();
+    Source src;
+    try {
+      src = getSource();
+    } catch (IOException e) {
+      TruffleLogger logger = TruffleLogger.getLogger(LanguageInfo.ID, Module.class);
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java]: Just use slf4j ... `TruffleLogger` is only good for fast path and this is behind `@TruffleBoundary`.

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java [hunk 2]
```diff
@@ -383,11 +383,17 @@ public Source getSource() throws IOException {
...
+      logger.log(Level.SEVERE, "Failed to retrieve sources of the module: " + e.getMessage(), e);
+      return null;
+    }
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java]: The `if src == null` check can be removed if you move the rest of the code into the `try/catch` block.

**Review by JaroslavTulach — APPROVED** [review]

File: engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java [hunk 3]
```diff
@@ -178,16 +178,6 @@ public void execute(
     var pending =
         submitExecution(
             () -> {
-              SourceSection src;
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java:181]: This change is _strictly speaking_ not necessary as I have fixed the underlying bug.
But the check is also obsolete - we check the source earlier as covered by our test suite.
