### PR TITLE
Node added inside collapsed node is never executed

### LINKED ISSUE #11251: Node added inside collapsed node is never executed.
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I tried to check one of my parsed columns inside collapsed function, but it's gray forever. That is, until the project is reopened.

Zrzut ekranu z 2024-10-04 09-34-59

### Expected behaviour

All nodes are executed, as I'm interested in their visualizations.

### How we can reproduce it?

Perhaps any side-branch of collapsed funtion has this issue?

If not, I attach the project here. I will also attach data file once I remove personal data.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

2024.5.1-nightly.2024.10.4

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #11251

Changelog:
- add: `CachePreferences` configuration of the expressions that are marked for caching
- update: Invalidate the `self` keywords in the parent frames on function edit
- update: persistance config

### Important Notes

The demo shows that:

1. The new node created in the collapsed function is highlighted (GUI receives the expression update)
2. When the collapsed function is edited, the nodes in the `main` method are updated correctly

https://github.com/user-attachments/assets/41c406ed-ba76-41c8-9e3f-89ac9ff63c3f

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala [hunk 1]
```diff
@@ -7206,6 +7206,272 @@ class RuntimeServerTest
...
+    val idYSelfMain = metadata.addItem(65, 4, "ad")
+    val idIncZ      = new UUID(0, 1)
+
+    val code =
+      """from Standard.Base import all
+        |
+        |main =
+        |    x = Main.inc 3
+        |    y = Main.inc 7
+        |    IO.println x+y
```
Comment (JaroslavTulach) [inline engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala:7334]: Why this example was not working before this PR?

Why it is working now?

File: engine/common/src/main/java/org/enso/common/CachePreferences.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+  }
+
+  /**
+   * Add a cache preference.
+   *
+   * @param id the node id
+   * @param kind the node kind
+   */
+  public void set(UUID id, Kind kind) {
+    preferences.put(id, kind);
```
Comment (JaroslavTulach) [inline engine/common/src/main/java/org/enso/common/CachePreferences.java:63]: I am afraid of a data structure read from _persistance_ that can be modified. At certain moment such a structure must become immutable. We cannot have a mutable structures flying around in the system. There are already plenty of such structures and we don't want to introduce new ones.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala [hunk 3]
```diff
@@ -403,6 +403,12 @@ class EnsureCompiledJob(
         CacheInvalidation.StackSelector.All,
         invalidateStaleCommand,
         Set(CacheInvalidation.IndexSelector.All)
+      ),
+      CacheInvalidation(
```
Comment (hubertp) [inline engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala:407]: So that's the _crucial point_ of this PR, right?

File: engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala [hunk 4]
```diff
@@ -177,13 +166,13 @@ case object CachePreferenceAnalysis extends IRPass {
     callArgument: CallArgument,
     weights: WeightInfo
   ): CallArgument = {
-    callArgument.value.getExternalId.foreach(weights.update(_, Weight.Always))
+    callArgument.value.getExternalId
+      .foreach(weights.update(_, CachePreferences.Kind.SELF_ARGUMENT))
```
Comment (hubertp) [inline engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala:170]: :+1:

**Review by hubertp — APPROVED** [review]
LGTM

File: engine/common/src/main/java/org/enso/common/CachePreferences.java (hunk 2 above)
Comment (4e6) [reply engine/common/src/main/java/org/enso/common/CachePreferences.java:63]: > I am afraid of a data structure read from persistance that can be modified.

From what I can see, all the compiler metadata is mutable currently. I introduced the `CachePreferences` to avoid copying and simply pass it to runtime after the compilation.

If we want to introduce an immutable object for persistence, we would need to convert mutable prefs to immutable to pass it to the persistence. And then convert immutable prefs to mutable again when we pass it to the runtime.

File: engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala (hunk 1 above)
Comment (4e6) [reply engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala:7334]: It was not working because the `self` argument was not invalidated after the method was edited. With the cached `self` we observed some stale nodes during the runtime, and the function call may return incorrect results (the result before the edit was done). Why it was the behavior is another question and I was not able to find the answer.

File: engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala (hunk 3 above)
Comment (4e6) [reply engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala:407]: Yes

File: engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java [hunk 5]
```diff
@@ -67,6 +68,7 @@
 @Persistable(clazz = TypeInference.class, id = 1280)
 @Persistable(clazz = FramePointerAnalysis$.class, id = 1281)
 @Persistable(clazz = TailCall.TailPosition.class, id = 1282)
+@Persistable(clazz = CachePreferences.class, id = 1284)
```
Comment (JaroslavTulach) [inline engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java:71]: - Adding this class without registering `CachePreferences.Kind` for persistance is causing #11858
