### PR TITLE
Compile imported module scope

### LINKED ISSUE #14856: NPE when referencing modules other than Main in user defined projects
## Issue

```
Execution finished with an error: java.lang.NullPointerException: Cannot invoke "org.enso.interpreter.runtime.scope.ModuleScope.getAssociatedType()" because the return value of "org.enso.interpreter.runtime.Module.getScope()" is null
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeMethodImportResolver.createResolvedImport(InvokeMethodImportResolver.java:131)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeMethodImportResolver.createResolvedImport(InvokeMethodImportResolver.java:18)
        at <java> org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolverAlgorithm.tryResolveImportNew(ImportResolverAlgorithm.java:128)
        at <java> org.enso.runtime.compiler/org.enso.compiler.phase.ImportResolverAlgorithm.tryResolveImport(ImportResolverAlgorithm.java:112)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeMethodImportResolver.tryResolve(InvokeMethodImportResolver.java:199)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InstanceInvokeMethodNode.doFunctionalDispatchUncachedSymbol(InstanceInvokeMethodNode.java:182)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InstanceInvokeMethodNodeGen.executeAndSpecialize(InstanceInvokeMethodNodeGen.java:647)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InstanceInvokeMethodNodeGen.execute(InstanceInvokeMethodNodeGen.java:529)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNode.invokeDynamicSymbol(InvokeCallableNode.java:286)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNodeGen.executeAndSpecialize(InvokeCallableNodeGen.java:274)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.InvokeCallableNodeGen.execute(InvokeCallableNodeGen.java:226)
        at <java> org.enso.runtime/org.enso.interpreter.node.callable.ApplicationNode.executeGeneric(ApplicationNode.java:97)
        at <java> org.enso.runtime/org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:91)
        at <enso> Main.main<arg-0>(Internal)
        at <enso> Main.main(src/Main.enso:5:12-30)
java.lang.NullPointerException: Cannot invoke "org.enso.interpreter.runtime.scope.ModuleScope.getAssociatedType()" because the return value of "org.enso.interpreter.runtime.Module.getScope()" is null
```

## How to reproduce

1. New Project 2 defines `local.NewProject2.Xyz.foo` method in `Xyz` module
2. New Project 1 calls this method:
```
from Standard.Base import all
import local.NewProject2

main =
    any1 = NewProject2.Xyz.foo
    any1
```

- [NewProject1.zip](https://github.com/user-attachments/files/25913107/NewProject1.zip)
- [NewProject2.zip](https://github.com/user-attachments/files/25913106/NewProject2.zip)

Calling methods in Main module (for example `local.NewProject2.foo` ) is fine

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

- close #14856 

Fix the issue with importing modules that are not referenced in Main

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 1]
```diff
@@ -132,7 +134,11 @@ protected Module loadLibraryModule(LibraryName libraryName, String moduleName)
 
   @Override
   protected EnsoObject createResolvedImport(UnresolvedSymbol imp, List<Object> exp, Module m) {
-    return m.getScope().getAssociatedType();
+    var scope = m.getScope();
+    if (scope == null) {
+      scope = m.compileScope(ctx);
+    }
+    return scope.getAssociatedType();
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:135]: - this change is OK, but what do you think about following idea:

- we often deal with these kind of `getScope || compileScope` double check
- wouldn't it be better to change signature of `getScope` to
```java
public ModuleScope getScope(boolean allowNull);
```
- and then we would just call `m.getScope(false)`
- and we could remove `compileScope` from the API
- btw. we don't need to pass `ctx` to `Module` as modules are always created from `EnsoContext` and are associated with a context and thus they can keep the pointer to `EnsoContext` internally

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 2]
```diff
@@ -30,10 +30,12 @@ final class InvokeMethodImportResolver
 
   private final Module module;
   private final TopLevelScope topScope;
+  private final EnsoContext ctx;
 
-  private InvokeMethodImportResolver(Module module, TopLevelScope topScope) {
+  private InvokeMethodImportResolver(Module module, TopLevelScope topScope, EnsoContext ctx) {
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java]:
```suggestion
  private InvokeMethodImportResolver(Module module, EnsoContext ctx) {
    this.topScope = ctx.getTopScope();
```

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java [hunk 3]
```diff
@@ -30,10 +30,12 @@ final class InvokeMethodImportResolver
 
   private final Module module;
   private final TopLevelScope topScope;
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java]: Possibly remove this variable and always use `ctx.getTopScope()`

**Review by JaroslavTulach — APPROVED** [review]
I think this change is OK, but I am curious to know answers to my questions.

File: engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java (hunk 1 above)
Comment (4e6) [reply engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java:135]: I think `getScope || compileScope` pattern can be replaced with just `compileScope` because this method already insures that the returned scope is compiled:
https://github.com/enso-org/enso/blob/4bc6e97110c4aad5130044f2e78d2d80fa8b3263/engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java#L385-L400
