### PR TITLE
Two findExceptionMessage methods to extract exception messages consistently

### LINKED ISSUE #5260: Throwing an unhandled exception in Polyglot Java results in a null in the UI and no caught error message
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184073253).
<hr />

Throwing a NPE within Java caused an error when command line:
```
Execution finished with an error: null
        at <java> org.enso.table.data.index.MultiValueIndex.makeCrossTabTable(MultiValueIndex.java:185)
        at <enso> case_branch(C:\Repos\Enso\ide\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Table\0.0.0-dev\src\Data\Table.enso:1299:21-122)
```

Within the UI get no error message and the viz shows `null`. Error from Language Server shown below.

## Comments:
 (James Dunkerley - Dec 20, 2022)
<hr />
```
from Standard.Base import Panic
polyglot java import java.lang.NullPointerException

main =
    x = NullPointerException.new
    Panic.throw x
```
Easily reproducible via cli
```
built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --no-ir-caches --run ~/work/repos/enso/test-cases/thrownpe.enso 
Execution finished with an error: null
        at <enso> Panic.throw(Internal)
        at <enso> thrownpe.main(thrownpe.enso:6:5-17)
```

It's because NPEs message is null. (Hubert Plociniczak - Dec 20, 2022)
<hr />

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Creating two `findExceptionMessage` methods in `HostEnsoUtils` and in `VisualizationResult`. Why two? Because one of them is using `org.graalvm.polyglot` SDK as it runs in _"normal Java"_ mode. The other one is using Truffle API as it is running inside of partially evaluated instrument.

There is a `FindExceptionMessageTest` to guarantee consistency between the two methods. It simulates some exceptions in Enso code and checks that both methods extract the same _"message"_ from the exception. The tests verifies hosted and well as Enso exceptions - however testing other polyglot languages is only possible in other modules - as such I created `PolyglotFindExceptionMessageTest` - but that one doesn't have access to Truffle API - e.g. it doesn't really check the consistency - just that a reasonable message is extracted from a JavaScript exception.

### Important Notes

This is not full fix of #5260 - something needs to be done on the IDE side, as the IDE seems to ignore the delivered JSON message - even if it contains properly extracted exception message.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java [hunk 1]
```diff
@@ -10,6 +11,38 @@ public final class VisualizationResult {
...
+   */
+  @CompilerDirectives.TruffleBoundary
+  public static String findExceptionMessage(Throwable ex) {
+    Object msg = ex;
+    var iop = InteropLibrary.getUncached();
+    if (iop.hasExceptionMessage(ex)) {
+      try {
+        msg = iop.getExceptionMessage(ex);
+      } catch (UnsupportedMessageException ignore) {
+        throw CompilerDirectives.shouldNotReachHere(ignore);
```
Comment (hubertp) [inline engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java:28]: I think we typically throw illegal state exception. is  `CompilerDirectives.shouldNotReachHere` the new recommended way?

File: project/FrgaalJavaCompiler.scala [hunk 2]
```diff
@@ -112,7 +112,7 @@ object FrgaalJavaCompiler {
     def checkTarget(x : Any) = {
       val p = asPath(x)
       val namesCheck = for (i <- 0 until p.getNameCount)
-        yield "target".equals(p.getName(i).toString())
+        yield "target".equals(p.getName(i).toString()) || p.getName(i).toString().endsWith("-windows") || p.getName(i).toString().endsWith("-unix")
```
Comment (hubertp) [inline project/FrgaalJavaCompiler.scala:115]: Why do we need those now?

**Review by hubertp — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java:28]: I believe `shouldNotReachHere` has a special treatment in the compiler and leads to shorter code then regular exceptions. In case of normla exception the constructor (including `fillInStackTrace` call) is still executed in the *partial evaluation* mode - e.g. the generated code is bigger than in case of `shouldNotReachHere`. I performed a little experiment and tried to compile in my [talk2compiler project](https://github.com/JaroslavTulach/talk2compiler/blob/master/src/main/java/org/apidesign/demo/talk2compiler/Main.java#L18):
```java
    @Override
    public Object execute(VirtualFrame frame) {
      final String name = (String) frame.getArguments()[0];
      if (name.length() > 0) {
        return formatGreeting("Hello from %s!", name);
      } else {
        throw CompilerDirectives.shouldNotReachHere("The 0-th arg is wrong and leads");
        // throw new NullPointerException("The 0-th arg is wrong and leads");
      }
    }
```
I am [attaching result of comparing](https://user-images.githubusercontent.com/26887752/220039461-8f6164c5-54ff-4b42-8143-89dc9fbda3b9.svg) `NullPointerException` with `shouldNotReachHere` handler. There is clearly a difference between `NullPointerException` and `shouldNotReachHere`:

NPEvsShouldNotReachHere

However I haven't managed to simulate the difference with `IllegalStateException`. Looks like there is a set of [skipped exception types](https://github.com/oracle/graal/blame/74562e44cdb97770d4cd62691319fcc727485208/compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/TruffleCompilerImpl.java#L174) and those get special treatment, similar to `shouldNotReachHere`.  The `IllegalStateException` has been added there two years ago - e.g. at the end we can continue to use `IllegalStateException` and get the same result of `shouldNotReachHere`.

File: project/FrgaalJavaCompiler.scala (hunk 2 above)
Comment (JaroslavTulach) [reply project/FrgaalJavaCompiler.scala:115]: I needed this to [Make sure logger-service can be debugged in Enso4Igv modules](https://github.com/enso-org/enso/pull/5684/commits/70e3ab0844789c26610722d2d63ab3635b3a0731). A bit unrelated, but I was trying to investigate #5683 and I cannot do that without being able to debug `logger-service`.
