### PR TITLE
Eliminate race condition for edit/close/open cmds

### LINKED ISSUE #6841: Enso stopped working properly when creating node during Libs compilation
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I create node too fast (before Libs are compiled) IDE looses connection to the Engine.

https://github.com/enso-org/enso/assets/108271897/94339f38-bf70-4c41-bffc-eaba9f390e91

### Expected behaviour

User shouldn't be allowed to create a node before Libs are compiled.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

[2305242131_shareX 20230524-192640-619-enso-project-manager.log](https://github.com/enso-org/enso/files/11562250/2305242131_shareX.20230524-192640-619-enso-project-manager.log)

### Enso Version

2023.5.24 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

There was an inherent race condition between edit, close & open commands which could not be prevented solely using locks. `EditFileCmd` triggered `EnsureCompiledJob` which was applying edits collected over time. At the same `CloseFileCmd` and `OpenFileCmd` were executed asynchronously and required locks on compilation unit  and file lock.

Additionally, open file was resetting the module's runtime source irrespective of any edits that could already have been applied with the asynchronous execution in `EnsureCompiledJob`. This was visible especially during early manipulation of the project when open/close was performed due to a bug in IDE (#6843).

Now commands can be run either synchronously or asynchronously. Only that way can we ensure that `close` & `open` commands finish by the time any editions are being applied to module's sources.

Closes #6841.

### Important Notes

In the given video, `"foo"` would be greyed out because it would never be part of the module's (runtime) sources. Therefore no IR would be generated for it or instrumentation, meaning it would be present in `expressionUpdates` information necessary for IDE.

[Kazam_screencast_00014.webm](https://github.com/enso-org/enso/assets/292128/226a17b8-729a-415a-803f-003a9695b2f1)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]
I like this approach :+1:

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AsynchronousCommand.scala [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+import java.util.logging.Level
+import scala.concurrent.{ExecutionContext, Future}
+import scala.util.control.NonFatal
+import scala.util.{Failure, Success}
+
+abstract class AsynchronousCommand(maybeRequestId: Option[RequestId])
+    extends Command(maybeRequestId) {
+  type Result[T] = Future[T]
+
+  override def execute(implicit
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AsynchronousCommand.scala]: Can this method be made `final`?

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/SynchronousCommand.scala [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+import org.enso.polyglot.runtime.Runtime.Api.RequestId
+
+import java.util.logging.Level
+import scala.concurrent.ExecutionContext
+
+abstract class SynchronousCommand(maybeRequestId: Option[RequestId])
+    extends Command(maybeRequestId) {
+  type Result[T] = T
+
+  override def execute(implicit
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/SynchronousCommand.scala]: We don't want anyone else to override this method. Can it be made `final`?

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala [hunk 3]
```diff
@@ -63,43 +57,8 @@ class CommandExecutionEngine(interpreterContext: InterpreterContext)
...
-        }
-
-    for {
-      _ <- Future { logger.log(Level.FINE, s"Executing command: $cmd...") }
-      _ <- doIt()
-      _ <- Future { logger.log(Level.FINE, s"Command $cmd finished.") }
-    } yield Done
-
+  def invoke(cmd: Command): cmd.Result[Completion] = {
+    cmd.execute(runtimeContext, commandExecutionContext)
```
Comment (JaroslavTulach) [inline engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala]: I don't understand what this PR changes except seeing some _stylistic modifications_:
- previously `Command.execute` had to be overriden and the exception handling was in `CommandExecutionEngine`
- now `Command.execute` is (almost) `final` and contains exception handling. `CommandExecutionEngine` just invokes it
- commands that want original functionality just implement `executeAsynchronously` and have access to `ec`
- some commands may decide that they don't need access to `ec` and then they implement `executeSynchronously`

All of such functionality has already been possible before. I don't understand where is the change?

**Review by JaroslavTulach — APPROVED** [review]
Approving as _harmless_, but I don't see what this PR actually changes except doing some stylistic refactorings. How it is supposed to eliminate race condition? That remains a mystery to me.

File: engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala (hunk 3 above)
Comment (hubertp) [reply engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala]: The hint is in the return type of `Command`'s `execute`. In the case of `AsynchronousCommand` the type is `Future[Unit]`, in the case of `SynchronousCommand` it is `Unit`. The latter will execute immediately, while the former will execute whenever the  executor's scheduler decides to.
Previously, we only had the former. It also happened to schedule it around the time `EnsureCompiled` job was running which meant that required locks were already taken and `close`/`open` would only execute after we applied  edits (too late).

**Comment by hubertp** [comment]
This PR also helps with the
```
org.enso.syntax.text.Parser.ParserError: Some(Internal error in parser Could not not deserialize metadata (found 2 metadata sections))
  at org.enso.syntax.text.Parser.splitMeta(Parser.scala:44)
```
error that people were reporting occasionally.
