### PR TITLE
Right Panel fixes

### LINKED ISSUE #13539: Doc panel menu needs to align with graph editor menu
Image

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Closes #13539 
Part of #13222 

1. The buttons in Graph are aligned to those in Description/Documentation editor.

image

2. The graph editor "anchor" point is now left-top corner instead of center: this makes nodes not move when opening/resizing right and bottom panel.

https://github.com/user-attachments/assets/c117b972-0593-472a-9f92-f6cbf2f28bf1

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/util/data/vec2.ts [hunk 1]
```diff
@@ -60,22 +60,22 @@ export class Vec2 {
...
   }
 
-  /** TODO: Add docs */
+  /** Check if both coords have finite values. */
   isFinite(): boolean {
     return Number.isFinite(this.x) && Number.isFinite(this.y)
   }
 
-  /** TODO: Add docs */
+  /** Change Inf values in vector to 0. */
```
Comment (kazcw) [inline app/gui/src/project-view/util/data/vec2.ts]: `NaN` is also non-finite

**Review by kazcw — APPROVED** [review]

File: app/gui/src/project-view/util/data/vec2.ts (hunk 1 above)
Comment (Frizi) [reply app/gui/src/project-view/util/data/vec2.ts]: This method intentionally coerces `NaN` to `0` as well. I think it's just a matter of adjusting docs.

```suggestion
  /** Change any infinite or non-numeric (e.g. `Infinity` or `NaN`) vector values to `0`. */
```

File: app/gui/src/project-view/composables/navigator.ts [hunk 2]
```diff
@@ -270,10 +270,15 @@ export function useNavigator(
       minScale,
       maxScale,
     )
-    targetCenter.value = rect.center().finiteOrZero()
+    const w = viewportElem.value.clientWidth / targetScale.value
+    const h = viewportElem.value.clientHeight / targetScale.value
+    targetLeftTop.value = rect
+      .center()
+      .finiteOrZero()
+      .sub(new Vec2(w / 2, h / 2))
```
Comment (Frizi) [inline app/gui/src/project-view/composables/navigator.ts:279]: I've got a little confused for a bit and was about to propose to just use `rect.pos` instead here, but I see that this wouldn't be correct. Let's drop a comment here explaining that `rect` might have different aspect ratio than viewport, so we still want to move viewport center to rect center explicitly.

**Review by Frizi — APPROVED** [review]

File: app/gui/src/project-view/util/data/vec2.ts (hunk 1 above)
Comment (kazcw) [reply app/gui/src/project-view/util/data/vec2.ts]: Yes

Comment (farmaazon) [reply app/gui/src/project-view/util/data/vec2.ts]: Yes
