### PR TITLE
Do not immediately modify code when disconnecting the edge at target side.

### LINKED ISSUE #6772: Malfunctioning edge after detaching source end
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Under some (common) conditions, an edge that has been detached from its source node cannot be attached to anything, and is stuck in a broken state.

### Expected behaviour

After detaching an edge from a source, it should be possible to attach the source end to an output port.

### How we can reproduce it?

1. Choose an edge that would cause errors in the graph if detached, e.g. a node a method is invoked on.
2. Click on the edge near the target side, to disconnect it from its source.
3. Wait for the graph to show errors.
4. (Once the errors show, you can see the edge slightly disconnect from the target node; this indicates the broken state has been reached.)
5. Click on some output port to attempt to reattach the edge: Nothing happens.

### Screenshots or screencasts

[vokoscreenNG-2023-05-18_16-19-54.webm](https://github.com/enso-org/enso/assets/1047859/395c94e6-c6d5-46ce-8a3f-4e8f25e86f95)

### Enso Version

develop (a32a2eafba)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #6772 

When detaching an existing edge by grabbing by a source port, the node's code is no longer immediately modified. It is only changed once the edge has been either connected or destroyed. When grabbing on the source side, the existing behavior is preserved. That way, we always have guaranteed place to keep the edge connected to. 

https://github.com/enso-org/enso/assets/919491/49e560cb-0a29-4c6a-97ec-4370185b8c89

In general, the detached edges are now more stable, resilient to all kinds of expression modifications during the drag.

https://github.com/enso-org/enso/assets/919491/e62450ff-46b2-466f-ac33-f4f19e66ee1d

In case there is a situation where the currently dragged edge's port is destroyed (e.g. by Undo/Redo), instead of showing glitched port position it is simply dropped.

https://github.com/enso-org/enso/assets/919491/8fb089aa-a4a5-4a8c-92eb-23aeff9867b8

# Important Notes

The whole edge connection and view handling at the graph-editor view level has been completely rewritten. The edge endpoints are now identified using new `PortId` structure, that is not dependant on the span-tree. This prepares us for eventual removal of the span-tree in favour of manipulating AST directly. Right now those `PortId`s are still stored within the span-tree nodes, but it will be easy to eventually generate them on the fly from the AST itself. The widget tree has also already been switched to that representation where appropriate.

Additionally, I have started splitting the graph editor FRP network into smaller methods. Due to its absolutely enormous size and complexity of it, I haven't finished the split completely, and mostly edge-related part is refactored. I don't want to block this PR on this any longer though, as the merge conflicts are getting a bit unwieldy to deal with.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

File: app/gui/controller/double-representation/src/connection.rs [hunk 1]
```diff
@@ -33,61 +35,45 @@ impl Endpoint {
     ///
     /// Returns None if first crumb is not present or does not denote a valid node.
     fn new_in_block(block: &ast::Block<Ast>, mut crumbs: Crumbs) -> Option<Endpoint> {
-        let line_crumb = crumbs.pop_front()?;
-        let line_crumb = match line_crumb {
-            Crumb::Block(block_crumb) => Some(block_crumb),
-            _ => None,
-        }?;
+        let Some(Crumb::Block(line_crumb)) = crumbs.pop_front() else { return None };
```
Comment (kazcw) [inline app/gui/controller/double-representation/src/connection.rs:37]: Why not the `?` operator?

File: app/gui/controller/double-representation/src/connection.rs [hunk 2]
```diff
@@ -21,10 +22,11 @@ use ast::crumbs::Crumbs;
...
 pub struct Endpoint {
     /// Id of the node where the endpoint is located.
-    pub node:   Id,
-    /// Crumbs to the AST creating this endpoint. These crumbs are relative to the node's AST,
-    /// not just expression, if the node is binding, there'll crumb for left/right operand first.
-    pub crumbs: Crumbs,
+    pub node: Id,
+    /// The located AST ID of port creating this endpoint. Port crumbs are relative to the node's
+    /// AST, not just expression, if the node is binding, there'll crumb for left/right operand
+    /// first.
```
Comment (kazcw) [inline app/gui/controller/double-representation/src/connection.rs]: I can't make sense of this sentence (not new code, I know).

File: app/gui/src/presenter/graph/state.rs [hunk 3]
```diff
@@ -615,22 +514,20 @@ impl<'a> ControllerChange<'a> {
...
-            .add_ast_connection(connection.clone())
-            .and_option_from(move || self.view_edge_targets_of_ast_connection(connection))
-    }
-
-    /// Remove all connection not belonging to the given set. Returns the list of to-be-removed
-    /// views.
-    pub fn retain_connections(&self, connections: &HashSet<AstConnection>) -> Vec<ViewConnection> {
-        self.connections.borrow_mut().retain_connections(connections)
+    /// Map controller connections to view connections. Only creates connections for nodes that
+    /// are currently in state.
```
Comment (kazcw) [inline app/gui/src/presenter/graph/state.rs]: docs: Is it expected that some connections will refer to nodes that aren't in the state?

File: app/gui/src/presenter/graph/state.rs [hunk 4]
```diff
@@ -829,43 +726,19 @@ impl<'a> ViewChange<'a> {
...
-        let mut connections = self.connections.borrow_mut();
-        let should_update_controllers =
-            connections.add_connection_view(ast_connection.clone(), connection);
-        should_update_controllers.then_some(ast_connection)
-    }
 
-    /// Remove the connection and return the corresponding AST connection which should be removed.
-    pub fn remove_connection(&self, id: ViewConnection) -> Option<AstConnection> {
-        self.connections.borrow_mut().remove_connection(id)
+    /// Map a connection on view side to a connection on controller side.
```
Comment (kazcw) [inline app/gui/src/presenter/graph/state.rs]: docs: When might this return `None`?

File: app/gui/view/graph-editor/src/component/edge.rs [hunk 5]
```diff
@@ -123,16 +130,16 @@ impl Edge {
...
+            redraw_needed <- any_(...);
+            redraw_needed <+ frp.target_position;
+            redraw_needed <+ frp.source_attached;
+            redraw_needed <+ frp.target_attached;
+            redraw_needed <+ frp.source_size;
+            redraw_needed <+ frp.set_disabled;
+            redraw_needed <+ mouse_move;
+            redraw_needed <+ mouse_out;
+            redraw_needed <+ edge_color.value;
+            redraw_needed <+ display_object.on_transformed;
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/edge.rs]: These should refer to the new gated events.

File: app/gui/view/graph-editor/src/component/node/input/area.rs [hunk 6]
```diff
@@ -284,13 +310,13 @@ impl Model {
         let new_expression = Expression::from(new_expression.into());
         debug!("Set expression: \n{:?}", new_expression.tree_pretty_printer());
 
+        self.request_widget_config_overrides(&new_expression, area_frp);
         self.widget_tree.rebuild_tree(
             &new_expression.span_tree,
             &new_expression.code,
             &self.styles,
         );
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/node/input/area.rs:321]: If relative order of these is important due to side effects, that deserves a comment.

File: app/gui/view/graph-editor/src/component/edge.rs [hunk 7]
```diff
@@ -47,13 +47,15 @@ define_endpoints_2! {
         /// dragged by the mouse.)
         source_attached(bool),
         set_disabled(bool),
+        /// Whether the edge should stop responding to mouse movement.
+        set_hover_disabled(bool),
```
Comment (kazcw) [inline app/gui/view/graph-editor/src/component/edge.rs:51]: Is this ever different from `!source_attached || !target_attached`?

File: lib/rust/frp/src/nodes.rs [hunk 8]
```diff
@@ -1029,6 +1051,29 @@ impl Network {
...
+    where
+        T: EventOutput<Output = Option<In>>,
+        Out: Data,
+        F: 'static + Fn(&In) -> Out, {
+        self.map(label, src, move |value| value.as_ref().map(&f))
+    }
+
+    /// A version of map that operates on optionals. The provided function will only be called when
+    /// incoming stream's value is [`Some`], and then the provided function can return an optional
+    /// itself. If you want a non-optional return type, use [`Network::and_then`].
```
Comment (kazcw) [inline lib/rust/frp/src/nodes.rs]:
```suggestion
    /// itself. If you want a non-optional return type, use [`Network::map_some`].
```

File: lib/rust/ensogl/core/src/control/io/mouse/event.rs [hunk 9]
```diff
@@ -236,6 +249,79 @@ macro_rules! define_events {
...
+/// An JS event type that is convertible to a light copyable struct containing its associated data.
+#[allow(missing_docs)]
+pub trait ToEventData {
+    type Data: Default + Debug + Copy;
+    fn to_data(&self, shape: Shape) -> Self::Data;
+}
+
+/// The data associated with a mouse event. In web environment, it is derived from the mouse event
+/// itself. In test environment, it is passed as a parameter in order to simulate a particular
+/// mouse event.
```
Comment (kazcw) [inline lib/rust/ensogl/core/src/control/io/mouse/event.rs:261]: Could we prevent testing from complicating production code by adding support for real (mock) data to `web::binding::mock::MouseEvent`, instead of adding this new abstraction?

**Review by kazcw — APPROVED** [review]
It's nice to see this stuff getting cleaned up.

File: lib/rust/ensogl/core/src/control/io/mouse/event.rs (hunk 9 above)
Comment (Frizi) [reply lib/rust/ensogl/core/src/control/io/mouse/event.rs:261]: I tried. The mock types right now are all assuming they are ZST and free to transmute between each other, which is a pain to deal with. Especially given that they emulate the inheritance that way. I think there is a way to do it using composition and derefs instead, but that was a bit more than I was willing to clean up right now. The simple copyable structs per event are definitely easier to deal with, and also simplify the accessors quite a lot (no need to go through JS function call every time you want event position etc.).

File: app/gui/src/presenter/graph/state.rs (hunk 3 above)
Comment (Frizi) [reply app/gui/src/presenter/graph/state.rs]: Not exactly expected right now, but also not forbidden given our view API. It is entirely possible (and happens transiently while events are propagating) that either the view has already created a node while the controller has no representation of it, or that the node on the controller side hasn't yet been assigned to any node view.

File: app/gui/controller/double-representation/src/connection.rs (hunk 1 above)
Comment (Frizi) [reply app/gui/controller/double-representation/src/connection.rs:37]: It is more than a `Some` match. I also want to also test for `Crumb::Block` variant. I could do it like this
```rs
let Crumb::Block(line_crumb) = crumbs.pop_front()? else { return None };
```

But I don't think it's any better.

File: app/gui/view/graph-editor/src/component/edge.rs (hunk 7 above)
Comment (Frizi) [reply app/gui/view/graph-editor/src/component/edge.rs:51]: Yes. The hover is disabled for all edges whenever there is any detached edge present. It is disabled not only for the edge that is actually detached.

File: app/gui/controller/double-representation/src/identifier.rs [hunk 10]
```diff
@@ -191,18 +191,18 @@ impl Hash for Identifier {
...
+    base: &str,
+    unavailable: impl IntoIterator<Item = &'a str>,
 ) -> FallibleResult<Identifier> {
-    let base = base.as_ref();
-    let is_relevant = |name: &String| name.starts_with(base);
-    let unavailable = unavailable.into_iter().filter(is_relevant).collect::<HashSet<_>>();
+    let unavailable = unavailable
+        .into_iter()
+        .filter_map(|name| name.strip_prefix(base).and_then(|suffix| suffix.parse::<usize>().ok()))
+        .collect::<HashSet<_>>();
```
Comment (farmaazon) [inline app/gui/controller/double-representation/src/identifier.rs]: This code is less understandable than before; it was obvious we leave "relevant" unavailable names only, now we do some stripping. The var should be named differently.

File: app/gui/controller/double-representation/src/refactorings/collapse.rs [hunk 11]
```diff
@@ -206,13 +206,13 @@ impl Extracted {
...
         for connection in graph.info.connections() {
             let starts_inside = extracted_nodes_set.contains(&connection.source.node);
-            let ends_inside = extracted_nodes_set.contains(&connection.destination.node);
-            let identifier = graph.connection_variable(&connection)?;
+            let ends_inside = extracted_nodes_set.contains(&connection.target.node);
 
             leaves.remove(&connection.source.node);
             if !starts_inside && ends_inside {
-                inputs.push(identifier)
+                inputs.push(graph.connection_variable(&connection)?)
```
Comment (farmaazon) [inline app/gui/controller/double-representation/src/refactorings/collapse.rs]: Now, if we somehow cannot get `connection_variable`, the node still won't be treated as a leaf. Is that a conscious change?

File: app/gui/src/controller/graph.rs [hunk 12]
```diff
@@ -632,30 +553,46 @@ impl Handle {
...
+            true => self.introduce_pattern_if_missing(connection.source.node)?,
+            false => {
+                let source_node = self.node_info(connection.source.node)?;
+                // For subports we would not have any idea what pattern to introduce. So we fail.
+                source_node
+                    .pattern()
+                    .ok_or(NoPatternOnNode { node: connection.source.node })?
+                    .clone()
+            }
+        };
```
Comment (farmaazon) [inline app/gui/src/controller/graph.rs]: What is the advantage of matching bool over a single `if`? The latter is quicker to read IMO.

**Review by farmaazon — COMMENTED** [review]
Added some nitpicking in controller/presenter part.

File: app/gui/controller/double-representation/src/refactorings/collapse.rs (hunk 11 above)
Comment (Frizi) [reply app/gui/controller/double-representation/src/refactorings/collapse.rs]: You are right, the logic change here was not intentional. I'll change it back. Though I'm not really sure which way is "more correct" here.

File: app/gui/src/controller/graph.rs (hunk 12 above)
Comment (Frizi) [reply app/gui/src/controller/graph.rs]: I think it was more concise in this form at some point. But now it doesn't really make sense anymore.

**Comment by farmaazon** [comment]
## QA report: :green_book: 

Did one of the bookclubs and no regression spotted.
