### PR TITLE
Fix refocusing text widget

### LINKED ISSUE #12571: Text Widget isn't editable after application loses focus
1. Add a text input widget
2. Start typing
3. Remove focus from entire application (say to copy some text to past in)
4. Click back onto the text input widget

You can't put the cursor back in the text input without clicking off and back on component.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix refocusing text widget after losing focus in an unexpected way.

Fixes #12571.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

File: app/gui/src/project-view/providers/widgetRegistry/editHandler.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ export abstract class WidgetEditHandlerParent {
   }
 
   protected onStart(origin: PortId) {
+    if (this.parent && this.parent.activeChild.value === this) return
```
Comment (farmaazon) [inline app/gui/src/project-view/providers/widgetRegistry/editHandler.ts]: Same as `this.active` or `this.isActive`

**Review by farmaazon — APPROVED** [review]
