### PR TITLE
Fix missing dropdowns in constructor subexpressions

### LINKED ISSUE #10341: Delimiter dropdown broken on data.read
Got broken between the Version 2024.2.1-nightly.2024.6.18
and  Version 2024.2.1-nightly.2024.6.19 builds

Expected:

image

Actual:
No dropdown

image

### PR DESCRIPTION
**Pull request by Frizi**
### Pull Request Description

Fixes #10341 

image

Also added a new version of vue devtools that is embedded into the dev app itself, and has much better performance than the browser plugin.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
appriing vite update for dashboard

File: app/gui2/src/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts [hunk 1]
```diff
@@ -64,17 +59,22 @@ export function useWidgetFunctionCallInfo(
...
+        : getAccessOprSubject(analyzed.func)
 
-      return selfArgument?.externalId
-    } else {
-      return null
+      if (!selfArgument && knownArguments == null) {
+        return selfByName?.externalId ?? analyzed?.args[0]?.argument?.externalId
+      } else {
+        return selfArgument?.externalId
+      }
```
Comment (farmaazon) [inline app/gui2/src/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts]: I think it would be clearer in this form:
1. First, if selfArgument exists, just return it's external Id
2. Then if knownArguments _exist_, return null (known static function)
3. Then return first argument

This way we have a clear path "what happens in case of constructors/static methods?"

**Review by farmaazon — APPROVED** [review]
Approving with `memberOf` fix.
