### PR TITLE
Fix re-exports of type constructors

### LINKED ISSUE #7674: Fix re-exports of type constructors
## Issue

Created from discussion #7671

The type constructor `Standard.Base.Data.Regression.Mode.Logarithmic` has `reexport` field set to `Standard.Base.Main` which is wrong. The `Standard.Base` only exports the `Standard.Base.Data.Regression` module and not its contents.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7674

Changelog:
- fix: setting reexport field when serializing the library

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

File: engine/runtime/src/test/java/org/enso/compiler/SerializationManagerTest.java [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+  @Test
+  public void serializeLibrarySuggestions()
+      throws ExecutionException, InterruptedException, TimeoutException {
+    SerializationManager serializationManager = new SerializationManager(ensoContext.getCompiler());
+    LibraryName standardBaseLibrary = new LibraryName("Standard", "Base");
+    Package<TruffleFile> standardBasePackage = getLibraryPackage(standardBaseLibrary);
+    ensoContext
+        .getPackageRepository()
+        .registerMainProjectPackage(standardBaseLibrary, standardBasePackage);
+    Object result = ensoContext.getCompiler().compile(false, false).get(20, TimeUnit.SECONDS);
```
Comment (hubertp) [inline engine/runtime/src/test/java/org/enso/compiler/SerializationManagerTest.java]: Let's have this as a constant somewhere. Easier to spot than deep within the test implementation.

**Review by hubertp — APPROVED** [review]
